import type { Question } from '../types';

export const graphTheoryQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8201,
    topic: 'graph-theory',
    difficulty: 'easy',
    question: "Euler's formula for connected planar graphs states $V - E + F = $?",
    options: ['$2$', '$0$', '$1$', '$-1$'],
    correctIndex: 0,
    explanation: "Euler's polyhedron formula $V - E + F = 2$ (vertices minus edges plus faces) is one of the most beautiful results in mathematics. It connects combinatorics to topology — the Euler characteristic $\\chi = 2$ for any convex polyhedron. This was one of the first topological invariants ever discovered.",
    realWorld: "Euler's formula is used to prove that there are exactly 5 Platonic solids and to verify mesh integrity in 3D modeling.",
    hint: 'For a cube: $V=8, E=12, F=6$ — check the formula.',
    symbolLinks: { 'V': 'upsilon', 'E': 'epsilon', 'F': 'phi' },
    glossaryLinks: ['euler-characteristic', 'planar-graph'],
    formulaLinks: ["Euler's Polyhedron Formula"],
  },
  {
    id: 8202,
    topic: 'graph-theory',
    difficulty: 'easy',
    question: 'A graph is bipartite if and only if it contains no cycle of which type?',
    options: ['Odd-length cycle', 'Even-length cycle', 'Hamiltonian cycle', 'Self-loop'],
    correctIndex: 0,
    explanation: 'A graph is bipartite (2-colorable) iff it has no odd cycles. This elegant characterization connects graph coloring to parity — you can BFS from any vertex, alternating colors, and an odd cycle forces a contradiction. König proved this in 1936.',
    realWorld: 'Bipartite matching is used in job assignment, organ donor matching, and recommendation systems.',
    hint: 'Try 2-coloring a triangle (odd cycle) — it fails.',
    glossaryLinks: ['bipartite-graph'],
  },
  {
    id: 8203,
    topic: 'graph-theory',
    difficulty: 'easy',
    question: 'In a tree with $n$ vertices, how many edges are there?',
    options: ['$n - 1$', '$n$', '$n + 1$', '$2n$'],
    correctIndex: 0,
    explanation: 'A tree is a connected acyclic graph, and it always has exactly $n-1$ edges. This is a foundational fact — adding any edge creates a cycle, removing any edge disconnects the graph. Trees are the minimal connected graphs and the maximal acyclic graphs.',
    realWorld: 'Spanning trees optimize network design — minimum wiring, maximum connectivity.',
    hint: 'Each new vertex added to build a tree contributes exactly one edge.',
    symbolLinks: { 'n': 'nu' },
    glossaryLinks: ['spanning-tree'],
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8204,
    topic: 'graph-theory',
    difficulty: 'hard',
    question: 'The chromatic polynomial $P(G, k)$ counts the number of proper $k$-colorings of graph $G$. For the complete graph $K_n$, what is $P(K_n, k)$?',
    options: [
      '$k(k-1)(k-2)\\cdots(k-n+1)$',
      '$k^n$',
      '$\\binom{k}{n}$',
      '$n! \\cdot k$',
    ],
    correctIndex: 0,
    explanation: 'For $K_n$, the first vertex gets $k$ colors, the second $k-1$, etc. — giving the falling factorial $k^{\\underline{n}}$. Chromatic polynomials were introduced by Birkhoff (1912) in an attempt to prove the four-color theorem. They encode deep combinatorial structure.',
    realWorld: 'Chromatic polynomials model scheduling conflicts — coloring a conflict graph assigns non-overlapping time slots.',
    hint: 'In a complete graph, every vertex is adjacent to every other — each needs a distinct color.',
    symbolLinks: { 'k': 'kappa', 'n': 'nu' },
    glossaryLinks: ['chromatic-polynomial'],
    formulaLinks: ['Chromatic Polynomial'],
  },
  {
    id: 8205,
    topic: 'graph-theory',
    difficulty: 'hard',
    question: "Ramsey's theorem guarantees that $R(3,3) = 6$. This means in any 2-coloring of edges of $K_6$:",
    options: [
      'There is a monochromatic triangle',
      'There are exactly 3 red and 3 blue edges',
      'The graph is bipartite',
      'Every vertex has the same color degree',
    ],
    correctIndex: 0,
    explanation: "$R(3,3) = 6$ means any 2-coloring of $K_6$'s edges contains a monochromatic triangle. The pigeonhole argument: pick a vertex $v$ — it has 5 edges, so $\\ge 3$ share a color (say red). Among those 3 neighbors, if any edge between them is red → red triangle. If none → blue triangle among those 3 vertices. Erdős said: 'If aliens demanded $R(5,5)$ or destruction, we should muster all computers. If they demanded $R(6,6)$, we should negotiate.'",
    realWorld: 'Ramsey theory finds unavoidable patterns in networks — used in distributed computing to prove impossibility results.',
    hint: 'Pigeonhole: 5 edges from one vertex, 2 colors → at least 3 same color.',
    symbolLinks: { 'R': 'rho', 'K': 'kappa' },
    glossaryLinks: ['ramsey-number'],
    formulaLinks: ["Ramsey's Theorem"],
  },
  {
    id: 8206,
    topic: 'graph-theory',
    difficulty: 'hard',
    question: 'The Tutte polynomial $T(G; x, y)$ generalizes the chromatic polynomial. At the evaluation $T(G; 1, 1)$, it counts:',
    options: ['The number of spanning trees', 'The number of colorings', 'The number of perfect matchings', 'The treewidth'],
    correctIndex: 0,
    explanation: "The Tutte polynomial is a universal graph invariant — it specializes to the chromatic polynomial, flow polynomial, reliability polynomial, and Jones polynomial (for knots!). At $(1,1)$ it counts spanning trees, connecting to Kirchhoff's matrix-tree theorem. It is #P-hard to compute in general.",
    realWorld: 'Spanning tree enumeration via Tutte polynomials is used in network reliability analysis.',
    hint: 'Spanning trees are the $(1,1)$ evaluation — the simplest specialization.',
    symbolLinks: { 'T': 'tau', 'G': 'gamma' },
    formulaLinks: ['Tutte Polynomial'],
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8207,
    topic: 'graph-theory',
    difficulty: 'sota',
    question: 'The Szemerédi regularity lemma partitions any large graph into a bounded number of parts such that most pairs behave:',
    options: ['Pseudorandomly (ε-regular)', 'As complete bipartite graphs', 'As independent sets', 'As expanders'],
    correctIndex: 0,
    explanation: "Szemerédi's regularity lemma (1978) is one of the most powerful tools in combinatorics. It says any graph can be approximated by a bounded-complexity structure where most pairs of parts have edge density behaving pseudorandomly ($\\varepsilon$-regularly). The tower-type bounds are necessary (Gowers 1997). It underpins proofs of Szemerédi's theorem on arithmetic progressions.",
    realWorld: 'Graph regularity methods inspire graph neural network architectures that exploit structural regularity.',
    hint: 'The lemma guarantees a structured approximation — "pseudo-random" pair behavior.',
    symbolLinks: { '\\varepsilon': 'epsilon' },
    glossaryLinks: ['regularity-lemma'],
  },
  {
    id: 8208,
    topic: 'graph-theory',
    difficulty: 'sota',
    question: 'The Robertson-Seymour theorem (graph minor theorem) states that the set of finite graphs under the minor relation is:',
    options: ['A well-quasi-order (no infinite antichains)', 'A total order', 'A lattice', 'Not well-founded'],
    correctIndex: 0,
    explanation: 'The Robertson-Seymour theorem (proved over 20 papers, 1983–2004) is one of the deepest results in combinatorics. It implies that every minor-closed graph property (planarity, bounded treewidth, etc.) is characterized by a finite set of forbidden minors. The proof is highly non-constructive — for many properties, the forbidden minors are unknown.',
    realWorld: 'The theory gives polynomial-time algorithms for many graph problems restricted to bounded treewidth.',
    hint: 'No infinite antichain — every minor-closed family has finitely many obstructions.',
    glossaryLinks: ['graph-minor'],
  },
  {
    id: 8209,
    topic: 'graph-theory',
    difficulty: 'sota',
    question: 'The Unique Games Conjecture (Khot, 2002), if true, implies the optimal hardness of approximation for which classic problem?',
    options: ['MAX-CUT (Goemans-Williamson ratio is optimal)', 'Graph coloring', 'Hamiltonian path', 'Maximum clique'],
    correctIndex: 0,
    explanation: "Khot's UGC would prove that the Goemans-Williamson SDP algorithm achieves the best possible approximation ratio ($\\approx 0.878$) for MAX-CUT, assuming P ≠ NP. This would establish a remarkable tight connection between semidefinite programming and computational complexity. The conjecture remains one of the central open problems in theoretical CS.",
    realWorld: 'MAX-CUT algorithms are used in VLSI circuit design and statistical physics (Ising model ground states).',
    hint: 'Goemans-Williamson (1995) gave 0.878... — UGC says you can\'t beat it.',
    symbolLinks: { 'P': 'pi' },
    glossaryLinks: ['unique-games-conjecture'],
    formulaLinks: ['Goemans-Williamson Relaxation'],
  },
];
