import type { Question } from '../types';

export const aerospaceQuestions: Question[] = [
  {
    id: 40901, topic: 'aerospace', difficulty: 'easy',
    question: 'The Tsiolkovsky rocket equation $\\Delta v = v_e \\ln(m_0/m_f)$ shows that:',
    options: [
      'A rocket\'s velocity change depends logarithmically on its mass ratio — you need exponentially more fuel for linearly more speed',
      'Rockets accelerate at a constant rate regardless of fuel',
      'Heavier rockets are always faster',
      'Fuel mass doesn\'t affect rocket performance',
    ],
    correctIndex: 0,
    explanation: 'The tyranny of the rocket equation: to double Δv, you need to square the mass ratio. This is why multi-stage rockets exist — each stage sheds dead weight.',
    realWorld: 'SpaceX\'s Falcon 9 is 96% fuel by mass at launch. The Saturn V was 85% fuel. Reusable first stages save the most expensive hardware.',
    hint: 'The logarithm means diminishing returns — each extra km/s costs exponentially more fuel.',
  },
  {
    id: 40904, topic: 'aerospace', difficulty: 'easy',
    question: 'Lift on an airplane wing is generated primarily by:',
    options: [
      'The wing\'s angle of attack deflecting air downward — Newton\'s third law means the air pushes the wing up, with pressure differences described by Bernoulli\'s equation',
      'Vacuum above the wing pulling it upward',
      'Hot air rising under the wing',
      'Magnetic interaction with Earth\'s field',
    ],
    correctIndex: 0,
    explanation: 'Lift involves both Bernoulli (lower pressure above curved wing) and Newtonian (redirecting airflow downward) explanations — they\'re complementary, not competing. The angle of attack is the dominant factor at practical flight conditions.',
    realWorld: 'Understanding lift enabled the Wright brothers\' flight (1903), and modern computational fluid dynamics (CFD) optimizes wing shapes. Boeing 787 wings flex 8 meters in flight — designed by CFD simulations.',
    hint: 'Push air down → air pushes wing up. The shape and angle both matter.',
  },
  {
    id: 40902, topic: 'aerospace', difficulty: 'hard',
    question: 'Orbital mechanics requires understanding that objects in orbit are:',
    options: [
      'Continuously falling toward Earth but moving fast enough sideways that they keep missing it — free-fall at orbital velocity creates apparent weightlessness',
      'Floating because there is no gravity in space',
      'Held up by atmospheric pressure',
      'Pushed outward by centrifugal force that cancels gravity',
    ],
    correctIndex: 0,
    explanation: 'At ISS altitude (~400 km), gravity is still ~90% of surface gravity. Astronauts feel weightless because they\'re in free-fall. Orbital velocity (~7.8 km/s at LEO) ensures the curved trajectory matches Earth\'s curvature.',
    realWorld: 'Understanding orbits enables GPS (needs orbital mechanics + relativistic corrections), Starlink (5,000+ satellites), and interplanetary missions using gravitational slingshots.',
    hint: 'Newton\'s cannonball: fire fast enough and you fall around the Earth.',
  },
  {
    id: 40905, topic: 'aerospace', difficulty: 'hard',
    question: 'Hohmann transfer orbits are the most fuel-efficient way to move between orbits because:',
    options: [
      'They use exactly two engine burns (tangential to both orbits) connected by an elliptical path — any other transfer uses more Δv for the same orbit change',
      'They use continuous low thrust throughout the transfer',
      'They follow a straight line between two orbits',
      'They require only one engine burn',
    ],
    correctIndex: 0,
    explanation: 'A Hohmann transfer uses an ellipse tangent to both the starting and target orbits. Burn 1 (at periapsis) enters the transfer ellipse; burn 2 (at apoapsis) circularizes at the target. Total Δv is minimized for coplanar circular orbit transfers.',
    realWorld: 'Mars missions use (near-)Hohmann transfers: ~9 months transit time. The 2020 Mars window saw launches from NASA (Perseverance), China (Tianwen-1), and UAE (Hope) — all using similar transfer orbits.',
    hint: 'Two precise burns connected by an ellipse — the most economical orbital highway.',
  },
  {
    id: 40903, topic: 'aerospace', difficulty: 'sota',
    question: 'SpaceX\'s Starship full-stack reusability changes space economics because:',
    options: [
      'Reducing launch cost from ~$10,000/kg (expendable) to potentially ~$100/kg (fully reusable) enables economically viable Mars colonization and space manufacturing',
      'It is the first rocket ever built',
      'It uses nuclear propulsion',
      'It eliminates the need for the rocket equation',
    ],
    correctIndex: 0,
    explanation: 'Starship\'s 150-ton payload to LEO with full reusability could reduce costs 100×. The key innovation: catching the booster with the launch tower eliminates landing legs and maximizes payload.',
    realWorld: 'At $100/kg, a human mission to Mars costs ~$10M in launch costs (vs. ~$1B today). This also enables orbital manufacturing, space solar power, and asteroid mining.',
    hint: 'If you could reuse an airplane only once, flights would cost $100,000. Reusability changes everything.',
  },
  {
    id: 40906, topic: 'aerospace', difficulty: 'sota',
    question: 'Ion propulsion (Hall thrusters, used on Starlink satellites) works by:',
    options: [
      'Ionizing propellant (xenon) and accelerating ions to 30-50 km/s using electric fields — 10× higher exhaust velocity than chemical rockets, but with millinewton thrust levels',
      'Burning rocket fuel in a vacuum',
      'Using nuclear fission to heat propellant',
      'Ejecting solid particles at high speed',
    ],
    correctIndex: 0,
    explanation: 'Ion engines have specific impulse (Isp) of 1,500-5,000s vs. ~450s for chemical rockets. The rocket equation shows higher Isp means exponentially less propellant needed. The trade-off: tiny thrust (mN) requires weeks of continuous firing.',
    realWorld: 'Each Starlink satellite uses krypton Hall thrusters for orbit raising and maintenance. NASA\'s Dawn mission used ion propulsion to orbit both Vesta and Ceres — impossible with chemical propulsion.',
    hint: 'Tiny push, but incredibly efficient — like a gentle breeze that never stops blowing.',
  },
];
