import type { Question } from '../types';

export const aerospaceQuestions: Question[] = [
  {
    id: 40901, topic: "spaceflight-systems", difficulty: "easy",
    question: "Rocket specific impulse is a measure of:",
    options: ["Propellant efficiency","Vehicle dry mass","Orbital period","Payload volume"],
    correctIndex: 0,
    explanation: "Specific impulse relates thrust to propellant weight flow and is commonly reported in seconds; higher values correspond to greater effective exhaust velocity.",
    realWorld: "It is useful for comparing propulsion efficiency independently of vehicle size.",
    hint: "It describes how effectively propellant produces impulse.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40904, topic: 'aerodynamics', difficulty: 'easy',
    question: 'Below stall, increasing an airfoil\'s angle of attack generally increases lift because it:',
    options: ['Eliminates pressure differences around the wing', 'Removes the need to deflect airflow', 'Strengthens the aerodynamic circulation and pressure loading that turn airflow downward', 'Makes gravity weaker'],
    correctIndex: 2,
    explanation: 'For a given airfoil and Reynolds/Mach regime below stall, increasing angle of attack generally increases lift coefficient by changing the pressure distribution and the downward momentum imparted to the flow.',
    realWorld: 'Pilots and flight-control systems manage angle of attack because lift rises only up to the point where flow separation causes stall.',
    hint: 'Before stall, angle of attack changes both pressure loading and the direction of the wake.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40902, topic: 'orbital-mechanics', difficulty: 'easy',
    question: 'Orbital mechanics requires understanding that objects in orbit are:',
    options: ['Held up by atmospheric pressure', 'Floating because there is no gravity in space', 'Continuously falling toward Earth but moving fast enough sideways that they keep missing it — free-fall at orbital velocity creates apparent weightlessness', 'Pushed outward by centrifugal force that cancels gravity'],
    correctIndex: 2,
    explanation: 'At ISS altitude (~400 km), gravity is still ~90% of surface gravity. Astronauts feel weightless because they\'re in free-fall. Orbital velocity (~7.8 km/s at LEO) ensures the curved trajectory matches Earth\'s curvature.',
    realWorld: 'Understanding orbits enables GPS (needs orbital mechanics + relativistic corrections), Starlink (5,000+ satellites), and interplanetary missions using gravitational slingshots.',
    hint: 'Newton\'s cannonball: fire fast enough and you fall around the Earth.',
  },
  {
    id: 40905, topic: 'orbital-mechanics', difficulty: 'hard',
    question: 'For two coplanar circular orbits with a moderate radius ratio, a Hohmann transfer is notable because it:',
    options: ['Uses continuous thrust throughout the coast arc', 'Uses two tangential impulses and is minimum-delta-v among the standard two-impulse transfers for that case', 'Requires no coast time', 'Always beats every possible multi-impulse transfer for any radius ratio'],
    correctIndex: 1,
    explanation: 'The Hohmann transfer uses an ellipse tangent to both circular orbits and two impulsive burns. It is the classic minimum-delta-v two-impulse solution for common circular-orbit transfers, but it is not universally optimal against every multi-impulse strategy at extreme radius ratios.',
    realWorld: 'Mission designers trade delta-v, time of flight, plane changes, launch windows, and propulsion constraints rather than assuming one transfer is optimal in every case.',
    hint: 'The key qualifier is two impulses between coplanar circular orbits.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40903, topic: "spaceflight-systems", difficulty: "sota",
    question: "Nuclear thermal propulsion differs from a chemical rocket because it heats propellant using:",
    options: ["A fission reactor","Solar cells only","Atmospheric combustion","Battery resistors"],
    correctIndex: 0,
    explanation: "Nuclear thermal propulsion uses reactor heat to raise a propellant's temperature before expansion through a nozzle, enabling high thrust with higher propellant efficiency than conventional chemical systems.",
    realWorld: "NASA continues technology work on nuclear thermal and nuclear electric propulsion for future deep-space missions.",
    hint: "The heat source is nuclear fission rather than chemical combustion.",
    sources: [{"title":"Space Nuclear Propulsion","url":"https://www.nasa.gov/space-technology-mission-directorate/tdm/space-nuclear-propulsion/","publisher":"NASA","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 40906, topic: "spaceflight-systems", difficulty: "hard",
    question: "Hall-effect propulsion produces thrust by:",
    options: ["Burning propellant with atmospheric oxygen","Expanding steam through a turbine","Electrically accelerating ionized propellant","Using solar radiation pressure only"],
    correctIndex: 2,
    explanation: "Hall thrusters ionize a propellant and use electric and magnetic fields to accelerate ions to high exhaust velocity, trading low thrust for high propellant efficiency.",
    realWorld: "Electric propulsion is well suited to long-duration orbital transfer and station-keeping where thrust can be applied for extended periods.",
    hint: "The energy source is electrical; the expelled reaction mass is ionized propellant.",
    reviewedAt: "2026-09-19",
  },

  // ── Spaceflight Systems foundation wave 3 ─────────────────────────────
  {
    id: 41950, topic: "spaceflight-systems", difficulty: "easy",
    question: "The rocket equation shows that achievable delta-v depends logarithmically on:",
    options: ["Engine chamber pressure only","Initial-to-final mass ratio","Launch-site latitude only","Payload volume"],
    correctIndex: 1,
    explanation: "The Tsiolkovsky rocket equation gives delta-v as effective exhaust velocity times the logarithm of initial mass divided by final mass.",
    realWorld: "This logarithmic dependence is why propellant fraction and staging dominate launch-vehicle architecture.",
    hint: "The key ratio compares mass before and after propellant is expended.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41951, topic: "spaceflight-systems", difficulty: "easy",
    question: "Staging improves launch-vehicle performance mainly because it:",
    options: ["Raises Earth's escape velocity","Discards inert mass during flight","Removes aerodynamic drag entirely","Eliminates gravity losses"],
    correctIndex: 1,
    explanation: "Dropping empty tanks and engines reduces inert mass that later stages must accelerate, improving the effective mass ratio for remaining burns.",
    realWorld: "Multistage launch vehicles exploit this mass-management benefit even when every stage obeys the same rocket equation.",
    hint: "Empty hardware no longer needs to be accelerated.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41952, topic: "spaceflight-systems", difficulty: "hard",
    question: "A thermal-protection system on a reentry vehicle is designed mainly for:",
    options: ["Radio-bandwidth control","Orbital navigation timing","Thermal protection","Propellant pressurization"],
    correctIndex: 2,
    explanation: "Atmospheric entry converts kinetic energy into intense aerodynamic heating, so thermal-protection materials and structures must limit temperatures and heat flux reaching the vehicle.",
    realWorld: "Reusable systems add requirements for durability, inspectability, and repeatable performance.",
    hint: "The system manages heat, not propulsion or communications.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41953, topic: "spaceflight-systems", difficulty: "hard",
    question: "An ullage-settling maneuver before an engine restart is used for:",
    options: ["Propellant settling","Solar-array pointing","Antenna beam steering","Nozzle-area control"],
    correctIndex: 0,
    explanation: "In low gravity, liquid propellant can float or slosh away from feed outlets; a small acceleration can settle liquid so pumps or feed systems ingest propellant rather than gas.",
    realWorld: "Propellant-management devices and settling strategies are important for reliable in-space restarts.",
    hint: "The goal is to control where liquid sits inside the tank.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41954, topic: "spaceflight-systems", difficulty: "sota",
    question: "NASA's AEPS program is developing a 12-kW-class propulsion system based on:",
    options: ["Solid rocket motors","Cold-gas thrusters","Chemical monopropellant","Hall thrusters"],
    correctIndex: 3,
    explanation: "The Advanced Electric Propulsion System uses a 12-kW-class Hall thruster intended for high-power solar-electric propulsion applications associated with Gateway's Power and Propulsion Element.",
    realWorld: "The program illustrates how electric propulsion scales toward higher power for large spacecraft orbital transfer and maneuvering.",
    hint: "AEPS is an electric, magnetically accelerated ion propulsion system.",
    paper: {"title":"12-kW Advanced Electric Propulsion System Hall Current Thruster Qualification and Production Status","url":"https://ntrs.nasa.gov/citations/20250003901","venue":"Journal of Electric Propulsion","year":2025},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 41955, topic: "spaceflight-systems", difficulty: "sota",
    question: "NASA's LOXSAT demonstration targets in-space engineering challenges including:",
    options: ["Wing icing controls","Deep-ocean buoyancy","Ground fueling only","Cryogenic fluid control"],
    correctIndex: 3,
    explanation: "LOXSAT is intended to demonstrate multiple cryogenic-fluid-management technologies relevant to storing, measuring, controlling, and transferring very cold propellants in microgravity.",
    realWorld: "Cryogenic fluid management is a prerequisite for architectures that depend on long-duration storage or orbital refueling rather than immediate propellant use.",
    hint: "The challenge is keeping and moving cryogenic liquid reliably in microgravity.",
    sources: [{"title":"NASA, Industry Prepare Cryogenic Fuel Technology Demo","url":"https://www.nasa.gov/directorates/stmd/tech-demo-missions-program/cryogenic-fluid-management-cfm/nasa-industry-prepare-cryogenic-fuel-technology-demo/","publisher":"NASA","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },

  // ── Aerodynamics foundation wave 6 ──────────────────────────────
  {
    id: 80644, topic: 'aerodynamics', difficulty: 'hard',
    question: 'The critical Mach number of an aircraft is the freestream Mach number at which:',
    options: ['The entire aircraft becomes supersonic', 'Wave drag becomes exactly zero', 'The boundary layer becomes inviscid', 'Sonic flow first appears somewhere locally on the aircraft'],
    correctIndex: 3,
    explanation: 'Local flow can accelerate over an airfoil faster than the freestream. The critical Mach number marks the freestream condition at which the first local point reaches Mach 1.',
    realWorld: 'Critical Mach number helps define the onset of transonic effects such as local shocks, drag rise, and changes in control behavior.',
    hint: 'The freestream can still be subsonic when one local region first reaches Mach 1.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 80645, topic: 'aerodynamics', difficulty: 'sota',
    question: 'NASA\'s X-59 reduces the loudness of its ground-level sonic signature primarily by:',
    options: ['Shaping the aircraft so its individual shock waves are managed to avoid merging into a conventional strong sonic boom', 'Flying below Mach 1 during all community tests', 'Using active noise-canceling loudspeakers outside the aircraft', 'Eliminating shock waves entirely in supersonic flight'],
    correctIndex: 0,
    explanation: 'Supersonic aircraft still create shock waves, but the X-59 outer mold line is designed to control how those pressure disturbances form and propagate so they do not coalesce into the classic strong N-wave boom at the ground.',
    realWorld: 'In 2026 NASA flew the X-59 at its Mach 1.4, 55,000-foot mission condition as it progressed toward acoustic validation and community-response testing.',
    hint: 'The design changes how shocks combine; it does not abolish supersonic shocks.',
    sources: [{ title: 'NASA X-59 Explainer: Science of Sonic Booms', url: 'https://www.nasa.gov/blogs/quesst/2026/08/10/nasa-x-59-explainer-science-of-sonic-booms/', publisher: 'NASA', year: 2026 }],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 80646, topic: 'aerodynamics', difficulty: 'sota',
    question: 'During 2026 X-59 flight testing, NASA described a real-time digital twin as a tool that:',
    options: ['Compares live flight data with simulated predictions to help evaluate aircraft behavior', 'Replaces all physical sensors with a purely virtual aircraft', 'Guarantees CFD has zero modeling error', 'Commands the aircraft without using measured flight data'],
    correctIndex: 0,
    explanation: 'A digital twin links measured behavior with a computational representation. Comparing flight telemetry with predicted response helps engineers validate models and identify deviations as the test envelope expands.',
    realWorld: 'NASA reported using a real-time digital twin while X-59 flight testing validated years of aerodynamic modeling and wind-tunnel predictions.',
    hint: 'It is a measured-versus-modeled comparison loop.',
    sources: [{ title: 'NASA’s X-59 Aircraft Builds Momentum Through 25th Flight', url: 'https://www.nasa.gov/blogs/quesst/2026/09/04/nasas-x-59-aircraft-builds-momentum-through-25th-flight/', publisher: 'NASA', year: 2026 }],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },

  // ── Orbital Mechanics foundation wave 6 ────────────────────────
  {
    id: 80647, topic: 'orbital-mechanics', difficulty: 'easy',
    question: 'For circular orbits around the same central body, Kepler\'s third-law scaling implies that orbital period $T$ grows with orbital radius $r$ approximately as:',
    options: ['$T \\propto r^{-1}$', '$T \\propto r$', '$T \\propto r^2$', '$T \\propto r^{3/2}$'],
    correctIndex: 3,
    explanation: 'For a circular orbit, $T = 2\\pi\\sqrt{r^3/\\mu}$, so period scales as $r^{3/2}$ when the central body and its gravitational parameter are fixed.',
    realWorld: 'Higher circular orbits move more slowly and take longer to complete each revolution than lower circular orbits around the same body.',
    hint: 'Square the period and compare it with the cube of orbital radius.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 80648, topic: 'orbital-mechanics', difficulty: 'sota',
    question: 'A near-rectilinear halo orbit (NRHO) is attractive for lunar Gateway operations because it combines:',
    options: ['A highly elongated cislunar orbit with favorable South Pole access, Earth visibility, and relatively modest station-keeping needs', 'A perfectly circular low-lunar orbit with continuous atmospheric drag', 'A geostationary orbit centered on Earth', 'A ballistic trajectory that never requires navigation'],
    correctIndex: 0,
    explanation: 'An NRHO is a three-body-family orbit shaped by Earth-Moon dynamics. Its geometry provides repeated close approaches to the Moon, broad lunar access, Earth visibility, and operational benefits for a long-lived cislunar platform.',
    realWorld: 'NASA\'s CAPSTONE mission characterized an NRHO and reduced risk for future Artemis/Gateway operations before its NASA mission activities concluded in June 2026.',
    hint: 'Think three-body cislunar dynamics rather than an ordinary circular lunar orbit.',
    sources: [{ title: 'CAPSTONE', url: 'https://www.nasa.gov/mission/capstone/', publisher: 'NASA', year: 2026 }],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 80649, topic: 'orbital-mechanics', difficulty: 'sota',
    question: 'CAPSTONE\'s Cislunar Autonomous Positioning System (CAPS) demonstrated an important navigation concept by:',
    options: ['Using spacecraft-to-spacecraft measurements with Lunar Reconnaissance Orbiter to support autonomous cislunar navigation', 'Relying only on atmospheric GPS signals at the Moon', 'Determining position from aerodynamic lift', 'Avoiding all radio measurements'],
    correctIndex: 0,
    explanation: 'CAPS demonstrated peer-to-peer ranging and navigation concepts using communication with NASA\'s Lunar Reconnaissance Orbiter, showing how spacecraft can supplement Earth-based tracking in cislunar space.',
    realWorld: 'NASA cites CAPSTONE\'s navigation and networking demonstrations as risk reduction for future lunar exploration operations.',
    hint: 'The demonstration used another spacecraft as part of the navigation solution.',
    sources: [{ title: 'What is CAPSTONE?', url: 'https://www.nasa.gov/smallspacecraft/capstone/', publisher: 'NASA', year: 2026 }],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
];
