import type { Question } from '../types';

export const aerospaceQuestions: Question[] = [
  {
    id: 40901, topic: "spaceflight-systems", difficulty: "easy",
    question: "Rocket specific impulse is a measure of:",
    options: ["Propellant efficiency","Vehicle dry mass","Orbital period","Payload volume"],
    correctIndex: 0,
    explanation: "Specific impulse relates thrust to propellant weight flow and is commonly reported in seconds; higher values correspond to greater effective exhaust velocity.",
    realWorld: "It is useful for comparing propulsion efficiency independently of vehicle size.",
    hint: "It describes how effectively propellant produces impulse.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40904, topic: 'aerodynamics', difficulty: 'easy',
    question: 'An aerodynamic stall occurs primarily when:',
    options: ['The aircraft reaches exactly Mach 1', 'The wing produces no pressure difference at any angle', 'Angle of attack exceeds the range where attached flow can be maintained, causing major separation and lift loss', 'The wingtip vortices disappear completely'],
    correctIndex: 2,
    explanation: 'Stall is fundamentally an angle-of-attack and flow-separation phenomenon. Beyond the critical angle of attack, large regions of separated flow reduce the wing\'s ability to increase lift normally.',
    realWorld: 'Pilots manage angle of attack and airspeed together because the same wing can stall at different indicated speeds depending on load factor, weight, and maneuvering condition.',
    hint: 'The key variable is the wing\'s angle relative to the incoming airflow.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40902, topic: 'orbital-mechanics', difficulty: 'easy',
    question: 'Orbital mechanics requires understanding that objects in orbit are:',
    options: [
      'Continuously falling toward Earth but moving fast enough sideways that they keep missing it — free-fall at orbital velocity creates apparent weightlessness',
      'Floating because there is no gravity in space',
      'Held up by atmospheric pressure',
      'Pushed outward by centrifugal force that cancels gravity',
    ],
    correctIndex: 0,
    explanation: 'At ISS altitude (~400 km), gravity is still ~90% of surface gravity. Astronauts feel weightless because they\'re in free-fall. Orbital velocity (~7.8 km/s at LEO) ensures the curved trajectory matches Earth\'s curvature.',
    realWorld: 'Understanding orbits enables GPS (needs orbital mechanics + relativistic corrections), Starlink (5,000+ satellites), and interplanetary missions using gravitational slingshots.',
    hint: 'Newton\'s cannonball: fire fast enough and you fall around the Earth.',
  },
  {
    id: 40905, topic: 'orbital-mechanics', difficulty: 'hard',
    question: 'For an impulsive orbital plane change of angle $\\Delta i$ performed at speed $v$, why is the maneuver often cheaper near apoapsis?',
    options: ['Gravity is zero at apoapsis', 'The spacecraft mass becomes smaller at apoapsis without burning propellant', 'Orbital inclination can change without any velocity change there', 'The required plane-change $\\Delta v=2v\\sin(\\Delta i/2)$ is smaller when orbital speed is lower'],
    correctIndex: 3,
    explanation: 'A pure impulsive plane change rotates the velocity vector. For a fixed angular change, the required $\\Delta v$ scales with the current speed, so performing the maneuver where the spacecraft is moving more slowly can reduce propellant cost.',
    realWorld: 'Mission designers often combine plane changes with other burns or place them near high-altitude portions of an orbit where velocity is lower.',
    hint: 'The same velocity-vector rotation costs less when the vector is shorter.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40903, topic: "spaceflight-systems", difficulty: "sota",
    question: "Nuclear thermal propulsion differs from a chemical rocket because it heats propellant using:",
    options: ["A fission reactor","Solar cells only","Atmospheric combustion","Battery resistors"],
    correctIndex: 0,
    explanation: "Nuclear thermal propulsion uses reactor heat to raise a propellant's temperature before expansion through a nozzle, enabling high thrust with higher propellant efficiency than conventional chemical systems.",
    realWorld: "NASA continues technology work on nuclear thermal and nuclear electric propulsion for future deep-space missions.",
    hint: "The heat source is nuclear fission rather than chemical combustion.",
    sources: [{"title":"Space Nuclear Propulsion","url":"https://www.nasa.gov/space-technology-mission-directorate/tdm/space-nuclear-propulsion/","publisher":"NASA","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 40906, topic: "spaceflight-systems", difficulty: "hard",
    question: "Hall-effect propulsion produces thrust by:",
    options: ["Burning propellant with atmospheric oxygen","Expanding steam through a turbine","Electrically accelerating ionized propellant","Using solar radiation pressure only"],
    correctIndex: 2,
    explanation: "Hall thrusters ionize a propellant and use electric and magnetic fields to accelerate ions to high exhaust velocity, trading low thrust for high propellant efficiency.",
    realWorld: "Electric propulsion is well suited to long-duration orbital transfer and station-keeping where thrust can be applied for extended periods.",
    hint: "The energy source is electrical; the expelled reaction mass is ionized propellant.",
    reviewedAt: "2026-09-19",
  },

  // ── Spaceflight Systems foundation wave 3 ─────────────────────────────
  {
    id: 41950, topic: "spaceflight-systems", difficulty: "easy",
    question: "The rocket equation shows that achievable delta-v depends logarithmically on:",
    options: ["Engine chamber pressure only","Initial-to-final mass ratio","Launch-site latitude only","Payload volume"],
    correctIndex: 1,
    explanation: "The Tsiolkovsky rocket equation gives delta-v as effective exhaust velocity times the logarithm of initial mass divided by final mass.",
    realWorld: "This logarithmic dependence is why propellant fraction and staging dominate launch-vehicle architecture.",
    hint: "The key ratio compares mass before and after propellant is expended.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41951, topic: "spaceflight-systems", difficulty: "easy",
    question: "Staging improves launch-vehicle performance mainly because it:",
    options: ["Raises Earth's escape velocity","Discards inert mass during flight","Removes aerodynamic drag entirely","Eliminates gravity losses"],
    correctIndex: 1,
    explanation: "Dropping empty tanks and engines reduces inert mass that later stages must accelerate, improving the effective mass ratio for remaining burns.",
    realWorld: "Multistage launch vehicles exploit this mass-management benefit even when every stage obeys the same rocket equation.",
    hint: "Empty hardware no longer needs to be accelerated.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41952, topic: "spaceflight-systems", difficulty: "hard",
    question: "A thermal-protection system on a reentry vehicle is designed mainly for:",
    options: ["Radio-bandwidth control","Orbital navigation timing","Thermal protection","Propellant pressurization"],
    correctIndex: 2,
    explanation: "Atmospheric entry converts kinetic energy into intense aerodynamic heating, so thermal-protection materials and structures must limit temperatures and heat flux reaching the vehicle.",
    realWorld: "Reusable systems add requirements for durability, inspectability, and repeatable performance.",
    hint: "The system manages heat, not propulsion or communications.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41953, topic: "spaceflight-systems", difficulty: "hard",
    question: "An ullage-settling maneuver before an engine restart is used for:",
    options: ["Propellant settling","Solar-array pointing","Antenna beam steering","Nozzle-area control"],
    correctIndex: 0,
    explanation: "In low gravity, liquid propellant can float or slosh away from feed outlets; a small acceleration can settle liquid so pumps or feed systems ingest propellant rather than gas.",
    realWorld: "Propellant-management devices and settling strategies are important for reliable in-space restarts.",
    hint: "The goal is to control where liquid sits inside the tank.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41954, topic: "spaceflight-systems", difficulty: "sota",
    question: "NASA's AEPS program is developing a 12-kW-class propulsion system based on:",
    options: ["Solid rocket motors","Cold-gas thrusters","Chemical monopropellant","Hall thrusters"],
    correctIndex: 3,
    explanation: "The Advanced Electric Propulsion System uses a 12-kW-class Hall thruster intended for high-power solar-electric propulsion applications associated with Gateway's Power and Propulsion Element.",
    realWorld: "The program illustrates how electric propulsion scales toward higher power for large spacecraft orbital transfer and maneuvering.",
    hint: "AEPS is an electric, magnetically accelerated ion propulsion system.",
    paper: {"title":"12-kW Advanced Electric Propulsion System Hall Current Thruster Qualification and Production Status","url":"https://ntrs.nasa.gov/citations/20250003901","venue":"Journal of Electric Propulsion","year":2025},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 41955, topic: "spaceflight-systems", difficulty: "sota",
    question: "NASA's LOXSAT demonstration targets in-space engineering challenges including:",
    options: ["Wing icing controls","Deep-ocean buoyancy","Ground fueling only","Cryogenic fluid control"],
    correctIndex: 3,
    explanation: "LOXSAT is intended to demonstrate multiple cryogenic-fluid-management technologies relevant to storing, measuring, controlling, and transferring very cold propellants in microgravity.",
    realWorld: "Cryogenic fluid management is a prerequisite for architectures that depend on long-duration storage or orbital refueling rather than immediate propellant use.",
    hint: "The challenge is keeping and moving cryogenic liquid reliably in microgravity.",
    sources: [{"title":"NASA, Industry Prepare Cryogenic Fuel Technology Demo","url":"https://www.nasa.gov/directorates/stmd/tech-demo-missions-program/cryogenic-fluid-management-cfm/nasa-industry-prepare-cryogenic-fuel-technology-demo/","publisher":"NASA","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
];
