import type { Question } from '../types';

export const cs50Questions: Question[] = [
  {
    id: 95000,
    topic: 'cs50',
    difficulty: 'easy',
    question: 'CS50 Week 1 (C): `int height = get_int("Height: ");` reads user input as?',
    options: ['Integer', 'String', 'Float', 'Character array'],
    correctIndex: 0,
    explanation: 'CS50\'s `get_int()` is a wrapper that validates integer input from stdin, reprompting on invalid input.',
    realWorld: 'Used in the Mario pyramid pset — robust input handling is essential for user-facing applications.',
    hint: 'CS50 provides typed input helpers for each C primitive.',
    symbolLinks: {},
    formulaLinks: ['big-o'],
    glossaryLinks: ['type-system'],
  },
  {
    id: 95001,
    topic: 'cs50',
    difficulty: 'hard',
    question: 'Week 3 Algorithms: Binary search on a sorted array runs in what time complexity?',
    options: ['$O(\\log n)$', '$O(n)$', '$O(n \\log n)$', '$O(n^2)$'],
    correctIndex: 0,
    explanation: 'Binary search halves the search space each step: $\\log_2 n$ comparisons in the worst case.',
    realWorld: 'Git bisect, TCP congestion window, B-tree database indexes all use binary search.',
    hint: 'Halving the problem on each iteration.',
    symbolLinks: { 'O': 'omicron', 'n': 'nu' },
    formulaLinks: ['binary-search', 'big-o'],
    glossaryLinks: ['big-o', 'algorithm'],
  },
  {
    id: 95002,
    topic: 'cs50',
    difficulty: 'hard',
    question: 'Week 4 Memory: `char *s = "HI!"; s[0] = \'M\';` causes?',
    options: ['Segmentation fault', 'Compiles and prints "MI!"', 'Modifies the string literal in place', 'Compiler warning only'],
    correctIndex: 0,
    explanation: 'String literals reside in a read-only memory segment. Attempting to modify one triggers a segfault at runtime.',
    realWorld: 'Classic buffer overflow vulnerability vector in C — understanding memory layout is critical for security.',
    hint: 'String literals are immutable in C.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['pointer', 'memory-management'],
  },
  {
    id: 95003,
    topic: 'cs50',
    difficulty: 'sota',
    question: 'Week 5 Data Structures: Hash table average lookup is $O(1)$ assuming?',
    options: ['Uniform hashing + load factor $\\alpha < 1$', 'Keys are sorted', 'Linked list chaining only', 'Perfect hash function'],
    correctIndex: 0,
    explanation: 'With a good hash function and dynamic resizing (keeping $\\alpha$ bounded), expected chain length is constant.',
    realWorld: 'Python dicts, Redis, JavaScript objects — virtually every language relies on hash tables.',
    hint: 'Amortized analysis over the load factor.',
    symbolLinks: { 'α': 'alpha', 'O': 'omicron' },
    formulaLinks: ['hash-collision'],
    glossaryLinks: ['hash-table', 'amortized-analysis'],
  },
  {
    id: 95004,
    topic: 'cs50',
    difficulty: 'hard',
    question: 'Week 7 SQL: `SELECT * FROM users WHERE username = ?` (parameterized query) prevents?',
    options: ['SQL injection attacks', 'Deadlocks', 'Index scans', 'Transaction rollback'],
    correctIndex: 0,
    explanation: 'Parameterized queries separate code from data, escaping user input so injected SQL cannot execute.',
    realWorld: 'OWASP Top 10 #1: injection. Every production app must use parameterized queries.',
    hint: 'Never concatenate user strings into SQL.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['sql', 'cybersecurity'],
  },
  {
    id: 95005,
    topic: 'cs50',
    difficulty: 'hard',
    question: 'Week 8 Web: Flask `render_template("index.html")` serves?',
    options: ['Dynamic HTML from Jinja2 templates', 'A static file unchanged', 'A JSON API response', 'Server-Sent Events'],
    correctIndex: 0,
    explanation: 'Flask + Jinja2 renders Python data into HTML templates server-side before sending to the client.',
    realWorld: 'Finance dashboards, admin panels — server-side rendering remains critical for SEO and initial load.',
    hint: 'Server-side rendering with template variables.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['web-development'],
  },
  {
    id: 95006,
    topic: 'cs50',
    difficulty: 'easy',
    question: 'CS50 emphasizes which skill above language syntax?',
    options: ['Algorithmic thinking and problem decomposition', 'Memorizing language keywords', 'IDE shortcuts and tooling', 'Framework-specific patterns'],
    correctIndex: 0,
    explanation: 'CS50 teaches computational thinking that transfers across all languages: Scratch → C → Python → Web.',
    realWorld: 'Google, Meta, Jane Street all value problem-solving ability over syntax memorization.',
    hint: 'The course spans four different languages on purpose.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['algorithm', 'abstraction'],
  },
  {
    id: 95007,
    topic: 'cs50',
    difficulty: 'sota',
    question: 'Week 2 Arrays: `char s[] = "EMMA"; s[1] = \'M\';` works because?',
    options: ['Array declaration copies to mutable stack memory', 'Compiler optimization inlines the change', 'Stack allocation is always writable', 'The null terminator allows mutation'],
    correctIndex: 0,
    explanation: '`char s[]` copies the literal into a stack-allocated array (mutable). `char *s = "EMMA"` points to a read-only literal.',
    realWorld: 'C string handling gotchas in embedded systems — understanding the stack vs. data segment.',
    hint: 'Array initialization vs. pointer-to-literal — different memory regions.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['pointer', 'memory-management'],
  },
  {
    id: 95008,
    topic: 'cs50',
    difficulty: 'hard',
    question: 'Week 6 Python: `def factorial(n): return 1 if n == 0 else n * factorial(n-1)` is an example of?',
    options: ['Recursion', 'Iteration', 'Dynamic programming (bottom-up)', 'Tail-call optimization'],
    correctIndex: 0,
    explanation: 'Base case ($n=0$) + recursive case ($n \\cdot f(n-1)$) = recursion. Python lacks tail-call optimization.',
    realWorld: 'Tree traversals, divide-and-conquer algorithms, fractal generation all rely on recursion.',
    hint: 'The function calls itself with a smaller argument.',
    symbolLinks: { 'n': 'nu' },
    formulaLinks: ['recursion', 'big-o'],
    glossaryLinks: ['recursion', 'algorithm'],
  },
  {
    id: 95009,
    topic: 'cs50',
    difficulty: 'easy',
    question: 'CS50 evaluates final projects primarily on which three criteria?',
    options: ['Correctness, design, and style', 'Code length and feature count', 'Performance benchmarks', 'Buzzword density and framework choice'],
    correctIndex: 0,
    explanation: 'CS50\'s trinity: Does it work? Is it well-designed? Is it readable? Tools: `check50`, `style50`.',
    realWorld: 'Production code review at any company follows the same core criteria.',
    hint: 'Think `check50` and `style50`.',
    symbolLinks: {},
    formulaLinks: [],
    glossaryLinks: ['software-engineering'],
  },
];
