import type { Question } from '../types';

export const examSRMQuestions: Question[] = [
  {
    id: 82400,
    topic: 'actuarial-exam-srm',
    difficulty: 'easy',
    question: 'In simple linear regression $Y = \\beta_0 + \\beta_1 X + \\varepsilon$, the OLS estimator $\\hat{\\beta}_1$ equals:',
    options: [
      '$\\frac{\\sum(X_i - \\bar{X})(Y_i - \\bar{Y})}{\\sum(X_i - \\bar{X})^2}$',
      '$\\frac{\\bar{Y}}{\\bar{X}}$',
      '$\\frac{\\sum X_i Y_i}{n}$',
      '$\\bar{Y} - \\bar{X}$',
    ],
    correctIndex: 0,
    explanation: 'The OLS slope is the ratio of the sample covariance of X and Y to the sample variance of X, minimizing the sum of squared residuals.',
    realWorld: 'Actuaries use regression to model how claim costs vary with policyholder characteristics like age or vehicle value.',
    hint: 'It\'s covariance over variance.',
  },
  {
    id: 82401,
    topic: 'actuarial-exam-srm',
    difficulty: 'easy',
    question: 'The coefficient of determination $R^2$ in a regression model measures:',
    options: [
      'The proportion of variance in Y explained by the model',
      'The slope of the regression line',
      'The standard error of the residuals',
      'The p-value of the intercept',
    ],
    correctIndex: 0,
    explanation: '$R^2 = 1 - SS_{res}/SS_{tot}$. It ranges from 0 to 1, with higher values indicating better fit.',
    realWorld: 'Insurance pricing models are evaluated by $R^2$ and other goodness-of-fit metrics to ensure predictive accuracy.',
    hint: 'It\'s the ratio of explained to total variation.',
  },
  {
    id: 82402,
    topic: 'actuarial-exam-srm',
    difficulty: 'hard',
    question: 'In a Generalized Linear Model (GLM) with a Poisson response, the canonical link function is:',
    options: [
      'The natural logarithm: $g(\\mu) = \\ln(\\mu)$',
      'The identity: $g(\\mu) = \\mu$',
      'The logit: $g(\\mu) = \\ln(\\mu/(1-\\mu))$',
      'The inverse: $g(\\mu) = 1/\\mu$',
    ],
    correctIndex: 0,
    explanation: 'The log link ensures predicted counts are positive and connects the linear predictor to the mean through $\\ln(\\mu) = X\\beta$.',
    realWorld: 'Poisson GLMs with log link are the standard for modeling claim frequency in P&C insurance ratemaking.',
    hint: 'The canonical link for Poisson comes from the exponential family form.',
  },
  {
    id: 82403,
    topic: 'actuarial-exam-srm',
    difficulty: 'hard',
    question: 'LASSO regression differs from Ridge regression in that LASSO:',
    options: [
      'Uses an L1 penalty that can shrink coefficients exactly to zero, performing variable selection',
      'Uses an L2 penalty that spreads weight evenly across all predictors',
      'Does not require a tuning parameter',
      'Always produces higher $R^2$ than Ridge',
    ],
    correctIndex: 0,
    explanation: 'LASSO minimizes $RSS + \\lambda \\sum|\\beta_j|$. The L1 geometry creates corner solutions at zero, enabling automatic feature selection.',
    realWorld: 'Actuaries use LASSO to identify the most important rating factors from hundreds of candidate variables.',
    hint: 'L1 penalty creates sparsity; L2 penalty does not.',
  },
  {
    id: 82404,
    topic: 'actuarial-exam-srm',
    difficulty: 'sota',
    question: 'In gradient boosting for insurance claim modeling, the key difference from random forests is:',
    options: [
      'Trees are built sequentially, each fitting the residuals (pseudo-residuals) of the previous ensemble',
      'All trees are built independently on bootstrapped samples',
      'It uses a single deep tree instead of many shallow ones',
      'It cannot handle categorical predictors',
    ],
    correctIndex: 0,
    explanation: 'Gradient boosting iteratively reduces bias by fitting new trees to the gradient of the loss function, producing an additive ensemble.',
    realWorld: 'XGBoost and LightGBM are now standard tools in actuarial predictive modeling competitions and pricing.',
    hint: 'Sequential learning from mistakes, not parallel averaging.',
  },
];
