import type { Question } from '../types';

// ── CAS MAS-I: Modern Actuarial Statistics I ──
export const examMASIQuestions: Question[] = [
  {
    id: 82800,
    topic: 'actuarial-mas-i',
    difficulty: 'easy',
    question: 'The method of maximum likelihood estimation (MLE) finds parameter values that:',
    options: [
      'Maximize the probability of observing the given sample data',
      'Minimize the sum of squared residuals',
      'Set all parameters equal to their sample means',
      'Minimize the prior probability',
    ],
    correctIndex: 0,
    explanation: 'MLE maximizes $L(\\theta) = \\prod f(x_i|\\theta)$, or equivalently the log-likelihood $\\ell(\\theta) = \\sum \\ln f(x_i|\\theta)$.',
    realWorld: 'P&C actuaries use MLE to fit loss distributions (Pareto, Lognormal, Weibull) to historical claims data.',
    hint: 'It\'s the parameter value that makes the observed data most probable.',
  },
  {
    id: 82801,
    topic: 'actuarial-mas-i',
    difficulty: 'easy',
    question: 'A time series is said to be stationary if:',
    options: [
      'Its mean, variance, and autocovariance structure do not change over time',
      'It has an increasing trend',
      'Its values are always positive',
      'It has no seasonal component',
    ],
    correctIndex: 0,
    explanation: 'Weak stationarity requires constant first two moments and covariance depending only on lag, not time.',
    realWorld: 'Loss development triangles and claim frequency trends must be assessed for stationarity before applying time series models.',
    hint: 'Statistical properties don\'t depend on when you observe the series.',
  },
  {
    id: 82802,
    topic: 'actuarial-mas-i',
    difficulty: 'hard',
    question: 'In an ARIMA(1,1,1) model, the "1,1,1" refers to:',
    options: [
      'One autoregressive term, one difference, and one moving average term',
      'One variable, one observation, one prediction',
      'First-order polynomial, linear trend, one seasonal period',
      'One lag, one lead, one error term',
    ],
    correctIndex: 0,
    explanation: 'ARIMA(p,d,q): p=AR order, d=differencing order (to achieve stationarity), q=MA order. The differenced series follows an ARMA(1,1).',
    realWorld: 'Actuaries model claim frequency trends and inflation indices using ARIMA for reserve projections.',
    hint: 'The three numbers are AR order, differencing order, MA order.',
  },
  {
    id: 82803,
    topic: 'actuarial-mas-i',
    difficulty: 'hard',
    question: 'The Kaplan-Meier estimator for the survival function handles censored data by:',
    options: [
      'Computing the product of conditional survival probabilities at each observed failure time',
      'Ignoring all censored observations',
      'Treating censored observations as failures',
      'Using only the first and last observed times',
    ],
    correctIndex: 0,
    explanation: '$\\hat{S}(t) = \\prod_{t_i \\leq t} \\frac{n_i - d_i}{n_i}$ where $n_i$ = at risk and $d_i$ = failures. Censored observations reduce the risk set without contributing events.',
    realWorld: 'Actuaries use Kaplan-Meier to estimate lapse rates for insurance policies where some policyholders are still active (censored).',
    hint: 'It\'s a nonparametric product-limit estimator.',
  },
  {
    id: 82804,
    topic: 'actuarial-mas-i',
    difficulty: 'sota',
    question: 'The bootstrap method for constructing confidence intervals for an actuarial estimator works by:',
    options: [
      'Resampling with replacement from the observed data to approximate the sampling distribution',
      'Assuming the data follows a normal distribution',
      'Using only the first 10% of the data',
      'Analytically deriving the exact distribution of the estimator',
    ],
    correctIndex: 0,
    explanation: 'Bootstrap generates B resamples, computes the statistic on each, and uses the empirical distribution of those B values for inference.',
    realWorld: 'Actuaries bootstrap reserve estimates to quantify uncertainty in loss development when analytical formulas are intractable.',
    hint: 'Resample your data to simulate what could have happened.',
  },
];

// ── CAS MAS-II: Modern Actuarial Statistics II ──
export const examMASIIQuestions: Question[] = [
  {
    id: 82900,
    topic: 'actuarial-mas-ii',
    difficulty: 'easy',
    question: 'Bayesian credibility differs from classical (Bühlmann) credibility in that Bayesian credibility:',
    options: [
      'Specifies a prior distribution for the risk parameter and updates it with observed data via Bayes\' theorem',
      'Uses only the sample mean without any prior information',
      'Ignores the variance of the data',
      'Always assigns credibility $Z = 1$',
    ],
    correctIndex: 0,
    explanation: 'Bayesian credibility computes the posterior $f(\\theta|X) \\propto f(X|\\theta) \\cdot \\pi(\\theta)$ and uses the posterior mean as the premium.',
    realWorld: 'Bayesian methods are increasingly used in P&C pricing where informative priors from related markets improve estimates.',
    hint: 'Prior × Likelihood = Posterior (up to a normalizing constant).',
  },
  {
    id: 82901,
    topic: 'actuarial-mas-ii',
    difficulty: 'easy',
    question: 'In a GLM for insurance severity, the Gamma distribution is often preferred because:',
    options: [
      'It models positive, right-skewed continuous data with variance proportional to the square of the mean',
      'It only produces integer values',
      'It has a fixed variance regardless of the mean',
      'It is symmetric around the mean',
    ],
    correctIndex: 0,
    explanation: 'For Gamma: $\\text{Var}(Y) = \\mu^2/\\alpha$. This constant CV property matches the empirical behavior of insurance claim amounts.',
    realWorld: 'Tweedie and Gamma GLMs are standard for modeling per-claim severity in auto and property insurance.',
    hint: 'Claim amounts are positive, skewed, and have variance growing with the mean.',
  },
  {
    id: 82902,
    topic: 'actuarial-mas-ii',
    difficulty: 'hard',
    question: 'The Expectation-Maximization (EM) algorithm is used in actuarial modeling to:',
    options: [
      'Estimate parameters of mixture models when some data (latent class membership) is unobserved',
      'Directly minimize the sum of squared errors',
      'Perform variable selection via penalization',
      'Generate random samples from the posterior distribution',
    ],
    correctIndex: 0,
    explanation: 'EM alternates between E-step (compute expected latent variables given current parameters) and M-step (maximize likelihood given expected latent variables).',
    realWorld: 'Claim severity mixtures (e.g., small routine claims + large catastrophic claims) are fit using EM.',
    hint: 'It handles missing or latent data by iterating between expectation and maximization.',
  },
  {
    id: 82903,
    topic: 'actuarial-mas-ii',
    difficulty: 'hard',
    question: 'In Bayesian estimation, a conjugate prior is useful because:',
    options: [
      'The posterior distribution has the same functional form as the prior, simplifying computation',
      'It always produces a uniform posterior',
      'It eliminates the need for data',
      'It guarantees the MAP estimate equals the MLE',
    ],
    correctIndex: 0,
    explanation: 'Conjugate pairs (e.g., Beta-Binomial, Gamma-Poisson) yield closed-form posteriors, avoiding numerical integration.',
    realWorld: 'Actuaries use Gamma priors with Poisson claim counts for closed-form Bayesian credibility premiums.',
    hint: 'Prior and posterior are in the same family of distributions.',
  },
  {
    id: 82904,
    topic: 'actuarial-mas-ii',
    difficulty: 'sota',
    question: 'Markov Chain Monte Carlo (MCMC) methods like Metropolis-Hastings are used in actuarial science when:',
    options: [
      'The posterior distribution is analytically intractable and sampling is needed for inference',
      'The posterior has a known closed-form solution',
      'Only point estimates are required',
      'The likelihood function is linear',
    ],
    correctIndex: 0,
    explanation: 'MCMC generates correlated samples from the target posterior by constructing a Markov chain whose stationary distribution is the posterior.',
    realWorld: 'Complex reserving models (e.g., hierarchical Bayesian chain-ladder) require MCMC for full posterior inference.',
    hint: 'When you can\'t integrate analytically, simulate instead.',
  },
];
