import type { Question } from '../types';

export const examPAQuestions: Question[] = [
  {
    id: 82700,
    topic: 'actuarial-exam-pa',
    difficulty: 'easy',
    question: 'In R, the function `glm(y ~ x1 + x2, family = poisson)` fits a model with which link function by default?',
    options: [
      'Log link: $\\ln(\\mu) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2$',
      'Identity link: $\\mu = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2$',
      'Logit link: $\\ln(\\mu/(1-\\mu)) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2$',
      'Probit link',
    ],
    correctIndex: 0,
    explanation: 'The Poisson family in R defaults to the canonical log link, ensuring non-negative predicted values.',
    realWorld: 'Actuarial pricing models in R overwhelmingly use Poisson GLMs with log link for claim frequency.',
    hint: 'The canonical link for Poisson is the natural log.',
  },
  {
    id: 82701,
    topic: 'actuarial-exam-pa',
    difficulty: 'easy',
    question: 'Cross-validation in predictive modeling primarily helps to:',
    options: [
      'Estimate out-of-sample prediction error and prevent overfitting',
      'Increase the training set size',
      'Guarantee the model has zero bias',
      'Eliminate the need for a test set entirely',
    ],
    correctIndex: 0,
    explanation: 'K-fold CV repeatedly holds out different portions of data for validation, giving a robust estimate of generalization performance.',
    realWorld: 'SOA Exam PA requires candidates to implement and interpret cross-validation results in R.',
    hint: 'It simulates how the model will perform on unseen data.',
  },
  {
    id: 82702,
    topic: 'actuarial-exam-pa',
    difficulty: 'hard',
    question: 'When building a decision tree for insurance claim prediction, the Gini impurity at a node measures:',
    options: [
      'The probability that a randomly chosen sample would be misclassified if labeled according to the node\'s distribution',
      'The depth of the tree',
      'The number of features used',
      'The total number of observations',
    ],
    correctIndex: 0,
    explanation: 'Gini = $1 - \\sum p_k^2$ where $p_k$ is the proportion of class $k$. Lower Gini = purer node. Splits are chosen to maximize Gini reduction.',
    realWorld: 'Insurers use classification trees to identify fraud patterns in claims data.',
    hint: 'It measures node purity — how mixed the classes are.',
  },
  {
    id: 82703,
    topic: 'actuarial-exam-pa',
    difficulty: 'hard',
    question: 'The AIC (Akaike Information Criterion) balances model fit and complexity by:',
    options: [
      'Adding a penalty of $2k$ (where k = number of parameters) to $-2\\ln(L)$',
      'Minimizing only the log-likelihood',
      'Maximizing the number of parameters',
      'Using only the training $R^2$',
    ],
    correctIndex: 0,
    explanation: 'AIC = $-2\\ln(L) + 2k$. Lower AIC is preferred. It penalizes complexity to guard against overfitting while rewarding fit.',
    realWorld: 'Actuaries compare GLM specifications using AIC to select the most parsimonious rating model.',
    hint: 'It penalizes for each additional parameter to prevent overfitting.',
  },
  {
    id: 82704,
    topic: 'actuarial-exam-pa',
    difficulty: 'sota',
    question: 'In an actuarial predictive analytics report, the "business problem framing" section should:',
    options: [
      'Translate the statistical findings into actionable business recommendations with quantified impact',
      'Present only raw R code output without interpretation',
      'Focus exclusively on statistical significance p-values',
      'Omit any discussion of model limitations or assumptions',
    ],
    correctIndex: 0,
    explanation: 'Exam PA emphasizes communication: connecting technical analysis to business decisions, quantifying financial impact, and acknowledging limitations.',
    realWorld: 'Chief actuaries present model results to boards and regulators, requiring clear business translation.',
    hint: 'The exam tests communication as much as technical skill.',
  },
];
