import type { Question } from '../types';

export const examASTAMQuestions: Question[] = [
  {
    id: 82600,
    topic: 'actuarial-exam-astam',
    difficulty: 'easy',
    question: 'In experience rating, credibility $Z$ represents:',
    options: [
      'The weight given to the insured\'s own experience versus the class average',
      'The probability of ruin',
      'The loading factor for expenses',
      'The policy deductible amount',
    ],
    correctIndex: 0,
    explanation: 'Credibility-weighted premium = $Z \\cdot \\text{Experience} + (1-Z) \\cdot \\text{Manual Rate}$, blending individual data with population data.',
    realWorld: 'Workers\' compensation experience modification factors use this exact credibility framework.',
    hint: 'It\'s about how much to trust the individual\'s data.',
  },
  {
    id: 82601,
    topic: 'actuarial-exam-astam',
    difficulty: 'easy',
    question: 'The loss ratio method in ratemaking calculates the indicated rate change as:',
    options: [
      '$\\frac{\\text{Actual Loss Ratio}}{\\text{Target Loss Ratio}} - 1$',
      'Actual losses divided by number of policies',
      'Target loss ratio minus actual loss ratio',
      'Total premium divided by total claims',
    ],
    correctIndex: 0,
    explanation: 'If actual LR = 70% and target LR = 60%, the indicated change is 70/60 - 1 = +16.7%.',
    realWorld: 'State insurance regulators review loss ratio analyses when approving or denying rate increase filings.',
    hint: 'Compare what you\'re experiencing to what you\'re targeting.',
  },
  {
    id: 82602,
    topic: 'actuarial-exam-astam',
    difficulty: 'hard',
    question: 'Bühlmann credibility assigns $Z = n/(n+k)$ where $k$ equals:',
    options: [
      '$k = \\text{Expected Value of Process Variance} / \\text{Variance of Hypothetical Means}$',
      '$k = n \\cdot \\sigma^2$',
      '$k$ is always equal to 1',
      '$k = \\text{Variance of Hypothetical Means} / n$',
    ],
    correctIndex: 0,
    explanation: '$k = v/a$ where $v = E[\\text{Var}(X|\\Theta)]$ (within-risk variance) and $a = \\text{Var}(E[X|\\Theta])$ (between-risk variance). More heterogeneity → smaller k → faster credibility.',
    realWorld: 'Bühlmann credibility is the backbone of commercial lines pricing where individual risk data is limited.',
    hint: 'k is the ratio of expected process variance to variance of hypothetical means.',
  },
  {
    id: 82603,
    topic: 'actuarial-exam-astam',
    difficulty: 'hard',
    question: 'In proportional reinsurance, a quota share treaty with 40% cession means the reinsurer:',
    options: [
      'Pays 40% of every loss and receives 40% of the premium (minus ceding commission)',
      'Pays losses only above a $40,000 retention',
      'Pays 40% only for losses exceeding a threshold',
      'Receives the entire premium but pays all losses',
    ],
    correctIndex: 0,
    explanation: 'Quota share is the simplest reinsurance: a fixed percentage of every risk is ceded, with premium and losses shared proportionally.',
    realWorld: 'Small insurers use quota share to reduce volatility and leverage the reinsurer\'s capital for regulatory compliance.',
    hint: 'Proportional means the same percentage applies to every single loss.',
  },
  {
    id: 82604,
    topic: 'actuarial-exam-astam',
    difficulty: 'sota',
    question: 'The adjustment coefficient $R$ in classical ruin theory satisfies:',
    options: [
      '$\\lambda + cR = \\lambda M_X(R)$, where $M_X$ is the MGF of individual claim sizes',
      '$R = 1/\\lambda$ for all claim distributions',
      '$R$ equals the force of interest',
      '$R = \\text{Var}(S)/E[S]$',
    ],
    correctIndex: 0,
    explanation: 'Lundberg\'s equation $1 + (1+\\theta)\\mu R = M_X(R)$ (equivalently $\\lambda + cR = \\lambda M_X(R)$) defines R. The ruin probability bound is $\\psi(u) \\leq e^{-Ru}$.',
    realWorld: 'Reinsurers use ruin theory to set capital adequacy targets and evaluate the impact of reinsurance structures.',
    hint: 'It comes from the Lundberg inequality for the probability of ruin.',
  },
];
