import type { Question } from '../types';

export const examALTAMQuestions: Question[] = [
  {
    id: 82500,
    topic: 'actuarial-exam-altam',
    difficulty: 'easy',
    question: 'In a multi-state model for disability insurance, a healthy life can transition to which states?',
    options: [
      'Disabled and Dead, with separate transition intensities for each',
      'Only the Dead state',
      'Only the Disabled state with no possibility of death',
      'A single absorbing state that combines all decrements',
    ],
    correctIndex: 0,
    explanation: 'Multi-state models allow transitions between multiple states (healthy → disabled, healthy → dead, disabled → healthy, disabled → dead) with distinct forces of transition.',
    realWorld: 'Long-term disability insurers use multi-state models to price income protection policies with recovery provisions.',
    hint: 'Think of a Markov chain with healthy, disabled, and dead states.',
  },
  {
    id: 82501,
    topic: 'actuarial-exam-altam',
    difficulty: 'easy',
    question: 'The net premium reserve for a term insurance policy at duration $t$ represents:',
    options: [
      'The expected present value of future benefits minus expected present value of future premiums',
      'The total premiums collected from inception',
      'The death benefit amount divided by the policy term',
      'The policyholder\'s accumulated cash value',
    ],
    correctIndex: 0,
    explanation: 'The prospective reserve formula ${}_tV = A_{x+t:\\overline{n-t}|} - P \\cdot \\ddot{a}_{x+t:\\overline{n-t}|}$ measures the insurer\'s net liability.',
    realWorld: 'Regulators require statutory reserves to ensure insurers hold adequate assets to cover future obligations.',
    hint: 'Prospective = future benefits minus future premiums.',
  },
  {
    id: 82502,
    topic: 'actuarial-exam-altam',
    difficulty: 'hard',
    question: 'Thiele\'s differential equation for continuous reserves $\\frac{d}{dt}{}_tV$ includes which components?',
    options: [
      'Premium income, interest on reserve, and expected claim outgo weighted by force of mortality',
      'Only interest on reserve',
      'Only premium income minus expenses',
      'A constant rate independent of the force of mortality',
    ],
    correctIndex: 0,
    explanation: '$\\frac{d}{dt}{}_tV = \\delta \\cdot {}_tV + P_t - \\mu_{x+t}(b_{t} - {}_tV)$ balances interest earnings, premiums, and expected mortality cost.',
    realWorld: 'Thiele\'s equation is the foundation of modern actuarial cash-flow projection systems used in valuation.',
    hint: 'It\'s a continuous-time balance equation for reserves.',
  },
  {
    id: 82503,
    topic: 'actuarial-exam-altam',
    difficulty: 'hard',
    question: 'In pension mathematics, the Entry Age Normal (EAN) cost method determines the annual normal cost as:',
    options: [
      'A level percentage of salary from entry age to retirement that funds the projected benefit',
      'The change in accrued liability from year to year',
      'The benefit payable at retirement divided by years of service',
      'A percentage that varies annually based on investment returns',
    ],
    correctIndex: 0,
    explanation: 'EAN sets a constant contribution rate from hire date such that the PV of all contributions equals the PV of projected benefits at retirement.',
    realWorld: 'Most US public pension plans use EAN for determining employer contribution requirements.',
    hint: 'Entry Age Normal = level cost from the date of hire.',
  },
  {
    id: 82504,
    topic: 'actuarial-exam-altam',
    difficulty: 'sota',
    question: 'The Kolmogorov forward equations for a continuous-time Markov chain describe:',
    options: [
      'How state occupation probabilities evolve over time as a system of differential equations involving transition intensities',
      'The equilibrium distribution of a discrete-time chain',
      'The expected number of transitions in a fixed interval',
      'The variance of the time spent in each state',
    ],
    correctIndex: 0,
    explanation: '$\\frac{d}{dt}P(t) = P(t) \\cdot Q$ where $Q$ is the generator matrix of transition intensities. These ODEs govern all multi-state actuarial models.',
    realWorld: 'Health insurance and long-term care products are priced using numerical solutions to Kolmogorov equations.',
    hint: 'Forward equations describe how probabilities propagate forward in time.',
  },
];
