import type { Question } from '../types';

export const easyQuestions: Question[] = [
  {
    id: 1,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'What does $\\mathbf{A}\\mathbf{x} = \\mathbf{b}$ represent?',
    options: ['A system of linear equations', 'A differential equation', 'A probability distribution', 'An optimization problem'],
    correctIndex: 0,
    explanation: 'Matrix-vector multiplication $\\mathbf{A}\\mathbf{x} = \\mathbf{b}$ encodes a system of linear equations where $\\mathbf{A}$ is the coefficient matrix.',
    realWorld: 'Used everywhere from solving circuits to training linear regression models.',
    hint: 'Think about how rows of a matrix combine with entries of a vector.',
  },
  {
    id: 2,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'What is the $L_2$ norm $\\|\\mathbf{x}\\|_2$ of a vector?',
    options: ['Sum of absolute values', 'Euclidean length (square root of sum of squares)', 'Maximum component', 'Number of nonzero entries'],
    correctIndex: 1,
    explanation: '$\\|\\mathbf{x}\\|_2 = \\sqrt{\\sum_i x_i^2}$ gives the Euclidean distance from the origin.',
    realWorld: 'L2 norm is the backbone of regularization in ML (Ridge regression).',
    hint: 'Recall the Pythagorean theorem generalized to n dimensions.',
  },
  {
    id: 26,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'The transpose of $\\mathbf{A}$ swaps:',
    options: ['Eigenvalues and eigenvectors', 'Rows and columns', 'Diagonal and off-diagonal', 'Real and imaginary parts'],
    correctIndex: 1,
    explanation: 'The transpose $\\mathbf{A}^T$ has $(A^T)_{ij} = A_{ji}$, effectively reflecting the matrix across its diagonal.',
    realWorld: 'Transposition is used in computing $\\mathbf{A}^T\\mathbf{A}$ for least-squares and covariance matrices.',
    hint: 'What happens when you flip a matrix along its main diagonal?',
  },
  {
    id: 29,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'The dot product $\\mathbf{a} \\cdot \\mathbf{b} = 0$ means the vectors are:',
    options: ['Parallel', 'Orthogonal (perpendicular)', 'Equal', 'Unit vectors'],
    correctIndex: 1,
    explanation: 'A zero dot product means the angle between vectors is 90° — they are orthogonal.',
    realWorld: 'Orthogonality is fundamental in PCA, Gram-Schmidt, and attention mechanisms in transformers.',
    hint: 'Consider what angle between two vectors gives cosine = 0.',
  },
  {
    id: 48,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'An identity matrix $\\mathbf{I}$ satisfies $\\mathbf{I}\\mathbf{x} = $?',
    options: ['$\\mathbf{0}$', '$\\mathbf{x}$', '$\\mathbf{x}^T$', '$2\\mathbf{x}$'],
    correctIndex: 1,
    explanation: 'The identity matrix leaves any vector unchanged: $\\mathbf{I}\\mathbf{x} = \\mathbf{x}$. It has ones on the diagonal and zeros elsewhere.',
    realWorld: 'Identity matrices appear in initialization of neural network weights and as default transformations.',
    hint: 'This special matrix does absolutely nothing to whatever it multiplies.',
  },
  {
    id: 49,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'A $3 \\times 2$ matrix has:',
    options: ['3 columns and 2 rows', '3 rows and 2 columns', '6 rows', '5 elements'],
    correctIndex: 1,
    explanation: 'Matrix dimensions are always rows × columns. A $3 \\times 2$ matrix has 3 rows and 2 columns (6 elements total).',
    realWorld: 'Understanding matrix dimensions is essential for verifying valid matrix multiplications in neural network architectures.',
    hint: 'The first number is always the number of rows.',
  },
  {
    id: 50,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'Matrix multiplication $\\mathbf{A}\\mathbf{B}$ requires:',
    options: ['Both matrices to be square', 'Columns of $\\mathbf{A}$ = rows of $\\mathbf{B}$', 'Same number of rows', 'Both matrices to be symmetric'],
    correctIndex: 1,
    explanation: 'For $\\mathbf{A}_{m \\times n} \\cdot \\mathbf{B}_{n \\times p}$, the inner dimensions must match. The result is $m \\times p$.',
    realWorld: 'Layer dimensions in neural networks must be compatible for forward propagation.',
    hint: 'The inner dimensions must agree — columns on the left, rows on the right.',
  },
  {
    id: 51,
    topic: 'linear-algebra',
    difficulty: 'easy',
    question: 'A symmetric matrix satisfies:',
    options: ['$\\mathbf{A} = -\\mathbf{A}^T$', '$\\mathbf{A} = \\mathbf{A}^T$', '$\\mathbf{A} = \\mathbf{A}^{-1}$', '$\\det(\\mathbf{A}) = 1$'],
    correctIndex: 1,
    explanation: 'A symmetric matrix equals its own transpose: $A_{ij} = A_{ji}$ for all $i, j$.',
    realWorld: 'Covariance matrices and kernel matrices in ML are always symmetric.',
    hint: 'This matrix is a mirror image of itself across the diagonal.',
  },
];
