import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 3,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'If $\\mathbf{A}\\mathbf{v} = \\lambda \\mathbf{v}$, what is $\\lambda$?',
    options: ['A singular value', 'The determinant', 'An eigenvalue', 'The trace'],
    correctIndex: 2,
    explanation: '$\\lambda$ is an eigenvalue of $\\mathbf{A}$, and $\\mathbf{v}$ is the corresponding eigenvector — a direction that $\\mathbf{A}$ only scales.',
    realWorld: 'PCA uses eigenvalues to find principal directions in data.',
    hint: 'This scalar tells you how much a special direction gets stretched.',
  },
  {
    id: 5,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'What does the determinant $\\det(\\mathbf{A}) = 0$ imply?',
    options: ['$\\mathbf{A}$ has orthonormal columns', '$\\mathbf{A}$ has only real eigenvalues', '$\\mathbf{A}$ has full rank', '$\\mathbf{A}$ has a nontrivial null space'],
    correctIndex: 3,
    explanation: 'A zero determinant means $\\mathbf{A}$ is singular. Equivalently, its columns are linearly dependent and there is a nonzero vector $\\mathbf{x}$ with $\\mathbf{A}\\mathbf{x}=\\mathbf{0}$, so the null space is nontrivial and $\\mathbf{A}$ cannot be inverted.',
    realWorld: 'Singularity detection prevents crashes in numerical solvers.',
    hint: 'What happens to the volume of a parallelepiped when it collapses?',
  },
  {
    id: 27,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'The trace $\\text{tr}(\\mathbf{A})$ equals:',
    options: ['The product of eigenvalues', 'The sum of diagonal elements', 'The determinant', 'The rank'],
    correctIndex: 1,
    explanation: '$\\text{tr}(\\mathbf{A}) = \\sum_i A_{ii}$. It also equals the sum of eigenvalues.',
    realWorld: 'The trace appears in Frobenius norm and is used in spectral methods for graph clustering.',
    hint: 'Look at what sits on the main diagonal and sum it up.',
  },
  {
    id: 52,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'The null space of $\\mathbf{A}$ is the set of vectors $\\mathbf{x}$ where:',
    options: ['$\\mathbf{A}\\mathbf{x} = \\mathbf{0}$', '$\\mathbf{A}\\mathbf{x} = \\mathbf{x}$', '$\\|\\mathbf{x}\\| = 0$', '$\\mathbf{x}^T\\mathbf{A} = \\mathbf{x}^T$'],
    correctIndex: 0,
    explanation: 'The null space (kernel) contains all vectors mapped to zero by $\\mathbf{A}$. A nontrivial null space means $\\mathbf{A}$ is rank-deficient.',
    realWorld: 'Understanding null spaces helps diagnose underdetermined systems in robotics and control theory.',
    hint: 'Which vectors get completely annihilated by the matrix?',
  },
  {
    id: 53,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'An orthogonal matrix $\\mathbf{Q}$ satisfies $\\mathbf{Q}^T\\mathbf{Q} = $?',
    options: ['$\\mathbf{0}$', '$\\mathbf{Q}$', '$\\mathbf{I}$', '$\\mathbf{Q}^2$'],
    correctIndex: 2,
    explanation: 'An orthogonal matrix has orthonormal columns: $\\mathbf{Q}^T\\mathbf{Q} = \\mathbf{I}$, meaning $\\mathbf{Q}^{-1} = \\mathbf{Q}^T$.',
    realWorld: 'QR decomposition uses orthogonal matrices for stable numerical computation.',
    hint: 'The transpose does the job of the inverse for this special matrix.',
  },
  {
    id: 54,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'The column space of $\\mathbf{A}$ is:',
    options: ['The set of vectors mapped to zero by $\\mathbf{A}$', 'The set of all linear combinations of the rows of $\\mathbf{A}$', 'The span of eigenvectors associated with nonzero eigenvalues', 'The set of vectors $\\mathbf{A}\\mathbf{x}$ as $\\mathbf{x}$ varies'],
    correctIndex: 3,
    explanation: 'The column space is the span of all columns of $\\mathbf{A}$ — the set of all linear combinations $\\mathbf{A}\\mathbf{x}$.',
    realWorld: 'Least-squares projects $\\mathbf{b}$ onto the column space of $\\mathbf{A}$ when exact solutions don\'t exist.',
    hint: 'What outputs can the matrix actually produce?',
  },
  {
    id: 55,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'If $\\mathbf{A}$ is $n \\times n$ with $n$ distinct eigenvalues, then $\\mathbf{A}$ is:',
    options: ['Always singular', 'Diagonalizable', 'Always symmetric', 'Always orthogonal'],
    correctIndex: 1,
    explanation: 'Distinct eigenvalues guarantee linearly independent eigenvectors, so $\\mathbf{A} = \\mathbf{P}\\mathbf{D}\\mathbf{P}^{-1}$.',
    realWorld: 'Diagonalization speeds up matrix powers, used in Markov chain analysis and dynamical systems.',
    hint: 'Distinct eigenvalues ensure the eigenvectors form a basis.',
  },
  {
    id: 56,
    topic: 'linear-algebra',
    difficulty: 'hard',
    question: 'The Frobenius norm $\\|\\mathbf{A}\\|_F$ is:',
    options: ['$\\sqrt{\\sum_{i,j} |A_{ij}|^2}$', '$\\max_{\\|\\mathbf{x}\\|_2=1} \\|\\mathbf{A}\\mathbf{x}\\|_2$', '$\\max_i \\sum_j |A_{ij}|$', '$\\sum_i |\\lambda_i(\\mathbf{A})|$'],
    correctIndex: 0,
    explanation: 'The Frobenius norm treats the matrix as a vector and takes the L2 norm: $\\sqrt{\\sum_{i,j} |a_{ij}|^2}$.',
    realWorld: 'Used as a regularization term for weight matrices in neural networks.',
    hint: 'Square every entry, add them all up, then take the square root.',
  },
];
