import type { Question } from '../types';

export const sotaQuestions: Question[] = [
  {
    id: 4,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'In SVD, $\\mathbf{A} = \\mathbf{U}\\mathbf{\\Sigma}\\mathbf{V}^T$. What are $\\mathbf{U}$ and $\\mathbf{V}$?',
    options: ['Diagonal matrices', 'Orthogonal (unitary) matrices', 'Lower triangular matrices', 'Permutation matrices'],
    correctIndex: 1,
    explanation: '$\\mathbf{U}$ and $\\mathbf{V}$ are orthogonal matrices whose columns are left and right singular vectors. $\\mathbf{\\Sigma}$ holds singular values.',
    realWorld: 'SVD powers Netflix recommendations and image compression.',
    hint: 'These matrices have the property that their transpose equals their inverse.',
  },
  {
    id: 28,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'A positive definite matrix $\\mathbf{A}$ satisfies $\\mathbf{x}^T\\mathbf{A}\\mathbf{x} > 0$ for all $\\mathbf{x} \\neq 0$. This guarantees:',
    options: ['$\\mathbf{A}$ is diagonal', 'All eigenvalues are positive', '$\\mathbf{A}$ has rank 1', '$\\det(\\mathbf{A}) = 0$'],
    correctIndex: 1,
    explanation: 'Positive definiteness means the quadratic form is always positive, which is equivalent to all eigenvalues being strictly positive.',
    realWorld: 'Covariance matrices must be positive semi-definite; Hessians of convex functions are positive definite.',
    hint: 'What must be true about eigenvalues for the quadratic form to never go negative?',
  },
  {
    id: 30,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'The rank of $\\mathbf{A} \\in \\mathbb{R}^{m \\times n}$ is:',
    options: ['Always $\\min(m, n)$', 'The number of linearly independent columns (or rows)', 'The number of zero eigenvalues', 'Equal to $m \\cdot n$'],
    correctIndex: 1,
    explanation: 'Rank counts the maximum number of linearly independent rows or columns. A rank-deficient matrix has dependent rows/columns.',
    realWorld: 'Low-rank approximations (LoRA) are used to efficiently fine-tune large language models.',
    hint: 'Think about the dimension of the column space.',
  },
  {
    id: 57,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'The spectral theorem states that a real symmetric matrix can be decomposed as:',
    options: ['$\\mathbf{A} = \\mathbf{L}\\mathbf{U}$', '$\\mathbf{A} = \\mathbf{Q}\\mathbf{\\Lambda}\\mathbf{Q}^T$ with orthogonal $\\mathbf{Q}$', '$\\mathbf{A} = \\mathbf{A}^T\\mathbf{A}$', '$\\mathbf{A} = \\mathbf{P}\\mathbf{D}$ with permutation $\\mathbf{P}$'],
    correctIndex: 1,
    explanation: 'The spectral theorem guarantees real symmetric matrices have real eigenvalues and orthogonal eigenvectors: $\\mathbf{A} = \\mathbf{Q}\\mathbf{\\Lambda}\\mathbf{Q}^T$.',
    realWorld: 'The spectral theorem underpins PCA, spectral clustering, and graph Laplacian methods.',
    hint: 'Symmetric matrices have a particularly clean eigendecomposition with orthogonal eigenvectors.',
  },
  {
    id: 58,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'The condition number $\\kappa(\\mathbf{A}) = \\|\\mathbf{A}\\| \\cdot \\|\\mathbf{A}^{-1}\\|$ measures:',
    options: ['The rank of $\\mathbf{A}$', 'How sensitive solutions are to perturbations', 'The number of eigenvalues', 'Whether $\\mathbf{A}$ is symmetric'],
    correctIndex: 1,
    explanation: 'A large condition number means small changes in $\\mathbf{b}$ cause large changes in $\\mathbf{x}$. The system is ill-conditioned.',
    realWorld: 'Ill-conditioned matrices cause numerical instability in training deep networks and solving PDEs.',
    hint: 'It is the ratio of the largest to smallest singular value.',
  },
  {
    id: 59,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'In the Moore-Penrose pseudoinverse $\\mathbf{A}^+$, when $\\mathbf{A}$ is not square:',
    options: ['$\\mathbf{A}^+ = \\mathbf{A}^T$', '$\\mathbf{A}^+$ minimizes $\\|\\mathbf{A}\\mathbf{x} - \\mathbf{b}\\|$ with smallest $\\|\\mathbf{x}\\|$', '$\\mathbf{A}^+$ does not exist', '$\\mathbf{A}^+ = \\mathbf{A}^{-1}$'],
    correctIndex: 1,
    explanation: 'The pseudoinverse gives the minimum-norm least-squares solution, generalizing the inverse to non-square and singular matrices.',
    realWorld: 'Used in underdetermined systems, robotics inverse kinematics, and linear regression.',
    hint: 'It finds the best approximate solution when an exact inverse does not exist.',
  },
  {
    id: 60,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'The Kronecker product $\\mathbf{A} \\otimes \\mathbf{B}$ of $m \\times n$ and $p \\times q$ matrices has size:',
    options: ['$(m+p) \\times (n+q)$', '$(mp) \\times (nq)$', '$m \\times q$', '$\\max(m,p) \\times \\max(n,q)$'],
    correctIndex: 1,
    explanation: 'The Kronecker product replaces each entry $a_{ij}$ with the block $a_{ij}\\mathbf{B}$, yielding a $(mp) \\times (nq)$ matrix.',
    realWorld: 'Used in quantum computing (tensor product of qubit states) and multi-task learning.',
    hint: 'Each element of A gets replaced by a scaled copy of the entire B matrix.',
  },
  {
    id: 61,
    topic: 'linear-algebra',
    difficulty: 'sota',
    question: 'The matrix exponential $e^{\\mathbf{A}} = \\sum_{k=0}^{\\infty} \\frac{\\mathbf{A}^k}{k!}$ is used to solve:',
    options: ['$\\mathbf{A}\\mathbf{x} = \\mathbf{b}$', '$\\frac{d\\mathbf{x}}{dt} = \\mathbf{A}\\mathbf{x}$ with solution $\\mathbf{x}(t) = e^{\\mathbf{A}t}\\mathbf{x}_0$', '$\\det(\\mathbf{A}) = 0$', '$\\mathbf{A}^T = \\mathbf{A}^{-1}$'],
    correctIndex: 1,
    explanation: 'The matrix exponential solves linear ODEs: $\\mathbf{x}(t) = e^{\\mathbf{A}t}\\mathbf{x}_0$ generalizes scalar exponential growth.',
    realWorld: 'Used in continuous-time neural ODEs, control theory, and quantum mechanics.',
    hint: 'It generalizes the scalar exponential to solve systems of differential equations.',
  },
];
