import type { Question } from '../types';

export const sota2024Questions: Question[] = [
  // ── Foundational LLMs ──────────────────────────────────────
  {
    id: 2401,
    topic: 'sota-2024',
    difficulty: 'easy',
    question: 'GPT-4 primarily uses which architecture?',
    options: ['Recurrent Neural Network', 'Transformer (decoder-only)', 'Convolutional Neural Network', 'Graph Neural Network'],
    correctIndex: 1,
    explanation: 'GPT-4 is a decoder-only Transformer, scaling the architecture introduced in "Attention Is All You Need" to trillions of tokens.',
    realWorld: 'GPT-4 powers ChatGPT, Copilot, and thousands of enterprise applications worldwide.',
    hint: 'Think about the "T" in GPT.',
  },
  {
    id: 2402,
    topic: 'sota-2024',
    difficulty: 'easy',
    question: 'Llama 2 was released by which organization?',
    options: ['Google DeepMind', 'OpenAI', 'Meta AI', 'Anthropic'],
    correctIndex: 2,
    explanation: 'Meta AI released Llama 2 as an open-weight model family, enabling broad community research and fine-tuning.',
    realWorld: 'Llama 2 kickstarted the open-weight LLM movement, spawning thousands of community fine-tunes.',
    hint: 'This company also owns Facebook and Instagram.',
  },
  {
    id: 2403,
    topic: 'sota-2024',
    difficulty: 'easy',
    question: 'What does "MoE" stand for in Mixtral\'s architecture?',
    options: ['Model of Everything', 'Mixture of Experts', 'Module of Encoders', 'Multi-objective Estimation'],
    correctIndex: 1,
    explanation: 'Mixture of Experts routes each token to a subset of "expert" FFN layers, allowing large capacity with lower compute per token.',
    realWorld: 'Mixtral 8x7B matches GPT-3.5 quality while using only ~13B active parameters per token.',
    hint: 'Not all experts are used for every input token.',
  },
  {
    id: 2404,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'In Llama 2, Grouped Query Attention (GQA) reduces memory by:',
    options: ['Sharing key-value heads across multiple query heads', 'Eliminating attention entirely', 'Using only local attention windows', 'Quantizing all weights to 4-bit'],
    correctIndex: 0,
    explanation: 'GQA uses fewer KV heads than query heads, reducing the KV cache size while maintaining most of multi-head attention\'s quality.',
    realWorld: 'GQA enables serving 70B models on fewer GPUs by dramatically shrinking KV cache memory.',
    hint: 'It\'s between multi-head attention and multi-query attention.',
  },
  {
    id: 2405,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'Phi-2 (2.7B params) achieved strong benchmarks primarily through:',
    options: ['Massive model scale', 'High-quality "textbook-quality" training data', 'Reinforcement learning from human feedback', 'Sparse mixture of experts'],
    correctIndex: 1,
    explanation: 'Microsoft\'s Phi-2 demonstrated that curated, high-quality synthetic and textbook data can compensate for smaller model size.',
    realWorld: 'Phi-2 showed that data quality matters more than raw scale, influencing the "small but mighty" model trend.',
    hint: 'Quality over quantity in training data.',
  },
  {
    id: 2406,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'The key innovation in Mixtral 8x7B\'s routing mechanism is:',
    options: ['Each token activates all 8 experts', 'A top-2 gating function selects 2 of 8 experts per token', 'Experts are selected randomly', 'All tokens share the same expert'],
    correctIndex: 1,
    explanation: 'Mixtral uses a learned router that selects the top-2 experts per token, keeping compute at ~13B params while having 47B total.',
    realWorld: 'This sparse activation enables Mixtral to match or beat GPT-3.5 at 6× lower inference cost.',
    hint: 'Sparse routing — only a fraction of parameters are active.',
  },
  // ── Alignment & Safety ──────────────────────────────────────
  {
    id: 2407,
    topic: 'sota-2024',
    difficulty: 'easy',
    question: 'RLHF stands for:',
    options: ['Recursive Learning from Heuristic Functions', 'Reinforcement Learning from Human Feedback', 'Regularized Linear High-Frequency', 'Reward Learning for Helpful Features'],
    correctIndex: 1,
    explanation: 'RLHF trains a reward model from human preference data, then optimizes the LLM policy using PPO against that reward.',
    realWorld: 'RLHF is the technique that made ChatGPT helpful and safe compared to raw GPT-3.',
    hint: 'Humans rank outputs, and the model learns from those rankings.',
  },
  {
    id: 2408,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'Direct Preference Optimization (DPO) improves on RLHF by:',
    options: ['Using a separate reward model with PPO', 'Directly optimizing the policy without a reward model', 'Training only on rejected outputs', 'Requiring no preference data at all'],
    correctIndex: 1,
    explanation: 'DPO reparameterizes the RLHF objective so the optimal policy can be obtained directly from preference pairs without training a reward model or running PPO.',
    realWorld: 'DPO is simpler, more stable, and used in Zephyr, Tulu 2, and many open-source alignment pipelines.',
    hint: 'It eliminates the reward model training step.',
  },
  {
    id: 2409,
    topic: 'sota-2024',
    difficulty: 'sota',
    question: 'Constitutional AI (Anthropic) uses which technique to reduce harmful outputs?',
    options: ['Only human labelers for all feedback', 'AI self-critique guided by a set of principles ("constitution")', 'Removing all safety training data', 'Hard-coding response filters'],
    correctIndex: 1,
    explanation: 'Constitutional AI has the model critique and revise its own outputs according to a set of explicit principles, then uses RLAIF (RL from AI Feedback) for further alignment.',
    realWorld: 'Claude\'s safety properties are largely derived from Constitutional AI, reducing reliance on expensive human annotation.',
    hint: 'The AI follows a written set of rules to judge its own behavior.',
  },
  {
    id: 2410,
    topic: 'sota-2024',
    difficulty: 'sota',
    question: 'The DPO loss function $\\mathcal{L}_{DPO} = -\\log \\sigma(\\beta \\log \\frac{\\pi_\\theta(y_w|x)}{\\pi_{ref}(y_w|x)} - \\beta \\log \\frac{\\pi_\\theta(y_l|x)}{\\pi_{ref}(y_l|x)})$ optimizes:',
    options: ['The reward model accuracy', 'The log-likelihood ratio between preferred and dispreferred completions', 'The KL divergence from a uniform prior', 'Cross-entropy on next-token prediction'],
    correctIndex: 1,
    explanation: 'DPO directly increases the log-probability ratio of preferred ($y_w$) over dispreferred ($y_l$) completions relative to a reference policy, without an explicit reward model.',
    realWorld: 'This elegant formulation made RLHF-quality alignment accessible to researchers without massive compute for PPO.',
    hint: 'It\'s a contrastive objective on preference pairs.',
  },
  // ── Vision & Multimodal ──────────────────────────────────────
  {
    id: 2411,
    topic: 'sota-2024',
    difficulty: 'easy',
    question: 'DALL-E 3 generates images from:',
    options: ['Audio waveforms', 'Text descriptions (prompts)', 'Video frames only', '3D mesh data'],
    correctIndex: 1,
    explanation: 'DALL-E 3 is a text-to-image diffusion model that generates high-quality images from natural language prompts with improved text rendering.',
    realWorld: 'DALL-E 3 is integrated into ChatGPT Plus, enabling conversational image creation.',
    hint: 'You describe what you want in words.',
  },
  {
    id: 2412,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'GPT-4V (Vision) processes images by:',
    options: ['Converting images to text descriptions first', 'Encoding image patches as tokens alongside text tokens', 'Using a separate CNN with no language connection', 'Only accepting pre-labeled images'],
    correctIndex: 1,
    explanation: 'GPT-4V uses a vision encoder to convert image patches into token embeddings that are processed alongside text tokens in the Transformer.',
    realWorld: 'This enables multimodal reasoning: describing photos, reading charts, solving visual math problems.',
    hint: 'Images become tokens, just like words.',
  },
  {
    id: 2413,
    topic: 'sota-2024',
    difficulty: 'sota',
    question: 'Stable Diffusion XL (SDXL) uses which key architectural improvement over SD 1.5?',
    options: ['Single-stage U-Net only', 'A two-stage pipeline with a base model + refiner model', 'Pure autoregressive generation', 'No latent space — operates in pixel space'],
    correctIndex: 1,
    explanation: 'SDXL uses a base model for initial generation and an optional refiner model that operates on the same latent space for high-frequency detail enhancement.',
    realWorld: 'SDXL produces 1024×1024 images natively, a major step up from SD 1.5\'s 512×512.',
    hint: 'Two models work together: one creates, one refines.',
  },
  {
    id: 2414,
    topic: 'sota-2024',
    difficulty: 'sota',
    question: 'LLaVA (Large Language and Vision Assistant) connects a vision encoder to an LLM via:',
    options: ['Fine-tuning the entire vision encoder end-to-end', 'A simple linear projection layer mapping visual features to the LLM\'s embedding space', 'A separate retrieval pipeline', 'Pre-computing all image captions offline'],
    correctIndex: 1,
    explanation: 'LLaVA uses a lightweight linear projection to map CLIP visual features into the LLM\'s word embedding space, enabling visual instruction following with minimal overhead.',
    realWorld: 'LLaVA demonstrated that connecting frozen vision encoders to LLMs via simple projections achieves strong multimodal performance.',
    hint: 'The simplest possible bridge between vision and language.',
  },
  {
    id: 2415,
    topic: 'sota-2024',
    difficulty: 'hard',
    question: 'Google\'s Gemini 1.0 was notable for being:',
    options: ['Text-only like GPT-3', 'Natively multimodal from pre-training (text, image, audio, video)', 'A pure image generation model', 'A reinforcement learning agent only'],
    correctIndex: 1,
    explanation: 'Gemini was trained natively on interleaved text, image, audio, and video data from the start, rather than adding modalities post-hoc.',
    realWorld: 'Gemini Ultra matched or exceeded GPT-4 on many benchmarks and powered Google\'s Bard (now Gemini) chatbot.',
    hint: 'It was designed from the ground up to handle multiple types of input.',
  },
];
