import type { Question } from "../types";

export const cryptographyExpansionQuestions: Question[] = [
  {
    id: 60022, topic: "cryptography", difficulty: "easy",
    question: "What security property does a cryptographic hash function primarily provide when checking whether a downloaded file changed?",
    options: ["Integrity checking", "Confidentiality", "Forward secrecy", "Key exchange"],
    correctIndex: 0,
    explanation: "Comparing a trusted cryptographic hash with the downloaded file's hash can reveal accidental or malicious changes to the file.",
    realWorld: "Software distributors publish checksums so users and automated systems can verify that release artifacts were not altered in transit or storage.",
    hint: "The goal is to detect modification, not to hide the file.",
    glossaryLinks: ["hash-function"],
    reviewedAt: "2026-09-20",
  },
  {
    id: 60023, topic: "cryptography", difficulty: "easy",
    question: "In symmetric-key encryption, the sender and receiver normally:",
    options: ["Use unrelated public keys", "Share the same secret key", "Publish the decryption key", "Avoid using any key"],
    correctIndex: 1,
    explanation: "Symmetric encryption uses a shared secret: the parties use the same key, or directly related secret key material, for encryption and decryption.",
    realWorld: "High-throughput protocols commonly use symmetric ciphers such as AES after a separate key-establishment step creates shared secret material.",
    hint: "The defining feature is a secret known to both communicating parties.",
    reviewedAt: "2026-09-20",
  },
  {
    id: 60024, topic: "cryptography", difficulty: "easy",
    question: "A digital signature is designed to let a verifier check that a message:",
    options: ["Was encrypted so only the verifier can read it", "Was compressed without losing any of its contents", "Was signed by the private key holder and was not altered", "Can be recovered if the original copy is deleted"],
    correctIndex: 2,
    explanation: "A valid digital signature authenticates the signer relative to a public key and protects message integrity; it does not by itself provide confidentiality.",
    realWorld: "Code signing, software updates, certificates, and signed documents use digital signatures to authenticate origin and detect tampering.",
    hint: "Think authentication plus integrity, not secrecy.",
    reviewedAt: "2026-09-20",
  },
  {
    id: 60025, topic: "cryptography", difficulty: "hard",
    question: "Why should AES-GCM never reuse the same nonce with the same key?",
    options: ["It makes the AES key twice as long", "It forces every plaintext to be padded", "It converts AES into a hash function", "Nonce reuse can break confidentiality and authentication"],
    correctIndex: 3,
    explanation: "GCM requires nonce uniqueness for a fixed key. Reusing a nonce repeats counter-mode keystream material and also undermines the polynomial authentication construction, enabling serious attacks.",
    realWorld: "Protocol implementations construct or track nonces carefully because a key/nonce collision can compromise multiple protected messages.",
    hint: "GCM's security argument depends on unique nonces under each key.",
    reviewedAt: "2026-09-20",
  },
  {
    id: 60026, topic: "cryptography", difficulty: "hard",
    question: "What does forward secrecy protect if a server's long-term private key is compromised later?",
    options: ["Future updates from signature failures", "Earlier session keys from later reconstruction", "Expired certificates from replacement", "Stored passwords from offline guessing"],
    correctIndex: 1,
    explanation: "Forward-secret key exchange uses ephemeral secrets so later compromise of a long-term authentication key does not by itself reveal earlier session keys.",
    realWorld: "Modern TLS deployments use ephemeral Diffie-Hellman variants so recorded traffic is not automatically exposed by a later theft of the server's certificate private key.",
    hint: "The property limits how much historical traffic a future key compromise can expose.",
    reviewedAt: "2026-09-20",
  },
  {
    id: 60027, topic: "cryptography", difficulty: "hard",
    question: "For password storage, why is a memory-hard password hashing function preferable to a fast general-purpose hash?",
    options: ["It makes passwords reversible for recovery", "It removes the need for salts", "It makes each offline guess more resource-intensive", "It guarantees users choose high-entropy passwords"],
    correctIndex: 2,
    explanation: "Memory-hard password hashing deliberately raises the computational and memory cost of each guess, increasing an attacker's expense in large offline cracking attempts.",
    realWorld: "Password systems use dedicated functions such as Argon2id with unique salts rather than storing a fast SHA-family digest of each password.",
    hint: "Defenders want legitimate verification to be tolerable while making billions of guesses expensive.",
    reviewedAt: "2026-09-20",
  },
  {
    id: 60028, topic: "cryptography", difficulty: "sota",
    question: "In NIST's 2024 post-quantum signature standards, ML-DSA is derived from which submission?",
    options: ["Dilithium", "SPHINCS+", "Falcon", "Classic McEliece"],
    correctIndex: 0,
    explanation: "FIPS 204 specifies ML-DSA, a module-lattice-based digital signature standard derived from CRYSTALS-Dilithium.",
    realWorld: "Organizations planning post-quantum migrations can use ML-DSA as a standardized replacement for signature schemes threatened by sufficiently capable quantum computers.",
    hint: "The standardized name changed, but the underlying NIST competition submission is from the CRYSTALS family.",
    paper: {"title":"FIPS 204: Module-Lattice-Based Digital Signature Standard","url":"https://csrc.nist.gov/pubs/fips/204/final","venue":"NIST","year":2024},
    reviewedAt: "2026-09-20",
    factualAsOf: "2026-09-20",
  },
  {
    id: 60029, topic: "cryptography", difficulty: "sota",
    question: "NIST's SLH-DSA post-quantum signature standard is based primarily on:",
    options: ["Integer factorization", "Hash functions", "Elliptic-curve pairings", "Code-based encryption"],
    correctIndex: 1,
    explanation: "FIPS 205 specifies SLH-DSA, derived from SPHINCS+, whose security is built from hash-function constructions rather than lattice assumptions.",
    realWorld: "SLH-DSA gives deployers a standardized post-quantum signature option based on a different assumption family from ML-DSA.",
    hint: "Its lineage is SPHINCS+, a stateless hash-based signature scheme.",
    glossaryLinks: ["hash-function"],
    paper: {"title":"FIPS 205: Stateless Hash-Based Digital Signature Standard","url":"https://csrc.nist.gov/pubs/fips/205/final","venue":"NIST","year":2024},
    reviewedAt: "2026-09-20",
    factualAsOf: "2026-09-20",
  },
  {
    id: 60030, topic: "cryptography", difficulty: "sota",
    question: "NIST describes a hybrid key-establishment mode as combining:",
    options: ["A signature scheme with a password database", "A block cipher with a compression codec", "One nonce reused across multiple sessions", "Two or more cryptographic key-establishment schemes"],
    correctIndex: 3,
    explanation: "NIST defines hybrid key establishment as a composition of multiple key-establishment components. Such designs can combine classical and post-quantum mechanisms during migration.",
    realWorld: "Hybrid designs let protocols transition toward post-quantum key establishment while retaining an established component during the migration period.",
    hint: "The word hybrid refers to composing multiple key-establishment mechanisms.",
    paper: {"title":"Post-Quantum Cryptography FAQs — Transition and Migration","url":"https://csrc.nist.gov/Projects/Post-Quantum-Cryptography/faqs","venue":"NIST","year":2024},
    reviewedAt: "2026-09-20",
    factualAsOf: "2026-09-20",
  },
];
