import type { Question } from "../types";

export const computerScienceQuestions: Question[] = [
  // ── Algorithms ──────────────────────────────────────────────
  {
    id: 60001, topic: "algorithms", difficulty: "easy",
    conceptIds: ["asymptotic-algorithm-analysis"],
    question: "Binary search on a sorted array of n elements has worst-case time complexity:",
    options: ["O(n)","O(1)","O(log n)","O(n log n)"],
    correctIndex: 2,
    explanation: "Binary search compares against the middle element and discards roughly half of the remaining search interval after each comparison.",
    realWorld: "Binary search appears in sorted lookup tables, database internals, numerical root-finding variants, and standard-library search routines.",
    hint: "Ask how many times a set of n candidates can be halved before one candidate remains.",
    glossaryLinks: ["big-o"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60010, topic: "algorithms", difficulty: "easy",
    conceptIds: ["graph-algorithms"],
    question: "For an unweighted graph, which traversal finds shortest-path distances from one source in number of edges?",
    options: ["Breadth-first search","Depth-first search","Quicksort","Binary search"],
    correctIndex: 0,
    explanation: "Breadth-first search explores vertices in nondecreasing distance layers, so the first time a vertex is reached gives its shortest unweighted path length.",
    realWorld: "BFS is used for hop counts in networks, maze solving, social-network degrees of separation, and many graph preprocessing tasks.",
    hint: "The correct traversal visits all vertices one edge away before moving two edges away.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60011, topic: "algorithms", difficulty: "easy",
    conceptIds: ["asymptotic-algorithm-analysis"],
    question: "A sorting algorithm is stable if it:",
    options: ["Uses O(1) extra memory","Always runs in O(n log n)","Never compares equal keys","Keeps ties in input order"],
    correctIndex: 3,
    explanation: "Stability means records that compare equal retain their input order in the sorted output.",
    realWorld: "Stable sorting matters when data are sorted by multiple fields in successive passes, such as sorting records by last name after an earlier first-name sort.",
    hint: "Focus on what happens to two items whose sort keys are equal.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60002, topic: "algorithms", difficulty: "hard",
    conceptIds: ["asymptotic-algorithm-analysis"],
    question: "For T(n)=aT(n/b)+f(n), the Master Theorem case f(n)=Θ(n^(log_b a)) gives:",
    options: ["Θ(n^(log_b a))","Θ(n^(log_b a) log n)","Θ(f(n) log² n)","Θ(n log n) for every a and b"],
    correctIndex: 1,
    explanation: "When the recursive contribution and nonrecursive work have the same polynomial order, each recursion level contributes the same asymptotic work and there are Θ(log n) levels.",
    realWorld: "This case explains the Θ(n log n) running time of merge sort from T(n)=2T(n/2)+Θ(n).",
    hint: "Equal work per recursion level adds one logarithmic factor.",
    glossaryLinks: ["big-o"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60012, topic: "algorithms", difficulty: "hard",
    conceptIds: ["graph-algorithms"],
    question: "Why does standard Dijkstra's algorithm require nonnegative edge weights?",
    options: ["Negative edges make every graph disconnected","It can revisit infinitely many vertices even in a finite graph","A finalized distance can later decrease","Its priority queue cannot store negative numbers"],
    correctIndex: 2,
    explanation: "Dijkstra's greedy finalization is valid only when extending a path cannot reduce its length; a negative edge can invalidate an already finalized distance.",
    realWorld: "Routing and network optimization systems choose algorithms based partly on whether their cost model can contain negative weights.",
    hint: "Ask what property justifies declaring the currently smallest tentative distance final.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60013, topic: "algorithms", difficulty: "hard",
    conceptIds: ["asymptotic-algorithm-analysis"],
    question: "If a dynamic array doubles its capacity whenever full, the amortized cost of append is:",
    options: ["O(1)","O(log n)","O(n)","O(n log n)"],
    correctIndex: 0,
    explanation: "Most appends write one element, while occasional resizing copies many elements; spread over a long sequence of appends, the total copying work is linear.",
    realWorld: "Dynamic arrays in common language runtimes rely on geometric growth so appending remains cheap on average despite occasional reallocations.",
    hint: "Expensive resize operations are rare enough that their cost can be averaged across many cheap appends.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60003, topic: "algorithms", difficulty: "sota",
    conceptIds: ["fast-algorithm-frontiers","asymptotic-algorithm-analysis"],
    question: "As of September 2026, the best published preprint upper bound on the square matrix-multiplication exponent ω is approximately:",
    options: ["ω < 2.50","ω < 2.372","ω = 2 exactly","ω < 2.371177"],
    correctIndex: 3,
    explanation: "A 2026 optimization of combination-loss analysis reports ω < 2.371177, improving the previous ω < 2.371339 bound.",
    realWorld: "The matrix-multiplication exponent affects asymptotic bounds for many linear-algebra and graph problems even though practical implementations often use different crossover strategies.",
    hint: "The frontier exponent is above the information-theoretic floor of 2, but below 2.372.",
    glossaryLinks: ["big-o"],
    paper: {"title":"Improving the matrix multiplication exponent with modern optimization and AlphaEvolve","url":"https://arxiv.org/abs/2608.16884","venue":"arXiv","year":2026},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 60014, topic: "algorithms", difficulty: "sota",
    conceptIds: ["fast-algorithm-frontiers","asymptotic-algorithm-analysis"],
    question: "Harvey and van der Hoeven proved that multiplying two n-bit integers can be done in:",
    options: ["O(n²) bit operations","O(n log n) bit operations","O(n log² n) comparisons only","O(log n) bit operations"],
    correctIndex: 1,
    explanation: "Their algorithm achieves O(n log n) bit complexity in the multitape Turing-machine model, resolving the asymptotic conjecture associated with Schönhage and Strassen.",
    realWorld: "Fast integer multiplication underlies arbitrary-precision arithmetic and influences the complexity of higher-level number-theoretic computations.",
    hint: "The result reaches linear time up to a single logarithmic factor.",
    glossaryLinks: ["big-o"],
    paper: {"title":"Integer multiplication in time O(n log n)","url":"https://annals.math.princeton.edu/2021/193-2/p04","venue":"Annals of Mathematics","year":2021},
    reviewedAt: "2026-09-19",
  },
  {
    id: 60015, topic: "algorithms", difficulty: "sota",
    conceptIds: ["graph-algorithms","fast-algorithm-frontiers"],
    question: "A 2022 breakthrough for exact directed maximum flow with polynomially bounded integral data achieved running time:",
    options: ["O(m²)","O(m log² m) for every graph model","m^(1+o(1))","O(2^m)"],
    correctIndex: 2,
    explanation: "Chen and collaborators gave exact maximum-flow and minimum-cost-flow algorithms running in m^(1+o(1)) time under polynomially bounded integral demands, costs, and capacities.",
    realWorld: "Near-linear flow algorithms improve a primitive used throughout routing, matching reductions, scheduling, transport, and optimization.",
    hint: "The breakthrough is described as almost-linear in the number of edges m.",
    glossaryLinks: ["big-o"],
    paper: {"title":"Maximum Flow and Minimum-Cost Flow in Almost-Linear Time","url":"https://arxiv.org/abs/2203.00671","venue":"arXiv","year":2022},
    reviewedAt: "2026-09-19",
  },

  // ── Machine Learning ──────────────────────────────────────────────
  {
    id: 60004, topic: "machine-learning", difficulty: "easy",
    conceptIds: ["supervised-learning-generalization"],
    question: "In supervised learning, training examples normally contain:",
    options: ["Only unlabeled inputs","Inputs paired with target labels or values","Only rewards from an environment","Random parameters without data"],
    correctIndex: 1,
    explanation: "Supervised learning fits a predictive mapping from inputs to known targets supplied in the training data.",
    realWorld: "Classification, regression, spam filtering, and many diagnostic models are trained from labeled examples.",
    hint: "The supervision is the target answer paired with each training input.",
    glossaryLinks: ["overfitting","gradient-descent"],
    formulaLinks: ["Gradient Descent Update Rule"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60016, topic: "machine-learning", difficulty: "easy",
    conceptIds: ["supervised-learning-generalization"],
    question: "Overfitting occurs when a model:",
    options: ["Fits training data but generalizes poorly","Has too few parameters to fit even the training set","Uses a validation set","Normalizes its input features"],
    correctIndex: 0,
    explanation: "An overfit model captures idiosyncrasies or noise in the training sample that do not generalize to new examples.",
    realWorld: "Regularization, more representative data, early stopping, and careful validation are common tools for controlling overfitting.",
    hint: "Compare training performance with performance on data the model did not train on.",
    glossaryLinks: ["overfitting"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60017, topic: "machine-learning", difficulty: "easy",
    conceptIds: ["supervised-learning-generalization"],
    question: "The main purpose of a validation set is to:",
    options: ["Train every model parameter directly","Report the final unbiased test score","Replace all training data","Tune models without using the test set"],
    correctIndex: 3,
    explanation: "A validation set supports model and hyperparameter selection while preserving the test set for a final evaluation that was not used to guide choices.",
    realWorld: "Separating training, validation, and test roles reduces optimistic evaluation caused by repeatedly tuning against the final benchmark.",
    hint: "Use one held-out split for decisions and reserve another for the final check.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60005, topic: "machine-learning", difficulty: "hard",
    conceptIds: ["supervised-learning-generalization"],
    question: "For squared-error regression, the classic bias-variance decomposition contains:",
    options: ["Bias + variance only","Bias × variance","Bias² + variance + noise","Training loss + test loss"],
    correctIndex: 2,
    explanation: "Expected squared prediction error decomposes into squared bias, estimator variance, and irreducible noise under the standard setup.",
    realWorld: "The decomposition explains why increasing model flexibility can reduce systematic error while increasing sensitivity to the sampled training data.",
    hint: "One term is squared, one measures sensitivity to datasets, and one cannot be removed by the predictor.",
    glossaryLinks: ["overfitting"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60018, topic: "machine-learning", difficulty: "hard",
    conceptIds: ["neural-network-training"],
    question: "Backpropagation computes gradients through a neural network primarily by applying:",
    options: ["The chain rule","A breadth-first search over labels","Bayes' theorem once per layer","Principal-component analysis to every weight matrix"],
    correctIndex: 0,
    explanation: "Backpropagation efficiently applies the chain rule to reuse intermediate derivatives as gradients are propagated backward through a computation graph.",
    realWorld: "Automatic-differentiation systems in modern ML frameworks implement this principle to train large neural networks.",
    hint: "The derivative of a composition is built from derivatives of its component functions.",
    glossaryLinks: ["backpropagation","gradient-descent"],
    reviewedAt: "2026-09-19",
  },
  {
    id: 60019, topic: "machine-learning", difficulty: "hard",
    conceptIds: ["neural-network-training","supervised-learning-generalization"],
    question: "Adding an L2 penalty λ||w||² to a training objective directly encourages:",
    options: ["Exact zero-one predictions","Larger weight magnitudes","A larger training dataset","Smaller weight magnitudes"],
    correctIndex: 3,
    explanation: "L2 regularization penalizes large parameter norms, typically shrinking weights and reducing sensitivity to individual training examples.",
    realWorld: "Weight decay is a common regularization mechanism, although its exact relationship to an L2 penalty depends on the optimizer implementation.",
    hint: "The penalty grows as the squared size of the parameter vector grows.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 60006, topic: "machine-learning", difficulty: "sota",
    conceptIds: ["attention-transformers"],
    question: "Scaled dot-product attention in the original Transformer computes:",
    options: ["softmax(QKᵀ/√d_k)V","sigmoid(QKᵀ)V","QKᵀV/d_k without normalization","ReLU(Q+K+V)"],
    correctIndex: 0,
    explanation: "The Transformer scales query-key dot products by the square root of key dimension before softmax, then uses the resulting weights to combine values.",
    realWorld: "This attention primitive became a foundation for modern sequence models and large language models.",
    hint: "The scaling factor keeps large dot products from pushing softmax too strongly toward saturation.",
    glossaryLinks: ["transformer","backpropagation"],
    paper: {"title":"Attention Is All You Need","url":"https://arxiv.org/abs/1706.03762","venue":"NeurIPS","year":2017},
    reviewedAt: "2026-09-19",
  },
  {
    id: 60020, topic: "machine-learning", difficulty: "sota",
    conceptIds: ["attention-transformers"],
    question: "FlashAttention accelerates exact attention mainly by:",
    options: ["Replacing attention with a recurrent network","Quantizing every activation to one bit","IO-aware tiling across GPU memory","Dropping softmax from the attention calculation"],
    correctIndex: 2,
    explanation: "FlashAttention is an IO-aware exact attention algorithm that tiles the computation so fewer intermediate values move between high-bandwidth memory and faster on-chip memory.",
    realWorld: "Reducing memory traffic can improve Transformer training and inference speed while preserving exact attention semantics.",
    hint: "The key optimization is memory movement, not an approximation of the attention formula.",
    glossaryLinks: ["transformer"],
    paper: {"title":"FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness","url":"https://arxiv.org/abs/2205.14135","venue":"NeurIPS","year":2022},
    reviewedAt: "2026-09-19",
  },
  {
    id: 60021, topic: "machine-learning", difficulty: "sota",
    conceptIds: ["neural-network-training"],
    question: "LoRA adapts a large pretrained model by:",
    options: ["Retraining every base-model parameter","Freezing base weights and training low-rank update matrices","Replacing the model with nearest-neighbour search","Adding labels to the pretraining corpus only"],
    correctIndex: 1,
    explanation: "Low-Rank Adaptation keeps pretrained weights frozen and learns compact low-rank matrices whose product represents a task-specific weight update.",
    realWorld: "Parameter-efficient adaptation reduces the number of trainable parameters and can make maintaining many specialized model variants substantially cheaper.",
    hint: "The method changes a small low-rank update rather than the full pretrained weight matrix.",
    paper: {"title":"LoRA: Low-Rank Adaptation of Large Language Models","url":"https://arxiv.org/abs/2106.09685","venue":"ICLR","year":2022},
    reviewedAt: "2026-09-19",
  },

  // ── Cryptography ──────────────────────────────────────────────
  {
    id: 60007, topic: "cryptography", difficulty: "easy",
    question: "RSA encryption relies on the difficulty of:",
    options: ["Factoring large semiprime numbers","Computing discrete logarithms","Solving linear equations","Finding hash collisions"],
    correctIndex: 0,
    explanation: "RSA security assumes that factoring the product of two large primes $n = pq$ is computationally infeasible.",
    realWorld: "RSA secures HTTPS connections, digital signatures, and secure email worldwide.",
    hint: "Multiplying two primes is easy; reversing it is believed to be hard.",
    symbolLinks: {"n":"nu","p":"pi","q":"capital-psi"},
    glossaryLinks: ["hash-function"],
  },
  {
    id: 60008, topic: "cryptography", difficulty: "hard",
    question: "A zero-knowledge proof allows a prover to:",
    options: ["Convince a verifier of a statement's truth without revealing any information beyond validity","Encrypt data using a shared secret","Generate a digital signature","Compress data losslessly"],
    correctIndex: 0,
    explanation: "Zero-knowledge proofs enable authentication and verification without revealing the underlying secret — the verifier learns nothing except that the statement is true.",
    realWorld: "Used in blockchain privacy (Zcash), anonymous credentials, and secure voting systems.",
    hint: "The verifier becomes convinced but gains zero additional knowledge.",
  },
  {
    id: 60009, topic: "cryptography", difficulty: "sota",
    question: "Post-quantum cryptography's ML-KEM (Kyber) standard is based on:",
    options: ["Module Learning with Errors (MLWE) lattice problem","Elliptic curve discrete log problem","Integer factorization","Supersingular isogenies"],
    correctIndex: 0,
    explanation: "NIST standardized ML-KEM (formerly Kyber) in 2024, which relies on the hardness of the Module-LWE problem — believed to be secure against quantum computers.",
    realWorld: "Google Chrome and Signal already use ML-KEM for quantum-resistant key exchange.",
    hint: "Lattice-based cryptography adds structured 'noise' to linear algebra problems.",
    symbolLinks: {"A":"capital-alpha","s":"sigma","e":"epsilon"},
    glossaryLinks: ["hash-function"],
    formulaLinks: ["Shannon Entropy"],
  },
];
