import type { Question } from '../types';

export const computerScienceQuestions: Question[] = [
  // ── Algorithms ──────────────────────────────────────────────
  {
    id: 60001, topic: 'algorithms', difficulty: 'easy',
    question: 'The time complexity of binary search on a sorted array of $n$ elements is:',
    options: ['$O(\\log n)$', '$O(n)$', '$O(n \\log n)$', '$O(1)$'],
    correctIndex: 0,
    explanation: 'Binary search halves the search space at each step, giving $O(\\log n)$ comparisons.<br><br><strong>🔤 Variable Definitions:</strong><br>$n$ = array size (total elements)<br>$O(\\log n)$ = logarithmic time (base-2 log)',
    realWorld: 'Used in database indexing, spell checkers, and searching sorted datasets.',
    hint: 'Each comparison eliminates half the remaining elements. <strong>🎯 Pro Tip:</strong> Imagine a phone book—find "Smith" by opening to middle, then deciding left/right. Always halves!',
  },
  {
    id: 60002, topic: 'algorithms', difficulty: 'hard',
    question: 'The Master Theorem solves recurrences of the form $T(n) = aT(n/b) + f(n)$. If $f(n) = \\Theta(n^{\\log_b a})$, then $T(n) = $:',
    options: ['$\\Theta(n^{\\log_b a} \\log n)$', '$\\Theta(n^{\\log_b a})$', '$\\Theta(f(n))$', '$\\Theta(n \\log n)$'],
    correctIndex: 0,
    explanation: "This is Case 2 of the Master Theorem: when $f(n)$ grows at the same rate as $n^{\\log_b a}$, an extra $\\log n$ factor appears.<br><br><strong>🔤 Variable Definitions:</strong><br>$T(n)$ = time complexity<br>$a$ = #subproblems<br>$b$ = size reduction factor<br>$f(n)$ = work outside recursion<br>$\\log_b a$ = critical exponent",
    realWorld: 'The Master Theorem characterizes the complexity of divide-and-conquer algorithms like merge sort ($T(n) = 2T(n/2) + O(n)$).',
    hint: 'Case 2: the work at each level is equal, so we multiply by the number of levels ($\\log_b n$). <strong>⚡ Merge Sort Example:</strong> $a=2,b=2,f(n)=n$ → $\\log_2 2 = 1$, so Case 2!',
  },
  {
    id: 60003, topic: 'algorithms', difficulty: 'sota',
    question: 'The fastest known algorithm for matrix multiplication has complexity approximately:',
    options: ['$O(n^{2.371})$ (Alman-Williams)', '$O(n^3)$', '$O(n^2)$', '$O(n^{2.5})$'],
    correctIndex: 0,
    explanation: 'The current best bound for matrix multiplication is $O(n^{2.3716})$ by Alman and Williams (2024), improving on the Coppersmith-Winograd line of research.<br><br><strong>🔤 Variable Definitions:</strong><br>$n$ = matrix dimension (n×n)<br>$\\omega$ = matrix mult. exponent (goal: $\\omega=2$)<br>Current: $\\omega \\approx 2.3716$',
    realWorld: 'Faster matrix multiplication directly speeds up graph algorithms, scientific simulation, and machine learning training.',
    hint: 'The exponent $\\omega$ has been slowly decreasing from Strassen\\'s 2.807 (1969) → 2.371 (2024). <strong>🚀 Impact:</strong> Every 0.01 drop = 10% faster neural nets!',
  },
  // ── Machine Learning ──────────────────────────────────────
  {
    id: 60004, topic: 'machine-learning', difficulty: 'easy',
    question: 'In supervised learning, the model learns from:',
    options: ['Labeled input-output pairs', 'Unlabeled data only', 'Reward signals from an environment', 'Random initialization only'],
    correctIndex: 0,
    explanation: 'Supervised learning uses labeled training data — each input has a known target output that the model learns to predict.',
    realWorld: 'Email spam filters, image classifiers, and medical diagnosis systems all use supervised learning.',
    hint: 'The "supervisor" provides the correct answers during training. <strong>📊 Example:</strong> Photos labeled "cat" vs "dog" → model learns cat features.',
  },
  {
    id: 60005, topic: 'machine-learning', difficulty: 'hard',
    question: 'The bias-variance tradeoff states that a model\\'s expected generalization error equals:',
    options: ['$\\text{Bias}^2 + \\text{Variance} + \\text{Irreducible noise}$', '$\\text{Bias} + \\text{Variance}$', '$\\text{Bias} \\times \\text{Variance}$', '$\\text{Bias}^2 - \\text{Variance}$'],
    correctIndex: 0,
    explanation: 'The expected squared error decomposes into squared bias (systematic error), variance (sensitivity to training set), and irreducible noise.<br><br><strong>🔤 Variable Definitions:</strong><br>$\\text{Bias}^2$ = (average prediction - true value)²<br>$\\text{Variance}$ = E[(pred₁ - pred₂)²]<br>Noise = inherent randomness',
    realWorld: 'This tradeoff guides model selection — simple models have high bias, complex models have high variance.',
    hint: 'Think of throwing darts: bias is how far the center is from the target, variance is how spread out the darts are. <strong>🎯 Goldilocks:</strong> "Just right" complexity!',
  },
  {
    id: 60006, topic: 'machine-learning', difficulty: 'sota',
    question: 'In the transformer architecture, the attention mechanism computes:',
    options: ['$\\text{softmax}(QK^T / \\sqrt{d_k})V$', '$\\text{sigmoid}(QK^T)V$', '$QK^TV / d_k$', '$\\text{ReLU}(QK^T)V$'],
    correctIndex: 0,
    explanation: 'Scaled dot-product attention divides by $\\sqrt{d_k}$ to prevent softmax saturation, then applies the softmax to get attention weights over values $V$.<br><br><strong>🔤 Variable Definitions:</strong><br>$Q$ = Query matrix<br>$K$ = Key matrix<br>$V$ = Value matrix<br>$d_k$ = key dimension',
    realWorld: 'This mechanism powers GPT, BERT, and all modern large language models.',
    hint: 'The scaling factor $\\sqrt{d_k}$ prevents the dot products from growing too large. <strong>🧠 Intuition:</strong> "How much should I pay attention to word #5 when reading word #3?"',
  },
  // ── Cryptography ──────────────────────────────────────────
  {
    id: 60007, topic: 'cryptography', difficulty: 'easy',
    question: 'RSA encryption relies on the difficulty of:',
    options: ['Factoring large semiprime numbers', 'Computing discrete logarithms', 'Solving linear equations', 'Finding hash collisions'],
    correctIndex: 0,
    explanation: 'RSA security assumes that factoring the product of two large primes $n = pq$ is computationally infeasible.<br><br><strong>🔤 Variable Definitions:</strong><br>$n = p \\times q$ (semiprime)<br>$p,q$ = large primes (~1024+ bits)<br>public key = $(n,e)$; private = $d$',
    realWorld: 'RSA secures HTTPS connections, digital signatures, and secure email worldwide.',
    hint: 'Multiplying two primes is easy; reversing it is believed to be hard. <strong>🔒 Math:</strong> $n=3233=61×53$ (easy); $n=2^{2048}+...$ (impossible).',
  },
  {
    id: 60008, topic: 'cryptography', difficulty: 'hard',
    question: 'A zero-knowledge proof allows a prover to:',
    options: ['Convince a verifier of a statement\\'s truth without revealing any information beyond validity', 'Encrypt data using a shared secret', 'Generate a digital signature', 'Compress data losslessly'],
    correctIndex: 0,
    explanation: 'Zero-knowledge proofs enable authentication and verification without revealing the underlying secret — the verifier learns nothing except that the statement is true.',
    realWorld: 'Used in blockchain privacy (Zcash), anonymous credentials, and secure voting systems.',
    hint: 'The verifier becomes convinced but gains zero additional knowledge. <strong>🎭 Cave Analogy:</strong> Prove you know cave password without revealing it!',
  },
  {
    id: 60009, topic: 'cryptography', difficulty: 'sota',
    question: 'Post-quantum cryptography\\'s ML-KEM (Kyber) standard is based on:',
    options: ['Module Learning with Errors (MLWE) lattice problem', 'Elliptic curve discrete log problem', 'Integer factorization', 'Supersingular isogenies'],
    correctIndex: 0,
    explanation: 'NIST standardized ML-KEM (formerly Kyber) in 2024, which relies on the hardness of the Module-LWE problem — believed to be secure against quantum computers.<br><br><strong>🔤 Variable Definitions:</strong><br>MLWE = Module Learning With Errors<br>$As+b+e$ problem (noisy linear algebra)<br>Quantum-resistant!',
    realWorld: 'Google Chrome and Signal already use ML-KEM for quantum-resistant key exchange.',
    hint: 'Lattice-based cryptography adds structured "noise" to linear algebra problems. <strong>🛡️ Why Quantum-Safe:</strong> Shor\\'s algorithm breaks RSA/EC; lattices survive Grover.',
  },
];
