import type { Question } from '../types';

export const oceanographyQuestions: Question[] = [
  {
    id: 40701, topic: 'oceanography', difficulty: 'easy',
    question: 'The thermohaline circulation (global "conveyor belt") is driven by:',
    options: [
      'Differences in water density caused by temperature (thermo) and salinity (haline) — cold, salty water sinks in the North Atlantic and flows south along the ocean floor',
      'Wind alone pushing water around the globe',
      'The Moon\'s gravitational pull creating permanent currents',
      'Volcanic heating at mid-ocean ridges',
    ],
    correctIndex: 0,
    explanation: 'Cold, salty water in the North Atlantic is dense enough to sink to the ocean floor, driving the AMOC. This deep water flows south, surfaces in the Southern Ocean, and returns north — a cycle taking ~1,000 years.',
    realWorld: 'The AMOC transports ~1.3 petawatts of heat northward, keeping Europe ~5°C warmer than equivalent latitudes. Its potential weakening is a major climate concern.',
    hint: 'Density differences from temperature and salt content drive a global-scale circulation.',
  },
  {
    id: 40704, topic: 'oceanography', difficulty: 'easy',
    question: 'Ocean tides are primarily caused by:',
    options: [
      'The gravitational pull of the Moon (and Sun) creating two tidal bulges — one facing the Moon and one on the opposite side due to differential gravitational force across Earth\'s diameter',
      'Wind pushing water toward the shore',
      'Earth\'s rotation alone without any external forces',
      'Underwater volcanic activity',
    ],
    correctIndex: 0,
    explanation: 'The Moon\'s gravity is stronger on the near side of Earth than the far side. This differential creates two bulges: one pulled toward the Moon, one "left behind" on the opposite side. As Earth rotates, coastlines pass through these bulges → two high tides daily.',
    realWorld: 'Tidal power (Bay of Fundy has 16m tides) generates clean energy. Tidal predictions are essential for shipping, fishing, and coastal engineering. Spring tides (Sun+Moon aligned) cause flooding risks.',
    hint: 'The Moon pulls water toward it on one side, and Earth "falls away" from water on the other side.',
  },
  {
    id: 40702, topic: 'oceanography', difficulty: 'hard',
    question: 'Ocean acidification threatens marine ecosystems because:',
    options: [
      'Absorbed CO₂ reacts with seawater to form carbonic acid ($\\text{CO}_2 + \\text{H}_2\\text{O} \\rightarrow \\text{H}_2\\text{CO}_3$), lowering pH and reducing carbonate ions needed for shell formation',
      'The ocean is becoming more alkaline over time',
      'Fish cannot survive in water with any dissolved CO₂',
      'Acidification only affects freshwater lakes',
    ],
    correctIndex: 0,
    explanation: 'The ocean has absorbed ~30% of anthropogenic CO₂, reducing surface pH from 8.2 to 8.1 (a 26% increase in H⁺ concentration).',
    realWorld: 'Coral reefs support 25% of marine species and $375B in annual economic activity. At current rates, most tropical reefs will experience dissolution conditions by 2050.',
    hint: 'CO₂ dissolves in water and becomes an acid — bad news for anything with a calcium carbonate shell.',
  },
  {
    id: 40705, topic: 'oceanography', difficulty: 'hard',
    question: 'Ekman transport causes surface water to move at 90° to the wind direction because:',
    options: [
      'The Coriolis effect deflects each layer of water slightly from the one above, creating a spiral — net transport is perpendicular to the wind (right in Northern Hemisphere)',
      'Water always flows perpendicular to any force',
      'Ocean currents ignore wind direction entirely',
      'The continents deflect all water at right angles',
    ],
    correctIndex: 0,
    explanation: 'Wind drags the surface layer, which drags the layer below. Coriolis deflects each layer further from the wind direction, creating the Ekman spiral. The depth-integrated transport is 90° to the wind — this drives coastal upwelling when wind blows parallel to the coast.',
    realWorld: 'Ekman transport drives upwelling along the California, Peru, and West African coasts — bringing nutrient-rich deep water to the surface, supporting the world\'s most productive fisheries.',
    hint: 'Wind blows north, water moves east (in the Northern Hemisphere) — the Coriolis effect twists each layer.',
  },
  {
    id: 40703, topic: 'oceanography', difficulty: 'sota',
    question: 'Autonomous underwater vehicles (AUVs) equipped with AI are revolutionizing oceanography by:',
    options: [
      'Performing adaptive sampling — using onboard ML to detect anomalies in real-time and autonomously redirect to collect high-value data',
      'Simply following pre-programmed paths without intelligence',
      'Replacing all satellite ocean observation',
      'Only operating in shallow coastal waters',
    ],
    correctIndex: 0,
    explanation: 'Modern AUVs use onboard edge ML to identify features of interest and adapt their sampling strategy in real-time, maximizing scientific value per mission.',
    realWorld: 'The Argo network provides 400+ profiles per day of ocean temperature and salinity to 2,000m depth. AI-equipped AUVs discovered deep-sea hydrothermal vents and mapped under-ice Arctic conditions.',
    hint: 'Smart robots that decide where to look based on what they\'re finding.',
  },
  {
    id: 40706, topic: 'oceanography', difficulty: 'sota',
    question: 'Deep-sea mining of polymetallic nodules is controversial because:',
    options: [
      'Nodules contain critical minerals (cobalt, nickel, manganese) for batteries, but harvesting them would destroy poorly understood abyssal ecosystems that take millions of years to form',
      'Nodules have no economic value',
      'Deep-sea ecosystems recover within months of disturbance',
      'Mining technology does not yet exist',
    ],
    correctIndex: 0,
    explanation: 'Polymetallic nodules in the Clarion-Clipperton Zone contain more cobalt, nickel, and manganese than all land reserves combined. But abyssal plains host unique biodiversity — sediment plumes from mining could affect ecosystems across vast areas.',
    realWorld: 'The ISA (International Seabed Authority) is debating regulations. Companies like The Metals Company want to mine; scientists warn of irreversible damage. The EV battery boom makes this a trillion-dollar question.',
    hint: 'The minerals we need for green energy are on the ocean floor — but getting them could destroy ecosystems we barely understand.',
  },
];
