import type { Question } from '../types';

export const meteorologyQuestions: Question[] = [
  {
    id: 40301, topic: "meteorology", difficulty: "easy",
    question: "In large-scale Northern Hemisphere flow, the Coriolis effect deflects moving air primarily:",
    options: ["To the right of its motion","To the left of its motion","Straight upward","Toward the equator regardless of motion"],
    correctIndex: 0,
    explanation: "Earth's rotation causes moving air to be deflected to the right in the Northern Hemisphere and to the left in the Southern Hemisphere.",
    realWorld: "Coriolis deflection helps organize large-scale winds, jet streams, and rotating weather systems.",
    hint: "The sign of the deflection reverses between hemispheres.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40304, topic: "meteorology", difficulty: "easy",
    question: "A weather front is a boundary separating:",
    options: ["Two ocean currents only","Contrasting air masses","The troposphere and stratosphere","Day and night sides of Earth"],
    correctIndex: 1,
    explanation: "Fronts mark boundaries between air masses; lifting near those boundaries often produces clouds, precipitation, and sharp wind or temperature changes.",
    realWorld: "Synoptic weather maps track fronts because they organize many mid-latitude storms.",
    hint: "Think of a boundary between distinct air masses.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40306, topic: "meteorology", difficulty: "easy",
    question: "When air temperature falls to its dew point while water vapour content stays nearly constant, the relative humidity approaches:",
    options: ["0%","25%","100%","50%"],
    correctIndex: 2,
    explanation: "At the dew point, the air is saturated with respect to liquid water, so relative humidity is approximately 100%.",
    realWorld: "Near-surface cooling to the dew point can lead to fog, dew, or cloud formation if condensation nuclei are available.",
    hint: "The dew point is the temperature at which saturation is reached.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40302, topic: "meteorology", difficulty: "hard",
    question: "Numerical weather prediction models integrate equations representing atmospheric:",
    options: ["Only ideal-gas thermodynamics without fluid motion","Quantum mechanics of individual atmospheric molecules","Plate-motion equations coupled to tides","Momentum, continuity, heat, and moisture"],
    correctIndex: 3,
    explanation: "NWP solves discretized fluid-dynamical and thermodynamic equations on a rotating Earth, together with parameterizations for unresolved processes.",
    realWorld: "Modern forecasts combine these equations with vast observing systems and data assimilation.",
    hint: "The atmosphere is treated as a rotating, stratified, moist fluid.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40305, topic: "meteorology", difficulty: "hard",
    question: "Lorenz's classic chaos result showed that even deterministic atmospheric models can have:",
    options: ["Sensitivity to initial conditions","Perfect predictability at arbitrary lead time","No nonlinear behaviour","Only periodic solutions"],
    correctIndex: 0,
    explanation: "Small differences in initial conditions can grow rapidly in nonlinear systems, imposing a practical horizon on detailed deterministic weather prediction.",
    realWorld: "Ensemble forecasting samples uncertainty in initial conditions and model evolution rather than pretending one trajectory is exact.",
    hint: "The famous butterfly effect is about how tiny initial differences can grow.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40307, topic: "meteorology", difficulty: "hard",
    question: "In idealized large-scale geostrophic balance, the horizontal pressure-gradient force is balanced by:",
    options: ["Surface friction only","The Coriolis force","Buoyancy only","Latent heating only"],
    correctIndex: 1,
    explanation: "Away from strong friction and rapid acceleration, large-scale winds can approach geostrophic balance between pressure-gradient and Coriolis forces.",
    realWorld: "Geostrophic reasoning explains why upper-level winds often flow approximately parallel to height or pressure contours.",
    hint: "The balancing force arises from Earth's rotation.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40303, topic: "meteorology", difficulty: "sota",
    question: "GraphCast demonstrated medium-range global weather prediction using a machine-learning system based largely on:",
    options: ["A hand-solved set of weather maps","Quantum annealing of each forecast","A graph neural network trained on reanalysis data","Only surface thermometer readings"],
    correctIndex: 2,
    explanation: "GraphCast learns atmospheric evolution from reanalysis data using a graph-based neural architecture and achieved strong deterministic medium-range forecast skill in published evaluation.",
    realWorld: "Data-driven global forecasting showed that learned models can complement traditional numerical weather prediction while running far faster at inference.",
    hint: "Its architecture represents the globe as an interconnected graph rather than a simple image grid.",
    paper: {"title":"Learning skillful medium-range global weather forecasting","url":"https://www.science.org/doi/10.1126/science.adi2336","venue":"Science","year":2023},
    reviewedAt: "2026-09-19",
  },
  {
    id: 40308, topic: "meteorology", difficulty: "sota",
    question: "GenCast differs importantly from a single deterministic forecast because it is designed to:",
    options: ["Return only one fixed future trajectory","Forecast climate centuries ahead from one initialization","Ignore uncertainty by averaging all weather states","Probabilistic ensembles of plausible futures"],
    correctIndex: 3,
    explanation: "GenCast is a diffusion-based machine-learning weather model that generates an ensemble of possible future states, enabling probabilistic medium-range forecasting.",
    realWorld: "Probabilistic ensembles are valuable for risk decisions because they estimate uncertainty and the range of plausible outcomes, especially for high-impact events.",
    hint: "The model produces many possible futures rather than one path.",
    paper: {"title":"Probabilistic weather forecasting with machine learning","url":"https://www.nature.com/articles/s41586-024-08252-9","venue":"Nature","year":2025},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 40309, topic: "meteorology", difficulty: "sota",
    question: "Deep generative radar nowcasting is especially suited to forecasting:",
    options: ["Very-short-range precipitation fields","Plate motion over millions of years","Seasonal ocean salinity only","Solar flares from stellar spectra"],
    correctIndex: 0,
    explanation: "Generative nowcasting learns a conditional distribution of future radar precipitation fields, allowing multiple plausible high-resolution rain evolutions to be sampled.",
    realWorld: "Probabilistic short-range precipitation forecasts support flood warning, aviation, emergency response, and other decisions sensitive to localized heavy rain.",
    hint: "Nowcasting refers to the very short-range evolution of current weather.",
    paper: {"title":"Skilful precipitation nowcasting using deep generative models of radar","url":"https://www.nature.com/articles/s41586-021-03854-z","venue":"Nature","year":2021},
    reviewedAt: "2026-09-19",
  },
];
