import type { Question } from '../types';

export const easyQuestions: Question[] = [
  {
    id: 6,
    topic: 'calculus',
    conceptIds: ['gradient', 'derivatives'],
    difficulty: 'easy',
    question: 'What does $\\nabla f(\\mathbf{x})$ represent?',
    options: ['The Hessian matrix', 'The gradient vector', 'The Jacobian matrix', 'The Laplacian'],
    correctIndex: 1,
    explanation: 'The gradient $\\nabla f(\\mathbf{x})$ is the vector of partial derivatives. When the gradient is nonzero, it points in the direction of greatest local increase, and its magnitude gives that maximum directional rate of change.',
    realWorld: 'Gradient-based optimization uses this local first-order information to choose parameter-update directions in models such as neural networks.',
    hint: 'It collects the partial derivatives into one vector; its direction and magnitude describe the steepest local increase.',
  },
  {
    id: 7,
    topic: 'calculus',
    conceptIds: ['derivatives'],
    difficulty: 'easy',
    question: 'What is $\\frac{d}{dx}[x^n]$?',
    options: ['$x^{n+1}/(n+1)$', '$nx^{n-1}$', '$n!$', '$\\ln(x^n)$'],
    correctIndex: 1,
    explanation: 'The power rule: differentiate $x^n$ to get $nx^{n-1}$. Fundamental to all of calculus.',
    realWorld: 'Power rule appears in polynomial regression and Taylor series approximations.',
    hint: 'Bring the exponent down and reduce it by one.',
  },
  {
    id: 31,
    topic: 'calculus',
    conceptIds: ['elementary-derivatives', 'derivatives'],
    difficulty: 'easy',
    question: 'What is $\\frac{d}{dx}[e^x]$?',
    options: ['$xe^{x-1}$', '$e^x$', '$\\ln(x)$', '$e^{x+1}$'],
    correctIndex: 1,
    explanation: 'The exponential function satisfies $\\frac{d}{dx}e^x=e^x$. More generally, the differentiable solutions of $f\'=f$ are $f(x)=Ce^x$; the condition $f(0)=1$ selects $e^x$ itself.',
    realWorld: 'This self-reproducing derivative makes exponentials natural solutions of continuous growth and decay equations, from compound growth to first-order dynamical models.',
    hint: 'Differentiating this exponential leaves the same function.',
  },
  {
    id: 62,
    topic: 'calculus',
    conceptIds: ['elementary-derivatives', 'derivatives'],
    difficulty: 'easy',
    question: 'What is $\\frac{d}{dx}[\\sin(x)]$?',
    options: ['$-\\cos(x)$', '$\\cos(x)$', '$\\sin(x)$', '$\\tan(x)$'],
    correctIndex: 1,
    explanation: 'The derivative of $\\sin(x)$ is $\\cos(x)$. This follows from the limit definition of the derivative.',
    realWorld: 'Sinusoidal functions and their derivatives model oscillations in signal processing and physics.',
    hint: 'The sine and cosine functions are derivatives of each other (with sign changes).',
  },
  {
    id: 63,
    topic: 'calculus',
    conceptIds: ['elementary-derivatives', 'derivatives'],
    difficulty: 'easy',
    question: 'What is $\\frac{d}{dx}[\\ln(x)]$?',
    options: ['$e^x$', '$\\frac{1}{x}$', '$x\\ln(x)$', '$\\ln(x)/x$'],
    correctIndex: 1,
    explanation: 'For the real-valued natural logarithm, $\\frac{d}{dx}\\ln(x)=1/x$ on its domain $x>0$. The domain condition matters: the real function $\\ln(x)$ is not defined for $x\\le 0$.',
    realWorld: 'Log-likelihood derivatives use this rule extensively in statistical learning.',
    hint: 'The natural log has a beautifully simple derivative — just a reciprocal.',
  },
  {
    id: 64,
    topic: 'calculus',
    conceptIds: ['antiderivatives', 'derivatives'],
    difficulty: 'easy',
    question: 'The antiderivative (indefinite integral) of $2x$ is:',
    options: ['$2$', '$x^2 + C$', '$x^2$', '$2x^2 + C$'],
    correctIndex: 1,
    explanation: '$\\int 2x\\,dx = x^2 + C$. The constant $C$ accounts for the family of functions with the same derivative.',
    realWorld: 'Integration is used to compute areas, volumes, and cumulative distributions.',
    hint: 'Reverse the power rule and don\'t forget the constant.',
  },
  {
    id: 65,
    topic: 'calculus',
    conceptIds: ['continuity'],
    difficulty: 'easy',
    question: 'A function is continuous at $x = a$ if:',
    options: ['It has a derivative at $a$', '$\\lim_{x \\to a} f(x) = f(a)$', 'It is differentiable everywhere', '$f(a) = 0$'],
    correctIndex: 1,
    explanation: 'Continuity at $a$ means three things line up: $f(a)$ is defined, $\\lim_{x\\to a}f(x)$ exists, and that limit equals $f(a)$. Differentiability at $a$ is sufficient for continuity there, but it is not required.',
    realWorld: 'Continuity and smoothness assumptions help optimization methods reason about local changes in an objective; discontinuities can make ordinary gradient-based steps undefined or unreliable at the jump.',
    hint: 'The function value and the limit must agree at that point.',
  },
  {
    id: 66,
    topic: 'calculus',
    conceptIds: ['product-rule', 'derivatives'],
    difficulty: 'easy',
    question: 'The product rule states $\\frac{d}{dx}[f(x)g(x)] = $?',
    options: ["$f'(x)g'(x)$", "$f'(x)g(x) + f(x)g'(x)$", "$f(x)g'(x)$", "$[f(x)g(x)]'$"],
    correctIndex: 1,
    explanation: 'The product rule: differentiate one factor at a time and sum. $(fg)\' = f\'g + fg\'$.',
    realWorld: 'The product rule appears in deriving loss functions that involve products of probabilities.',
    hint: 'Each factor gets its turn to be differentiated while the other stays.',
  },
];
