import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 8,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'In the chain rule, if $y = f(g(x))$, what is $\\frac{dy}{dx}$?',
    options: ["$f'(x) \\cdot g'(x)$", "$f'(g(x)) \\cdot g'(x)$", "$f(g'(x))$", "$f'(x) + g'(x)$"],
    correctIndex: 1,
    explanation: "The chain rule composes derivatives: differentiate the outer function at the inner, then multiply by the inner's derivative.",
    realWorld: 'Backpropagation in deep learning IS the chain rule applied layer by layer.',
    hint: 'Differentiate the outer at the inner, then multiply by the inner derivative.',
  },
  {
    id: 10,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'What is $\\frac{\\partial}{\\partial x}[xy^2 + x^2]$?',
    options: ['$2xy + 2x$', '$y^2 + 2x$', '$x^2 + 2xy$', '$2y + x$'],
    correctIndex: 1,
    explanation: 'Partial derivative with respect to $x$: treat $y$ as constant. $\\frac{\\partial}{\\partial x}(xy^2) = y^2$ and $\\frac{\\partial}{\\partial x}(x^2) = 2x$.',
    realWorld: 'Partial derivatives are used to compute gradients for multi-variable loss functions in ML.',
    hint: 'Treat y as a constant and differentiate only with respect to x.',
  },
  {
    id: 32,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'The integral $\\int_a^b f(x)\\,dx$ geometrically represents:',
    options: ['The slope of $f$', 'The signed area under $f$ between $a$ and $b$', 'The maximum of $f$', 'The derivative of $f$'],
    correctIndex: 1,
    explanation: 'The definite integral computes the signed area between the curve and the x-axis over $[a,b]$.',
    realWorld: 'Integration computes total probability, expected values, and cumulative distributions in statistics.',
    hint: 'Think about the region between the curve and the horizontal axis.',
  },
  {
    id: 67,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'L\'Hôpital\'s rule applies when the limit has the form:',
    options: ['$\\infty - \\infty$', '$0/0$ or $\\infty/\\infty$', '$0 \\cdot \\infty$', '$1^\\infty$'],
    correctIndex: 1,
    explanation: 'L\'Hôpital\'s rule applies to quotient limits with indeterminate form $0/0$ or $\\infty/\\infty$ when the numerator and denominator are differentiable near the limit point, the denominator derivative is nonzero there, and the derivative quotient has a limit (possibly infinite). Under those conditions, $\\lim \\frac{f}{g} = \\lim \\frac{f\'}{g\'}$.',
    realWorld: 'Used to analyze convergence rates of loss functions and regularization terms.',
    hint: 'When both numerator and denominator go to the same extreme, differentiate them both.',
  },
  {
    id: 68,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'The Fundamental Theorem of Calculus connects:',
    options: ['Limits and continuity', 'Differentiation and integration', 'Sequences and series', 'Vectors and scalars'],
    correctIndex: 1,
    explanation: 'It states that differentiation and integration are inverse operations: $\\frac{d}{dx}\\int_a^x f(t)\\,dt = f(x)$.',
    realWorld: 'Enables computing exact areas and probabilities from antiderivatives.',
    hint: 'These two fundamental operations of calculus undo each other.',
  },
  {
    id: 69,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'The directional derivative $D_{\\mathbf{u}} f$ gives:',
    options: ['The maximum rate of change', 'The rate of change of $f$ in direction $\\mathbf{u}$', 'The second derivative', 'The integral along $\\mathbf{u}$'],
    correctIndex: 1,
    explanation: 'For a unit direction vector $\\mathbf{u}$, $D_{\\mathbf{u}}f = \\nabla f \\cdot \\mathbf{u}$. This dot product projects the gradient onto $\\mathbf{u}$, so it measures the signed rate of change in that direction. The maximum directional derivative is $\\|\\nabla f\\|$, attained in the gradient direction.',
    realWorld: 'Directional derivatives help understand how loss changes along specific parameter directions.',
    hint: 'Project the gradient onto a specific direction to see how fast the function changes.',
  },
  {
    id: 70,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'Integration by parts uses the formula:',
    options: ['$\\int uv\\,dx = u \\cdot v$', '$\\int u\\,dv = uv - \\int v\\,du$', '$\\int f(g(x))\\,dx = F(g(x))$', '$\\int (u+v)\\,dx = \\int u\\,dx + \\int v\\,dx$'],
    correctIndex: 1,
    explanation: 'Integration by parts reverses the product rule: $\\int u\\,dv = uv - \\int v\\,du$.',
    realWorld: 'Used in deriving the ELBO in variational inference and many ML derivations.',
    hint: 'It is the integral version of the product rule for differentiation.',
  },
  {
    id: 71,
    topic: 'calculus',
    difficulty: 'hard',
    question: 'A critical point of $f(x)$ occurs where:',
    options: ['$f(x) = 0$', "$f'(x) = 0$ or $f'(x)$ is undefined", '$f(x)$ is maximum', "$f''(x) = 0$"],
    correctIndex: 1,
    explanation: 'At an interior point of the domain, a critical point occurs where $f\'(x)=0$ or where $f\'$ does not exist. Critical points are candidates for local extrema, but they need not be extrema; for example, $f(x)=x^3$ has a critical point at $x=0$ without a local maximum or minimum.',
    realWorld: 'Finding critical points identifies candidates that optimization methods can classify as minima, maxima, or other stationary behavior.',
    hint: 'Find domain points where the derivative is zero or fails to exist; classification comes afterward.',
  },
];
