import type { Question } from '../types';

export const sotaQuestions: Question[] = [
  {
    id: 9,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The Hessian $\\mathbf{H}$ of $f$ is:',
    options: ['The vector of first partial derivatives', 'The matrix of second partial derivatives', 'The determinant of the Jacobian', 'The integral of the gradient'],
    correctIndex: 1,
    explanation: '$H_{ij} = \\frac{\\partial^2 f}{\\partial x_i \\partial x_j}$. The Hessian captures local second-order curvature. At a stationary point, a positive-definite Hessian implies a strict local minimum and a negative-definite Hessian implies a strict local maximum; an indefinite Hessian implies a saddle point.',
    realWorld: "Newton's method uses the Hessian to build a local quadratic model of the objective, while Hessian eigenvalues diagnose curvature directions and conditioning.",
    hint: 'Go one derivative deeper than the gradient: collect every second partial derivative into a matrix.',
  },
  {
    id: 23,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The Jacobian matrix $\\mathbf{J}$ of $\\mathbf{f}: \\mathbb{R}^n \\to \\mathbb{R}^m$ has entries:',
    options: ['$J_{ij} = \\frac{\\partial f_i}{\\partial x_j}$', '$J_{ij} = \\frac{\\partial^2 f}{\\partial x_i \\partial x_j}$', '$J_{ij} = f_i \\cdot x_j$', '$J_{ij} = \\delta_{ij}$'],
    correctIndex: 0,
    explanation: 'The Jacobian generalizes the derivative to vector-valued functions. Each row is the gradient of one output component.',
    realWorld: 'Jacobians appear in robotics (kinematics), normalizing flows, and change-of-variables in probability.',
    hint: 'Each row is the gradient of one output component with respect to all inputs.',
  },
  {
    id: 33,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The Taylor expansion of $f(x)$ around $a$ is $\\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n$. The first-order approximation gives:',
    options: ['$f(a)$', "$f(a) + f'(a)(x-a)$", "$f'(a)$", '$f(a) \\cdot (x-a)$'],
    correctIndex: 1,
    explanation: 'The first-order Taylor approximation is a linear approximation: tangent line at $a$.',
    realWorld: 'Taylor approximations linearize complex functions in optimization, physics simulations, and control theory.',
    hint: 'Keep only the constant and linear terms of the series.',
  },
  {
    id: 72,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The Laplacian $\\nabla^2 f = \\sum_i \\frac{\\partial^2 f}{\\partial x_i^2}$ measures:',
    options: ['The gradient magnitude', 'The divergence of the gradient (net curvature)', 'The cross-partial derivatives', 'The integral of $f$'],
    correctIndex: 1,
    explanation: 'The Laplacian is the trace of the Hessian — it sums the second derivatives along each axis, measuring total concavity.',
    realWorld: 'Laplacians appear in heat equations, image processing (edge detection), and graph neural networks.',
    hint: 'Sum up the second derivatives along each coordinate axis.',
  },
  {
    id: 73,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The divergence theorem relates:',
    options: ['Line integrals to derivatives', 'Surface flux to volume integral of divergence', 'Gradient to Hessian', 'Eigenvalues to singular values'],
    correctIndex: 1,
    explanation: '$\\oint_S \\mathbf{F} \\cdot d\\mathbf{S} = \\int_V (\\nabla \\cdot \\mathbf{F})\\,dV$. It connects local divergence to total flux through a surface.',
    realWorld: 'Used in physics-informed neural networks and computational fluid dynamics.',
    hint: 'Total outflow through the boundary equals the integral of sources inside.',
  },
  {
    id: 74,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'Automatic differentiation (AD) computes exact gradients by:',
    options: ['Symbolic simplification', 'Numerical finite differences', 'Applying the chain rule to elementary operations', 'Approximating with random perturbations'],
    correctIndex: 2,
    explanation: 'AD decomposes computations into elementary ops, applies chain rule exactly — no approximation or symbolic algebra needed.',
    realWorld: 'PyTorch autograd and JAX use reverse-mode AD to train neural networks.',
    hint: 'Break the computation into tiny steps and chain their derivatives together.',
  },
  {
    id: 75,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'The Leibniz integral rule $\\frac{d}{dx}\\int_{a(x)}^{b(x)} f(x,t)\\,dt$ involves:',
    options: ['Only the boundary terms', 'Boundary terms plus an integral of $\\partial f/\\partial x$', 'Just $f(b(x)) - f(a(x))$', 'The Hessian of $f$'],
    correctIndex: 1,
    explanation: 'Leibniz rule differentiates under the integral sign, accounting for both the integrand\'s dependence on $x$ and moving limits.',
    realWorld: 'Used in deriving score functions for variational inference and policy gradients in RL.',
    hint: 'You need to handle both the changing limits and the integrand\'s dependence on x.',
  },
  {
    id: 76,
    topic: 'calculus',
    difficulty: 'sota',
    question: 'A saddle point has:',
    options: ['All positive second derivatives', 'All negative second derivatives', 'The Hessian has both positive and negative eigenvalues', 'Zero gradient and zero Hessian'],
    correctIndex: 2,
    explanation: 'At a saddle point, the function curves up in some directions and down in others — the Hessian is indefinite.',
    realWorld: 'Saddle points are more common than local minima in high-dimensional loss landscapes of deep networks.',
    hint: 'It looks like a minimum along one axis but a maximum along another.',
  },
];
