import type { Question } from '../types';

export const compilerTheoryQuestions: Question[] = [
  // ── Easy ──
  {
    id: 95001, topic: 'compiler-theory', difficulty: 'easy',
    question: 'The first phase of a typical compiler is:',
    options: ['Lexical analysis (tokenization)', 'Code generation', 'Optimization', 'Linking'],
    correctIndex: 0,
    explanation: 'Lexical analysis breaks source code into tokens (keywords, identifiers, literals, operators).',
    realWorld: 'Tokenizers are also the first step in LLM pipelines (BPE, SentencePiece).',
    hint: 'This phase reads characters and groups them into meaningful units.',
  },
  {
    id: 95002, topic: 'compiler-theory', difficulty: 'easy',
    question: 'A context-free grammar (CFG) is used primarily in which compiler phase?',
    options: ['Parsing (syntax analysis)', 'Lexical analysis', 'Register allocation', 'Linking'],
    correctIndex: 0,
    explanation: 'CFGs define the syntactic structure of programming languages; parsers check programs against these grammars.',
    realWorld: 'CFGs also define structured output formats for LLM constrained generation.',
    hint: 'This phase builds an abstract syntax tree (AST).',
  },
  {
    id: 95003, topic: 'compiler-theory', difficulty: 'easy',
    question: 'An Abstract Syntax Tree (AST) represents:',
    options: ['The hierarchical syntactic structure of source code', 'The machine code output', 'The symbol table', 'Runtime memory layout'],
    correctIndex: 0,
    explanation: 'An AST strips away syntactic sugar and captures the essential structure of the program.',
    realWorld: 'ASTs are used by code analysis tools, linters, and AI code assistants.',
    hint: 'It is a tree data structure produced by the parser.',
  },
  {
    id: 95004, topic: 'compiler-theory', difficulty: 'easy',
    question: 'Static Single Assignment (SSA) form requires that each variable is:',
    options: ['Assigned exactly once', 'Used exactly once', 'Always a constant', 'Never aliased'],
    correctIndex: 0,
    explanation: 'SSA form renames variables so each definition site creates a unique name, simplifying optimization.',
    realWorld: 'LLVM IR uses SSA form as its core intermediate representation.',
    hint: 'New versions of a variable get new names ($x_1, x_2, \\ldots$).',
  },
  {
    id: 95005, topic: 'compiler-theory', difficulty: 'easy',
    question: 'Register allocation is the process of:',
    options: ['Mapping virtual registers/variables to physical CPU registers', 'Allocating heap memory', 'Managing the call stack', 'Scheduling instructions'],
    correctIndex: 0,
    explanation: 'Register allocation minimizes memory accesses by keeping frequently used values in fast CPU registers.',
    realWorld: 'Graph coloring-based register allocation is an NP-hard problem solved by heuristics in production compilers.',
    hint: 'CPUs have a limited number of registers; the compiler must choose which values go where.',
  },
  // ── Hard ──
  {
    id: 95006, topic: 'compiler-theory', difficulty: 'hard',
    question: 'LLVM\'s intermediate representation (IR) is designed to be:',
    options: ['Language-independent and target-independent, enabling multi-language/multi-target compilation', 'Specific to C/C++ only', 'Interpreted at runtime', 'A binary format only'],
    correctIndex: 0,
    explanation: 'LLVM IR is a typed, SSA-based IR that separates language frontends from target backends.',
    realWorld: 'LLVM powers Clang, Rust, Swift, Julia, and many ML compiler frameworks (XLA, TVM).',
    hint: 'LLVM stands for "Low Level Virtual Machine" and provides a universal compilation framework.',
  },
  {
    id: 95007, topic: 'compiler-theory', difficulty: 'hard',
    question: 'Polyhedral compilation optimizes loop nests by modeling iteration spaces as:',
    options: ['Integer polyhedra, enabling affine transformations for parallelism and locality', 'Binary trees', 'Finite automata', 'Hash tables'],
    correctIndex: 0,
    explanation: 'The polyhedral model represents loop iterations as lattice points in polyhedra, enabling optimal tiling and parallelization.',
    realWorld: 'Polyhedral optimization is used in ML compilers (TensorFlow XLA, MLIR) for tensor operation fusion.',
    hint: 'Loop iterations form a grid of integer points that can be rearranged geometrically.',
  },
  {
    id: 95008, topic: 'compiler-theory', difficulty: 'hard',
    question: 'Hindley-Milner type inference (used in ML, Haskell) uses which algorithm?',
    options: ['Algorithm W based on unification', 'Backtracking search', 'Gradient descent', 'Dynamic programming'],
    correctIndex: 0,
    explanation: 'Algorithm W infers principal types by solving type constraints through Robinson\'s unification algorithm.',
    realWorld: 'HM inference enables writing Haskell/OCaml code without type annotations while maintaining full type safety.',
    hint: 'The algorithm unifies type variables to find the most general type.',
  },
  {
    id: 95009, topic: 'compiler-theory', difficulty: 'hard',
    question: 'JIT (Just-In-Time) compilation differs from AOT (Ahead-Of-Time) in that:',
    options: ['JIT compiles code at runtime, enabling profile-guided optimizations', 'JIT is always slower', 'AOT cannot optimize', 'JIT requires no runtime'],
    correctIndex: 0,
    explanation: 'JIT compilers (V8, HotSpot) use runtime profiling to specialize code for observed behavior.',
    realWorld: 'PyTorch\'s torch.compile and JAX\'s jit use JIT compilation for ML workload optimization.',
    hint: 'Runtime information allows optimizations that static compilers cannot perform.',
  },
  {
    id: 95010, topic: 'compiler-theory', difficulty: 'hard',
    question: 'Escape analysis in a compiler determines whether an object:',
    options: ['Can be allocated on the stack instead of the heap', 'Is a global variable', 'Is used in a loop', 'Has type errors'],
    correctIndex: 0,
    explanation: 'If an object doesn\'t "escape" its creating method, it can be stack-allocated, avoiding GC pressure.',
    realWorld: 'Go and Java HotSpot use escape analysis to reduce garbage collection overhead.',
    hint: 'Can the reference to this object be seen outside the current function?',
  },
  // ── SOTA ──
  {
    id: 95011, topic: 'compiler-theory', difficulty: 'sota',
    question: 'MLIR (Multi-Level Intermediate Representation) advances compiler infrastructure by:',
    options: ['Providing a framework for defining domain-specific IRs with reusable optimization passes', 'Replacing LLVM entirely', 'Only targeting GPUs', 'Being a new programming language'],
    correctIndex: 0,
    explanation: 'MLIR allows defining custom "dialects" (tensor ops, GPU ops, etc.) with shared infrastructure for lowering and optimization.',
    realWorld: 'MLIR powers TensorFlow, PyTorch 2.0 (torch-mlir), and hardware-specific ML compilers.',
    hint: 'MLIR is about having multiple levels of abstraction in a single compiler framework.',
  },
  {
    id: 95012, topic: 'compiler-theory', difficulty: 'sota',
    question: 'Equality saturation (e-graphs) optimizes programs by:',
    options: ['Exploring all equivalent rewrites simultaneously using an e-graph data structure', 'Applying rewrites one at a time greedily', 'Using gradient descent on cost functions', 'Random sampling of transformations'],
    correctIndex: 0,
    explanation: 'E-graphs compactly represent exponentially many equivalent programs; extraction finds the optimal variant.',
    realWorld: 'The egg library uses equality saturation for ML compiler optimization and verified rewriting.',
    hint: 'Instead of choosing one rewrite at a time, represent ALL equivalent forms at once.',
  },
  {
    id: 95013, topic: 'compiler-theory', difficulty: 'sota',
    question: 'Verified compilers like CompCert guarantee:',
    options: ['Semantic preservation: the compiled code behaves exactly as the source semantics specify', 'Faster compilation', 'Smaller binary size', 'Platform independence'],
    correctIndex: 0,
    explanation: 'CompCert has a machine-checked Coq proof that every compilation pass preserves observable behavior.',
    realWorld: 'CompCert is used in safety-critical avionics and nuclear applications requiring DO-178C certification.',
    hint: 'The compiler itself is proven correct, not just tested.',
  },
  {
    id: 95014, topic: 'compiler-theory', difficulty: 'sota',
    question: 'LLM-based code generation (Codex, StarCoder) challenges traditional compilers because:',
    options: ['They generate code probabilistically without formal correctness guarantees', 'They are always faster', 'They replace type systems', 'They don\'t use tokenization'],
    correctIndex: 0,
    explanation: 'LLM code generators are stochastic — they can produce plausible but incorrect code, unlike deterministic compilers.',
    realWorld: 'Combining LLM generation with formal verification (LeanDojo, AlphaProof) is an active research frontier.',
    hint: 'Think about the gap between "likely correct" and "provably correct".',
  },
  {
    id: 95015, topic: 'compiler-theory', difficulty: 'sota',
    question: 'Tensor compilers (TVM, Triton, XLA) differ from traditional compilers in their focus on:',
    options: ['Optimizing multi-dimensional array operations for heterogeneous hardware (GPU/TPU/NPU)', 'Only scalar operations', 'Text processing', 'Network protocols'],
    correctIndex: 0,
    explanation: 'Tensor compilers fuse, tile, and schedule tensor operations to maximize data locality and parallelism on accelerators.',
    realWorld: 'Triton (OpenAI) enables writing custom GPU kernels in Python with compiler-level optimizations.',
    hint: 'The key challenge is mapping high-dimensional tensor operations to hardware-specific execution patterns.',
  },
];
