import type { Question } from '../types';

export const biologyQuestions: Question[] = [
  // ── Molecular Biology ──────────────────────────────────────
  {
    id: 50001, topic: "molecular-biology", difficulty: "easy",
    question: "The central dogma of molecular biology describes the usual flow of sequence information as:",
    options: ["Protein → RNA → DNA","RNA → Protein → DNA","DNA → RNA → Protein","DNA → Protein → RNA"],
    correctIndex: 2,
    explanation: "The central dogma summarizes the usual transfer of sequence information from DNA to RNA by transcription and from RNA to protein by translation.",
    realWorld: "It provides the conceptual backbone for interpreting gene expression, mRNA therapeutics, and many molecular diagnostic assays.",
    hint: "Start with the long-term genetic store, then move to the transient message and finally to the translated product.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50002, topic: "molecular-biology", difficulty: "hard",
    question: "In standard CRISPR-Cas9 genome editing, what gives Cas9 most of its sequence specificity?",
    options: ["DNA methylation at the target","Random diffusion into open chromatin","Ribosome binding to Cas9","Base pairing between a guide RNA and the target DNA next to a compatible PAM"],
    correctIndex: 3,
    explanation: "A guide RNA base-pairs with a complementary target sequence while Cas9 also requires an appropriate protospacer-adjacent motif, or PAM, near that target.",
    realWorld: "Guide design is central to CRISPR experiments because target recognition and off-target risk both depend strongly on sequence context.",
    hint: "Think about the programmable nucleic-acid component that directs the nuclease to an address in the genome.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50003, topic: "molecular-biology", difficulty: "sota",
    question: "Histone H3K27me3 is most strongly associated with which chromatin state?",
    options: ["Polycomb-associated transcriptional repression","Constitutive activation of ribosomal translation","Replication-fork initiation at every promoter","Permanent removal of nucleosomes from DNA"],
    correctIndex: 0,
    explanation: "Trimethylation of histone H3 lysine 27 is deposited by Polycomb repressive complex 2 and is a hallmark of Polycomb-associated repressive chromatin.",
    realWorld: "H3K27me3 profiling is widely used to study developmental gene regulation, cell identity, and epigenetic dysregulation in disease.",
    hint: "The relevant complex is PRC2; ask whether its hallmark mark is generally activating or repressive.",
    sources: [{"title":"An evolving landscape of PRC2–RNA interactions in chromatin regulation","url":"https://www.nature.com/articles/s41580-025-00850-3","publisher":"Nature Reviews Molecular Cell Biology","year":2025}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 55001, topic: "molecular-biology", difficulty: "easy",
    question: "DNA polymerases extend a newly synthesized DNA strand in which direction?",
    options: ["3′ → 5′","5′ → 3′","From the chromosome center toward both telomeres only","In either direction with equal probability"],
    correctIndex: 1,
    explanation: "DNA polymerases add each incoming nucleotide to the 3′ hydroxyl of the growing strand, so synthesis proceeds in the 5′ to 3′ direction.",
    realWorld: "This directional constraint explains why replication uses continuous leading-strand synthesis and discontinuous lagging-strand synthesis.",
    hint: "Ask which end of the growing strand provides the hydroxyl group used to form the next phosphodiester bond.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55002, topic: "molecular-biology", difficulty: "easy",
    question: "During maturation of a typical eukaryotic pre-mRNA, the spliceosome primarily:",
    options: ["Copies the transcript back into DNA","Adds amino acids to the RNA","Duplicates every exon","Removes introns and joins selected exons"],
    correctIndex: 3,
    explanation: "The spliceosome recognizes splice sites in pre-mRNA, removes introns as lariat intermediates, and ligates neighboring exons to form mature RNA.",
    realWorld: "RNA splicing is essential for gene expression and creates opportunities for regulated alternative isoforms from the same gene.",
    hint: "Focus on what happens to intervening sequences before an mRNA is exported for translation.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55003, topic: "molecular-biology", difficulty: "hard",
    question: "In a well-controlled quantitative PCR experiment, a sample with a lower threshold cycle (Ct) usually started with:",
    options: ["More amplifiable target template","Less amplifiable target template","Exactly the same target amount regardless of Ct","No target sequence at all"],
    correctIndex: 0,
    explanation: "A lower Ct means the fluorescence threshold was crossed after fewer amplification cycles, which generally indicates more amplifiable target molecules were present at the start.",
    realWorld: "Ct comparisons are used in gene-expression assays, pathogen detection, and quality-control workflows when amplification efficiencies and controls are appropriate.",
    hint: "If more template is present initially, fewer doubling cycles are needed to cross a fixed fluorescence threshold.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55004, topic: "molecular-biology", difficulty: "hard",
    question: "How can alternative splicing increase protein diversity without increasing the number of genes?",
    options: ["By changing the DNA sequence in every cell","By translating introns directly into protein","By combining exons from the same pre-mRNA in different patterns","By replacing the genetic code with a tissue-specific code"],
    correctIndex: 2,
    explanation: "Alternative splicing selects different exon combinations from a single pre-mRNA, producing distinct mature transcripts that can encode different protein isoforms.",
    realWorld: "Tissue-specific splicing programs help generate specialized cell functions and can be disrupted by disease-causing variants in splice sites or regulators.",
    hint: "The gene stays the same; the key variation occurs while the RNA transcript is being processed.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55005, topic: "molecular-biology", difficulty: "sota",
    question: "Prime editing differs from standard nuclease-based CRISPR editing because it can:",
    options: ["Edit only mitochondrial DNA","Write specified small sequence changes using a Cas9 nickase–reverse-transcriptase system without requiring a donor DNA template or a double-strand break","Function only by deleting entire chromosomes","Operate without any guide RNA"],
    correctIndex: 1,
    explanation: "Prime editing couples a Cas9 nickase to an engineered reverse transcriptase and uses a prime-editing guide RNA that specifies both the genomic target and the desired edit.",
    realWorld: "The approach expands the set of programmable substitutions, small insertions, and deletions that can be introduced while avoiding a required double-strand break.",
    hint: "Think of a guide that carries not just an address but also template information for the edit.",
    paper: {"title":"Search-and-replace genome editing without double-strand breaks or donor DNA","url":"https://www.nature.com/articles/s41586-019-1711-4","venue":"Nature","year":2019},
    reviewedAt: "2026-09-19",
  },
  {
    id: 55006, topic: "molecular-biology", difficulty: "sota",
    question: "What information does spatial transcriptomics add that ordinary dissociative single-cell RNA sequencing tends to lose?",
    options: ["The exact atomic mass of every RNA molecule","A complete protein structure for every transcript","The germline sequence of each chromosome","Where gene-expression patterns occurred within the original tissue"],
    correctIndex: 3,
    explanation: "Spatial transcriptomic methods preserve or reconstruct positional information for RNA measurements, allowing expression states to be interpreted in their tissue context.",
    realWorld: "Combining spatial and single-cell measurements helps reveal tissue architecture, local cell interactions, developmental niches, and tumor microenvironments.",
    hint: "Dissociating a tissue separates cells from the neighborhood in which their expression profile originally occurred.",
    sources: [{"title":"Integrating single-cell and spatial transcriptomics to elucidate intercellular tissue dynamics","url":"https://www.nature.com/articles/s41576-021-00370-8","publisher":"Nature Reviews Genetics","year":2021}],
    reviewedAt: "2026-09-19",
  },

  // ── Genetics ──────────────────────────────────────
  {
    id: 50004, topic: "genetics", difficulty: "easy",
    question: "Mendel's law of segregation states that:",
    options: ["Dominant alleles must be more common in a population","Linked genes always remain together","The two alleles at a locus separate so a gamete receives one of them","Every mutation produces a recessive phenotype"],
    correctIndex: 2,
    explanation: "During gamete formation, the two alleles carried by a diploid individual segregate so that each gamete receives one allele at the locus.",
    realWorld: "Segregation is the starting point for pedigree analysis, genetic counseling, and probability calculations for simple Mendelian traits.",
    hint: "Connect the law to what happens when homologous chromosome copies are partitioned into gametes.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50005, topic: "genetics", difficulty: "hard",
    question: "Epistasis describes a situation in which:",
    options: ["A chromosome acquires an extra centromere","The phenotypic effect of one locus depends on genotype at another locus","Every allele contributes additively to phenotype","A gene is expressed equally in every tissue"],
    correctIndex: 1,
    explanation: "Epistasis is interaction between loci: the effect of an allele at one locus changes depending on which alleles are present at another locus.",
    realWorld: "Gene-gene interactions help explain many pathway phenotypes and can complicate attempts to predict traits from variants considered one at a time.",
    hint: "The defining feature is dependence between loci, not merely physical linkage on a chromosome.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50006, topic: "genetics", difficulty: "sota",
    question: "A genome-wide association study (GWAS) is designed primarily to:",
    options: ["Sequence only a preselected disease gene","Measure protein abundance without genotyping","Infer a pedigree without phenotype data","Test associations between genetic variants across the genome and a measured trait or disease"],
    correctIndex: 3,
    explanation: "GWAS scans large numbers of genetic variants across many individuals and tests whether allele frequencies or genotypes are statistically associated with a phenotype.",
    realWorld: "GWAS has mapped thousands of trait-associated loci, but association signals usually require fine-mapping and functional follow-up before causal mechanisms are established.",
    hint: "The method is intentionally genome-wide rather than restricted to a single candidate gene.",
    sources: [{"title":"Decoding disease: from genomes to networks to phenotypes","url":"https://www.nature.com/articles/s41576-021-00389-x","publisher":"Nature Reviews Genetics","year":2021}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 55007, topic: "genetics", difficulty: "easy",
    question: "For a two-allele locus with allele frequencies p and q in Hardy-Weinberg equilibrium, the expected heterozygote frequency is:",
    options: ["2pq","p²","q²","p + q + 1"],
    correctIndex: 0,
    explanation: "Under Hardy-Weinberg assumptions, genotype frequencies are p² for one homozygote, 2pq for heterozygotes, and q² for the other homozygote.",
    realWorld: "Hardy-Weinberg expectations provide a baseline for detecting population structure, selection, genotyping problems, or other departures from simple assumptions.",
    hint: "Expand the binomial expression (p + q)² when p + q = 1.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55008, topic: "genetics", difficulty: "easy",
    question: "For two loci that are close enough for recombination frequency to estimate genetic distance, a recombination frequency of about 10% corresponds roughly to:",
    options: ["100 centimorgans","1 centimorgan","0.1 centimorgan","10 centimorgans"],
    correctIndex: 3,
    explanation: "For relatively short genetic distances, one percent recombination is approximately one centimorgan, so a 10% recombination fraction corresponds to about 10 cM.",
    realWorld: "Linkage maps use recombination to order loci before or alongside physical sequence maps.",
    hint: "For short intervals, convert percent recombination approximately one-for-one into centimorgans.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55009, topic: "genetics", difficulty: "hard",
    question: "Which statement correctly distinguishes penetrance from variable expressivity?",
    options: ["Penetrance is whether a genotype shows the phenotype at all; expressivity is the degree or form of the phenotype among those who show it","Penetrance measures chromosome length; expressivity measures gene count","Penetrance applies only to recessive traits; expressivity only to dominant traits","They are two names for the same probability"],
    correctIndex: 0,
    explanation: "Penetrance asks what fraction of people with a genotype display the associated phenotype, whereas expressivity describes how strongly or in what form the phenotype appears.",
    realWorld: "The distinction matters in pedigree interpretation because the same pathogenic genotype can be absent phenotypically in some carriers and variable in severity in others.",
    hint: "Separate the yes-or-no question of showing a trait from the question of how strongly it is expressed.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55010, topic: "genetics", difficulty: "hard",
    question: "Linkage disequilibrium (LD) refers to:",
    options: ["Independent assortment of every pair of variants","Permanent physical fusion of two chromosomes","A non-random association of alleles at different loci in a population","A failure of DNA polymerase to replicate linked genes"],
    correctIndex: 2,
    explanation: "LD occurs when combinations of alleles at different loci are observed more or less often than expected from their individual frequencies, reflecting recombination history and population processes.",
    realWorld: "GWAS and fine-mapping rely heavily on LD because a genotyped marker can tag nearby causal variation without itself being causal.",
    hint: "Think about statistical association between alleles across loci, not simply whether the loci are physically adjacent.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55011, topic: "genetics", difficulty: "sota",
    question: "What is a major advantage of a human pangenome reference over representing human variation with one linear reference sequence?",
    options: ["It removes all sequencing errors by definition","It can represent alternative haplotypes and structurally diverse sequence, reducing dependence on a single reference path","It guarantees identical variant frequencies across populations","It replaces the need to sequence individual genomes"],
    correctIndex: 1,
    explanation: "A pangenome represents multiple high-quality haplotypes and alternative sequence paths, capturing variants and structurally complex regions that a single linear reference cannot represent as naturally.",
    realWorld: "Pangenome references are intended to improve read mapping and variant discovery across diverse genomes while reducing reference-related blind spots.",
    hint: "The key idea is multiple valid sequence paths rather than one canonical chromosome string.",
    paper: {"title":"A draft human pangenome reference","url":"https://www.nature.com/articles/s41586-023-05896-x","venue":"Nature","year":2023},
    reviewedAt: "2026-09-19",
  },
  {
    id: 55012, topic: "genetics", difficulty: "sota",
    question: "Why can a polygenic risk score trained mainly in one ancestry group lose predictive accuracy in another?",
    options: ["Because DNA uses a different genetic code in different populations","Because risk alleles cease to exist outside the training population","Because allele frequencies, linkage-disequilibrium patterns, and the representativeness of discovery data can differ across populations","Because polygenic scores can be computed only from mitochondrial variants"],
    correctIndex: 2,
    explanation: "Polygenic scores combine effects learned from association studies, and their portability can decline when discovery cohorts do not represent the target population's allele frequencies, LD structure, and genetic architecture.",
    realWorld: "Improving diversity in genomic studies is both a scientific and equity requirement for robust risk prediction across populations.",
    hint: "A score inherits the sampling and correlation structure of the data used to estimate its variant weights.",
    sources: [{"title":"Clinical use of current polygenic risk scores may exacerbate health disparities","url":"https://www.nature.com/articles/s41588-019-0379-x","publisher":"Nature Genetics","year":2019}],
    reviewedAt: "2026-09-19",
  },

  // ── Ecology ──────────────────────────────────────
  {
    id: 50007, topic: "ecology", difficulty: "easy",
    question: "In a simple ecological energy pyramid, which trophic level normally receives the largest total energy input?",
    options: ["Primary consumers","Decomposers only","Primary producers","Top predators"],
    correctIndex: 2,
    explanation: "Primary producers capture external energy, usually through photosynthesis, and only a fraction of that energy is transferred onward to each consumer level.",
    realWorld: "Energy-flow constraints help explain why food webs generally support less biomass and fewer organisms at high trophic positions, though exact transfer efficiencies vary.",
    hint: "Start with the organisms that introduce new chemical energy into most ecosystems.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50008, topic: "ecology", difficulty: "hard",
    question: "The competitive exclusion principle predicts that, under stable conditions, two species with effectively identical limiting niches will:",
    options: ["Fail to coexist indefinitely unless some ecological difference reduces direct competition","Always evolve into the same species","Partition every resource equally from the start","Become mutualists automatically"],
    correctIndex: 0,
    explanation: "If two species depend on the same limiting resource in the same way, sustained competition tends to favor one; stable coexistence generally requires niche differences, trade-offs, or other mechanisms.",
    realWorld: "The principle motivates tests of resource partitioning, coexistence mechanisms, and the ecological effects of invasive competitors.",
    hint: "Ask what must change if two competitors otherwise require the same limiting niche indefinitely.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 50009, topic: "ecology", difficulty: "sota",
    question: "A metacommunity is best described as:",
    options: ["A single population with no dispersal","A set of local ecological communities linked by dispersal across a broader landscape","Only the microbial species living inside one host","A food web containing exactly four trophic levels"],
    correctIndex: 1,
    explanation: "Metacommunity theory links local species interactions and environmental filtering with regional processes such as dispersal among habitat patches.",
    realWorld: "The framework helps ecologists reason about fragmentation, connectivity, restoration, and how local diversity depends on processes operating beyond one site.",
    hint: "The prefix meta- signals that several local communities are coupled rather than analyzed in isolation.",
    sources: [{"title":"Metacommunity Dynamics in Ecological Systems","url":"https://www.nature.com/nature-index/topics/l4/metacommunity-dynamics-in-ecological-systems","publisher":"Nature Index"}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 55013, topic: "ecology", difficulty: "easy",
    question: "In the logistic population-growth model, carrying capacity K represents:",
    options: ["The maximum mutation rate a species can tolerate","The population size around which growth tends to slow as density-dependent limits become important","The minimum number of predators required for a food web","The number of species in the regional pool"],
    correctIndex: 1,
    explanation: "Carrying capacity is the population level at which limited resources and other density-dependent effects reduce net growth toward zero in the simple logistic model.",
    realWorld: "Although real populations rarely have a perfectly fixed K, the concept is useful for thinking about resource limitation and density dependence.",
    hint: "Look for the population scale at which growth no longer behaves as unconstrained exponential increase.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55014, topic: "ecology", difficulty: "easy",
    question: "A keystone species is defined primarily by:",
    options: ["Being the most numerous species in every habitat","Having the largest body size in the community","Occupying the lowest trophic level","Having an ecological effect disproportionately large relative to its abundance"],
    correctIndex: 3,
    explanation: "A keystone species has an unusually large influence on community structure or ecosystem processes compared with how abundant it is.",
    realWorld: "Removing a keystone predator, herbivore, engineer, or mutualist can trigger large community changes even if that species was never numerically dominant.",
    hint: "The term is about disproportionate effect, not simply abundance or size.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55015, topic: "ecology", difficulty: "hard",
    question: "In classical island biogeography theory, equilibrium species richness reflects a balance between:",
    options: ["Primary production and respiration","Mutation and genetic drift","Immigration of new species and extinction of resident species","Predation and photosynthesis"],
    correctIndex: 2,
    explanation: "MacArthur-Wilson island biogeography models species richness as a dynamic balance between immigration and extinction rates, which depend in part on isolation and island area.",
    realWorld: "The framework influenced reserve design and modern thinking about habitat fragments as island-like patches.",
    hint: "One process adds species to the island pool while another removes them.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55016, topic: "ecology", difficulty: "hard",
    question: "A trophic cascade occurs when:",
    options: ["Changes at one trophic level propagate indirectly through other trophic levels, altering abundance or ecosystem processes","Every species consumes organisms at the same trophic level","Nutrients stop cycling through an ecosystem","Only decomposers respond to a predator"],
    correctIndex: 0,
    explanation: "A trophic cascade is an indirect chain of ecological effects, often beginning with predators and propagating through prey or herbivores to producers or ecosystem functions.",
    realWorld: "Trophic cascades are important when predicting how predator recovery, harvest, or species loss can reshape communities beyond the directly affected species.",
    hint: "Think beyond a direct predator-prey pair to effects that continue through the food web.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 55017, topic: "ecology", difficulty: "sota",
    question: "Environmental DNA (eDNA) metabarcoding can survey biodiversity by:",
    options: ["Tagging every animal with a radio transmitter","Inferring species only from satellite temperature data","Counting organisms from fossil layers only","Sequencing diagnostic DNA fragments shed into environmental samples such as water, soil, sediment, or air"],
    correctIndex: 3,
    explanation: "eDNA approaches recover genetic material organisms leave in the environment, and metabarcoding uses sequence markers to detect many taxa from mixed samples.",
    realWorld: "The method can complement direct surveys for biodiversity monitoring, invasive-species detection, and ecosystem assessment while introducing its own sampling and interpretation biases.",
    hint: "The organisms do not have to be captured directly; traces of their DNA can remain in the sampled environment.",
    sources: [{"title":"Utilizing aquatic environmental DNA to address global biodiversity targets","url":"https://www.nature.com/articles/s44358-025-00044-x","publisher":"Nature Reviews Biodiversity","year":2025}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 55018, topic: "ecology", difficulty: "sota",
    question: "Why is combining ecological field observations with remote sensing especially powerful for biodiversity monitoring?",
    options: ["Remote sensing measures every species identity perfectly without field data","The two data sources connect local biological measurements with repeated spatial coverage over much larger areas","Field observations become unnecessary once a satellite image exists","Remote sensing can measure only atmospheric chemistry, not ecosystem structure"],
    correctIndex: 1,
    explanation: "Field observations provide direct biological detail while remote sensing supplies repeated spatial and temporal coverage of habitat structure, function, and environmental context; integration exploits complementary strengths.",
    realWorld: "Combined workflows support habitat mapping, change detection, conservation prioritization, and models that extrapolate sparse field measurements across landscapes.",
    hint: "One method is detailed but spatially sparse; the other can be broad and repeatable but usually needs biological calibration.",
    sources: [{"title":"Integrating remote sensing with ecology and evolution to advance biodiversity conservation","url":"https://www.nature.com/articles/s41559-022-01702-5","publisher":"Nature Ecology & Evolution","year":2022}],
    reviewedAt: "2026-09-19",
  },
];
