import type { Question } from '../types';

export const ergodicTheoryQuestions: Question[] = [
  // ── Easy ──
  {
    id: 92001, topic: 'ergodic-theory', difficulty: 'easy',
    question: 'An ergodic system is one where:',
    options: ['Time averages equal space averages for almost every initial condition', 'All orbits are periodic', 'The system is linear', 'Energy is always conserved'],
    correctIndex: 0,
    explanation: 'Birkhoff\'s ergodic theorem guarantees time averages converge to space (ensemble) averages in ergodic systems.',
    realWorld: 'Ergodicity justifies using time-series data to estimate ensemble statistics in climate modeling.',
    hint: 'Think about what happens when a system explores its entire state space over time.',
  },
  {
    id: 92002, topic: 'ergodic-theory', difficulty: 'easy',
    question: 'A measure-preserving transformation $T$ on $(X, \\mu)$ satisfies:',
    options: ['$\\mu(T^{-1}(A)) = \\mu(A)$ for all measurable $A$', '$T(x) = x$ for all $x$', '$\\mu(A) = 0$ for all $A$', '$T$ is continuous'],
    correctIndex: 0,
    explanation: 'Measure preservation means the pre-image of any measurable set has the same measure as the original set.',
    realWorld: 'Hamiltonian dynamics in physics preserves phase-space volume (Liouville\'s theorem).',
    hint: 'The transformation doesn\'t change the "size" of any measurable set.',
  },
  {
    id: 92003, topic: 'ergodic-theory', difficulty: 'easy',
    question: 'Poincaré\'s recurrence theorem states that in a measure-preserving system, almost every point:',
    options: ['Returns arbitrarily close to its initial position', 'Converges to a fixed point', 'Diverges to infinity', 'Reaches equilibrium in finite time'],
    correctIndex: 0,
    explanation: 'In a finite-measure system, almost every orbit returns to any neighborhood of its starting point infinitely often.',
    realWorld: 'Recurrence underpins the reversibility paradox in statistical mechanics.',
    hint: 'Think about what happens in a bounded system that preserves volume.',
  },
  {
    id: 92004, topic: 'ergodic-theory', difficulty: 'easy',
    question: 'The simplest example of an ergodic transformation on $[0,1)$ is:',
    options: ['Irrational rotation $x \\mapsto x + \\alpha \\pmod{1}$', 'The identity map', 'The constant map $x \\mapsto 0$', '$x \\mapsto x^2$'],
    correctIndex: 0,
    explanation: 'Rotation by an irrational $\\alpha$ is ergodic because the orbit of any point is equidistributed on the circle.',
    realWorld: 'Irrational rotations model quasicrystal diffraction patterns and Penrose tilings.',
    hint: 'Which rotation ensures no point is periodic?',
  },
  {
    id: 92005, topic: 'ergodic-theory', difficulty: 'easy',
    question: 'Mixing is a stronger property than ergodicity. A system is mixing if:',
    options: ['$\\mu(T^{-n}(A) \\cap B) \\to \\mu(A)\\mu(B)$ as $n \\to \\infty$', 'All orbits are dense', 'The system has no invariant sets', 'The system is reversible'],
    correctIndex: 0,
    explanation: 'Mixing means any two sets become asymptotically independent under iteration.',
    realWorld: 'Mixing rates determine how quickly Monte Carlo Markov chains converge to their stationary distribution.',
    hint: 'Think about correlations decaying over time.',
  },
  // ── Hard ──
  {
    id: 92006, topic: 'ergodic-theory', difficulty: 'hard',
    question: 'The Kolmogorov-Sinai (metric) entropy of an ergodic system measures:',
    options: ['The rate of information production / orbit unpredictability', 'The total energy of the system', 'The number of fixed points', 'The dimension of the phase space'],
    correctIndex: 0,
    explanation: 'KS entropy quantifies the exponential complexity of distinguishing orbits as time progresses.',
    realWorld: 'KS entropy connects dynamical systems to information theory and chaos quantification.',
    hint: 'Think about how much new information each time step reveals about the orbit.',
  },
  {
    id: 92007, topic: 'ergodic-theory', difficulty: 'hard',
    question: 'The Lyapunov exponent of a smooth dynamical system measures:',
    options: ['The exponential rate of divergence of nearby trajectories', 'The periodicity of orbits', 'The total number of fixed points', 'The fractal dimension'],
    correctIndex: 0,
    explanation: 'A positive Lyapunov exponent $\\lambda > 0$ means nearby trajectories separate as $\\sim e^{\\lambda t}$, indicating chaos.',
    realWorld: 'Lyapunov exponents determine predictability horizons in weather forecasting (Lorenz system).',
    hint: 'Think about sensitive dependence on initial conditions.',
  },
  {
    id: 92008, topic: 'ergodic-theory', difficulty: 'hard',
    question: 'Szemerédi\'s theorem, proven using ergodic theory by Furstenberg (1977), states that any subset of integers with positive upper density contains:',
    options: ['Arbitrarily long arithmetic progressions', 'A geometric progression', 'A perfect square', 'Infinitely many primes'],
    correctIndex: 0,
    explanation: 'Furstenberg\'s ergodic proof translates the combinatorial statement to a multiple recurrence theorem.',
    realWorld: 'This connection sparked the field of ergodic Ramsey theory with applications to additive combinatorics.',
    hint: 'Furstenberg used the correspondence principle to convert this to a dynamical statement.',
  },
  {
    id: 92009, topic: 'ergodic-theory', difficulty: 'hard',
    question: 'In the context of Navier-Stokes turbulence, the ergodic hypothesis is used to justify:',
    options: ['Replacing ensemble averages with time averages in turbulent statistics', 'Laminar flow assumptions', 'Zero viscosity limits', 'Periodic boundary conditions'],
    correctIndex: 0,
    explanation: 'Turbulence statistics (Reynolds stresses, energy spectra) are computed via time averaging under ergodic assumptions.',
    realWorld: 'This is fundamental to Reynolds-averaged Navier-Stokes (RANS) simulations used in aerodynamics.',
    hint: 'How do engineers compute "average" properties of turbulent flows in practice?',
  },
  {
    id: 92010, topic: 'ergodic-theory', difficulty: 'hard',
    question: 'The Ornstein isomorphism theorem shows that Bernoulli shifts are classified up to isomorphism by:',
    options: ['Their entropy alone', 'Their alphabet size', 'Their mixing rate', 'Their spectral type'],
    correctIndex: 0,
    explanation: 'Two Bernoulli shifts are isomorphic if and only if they have the same entropy, a remarkable complete invariant.',
    realWorld: 'This settled the classification of the most fundamental class of ergodic systems.',
    hint: 'The entropy is a complete invariant for this class of systems.',
  },
  // ── SOTA ──
  {
    id: 92011, topic: 'ergodic-theory', difficulty: 'sota',
    question: 'The Avila-Viana theorem (Fields Medal 2014 contribution) resolved the Kontsevich-Zorich conjecture about:',
    options: ['Simplicity of Lyapunov spectra for translation surfaces', 'Existence of periodic orbits in billiards', 'Convergence of continued fractions', 'Ergodicity of geodesic flow on flat surfaces'],
    correctIndex: 0,
    explanation: 'Avila proved that typical Teichmüller flows have simple (distinct) Lyapunov exponents.',
    realWorld: 'This connects dynamics on moduli spaces to the geometry of flat surfaces and rational billiards.',
    hint: 'Think about the spectrum of Lyapunov exponents for cocycles over Teichmüller flow.',
  },
  {
    id: 92012, topic: 'ergodic-theory', difficulty: 'sota',
    question: 'Ergodic theory of group actions beyond $\\mathbb{Z}$ is relevant because:',
    options: ['It connects to rigidity theorems (Margulis, Zimmer) and higher-rank dynamics', 'Only $\\mathbb{Z}$-actions are ergodic', 'Group actions are always periodic', 'It only applies to abelian groups'],
    correctIndex: 0,
    explanation: 'Zimmer\'s program and Margulis\' super-rigidity use ergodic theory of lattice actions in semisimple Lie groups.',
    realWorld: 'Brown-Fisher-Hurtado\'s proof of Zimmer\'s conjecture (2022) was a landmark in geometric group theory.',
    hint: 'Think about what happens when $\\mathbb{Z}$ is replaced by higher-rank lattices like $SL(n,\\mathbb{Z})$.',
  },
  {
    id: 92013, topic: 'ergodic-theory', difficulty: 'sota',
    question: 'In the ergodic theory of the Navier-Stokes equations, a key open question is whether:',
    options: ['Stationary statistical solutions are unique for given forcing', 'Solutions always blow up in finite time', 'Turbulent flows are always 2D', 'Viscosity has no effect on long-time behavior'],
    correctIndex: 0,
    explanation: 'Uniqueness of invariant measures for 3D stochastic NSE is central to turbulence theory.',
    realWorld: 'This is directly connected to Kolmogorov\'s 1941 theory of homogeneous isotropic turbulence.',
    hint: 'Think about the statistical steady state of forced turbulence.',
  },
  {
    id: 92014, topic: 'ergodic-theory', difficulty: 'sota',
    question: 'Operator algebras connect to ergodic theory through:',
    options: ['The crossed product construction $C(X) \\rtimes_T \\mathbb{Z}$ encoding dynamics in a C*-algebra', 'Matrix multiplication only', 'Finite group representations', 'Commutative algebra exclusively'],
    correctIndex: 0,
    explanation: 'The crossed product C*-algebra encodes the dynamical system and its properties (ergodicity, mixing) algebraically.',
    realWorld: 'This connection (Connes, Jones) links dynamics to quantum mechanics and knot invariants.',
    hint: 'The dynamical system becomes encoded in a noncommutative algebra.',
  },
  {
    id: 92015, topic: 'ergodic-theory', difficulty: 'sota',
    question: 'Homogeneous dynamics (Ratner\'s theorems) proves that unipotent flows on homogeneous spaces have orbits that are:',
    options: ['Equidistributed on algebraically defined submanifolds', 'Always periodic', 'Chaotic with positive entropy', 'Dense but not equidistributed'],
    correctIndex: 0,
    explanation: 'Ratner\'s measure classification shows every ergodic unipotent-invariant measure is algebraically defined.',
    realWorld: 'This was used to prove the Oppenheim conjecture about values of quadratic forms.',
    hint: 'Unipotent dynamics is remarkably rigid — orbit closures are always "nice" algebraic objects.',
  },
];
