import type { Question } from '../types';

export const marketMicrostructureQuestions: Question[] = [
  {
    id: 184001, topic: 'market-microstructure', difficulty: 'easy',
    question: 'The bid-ask spread represents:',
    options: ['The difference between the highest buy price and lowest sell price', 'The daily price range', 'The trading volume', 'The market capitalization'],
    correctIndex: 0,
    explanation: 'The bid-ask spread is the cost of immediacy — crossing the spread is the price you pay for instant execution. Tighter spreads indicate more liquid markets.',
    realWorld: 'Apple stock has a ~$0.01 spread; illiquid penny stocks may have $0.10+ spreads.',
    hint: 'Bid = what buyers offer; Ask = what sellers demand. The gap is the spread.',
  },
  {
    id: 184002, topic: 'market-microstructure', difficulty: 'easy',
    question: 'A limit order differs from a market order because:',
    options: ['It specifies a maximum buy (or minimum sell) price and may not execute immediately', 'It executes at the best available price immediately', 'It can only be placed after hours', 'It always gets filled'],
    correctIndex: 0,
    explanation: 'Limit orders provide liquidity by resting in the order book. Market orders take liquidity by executing against resting limits. Limit orders risk non-execution; market orders risk adverse price impact.',
    realWorld: 'HFT firms earn money by placing limit orders and capturing the bid-ask spread.',
    hint: 'Limit orders are patient; market orders are impatient.',
  },
  {
    id: 184003, topic: 'market-microstructure', difficulty: 'easy',
    question: 'Market depth refers to:',
    options: ['The volume of orders at different price levels in the order book', 'The number of listed stocks', 'The daily trading volume', 'The market capitalization'],
    correctIndex: 0,
    explanation: 'Market depth (the order book) shows how many shares are available at each price level. Deep markets can absorb large orders without significant price impact.',
    realWorld: 'Traders analyze Level 2 data (full order book) to gauge depth before placing large orders.',
    hint: 'Deep = lots of liquidity at many price levels; shallow = sparse orders.',
  },
  {
    id: 184004, topic: 'market-microstructure', difficulty: 'hard',
    question: 'The Kyle (1985) model of informed trading predicts that the price impact of a trade is:',
    options: ['Linear in order size: $\\Delta P = \\lambda Q$, where $\\lambda$ is Kyle\'s lambda', 'Independent of order size', 'Quadratic in order size', 'Zero for informed traders'],
    correctIndex: 0,
    explanation: 'Kyle\'s model shows that the market maker sets $\\lambda = \\sigma_v / (2\\sigma_u)$ — price impact is linear in order flow, balancing information asymmetry.',
    realWorld: 'Kyle\'s lambda is used to measure adverse selection costs in equity markets and is central to optimal execution algorithms.',
    hint: 'The market maker adjusts prices proportionally to net order flow to protect against informed traders.',
  },
  {
    id: 184005, topic: 'market-microstructure', difficulty: 'hard',
    question: 'The Almgren-Chriss optimal execution framework minimizes:',
    options: ['A combination of expected market impact cost and execution risk (variance)', 'Total commission fees', 'The number of trades', 'Time to complete execution'],
    correctIndex: 0,
    explanation: 'The Almgren-Chriss model finds the optimal trading trajectory balancing market impact (from trading too fast) against price risk (from trading too slow): $\\min \\mathbb{E}[\\text{cost}] + \\lambda \\cdot \\text{Var}[\\text{cost}]$.',
    realWorld: 'Every institutional trading desk uses Almgren-Chriss or its extensions for VWAP/TWAP execution.',
    hint: 'Trade fast → high impact. Trade slow → more risk. The model finds the optimal pace.',
  },
  {
    id: 184006, topic: 'market-microstructure', difficulty: 'hard',
    question: 'Maker-taker fee structures incentivize:',
    options: ['Providing liquidity (limit orders) by paying rebates and charging fees for taking liquidity', 'All orders equally', 'Only market orders', 'Dark pool routing'],
    correctIndex: 0,
    explanation: 'Exchanges pay rebates (~$0.002/share) to limit orders (makers) and charge fees (~$0.003/share) to market orders (takers), incentivizing deeper order books.',
    realWorld: 'This fee structure drives much of HFT strategy design and exchange competition.',
    hint: 'Makers add liquidity to the book; takers remove it.',
  },
  {
    id: 184007, topic: 'market-microstructure', difficulty: 'sota',
    question: 'The Avellaneda-Stoikov model for optimal market making determines bid/ask quotes by:',
    options: ['Maximizing expected P&L while controlling inventory risk via a reservation price adjustment', 'Keeping a fixed spread at all times', 'Matching the best bid/offer always', 'Ignoring inventory position'],
    correctIndex: 0,
    explanation: 'The reservation price $r = s - q\\gamma\\sigma^2(T-t)$ shifts quotes based on inventory $q$, risk aversion $\\gamma$, volatility $\\sigma$, and time horizon. This balances profit capture with inventory risk.',
    realWorld: 'Automated market makers on crypto exchanges and HFT equity firms use Avellaneda-Stoikov-style models.',
    hint: 'If you\'re long, lower your ask to reduce inventory; if short, raise your bid.',
  },
  {
    id: 184008, topic: 'market-microstructure', difficulty: 'sota',
    question: 'Hawkes processes in market microstructure model:',
    options: ['Self-exciting order flow dynamics where each event increases the probability of subsequent events', 'Constant-intensity arrival of orders', 'Only dark pool matching', 'Quarterly earnings patterns'],
    correctIndex: 0,
    explanation: 'Hawkes processes capture clustering in trade arrivals — a trade triggers more trades (momentum, HFT reactions). Intensity: $\\lambda(t) = \\mu + \\sum_{t_i < t} \\alpha e^{-\\beta(t-t_i)}$.',
    realWorld: 'Used to model flash crashes, HFT dynamics, and to detect market manipulation patterns.',
    hint: 'Events beget events — like aftershocks following an earthquake.',
  },
  {
    id: 184009, topic: 'market-microstructure', difficulty: 'sota',
    question: 'The PIN (Probability of Informed Trading) model estimates:',
    options: ['The fraction of trades driven by private information vs. noise trading', 'The probability of profit', 'The chance of a market crash', 'The correlation between stocks'],
    correctIndex: 0,
    explanation: 'PIN = $\\alpha\\mu / (\\alpha\\mu + 2\\varepsilon)$ from the Easley-Kiefer-O\'Hara model. It uses buy/sell trade imbalances to estimate information asymmetry.',
    realWorld: 'PIN is used by regulators to detect insider trading and by exchanges to set tick sizes.',
    hint: 'More buy-sell imbalance → higher probability of informed trading.',
  },
];
