import type { Question } from '../types';

export const nonlinearDynamicsEasyQuestions: Question[] = [
  {
    id: 28301,
    topic: 'nonlinear-dynamics',
    difficulty: 'easy',
    question: 'The logistic map $x_{n+1} = rx_n(1-x_n)$ exhibits chaos for $r$ values above approximately:',
    options: ['$r \\approx 3.57$ (onset of chaos via period-doubling cascade)', '$r = 1$', '$r = 2$', '$r = 4$ only'],
    correctIndex: 0,
    explanation: 'As $r$ increases, the logistic map undergoes period-doubling bifurcations at $r = 3, 3.449, 3.544, \\ldots$ converging to $r_\\infty \\approx 3.5699$ where chaos begins.',
    realWorld: 'The logistic map models population dynamics, epidemic spread, and is a benchmark for understanding chaos in all dynamical systems.',
    hint: 'Feigenbaum\'s universal constant $\\delta \\approx 4.669$ governs the rate of period-doubling.',
  },
  {
    id: 28302,
    topic: 'nonlinear-dynamics',
    difficulty: 'easy',
    question: 'A strange attractor is characterized by:',
    options: [
      'Fractal geometry and sensitive dependence on initial conditions',
      'A single fixed point',
      'Periodic orbits only',
      'Infinite dimensionality',
    ],
    correctIndex: 0,
    explanation: 'Strange attractors have non-integer (fractal) dimension and exhibit chaotic trajectories. The Lorenz attractor ($d \\approx 2.06$) and Rössler attractor are canonical examples.',
    realWorld: 'Strange attractors appear in weather models, turbulent fluid flows, cardiac arrhythmias, and financial time series.',
    hint: 'The trajectory never repeats, yet it stays bounded in a region with fractal structure.',
  },
  {
    id: 28303,
    topic: 'nonlinear-dynamics',
    difficulty: 'easy',
    question: 'A bifurcation in a dynamical system occurs when:',
    options: [
      'A small change in a parameter causes a qualitative change in the system\'s behavior (e.g., stability switch)',
      'The system reaches equilibrium',
      'Energy is conserved',
      'The equations become linear',
    ],
    correctIndex: 0,
    explanation: 'At a bifurcation point, the number or stability of fixed points, limit cycles, or chaotic attractors changes. Common types: saddle-node, pitchfork, Hopf, period-doubling.',
    realWorld: 'Bifurcations explain tipping points in climate, onset of oscillations in lasers, and flutter instabilities in aircraft wings.',
    hint: 'Think of a phase transition for dynamical systems — a parameter crosses a threshold and behavior changes qualitatively.',
  },
];

export const nonlinearDynamicsHardQuestions: Question[] = [
  {
    id: 28311,
    topic: 'nonlinear-dynamics',
    difficulty: 'hard',
    question: 'The Lorenz system $\\dot{x} = \\sigma(y-x),\\ \\dot{y} = x(\\rho-z)-y,\\ \\dot{z} = xy-\\beta z$ exhibits chaos for the classic parameters $\\sigma=10, \\beta=8/3, \\rho=$:',
    options: ['$28$', '$1$', '$10$', '$100$'],
    correctIndex: 0,
    explanation: 'At $\\rho = 28$, the origin is unstable and two symmetric fixed points are unstable spirals. Trajectories oscillate between the two "wings" of the butterfly-shaped Lorenz attractor.',
    realWorld: 'Lorenz discovered this in 1963 while modeling atmospheric convection — birthing chaos theory and proving long-range weather prediction is fundamentally impossible.',
    hint: 'The famous butterfly attractor emerges when $\\rho$ exceeds a critical value near 24.74.',
  },
  {
    id: 28312,
    topic: 'nonlinear-dynamics',
    difficulty: 'hard',
    question: 'Feigenbaum\'s universality constant $\\delta \\approx 4.6692$ describes the rate of convergence of:',
    options: [
      'Successive period-doubling bifurcation parameter values: $\\delta = \\lim_{n \\to \\infty} \\frac{r_n - r_{n-1}}{r_{n+1} - r_n}$',
      'Lyapunov exponents as a function of system size',
      'Fixed point locations in phase space',
      'Fractal dimension of the attractor',
    ],
    correctIndex: 0,
    explanation: 'Feigenbaum showed this constant is universal — it appears in ANY one-dimensional map with a quadratic maximum, from the logistic map to forced oscillators.',
    realWorld: 'Feigenbaum universality was confirmed experimentally in fluid convection, electronics, and nonlinear optics.',
    hint: 'The bifurcation spacings shrink geometrically, always by the same ratio $\\delta$.',
  },
  {
    id: 28313,
    topic: 'nonlinear-dynamics',
    difficulty: 'hard',
    question: 'The Poincaré-Bendixson theorem states that a bounded trajectory of a continuous 2D dynamical system that does not approach a fixed point must:',
    options: [
      'Approach a limit cycle (periodic orbit)',
      'Become chaotic',
      'Diverge to infinity',
      'Remain stationary',
    ],
    correctIndex: 0,
    explanation: 'In 2D, chaos is impossible for continuous flows! Bounded trajectories must converge to fixed points or limit cycles. Chaos requires $\\geq 3$ dimensions.',
    realWorld: 'This is why the Lorenz system needs 3 variables, and why 2D predator-prey models can oscillate but never produce chaos.',
    hint: 'Chaos is forbidden in 2D continuous systems — trajectories cannot cross in a plane.',
  },
];

export const nonlinearDynamicsSotaQuestions: Question[] = [
  {
    id: 28321,
    topic: 'nonlinear-dynamics',
    difficulty: 'sota',
    question: 'Takens\' embedding theorem guarantees that a chaotic attractor can be reconstructed from a scalar time series using:',
    options: [
      'Time-delay embedding in dimension $d > 2D$ where $D$ is the attractor\'s box-counting dimension',
      'Fourier transform only',
      'Linear regression',
      'Principal component analysis with 2 components',
    ],
    correctIndex: 0,
    explanation: 'Takens proved that delay coordinates $(x(t), x(t+\\tau), \\ldots, x(t+d\\tau))$ generically produce a diffeomorphic copy of the original attractor if $d > 2D$.',
    realWorld: 'Takens\' theorem enables chaotic prediction from single-sensor data — used in ECG analysis, financial forecasting, and climate reconstruction.',
    hint: 'You can reconstruct the full geometry of an attractor from just one measured variable, if you delay-embed it.',
  },
  {
    id: 28322,
    topic: 'nonlinear-dynamics',
    difficulty: 'sota',
    question: 'Reservoir computing exploits chaotic dynamics for machine learning by:',
    options: [
      'Using a high-dimensional nonlinear dynamical system as a fixed "reservoir" and training only the output layer',
      'Training all weights via backpropagation',
      'Using linear recurrence relations',
      'Replacing activation functions with sinusoids',
    ],
    correctIndex: 0,
    explanation: 'Echo state networks and liquid state machines use a random, chaotic dynamical system as a reservoir. Only the readout weights are trained — making training extremely fast.',
    realWorld: 'Reservoir computing has been implemented in photonic systems, memristive devices, and even water waves — achieving competitive performance on chaotic time series prediction.',
    hint: 'The reservoir is a chaotic system that maps input to a rich high-dimensional representation — no backpropagation needed.',
  },
  {
    id: 28323,
    topic: 'nonlinear-dynamics',
    difficulty: 'sota',
    question: 'The Smale horseshoe map demonstrates the fundamental mechanism of chaos through:',
    options: [
      'Repeated stretching and folding of phase space, creating a Cantor set of invariant orbits',
      'Rotation of phase space at irrational frequency',
      'Compression of all trajectories to a fixed point',
      'Random perturbation of a linear map',
    ],
    correctIndex: 0,
    explanation: 'Smale\'s horseshoe stretches a square, folds it into a horseshoe shape, and maps it back. The invariant set has Cantor structure, contains countably many periodic orbits and uncountably many aperiodic ones — all hallmarks of chaos.',
    realWorld: 'The horseshoe is the geometric template underlying chaos in virtually every chaotic system, from the double pendulum to turbulence.',
    hint: 'Stretch + fold + repeat = the recipe for generating sensitive dependence on initial conditions.',
  },
];
