import type { Question } from '../types';

export const easyQuestions: Question[] = [
  {
    id: 19,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'If an algorithm runs in $O(n^2)$ time, what does this mean?',
    options: ['It takes exactly $n^2$ steps', 'Runtime grows at most quadratically with input size', 'It uses $n^2$ memory', 'It is the fastest possible'],
    correctIndex: 1,
    explanation: 'Big-O notation $O(n^2)$ describes an upper bound — runtime scales quadratically as input grows.',
    realWorld: 'Choosing $O(n \\log n)$ sort over $O(n^2)$ can mean seconds vs. hours on large datasets.',
    hint: 'Big-O describes an upper bound on growth rate, not exact step count.',
  },
  {
    id: 42,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'What is a hash function used for?',
    options: ['Sorting data', 'Mapping data to fixed-size values for fast lookup', 'Encrypting passwords only', 'Compressing images'],
    correctIndex: 1,
    explanation: 'Hash functions map arbitrary input to a fixed-size output, enabling $O(1)$ average-case lookups in hash tables.',
    realWorld: 'Hash tables power Python dictionaries, database indexing, and caching in web applications.',
    hint: 'It converts any input into a fixed-size fingerprint for quick retrieval.',
  },
  {
    id: 44,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'Binary search on a sorted array runs in:',
    options: ['$O(n)$', '$O(n^2)$', '$O(\\log n)$', '$O(1)$'],
    correctIndex: 2,
    explanation: 'Binary search halves the search space each step, giving logarithmic time complexity.',
    realWorld: 'Binary search is used in database queries, hyperparameter tuning, and finding thresholds in ML.',
    hint: 'Each comparison eliminates half the remaining candidates.',
  },
  {
    id: 107,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'A stack data structure follows:',
    options: ['First-In, First-Out (FIFO)', 'Last-In, First-Out (LIFO)', 'Random access', 'Priority-based ordering'],
    correctIndex: 1,
    explanation: 'A stack operates LIFO — the last element pushed is the first one popped. Think of a stack of plates.',
    realWorld: 'Function call stacks, undo operations in editors, and parsing expressions all use stacks.',
    hint: 'The most recently added item is the first to be removed.',
  },
  {
    id: 108,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'A queue data structure follows:',
    options: ['Last-In, First-Out (LIFO)', 'First-In, First-Out (FIFO)', 'Sorted order', 'Random access'],
    correctIndex: 1,
    explanation: 'A queue is FIFO — elements are processed in the order they arrive, like a line at a store.',
    realWorld: 'Task queues, BFS graph traversal, and message brokers (Kafka, RabbitMQ) use queues.',
    hint: 'Just like waiting in line — first to arrive, first to be served.',
  },
  {
    id: 109,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'A tree data structure with no cycles is called:',
    options: ['A linked list', 'A graph', 'An acyclic connected graph', 'A hash table'],
    correctIndex: 2,
    explanation: 'A tree is a connected graph with no cycles. It has $n-1$ edges for $n$ nodes.',
    realWorld: 'Decision trees, file systems, and DOM structures are all tree-based.',
    hint: 'No loops allowed — every node has exactly one path from the root.',
  },
  {
    id: 110,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'The boolean operation AND ($\\wedge$) returns true only when:',
    options: ['At least one input is true', 'Both inputs are true', 'Both inputs are false', 'Inputs are different'],
    correctIndex: 1,
    explanation: 'AND requires all inputs to be true. If any input is false, the result is false.',
    realWorld: 'Logical AND gates are fundamental to digital circuits and conditional logic in programming.',
    hint: 'Every single input must be true for the output to be true.',
  },
  {
    id: 111,
    topic: 'discrete-math',
    difficulty: 'easy',
    question: 'An array provides $O(1)$ access by:',
    options: ['Sorting elements first', 'Using a hash function', 'Direct indexing with memory offset', 'Binary search'],
    correctIndex: 2,
    explanation: 'Arrays store elements contiguously in memory, so accessing element $i$ is just base_address + i × element_size.',
    realWorld: 'NumPy arrays and GPU tensors rely on contiguous memory layout for fast vectorized operations.',
    hint: 'Knowing the position lets you jump directly to the memory location.',
  },
];
