import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 20,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Shannon entropy $H(X) = -\\sum_i p_i \\log p_i$ measures:',
    options: ['Energy of a system', 'Information content / uncertainty', 'Compression ratio', 'Temperature'],
    correctIndex: 1,
    explanation: 'Entropy quantifies average surprise or uncertainty in a random variable. Higher entropy = more unpredictable.',
    realWorld: 'Used in decision trees (information gain), data compression, and cross-entropy loss.',
    hint: 'More uncertainty in the outcome means higher information content.',
  },
  {
    id: 21,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'A tensor $X_{i,j,k}$ is:',
    options: ['A scalar', 'A 2D matrix', 'A multi-dimensional array generalizing vectors and matrices', 'A vector'],
    correctIndex: 2,
    explanation: 'Tensors generalize: scalar (0D), vector (1D), matrix (2D), 3D tensor, etc. They are the fundamental data structure in deep learning.',
    realWorld: 'PyTorch and TensorFlow represent all data as tensors for GPU-accelerated computation.',
    hint: 'Think of it as a matrix with more than two index dimensions.',
  },
  {
    id: 43,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Softmax converts logits to:',
    options: ['Binary values', 'A probability distribution summing to 1', 'Negative values', 'Integer labels'],
    correctIndex: 1,
    explanation: '$\\text{softmax}(z_i) = e^{z_i}/\\sum_j e^{z_j}$ produces valid probabilities that sum to 1.',
    realWorld: 'Used in the final layer of classification networks and in attention mechanisms.',
    hint: 'Exponentiate and normalize so everything sums to one.',
  },
  {
    id: 46,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Dynamic programming solves problems by:',
    options: ['Random sampling', 'Breaking into overlapping subproblems and caching results', 'Brute force enumeration', 'Gradient descent'],
    correctIndex: 1,
    explanation: 'DP identifies overlapping subproblems, solves each once, and caches (memoizes) results to avoid redundant computation.',
    realWorld: 'Powers the Viterbi algorithm, sequence alignment (BLAST), and optimal policy computation in RL.',
    hint: 'Solve each subproblem once, store the result, and reuse it.',
  },
  {
    id: 112,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'BFS (Breadth-First Search) explores a graph:',
    options: ['Deepest nodes first', 'Level by level from the source', 'Random order', 'By edge weight'],
    correctIndex: 1,
    explanation: 'BFS uses a queue to explore all neighbors at distance $d$ before distance $d+1$. It finds shortest paths in unweighted graphs.',
    realWorld: 'Used in social network friend suggestions, web crawlers, and shortest path algorithms.',
    hint: 'Explore all immediate neighbors before going deeper.',
  },
  {
    id: 113,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'The time complexity of merge sort is:',
    options: ['$O(n^2)$', '$O(n \\log n)$', '$O(n)$', '$O(\\log n)$'],
    correctIndex: 1,
    explanation: 'Merge sort divides the array in half recursively and merges in $O(n)$, giving $O(n \\log n)$ total.',
    realWorld: 'Merge sort is used in external sorting (data too large for memory) and is the basis for TimSort in Python.',
    hint: 'Divide in half each time (log n levels) and merge all elements at each level (n work).',
  },
  {
    id: 114,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'A binary search tree (BST) has the property that:',
    options: ['All nodes have exactly two children', 'Left child < parent < right child', 'All leaves are at the same depth', 'It is always balanced'],
    correctIndex: 1,
    explanation: 'BST ordering: every left subtree contains smaller values and every right subtree contains larger values.',
    realWorld: 'BSTs underlie database indexes, and balanced variants (AVL, Red-Black) guarantee O(log n) operations.',
    hint: 'Smaller values go left, larger values go right.',
  },
  {
    id: 115,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'The pigeonhole principle states that if $n$ items go into $m$ containers with $n > m$:',
    options: ['All containers are empty', 'At least one container has more than one item', 'Items are evenly distributed', 'No container overflows'],
    correctIndex: 1,
    explanation: 'If you put more pigeons than holes, at least one hole must contain multiple pigeons. Simple but powerful in proofs.',
    realWorld: 'Used to prove hash collision inevitability and birthday paradox bounds in cryptography.',
    hint: 'More items than slots means at least one slot must be shared.',
  },
];
