import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 20,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Shannon entropy $H(X) = -\\sum_i p_i \\log p_i$ measures:',
    options: ['Expected codeword length for every encoding', 'Average uncertainty in the outcome of $X$', 'Probability of the most likely outcome', 'Number of distinct outcomes with nonzero probability'],
    correctIndex: 1,
    explanation: 'Entropy quantifies average surprise or uncertainty in a random variable. Higher entropy = more unpredictable.',
    realWorld: 'Used in decision trees (information gain), data compression, and cross-entropy loss.',
    hint: 'More uncertainty in the outcome means higher information content.',
  },
  {
    id: 21,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'A tensor $X_{i,j,k}$ is:',
    options: ['A scalar carrying three coordinate labels but remaining invariant under every basis change', 'A matrix whose entries must themselves be vectors in the same coordinate basis', 'A vector indexed by three independent labels with no transformation rule between bases', 'A three-index array, with tensor meaning determined by its transformation law'],
    correctIndex: 3,
    explanation: 'The three indices indicate a three-index array of components. In mathematics and physics, calling those components a tensor additionally refers to how they transform under a change of basis.',
    realWorld: 'PyTorch and TensorFlow use tensor-shaped arrays for GPU-accelerated computation, while mathematical tensors add basis-transformation structure.',
    hint: 'Three indices indicate more than a scalar, vector, or ordinary matrix; in the mathematical sense, transformation behavior also matters.',
  },
  {
    id: 43,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Softmax converts logits to:',
    options: ['Independent probabilities that need not sum to one', 'Signed scores constrained to have mean zero', 'A probability distribution whose entries sum to 1', 'One-hot labels obtained by taking the largest logit'],
    correctIndex: 2,
    explanation: '$\\text{softmax}(z_i) = e^{z_i}/\\sum_j e^{z_j}$ produces valid probabilities that sum to 1.',
    realWorld: 'Used in the final layer of classification networks and in attention mechanisms.',
    hint: 'Exponentiate and normalize so everything sums to one.',
  },
  {
    id: 46,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'Dynamic programming solves problems by:',
    options: ['Solving overlapping subproblems once and reusing their results', 'Enumerating every complete candidate without storing partial results', 'Choosing the locally best move at each step without reconsideration', 'Splitting into independent subproblems that never share intermediate states'],
    correctIndex: 0,
    explanation: 'DP identifies overlapping subproblems, solves each once, and caches (memoizes) results to avoid redundant computation.',
    realWorld: 'Powers the Viterbi algorithm, sequence alignment (BLAST), and optimal policy computation in RL.',
    hint: 'Solve each subproblem once, store the result, and reuse it.',
  },
  {
    id: 112,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'BFS (Breadth-First Search) explores a graph:',
    options: ['By repeatedly following the newest discovered vertex first until that path can no longer be extended', 'In increasing order of cumulative weighted path cost from the source vertex', 'By selecting the globally smallest-labeled unvisited vertex at every iteration', 'Level by level in increasing unweighted distance from the source'],
    correctIndex: 3,
    explanation: 'BFS uses a queue to explore all neighbors at distance $d$ before distance $d+1$. It finds shortest paths in unweighted graphs.',
    realWorld: 'Used in social network friend suggestions, web crawlers, and shortest path algorithms.',
    hint: 'Explore all immediate neighbors before going deeper.',
  },
  {
    id: 113,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'The time complexity of merge sort is:',
    options: ['$O(n^2)$ because every merge step compares each element with every other element in its subarray', '$O(n)$ because each element participates in only one merge over the entire recursion', '$O(\\log n)$ because only the logarithmic recursion depth contributes to running time', '$O(n \\log n)$ because each recursion level does linear merge work'],
    correctIndex: 3,
    explanation: 'Merge sort divides the array in half recursively and merges in $O(n)$, giving $O(n \\log n)$ total.',
    realWorld: 'Merge sort is used in external sorting (data too large for memory) and is the basis for TimSort in Python.',
    hint: 'Divide in half each time (log n levels) and merge all elements at each level (n work).',
  },
  {
    id: 114,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'A binary search tree (BST) has the property that:',
    options: ['Every internal node has exactly two children, so missing children occur only at the deepest level', 'Every root-to-leaf path has the same number of edges, which keeps search logarithmic', 'Keys in each left subtree are smaller and keys in each right subtree are larger than the node key', 'Each parent key is smaller than every key in both of its descendant subtrees'],
    correctIndex: 2,
    explanation: 'BST ordering requires every key in a node’s left subtree to be smaller and every key in its right subtree to be larger, assuming distinct keys.',
    realWorld: 'BSTs underlie ordered search structures, and balanced variants such as AVL and Red-Black trees guarantee $O(\\log n)$ operations.',
    hint: 'The ordering rule applies to whole subtrees, not merely to immediate children.',
  },
  {
    id: 115,
    topic: 'discrete-math',
    difficulty: 'hard',
    question: 'The pigeonhole principle states that if $n$ items go into $m$ containers with $n > m$:',
    options: ['Every container must receive at least one item', 'At least one container must receive at least two items', 'Some container must receive exactly $\\lceil n/m \\rceil$ items', 'The items must be distributed as evenly as possible'],
    correctIndex: 1,
    explanation: 'If you put more pigeons than holes, at least one hole must contain multiple pigeons. Simple but powerful in proofs.',
    realWorld: 'Used to prove hash collision inevitability and birthday paradox bounds in cryptography.',
    hint: 'More items than slots means at least one slot must be shared.',
  },
];
