import type { Question } from '../types';

export const sotaQuestions: Question[] = [
  {
    id: 22,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'An adjacency matrix $A_{ij} = 1$ if:',
    options: ['Node $i$ has degree $j$', 'There is an edge between node $i$ and node $j$', 'Shortest path from $i$ to $j$ is 1', 'Nodes have the same color'],
    correctIndex: 1,
    explanation: 'The adjacency matrix encodes graph connectivity: $A_{ij} = 1$ iff edge $(i,j)$ exists.',
    realWorld: 'GNNs use adjacency matrices to propagate features across social networks and molecular graphs.',
    hint: 'The matrix entry is 1 when there is a direct connection.',
  },
  {
    id: 45,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'In scaled dot-product attention, why divide by $\\sqrt{d_k}$?',
    options: ['To normalize the output', 'To prevent softmax saturation from large dot products', 'To reduce computation', 'To make $\\mathbf{Q}$ and $\\mathbf{K}$ orthogonal'],
    correctIndex: 1,
    explanation: 'With large $d_k$, dot products grow in magnitude, pushing softmax into regions of tiny gradients. Scaling by $\\sqrt{d_k}$ keeps gradients healthy.',
    realWorld: 'This scaling trick is foundational to all modern transformers (GPT, BERT, etc.).',
    hint: 'Large dot products saturate softmax — scaling keeps gradients healthy.',
  },
  {
    id: 47,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'The graph Laplacian $\\mathbf{L} = \\mathbf{D} - \\mathbf{A}$ is used for:',
    options: ['Image compression', 'Spectral clustering and graph partitioning', 'Sorting algorithms', 'Matrix inversion'],
    correctIndex: 1,
    explanation: 'The Laplacian\'s eigenvalues reveal graph connectivity. The Fiedler vector (2nd smallest eigenvalue) gives optimal graph cuts.',
    realWorld: 'Spectral clustering, graph neural networks, and community detection all use the graph Laplacian.',
    hint: 'The eigenvalues of this matrix reveal the structure and connectivity of the graph.',
  },
  {
    id: 116,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'NP-completeness means a problem:',
    options: ['Cannot be solved', 'Can be verified in polynomial time and is as hard as any problem in NP', 'Has only exponential algorithms', 'Is unsolvable by computers'],
    correctIndex: 1,
    explanation: 'NP-complete problems are the hardest in NP — if any can be solved in polynomial time, then all can (P = NP).',
    realWorld: 'The traveling salesman problem and SAT are NP-complete; heuristics and approximations are used in practice.',
    hint: 'Easy to verify a solution, but finding one seems to require exponential time.',
  },
  {
    id: 117,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'The master theorem solves recurrences of the form $T(n) = aT(n/b) + f(n)$ by comparing:',
    options: ['$a$ and $b$ only', '$f(n)$ with $n^{\\log_b a}$', 'The base case with $f(n)$', '$T(n)$ with $T(n-1)$'],
    correctIndex: 1,
    explanation: 'The master theorem compares the work at each level $f(n)$ with the number of subproblems $n^{\\log_b a}$ to determine overall complexity.',
    realWorld: 'Used to analyze divide-and-conquer algorithms like merge sort, Strassen multiplication, and FFT.',
    hint: 'Compare the cost of dividing/combining with how fast the problem shrinks.',
  },
  {
    id: 118,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'Message passing in Graph Neural Networks (GNNs) works by:',
    options: ['Sorting nodes by degree', 'Aggregating neighbor features to update each node\'s representation', 'Removing edges randomly', 'Applying convolutions on a grid'],
    correctIndex: 1,
    explanation: 'Each node gathers messages from its neighbors, aggregates them, and updates its own feature vector. This is repeated for $L$ layers.',
    realWorld: 'GNNs are used for drug discovery, traffic prediction, and recommendation systems.',
    hint: 'Each node collects information from its neighbors and updates itself.',
  },
  {
    id: 119,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'Amortized analysis shows that:',
    options: ['Every operation is O(1)', 'The average cost per operation over a sequence is low, even if some are expensive', 'Worst case equals best case', 'Space complexity is constant'],
    correctIndex: 1,
    explanation: 'Amortized analysis averages cost over a sequence of operations. E.g., dynamic array append is O(1) amortized despite occasional O(n) resizes.',
    realWorld: 'Hash table resizing, splay trees, and Python list appends all have amortized O(1) cost.',
    hint: 'Expensive operations are rare enough that the average cost stays low.',
  },
  {
    id: 120,
    topic: 'discrete-math',
    difficulty: 'sota',
    question: 'The Fast Fourier Transform (FFT) computes the DFT in:',
    options: ['$O(n^2)$', '$O(n \\log n)$', '$O(n)$', '$O(2^n)$'],
    correctIndex: 1,
    explanation: 'FFT exploits symmetry in the DFT matrix to reduce $O(n^2)$ to $O(n \\log n)$, one of the most important algorithms ever.',
    realWorld: 'Used in signal processing, audio analysis, polynomial multiplication, and training CNNs efficiently.',
    hint: 'Divide the problem into even and odd indices, solve recursively.',
  },
];
