import type { Question } from '../types';

export const easyQuestions: Question[] = [
  {
    id: 11,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["bayesian-inference","probability-rules"],
    question: "Bayes' theorem states $P(A|B) = $?",
    options: ['$P(B|A) \\cdot P(A)$', '$\\frac{P(B|A)P(A)}{P(B)}$', '$P(A) + P(B)$', '$P(A \\cap B)$'],
    correctIndex: 1,
    explanation: "Bayes' theorem inverts conditional probabilities using the prior $P(A)$, likelihood $P(B|A)$, and evidence $P(B)$.",
    realWorld: 'Powers spam filters, medical diagnosis, and Bayesian neural networks.',
    hint: 'You need the prior, the likelihood, and the evidence in the denominator.',
  },
  {
    id: 12,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["expectation-variance"],
    question: 'The expected value $E[X]$ is:',
    options: ['The most likely outcome', 'The weighted average over all outcomes', 'The median of the distribution', 'The maximum probability'],
    correctIndex: 1,
    explanation: '$E[X] = \\sum_x x \\cdot P(X=x)$ — the probability-weighted average. Not necessarily an observable value.',
    realWorld: 'Expected value is used in A/B testing and reinforcement learning reward signals.',
    hint: 'Weight each outcome by how likely it is, then sum.',
  },
  {
    id: 34,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["dependence-correlation","probability-rules"],
    question: 'If $X$ and $Y$ are independent, then $P(X, Y) = $?',
    options: ['$P(X) + P(Y)$', '$P(X) \\cdot P(Y)$', '$P(X|Y)$', '$P(X) / P(Y)$'],
    correctIndex: 1,
    explanation: 'Independence means joint probability factors: $P(X, Y) = P(X)P(Y)$. No information about $X$ helps predict $Y$.',
    realWorld: 'Naive Bayes classifiers assume feature independence to simplify computation.',
    hint: 'Independence means knowing one tells you nothing about the other.',
  },
  {
    id: 77,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["probability-rules"],
    question: 'The probability of any event $A$ must satisfy:',
    options: ['$-1 \\leq P(A) \\leq 1$', '$0 \\leq P(A) \\leq 1$', '$P(A) > 0$', '$P(A) = P(A^c)$'],
    correctIndex: 1,
    explanation: 'Probabilities are always between 0 (impossible) and 1 (certain). This is one of the Kolmogorov axioms.',
    realWorld: 'Ensuring model outputs are valid probabilities is why we use softmax and sigmoid activations.',
    hint: 'Probability can never be negative or greater than certainty.',
  },
  {
    id: 78,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["probability-rules"],
    question: 'The complement rule states $P(A^c) = $?',
    options: ['$P(A)$', '$1 - P(A)$', '$P(A)^2$', '$1/P(A)$'],
    correctIndex: 1,
    explanation: 'The probability of an event not happening is one minus the probability it does happen.',
    realWorld: 'Used in computing the probability of at least one success in multiple independent trials.',
    hint: 'The total probability of everything must sum to 1.',
  },
  {
    id: 79,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["probability-distributions"],
    question: 'The median of a distribution is:',
    options: ['The most frequent value', 'The value that splits the distribution in half', 'The average of all values', 'The range divided by 2'],
    correctIndex: 1,
    explanation: 'The median is the 50th percentile — half the probability mass is above and half below.',
    realWorld: 'Median income is often reported instead of mean because it is robust to extreme outliers.',
    hint: 'It is the middle value that divides the distribution into two equal halves.',
  },
  {
    id: 80,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["probability-distributions"],
    question: 'A uniform distribution on $[a, b]$ means:',
    options: ['All outcomes between $a$ and $b$ are equally likely', 'Most outcomes cluster near the mean', 'The variance is zero', 'Only $a$ and $b$ are possible'],
    correctIndex: 0,
    explanation: 'In a uniform distribution, every value in $[a,b]$ has equal probability density $f(x) = 1/(b-a)$.',
    realWorld: 'Random number generators typically start with uniform distributions before transforming to other shapes.',
    hint: 'The probability density is flat — no region is more likely than another.',
  },
  {
    id: 81,
    topic: 'probability-stats',
    difficulty: 'easy',
    conceptIds: ["expectation-variance"],
    question: 'Standard deviation $\\sigma$ is:',
    options: ['The square of the variance', 'The square root of the variance', 'The mean of absolute deviations', 'The range of the data'],
    correctIndex: 1,
    explanation: '$\\sigma = \\sqrt{\\text{Var}(X)}$. It measures spread in the same units as the data, unlike variance.',
    realWorld: 'Standard deviation is used in z-scores, confidence intervals, and batch normalization in neural networks.',
    hint: 'Take the variance and undo the squaring.',
  },
];
