import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 13,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["expectation-variance"],
    question: 'The variance $\\sigma^2 = E[(X - \\mu)^2]$ measures:',
    options: ['Central tendency', 'Spread of the distribution', 'Skewness', 'Correlation'],
    correctIndex: 1,
    explanation: 'Variance quantifies how far values spread from the mean $\\mu$. Standard deviation $\\sigma$ is its square root.',
    realWorld: 'Variance estimation is critical for risk modeling in finance and uncertainty in ML predictions.',
    hint: 'How far do values typically wander from the center?',
  },
  {
    id: 14,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["probability-distributions"],
    question: 'The Gaussian $\\mathcal{N}(\\mu, \\sigma^2)$ is defined by:',
    options: ['Mean and mode only', 'Mean $\\mu$ and variance $\\sigma^2$', 'Median and range', 'Rate parameter $\\lambda$'],
    correctIndex: 1,
    explanation: 'The normal distribution is fully characterized by its mean $\\mu$ (center) and variance $\\sigma^2$ (spread).',
    realWorld: 'Gaussians underpin noise models, GANs, variational autoencoders, and the Central Limit Theorem.',
    hint: 'This bell curve needs exactly two parameters: center and width.',
  },
  {
    id: 35,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["sampling-convergence"],
    question: 'The Central Limit Theorem states that sample means converge to:',
    options: ['A uniform distribution', 'A Poisson distribution', 'A normal distribution', 'The population median'],
    correctIndex: 2,
    explanation: 'Regardless of the population distribution, the mean of sufficiently large samples will be approximately normally distributed.',
    realWorld: 'CLT justifies using normal distributions for confidence intervals and hypothesis testing in data science.',
    hint: 'Average enough samples from any distribution and a familiar bell shape emerges.',
  },
  {
    id: 82,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["dependence-correlation"],
    question: 'Covariance $\\text{Cov}(X, Y) > 0$ indicates:',
    options: ['X and Y are independent', 'X and Y tend to increase together', 'X causes Y', 'X and Y have the same distribution'],
    correctIndex: 1,
    explanation: 'Positive covariance means when X is above its mean, Y tends to be above its mean too. It does NOT imply causation.',
    realWorld: 'Covariance matrices are central to PCA and portfolio optimization in finance.',
    hint: 'When one variable goes up, the other tends to follow.',
  },
  {
    id: 83,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["sampling-convergence"],
    question: 'The law of large numbers states that as $n \\to \\infty$:',
    options: ['Variance goes to infinity', 'The sample mean converges to the population mean', 'All outcomes become equally likely', 'The distribution becomes uniform'],
    correctIndex: 1,
    explanation: 'As sample size grows, the sample mean $\\bar{X}_n$ converges to $E[X]$ — the theoretical average.',
    realWorld: 'Justifies Monte Carlo methods and empirical risk minimization in machine learning.',
    hint: 'More data means the average gets closer to the true expected value.',
  },
  {
    id: 84,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["probability-distributions"],
    question: 'A Bernoulli random variable $X \\sim \\text{Bern}(p)$ takes values:',
    options: ['Any real number', '0 or 1 with $P(X=1) = p$', 'Integers from 0 to $n$', 'Only positive values'],
    correctIndex: 1,
    explanation: 'A Bernoulli trial has exactly two outcomes: success (1) with probability $p$ and failure (0) with probability $1-p$.',
    realWorld: 'Models coin flips, click/no-click, and binary classification outcomes.',
    hint: 'The simplest random variable — just success or failure.',
  },
  {
    id: 85,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["dependence-correlation"],
    question: 'The correlation coefficient $\\rho_{XY}$ ranges between:',
    options: ['$0$ and $1$', '$-1$ and $1$', '$-\\infty$ and $\\infty$', '$0$ and $\\infty$'],
    correctIndex: 1,
    explanation: '$\\rho = \\text{Cov}(X,Y)/(\\sigma_X \\sigma_Y)$ normalizes covariance to $[-1, 1]$. Perfect linear relationships give $\\pm 1$.',
    realWorld: 'Feature correlation analysis guides feature selection and multicollinearity detection in regression.',
    hint: 'It is a normalized version of covariance with fixed bounds.',
  },
  {
    id: 86,
    topic: 'probability-stats',
    difficulty: 'hard',
    conceptIds: ["probability-distributions"],
    question: 'The Poisson distribution $P(X=k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}$ models:',
    options: ['Continuous measurements', 'Count of events in a fixed interval', 'The mean of a sample', 'Time between events'],
    correctIndex: 1,
    explanation: 'Poisson models the number of events in a fixed time/space interval when events occur independently at rate $\\lambda$.',
    realWorld: 'Models website visits per hour, server requests, and rare event occurrences.',
    hint: 'It counts how many times something happens in a fixed window.',
  },
];
