import type { Question } from '../types';

export const sotaQuestions: Question[] = [
  {
    id: 15,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["statistical-inference"],
    question: 'In hypothesis testing, a p-value of 0.03 means:',
    options: ['3% chance the alternative is true', 'The result is 97% accurate', 'Under $H_0$, this extreme a result occurs 3% of the time', 'The effect size is 0.03'],
    correctIndex: 2,
    explanation: 'The p-value is the probability of seeing data this extreme assuming the null hypothesis $H_0$ is true.',
    realWorld: 'p-values guide decisions in clinical trials and A/B tests at tech companies.',
    hint: 'Assume the null is true — how surprising is this result?',
  },
  {
    id: 25,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["information-measures"],
    question: 'KL divergence $D_{KL}(P \\| Q) = \\sum_x P(x) \\log \\frac{P(x)}{Q(x)}$ measures:',
    options: ['Distance between two points', 'How much $P$ differs from $Q$', 'Correlation between $P$ and $Q$', 'The entropy of $P$'],
    correctIndex: 1,
    explanation: 'KL divergence quantifies information lost when approximating distribution $P$ with $Q$. It is not symmetric.',
    realWorld: 'KL divergence is the loss in variational autoencoders (VAEs) and policy gradient methods in RL.',
    hint: 'It measures the information cost of using Q to approximate P.',
  },
  {
    id: 36,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["statistical-inference"],
    question: 'Maximum Likelihood Estimation (MLE) finds parameters $\\theta$ that:',
    options: ['Minimize the prior probability', 'Maximize $P(\\text{data} | \\theta)$', 'Minimize the entropy', 'Maximize the p-value'],
    correctIndex: 1,
    explanation: 'MLE selects $\\theta^* = \\arg\\max_\\theta P(\\text{data}|\\theta)$, making the observed data most probable under the model.',
    realWorld: 'MLE trains logistic regression, fits Gaussian mixture models, and underlies many ML algorithms.',
    hint: 'Which parameters make the observed data most likely?',
  },
  {
    id: 87,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["information-measures"],
    question: 'The entropy $H(X) = -\\sum_x P(x)\\log P(x)$ is maximized when:',
    options: ['$X$ is deterministic', '$X$ is uniform over all outcomes', '$P(x) = 1$ for one outcome', 'The variance is zero'],
    correctIndex: 1,
    explanation: 'Maximum entropy occurs when all outcomes are equally likely — maximum uncertainty. This is the uniform distribution.',
    realWorld: 'Maximum entropy principle is used in language modeling and natural language processing.',
    hint: 'The most uncertain distribution has no preference for any particular outcome.',
  },
  {
    id: 88,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["bayesian-inference"],
    question: 'MAP estimation differs from MLE by:',
    options: ['Using a different loss function', 'Incorporating a prior distribution $P(\\theta)$', 'Not using the likelihood', 'Requiring more data'],
    correctIndex: 1,
    explanation: 'MAP maximizes $P(\\theta|\\text{data}) \\propto P(\\text{data}|\\theta)P(\\theta)$. The prior acts as regularization.',
    realWorld: 'MAP with a Gaussian prior is equivalent to L2 regularization (Ridge regression).',
    hint: 'It adds prior beliefs about the parameters to the likelihood.',
  },
  {
    id: 89,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["information-measures"],
    question: 'The mutual information $I(X;Y)$ measures:',
    options: ['Linear correlation only', 'The shared information between $X$ and $Y$', 'The causal effect of $X$ on $Y$', 'The joint entropy'],
    correctIndex: 1,
    explanation: '$I(X;Y) = H(X) - H(X|Y) = D_{KL}(P_{XY} \\| P_X P_Y)$. It captures all dependencies, not just linear ones.',
    realWorld: 'Used in feature selection, information bottleneck method, and representation learning.',
    hint: 'How much does knowing Y reduce your uncertainty about X?',
  },
  {
    id: 90,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["bayesian-inference"],
    question: 'A conjugate prior means:',
    options: ['The prior equals the posterior', 'The posterior belongs to the same family as the prior', 'The prior is always uniform', 'The likelihood is Gaussian'],
    correctIndex: 1,
    explanation: 'When the posterior has the same functional form as the prior, Bayesian updates are computationally convenient.',
    realWorld: 'Beta-Binomial and Normal-Normal are conjugate pairs used in online learning and A/B testing.',
    hint: 'The prior and posterior are from the same distribution family.',
  },
  {
    id: 91,
    topic: 'probability-stats',
    difficulty: 'sota',
    conceptIds: ["statistical-inference"],
    question: 'The Cramér-Rao lower bound states that the variance of an unbiased estimator is at least:',
    options: ['Zero', '$1/I(\\theta)$ where $I(\\theta)$ is the Fisher information', 'The population variance', '$1/n$'],
    correctIndex: 1,
    explanation: 'No unbiased estimator can have variance smaller than $1/I(\\theta)$. The Fisher information measures how much data tells about $\\theta$.',
    realWorld: 'Guides the design of efficient estimators and neural network architectures for statistical tasks.',
    hint: 'There is a fundamental limit on how precisely you can estimate a parameter.',
  },
];
