import type { Question } from '../types';

export const informationTheoryQuestions: Question[] = [
  {
    id: 187001, topic: 'information-theory', difficulty: 'easy',
    question: 'Shannon entropy $H(X) = -\\sum p(x) \\log_2 p(x)$ measures:',
    options: ['The average uncertainty or information content of a random variable', 'The maximum value of $X$', 'The variance of $X$', 'The mean of $X$'],
    correctIndex: 0,
    explanation: 'Entropy quantifies the average number of bits needed to encode outcomes of $X$. High entropy = high uncertainty = more information per observation.',
    realWorld: 'A fair coin has 1 bit of entropy; English text has ~1.0-1.5 bits per character (much less than the 4.7 bits of a uniform 26-letter alphabet).',
    hint: 'More unpredictable = more entropy = more information.',
  },
  {
    id: 187002, topic: 'information-theory', difficulty: 'easy',
    question: 'Data compression is fundamentally limited by:',
    options: ['Shannon\'s source coding theorem — entropy is the minimum average bits per symbol', 'Available RAM', 'CPU speed', 'File format restrictions'],
    correctIndex: 0,
    explanation: 'Shannon proved that no lossless compression can represent data using fewer than $H(X)$ bits per symbol on average. This is the entropy rate of the source.',
    realWorld: 'ZIP, gzip, and zstd all approach the entropy limit for typical files.',
    hint: 'You can\'t compress below the information content — entropy is the hard floor.',
  },
  {
    id: 187003, topic: 'information-theory', difficulty: 'easy',
    question: 'Mutual information $I(X;Y)$ measures:',
    options: ['How much knowing $X$ reduces uncertainty about $Y$ (and vice versa)', 'The correlation coefficient', 'The joint probability', 'The conditional variance'],
    correctIndex: 0,
    explanation: '$I(X;Y) = H(X) - H(X|Y) = H(Y) - H(Y|X)$. It captures all statistical dependencies (not just linear ones like correlation).',
    realWorld: 'Feature selection in ML often uses mutual information to find the most informative features.',
    hint: 'If $X$ and $Y$ are independent, $I(X;Y) = 0$. The more dependent, the higher the MI.',
  },
  {
    id: 187004, topic: 'information-theory', difficulty: 'hard',
    question: 'The channel capacity $C = \\max_{p(x)} I(X;Y)$ of the binary symmetric channel with error probability $p$ is:',
    options: ['$C = 1 - H(p) = 1 + p\\log_2 p + (1-p)\\log_2(1-p)$', '$C = 1 - p$', '$C = p \\log_2 p$', '$C = 2(1-p)$'],
    correctIndex: 0,
    explanation: 'The BSC flips each bit with probability $p$. Capacity is $1 - H(p)$ bits per channel use, where $H(p) = -p\\log p - (1-p)\\log(1-p)$ is the binary entropy.',
    realWorld: 'This sets the theoretical limit for reliable communication over noisy binary channels.',
    hint: 'When $p = 0$ (no errors), $C = 1$ bit. When $p = 0.5$ (random), $C = 0$ bits.',
  },
  {
    id: 187005, topic: 'information-theory', difficulty: 'hard',
    question: 'The KL divergence $D_{KL}(P \\| Q) = \\sum p(x) \\log \\frac{p(x)}{q(x)}$ measures:',
    options: ['The information lost when $Q$ is used to approximate $P$ (not symmetric)', 'The distance between $P$ and $Q$ (symmetric)', 'The entropy of $P$', 'The mutual information between $P$ and $Q$'],
    correctIndex: 0,
    explanation: 'KL divergence is not a true distance (not symmetric: $D_{KL}(P\\|Q) \\neq D_{KL}(Q\\|P)$). It measures the extra bits needed when using code optimized for $Q$ to encode samples from $P$.',
    realWorld: 'KL divergence is the loss function for training neural networks (cross-entropy loss = $H(P) + D_{KL}(P\\|Q)$).',
    hint: 'It is always $\\geq 0$ (Gibbs\' inequality) and equals 0 iff $P = Q$.',
  },
  {
    id: 187006, topic: 'information-theory', difficulty: 'hard',
    question: 'The rate-distortion function $R(D)$ characterizes the minimum bit rate to represent a source with distortion $\\leq D$. For a Gaussian source with MSE distortion:',
    options: ['$R(D) = \\frac{1}{2}\\log_2(\\sigma^2/D)$ for $D \\leq \\sigma^2$', '$R(D) = \\sigma^2 - D$', '$R(D) = D/\\sigma^2$', '$R(D) = \\log_2(1/D)$'],
    correctIndex: 0,
    explanation: 'For a Gaussian source $\\mathcal{N}(0,\\sigma^2)$ with MSE distortion, the rate-distortion function is $R(D) = \\frac{1}{2}\\log_2(\\sigma^2/D)$. This is the fundamental limit of lossy compression.',
    realWorld: 'JPEG, MP3, and video codecs all operate near the rate-distortion limit for their respective sources.',
    hint: 'Halving the distortion requires one extra bit per sample — logarithmic tradeoff.',
  },
  {
    id: 187007, topic: 'information-theory', difficulty: 'sota',
    question: 'The information bottleneck principle in deep learning suggests that DNNs learn by:',
    options: ['Compressing input information while preserving task-relevant information about the output', 'Memorizing all training data', 'Maximizing mutual information with the input', 'Minimizing entropy of all layers'],
    correctIndex: 0,
    explanation: 'The information bottleneck (Tishby, 2015) posits that each DNN layer progressively compresses input $I(X;T)$ while retaining output-relevant information $I(T;Y)$: $\\min I(X;T) - \\beta I(T;Y)$.',
    realWorld: 'This theory explains why deep networks generalize: they learn minimal sufficient statistics.',
    hint: 'Compress the representation (forget irrelevant input details), keep what matters for prediction.',
  },
  {
    id: 187008, topic: 'information-theory', difficulty: 'sota',
    question: 'Polar codes (Arıkan, 2009) are notable because they:',
    options: ['Are the first provably capacity-achieving codes with efficient $O(n \\log n)$ encoding/decoding', 'Have the lowest latency', 'Work only for erasure channels', 'Require exponential decoding time'],
    correctIndex: 0,
    explanation: 'Polar codes use channel polarization: synthetic channels split into perfectly reliable and perfectly unreliable ones. Information is sent only on reliable channels. They provably achieve Shannon capacity.',
    realWorld: 'Polar codes are used in 5G NR control channels — the first practical capacity-achieving code in a deployed standard.',
    hint: 'Arıkan\'s polarization: some channels become perfect, others become useless — use only the good ones.',
  },
  {
    id: 187009, topic: 'information-theory', difficulty: 'sota',
    question: 'The connection between information theory and thermodynamics is formalized by Landauer\'s principle, which states:',
    options: ['Erasing one bit of information dissipates at least $kT\\ln 2$ joules of heat', 'Information has no physical cost', 'Entropy always increases in information systems', 'Computation requires infinite energy'],
    correctIndex: 0,
    explanation: 'Landauer (1961): irreversible computation (bit erasure) has a minimum energy cost of $kT\\ln 2 \\approx 3 \\times 10^{-21}$ J at room temperature. This links Shannon entropy to thermodynamic entropy.',
    realWorld: 'Modern chips dissipate ~1000× more than the Landauer limit per operation — room for improvement!',
    hint: 'Deleting information generates heat — Maxwell\'s demon must pay the energy price.',
  },
];
