import type { Question } from '../types';

export const informationTheoryQuestions: Question[] = [
  {
    id: 187001, topic: 'information-theory', difficulty: 'easy',
    conceptIds: ["entropy-information-dependence"],
    question: 'Shannon entropy $H(X) = -\\sum p(x) \\log_2 p(x)$ measures:',
    options: ['The most probable outcome produced by the source', 'The average uncertainty carried by source outcomes', 'The variance of the numerical source symbols', 'The average distance between possible source outcomes'],
    correctIndex: 1,
    explanation: 'Entropy quantifies the average number of bits needed to encode outcomes of $X$. High entropy = high uncertainty = more information per observation.',
    realWorld: 'A fair coin has 1 bit of entropy; English text has ~1.0-1.5 bits per character (much less than the 4.7 bits of a uniform 26-letter alphabet).',
    hint: 'More unpredictable = more entropy = more information.',
  },
  {
    id: 187002, topic: 'information-theory', difficulty: 'easy',
    conceptIds: ["source-coding-rate-distortion"],
    question: 'Data compression is fundamentally limited by:',
    options: ['The maximum clock speed available to the encoder', 'The amount of temporary memory available during coding', 'The source entropy rate for lossless coding', 'The number of headers required by the file format'],
    correctIndex: 2,
    explanation: 'Shannon proved that no lossless compression can represent data using fewer than $H(X)$ bits per symbol on average. This is the entropy rate of the source.',
    realWorld: 'ZIP, gzip, and zstd all approach the entropy limit for typical files.',
    hint: 'You can\'t compress below the information content — entropy is the hard floor.',
  },
  {
    id: 187003, topic: 'information-theory', difficulty: 'easy',
    conceptIds: ["entropy-information-dependence"],
    question: 'Mutual information $I(X;Y)$ measures:',
    options: ['The variance shared by two random variables', 'The reduction in uncertainty about one variable from knowing the other', 'The probability that both variables take the same value', 'The average distance between samples from the variables'],
    correctIndex: 1,
    explanation: '$I(X;Y) = H(X) - H(X|Y) = H(Y) - H(Y|X)$. It captures all statistical dependencies (not just linear ones like correlation).',
    realWorld: 'Feature selection in ML often uses mutual information to find the most informative features.',
    hint: 'If $X$ and $Y$ are independent, $I(X;Y) = 0$. The more dependent, the higher the MI.',
  },
  {
    id: 187004, topic: 'information-theory', difficulty: 'hard',
    conceptIds: ["channel-capacity-coding"],
    question: 'The channel capacity $C = \\max_{p(x)} I(X;Y)$ of the binary symmetric channel with error probability $p$ is:',
    options: ['$C = H(p)$', '$C = 1 - H(p)$', '$C = 1 - p$', '$C = 1 - 2p$'],
    correctIndex: 1,
    explanation: 'The BSC flips each bit with probability $p$. Capacity is $1 - H(p)$ bits per channel use, where $H(p) = -p\\log p - (1-p)\\log(1-p)$ is the binary entropy.',
    realWorld: 'This sets the theoretical limit for reliable communication over noisy binary channels.',
    hint: 'When $p = 0$ (no errors), $C = 1$ bit. When $p = 0.5$ (random), $C = 0$ bits.',
  },
  {
    id: 187005, topic: 'information-theory', difficulty: 'hard',
    conceptIds: ["entropy-information-dependence"],
    question: 'The KL divergence $D_{KL}(P \\| Q) = \\sum p(x) \\log \\frac{p(x)}{q(x)}$ measures:',
    options: ['A symmetric metric distance between two probability distributions', 'The entropy contained in the reference distribution alone', 'The extra information cost of approximating $P$ with $Q$', 'The linear correlation between samples drawn from $P$ and $Q$'],
    correctIndex: 2,
    explanation: 'KL divergence is not a true distance (not symmetric: $D_{KL}(P\\|Q) \\neq D_{KL}(Q\\|P)$). It measures the extra bits needed when using code optimized for $Q$ to encode samples from $P$.',
    realWorld: 'KL divergence is the loss function for training neural networks (cross-entropy loss = $H(P) + D_{KL}(P\\|Q)$).',
    hint: 'It is always $\\geq 0$ (Gibbs\' inequality) and equals 0 iff $P = Q$.',
  },
  {
    id: 187006, topic: 'information-theory', difficulty: 'hard',
    conceptIds: ["source-coding-rate-distortion"],
    question: 'The rate-distortion function $R(D)$ characterizes the minimum bit rate to represent a source with distortion $\\leq D$. For a Gaussian source with MSE distortion:',
    options: ['$R(D) = \\log_2(\\sigma^2/D)$ for $0 < D \\leq \\sigma^2$', '$R(D) = \\frac{1}{2}\\log_2(\\sigma^2/D)$ for $0 < D \\leq \\sigma^2$', '$R(D) = D/\\sigma^2$ for $0 < D \\leq \\sigma^2$', '$R(D) = \\sigma^2 - D$ for $0 < D \\leq \\sigma^2$'],
    correctIndex: 1,
    explanation: 'For a Gaussian source $\\mathcal{N}(0,\\sigma^2)$ with MSE distortion, the rate-distortion function is $R(D) = \\frac{1}{2}\\log_2(\\sigma^2/D)$. This is the fundamental limit of lossy compression.',
    realWorld: 'JPEG, MP3, and video codecs all operate near the rate-distortion limit for their respective sources.',
    hint: 'Halving the distortion requires one extra bit per sample — logarithmic tradeoff.',
  },
  {
    id: 187007, topic: 'information-theory', difficulty: 'sota',
    conceptIds: ["entropy-information-dependence"],
    question: 'The information bottleneck principle in deep learning suggests that DNNs learn by:',
    options: ['Preserving every input detail while minimizing output entropy', 'Compressing input information while retaining output-relevant information', 'Maximizing information about the input at every hidden layer', 'Discarding output information while expanding input representations'],
    correctIndex: 1,
    explanation: 'The information bottleneck (Tishby, 2015) posits that each DNN layer progressively compresses input $I(X;T)$ while retaining output-relevant information $I(T;Y)$: $\\min I(X;T) - \\beta I(T;Y)$.',
    realWorld: 'This theory explains why deep networks generalize: they learn minimal sufficient statistics.',
    hint: 'Compress the representation (forget irrelevant input details), keep what matters for prediction.',
    paper: {
      title: 'Deep Learning and the Information Bottleneck Principle',
      url: 'https://arxiv.org/abs/1503.02406',
      venue: 'IEEE Information Theory Workshop',
      year: 2015,
    },
    reviewedAt: '2026-10-03',
  },
  {
    id: 187008, topic: 'information-theory', difficulty: 'sota',
    conceptIds: ["channel-capacity-coding"],
    question: 'Polar codes (Arıkan, 2009) are notable because they:',
    options: ['They achieve capacity only with superlinear polynomial decoding', 'They use channel polarization and achieve capacity with $O(n \\log n)$ algorithms', 'They attain minimum latency for every finite block length', 'They work only when the physical channel is an erasure channel'],
    correctIndex: 1,
    explanation: 'Polar codes use channel polarization: synthetic channels split into perfectly reliable and perfectly unreliable ones. Information is sent only on reliable channels. They provably achieve Shannon capacity.',
    realWorld: 'Polar codes are used in 5G NR control channels — the first practical capacity-achieving code in a deployed standard.',
    hint: 'Arıkan\'s polarization: some channels become perfect, others become useless — use only the good ones.',
    paper: {
      title: 'Channel polarization: A method for constructing capacity-achieving codes for symmetric binary-input memoryless channels',
      url: 'https://arxiv.org/abs/0807.3917',
      venue: 'IEEE Transactions on Information Theory',
      year: 2009,
    },
    reviewedAt: '2026-10-03',
  },
  {
    id: 187009, topic: 'information-theory', difficulty: 'sota',
    conceptIds: ["entropy-information-dependence"],
    question: 'The connection between information theory and thermodynamics is formalized by Landauer\'s principle, which states:',
    options: ['Reversible logic must dissipate $kT\\ln 2$ for every gate transition', 'Erasing one bit has a minimum heat cost of $kT\\ln 2$', 'Every arithmetic operation must consume at least one joule', 'Information storage has zero thermodynamic entropy at equilibrium'],
    correctIndex: 1,
    explanation: 'Landauer (1961): irreversible computation (bit erasure) has a minimum energy cost of $kT\\ln 2 \\approx 3 \\times 10^{-21}$ J at room temperature. This links Shannon entropy to thermodynamic entropy.',
    realWorld: 'Modern chips dissipate ~1000× more than the Landauer limit per operation — room for improvement!',
    hint: 'Deleting information generates heat — Maxwell\'s demon must pay the energy price.',
    sources: [
      {
        title: 'Irreversibility and Heat Generation in the Computing Process',
        url: 'https://doi.org/10.1147/rd.53.0183',
        publisher: 'IBM Journal of Research and Development',
        year: 1961,
      },
    ],
    reviewedAt: '2026-10-03',
  },
];
