import type { Question } from '../types';

// ── SIE: Securities Industry Essentials ──
export const sieQuestions: Question[] = [
  {
    id: 83000,
    topic: 'sie',
    difficulty: 'easy',
    question: 'The primary market refers to:',
    options: [
      'The market where new securities are issued and sold for the first time (IPOs)',
      'The market where existing securities are traded between investors',
      'The over-the-counter derivatives market',
      'The foreign exchange market',
    ],
    correctIndex: 0,
    explanation: 'Primary market is where issuers raise capital by selling new securities directly to investors, typically through underwriters.',
    realWorld: 'Investment banks earn underwriting fees by facilitating IPOs in the primary market.',
    hint: 'Primary = first time. Secondary = after that.',
  },
  {
    id: 83001,
    topic: 'sie',
    difficulty: 'easy',
    question: 'FINRA\'s primary role in the securities industry is to:',
    options: [
      'Regulate broker-dealers and protect investors through enforcement of rules and standards',
      'Set monetary policy for the United States',
      'Insure bank deposits up to $250,000',
      'Manage the Federal Reserve System',
    ],
    correctIndex: 0,
    explanation: 'FINRA is the largest self-regulatory organization (SRO) for broker-dealers, overseeing firms and registered representatives.',
    realWorld: 'FINRA conducts examinations, enforces rules, and administers qualification exams like the SIE and Series 7.',
    hint: 'It\'s a self-regulatory organization, not a government agency.',
  },
  {
    id: 83002,
    topic: 'sie',
    difficulty: 'hard',
    question: 'Under SEC Rule 144, restricted securities may be sold publicly after:',
    options: [
      'A holding period of at least 6 months (for reporting companies) with volume limitations',
      'Immediate resale with no restrictions',
      'A 30-day waiting period only',
      'Only after the company goes bankrupt',
    ],
    correctIndex: 0,
    explanation: 'Rule 144 permits resale of restricted/control securities after holding periods (6 months reporting, 1 year non-reporting) with volume and manner of sale conditions.',
    realWorld: 'Startup employees with stock options must understand Rule 144 before selling shares post-IPO.',
    hint: 'There\'s a holding period and volume limits for insider sales.',
  },
  {
    id: 83003,
    topic: 'sie',
    difficulty: 'hard',
    question: 'The Securities Investor Protection Corporation (SIPC) protects customers when:',
    options: [
      'A broker-dealer fails and customer assets are missing, up to $500,000 per customer',
      'A stock\'s price declines due to market conditions',
      'A mutual fund underperforms its benchmark',
      'Interest rates rise causing bond prices to fall',
    ],
    correctIndex: 0,
    explanation: 'SIPC covers up to $500K ($250K cash) when a brokerage fails. It does NOT protect against market losses.',
    realWorld: 'When Lehman Brothers collapsed, SIPC helped transfer customer accounts to solvent firms.',
    hint: 'It protects against brokerage failure, not investment losses.',
  },
  {
    id: 83004,
    topic: 'sie',
    difficulty: 'sota',
    question: 'Regulation Best Interest (Reg BI) requires broker-dealers to:',
    options: [
      'Act in the best interest of retail customers at the time of a recommendation, considering costs and conflicts',
      'Charge the lowest fees in the industry',
      'Only recommend proprietary products',
      'Provide the same duty of care as a registered investment adviser',
    ],
    correctIndex: 0,
    explanation: 'Reg BI (2020) enhances the suitability standard with disclosure, care, conflict of interest, and compliance obligations, but stops short of a full fiduciary duty.',
    realWorld: 'Broker-dealers had to overhaul compliance programs to implement Reg BI\'s four component obligations.',
    hint: 'It\'s higher than suitability but not quite a fiduciary standard.',
  },
];

// ── Series 7: General Securities Representative ──
export const series7Questions: Question[] = [
  {
    id: 83100,
    topic: 'series-7',
    difficulty: 'easy',
    question: 'A call option gives the holder the right to:',
    options: [
      'Buy the underlying security at the strike price before expiration',
      'Sell the underlying security at the strike price',
      'Receive dividends from the underlying stock',
      'Vote at the company\'s shareholder meeting',
    ],
    correctIndex: 0,
    explanation: 'A call option is the right (not obligation) to buy at the strike price. The writer has the obligation to sell if exercised.',
    realWorld: 'Equity options trade on exchanges like CBOE with standardized contracts of 100 shares each.',
    hint: 'Call = right to buy. Put = right to sell.',
  },
  {
    id: 83101,
    topic: 'series-7',
    difficulty: 'easy',
    question: 'Municipal bonds are attractive to investors primarily because:',
    options: [
      'Interest income is generally exempt from federal income tax',
      'They always offer the highest yields available',
      'They are guaranteed by the federal government',
      'They have no credit risk',
    ],
    correctIndex: 0,
    explanation: 'Municipal bond interest is typically exempt from federal tax and often from state/local tax for in-state residents, creating a tax-equivalent yield advantage.',
    realWorld: 'High-income investors in the 37% bracket benefit significantly from munis\' tax-exempt status.',
    hint: 'The key advantage is tax treatment, not absolute yield.',
  },
  {
    id: 83102,
    topic: 'series-7',
    difficulty: 'hard',
    question: 'In options trading, the maximum loss for a covered call writer is:',
    options: [
      'The purchase price of the stock minus the premium received',
      'Unlimited',
      'The strike price only',
      'Zero, because the premium provides full protection',
    ],
    correctIndex: 0,
    explanation: 'A covered call writer owns the stock, so max loss occurs if the stock goes to zero: Cost basis - Premium received. The premium provides only limited downside cushion.',
    realWorld: 'Income-oriented investors write covered calls on dividend stocks to generate additional yield.',
    hint: 'You still own the stock — what happens if it goes to zero?',
  },
  {
    id: 83103,
    topic: 'series-7',
    difficulty: 'hard',
    question: 'A customer\'s margin account has a long market value of $100,000 and a debit balance of $60,000. The equity is:',
    options: [
      '$40,000 (40% equity)',
      '$60,000',
      '$100,000',
      '$160,000',
    ],
    correctIndex: 0,
    explanation: 'Equity = Market Value - Debit Balance = $100,000 - $60,000 = $40,000. The maintenance requirement is typically 25%, so $40,000 > $25,000 minimum.',
    realWorld: 'Margin calls are issued when equity falls below maintenance requirements, forcing liquidation or additional deposits.',
    hint: 'Equity = what you own minus what you owe.',
  },
  {
    id: 83104,
    topic: 'series-7',
    difficulty: 'sota',
    question: 'A variable annuity\'s separate account is structured as:',
    options: [
      'A registered investment company (mutual fund) that pools contributions into subaccounts',
      'A guaranteed fixed-rate account',
      'A bank savings account insured by FDIC',
      'A money market fund with stable NAV',
    ],
    correctIndex: 0,
    explanation: 'The separate account is legally distinct from the insurer\'s general account, registered under the Investment Company Act of 1940, with investment risk borne by the contract owner.',
    realWorld: 'Variable annuities are dual-regulated as both insurance products (state) and securities (SEC/FINRA).',
    hint: 'Variable = investment risk to the owner. The account must be "separate" from the insurer\'s assets.',
  },
];

// ── Series 63: Uniform Securities Agent State Law ──
export const series63Questions: Question[] = [
  {
    id: 83200,
    topic: 'series-63',
    difficulty: 'easy',
    question: 'Under the Uniform Securities Act, a "security" includes all of the following EXCEPT:',
    options: [
      'A fixed annuity issued by an insurance company',
      'Common stock',
      'An investment contract',
      'A bond',
    ],
    correctIndex: 0,
    explanation: 'Fixed annuities are insurance products excluded from the definition of a security. Variable annuities ARE securities.',
    realWorld: 'This distinction determines whether a product requires securities registration and a licensed representative.',
    hint: 'Insurance products with guaranteed returns are generally not securities.',
  },
  {
    id: 83201,
    topic: 'series-63',
    difficulty: 'easy',
    question: 'State registration of securities by "coordination" means:',
    options: [
      'The state registration becomes effective simultaneously with the federal SEC registration',
      'The issuer must register in every state individually',
      'No state registration is required',
      'Only the SEC approves the offering',
    ],
    correctIndex: 0,
    explanation: 'Registration by coordination allows a federal registration (e.g., S-1) to automatically become effective at the state level when the SEC registration goes effective.',
    realWorld: 'IPOs typically use coordination to avoid separate state-by-state filing processes.',
    hint: 'It "coordinates" with the federal registration timing.',
  },
  {
    id: 83202,
    topic: 'series-63',
    difficulty: 'hard',
    question: 'Under state securities law, the Administrator may deny registration of a broker-dealer if:',
    options: [
      'The applicant has been convicted of a securities-related felony within the past 10 years',
      'The applicant\'s firm is located in another state',
      'The applicant has fewer than 5 years of experience',
      'The applicant is under age 30',
    ],
    correctIndex: 0,
    explanation: 'The Administrator can deny, suspend, or revoke registration based on felony convictions (securities-related within 10 years), injunctions, or violations of securities laws.',
    realWorld: 'State securities regulators coordinate through NASAA to share disciplinary information across jurisdictions.',
    hint: 'Criminal history related to securities is a statutory disqualification.',
  },
  {
    id: 83203,
    topic: 'series-63',
    difficulty: 'hard',
    question: 'An agent\'s registration in a state is effective:',
    options: [
      'At noon on the 30th day after filing, unless the Administrator issues a stop order',
      'Immediately upon filing',
      'Only after passing an additional state exam',
      'After 90 days regardless of any issues',
    ],
    correctIndex: 0,
    explanation: 'State registrations become effective by operation of law at noon on the 30th day unless the Administrator acts to delay or deny.',
    realWorld: 'This automatic effectiveness provision prevents bureaucratic delays from blocking legitimate registrations.',
    hint: 'There\'s a specific day and time when it becomes effective by default.',
  },
  {
    id: 83204,
    topic: 'series-63',
    difficulty: 'sota',
    question: 'The antifraud provisions of state securities law apply to:',
    options: [
      'ALL securities transactions, including exempt securities and exempt transactions',
      'Only registered securities',
      'Only transactions involving broker-dealers',
      'Only offerings above $1 million',
    ],
    correctIndex: 0,
    explanation: 'Antifraud provisions are universal — no exemption from fraud. Even exempt securities (government bonds, etc.) are subject to antifraud rules.',
    realWorld: 'This is a key principle: you can exempt from registration, but never from antifraud.',
    hint: 'Nothing is exempt from anti-fraud provisions.',
  },
];

// ── Series 65: Uniform Investment Adviser Law ──
export const series65Questions: Question[] = [
  {
    id: 83300,
    topic: 'series-65',
    difficulty: 'easy',
    question: 'An investment adviser has a fiduciary duty to clients, which means the adviser must:',
    options: [
      'Act in the client\'s best interest at all times and disclose all material conflicts',
      'Guarantee investment returns',
      'Only recommend the lowest-cost investments',
      'Achieve returns above the market benchmark',
    ],
    correctIndex: 0,
    explanation: 'Fiduciary duty encompasses loyalty (client\'s interest first), care (diligent analysis), and full disclosure of conflicts.',
    realWorld: 'The SEC vs. Capital Gains Research Bureau (1963) established the fiduciary standard for advisers under the Investment Advisers Act.',
    hint: 'Fiduciary = highest standard of care, above suitability.',
  },
  {
    id: 83301,
    topic: 'series-65',
    difficulty: 'easy',
    question: 'Modern Portfolio Theory (MPT) suggests that portfolio risk can be reduced by:',
    options: [
      'Combining assets with low or negative correlations (diversification)',
      'Concentrating in a single high-performing asset',
      'Only investing in risk-free assets',
      'Maximizing the beta of the portfolio',
    ],
    correctIndex: 0,
    explanation: 'MPT shows that portfolio variance depends on individual variances AND covariances. Low correlation reduces the portfolio\'s overall risk without proportionally reducing return.',
    realWorld: 'Harry Markowitz won the 1990 Nobel Prize for MPT, which forms the basis of modern asset allocation.',
    hint: 'Don\'t put all your eggs in one basket — mathematically proven.',
  },
  {
    id: 83302,
    topic: 'series-65',
    difficulty: 'hard',
    question: 'Under the Investment Advisers Act of 1940, an adviser with AUM of $100 million or more must:',
    options: [
      'Register with the SEC (federal registration)',
      'Register only with the state',
      'Register with both the SEC and the state',
      'No registration is required above $100 million',
    ],
    correctIndex: 0,
    explanation: 'Dodd-Frank set the threshold: ≥$100M AUM → SEC registration. <$100M → state registration (unless an exemption applies).',
    realWorld: 'The SEC/state division of regulatory authority was clarified by the Dodd-Frank Act of 2010.',
    hint: 'There\'s a clear AUM threshold separating SEC from state registration.',
  },
  {
    id: 83303,
    topic: 'series-65',
    difficulty: 'hard',
    question: 'The Sharpe ratio measures:',
    options: [
      'Excess return per unit of total risk (standard deviation)',
      'Total return divided by beta',
      'Alpha relative to the benchmark',
      'The maximum drawdown of a portfolio',
    ],
    correctIndex: 0,
    explanation: 'Sharpe = $(R_p - R_f) / \\sigma_p$. Higher is better. It rewards return but penalizes total volatility.',
    realWorld: 'Hedge funds and mutual funds are commonly ranked by Sharpe ratio for risk-adjusted performance comparison.',
    hint: 'It divides excess return by standard deviation.',
  },
  {
    id: 83304,
    topic: 'series-65',
    difficulty: 'sota',
    question: 'A wrap fee program bundles advisory fees, brokerage, and custody into a single fee, creating a potential conflict because:',
    options: [
      'The adviser may have an incentive to trade less (since commissions are included) even when trading would benefit the client',
      'The adviser is incentivized to overtrade',
      'Wrap fees are always lower than unbundled fees',
      'There are no conflicts in wrap programs',
    ],
    correctIndex: 0,
    explanation: 'Since the adviser pays trading costs from the wrap fee, there\'s an incentive to minimize trading (reverse churning), potentially harming clients who need active management.',
    realWorld: 'The SEC has brought enforcement actions against advisers for "reverse churning" in wrap accounts.',
    hint: 'When trading costs come out of your fee, you\'re incentivized to trade less.',
  },
];

// ── Series 66: Uniform Combined State Law ──
export const series66Questions: Question[] = [
  {
    id: 83400,
    topic: 'series-66',
    difficulty: 'easy',
    question: 'The Series 66 exam combines content from which two exams?',
    options: [
      'Series 63 (state securities law) and Series 65 (investment adviser law)',
      'Series 7 and Series 63',
      'SIE and Series 7',
      'Series 24 and Series 52',
    ],
    correctIndex: 0,
    explanation: 'The Series 66 is a combined exam covering both state securities agent law (63) and investment adviser representative law (65).',
    realWorld: 'Many financial advisors take the SIE + Series 7 + Series 66 to be fully licensed as both a registered rep and an IAR.',
    hint: 'It\'s the combination of the two state-law exams.',
  },
  {
    id: 83401,
    topic: 'series-66',
    difficulty: 'easy',
    question: 'A person is considered an "investment adviser representative" (IAR) if they:',
    options: [
      'Make investment recommendations or manage client portfolios on behalf of an advisory firm',
      'Only perform clerical tasks at the firm',
      'Work exclusively in the back office',
      'Are a client of the advisory firm',
    ],
    correctIndex: 0,
    explanation: 'An IAR is any individual who provides advice, manages accounts, or solicits for advisory services on behalf of an IA firm.',
    realWorld: 'IARs must pass the Series 65 or 66 and register in the states where they have clients.',
    hint: 'They give advice or manage money for clients of the advisory firm.',
  },
  {
    id: 83402,
    topic: 'series-66',
    difficulty: 'hard',
    question: 'Under state law, an investment adviser\'s contract with a client must include:',
    options: [
      'The services to be provided, the fee structure, and whether the adviser has discretionary authority',
      'A guarantee of minimum returns',
      'The adviser\'s personal tax returns',
      'Only the client\'s social security number',
    ],
    correctIndex: 0,
    explanation: 'State law requires written advisory contracts to disclose services, compensation, term, discretion, and assignment provisions.',
    realWorld: 'Regulators review advisory contracts during examinations to ensure compliance with fiduciary standards.',
    hint: 'The contract must make the relationship terms transparent.',
  },
  {
    id: 83403,
    topic: 'series-66',
    difficulty: 'hard',
    question: 'Performance-based fees (e.g., incentive fees) may only be charged to:',
    options: [
      'Qualified clients meeting minimum net worth or AUM thresholds (e.g., $1.1 million AUM or $2.2 million net worth)',
      'Any retail client',
      'Only institutional clients like pension funds',
      'Clients who have held accounts for more than 5 years',
    ],
    correctIndex: 0,
    explanation: 'SEC Rule 205-3 permits performance fees only for "qualified clients" to protect less sophisticated investors from asymmetric fee structures.',
    realWorld: 'Hedge funds and private wealth managers commonly charge "2 and 20" to qualified clients.',
    hint: 'There are wealth/AUM thresholds to protect smaller investors.',
  },
  {
    id: 83404,
    topic: 'series-66',
    difficulty: 'sota',
    question: 'An investment adviser\'s duty regarding custody of client assets under state law requires:',
    options: [
      'Using a qualified custodian, providing account statements, and undergoing an annual surprise examination',
      'Keeping all client funds in the adviser\'s personal bank account',
      'No special procedures if the adviser is registered',
      'Custody only with a bank that the adviser owns',
    ],
    correctIndex: 0,
    explanation: 'The custody rule protects clients: assets must be with a qualified custodian, clients receive direct statements, and a surprise audit verifies assets exist.',
    realWorld: 'The Madoff fraud highlighted the importance of independent custody and surprise examinations.',
    hint: 'Three safeguards: qualified custodian, statements, surprise exam.',
  },
];

// ── Series 24: General Securities Principal ──
export const series24Questions: Question[] = [
  {
    id: 83500,
    topic: 'series-24',
    difficulty: 'easy',
    question: 'A General Securities Principal (Series 24) is primarily responsible for:',
    options: [
      'Supervising the activities of registered representatives and ensuring firm compliance',
      'Executing trades on behalf of customers',
      'Setting monetary policy',
      'Auditing the firm\'s financial statements',
    ],
    correctIndex: 0,
    explanation: 'Series 24 principals oversee trading, customer accounts, correspondence review, and regulatory compliance for the broker-dealer.',
    realWorld: 'Every FINRA member firm must designate at least one principal to supervise each line of business.',
    hint: 'Principals supervise; representatives execute.',
  },
  {
    id: 83501,
    topic: 'series-24',
    difficulty: 'easy',
    question: 'The net capital rule (SEC Rule 15c3-1) requires broker-dealers to:',
    options: [
      'Maintain minimum net capital to cover liabilities and protect customer assets',
      'Have zero debt at all times',
      'Hold all assets in cash',
      'Distribute all profits to shareholders immediately',
    ],
    correctIndex: 0,
    explanation: 'The net capital rule ensures BDs have sufficient liquid assets to meet obligations to customers if the firm fails.',
    realWorld: 'Bear Stearns\' collapse was partly due to insufficient net capital relative to its leverage and illiquid assets.',
    hint: 'It\'s about having enough liquid capital as a financial cushion.',
  },
  {
    id: 83502,
    topic: 'series-24',
    difficulty: 'hard',
    question: 'FINRA Rule 3110 requires a broker-dealer\'s supervisory system to include:',
    options: [
      'Written supervisory procedures (WSPs), annual compliance reviews, and designated supervisors for each activity',
      'Only verbal instructions to representatives',
      'Supervision only for new hires',
      'Annual reviews only if there are customer complaints',
    ],
    correctIndex: 0,
    explanation: 'Rule 3110 mandates comprehensive WSPs, regular updates, designated supervisors, branch inspections, and annual compliance reviews.',
    realWorld: 'FINRA regularly fines firms for supervisory failures, with penalties often exceeding $1 million.',
    hint: 'It requires written procedures, not just informal oversight.',
  },
  {
    id: 83503,
    topic: 'series-24',
    difficulty: 'hard',
    question: 'When a broker-dealer is underwriting a new issue, the "cooling-off period" refers to:',
    options: [
      'The 20-day waiting period between filing the registration statement and its effective date',
      'The time after the IPO when shares cannot be traded',
      'A mandatory vacation for the underwriting team',
      'The period during which no marketing is allowed',
    ],
    correctIndex: 0,
    explanation: 'During the cooling-off period, the SEC reviews the filing. Preliminary prospectuses ("red herrings") may be distributed but no sales can be made.',
    realWorld: 'Underwriters use roadshows during the cooling-off period to gauge investor interest and build the book.',
    hint: 'It\'s between filing and SEC approval — a waiting period.',
  },
  {
    id: 83504,
    topic: 'series-24',
    difficulty: 'sota',
    question: 'Under FINRA\'s Customer Identification Program (CIP) requirements, broker-dealers must:',
    options: [
      'Verify the identity of each customer using documentary or non-documentary methods within a reasonable time of account opening',
      'Only verify identity for accounts over $50,000',
      'Accept any form of identification without verification',
      'Verify identity only if the customer requests it',
    ],
    correctIndex: 0,
    explanation: 'CIP (part of the Bank Secrecy Act / USA PATRIOT Act) requires name, date of birth, address, and identification number verification for all new accounts.',
    realWorld: 'Anti-money laundering compliance costs the financial industry billions annually, but CIP is the first line of defense.',
    hint: 'It\'s a post-9/11 anti-money laundering requirement for all accounts.',
  },
];

// ── Series 3: National Commodities Futures ──
export const series3Questions: Question[] = [
  {
    id: 83600,
    topic: 'series-3',
    difficulty: 'easy',
    question: 'A futures contract obligates both parties to:',
    options: [
      'Buy or sell a specific quantity of an asset at a predetermined price on a future date',
      'Only the buyer to purchase; the seller has no obligation',
      'Exchange assets immediately at the current spot price',
      'Pay a premium for the right to trade',
    ],
    correctIndex: 0,
    explanation: 'Unlike options, futures are bilateral obligations. Both buyer (long) and seller (short) must perform at expiration unless offset beforehand.',
    realWorld: 'Farmers sell corn futures to lock in prices before harvest; food processors buy to lock in input costs.',
    hint: 'Futures = obligation for both sides. Options = right for the buyer.',
  },
  {
    id: 83601,
    topic: 'series-3',
    difficulty: 'easy',
    question: 'Initial margin in futures trading represents:',
    options: [
      'A good-faith deposit (performance bond) required to open a position',
      'The full purchase price of the contract',
      'The maximum possible loss on the trade',
      'A fee paid to the exchange',
    ],
    correctIndex: 0,
    explanation: 'Initial margin is typically 3-12% of the contract value, set by the exchange, and serves as collateral against adverse price movements.',
    realWorld: 'CME Group adjusts margin requirements based on market volatility — margins spiked during the 2020 oil crash.',
    hint: 'It\'s a deposit, not a down payment — you get it back when you close.',
  },
  {
    id: 83602,
    topic: 'series-3',
    difficulty: 'hard',
    question: 'Contango in the futures market means:',
    options: [
      'Futures prices are higher than the spot price, reflecting storage costs and financing',
      'Futures prices are below the spot price',
      'The market is in equilibrium with no basis',
      'All futures contracts have the same price regardless of expiration',
    ],
    correctIndex: 0,
    explanation: 'Contango: $F > S$. Cost of carry model: $F = S \\cdot e^{(r+c-y)T}$ where storage costs and financing exceed convenience yield.',
    realWorld: 'Oil futures were in extreme contango in April 2020 when storage tanks were nearly full and front-month contracts went negative.',
    hint: 'It\'s the normal state when carrying costs exceed convenience yield.',
  },
  {
    id: 83603,
    topic: 'series-3',
    difficulty: 'hard',
    question: 'A commodity pool operator (CPO) differs from a commodity trading advisor (CTA) because a CPO:',
    options: [
      'Pools funds from multiple investors into a single trading vehicle (commodity pool)',
      'Provides only advice without managing money',
      'Trades exclusively in physical commodities',
      'Is exempt from NFA registration',
    ],
    correctIndex: 0,
    explanation: 'CPOs operate pooled investment vehicles (like hedge funds for futures). CTAs provide trading advice but don\'t necessarily pool funds.',
    realWorld: 'Managed futures funds are typically structured as commodity pools and must register with the CFTC and NFA.',
    hint: 'Pool = pooling money from multiple investors into one vehicle.',
  },
  {
    id: 83604,
    topic: 'series-3',
    difficulty: 'sota',
    question: 'The risk of basis convergence failure in futures hedging is most pronounced when:',
    options: [
      'The hedged asset and the futures contract\'s underlying are not identical (cross-hedging)',
      'The hedge ratio is exactly 1:1',
      'The futures contract expires on the same day as the physical delivery',
      'Both parties are hedgers with identical positions',
    ],
    correctIndex: 0,
    explanation: 'Basis risk arises when the hedged exposure and the futures contract don\'t perfectly correlate. Cross-hedging (e.g., jet fuel with crude oil futures) amplifies this risk.',
    realWorld: 'Airlines hedging jet fuel with crude oil futures experienced significant basis risk during the 2008 commodity collapse.',
    hint: 'If what you\'re hedging isn\'t exactly what the futures contract delivers, there\'s basis risk.',
  },
];

// ── Series 52: Municipal Securities Representative ──
export const series52Questions: Question[] = [
  {
    id: 83700,
    topic: 'series-52',
    difficulty: 'easy',
    question: 'General obligation (GO) bonds are backed by:',
    options: [
      'The full faith, credit, and taxing power of the issuing municipality',
      'Revenue from a specific project like a toll road',
      'Corporate guarantees from local businesses',
      'Federal government backing',
    ],
    correctIndex: 0,
    explanation: 'GO bonds are secured by the issuer\'s ability to levy taxes (property, sales, income) to pay debt service.',
    realWorld: 'Voters typically must approve GO bond issuances since they pledge taxpayer resources.',
    hint: 'The municipality\'s full taxing power backs these bonds.',
  },
  {
    id: 83701,
    topic: 'series-52',
    difficulty: 'easy',
    question: 'Revenue bonds differ from general obligation bonds because revenue bonds are:',
    options: [
      'Backed only by the revenue generated from the specific project they finance',
      'Guaranteed by the federal government',
      'Backed by the municipality\'s general tax revenues',
      'Always rated AAA',
    ],
    correctIndex: 0,
    explanation: 'Revenue bonds (e.g., for airports, hospitals, toll roads) are repaid from project revenues, not taxes. They typically carry higher yields due to the narrower revenue source.',
    realWorld: 'The Port Authority of NY/NJ funds infrastructure through revenue bonds backed by tolls and fees.',
    hint: 'The project itself must generate enough money to pay bondholders.',
  },
  {
    id: 83702,
    topic: 'series-52',
    difficulty: 'hard',
    question: 'The MSRB\'s Rule G-17 requires municipal securities dealers to:',
    options: [
      'Deal fairly with all persons and not engage in deceptive, dishonest, or unfair practices',
      'Only trade with institutional investors',
      'Guarantee profits on all municipal transactions',
      'Report all trades within 24 hours to the IRS',
    ],
    correctIndex: 0,
    explanation: 'G-17 is the MSRB\'s foundational fair dealing rule, analogous to FINRA\'s just and equitable principles of trade.',
    realWorld: 'The MSRB brought enforcement actions against dealers who failed to disclose material information to municipal issuers.',
    hint: 'It\'s the core ethical standard for municipal securities professionals.',
  },
  {
    id: 83703,
    topic: 'series-52',
    difficulty: 'hard',
    question: 'In a competitive municipal bond underwriting, the winning syndicate is typically determined by:',
    options: [
      'The lowest net interest cost (NIC) or true interest cost (TIC) bid',
      'The highest premium offered',
      'Random selection among qualified bidders',
      'The largest syndicate by number of members',
    ],
    correctIndex: 0,
    explanation: 'Issuers award competitive deals to the syndicate offering the lowest borrowing cost. TIC (present-value-weighted) is more accurate than NIC (simple average).',
    realWorld: 'Most GO bonds are sold competitively, while revenue bonds are more often negotiated.',
    hint: 'The issuer wants the cheapest financing — lowest interest cost wins.',
  },
  {
    id: 83704,
    topic: 'series-52',
    difficulty: 'sota',
    question: 'The de minimis tax rule for municipal bonds affects secondary market pricing because:',
    options: [
      'Bonds purchased at a discount below de minimis are taxed at ordinary income rates on the discount, reducing their attractiveness',
      'All municipal bond gains are always tax-free',
      'Only bonds held to maturity are subject to tax',
      'The rule only applies to bonds issued after 2020',
    ],
    correctIndex: 0,
    explanation: 'If a muni bond is bought at a discount exceeding 0.25% × remaining years to maturity, the discount is taxed as ordinary income rather than capital gains at sale or maturity.',
    realWorld: 'Traders adjust muni bond pricing around de minimis boundaries, creating pricing "cliffs" in the secondary market.',
    hint: 'Below a threshold discount, the tax treatment changes unfavorably.',
  },
];
