import type { Question } from '../types';

export const categoryTheoryQuestions: Question[] = [
  // ── Easy ──
  {
    id: 91001, topic: 'category-theory', difficulty: 'easy',
    question: 'A category consists of objects, morphisms, and which key operation?',
    options: ['Composition of morphisms', 'Tensor product', 'Direct sum', 'Cartesian product'],
    correctIndex: 0,
    explanation: 'A category requires a composition operation on morphisms that is associative and has identity morphisms.',
    realWorld: 'Category theory provides the foundation for type systems in Haskell and functional programming.',
    hint: 'Think about how arrows (morphisms) chain together.',
  },
  {
    id: 91002, topic: 'category-theory', difficulty: 'easy',
    question: 'A functor between categories preserves:',
    options: ['Objects, morphisms, composition, and identities', 'Only objects', 'Only morphisms', 'Only identities'],
    correctIndex: 0,
    explanation: 'A functor maps objects to objects and morphisms to morphisms while preserving composition and identity.',
    realWorld: 'Functors in programming (e.g., `map` on lists) transform contained values while preserving structure.',
    hint: 'A functor is a structure-preserving map between categories.',
  },
  {
    id: 91003, topic: 'category-theory', difficulty: 'easy',
    question: 'A natural transformation relates:',
    options: ['Two functors between the same categories', 'Two objects in a category', 'Two categories', 'Two morphisms'],
    correctIndex: 0,
    explanation: 'A natural transformation $\\eta: F \\Rightarrow G$ assigns to each object $X$ a morphism $\\eta_X: F(X) \\to G(X)$ satisfying naturality.',
    realWorld: 'Natural transformations model polymorphic functions in programming languages.',
    hint: 'It is a "morphism between functors".',
  },
  {
    id: 91004, topic: 'category-theory', difficulty: 'easy',
    question: 'An isomorphism in a category is a morphism $f: A \\to B$ such that:',
    options: ['There exists $g: B \\to A$ with $g \\circ f = \\text{id}_A$ and $f \\circ g = \\text{id}_B$', 'It is injective', 'It is surjective', 'It preserves order'],
    correctIndex: 0,
    explanation: 'An isomorphism has a two-sided inverse making both compositions equal to the respective identities.',
    realWorld: 'Isomorphisms capture the notion of "structurally identical" across all of mathematics.',
    hint: 'Think about invertible functions.',
  },
  {
    id: 91005, topic: 'category-theory', difficulty: 'easy',
    question: 'The product of two objects $A$ and $B$ in a category is characterized by:',
    options: ['A universal property with projection morphisms', 'Their union', 'Their intersection', 'The largest common subobject'],
    correctIndex: 0,
    explanation: 'The product $A \\times B$ has projections $\\pi_1, \\pi_2$ such that any pair of morphisms factors uniquely through it.',
    realWorld: 'Categorical products correspond to product types (tuples/structs) in programming.',
    hint: 'Universal properties define objects by how other objects map into/out of them.',
  },
  // ── Hard ──
  {
    id: 91006, topic: 'category-theory', difficulty: 'hard',
    question: 'The Yoneda Lemma states that natural transformations from $\\text{Hom}(A, -)$ to a functor $F$ are in bijection with:',
    options: ['Natural endomorphisms of $F$', '$\\text{Hom}(F(A),A)$', '$F(A)$', 'The limit of $F$ over the whole category'],
    correctIndex: 2,
    explanation: '$\\text{Nat}(\\text{Hom}(A,-), F) \\cong F(A)$, one of the most important results in category theory.',
    realWorld: 'Yoneda underpins representable functors and is key to modern algebraic geometry (schemes).',
    hint: 'A natural transformation is completely determined by where it sends the identity on $A$.',
  },
  {
    id: 91007, topic: 'category-theory', difficulty: 'hard',
    question: 'An adjunction $F \\dashv G$ between categories $\\mathcal{C}$ and $\\mathcal{D}$ means:',
    options: ['$F \\circ G$ and $G \\circ F$ are identity functors', '$F$ and $G$ are inverse equivalences of categories', '$F(X)$ and $G(Y)$ are isomorphic for every $X,Y$', '$\\text{Hom}_{\\mathcal{D}}(F(X),Y) \\cong \\text{Hom}_{\\mathcal{C}}(X,G(Y))$ naturally in $X,Y$'],
    correctIndex: 3,
    explanation: 'Adjunctions give a natural isomorphism of hom-sets, capturing "optimal solutions" to universal problems.',
    realWorld: 'Free-forgetful adjunctions model the relationship between syntax and semantics in type theory.',
    hint: 'The left adjoint $F$ is the "free" construction, and $G$ is the "forgetful" functor.',
  },
  {
    id: 91008, topic: 'category-theory', difficulty: 'hard',
    question: 'A monad on a category $\\mathcal{C}$ consists of an endofunctor $T$ together with:',
    options: ['A counit $T \\Rightarrow \\text{Id}$ and comultiplication $T \\Rightarrow T^2$', 'A unit $\\eta: \\text{Id} \\Rightarrow T$ and multiplication $\\mu: T^2 \\Rightarrow T$ satisfying the monad laws', 'A natural isomorphism $T \\cong \\text{Id}$ and no additional structure', 'A pair of inverse functors whose composite is exactly $T$'],
    correctIndex: 1,
    explanation: 'A monad $(T, \\eta, \\mu)$ satisfies $\\mu \\circ T\\mu = \\mu \\circ \\mu T$ and unit conditions.',
    realWorld: 'Monads in Haskell (IO, Maybe, List) structure side effects and computational contexts.',
    hint: 'Think of monads as "generalized algebraic theories" on a category.',
  },
  {
    id: 91009, topic: 'category-theory', difficulty: 'hard',
    question: 'A topos is a category that behaves like the category of sets. Which is NOT a defining property of an elementary topos?',
    options: ['Every morphism has a kernel', 'It has all finite limits', 'It is cartesian closed, hence has exponential objects', 'It has a subobject classifier'],
    correctIndex: 0,
    explanation: 'An elementary topos has finite limits, exponentials, and a subobject classifier. Not every morphism needs a kernel.',
    realWorld: 'Topos theory provides the foundation for constructive logic and sheaf-theoretic approaches in geometry.',
    hint: 'Topoi generalize Set, but focus on internal logic rather than abelian category properties.',
  },
  {
    id: 91010, topic: 'category-theory', difficulty: 'hard',
    question: 'The nerve of a category $\\mathcal{C}$ is a simplicial set where $n$-simplices correspond to:',
    options: ['Unordered sets of $n$ objects of $\\mathcal{C}$', 'Natural transformations between arbitrary endofunctors', 'Composable chains of $n$ morphisms $X_0 \\to X_1 \\to \\cdots \\to X_n$', 'Isomorphism classes of objects admitting exactly $n$ automorphisms'],
    correctIndex: 2,
    explanation: 'The nerve $N(\\mathcal{C})_n$ consists of chains $X_0 \\to X_1 \\to \\cdots \\to X_n$ of composable morphisms.',
    realWorld: 'The nerve construction connects category theory to topology and is fundamental to higher category theory and TDA.',
    hint: 'An $n$-simplex in the nerve is a "path" of $n$ consecutive arrows.',
  },
  // ── SOTA ──
  {
    id: 91011, topic: 'category-theory', difficulty: 'sota',
    question: 'In homotopy type theory (HoTT), types are interpreted as:',
    options: ['Spaces in an $\\infty$-groupoid / homotopy-theoretic sense', 'Classical sets', 'Finite automata', 'First-order logic formulas'],
    correctIndex: 0,
    explanation: 'HoTT interprets types as spaces where equality proofs correspond to paths, giving a synthetic homotopy theory.',
    realWorld: 'HoTT and the Univalence Axiom are being formalized in Lean/Coq for verified mathematics.',
    hint: 'Think about the connection between identity types and path spaces.',
  },
  {
    id: 91012, topic: 'category-theory', difficulty: 'sota',
    question: 'Lurie\'s $\\infty$-categories (quasi-categories) generalize ordinary categories by allowing:',
    options: ['Morphisms between morphisms at all higher levels (higher homotopies)', 'Only invertible morphisms', 'Finite morphism sets', 'Strict composition'],
    correctIndex: 0,
    explanation: 'Quasi-categories have $n$-morphisms for all $n$, with composition defined up to coherent homotopy.',
    realWorld: '$\\infty$-categories unify algebraic topology, derived algebraic geometry, and topological field theories.',
    hint: 'Think about simplicial sets satisfying the inner horn-filling condition.',
  },
  {
    id: 91013, topic: 'category-theory', difficulty: 'sota',
    question: 'Applied category theory uses string diagrams to reason about:',
    options: ['Monoidal categories with visual compositional calculus', 'Only commutative diagrams', 'Database schemas exclusively', 'Neural network layers only'],
    correctIndex: 0,
    explanation: 'String diagrams provide a graphical calculus for monoidal categories where wires = objects and boxes = morphisms.',
    realWorld: 'CatLab.jl and AlgebraicJulia use categorical frameworks for scientific modeling and compositional ML.',
    hint: 'Wires represent objects and boxes represent morphisms in a monoidal category.',
  },
  {
    id: 91014, topic: 'category-theory', difficulty: 'sota',
    question: 'The Curry-Howard-Lambek correspondence connects:',
    options: ['Proofs ↔ Programs ↔ Morphisms in cartesian closed categories', 'Sets ↔ Types ↔ Groups', 'Rings ↔ Modules ↔ Spaces', 'Graphs ↔ Trees ↔ Lattices'],
    correctIndex: 0,
    explanation: 'This three-way correspondence unifies logic (proofs), computation (programs), and category theory (morphisms in CCCs).',
    realWorld: 'This correspondence is the theoretical foundation of proof assistants like Lean 4 and Coq.',
    hint: 'Think about the triple correspondence: propositions-types-objects.',
  },
  {
    id: 91015, topic: 'category-theory', difficulty: 'sota',
    question: 'Polynomial functors, recently studied by Spivak and Niu for dynamical systems, model:',
    options: ['Systems with typed inputs/outputs and compositional interconnection', 'Only linear transformations', 'Static database queries', 'Fixed-point computations exclusively'],
    correctIndex: 0,
    explanation: 'Polynomial functors $p(y) = \\sum_{i} y^{B_i}$ model interfaces and wiring diagrams for composable dynamical systems.',
    realWorld: 'Poly is being used to give compositional semantics to neural networks and multi-agent systems.',
    hint: 'Think of $p = \\sum_i y^{B_i}$ as an interface with positions and directions.',
  },
];
