import type { Question } from '../types';

export const algoTradingQuestions: Question[] = [
  {
    id: 70300,
    topic: 'algo-trading',
    difficulty: 'easy',
    question: 'A VWAP (Volume-Weighted Average Price) execution algorithm aims to:',
    options: [
      'Match the volume-weighted average price over a trading period',
      'Execute all shares at the market open price',
      'Maximize the number of trades per second',
      'Guarantee best execution at the closing price',
    ],
    correctIndex: 0,
    explanation: 'VWAP algorithms slice orders to track the expected volume distribution throughout the day, achieving average execution near the benchmark.',
    realWorld: 'Institutional investors commonly use VWAP algos to reduce market impact on large orders.',
    hint: 'It\'s about matching volume-weighted benchmarks, not speed.',
  },
  {
    id: 70301,
    topic: 'algo-trading',
    difficulty: 'hard',
    question: 'The Almgren-Chriss model for optimal execution minimizes a tradeoff between:',
    options: [
      'Market impact cost and timing risk (price variance)',
      'Commission fees and latency',
      'Bid-ask spread and overnight gap risk',
      'Order routing complexity and regulatory compliance',
    ],
    correctIndex: 0,
    explanation: 'Almgren-Chriss formulates optimal liquidation as minimizing E[cost] + λ·Var[cost], balancing urgency against market impact.',
    realWorld: 'Quant desks at banks implement Almgren-Chriss to optimally unwind large positions.',
    hint: 'It\'s a mean-variance optimization applied to execution, not portfolio selection.',
  },
  {
    id: 70302, topic: "algo-trading", difficulty: "sota",
    question: "Avellaneda-Stoikov market making balances spread capture against:",
    options: ["Dividend forecasts","Inventory risk and order arrivals","Accounting leverage","Guaranteed arbitrage"],
    correctIndex: 1,
    explanation: "The model chooses bid and ask quotes for a dealer facing uncertain prices, stochastic order arrivals, and inventory risk.",
    realWorld: "It is a foundational stylized model for quantitative market making and has inspired many extensions.",
    hint: "The dealer earns spread but must manage fills and inventory.",
    paper: {"title":"High-frequency trading in a limit order book","url":"https://doi.org/10.1080/14697680701381228","venue":"Quantitative Finance","year":2008},
    reviewedAt: "2026-09-19",
  },

  // ── Algorithmic Trading foundation expansion ──────────────────────────
  {
    id: 70303, topic: "algo-trading", difficulty: "easy",
    question: "A TWAP schedule trades an order:",
    options: ["At the market close","Evenly through time","Only at high volume","At one fixed price"],
    correctIndex: 1,
    explanation: "Time-weighted average price execution spreads trading across time intervals instead of following a volume profile.",
    realWorld: "TWAP is simple and predictable when volume seasonality is not the main benchmark.",
    hint: "The clue is time-weighted.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70304, topic: "algo-trading", difficulty: "easy",
    question: "A market order prioritizes:",
    options: ["Exact price control","Passive queue position","Immediate execution","Avoiding the spread"],
    correctIndex: 2,
    explanation: "A market order seeks prompt execution against available liquidity, while a limit order provides more price control but may not fill.",
    realWorld: "Execution algorithms trade off urgency, spread, market impact, and fill risk.",
    hint: "Execution certainty comes before exact price.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70305, topic: "algo-trading", difficulty: "hard",
    question: "Implementation shortfall compares actual trading with:",
    options: ["Closing-price benchmark portfolio","VWAP benchmark portfolio","Next-day benchmark portfolio","Decision-price paper portfolio"],
    correctIndex: 3,
    explanation: "Implementation shortfall compares actual results with a frictionless paper trade executed at the decision price.",
    realWorld: "Transaction-cost analysis uses it to identify value lost to delay, impact, spread, commissions, and missed trades.",
    hint: "Compare reality with immediate frictionless execution.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70306, topic: "algo-trading", difficulty: "hard",
    question: "Adverse selection on a resting limit order means:",
    options: ["Favorable price movement after fill","Adverse price movement after fill","No price movement after fill","Guaranteed spread capture"],
    correctIndex: 1,
    explanation: "A passive quote can be executed by a better-informed or faster trader just before the market moves against it.",
    realWorld: "Market makers balance spread capture against inventory and adverse-selection risk.",
    hint: "Sometimes a fill is bad news.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70307, topic: "algo-trading", difficulty: "sota",
    question: "DeepLOB represents limit-order-book data using:",
    options: ["Daily-bar moving averages","Static linear regression only","Convolution plus sequence modeling","No temporal dependence"],
    correctIndex: 2,
    explanation: "DeepLOB combines convolutional layers for order-book structure with recurrent modeling for temporal dependencies.",
    realWorld: "Order-book ML research must still account for costs, leakage, latency, and regime shifts.",
    hint: "Learn book structure and time dependence.",
    paper: {"title":"DeepLOB: Deep Convolutional Neural Networks for Limit Order Books","url":"https://doi.org/10.48550/arXiv.1808.03668","venue":"IEEE Transactions on Signal Processing","year":2019},
    reviewedAt: "2026-09-19",
  },
  {
    id: 70308, topic: "algo-trading", difficulty: "sota",
    question: "Recent market-impact evidence continues to support approximate:",
    options: ["Linear scaling","No size effect","Exponential scaling","Square-root scaling"],
    correctIndex: 3,
    explanation: "A 2026 Tokyo Stock Exchange study reports square-root scaling at child-order and metaorder levels while studying the mechanical origin of impact.",
    realWorld: "Impact scaling matters because larger orders need not increase expected impact proportionally.",
    hint: "The empirical law is sublinear in volume.",
    paper: {"title":"The double square-root law: evidence for the mechanical origin of market impact using Tokyo stock exchange data","url":"https://doi.org/10.1080/14697688.2026.2615106","venue":"Quantitative Finance","year":2026},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
];
