import type { Question } from '../types';

export const fixedIncomeQuestions: Question[] = [
  {
    id: 70200,
    topic: 'fixed-income',
    difficulty: 'easy',
    question: 'Duration measures a bond\'s sensitivity to changes in:',
    options: [
      'Interest rates',
      'Credit rating',
      'Inflation expectations',
      'Currency exchange rates',
    ],
    correctIndex: 0,
    explanation: 'Duration quantifies the approximate percentage change in bond price for a 1% change in yield.',
    realWorld: 'Fixed income PMs use duration to immunize portfolios against interest rate risk.',
    hint: 'It\'s the first-order price sensitivity to yield.',
  },
  {
    id: 70201,
    topic: 'fixed-income',
    difficulty: 'hard',
    question: 'Convexity adjusts the duration estimate because:',
    options: ["Price-yield curvature","Duration only works for zero-coupon bonds","Credit spreads are constant","Bonds always trade at par"],
    correctIndex: 0,
    explanation: 'Duration is a linear approximation; convexity captures the curvature of the price-yield curve, improving accuracy for large yield changes.',
    realWorld: 'Traders add convexity adjustment: ΔP/P ≈ -D·Δy + ½·C·(Δy)².',
    hint: 'Think about second-order effects in a Taylor expansion.',
  },
  {
    id: 70202,
    topic: 'fixed-income',
    difficulty: 'sota',
    question: 'In the Heath-Jarrow-Morton (HJM) framework, the no-arbitrage drift of forward rates is determined by:',
    options: ["Forward-rate volatility","Historical mean reversion parameters only","The current spot rate exclusively","Central bank policy rate targets"],
    correctIndex: 0,
    explanation: 'HJM\'s key insight is the drift restriction: under Q, forward rate drifts are fully determined by their volatilities, preventing arbitrage.',
    realWorld: 'HJM underpins modern fixed-income derivatives pricing at banks and hedge funds.',
    hint: 'The drift is not free — it\'s constrained by vol under risk-neutral pricing.',
  
    paper: {"title":"Bond Pricing and the Term Structure of Interest Rates","url":"https://doi.org/10.2307/2951677","venue":"Econometrica","year":1992},
    reviewedAt: "2026-09-19",
  },

  // ── Fixed Income foundation expansion ──────────────────────────
  {
    id: 70203, topic: "fixed-income", difficulty: "easy",
    question: "For a plain fixed-rate bond, price and yield usually:",
    options: ["Move together","Move inversely","Are unrelated","Only rise"],
    correctIndex: 1,
    explanation: "Discounting unchanged cash flows at a higher yield lowers present value, while a lower yield raises present value.",
    realWorld: "This inverse relation is fundamental to bond-market gains and losses when rates move.",
    hint: "Higher discount rates lower present value.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70204, topic: "fixed-income", difficulty: "easy",
    question: "A zero-coupon bond has:",
    options: ["Floating coupons","Monthly coupons","No periodic coupons","Equity dividends"],
    correctIndex: 2,
    explanation: "A zero-coupon bond makes no periodic coupon payments; return comes from buying below maturity value.",
    realWorld: "Zero-coupon instruments make discounting mechanics especially transparent.",
    hint: "No intermediate coupon cash flows.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70205, topic: "fixed-income", difficulty: "hard",
    question: "Key-rate duration measures:",
    options: ["Issuer default sensitivity","Coupon reinvestment risk","Foreign-exchange sensitivity","Sensitivity at curve maturities"],
    correctIndex: 3,
    explanation: "Key-rate durations estimate price sensitivity to localized yield-curve shifts at selected maturities rather than one parallel move.",
    realWorld: "They help hedge steepening, flattening, and curve twists.",
    hint: "Break duration into maturity-specific exposures.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70206, topic: "fixed-income", difficulty: "hard",
    question: "Yield-curve bootstrapping uses:",
    options: ["One average market yield","Sequential curve solving","Only the longest bond","Ignoring earlier cash flows"],
    correctIndex: 1,
    explanation: "Bootstrapping solves discount factors or spot rates one maturity at a time using previously inferred values.",
    realWorld: "Bootstrapped curves support valuation, hedging, and forward-rate calculation.",
    hint: "Solve the next unknown using earlier solved cash flows.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70207, topic: "fixed-income", difficulty: "sota",
    question: "SOFR is based primarily on:",
    options: ["Unsecured corporate funding","Long-term municipal funding","Secured Treasury repo funding","Equity margin lending"],
    correctIndex: 2,
    explanation: "SOFR measures the cost of overnight cash borrowing collateralized by U.S. Treasury securities and is administered by the New York Fed.",
    realWorld: "It became a central U.S. reference rate in the transition away from USD LIBOR.",
    hint: "Secured overnight funding points to Treasury repo.",
    sources: [{"title":"Reference Rates","url":"https://www.newyorkfed.org/markets/reference-rates","publisher":"Federal Reserve Bank of New York","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 70208, topic: "fixed-income", difficulty: "sota",
    question: "A Treasury term premium compensates investors mainly for:",
    options: ["Coupon timing","Treasury default only","Tax accounting","Rate-path risk"],
    correctIndex: 3,
    explanation: "Longer Treasury yields can be decomposed into expected future short rates plus a term premium for uncertainty about rate paths.",
    realWorld: "Term-premium estimates are model-dependent rather than directly observed.",
    hint: "Separate expected short rates from duration-risk compensation.",
    sources: [{"title":"Treasury Term Premia: 1961-Present","url":"https://libertystreeteconomics.newyorkfed.org/2014/05/treasury-term-premia-1961-present/","publisher":"Federal Reserve Bank of New York","year":2014}],
    reviewedAt: "2026-09-19",
  },
];
