import type { Question } from '../types';

export const portfolioTheoryQuestions: Question[] = [
  {
    id: 70100,
    topic: 'portfolio-theory',
    difficulty: 'easy',
    question: 'In Markowitz mean-variance optimization, the efficient frontier represents portfolios that:',
    options: [
      'Maximize return for a given level of risk',
      'Minimize total assets held',
      'Maximize Sharpe ratio only',
      'Eliminate all unsystematic risk',
    ],
    correctIndex: 0,
    explanation: 'The efficient frontier is the set of portfolios offering the highest expected return for each level of risk (standard deviation).',
    realWorld: 'Pension funds and robo-advisors use efficient frontier analysis to build optimal allocations.',
    hint: 'Think about the risk-return tradeoff boundary.',
  },
  {
    id: 70101,
    topic: 'portfolio-theory',
    difficulty: 'hard',
    question: 'The Capital Market Line (CML) differs from the Security Market Line (SML) because:',
    options: [
      'CML uses total risk (σ) while SML uses systematic risk (β)',
      'CML applies only to individual securities',
      'SML assumes no risk-free asset exists',
      'They are mathematically identical',
    ],
    correctIndex: 0,
    explanation: 'CML plots efficient portfolios against total risk, while SML (from CAPM) prices any asset by its beta (systematic risk).',
    realWorld: 'Portfolio managers use SML to assess whether individual stocks are fairly valued relative to their market risk.',
    hint: 'One uses standard deviation, the other uses beta.',
  },
  {
    id: 70102,
    topic: 'portfolio-theory',
    difficulty: 'sota',
    question: 'Black-Litterman model improves on mean-variance optimization primarily by:',
    options: [
      'Combining market equilibrium returns with investor views via Bayesian updating',
      'Eliminating the need for a covariance matrix',
      'Using only historical returns without assumptions',
      'Replacing the risk-free rate with a stochastic process',
    ],
    correctIndex: 0,
    explanation: 'Black-Litterman starts from CAPM equilibrium returns and blends in subjective views using Bayes\' theorem, producing more stable allocations.',
    realWorld: 'Goldman Sachs developed Black-Litterman; it remains the industry standard for institutional asset allocation.',
    hint: 'It\'s a Bayesian approach to blending market-implied returns with personal views.',
  
    paper: {"title":"Global Portfolio Optimization","url":"https://rpc.cfainstitute.org/research/financial-analysts-journal/1992/faj-v48-n5-28","venue":"Financial Analysts Journal","year":1992},
    reviewedAt: "2026-09-19",
  },

  // ── Portfolio Theory foundation expansion ──────────────────────────
  {
    id: 70103, topic: "portfolio-theory", difficulty: "easy",
    question: "Diversification helps most when assets have:",
    options: ["Identical returns","Imperfect correlation","Guaranteed gains","Equal prices"],
    correctIndex: 1,
    explanation: "Combining assets that do not move perfectly together can reduce portfolio variance through covariance effects.",
    realWorld: "Diversification depends on co-movement, not merely the number of holdings.",
    hint: "Look at correlation.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70104, topic: "portfolio-theory", difficulty: "easy",
    question: "Portfolio variance depends importantly on:",
    options: ["Book values","Expected returns only","Covariances","Tax rates"],
    correctIndex: 2,
    explanation: "Portfolio variance includes covariance terms that capture how asset returns move together.",
    realWorld: "Covariance estimation is central to portfolio construction and risk management.",
    hint: "Risk depends on co-movement.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70105, topic: "portfolio-theory", difficulty: "hard",
    question: "CAPM beta measures:",
    options: ["Total volatility exposure","Dividend-yield exposure","Liquidity-risk exposure","Market beta exposure"],
    correctIndex: 3,
    explanation: "Beta is covariance with the market divided by market variance, so it measures systematic market sensitivity rather than total volatility.",
    realWorld: "CAPM distinguishes systematic risk from diversifiable idiosyncratic risk.",
    hint: "It is market sensitivity.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70106, topic: "portfolio-theory", difficulty: "hard",
    question: "Portfolio rebalancing means:",
    options: ["Chasing recent winners","Return to target weights","Eliminating cash holdings","Avoiding all trading"],
    correctIndex: 1,
    explanation: "As prices move, asset weights drift from policy targets; rebalancing trades them back toward chosen allocations subject to costs.",
    realWorld: "Institutional portfolios often use tolerance bands rather than continuous rebalancing.",
    hint: "Restore policy weights after drift.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70107, topic: "portfolio-theory", difficulty: "sota",
    question: "Ledoit-Wolf shrinkage moves sample covariance toward:",
    options: ["Expected-return forecasts","One asset's variance","Structured covariance target","Zero portfolio variance"],
    correctIndex: 2,
    explanation: "Covariance shrinkage trades some bias for lower estimation variance by moving a noisy sample matrix toward a structured target.",
    realWorld: "Better-conditioned covariance estimates can improve out-of-sample portfolio risk estimation.",
    hint: "Shrink noisy covariance toward a simpler target.",
    paper: {"title":"Improved estimation of the covariance matrix of stock returns with an application to portfolio selection","url":"https://www.sciencedirect.com/science/article/pii/S0927539803000070","venue":"Journal of Empirical Finance","year":2003},
    reviewedAt: "2026-09-19",
  },
  {
    id: 70108, topic: "portfolio-theory", difficulty: "sota",
    question: "Risk-parity portfolios target roughly:",
    options: ["Equal dollar allocations","Equal expected returns","Equal turnover budgets","Equal portfolio-risk contributions"],
    correctIndex: 3,
    explanation: "Equal-risk-contribution construction chooses weights so portfolio risk is distributed more evenly across components.",
    realWorld: "The approach reduces reliance on uncertain expected-return estimates.",
    hint: "Equalize risk, not capital.",
    paper: {"title":"On the Properties of Equally-Weighted Risk Contributions Portfolios","url":"https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1271972","venue":"The Journal of Portfolio Management","year":2010},
    reviewedAt: "2026-09-19",
  },
];
