import type { Question } from '../types';

export const quantEasyQuestions: Question[] = [
  {
    id: 30001,
    topic: 'stochastic-calculus',
    difficulty: 'easy',
    question: 'A standard Brownian motion $W_t$ has what distribution at time $t$?',
    options: ['$\\mathcal{N}(0, t)$', '$\\mathcal{N}(t, 1)$', 'Uniform on $[0, t]$', 'Exponential with rate $t$'],
    correctIndex: 0,
    explanation: '$W_t \\sim \\mathcal{N}(0, t)$ — mean zero, variance $t$. This is the defining property of standard Brownian motion.',
    realWorld: 'Models stock price log-returns in the Black-Scholes framework.',
    hint: 'Brownian motion starts at zero and has independent, stationary increments.',
  },
  {
    id: 30002,
    topic: 'stochastic-calculus',
    difficulty: 'easy',
    question: 'What is $\\mathbb{E}[W_t W_s]$ for standard Brownian motion where $s \\leq t$?',
    options: ['$\\min(s, t) = s$', '$s + t$', '$st$', '$0$'],
    correctIndex: 0,
    explanation: '$\\mathbb{E}[W_t W_s] = \\min(s, t)$ — a fundamental covariance property of Brownian motion.',
    realWorld: 'This covariance structure is exploited in option pricing and risk management.',
    hint: 'Split $W_t = W_s + (W_t - W_s)$ and use independence of increments.',
  },
  {
    id: 30003,
    topic: 'stochastic-calculus',
    difficulty: 'easy',
    question: 'In the SDE $dS_t = \\mu S_t \\, dt + \\sigma S_t \\, dW_t$, what does $\\sigma$ represent?',
    options: ['Volatility (instantaneous std dev of returns)', 'Expected return', 'Interest rate', 'Time step size'],
    correctIndex: 0,
    explanation: '$\\sigma$ is the volatility parameter — it scales the stochastic (random) component of the price process.',
    realWorld: 'Volatility is the key driver of option prices; higher $\\sigma$ means more expensive options.',
    hint: '$\\sigma$ multiplies the noise term $dW_t$.',
  },
  {
    id: 30004,
    topic: 'stochastic-calculus',
    difficulty: 'easy',
    question: 'What does the quadratic variation $[W]_t$ equal for standard Brownian motion?',
    options: ['$t$', '$W_t^2$', '$0$', '$t^2$'],
    correctIndex: 0,
    explanation: 'The quadratic variation of Brownian motion is $[W]_t = t$. This is sometimes written as $(dW_t)^2 = dt$.',
    realWorld: 'Quadratic variation is what makes Itô calculus different from ordinary calculus.',
    hint: 'Think of $(dW_t)^2 = dt$ — the "Itô table".',
  },
  {
    id: 30005,
    topic: 'stochastic-calculus',
    difficulty: 'easy',
    question: 'The Black-Scholes model assumes stock prices follow which process?',
    options: ['Geometric Brownian Motion', 'Arithmetic Brownian Motion', 'Poisson Process', 'Mean-Reverting OU Process'],
    correctIndex: 0,
    explanation: 'GBM ensures prices remain positive: $dS_t = \\mu S_t \\, dt + \\sigma S_t \\, dW_t$, with solution $S_t = S_0 e^{(\\mu - \\sigma^2/2)t + \\sigma W_t}$.',
    realWorld: 'GBM is the foundation of the entire options market, worth trillions of dollars globally.',
    hint: 'The key word is "geometric" — returns are proportional to price level.',
  },
  {
    id: 30006,
    topic: 'derivatives-pricing',
    difficulty: 'easy',
    question: 'A European call option gives the holder the right to:',
    options: ['Buy the underlying at strike price $K$ at expiry', 'Sell the underlying at strike price $K$ at expiry', 'Buy or sell at any time before expiry', 'Receive dividends from the underlying'],
    correctIndex: 0,
    explanation: 'A European call gives the right (not obligation) to buy at $K$ at expiry $T$. Payoff: $\\max(S_T - K, 0)$.',
    realWorld: 'Call options let investors benefit from upside while limiting downside to the premium paid.',
    hint: 'European = exercise only at expiry. Call = right to buy.',
  },
  {
    id: 30007,
    topic: 'derivatives-pricing',
    difficulty: 'easy',
    question: 'The payoff of a European put option at expiry is:',
    options: ['$\\max(K - S_T, 0)$', '$\\max(S_T - K, 0)$', '$S_T - K$', '$K - S_T$'],
    correctIndex: 0,
    explanation: 'A put pays off when the stock finishes below strike: $\\max(K - S_T, 0)$. You profit when prices fall.',
    realWorld: 'Puts are used as portfolio insurance — they pay off when markets crash.',
    hint: 'Put = right to sell. You want price to go down.',
  },
  {
    id: 30008,
    topic: 'derivatives-pricing',
    difficulty: 'easy',
    question: 'Put-Call Parity states that (for European options):',
    options: ['$C - P = S_0 - K e^{-rT}$', '$C + P = S_0 + K$', '$C = P + S_0$', '$C \\cdot P = K^2$'],
    correctIndex: 0,
    explanation: 'Put-Call Parity: $C - P = S_0 - K e^{-rT}$. This holds in arbitrage-free markets and links call/put prices.',
    realWorld: 'Traders use put-call parity to detect mispricing and execute risk-free arbitrage.',
    hint: 'Both sides represent the same payoff replication — no arbitrage enforces equality.',
  },
  {
    id: 30009,
    topic: 'derivatives-pricing',
    difficulty: 'easy',
    question: 'The "Greeks" in options are:',
    options: ['Sensitivities of option price to various parameters', 'Types of option contracts', 'Trading strategies', 'Risk management ratios'],
    correctIndex: 0,
    explanation: 'The Greeks (Delta, Gamma, Theta, Vega, Rho) measure how option price changes with underlying price, time, volatility, and interest rates.',
    realWorld: 'Every options market maker hedges using the Greeks to maintain a delta-neutral book.',
    hint: 'Think: derivatives of the option pricing formula with respect to inputs.',
  },
  {
    id: 30010,
    topic: 'derivatives-pricing',
    difficulty: 'easy',
    question: 'Delta ($\\Delta$) of a European call option is bounded in:',
    options: ['$[0, 1]$', '$[-1, 0]$', '$[-1, 1]$', '$[0, \\infty)$'],
    correctIndex: 0,
    explanation: 'Call Delta $\\Delta \\in [0, 1]$: deep out-of-money calls have $\\Delta \\approx 0$; deep in-the-money calls have $\\Delta \\approx 1$.',
    realWorld: 'Delta tells you how many shares to hold to hedge one call option position.',
    hint: 'Delta is the probability-like quantity $N(d_1)$ in Black-Scholes.',
  },
];

export const quantHardQuestions: Question[] = [
  {
    id: 30011,
    topic: 'stochastic-calculus',
    difficulty: 'hard',
    question: "Itô's lemma for $f(t, W_t)$ states $df = f_t \\, dt + f_W \\, dW_t + \\frac{1}{2} f_{WW} \\, dt$. What is the extra $\\frac{1}{2} f_{WW} \\, dt$ term called?",
    options: ["Itô correction (or Itô's correction term)", 'Drift term', 'Variance term', 'Stratonovich correction'],
    correctIndex: 0,
    explanation: "The $\\frac{1}{2} f_{WW} \\, dt$ is the Itô correction — it arises because $(dW)^2 = dt$, making stochastic calculus differ from ordinary calculus.",
    realWorld: "This correction is crucial in deriving the Black-Scholes PDE from GBM.",
    hint: 'It comes from the second-order Taylor expansion combined with $(dW)^2 = dt$.',
  },
  {
    id: 30012,
    topic: 'stochastic-calculus',
    difficulty: 'hard',
    question: 'The Ornstein-Uhlenbeck process $dX_t = \\theta(\\mu - X_t)\\,dt + \\sigma\\,dW_t$ models:',
    options: ['Mean-reverting process (e.g., interest rates)', 'Geometric Brownian motion', 'Pure diffusion', 'Jump-diffusion process'],
    correctIndex: 0,
    explanation: 'The OU process reverts to $\\mu$ at speed $\\theta$. It is stationary and used to model interest rates (Vasicek model) and volatility.',
    realWorld: 'Used in the Vasicek interest rate model and pairs trading mean-reversion strategies.',
    hint: 'The drift term $\\theta(\\mu - X_t)$ pulls $X_t$ toward $\\mu$ when it drifts away.',
  },
  {
    id: 30013,
    topic: 'stochastic-calculus',
    difficulty: 'hard',
    question: "Girsanov's theorem allows us to change the drift of a Brownian motion by:",
    options: ["Changing the probability measure using the Radon-Nikodym derivative", 'Adding a constant to the process', 'Multiplying by a scaling factor', 'Applying a time change'],
    correctIndex: 0,
    explanation: "Girsanov's theorem: under a new measure $\\tilde{\\mathbb{P}}$, $\\tilde{W}_t = W_t + \\int_0^t \\theta_s\\,ds$ is a Brownian motion. The measure change uses $\\exp(-\\int \\theta\\,dW - \\frac{1}{2}\\int \\theta^2\\,dt)$.",
    realWorld: "This is the mathematical engine behind risk-neutral pricing in derivatives.",
    hint: 'Think about the risk-neutral measure in option pricing — that is Girsanov in action.',
  },
  {
    id: 30014,
    topic: 'stochastic-calculus',
    difficulty: 'hard',
    question: 'For GBM $S_t = S_0 e^{(\\mu - \\sigma^2/2)t + \\sigma W_t}$, what is $\\mathbb{E}[S_t]$?',
    options: ['$S_0 e^{\\mu t}$', '$S_0 e^{(\\mu - \\sigma^2/2)t}$', '$S_0(1 + \\mu t)$', '$S_0 e^{\\mu t - \\sigma^2 t}$'],
    correctIndex: 0,
    explanation: '$\\mathbb{E}[S_t] = S_0 e^{\\mu t}$ because $\\mathbb{E}[e^{\\sigma W_t}] = e^{\\sigma^2 t/2}$, so the $-\\sigma^2/2$ and $+\\sigma^2/2$ cancel.',
    realWorld: 'This shows that $\\mu$ drives expected returns, while $\\sigma$ affects the distribution shape but not the mean.',
    hint: 'Use $\\mathbb{E}[e^{aZ}] = e^{a^2/2}$ for $Z \\sim \\mathcal{N}(0,1)$.',
  },
  {
    id: 30015,
    topic: 'stochastic-calculus',
    difficulty: 'hard',
    question: 'A martingale $M_t$ satisfies $\\mathbb{E}[M_t | \\mathcal{F}_s] = M_s$ for $s < t$. Which is NOT a martingale?',
    options: ['$W_t^2$', '$W_t$', '$e^{\\sigma W_t - \\sigma^2 t/2}$', '$\\int_0^t f(s)\\,dW_s$ (for deterministic $f$)'],
    correctIndex: 0,
    explanation: '$W_t^2$ is not a martingale — $\\mathbb{E}[W_t^2 | \\mathcal{F}_s] = W_s^2 + (t-s) \\neq W_s^2$. However $W_t^2 - t$ IS a martingale.',
    realWorld: 'Identifying martingales is key to option pricing and detecting arbitrage opportunities.',
    hint: 'Compute $\\mathbb{E}[W_t^2|W_s]$ using $W_t = W_s + (W_t - W_s)$ and independence.',
  },
  {
    id: 30016,
    topic: 'derivatives-pricing',
    difficulty: 'hard',
    question: 'The Black-Scholes formula for a European call is $C = S_0 N(d_1) - K e^{-rT} N(d_2)$ where $d_1 - d_2 =$:',
    options: ['$\\sigma\\sqrt{T}$', '$\\mu T$', '$rT$', '$\\sigma^2 T$'],
    correctIndex: 0,
    explanation: '$d_1 = \\frac{\\ln(S_0/K) + (r + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$, $d_2 = d_1 - \\sigma\\sqrt{T}$. The gap is exactly $\\sigma\\sqrt{T}$.',
    realWorld: 'This difference reflects the distinction between delta ($N(d_1)$) and exercise probability ($N(d_2)$).',
    hint: 'Write out $d_1$ and $d_2$ explicitly and subtract.',
  },
  {
    id: 30017,
    topic: 'derivatives-pricing',
    difficulty: 'hard',
    question: 'Gamma ($\\Gamma$) is the second derivative of option price with respect to spot. For a call at-the-money (ATM):',
    options: ['Gamma is maximized', 'Gamma is zero', 'Gamma equals Delta', 'Gamma is negative'],
    correctIndex: 0,
    explanation: 'Gamma peaks at-the-money because that is where Delta is most sensitive to small price moves. Deep ITM/OTM options have near-zero Gamma.',
    realWorld: 'Gamma scalping — delta-hedging a long-gamma position — is a core market-making strategy.',
    hint: 'Think about where a small move in $S$ changes Delta the most.',
  },
  {
    id: 30018,
    topic: 'derivatives-pricing',
    difficulty: 'hard',
    question: 'Under the risk-neutral measure $\\mathbb{Q}$, the stock price drifts at:',
    options: ['The risk-free rate $r$', 'The real-world drift $\\mu$', 'Zero', '$\\mu - r$'],
    correctIndex: 0,
    explanation: 'Under $\\mathbb{Q}$: $dS_t = r S_t\\,dt + \\sigma S_t\\,d\\tilde{W}_t$. The drift becomes $r$ regardless of $\\mu$ — this is the essence of risk-neutral pricing.',
    realWorld: 'This allows us to price derivatives without knowing investor risk preferences.',
    hint: "Girsanov's theorem shifts real drift $\\mu$ to risk-free $r$ under the risk-neutral measure.",
  },
  {
    id: 30019,
    topic: 'derivatives-pricing',
    difficulty: 'hard',
    question: 'Vega ($\\mathcal{V}$) measures sensitivity to implied volatility. Vega is highest for:',
    options: ['Long-dated, ATM options', 'Deep OTM options', 'Short-dated, deep ITM options', 'Forward contracts'],
    correctIndex: 0,
    explanation: 'Vega increases with time to expiry (more uncertainty) and peaks ATM (where payoff is most uncertain). $\\mathcal{V} = S_0 \\sqrt{T} N\'(d_1)$.',
    realWorld: 'Options traders "trade volatility" via vega — buying options when vol is cheap, selling when expensive.',
    hint: 'More time = more uncertainty = higher sensitivity to vol. ATM has the most convexity.',
  },
  {
    id: 30020,
    topic: 'derivatives-pricing',
    difficulty: 'hard',
    question: 'The volatility smile refers to:',
    options: ['Implied volatility varying with strike — higher for OTM options', 'Actual volatility exceeding implied volatility', 'Historical volatility increasing over time', 'A model where volatility is constant'],
    correctIndex: 0,
    explanation: 'Implied vol is not constant across strikes (contradicting Black-Scholes). OTM puts and calls tend to have higher implied vols — forming a "smile" or "skew".',
    realWorld: 'The vol smile reflects market fear of tail events and is modeled by stochastic vol models like Heston.',
    hint: 'If Black-Scholes were perfect, implied vol would be flat across all strikes.',
  },
];

export const quantSotaQuestions: Question[] = [
  {
    id: 30021,
    topic: 'stochastic-calculus',
    difficulty: 'sota',
    question: "The Feynman-Kac theorem connects PDEs to expectations. For the PDE $\\frac{\\partial u}{\\partial t} + \\frac{\\sigma^2}{2} \\frac{\\partial^2 u}{\\partial x^2} = 0$ with terminal condition $u(T,x) = g(x)$, the solution is:",
    options: ['$u(t,x) = \\mathbb{E}[g(x + \\sigma(W_T - W_t))]$', '$u(t,x) = \\int g(x)\\,dx$', '$u(t,x) = g(x) e^{-\\sigma^2(T-t)/2}$', '$u(t,x) = \\sigma^2 g\'\'(x)(T-t)$'],
    correctIndex: 0,
    explanation: "Feynman-Kac: the PDE solution equals the expectation of the terminal condition under the Brownian path. This is the bridge between stochastic calculus and PDEs.",
    realWorld: 'The Black-Scholes PDE is solved using Feynman-Kac — option price = discounted expected payoff.',
    hint: 'The PDE backward equation corresponds to the forward SDE $dX = \\sigma\\,dW$.',
  },
  {
    id: 30022,
    topic: 'stochastic-calculus',
    difficulty: 'sota',
    question: 'The Heston stochastic volatility model has variance $v_t$ following $dv_t = \\kappa(\\theta - v_t)\\,dt + \\xi\\sqrt{v_t}\\,dW_t^v$. The Feller condition $2\\kappa\\theta > \\xi^2$ ensures:',
    options: ['Variance stays strictly positive (process does not hit zero)', 'Variance is mean-reverting', 'Correlation between vol and spot is bounded', 'The model is arbitrage-free'],
    correctIndex: 0,
    explanation: 'The Feller condition ensures the CIR variance process stays positive a.s. Without it, $v_t$ can reach zero and become degenerate.',
    realWorld: 'Practitioners calibrate the Heston model to the vol surface; the Feller condition is a stability constraint.',
    hint: 'This is the same Feller condition as in the Cox-Ingersoll-Ross interest rate model.',
  },
  {
    id: 30023,
    topic: 'derivatives-pricing',
    difficulty: 'sota',
    question: 'In the SABR model, the implied vol smile is approximated by Hagan et al. The "backbone" (how ATM vol moves as $F$ changes) depends critically on:',
    options: ['The $\\beta$ parameter controlling the vol-of-vol backbone', 'The correlation $\\rho$', 'The vol-of-vol $\\alpha$', 'The initial forward $F_0$'],
    correctIndex: 0,
    explanation: '$\\beta \\in [0,1]$ determines whether the model behaves like normal ($\\beta=0$), log-normal ($\\beta=1$), or something in between. It controls the ATM vol level as a function of $F$.',
    realWorld: 'SABR is the industry standard model for interest rate derivatives (swaptions, caps/floors).',
    hint: '$\\beta=0$ gives a normal (Bachelier) backbone; $\\beta=1$ gives a log-normal backbone.',
  },
  {
    id: 30024,
    topic: 'derivatives-pricing',
    difficulty: 'sota',
    question: 'The fundamental theorem of asset pricing states that a market is arbitrage-free if and only if:',
    options: ['There exists an equivalent martingale measure (EMM)', 'All asset prices are martingales', 'The risk-free rate equals the drift', 'Options are priced by expected payoff'],
    correctIndex: 0,
    explanation: 'First FTAP: no-arbitrage ⟺ existence of an EMM $\\mathbb{Q}$ under which discounted prices are martingales. Completeness adds uniqueness of $\\mathbb{Q}$.',
    realWorld: 'This theorem is the mathematical backbone of the entire derivatives industry.',
    hint: 'EMM = equivalent martingale measure. "Equivalent" means same null sets as the real-world measure.',
  },
  {
    id: 30025,
    topic: 'derivatives-pricing',
    difficulty: 'sota',
    question: 'The Dupire local volatility model reconstructs $\\sigma(K,T)$ from the market price surface $C(K,T)$ using the Dupire formula. It gives $\\sigma^2(K,T) =$:',
    options: ['$\\dfrac{\\partial C/\\partial T}{\\frac{1}{2} K^2 \\partial^2 C/\\partial K^2}$', '$\\dfrac{\\partial^2 C}{\\partial K^2}$', '$\\dfrac{C(K,T)}{K e^{-rT}}$', '$\\dfrac{\\partial C/\\partial K}{\\partial C/\\partial T}$'],
    correctIndex: 0,
    explanation: "Dupire's formula extracts the local vol from the market's observed option prices. It implies a unique local vol surface consistent with all vanilla option prices.",
    realWorld: 'Local vol is the standard calibration tool for exotic option pricing in practice.',
    hint: 'Breeden-Litzenberger gives the risk-neutral density from $\\partial^2 C/\\partial K^2$; Dupire combines this with calendar spread pricing.',
  },
];
