import type { Question } from '../types';

export const economicsQuestions: Question[] = [
  // ── Microeconomics ──────────────────────────────────────────
  {
    id: 490001, topic: 'microeconomics', difficulty: 'easy',
    question: 'The law of demand states that, ceteris paribus, as price increases:',
    options: ['Quantity demanded decreases', 'Quantity demanded increases', 'Supply increases', 'Demand curve shifts right'],
    correctIndex: 0,
    explanation: 'The law of demand reflects the inverse relationship between price and quantity demanded, shown by a downward-sloping demand curve.',
    realWorld: 'When gas prices spike, people drive less and switch to public transit.',
    hint: 'Think about what happens to your shopping behavior when prices go up.',
  },
  {
    id: 490002, topic: 'microeconomics', difficulty: 'hard',
    question: 'In a Nash equilibrium:',
    options: ["No profitable unilateral deviation","All players achieve maximum payoff","One player dominates all others","Players must cooperate"],
    correctIndex: 0,
    explanation: 'A Nash equilibrium is a strategy profile where each player\'s strategy is a best response to the others — no unilateral deviation is profitable.',
    realWorld: 'The Prisoner\'s Dilemma Nash equilibrium explains why competitors often fail to cooperate even when mutual cooperation would be better.',
    hint: 'Named after John Nash — think about what happens when everyone plays their best response.',
  },
  {
    id: 490003, topic: 'microeconomics', difficulty: 'sota',
    question: 'The Arrow-Debreu theorem proves the existence of general equilibrium under conditions including:',
    options: ["Market-clearing prices exist","Perfect information only","Zero transaction costs only","Government price controls"],
    correctIndex: 0,
    explanation: 'Arrow and Debreu (1954) used fixed-point theorems to prove existence of competitive equilibrium prices that clear all markets simultaneously, under specific mathematical conditions.',
    realWorld: 'This theorem is the foundation of modern general equilibrium theory and earned both economists Nobel Prizes.',
    hint: 'They used Kakutani\'s fixed-point theorem — think about when supply equals demand everywhere.',
  
    paper: {"title":"Existence of an Equilibrium for a Competitive Economy","url":"https://doi.org/10.2307/1907353","venue":"Econometrica","year":1954},
    reviewedAt: "2026-09-19",
  },
  // ── Macroeconomics ──────────────────────────────────────────
  {
    id: 490004, topic: 'macroeconomics', difficulty: 'easy',
    question: 'GDP (Gross Domestic Product) measures:',
    options: ["Final domestic production","Total government spending","Total exports minus imports","Total stock market value"],
    correctIndex: 0,
    explanation: 'GDP = C + I + G + (X - M), where C is consumption, I is investment, G is government spending, and (X-M) is net exports.',
    realWorld: 'GDP growth rate is the most widely watched indicator of economic health.',
    hint: 'It captures the entire production output of a nation\'s economy.',
  },
  {
    id: 490005, topic: 'macroeconomics', difficulty: 'hard',
    question: 'The Phillips curve describes the short-run tradeoff between:',
    options: ['Inflation and unemployment', 'GDP and interest rates', 'Money supply and velocity', 'Taxes and government spending'],
    correctIndex: 0,
    explanation: 'A.W. Phillips observed an inverse relationship between wage inflation and unemployment. In the short run, stimulating demand reduces unemployment but increases inflation.',
    realWorld: 'Central banks use this tradeoff when setting interest rates — lowering rates reduces unemployment but may raise inflation.',
    hint: 'Think about what happens to wages and prices when the job market is very tight.',
  },
  {
    id: 490006, topic: 'macroeconomics', difficulty: 'sota',
    question: 'In DSGE models, the Euler equation for consumption relates:',
    options: ["Marginal utility across time","GDP to money supply","Investment to depreciation","Exports to exchange rates"],
    correctIndex: 0,
    explanation: 'The consumption Euler equation $u\'(c_t) = \\beta(1 + r_t)E_t[u\'(c_{t+1})]$ is the intertemporal optimality condition that governs household saving/consumption decisions in DSGE models.',
    realWorld: 'Central banks use DSGE models incorporating this equation to forecast the effects of monetary policy.',
    hint: 'Households optimize consumption across time periods — this is the first-order condition.',
  
    sources: [{"title":"Shocks and Frictions in US Business Cycles: A Bayesian DSGE Approach","url":"https://www.aeaweb.org/articles?id=10.1257/aer.97.3.586","publisher":"American Economic Association","year":2007}],
    reviewedAt: "2026-09-19",
  },
  // ── Econometrics ──────────────────────────────────────────
  {
    id: 490007, topic: 'econometrics', difficulty: 'easy',
    question: 'Ordinary Least Squares (OLS) regression minimizes:',
    options: ['The sum of squared residuals', 'The sum of absolute residuals', 'The maximum residual', 'The number of outliers'],
    correctIndex: 0,
    explanation: 'OLS finds the line that minimizes $\\sum_{i=1}^n (y_i - \\hat{y}_i)^2$, the total squared vertical distance between observed and predicted values.',
    realWorld: 'OLS is the most widely used regression method in social sciences, economics, and policy analysis.',
    hint: 'Squaring the residuals penalizes large errors more than small ones.',
  },
  {
    id: 490008, topic: 'econometrics', difficulty: 'hard',
    question: 'Instrumental variables (IV) estimation addresses:',
    options: ["Endogeneity","Heteroscedasticity","Multicollinearity","Serial correlation"],
    correctIndex: 0,
    explanation: 'IV estimation uses instruments correlated with the endogenous regressor but uncorrelated with the error term, providing consistent estimates when OLS is biased.',
    realWorld: 'Angrist & Krueger used quarter of birth as an instrument for education to estimate returns to schooling.',
    hint: 'The instrument must affect Y only through X — the exclusion restriction.',
  },
  {
    id: 490009, topic: 'econometrics', difficulty: 'sota',
    question: 'The difference-in-differences (DiD) estimator requires the assumption of:',
    options: ["Parallel counterfactual trends","Random assignment to treatment","Homogeneous treatment effects","No spillover between groups"],
    correctIndex: 0,
    explanation: 'DiD compares changes over time between treated and control groups. The key identifying assumption is that both groups would have followed parallel trends without the intervention.',
    realWorld: 'Card & Krueger\'s minimum wage study used DiD to compare employment in NJ vs PA after NJ raised its minimum wage.',
    hint: 'If the trends weren\'t parallel before treatment, the DiD estimate is biased.',
  
    sources: [{"title":"The Prize in Economic Sciences 2021","url":"https://www.nobelprize.org/prizes/economic-sciences/2021/press-release/","publisher":"Nobel Prize Outreach","year":2021}],
    reviewedAt: "2026-09-19",
  },

  // ── Microeconomics foundation expansion ──────────────────────────
  {
    id: 490010, topic: "microeconomics", difficulty: "easy",
    question: "Opportunity cost is:",
    options: ["A sunk accounting cost","The best forgone alternative","A tax on consumption","A firm's total revenue"],
    correctIndex: 1,
    explanation: "Opportunity cost is the value of the most valuable alternative sacrificed by choosing one use of a scarce resource.",
    realWorld: "The concept applies to time, capital, labor, land, and household choices.",
    hint: "Ask what you give up by making the choice.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490011, topic: "microeconomics", difficulty: "easy",
    question: "A binding price ceiling below equilibrium tends to create:",
    options: ["A surplus","A demand shift","A shortage","A supply shift"],
    correctIndex: 2,
    explanation: "At a capped price below equilibrium, quantity demanded exceeds quantity supplied, creating excess demand.",
    realWorld: "Rent controls and price caps are often analyzed with this basic supply-and-demand framework.",
    hint: "Compare quantity demanded with quantity supplied.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490012, topic: "microeconomics", difficulty: "hard",
    question: "If demand is price elastic, a small price increase usually makes total revenue:",
    options: ["Rise","Stay fixed","Turn negative","Fall"],
    correctIndex: 3,
    explanation: "With elastic demand, quantity falls proportionally more than price rises, so price times quantity declines.",
    realWorld: "Elasticity is central to pricing, tax incidence, and revenue analysis.",
    hint: "The quantity response dominates the price change.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490013, topic: "microeconomics", difficulty: "hard",
    question: "A single-price monopolist maximizes profit where:",
    options: ["Price equals average cost","Marginal revenue equals marginal cost","Demand is perfectly elastic","Consumer surplus is zero"],
    correctIndex: 1,
    explanation: "The monopolist chooses quantity where marginal revenue equals marginal cost, then uses demand to determine price.",
    realWorld: "The rule separates the output decision from the market price for that output.",
    hint: "Compare the extra revenue and cost of one more unit.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490014, topic: "microeconomics", difficulty: "sota",
    question: "Deferred acceptance in two-sided matching is designed to produce:",
    options: ["The highest price","Random assignment","A stable matching","Equal utility"],
    correctIndex: 2,
    explanation: "Gale-Shapley deferred acceptance produces a stable matching with no blocking pair who prefer one another to their assignments.",
    realWorld: "Matching-market design matters when prices alone cannot allocate scarce positions.",
    hint: "Stability rules out mutually preferred deviations.",
    sources: [{"title":"The Prize in Economic Sciences 2012","url":"https://www.nobelprize.org/prizes/economic-sciences/2012/press-release/","publisher":"Nobel Prize Outreach","year":2012}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 490015, topic: "microeconomics", difficulty: "sota",
    question: "In common-value auctions, winning with an unusually high estimate creates the risk called:",
    options: ["Moral hazard","Adverse selection","Price discrimination","Winner's curse"],
    correctIndex: 3,
    explanation: "When bidders estimate the same uncertain value, winning can signal that one's estimate was especially optimistic.",
    realWorld: "Auction theory informs spectrum sales, procurement, energy markets, and online advertising.",
    hint: "Winning can itself be information about your estimate.",
    sources: [{"title":"The Prize in Economic Sciences 2020","url":"https://www.nobelprize.org/prizes/economic-sciences/2020/press-release/","publisher":"Nobel Prize Outreach","year":2020}],
    reviewedAt: "2026-09-19",
  },

  // ── Macroeconomics foundation expansion ──────────────────────────
  {
    id: 490016, topic: "macroeconomics", difficulty: "easy",
    question: "Inflation is:",
    options: ["A fall in output","A broad rise in prices","Any one price increase","A rise in wages only"],
    correctIndex: 1,
    explanation: "Inflation is a broad increase in the general price level, measured with price indexes rather than one product's price.",
    realWorld: "Inflation changes purchasing power and influences interest rates, contracts, and monetary policy.",
    hint: "Think economy-wide prices.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490017, topic: "macroeconomics", difficulty: "easy",
    question: "The denominator of the unemployment rate is:",
    options: ["Total population","Employed workers","The labor force","Working-age population"],
    correctIndex: 2,
    explanation: "The labor force includes employed people plus unemployed people meeting the statistical criteria for participation.",
    realWorld: "Participation changes can alter the unemployment rate even when population is unchanged.",
    hint: "Exclude people outside the labor force.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490018, topic: "macroeconomics", difficulty: "hard",
    question: "The Fisher relation approximates the nominal rate as:",
    options: ["Real rate minus inflation","Money growth plus GDP","Inflation divided by growth","Real rate plus expected inflation"],
    correctIndex: 3,
    explanation: "For moderate rates, the nominal interest rate is approximately the real rate plus expected inflation.",
    realWorld: "The relation separates a real return from compensation for expected loss of purchasing power.",
    hint: "Add real return and expected inflation.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490019, topic: "macroeconomics", difficulty: "hard",
    question: "An automatic fiscal stabilizer is:",
    options: ["A discretionary stimulus vote","Automatic tax and transfer changes","A central-bank rate cut","A currency peg"],
    correctIndex: 1,
    explanation: "Progressive taxes and transfers such as unemployment benefits respond automatically to income and employment changes.",
    realWorld: "These mechanisms cushion disposable income and aggregate demand during downturns.",
    hint: "Look for a fiscal response that happens without a new vote.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490020, topic: "macroeconomics", difficulty: "sota",
    question: "HANK models emphasize monetary-policy transmission through:",
    options: ["Money-supply accounting","Direct substitution only","Income and equilibrium channels","Identical-household channels"],
    correctIndex: 2,
    explanation: "HANK models combine nominal rigidities with household heterogeneity and incomplete insurance, making indirect income and equilibrium effects important.",
    realWorld: "The framework connects policy to wealth, liquidity, and different marginal propensities to consume.",
    hint: "Heterogeneity changes how policy reaches households.",
    paper: {"title":"Monetary Policy According to HANK","url":"https://www.aeaweb.org/articles?id=10.1257/aer.20160042","venue":"American Economic Review","year":2018},
    reviewedAt: "2026-09-19",
  },
  {
    id: 490021, topic: "macroeconomics", difficulty: "sota",
    question: "R-star is an estimate of:",
    options: ["Observed nominal policy rate","Long-run inflation target","Long-run equity return","Neutral real interest rate"],
    correctIndex: 3,
    explanation: "The natural rate of interest is an unobserved real short-term rate associated with full economic strength and stable inflation.",
    realWorld: "Policymakers use r-star estimates as one reference for judging monetary-policy stance.",
    hint: "It is a latent real equilibrium rate.",
    sources: [{"title":"Measuring the Natural Rate of Interest","url":"https://www.newyorkfed.org/research/policy/rstar","publisher":"Federal Reserve Bank of New York","year":2026}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },

  // ── Econometrics foundation expansion ──────────────────────────
  {
    id: 490022, topic: "econometrics", difficulty: "easy",
    question: "A high correlation between X and Y by itself establishes:",
    options: ["Random assignment is proven","No causal conclusion alone","X directly causes Y","Y directly causes X"],
    correctIndex: 1,
    explanation: "Correlation alone cannot distinguish causation from reverse causality, omitted variables, selection, or coincidence.",
    realWorld: "Econometric designs add assumptions or exogenous variation to support causal claims.",
    hint: "Association is not a causal direction.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490023, topic: "econometrics", difficulty: "easy",
    question: "R-squared primarily summarizes:",
    options: ["Causal validity","Sampling randomness","In-sample explained variation","Instrument strength"],
    correctIndex: 2,
    explanation: "R-squared summarizes in-sample fit by comparing residual and total variation; it does not establish causality.",
    realWorld: "A high R-squared can coexist with biased coefficients or poor out-of-sample performance.",
    hint: "Treat it as a fit statistic.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490024, topic: "econometrics", difficulty: "hard",
    question: "A valid instrumental-variable design needs:",
    options: ["Large R-squared","Normal outcomes","No controls","Relevance and exclusion"],
    correctIndex: 3,
    explanation: "An instrument must shift the endogenous regressor and satisfy a credible exclusion-type condition for causal interpretation.",
    realWorld: "IV designs help when treatment is endogenous but an external source of variation exists.",
    hint: "The instrument must move X without another path to Y.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490025, topic: "econometrics", difficulty: "hard",
    question: "Unit fixed effects absorb:",
    options: ["Common time shocks","Time-invariant unit differences","All measurement error","Future treatment effects"],
    correctIndex: 1,
    explanation: "Unit fixed effects remove additive characteristics that do not change over time within a unit.",
    realWorld: "Panel designs often combine unit and time effects, but fixed effects do not solve every endogeneity problem.",
    hint: "Compare each unit mostly with itself over time.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 490026, topic: "econometrics", difficulty: "sota",
    question: "Double/debiased ML combines flexible nuisance models with:",
    options: ["Single-sample neural fitting","Ordinary least squares only","Orthogonality and cross-fitting","Bootstrap without sample splits"],
    correctIndex: 2,
    explanation: "DML uses orthogonal scores to reduce sensitivity to nuisance-estimation error and cross-fitting to limit overfitting bias.",
    realWorld: "It supports flexible prediction methods while preserving inference for selected target parameters under stated conditions.",
    hint: "Its signature ingredients are orthogonality and sample splitting.",
    paper: {"title":"Double/debiased machine learning for treatment and structural parameters","url":"https://academic.oup.com/ectj/article/21/1/C1/5056401","venue":"The Econometrics Journal","year":2018},
    reviewedAt: "2026-09-19",
  },
  {
    id: 490027, topic: "econometrics", difficulty: "sota",
    question: "Synthetic control builds a counterfactual using:",
    options: ["One treated trend","A random treated subset","No comparison units","A weighted donor combination"],
    correctIndex: 3,
    explanation: "Synthetic control weights untreated donor units so their pre-treatment path approximates the treated unit, then uses that path as a counterfactual.",
    realWorld: "It is widely used for aggregate policy interventions when randomized designs are unavailable.",
    hint: "Build one synthetic comparison from several donors.",
    paper: {"title":"Synthetic Control Methods for Comparative Case Studies","url":"https://www.nber.org/papers/w12831","venue":"Journal of the American Statistical Association","year":2010},
    reviewedAt: "2026-09-19",
  },
];
