import type { Question } from '../types';

export const alanTuringQuestions: Question[] = [
  {
    id: 10011,
    topic: 'alan-turing',
    difficulty: 'easy',
    question: 'What does a Turing Machine consist of?',
    options: [
      'An infinite tape, a read/write head, a state register, and a transition function',
      'A neural network, a memory stack, and a pointer register',
      'A set of logic gates, flip-flops, and a clock signal',
      'A finite set of rules, an output buffer, and a cache',
    ],
    correctIndex: 0,
    explanation: 'A Turing Machine is an abstract model with: an infinite tape (memory), a read/write head that moves along the tape, a finite set of states, and a transition function that specifies the next state, symbol, and head direction.',
    realWorld: 'Every programming language is Turing complete if it can simulate this model — Python, JavaScript, SQL, even Excel formulas under certain conditions.',
    hint: 'Think of it as a mathematician with an endless notepad, an eraser, and a rulebook.',
  },
  {
    id: 10012,
    topic: 'alan-turing',
    difficulty: 'easy',
    question: 'The Turing Test (1950) evaluates machine intelligence by:',
    options: [
      'Checking if a human evaluator cannot distinguish a machine from a human in natural conversation',
      'Measuring a machine\'s score on standardized IQ tests',
      'Counting how many problems a machine solves correctly per second',
      'Evaluating whether a machine can play chess at grandmaster level',
    ],
    correctIndex: 0,
    explanation: 'Turing proposed the "imitation game": an evaluator communicates via text with a human and a machine; if the evaluator cannot reliably identify which is which, the machine passes. This operationalized "intelligence" without defining it philosophically.',
    realWorld: 'GPT-4 has passed informal Turing tests in many domains, reigniting debate about whether the test is a sufficient criterion for intelligence.',
    hint: 'It\'s a conversation game — the machine wins if the human judge is fooled.',
  },
  {
    id: 10013,
    topic: 'alan-turing',
    difficulty: 'easy',
    question: 'The Halting Problem states that:',
    options: [
      'No general algorithm can determine whether an arbitrary program will halt or run forever',
      'Programs with infinite loops always terminate given enough memory',
      'Any program running longer than polynomial time is unsolvable',
      'All Turing-complete languages have the same computational power up to halting',
    ],
    correctIndex: 0,
    explanation: 'Turing (1936) proved by diagonalization that no program $H$ can exist that correctly decides for all programs $P$ and inputs $x$ whether $P(x)$ halts. This is the first undecidability result in computer science.',
    realWorld: 'Static analysis tools (linters, compilers) can only detect some infinite loops — the full problem is provably unsolvable for all programs.',
    hint: 'Assume such a program exists, then feed it a self-referential program — a contradiction arises.',
  },
  {
    id: 10014,
    topic: 'alan-turing',
    difficulty: 'easy',
    question: 'Church-Turing Thesis states:',
    options: [
      'Every effectively computable function can be computed by a Turing Machine',
      'All NP problems reduce to SAT in polynomial time',
      'Any function computable in polynomial time is also verifiable in polynomial time',
      'No physical machine can exceed the computational power of a Turing Machine',
    ],
    correctIndex: 0,
    explanation: 'The Church-Turing Thesis is not a theorem but a thesis — it claims that the informal notion of "computable by an algorithm" is captured exactly by Turing Machine computability. It unifies lambda calculus (Church) and Turing Machines.',
    realWorld: 'This thesis is the foundation of computer science — it tells us what can and cannot be automated, regardless of the hardware.',
    hint: 'It connects the informal idea of "algorithm" to a precise mathematical model.',
  },
  {
    id: 10015,
    topic: 'alan-turing',
    difficulty: 'hard',
    question: 'Turing\'s proof of the Halting Problem uses:',
    options: [
      'Diagonalization: constructing a program that does the opposite of what H predicts',
      'Reduction from the 3-SAT problem to show NP-completeness',
      'Fixed-point theorem applied to recursive program states',
      'Gödel numbering to encode programs as natural numbers and derive a contradiction',
    ],
    correctIndex: 0,
    explanation: 'Assume $H(P, x)$ halts correctly. Build $D(P)$: if $H(P,P) = $ "halts", loop forever; else halt. Then $D(D)$: if $H(D,D) = $ "halts", $D(D)$ loops — contradiction. If $H(D,D) = $ "loops", $D(D)$ halts — contradiction. Hence $H$ cannot exist.',
    realWorld: 'This argument structure (diagonalization) appears throughout mathematics and CS — Cantor\'s uncountability, Gödel\'s incompleteness, Rice\'s theorem.',
    hint: 'Build a program that contradicts the oracle\'s prediction about itself.',
  },
  {
    id: 10016,
    topic: 'alan-turing',
    difficulty: 'hard',
    question: 'An oracle Turing Machine $M^A$ can solve problems in class $X^A$. What does a Turing reduction from $B$ to $A$ (written $B \\leq_T A$) imply?',
    options: [
      'If $A$ is decidable then $B$ is decidable; the halting problem relative to $A$ may differ from absolute halting',
      'A and B are in the same complexity class P',
      'B is computable in polynomial time given A as a subroutine',
      'A and B are both undecidable but A is harder than B',
    ],
    correctIndex: 0,
    explanation: 'A Turing reduction $B \\leq_T A$ means $B$ is solvable given an oracle for $A$. If $A$ is decidable, so is $B$. Contrapositive: if $B$ is undecidable, so is $A$. This defines the arithmetical hierarchy of undecidability.',
    realWorld: 'The halting problem relative to an oracle can be strictly harder — this is Turing\'s jump operation, foundational in computability theory.',
    hint: 'Think of the oracle as a magic function — if you could call it, could you solve B?',
  },
  {
    id: 10017,
    topic: 'alan-turing',
    difficulty: 'hard',
    question: 'Rice\'s theorem states: for any non-trivial property $P$ of programs (functions they compute):',
    options: [
      'Deciding whether a given program has property $P$ is undecidable',
      'Property $P$ is decidable if and only if it is monotone',
      'Deciding $P$ requires exponential time in the program length',
      'Property $P$ can be approximated with at most 50% error',
    ],
    correctIndex: 0,
    explanation: 'Rice\'s theorem (1953) generalizes the halting problem: you cannot algorithmically decide any non-trivial semantic property of programs. "Non-trivial" means some programs have it and some don\'t.',
    realWorld: 'This means detecting all malware, all memory leaks, or all copyright violations by static analysis is provably impossible — security tools can only catch known patterns.',
    hint: 'If you could decide any non-trivial property, you could solve the halting problem.',
  },
  {
    id: 10018,
    topic: 'alan-turing',
    difficulty: 'sota',
    question: 'In the context of Turing\'s morphogenesis paper (1952), reaction-diffusion systems produce patterns because:',
    options: [
      'An activator diffuses slowly and a fast inhibitor create spatial instability leading to stable periodic patterns',
      'Random genetic mutations produce phenotypic variation selected by fitness',
      'Chemical gradients act as positional information during embryo development',
      'Protein folding creates self-similar fractal patterns through recursive chemical bonds',
    ],
    correctIndex: 0,
    explanation: 'Turing showed that two chemicals — a slow-diffusing activator and a fast-diffusing inhibitor — can spontaneously break symmetry. The math is a PDE system where uniform equilibrium becomes unstable, producing periodic spatial patterns (stripes, spots).',
    realWorld: 'Turing patterns explain animal coat markings (leopard spots, zebra stripes), neural column formation, and finger spacing in embryos.',
    hint: 'Fast diffusion of inhibitor + slow diffusion of activator = long-range inhibition, short-range activation.',
  },
  {
    id: 10019,
    topic: 'alan-turing',
    difficulty: 'sota',
    question: 'The complexity class BQP (Bounded-error Quantum Polynomial time) relates to Turing machines as:',
    options: [
      'BQP ⊆ PSPACE and P ⊆ BQP, but it is unknown whether BQP ⊆ P or BQP ⊇ NP',
      'BQP = P because quantum speedup is only constant factor',
      'BQP = NP because Shor\'s algorithm solves all NP problems',
      'BQP ⊃ PSPACE because quantum memory is unbounded',
    ],
    correctIndex: 0,
    explanation: 'Quantum computers (BQP) sit between P and PSPACE. Shor\'s algorithm proves factoring ∈ BQP but factoring is not known NP-complete. BQP likely doesn\'t contain all of NP — quantum isn\'t magic, just a different model.',
    realWorld: 'This complexity distinction tells us which problems quantum computers will (cryptography, simulation) and won\'t (NP-complete optimization) definitively solve.',
    hint: 'Quantum speedup is not unlimited — it helps with certain algebraic and search problems, not all hard problems.',
  },
  {
    id: 10020,
    topic: 'alan-turing',
    difficulty: 'sota',
    question: 'A Universal Turing Machine (UTM) $U$ can simulate any Turing Machine $M$ on input $x$ by:',
    options: [
      'Reading the encoding $\\langle M \\rangle$ and $x$ from tape, and simulating $M$\'s transitions step by step',
      'Compiling $M$ to a fixed hardware circuit and running $x$ through it',
      'Applying $M$\'s transition function as a lookup table stored in RAM',
      'Executing $M$ in parallel with all possible inputs simultaneously',
    ],
    correctIndex: 0,
    explanation: 'A UTM accepts $\\langle M, x \\rangle$ — the Gödel-encoded description of $M$ followed by input $x$ — and faithfully simulates each transition of $M$ on $x$. This proves one machine suffices to compute everything computable.',
    realWorld: 'Every modern computer is a physical UTM — your CPU executes any program you give it, exactly as Turing described.',
    hint: 'The key insight: programs are just data. The UTM reads the program description and interprets it.',
  },
];
