import type { Question } from '../types';

export const alexanderGrothendieckQuestions: Question[] = [
  {
    id: 12301,
    topic: 'alexander-grothendieck',
    difficulty: 'easy',
    question: 'Alexander Grothendieck revolutionized algebraic geometry by introducing:',
    options: [
      'Schemes — a vast generalization of algebraic varieties using commutative algebra and category theory',
      'Fractals — self-similar geometric objects with non-integer dimension',
      'Non-Euclidean geometry — consistent geometries violating the parallel postulate',
      'Graph theory — the mathematical study of networks and connections',
    ],
    correctIndex: 0,
    explanation: 'Grothendieck\'s scheme theory replaced classical varieties with locally ringed spaces built from commutative rings. This allowed algebraic geometry to work over any ring, unifying number theory and geometry.',
    realWorld: 'Scheme theory underpins modern cryptography (elliptic curve cryptography uses schemes over finite fields), the proof of Fermat\'s Last Theorem (Wiles), and arithmetic geometry.',
    hint: 'He replaced "solutions of polynomial equations" with a far more general algebraic-geometric framework.',
  },
  {
    id: 12302,
    topic: 'alexander-grothendieck',
    difficulty: 'easy',
    question: 'Grothendieck\'s approach to mathematics was characterized by:',
    options: [
      'Extreme abstraction — building the most general framework first, then deriving results as special cases',
      'Computational experimentation — testing conjectures with specific numerical examples',
      'Minimalism — proving theorems with the shortest possible proofs',
      'Collaboration — always working in large teams on joint projects',
    ],
    correctIndex: 0,
    explanation: 'Grothendieck famously described his approach as "the rising sea" — building abstract frameworks so general that difficult theorems become trivially obvious. His EGA and SGA seminars reshaped all of algebraic geometry.',
    realWorld: 'His philosophy of "generalize until the problem becomes trivial" has influenced software engineering (category theory in functional programming, Haskell) and theoretical physics.',
    hint: 'He compared it to the sea rising to submerge a rock — rather than attacking the rock (problem) directly.',
  },
  {
    id: 12303,
    topic: 'alexander-grothendieck',
    difficulty: 'hard',
    question: 'Grothendieck\'s étale cohomology theory was created specifically to:',
    options: [
      'Prove the Weil conjectures — providing a topological framework for varieties over finite fields',
      'Classify all algebraic curves over the complex numbers',
      'Compute intersection numbers on moduli spaces',
      'Solve Diophantine equations using p-adic methods',
    ],
    correctIndex: 0,
    explanation: 'The Weil conjectures (analogues of the Riemann Hypothesis for varieties over finite fields) required a cohomology theory that works in positive characteristic. Grothendieck built étale cohomology for this purpose; Deligne completed the proof.',
    realWorld: 'Étale cohomology is fundamental in modern number theory and was essential in the proof of Fermat\'s Last Theorem (modularity of elliptic curves).',
    hint: 'Over finite fields, the classical topology doesn\'t work — Grothendieck invented a new kind of topology.',
  },
  {
    id: 12304,
    topic: 'alexander-grothendieck',
    difficulty: 'hard',
    question: 'Grothendieck\'s introduction of toposes generalized the notion of:',
    options: [
      'Topological spaces — a topos is a category that behaves like the category of sheaves on a space',
      'Groups — a topos is a group with additional categorical structure',
      'Vector spaces — a topos replaces linear algebra with categorical algebra',
      'Manifolds — a topos is a smooth space with corners',
    ],
    correctIndex: 0,
    explanation: 'A Grothendieck topos is a category equivalent to the category of sheaves on some site. Toposes provide a framework where geometry, logic, and set theory merge — "a space is its category of sheaves."',
    realWorld: 'Topos theory is used in mathematical logic (forcing in set theory), theoretical computer science (denotational semantics), and has connections to quantum mechanics (topos approaches to quantum gravity).',
    hint: 'A topological space is determined by its sheaves — Grothendieck took the sheaves as the fundamental object.',
  },
  {
    id: 12305,
    topic: 'alexander-grothendieck',
    difficulty: 'sota',
    question: 'Grothendieck\'s "six operations" formalism for derived categories ($f^*, f_*, f^!, f_!, \\otimes, \\mathcal{Hom}$) achieves:',
    options: [
      'A unified framework for duality theorems (Poincaré, Serre, Verdier) across all cohomology theories via functorial operations',
      'A complete classification of all triangulated categories',
      'A constructive method for computing all cohomology groups',
      'A proof that all cohomology theories are equivalent',
    ],
    correctIndex: 0,
    explanation: 'The six operations provide a formal language in which Poincaré duality, Serre duality, and Verdier duality are all instances of adjunction between f_! and f^!. This framework unifies topology, algebraic geometry, and representation theory.',
    realWorld: 'The six operations formalism has been adopted in the geometric Langlands program, persistent homology (TDA), and D-module theory — providing a universal language for mathematical duality.',
    hint: 'Push forward, pull back, tensor, hom, and their "shriek" (!) variants — six functors that encode all of cohomological duality.',
  },
];
