import type { Question } from '../types';

export const markovQuestions: Question[] = [
  {
    id: 20410,
    topic: 'andrey-markov',
    difficulty: 'hard',
    question: 'The Markov property states that $P(X_{n+1} | X_n, X_{n-1}, \\ldots, X_0) = P(X_{n+1} | X_n)$. What is this property commonly called?',
    options: ['Memorylessness', 'Stationarity', 'Ergodicity', 'Recurrence'],
    correctIndex: 0,
    explanation: 'The Markov property means the future depends only on the present state, not the path taken to reach it — "memorylessness."',
    realWorld: 'Google\'s original PageRank modeled web browsing as a memoryless random walk across the internet graph.',
    hint: 'The chain forgets how it arrived at the current state.',
  },
  {
    id: 20411,
    topic: 'andrey-markov',
    difficulty: 'hard',
    question: 'For an irreducible, aperiodic Markov chain with finite state space, what does the Perron-Frobenius theorem guarantee about the transition matrix?',
    options: ['A unique stationary distribution exists', 'All eigenvalues are complex', 'The chain is transient', 'The mixing time is exponential'],
    correctIndex: 0,
    explanation: 'Perron-Frobenius guarantees a unique positive eigenvector (the stationary distribution) for primitive non-negative matrices.',
    realWorld: 'MCMC samplers in Bayesian statistics rely on convergence to a unique stationary distribution to generate valid posterior samples.',
    hint: 'An irreducible aperiodic chain on a finite space always converges to something unique.',
  },
  {
    id: 20412,
    topic: 'andrey-markov',
    difficulty: 'sota',
    question: 'The mixing time $t_{\\text{mix}}(\\varepsilon)$ of a Markov chain is bounded by the spectral gap $\\gamma$ of its transition matrix. What is the relationship?',
    options: ['$t_{\\text{mix}} = O(\\gamma^{-1} \\log(1/\\varepsilon))$', '$t_{\\text{mix}} = O(\\gamma^2)$', '$t_{\\text{mix}} = O(e^{\\gamma})$', '$t_{\\text{mix}} = O(1/\\varepsilon)$'],
    correctIndex: 0,
    explanation: 'The spectral gap controls how fast the chain converges: $t_{\\text{mix}} \\leq \\gamma^{-1} \\ln(1/(\\varepsilon \\pi_{\\min}))$.',
    realWorld: 'Understanding mixing times is critical for determining how long to run MCMC chains before trusting the samples in drug discovery simulations.',
    hint: 'A larger spectral gap means faster mixing — the bound is logarithmic in the accuracy parameter.',
  },
  {
    id: 20413,
    topic: 'andrey-markov',
    difficulty: 'sota',
    question: 'In Hidden Markov Models (HMMs), the Baum-Welch algorithm is an instance of which general optimization framework?',
    options: ['Expectation-Maximization (EM)', 'Gradient descent', 'Simulated annealing', 'Linear programming'],
    correctIndex: 0,
    explanation: 'Baum-Welch alternates between computing expected state occupancies (E-step) and re-estimating parameters (M-step), making it a special case of EM.',
    realWorld: 'HMMs trained via Baum-Welch powered speech recognition systems (like early Siri) before deep learning took over.',
    hint: 'It alternates between expectation and maximization steps.',
  },
  {
    id: 20414,
    topic: 'andrey-markov',
    difficulty: 'easy',
    question: 'What did Markov originally study to demonstrate his chain theory?',
    options: ['Vowel-consonant patterns in a Russian poem', 'Stock market prices', 'Weather patterns', 'Dice rolls'],
    correctIndex: 0,
    explanation: 'Markov analyzed the alternation of vowels and consonants in Pushkin\'s "Eugene Onegin" to demonstrate dependent sequences.',
    realWorld: 'This literary analysis pioneered computational linguistics — the ancestor of modern NLP and language models.',
    hint: 'He analyzed a famous work by Alexander Pushkin.',
  },
];
