import type { Question } from '../types';

export const andrewStromingerQuestions: Question[] = [
  {
    id: 313001, topic: 'andrew-strominger', difficulty: 'easy',
    question: 'Andrew Strominger\'s most celebrated result (with Cumrun Vafa, 1996) was:',
    options: [
      'The first microscopic derivation of Bekenstein-Hawking black hole entropy by counting D-brane microstates in string theory',
      'The discovery of cosmic microwave background anisotropies',
      'The proof that string theory requires exactly 10 dimensions',
      'The formulation of loop quantum gravity\'s spin foam models',
    ],
    correctIndex: 0,
    explanation: 'Strominger and Vafa showed that for an extremal 5D black hole built from $n_1$ D1-branes, $n_5$ D5-branes on $K3 \\times S^1$, and momentum $n_p$, the D-brane microstate count gives $S = 2\\pi\\sqrt{n_1 n_5 n_p}$, exactly matching $S_{BH} = A/(4G)$.',
    realWorld: 'This was the strongest evidence that string theory correctly describes quantum gravity — black holes have exactly the right number of microstates.',
    hint: 'Count brane excitations at weak coupling; the entropy matches the horizon area at strong coupling.',
    glossaryLinks: ['strominger-vafa', 'black-hole-entropy'],
  },
  {
    id: 313002, topic: 'andrew-strominger', difficulty: 'easy',
    question: 'Strominger\'s work on "soft theorems" and the "infrared triangle" connects three seemingly unrelated phenomena:',
    options: [
      'Soft graviton theorems (Weinberg), BMS supertranslation symmetries at null infinity, and the gravitational memory effect',
      'Hawking radiation, the Unruh effect, and the Casimir force',
      'Dark energy, dark matter, and cosmic inflation',
      'Quark confinement, asymptotic freedom, and chiral symmetry breaking',
    ],
    correctIndex: 0,
    explanation: 'Strominger showed that Weinberg\'s 1965 soft graviton theorem, the BMS (Bondi-van der Burg-Metzner-Sachs) supertranslation symmetries of asymptotically flat spacetimes, and the gravitational memory effect are three different manifestations of the same underlying infinite-dimensional symmetry.',
    realWorld: 'This "infrared triangle" suggests that every scattering event permanently imprints information on the asymptotic boundary of spacetime — potentially resolving the information paradox.',
    hint: 'Three vertices of the triangle: soft theorems, asymptotic symmetries, and memory effects.',
  },
  {
    id: 313003, topic: 'andrew-strominger', difficulty: 'hard',
    question: 'In the Strominger-Vafa calculation, the D-brane system\'s effective description at weak coupling is:',
    options: [
      'A 2D conformal field theory with central charge $c = 6n_1 n_5$ on the $S^1$, whose state count via the Cardy formula gives $S = 2\\pi\\sqrt{n_1 n_5 n_p}$',
      'A 4D $\\mathcal{N}=4$ super Yang-Mills theory on the brane worldvolume',
      'A 10D type IIA string theory with no compactification',
      'A topological quantum field theory on the $K3$ surface',
    ],
    correctIndex: 0,
    explanation: 'At weak string coupling ($g_s \\ll 1$), the D1-D5 system wrapping $K3 \\times S^1$ is described by open strings living on the branes, forming a 1+1D CFT along $S^1$ with central charge $c = 6n_1 n_5$. The Cardy formula $S = 2\\pi\\sqrt{cn_p/6}$ yields the entropy.',
    realWorld: 'The key bridge is supersymmetry (BPS protection): the microstate count at weak coupling is exact at strong coupling where the black hole exists.',
    hint: 'The effective theory lives in 1+1 dimensions along the compact circle.',
    glossaryLinks: ['strominger-vafa'],
  },
  {
    id: 313004, topic: 'andrew-strominger', difficulty: 'hard',
    question: 'Strominger\'s 1995 "massless black holes" paper showed that at conifold singularities in Calabi-Yau moduli space:',
    options: [
      'Black holes wrapped on vanishing 3-cycles become massless, smoothly connecting different Calabi-Yau topologies via topology-changing transitions',
      'All black holes evaporate instantaneously due to enhanced Hawking radiation',
      'The cosmological constant vanishes exactly at the singularity',
      'Spacetime dimensions increase from 10 to 11 at the transition point',
    ],
    correctIndex: 0,
    explanation: 'Strominger showed that D3-branes wrapping 3-cycles that shrink to zero size at conifold points become massless black holes. This resolved a long-standing puzzle about singularities in string theory moduli space and demonstrated that topology change is smooth in string theory.',
    realWorld: 'This work, along with Greene-Morrison-Strominger, proved that string theory unifies different Calabi-Yau topologies into a single connected moduli space.',
    hint: 'The key insight: what looks singular in geometry is physically smooth because new light states appear.',
  },
  {
    id: 313005, topic: 'andrew-strominger', difficulty: 'sota',
    question: 'Strominger\'s "soft hair" proposal (with Hawking and Perry, 2016) addresses the information paradox by arguing that:',
    options: [
      'Black holes carry an infinite number of soft charges (BMS supertranslation and superrotation hair) on their event horizons, encoding information about infalling matter that was previously thought lost',
      'Black holes have literal physical hair made of quantum entangled particles',
      'The no-hair theorem is exactly correct and information is truly destroyed',
      'Black holes store information in their interiors accessible via wormholes',
    ],
    correctIndex: 0,
    explanation: 'Hawking, Perry, and Strominger proposed that the BMS symmetry group acts on the black hole horizon, implanting "soft hair" — zero-energy quantum excitations that record information about everything that fell in. Each infalling particle shifts the vacuum via a supertranslation, leaving an imprint on the horizon\'s quantum state.',
    realWorld: 'This was one of Hawking\'s final papers (he died in 2018). Whether soft hair carries sufficient information to fully resolve the paradox remains an active research question.',
    hint: 'The "hair" is zero-energy — soft gravitons and photons on the horizon.',
  },
  {
    id: 313006, topic: 'andrew-strominger', difficulty: 'sota',
    question: 'The Strominger-Yau-Zaslow (SYZ) conjecture proposes that mirror symmetry between Calabi-Yau manifolds arises from:',
    options: [
      'T-duality applied fiberwise to a special Lagrangian torus fibration — the mirror manifold is obtained by dualizing all $T^3$ fibers',
      'S-duality between strong and weak coupling in type IIB string theory',
      'Conformal field theory equivalences on the worldsheet',
      'Large-N duality between gauge theory and gravity',
    ],
    correctIndex: 0,
    explanation: 'SYZ (1996) conjectured that every Calabi-Yau $X$ with a mirror $\\check{X}$ admits a special Lagrangian $T^3$ fibration, and that $\\check{X}$ is obtained by T-dualizing each fiber. This gives a geometric and physical explanation for mirror symmetry as fiberwise T-duality.',
    realWorld: 'SYZ provides the most intuitive geometric picture of mirror symmetry and has driven major advances in both physics and algebraic geometry.',
    hint: 'Dualize every torus fiber in a special Lagrangian fibration to get the mirror.',
  },
];
