import type { Question } from '../types';

export const wilesQuestions: Question[] = [
  {
    id: 21010,
    topic: 'wiles',
    difficulty: 'sota',
    question: 'Wiles proved Fermat\'s Last Theorem by establishing which major conjecture about elliptic curves?',
    options: ['The Taniyama–Shimura–Weil conjecture (for semistable curves)', 'The Birch and Swinnerton-Dyer conjecture', 'The Langlands correspondence for GL(2)', 'The Sato–Tate conjecture'],
    correctIndex: 0,
    explanation: 'Wiles proved that every semistable elliptic curve over $\\mathbb{Q}$ is modular, which by Ribet\'s theorem implies Fermat\'s Last Theorem.',
    realWorld: 'Modularity results underpin modern elliptic-curve cryptography and digital signature schemes.',
    hint: 'The key bridge connects elliptic curves to modular forms.',
  },
  {
    id: 21011,
    topic: 'wiles',
    difficulty: 'sota',
    question: 'Fermat\'s Last Theorem states that $a^n + b^n = c^n$ has no positive integer solutions for $n$ greater than which value?',
    options: ['2', '1', '3', '4'],
    correctIndex: 0,
    explanation: 'For $n = 2$ there are infinitely many Pythagorean triples, but Fermat claimed (and Wiles proved 358 years later) that no solutions exist for any integer $n > 2$.',
    realWorld: 'The theorem is a cornerstone of algebraic number theory and inspired centuries of mathematical development.',
    hint: 'Pythagoras handled the case where this threshold is an equality.',
  },
  {
    id: 21012,
    topic: 'wiles',
    difficulty: 'sota',
    question: 'Which mathematician proved the crucial link between Fermat\'s Last Theorem and the modularity conjecture?',
    options: ['Kenneth Ribet', 'Jean-Pierre Serre', 'Gerhard Frey', 'Richard Taylor'],
    correctIndex: 0,
    explanation: 'Ribet proved Serre\'s epsilon conjecture in 1986, showing that if the Taniyama–Shimura conjecture is true, then Fermat\'s Last Theorem follows. This gave Wiles a concrete target.',
    realWorld: 'Ribet\'s theorem exemplifies how seemingly unrelated conjectures can be chained to solve ancient problems.',
    hint: 'He proved the "epsilon conjecture" that formalized Frey\'s intuition.',
  },
  {
    id: 21013,
    topic: 'wiles',
    difficulty: 'sota',
    question: 'When a gap was found in Wiles\'s 1993 proof, who helped him repair it?',
    options: ['Richard Taylor', 'Kenneth Ribet', 'Barry Mazur', 'Peter Sarnak'],
    correctIndex: 0,
    explanation: 'Wiles and his former student Richard Taylor worked together for nearly a year to fix the flaw using an Iwasawa theory approach, completing the proof in 1994.',
    realWorld: 'The repair process highlights how collaborative peer review strengthens mathematical rigor.',
    hint: 'This collaborator was a former doctoral student of Wiles at Cambridge.',
  },
  {
    id: 21014,
    topic: 'wiles',
    difficulty: 'sota',
    question: 'Wiles\'s proof primarily uses deformation theory applied to which type of mathematical representation?',
    options: ['Galois representations', 'Linear representations of finite groups', 'Unitary representations of Lie groups', 'Permutation representations'],
    correctIndex: 0,
    explanation: 'The core of Wiles\'s argument involves showing that certain 2-dimensional Galois representations attached to elliptic curves are modular, using an intricate "R = T" theorem comparing deformation rings to Hecke algebras.',
    realWorld: 'Galois representations are central to the Langlands program, one of the deepest unifying visions in modern mathematics.',
    hint: 'These representations encode arithmetic information about number fields.',
  },
];
