import type { Question } from '../types';

export const benjaminBannekerQuestions: Question[] = [
  {
    id: 21700,
    topic: 'benjamin-banneker',
    difficulty: 'easy',
    question: 'What was Benjamin Banneker best known for publishing?',
    options: [
      'An almanac containing astronomical calculations, tide tables, and eclipse predictions',
      'A treatise on number theory and prime numbers',
      'A textbook on Euclidean geometry',
      'A catalog of star positions for navigation',
    ],
    correctIndex: 0,
    explanation: 'Banneker published his almanac annually from 1792 to 1797, containing ephemerides, eclipse predictions, and practical tables. It was widely circulated and cited as evidence of African-American intellectual achievement.',
    realWorld: 'His almanacs were used by farmers for planting schedules and by sailors for tide predictions.',
    hint: 'Think practical annual publication with astronomical data.',
  },
  {
    id: 21701,
    topic: 'benjamin-banneker',
    difficulty: 'easy',
    question: 'What mathematical technique did Banneker use to predict solar eclipses?',
    options: [
      'Calculating the intersection of the Moon\'s shadow cone with Earth\'s surface using Saros cycle arithmetic and spherical geometry',
      'Using Newton\'s method to solve polynomial equations',
      'Applying Fourier analysis to periodic light curves',
      'Using matrix algebra to track orbital perturbations',
    ],
    correctIndex: 0,
    explanation: 'Banneker mastered the Saros cycle (approximately 18 years, 11 days) and combined it with detailed ephemeris calculations to predict when and where solar eclipses would be visible — a feat requiring both astronomical knowledge and computational skill.',
    realWorld: 'Eclipse prediction remains critical for planning scientific observations and safety warnings.',
    hint: 'An ancient cycle of roughly 18 years governs eclipse recurrence.',
  },
  {
    id: 21702,
    topic: 'benjamin-banneker',
    difficulty: 'easy',
    question: 'What role did Banneker play in the survey of the new U.S. capital?',
    options: [
      'He assisted Andrew Ellicott in surveying the boundaries of the District of Columbia',
      'He designed the Capitol building',
      'He served as the first mayor of Washington, D.C.',
      'He calculated the national debt for the Treasury',
    ],
    correctIndex: 0,
    explanation: 'In 1791, Banneker was appointed to the survey team that laid out the boundaries of the District of Columbia, using astronomical observations to establish precise reference points.',
    realWorld: 'Surveying required precise astronomical measurements — Banneker\'s expertise was essential for accurate boundary determination.',
    hint: 'The federal capital needed its boundaries marked precisely.',
  },
  {
    id: 21703,
    topic: 'benjamin-banneker',
    difficulty: 'hard',
    question: 'How did Banneker compute ephemerides (tables of celestial positions) for his almanac without a formal education in mathematics?',
    options: [
      'He taught himself from borrowed astronomy texts and used iterative numerical methods to compute planetary positions from Keplerian orbital elements',
      'He copied tables directly from European almanacs',
      'He used a mechanical computing device built by a clockmaker',
      'He relied entirely on naked-eye observations without calculation',
    ],
    correctIndex: 0,
    explanation: 'Banneker borrowed texts including Ferguson\'s "Astronomy Explained" and taught himself the mathematical methods for computing planetary longitudes, lunar phases, and eclipse timings through laborious hand calculation.',
    realWorld: 'Self-taught mathematical computation was extraordinary in 18th-century America, especially for a free Black man with limited access to education.',
    hint: 'He learned from books and computed everything by hand.',
  },
  {
    id: 21704,
    topic: 'benjamin-banneker',
    difficulty: 'hard',
    question: 'What is the Saros cycle that Banneker used for eclipse prediction?',
    options: [
      'A period of approximately 6,585.3 days (18 years, 11 days, 8 hours) after which the Sun, Moon, and Earth return to nearly the same relative geometry',
      'A 12-month lunar calendar cycle',
      'A 76-year cycle relating the Julian and Gregorian calendars',
      'A 26,000-year axial precession cycle',
    ],
    correctIndex: 0,
    explanation: 'The Saros cycle arises because 223 synodic months ≈ 242 draconic months ≈ 239 anomalistic months. After one Saros, eclipses repeat with similar geometry but shifted ~120° in longitude.',
    realWorld: 'NASA still uses Saros numbering to catalogue and predict eclipse series.',
    hint: 'Three different lunar periods align after roughly 18 years.',
  },
  {
    id: 21705,
    topic: 'benjamin-banneker',
    difficulty: 'hard',
    question: 'As a young man, Banneker built a striking clock entirely from wood. What mathematical principle did this demonstrate?',
    options: [
      'Gear ratio calculation: he scaled a pocket watch mechanism to clock size by computing the correct tooth ratios for each gear',
      'He applied group theory to analyse rotational symmetries',
      'He used differential equations to model pendulum motion',
      'He calculated the escapement using Fourier harmonics',
    ],
    correctIndex: 0,
    explanation: 'Banneker carved each gear from wood, calculating the gear ratios needed to convert the oscillation of a balance mechanism into accurate timekeeping — a remarkable feat of applied mathematics and engineering.',
    realWorld: 'Gear ratio mathematics remains fundamental in mechanical engineering, robotics, and horology.',
    hint: 'Scaling a mechanism requires getting the ratios between gears exactly right.',
  },
  {
    id: 21706,
    topic: 'benjamin-banneker',
    difficulty: 'sota',
    question: 'What historiographical challenge surrounds Banneker\'s mathematical legacy?',
    options: [
      'Most of his original manuscripts were destroyed in a fire on the day of his funeral, making it difficult to fully assess his computational methods and potential original contributions',
      'His work was published under pseudonyms and cannot be attributed',
      'Contemporary mathematicians proved his calculations were incorrect',
      'His almanac was ghostwritten by Andrew Ellicott',
    ],
    correctIndex: 0,
    explanation: 'A fire destroyed Banneker\'s home and most of his papers on the day of his funeral in 1806. Only his commonplace book and a few manuscript pages survive, along with the published almanacs, making full assessment of his mathematical originality an ongoing scholarly challenge.',
    realWorld: 'The loss highlights the fragility of historical records and the importance of preserving scientific manuscripts.',
    hint: 'A devastating event on his funeral day destroyed most evidence.',
  },
  {
    id: 21707,
    topic: 'benjamin-banneker',
    difficulty: 'sota',
    question: 'How did Banneker\'s almanac serve as a political argument in the early American republic?',
    options: [
      'He sent a copy to Thomas Jefferson with a letter challenging Jefferson\'s views on Black intellectual inferiority, making the almanac itself proof of equal capacity',
      'He used encoded messages to support the abolitionist movement',
      'He published voting instructions for free Black citizens',
      'He included political cartoons criticising slavery',
    ],
    correctIndex: 0,
    explanation: 'In 1791, Banneker sent his first almanac to Secretary of State Jefferson, arguing that the mathematical sophistication of the work refuted claims of racial intellectual hierarchy. Jefferson forwarded the almanac to the French Academy of Sciences.',
    realWorld: 'Banneker\'s letter and almanac became iconic documents in the history of civil rights and the fight against scientific racism.',
    hint: 'He directly challenged a Founding Father with his own mathematical work as evidence.',
  },
];
