import type { Question } from '../types';

export const mandelbrotQuestions: Question[] = [
  {
    id: 20430,
    topic: 'benoit-mandelbrot',
    difficulty: 'hard',
    question: 'The Mandelbrot set is defined as the set of complex numbers $c$ for which the iteration $z_{n+1} = z_n^2 + c$ (starting from $z_0=0$) satisfies:',
    options: ['$|z_n|$ remains bounded as $n \\to \\infty$', '$|z_n| \\to \\infty$', '$z_n$ converges to a fixed point', '$z_n$ is periodic with period 2'],
    correctIndex: 0,
    explanation: 'The Mandelbrot set consists of all $c$ for which the orbit of 0 under $z \\mapsto z^2+c$ does not escape to infinity.',
    realWorld: 'Fractal geometry is used in antenna design — fractal antennas can receive multiple frequency bands in a compact form factor.',
    hint: 'Membership means the sequence stays bounded, not that it converges.',
  },
  {
    id: 20431,
    topic: 'benoit-mandelbrot',
    difficulty: 'hard',
    question: 'Mandelbrot argued that financial returns follow which type of distribution rather than Gaussian?',
    options: ['Lévy-stable (fat-tailed) distributions', 'Uniform distributions', 'Poisson distributions', 'Exponential distributions'],
    correctIndex: 0,
    explanation: 'Lévy-stable distributions have infinite variance and "fat tails," capturing the extreme events (crashes, spikes) that Gaussian models drastically underestimate.',
    realWorld: 'The 2008 financial crisis was a "25-sigma event" under Gaussian assumptions — essentially impossible — but expected under fat-tailed models.',
    hint: 'These distributions have heavier tails than the bell curve and can have infinite variance.',
  },
  {
    id: 20432,
    topic: 'benoit-mandelbrot',
    difficulty: 'sota',
    question: 'The Hausdorff dimension of the boundary of the Mandelbrot set has been proven to be:',
    options: ['Exactly 2', 'Approximately 1.5', 'Exactly 1', 'Unknown / unproven'],
    correctIndex: 0,
    explanation: 'Shishikura (1998) proved the boundary of the Mandelbrot set has Hausdorff dimension exactly 2 — it is so infinitely complex it is "area-filling."',
    realWorld: 'Fractal dimension analysis is used in medical imaging to quantify tumor boundary roughness as a diagnostic biomarker.',
    hint: 'The boundary is so complex it essentially fills a 2D region, despite being a curve.',
  },
  {
    id: 20433,
    topic: 'benoit-mandelbrot',
    difficulty: 'sota',
    question: 'Mandelbrot\'s concept of "multifractal" measures generalizes fractal dimension using the Rényi spectrum $D_q$. For a monofractal, what is true about $D_q$?',
    options: ['$D_q$ is constant for all $q$', '$D_q$ increases with $q$', '$D_q$ oscillates', '$D_q$ is undefined for $q < 0$'],
    correctIndex: 0,
    explanation: 'A monofractal has uniform scaling, so all generalized dimensions $D_q$ are equal. Multifractals have a non-trivial $D_q$ spectrum reflecting heterogeneous scaling.',
    realWorld: 'Multifractal analysis of financial time series reveals regime-dependent volatility clustering used in advanced risk models.',
    hint: 'If the fractal is perfectly self-similar at all scales, there\'s only one scaling exponent.',
  },
  {
    id: 20434,
    topic: 'benoit-mandelbrot',
    difficulty: 'easy',
    question: 'What geometric property defines a fractal?',
    options: ['Self-similarity at different scales', 'Perfect symmetry', 'Integer dimension', 'Smooth curves everywhere'],
    correctIndex: 0,
    explanation: 'Fractals exhibit self-similarity: zooming in reveals structure resembling the whole, often with non-integer (fractal) dimension.',
    realWorld: 'Coastlines, tree branches, blood vessels, and stock charts all exhibit fractal self-similarity.',
    hint: 'Zoom in and you see a smaller copy of the whole.',
  },
];
