import type { Question } from '../types';

export const bertrandRussellQuestions: Question[] = [
  {
    id: 20630,
    topic: 'bertrand-russell',
    difficulty: 'hard',
    question: 'Russell\'s Paradox considers the set $R = \\{x : x \\notin x\\}$. What is the paradox?',
    options: ['$R \\in R \\iff R \\notin R$ — a contradiction', '$R$ is empty', '$R$ contains all sets', '$R$ is identical to the universal set'],
    correctIndex: 0,
    explanation: 'If $R \\in R$, then by definition $R \\notin R$. If $R \\notin R$, then $R \\in R$. Either way, contradiction — destroying naïve set theory.',
    realWorld: 'This paradox forced the creation of axiomatic set theory (ZFC), which is the foundation of virtually all modern mathematics.',
    hint: 'Ask: does the set of all sets that don\'t contain themselves contain itself?',
  },
  {
    id: 20631,
    topic: 'bertrand-russell',
    difficulty: 'hard',
    question: 'Russell and Whitehead\'s "Principia Mathematica" attempted to derive all mathematics from logic. This program is called:',
    options: ['Logicism', 'Formalism', 'Intuitionism', 'Constructivism'],
    correctIndex: 0,
    explanation: 'Logicism holds that mathematics is reducible to logic. Principia Mathematica famously took 362 pages to prove that 1+1=2.',
    realWorld: 'Though Gödel showed logicism cannot be complete, the rigorous logical foundations it established underpin all formal verification in software.',
    hint: 'The philosophy that math is just logic in disguise.',
  },
  {
    id: 20632,
    topic: 'bertrand-russell',
    difficulty: 'sota',
    question: 'Russell\'s theory of types was designed to avoid his paradox. In modern type theory, what role do "universes" (à la Martin-Löf) play?',
    options: ['They create a hierarchy of types to prevent self-referential paradoxes', 'They model parallel universes', 'They define physical constants', 'They replace set theory entirely'],
    correctIndex: 0,
    explanation: 'Universe hierarchies ($\\mathcal{U}_0 : \\mathcal{U}_1 : \\mathcal{U}_2 : \\cdots$) prevent a type from containing itself, avoiding Russell-style paradoxes in dependent type theory.',
    realWorld: 'Proof assistants like Lean, Coq, and Agda use universe hierarchies to verify mathematical proofs and safety-critical software.',
    hint: 'Types are stratified into levels so no type can reference itself at the same level.',
  },
  {
    id: 20633,
    topic: 'bertrand-russell',
    difficulty: 'sota',
    question: 'Zermelo-Fraenkel set theory avoids Russell\'s Paradox primarily through which axiom?',
    options: ['The Axiom Schema of Separation (subsets only, not arbitrary set formation)', 'The Axiom of Choice', 'The Axiom of Infinity', 'The Axiom of Extensionality'],
    correctIndex: 0,
    explanation: 'Separation allows forming subsets of existing sets only — you cannot form "the set of all sets" because there is no universal set to take subsets of.',
    realWorld: 'ZFC is the standard foundation for virtually all published mathematics, from number theory to topology.',
    hint: 'Naïve set theory allows any predicate to define a set; ZFC restricts this to subsets of existing sets.',
  },
  {
    id: 20634,
    topic: 'bertrand-russell',
    difficulty: 'easy',
    question: 'Russell\'s Paradox devastated whose life\'s work on set theory, forcing a last-minute appendix admitting the foundation was broken?',
    options: ['Gottlob Frege', 'Georg Cantor', 'David Hilbert', 'Ernst Zermelo'],
    correctIndex: 0,
    explanation: 'Frege received Russell\'s letter just as his magnum opus "Grundgesetze der Arithmetik" was going to press, forcing a tragic appendix.',
    realWorld: 'Frege wrote: "A scientist can hardly encounter anything more undesirable than to have the foundation collapse just as the work is finished."',
    hint: 'This German logician was building the logical foundations of arithmetic when Russell wrote him a letter.',
  },
];
