import type { Question } from '../types';

export const bradleyEfronQuestions: Question[] = [
  {
    id: 21500,
    topic: 'bradley-efron',
    difficulty: 'easy',
    question: 'What is the bootstrap method invented by Bradley Efron?',
    options: [
      'A resampling technique that draws samples with replacement from observed data to estimate sampling distributions',
      'A gradient-based optimisation algorithm for neural networks',
      'A regularisation technique that shrinks coefficients toward zero',
      'A Bayesian prior selection method based on conjugate families',
    ],
    correctIndex: 0,
    explanation: 'The bootstrap resamples the observed data with replacement to approximate the sampling distribution of a statistic, enabling confidence intervals and hypothesis tests without parametric assumptions.',
    realWorld: 'Used in virtually every field of science to quantify uncertainty when theoretical formulas are unavailable.',
    hint: 'Think about pulling data points out of a hat — with replacement.',
    glossaryLinks: ['bootstrap'],
    formulaLinks: ['bootstrap-variance-estimator'],
  },
  {
    id: 21501,
    topic: 'bradley-efron',
    difficulty: 'easy',
    question: 'What does "empirical Bayes" refer to in Efron\'s framework?',
    options: [
      'Estimating the prior distribution from the data itself rather than specifying it subjectively',
      'Using maximum likelihood instead of Bayesian methods',
      'A frequentist rejection of all Bayesian reasoning',
      'Applying Bayes\' theorem only to coin-flip problems',
    ],
    correctIndex: 0,
    explanation: 'Empirical Bayes estimates the prior $f(\\theta)$ from the marginal distribution of the data, blending frequentist and Bayesian ideas. Efron showed this is both principled and powerful for large-scale inference.',
    realWorld: 'James-Stein estimation, false discovery rate control in genomics, and insurance pricing all use empirical Bayes.',
    hint: 'The prior comes from data, not from belief.',
    symbolLinks: { 'θ': 'theta' },
    glossaryLinks: ['empirical-bayes'],
  },
  {
    id: 21502,
    topic: 'bradley-efron',
    difficulty: 'easy',
    question: 'In bootstrap resampling, how is each bootstrap sample constructed?',
    options: [
      'By drawing $n$ observations with replacement from the original $n$ data points',
      'By splitting the data into two halves',
      'By adding Gaussian noise to each observation',
      'By removing one observation at a time (leave-one-out)',
    ],
    correctIndex: 0,
    explanation: 'Each bootstrap sample has the same size $n$ as the original data but is drawn with replacement, so some points appear multiple times while others are omitted.',
    realWorld: 'Random forests use bootstrap samples (bagging) to reduce variance of decision trees.',
    hint: 'Replacement is the key word.',
    symbolLinks: { 'n': 'nu' },
    glossaryLinks: ['bootstrap'],
  },
  {
    id: 21503,
    topic: 'bradley-efron',
    difficulty: 'hard',
    question: 'What is the BCa (bias-corrected and accelerated) bootstrap?',
    options: [
      'A refinement of the percentile bootstrap that corrects for bias and skewness in the bootstrap distribution',
      'A bootstrap that uses weighted sampling to reduce variance',
      'A parametric bootstrap assuming normality',
      'A method that replaces resampling with analytical formulas',
    ],
    correctIndex: 0,
    explanation: 'BCa adjusts the percentile method using a bias-correction factor $z_0$ and an acceleration constant $a$ to produce more accurate confidence intervals, especially for skewed statistics.',
    realWorld: 'Standard in modern statistical software (R\'s boot package) for reliable confidence intervals.',
    hint: 'It fixes two problems: bias and non-constant variance.',
    glossaryLinks: ['bootstrap'],
    formulaLinks: ['bootstrap-variance-estimator'],
  },
  {
    id: 21504,
    topic: 'bradley-efron',
    difficulty: 'hard',
    question: 'How does Efron\'s empirical Bayes approach handle the "large-scale simultaneous inference" problem?',
    options: [
      'By estimating the mixture density $f(z) = \\pi_0 f_0(z) + (1-\\pi_0) f_1(z)$ from thousands of parallel test statistics',
      'By applying Bonferroni correction to each test individually',
      'By reducing the problem to a single hypothesis test',
      'By using a flat prior for all parameters',
    ],
    correctIndex: 0,
    explanation: 'Efron models the observed $z$-scores as a mixture of null and non-null distributions, estimating $\\pi_0$ and $f_1$ from the data. This yields local false discovery rates for each test.',
    realWorld: 'Gene expression studies testing 20,000+ genes simultaneously use this framework to identify differentially expressed genes.',
    hint: 'Think mixture model: some tests are null, some are real.',
    symbolLinks: { 'π': 'pi' },
    glossaryLinks: ['false-discovery-rate', 'empirical-bayes'],
  },
  {
    id: 21505,
    topic: 'bradley-efron',
    difficulty: 'hard',
    question: 'What is the ".632 bootstrap" estimator introduced by Efron?',
    options: [
      'A prediction error estimator that blends apparent error and leave-one-out bootstrap error, using the fact that each bootstrap sample contains ~63.2% of unique observations',
      'A bootstrap that uses exactly 632 resamples',
      'A method that discards 36.8% of the data before resampling',
      'A cross-validation scheme with 632 folds',
    ],
    correctIndex: 0,
    explanation: 'Since $P(\\text{not selected}) = (1-1/n)^n \\approx e^{-1} \\approx 0.368$, each bootstrap sample contains about 63.2% unique points. The .632 estimator weights this to reduce optimistic bias.',
    realWorld: 'Used when sample sizes are too small for reliable $k$-fold cross-validation.',
    hint: 'The probability of being left out of a bootstrap sample converges to $1/e$.',
    symbolLinks: { 'n': 'nu' },
    glossaryLinks: ['bootstrap', 'cross-validation'],
  },
  {
    id: 21506,
    topic: 'bradley-efron',
    difficulty: 'sota',
    question: 'In Efron\'s 2010 monograph "Large-Scale Inference," what role does the local false discovery rate (lfdr) play?',
    options: [
      'It estimates the posterior probability that a specific case is null: $\\text{lfdr}(z) = \\pi_0 f_0(z) / f(z)$, enabling case-by-case inference',
      'It replaces all p-values with Bayesian posteriors',
      'It is a global measure identical to the Benjamini-Hochberg FDR',
      'It eliminates the need for any null hypothesis specification',
    ],
    correctIndex: 0,
    explanation: 'The local fdr gives a per-case probability of being null, computed as the ratio of the null density to the mixture density at the observed test statistic. This is more informative than a global FDR threshold.',
    realWorld: 'Precision medicine uses lfdr to rank individual patients by likelihood of treatment response.',
    hint: 'It\'s "local" because it assigns a probability to each individual case.',
    symbolLinks: { 'π': 'pi' },
    glossaryLinks: ['false-discovery-rate', 'empirical-bayes'],
    paper: {
      title: 'Large-Scale Inference: Empirical Bayes Methods for Estimation, Testing, and Prediction',
      url: 'https://statweb.stanford.edu/~ckirby/brad/LSI/monograph_CUP.pdf',
      venue: 'Cambridge University Press',
      year: 2010,
    },
  },
  {
    id: 21507,
    topic: 'bradley-efron',
    difficulty: 'sota',
    question: 'How does Efron\'s "exponential tilting" relate bootstrap confidence intervals to classical likelihood theory?',
    options: [
      'It reweights bootstrap samples using exponential family tilts to produce saddlepoint-accurate intervals that match likelihood ratio tests',
      'It replaces the bootstrap with pure maximum likelihood estimation',
      'It uses exponential smoothing to remove outliers from bootstrap samples',
      'It converts bootstrap distributions to exponential distributions',
    ],
    correctIndex: 0,
    explanation: 'Exponential tilting assigns weights $w_i \\propto e^{\\lambda x_i}$ to resampled points, connecting the nonparametric bootstrap to parametric likelihood theory and achieving higher-order accuracy.',
    realWorld: 'Used in importance sampling and rare-event simulation in computational statistics.',
    hint: 'Think saddlepoint approximation meets resampling.',
    symbolLinks: { 'λ': 'lambda' },
    glossaryLinks: ['bootstrap'],
  },
];
