import type { Question } from '../types';

export const brahmaguptaQuestions: Question[] = [
  {
    id: 20521,
    topic: 'brahmagupta',
    difficulty: 'hard',
    question: 'Brahmagupta established rules for arithmetic with zero. What did he define as the result of $0 \\div 0$?',
    options: ['Zero (though modern math leaves it undefined)', 'One', 'Infinity', 'He left it undefined'],
    correctIndex: 0,
    explanation: 'Brahmagupta stated $0/0 = 0$ in his Brahmasphutasiddhanta (628 CE). Modern mathematics considers this indeterminate, but his attempt was revolutionary.',
    realWorld: 'The formalization of zero as a number (not just a placeholder) enabled positional number systems and all of modern computation.',
    hint: 'He attempted a definition that modern mathematicians would disagree with.',
  },
  {
    id: 20522,
    topic: 'brahmagupta',
    difficulty: 'hard',
    question: 'Brahmagupta\'s formula gives the area of a cyclic quadrilateral with sides $a,b,c,d$ and semiperimeter $s$. What is it?',
    options: ['$\\sqrt{(s-a)(s-b)(s-c)(s-d)}$', '$\\frac{1}{2}|ac + bd|$', '$abcd / 4R$', '$s^2 - (a^2+b^2+c^2+d^2)/2$'],
    correctIndex: 0,
    explanation: 'This elegant formula generalizes Heron\'s formula for triangles (set $d=0$). It applies only to quadrilaterals inscribed in a circle.',
    realWorld: 'Computational geometry algorithms for surveying and GIS systems use Brahmagupta\'s formula for area calculations.',
    hint: 'It looks like Heron\'s formula but with four terms instead of three.',
  },
  {
    id: 20523,
    topic: 'brahmagupta',
    difficulty: 'sota',
    question: 'Brahmagupta solved the Pell equation $x^2 - Ny^2 = 1$ using his "samasa" (composition) method. This method is equivalent to which modern algebraic operation?',
    options: ['Multiplication in the ring $\\mathbb{Z}[\\sqrt{N}]$', 'Gaussian elimination', 'Euclidean algorithm', 'Fourier transform'],
    correctIndex: 0,
    explanation: 'His composition rule $(x_1^2-Ny_1^2)(x_2^2-Ny_2^2)=(x_1x_2+Ny_1y_2)^2-N(x_1y_2+x_2y_1)^2$ is the norm multiplication in $\\mathbb{Z}[\\sqrt{N}]$.',
    realWorld: 'The Pell equation appears in continued fraction theory and is fundamental to algebraic number theory and cryptographic protocols.',
    hint: 'He found that solutions can be "composed" to generate new solutions — an algebraic structure.',
  },
  {
    id: 20524,
    topic: 'brahmagupta',
    difficulty: 'hard',
    question: 'Brahmagupta referred to positive numbers as "fortunes" and negative numbers as "debts." What rule did he establish for multiplying two "debts"?',
    options: ['A debt times a debt is a fortune (negative × negative = positive)', 'A debt times a debt is a debt', 'The result is zero', 'The operation is undefined'],
    correctIndex: 0,
    explanation: 'He correctly established that the product of two negatives is positive — the first known statement of this fundamental arithmetic rule.',
    realWorld: 'This rule underpins all financial accounting, physics (direction × direction), and computer arithmetic.',
    hint: 'His terminology made the abstract concrete: what happens when you multiply two debts?',
  },
  {
    id: 20525,
    topic: 'brahmagupta',
    difficulty: 'easy',
    question: 'Brahmagupta is best known for being the first mathematician to formalize rules for computing with which number?',
    options: ['Zero', 'Pi', 'Infinity', 'Imaginary unit $i$'],
    correctIndex: 0,
    explanation: 'In his Brahmasphutasiddhanta (628 CE), he defined addition, subtraction, and multiplication rules involving zero for the first time.',
    realWorld: 'Without zero as a proper number, we would have no binary code, no computers, and no digital age.',
    hint: 'The "Lord of Zero" — his most famous contribution.',
  },
];
