import type { Question } from '../types';

export const brianArthurQuestions: Question[] = [
  {
    id: 21160,
    topic: 'brian-arthur',
    difficulty: 'sota',
    question: 'W. Brian Arthur\'s theory of "increasing returns" explains which phenomenon in technology markets?',
    options: ['Lock-in — an inferior product can dominate simply because it got adopted first', 'Markets always converge to the optimal product', 'Competition always drives prices to marginal cost', 'Technological progress follows a linear trajectory'],
    correctIndex: 0,
    explanation: 'Arthur showed that positive feedback loops (network effects, learning effects, switching costs) can lock markets into inferior technologies. The first mover advantage compounds, making the initial random advantage permanent.',
    realWorld: 'This explains why QWERTY keyboards, VHS over Betamax, and Windows over technically superior alternatives dominated their markets.',
    hint: 'The more people use something, the more valuable it becomes — regardless of quality.',
  },
  {
    id: 21161,
    topic: 'brian-arthur',
    difficulty: 'sota',
    question: 'Arthur\'s Pólya urn model demonstrates increasing returns using what simple setup?',
    options: ['An urn where drawing a colored ball causes more balls of that color to be added', 'A coin flip where the probability changes based on past results', 'A random walk with absorbing barriers', 'A branching process with random offspring distribution'],
    correctIndex: 0,
    explanation: 'Each time a ball of color A is drawn, more A balls are added, making A more likely to be drawn again. The urn eventually locks in to one color, but which one is fundamentally unpredictable — path-dependent.',
    realWorld: 'The urn model is a mathematical metaphor for how small random events in technology adoption can determine the long-run market winner.',
    hint: 'Success breeds success through a self-reinforcing feedback mechanism.',
  },
  {
    id: 21162,
    topic: 'brian-arthur',
    difficulty: 'sota',
    question: 'Arthur\'s "El Farol Bar Problem" is a canonical example of which concept in game theory?',
    options: ['Bounded rationality and inductive reasoning under uncertainty', 'Nash equilibrium with complete information', 'Dominant strategy equilibrium', 'Pareto optimal allocation'],
    correctIndex: 0,
    explanation: 'In the problem, agents independently decide whether to attend a bar that\'s only fun if not too crowded. No deductive solution exists, so agents use inductive heuristics — a model of bounded rationality.',
    realWorld: 'The El Farol problem models congestion, resource allocation, and minority games in finance.',
    hint: 'If everyone predicts the bar will be empty, they\'ll all go, making it crowded.',
  },
  {
    id: 21163,
    topic: 'brian-arthur',
    difficulty: 'sota',
    question: 'Arthur argues that the economy should be understood not as an equilibrium system but as what?',
    options: ['A complex adaptive system that is always evolving and never in equilibrium', 'A deterministic system governed by fixed laws', 'A random walk with no underlying structure', 'A system that always returns to a unique stable state'],
    correctIndex: 0,
    explanation: 'Arthur\'s "complexity economics" views the economy as an evolving ecology of strategies, technologies, and institutions that is perpetually in disequilibrium, creating novelty and innovation endogenously.',
    realWorld: 'This framework better explains innovation, disruption, and the formation of tech monopolies than classical equilibrium economics.',
    hint: 'The economy is more like a living ecosystem than a static machine.',
  },
  {
    id: 21164,
    topic: 'brian-arthur',
    difficulty: 'sota',
    question: 'Arthur\'s concept of "combinatorial evolution" in technology argues that new technologies are created how?',
    options: ['By combining existing technologies in novel ways', 'Through random invention disconnected from prior art', 'By top-down government planning', 'Through gradual linear improvement of single technologies'],
    correctIndex: 0,
    explanation: 'Arthur argues that technology evolves not through isolated invention but by recombining existing components — just as biological evolution combines existing genes. The steam engine combined cylinders, pistons, and valves that already existed.',
    realWorld: 'This explains why innovation clusters in time and space — regions with diverse technological "ingredients" produce more combinations.',
    hint: 'Innovation is recombination, not creation from nothing.',
  },
];
