import type { Question } from '../types';

export const birkarQuestions: Question[] = [
  {
    id: 12201,
    topic: 'caucher-birkar',
    difficulty: 'easy',
    question: 'Caucher Birkar, a Kurdish-British mathematician, won the 2018 Fields Medal for his work on:',
    options: [
      'The minimal model program (MMP) in birational geometry — classifying algebraic varieties',
      'Solving the Poincaré conjecture in dimension 7',
      'Proving the abc conjecture using inter-universal Teichmüller theory',
      'Developing new methods in analytic number theory',
    ],
    correctIndex: 0,
    explanation: 'Birkar proved the boundedness of Fano varieties (BAB conjecture) and made fundamental contributions to the minimal model program, which seeks to classify algebraic varieties by simplifying them to "minimal" or "Fano" models.',
    realWorld: 'Algebraic geometry underpins string theory (Calabi–Yau manifolds), cryptography (elliptic curves), and error-correcting codes (algebraic geometry codes).',
    hint: 'The minimal model program is like a "simplification algorithm" for geometric shapes defined by polynomial equations.',
  },
  {
    id: 12202,
    topic: 'caucher-birkar',
    difficulty: 'easy',
    question: 'Birkar\'s personal story is remarkable because:',
    options: [
      'He grew up in wartime Kurdistan, studied math from limited textbooks, and became a refugee before his Fields Medal',
      'He was a child prodigy who entered university at age 12',
      'He discovered his theorem using computer-assisted proof techniques',
      'He turned down multiple prizes before accepting the Fields Medal',
    ],
    correctIndex: 0,
    explanation: 'Born in Iran\'s Kurdistan province during the Iran–Iraq war, Birkar studied mathematics with scarce resources. He sought asylum in the UK as a refugee and eventually became a professor at Cambridge. His Fields Medal was famously stolen minutes after the ceremony.',
    realWorld: 'Birkar\'s story highlights how mathematical talent exists globally and how providing access to education for refugees and displaced people can lead to world-changing contributions.',
    hint: 'His journey from conflict zone to the highest honor in mathematics is one of the most inspiring in modern science.',
  },
  {
    id: 12203,
    topic: 'caucher-birkar',
    difficulty: 'hard',
    question: 'The BAB conjecture (Borisov–Alexeev–Borisov), proved by Birkar, states that:',
    options: [
      'Fano varieties of fixed dimension with mild singularities form a bounded family — there are only finitely many deformation types',
      'All Fano varieties are rational',
      'The Picard number of Fano varieties is bounded by the dimension',
      'Fano varieties in dimension ≥ 4 always have Kähler–Einstein metrics',
    ],
    correctIndex: 0,
    explanation: 'BAB says that ε-log terminal Fano varieties of dimension n form a bounded family. This means the "zoo" of Fano shapes is not infinite — they can be parameterized by finitely many families. This is a cornerstone of birational geometry.',
    realWorld: 'Classification of Fano varieties is relevant to string theory, where Calabi–Yau manifolds (related to Fano by anticanonical divisors) determine the geometry of extra dimensions.',
    hint: '"Bounded" means you can list all possible shapes up to continuous deformation — there\'s a finite catalog.',
  },
  {
    id: 12204,
    topic: 'caucher-birkar',
    difficulty: 'hard',
    question: 'In the minimal model program (MMP), the key operations that simplify varieties are:',
    options: [
      'Divisorial contractions and flips — surgery operations guided by the sign of the canonical class',
      'Blowing up singular points and resolving indeterminacies',
      'Taking hyperplane sections and projecting to lower dimensions',
      'Computing cohomology groups and Hodge numbers',
    ],
    correctIndex: 0,
    explanation: 'The MMP iteratively contracts curves with negative intersection with the canonical divisor (contractions), or performs flips when direct contraction fails. Birkar\'s work proved termination and existence of these operations in key cases.',
    realWorld: 'The MMP provides a computational framework for classifying shapes, analogous to how the classification of finite simple groups organizes algebra — a "periodic table" for geometry.',
    hint: 'Like simplifying a fraction: each step makes the variety "simpler" until you reach a minimal model or a Fano fibration.',
  },
  {
    id: 12205,
    topic: 'caucher-birkar',
    difficulty: 'sota',
    question: 'Birkar\'s proof of BAB uses the theory of complements and anti-canonical linear systems. The key technical innovation is:',
    options: [
      'Showing that n-complements (effective divisors bounding the anti-canonical class) exist with n bounded depending only on dimension',
      'Constructing Kähler–Einstein metrics on all Fano varieties using continuity method',
      'Reducing to characteristic p and using Frobenius splitting',
      'Applying derived categories and Bridgeland stability conditions',
    ],
    correctIndex: 0,
    explanation: 'Birkar showed that for ε-lc Fano varieties, there exists an n-complement with n ≤ N(n, ε). This uniform bound on complements implies boundedness of the family. The proof combines MMP techniques with ACC for log canonical thresholds.',
    realWorld: 'The theory of complements has become a standard tool in birational geometry and is being extended to positive characteristic, with implications for arithmetic geometry and number theory.',
    hint: 'An n-complement is like a "certificate" that the variety belongs to a bounded family — Birkar proved these certificates always exist.',
  },
];
