import type { Question } from '../types';

export const chandrasekharaVRamanQuestions: Question[] = [
  {
    id: 11601,
    topic: 'chandrasekhara-v-raman',
    difficulty: 'easy',
    question: 'C.V. Raman won the Nobel Prize in Physics (1930) for discovering the Raman effect. What is it?',
    options: [
      'Inelastic scattering of light where photons gain or lose energy from molecular vibrations',
      'The bending of light around massive objects due to gravity',
      'The splitting of spectral lines in a magnetic field',
      'The emission of electrons from a surface when hit by light',
    ],
    correctIndex: 0,
    explanation: 'When light scatters off molecules, most photons scatter elastically (Rayleigh). A small fraction exchange energy with molecular vibrations, shifting frequency — this is Raman scattering. It reveals molecular structure.',
    realWorld: 'Raman spectroscopy is used in pharmaceutical quality control, cancer detection, art authentication, and forensics — identifying molecular composition without destroying the sample.',
    hint: 'Most scattered light keeps its frequency. Raman found the rare photons that change frequency.',
  },
  {
    id: 11602,
    topic: 'chandrasekhara-v-raman',
    difficulty: 'easy',
    question: 'Raman famously explained the blue color of the sea. His explanation was based on:',
    options: [
      'Molecular scattering of light by water molecules, not reflection of the sky',
      'Reflection of the blue sky on the water surface',
      'Absorption of red light by dissolved minerals',
      'Refraction of sunlight through ocean waves',
    ],
    correctIndex: 0,
    explanation: 'Lord Rayleigh had attributed the sea\'s blue to sky reflection. Raman proved on a ship voyage (1921) that water molecules themselves scatter blue light — molecular scattering, not reflection.',
    realWorld: 'Understanding light scattering in water is fundamental to ocean optics, remote sensing of ocean color for climate science, and underwater communication systems.',
    hint: 'He questioned the prevailing theory while sailing to Europe and proved it wrong with simple experiments.',
  },
  {
    id: 11603,
    topic: 'chandrasekhara-v-raman',
    difficulty: 'hard',
    question: 'In Raman scattering, the frequency shifts (Stokes and anti-Stokes lines) directly correspond to:',
    options: [
      'Vibrational and rotational energy levels of the molecule — providing a molecular fingerprint',
      'Electronic transitions between atomic orbitals',
      'Nuclear spin states of the atoms',
      'The thermal energy distribution of the gas',
    ],
    correctIndex: 0,
    explanation: 'Stokes lines (photon loses energy) and anti-Stokes lines (photon gains energy from an excited molecule) map directly to molecular vibrational modes. The spectrum is a unique fingerprint of molecular structure.',
    realWorld: 'Surface-Enhanced Raman Spectroscopy (SERS) can detect single molecules, enabling early cancer detection, explosive detection at airports, and environmental pollutant monitoring.',
    hint: 'Stokes = photon gives energy to molecule (red shift); Anti-Stokes = photon takes energy (blue shift).',
  },
  {
    id: 11604,
    topic: 'chandrasekhara-v-raman',
    difficulty: 'hard',
    question: 'The intensity ratio of anti-Stokes to Stokes lines in Raman scattering depends on:',
    options: [
      'The Boltzmann distribution — fewer molecules in excited states means weaker anti-Stokes lines',
      'The polarization of the incident laser beam',
      'The wavelength of the excitation source only',
      'The refractive index of the medium',
    ],
    correctIndex: 0,
    explanation: 'Anti-Stokes requires molecules already in excited vibrational states. By Boltzmann: N_excited/N_ground = exp(-ΔE/kT). This ratio measures temperature — Raman thermometry.',
    realWorld: 'Raman thermometry measures temperature in hostile environments (jet engines, semiconductor fabrication) non-invasively by analyzing anti-Stokes/Stokes intensity ratios.',
    hint: 'At room temperature, most molecules are in the ground vibrational state — anti-Stokes is weak.',
  },
  {
    id: 11605,
    topic: 'chandrasekhara-v-raman',
    difficulty: 'sota',
    question: 'Modern coherent anti-Stokes Raman scattering (CARS) microscopy achieves:',
    options: [
      'Label-free chemical imaging of living cells with ~200nm resolution using nonlinear four-wave mixing',
      'Single-atom resolution using X-ray Raman scattering',
      'Quantum entanglement-enhanced sensitivity beyond the shot noise limit',
      'Direct measurement of molecular wave functions in real time',
    ],
    correctIndex: 0,
    explanation: 'CARS uses two synchronized laser pulses to coherently drive molecular vibrations, producing a signal orders of magnitude stronger than spontaneous Raman. It enables real-time, label-free imaging of lipids, proteins, and drugs in living tissue.',
    realWorld: 'CARS microscopy is used for intraoperative brain tumor detection, studying lipid metabolism in obesity research, and pharmaceutical tablet analysis — all without staining or fluorescent labels.',
    hint: 'Coherent = all molecules oscillate in phase → much stronger signal than spontaneous Raman.',
  },
];
