import type { Question } from '../types';

export const shannonQuestions: Question[] = [
  {
    id: 10021,
    topic: 'shannon',
    difficulty: 'easy',
    question: 'Shannon entropy $H(X)$ of a discrete random variable $X$ measures:',
    options: [
      'The average amount of information (uncertainty) in a random variable',
      'The maximum value a random variable can take',
      'The variance of a probability distribution',
      'The number of bits needed to represent the alphabet',
    ],
    correctIndex: 0,
    explanation: '$H(X) = -\\sum_x p(x) \\log_2 p(x)$ bits. A fair coin has entropy 1 bit — maximum uncertainty. A biased coin has less. A deterministic variable has entropy 0.',
    realWorld: 'Entropy quantifies how compressible data is. High-entropy data (random noise) cannot be compressed; low-entropy data (text, images) can.',
    hint: 'More surprise → more information. A predictable event gives you no new information.',
  },
  {
    id: 10022,
    topic: 'shannon',
    difficulty: 'easy',
    question: 'Shannon\'s Channel Capacity theorem (1948) states:',
    options: [
      'The maximum error-free data rate over a noisy channel is $C = B \\log_2(1 + S/N)$ bits/second',
      'Any channel with noise will corrupt at least half of transmitted bits',
      'The channel capacity equals the number of symbols in the alphabet',
      'Error-free transmission requires infinite redundancy',
    ],
    correctIndex: 0,
    explanation: 'The Shannon-Hartley theorem gives channel capacity $C$ in terms of bandwidth $B$ and signal-to-noise ratio $S/N$. Below $C$, reliable communication is theoretically possible; above $C$, it is not.',
    realWorld: 'Every WiFi standard (802.11ac, WiFi 6) and 5G specification uses this formula to determine maximum data throughput.',
    hint: 'More bandwidth + better signal-to-noise = higher capacity. Noise is the enemy.',
  },
  {
    id: 10023,
    topic: 'shannon',
    difficulty: 'easy',
    question: 'Huffman coding achieves compression by:',
    options: [
      'Assigning shorter binary codes to more frequent symbols',
      'Replacing repeated sequences with pointers to previous occurrences',
      'Transforming data using a discrete cosine transform',
      'Encrypting data with a shorter key representation',
    ],
    correctIndex: 0,
    explanation: 'Huffman coding builds a binary tree where frequent symbols get short codes and rare symbols get long ones. It is provably optimal for symbol-by-symbol encoding and approaches the entropy bound.',
    realWorld: 'JPEG, MP3, ZIP, and HTTP compression all use Huffman coding internally as part of their compression pipeline.',
    hint: 'Common letters like "e" and "t" should use fewer bits than rare letters like "z" and "q".',
  },
  {
    id: 10024,
    topic: 'shannon',
    difficulty: 'easy',
    question: 'Mutual information $I(X; Y)$ between two variables measures:',
    options: [
      'How much knowing $Y$ reduces uncertainty about $X$ (and vice versa)',
      'The correlation coefficient between $X$ and $Y$',
      'The joint entropy of the pair $(X, Y)$',
      'The probability that $X = Y$',
    ],
    correctIndex: 0,
    explanation: '$I(X;Y) = H(X) - H(X|Y)$ = the reduction in $X$\'s entropy when $Y$ is known. It is symmetric: $I(X;Y) = I(Y;X)$ and equals 0 iff $X$ and $Y$ are independent.',
    realWorld: 'Mutual information is used in feature selection (which input features carry most information about the output label?) and in training InfoGAN and MINE neural networks.',
    hint: 'If knowing Y tells you nothing new about X, mutual information is 0.',
  },
  {
    id: 10025,
    topic: 'shannon',
    difficulty: 'hard',
    question: 'The source coding theorem (Shannon\'s first theorem) states that the minimum average code length $L$ satisfies:',
    options: [
      '$H(X) \\leq L < H(X) + 1$ for uniquely decodable codes over binary alphabet',
      '$L = H(X)$ exactly for all optimal codes',
      '$L \\geq 2H(X)$ for any lossless code',
      '$L = \\lceil \\log_2 |\\mathcal{X}| \\rceil$ regardless of the distribution',
    ],
    correctIndex: 0,
    explanation: 'The entropy $H(X)$ is a lower bound on average code length. Huffman coding achieves $H(X) \\leq L < H(X) + 1$. The gap approaches zero when coding blocks of symbols (arithmetic coding achieves the entropy bound asymptotically).',
    realWorld: 'Arithmetic coding (used in HEVC video compression) approaches the entropy bound to within 0.001 bits/symbol.',
    hint: 'Entropy is the minimum — you cannot compress below it on average.',
  },
  {
    id: 10026,
    topic: 'shannon',
    difficulty: 'hard',
    question: 'KL divergence $D_{KL}(P \\| Q)$ is related to Shannon entropy by:',
    options: [
      '$D_{KL}(P \\| Q) = H(P, Q) - H(P)$, where $H(P,Q)$ is cross-entropy',
      '$D_{KL}(P \\| Q) = H(P) - H(Q)$',
      '$D_{KL}(P \\| Q) = H(P) \\cdot H(Q)$',
      '$D_{KL}(P \\| Q) = \\sqrt{H(P)^2 + H(Q)^2}$',
    ],
    correctIndex: 0,
    explanation: '$D_{KL}(P\\|Q) = \\sum_x p(x) \\log \\frac{p(x)}{q(x)} = H(P,Q) - H(P)$. It measures the extra bits needed to encode $P$ using code optimized for $Q$. It is non-negative and zero only when $P = Q$.',
    realWorld: 'KL divergence is the loss in variational autoencoders (VAEs), language model perplexity evaluation, and RL policy optimization.',
    hint: 'Cross-entropy minus self-entropy = extra cost of using the wrong distribution.',
  },
  {
    id: 10027,
    topic: 'shannon',
    difficulty: 'hard',
    question: 'Lempel-Ziv compression (LZ77/LZ78) achieves entropy-rate compression by:',
    options: [
      'Building a dynamic dictionary of previously seen patterns and replacing repetitions with (offset, length) references',
      'Applying a wavelet transform and discarding high-frequency coefficients',
      'Encoding individual symbols with Huffman codes derived from frequency tables',
      'Modeling the source as a hidden Markov model and using Viterbi decoding',
    ],
    correctIndex: 0,
    explanation: 'LZ algorithms exploit redundancy across the data stream, not just symbol frequencies. They adapt the dictionary online without needing prior knowledge of the source distribution, provably achieving the entropy rate of ergodic sources.',
    realWorld: 'gzip, PNG, and HTTP/2 header compression all use LZ77 variants. LZ compression underpins the internet.',
    hint: 'Instead of compressing symbols, compress repeated sequences using references to what came before.',
  },
  {
    id: 10028,
    topic: 'shannon',
    difficulty: 'sota',
    question: 'Shannon\'s noisy channel coding theorem guarantees reliable communication at rate $R < C$ by:',
    options: [
      'Proving existence of random codes with vanishing error probability, without constructing explicit codes',
      'Constructing Hamming codes that correct up to $\\lfloor (d-1)/2 \\rfloor$ errors',
      'Requiring infinite block length and Gaussian input distributions',
      'Showing that repetition codes achieve capacity in the limit',
    ],
    correctIndex: 0,
    explanation: 'Shannon\'s coding theorem is an existence proof using random codebooks — he showed that with high probability a random code achieves arbitrarily low error probability for $R < C$. Constructing explicit capacity-achieving codes took decades (turbo codes 1993, LDPC 1993, polar codes 2008).',
    realWorld: 'Modern 5G uses polar codes (Arıkan 2009) that provably achieve Shannon capacity — 70 years after Shannon\'s theorem.',
    hint: 'The proof picks codes randomly and shows most of them work — it doesn\'t tell you which one.',
  },
  {
    id: 10029,
    topic: 'shannon',
    difficulty: 'sota',
    question: 'The data processing inequality states: for a Markov chain $X \\to Y \\to Z$:',
    options: [
      '$I(X; Z) \\leq I(X; Y)$, processing data cannot increase mutual information',
      '$I(X; Z) = I(X; Y) \\cdot I(Y; Z)$ by the chain rule',
      '$H(Z) \\leq H(Y) \\leq H(X)$ since each processing step removes entropy',
      '$I(X; Z) \\geq I(X; Y)$ if the processing is invertible',
    ],
    correctIndex: 0,
    explanation: 'In a Markov chain $X \\to Y \\to Z$, $Z$ depends on $X$ only through $Y$. Therefore $I(X;Z) \\leq I(X;Y)$. Processing (transformations) cannot create information about $X$ that wasn\'t in $Y$.',
    realWorld: 'This proves that dimensionality reduction (PCA, autoencoders) cannot increase the information content — it can only preserve or lose it.',
    hint: 'A downstream observer has at most as much information as the intermediate variable.',
  },
  {
    id: 10030,
    topic: 'shannon',
    difficulty: 'sota',
    question: 'Rate-distortion theory addresses the tradeoff between:',
    options: [
      'Compression rate (bits per symbol) and reconstruction quality (expected distortion) for lossy compression',
      'Encoding speed and decoding speed in arithmetic coding',
      'Noise resilience and compression ratio in error-correcting codes',
      'Channel capacity and transmission delay in queuing networks',
    ],
    correctIndex: 0,
    explanation: 'Rate-distortion function $R(D)$ gives the minimum bits/symbol needed to reconstruct a source with expected distortion $\\leq D$. For a Gaussian source with MSE distortion: $R(D) = \\frac{1}{2}\\log_2(\\sigma^2/D)$.',
    realWorld: 'JPEG quality settings, audio codec bitrates, and video streaming quality tiers are all operating points on rate-distortion curves.',
    hint: 'You trade bits (rate) for quality (inverse distortion) — the fundamental tradeoff of lossy compression.',
  },
];
