import type { Question } from '../types';

export const cumrunVafaQuestions: Question[] = [
  {
    id: 314001, topic: 'cumrun-vafa', difficulty: 'easy',
    question: 'Cumrun Vafa\'s "Swampland" program (2005–present) distinguishes between:',
    options: [
      'Effective field theories that can be consistently completed into quantum gravity (the "landscape") and those that cannot (the "swampland")',
      'Mathematically consistent and inconsistent string vacua',
      'Stable and unstable de Sitter vacua in cosmology',
      'Perturbative and non-perturbative string theories',
    ],
    correctIndex: 0,
    explanation: 'Vafa proposed that most apparently consistent low-energy effective field theories are in the "swampland" — they look fine classically but cannot be UV-completed into a consistent theory of quantum gravity. The swampland conjectures (weak gravity, distance, de Sitter) constrain which low-energy theories are actually possible.',
    realWorld: 'The de Sitter swampland conjecture, if correct, would rule out a positive cosmological constant in string theory — with profound implications for dark energy and the fate of the universe.',
    hint: 'Not every low-energy theory has a UV completion — most are in the swamp.',
  },
  {
    id: 314002, topic: 'cumrun-vafa', difficulty: 'easy',
    question: 'Vafa\'s F-theory (1996) extends type IIB string theory by:',
    options: [
      'Geometrizing the varying axio-dilaton $\\tau = C_0 + ie^{-\\phi}$ as the complex structure modulus of an auxiliary elliptic fiber — encoding non-perturbative physics in geometry',
      'Adding a 12th spacetime dimension with Lorentzian signature',
      'Replacing strings with membranes as the fundamental objects',
      'Compactifying M-theory on a circle to recover 10D string theory',
    ],
    correctIndex: 0,
    explanation: 'F-theory encodes the spatially varying string coupling $g_s = e^\\phi$ and axion $C_0$ as the modular parameter $\\tau$ of an elliptic curve (torus) fibered over the compactification space. This allows non-perturbative effects (7-branes, strong coupling) to be described purely geometrically.',
    realWorld: 'F-theory compactifications on Calabi-Yau fourfolds produce the richest landscape of string vacua with realistic particle physics (GUT models, Yukawa couplings).',
    hint: 'The coupling constant becomes geometry — the shape of a torus fiber.',
  },
  {
    id: 314003, topic: 'cumrun-vafa', difficulty: 'hard',
    question: 'Vafa\'s topological string theory relates the topological A-model partition function to:',
    options: [
      'Gromov-Witten invariants (counting holomorphic curves) and, via large-N duality, Chern-Simons gauge theory on $S^3$',
      'The Donaldson invariants of 4-manifolds',
      'The Jones polynomial of knots in $S^3$',
      'The Witten-Reshetikhin-Turaev invariants of 3-manifolds',
    ],
    correctIndex: 0,
    explanation: 'The topological A-model on a Calabi-Yau $X$ computes Gromov-Witten invariants — counts of holomorphic curves with genus $g$ and degree $\\beta$. Gopakumar and Vafa showed this is dual to Chern-Simons theory on $S^3$ (large-N transition), connecting string theory, enumerative geometry, and 3-manifold invariants.',
    realWorld: 'The Gopakumar-Vafa invariants reformulate Gromov-Witten theory in terms of integer BPS state counts, resolving integrality puzzles.',
    hint: 'Holomorphic curves in the A-model become Wilson loops in Chern-Simons theory.',
  },
  {
    id: 314004, topic: 'cumrun-vafa', difficulty: 'hard',
    question: 'The "Weak Gravity Conjecture" (Arkani-Hamed, Motl, Nicolis, Vafa, 2006) states that in any consistent quantum gravity theory:',
    options: [
      'There must exist a particle whose charge-to-mass ratio exceeds that of an extremal black hole: $q/m \\geq q_{\\text{ext}}/m_{\\text{ext}}$, ensuring black holes can always decay',
      'Gravity must be the weakest force at all energy scales',
      'Gravitons must have zero mass in all consistent vacua',
      'The gravitational coupling must run to zero in the UV',
    ],
    correctIndex: 0,
    explanation: 'The WGC ensures that extremal black holes are kinematically allowed to decay — preventing stable remnants that would lead to an infinite number of species and violate entropy bounds. For $U(1)$ gauge theory coupled to gravity, at least one particle must satisfy $m \\leq \\sqrt{2} q M_{\\text{Pl}}$.',
    realWorld: 'The WGC has been verified in every known string compactification and constrains axion physics, large field inflation, and dark photon models.',
    hint: 'Extremal black holes must be able to decay — that requires a super-extremal particle.',
  },
  {
    id: 314005, topic: 'cumrun-vafa', difficulty: 'sota',
    question: 'Vafa\'s "de Sitter Swampland Conjecture" (2018) proposes that in any consistent quantum gravity theory:',
    options: [
      'The scalar field potential satisfies $|\\nabla V| \\geq c \\cdot V / M_{\\text{Pl}}$ for some $O(1)$ constant $c$ — ruling out stable de Sitter vacua and implying dark energy must be quintessence, not a cosmological constant',
      'De Sitter space is unstable only in $D > 4$ dimensions',
      'The cosmological constant must be exactly zero',
      'Dark energy arises from a cosmological phase transition at $T \\sim 1$ eV',
    ],
    correctIndex: 0,
    explanation: 'The conjecture states that the potential must be sufficiently steep everywhere: $|\\nabla V| / V \\geq c/M_{\\text{Pl}}$ with $c \\sim O(1)$. This forbids flat de Sitter minima, implying our universe\'s accelerated expansion is driven by a rolling scalar field (quintessence) rather than a cosmological constant $\\Lambda$.',
    realWorld: 'If correct, this would overturn the standard $\\Lambda$CDM cosmological model and predict that dark energy evolves with time — potentially testable by DESI and Euclid.',
    hint: 'The potential must always be steep enough — no flat de Sitter plateaus allowed.',
  },
  {
    id: 314006, topic: 'cumrun-vafa', difficulty: 'sota',
    question: 'In the Strominger-Vafa calculation, Vafa\'s specific contribution was recognizing that:',
    options: [
      'The D-brane bound state at weak coupling could be exactly mapped to the black hole at strong coupling via BPS state protection under supersymmetry — and that the Cardy formula applied to the effective CFT gives the exact entropy',
      'The black hole must be non-rotating for the calculation to work',
      'The calculation requires M-theory rather than type IIB string theory',
      'The entropy formula requires quantum corrections beyond the leading order',
    ],
    correctIndex: 0,
    explanation: 'Vafa brought the key insight that BPS (Bogomol\'nyi-Prasad-Sommerfield) states — which saturate the mass-charge bound — have degeneracies protected by supersymmetry. This means the microstate count at weak coupling (where D-branes are tractable) is exact at strong coupling (where the black hole geometry emerges). The Cardy formula then gives $S = 2\\pi\\sqrt{c \\cdot n/6}$ with no corrections.',
    realWorld: 'This "non-renormalization" argument is what makes the Strominger-Vafa calculation exact rather than approximate — a profound consequence of supersymmetry.',
    hint: 'Supersymmetry protects the counting: weak coupling = strong coupling for BPS states.',
    glossaryLinks: ['strominger-vafa'],
  },
];
