import type { Question } from '../types';

export const blackwellQuestions: Question[] = [
  { id: 20940, topic: 'blackwell', difficulty: 'sota', question: "The Rao-Blackwell theorem establishes that conditioning on a sufficient statistic yields:", options: ['The unique minimum variance unbiased estimator (UMVUE)', 'A maximum likelihood estimator', 'A Bayesian posterior mean', 'A consistent but biased estimator'], correctIndex: 0, explanation: "Conditioning any unbiased estimator on a sufficient statistic reduces variance, yielding the UMVUE.", realWorld: "This theorem is fundamental to designing efficient clinical trial endpoints and quality control metrics.", hint: "Sufficiency captures all information — conditioning on it removes noise without adding bias." },
  { id: 20941, topic: 'blackwell', difficulty: 'sota', question: "In Blackwell's comparison of experiments, α is 'more informative' than β if:", options: ['β can be obtained from α by randomization (garbling)', 'α has more observations', 'α has lower Type I error rates', 'β is a subset of α\'s sample space'], correctIndex: 0, explanation: "α ≥ β if β's distribution can be derived from α's by adding noise — α is better for every decision problem.", realWorld: "This framework helps decide whether to invest in a better sensor vs. more data from a worse one.", hint: "More informative means you can simulate the worse experiment from the better one by adding noise." },
  { id: 20942, topic: 'blackwell', difficulty: 'sota', question: "'Blackwell optimality' in MDPs requires a policy that is optimal for:", options: ['All discount factors sufficiently close to 1', 'A finite horizon only', 'Immediate reward maximization', 'Discount factor 0 only'], correctIndex: 0, explanation: "Blackwell optimality is stronger than discount-optimality — the policy works for all β ∈ (β*, 1).", realWorld: "This concept ensures robust long-term planning in robotics and operations research.", hint: "It's a policy so good it works regardless of how patient you are, as long as you're patient enough." },
  { id: 20943, topic: 'blackwell', difficulty: 'sota', question: "What historic barrier did David Blackwell break at UC Berkeley?", options: ['First Black tenured professor at the university', 'First statistician to hold a named chair', 'Youngest full professor in the department', 'First non-American to chair the statistics dept'], correctIndex: 0, explanation: "Despite racial discrimination (IAS initially refused him), he became Berkeley's first Black tenured professor.", realWorld: "His career illustrates how systemic racism delayed recognition of mathematical brilliance for decades.", hint: "He overcame severe institutional discrimination to achieve a historic academic milestone." },
  { id: 20944, topic: 'blackwell', difficulty: 'sota', question: "Blackwell's approachability theorem: a set S is approachable if a player can:", options: ["Force the long-run average payoff to converge to S regardless of the opponent", 'Find a dominant strategy leading to S', 'Identify all Nash equilibria in S', 'Compute S as the convex hull of payoffs'], correctIndex: 0, explanation: "Blackwell's theorem gives conditions for guaranteeing convergence of time-averaged payoffs to a target set.", realWorld: "This theorem underpins modern online learning algorithms and no-regret optimization.", hint: "Think about guaranteeing long-run average performance against any adversary." },
];
