import type { Question } from '../types';

export const davidHilbertQuestions: Question[] = [
  {
    id: 13001,
    topic: 'david-hilbert',
    difficulty: 'easy',
    question: 'David Hilbert is most famous for:',
    options: [
      'Presenting 23 unsolved problems in 1900 that shaped the direction of 20th-century mathematics',
      'Inventing calculus independently from Newton',
      'Proving Fermat\'s Last Theorem',
      'Discovering the structure of DNA',
    ],
    correctIndex: 0,
    explanation: 'At the 1900 International Congress of Mathematicians in Paris, Hilbert presented 23 problems that he believed would drive mathematical progress. Many remain unsolved and continue to shape research today.',
    realWorld: 'Hilbert\'s problems influenced fields from logic (Gödel\'s incompleteness) to physics (axiomatization) to computer science (the Entscheidungsproblem, which led to Turing machines).',
    hint: 'He stood up at a conference in Paris in 1900 and challenged mathematicians for the next century.',
  },
  {
    id: 13002,
    topic: 'david-hilbert',
    difficulty: 'easy',
    question: 'A Hilbert space, named after David Hilbert, is:',
    options: [
      'A complete inner product space — generalizing Euclidean geometry to infinite dimensions with the notion of angle and distance',
      'A three-dimensional room where Hilbert worked',
      'A type of computer memory architecture',
      'A space with exactly 23 dimensions',
    ],
    correctIndex: 0,
    explanation: 'A Hilbert space is a vector space with an inner product $\\langle x, y \\rangle$ that is complete (all Cauchy sequences converge). It provides the mathematical framework for quantum mechanics and functional analysis.',
    realWorld: 'Quantum mechanics is formulated entirely in Hilbert spaces — every quantum state is a vector, every measurement is an operator. Signal processing (Fourier analysis) and ML (kernel methods, SVMs) also live in Hilbert spaces.',
    hint: 'Think of it as Euclidean space extended to infinite dimensions — with dot products and distances.',
  },
  {
    id: 13003,
    topic: 'david-hilbert',
    difficulty: 'hard',
    question: 'Hilbert\'s program aimed to:',
    options: [
      'Prove that all of mathematics could be derived from a finite, consistent, and complete set of axioms — a goal later shown impossible by Gödel',
      'Build the fastest mechanical calculator',
      'Classify all prime numbers up to one billion',
      'Create a universal language for international communication',
    ],
    correctIndex: 0,
    explanation: 'Hilbert wanted to formalize all mathematics and prove it free of contradictions. Gödel\'s incompleteness theorems (1931) showed this is impossible: any sufficiently powerful consistent system contains true statements it cannot prove.',
    realWorld: 'The failure of Hilbert\'s program led directly to computability theory (Turing, Church), which led to computer science. The limits of formalization remain relevant in AI — no formal system can capture all mathematical truth.',
    hint: 'He wanted mathematics to be a perfect, complete, consistent formal system — but Gödel proved it can\'t be.',
  },
  {
    id: 13004,
    topic: 'david-hilbert',
    difficulty: 'hard',
    question: 'Hilbert\'s 6th problem asked for:',
    options: [
      'The axiomatization of physics — putting all of physics on a rigorous mathematical foundation like Euclid\'s geometry',
      'Finding all prime numbers less than one million',
      'Proving the Riemann Hypothesis',
      'Building a perpetual motion machine',
    ],
    correctIndex: 0,
    explanation: 'Hilbert envisioned treating physics axiomatically: deriving all physical laws from a minimal set of axioms, just as geometry follows from Euclid\'s five postulates. This remains partially open — quantum gravity lacks an axiomatic foundation.',
    realWorld: 'Quantum mechanics was successfully axiomatized (von Neumann, Dirac), but combining it with general relativity into a single axiomatic framework remains the holy grail of theoretical physics.',
    hint: 'He wanted physics to have the same rigorous axiomatic structure as geometry.',
  },
  {
    id: 13005,
    topic: 'david-hilbert',
    difficulty: 'sota',
    question: 'The Entscheidungsproblem (decision problem), posed by Hilbert, asked whether:',
    options: [
      'There exists an algorithm that can determine the truth or falsity of any mathematical statement — proven impossible independently by Turing and Church in 1936',
      'Every equation has a solution in rational numbers',
      'Every geometric construction can be done with compass and straightedge',
      'Every matrix has real eigenvalues',
    ],
    correctIndex: 0,
    explanation: 'Hilbert asked: is there a mechanical procedure to decide any mathematical statement? Turing showed no such algorithm exists by constructing the Halting Problem. Church independently proved it using lambda calculus. This negative result CREATED computer science.',
    realWorld: 'The impossibility proof required defining "algorithm" precisely — Turing\'s definition (Turing machines) became the foundation of computer science. Every computer is a finite approximation of Turing\'s theoretical machine.',
    hint: 'Can a machine decide if any mathematical statement is true? The answer revolutionized what "computation" means.',
  },
];
