import type { Question } from '../types';

export const ritchieQuestions: Question[] = [
  {
    id: 21030,
    topic: 'dennis-ritchie',
    difficulty: 'sota',
    question: 'Dennis Ritchie\'s C language introduced which memory management paradigm that remains fundamental to systems programming?',
    options: ['Manual pointer arithmetic with malloc/free', 'Garbage collection via reference counting', 'Region-based memory management', 'Automatic stack-only allocation'],
    correctIndex: 0,
    explanation: 'C gave programmers direct access to memory through pointers, with manual allocation (malloc) and deallocation (free). This power-and-responsibility model underlies virtually all operating systems.',
    realWorld: 'Linux, Windows, macOS kernels, and most embedded systems are still written in C or its direct descendants.',
    hint: 'The programmer explicitly allocates and frees heap memory.',
  },
  {
    id: 21031,
    topic: 'dennis-ritchie',
    difficulty: 'sota',
    question: 'What radical design decision made Unix uniquely portable compared to earlier operating systems?',
    options: ['Writing the OS kernel in C instead of assembly', 'Using a microkernel architecture', 'Implementing virtual memory from the start', 'Supporting multithreading natively'],
    correctIndex: 0,
    explanation: 'Unix was revolutionary because its kernel was written in a high-level language (C), making it portable to different hardware architectures — a concept considered heretical at the time.',
    realWorld: 'This decision spawned the entire family of Unix-like systems: Linux, macOS, Android, iOS, and BSD.',
    hint: 'Before this, operating systems were tied to specific hardware through assembly code.',
  },
  {
    id: 21032,
    topic: 'dennis-ritchie',
    difficulty: 'sota',
    question: 'The Unix philosophy is best summarized by which principle?',
    options: ['"Do one thing and do it well"', '"Move fast and break things"', '"Worse is better"', '"Convention over configuration"'],
    correctIndex: 0,
    explanation: 'Unix programs are designed as small, focused tools that can be composed via pipes and redirection. This modularity principle (articulated by Doug McIlroy) is the foundation of the Unix philosophy.',
    realWorld: 'Modern microservices architecture, functional programming, and the Unix pipeline model all descend from this philosophy.',
    hint: 'Small programs connected by pipes, each performing a single task.',
  },
  {
    id: 21033,
    topic: 'dennis-ritchie',
    difficulty: 'sota',
    question: 'C\'s "undefined behavior" for operations like signed integer overflow is a deliberate design choice for what reason?',
    options: ['To allow maximum compiler optimization across different hardware', 'To simplify the language specification', 'To prevent security vulnerabilities', 'To maintain backward compatibility with B'],
    correctIndex: 0,
    explanation: 'By leaving certain behaviors undefined, C allows compilers to generate the most efficient code for each target architecture without being constrained by a single interpretation.',
    realWorld: 'Undefined behavior remains one of the most consequential design decisions in computing, enabling both extreme performance and subtle security vulnerabilities.',
    hint: 'Different CPUs handle overflow differently; the language avoids picking one.',
  },
  {
    id: 21034,
    topic: 'dennis-ritchie',
    difficulty: 'sota',
    question: 'Ritchie and Thompson\'s original Unix was developed at which research laboratory?',
    options: ['Bell Labs (AT&T)', 'Xerox PARC', 'MIT Lincoln Laboratory', 'IBM Watson Research Center'],
    correctIndex: 0,
    explanation: 'Unix was created at Bell Labs in 1969–1971, the same legendary lab that produced the transistor, information theory, and the laser.',
    realWorld: 'Bell Labs\' culture of funding pure research without immediate commercial pressure produced many of the 20th century\'s most important inventions.',
    hint: 'The lab where Claude Shannon, the transistor team, and Unix all originated.',
  },
];
