import type { Question } from '../types';

export const wittenQuestions: Question[] = [
  {
    id: 21080,
    topic: 'witten',
    difficulty: 'sota',
    question: 'Witten\'s M-theory unifies the five consistent superstring theories in how many spacetime dimensions?',
    options: ['11', '10', '26', '12'],
    correctIndex: 0,
    explanation: 'At the 1995 String Theory conference, Witten proposed that all five 10-dimensional superstring theories are different limits of a single 11-dimensional theory he called "M-theory."',
    realWorld: 'M-theory remains the leading candidate for a "theory of everything" unifying quantum mechanics and general relativity.',
    hint: 'One more dimension than the string theories it unifies.',
  },
  {
    id: 21081,
    topic: 'witten',
    difficulty: 'sota',
    question: 'Witten won the Fields Medal (1990) primarily for his work applying physics to which area of pure mathematics?',
    options: ['Topological quantum field theory and knot invariants', 'Algebraic geometry', 'Number theory', 'Combinatorics'],
    correctIndex: 0,
    explanation: 'Witten showed that quantum field theory methods could solve deep problems in topology, including providing a physical framework for the Jones polynomial (knot invariants) and Donaldson invariants of 4-manifolds.',
    realWorld: 'He remains the only physicist to win the Fields Medal, mathematics\' highest honor.',
    hint: 'He used quantum physics to classify knots and understand 4-dimensional spaces.',
  },
  {
    id: 21082,
    topic: 'witten',
    difficulty: 'sota',
    question: 'The AdS/CFT correspondence, closely related to Witten\'s work, conjectures an equivalence between which two theories?',
    options: ['A gravitational theory in anti-de Sitter space and a conformal field theory on its boundary', 'String theory and loop quantum gravity', 'Classical and quantum electrodynamics', 'General relativity and Newtonian gravity'],
    correctIndex: 0,
    explanation: 'AdS/CFT (proposed by Maldacena, with key contributions by Witten) states that a theory of quantum gravity in a bulk spacetime is exactly equivalent to a non-gravitational quantum field theory on its boundary — a holographic duality.',
    realWorld: 'AdS/CFT has found unexpected applications in condensed matter physics, heavy-ion collisions, and even quantum error correction.',
    hint: 'A holographic principle: the physics inside a volume is encoded on its boundary.',
  },
  {
    id: 21083,
    topic: 'witten',
    difficulty: 'sota',
    question: 'Witten\'s Chern-Simons theory provides a 3-dimensional topological field theory interpretation of which mathematical invariant?',
    options: ['The Jones polynomial of knots', 'The Alexander polynomial', 'The Euler characteristic', 'The Betti numbers'],
    correctIndex: 0,
    explanation: 'Witten showed that the Jones polynomial (a knot invariant discovered by Vaughan Jones in 1984) naturally arises as a Wilson loop expectation value in Chern-Simons gauge theory — unifying physics and knot theory.',
    realWorld: 'This connection spawned the field of quantum topology and influenced quantum computing approaches to knot problems.',
    hint: 'This knot invariant was previously discovered by a mathematician, but Witten gave it a physical meaning.',
  },
  {
    id: 21084,
    topic: 'witten',
    difficulty: 'sota',
    question: 'Before becoming a physicist, what was Edward Witten\'s undergraduate major?',
    options: ['History', 'Physics', 'Mathematics', 'Philosophy'],
    correctIndex: 0,
    explanation: 'Witten studied history at Brandeis University and briefly worked on George McGovern\'s presidential campaign before switching to mathematics and physics in graduate school at Princeton.',
    realWorld: 'His unconventional path highlights that the greatest scientific breakthroughs often come from outsiders with fresh perspectives.',
    hint: 'He studied a liberal arts subject and even worked in politics before switching to science.',
  },
];
