import type { Question } from '../types';

export const ostromQuestions: Question[] = [
  { id: 20920, topic: 'ostrom', difficulty: 'sota', question: "Elinor Ostrom's work fundamentally challenged which famous argument?", options: ["Garrett Hardin's 'Tragedy of the Commons'", "Adam Smith's invisible hand", "Coase's theorem on externalities", "Arrow's impossibility theorem"], correctIndex: 0, explanation: "Ostrom proved communities successfully manage common-pool resources through self-governance, contradicting Hardin.", realWorld: "Her work guides sustainable fisheries, forest management, and open-source software governance worldwide.", hint: "Hardin argued shared resources inevitably get destroyed — Ostrom found counterexamples everywhere." },
  { id: 20921, topic: 'ostrom', difficulty: 'sota', question: "Which is NOT one of Ostrom's eight design principles for commons management?", options: ['Centralized government enforcement of extraction limits', 'Clearly defined boundaries of the resource and user group', 'Collective-choice arrangements for affected parties', 'Graduated sanctions for rule violators'], correctIndex: 0, explanation: "Ostrom's framework shows centralized government enforcement is NOT required — self-governance works.", realWorld: "Many successful irrigation systems in Nepal and Indonesia follow her principles without government management.", hint: "Her whole thesis is that communities don't need a central authority." },
  { id: 20922, topic: 'ostrom', difficulty: 'sota', question: "Ostrom's IAD framework models commons governance by analyzing:", options: ['Action arenas where participants interact under rules within biophysical and community contexts', 'Pure Nash equilibria in static games', 'Pareto-optimal allocations in general equilibrium', 'Principal-agent relationships with asymmetric information'], correctIndex: 0, explanation: "The IAD framework examines how rules, biophysical conditions, and community attributes shape decision-making.", realWorld: "The framework is used to analyze governance of everything from Wikipedia editing to atmospheric carbon.", hint: "It's a multi-level analytical tool — think about nested institutional layers." },
  { id: 20923, topic: 'ostrom', difficulty: 'sota', question: "What historic distinction did Ostrom achieve with the 2009 Nobel Prize?", options: ['First woman to win the Nobel Prize in Economics', 'Youngest Nobel laureate in Economics', 'First political scientist to win any Nobel Prize', 'First American woman to win the Nobel Prize'], correctIndex: 0, explanation: "Ostrom became the first woman to win the Nobel in Economics. She was told as a teenager she couldn't take trigonometry because she was a girl.", realWorld: "Her award expanded the economics Nobel beyond traditional mathematical/theoretical work.", hint: "She broke a gender barrier that had stood for decades." },
  { id: 20924, topic: 'ostrom', difficulty: 'sota', question: "What distinguishes a 'common-pool resource' from a 'public good'?", options: ['Common-pool resources are rivalrous but non-excludable; public goods are neither', 'Common-pool resources are excludable; public goods are rivalrous', 'No economic distinction exists', 'Common-pool resources are privately owned'], correctIndex: 0, explanation: "Common-pool resources are rivalrous (one person's use diminishes availability) but hard to exclude people from.", realWorld: "Fish stocks are rivalrous (catching fish reduces the stock) but hard to fence off — a classic common-pool resource.", hint: "Think about subtractability: does one person's use reduce what's available for others?" },
];
