import type { Question } from '../types';

export const emilWarburgQuestions: Question[] = [
  {
    id: 405001,
    topic: 'emil-warburg',
    difficulty: 'easy',
    question: 'Emil Warburg is best known for his experimental work on:',
    options: [
      'Gas kinetics, viscosity of rarefied gases, and temperature discontinuity at surfaces',
      'Nuclear fission chain reactions',
      'Electromagnetic wave propagation',
      'Crystal structure determination by X-ray diffraction',
    ],
    correctIndex: 0,
    explanation: 'Warburg made precise measurements of gas viscosity and discovered temperature discontinuity (temperature jump) at surfaces in rarefied gases — a phenomenon Smoluchowski later explained theoretically.',
    realWorld: 'Temperature jump effects are critical in modern microfluidics, vacuum technology, and spacecraft thermal design.',
    hint: 'Gas behavior near surfaces at low pressures.',
    glossaryLinks: ['diffusion', 'brownian-motion'],
  },
  {
    id: 405002,
    topic: 'emil-warburg',
    difficulty: 'hard',
    question: 'The temperature discontinuity Warburg discovered occurs when:',
    options: [
      'The mean free path of gas molecules becomes comparable to the vessel dimensions (Knudsen regime)',
      'The gas undergoes a phase transition',
      'Electromagnetic radiation heats the surface unevenly',
      'The gas is at absolute zero temperature',
    ],
    correctIndex: 0,
    explanation: 'When the Knudsen number (mean free path / characteristic length) approaches or exceeds 1, gas molecules near a surface are not in local thermal equilibrium, creating a measurable temperature jump at the boundary.',
    realWorld: 'This effect matters in semiconductor fabrication, MEMS devices, and atmospheric re-entry thermal modeling.',
    hint: 'When gas is thin enough that molecules don\'t collide much before hitting the wall.',
    glossaryLinks: ['diffusion'],
  },
  {
    id: 405003,
    topic: 'emil-warburg',
    difficulty: 'hard',
    question: 'Smoluchowski worked with Warburg in Berlin and later explained temperature discontinuity using:',
    options: [
      'Kinetic theory and the accommodation coefficient concept',
      'Quantum tunneling of phonons',
      'Electromagnetic boundary conditions',
      'Navier–Stokes turbulence theory',
    ],
    correctIndex: 0,
    explanation: 'Smoluchowski used kinetic theory to show that gas molecules don\'t fully equilibrate with the surface on each collision. The accommodation coefficient α (0 to 1) measures how completely energy is exchanged.',
    realWorld: 'The accommodation coefficient is still a key parameter in rarefied gas dynamics and molecular beam experiments.',
    hint: 'How much energy do molecules exchange with the wall per bounce?',
    glossaryLinks: ['brownian-motion', 'diffusion'],
  },
  {
    id: 405004,
    topic: 'emil-warburg',
    difficulty: 'sota',
    question: 'As president of the Physikalisch-Technische Reichsanstalt (PTR), Warburg oversaw:',
    options: [
      'Precision blackbody radiation measurements that motivated Planck\'s quantum hypothesis',
      'The first detection of gravitational waves',
      'Construction of the first cyclotron',
      'The Manhattan Project\'s German counterpart',
    ],
    correctIndex: 0,
    explanation: 'Under Warburg\'s leadership, the PTR conducted the exacting spectral measurements of blackbody radiation that revealed the ultraviolet catastrophe — directly prompting Max Planck to introduce energy quantization in 1900.',
    realWorld: 'Without the PTR\'s experimental precision under Warburg, Planck might not have had the data that forced him to invent quantum theory.',
    hint: 'The experiments that broke classical physics happened under his watch.',
    glossaryLinks: ['planck-constant'],
  },
];
