import type { Question } from '../types';

export const euclidQuestions: Question[] = [
  {
    id: 11001,
    topic: 'euclid-of-alexandria',
    difficulty: 'easy',
    question: 'What is the fundamental claim of Euclid\'s first postulate?',
    options: [
      'A straight line can be drawn between any two points',
      'All right angles are equal',
      'A circle can be drawn with any center and radius',
      'Parallel lines never meet',
    ],
    correctIndex: 0,
    explanation: 'The first postulate states that two points determine a unique straight line segment. This axiom underlies all of Euclidean geometry and formal proof systems.',
    realWorld: 'GPS routing algorithms assume Euclidean geometry locally — shortest paths between nearby points are straight lines.',
    hint: 'Think about the most basic construction you can make with two points.',
  },
  {
    id: 11002,
    topic: 'euclid-of-alexandria',
    difficulty: 'easy',
    question: 'Euclid\'s proof that there are infinitely many primes uses which key idea?',
    options: [
      'Multiplying all known primes together and adding 1 yields a number with a new prime factor',
      'Every even number greater than 2 is the sum of two primes',
      'The nth prime is always less than 2^n',
      'Primes are uniformly distributed modulo 6',
    ],
    correctIndex: 0,
    explanation: 'Euclid assumed a finite list of primes, formed their product + 1, and showed this number must have a prime factor not on the list — contradiction. It is one of the oldest proofs by contradiction.',
    realWorld: 'The infinitude of primes is the foundation of RSA encryption — security relies on primes being inexhaustible.',
    hint: 'What happens to P₁×P₂×...×Pₙ + 1 when you try to divide it by any known prime?',
  },
  {
    id: 11003,
    topic: 'euclid-of-alexandria',
    difficulty: 'easy',
    question: 'The Euclidean Algorithm computes the GCD of two numbers by:',
    options: [
      'Repeatedly replacing the larger number with the remainder of dividing the two numbers',
      'Factoring both numbers into primes and taking the intersection',
      'Subtracting the smaller from the larger until they are equal',
      'Computing the LCM and dividing by the product',
    ],
    correctIndex: 0,
    explanation: 'gcd(a, b) = gcd(b, a mod b), repeated until the remainder is 0. This is O(log min(a,b)) — exponentially faster than trial division.',
    realWorld: 'The Euclidean Algorithm is used in fraction simplification, modular inverses for cryptography, and polynomial GCDs in computer algebra systems.',
    hint: 'gcd(48, 18) → gcd(18, 12) → gcd(12, 6) → gcd(6, 0) = 6.',
  },
  {
    id: 11004,
    topic: 'euclid-of-alexandria',
    difficulty: 'easy',
    question: 'Which of Euclid\'s five postulates was most controversial and led to non-Euclidean geometry?',
    options: [
      'The parallel postulate: through a point not on a line, exactly one parallel line exists',
      'A straight line can be extended indefinitely',
      'All right angles are equal to one another',
      'A circle can be drawn with any center and radius',
    ],
    correctIndex: 0,
    explanation: 'For 2000 years, mathematicians tried to prove the parallel postulate from the others. Failing to do so, Bolyai and Lobachevsky showed you could replace it to get consistent hyperbolic geometry.',
    realWorld: 'General relativity uses Riemannian (non-Euclidean) geometry — spacetime is curved, so the parallel postulate fails at cosmological scales.',
    hint: 'On a sphere, lines of longitude all meet at the poles — two "parallels" can intersect.',
  },
  {
    id: 11005,
    topic: 'euclid-of-alexandria',
    difficulty: 'hard',
    question: 'The Extended Euclidean Algorithm finds integers $x, y$ such that $ax + by = \\gcd(a, b)$. This is used in cryptography to compute:',
    options: [
      'The modular inverse $a^{-1} \\pmod{b}$ when $\\gcd(a,b)=1$',
      'The discrete logarithm of $a$ modulo $b$',
      'The Euler totient $\\phi(ab)$',
      'The Jacobi symbol $\\left(\\frac{a}{b}\\right)$',
    ],
    correctIndex: 0,
    explanation: 'When gcd(a,b)=1, Bézout\'s identity gives ax ≡ 1 (mod b), so x is the modular inverse of a. RSA decryption and ECDSA signing both require computing modular inverses.',
    realWorld: 'Every HTTPS connection uses modular inverses computed via the Extended Euclidean Algorithm to set up public-key cryptography.',
    hint: 'If ax + by = 1, what is ax modulo b?',
  },
  {
    id: 11006,
    topic: 'euclid-of-alexandria',
    difficulty: 'hard',
    question: 'A "golden ratio" $\\phi$ satisfies $\\phi^2 = \\phi + 1$. What is the continued fraction expansion of $\\phi$?',
    options: [
      '$\\phi = 1 + \\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{\\ddots}}}$',
      '$\\phi = 2 + \\cfrac{1}{2 + \\cfrac{1}{2 + \\cdots}}$',
      '$\\phi = 1 + \\cfrac{1}{2 + \\cfrac{1}{3 + \\cdots}}$',
      '$\\phi = 3 + \\cfrac{1}{7 + \\cfrac{1}{15 + \\cdots}}$',
    ],
    correctIndex: 0,
    explanation: 'Since φ = 1 + 1/φ, substituting recursively gives the continued fraction [1;1,1,1,...]. This makes φ the "most irrational" number — hardest to approximate by rationals, which is why it appears in phyllotaxis and optimal search.',
    realWorld: 'Fibonacci spiral proportions in sunflowers and nautilus shells arise because φ is the limit of Fibonacci ratios — nature packs seeds using the "most irrational" angle.',
    hint: 'φ = 1 + 1/φ — now substitute φ again into the right-hand side recursively.',
  },
  {
    id: 11007,
    topic: 'euclid-of-alexandria',
    difficulty: 'hard',
    question: 'Euclid\'s proof of the Pythagorean theorem ($a^2 + b^2 = c^2$) in Book I uses:',
    options: [
      'Area-preserving shearing transformations on squares built on each side',
      'Similar triangle proportionality and the angle bisector theorem',
      'Trigonometric identities $\\sin^2\\theta + \\cos^2\\theta = 1$',
      'The dot product formula for orthogonal vectors',
    ],
    correctIndex: 0,
    explanation: 'Proposition 47 (Book I) constructs squares on each side and uses SAS congruence plus shearing (parallelograms with same base and height have equal area) to partition the hypotenuse square into two rectangles equaling the leg squares.',
    realWorld: 'The Pythagorean theorem underlies Euclidean distance, which powers k-NN classifiers, clustering, and any ML model using L2 loss.',
    hint: 'No algebra is used — only area arguments about rectangles and triangles with equal bases and heights.',
  },
  {
    id: 11008,
    topic: 'euclid-of-alexandria',
    difficulty: 'sota',
    question: 'In formal proof systems, Euclid\'s Elements was re-examined and found to have gaps. Which modern framework fully formalizes Euclidean geometry without intuitive leaps?',
    options: [
      'Hilbert\'s axiom system with 20 axioms covering incidence, order, congruence, continuity, and parallels',
      'ZFC set theory with the axiom of choice',
      'Peano arithmetic extended with geometric predicates',
      'Category theory with a topos of geometric spaces',
    ],
    correctIndex: 0,
    explanation: 'Euclid\'s proofs rely on diagrams and implicit continuity assumptions. Hilbert\'s 1899 "Grundlagen der Geometrie" filled all gaps with a complete, consistent axiom system — a model for modern axiomatic mathematics.',
    realWorld: 'Automated theorem provers like Lean and Coq use Hilbert-style axiomatic geometry to formally verify proofs, enabling mathematically certain software verification.',
    hint: 'Euclid assumed lines intersect without proving it — which axiom group addresses this?',
  },
  {
    id: 11009,
    topic: 'euclid-of-alexandria',
    difficulty: 'sota',
    question: 'The "Elements" structure — definitions, postulates, common notions, propositions — is best described as an example of:',
    options: [
      'The axiomatic-deductive method: all theorems follow from a minimal set of self-evident assumptions via formal logic',
      'The empirical-inductive method: conclusions derived from geometric measurements',
      'Proof by exhaustion: all cases enumerated and verified computationally',
      'The dialectical method: opposing views synthesized into geometric truth',
    ],
    correctIndex: 0,
    explanation: 'The axiomatic method — start with axioms, derive everything else — is the foundation of all pure mathematics, logic, and formal computer science. Euclid\'s Elements was the canonical model for 2,000 years.',
    realWorld: 'Every programming language specification, type system, and security proof follows the axiomatic method: define primitives, then derive all properties logically.',
    hint: 'Euclid starts with what he accepts without proof — then derives everything else.',
  },
  {
    id: 11010,
    topic: 'euclid-of-alexandria',
    difficulty: 'sota',
    question: 'In machine learning, "Euclidean distance" fails in high dimensions due to the "curse of dimensionality." Specifically:',
    options: [
      'All pairwise distances converge to the same value as dimension d → ∞, making nearest-neighbor meaningless',
      'The L2 norm grows without bound, requiring normalization before use',
      'Euclidean distance violates the triangle inequality in high dimensions',
      'The Euclidean ball has zero volume relative to the enclosing hypercube as d grows',
    ],
    correctIndex: 0,
    explanation: 'In high dimensions, E[dist_max]/E[dist_min] → 1 — all points are roughly equidistant. This makes k-NN, clustering, and any distance-based algorithm degenerate. Alternatives include cosine similarity, learned metrics, or dimensionality reduction.',
    realWorld: 'This is why embedding models (BERT, CLIP) project to lower-dimensional spaces before nearest-neighbor search — raw pixel/token spaces are too high-dimensional for Euclidean distance to be meaningful.',
    hint: 'In 1000D, the nearest and farthest neighbor distances become almost identical — why?',
  },
];
