import type { Question } from '../types';

export const gabrielLippmannQuestions: Question[] = [
  {
    id: 403001,
    topic: 'gabriel-lippmann',
    difficulty: 'easy',
    question: 'Gabriel Lippmann won the 1908 Nobel Prize in Physics for:',
    options: [
      'Reproducing colours photographically using interference of light waves',
      'Discovering X-rays',
      'Inventing the incandescent light bulb',
      'Measuring the speed of light precisely',
    ],
    correctIndex: 0,
    explanation: 'Lippmann\'s interference colour photography captured the full visible spectrum without dyes or pigments by recording standing light waves in a photographic emulsion backed by a mercury mirror.',
    realWorld: 'Though impractical for everyday use, Lippmann\'s method anticipated holography and is the physical basis of modern interference-based colour filters.',
    hint: 'Colour from physics, not chemistry.',
    glossaryLinks: ['wave-particle', 'doppler-effect'],
    formulaLinks: ['lippmann-interference'],
  },
  {
    id: 403002,
    topic: 'gabriel-lippmann',
    difficulty: 'hard',
    question: 'How did Lippmann\'s colour photography work without using any dyes or colour filters?',
    options: [
      'Standing waves in a thin emulsion recorded the wavelength of light, which reconstructed colours on viewing',
      'He used three separate exposures through red, green, and blue filters',
      'He painted colours onto the developed plate by hand',
      'He used fluorescent chemicals that glowed under UV light',
    ],
    correctIndex: 0,
    explanation: 'A mercury mirror behind the emulsion reflected light back, creating standing waves. The emulsion recorded the interference nodes as layers of silver grains spaced at half-wavelength intervals. On illumination, only the original wavelengths constructively interfere.',
    realWorld: 'This is essentially a Bragg reflector — the same physics used in modern fiber optic gratings and structural colour in butterflies.',
    hint: 'Thin-film interference recorded permanently in silver.',
    formulaLinks: ['lippmann-interference'],
  },
  {
    id: 403003,
    topic: 'gabriel-lippmann',
    difficulty: 'hard',
    question: 'Lippmann also made foundational contributions to which measurement instrument?',
    options: [
      'The capillary electrometer — measuring tiny voltages via mercury meniscus movement',
      'The telescope — improving lens grinding techniques',
      'The barometer — correcting for altitude effects',
      'The thermometer — inventing the mercury-in-glass design',
    ],
    correctIndex: 0,
    explanation: 'Lippmann developed the theory and refined the capillary electrometer, which measures voltage by observing the position of a mercury meniscus in a fine capillary tube. It was crucial for early electrophysiology.',
    realWorld: 'Einthoven used Lippmann\'s electrometer principles when developing the first ECG (electrocardiogram).',
    hint: 'Mercury in a thin tube responds to electrical potential.',
  },
  {
    id: 403004,
    topic: 'gabriel-lippmann',
    difficulty: 'sota',
    question: 'In Lippmann photography, the spacing of recorded silver layers equals $\\lambda / (2n)$, where $n$ is the refractive index of the emulsion. This is equivalent to:',
    options: [
      'A Bragg reflector that selectively reflects the recorded wavelength',
      'A diffraction grating that disperses all wavelengths equally',
      'A Fabry–Pérot cavity with variable spacing',
      'A total internal reflection condition',
    ],
    correctIndex: 0,
    explanation: 'The layers act as a volume Bragg grating satisfying $2d\\sin\\theta = m\\lambda$. When white light illuminates the developed plate, only wavelengths matching the recorded spacing are constructively reflected — reproducing the original colours.',
    realWorld: 'Modern volume holographic gratings, fiber Bragg gratings in telecom, and photonic crystals all rely on the same physics Lippmann exploited in 1891.',
    hint: 'Periodic layers of different refractive index selectively reflect one wavelength.',
    formulaLinks: ['lippmann-interference'],
  },
];
