import type { Question } from '../types';

export const georgeBooleQuestions: Question[] = [
  {
    id: 20400,
    topic: 'george-boole',
    difficulty: 'hard',
    question: 'In Boolean algebra, which identity states that $\\overline{A \\cap B} = \\overline{A} \\cup \\overline{B}$?',
    options: ["De Morgan's Law", "Absorption Law", "Distributive Law", "Idempotent Law"],
    correctIndex: 0,
    explanation: "De Morgan's Laws are the duality bridge between AND/OR and their complements — foundational to every logic gate simplification in chip design.",
    realWorld: 'Every CPU in existence uses De Morgan transformations to minimize transistor counts in logic circuits.',
    hint: 'Think about how negating a conjunction relates to a disjunction of negations.',
  },
  {
    id: 20401,
    topic: 'george-boole',
    difficulty: 'hard',
    question: 'Boole\'s original algebra operated on classes of objects. What structure does a Boolean algebra form in modern abstract algebra?',
    options: ['Complemented distributive lattice', 'Non-commutative ring', 'Free group', 'Euclidean domain'],
    correctIndex: 0,
    explanation: 'A Boolean algebra is a complemented distributive lattice — every element has a complement, and meet distributes over join (and vice versa).',
    realWorld: 'Database query optimizers use lattice theory to restructure SQL WHERE clauses for minimal disk I/O.',
    hint: 'Consider a structure where every element has a complement and both distributive laws hold.',
  },
  {
    id: 20402,
    topic: 'george-boole',
    difficulty: 'sota',
    question: 'Stone\'s Representation Theorem (1936) establishes a duality between Boolean algebras and which class of topological spaces?',
    options: ['Compact totally disconnected Hausdorff spaces', 'Connected manifolds', 'Locally compact abelian groups', 'Metric spaces with the Baire property'],
    correctIndex: 0,
    explanation: 'Stone duality shows every Boolean algebra is isomorphic to the clopen algebra of a compact totally disconnected Hausdorff (Stone) space — linking algebra to topology.',
    realWorld: 'Stone duality underpins denotational semantics in programming language theory and domain theory.',
    hint: 'The dual spaces are sometimes called "Stone spaces" — what topological properties define them?',
  },
  {
    id: 20403,
    topic: 'george-boole',
    difficulty: 'sota',
    question: 'Shannon\'s 1937 master\'s thesis showed Boolean algebra maps to relay circuits. What is the minimum number of two-input NAND gates needed to implement an arbitrary Boolean function of $n$ variables (Lupanov bound)?',
    options: ['$O(2^n / n)$', '$O(n!)$', '$O(n \\log n)$', '$O(2^{2^n})$'],
    correctIndex: 0,
    explanation: 'The Lupanov bound proves $O(2^n/n)$ gates suffice for any $n$-variable Boolean function — matching the Shannon counting lower bound asymptotically.',
    realWorld: 'FPGA synthesis tools use these bounds to estimate the minimum look-up table resources needed for arbitrary logic.',
    hint: 'Shannon counting shows most functions need $\\Omega(2^n/n)$ gates; Lupanov showed this is also an upper bound.',
  },
  {
    id: 20404,
    topic: 'george-boole',
    difficulty: 'easy',
    question: 'What does the Boolean expression $A \\oplus B$ (XOR) evaluate to when both $A$ and $B$ are true?',
    options: ['False', 'True', 'Undefined', 'Null'],
    correctIndex: 0,
    explanation: 'XOR returns true only when the inputs differ. When both are true, the result is false.',
    realWorld: 'XOR is the core operation in checksums, parity bits, and one-time pad encryption.',
    hint: 'XOR means "exclusive or" — exactly one must be true.',
  },
];
