import type { Question } from '../types';

export const goodfellowQuestions: Question[] = [
  {
    id: 11901,
    topic: 'goodfellow',
    difficulty: 'easy',
    question: 'Generative Adversarial Networks (GANs), invented by Goodfellow, consist of:',
    options: [
      'A generator that creates fake samples and a discriminator that distinguishes real from fake — trained adversarially',
      'Two generators that compete to produce the most realistic images',
      'An encoder-decoder pair trained with reconstruction and perceptual losses',
      'A discriminator trained to classify images and a generator trained as a regularizer',
    ],
    correctIndex: 0,
    explanation: 'GANs frame image generation as a minimax game: G minimizes log(1-D(G(z))), D maximizes log D(x) + log(1-D(G(z))). At equilibrium, G generates samples indistinguishable from data. Goodfellow invented GANs after a pub discussion in 2014.',
    realWorld: 'GANs power deepfakes, StyleGAN faces, image super-resolution, drug molecule generation, and data augmentation for rare medical conditions — Goodfellow\'s pub idea reshaped generative AI.',
    hint: 'A forger (generator) vs. a detective (discriminator) — they improve each other through competition.',
  },
  {
    id: 11902,
    topic: 'goodfellow',
    difficulty: 'easy',
    question: 'The GAN training objective is a minimax game: $\\min_G \\max_D V(D,G)$ where $V = $',
    options: [
      '$\\mathbb{E}_{x \\sim p_{data}}[\\log D(x)] + \\mathbb{E}_{z \\sim p_z}[\\log(1-D(G(z)))]$',
      '$\\mathbb{E}_{x \\sim p_{data}}[D(x)] - \\mathbb{E}_{z \\sim p_z}[D(G(z))]$',
      '$\\mathbb{E}_{x}[\\|x - G(z)\\|^2] + \\lambda \\mathbb{E}_z[\\|z\\|^2]$',
      '$D_{KL}(p_{data} \\| p_G) + D_{KL}(p_G \\| p_{data})$',
    ],
    correctIndex: 0,
    explanation: 'The optimal discriminator D*(x) = p_data(x)/(p_data(x)+p_G(x)), and substituting back shows the GAN objective is equivalent to minimizing Jensen-Shannon divergence between p_data and p_G — measuring distribution overlap.',
    realWorld: 'The JS divergence perspective explains early GAN training failures: when G is poor, D perfectly separates distributions, JS divergence saturates, and G gets zero gradient. This led to Wasserstein GANs (WGANs).',
    hint: 'D wants to output 1 for real (log D(x) high) and 0 for fake (log(1-D(G(z))) high). G wants to fool D.',
  },
  {
    id: 11903,
    topic: 'goodfellow',
    difficulty: 'easy',
    question: 'The "Deep Learning" textbook by Goodfellow, Bengio, and Courville is widely used because it covers:',
    options: [
      'Mathematical prerequisites, core deep learning algorithms, and research frontiers in a unified framework',
      'Only practical PyTorch and TensorFlow implementation recipes',
      'Exclusively the theory of deep learning without any applications',
      'A historical survey of neural network research from 1943 to 2015',
    ],
    correctIndex: 0,
    explanation: 'The "Deep Learning Book" (2016) is the standard graduate textbook — covering linear algebra, probability, ML basics, feedforward networks, regularization, optimization, RNNs, CNNs, and generative models in a coherent theoretical framework.',
    realWorld: 'The book is freely available online at deeplearningbook.org and has been cited over 50,000 times — the canonical reference for anyone seriously studying deep learning foundations.',
    hint: 'The book has three parts: mathematics, practical ML, and deep learning research — building from foundations to frontiers.',
  },
  {
    id: 11904,
    topic: 'goodfellow',
    difficulty: 'easy',
    question: 'Adversarial examples, extensively studied by Goodfellow, are inputs that:',
    options: [
      'Fool neural networks by adding imperceptible perturbations that change the predicted class',
      'Adversarially selected training samples that maximally improve model robustness',
      'Real-world out-of-distribution inputs the model has never seen before',
      'Correctly labeled data points that the model misclassifies due to memorization',
    ],
    correctIndex: 0,
    explanation: 'Adding a tiny gradient-aligned perturbation ε·sign(∇_x L) to a panda image can make a ResNet classify it as a "gibbon" with 99.9% confidence while humans see no difference. This reveals deep learning\'s brittle pattern matching.',
    realWorld: 'Adversarial examples affect self-driving car perception (stop sign → yield sign with stickers), face recognition, malware detection, and medical imaging. Adversarial robustness is a critical safety concern for deployed AI.',
    hint: 'Move the pixel values in the direction that maximizes the loss — even tiny steps can completely fool the classifier.',
  },
  {
    id: 11905,
    topic: 'goodfellow',
    difficulty: 'hard',
    question: 'The Fast Gradient Sign Method (FGSM) for generating adversarial examples computes:',
    options: [
      '$x_{adv} = x + \\epsilon \\cdot \\text{sign}(\\nabla_x J(\\theta, x, y))$',
      '$x_{adv} = x - \\epsilon \\cdot \\nabla_x J(\\theta, x, y)$',
      '$x_{adv} = \\text{clip}(x + \\epsilon \\cdot \\nabla_\\theta J(\\theta, x, y))$',
      '$x_{adv} = x \\cdot (1 + \\epsilon \\cdot \\text{sign}(x))$',
    ],
    correctIndex: 0,
    explanation: 'FGSM takes one gradient step in the sign direction of the loss gradient w.r.t. the input. The sign() function ensures each pixel is perturbed by exactly ε in the direction that increases loss most.',
    realWorld: 'FGSM-generated adversarial examples are used for adversarial training: adding them to the training set (Goodfellow et al. 2014) improves robustness but at the cost of clean accuracy.',
    hint: 'Not gradient descent on parameters θ — gradient ascent on the input x to maximize the loss.',
  },
  {
    id: 11906,
    topic: 'goodfellow',
    difficulty: 'hard',
    question: 'Mode collapse in GAN training occurs when the generator:',
    options: [
      'Learns to produce only a few high-quality samples that fool D, ignoring most of the data distribution',
      'Generates samples that are blurry because MSE loss averages multiple modes',
      'Produces the same sample regardless of the noise input z',
      'Exactly memorizes training samples with zero generalization to new images',
    ],
    correctIndex: 0,
    explanation: 'If G finds a few samples that fool D perfectly, it has no incentive to diversify. D adapts to reject these, G finds new fooling samples — but diversity collapses to a cycle between a few modes rather than covering all of p_data.',
    realWorld: 'Mode collapse produces GANs that generate only a few classes of faces or only certain drug molecules. Minibatch discrimination, Wasserstein distance, and unrolled GANs address this diversity failure.',
    hint: 'If generating "5" always fools the discriminator, why generate anything else? The incentive for diversity disappears.',
  },
  {
    id: 11907,
    topic: 'goodfellow',
    difficulty: 'hard',
    question: 'Conditional GANs (cGANs) extend standard GANs by:',
    options: [
      'Conditioning both G and D on auxiliary information $y$ (class labels, text, image) enabling controlled generation',
      'Conditioning the training on a validation set to prevent overfitting of the generator',
      'Conditioning the noise vector $z$ to follow the data distribution rather than Gaussian',
      'Adding a classification head to D that conditions on the generator\'s uncertainty',
    ],
    correctIndex: 0,
    explanation: 'cGAN: G(z,y) generates samples conditioned on y; D(x,y) discriminates real/fake conditioned on y. This enables text-to-image generation, image-to-image translation (pix2pix), and class-conditional synthesis.',
    realWorld: 'pix2pix (conditional image translation), SPADE (semantic image synthesis), and most modern text-to-image systems are conditional GANs or descendants — Goodfellow\'s conditioning idea scales to GPT-4V and DALL-E.',
    hint: 'Feed the class label (or text description) to both G and D — now the GAN knows what it should generate.',
  },
  {
    id: 11908,
    topic: 'goodfellow',
    difficulty: 'sota',
    question: 'The Wasserstein GAN (WGAN) replaces the JS divergence with the Earth Mover\'s Distance. The WGAN objective is:',
    options: [
      '$\\min_G \\max_{D: \\|D\\|_L \\leq 1} \\mathbb{E}_{x}[D(x)] - \\mathbb{E}_z[D(G(z))]$',
      '$\\min_G \\max_D \\mathbb{E}_x[\\log D(x)] + \\mathbb{E}_z[\\log(1-D(G(z)))]$',
      '$\\min_G \\max_D \\mathbb{E}_x[D(x)^2] + \\mathbb{E}_z[(1-D(G(z)))^2]$',
      '$\\min_G D_{KL}(p_G \\| p_{data}) + D_{KL}(p_{data} \\| p_G)$',
    ],
    correctIndex: 0,
    explanation: 'The discriminator D is constrained to be 1-Lipschitz (via weight clipping or gradient penalty). This gives a meaningful gradient even when p_G and p_data are disjoint — solving the vanishing gradient problem of original GANs.',
    realWorld: 'WGAN-GP (Gradient Penalty) is the standard stable GAN training recipe. It enables training on small datasets, diverse outputs, and serves as the foundation for progressive GAN, StyleGAN, and BigGAN.',
    hint: 'Earth Mover\'s Distance = minimum "work" to transport p_G onto p_data — always finite and differentiable, unlike JS divergence.',
  },
  {
    id: 11909,
    topic: 'goodfellow',
    difficulty: 'sota',
    question: 'Adversarial training for robustness (Madry et al., building on Goodfellow) solves the min-max problem:',
    options: [
      '$\\min_\\theta \\mathbb{E}_{(x,y)}[\\max_{\\delta \\in \\mathcal{S}} L(f_\\theta(x+\\delta), y)]$',
      '$\\min_\\theta \\max_{\\theta\'} \\mathbb{E}[(f_\\theta(x) - f_{\\theta\'}(x))^2]$',
      '$\\min_{\\delta} \\max_\\theta L(f_\\theta(x+\\delta), y)$',
      '$\\min_\\theta \\mathbb{E}[L(f_\\theta(x), y)] + \\lambda \\max_\\delta \\|\\nabla_x L\\|$',
    ],
    correctIndex: 0,
    explanation: 'Adversarial training minimizes the worst-case loss over the perturbation set S (typically L∞ ball of radius ε). The inner maximization (finding the worst perturbation) is solved approximately with PGD — projected gradient ascent.',
    realWorld: 'Adversarially trained models are deployed in safety-critical applications (autonomous vehicles, medical AI) where certified robustness to small perturbations is required. PGD adversarial training remains the strongest empirical defense.',
    hint: 'Train on worst-case inputs within perturbation budget S — minimize the maximum possible loss an adversary can cause.',
  },
  {
    id: 11910,
    topic: 'goodfellow',
    difficulty: 'sota',
    question: 'Goodfellow\'s work on "Maxout Networks" introduced activations of the form $h_i(x) = \\max_{j \\in [k]} z_{ij}$. Their key theoretical property is:',
    options: [
      'They can approximate any convex function and implement dropout efficiently as model averaging',
      'They have zero-gradient regions that naturally prune inactive neurons',
      'They are the only smooth activations that satisfy the universal approximation theorem',
      'They eliminate the vanishing gradient problem by having gradient exactly 1 everywhere',
    ],
    correctIndex: 0,
    explanation: 'Maxout is a piecewise-linear function whose pieces are determined by which unit wins the max. It can approximate any convex function and is equivalent to averaging an exponential number of linear networks — making dropout (dropping units) equivalent to model averaging.',
    realWorld: 'Maxout networks achieved state-of-art on CIFAR-10, MNIST, and SVHN in 2013. The piecewise-linear insight influenced ReLU variants (Leaky ReLU, PReLU) and modern activation design principles.',
    hint: 'max(W₁ᵀx+b₁, W₂ᵀx+b₂) is piecewise linear — can any piecewise linear function be written as a max of affine functions?',
  },
];
