import type { Question } from '../types';

export const perelmanQuestions: Question[] = [
  {
    id: 21000,
    topic: 'grigori-perelman',
    difficulty: 'sota',
    question: 'Perelman\'s proof of the Poincaré Conjecture relies on which geometric flow?',
    options: ['Ricci flow with surgery', 'Mean curvature flow', 'Yamabe flow', 'Kähler–Ricci flow'],
    correctIndex: 0,
    explanation: 'Perelman extended Hamilton\'s Ricci flow program by introducing surgery techniques to handle singularities, proving Thurston\'s Geometrization Conjecture (which implies Poincaré).',
    realWorld: 'Ricci flow is now used in image processing and mesh smoothing in computer graphics.',
    hint: 'Think of a PDE that smoothly deforms the metric of a manifold toward uniform curvature.',
  },
  {
    id: 21001,
    topic: 'grigori-perelman',
    difficulty: 'sota',
    question: 'The Poincaré Conjecture states that every simply connected, closed 3-manifold is homeomorphic to which object?',
    options: ['The 3-sphere $S^3$', 'The 3-torus $T^3$', 'Real projective space $\\mathbb{R}P^3$', 'The Poincaré homology sphere'],
    correctIndex: 0,
    explanation: 'The conjecture asserts that the 3-sphere is the only simply connected closed 3-manifold, up to homeomorphism.',
    realWorld: 'Understanding the topology of 3-manifolds is fundamental to cosmological models of the shape of the universe.',
    hint: 'Simply connected means every loop can be continuously shrunk to a point.',
  },
  {
    id: 21002,
    topic: 'grigori-perelman',
    difficulty: 'sota',
    question: 'Perelman introduced which key monotonic quantity to control Ricci flow singularities?',
    options: ['The $\\mathcal{W}$-entropy functional', 'The Boltzmann entropy', 'The Yang–Mills action', 'The Dirichlet energy'],
    correctIndex: 0,
    explanation: 'Perelman\'s $\\mathcal{W}$-entropy (and the related $\\mathcal{F}$-functional) provided crucial monotonicity formulas that rule out collapsing and control the long-time behavior of Ricci flow.',
    realWorld: 'These entropy functionals connect geometric analysis to statistical mechanics and information theory.',
    hint: 'It is a logarithmic Sobolev-type functional that is monotonically non-decreasing under the flow.',
  },
  {
    id: 21003,
    topic: 'grigori-perelman',
    difficulty: 'sota',
    question: 'Perelman\'s work proves which broader conjecture that classifies all compact 3-manifolds?',
    options: ['Thurston\'s Geometrization Conjecture', 'The Borel Conjecture', 'The Virtual Haken Conjecture', 'The Novikov Conjecture'],
    correctIndex: 0,
    explanation: 'Thurston\'s Geometrization Conjecture states that every closed 3-manifold can be decomposed into pieces that each admit one of eight geometric structures. The Poincaré Conjecture is a special case.',
    realWorld: 'Geometrization provides a complete "periodic table" for 3-dimensional spaces.',
    hint: 'This conjecture generalizes Poincaré and involves eight model geometries.',
  },
  {
    id: 21004,
    topic: 'grigori-perelman',
    difficulty: 'sota',
    question: 'What is the total prize money Perelman declined for his proof of the Poincaré Conjecture?',
    options: ['$1,000,000 (Clay Millennium Prize)', '$500,000 (Abel Prize)', '$250,000 (Breakthrough Prize)', '$15,000 (Fields Medal)'],
    correctIndex: 0,
    explanation: 'Perelman declined both the Fields Medal (2006) and the Clay Millennium Prize ($1M, 2010), saying "the prize is irrelevant" since his proof was correct.',
    realWorld: 'The Clay Millennium Problems remain one of the most famous open challenges in mathematics, with six still unsolved.',
    hint: 'The Clay Mathematics Institute offered the largest single mathematical prize.',
  },
];
