import type { Question } from '../types';

export const henriPoincareQuestions: Question[] = [
  {
    id: 10031,
    topic: 'henri-poincare',
    difficulty: 'easy',
    question: 'In topology, two spaces are considered equivalent if they are:',
    options: [
      'Homeomorphic — related by a continuous bijection with continuous inverse',
      'Isometric — having the same distances between all points',
      'Diffeomorphic — related by a smooth invertible map',
      'Homotopic — connected by a continuous deformation without inversion',
    ],
    correctIndex: 0,
    explanation: 'Topology studies properties preserved under homeomorphisms (continuous deformations that can stretch and bend but not tear or glue). A donut and a coffee mug are homeomorphic — both have exactly one hole.',
    realWorld: 'Topological data analysis (TDA) uses these ideas to find "shape" in high-dimensional datasets, revealing clusters and loops in data manifolds.',
    hint: 'In topology, a donut and a teacup are the same — both have one hole.',
  },
  {
    id: 10032,
    topic: 'henri-poincare',
    difficulty: 'easy',
    question: 'The Poincaré Conjecture (proved by Perelman 2003) states:',
    options: [
      'Every simply connected closed 3-manifold is homeomorphic to the 3-sphere $S^3$',
      'Every compact manifold admits a metric of constant curvature',
      'Every continuous function on a sphere has a fixed point',
      'The fundamental group of any compact manifold is finite',
    ],
    correctIndex: 0,
    explanation: 'Simply connected means every loop can be contracted to a point. Poincaré conjectured (1904) that in 3D, this implies the space is a 3-sphere. Perelman proved it in 2003 using Ricci flow with surgery — the only Millennium Prize solved.',
    realWorld: 'The conjecture asks: if a 3D universe has no holes, must it be spherical? Relevant to cosmologists modeling the shape of the universe.',
    hint: 'No holes = sphere in 3D. Simple in 2D (sphere), fiendishly hard in 3D.',
  },
  {
    id: 10033,
    topic: 'henri-poincare',
    difficulty: 'easy',
    question: 'Poincaré\'s discovery of chaos arose from studying:',
    options: [
      'The three-body problem — he found that even simple gravitational systems can have unpredictable trajectories',
      'Heat diffusion equations with nonlinear boundary conditions',
      'The stability of electrical circuits with feedback',
      'Random walks on graph structures',
    ],
    correctIndex: 0,
    explanation: 'While studying whether the solar system is stable, Poincaré (1890) discovered that the three-body problem has no general closed-form solution and tiny perturbations can lead to wildly different trajectories — the seed of chaos theory.',
    realWorld: 'Weather prediction is limited by this sensitivity — the "butterfly effect" — making forecasts beyond ~10 days fundamentally uncertain.',
    hint: 'Three gravitating bodies create complexity that two bodies don\'t — the solar system could be chaotic.',
  },
  {
    id: 10034,
    topic: 'henri-poincare',
    difficulty: 'easy',
    question: 'A manifold is a mathematical space that:',
    options: [
      'Locally resembles Euclidean space $\\mathbb{R}^n$ near every point',
      'Has constant curvature everywhere',
      'Embeds in at most $2n$ dimensions by Whitney\'s theorem',
      'Admits a global coordinate system',
    ],
    correctIndex: 0,
    explanation: 'A manifold locally looks flat (Euclidean) even if globally curved or twisted. Earth\'s surface is a 2-manifold — locally it looks flat, globally it\'s a sphere.',
    realWorld: 'In machine learning, the "manifold hypothesis" states that high-dimensional data (images, text) lies on a low-dimensional manifold — the basis of dimensionality reduction and generative models.',
    hint: 'Think of Earth\'s surface: locally flat (your yard), globally round.',
  },
  {
    id: 10035,
    topic: 'henri-poincare',
    difficulty: 'hard',
    question: 'The Euler characteristic $\\chi$ of a surface satisfies $\\chi = V - E + F$. For a sphere, $\\chi = 2$; for a torus, $\\chi = 0$. What does this classify?',
    options: [
      'The topological type of a closed orientable surface — genus $g$ surfaces have $\\chi = 2 - 2g$',
      'The number of holes that can be drilled through the surface',
      'The minimum number of colors needed to color a map on the surface',
      'The dimension of the surface\'s homology group $H_1$',
    ],
    correctIndex: 0,
    explanation: 'The Euler characteristic is a topological invariant. For orientable closed surfaces, $\\chi = 2-2g$ where $g$ is the genus (number of handles). Sphere: $g=0, \\chi=2$. Torus: $g=1, \\chi=0$. This completely classifies 2-manifolds.',
    realWorld: 'Persistent homology (TDA) computes topological invariants like $\\chi$ to classify and compare data manifold shapes robustly.',
    hint: 'Genus counts "handles" or "holes through" the surface. Each handle decreases $\\chi$ by 2.',
  },
  {
    id: 10036,
    topic: 'henri-poincare',
    difficulty: 'hard',
    question: 'Poincaré\'s recurrence theorem states: for a measure-preserving dynamical system with finite measure, almost every point:',
    options: [
      'Returns arbitrarily close to its initial state infinitely often',
      'Converges to a fixed point attractor after sufficient time',
      'Diverges to infinity at an exponential rate',
      'Follows a periodic orbit with period bounded by the system\'s entropy',
    ],
    correctIndex: 0,
    explanation: 'For a Hamiltonian system with finite phase-space volume, almost every trajectory returns infinitely often to any neighborhood of its starting point. This seems to contradict thermodynamic irreversibility (the Zermelo paradox).',
    realWorld: 'The recurrence time for macroscopic systems (like a room of gas) is astronomically long — longer than the universe\'s age — resolving the paradox practically.',
    hint: 'Finite space + measure preservation = almost every orbit must come back.',
  },
  {
    id: 10037,
    topic: 'henri-poincare',
    difficulty: 'hard',
    question: 'In dynamical systems, a Poincaré section (or map) is used to:',
    options: [
      'Reduce a continuous flow to a discrete map by recording intersections with a transversal surface',
      'Compute Lyapunov exponents from time series data',
      'Decompose a chaotic attractor into Fourier modes',
      'Calculate the period of a limit cycle exactly',
    ],
    correctIndex: 0,
    explanation: 'A Poincaré section intersects the trajectory at a lower-dimensional surface, converting the continuous ODE into a discrete map. Fixed points of the map correspond to periodic orbits; the structure of the map reveals chaos.',
    realWorld: 'Used to analyze heart rhythm dynamics — ventricular fibrillation appears as chaos in the cardiac Poincaré map.',
    hint: 'Slice through the flow to get a sequence of points — study the sequence instead of the continuous flow.',
  },
  {
    id: 10038,
    topic: 'henri-poincare',
    difficulty: 'sota',
    question: 'The manifold hypothesis in deep learning posits that data lives on a low-dimensional manifold $\\mathcal{M} \\subset \\mathbb{R}^D$. A key implication for generative models is:',
    options: [
      'The generator need only learn a mapping from a low-dimensional latent space to the manifold, not the full ambient space',
      'Classification boundaries must be linear to respect the manifold structure',
      'Generative models cannot extrapolate beyond the training manifold by definition',
      'The intrinsic dimension equals the embedding dimension when the manifold is flat',
    ],
    correctIndex: 0,
    explanation: 'If images lie on a $d$-dimensional manifold embedded in $\\mathbb{R}^D$ with $d \\ll D$, a generative model only needs to parameterize $d$-dimensional structure. GANs and VAEs exploit this by mapping from $\\mathbb{R}^d$ latent codes to data space.',
    realWorld: 'A face image has ~$10^6$ pixels but the face manifold has ~50-100 intrinsic dimensions (pose, lighting, identity attributes).',
    hint: 'High-dimensional data has low-dimensional structure — learn to navigate the manifold, not the full space.',
  },
  {
    id: 10039,
    topic: 'henri-poincare',
    difficulty: 'sota',
    question: 'Lyapunov exponents characterize chaos by measuring:',
    options: [
      'The exponential rate of divergence of initially nearby trajectories: $|\\delta x(t)| \\approx e^{\\lambda t}|\\delta x(0)|$',
      'The fractal dimension of a strange attractor',
      'The average period of unstable periodic orbits in the attractor',
      'The entropy production rate of a Hamiltonian system',
    ],
    correctIndex: 0,
    explanation: 'A positive maximal Lyapunov exponent $\\lambda > 0$ signals chaos — nearby trajectories separate exponentially. This quantifies the "butterfly effect" and sets the horizon beyond which prediction is impossible: $t_{pred} \\sim \\lambda^{-1} \\ln(\\delta_{tolerance}/\\delta_0)$.',
    realWorld: 'Weather models estimate $\\lambda^{-1} \\approx 5$ days — meaning predictability doubles with each additional order of magnitude improvement in initial measurements.',
    hint: 'Positive Lyapunov = exponential sensitivity = chaos.',
  },
  {
    id: 10040,
    topic: 'henri-poincare',
    difficulty: 'sota',
    question: 'Poincaré duality for a closed orientable $n$-manifold $M$ states:',
    options: [
      '$H^k(M) \\cong H_{n-k}(M)$ — cohomology and homology are mirrored across middle dimension',
      '$\\pi_k(M) \\cong \\pi_{n-k}(M)$ for homotopy groups by Alexander duality',
      '$\\chi(M) = 0$ whenever $n$ is odd',
      '$H^k(M) = 0$ for $k > n/2$ when $M$ admits positive curvature',
    ],
    correctIndex: 0,
    explanation: 'Poincaré duality $H^k(M) \\cong H_{n-k}(M)$ shows deep symmetry in the topology of closed manifolds — $k$-dimensional "holes" pair with $(n-k)$-dimensional "cycles". It is proved using the fundamental class and cap product.',
    realWorld: 'Poincaré duality underlies topological quantum field theory (TQFT) and the index theorem connecting geometry and analysis.',
    hint: 'Holes and cocycles of complementary dimensions are in bijection — the manifold is self-dual.',
  },
];
