import type { Question } from '../types';

export const herbertFrohlichQuestions: Question[] = [
  {
    id: 312001, topic: 'herbert-frohlich', difficulty: 'easy',
    question: 'Herbert Fröhlich\'s most famous prediction (1968) in biological physics was:',
    options: [
      'That metabolic energy could drive biological oscillators into a single coherent quantum mode — a phonon condensate at terahertz frequencies, even at body temperature',
      'That DNA stores quantum information in its base-pair hydrogen bonds',
      'That neurons communicate via quantum tunneling across synaptic clefts',
      'That proteins fold via quantum annealing in their hydrophobic cores',
    ],
    correctIndex: 0,
    explanation: 'Fröhlich proposed that biological macromolecules receiving metabolic energy (e.g., GTP hydrolysis) faster than they dissipate it would channel excess energy into the lowest-frequency collective mode, achieving macroscopic quantum coherence — analogous to a Bose-Einstein condensate but maintained by energy pumping rather than cooling.',
    realWorld: 'Fröhlich condensation is the theoretical foundation for Hameroff\'s claim that microtubules support quantum coherence at 310K.',
    hint: 'Think of a biological laser — energy pumping drives oscillations into one coherent mode.',
    glossaryLinks: ['frohlich-condensate', 'microtubule-quantum-coherence'],
  },
  {
    id: 312002, topic: 'herbert-frohlich', difficulty: 'easy',
    question: 'Before his biological physics work, Fröhlich made foundational contributions to:',
    options: [
      'The theory of superconductivity — his polaron model of electron-phonon coupling influenced the BCS theory',
      'The invention of the scanning tunneling microscope',
      'The discovery of the muon in cosmic ray experiments',
      'The development of nuclear magnetic resonance imaging',
    ],
    correctIndex: 0,
    explanation: 'Fröhlich\'s work on dielectric theory and electron-phonon interactions in the 1950s, particularly his "Fröhlich polaron" and "Fröhlich Hamiltonian," provided key theoretical ingredients that Bardeen, Cooper, and Schrieffer used in formulating BCS theory of superconductivity (1957).',
    realWorld: 'The Fröhlich Hamiltonian $H = \\sum_k \\hbar\\omega_k a_k^\\dagger a_k + \\sum_{k,q} g_{kq}(a_q + a_{-q}^\\dagger) c_k^\\dagger c_{k+q}$ remains central to condensed matter physics.',
    hint: 'His name appears in the theory that won Bardeen, Cooper, and Schrieffer the Nobel Prize.',
  },
  {
    id: 312003, topic: 'herbert-frohlich', difficulty: 'hard',
    question: 'The Fröhlich condensation rate equation $\\dot{n}_s = P_s - \\gamma_s n_s + \\sum_{s\'} \\Phi_{ss\'}(n_s n_{s\'} - n_{s\'} n_s)$ predicts condensation when:',
    options: [
      'The pumping rate $P_s$ exceeds a critical threshold where the nonlinear mode-coupling terms $\\Phi_{ss\'}$ redirect energy from higher modes into the lowest mode, achieving macroscopic occupation',
      'The temperature drops below a critical value $T_c$ determined by the Debye frequency',
      'The damping rate $\\gamma_s$ vanishes identically for all modes',
      'External electromagnetic radiation at the resonant frequency is applied continuously',
    ],
    correctIndex: 0,
    explanation: 'The key insight is the nonlinear $\\Phi_{ss\'}$ coupling: above a critical pumping rate, energy flows preferentially into the lowest-frequency mode. Unlike BEC which requires cooling, Fröhlich condensation is a driven, open-system phenomenon — the biological equivalent of stimulated emission in a laser.',
    realWorld: 'This explains why Bandyopadhyay observes discrete THz resonances in microtubules — the metabolic pumping from GTP hydrolysis drives specific modes above the condensation threshold.',
    hint: 'The condensation is driven by energy pumping, not by cooling — it\'s an open-system phenomenon.',
    glossaryLinks: ['frohlich-condensate'],
  },
  {
    id: 312004, topic: 'herbert-frohlich', difficulty: 'hard',
    question: 'Fröhlich\'s "giant dipole oscillation" model predicts that biological membranes and protein assemblies exhibit:',
    options: [
      'Collective longitudinal vibration modes in the 10¹¹–10¹² Hz (sub-THz to THz) range, where the entire structure oscillates coherently as a single dipole',
      'Ferroelectric phase transitions at cryogenic temperatures',
      'Magnetic monopole excitations at room temperature',
      'Gravitational wave emission from metabolic processes',
    ],
    correctIndex: 0,
    explanation: 'Fröhlich predicted that large biological structures (microtubules, membranes, enzyme complexes) should exhibit coherent oscillations at frequencies $\\omega \\sim 10^{11}$–$10^{12}$ Hz, arising from the collective motion of many dipolar subunits. These "giant dipole oscillations" would be metabolically pumped above the condensation threshold.',
    realWorld: 'The prediction sat untested for decades until modern THz spectroscopy techniques (2010s–2020s) allowed direct measurement of protein vibrations in this frequency range.',
    hint: 'The frequencies are between microwave and infrared — the "THz gap" that was experimentally inaccessible for decades.',
  },
  {
    id: 312005, topic: 'herbert-frohlich', difficulty: 'sota',
    question: 'Fröhlich\'s polaron Hamiltonian $H_F = \\sum_k \\epsilon_k c_k^\\dagger c_k + \\sum_q \\hbar\\omega_q a_q^\\dagger a_q + \\sum_{k,q} g_{kq}(a_q + a_{-q}^\\dagger)c_k^\\dagger c_{k+q}$ describes:',
    options: [
      'An electron coupled to a phonon field via interaction strength $g_{kq}$ — the resulting quasiparticle (polaron) has renormalized mass and energy, foundational to BCS superconductivity',
      'A photon-photon interaction in nonlinear optical media',
      'The coupling between gravitons and matter fields in linearized quantum gravity',
      'The interaction between quarks and gluons in quantum chromodynamics',
    ],
    correctIndex: 0,
    explanation: 'The Fröhlich Hamiltonian captures the essential physics of an electron (fermion operators $c_k$) interacting with lattice vibrations (boson operators $a_q$) through a coupling constant $g_{kq}$ that depends on the material\'s dielectric properties. The electron "dresses" itself with a phonon cloud, forming a polaron with effective mass $m^* > m_e$.',
    realWorld: 'This Hamiltonian is the starting point for BCS theory: Cooper pairing arises from the attractive interaction mediated by virtual phonon exchange in Fröhlich\'s framework.',
    hint: 'The three terms represent: free electrons, free phonons, and their interaction.',
  },
  {
    id: 312006, topic: 'herbert-frohlich', difficulty: 'sota',
    question: 'The connection between Fröhlich\'s biological condensate and Penrose\'s objective reduction is that:',
    options: [
      'Fröhlich condensation provides the mechanism for maintaining quantum coherence in microtubules long enough for the gravitational self-energy $E_G$ to accumulate to $\\hbar/\\tau$, triggering OR collapse at brain-relevant timescales',
      'Fröhlich condensation causes gravitational waves that trigger wavefunction collapse',
      'Penrose used Fröhlich\'s polaron theory to calculate black hole entropy',
      'Both theories predict that consciousness requires temperatures below 4 Kelvin',
    ],
    correctIndex: 0,
    explanation: 'In Orch OR, the "orchestration" comes from Fröhlich condensation: metabolic energy maintains quantum coherence in the tubulin lattice (preventing thermal decoherence) until enough tubulins (~$10^4$–$10^5$) are in superposition that $E_G \\sim \\hbar/(25\\text{ ms})$, triggering Penrose\'s OR collapse — a moment of conscious experience.',
    realWorld: 'Without Fröhlich\'s mechanism, quantum coherence at 310K would decohere in femtoseconds. The condensate extends this to milliseconds — exactly the timescale consciousness operates on.',
    hint: 'Fröhlich keeps the quantum states alive; Penrose collapses them. Together they produce consciousness.',
    glossaryLinks: ['frohlich-condensate', 'objective-reduction', 'orch-or'],
    formulaLinks: ['penrose-or-timescale'],
  },
];
