import type { Question } from '../types';

export const hintonQuestions: Question[] = [
  {
    id: 10001,
    topic: 'hinton',
    difficulty: 'easy',
    question: 'What is backpropagation?',
    options: [
      'An algorithm to propagate errors backward through a network to compute gradients',
      'A technique to initialize neural network weights',
      'A method to regularize deep networks',
      'A forward pass through a recurrent network',
    ],
    correctIndex: 0,
    explanation: 'Backpropagation applies the chain rule of calculus to compute how much each weight contributed to the error, enabling gradient descent to update weights efficiently.',
    realWorld: 'Every modern deep learning framework (PyTorch, TensorFlow) uses backprop to train billions of parameters.',
    hint: 'Think about how errors "travel" from the output layer back to the input layer.',
  },
  {
    id: 10002,
    topic: 'hinton',
    difficulty: 'easy',
    question: 'What does a Restricted Boltzmann Machine (RBM) model?',
    options: [
      'A joint probability distribution over visible and hidden units',
      'A deterministic mapping from inputs to outputs',
      'A Markov chain over time steps',
      'A supervised classification boundary',
    ],
    correctIndex: 0,
    explanation: 'An RBM is an undirected graphical model that learns a probability distribution over its inputs using hidden variables, enabling unsupervised feature learning.',
    realWorld: 'RBMs were used to pre-train deep belief networks before modern initialization techniques, kickstarting the deep learning revolution.',
    hint: 'Consider it as learning what combinations of features are likely to appear together.',
  },
  {
    id: 10003,
    topic: 'hinton',
    difficulty: 'easy',
    question: 'What problem do Capsule Networks (CapsNets) aim to solve that CNNs struggle with?',
    options: [
      'Preserving spatial relationships and pose information between features',
      'Reducing the number of parameters in a network',
      'Training on smaller datasets',
      'Eliminating the need for convolutions',
    ],
    correctIndex: 0,
    explanation: 'CNNs use pooling which discards spatial information. CapsNets use capsules (groups of neurons) whose activity vectors encode both the existence and pose (position, orientation) of features.',
    realWorld: 'A face recognition system needs to know that eyes are above a nose, not just that both exist — that\'s the spatial hierarchy CapsNets preserve.',
    hint: 'Think about what information is lost when you "pool" features in a CNN.',
  },
  {
    id: 10004,
    topic: 'hinton',
    difficulty: 'easy',
    question: 'What does "dropout" do during neural network training?',
    options: [
      'Randomly sets neuron outputs to zero to prevent co-adaptation',
      'Reduces the learning rate when loss plateaus',
      'Clips gradients to prevent explosion',
      'Normalizes layer activations to unit variance',
    ],
    correctIndex: 0,
    explanation: 'Dropout (Hinton et al., 2012) randomly deactivates neurons during training, forcing the network to learn redundant representations and acting as a powerful regularizer.',
    realWorld: 'Dropout is the most widely used regularization trick in deep learning and remains standard in vision and NLP models.',
    hint: 'It forces the network to not rely on any single neuron — think ensemble of sub-networks.',
  },
  {
    id: 10005,
    topic: 'hinton',
    difficulty: 'hard',
    question: 'In backpropagation, the gradient of the loss $L$ w.r.t. weight $w_{ij}^{(l)}$ is:',
    options: [
      '$\\frac{\\partial L}{\\partial w_{ij}^{(l)}} = \\delta_j^{(l)} \\cdot a_i^{(l-1)}$',
      '$\\frac{\\partial L}{\\partial w_{ij}^{(l)}} = a_j^{(l)} \\cdot \\delta_i^{(l-1)}$',
      '$\\frac{\\partial L}{\\partial w_{ij}^{(l)}} = \\delta_j^{(l)} + a_i^{(l-1)}$',
      '$\\frac{\\partial L}{\\partial w_{ij}^{(l)}} = \\nabla L \\cdot w_{ij}^{(l)}$',
    ],
    correctIndex: 0,
    explanation: 'The weight gradient is the product of the error signal (delta) at the post-synaptic neuron $j$ in layer $l$ and the activation of the pre-synaptic neuron $i$ from layer $l-1$. This is the outer-product rule that makes backprop efficient.',
    realWorld: 'This formula is directly what PyTorch autograd computes internally for every linear layer.',
    hint: 'The chain rule gives: upstream gradient (delta) × local input (activation from previous layer).',
  },
  {
    id: 10006,
    topic: 'hinton',
    difficulty: 'hard',
    question: 'Contrastive Divergence (CD-k) in training RBMs approximates:',
    options: [
      'The gradient of the log-likelihood by running k steps of Gibbs sampling from the data',
      'The KL divergence between prior and posterior distributions',
      'The gradient of the variational lower bound',
      'The Fisher information matrix diagonal',
    ],
    correctIndex: 0,
    explanation: 'Exact maximum likelihood for RBMs requires computing an intractable partition function. CD-k approximates the negative phase gradient using k steps of Gibbs sampling starting from training data rather than random noise.',
    realWorld: 'CD-1 (one Gibbs step) was sufficient to train useful RBMs for collaborative filtering and speech recognition pre-training.',
    hint: 'The "positive phase" clamps data; the "negative phase" needs sampling — CD approximates that sampling.',
  },
  {
    id: 10007,
    topic: 'hinton',
    difficulty: 'hard',
    question: 'In CapsNets, "dynamic routing by agreement" determines:',
    options: [
      'How much each lower-level capsule contributes to each higher-level capsule based on prediction consistency',
      'The learning rate schedule for capsule weight updates',
      'Which capsules to dropout during training',
      'The activation function used inside each capsule',
    ],
    correctIndex: 0,
    explanation: 'Dynamic routing iteratively adjusts coupling coefficients $c_{ij}$ so capsule $i$ routes more of its output to capsule $j$ when capsule $i$\'s prediction for $j$ agrees with $j$\'s actual value. This replaces max-pooling with a vote-based consensus.',
    realWorld: 'This mimics how the brain\'s visual cortex hierarchically combines evidence — a horizontal edge and vertical edge "agree" they form a corner.',
    hint: 'Capsules vote for what higher-level entity they belong to — routing is the counting of votes.',
  },
  {
    id: 10008,
    topic: 'hinton',
    difficulty: 'sota',
    question: 'A Deep Belief Network (DBN) is trained greedily by treating each pair of layers as an RBM. What property makes this greedy training principled?',
    options: [
      'Each RBM layer improves a variational lower bound on the log probability of the data',
      'Each RBM layer minimizes cross-entropy independently',
      'Each RBM layer is a sufficient statistic for the next layer',
      'The RBM weights form an orthonormal basis by construction',
    ],
    correctIndex: 0,
    explanation: 'Hinton et al. 2006 proved that training each layer as an RBM while keeping lower layers fixed always improves a variational lower bound on $\\log P(\\mathbf{v})$. This theoretical guarantee justified the greedy layer-wise pre-training strategy.',
    realWorld: 'This 2006 Science paper restarted the field of deep learning after a decade of neural network winter.',
    hint: 'Think of the variational bound — adding a layer can only improve the approximation, never worsen it.',
  },
  {
    id: 10009,
    topic: 'hinton',
    difficulty: 'sota',
    question: 'The "vanishing gradient" problem in deep networks occurs because:',
    options: [
      'Repeated multiplication of Jacobians with singular values < 1 shrinks gradients exponentially with depth',
      'The learning rate decays too quickly during training',
      'Batch normalization removes gradient information between layers',
      'Weight matrices become too large and dominate the signal',
    ],
    correctIndex: 0,
    explanation: 'In backprop, gradients are products of Jacobian matrices across layers. If those Jacobians have spectral radius < 1 (e.g., saturating sigmoids), the gradient norm decays exponentially, making it nearly impossible to train early layers.',
    realWorld: 'This motivated ReLU activations, residual connections (ResNets), and careful weight initialization — all of which ensure gradient flow across hundreds of layers.',
    hint: 'Consider what happens when you multiply 100 numbers each slightly less than 1 together.',
  },
  {
    id: 10010,
    topic: 'hinton',
    difficulty: 'sota',
    question: 'Hinton\'s "Mortal Computation" critique of backpropagation argues that:',
    options: [
      'Backprop requires identical forward and backward weights, which is biologically implausible and limits distributed learning',
      'Backpropagation cannot be parallelized across multiple GPUs efficiently',
      'Gradient descent always converges to sharp minima with poor generalization',
      'The chain rule approximation breaks down for networks deeper than 100 layers',
    ],
    correctIndex: 0,
    explanation: 'Hinton (2022) argues the "weight transport problem" — backprop needs exact transposes of forward weights — makes it incompatible with biological neurons and hardware systems where knowledge cannot be copied between units.',
    realWorld: 'This motivated alternatives like Forward-Forward Algorithm and local learning rules that could enable truly distributed AI systems.',
    hint: 'Real neurons don\'t share weights — when a signal goes forward, nothing forces the backward signal to use the same connections.',
  },
];
