import type { Question } from '../types';

export const hodgkinHuxleyQuestions: Question[] = [
  {
    id: 97140, topic: 'hodgkin-huxley', difficulty: 'easy',
    question: 'Hodgkin and Huxley\'s Nobel Prize-winning work on the giant squid axon revealed that:',
    options: ['Action potentials are generated by sequential opening of voltage-gated Na⁺ channels (depolarization) followed by K⁺ channels (repolarization)', 'Nerves transmit signals hydraulically through fluid', 'Action potentials travel at the speed of light', 'Only calcium channels are involved in nerve signaling'],
    correctIndex: 0,
    explanation: 'Using voltage clamp on squid giant axon (~1 mm diameter), they measured ionic currents: fast inward Na⁺ current (depolarization) followed by delayed outward K⁺ current (repolarization), producing the ~1 ms action potential.',
    realWorld: 'Their model predicted that blocking Na⁺ channels would prevent action potentials — the mechanism of local anesthetics (lidocaine) and antiepileptics.',
    hint: 'Sodium rushes in, then potassium flows out — that\'s the spike.',
  },
  {
    id: 97141, topic: 'hodgkin-huxley', difficulty: 'hard',
    question: 'The Hodgkin-Huxley model describes membrane current as:',
    options: ['$I = C_m \\frac{dV}{dt} + \\bar{g}_{Na} m^3 h (V - E_{Na}) + \\bar{g}_K n^4 (V - E_K) + g_L (V - E_L)$, with gating variables $m, h, n$ following first-order kinetics', '$I = V/R$ (simple Ohm\'s law)', '$I = C \\frac{dV}{dt}$ (pure capacitor)', '$I = g(V - E)$ (single conductance)'],
    correctIndex: 0,
    explanation: 'Four coupled ODEs: $m^3h$ gates Na⁺ (3 activation, 1 inactivation), $n^4$ gates K⁺ (4 activation). Each gating variable: $\\frac{dx}{dt} = \\alpha_x(V)(1-x) - \\beta_x(V)x$. Nernst potentials: $E_{Na} \\approx +50$ mV, $E_K \\approx -77$ mV.',
    realWorld: 'The HH model was the first biophysical computation — solved on a hand-cranked calculator in 1952, it launched computational neuroscience.',
    hint: 'Four differential equations, three gating variables, two major ion channels.',
  },
  {
    id: 97142, topic: 'hodgkin-huxley', difficulty: 'sota',
    question: 'The Hodgkin-Huxley model predicts action potential conduction velocity. For unmyelinated axons:',
    options: ['$v \\propto \\sqrt{d}$, where $d$ is axon diameter — explaining why squid giant axons evolved large diameters (~1 mm) for fast escape responses', '$v \\propto d^2$ (quadratic dependence)', '$v$ is independent of diameter', '$v \\propto 1/d$ (inverse relationship)'],
    correctIndex: 0,
    explanation: 'Cable theory: $v = \\frac{1}{\\sqrt{r_i c_m}} \\propto \\sqrt{d}$. Internal resistance $r_i \\propto 1/d^2$, membrane capacitance $c_m \\propto d$. Myelination changes this to $v \\propto d$ (linear), enabling thin fast axons.',
    realWorld: 'This explains why myelination was an evolutionary breakthrough: a 10 μm myelinated axon conducts as fast as a 500 μm unmyelinated one, enabling complex vertebrate nervous systems.',
    hint: 'Double the diameter, get ~1.4× the speed — square root relationship.',
  },
];
