import type { Question } from '../types';

export const farmerQuestions: Question[] = [
  {
    id: 21150,
    topic: 'j-doyne-farmer',
    difficulty: 'sota',
    question: 'J. Doyne Farmer\'s "Eudaemonic Enterprises" group used physics to beat which casino game in the 1970s?',
    options: ['Roulette — using a wearable computer hidden in a shoe', 'Blackjack — using card counting', 'Craps — predicting dice outcomes', 'Poker — using game theory optimal play'],
    correctIndex: 0,
    explanation: 'Farmer and Norman Packard built a toe-operated wearable computer that modeled the physics of the roulette ball and wheel in real time, achieving a ~20% edge over the house.',
    realWorld: 'This was one of the first wearable computers ever built, predating smartwatches by decades.',
    hint: 'They literally wore the computer on their body inside the casino.',
  },
  {
    id: 21151,
    topic: 'j-doyne-farmer',
    difficulty: 'sota',
    question: 'Farmer\'s agent-based models of financial markets challenge the efficient market hypothesis by demonstrating what?',
    options: ['Realistic market dynamics (bubbles, crashes, fat tails) emerge from heterogeneous interacting agents', 'Markets always converge to fundamental value', 'A single representative agent can explain all price dynamics', 'Technical analysis is always profitable'],
    correctIndex: 0,
    explanation: 'By simulating markets with diverse agents using different strategies, Farmer showed that realistic statistical features (volatility clustering, power-law returns, bubbles) emerge naturally — without requiring irrational agents.',
    realWorld: 'Agent-based models are now used by central banks and regulators to stress-test financial systems.',
    hint: 'Complexity emerges from the interaction of many simple agents, not from individual irrationality.',
  },
  {
    id: 21152,
    topic: 'j-doyne-farmer',
    difficulty: 'sota',
    question: 'Farmer\'s work on technological progress uses which mathematical framework to predict how costs decrease over time?',
    options: ['Wright\'s Law (power-law learning curves)', 'Moore\'s Law (exponential transistor scaling)', 'Metcalfe\'s Law (network value scaling)', 'Kaldor\'s growth facts'],
    correctIndex: 0,
    explanation: 'Farmer showed that Wright\'s Law — where costs decrease as a power law of cumulative production — provides more accurate and generalizable predictions of technological improvement than Moore\'s Law.',
    realWorld: 'His team used this framework to accurately forecast the dramatic cost decline of solar energy years in advance.',
    hint: 'Cost decreases as a function of cumulative experience, not just time.',
  },
  {
    id: 21153,
    topic: 'j-doyne-farmer',
    difficulty: 'sota',
    question: 'Farmer co-founded which pioneering quantitative trading firm in the 1990s?',
    options: ['Prediction Company', 'Renaissance Technologies', 'D.E. Shaw', 'Two Sigma'],
    correctIndex: 0,
    explanation: 'Farmer and Packard founded Prediction Company in 1991, applying chaos theory and machine learning to financial markets. It was acquired by UBS in 2005.',
    realWorld: 'Prediction Company was one of the earliest systematic trading firms, predating the modern quant hedge fund era.',
    hint: 'The name reflects their goal of forecasting market movements using physics.',
  },
  {
    id: 21154,
    topic: 'j-doyne-farmer',
    difficulty: 'sota',
    question: 'Farmer\'s concept of "market ecology" draws an analogy between trading strategies and which biological concept?',
    options: ['Species competing for resources in an ecosystem', 'Genetic mutation and natural selection', 'Symbiotic relationships between organisms', 'Predator-prey population dynamics'],
    correctIndex: 0,
    explanation: 'Farmer models different trading strategies as species competing for profit (resources). When one strategy becomes crowded, its returns diminish — just as overpopulation depletes an ecological niche.',
    realWorld: 'This framework explains why profitable strategies decay over time as more capital flows into them.',
    hint: 'Strategies fill niches and compete, just like species in an ecosystem.',
  },
];
