import type { Question } from '../types';

export const jRobertOppenheimerQuestions: Question[] = [
  {
    id: 21100,
    topic: 'j-robert-oppenheimer',
    difficulty: 'sota',
    question: 'Oppenheimer\'s early theoretical work on gravitational collapse predicted which astrophysical phenomenon decades before observational confirmation?',
    options: ['Black holes (Oppenheimer–Snyder collapse)', 'Neutron stars only', 'Gravitational lensing', 'Dark matter halos'],
    correctIndex: 0,
    explanation: 'The 1939 Oppenheimer–Snyder paper showed that a sufficiently massive star collapses indefinitely past its Schwarzschild radius, predicting what we now call black holes — decades before the term was coined.',
    realWorld: 'The Event Horizon Telescope\'s 2019 image of M87* confirmed the predictions of gravitational collapse theory.',
    hint: 'His paper with Snyder described matter collapsing past a critical radius from which light cannot escape.',
  },
  {
    id: 21101,
    topic: 'j-robert-oppenheimer',
    difficulty: 'sota',
    question: 'The Born–Oppenheimer approximation simplifies molecular quantum mechanics by separating which two types of motion?',
    options: ['Nuclear and electronic motion', 'Translational and rotational motion', 'Vibrational and electronic motion', 'Spin and orbital motion'],
    correctIndex: 0,
    explanation: 'Because nuclei are thousands of times heavier than electrons, the approximation treats nuclear positions as fixed when solving for electronic wavefunctions, dramatically simplifying molecular calculations.',
    realWorld: 'Virtually all computational chemistry and drug design relies on this approximation as a starting point.',
    hint: 'Heavy particles move slowly; light particles adjust instantaneously.',
  },
  {
    id: 21102,
    topic: 'j-robert-oppenheimer',
    difficulty: 'sota',
    question: 'What was the codename of the first nuclear weapons test, directed by Oppenheimer in July 1945?',
    options: ['Trinity', 'Manhattan', 'Fat Man', 'Crossroads'],
    correctIndex: 0,
    explanation: 'The Trinity test on July 16, 1945 in New Mexico was the first detonation of a nuclear weapon. Oppenheimer named it after a John Donne poem.',
    realWorld: 'Trinity proved that nuclear fission could be weaponized, ushering in the atomic age and the Cold War arms race.',
    hint: 'Oppenheimer named it after a metaphysical poem about three-in-one.',
  },
  {
    id: 21103,
    topic: 'j-robert-oppenheimer',
    difficulty: 'sota',
    question: 'Oppenheimer\'s security clearance was revoked in 1954 primarily due to his opposition to developing which weapon?',
    options: ['The hydrogen bomb (thermonuclear weapon)', 'Tactical nuclear weapons', 'Biological weapons', 'Chemical weapons'],
    correctIndex: 0,
    explanation: 'Oppenheimer opposed the "Super" (hydrogen bomb) on both moral and technical grounds. Edward Teller and others pushed for it, and Oppenheimer\'s opposition was used against him during the McCarthy-era security hearings.',
    realWorld: 'His clearance was posthumously restored by the U.S. government in 2022, acknowledging the hearings were a miscarriage of justice.',
    hint: 'This weapon uses fusion rather than fission and is orders of magnitude more powerful.',
  },
  {
    id: 21104,
    topic: 'j-robert-oppenheimer',
    difficulty: 'sota',
    question: 'The Oppenheimer–Phillips process describes which nuclear reaction mechanism?',
    options: ['Deuteron stripping — where only the neutron is captured by the target nucleus', 'Complete fusion of two heavy nuclei', 'Beta decay of unstable isotopes', 'Neutron capture followed by gamma emission'],
    correctIndex: 0,
    explanation: 'Oppenheimer and Phillips explained why deuterons can induce nuclear reactions at lower energies than expected: the loosely bound deuteron\'s neutron is stripped and captured while the proton is repelled by Coulomb forces.',
    realWorld: 'Deuteron stripping reactions are used in nuclear physics experiments and isotope production for medical imaging.',
    hint: 'The deuteron\'s two nucleons have different fates when approaching a target nucleus.',
  },
];
