import type { Question } from '../types';

export const jacobBekensteinQuestions: Question[] = [
  {
    id: 310001, topic: 'jacob-bekenstein', difficulty: 'easy',
    question: 'Bekenstein proposed that black hole entropy is proportional to:',
    options: [
      'The area of the event horizon in Planck units: $S = A / 4\\ell_P^2$',
      'The volume enclosed by the event horizon',
      'The mass of the black hole squared',
      'The temperature of the Hawking radiation',
    ],
    correctIndex: 0,
    explanation: 'Bekenstein (1973) argued that a black hole must carry entropy proportional to its horizon area $A$ in Planck units: $S_{BH} = k_B c^3 A / (4G\\hbar)$. This was revolutionary because entropy scaling with area (not volume) hinted at a fundamentally holographic structure of spacetime.',
    realWorld: 'This formula unified thermodynamics, quantum mechanics, and general relativity for the first time.',
    hint: 'Entropy goes as surface, not volume — the first hint of holography.',
    glossaryLinks: ['black-hole-entropy', 'holographic-principle'],
    formulaLinks: ['bekenstein-hawking'],
  },
  {
    id: 310002, topic: 'jacob-bekenstein', difficulty: 'easy',
    question: 'Bekenstein\'s generalized second law of thermodynamics states that:',
    options: [
      'The sum of ordinary entropy plus black hole entropy $S_{\\text{matter}} + S_{BH}$ never decreases',
      'Black hole entropy always increases while matter entropy decreases',
      'Entropy is conserved (not just non-decreasing) in black hole processes',
      'The second law of thermodynamics does not apply to systems containing black holes',
    ],
    correctIndex: 0,
    explanation: 'When matter falls into a black hole, its entropy seems to vanish from the observable universe. Bekenstein resolved this paradox by showing that the black hole\'s horizon area (and thus its entropy) increases by at least as much — preserving $\\Delta(S_{\\text{matter}} + S_{BH}) \\geq 0$.',
    realWorld: 'The generalized second law is the thermodynamic foundation for all of black hole information theory.',
    hint: 'Ordinary entropy can decrease locally if the horizon grows enough to compensate.',
    glossaryLinks: ['black-hole-entropy'],
  },
  {
    id: 310003, topic: 'jacob-bekenstein', difficulty: 'hard',
    question: 'The Bekenstein bound places a maximum on the entropy of a system with energy $E$ enclosed in a sphere of radius $R$:',
    options: [
      '$S \\leq 2\\pi k_B E R / (\\hbar c)$ — entropy is bounded by energy times size',
      '$S \\leq E / (k_B T)$ — entropy bounded by energy over temperature',
      '$S \\leq k_B \\ln(E/\\hbar\\omega)$ — entropy bounded logarithmically in energy',
      '$S \\leq (R/\\ell_P)^3$ — entropy bounded by volume in Planck units',
    ],
    correctIndex: 0,
    explanation: 'The Bekenstein bound $S \\leq 2\\pi k_B ER/(\\hbar c)$ is the tightest universal bound on information content. It implies that the information in any region is finite and bounded by its gravitational properties, not its volume.',
    realWorld: 'The Bekenstein bound directly inspired \'t Hooft\'s holographic principle and constrains the information density of any physical system — including quantum computers.',
    hint: 'The bound is linear in both energy and radius, set by fundamental constants.',
    glossaryLinks: ['holographic-principle'],
  },
  {
    id: 310004, topic: 'jacob-bekenstein', difficulty: 'hard',
    question: 'Bekenstein\'s original argument for black hole entropy used a thought experiment involving:',
    options: [
      'Lowering a box of thermal radiation toward a black hole and analyzing the minimum information lost when it crosses the horizon',
      'Colliding two black holes and measuring the gravitational wave spectrum',
      'Scattering photons off the event horizon to measure its temperature',
      'Constructing a Dyson sphere around a black hole to capture Hawking radiation',
    ],
    correctIndex: 0,
    explanation: 'Bekenstein imagined lowering a box of known entropy toward a black hole. When the box crosses the horizon, its entropy is lost to the exterior. To avoid violating the second law, the black hole must gain at least that much entropy — and the only quantity that increases is the horizon area.',
    realWorld: 'This gedankenexperiment established that information has a gravitational cost — a deep connection later formalized in the holographic principle.',
    hint: 'A box of entropy crossing the horizon must be compensated by horizon area growth.',
  },
  {
    id: 310005, topic: 'jacob-bekenstein', difficulty: 'sota',
    question: 'Bekenstein\'s "no-hair" theorem considerations led him to argue that black hole entropy must be $S = \\eta (k_B c^3 / G\\hbar) A$ where $\\eta$ is:',
    options: [
      'A dimensionless constant of order unity that Bekenstein could not fix — Hawking later determined $\\eta = 1/4$ via the temperature calculation',
      'Exactly $\\pi$ from geometric considerations of the horizon',
      'The fine structure constant $\\alpha \\approx 1/137$',
      'Zero for extremal black holes and infinity for Schwarzschild black holes',
    ],
    correctIndex: 0,
    explanation: 'Bekenstein showed that $S \\propto A$ on dimensional and thermodynamic grounds, with $\\eta$ an unknown $O(1)$ constant. Hawking\'s 1974 calculation of black hole radiation temperature $T = \\hbar c^3/(8\\pi G M k_B)$ fixed $\\eta = 1/4$ via $dS = dE/T$.',
    realWorld: 'The Bekenstein-Hawking collaboration (one proposing entropy, the other fixing the coefficient via temperature) is one of the great two-step discoveries in physics.',
    hint: 'Bekenstein got the proportionality; Hawking fixed the constant by computing the temperature.',
    glossaryLinks: ['black-hole-entropy'],
  },
];
