import type { Question } from '../types';

export const jeffDeanQuestions: Question[] = [
  {
    id: 12401,
    topic: 'jeff-dean',
    difficulty: 'easy',
    question: 'Jeff Dean is most associated with building which foundational infrastructure at Google?',
    options: [
      'MapReduce, BigTable, and TensorFlow — the backbone of large-scale distributed computing and ML',
      'The Chrome browser and V8 JavaScript engine',
      'The Android operating system and mobile ecosystem',
      'Google Search ranking algorithms exclusively',
    ],
    correctIndex: 0,
    explanation: 'Jeff Dean co-authored MapReduce, BigTable, Spanner, and TensorFlow — systems that defined how the world does distributed computing and machine learning at scale.',
    realWorld: 'Every Google Search, YouTube recommendation, and Gmail spam filter runs on infrastructure Dean helped create. TensorFlow powers ML at thousands of companies worldwide.',
    hint: 'Think distributed systems + the ML framework that democratized deep learning.',
  },
  {
    id: 12402,
    topic: 'jeff-dean',
    difficulty: 'easy',
    question: 'The Chinchilla scaling law, which Dean\'s teams helped validate, states that optimal training requires:',
    options: [
      'Scaling data and model size equally — roughly $\\text{FLOPs} \\approx 6ND$ where N is parameters and D is tokens',
      'Making models as large as possible regardless of data',
      'Using only synthetic data for training',
      'Training on small curated datasets with massive models',
    ],
    correctIndex: 0,
    explanation: 'The Chinchilla paper showed that many large models were undertrained: optimal compute allocation requires roughly equal scaling of parameters (N) and training tokens (D), with total FLOPs ≈ 6ND.',
    realWorld: 'This insight redirected the entire LLM industry — Llama, Mistral, and later models trained on far more data relative to their size, achieving better performance at lower cost.',
    hint: 'It\'s about the balance between model size and the amount of training data.',
  },
  {
    id: 12403,
    topic: 'jeff-dean',
    difficulty: 'hard',
    question: 'Google\'s Pathways system, led by Dean, differs from traditional ML infrastructure by:',
    options: [
      'Enabling a single model to handle thousands of tasks across modalities using sparse activation (MoE)',
      'Training one model per task with maximum specialization',
      'Replacing neural networks with symbolic reasoning systems',
      'Using only CPUs instead of TPUs for cost efficiency',
    ],
    correctIndex: 0,
    explanation: 'Pathways is Google\'s vision for a single, sparsely-activated model that can generalize across tasks and modalities — only activating relevant subnetworks for each input, inspired by Mixture-of-Experts architectures.',
    realWorld: 'Pathways powers PaLM and Gemini models. The sparse activation idea means a 1T-parameter model might only use 10% of its parameters per query, making it efficient enough for production.',
    hint: 'One model, many tasks, sparse activation — not one model per task.',
  },
  {
    id: 12404,
    topic: 'jeff-dean',
    difficulty: 'hard',
    question: 'Knowledge distillation, heavily used at Google under Dean\'s leadership, achieves:',
    options: [
      'Compressing a large "teacher" model into a small "student" model that approximates the teacher\'s soft probability outputs',
      'Removing all unnecessary parameters by pruning to zero',
      'Converting neural networks into decision trees',
      'Training models on encrypted data without decryption',
    ],
    correctIndex: 0,
    explanation: 'Distillation trains a compact student network to mimic the softmax probability distribution of a large teacher. The "dark knowledge" in the teacher\'s non-top predictions carries valuable information about inter-class similarities.',
    realWorld: 'Google uses distillation to deploy models on phones (e.g., on-device speech recognition). A 1T-parameter server model can be distilled to a 7B model that runs on a laptop.',
    hint: 'The student learns from the teacher\'s soft outputs, not just hard labels.',
  },
  {
    id: 12405,
    topic: 'jeff-dean',
    difficulty: 'sota',
    question: 'In Dean\'s work on large-scale distributed training, the key challenge of gradient staleness in asynchronous SGD is addressed by:',
    options: [
      'Bounded-staleness protocols that limit how far behind any worker can fall, trading consistency for throughput',
      'Forcing all workers to synchronize after every single gradient step',
      'Using only a single GPU to avoid communication overhead',
      'Replacing gradient descent with evolutionary optimization',
    ],
    correctIndex: 0,
    explanation: 'Asynchronous SGD allows workers to update shared parameters without waiting, but stale gradients can destabilize training. Bounded-staleness (used in DistBelief/TensorFlow) limits the maximum delay, providing a principled speed-accuracy tradeoff.',
    realWorld: 'This technique enabled Google to train models across thousands of TPUs simultaneously — the foundation for training GPT-scale models in days rather than years.',
    hint: 'Pure async is fast but unstable; pure sync is stable but slow. The answer is in between.',
  },
];
