import type { Question } from '../types';

export const jimSimonsQuestions: Question[] = [
  {
    id: 10081,
    topic: 'jim-simons',
    difficulty: 'easy',
    question: 'A Hidden Markov Model (HMM) assumes:',
    options: [
      'An unobserved Markov chain generates observed emissions — the hidden state at time $t$ depends only on state at $t-1$',
      'All state variables are observed but transitions are random',
      'The observation sequence itself forms a Markov chain',
      'Hidden variables follow a Gaussian process over continuous time',
    ],
    correctIndex: 0,
    explanation: 'In an HMM, $P(z_t | z_{t-1}, ..., z_1) = P(z_t | z_{t-1})$ (Markov) and $P(x_t | z_1,...,z_t,x_1,...,x_{t-1}) = P(x_t | z_t)$ (emission). The Viterbi algorithm finds the most likely hidden state sequence.',
    realWorld: 'Renaissance Technologies used HMMs to model regime changes in financial markets — bull vs. bear market as hidden states with observable price returns.',
    hint: 'You see the symptoms (emissions) but not the disease (hidden states) — HMM infers the disease.',
  },
  {
    id: 10082,
    topic: 'jim-simons',
    difficulty: 'easy',
    question: 'Stochastic calculus (Itô calculus) differs from ordinary calculus because:',
    options: [
      'Brownian motion has infinite variation, so the chain rule gains an extra term: $d(f(W)) = f\'(W)dW + \\frac{1}{2}f\'\'(W)dt$',
      'Derivatives are replaced by probability distributions at each time step',
      'Integration is performed over probability measures rather than Lebesgue measures',
      'Time steps must be discrete to maintain mathematical consistency',
    ],
    correctIndex: 0,
    explanation: 'Brownian motion $W_t$ has quadratic variation $[W]_t = t$ (unlike smooth functions where $[f]_t = 0$). This adds the $\\frac{1}{2}f\'\'(W)dt$ "Itô correction" — essential for pricing derivatives and modeling stochastic systems.',
    realWorld: 'Black-Scholes equation is derived using Itô\'s lemma on geometric Brownian motion — every option price on Wall Street uses this result.',
    hint: 'Randomness accumulates quadratically in time — the chain rule needs a correction term for that.',
  },
  {
    id: 10083,
    topic: 'jim-simons',
    difficulty: 'easy',
    question: 'Arbitrage in finance means:',
    options: [
      'A risk-free profit opportunity from price discrepancies between markets — buying low and selling high simultaneously',
      'Leveraging borrowed capital to amplify investment returns',
      'Hedging a portfolio to reduce systematic market risk',
      'Taking opposite positions in correlated assets to reduce variance',
    ],
    correctIndex: 0,
    explanation: 'True arbitrage is simultaneously buying and selling the same or equivalent assets in different markets at different prices, locking in a guaranteed profit with no risk and no capital. Markets rapidly close arbitrage opportunities.',
    realWorld: 'Simons\' Medallion fund sought statistical arbitrage — not pure arbitrage, but exploiting small, persistent mispricings using pattern recognition and signal processing.',
    hint: 'Buy cheap here, sell expensive there, at the same time — guaranteed profit with zero risk.',
  },
  {
    id: 10084,
    topic: 'jim-simons',
    difficulty: 'easy',
    question: 'A time series is said to be stationary if:',
    options: [
      'Its mean, variance, and autocovariance are invariant under time shifts',
      'It has no trend component in its additive decomposition',
      'Its autocorrelation function decays to zero monotonically',
      'It passes the Augmented Dickey-Fuller unit root test',
    ],
    correctIndex: 0,
    explanation: 'Weak (covariance) stationarity requires: $E[X_t] = \\mu$ (constant mean), $\\text{Var}(X_t) = \\sigma^2$ (constant variance), and $\\text{Cov}(X_t, X_{t+h})$ depends only on lag $h$, not $t$. Many financial models require stationarity for valid inference.',
    realWorld: 'Most raw financial price series are non-stationary (random walk). Returns (differences of log prices) are approximately stationary — a key preprocessing step.',
    hint: 'The statistical properties don\'t change over time — the series looks the same on Monday and on Friday.',
  },
  {
    id: 10085,
    topic: 'jim-simons',
    difficulty: 'hard',
    question: 'The Viterbi algorithm for HMM decoding computes:',
    options: [
      'The most probable hidden state sequence $\\arg\\max_{z_{1:T}} P(z_{1:T} | x_{1:T})$ using dynamic programming in $O(TK^2)$ time',
      'The posterior marginals $P(z_t | x_{1:T})$ for each time step using forward-backward algorithm',
      'The maximum likelihood parameters $\\theta$ of the HMM via expectation-maximization',
      'The evidence $P(x_{1:T})$ by marginalizing over all hidden state sequences',
    ],
    correctIndex: 0,
    explanation: 'Viterbi tracks $\\delta_t(k) = \\max_{z_{1:t-1}} P(z_{1:t-1}, z_t=k, x_{1:t})$ via DP. Backtracking recovers the optimal path. Without DP, enumeration requires $O(K^T)$ — computationally infeasible for long sequences.',
    realWorld: 'Viterbi is used in speech recognition (phoneme sequence decoding), DNA sequencing (gene finding), and network packet decoding (convolutional codes).',
    hint: 'DP computes the best path to each state at each time, then traces back the optimal sequence.',
  },
  {
    id: 10086,
    topic: 'jim-simons',
    difficulty: 'hard',
    question: 'The Sharpe ratio measures risk-adjusted return as $S = (R_p - R_f) / \\sigma_p$. A high Sharpe ratio indicates:',
    options: [
      'High excess return per unit of volatility — the strategy earns well relative to the risk taken',
      'Low drawdown relative to average return over the investment period',
      'The portfolio beats the market index on more than 50% of trading days',
      'Returns are normally distributed with minimal skewness',
    ],
    correctIndex: 0,
    explanation: 'Sharpe ratio = excess return / standard deviation. A Sharpe > 1 is good; > 2 is excellent; > 3 is exceptional. Renaissance\'s Medallion Fund reportedly achieved Sharpes > 5 — essentially impossible by random chance, implying genuine edge.',
    realWorld: 'The S&P 500 has a Sharpe of ~0.5. Medallion\'s reported Sharpe of 5+ (before fees) is among the highest sustained in financial history.',
    hint: 'How much return do you get for each unit of risk you take? Higher = better.',
  },
  {
    id: 10087,
    topic: 'jim-simons',
    difficulty: 'hard',
    question: 'Pairs trading exploits mean reversion by:',
    options: [
      'Going long the underperforming asset and short the outperforming one when their spread deviates from the historical mean, expecting convergence',
      'Buying both assets in a correlated pair when market volatility is elevated',
      'Hedging one asset with options on its correlated pair to reduce directional exposure',
      'Arbitraging futures and spot prices of two correlated commodities simultaneously',
    ],
    correctIndex: 0,
    explanation: 'If assets $A$ and $B$ are cointegrated, the spread $S_t = A_t - \\beta B_t$ is stationary with mean $\\mu$. When $S_t > \\mu + k\\sigma$, sell $A$, buy $B$; when $S_t < \\mu - k\\sigma$, buy $A$, sell $B$. Profit from mean reversion.',
    realWorld: 'Simons\' team pioneered statistical arbitrage using cointegration. Modern quant funds trade thousands of such pairs simultaneously using ML to detect cointegrated relationships.',
    hint: 'When two correlated stocks temporarily diverge, bet on them converging — that\'s mean reversion.',
  },
  {
    id: 10088,
    topic: 'jim-simons',
    difficulty: 'sota',
    question: 'Geometric Brownian Motion (GBM) $dS = \\mu S\\,dt + \\sigma S\\,dW$ has the solution:',
    options: [
      '$S_t = S_0 \\exp\\left((\\mu - \\frac{\\sigma^2}{2})t + \\sigma W_t\\right)$ — log-normal distribution at each time',
      '$S_t = S_0 + \\mu t + \\sigma W_t$ — normal distribution at each time',
      '$S_t = S_0 e^{\\mu t}$ — deterministic exponential growth',
      '$S_t = S_0 e^{\\sigma W_t}$ — pure multiplicative noise with zero drift',
    ],
    correctIndex: 0,
    explanation: 'Applying Itô\'s lemma to $f(S) = \\ln S$ gives $d(\\ln S) = (\\mu - \\sigma^2/2)dt + \\sigma dW$. The $-\\sigma^2/2$ term is the Itô correction. Integrating: $\\ln(S_t/S_0) \\sim \\mathcal{N}((\\mu-\\sigma^2/2)t, \\sigma^2 t)$ — log-normal prices.',
    realWorld: 'GBM is the foundation of the Black-Scholes model. The $\\sigma^2/2$ correction explains why expected log-return differs from expected return — critical for long-horizon investment analysis.',
    hint: 'Itô\'s lemma on $\\ln S$ generates the $-\\sigma^2/2$ correction that makes prices log-normal.',
  },
  {
    id: 10089,
    topic: 'jim-simons',
    difficulty: 'sota',
    question: 'The Kalman filter for a linear-Gaussian state space model provides:',
    options: [
      'The exact posterior $P(z_t | x_{1:t})$ as a Gaussian, updated recursively via predict and update steps',
      'The maximum likelihood estimate of model parameters via the EM algorithm',
      'The optimal trading signal by filtering noise from financial time series',
      'The minimum variance linear predictor of future observations given past observations',
    ],
    correctIndex: 0,
    explanation: 'For linear dynamics and Gaussian noise, the Kalman filter computes the exact posterior mean $\\hat{z}_{t|t}$ and covariance $P_{t|t}$ via two steps: predict ($\\hat{z}_{t|t-1} = F\\hat{z}_{t-1|t-1}$) and update (incorporate new observation via Kalman gain $K_t$).',
    realWorld: 'Simons\' team used Kalman filtering to extract true market signals from noisy price data. GPS, autonomous vehicles, and robotics all rely on Kalman filters for state estimation.',
    hint: 'For linear + Gaussian systems, the posterior is always Gaussian — Kalman tracks its mean and variance exactly.',
  },
  {
    id: 10090,
    topic: 'jim-simons',
    difficulty: 'sota',
    question: 'The Chern-Simons theory (named partly for Simons\' mathematical work on characteristic classes) computes topological invariants. The Chern-Simons 3-form $\\text{CS}(A) = \\text{tr}(A \\wedge dA + \\frac{2}{3} A \\wedge A \\wedge A)$ is significant because:',
    options: [
      'Its integral over a 3-manifold is a topological invariant of the gauge bundle, unchanged under smooth deformations of the gauge field',
      'It equals the Yang-Mills action density for self-dual gauge fields',
      'It generates the topological charge (winding number) of instanton solutions',
      'It provides the anomaly coefficient for chiral fermions in quantum field theory',
    ],
    correctIndex: 0,
    explanation: 'The Chern-Simons functional is gauge-invariant modulo integers, making $e^{2\\pi i \\int \\text{CS}(A)}$ a topological invariant. Witten (1988) used it to define 3-manifold and knot invariants, connecting topology to quantum field theory.',
    realWorld: 'Chern-Simons theory describes topological phases of matter (fractional quantum Hall effect, topological insulators) and is the basis for proposed topological quantum computers.',
    hint: 'The integral depends only on the topology of the bundle, not the specific gauge field — a pure topological quantity.',
  },
];
