import type { Question } from '../types';

export const johnHollandQuestions: Question[] = [
  {
    id: 21170,
    topic: 'john-holland',
    difficulty: 'sota',
    question: 'John Holland\'s genetic algorithms use which operators inspired by biological evolution?',
    options: ['Selection, crossover (recombination), and mutation', 'Gradient descent and backpropagation', 'Simulated annealing and cooling schedules', 'Branch and bound with pruning'],
    correctIndex: 0,
    explanation: 'Genetic algorithms maintain a population of candidate solutions that undergo selection (survival of the fittest), crossover (combining parts of two parents), and mutation (random changes) — mimicking Darwinian evolution.',
    realWorld: 'GAs are used to design antenna shapes for NASA, optimize supply chains, and evolve neural network architectures.',
    hint: 'The three operators mirror the mechanisms Darwin described in natural populations.',
  },
  {
    id: 21171,
    topic: 'john-holland',
    difficulty: 'sota',
    question: 'Holland\'s "Schema Theorem" provides a theoretical foundation for genetic algorithms by showing what?',
    options: ['Short, low-order, above-average schemata receive exponentially increasing trials', 'All schemata converge to the global optimum', 'Crossover is always superior to mutation alone', 'Genetic algorithms find exact solutions in polynomial time'],
    correctIndex: 0,
    explanation: 'The Schema Theorem (the "fundamental theorem of genetic algorithms") shows that building blocks (short, high-fitness patterns) propagate exponentially through the population, driving the search toward good solutions.',
    realWorld: 'The schema theorem explains why GAs work well on problems with useful building blocks but struggle on deceptive fitness landscapes.',
    hint: 'It concerns the growth rate of useful partial patterns within the population.',
  },
  {
    id: 21172,
    topic: 'john-holland',
    difficulty: 'sota',
    question: 'Holland\'s classifier systems combine genetic algorithms with which learning paradigm?',
    options: ['Reinforcement learning — rules compete for credit based on environmental rewards', 'Supervised learning with labeled datasets', 'Unsupervised clustering of input data', 'Transfer learning from pre-trained models'],
    correctIndex: 0,
    explanation: 'Holland\'s Learning Classifier Systems (LCS) use if-then rules that compete for activation and receive credit based on environmental feedback, with a genetic algorithm evolving better rule sets over time.',
    realWorld: 'LCS influenced the development of modern reinforcement learning systems and evolutionary robotics.',
    hint: 'Rules earn "payment" from the environment and reproduce based on their success.',
  },
  {
    id: 21173,
    topic: 'john-holland',
    difficulty: 'sota',
    question: 'Holland\'s concept of "complex adaptive systems" (CAS) identifies which key property shared by economies, ecosystems, and immune systems?',
    options: ['Emergence — system-level patterns arise from local interactions of adaptive agents', 'Central control by a single agent', 'Linear predictability from initial conditions', 'Convergence to a single equilibrium state'],
    correctIndex: 0,
    explanation: 'CAS are systems composed of many interacting agents that adapt their behavior based on experience, producing emergent macro-level patterns (like market prices or immune responses) that no single agent controls or predicts.',
    realWorld: 'CAS theory is foundational to the Santa Fe Institute\'s approach to economics, ecology, and artificial life.',
    hint: 'The whole is more than the sum of its parts — patterns appear that no agent intended.',
  },
  {
    id: 21174,
    topic: 'john-holland',
    difficulty: 'sota',
    question: 'Holland\'s "royal road" functions were designed to test which hypothesis about genetic algorithms?',
    options: ['That GAs exploit building blocks (schemata) through crossover', 'That mutation alone is sufficient for optimization', 'That larger populations always perform better', 'That elitism prevents premature convergence'],
    correctIndex: 0,
    explanation: 'Royal road functions were specifically constructed so that combining building blocks (via crossover) is the only efficient path to the optimum, testing whether GAs actually exploit schema recombination as the Schema Theorem predicts.',
    realWorld: 'Surprisingly, simple hill-climbing sometimes outperformed GAs on royal road functions, sparking important debates about when GAs are truly advantageous.',
    hint: 'These fitness landscapes were designed with an explicit hierarchical building-block structure.',
  },
];
