import type { Question } from '../types';

export const johnVonNeumannQuestions: Question[] = [
  {
    id: 10061,
    topic: 'john-von-neumann',
    difficulty: 'easy',
    question: 'In game theory, a zero-sum game is one where:',
    options: [
      'One player\'s gain is exactly equal to the other player\'s loss, so total payoff is always zero',
      'Both players earn zero payoff at the Nash equilibrium',
      'The sum of all players\' strategies equals zero',
      'No player can improve their payoff by changing strategy',
    ],
    correctIndex: 0,
    explanation: 'In a zero-sum game, wealth is conserved between players — what one gains, the other loses. Von Neumann proved the minimax theorem for such games, guaranteeing optimal strategies exist.',
    realWorld: 'Chess, poker, and adversarial ML (GANs, adversarial examples) are zero-sum games. AlphaGo uses minimax-style tree search.',
    hint: 'The payoff table rows sum to zero — every dollar I win, you lose.',
  },
  {
    id: 10062,
    topic: 'john-von-neumann',
    difficulty: 'easy',
    question: 'The von Neumann minimax theorem states: for a finite zero-sum game:',
    options: [
      '$\\max_{x} \\min_{y} u(x,y) = \\min_{y} \\max_{x} u(x,y)$ — there exists an optimal mixed strategy pair',
      'The dominant strategy always achieves the highest payoff regardless of opponent',
      'Nash equilibria always exist and are unique in zero-sum games',
      'The game can always be solved by backward induction in finite time',
    ],
    correctIndex: 0,
    explanation: 'Von Neumann (1928) proved that in any finite two-player zero-sum game, the maximin equals the minimax when players use mixed (randomized) strategies. This defines the game\'s value and guarantees rational play.',
    realWorld: 'DeepMind\'s AlphaStar and OpenAI Five use minimax principles. The theorem underpins all of adversarial machine learning.',
    hint: 'What\'s the best you can guarantee regardless of what the opponent does? That\'s the minimax value.',
  },
  {
    id: 10063,
    topic: 'john-von-neumann',
    difficulty: 'easy',
    question: 'The Von Neumann architecture of modern computers consists of:',
    options: [
      'A shared memory for data and instructions, a CPU, and an I/O system — the stored-program concept',
      'Separate instruction memory and data memory connected by a bus',
      'A neural processing unit, a memory bank, and a parallel instruction pipeline',
      'Multiple specialized co-processors coordinated by a master control unit',
    ],
    correctIndex: 0,
    explanation: 'Von Neumann\'s stored-program concept (1945) places instructions and data in the same memory, with a single processor fetching and executing them sequentially. This allows programs to modify themselves and treat code as data.',
    realWorld: 'Every laptop, smartphone, and server today is a von Neumann machine. The "von Neumann bottleneck" (memory bandwidth limit) drives cache hierarchy and neuromorphic computing research.',
    hint: 'Programs stored in memory alongside data — this seems obvious now, but it was revolutionary in 1945.',
  },
  {
    id: 10064,
    topic: 'john-von-neumann',
    difficulty: 'easy',
    question: 'The Prisoner\'s Dilemma is a non-zero-sum game where rational players:',
    options: [
      'Defect (betray), reaching a Nash equilibrium that is suboptimal for both compared to mutual cooperation',
      'Cooperate, since mutual cooperation maximizes total utility',
      'Play a mixed strategy of cooperating and defecting with equal probability',
      'Have no Nash equilibrium because payoffs are asymmetric',
    ],
    correctIndex: 0,
    explanation: 'Both players have dominant strategy: defect (betray). But (Defect, Defect) gives 2 years each vs. (Cooperate, Cooperate) giving 1 year each. Rational individual choice leads to collectively suboptimal outcomes — the core tension of social dilemmas.',
    realWorld: 'Arms races, climate negotiations, open-source contribution, and pricing wars are all prisoner\'s dilemmas. Iterated versions (tit-for-tat) enable cooperation.',
    hint: 'Each player is better off defecting regardless of what the other does — but if both defect, both lose.',
  },
  {
    id: 10065,
    topic: 'john-von-neumann',
    difficulty: 'hard',
    question: 'In the minimax algorithm for game trees, alpha-beta pruning improves efficiency by:',
    options: [
      'Eliminating branches that cannot affect the final decision because one player already has a better option',
      'Reducing the depth of the search tree by evaluating terminal positions only',
      'Caching previously evaluated positions to avoid recomputation',
      'Sampling random continuations instead of exhaustively evaluating all moves',
    ],
    correctIndex: 0,
    explanation: 'Alpha ($\\alpha$) = best value maximizer can guarantee; beta ($\\beta$) = best value minimizer can guarantee. When a branch\'s value falls outside $[\\alpha, \\beta]$, it won\'t be chosen by a rational opponent and can be pruned. Best case: $O(b^{d/2})$ instead of $O(b^d)$.',
    realWorld: 'Chess engines (Stockfish) use alpha-beta with iterative deepening. AlphaZero replaced it with MCTS + neural networks for more complex games.',
    hint: 'If you already have a move that gives you X, you don\'t need to explore branches that guarantee < X for your opponent.',
  },
  {
    id: 10066,
    topic: 'john-von-neumann',
    difficulty: 'hard',
    question: 'Von Neumann\'s ergodic theorem states: for a measure-preserving transformation $T$ and $f \\in L^2$:',
    options: [
      'The time average $\\frac{1}{N}\\sum_{n=0}^{N-1} f(T^n x)$ converges in $L^2$ to the space average $\\int f\\,d\\mu$ for ergodic $T$',
      'Every orbit of $T$ is dense in the phase space when $T$ is measure-preserving',
      'The correlation function $\\langle f(T^n x) f(x) \\rangle$ decays exponentially for ergodic systems',
      'The entropy of $T$ equals the logarithm of its spectral radius',
    ],
    correctIndex: 0,
    explanation: 'For an ergodic system, time averages equal space averages. Von Neumann proved $L^2$ convergence; Birkhoff proved pointwise. This is the mathematical foundation of statistical mechanics — why thermodynamic averages work.',
    realWorld: 'Monte Carlo integration relies on ergodicity: the samples approximate the distribution\'s space average by time-averaging a Markov chain.',
    hint: 'Ergodic = the system explores all of phase space — time averaging becomes space averaging.',
  },
  {
    id: 10067,
    topic: 'john-von-neumann',
    difficulty: 'hard',
    question: 'Von Neumann algebras (W*-algebras) are characterized as:',
    options: [
      'C*-algebras that are closed in the weak operator topology, equivalently equal to their double commutant',
      'Banach algebras of bounded operators with a normalized trace functional',
      'Algebras of observables that satisfy canonical commutation relations',
      'Operator algebras defined on finite-dimensional Hilbert spaces only',
    ],
    correctIndex: 0,
    explanation: 'A von Neumann algebra $M$ is a *-subalgebra of $B(\\mathcal{H})$ closed in the weak operator topology, equivalently $M = M\'\'$ (bicommutant theorem). They classify as Types I, II, III depending on their projection lattice — the foundation of quantum logic.',
    realWorld: 'Von Neumann algebras are the mathematical framework for quantum field theory (local algebras of observables) and quantum information (entanglement entropy).',
    hint: 'Closed in the weak topology — limits of sequences of operators remain in the algebra.',
  },
  {
    id: 10068,
    topic: 'john-von-neumann',
    difficulty: 'sota',
    question: 'The Nash equilibrium concept generalizes von Neumann\'s minimax to non-zero-sum games. A strategy profile $(s_1^*, ..., s_n^*)$ is a Nash equilibrium if:',
    options: [
      'No player can increase their payoff by unilaterally deviating: $u_i(s_i^*, s_{-i}^*) \\geq u_i(s_i, s_{-i}^*)$ for all $i$ and all $s_i$',
      'The joint strategy maximizes the sum of all players\' payoffs',
      'Each player\'s strategy is optimal regardless of all other players\' strategies',
      'The strategy profile is on the Pareto frontier of the payoff space',
    ],
    correctIndex: 0,
    explanation: 'Nash (1950) proved that every finite game has at least one mixed strategy Nash equilibrium (Nash\'s theorem, proved via Brouwer fixed-point theorem). This extended von Neumann\'s minimax from 2-player zero-sum to general $n$-player games.',
    realWorld: 'Multi-agent RL systems (OpenAI Five, AlphaStar) seek Nash equilibria. Auction design and mechanism design guarantee Nash equilibria for desired outcomes.',
    hint: 'No one wants to change their strategy given what everyone else is doing — that\'s a Nash equilibrium.',
  },
  {
    id: 10069,
    topic: 'john-von-neumann',
    difficulty: 'sota',
    question: 'Von Neumann\'s self-reproducing automata demonstrated that:',
    options: [
      'A sufficiently complex automaton can contain a complete description of itself and use it to make copies, separating description from construction',
      'Any finite state machine can reproduce itself given enough memory',
      'Life requires a continuous energy source to maintain its self-reproducing property',
      'Self-reproduction requires quantum superposition to copy genetic information',
    ],
    correctIndex: 0,
    explanation: 'Von Neumann (1948) designed a cellular automaton that: (1) reads its description and uses it to build a copy, (2) copies the description into the offspring. This logically anticipated DNA\'s dual role as information carrier (genotype) and construction template (phenotype).',
    realWorld: 'This inspired Quine programs (self-printing code), computer viruses (self-replicating code), and synthetic biology (designing self-replicating genetic circuits).',
    hint: 'Separate what you are (description) from what you do (construction) — and copy both.',
  },
  {
    id: 10070,
    topic: 'john-von-neumann',
    difficulty: 'sota',
    question: 'The quantum no-cloning theorem (Wootters & Zurek 1982), building on von Neumann measurement theory, states:',
    options: [
      'An unknown quantum state $|\\psi\\rangle$ cannot be perfectly copied: no unitary $U$ satisfies $U|\\psi\\rangle|0\\rangle = |\\psi\\rangle|\\psi\\rangle$ for all $|\\psi\\rangle$',
      'Quantum measurement necessarily destroys the measured state entirely',
      'Entangled states cannot be separated once created without decoherence',
      'The density matrix of a mixed state cannot be purified without ancilla qubits',
    ],
    correctIndex: 0,
    explanation: 'Proof: if $U$ cloned $|\\psi\\rangle$ and $|\\phi\\rangle$, linearity gives $U(\\alpha|\\psi\\rangle + \\beta|\\phi\\rangle)|0\\rangle = \\alpha|\\psi\\rangle|\\psi\\rangle + \\beta|\\phi\\rangle|\\phi\\rangle \\neq (\\alpha|\\psi\\rangle + \\beta|\\phi\\rangle)^{\\otimes 2}$. Quantum linearity forbids cloning.',
    realWorld: 'No-cloning guarantees security in quantum key distribution (BB84) — an eavesdropper cannot copy qubits without being detected.',
    hint: 'Quantum linearity is the enemy of cloning — superposition states cannot be duplicated without contradiction.',
  },
];
