import type { Question } from '../types';

export const hopfieldQuestions: Question[] = [
  {
    id: 20440,
    topic: 'hopfield',
    difficulty: 'hard',
    question: 'In a Hopfield network, the energy function $E = -\\frac{1}{2}\\sum_{i \\neq j} w_{ij} s_i s_j$ is guaranteed to do what during asynchronous updates?',
    options: ['Monotonically decrease or stay constant', 'Increase', 'Oscillate', 'Remain exactly constant'],
    correctIndex: 0,
    explanation: 'Each asynchronous update reduces or maintains the energy — the network descends to a local minimum, which represents a stored memory.',
    realWorld: 'This energy minimization principle inspired simulated annealing and modern optimization algorithms used in chip placement.',
    hint: 'Think of a ball rolling downhill in an energy landscape.',
  },
  {
    id: 20441,
    topic: 'hopfield',
    difficulty: 'hard',
    question: 'The storage capacity of a Hopfield network with $N$ neurons using Hebbian learning is approximately:',
    options: ['$0.14N$ patterns', '$N^2$ patterns', '$2^N$ patterns', '$N$ patterns'],
    correctIndex: 0,
    explanation: 'Beyond $\\approx 0.14N$ stored patterns, retrieval errors spike dramatically due to spurious attractors — a phase transition in the network.',
    realWorld: 'Understanding capacity limits of associative memory informs modern transformer attention mechanisms and memory-augmented networks.',
    hint: 'It\'s a fraction of $N$, not proportional to $N$ or exponential.',
  },
  {
    id: 20442,
    topic: 'hopfield',
    difficulty: 'sota',
    question: 'The modern Hopfield network (Ramsauer et al., 2020) replaces the quadratic energy with an exponential interaction. What is the resulting storage capacity?',
    options: ['Exponential in $N$', 'Linear in $N$', 'Logarithmic in $N$', 'Polynomial in $N$'],
    correctIndex: 0,
    explanation: 'The exponential energy function allows storing exponentially many patterns with sharp retrieval — and the update rule is equivalent to the transformer attention mechanism.',
    realWorld: 'This connection proved that transformer self-attention is performing associative memory retrieval — a deep unification of two fields.',
    hint: 'The exponential interaction dramatically increases capacity beyond the classical $0.14N$ limit.',
  },
  {
    id: 20443,
    topic: 'hopfield',
    difficulty: 'sota',
    question: 'Hopfield shared the 2024 Nobel Prize in Physics. The Nobel committee cited his work as foundational to which broader paradigm?',
    options: ['Machine learning using artificial neural networks', 'Quantum computing', 'String theory', 'Topological insulators'],
    correctIndex: 0,
    explanation: 'The 2024 Nobel recognized Hopfield (and Hinton) for foundational discoveries enabling machine learning with artificial neural networks.',
    realWorld: 'This was the first Nobel Prize explicitly recognizing artificial intelligence research, marking AI\'s arrival as a fundamental science.',
    hint: 'He shared it with Geoffrey Hinton for work on neural networks.',
  },
  {
    id: 20444,
    topic: 'hopfield',
    difficulty: 'easy',
    question: 'Hopfield drew an analogy between neural networks and which physical system?',
    options: ['Spin glasses (magnetic systems)', 'Planetary orbits', 'Fluid flow', 'Crystal growth'],
    correctIndex: 0,
    explanation: 'Hopfield showed that neurons updating their states behave like magnetic spins minimizing energy in a spin glass — bridging physics and neuroscience.',
    realWorld: 'This physics-to-biology bridge inspired an entire generation of computational neuroscientists.',
    hint: 'Think of magnetic materials where spins interact and settle into low-energy configurations.',
  },
];
