import type { Question } from '../types';

export const conwayQuestions: Question[] = [
  {
    id: 20750,
    topic: 'conway',
    difficulty: 'hard',
    question: 'Conway\'s Game of Life uses four rules on a 2D grid. A dead cell becomes alive if it has exactly how many live neighbors?',
    options: ['Exactly 3', 'Exactly 2', 'Exactly 4', '1 or more'],
    correctIndex: 0,
    explanation: 'Birth requires exactly 3 neighbors. Survival requires 2 or 3. Anything else means death. From these four rules, Turing-complete computation emerges.',
    realWorld: 'The Game of Life demonstrated that complex, self-organizing behavior can emerge from trivially simple rules — a key insight for complexity science.',
    hint: 'The "B3/S23" rule: Birth at 3, Survival at 2 or 3.',
  },
  {
    id: 20751,
    topic: 'conway',
    difficulty: 'hard',
    question: 'Conway\'s Game of Life has been proven to be Turing-complete. What does this mean?',
    options: ['It can simulate any computation that a Turing machine can perform', 'It always halts', 'It can only compute finite functions', 'It requires external input'],
    correctIndex: 0,
    explanation: 'Patterns like "glider guns" and "spaceships" can be arranged to build logic gates, memory, and any arbitrary computation — it\'s a universal computer.',
    realWorld: 'People have built working digital clocks, prime number calculators, and even a Game of Life inside a Game of Life.',
    hint: 'Turing-completeness means universal computation — any algorithm, any program.',
  },
  {
    id: 20752,
    topic: 'conway',
    difficulty: 'sota',
    question: 'Conway\'s "Monstrous Moonshine" conjecture (with Simon Norton) connected the Monster group to modular functions. What is the order of the Monster group?',
    options: ['$\\approx 8 \\times 10^{53}$', '$\\approx 10^{20}$', '$\\approx 10^{100}$', '$\\approx 2^{256}$'],
    correctIndex: 0,
    explanation: 'The Monster has order $|M| \\approx 8.08 \\times 10^{53}$ — the largest sporadic simple group. Its mysterious connection to the $j$-function was proven by Borcherds (Fields Medal, 1998).',
    realWorld: 'Monstrous Moonshine connects group theory to string theory and conformal field theory — one of the deepest unexpected connections in mathematics.',
    hint: 'It\'s the largest of the 26 sporadic simple groups — truly monstrous in size.',
  },
  {
    id: 20753,
    topic: 'conway',
    difficulty: 'sota',
    question: 'Conway invented the "surreal numbers" — a number system that contains:',
    options: ['All reals, all ordinals, infinitesimals, and every combinatorial game value', 'Only integers and rationals', 'Only complex numbers', 'Only non-standard reals'],
    correctIndex: 0,
    explanation: 'Surreal numbers form the largest ordered field: they contain real numbers, transfinite ordinals, infinitesimals like $1/\\omega$, and every combinatorial game value.',
    realWorld: 'Surreal numbers provide a rigorous framework for analyzing combinatorial games and have connections to non-standard analysis.',
    hint: 'They\'re "surreal" because they encompass everything — reals, infinities, infinitesimals, and more.',
  },
  {
    id: 20754,
    topic: 'conway',
    difficulty: 'easy',
    question: 'Conway famously grew to dislike his most popular invention. What was it?',
    options: ['The Game of Life', 'Surreal numbers', 'The Monster group', 'Sprouts'],
    correctIndex: 0,
    explanation: 'He felt the Game of Life overshadowed his deeper mathematical work on groups, knots, and number systems — it was "just a game" to him.',
    realWorld: 'Despite his feelings, the Game of Life remains one of the most important demonstrations of emergence and computational universality.',
    hint: 'It\'s a zero-player cellular automaton that took on a life of its own.',
  },
];
