import type { Question } from '../types';

export const juanMaldacenaQuestions: Question[] = [
  {
    id: 310301, topic: 'juan-maldacena', difficulty: 'easy',
    question: 'Maldacena\'s AdS/CFT correspondence (1997) states that:',
    options: [
      'Type IIB string theory on $AdS_5 \\times S^5$ is exactly dual to $\\mathcal{N}=4$ super Yang-Mills in 4D — a quantum gravity theory equals a non-gravitational gauge theory',
      'Any quantum field theory is equivalent to string theory in flat spacetime',
      'Anti-de Sitter space is unstable and decays to de Sitter space',
      'Conformal field theories only exist in two dimensions',
    ],
    correctIndex: 0,
    explanation: 'Maldacena\'s conjecture identifies the full quantum gravity theory (strings in the bulk AdS spacetime) with a specific conformal field theory ($\\mathcal{N}=4$ SYM with gauge group $SU(N)$) living on the boundary. This is the most concrete realization of the holographic principle.',
    realWorld: 'AdS/CFT has been applied to compute quark-gluon plasma viscosity (η/s = 1/4π), model superconductors, and study quantum chaos — far beyond its original string theory context.',
    hint: 'Gravity in the bulk = gauge theory on the boundary.',
    glossaryLinks: ['ads-cft', 'holographic-principle'],
  },
  {
    id: 310302, topic: 'juan-maldacena', difficulty: 'easy',
    question: 'In AdS/CFT, a black hole in the bulk anti-de Sitter space corresponds to:',
    options: [
      'A thermal state in the boundary CFT at the Hawking temperature — black hole entropy matches the thermal entropy of the gauge theory',
      'A vacuum state with zero temperature and zero entropy',
      'A single particle excitation above the CFT ground state',
      'A topological defect in the boundary theory',
    ],
    correctIndex: 0,
    explanation: 'A large AdS black hole with temperature $T$ maps to the deconfined thermal phase of the $\\mathcal{N}=4$ SYM plasma at the same temperature. The Bekenstein-Hawking entropy $S = A/(4G)$ matches the $O(N^2)$ degrees of freedom of the gauge theory at strong coupling.',
    realWorld: 'This mapping proves that black hole evaporation is unitary — because the boundary thermal evolution is manifestly unitary.',
    hint: 'Hot black hole in the bulk = hot soup of gluons on the boundary.',
    glossaryLinks: ['black-hole-entropy'],
  },
  {
    id: 310303, topic: 'juan-maldacena', difficulty: 'hard',
    question: 'The Ryu-Takayanagi formula, which extends Bekenstein-Hawking entropy in AdS/CFT, states that the entanglement entropy of a boundary region $A$ equals:',
    options: [
      '$S(A) = \\text{Area}(\\gamma_A) / (4G_N)$ where $\\gamma_A$ is the minimal surface in the bulk homologous to $A$',
      '$S(A) = \\text{Volume}(\\Sigma_A) / (4G_N)$ where $\\Sigma_A$ is a bulk region',
      '$S(A) = \\text{Length}(\\partial A) / (4G_N)$ for any boundary curve',
      '$S(A) = k_B \\ln(\\dim \\mathcal{H}_A)$ with no geometric interpretation',
    ],
    correctIndex: 0,
    explanation: 'Ryu-Takayanagi (2006) generalized Bekenstein-Hawking: the entanglement entropy of a boundary subregion equals the area of the minimal surface anchored to $\\partial A$ and extending into the bulk. This formula connects quantum information (entanglement) to geometry (area), expressing "entanglement builds spacetime."',
    realWorld: 'The RT formula has been proven (by Lewkowycz and Maldacena) in the Euclidean gravity regime and extended to time-dependent settings via the HRT (Hubeny-Rangamani-Takayanagi) formula.',
    hint: 'Like Bekenstein-Hawking, but for arbitrary regions — find the minimal surface anchored to the boundary.',
    formulaLinks: ['ryu-takayanagi'],
    glossaryLinks: ['ads-cft'],
  },
  {
    id: 310304, topic: 'juan-maldacena', difficulty: 'hard',
    question: 'The AdS/CFT dictionary maps the radial direction in AdS to:',
    options: [
      'The energy scale (RG flow) of the boundary theory — the bulk interior corresponds to IR physics, and the boundary to UV physics',
      'Physical time in the boundary theory',
      'The number of colors $N$ in the gauge group',
      'The string coupling constant $g_s$',
    ],
    correctIndex: 0,
    explanation: 'The radial coordinate $z$ in AdS maps to the RG scale of the boundary CFT: $z \\to 0$ (boundary) corresponds to UV, $z \\to \\infty$ (interior) to IR. A massive field in AdS with mass $m$ maps to an operator with conformal dimension $\\Delta$ related by $m^2 L^2 = \\Delta(\\Delta - d)$.',
    realWorld: 'This UV/IR connection means that probing deep into the bulk requires low-energy (large-scale) boundary observations — a geometric realization of the renormalization group.',
    hint: 'Going deeper into AdS is like zooming out in the boundary theory.',
  },
  {
    id: 310305, topic: 'juan-maldacena', difficulty: 'sota',
    question: 'Maldacena and Susskind\'s ER = EPR conjecture identifies:',
    options: [
      'Einstein-Rosen bridges (non-traversable wormholes) with quantum entanglement between particles — spacetime connectivity emerges from quantum correlations',
      'Wormholes as FTL communication channels between entangled black holes',
      'EPR pairs as classical objects connected by visible bridges',
      'Quantum teleportation as physical matter transport through spacetime',
    ],
    correctIndex: 0,
    explanation: 'ER = EPR proposes that the geometric connection (Einstein-Rosen bridge) between two entangled black holes in AdS is the same phenomenon as the quantum entanglement (Einstein-Podolsky-Rosen) between them. The wormhole IS the entanglement, geometrized. This extends to all entangled systems via Planck-scale wormholes.',
    realWorld: 'ER = EPR suggests that the fabric of spacetime itself is woven from quantum entanglement — destroying entanglement would tear spacetime apart.',
    hint: 'Wormholes and entanglement are the same thing seen from different perspectives.',
    glossaryLinks: ['ads-cft', 'holographic-principle'],
  },
  {
    id: 310306, topic: 'juan-maldacena', difficulty: 'sota',
    question: 'The Strominger-Vafa calculation (1996), which Maldacena extended, derived Bekenstein-Hawking entropy microscopically by:',
    options: [
      'Counting D-brane microstates of an extremal black hole in string theory and matching the Cardy formula result $S = 2\\pi\\sqrt{n_1 n_5 n_p}$ to the horizon area',
      'Computing the one-loop determinant of all Standard Model fields near a black hole horizon',
      'Summing over all possible topologies of the Euclidean path integral',
      'Using lattice gauge theory simulations of $SU(N)$ at finite temperature',
    ],
    correctIndex: 0,
    explanation: 'Strominger and Vafa (1996) considered a 5D extremal black hole built from $n_1$ D1-branes, $n_5$ D5-branes wrapping $K3 \\times S^1$, with momentum $n_p$. At weak coupling, the microstates are excitations of an effective 2D CFT with central charge $c = 6n_1 n_5$. The Cardy formula gives $S = 2\\pi\\sqrt{c \\cdot n_p / 6} = 2\\pi\\sqrt{n_1 n_5 n_p}$, exactly matching $S_{BH} = A/(4G)$.',
    realWorld: 'This was the first microscopic derivation of black hole entropy, vindicating Bekenstein\'s 1973 proposal and providing the strongest evidence for string theory as a quantum gravity candidate.',
    hint: 'Count brane excitations at weak coupling; the answer matches the horizon area at strong coupling.',
    glossaryLinks: ['black-hole-entropy'],
    formulaLinks: ['bekenstein-hawking'],
  },
];
