import type { Question } from '../types';

export const pearlQuestions: Question[] = [
  {
    id: 10071,
    topic: 'pearl',
    difficulty: 'easy',
    question: 'A Bayesian Network represents:',
    options: [
      'A directed acyclic graph where nodes are random variables and edges encode conditional independence via $P(X_i | \\text{Pa}(X_i))$',
      'A neural network trained with Bayesian optimization of hyperparameters',
      'An undirected graphical model where edges represent correlations',
      'A causal graph where all edges have proven causal direction',
    ],
    correctIndex: 0,
    explanation: 'A Bayesian network factorizes the joint distribution as $P(X_1,...,X_n) = \\prod_i P(X_i | \\text{Pa}(X_i))$, where $\\text{Pa}(X_i)$ are the parents of node $i$. It encodes conditional independence structure compactly.',
    realWorld: 'Medical diagnosis systems (MYCIN, QMR-DT), spam filters, and search engine click models use Bayesian networks for probabilistic reasoning.',
    hint: 'Each node depends only on its parents — this conditional independence makes inference tractable.',
  },
  {
    id: 10072,
    topic: 'pearl',
    difficulty: 'easy',
    question: 'Pearl\'s do-calculus distinguishes $P(Y|X=x)$ from $P(Y|do(X=x))$ because:',
    options: [
      'Conditioning on X uses observational data (selecting units where X=x), while do(X=x) represents an intervention that forces X=x regardless of its causes',
      'The do-operator applies a prior distribution while conditioning uses the likelihood',
      'Do-calculus operates on categorical variables while conditioning works on continuous ones',
      '$P(Y|X=x)$ is the posterior while $P(Y|do(X=x))$ is the marginal likelihood',
    ],
    correctIndex: 0,
    explanation: 'Observing $X=x$ selects from existing data (selection bias may apply). Intervening $do(X=x)$ cuts $X$\'s incoming edges in the causal graph, forcing $X$ externally. These give different distributions unless $X$ has no confounders.',
    realWorld: 'A drug trial: observing who takes the drug (self-selection) vs. randomly assigning the drug (intervention). Only the latter estimates the causal effect.',
    hint: 'Observing that people who carry lighters have lung cancer ≠ lighters cause cancer. Intervention breaks the confounder (smoking).',
  },
  {
    id: 10073,
    topic: 'pearl',
    difficulty: 'easy',
    question: 'In a causal DAG, a "backdoor path" from $X$ to $Y$ is:',
    options: [
      'A path from $X$ to $Y$ that begins with an arrow into $X$ (a non-causal path through confounders)',
      'A directed path from $X$ to $Y$ through a mediating variable',
      'A cycle in the graph that loops back to $X$',
      'A path blocked by a collider variable with no descendants observed',
    ],
    correctIndex: 0,
    explanation: 'Backdoor paths carry spurious correlation from confounders. The backdoor criterion: adjusting for a set $Z$ that blocks all backdoor paths from $X$ to $Y$ (without opening new paths) gives the causal effect: $P(y|do(x)) = \\sum_z P(y|x,z)P(z)$.',
    realWorld: 'In economics, instrumental variables (IV) block backdoor paths when direct adjustment is impossible — used to estimate causal effects of education on income.',
    hint: 'Confounders create backdoor paths — common causes of both X and Y that mimic causation.',
  },
  {
    id: 10074,
    topic: 'pearl',
    difficulty: 'easy',
    question: 'The "ladder of causation" (Pearl) has three rungs. From lowest to highest:',
    options: [
      'Association (seeing/correlating), Intervention (doing), Counterfactuals (imagining)',
      'Correlation, Regression, Structural Equations',
      'Description, Prediction, Prescription',
      'Bayesian inference, Maximum likelihood, Causal discovery',
    ],
    correctIndex: 0,
    explanation: 'Rung 1: Association — $P(Y|X)$ (observational). Rung 2: Intervention — $P(Y|do(X))$ (experimental). Rung 3: Counterfactual — $P(Y_{x}|X=x\', Y=y\')$ (imagining). Most ML systems operate at Rung 1 — Pearl argues Rung 3 is needed for true intelligence.',
    realWorld: 'A Rung 3 question: "Would this patient have recovered if they had received treatment?" — counterfactual reasoning required for medical decision-making.',
    hint: 'Seeing → Doing → Imagining. Current ML only sees — it cannot do or imagine.',
  },
  {
    id: 10075,
    topic: 'pearl',
    difficulty: 'hard',
    question: 'D-separation in a Bayesian network: nodes $X$ and $Y$ are d-separated by set $Z$ if:',
    options: [
      'Every path between $X$ and $Y$ is blocked by $Z$ — a path is blocked if it contains a non-collider in $Z$ or a collider with no descendants in $Z$',
      'The conditional mutual information $I(X;Y|Z) = 0$ exactly',
      'No directed path exists from $X$ to $Y$ after removing all nodes in $Z$',
      'The correlation $\\text{Corr}(X, Y | Z) = 0$ for Gaussian distributions',
    ],
    correctIndex: 0,
    explanation: 'D-separation encodes conditional independence in graphical models. A collider (→Z←) blocks a path when NOT observed and opens it when observed (or its descendants are observed). This is the key to reading off independences from a DAG without computing distributions.',
    realWorld: 'Pearl\'s d-separation is used in causal discovery algorithms (PC algorithm, FCI) to recover causal structure from observational data.',
    hint: 'Colliders behave opposite to non-colliders: observing a collider opens its path; not observing a non-collider opens it.',
  },
  {
    id: 10076,
    topic: 'pearl',
    difficulty: 'hard',
    question: 'The front-door criterion (Pearl) allows causal identification when:',
    options: [
      'There is a mediator $M$ between $X$ and $Y$ that (1) captures all of $X$\'s effect on $Y$, (2) has no unblocked backdoor paths from $X$, and (3) all backdoor paths from $M$ to $Y$ are blocked by $X$',
      'All confounders between $X$ and $Y$ are observed and can be adjusted for',
      'The instrument variable satisfies relevance, exclusion restriction, and monotonicity',
      'A randomized experiment is available for the $X \\to M$ pathway only',
    ],
    correctIndex: 0,
    explanation: 'The front-door formula: $P(y|do(x)) = \\sum_m P(m|x) \\sum_{x\'} P(y|m,x\') P(x\')$. This allows causal identification even with unmeasured confounders between $X$ and $Y$, using only observational data — provided the mediator $M$ exists.',
    realWorld: 'Pearl used the example of smoking ($X$) → tar deposits ($M$) → cancer ($Y$) with unmeasured genetic confounders between smoking and cancer.',
    hint: 'Route through the mediator to bypass unmeasured confounders — a clever two-step observational trick.',
  },
  {
    id: 10077,
    topic: 'pearl',
    difficulty: 'hard',
    question: 'Structural Causal Models (SCMs) represent variables as:',
    options: [
      '$X_i = f_i(\\text{Pa}(X_i), U_i)$ where $U_i$ are independent exogenous noise variables and $f_i$ are structural equations',
      'Conditional probability tables in a Bayesian network',
      'Linear combinations of parent variables with Gaussian noise',
      'Potential outcomes $Y(1)$ and $Y(0)$ for treated and control conditions',
    ],
    correctIndex: 0,
    explanation: 'An SCM is a set of structural equations where each variable is a deterministic function of its parents and an independent noise term. This supports all three rungs: observational ($P$), interventional ($do$), and counterfactual (fixing $U_i$) reasoning.',
    realWorld: 'SCMs enable algorithmic recourse: "What would I need to change about my loan application to get approved?" — a counterfactual question requiring SCM structure.',
    hint: 'Each structural equation is a mechanism — interventions change equations; counterfactuals fix noise variables.',
  },
  {
    id: 10078,
    topic: 'pearl',
    difficulty: 'sota',
    question: 'The do-calculus (Pearl 1995) provides three rules for manipulating $P(y|do(x), z)$. Rule 2 (action/observation exchange) states:',
    options: [
      '$P(y|do(x), do(z), w) = P(y|do(x), z, w)$ when $Z$ is d-separated from $Y$ by $(X \\cup W)$ in $G_{\\overline{X}\\underline{Z}}$ (graph with $X$\'s incoming and $Z$\'s outgoing edges removed)',
      '$P(y|do(x), z) = P(y|do(x))$ when $Z$ is independent of $Y$ marginally',
      '$P(y|do(x), do(z)) = P(y|do(x)) P(y|do(z))$ when $X$ and $Z$ are independent interventions',
      '$P(y|do(x), z) = P(y|x, z)$ when no backdoor paths exist between $X$ and $Y$',
    ],
    correctIndex: 0,
    explanation: 'Rule 2 allows replacing an observation of $Z$ with an intervention on $Z$ (or vice versa) under specific graphical conditions. Together, the three rules are complete — any identifiable causal quantity can be computed using do-calculus.',
    realWorld: 'Do-calculus completeness (Shpitser & Pearl 2006) means a causal query is identifiable from observational data if and only if the do-calculus rules can derive it.',
    hint: 'The three rules tell you when you can convert between observations and interventions in the formula.',
  },
  {
    id: 10079,
    topic: 'pearl',
    difficulty: 'sota',
    question: 'Average Treatment Effect (ATE) vs. Average Treatment Effect on the Treated (ATT) differ because:',
    options: [
      'ATE = $E[Y(1) - Y(0)]$ averages over the whole population; ATT = $E[Y(1) - Y(0) | T=1]$ averages only over those who received treatment — these can differ when effects are heterogeneous',
      'ATE uses randomized data; ATT uses observational data with propensity score weighting',
      'ATE requires positivity assumption; ATT does not because we only need $P(T=0|X) > 0$',
      'ATT equals ATE only in completely randomized experiments with no effect modification',
    ],
    correctIndex: 0,
    explanation: 'ATE is the causal effect for the whole population. ATT asks: "For people who actually got treatment, what was the average effect?" These differ when treated individuals differ systematically from controls. ATT requires weaker overlap assumptions.',
    realWorld: 'Job training programs: ATE estimates effect on everyone; ATT estimates effect on those who actually enrolled — policy-relevant since the program only targets participants.',
    hint: 'ATE is about everyone; ATT is only about those who actually received treatment — different populations.',
  },
  {
    id: 10080,
    topic: 'pearl',
    difficulty: 'sota',
    question: 'Pearl\'s critique of deep learning argues that neural networks are limited to Rung 1 (association) because:',
    options: [
      'They optimize $P(Y|X)$ from observational data and cannot represent intervention distributions $P(Y|do(X))$ without causal structure embedded explicitly',
      'Neural networks cannot approximate functions beyond polynomial complexity',
      'Backpropagation is non-causal because gradients flow backward',
      'Large language models conflate correlation with causation in training data',
    ],
    correctIndex: 0,
    explanation: 'Pearl argues that $P(Y|X)$ cannot distinguish causation from correlation — training on observational data cannot identify $P(Y|do(X))$ without causal assumptions. Deep learning systems may learn spurious correlations that fail under distribution shift (interventions).',
    realWorld: 'COVID models trained on pre-pandemic data failed under interventions (lockdowns changed behavior). Causal ML aims to build models robust to such interventional distribution shifts.',
    hint: 'A model trained on patterns cannot tell whether X causes Y or they share a common cause — it only sees the correlation.',
  },
];
