import type { Question } from '../types';

export const juergenSchmidhuberQuestions: Question[] = [
  {
    id: 12601,
    topic: 'juergen-schmidhuber',
    difficulty: 'easy',
    question: 'Jürgen Schmidhuber\'s most impactful invention is:',
    options: [
      'Long Short-Term Memory (LSTM) — a recurrent architecture that solves the vanishing gradient problem with gating mechanisms',
      'The transformer architecture used in GPT models',
      'Convolutional neural networks for image recognition',
      'Generative adversarial networks (GANs)',
    ],
    correctIndex: 0,
    explanation: 'LSTM (1997, with Hochreiter) introduced input, forget, and output gates that control information flow, solving the vanishing gradient problem that plagued vanilla RNNs. The cell state acts as a "conveyor belt" for long-range information.',
    realWorld: 'LSTMs powered Google Translate, Siri\'s speech recognition, and Amazon Alexa before transformers took over. They remain widely used in time-series forecasting and music generation.',
    hint: 'Three gates (input, forget, output) control what the network remembers and forgets.',
  },
  {
    id: 12602,
    topic: 'juergen-schmidhuber',
    difficulty: 'easy',
    question: 'The LSTM cell state update equation $c_t = f_t \\odot c_{t-1} + i_t \\odot \\tilde{c}_t$ means:',
    options: [
      'The new cell state is a mix of the old state (scaled by the forget gate) plus new candidate information (scaled by the input gate)',
      'The cell state is completely replaced at every timestep',
      'Only the forget gate determines the cell state',
      'The cell state is the simple average of all previous states',
    ],
    correctIndex: 0,
    explanation: 'The forget gate $f_t$ decides how much old information to keep (element-wise multiply), while the input gate $i_t$ decides how much new candidate information $\\tilde{c}_t$ to add. This selective memory is what makes LSTMs powerful.',
    realWorld: 'This gating mechanism is why LSTMs can remember relevant context over hundreds of timesteps — essential for understanding long documents or multi-turn conversations.',
    hint: 'The ⊙ symbol means element-wise multiplication — each dimension is independently gated.',
  },
  {
    id: 12603,
    topic: 'juergen-schmidhuber',
    difficulty: 'hard',
    question: 'Schmidhuber\'s work on "Formal Theory of Creativity" proposes that:',
    options: [
      'An agent should be intrinsically motivated to find novel patterns that compress its world model — curiosity as compression progress',
      'Creativity is purely random and cannot be formalized',
      'Only humans can be creative; machines can only memorize',
      'Creativity requires quantum randomness in neural computations',
    ],
    correctIndex: 0,
    explanation: 'Schmidhuber formalized curiosity as the drive to discover new regularities that improve data compression. An agent finds "beauty" in patterns that yield maximum compression progress — connecting aesthetics, science, and AI.',
    realWorld: 'This framework inspired intrinsic motivation in RL (curiosity-driven exploration) used in game-playing agents and robots that explore environments without external rewards.',
    hint: 'Curiosity = finding patterns that let you compress your experience more efficiently.',
  },
  {
    id: 12604,
    topic: 'juergen-schmidhuber',
    difficulty: 'hard',
    question: 'Schmidhuber argues LSTMs solve the vanishing gradient problem because:',
    options: [
      'The cell state provides an uninterrupted gradient highway — the forget gate\'s multiplicative path allows gradients to flow unchanged across many timesteps',
      'They use larger learning rates than vanilla RNNs',
      'They have fewer parameters than standard RNNs',
      'They replace backpropagation with evolution strategies',
    ],
    correctIndex: 0,
    explanation: 'When the forget gate is close to 1, the gradient flows through the cell state virtually unchanged (the "constant error carousel"). This linear self-connection prevents the exponential gradient decay/explosion of vanilla RNNs.',
    realWorld: 'Before LSTMs, RNNs could only learn dependencies spanning ~10 timesteps. LSTMs extended this to 1000+, enabling practical speech recognition and machine translation.',
    hint: 'Think of the cell state as a highway where gradients can travel without being repeatedly multiplied by small weights.',
  },
  {
    id: 12605,
    topic: 'juergen-schmidhuber',
    difficulty: 'sota',
    question: 'Schmidhuber\'s concept of "self-referential" neural networks involves:',
    options: [
      'Networks that can modify their own weights during inference by learning weight-update rules — a form of learned meta-learning',
      'Networks that simply predict their own outputs recursively',
      'Networks that are trained on their own source code',
      'Standard recurrent networks with skip connections',
    ],
    correctIndex: 0,
    explanation: 'Self-referential networks contain weight matrices that encode rules for modifying the network\'s own weights. This is a form of "learning to learn" where the meta-learning algorithm itself is learned, potentially leading to open-ended self-improvement.',
    realWorld: 'This concept prefigured modern meta-learning (MAML), in-context learning in transformers, and discussions about recursive self-improvement in AGI safety research.',
    hint: 'The network doesn\'t just process data — it rewrites its own learning algorithm.',
  },
];
