import type { Question } from '../types';

export const kaiFuLeeQuestions: Question[] = [
  {
    id: 12501,
    topic: 'kai-fu-lee',
    difficulty: 'easy',
    question: 'Kai-Fu Lee describes AI development as occurring in four waves. The correct order is:',
    options: [
      'Internet AI → Business AI → Perception AI → Autonomous AI',
      'Autonomous AI → Perception AI → Business AI → Internet AI',
      'Business AI → Internet AI → Autonomous AI → Perception AI',
      'Perception AI → Autonomous AI → Internet AI → Business AI',
    ],
    correctIndex: 0,
    explanation: 'Lee\'s "AI Superpowers" framework identifies four sequential waves: Internet AI (recommendation engines), Business AI (enterprise optimization), Perception AI (vision/speech), and Autonomous AI (self-driving, robotics).',
    realWorld: 'This framework helps investors and policymakers understand which industries will be disrupted next — we\'re currently in the transition from Wave 3 to Wave 4.',
    hint: 'It starts with the simplest data (clicks) and progresses to the most complex (physical world).',
  },
  {
    id: 12502,
    topic: 'kai-fu-lee',
    difficulty: 'easy',
    question: 'Before becoming an AI investor, Kai-Fu Lee made foundational contributions to:',
    options: [
      'Speech recognition — building one of the first speaker-independent continuous speech systems using HMMs',
      'Computer vision — creating the first face detection algorithm',
      'Natural language processing — inventing the transformer architecture',
      'Robotics — building the first autonomous humanoid robot',
    ],
    correctIndex: 0,
    explanation: 'Lee\'s PhD work at Carnegie Mellon produced Sphinx, one of the first large-vocabulary speaker-independent speech recognition systems, using Hidden Markov Models (HMMs).',
    realWorld: 'His speech recognition work laid groundwork for Siri, Alexa, and every voice assistant today. He later led Google China and now invests in AI via Sinovation Ventures.',
    hint: 'His early academic work was in making computers understand human speech.',
  },
  {
    id: 12503,
    topic: 'kai-fu-lee',
    difficulty: 'hard',
    question: 'Lee argues China\'s AI advantage over the US comes primarily from:',
    options: [
      'Massive data generation from 1B+ mobile users, aggressive entrepreneurship, and government support — not algorithmic superiority',
      'Superior AI algorithms developed by Chinese researchers',
      'Cheaper hardware manufacturing and chip design',
      'More advanced quantum computing infrastructure',
    ],
    correctIndex: 0,
    explanation: 'Lee\'s thesis is that AI\'s value comes from data and implementation, not algorithmic breakthroughs. China\'s mobile-first economy generates vast behavioral data, and its entrepreneurs iterate faster with fewer regulatory constraints.',
    realWorld: 'WeChat, TikTok, and Alibaba generate more transactional AI training data than their Western equivalents, validating Lee\'s data-centric AI thesis.',
    hint: 'It\'s not about who has better algorithms — it\'s about who has more data and faster execution.',
  },
  {
    id: 12504,
    topic: 'kai-fu-lee',
    difficulty: 'hard',
    question: 'Hidden Markov Models (HMMs), central to Lee\'s speech recognition work, model speech as:',
    options: [
      'A sequence of hidden phonetic states emitting observable acoustic features, with transition probabilities between states',
      'A single neural network that directly maps audio waveforms to text',
      'A rule-based grammar system matching audio patterns to words',
      'A reinforcement learning agent maximizing transcription accuracy',
    ],
    correctIndex: 0,
    explanation: 'HMMs treat speech as a Markov chain of hidden states (phonemes) where each state emits observable acoustic vectors. The Viterbi algorithm finds the most likely state sequence given observations.',
    realWorld: 'HMMs dominated speech recognition from 1985–2012 before being replaced by deep learning. Lee\'s Sphinx system proved HMMs could work at scale.',
    hint: 'The "hidden" part refers to phoneme states you can\'t directly observe — you only hear acoustic features.',
  },
  {
    id: 12505,
    topic: 'kai-fu-lee',
    difficulty: 'sota',
    question: 'Lee\'s Sinovation-backed models compete with Western LLMs by leveraging:',
    options: [
      'Mixture-of-Experts with Chinese-language-optimized tokenizers and data pipelines tuned for CJK character distributions',
      'Exact replicas of GPT-4 architecture with no modifications',
      'Purely symbolic AI systems without neural networks',
      'Quantum computing for all training runs',
    ],
    correctIndex: 0,
    explanation: 'Chinese LLMs like Yi and DeepSeek use MoE architectures with tokenizers optimized for CJK characters (which have different byte distributions than Latin text), plus training data enriched with Chinese web, academic, and code corpora.',
    realWorld: 'DeepSeek-R1 and Yi-34B demonstrate that non-US labs can match frontier models by optimizing for their linguistic and data advantages rather than simply copying Western architectures.',
    hint: 'Language-specific optimization matters — Chinese characters need different tokenization strategies.',
  },
];
