import type { Question } from '../types';

export const kashiwaraQuestions: Question[] = [
  {
    id: 12101,
    topic: 'kashiwara',
    difficulty: 'easy',
    question: 'Masaki Kashiwara won the Abel Prize (2025) for his foundational contributions to:',
    options: [
      'Algebraic analysis and D-module theory — extending calculus to algebraic and geometric settings',
      'Fluid dynamics and turbulence modeling',
      'Combinatorial optimization and graph algorithms',
      'Statistical mechanics and phase transitions',
    ],
    correctIndex: 0,
    explanation: 'Kashiwara developed D-module theory, which studies systems of linear partial differential equations algebraically. This unified analysis, algebra, and geometry in profound ways.',
    realWorld: 'D-modules are used in mathematical physics (quantum field theory), representation theory, and the geometric Langlands program — one of the deepest research programs in modern mathematics.',
    hint: 'He treated differential equations as algebraic objects, opening up entirely new ways to solve and understand them.',
  },
  {
    id: 12102,
    topic: 'kashiwara',
    difficulty: 'easy',
    question: 'Kashiwara\'s crystal bases revolutionized representation theory by:',
    options: [
      'Providing a combinatorial framework to study quantum group representations at q → 0',
      'Classifying all finite simple groups using crystal structures',
      'Computing character tables of symmetric groups using ice models',
      'Solving the word problem for braid groups',
    ],
    correctIndex: 0,
    explanation: 'Crystal bases emerge as quantum group representations "crystallize" when the deformation parameter q → 0. They have beautiful combinatorial structure (crystal graphs) that makes representation theory computable.',
    realWorld: 'Crystal bases have applications in statistical mechanics (exactly solvable lattice models), algebraic combinatorics, and even in categorification programs connecting algebra to topology.',
    hint: 'At q = 0, quantum group representations become rigid combinatorial objects — "crystals" — that are much easier to work with.',
  },
  {
    id: 12103,
    topic: 'kashiwara',
    difficulty: 'hard',
    question: 'The Kazhdan–Lusztig conjecture, proved by Kashiwara (and independently Brylinski–Beilinson), connects:',
    options: [
      'Characters of highest weight modules for semisimple Lie algebras to intersection cohomology of Schubert varieties',
      'The dimension of modular representations to the order of the Weyl group',
      'Hecke algebra traces to knot invariants',
      'Verma module embeddings to root system combinatorics',
    ],
    correctIndex: 0,
    explanation: 'The proof uses the Riemann–Hilbert correspondence (D-modules ↔ perverse sheaves) to translate a representation theory question into a geometric one about intersection cohomology. This was a triumph of geometric methods.',
    realWorld: 'The Kazhdan–Lusztig polynomials that emerged have become central in geometric representation theory, with connections to knot invariants (Khovanov homology) and categorification.',
    hint: 'The key idea: D-modules on flag varieties correspond to representations, and their singularities encode multiplicities.',
  },
  {
    id: 12104,
    topic: 'kashiwara',
    difficulty: 'hard',
    question: 'Kashiwara\'s Riemann–Hilbert correspondence establishes an equivalence between:',
    options: [
      'Regular holonomic D-modules and perverse sheaves (constructible sheaves with cohomological conditions)',
      'Vector bundles and coherent sheaves on projective varieties',
      'Differential forms and singular chains on manifolds',
      'Harmonic functions and holomorphic functions on Riemann surfaces',
    ],
    correctIndex: 0,
    explanation: 'This deep equivalence says that systems of linear PDEs with regular singularities correspond bijectively to topological objects (perverse sheaves). It\'s a vast generalization of the classical Riemann–Hilbert problem for ODEs.',
    realWorld: 'The Riemann–Hilbert correspondence is a key tool in the geometric Langlands program and has influenced the development of homological mirror symmetry in string theory.',
    hint: 'It generalizes the classical result that a linear ODE is determined by its monodromy — local differential equations ↔ global topology.',
  },
  {
    id: 12105,
    topic: 'kashiwara',
    difficulty: 'sota',
    question: 'Kashiwara\'s work on microlocal analysis studies D-modules via their characteristic variety in the cotangent bundle. The fundamental result is:',
    options: [
      'The characteristic variety of a holonomic D-module is Lagrangian — its dimension equals the dimension of the base space',
      'The characteristic variety is always smooth',
      'Holonomic D-modules have infinite-dimensional solution spaces',
      'The characteristic variety determines the D-module up to isomorphism',
    ],
    correctIndex: 0,
    explanation: 'Holonomic D-modules are those whose characteristic variety (the "microlocal support") is Lagrangian in T*X. This constraint is what makes them "finite-dimensional" in a precise sense — their solution spaces are finite-dimensional on each fiber.',
    realWorld: 'Microlocal analysis is fundamental in modern PDE theory, semiclassical analysis (quantum-classical correspondence), and has recently been applied to deep learning theory for understanding neural network expressivity.',
    hint: 'Lagrangian means half-dimensional and isotropic — the tightest geometric constraint on the support.',
  },
];
