import type { Question } from '../types';

export const kennethArrowQuestions: Question[] = [
  { id: 20900, topic: 'kenneth-arrow', difficulty: 'sota', question: "Arrow's Impossibility Theorem proves that no ranked-choice voting system with ≥3 alternatives can simultaneously satisfy which set of conditions?", options: ['Unrestricted domain, Pareto efficiency, IIA, and non-dictatorship', 'Transitivity, completeness, continuity, and monotonicity', 'Anonymity, neutrality, positive responsiveness, and unanimity', 'Strategy-proofness, onto, one-to-one, and non-manipulability'], correctIndex: 0, explanation: "Arrow proved no social welfare function over ≥3 alternatives can satisfy all four conditions simultaneously.", realWorld: "Arrow's theorem shapes how we design elections, committee decision-making, and AI alignment preference aggregation.", hint: "Think about what 'fairness' conditions a perfect voting system should satisfy." },
  { id: 20901, topic: 'kenneth-arrow', difficulty: 'sota', question: "In the Arrow-Debreu model of general equilibrium, existence of equilibrium is proven using which fixed-point theorem?", options: ["Kakutani's fixed-point theorem", "Banach's contraction mapping theorem", "Brouwer's fixed-point theorem applied directly", "Tarski's lattice fixed-point theorem"], correctIndex: 0, explanation: "Arrow and Debreu used Kakutani's fixed-point theorem (a set-valued generalization of Brouwer's) to prove existence of competitive equilibrium.", realWorld: "This theorem underpins the mathematical proof that free markets can theoretically reach equilibrium.", hint: "The proof needs a generalization that handles set-valued (correspondence) mappings." },
  { id: 20902, topic: 'kenneth-arrow', difficulty: 'sota', question: "Which condition in Arrow's theorem states that society's ranking of two alternatives depends only on individuals' rankings of those two?", options: ['Independence of Irrelevant Alternatives (IIA)', 'Pareto efficiency', 'Non-dictatorship', 'Unrestricted domain'], correctIndex: 0, explanation: "IIA requires the social ordering between any pair depends only on individual preferences over that pair.", realWorld: "IIA violations explain why adding a third-party candidate can flip election outcomes between the original two.", hint: "This condition says 'irrelevant' third options shouldn't change the ranking between two candidates." },
  { id: 20903, topic: 'kenneth-arrow', difficulty: 'sota', question: "Arrow's theorem applies to ordinal rankings. Which relaxation allows escape from the impossibility?", options: ['Allowing cardinal utility with interpersonal comparability', 'Restricting to exactly two candidates', 'Allowing only dictatorial rules', 'Removing the Pareto condition'], correctIndex: 0, explanation: "If we allow cardinal utilities with interpersonal comparisons (e.g., utilitarian welfare), the impossibility dissolves.", realWorld: "This is why cost-benefit analysis (which uses dollar values as cardinal utility) can aggregate preferences where voting cannot.", hint: "Arrow's proof exploits the fact that rankings contain no intensity information." },
  { id: 20904, topic: 'kenneth-arrow', difficulty: 'sota', question: 'At what age did Kenneth Arrow win the Nobel Memorial Prize in Economics, making him the youngest laureate in the field?', options: ['51', '45', '39', '58'], correctIndex: 0, explanation: "Arrow won the 1972 Nobel at age 51, the youngest economics laureate at the time.", realWorld: "His work on social choice theory remains the mathematical foundation of welfare economics and voting theory.", hint: "He won it in 1972, and was born in 1921." },
];
