import type { Question } from '../types';

export const kiyosiItoQuestions: Question[] = [
  {
    id: 20780,
    topic: 'kiyosi-ito',
    difficulty: 'hard',
    question: 'Itô\'s Lemma gives the differential of $f(X_t)$ where $X_t$ follows an Itô process. The key difference from the classical chain rule is the presence of:',
    options: ['A $\\frac{1}{2}f\'\'(X_t)(dX_t)^2$ second-order correction term', 'A third derivative term', 'No difference from classical calculus', 'An integral term'],
    correctIndex: 0,
    explanation: 'Because Brownian motion has quadratic variation $(dW_t)^2 = dt$, the second-order term survives — unlike in ordinary calculus where $(dx)^2 = 0$.',
    realWorld: 'Itô\'s Lemma is the mathematical engine behind the Black-Scholes formula — every options price on Wall Street depends on it.',
    hint: 'In stochastic calculus, $(dW)^2 \\neq 0$ — this changes everything.',
  },
  {
    id: 20781,
    topic: 'kiyosi-ito',
    difficulty: 'hard',
    question: 'In the Itô integral $\\int_0^T f(t)\\,dW_t$, the integrand is evaluated at which point of each partition interval?',
    options: ['The left endpoint (non-anticipating/adapted)', 'The right endpoint', 'The midpoint (Stratonovich convention)', 'A random point'],
    correctIndex: 0,
    explanation: 'Itô integration evaluates at the left endpoint, making the integral a martingale and ensuring the integrand doesn\'t "see the future" — essential for financial modeling.',
    realWorld: 'The Stratonovich integral (midpoint) is used in physics; the Itô integral (left endpoint) is used in finance — different conventions for different needs.',
    hint: 'The integrand must be "adapted" — it can only use information available at the current time.',
  },
  {
    id: 20782,
    topic: 'kiyosi-ito',
    difficulty: 'sota',
    question: 'The Itô isometry states that $E\\left[\\left(\\int_0^T f\\,dW\\right)^2\\right] = \\int_0^T E[f^2]\\,dt$. This is analogous to which property in deterministic analysis?',
    options: ['Parseval\'s theorem (energy conservation in Fourier space)', 'The fundamental theorem of calculus', 'The mean value theorem', 'L\'Hôpital\'s rule'],
    correctIndex: 0,
    explanation: 'Just as Parseval\'s theorem equates time-domain and frequency-domain energy, the Itô isometry equates the variance of a stochastic integral to the integral of the variance.',
    realWorld: 'The Itô isometry is essential for computing hedge ratios and risk measures in quantitative portfolio management.',
    hint: 'It\'s an energy conservation law for stochastic integrals.',
  },
  {
    id: 20783,
    topic: 'kiyosi-ito',
    difficulty: 'sota',
    question: 'Geometric Brownian Motion $dS = \\mu S\\,dt + \\sigma S\\,dW$ models stock prices. Applying Itô\'s Lemma to $\\ln S$ yields $d(\\ln S) =$:',
    options: ['$(\\mu - \\sigma^2/2)dt + \\sigma\\,dW$', '$\\mu\\,dt + \\sigma\\,dW$', '$(\\mu + \\sigma^2/2)dt + \\sigma\\,dW$', '$\\mu S\\,dt$'],
    correctIndex: 0,
    explanation: 'The $-\\sigma^2/2$ correction is the Itô correction — log returns are normally distributed with drift $\\mu - \\sigma^2/2$, not $\\mu$.',
    realWorld: 'This correction means high-volatility assets have lower expected geometric returns than their arithmetic drift suggests — critical for portfolio optimization.',
    hint: 'The second derivative of $\\ln S$ is $-1/S^2$, which generates the correction term.',
  },
  {
    id: 20784,
    topic: 'kiyosi-ito',
    difficulty: 'easy',
    question: 'Itô\'s stochastic calculus extends ordinary calculus to handle processes driven by:',
    options: ['Brownian motion (random noise)', 'Electromagnetic fields', 'Gravitational waves', 'Quantum entanglement'],
    correctIndex: 0,
    explanation: 'Brownian motion is the mathematical model of random continuous-time noise. Itô\'s calculus provides the rules for "differentiating" and "integrating" with it.',
    realWorld: 'Without Itô calculus, there would be no Black-Scholes, no modern derivatives pricing, and no quantitative finance as we know it.',
    hint: 'The jittery, random movement first observed in pollen grains suspended in water.',
  },
];
