import type { Question } from '../types';

export const kozyrkovQuestions: Question[] = [
  {
    id: 12801,
    topic: 'kozyrkov',
    difficulty: 'easy',
    question: 'Cassie Kozyrkov founded and led which discipline at Google?',
    options: [
      'Decision Intelligence — applying data science and behavioral science to improve organizational decision-making',
      'Quantum Computing — building Google\'s quantum processors',
      'Search Quality — improving Google Search ranking algorithms',
      'Cloud Infrastructure — scaling Google Cloud Platform',
    ],
    correctIndex: 0,
    explanation: 'Kozyrkov created "Decision Intelligence" as a discipline at Google, combining statistics, behavioral economics, and management science to help teams make better decisions with data — not just build better models.',
    realWorld: 'Decision Intelligence reframes ML from "build a model" to "make a decision." This shifts focus to what matters: defining success criteria before touching data, preventing many common ML project failures.',
    hint: 'It\'s not about building better models — it\'s about making better decisions.',
  },
  {
    id: 12802,
    topic: 'kozyrkov',
    difficulty: 'easy',
    question: 'Kozyrkov\'s key insight about ML project failures is:',
    options: [
      'Most ML projects fail not from bad algorithms but from poorly defined objectives and decision criteria set before analysis begins',
      'ML projects fail because neural networks are too complex',
      'The main issue is always insufficient data quantity',
      'Projects fail due to lack of GPU compute resources',
    ],
    correctIndex: 0,
    explanation: 'Kozyrkov emphasizes that you must define your decision criteria and success metrics BEFORE looking at data. "If you don\'t know what you\'re looking for, you\'ll find something — and it\'ll be wrong."',
    realWorld: 'Companies spend millions on ML models that never deploy because nobody defined what "good enough" means upfront. Kozyrkov\'s framework prevents this by front-loading the decision design.',
    hint: 'The problem isn\'t the model — it\'s not knowing what question you\'re actually trying to answer.',
  },
  {
    id: 12803,
    topic: 'kozyrkov',
    difficulty: 'hard',
    question: 'Kozyrkov warns that A/B tests commonly fail because:',
    options: [
      'Teams peek at results early, change metrics mid-test, or fail to set stopping criteria — all forms of "p-hacking by design"',
      'A/B tests are mathematically invalid for web applications',
      'Sample sizes are always too small to detect any effect',
      'A/B tests can only work for medical trials, not tech products',
    ],
    correctIndex: 0,
    explanation: 'Common A/B test failures include: peeking at results before the planned sample size (inflates false positives), switching the primary metric when the original shows no effect, and not pre-registering the analysis plan.',
    realWorld: 'Google runs 10,000+ A/B tests per year. Kozyrkov\'s framework ensures rigor: pre-commit to metrics, sample size, and decision rules before the test starts — no moving the goalposts.',
    hint: 'The statistical validity requires committing to your analysis plan BEFORE seeing any results.',
  },
  {
    id: 12804,
    topic: 'kozyrkov',
    difficulty: 'hard',
    question: 'The distinction between correlation and causation is central to Kozyrkov\'s teaching. In ML, this means:',
    options: [
      'A model that predicts well (correlation) may not identify causal mechanisms — intervening based on correlational models can backfire catastrophically',
      'Correlation and causation are the same thing in large datasets',
      'Deep learning automatically discovers causal relationships',
      'Causation is irrelevant for practical ML applications',
    ],
    correctIndex: 0,
    explanation: 'A model might learn that ice cream sales predict drowning deaths (both correlated with hot weather). Acting on this correlation (banning ice cream) would be absurd. Kozyrkov emphasizes that prediction ≠ understanding.',
    realWorld: 'Healthcare ML models often find correlations (e.g., asthma patients have lower pneumonia mortality) that would be dangerous to act on causally — the correlation exists because asthma patients receive more aggressive treatment.',
    hint: 'Predicting outcomes accurately doesn\'t mean you understand what causes them.',
  },
  {
    id: 12805,
    topic: 'kozyrkov',
    difficulty: 'sota',
    question: 'Kozyrkov\'s "Decision Intelligence" framework structures every data decision as:',
    options: [
      'A three-step process: (1) define the decision and default action, (2) set the metric and threshold BEFORE analysis, (3) collect data and apply the pre-committed rule',
      'Training the largest possible model and using its output directly',
      'Letting stakeholders vote on what the data means',
      'Running as many statistical tests as possible and reporting the best result',
    ],
    correctIndex: 0,
    explanation: 'The framework requires pre-commitment: define what action you\'ll take, what metric will trigger it, and what threshold matters — all before touching data. This prevents confirmation bias, p-hacking, and post-hoc rationalization.',
    realWorld: 'This is essentially the scientific method applied to business: pre-register your hypothesis and decision rule, then let the data decide. It\'s the antidote to "data-driven" organizations that actually cherry-pick results.',
    hint: 'Pre-commit to your decision rule, then let the data make the call — no second-guessing allowed.',
  },
];
