import type { Question } from '../types';

export const eulerQuestions: Question[] = [
  {
    id: 11301,
    topic: 'leonhard-euler',
    difficulty: 'easy',
    question: 'Euler\'s identity $e^{i\\pi} + 1 = 0$ is considered the most beautiful in mathematics because it combines:',
    options: [
      'The five most fundamental constants: e, i, π, 1, 0 — in one equation',
      'The three operations: addition, multiplication, exponentiation',
      'The four fundamental theorems of calculus',
      'All Platonic solids in a single algebraic relationship',
    ],
    correctIndex: 0,
    explanation: 'e^{iπ} + 1 = 0 unites e (growth/calculus), i (imaginary unit/complex numbers), π (geometry/circles), 1 (multiplicative identity), and 0 (additive identity). It follows from Euler\'s formula e^{ix} = cos x + i sin x.',
    realWorld: 'Euler\'s formula is the foundation of signal processing: complex exponentials e^{iωt} are the eigenfunctions of linear time-invariant systems — every filter, modulator, and FFT uses this.',
    hint: 'Plug x = π into Euler\'s formula e^{ix} = cos(x) + i·sin(x).',
  },
  {
    id: 11302,
    topic: 'leonhard-euler',
    difficulty: 'easy',
    question: 'Euler\'s formula for polyhedra states that for any convex polyhedron:',
    options: [
      '$V - E + F = 2$ (vertices minus edges plus faces equals 2)',
      '$V + E - F = 2$',
      '$V \\cdot E / F = \\pi$',
      '$V + E + F = \\text{constant}$',
    ],
    correctIndex: 0,
    explanation: 'V - E + F = 2 holds for all convex polyhedra (and any topologically sphere-equivalent surface). The quantity χ = V - E + F is the Euler characteristic — a topological invariant fundamental to algebraic topology.',
    realWorld: '3D mesh processing in computer graphics validates mesh topology using V - E + F. Euler characteristic distinguishes surfaces: sphere (χ=2), torus (χ=0), used in shape analysis and computational topology.',
    hint: 'A cube has 8V, 12E, 6F: 8 - 12 + 6 = 2 ✓',
  },
  {
    id: 11303,
    topic: 'leonhard-euler',
    difficulty: 'easy',
    question: 'The Basel problem, solved by Euler, showed that $\\sum_{n=1}^{\\infty} \\frac{1}{n^2} =$',
    options: [
      '$\\frac{\\pi^2}{6}$',
      '$\\frac{\\pi}{4}$',
      '$\\ln(2)$',
      '$\\sqrt{2}$',
    ],
    correctIndex: 0,
    explanation: 'Euler proved ∑1/n² = π²/6 by comparing the Taylor series of sin(x)/x with its infinite product over roots. This connected number theory (integer sums) with geometry (π) in a shocking way.',
    realWorld: 'The Riemann zeta function ζ(s) = ∑1/nˢ generalizes this. ζ(2) = π²/6 is used in quantum field theory calculations and the distribution of prime numbers.',
    hint: 'Euler showed sin(x)/x has roots at ±π, ±2π, ... which constrains the sum of squares of roots.',
  },
  {
    id: 11304,
    topic: 'leonhard-euler',
    difficulty: 'easy',
    question: 'Graph theory was invented by Euler to solve the Königsberg bridge problem. His key insight was:',
    options: [
      'An Eulerian path (traversing all edges once) exists iff at most 2 vertices have odd degree',
      'Any connected planar graph has a Hamiltonian cycle',
      'The chromatic number of any planar graph is at most 4',
      'Every tree with n vertices has exactly n-1 edges',
    ],
    correctIndex: 0,
    explanation: 'Königsberg has 4 landmasses all with odd degree — so no Eulerian path exists. Euler proved the degree parity condition and invented graph theory in doing so (1736), solving the first problem in combinatorial optimization.',
    realWorld: 'Route optimization (postal delivery, garbage collection, circuit board etching) requires Eulerian paths. DNA sequencing assembly uses Eulerian path algorithms on de Bruijn graphs.',
    hint: 'If you enter a node, you must be able to leave — odd-degree nodes are dead ends.',
  },
  {
    id: 11305,
    topic: 'leonhard-euler',
    difficulty: 'hard',
    question: 'Euler\'s product formula connects the zeta function to primes: $\\zeta(s) = \\prod_{p \\text{ prime}} \\frac{1}{1-p^{-s}}$. This implies:',
    options: [
      'The distribution of primes is encoded in the analytic structure of a complex function',
      'Every integer is prime with probability 1/ζ(s)',
      'The sum of prime reciprocals converges to ζ(1)',
      'The nth prime is approximately n log n for all n',
    ],
    correctIndex: 0,
    explanation: 'The Euler product reformulates ∑1/nˢ as a product over primes via unique factorization. The zeros of ζ(s) (Riemann Hypothesis) then control prime distribution — linking analysis, primes, and complex function theory.',
    realWorld: 'Cryptographic prime generation, sieve algorithms, and prime counting functions all rely on analytic number theory rooted in Euler\'s product formula.',
    hint: 'Unique prime factorization means every integer term 1/nˢ appears exactly once when the product is expanded.',
  },
  {
    id: 11306,
    topic: 'leonhard-euler',
    difficulty: 'hard',
    question: 'The Euler-Lagrange equation $\\frac{\\partial L}{\\partial q} - \\frac{d}{dt}\\frac{\\partial L}{\\partial \\dot{q}} = 0$ describes:',
    options: [
      'The stationary path of an action functional — the trajectory a physical system follows',
      'The gradient of the Lagrangian with respect to generalized coordinates',
      'The equilibrium condition for conservative force fields',
      'The Hamiltonian flow in phase space',
    ],
    correctIndex: 0,
    explanation: 'By the calculus of variations, the physical path minimizes the action S = ∫L dt. Setting δS = 0 yields the Euler-Lagrange equations. This reformulation of mechanics is coordinate-free and generalizes to field theory.',
    realWorld: 'Path planning in robotics uses variational principles. Reinforcement learning\'s policy gradient theorem is a stochastic analog of the Euler-Lagrange equation for expected return.',
    hint: 'δS = 0 — varying the path and requiring zero first-order change gives the equation of motion.',
  },
  {
    id: 11307,
    topic: 'leonhard-euler',
    difficulty: 'hard',
    question: 'Euler\'s totient function $\\phi(n)$ counts integers up to $n$ coprime to $n$. For prime $p$: $\\phi(p) = p-1$. Euler\'s theorem states:',
    options: [
      '$a^{\\phi(n)} \\equiv 1 \\pmod{n}$ for $\\gcd(a,n)=1$',
      '$a^n \\equiv a \\pmod{n}$ for all integers $a$',
      '$\\phi(ab) = \\phi(a) + \\phi(b)$ for all $a, b$',
      '$a^{\\phi(n)} \\equiv 0 \\pmod{\\phi(n)}$',
    ],
    correctIndex: 0,
    explanation: 'Euler\'s theorem generalizes Fermat\'s little theorem to composite moduli. For n = pq (RSA), φ(pq) = (p-1)(q-1), and a^{φ(n)} ≡ 1 means encryption/decryption are inverses mod n.',
    realWorld: 'RSA encryption is entirely built on Euler\'s theorem: encrypting with e and decrypting with d where ed ≡ 1 (mod φ(n)) works because a^{ed} = a^{1+kφ(n)} ≡ a.',
    hint: 'For RSA with n = pq: knowing φ(n) = (p-1)(q-1) lets you invert the exponent.',
  },
  {
    id: 11308,
    topic: 'leonhard-euler',
    difficulty: 'sota',
    question: 'The Euler characteristic in higher dimensions satisfies $\\chi = \\sum_k (-1)^k \\beta_k$ where $\\beta_k$ are Betti numbers. For a torus $\\mathbb{T}^2$:',
    options: [
      '$\\chi = 0$, since $\\beta_0=1, \\beta_1=2, \\beta_2=1$, giving $1-2+1=0$',
      '$\\chi = 2$, same as the sphere',
      '$\\chi = -2$, since the torus has two holes',
      '$\\chi = 1$, since the torus is connected',
    ],
    correctIndex: 0,
    explanation: 'The torus has β₀=1 (connected), β₁=2 (two independent 1-cycles: longitude and latitude), β₂=1 (one 2-cycle: the surface itself). χ = 1-2+1 = 0. The Euler characteristic distinguishes topological spaces and drives persistent homology in TDA.',
    realWorld: 'Topological Data Analysis (TDA) computes Euler characteristics and Betti numbers of data point clouds to detect loops, voids, and connected components in high-dimensional datasets.',
    hint: 'The torus has two independent loops you cannot shrink to a point — that gives β₁ = 2.',
  },
  {
    id: 11309,
    topic: 'leonhard-euler',
    difficulty: 'sota',
    question: 'Euler\'s method for ODEs approximates the solution to $y\' = f(t,y)$ by:',
    options: [
      '$y_{n+1} = y_n + h f(t_n, y_n)$ — first-order, global error $O(h)$',
      '$y_{n+1} = y_n + h f(t_{n+1}, y_{n+1})$ — implicit, unconditionally stable',
      '$y_{n+1} = y_{n-1} + 2h f(t_n, y_n)$ — leapfrog, second-order',
      '$y_{n+1} = y_n + h[f(t_n,y_n) + f(t_{n+1},y_{n+1})]/2$ — trapezoidal, second-order',
    ],
    correctIndex: 0,
    explanation: 'Euler\'s explicit method uses the current slope to step forward. Global error is O(h) — doubling steps halves error. It\'s unstable for stiff equations (e.g., requires tiny h for fast-decaying modes).',
    realWorld: 'Neural ODE frameworks (Chen et al., 2018) use adaptive-step ODE solvers (Dormand-Prince) — Euler\'s method is the conceptual baseline from which all adaptive solvers are built.',
    hint: 'Forward Euler: take a step of size h in the direction of the current derivative.',
  },
  {
    id: 11310,
    topic: 'leonhard-euler',
    difficulty: 'sota',
    question: 'Euler\'s formula $e^{i\\theta} = \\cos\\theta + i\\sin\\theta$ makes complex exponentials the natural basis for the Discrete Fourier Transform. The DFT matrix $F$ satisfies:',
    options: [
      '$F^* F = N \\cdot I$, making $\\frac{1}{\\sqrt{N}}F$ unitary — the DFT is an orthonormal change of basis',
      '$F^2 = I$, making the DFT its own inverse',
      '$F = F^T$, making the DFT matrix symmetric',
      '$\\det(F) = N^N$, reflecting the N-fold periodicity',
    ],
    correctIndex: 0,
    explanation: 'The DFT matrix has entries F_{jk} = e^{-2πijk/N}. Since these are orthogonal complex exponentials, F*F = NI, and (1/√N)F is unitary. The FFT computes this in O(N log N) using the factorization of F into sparse matrices.',
    realWorld: 'Every audio codec (MP3, AAC), image codec (JPEG), 5G/WiFi OFDM modulation, and spectrogram uses the FFT — Euler\'s formula disguised as an O(N log N) algorithm.',
    hint: 'Unitary matrices preserve inner products — the DFT is an isometry from time domain to frequency domain.',
  },
];
