import type { Question } from '../types';

export const kantorovichQuestions: Question[] = [
  { id: 20930, topic: 'kantorovich', difficulty: 'sota', question: "Kantorovich invented linear programming in 1939 to solve which Soviet industrial problem?", options: ['Optimizing plywood production across multiple machine types', 'Scheduling Trans-Siberian Railway logistics', 'Allocating steel quotas among factories', 'Minimizing military aircraft fuel consumption'], correctIndex: 0, explanation: "He developed LP to optimally assign raw materials to different plywood cutting machines.", realWorld: "Linear programming now powers airline scheduling, supply chains, and portfolio optimization globally.", hint: "Think about allocating resources across different machines to maximize output." },
  { id: 20931, topic: 'kantorovich', difficulty: 'sota', question: "The fundamental theorem of LP states that if an optimal solution exists, it occurs at:", options: ['A vertex of the feasible polytope', 'The centroid of the feasible region', 'An interior point of the feasible set', 'The intersection of all constraints'], correctIndex: 0, explanation: "Optimality is attained at a vertex — this is why the simplex method walks along vertices.", realWorld: "The simplex algorithm exploits this by efficiently jumping between vertices of high-dimensional polytopes.", hint: "A linear function over a convex shape is maximized at a corner." },
  { id: 20932, topic: 'kantorovich', difficulty: 'sota', question: "Soviet ideologues attacked Kantorovich's work because:", options: ['His shadow prices implied market-like valuation, contradicting Marxist labor theory of value', 'He refused to share algorithms with the military', 'His methods were too computationally expensive', 'He advocated free-market capitalism'], correctIndex: 0, explanation: "His dual variables revealed implicit market prices for resources — dangerously close to capitalist price theory.", realWorld: "The irony: optimal central planning mathematically requires the same price signals that markets produce.", hint: "The dual problem produces 'prices' for scarce resources — politically dangerous in the USSR." },
  { id: 20933, topic: 'kantorovich', difficulty: 'sota', question: "The dual of a minimization LP with ≥ constraints is:", options: ['A maximization problem with ≤ constraints', 'A minimization problem with = constraints', 'A maximization with ≥ constraints', 'Another minimization with ≤ constraints'], correctIndex: 0, explanation: "LP duality flips min↔max and ≥↔≤. Strong duality guarantees equal optimal values.", realWorld: "Duality is used in economics to derive equilibrium prices from resource allocation problems.", hint: "Duality swaps the direction of both optimization and constraints." },
  { id: 20934, topic: 'kantorovich', difficulty: 'sota', question: "Kantorovich shared the 1975 Nobel Prize with:", options: ['Tjalling Koopmans', 'George Dantzig', 'Paul Samuelson', 'Kenneth Arrow'], correctIndex: 0, explanation: "He shared it with Koopmans for optimal resource allocation theory. Dantzig (simplex inventor) was notably excluded.", realWorld: "The Nobel recognized that optimal planning and market economics share the same mathematical foundations.", hint: "His co-laureate was an American who independently developed activity analysis." },
];
