import type { Question } from '../types';

export const lorenzQuestions: Question[] = [
  {
    id: 20420,
    topic: 'lorenz',
    difficulty: 'hard',
    question: 'The Lorenz system $\\dot{x}=\\sigma(y-x),\\; \\dot{y}=x(\\rho-z)-y,\\; \\dot{z}=xy-\\beta z$ exhibits chaos for $\\sigma=10, \\beta=8/3, \\rho=28$. What geometric object does the trajectory trace?',
    options: ['A strange attractor', 'A limit cycle', 'A fixed point', 'A torus'],
    correctIndex: 0,
    explanation: 'The Lorenz attractor is a fractal, non-repeating trajectory in 3D — the archetype of "strange attractors" in chaotic systems.',
    realWorld: 'Weather prediction models must account for Lorenz-like sensitivity; this is why forecasts beyond ~10 days are fundamentally unreliable.',
    hint: 'The trajectory never repeats and has fractal dimension ≈ 2.06.',
  },
  {
    id: 20421,
    topic: 'lorenz',
    difficulty: 'hard',
    question: 'Lorenz discovered chaos by accident when he rounded a number from 0.506127 to 0.506. This illustrates which property of chaotic systems?',
    options: ['Sensitive dependence on initial conditions', 'Periodicity', 'Linearity', 'Conservation of energy'],
    correctIndex: 0,
    explanation: 'Tiny perturbations in initial conditions lead to exponentially diverging trajectories — the hallmark of deterministic chaos.',
    realWorld: 'This is why ensemble forecasting (running many slightly perturbed simulations) is used in modern weather prediction.',
    hint: 'A butterfly flapping its wings...',
  },
  {
    id: 20422,
    topic: 'lorenz',
    difficulty: 'sota',
    question: 'The largest Lyapunov exponent $\\lambda_1$ of the Lorenz system at standard parameters is approximately:',
    options: ['$\\approx 0.9$', '$\\approx 0$', '$\\approx -2.7$', '$\\approx 28$'],
    correctIndex: 0,
    explanation: 'The positive Lyapunov exponent $\\lambda_1 \\approx 0.9$ quantifies the exponential rate of divergence of nearby trajectories.',
    realWorld: 'Positive Lyapunov exponents are used in finance to detect chaotic regimes in asset price dynamics for risk management.',
    hint: 'A positive value indicates chaos; the magnitude tells you how fast trajectories diverge.',
  },
  {
    id: 20423,
    topic: 'lorenz',
    difficulty: 'sota',
    question: 'Tucker (2002) provided a computer-assisted proof that the Lorenz attractor exists as a robust strange attractor. What mathematical technique was central to his proof?',
    options: ['Rigorous interval arithmetic with validated numerics', 'Symbolic dynamics only', 'Perturbation theory', 'Monte Carlo simulation'],
    correctIndex: 0,
    explanation: 'Tucker used interval arithmetic to rigorously bound all numerical errors, proving the attractor exists — resolving Smale\'s 14th problem.',
    realWorld: 'Computer-assisted proofs are now used in materials science, fluid dynamics, and verifying safety-critical aerospace software.',
    hint: 'The proof needed to account for floating-point errors rigorously.',
  },
  {
    id: 20424,
    topic: 'lorenz',
    difficulty: 'easy',
    question: 'Edward Lorenz was primarily a researcher in which field when he discovered chaos?',
    options: ['Meteorology', 'Pure mathematics', 'Quantum physics', 'Economics'],
    correctIndex: 0,
    explanation: 'Lorenz was a meteorologist running simplified weather models on an early computer when he stumbled upon chaotic behavior.',
    realWorld: 'His discovery fundamentally changed how we understand the limits of weather prediction.',
    hint: 'He was trying to predict the weather.',
  },
];
