import type { Question } from '../types';

export const lynnMargulisQuestions: Question[] = [
  {
    id: 402001,
    topic: 'lynn-margulis',
    difficulty: 'easy',
    question: 'Lynn Margulis is best known for championing which theory of eukaryotic cell evolution?',
    options: [
      'Endosymbiotic theory — mitochondria and chloroplasts were once free-living bacteria',
      'Panspermia — life was seeded from space',
      'Spontaneous generation — cells arise from non-living matter',
      'Autogenous theory — organelles arose from membrane invagination',
    ],
    correctIndex: 0,
    explanation: 'Margulis revived and rigorously supported the endosymbiotic theory, arguing that mitochondria derived from alpha-proteobacteria and chloroplasts from cyanobacteria, engulfed by ancestral eukaryotic cells.',
    realWorld: 'Her 1967 paper was rejected 15 times before publication. It is now one of the most cited papers in evolutionary biology.',
    hint: 'Bacteria living inside other cells became organelles.',
    glossaryLinks: ['endosymbiosis', 'natural-selection'],
  },
  {
    id: 402002,
    topic: 'lynn-margulis',
    difficulty: 'easy',
    question: 'What key evidence did Margulis use to support the endosymbiotic origin of mitochondria?',
    options: [
      'Mitochondria have their own circular DNA and double membranes, like bacteria',
      'Mitochondria can be seen dividing under a light microscope',
      'Mitochondria contain chlorophyll',
      'Mitochondria are found in prokaryotes',
    ],
    correctIndex: 0,
    explanation: 'Mitochondria possess circular DNA, 70S ribosomes, double membranes (inner = original bacterial membrane), and divide by binary fission — all hallmarks of bacterial ancestry.',
    realWorld: 'Phylogenetic analysis confirms mitochondrial rRNA is most closely related to Rickettsiales (alpha-proteobacteria).',
    hint: 'What bacterial features do mitochondria still retain?',
    glossaryLinks: ['endosymbiosis', 'central-dogma'],
  },
  {
    id: 402003,
    topic: 'lynn-margulis',
    difficulty: 'hard',
    question: 'Margulis proposed that eukaryotic flagella (undulipodia) originated from:',
    options: [
      'Spirochete bacteria that became motility organelles',
      'Viral tail fibers incorporated into cell membranes',
      'Extensions of the endoplasmic reticulum',
      'Modified mitochondrial cristae',
    ],
    correctIndex: 0,
    explanation: 'Margulis\'s serial endosymbiosis theory (SET) proposed a third symbiotic merger: spirochetes attaching to host cells and evolving into cilia/flagella. This remains the most controversial part of SET.',
    realWorld: 'Unlike the mitochondria/chloroplast cases, molecular evidence for a spirochete origin of flagella remains weak.',
    hint: 'She proposed not two but three symbiotic mergers.',
    glossaryLinks: ['endosymbiosis'],
  },
  {
    id: 402004,
    topic: 'lynn-margulis',
    difficulty: 'sota',
    question: 'How does Margulis\'s endosymbiotic theory challenge the neo-Darwinian emphasis on competition?',
    options: [
      'It shows that major evolutionary innovations arose through symbiotic cooperation, not just mutation and selection',
      'It proves that natural selection does not exist',
      'It replaces genetics with Lamarckism',
      'It shows that all evolution is neutral drift',
    ],
    correctIndex: 0,
    explanation: 'Margulis argued that the most significant leaps in evolution — the origin of eukaryotes, photosynthetic plants, and complex cells — arose through symbiogenesis (merger of organisms) rather than gradual competitive selection alone.',
    realWorld: 'Holobiont theory (organisms + their microbiomes as evolutionary units) extends Margulis\'s vision into modern microbiome science.',
    hint: 'Cooperation, not just competition, drives major evolutionary transitions.',
    glossaryLinks: ['endosymbiosis', 'natural-selection'],
  },
];
