import type { Question } from '../types';

export const margaretHamiltonQuestions: Question[] = [
  {
    id: 20460,
    topic: 'margaret-hamilton',
    difficulty: 'hard',
    question: 'During Apollo 11\'s lunar descent, Hamilton\'s software used which technique to handle the computer overload caused by a rendezvous radar switch left on?',
    options: ['Asynchronous priority-based task scheduling', 'Full system reboot', 'Ignoring all interrupts', 'Manual operator intervention'],
    correctIndex: 0,
    explanation: 'The software\'s priority scheduling dropped lower-priority tasks and continued critical ones — landing the module safely despite being overloaded.',
    realWorld: 'Priority-based preemptive scheduling is now standard in every real-time operating system from aircraft avionics to pacemakers.',
    hint: 'The system intelligently shed non-critical tasks rather than crashing.',
  },
  {
    id: 20461,
    topic: 'margaret-hamilton',
    difficulty: 'hard',
    question: 'Hamilton coined the term "software engineering." What was her primary motivation for creating this term?',
    options: ['To give software development the same rigor and respect as hardware engineering', 'To create a new academic department', 'To differentiate from computer science theory', 'To secure government funding'],
    correctIndex: 0,
    explanation: 'She fought to have software treated as a serious engineering discipline rather than an afterthought — a radical idea in the 1960s.',
    realWorld: 'The field of software engineering, now employing millions worldwide, exists in part because of her insistence on disciplinary rigor.',
    hint: 'In the 1960s, "programming" wasn\'t considered real engineering.',
  },
  {
    id: 20462,
    topic: 'margaret-hamilton',
    difficulty: 'sota',
    question: 'Hamilton\'s "Higher-Order Software" (HOS) methodology formalized error prevention using which mathematical concept?',
    options: ['Axiomatic correctness proofs with control flow hierarchies', 'Statistical testing', 'Neural network verification', 'Fuzzy logic'],
    correctIndex: 0,
    explanation: 'HOS used mathematical axioms to prove software correct by construction — eliminating entire categories of bugs before code was written.',
    realWorld: 'Modern formal verification tools (TLA+, Coq, Lean) continue this tradition in verifying safety-critical systems.',
    hint: 'She wanted to prevent errors mathematically, not find them through testing.',
  },
  {
    id: 20463,
    topic: 'margaret-hamilton',
    difficulty: 'sota',
    question: 'The Apollo Guidance Computer had only 74 KB of ROM and 4 KB of RAM. Hamilton\'s team achieved reliability through which software architecture pattern?',
    options: ['Restart-protected checkpointing with priority-driven recovery', 'Redundant hardware voting', 'Monolithic kernel design', 'Garbage-collected memory management'],
    correctIndex: 0,
    explanation: 'The software could restart mid-computation and recover state from checkpoints, ensuring mission-critical tasks survived any transient failure.',
    realWorld: 'This pattern evolved into modern crash-recovery systems: database WAL logs, Kubernetes pod restarts, and spacecraft fault tolerance.',
    hint: 'The system could recover gracefully from restarts without losing critical state.',
  },
  {
    id: 20464,
    topic: 'margaret-hamilton',
    difficulty: 'easy',
    question: 'What famous photo shows Margaret Hamilton standing next to stacks of Apollo guidance code?',
    options: ['Her standing beside printed source code listings as tall as she was', 'Her at a computer terminal', 'Her in a spacesuit', 'Her receiving the Presidential Medal'],
    correctIndex: 0,
    explanation: 'The iconic photo shows Hamilton next to the printed AGC source code, dramatically illustrating the scale of software needed for the moon landing.',
    realWorld: 'The photo became a symbol of women in STEM and the importance of software engineering.',
    hint: 'The code was printed on paper and stacked up impressively high.',
  },
];
