import type { Question } from '../types';

export const markKacQuestions: Question[] = [
  {
    id: 404001,
    topic: 'mark-kac',
    difficulty: 'easy',
    question: 'Mark Kac is famous for posing the question:',
    options: [
      '"Can one hear the shape of a drum?"',
      '"Is mathematics discovered or invented?"',
      '"What is the sound of one hand clapping?"',
      '"Does God play dice?"',
    ],
    correctIndex: 0,
    explanation: 'Kac\'s 1966 paper asked whether the eigenvalues of the Laplacian on a domain (frequencies of a vibrating membrane) uniquely determine the domain\'s shape. The answer is no — counterexamples were found in 1992.',
    realWorld: 'This problem connects spectral theory, inverse problems, and even quantum chaos — and is still actively studied.',
    hint: 'Eigenvalues of the Laplacian ↔ geometry.',
    glossaryLinks: ['partition-function'],
    formulaLinks: ['kac-feynman-formula'],
  },
  {
    id: 404002,
    topic: 'mark-kac',
    difficulty: 'hard',
    question: 'The Feynman–Kac formula provides a probabilistic solution to which type of equation?',
    options: [
      'Parabolic PDEs (e.g., the heat equation and Schrödinger equation in imaginary time)',
      'Hyperbolic PDEs (e.g., the wave equation)',
      'Elliptic systems with no boundary conditions',
      'Algebraic equations of degree 5 or higher',
    ],
    correctIndex: 0,
    explanation: 'The Feynman–Kac formula expresses the solution of $\\partial_t u = \\frac{1}{2}\\Delta u + V u$ as an expectation over Brownian motion paths: $u(x,t) = E_x[e^{\\int_0^t V(B_s)ds} f(B_t)]$.',
    realWorld: 'Used extensively in quantitative finance to price derivatives (Black–Scholes is a special case) and in quantum mechanics for path integrals.',
    hint: 'Brownian motion + potential = PDE solution.',
    glossaryLinks: ['stochastic-process', 'brownian-motion'],
    formulaLinks: ['kac-feynman-formula'],
  },
  {
    id: 404003,
    topic: 'mark-kac',
    difficulty: 'hard',
    question: 'Kac extended Smoluchowski\'s work on stochastic processes by developing:',
    options: [
      'Rigorous probabilistic methods connecting random walks to PDEs',
      'A disproof of the ergodic hypothesis',
      'A purely deterministic model of Brownian motion',
      'A replacement for the Boltzmann distribution',
    ],
    correctIndex: 0,
    explanation: 'Building on Smoluchowski\'s physical intuition about stochastic processes, Kac provided the mathematical rigor connecting probability theory, random walks, and partial differential equations.',
    realWorld: 'Kac credited Smoluchowski as a key inspiration, calling him "one of the great pioneers of the theory of stochastic processes."',
    hint: 'He made Smoluchowski\'s physical insights mathematically precise.',
    glossaryLinks: ['stochastic-process', 'brownian-motion', 'diffusion'],
  },
  {
    id: 404004,
    topic: 'mark-kac',
    difficulty: 'sota',
    question: 'The Kac ring model was designed to illuminate which conceptual paradox in statistical mechanics?',
    options: [
      'How irreversible macroscopic behavior emerges from reversible microscopic dynamics',
      'Why entropy can decrease in isolated systems',
      'How to compute partition functions exactly',
      'Why quantum mechanics is non-deterministic',
    ],
    correctIndex: 0,
    explanation: 'The Kac ring model is an exactly solvable toy model showing how apparent irreversibility (approach to equilibrium) arises from deterministic, time-reversible dynamics — resolving the Loschmidt paradox in a transparent way.',
    realWorld: 'It remains one of the clearest pedagogical tools for understanding the arrow of time and the second law of thermodynamics.',
    hint: 'Reversible rules, irreversible outcomes.',
    glossaryLinks: ['entropy-phys', 'boltzmann-distribution-gloss'],
  },
];
