import type { Question } from '../types';

export const gellMannQuestions: Question[] = [
  {
    id: 21180,
    topic: 'gell-mann',
    difficulty: 'sota',
    question: 'Gell-Mann\'s "Eightfold Way" organized hadrons using which mathematical structure?',
    options: ['The SU(3) flavor symmetry group', 'The SU(2) isospin group', 'The U(1) electromagnetic gauge group', 'The Poincaré group of spacetime symmetries'],
    correctIndex: 0,
    explanation: 'Gell-Mann classified mesons and baryons into geometric multiplets of the SU(3) Lie group, revealing an underlying order in the "particle zoo" — analogous to Mendeleev\'s periodic table for elements.',
    realWorld: 'The Eightfold Way predicted the existence and properties of the Ω⁻ baryon before it was discovered, confirming the theory.',
    hint: 'The name references both Buddhism and a specific Lie group with 8 generators.',
  },
  {
    id: 21181,
    topic: 'gell-mann',
    difficulty: 'sota',
    question: 'Gell-Mann proposed that hadrons are composed of fractionally charged constituents he named after a word from which literary work?',
    options: ['Finnegans Wake by James Joyce', 'Ulysses by James Joyce', 'The Waste Land by T.S. Eliot', 'Moby-Dick by Herman Melville'],
    correctIndex: 0,
    explanation: 'Gell-Mann took the name "quark" from the line "Three quarks for Muster Mark!" in Joyce\'s notoriously difficult novel, fitting the three-quark structure of baryons.',
    realWorld: 'Quarks are now confirmed as fundamental constituents of matter, with six "flavors" (up, down, charm, strange, top, bottom).',
    hint: '"Three quarks for Muster Mark!" — a nonsense phrase from a famously impenetrable novel.',
  },
  {
    id: 21182,
    topic: 'gell-mann',
    difficulty: 'sota',
    question: 'Quantum chromodynamics (QCD), which Gell-Mann helped develop, describes the strong force using which gauge group?',
    options: ['SU(3) color symmetry', 'SU(2) × U(1) electroweak symmetry', 'U(1) electromagnetic symmetry', 'SO(10) grand unified symmetry'],
    correctIndex: 0,
    explanation: 'QCD is a non-Abelian gauge theory based on SU(3) color symmetry, where quarks carry one of three "color" charges (red, green, blue) and interact via eight gluons.',
    realWorld: 'QCD explains why quarks are permanently confined inside protons and neutrons — the force between them grows stronger with distance.',
    hint: 'The same Lie group as the Eightfold Way, but now applied to a different quantum number.',
  },
  {
    id: 21183,
    topic: 'gell-mann',
    difficulty: 'sota',
    question: 'Gell-Mann co-founded which interdisciplinary research institute dedicated to complexity science?',
    options: ['The Santa Fe Institute', 'The Perimeter Institute', 'The Institute for Advanced Study', 'CERN'],
    correctIndex: 0,
    explanation: 'Gell-Mann co-founded the Santa Fe Institute in 1984 to study complex adaptive systems — applying insights from physics to economics, biology, linguistics, and computation.',
    realWorld: 'The Santa Fe Institute pioneered agent-based modeling, network science, and complexity economics.',
    hint: 'Located in New Mexico, this institute is dedicated to the study of complexity.',
  },
  {
    id: 21184,
    topic: 'gell-mann',
    difficulty: 'sota',
    question: 'Gell-Mann\'s concept of "effective complexity" distinguishes between which two types of information in a system?',
    options: ['Regular (compressible) patterns versus random (incompressible) noise', 'Classical versus quantum information', 'Syntactic versus semantic information', 'Analog versus digital information'],
    correctIndex: 0,
    explanation: 'Effective complexity measures only the regularities in a system (its compressible structure), ignoring random fluctuations. A perfectly random sequence has zero effective complexity despite high Shannon entropy.',
    realWorld: 'This concept is crucial for understanding biological complexity, where meaningful structure coexists with random variation.',
    hint: 'Maximum randomness and perfect order both have low effective complexity — it peaks in between.',
  },
];
