import type { Question } from '../types';

export const mustafaSuleymanQuestions: Question[] = [
  {
    id: 412901,
    topic: 'mustafa-suleyman',
    difficulty: 'easy',
    question: 'Mustafa Suleyman co-founded which pioneering AI lab before leading AI at Microsoft?',
    options: [
      'DeepMind — which achieved breakthroughs in AlphaGo, AlphaFold, and game-playing AI',
      'OpenAI — creators of ChatGPT and GPT-4',
      'Anthropic — makers of Claude',
      'Meta AI — Facebook\'s research lab',
    ],
    correctIndex: 0,
    explanation: 'Suleyman co-founded DeepMind in 2010 with Demis Hassabis and Shane Legg. DeepMind produced AlphaGo (beat world Go champion), AlphaFold (solved protein folding), and numerous breakthroughs in RL and neuroscience.',
    realWorld: 'After DeepMind (acquired by Google for ~$500M), Suleyman founded Inflection AI (building Pi chatbot), then became CEO of Microsoft AI — shaping AI strategy at the largest tech company.',
    hint: 'The London-based lab famous for beating humans at Go.',
  },
  {
    id: 412902,
    topic: 'mustafa-suleyman',
    difficulty: 'easy',
    question: 'Suleyman\'s concept of "The Coming Wave" warns about:',
    options: [
      'The convergence of AI and synthetic biology creating unprecedented power that may be impossible to control or contain',
      'A literal tsunami caused by climate change',
      'The next generation of social media platforms',
      'A new cryptocurrency wave disrupting finance',
    ],
    correctIndex: 0,
    explanation: 'In his book "The Coming Wave," Suleyman argues that AI and synthetic biology are dual general-purpose technologies that will reshape civilization. Unlike previous technologies, their containment may be fundamentally impossible.',
    realWorld: 'His "containment problem" thesis — that powerful technologies inevitably proliferate — informs AI governance debates at the UN, EU AI Act discussions, and corporate AI safety policies.',
    hint: 'Two technologies converging: artificial intelligence and the ability to engineer life itself.',
  },
  {
    id: 412903,
    topic: 'mustafa-suleyman',
    difficulty: 'hard',
    question: 'RLHF (Reinforcement Learning from Human Feedback), central to Suleyman\'s work on AI safety, works by:',
    options: [
      'Training a reward model on human preference rankings, then using PPO to optimize the language model against that reward model',
      'Simply filtering training data to remove toxic content',
      'Hard-coding rules about what the model can and cannot say',
      'Training the model exclusively on curated academic papers',
    ],
    correctIndex: 0,
    explanation: 'RLHF has three stages: (1) supervised fine-tuning on demonstrations, (2) training a reward model on human comparisons of outputs, (3) optimizing the policy with PPO against the reward model while constraining divergence from the base model (KL penalty).',
    realWorld: 'RLHF is what makes ChatGPT, Claude, and Pi helpful and safe. Without it, base language models produce unpredictable, often toxic outputs. Suleyman\'s Inflection Pi was designed as "the world\'s most empathetic AI."',
    hint: 'Humans rank outputs → reward model learns preferences → RL optimizes for those preferences.',
  },
  {
    id: 12904,
    topic: 'mustafa-suleyman',
    difficulty: 'hard',
    question: 'Suleyman\'s "containment problem" differs from traditional AI safety concerns because:',
    options: [
      'It argues the problem is fundamentally about technology proliferation — once capable AI exists, preventing its spread is nearly impossible regardless of any single actor\'s choices',
      'It focuses only on making individual AI models safer',
      'It claims AI can never be dangerous',
      'It suggests government regulation alone can solve all risks',
    ],
    correctIndex: 0,
    explanation: 'Unlike alignment research (making AI do what we want), containment asks whether powerful technology can be kept from spreading. Suleyman argues that open-source models, falling compute costs, and global competition make containment fundamentally difficult.',
    realWorld: 'The leak of LLaMA weights, proliferation of open-source models, and nation-state AI races validate his thesis — containing powerful AI is harder than aligning it.',
    hint: 'The question isn\'t "can we make safe AI?" but "can we prevent unsafe AI from spreading?"',
  },
  {
    id: 12905,
    topic: 'mustafa-suleyman',
    difficulty: 'sota',
    question: 'Suleyman proposes the "Modern Turing Test" (MTT) to evaluate AI capability, which requires:',
    options: [
      'An AI that can turn $100,000 into $1,000,000 in a retail business — demonstrating real-world economic agency, not just conversation',
      'An AI that can pass a standard IQ test',
      'An AI that can write a novel indistinguishable from a human author',
      'An AI that can beat all humans at every board game',
    ],
    correctIndex: 0,
    explanation: 'The MTT replaces conversational deception with economic capability: can an AI autonomously navigate the real world — research products, negotiate with suppliers, manage inventory, handle customers — to generate profit? This tests genuine agency, not mimicry.',
    realWorld: 'This benchmark is more meaningful than chatbot benchmarks because it requires planning, tool use, social interaction, and adaptation — the capabilities needed for transformative economic impact.',
    hint: 'It measures real-world agency and economic value creation, not just conversation ability.',
  },
];
