import type { Question } from '../types';

export const newtonQuestions: Question[] = [
  {
    id: 11201,
    topic: 'newton',
    difficulty: 'easy',
    question: 'Newton\'s second law relates force, mass, and acceleration as:',
    options: [
      '$F = ma$ — net force equals mass times acceleration',
      '$F = mv$ — force is mass times velocity',
      '$F = m/a$ — force decreases as acceleration increases',
      '$F = \\frac{1}{2}mv^2$ — force equals kinetic energy',
    ],
    correctIndex: 0,
    explanation: 'F = ma is one of the most productive equations in science. It defines force operationally and enables predicting motion from forces — the foundation of classical mechanics and engineering.',
    realWorld: 'Every physics engine in video games and robot simulators implements F=ma to compute trajectories, collisions, and rigid body dynamics.',
    hint: 'Heavier objects need more force to accelerate at the same rate.',
  },
  {
    id: 11202,
    topic: 'newton',
    difficulty: 'easy',
    question: 'Newton\'s method for finding roots of $f(x)=0$ iterates using the formula:',
    options: [
      '$x_{n+1} = x_n - \\frac{f(x_n)}{f\'(x_n)}$',
      '$x_{n+1} = x_n - f(x_n) \\cdot f\'(x_n)$',
      '$x_{n+1} = x_n + \\frac{f\'(x_n)}{f(x_n)}$',
      '$x_{n+1} = \\frac{x_n + x_{n-1}}{2}$',
    ],
    correctIndex: 0,
    explanation: 'Newton\'s method linearizes f near xₙ using the tangent line and solves for the root of that line. It converges quadratically — the number of correct digits roughly doubles each iteration near the root.',
    realWorld: 'Newton\'s method is used in GPU shader compilers to compute 1/√x (fast inverse square root), in training neural networks via second-order optimization, and in solving nonlinear equations everywhere.',
    hint: 'The tangent line at (xₙ, f(xₙ)) intersects the x-axis at the next iterate.',
  },
  {
    id: 11203,
    topic: 'newton',
    difficulty: 'easy',
    question: 'The binomial theorem, developed by Newton, states that for any $n$:',
    options: [
      '$(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k$',
      '$(a+b)^n = a^n + b^n$ for prime $n$',
      '$(a+b)^n = n! \\cdot a \\cdot b$ for integer $n$',
      '$(a+b)^n = a^n + na^{n-1}b$ (first-order approximation)',
    ],
    correctIndex: 0,
    explanation: 'Newton generalized the binomial theorem to non-integer and negative exponents, enabling power series expansions like (1+x)^(1/2) = 1 + x/2 - x²/8 + ... This was central to his development of calculus.',
    realWorld: 'The binomial theorem underlies probability distributions (binomial, negative binomial), polynomial hashing algorithms, and Taylor series approximations used throughout ML.',
    hint: 'Pascal\'s triangle gives the coefficients — the kth entry is C(n,k).',
  },
  {
    id: 11204,
    topic: 'newton',
    difficulty: 'easy',
    question: 'Newton\'s law of universal gravitation states that the force between two masses is:',
    options: [
      'Proportional to the product of masses and inversely proportional to the square of distance',
      'Proportional to the sum of masses and inversely proportional to distance',
      'Proportional to the product of masses and inversely proportional to distance',
      'Proportional to mass difference and independent of distance',
    ],
    correctIndex: 0,
    explanation: 'F = Gm₁m₂/r² — the inverse-square law. Newton derived this from Kepler\'s orbital laws and verified it predicts the Moon\'s centripetal acceleration from Earth\'s surface gravity.',
    realWorld: 'Satellite orbit calculations, trajectory planning for interplanetary probes, and tidal force models all use Newton\'s inverse-square gravity law.',
    hint: 'Double the distance → quarter the gravitational force.',
  },
  {
    id: 11205,
    topic: 'newton',
    difficulty: 'hard',
    question: 'Newton\'s method has quadratic convergence near a simple root, meaning:',
    options: [
      '$|e_{n+1}| \\approx C|e_n|^2$, so the error squares each iteration',
      '$|e_{n+1}| \\approx C|e_n|/2$, so the error halves each iteration',
      '$|e_{n+1}| = |e_n|^{0.5}$, convergence is sublinear',
      '$|e_{n+1}| \\approx C|e_n|^3$, convergence is cubic',
    ],
    correctIndex: 0,
    explanation: 'By Taylor expanding f(x*) = 0 around the root, the error satisfies e_{n+1} ≈ -f\'\'(xₙ)/(2f\'(xₙ)) × eₙ². This squaring of error means starting from 0.1 error gives 0.01, then 0.0001, then 10^-8 — very fast.',
    realWorld: 'Quadratic convergence makes Newton\'s method the gold standard for nonlinear solvers — 6 iterations from a decent starting point gives machine precision.',
    hint: 'If eₙ = 0.001, then e_{n+1} ≈ C × (0.001)² = O(10^{-6}).',
  },
  {
    id: 11206,
    topic: 'newton',
    difficulty: 'hard',
    question: 'Newton\'s forward difference formula for polynomial interpolation through points $(x_0, f_0), \\ldots, (x_n, f_n)$ is:',
    options: [
      '$p(x) = \\sum_{k=0}^{n} \\binom{s}{k} \\Delta^k f_0$ where $s = (x-x_0)/h$',
      '$p(x) = \\sum_{k=0}^{n} \\frac{f_k}{(x-x_k)}$',
      '$p(x) = f_0 + f_1(x-x_0) + f_2(x-x_0)(x-x_1)$',
      '$p(x) = \\frac{1}{n}\\sum_{k=0}^{n} f_k \\cos(k\\pi x)$',
    ],
    correctIndex: 0,
    explanation: 'Using finite differences Δᵏf₀ and the generalized binomial coefficient, Newton\'s formula interpolates through equally spaced data. It is the foundation for numerical differentiation and integration tables used before computers.',
    realWorld: 'Finite difference methods for PDEs (heat equation, wave equation, Navier-Stokes) in computational fluid dynamics and weather simulation are direct descendants of Newton\'s interpolation formula.',
    hint: 'Δ⁰f₀ = f₀, Δ¹f₀ = f₁-f₀, Δ²f₀ = f₂-2f₁+f₀ — these are the "discrete derivatives".',
  },
  {
    id: 11207,
    topic: 'newton',
    difficulty: 'hard',
    question: 'The Newton-Raphson method fails or converges slowly near a root where $f\'(x^*) = 0$. For a root of multiplicity $m$, convergence becomes:',
    options: [
      'Linear with rate $(1 - 1/m)$ instead of quadratic',
      'Quadratic but with a larger constant $C$',
      'Cubic when $m = 2$',
      'Divergent for any $m > 1$',
    ],
    correctIndex: 0,
    explanation: 'At a root of multiplicity m, f(x) = (x-x*)^m × g(x) with g(x*) ≠ 0. Newton\'s method converges linearly with rate (1-1/m). The modified iteration x_{n+1} = xₙ - m·f(xₙ)/f\'(xₙ) restores quadratic convergence.',
    realWorld: 'Eigenvalue solvers must detect repeated eigenvalues — the Newton-Raphson iteration for the characteristic polynomial degrades near defective matrices.',
    hint: 'A double root means f(x*) = f\'(x*) = 0 — the denominator is also zero in the Newton step.',
  },
  {
    id: 11208,
    topic: 'newton',
    difficulty: 'sota',
    question: 'The Newton-Euler equations for rigid body dynamics extend F=ma to rotational motion. The rotational analog is:',
    options: [
      '$\\tau = I\\dot{\\omega} + \\omega \\times I\\omega$ (Euler\'s equations in body frame)',
      '$\\tau = I\\omega$ (torque equals moment of inertia times angular velocity)',
      '$\\tau = m r^2 \\alpha$ (scalar moment equation)',
      '$\\tau = \\nabla \\times F$ (torque as curl of force field)',
    ],
    correctIndex: 0,
    explanation: 'In the body frame, the inertia tensor I is constant, but the rotating frame introduces the Coriolis-like term ω × Iω. This is why spinning tops precess and gyroscopes resist tilting — the cross-product term couples rotation axes.',
    realWorld: 'Robot arm trajectory control, drone attitude control, and spacecraft attitude determination all solve the Newton-Euler equations in real time.',
    hint: 'The extra ω × Iω term appears because the body frame itself is rotating — Newton\'s laws need a correction for rotating reference frames.',
  },
  {
    id: 11209,
    topic: 'newton',
    difficulty: 'sota',
    question: 'In optimization, the pure Newton step minimizing $f(x)$ updates as $x \\leftarrow x - H^{-1}\\nabla f$. This fails when:',
    options: [
      '$H$ is indefinite (not positive definite), causing ascent steps at saddle points',
      '$\\nabla f = 0$ exactly, which terminates the algorithm prematurely',
      'The Hessian $H$ is diagonal, reducing to gradient descent',
      '$f$ is convex, because Newton\'s method only works for non-convex functions',
    ],
    correctIndex: 0,
    explanation: 'At saddle points, H has negative eigenvalues. The Newton direction H⁻¹∇f may point toward a saddle rather than a minimum. Trust-region methods and Levenberg-Marquardt add λI to H to ensure positive definiteness.',
    realWorld: 'In training neural networks, saddle points dominate the loss landscape. Second-order optimizers (K-FAC, Shampoo) approximate the Hessian while ensuring positive definiteness for stable updates.',
    hint: 'If H has negative eigenvalues, -H⁻¹∇f could increase f rather than decrease it.',
  },
  {
    id: 11210,
    topic: 'newton',
    difficulty: 'sota',
    question: 'Newton discovered that light is composed of colors by prism experiments. The mathematical analog in signal processing is:',
    options: [
      'Fourier decomposition: any signal decomposes into sinusoidal components at different frequencies (colors of sound)',
      'Wavelet decomposition: signals decompose into localized time-frequency atoms',
      'PCA: signals decompose into orthogonal components of maximum variance',
      'Convolution: signals are built by superposing shifted impulse responses',
    ],
    correctIndex: 0,
    explanation: 'Newton\'s prism shows white light = sum of pure colors. Fourier analysis shows any signal = sum of pure sinusoids. Both are "spectral decompositions" — breaking a complex signal into pure components. Newton\'s optics directly inspired Fourier\'s mathematics.',
    realWorld: 'Audio equalizers, MRI scanner image reconstruction, JPEG compression, and spectrogram-based speech recognition all use Fourier decomposition — Newton\'s prism in mathematical form.',
    hint: 'White light is a "mixture" of frequencies — Fourier analysis does the same decomposition for arbitrary signals.',
  },
];
