import type { Question } from '../types';

export const paulSamuelsonQuestions: Question[] = [
  {
    id: 21070,
    topic: 'paul-samuelson',
    difficulty: 'sota',
    question: 'Samuelson\'s "Foundations of Economic Analysis" borrowed its mathematical framework primarily from which branch of physics?',
    options: ['Classical thermodynamics and Lagrangian mechanics', 'Quantum mechanics', 'Fluid dynamics', 'Electromagnetism'],
    correctIndex: 0,
    explanation: 'Samuelson explicitly adapted the constrained optimization methods of Lagrangian mechanics and the equilibrium concepts of thermodynamics to formalize economic theory.',
    realWorld: 'His mathematization of economics created the template that every PhD economics program still follows today.',
    hint: 'He used the same math that describes heat engines and mechanical systems.',
  },
  {
    id: 21071,
    topic: 'paul-samuelson',
    difficulty: 'sota',
    question: 'Samuelson\'s "revealed preference" theory resolves which philosophical problem in economics?',
    options: ['Deriving utility functions from observable choices without assuming introspection', 'Proving that markets are always efficient', 'Showing that rational agents always maximize profit', 'Eliminating the need for supply and demand curves'],
    correctIndex: 0,
    explanation: 'Rather than assuming consumers have measurable internal utility, Samuelson showed that consistent choice behavior alone is sufficient to reconstruct preference orderings — making economics empirically testable.',
    realWorld: 'Revealed preference is the foundation of modern demand estimation in tech (A/B testing, recommendation systems).',
    hint: 'We observe what people do, not what they say they want.',
  },
  {
    id: 21072,
    topic: 'paul-samuelson',
    difficulty: 'sota',
    question: 'Samuelson\'s "efficient market hypothesis" contribution showed that properly anticipated prices must exhibit which statistical property?',
    options: ['They fluctuate randomly (martingale property)', 'They trend upward over time', 'They revert to the mean', 'They follow periodic cycles'],
    correctIndex: 0,
    explanation: 'Samuelson proved that in an informationally efficient market, price changes must be unpredictable — if they were predictable, arbitrageurs would trade until the predictability disappeared.',
    realWorld: 'This insight underpins index fund investing and the debate about whether active management can consistently beat the market.',
    hint: 'If you could predict tomorrow\'s price, you\'d trade on it today, eliminating the pattern.',
  },
  {
    id: 21073,
    topic: 'paul-samuelson',
    difficulty: 'sota',
    question: 'Samuelson\'s multiplier-accelerator model explains which macroeconomic phenomenon?',
    options: ['Business cycles arising from the interaction of consumption and investment', 'Hyperinflation in developing economies', 'The Phillips curve trade-off', 'Currency crises in fixed exchange rate regimes'],
    correctIndex: 0,
    explanation: 'The model shows how government spending multiplies through the economy (the multiplier) while rising output induces more investment (the accelerator), creating self-reinforcing boom-bust cycles.',
    realWorld: 'This model influenced Keynesian stimulus policies and modern macroeconomic forecasting.',
    hint: 'Two feedback loops — spending begets income, and income begets investment.',
  },
  {
    id: 21074,
    topic: 'paul-samuelson',
    difficulty: 'sota',
    question: 'Samuelson famously quipped about which economic indicator: "It has predicted nine of the last five recessions"?',
    options: ['The stock market', 'The yield curve', 'Consumer confidence surveys', 'Leading economic indicators'],
    correctIndex: 0,
    explanation: 'Samuelson joked that stock market declines are unreliable recession predictors because they generate too many false positives — the market panics more often than the economy actually contracts.',
    realWorld: 'This quip remains one of the most cited warnings about over-relying on any single economic indicator.',
    hint: 'This indicator famously produces more false alarms than real predictions.',
  },
];
