import type { Question } from '../types';

export const perlmanQuestions: Question[] = [
  {
    id: 20500,
    topic: 'perlman',
    difficulty: 'hard',
    question: 'Radia Perlman\'s Spanning Tree Protocol (STP) prevents broadcast storms by constructing which graph structure over a bridged LAN?',
    options: ['A minimum spanning tree rooted at a designated bridge', 'A complete bipartite graph', 'A Hamiltonian cycle', 'A directed acyclic graph'],
    correctIndex: 0,
    explanation: 'STP elects a root bridge, then computes shortest paths to it, disabling redundant links to create a loop-free spanning tree.',
    realWorld: 'Every enterprise Ethernet network on Earth uses STP (or its successors RSTP/MSTP) to prevent catastrophic broadcast storms.',
    hint: 'The protocol eliminates loops by keeping only a tree subset of the network graph.',
  },
  {
    id: 20501,
    topic: 'perlman',
    difficulty: 'hard',
    question: 'RSTP (802.1w) improved STP convergence from ~50 seconds to approximately:',
    options: ['1–2 seconds', '10–15 seconds', '30 seconds', '5 minutes'],
    correctIndex: 0,
    explanation: 'RSTP uses proposal-agreement handshakes between bridges for rapid port transitions, converging in 1–2 seconds versus STP\'s 30–50 second timers.',
    realWorld: 'Sub-second failover is critical for data center networks where even brief outages cause millions in losses.',
    hint: 'The "Rapid" in RSTP means convergence is orders of magnitude faster.',
  },
  {
    id: 20502,
    topic: 'perlman',
    difficulty: 'sota',
    question: 'Perlman later invented TRILL (Transparent Interconnection of Lots of Links). How does TRILL improve on STP?',
    options: ['It uses IS-IS routing to enable multi-path forwarding while preventing loops', 'It removes the need for MAC addresses', 'It replaces Ethernet with token ring', 'It uses TCP for Layer 2 forwarding'],
    correctIndex: 0,
    explanation: 'TRILL replaces STP\'s single-path tree with IS-IS link-state routing at Layer 2, enabling all links to carry traffic simultaneously — dramatically improving bandwidth utilization.',
    realWorld: 'TRILL and its successor technologies (VXLAN, EVPN) power modern hyperscale data centers at Google, Amazon, and Microsoft.',
    hint: 'Instead of blocking redundant paths, TRILL uses all of them with a proper routing protocol.',
  },
  {
    id: 20503,
    topic: 'perlman',
    difficulty: 'sota',
    question: 'In STP, the Bridge Protocol Data Unit (BPDU) election uses a tuple $(priority, MAC)$. What is the default bridge priority value in IEEE 802.1D?',
    options: ['32768', '0', '65535', '128'],
    correctIndex: 0,
    explanation: 'The default priority is 32768 (0x8000). The bridge with the lowest (priority, MAC) tuple becomes root. Administrators lower the priority to force root election.',
    realWorld: 'Misconfigured STP priorities have caused major network outages — understanding root bridge election is a core network engineering skill.',
    hint: 'It\'s a 16-bit value, and the default is exactly half the maximum.',
  },
  {
    id: 20504,
    topic: 'perlman',
    difficulty: 'easy',
    question: 'Radia Perlman is often called the "Mother of the Internet" for inventing which protocol?',
    options: ['Spanning Tree Protocol (STP)', 'TCP/IP', 'HTTP', 'DNS'],
    correctIndex: 0,
    explanation: 'STP prevents network loops in Ethernet — a foundational protocol that keeps the internet\'s physical layer functioning.',
    realWorld: 'She famously invented the algorithm over a single weekend and even wrote a poem about it.',
    hint: 'It\'s named after a graph theory concept — a connected subgraph with no cycles.',
  },
];
