import type { Question } from '../types';

export const pythagorasQuestions: Question[] = [
  {
    id: 11401,
    topic: 'pythagoras',
    difficulty: 'easy',
    question: 'The Pythagorean theorem states that for a right triangle with legs $a$, $b$ and hypotenuse $c$:',
    options: [
      '$a^2 + b^2 = c^2$',
      '$a + b = c$',
      '$a^2 - b^2 = c$',
      '$\\sqrt{a} + \\sqrt{b} = \\sqrt{c}$',
    ],
    correctIndex: 0,
    explanation: 'a² + b² = c² is one of the most proven theorems in mathematics (over 370 known proofs). It defines Euclidean distance and is the foundation of all geometric measurement.',
    realWorld: 'Euclidean distance in ML (||x-y||₂ = √∑(xᵢ-yᵢ)²) is a direct application — every distance matrix, k-NN classifier, and k-means algorithm uses the Pythagorean theorem.',
    hint: 'The square on the hypotenuse equals the sum of squares on the two shorter sides.',
  },
  {
    id: 11402,
    topic: 'pythagoras',
    difficulty: 'easy',
    question: 'The Pythagoreans discovered that $\\sqrt{2}$ is irrational. The proof proceeds by:',
    options: [
      'Assuming √2 = p/q in lowest terms and deriving that both p and q must be even — a contradiction',
      'Showing that 2 is prime and hence has no rational square root',
      'Proving the decimal expansion of √2 is non-repeating by long division',
      'Using the Archimedean property to bound √2 between rationals',
    ],
    correctIndex: 0,
    explanation: 'If √2 = p/q (lowest terms), then p² = 2q², so p is even (p=2k), then 4k² = 2q², so q is even — contradicting lowest terms. This was a philosophical shock to the Pythagoreans who believed all lengths were commensurable.',
    realWorld: 'Irrational numbers require floating-point representation. IEEE 754 double precision represents √2 ≈ 1.41421356... — the representation gap between rationals and irrationals is fundamental to numerical computing.',
    hint: 'Assume √2 = p/q fully reduced — what must be true about p²?',
  },
  {
    id: 11403,
    topic: 'pythagoras',
    difficulty: 'easy',
    question: 'Pythagorean triples are integer solutions to $a^2 + b^2 = c^2$. The general formula generates them as:',
    options: [
      '$a = m^2 - n^2$, $b = 2mn$, $c = m^2 + n^2$ for integers $m > n > 0$',
      '$a = n$, $b = n+1$, $c = \\sqrt{2n+1}$ for odd $n$',
      '$a = p$, $b = q$, $c = pq$ for primes $p, q$',
      '$a = F_n$, $b = F_{n+1}$, $c = F_{n+2}$ for Fibonacci numbers',
    ],
    correctIndex: 0,
    explanation: 'The parametrization (m²-n², 2mn, m²+n²) generates all primitive Pythagorean triples for coprime m>n>0 with opposite parity. E.g., m=2, n=1 gives (3,4,5).',
    realWorld: 'Pythagorean triples in computer graphics define integer-coordinate triangles for exact pixel-perfect rasterization without floating-point error.',
    hint: 'm=2, n=1: (4-1, 4, 4+1) = (3, 4, 5). ✓',
  },
  {
    id: 11404,
    topic: 'pythagoras',
    difficulty: 'easy',
    question: 'In music theory, the Pythagorean tuning system is based on:',
    options: [
      'Stacking perfect fifths (frequency ratio 3:2) to generate all musical intervals',
      'Dividing the octave into 12 equal semitones',
      'Using the harmonic series 1:2:3:4:5:... to define consonance',
      'Minimizing the sum of squared frequency deviations from just intonation',
    ],
    correctIndex: 0,
    explanation: 'Pythagoras discovered that consonant intervals correspond to simple frequency ratios (octave 2:1, fifth 3:2, fourth 4:3). Stacking 12 perfect fifths theoretically returns to the octave — but the Pythagorean comma (≈23.46 cents) means it doesn\'t quite.',
    realWorld: 'Equal temperament (12-TET) resolves the Pythagorean comma by making each semitone 2^(1/12) — a mathematical compromise enabling transposition-invariant harmony in all modern music.',
    hint: 'The frequency ratio of a perfect fifth is 3:2 — stacking two gives 9:4, reducing to 9:8 for a major second.',
  },
  {
    id: 11405,
    topic: 'pythagoras',
    difficulty: 'hard',
    question: 'The generalization of the Pythagorean theorem to inner product spaces states that for orthogonal vectors $u \\perp v$:',
    options: [
      '$\\|u + v\\|^2 = \\|u\\|^2 + \\|v\\|^2$ (Pythagorean theorem in Hilbert space)',
      '$\\|u + v\\| = \\|u\\| + \\|v\\|$ (triangle inequality becomes equality)',
      '$\\langle u, v \\rangle = \\|u\\|\\|v\\|$ when vectors are parallel',
      '$\\|u - v\\|^2 = \\|u\\|^2 + \\|v\\|^2$ for any inner product',
    ],
    correctIndex: 0,
    explanation: 'In any inner product space, ‖u+v‖² = ‖u‖² + 2⟨u,v⟩ + ‖v‖². Orthogonality (⟨u,v⟩=0) makes the cross-term vanish, recovering the Pythagorean theorem. This works in infinite-dimensional function spaces (L² spaces) too.',
    realWorld: 'Variance decomposition in statistics: Var(X+Y) = Var(X) + Var(Y) for independent X,Y is the Pythagorean theorem for random variables (orthogonal in L²).',
    hint: 'Expand ‖u+v‖² = ⟨u+v, u+v⟩ and use bilinearity of the inner product.',
  },
  {
    id: 11406,
    topic: 'pythagoras',
    difficulty: 'hard',
    question: 'Fermat\'s Last Theorem (proved 1995) states that $a^n + b^n = c^n$ has no positive integer solutions for $n \\geq 3$. Pythagorean triples exist for $n=2$ because:',
    options: [
      'Gaussian integers $\\mathbb{Z}[i]$ have unique factorization, parameterizing all solutions',
      'The elliptic curve $y^2 = x^3 - x$ has infinitely many rational points',
      'Every prime $p \\equiv 1 \\pmod{4}$ is a sum of two squares',
      'The quadratic form $a^2 + b^2$ represents all positive integers',
    ],
    correctIndex: 0,
    explanation: 'In Z[i], c = a+bi has norm N(c) = a²+b². Pythagorean triples correspond to factorizations of c² in Z[i]. The unique factorization in Gaussian integers (a Euclidean domain) completely classifies all solutions — a structure absent for n≥3.',
    realWorld: 'Wiles\' proof of Fermat\'s Last Theorem connects elliptic curves, modular forms, and Galois representations — motivating modern cryptographic schemes like elliptic curve cryptography (ECC).',
    hint: 'c² = (a+bi)(a-bi) in Z[i] — unique factorization in Gaussian integers explains everything.',
  },
  {
    id: 11407,
    topic: 'pythagoras',
    difficulty: 'hard',
    question: 'The law of cosines generalizes the Pythagorean theorem to arbitrary triangles as $c^2 = a^2 + b^2 - 2ab\\cos C$. When $C = 90°$ this reduces to $a^2+b^2=c^2$ because:',
    options: [
      '$\\cos(90°) = 0$, eliminating the correction term',
      '$\\cos(90°) = 1$, making the correction equal to $2ab$',
      '$\\sin(90°) = 0$, zeroing the Pythagorean term',
      '$\\tan(90°) = \\infty$, making the formula degenerate',
    ],
    correctIndex: 0,
    explanation: 'The law of cosines is the general inner product formula: c² = ‖a-b‖² = ‖a‖²-2⟨a,b⟩+‖b‖². For right angles, ⟨a,b⟩ = ‖a‖‖b‖cos(90°) = 0, recovering Pythagoras. This is the geometric-algebraic duality at the heart of linear algebra.',
    realWorld: 'Cosine similarity in NLP: sim(u,v) = cos θ = ⟨u,v⟩/(‖u‖‖v‖) — measuring angle between document embeddings uses the law of cosines in high-dimensional space.',
    hint: 'cos(90°) = 0, so the -2ab·cos(C) term vanishes completely.',
  },
  {
    id: 11408,
    topic: 'pythagoras',
    difficulty: 'sota',
    question: 'The Pythagorean theorem in $L^p$ spaces generalizes distance as $d_p(x,y) = (\\sum|x_i-y_i|^p)^{1/p}$. For $p=2$ this is Euclidean. The choice of $p$ affects machine learning because:',
    options: [
      '$p=1$ (Manhattan) promotes sparsity; $p=2$ (Euclidean) promotes smoothness; $p=\\infty$ (Chebyshev) maximizes worst-case coordinate deviation',
      '$p=2$ is always optimal by the Cramér-Rao bound',
      '$p=1$ satisfies the triangle inequality while $p=2$ does not',
      'All $L^p$ norms are equivalent on finite-dimensional spaces so $p$ never matters in practice',
    ],
    correctIndex: 0,
    explanation: 'L1 regularization (LASSO) produces sparse solutions because L1 balls have corners at axes. L2 (Ridge) produces smooth solutions — circular level sets. The geometry of the norm ball determines sparsity and the nature of optimal solutions.',
    realWorld: 'LASSO (L1) selects features in genomics. Ridge (L2) shrinks coefficients smoothly. Elastic Net combines both. The choice of p is a fundamental modeling decision in high-dimensional statistics.',
    hint: 'L1 balls are diamonds (corners at axes) — corners promote sparse solutions where some coordinates are zero.',
  },
  {
    id: 11409,
    topic: 'pythagoras',
    difficulty: 'sota',
    question: 'The Parseval-Plancherel identity $\\|f\\|_{L^2}^2 = \\|\\hat{f}\\|_{L^2}^2$ is the infinite-dimensional Pythagorean theorem. It states:',
    options: [
      'Energy is preserved under the Fourier transform — total signal power equals total spectral power',
      'The Fourier transform is its own inverse up to a sign change',
      'Convolution in time equals multiplication in frequency',
      'The DFT matrix is symmetric and therefore equal to its own inverse',
    ],
    correctIndex: 0,
    explanation: 'Parseval\'s theorem ∫|f(t)|²dt = ∫|f̂(ξ)|²dξ says the Fourier transform is an isometry on L² — preserving energy. This is the Pythagorean theorem in function space: the "length" of a signal equals the "length" of its spectrum.',
    realWorld: 'Audio compression algorithms verify energy preservation using Parseval\'s theorem. Signal-to-noise ratio analysis in communications converts between time-domain and frequency-domain power using this identity.',
    hint: 'The Fourier transform is a unitary operator on L²(ℝ) — unitary operators preserve inner products and norms.',
  },
  {
    id: 11410,
    topic: 'pythagoras',
    difficulty: 'sota',
    question: 'Bregman divergences generalize the squared Euclidean distance. The squared L2 distance $\\|x-y\\|^2$ corresponds to the Bregman divergence with generator $\\phi(x)=$',
    options: [
      '$\\|x\\|^2$ — giving $D_\\phi(x,y) = \\|x-y\\|^2$ exactly',
      '$\\|x\\|$ — giving the L1-type divergence',
      '$x\\log x$ — giving the KL divergence',
      '$\\log(1+\\|x\\|^2)$ — giving the logistic divergence',
    ],
    correctIndex: 0,
    explanation: 'The Bregman divergence D_φ(x,y) = φ(x) - φ(y) - ⟨∇φ(y), x-y⟩. For φ(x)=‖x‖², ∇φ=2x, giving D_φ(x,y) = ‖x‖²-‖y‖²-2⟨y,x-y⟩ = ‖x-y‖². KL divergence uses φ(x) = x log x — entropy.',
    realWorld: 'Bregman divergences unify exponential family distributions with mirror descent optimization — used in online learning, boosting (AdaBoost uses KL-Bregman), and information geometry.',
    hint: 'φ(x)=‖x‖² gives ∇φ=2x. Plug into D_φ(x,y) = φ(x)-φ(y)-⟨∇φ(y),x-y⟩ and simplify.',
  },
];
