import type { Question } from '../types';

export const richardSuttonQuestions: Question[] = [
  {
    id: 11801,
    topic: 'richard-sutton',
    difficulty: 'easy',
    question: 'Temporal Difference (TD) learning, developed by Sutton, updates value estimates using:',
    options: [
      'The difference between the current estimate and the next step\'s estimate plus observed reward',
      'The full Monte Carlo return averaged over complete episodes',
      'The gradient of the Bellman equation with respect to state features',
      'The difference between consecutive action-value estimates over the same episode',
    ],
    correctIndex: 0,
    explanation: 'TD(0): V(s) ← V(s) + α[r + γV(s\') - V(s)]. The "TD error" δ = r + γV(s\') - V(s) is the difference between the bootstrapped target and current estimate — learning from incomplete episodes unlike Monte Carlo.',
    realWorld: 'AlphaGo, AlphaZero, and Atari-playing DQN all use TD learning. Dopamine neurons in the brain fire with TD-error-like signals — Sutton\'s algorithm may model biological reward learning.',
    hint: 'TD uses the next-state estimate as a "bootstrap" target — you don\'t wait until the episode ends to update.',
  },
  {
    id: 11802,
    topic: 'richard-sutton',
    difficulty: 'easy',
    question: 'The Q-learning update rule (Watkins, building on Sutton\'s work) is:',
    options: [
      '$Q(s,a) \\leftarrow Q(s,a) + \\alpha[r + \\gamma \\max_{a\'} Q(s\',a\') - Q(s,a)]$',
      '$Q(s,a) \\leftarrow r + \\gamma \\max_{a\'} Q(s\',a\')$',
      '$Q(s,a) \\leftarrow Q(s,a) - \\alpha \\nabla_{\\theta} \\mathbb{E}[R_t]$',
      '$Q(s,a) \\leftarrow \\mathbb{E}_{\\pi}[G_t | S_t=s, A_t=a]$',
    ],
    correctIndex: 0,
    explanation: 'Q-learning is off-policy TD — it uses the max over actions in the next state regardless of the behavior policy. This makes it off-policy and allows learning the optimal policy while following any exploration policy.',
    realWorld: 'Deep Q-Network (DQN) by DeepMind uses Q-learning with neural networks as Q-function approximators, achieving superhuman Atari performance. Every game-playing AI builds on this foundation.',
    hint: 'The key is max_{a\'} — Q-learning always assumes the best future action, making it off-policy.',
  },
  {
    id: 11803,
    topic: 'richard-sutton',
    difficulty: 'easy',
    question: 'Sutton\'s "Reward Hypothesis" claims that:',
    options: [
      'All goals and purposes of an intelligent agent can be formalized as maximizing expected cumulative scalar reward',
      'Reward signals must be dense (given at every step) for reinforcement learning to be effective',
      'Multi-objective problems require separate reward functions that cannot be combined',
      'Intrinsic motivation requires a separate non-scalar internal reward system',
    ],
    correctIndex: 0,
    explanation: 'The reward hypothesis is the central tenet of RL: goal-directed behavior = reward maximization. Despite its simplicity, it is surprisingly general — from playing games to language model alignment (RLHF) to robot control.',
    realWorld: 'RLHF (InstructGPT/ChatGPT) operationalizes the reward hypothesis: human preference ratings become a scalar reward signal used to align LLM outputs with human values.',
    hint: 'Chess winning, making coffee, translating text — can all these goals be captured by a single scalar?',
  },
  {
    id: 11804,
    topic: 'richard-sutton',
    difficulty: 'easy',
    question: 'In Sutton\'s RL framework, the distinction between "model-free" and "model-based" RL is:',
    options: [
      'Model-free learns value/policy directly from experience; model-based learns a world model and plans through it',
      'Model-free uses neural networks; model-based uses tabular representations',
      'Model-free is off-policy; model-based is on-policy by definition',
      'Model-free requires more data; model-based requires more compute',
    ],
    correctIndex: 0,
    explanation: 'Model-free (Q-learning, policy gradient) learns from raw experience without learning environment dynamics. Model-based (Dyna, MBPO, AlphaZero) learns P(s\'|s,a) and R(s,a) and plans by simulating trajectories.',
    realWorld: 'AlphaZero is model-based (uses the game rules as a perfect model for MCTS). DQN is model-free. Model-based RL is more sample efficient but requires accurate world models — a key research frontier.',
    hint: 'Does the agent learn what will happen next (model), or just what to do (policy/value)?',
  },
  {
    id: 11805,
    topic: 'richard-sutton',
    difficulty: 'hard',
    question: 'TD(λ) interpolates between TD(0) and Monte Carlo using eligibility traces. The λ-return $G_t^\\lambda$ is:',
    options: [
      '$(1-\\lambda)\\sum_{n=1}^{\\infty} \\lambda^{n-1} G_t^{(n)}$ — a geometric mixture of n-step returns',
      '$\\lambda G_t + (1-\\lambda) V(S_t)$ — a linear blend of full return and value estimate',
      '$\\sum_{t\'=t}^{T} \\lambda^{t\'-t} r_{t\'}$ — geometrically discounted future rewards',
      '$G_t^{(\\lceil \\lambda T \\rceil)}$ — the $(\\lambda T)$-step return rounded to an integer',
    ],
    correctIndex: 0,
    explanation: 'The λ-return combines all n-step returns with geometric weights (1-λ)λ^{n-1}. λ=0 gives TD(0); λ=1 gives Monte Carlo. Eligibility traces implement this efficiently online: z_t = γλ z_{t-1} + ∇V(s_t).',
    realWorld: 'TD(λ) with function approximation (Sutton\'s linear FA paper) is the theoretical basis for modern actor-critic methods and policy gradient algorithms used in robotics and game AI.',
    hint: 'λ controls the bias-variance tradeoff: λ=0 is high bias (one-step); λ=1 is high variance (full episode).',
  },
  {
    id: 11806,
    topic: 'richard-sutton',
    difficulty: 'hard',
    question: 'The policy gradient theorem (Sutton et al. 1999) states that $\\nabla J(\\theta) \\propto$:',
    options: [
      '$\\sum_s \\mu(s) \\sum_a Q^\\pi(s,a) \\nabla_{\\theta} \\pi(a|s,\\theta)$',
      '$\\mathbb{E}_{\\pi}[\\nabla_{\\theta} \\log \\pi(a|s,\\theta) \\cdot R_t]$',
      '$\\nabla_{\\theta} \\mathbb{E}_{\\pi}[r_t + \\gamma V(s_{t+1}) - V(s_t)]$',
      '$\\sum_t \\nabla_{\\theta} \\pi(a_t|s_t) \\cdot (G_t - b(s_t))$',
    ],
    correctIndex: 0,
    explanation: 'The policy gradient theorem gives an exact expression for ∇J without differentiating the state distribution — key since μ(s) depends on θ in a complex way. REINFORCE, PPO, SAC all implement variations of this gradient estimator.',
    realWorld: 'Every RLHF-trained LLM (ChatGPT, Claude, Gemini) is optimized using the policy gradient theorem — the gradient of expected human preference reward with respect to model parameters.',
    hint: 'The elegance: ∇J only requires ∇π, not ∇μ — the state distribution derivative cancels out.',
  },
  {
    id: 11807,
    topic: 'richard-sutton',
    difficulty: 'hard',
    question: 'The "deadly triad" in RL (Sutton & Barto 2018) refers to the dangerous combination of:',
    options: [
      'Function approximation + bootstrapping + off-policy learning — together can cause divergence',
      'Sparse rewards + continuous actions + partial observability — causing sample inefficiency',
      'High learning rate + large replay buffer + no target network — causing Q-value explosion',
      'Actor-critic + eligibility traces + entropy regularization — causing policy collapse',
    ],
    correctIndex: 0,
    explanation: 'Each component alone is stable, but together they can cause Q-values to diverge to infinity. DQN manages this via target networks (frozen bootstrapping) and experience replay (breaking correlations), but the triad remains an open theoretical problem.',
    realWorld: 'Early attempts at neural network RL failed due to the deadly triad. DQN\'s target networks and replay buffer are engineering solutions to this fundamental instability — still an active research area.',
    hint: 'Function approximation generalizes; bootstrapping reuses estimates; off-policy samples from different policies — each is fine alone.',
  },
  {
    id: 11808,
    topic: 'richard-sutton',
    difficulty: 'sota',
    question: 'Sutton\'s "Bitter Lesson" (2019) argues that the history of AI shows:',
    options: [
      'General methods leveraging computation (search + learning) always outperform human-knowledge-based approaches in the long run',
      'Hand-crafted features are essential for sample efficiency in real-world AI systems',
      'Symbolic AI will eventually surpass neural networks for reasoning tasks',
      'Scaling model size is less important than improving training data quality',
    ],
    correctIndex: 0,
    explanation: 'Reviewing 70 years of AI history, Sutton shows: chess (minimax search beats handcrafted evaluation), Go (MCTS/learning beats human patterns), speech (end-to-end learning beats HMM+linguistics). Computation scales; human knowledge doesn\'t.',
    realWorld: 'GPT-3 to GPT-4 exemplifies the Bitter Lesson — scaling computation and data overwhelmed all specialized NLP approaches. The pattern repeats in protein folding (AlphaFold), robotics, and scientific discovery.',
    hint: 'IBM\'s chess programs failed by modeling chess knowledge; Deep Blue won with brute-force search. Which approach generalized?',
  },
  {
    id: 11809,
    topic: 'richard-sutton',
    difficulty: 'sota',
    question: 'Dyna architecture (Sutton 1991) integrates model-free and model-based RL by:',
    options: [
      'Interleaving real environment steps with simulated steps from a learned model, sharing the same Q-learning update',
      'Using the world model to initialize the Q-function before model-free fine-tuning',
      'Training the world model on the Q-function\'s prediction errors',
      'Applying model-based planning only during evaluation, while training remains model-free',
    ],
    correctIndex: 0,
    explanation: 'Dyna-Q performs n simulated updates per real step: the learned model P(s\'|s,a), R(s,a) generates synthetic experience used for Q-learning. This dramatically improves sample efficiency — key for real-robot learning where interaction is expensive.',
    realWorld: 'MBPO (Janner et al. 2019) — a modern Dyna variant — achieves state-of-art sample efficiency on MuJoCo robot tasks. AlphaZero uses perfect model + MCTS — Dyna with a perfect simulator.',
    hint: 'Real interaction is expensive; simulated rollouts are cheap. Why not use the learned model to practice?',
  },
  {
    id: 11810,
    topic: 'richard-sutton',
    difficulty: 'sota',
    question: 'Proximal Policy Optimization (PPO), building on Sutton\'s policy gradient work, stabilizes training using:',
    options: [
      'A clipped surrogate objective that limits policy updates to stay within a trust region without computing the KL divergence exactly',
      'A constraint on the Fisher information matrix to ensure natural gradient updates',
      'A replay buffer shared between the actor and critic networks',
      'Entropy regularization added to the policy gradient loss',
    ],
    correctIndex: 0,
    explanation: 'PPO clips the probability ratio r_t(θ) = π_θ/π_{θ_old} to [1-ε, 1+ε], preventing large policy updates that destabilize training. This is simpler than TRPO\'s constrained optimization while achieving similar performance.',
    realWorld: 'PPO is the default RL algorithm for RLHF (ChatGPT, Claude, Gemini alignment). Its simplicity and stability made it the industry standard for training large models from human feedback.',
    hint: 'Clip the policy update ratio to [1-ε, 1+ε] — this prevents catastrophically large steps without solving a constrained optimization problem.',
  },
];
