import type { Question } from '../types';

export const richardFeynmanQuestions: Question[] = [
  {
    id: 10051,
    topic: 'richard-feynman',
    difficulty: 'easy',
    question: 'Feynman\'s path integral formulation of quantum mechanics says the probability amplitude is:',
    options: [
      'The sum of $e^{iS/\\hbar}$ over all possible paths from $A$ to $B$, where $S$ is the classical action',
      'The eigenvalue of the Hamiltonian operator acting on the wave function',
      'The product of transition probabilities along the most likely path',
      'The Fourier transform of the position-space wave function',
    ],
    correctIndex: 0,
    explanation: 'Instead of a single classical trajectory, quantum mechanics sums contributions $e^{iS[x(t)]/\\hbar}$ from all paths. Classical mechanics emerges in the limit $\\hbar \\to 0$ where destructive interference cancels all but the stationary-action path.',
    realWorld: 'Path integrals underlie quantum field theory, lattice QCD simulations, and financial option pricing (the Black-Scholes model is a path integral over Brownian motion).',
    hint: 'Every possible path contributes — the most probable path is just where they constructively interfere.',
  },
  {
    id: 10052,
    topic: 'richard-feynman',
    difficulty: 'easy',
    question: 'Feynman diagrams are graphical representations of:',
    options: [
      'Terms in a perturbation expansion of a quantum field theory amplitude',
      'Electron orbital transitions in atomic physics',
      'The energy spectrum of a quantum harmonic oscillator',
      'Classical scattering trajectories of charged particles',
    ],
    correctIndex: 0,
    explanation: 'Each Feynman diagram corresponds to a mathematical term in the perturbation series for a scattering amplitude. Lines represent particles; vertices represent interactions. The diagrams are a bookkeeping tool for quantum field theory calculations.',
    realWorld: 'QED calculations using Feynman diagrams have matched experiments to 12 significant figures — the most precise predictions in physics.',
    hint: 'Each diagram = one term in an infinite series. More complex diagrams = higher-order quantum corrections.',
  },
  {
    id: 10053,
    topic: 'richard-feynman',
    difficulty: 'easy',
    question: 'Feynman proposed quantum computers in 1982 because:',
    options: [
      'Classical computers cannot efficiently simulate quantum systems due to exponentially large state spaces',
      'Quantum computers can solve NP-complete problems in polynomial time',
      'Classical computers violate Heisenberg\'s uncertainty principle when simulating particles',
      'Quantum computers can process analog signals with infinite precision',
    ],
    correctIndex: 0,
    explanation: 'Feynman observed that simulating $n$ quantum particles on a classical computer requires exponential memory and time (the Hilbert space is $2^n$-dimensional). A quantum computer naturally represents these states with $n$ qubits.',
    realWorld: 'Quantum chemistry simulation is the killer app for quantum computers — modeling drug molecules, catalysts, and materials that are intractable classically.',
    hint: 'To simulate quantum nature, use quantum nature — a quantum computer is nature simulating itself.',
  },
  {
    id: 10054,
    topic: 'richard-feynman',
    difficulty: 'easy',
    question: 'The principle of least action states that a physical system evolves by:',
    options: [
      'The path that makes the action $S = \\int L\\,dt$ stationary (typically minimal)',
      'The path of maximum entropy production at each instant',
      'The trajectory with the least total distance traveled',
      'The path minimizing kinetic energy subject to energy conservation',
    ],
    correctIndex: 0,
    explanation: 'The action $S = \\int_a^b L(q, \\dot{q}, t)\\,dt$ is stationary for the true path (Euler-Lagrange equations). This unifies classical mechanics, optics, and field theory in one elegant variational principle.',
    realWorld: 'Physics-informed neural networks (PINNs) embed least-action principles as loss terms, enabling data-efficient physics simulation.',
    hint: 'Nature is lazy — it takes the path that doesn\'t deviate from optimality.',
  },
  {
    id: 10055,
    topic: 'richard-feynman',
    difficulty: 'hard',
    question: 'In the path integral formulation, the propagator $K(x_b, t_b; x_a, t_a)$ satisfies:',
    options: [
      'The Schrödinger equation $i\\hbar \\partial_t K = \\hat{H} K$ with initial condition $K(x,t;x_a,t_a) \\to \\delta(x-x_a)$ as $t \\to t_a$',
      'The classical Hamilton-Jacobi equation with stochastic boundary conditions',
      'The heat equation $\\partial_t K = D\\nabla^2 K$ after Wick rotation to imaginary time',
      'The Fokker-Planck equation for the probability density of paths',
    ],
    correctIndex: 0,
    explanation: 'The propagator $K$ is the Green\'s function of the Schrödinger equation — it gives the amplitude to go from $(x_a, t_a)$ to $(x_b, t_b)$. After Wick rotation $t \\to -i\\tau$, it becomes the heat equation propagator, connecting QM to statistical mechanics.',
    realWorld: 'This Wick rotation bridge is why lattice QCD simulations use imaginary time (Euclidean path integrals) — it makes the integrand real and positive, enabling Monte Carlo sampling.',
    hint: 'The propagator is the quantum mechanical kernel that evolves wave functions forward in time.',
  },
  {
    id: 10056,
    topic: 'richard-feynman',
    difficulty: 'hard',
    question: 'Physics-Informed Neural Networks (PINNs) incorporate physical laws by:',
    options: [
      'Adding PDE residual terms to the loss function: $\\mathcal{L} = \\mathcal{L}_{data} + \\lambda\\|\\mathcal{N}[u]\\|^2$ where $\\mathcal{N}$ is the differential operator',
      'Using physics equations as activation functions in each network layer',
      'Pre-training on physics simulation data before fine-tuning on observations',
      'Constraining weight matrices to be physically interpretable rotation matrices',
    ],
    correctIndex: 0,
    explanation: 'PINNs (Raissi et al. 2019) train a neural network $u_\\theta(x,t)$ to satisfy both data constraints and PDE constraints simultaneously. The PDE is enforced via automatic differentiation computing $\\mathcal{N}[u_\\theta]$ as a loss term.',
    realWorld: 'PINNs solve fluid dynamics, heat transfer, and wave equations without meshes — critical for real-time simulation in engineering design.',
    hint: 'The network learns to satisfy both the data and the physics equations — the equations are the regularizer.',
  },
  {
    id: 10057,
    topic: 'richard-feynman',
    difficulty: 'hard',
    question: 'Renormalization in quantum field theory addresses:',
    options: [
      'Divergences in loop integrals by absorbing infinities into redefined physical parameters',
      'The normalization of quantum state vectors to unit probability',
      'The rescaling of units from natural units to SI units in calculations',
      'The convergence of perturbation series by resumming higher-order terms',
    ],
    correctIndex: 0,
    explanation: 'Loop Feynman diagrams give divergent integrals. Renormalization (systematized by Feynman, Schwinger, Tomonaga) regularizes these, absorbs infinities into bare parameters, and extracts finite physical predictions. This made QED predictive.',
    realWorld: 'The renormalization group (Wilson) explains why different theories look similar at different scales — fundamental to phase transitions, critical phenomena, and why QCD becomes weakly coupled at high energies.',
    hint: 'Infinities appear, but they can be hidden in unobservable bare parameters — what\'s left is finite and predictive.',
  },
  {
    id: 10058,
    topic: 'richard-feynman',
    difficulty: 'sota',
    question: 'Shor\'s quantum factoring algorithm achieves exponential speedup using:',
    options: [
      'Quantum Fourier Transform to find the period of $f(x) = a^x \\mod N$, reducing factoring to period-finding',
      'Grover\'s search to find factors quadratically faster than classical trial division',
      'Quantum annealing to minimize the factoring cost function',
      'Quantum phase estimation to compute the discrete logarithm of $N$',
    ],
    correctIndex: 0,
    explanation: 'Shor (1994): factoring $N$ reduces to finding the period $r$ of $f(x) = a^x \\mod N$. The QFT finds $r$ in $O((\\log N)^3)$ quantum operations vs. the best classical $e^{O(\\sqrt[3]{\\log N})}$. The factors are then $\\gcd(a^{r/2} \\pm 1, N)$.',
    realWorld: 'RSA-2048 encryption would fall in hours to a large enough quantum computer running Shor\'s algorithm — motivating post-quantum cryptography standardization (NIST 2024).',
    hint: 'The trick: factoring reduces to period-finding, and the QFT finds periods exponentially faster than classical FFT.',
  },
  {
    id: 10059,
    topic: 'richard-feynman',
    difficulty: 'sota',
    question: 'The variational quantum eigensolver (VQE) finds ground state energies by:',
    options: [
      'Minimizing $\\langle \\psi(\\theta) | H | \\psi(\\theta) \\rangle$ over parameters $\\theta$ of a parameterized quantum circuit',
      'Applying quantum phase estimation with exponentially deep circuits',
      'Running Hamiltonian simulation for time $T = 1/\\Delta E$ and measuring the energy gap',
      'Performing quantum annealing by slowly turning on the problem Hamiltonian',
    ],
    correctIndex: 0,
    explanation: 'VQE is a hybrid quantum-classical algorithm: a quantum circuit prepares a parameterized trial state, classical optimization minimizes the energy expectation. The variational principle guarantees $\\langle\\psi|H|\\psi\\rangle \\geq E_0$.',
    realWorld: 'VQE on near-term (NISQ) quantum hardware is the leading approach for quantum chemistry — finding ground states of molecules like FeMoco for nitrogen fixation.',
    hint: 'The variational principle: any guess for the wave function gives an energy above the true ground state.',
  },
  {
    id: 10060,
    topic: 'richard-feynman',
    difficulty: 'sota',
    question: 'Feynman\'s checkerboard model shows that the Dirac equation in 1+1 dimensions can be derived as:',
    options: [
      'A limit of a discrete random walk on a checkerboard where the particle changes direction with amplitude $i\\epsilon m$',
      'A continuous-time Markov chain on a bipartite graph with transition rates $mc^2/\\hbar$',
      'A lattice gauge theory with staggered fermions on a checkerboard lattice',
      'A cellular automaton that reproduces quantum interference from classical update rules',
    ],
    correctIndex: 0,
    explanation: 'Feynman showed that a particle moving on a checkerboard lattice, making straight paths but changing direction with amplitude $i\\epsilon m c^2/\\hbar$ at each step, gives the Dirac propagator in the continuum limit. This makes spin and special relativity emerge from a simple combinatorial rule.',
    realWorld: 'This model inspired lattice QFT and modern tensor network methods for simulating quantum systems — a connection between combinatorics and relativistic quantum mechanics.',
    hint: 'A zig-zagging path on a lattice becomes Dirac\'s relativistic electron equation in the continuum limit.',
  },
];
