import type { Question } from '../types';

export const robertTibshiraniQuestions: Question[] = [
  {
    id: 21300,
    topic: 'robert-tibshirani',
    difficulty: 'easy',
    question: 'What does LASSO stand for in Tibshirani\'s 1996 paper?',
    options: [
      'Least Absolute Shrinkage and Selection Operator',
      'Linear Algebraic Sparse Signal Optimizer',
      'Lagrangian Adjusted Sum of Squared Observations',
      'Least Additive Sequential Subset Operator'
    ],
    correctIndex: 0,
    explanation: 'LASSO = Least Absolute Shrinkage and Selection Operator. It adds an $L_1$ penalty $\\lambda\\|\\beta\\|_1$ to ordinary least squares, which drives some coefficients exactly to zero — performing automatic variable selection.',
    realWorld: 'Genomics labs use LASSO to find the ~20 disease-associated genes out of 20,000+ candidates.',
    hint: 'The name describes both what the penalty does (shrinks) and what it achieves (selects).',
    symbolLinks: { 'λ': 'lambda', 'β': 'beta' },
    formulaLinks: ['lasso-l1-regularisation'],
    glossaryLinks: ['lasso', 'regularization'],
  },
  {
    id: 21301,
    topic: 'robert-tibshirani',
    difficulty: 'easy',
    question: 'LASSO\'s $L_1$ penalty induces what property in the solution vector $\\hat{\\beta}$?',
    options: [
      'Sparsity — many coefficients are exactly zero',
      'Smoothness — all coefficients are small but nonzero',
      'Orthogonality — coefficients are mutually perpendicular',
      'Normality — coefficients follow a Gaussian distribution'
    ],
    correctIndex: 0,
    explanation: 'The $L_1$ ball has corners on the coordinate axes. The constrained optimum typically lands on a corner, zeroing out some coordinates. This geometric property makes LASSO a variable selector, not just a shrinkage estimator.',
    realWorld: 'In clinical trials, LASSO identifies which of 500 biomarkers actually predict patient response.',
    hint: 'Think about the geometry of the diamond-shaped $L_1$ constraint region.',
    symbolLinks: { 'β': 'beta' },
    formulaLinks: ['lasso-l1-regularisation'],
    glossaryLinks: ['lasso', 'sparsity'],
  },
  {
    id: 21302,
    topic: 'robert-tibshirani',
    difficulty: 'hard',
    question: 'How does Elastic Net (Zou & Hastie, 2005) extend Tibshirani\'s LASSO?',
    options: [
      'Combines $L_1$ and $L_2$ penalties: $\\lambda_1\\|\\beta\\|_1 + \\lambda_2\\|\\beta\\|_2^2$',
      'Replaces $L_1$ with $L_\\infty$ penalty',
      'Uses an adaptive weighting scheme on each coefficient',
      'Applies LASSO iteratively with decreasing $\\lambda$'
    ],
    correctIndex: 0,
    explanation: 'Elastic Net adds a Ridge ($L_2$) penalty alongside LASSO\'s $L_1$. This handles correlated predictors better — where LASSO arbitrarily selects one from a correlated group, Elastic Net keeps them together. The $L_2$ term also ensures a unique solution when $p \\gg n$.',
    realWorld: 'Gene expression studies with correlated gene pathways use Elastic Net because pure LASSO drops important co-regulated genes.',
    hint: 'It\'s a convex combination of two familiar penalties.',
    symbolLinks: { 'λ': 'lambda', 'β': 'beta' },
    formulaLinks: ['lasso-l1-regularisation', 'elastic-net'],
    glossaryLinks: ['lasso', 'elastic-net', 'regularization'],
  },
  {
    id: 21303,
    topic: 'robert-tibshirani',
    difficulty: 'hard',
    question: 'Tibshirani\'s SAM (Significance Analysis of Microarrays) addresses what problem in genomics?',
    options: [
      'Multiple testing: identifying truly differentially expressed genes among thousands',
      'Sequence alignment of DNA fragments',
      'Protein folding prediction',
      'Phylogenetic tree construction'
    ],
    correctIndex: 0,
    explanation: 'With 20,000+ genes tested simultaneously, naive $t$-tests produce massive false positives. SAM uses a modified $t$-statistic with permutation-based FDR control, handling the "small $n$, large $p$" problem where you have few samples but thousands of variables.',
    realWorld: 'SAM identified differentially expressed genes in breast cancer subtypes, leading to targeted therapies.',
    hint: 'Testing thousands of hypotheses simultaneously requires controlling the false discovery rate.',
    symbolLinks: { 'n': 'nu' },
    formulaLinks: ['sam-statistic'],
    glossaryLinks: ['false-discovery-rate', 'multiple-testing'],
  },
  {
    id: 21304,
    topic: 'robert-tibshirani',
    difficulty: 'hard',
    question: 'In "The Elements of Statistical Learning" (Hastie, Tibshirani, Friedman), what is the bias-variance decomposition?',
    options: [
      '$\\text{MSE} = \\text{Bias}^2 + \\text{Variance} + \\text{Irreducible Noise}$',
      '$\\text{MSE} = \\text{Bias} + \\text{Variance}$',
      '$\\text{MSE} = \\text{Bias} \\times \\text{Variance}$',
      '$\\text{MSE} = \\text{Variance} / \\text{Bias}$'
    ],
    correctIndex: 0,
    explanation: 'For a prediction $\\hat{f}(x)$: $E[(y - \\hat{f})^2] = (E[\\hat{f}] - f)^2 + E[(\\hat{f} - E[\\hat{f}])^2] + \\sigma^2$. LASSO trades increased bias for reduced variance, winning when $p \\gg n$.',
    realWorld: 'Every ML model selection decision is implicitly a bias-variance trade-off.',
    hint: 'Expected prediction error decomposes into three additive terms.',
    symbolLinks: { 'σ': 'sigma' },
    formulaLinks: ['bias-variance-decomposition'],
    glossaryLinks: ['bias-variance-tradeoff'],
  },
  {
    id: 21305,
    topic: 'robert-tibshirani',
    difficulty: 'sota',
    question: 'The LASSO solution path as $\\lambda$ varies is computed efficiently by which algorithm?',
    options: [
      'LARS (Least Angle Regression) — piecewise-linear path in $O(np \\min(n,p))$',
      'Gradient descent with adaptive learning rate',
      'Newton\'s method with Hessian computation',
      'Simulated annealing over the coefficient space'
    ],
    correctIndex: 0,
    explanation: 'Efron, Hastie, Johnstone & Tibshirani (2004) showed the entire LASSO regularization path is piecewise linear. LARS traces this path efficiently: at each step, the coefficient most correlated with the residual enters, and the algorithm adjusts angles to maintain equal correlation — computing all solutions for every $\\lambda$ at the cost of a single OLS fit.',
    realWorld: 'LARS makes cross-validation over $\\lambda$ essentially free — you get the full path, not just one solution.',
    hint: 'The path is piecewise linear, so you can compute it exactly with a modified forward selection.',
    symbolLinks: { 'λ': 'lambda' },
    formulaLinks: ['lasso-l1-regularisation'],
    glossaryLinks: ['lasso', 'lars'],
    paper: {
      title: 'Least Angle Regression',
      url: 'https://projecteuclid.org/journals/annals-of-statistics/volume-32/issue-2/Least-angle-regression/10.1214/009053604000000067.full',
      venue: 'Annals of Statistics',
      year: 2004,
    },
  },
  {
    id: 21306,
    topic: 'robert-tibshirani',
    difficulty: 'sota',
    question: 'Tibshirani\'s "gap statistic" (2001) estimates what in unsupervised learning?',
    options: [
      'The optimal number of clusters $k$ by comparing within-cluster dispersion to a null reference',
      'The optimal regularization parameter $\\lambda$',
      'The number of principal components to retain',
      'The false discovery rate in multiple testing'
    ],
    correctIndex: 0,
    explanation: 'Gap$(k) = E^*[\\log W_k] - \\log W_k$, where $W_k$ is within-cluster sum of squares and $E^*$ is expectation under a null reference distribution (uniform). The optimal $k$ maximizes the gap — the biggest departure from random clustering. Elegant because it provides a principled stopping rule rather than ad-hoc "elbow" methods.',
    realWorld: 'Used in customer segmentation, single-cell RNA-seq clustering, and market regime detection.',
    hint: 'Compare your clustering quality to what you\'d get from uniformly distributed data.',
    symbolLinks: { 'k': 'kappa' },
    formulaLinks: ['gap-statistic'],
    glossaryLinks: ['clustering', 'k-means'],
    paper: {
      title: 'Estimating the Number of Clusters in a Data Set via the Gap Statistic',
      url: 'https://hastie.su.domains/Papers/gap.pdf',
      venue: 'Journal of the Royal Statistical Society B',
      year: 2001,
    },
  },
  {
    id: 21307,
    topic: 'robert-tibshirani',
    difficulty: 'sota',
    question: 'Conformal prediction (Tibshirani et al., 2019 extensions) provides what guarantee for ML predictions?',
    options: [
      'Distribution-free prediction intervals with exact finite-sample coverage $P(Y \\in C(X)) \\geq 1-\\alpha$',
      'Asymptotic normality of the estimator',
      'Minimax optimal convergence rates',
      'Unbiased risk estimation via cross-validation'
    ],
    correctIndex: 0,
    explanation: 'Conformal prediction wraps any black-box model to produce prediction sets $C(X)$ that contain the true $Y$ with probability $\\geq 1-\\alpha$, with NO distributional assumptions beyond exchangeability. Works for neural nets, random forests, anything. The coverage guarantee is exact, not asymptotic.',
    realWorld: 'Medical AI: "This patient\'s risk is 30-45% with 90% coverage" instead of a bare point estimate.',
    hint: 'The guarantee holds in finite samples — no asymptotics needed.',
    symbolLinks: { 'α': 'alpha' },
    formulaLinks: ['conformal-prediction'],
    glossaryLinks: ['conformal-prediction', 'prediction-interval'],
    paper: {
      title: 'Conformal Prediction Under Covariate Shift',
      url: 'https://arxiv.org/abs/1904.06019',
      venue: 'NeurIPS',
      year: 2019,
    },
  },
];
