import type { Question } from '../types';

export const rogerPenroseQuestions: Question[] = [
  {
    id: 21020,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'Penrose\'s singularity theorem proves that gravitational collapse inevitably produces singularities under what key condition?',
    options: ['The existence of a trapped surface', 'The presence of a Killing vector field', 'The vanishing of the Weyl tensor', 'The absence of angular momentum'],
    correctIndex: 0,
    explanation: 'Penrose proved that once a trapped surface forms (where both ingoing and outgoing light rays converge), singularity formation is inevitable under general relativity with reasonable energy conditions.',
    realWorld: 'This theorem provided the first rigorous mathematical proof that black holes must form in nature, earning Penrose the 2020 Nobel Prize in Physics.',
    hint: 'It involves a surface from which light cannot escape in any direction.',
  },
  {
    id: 21021,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'Penrose tilings are a famous example of what mathematical property?',
    options: ['Aperiodicity — they tile the plane without repeating', 'Fractality — they are self-similar at every scale', 'Hyperbolicity — they tile the hyperbolic plane', 'Periodicity — they have a fundamental domain'],
    correctIndex: 0,
    explanation: 'Penrose tilings use two shapes to cover the infinite plane without any translational symmetry, yet they possess five-fold rotational symmetry forbidden by classical crystallography.',
    realWorld: 'The discovery of quasicrystals by Dan Shechtman (2011 Nobel Prize in Chemistry) confirmed that Penrose-tiling symmetries exist in nature.',
    hint: 'The pattern never repeats, yet it is not random.',
  },
  {
    id: 21022,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'What is the name of Penrose\'s graphical notation for multilinear algebra in general relativity?',
    options: ['Penrose graphical notation (tensor diagrams)', 'Feynman diagrams', 'Dynkin diagrams', 'Chord diagrams'],
    correctIndex: 0,
    explanation: 'Penrose invented a diagrammatic notation where tensors are represented as shapes and contractions as connecting lines, greatly simplifying calculations in general relativity and quantum gravity.',
    realWorld: 'This notation evolved into modern tensor network methods used in quantum computing and machine learning.',
    hint: 'It replaces index-heavy tensor equations with intuitive pictures.',
  },
  {
    id: 21023,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'Penrose\'s twistor theory reformulates spacetime geometry using objects in which kind of space?',
    options: ['Complex projective 3-space $\\mathbb{CP}^3$', 'Real projective 4-space $\\mathbb{RP}^4$', 'Minkowski space $\\mathbb{R}^{3,1}$', 'Hilbert space $\\mathcal{H}$'],
    correctIndex: 0,
    explanation: 'Twistor space $\\mathbb{CP}^3$ encodes the geometry of Minkowski spacetime, translating gravitational physics problems into complex geometry where powerful algebraic tools apply.',
    realWorld: 'Twistor methods revolutionized the calculation of scattering amplitudes in particle physics (Witten\'s twistor string theory).',
    hint: 'The fundamental objects are null geodesics (light rays) encoded as points in a complex space.',
  },
  {
    id: 21024,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'In 2023, what geometric breakthrough related to Penrose was achieved with a single tile shape?',
    options: ['The "einstein" aperiodic monotile was discovered', 'A periodic monotile was found to tile all dimensions', 'Penrose tilings were proven to be periodic after all', 'A single tile was shown to tile hyperbolic space'],
    correctIndex: 0,
    explanation: 'The "hat" tile (an einstein or "one stone") was discovered by David Smith et al. in 2023, proving that a single shape can tile the plane aperiodically — something Penrose\'s original tilings required two shapes to do.',
    realWorld: 'This solved a 60-year-old open problem in combinatorial geometry and tiling theory.',
    hint: 'The German word "ein Stein" means "one stone" — a single tile that forces aperiodicity.',
  },
];
