import type { Question } from '../types';

export const rogerPenroseQuestions: Question[] = [
  {
    id: 21020,
    topic: 'roger-penrose',
    difficulty: 'easy',
    question: 'Penrose\'s singularity theorem proves that gravitational collapse inevitably produces singularities under what key condition?',
    options: ['The existence of a trapped surface', 'The presence of a Killing vector field', 'The vanishing of the Weyl tensor', 'The absence of angular momentum'],
    correctIndex: 0,
    explanation: 'Penrose proved that once a trapped surface forms (where both ingoing and outgoing light rays converge), singularity formation is inevitable under general relativity with reasonable energy conditions.',
    realWorld: 'This theorem provided the first rigorous mathematical proof that black holes must form in nature, earning Penrose the 2020 Nobel Prize in Physics.',
    hint: 'It involves a surface from which light cannot escape in any direction.',
    glossaryLinks: ['black-hole-entropy'],
  },
  {
    id: 21021,
    topic: 'roger-penrose',
    difficulty: 'easy',
    question: 'Penrose tilings are a famous example of what mathematical property?',
    options: ['Aperiodicity — they tile the plane without repeating', 'Fractality — they are self-similar at every scale', 'Hyperbolicity — they tile the hyperbolic plane', 'Periodicity — they have a fundamental domain'],
    correctIndex: 0,
    explanation: 'Penrose tilings use two shapes to cover the infinite plane without any translational symmetry, yet they possess five-fold rotational symmetry forbidden by classical crystallography.',
    realWorld: 'The discovery of quasicrystals by Dan Shechtman (2011 Nobel Prize in Chemistry) confirmed that Penrose-tiling symmetries exist in nature.',
    hint: 'The pattern never repeats, yet it is not random.',
  },
  {
    id: 21022,
    topic: 'roger-penrose',
    difficulty: 'hard',
    question: 'Penrose\'s Objective Reduction (OR) proposes that quantum superpositions collapse when:',
    options: [
      'The gravitational self-energy $E_G$ of the superposed mass distribution reaches $\\hbar / \\tau$ — spacetime geometry itself becomes unstable',
      'An observer makes a measurement, following the Copenhagen interpretation',
      'Environmental decoherence causes the density matrix to diagonalize',
      'The wavefunction reaches the boundary of the universe',
    ],
    correctIndex: 0,
    explanation: 'Penrose argues that quantum superpositions of different spacetime geometries are inherently unstable. When the gravitational self-energy difference $E_G$ between two superposed configurations satisfies $\\tau \\approx \\hbar / E_G$, the superposition spontaneously collapses — a non-computable, non-unitary process built into the fabric of spacetime.',
    realWorld: 'OR is the physical mechanism underlying Orch OR (with Hameroff): in microtubules, ~10⁴ tubulins yield $\\tau \\sim 25$ ms, matching the 40 Hz rhythm of consciousness.',
    hint: 'The collapse is gravitational, not environmental — spacetime itself can\'t sustain the superposition.',
    glossaryLinks: ['objective-reduction', 'orch-or'],
    formulaLinks: ['penrose-or-timescale'],
  },
  {
    id: 21023,
    topic: 'roger-penrose',
    difficulty: 'hard',
    question: 'Penrose\'s twistor theory reformulates spacetime geometry using objects in which kind of space?',
    options: ['Complex projective 3-space $\\mathbb{CP}^3$', 'Real projective 4-space $\\mathbb{RP}^4$', 'Minkowski space $\\mathbb{R}^{3,1}$', 'Hilbert space $\\mathcal{H}$'],
    correctIndex: 0,
    explanation: 'Twistor space $\\mathbb{CP}^3$ encodes the geometry of Minkowski spacetime, translating gravitational physics problems into complex geometry where powerful algebraic tools apply.',
    realWorld: 'Twistor methods revolutionized the calculation of scattering amplitudes in particle physics (Witten\'s twistor string theory).',
    hint: 'The fundamental objects are null geodesics (light rays) encoded as points in a complex space.',
  },
  {
    id: 21024,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'Penrose\'s argument in "The Emperor\'s New Mind" (1989) uses Gödel\'s incompleteness theorems to claim that:',
    options: [
      'Human mathematical understanding involves non-computable processes — consciousness cannot be simulated by any Turing machine',
      'Quantum computers are more powerful than classical computers',
      'General relativity is an incomplete theory requiring quantum corrections',
      'The halting problem can be solved by sufficiently intelligent minds',
    ],
    correctIndex: 0,
    explanation: 'Penrose argues that mathematicians can perceive truths (e.g., the consistency of formal systems) that no algorithm can prove — citing Gödel\'s theorems. This implies human cognition transcends Turing computability, requiring new physics (OR) that is fundamentally non-algorithmic.',
    realWorld: 'This argument remains deeply controversial: most AI researchers and logicians disagree, but Penrose\'s position has never been formally refuted.',
    hint: 'Gödel showed limits of formal systems; Penrose argues human minds transcend those limits.',
    glossaryLinks: ['penrose-non-computability', 'objective-reduction'],
  },
  {
    id: 21025,
    topic: 'roger-penrose',
    difficulty: 'sota',
    question: 'In 2023, what geometric breakthrough related to Penrose was achieved with a single tile shape?',
    options: ['The "einstein" aperiodic monotile was discovered', 'A periodic monotile was found to tile all dimensions', 'Penrose tilings were proven to be periodic after all', 'A single tile was shown to tile hyperbolic space'],
    correctIndex: 0,
    explanation: 'The "hat" tile (an einstein or "one stone") was discovered by David Smith et al. in 2023, proving that a single shape can tile the plane aperiodically — something Penrose\'s original tilings required two shapes to do.',
    realWorld: 'This solved a 60-year-old open problem in combinatorial geometry and tiling theory.',
    hint: 'The German word "ein Stein" means "one stone" — a single tile that forces aperiodicity.',
  },
];
