import type { Question } from '../types';

export const satyendraBoseQuestions: Question[] = [
  {
    id: 20526,
    topic: 'satyendra-bose',
    difficulty: 'hard',
    question: 'Bose-Einstein statistics describe particles whose wave function is symmetric under exchange. What is the key consequence for occupation numbers?',
    options: ['Any number of bosons can occupy the same quantum state', 'At most one boson per state', 'Bosons must occupy adjacent energy levels', 'Bosons cannot exist at zero temperature'],
    correctIndex: 0,
    explanation: 'Unlike fermions (Pauli exclusion), bosons have no restriction on occupation numbers — enabling phenomena like Bose-Einstein condensation and laser coherence.',
    realWorld: 'Lasers work because photons (bosons) pile into the same quantum state, producing coherent light.',
    hint: 'The key difference from Fermi-Dirac statistics is about how many particles can share a state.',
  },
  {
    id: 20527,
    topic: 'satyendra-bose',
    difficulty: 'hard',
    question: 'Bose derived Planck\'s radiation law without using classical electrodynamics. His key insight was to treat photons as:',
    options: ['Indistinguishable particles counted by states, not individual identities', 'Classical waves with quantized energy', 'Distinguishable particles following Maxwell-Boltzmann statistics', 'Fermions with spin-1'],
    correctIndex: 0,
    explanation: 'Bose realized that photons are truly indistinguishable — swapping two photons doesn\'t create a new microstate. This changes the counting of states fundamentally.',
    realWorld: 'This insight that identical quantum particles lack individual identity is one of the deepest conceptual shifts in all of physics.',
    hint: 'Classical statistics treats particles as distinguishable balls; Bose said photons are not balls.',
  },
  {
    id: 20528,
    topic: 'satyendra-bose',
    difficulty: 'sota',
    question: 'Below the critical temperature $T_c$, a Bose gas undergoes Bose-Einstein condensation. For a 3D ideal Bose gas, $T_c$ scales with particle density $n$ as:',
    options: ['$T_c \\propto n^{2/3}$', '$T_c \\propto n$', '$T_c \\propto n^{1/2}$', '$T_c \\propto \\ln n$'],
    correctIndex: 0,
    explanation: '$T_c = \\frac{2\\pi\\hbar^2}{mk_B}\\left(\\frac{n}{\\zeta(3/2)}\\right)^{2/3}$. The $n^{2/3}$ scaling comes from the 3D density of states.',
    realWorld: 'BEC was achieved in labs in 1995 (Nobel Prize 2001) and is now used in quantum simulation and precision measurement.',
    hint: 'The exponent comes from the relationship between thermal de Broglie wavelength and interparticle spacing in 3D.',
  },
  {
    id: 20529,
    topic: 'satyendra-bose',
    difficulty: 'sota',
    question: 'The Higgs boson, discovered in 2012, is named after Bose\'s particle classification. What spin does the Higgs boson carry?',
    options: ['Spin-0 (scalar boson)', 'Spin-1', 'Spin-2', 'Spin-1/2'],
    correctIndex: 0,
    explanation: 'The Higgs is the only known fundamental scalar (spin-0) boson. Other bosons like photons (spin-1) and gravitons (spin-2, predicted) have higher spin.',
    realWorld: 'The Higgs field gives mass to fundamental particles — without it, electrons would be massless and atoms could not form.',
    hint: 'It\'s the simplest possible boson — no internal angular momentum.',
  },
  {
    id: 20530,
    topic: 'satyendra-bose',
    difficulty: 'easy',
    question: 'When journals rejected Bose\'s groundbreaking paper, who did he send it to for help?',
    options: ['Albert Einstein, who translated and published it', 'Niels Bohr', 'Max Planck', 'Werner Heisenberg'],
    correctIndex: 0,
    explanation: 'Einstein immediately recognized the paper\'s importance, translated it into German himself, and submitted it to Zeitschrift für Physik with his endorsement.',
    realWorld: 'Half the fundamental particles in the universe — "bosons" — are named in Bose\'s honor because of Einstein\'s championship of his work.',
    hint: 'The resulting statistics bear both their names.',
  },
];
