import type { Question } from '../types';

export const seppoLinnainmaaQuestions: Question[] = [
  {
    id: 412701,
    topic: 'seppo-linnainmaa',
    difficulty: 'easy',
    question: 'Seppo Linnainmaa\'s key contribution to AI is:',
    options: [
      'The first published algorithm for reverse-mode automatic differentiation (1970) — the mathematical foundation of backpropagation',
      'The invention of convolutional neural networks',
      'The discovery of the ReLU activation function',
      'The creation of the Python programming language',
    ],
    correctIndex: 0,
    explanation: 'In his 1970 master\'s thesis, Linnainmaa described the reverse-mode of automatic differentiation — computing $\\partial L / \\partial w$ by propagating derivatives backward through a computational graph. This is the core algorithm behind backpropagation.',
    realWorld: 'Every neural network trained today uses Linnainmaa\'s algorithm. PyTorch\'s autograd and TensorFlow\'s GradientTape are direct implementations of reverse-mode AD.',
    hint: 'He discovered the efficient way to compute gradients — working backwards from output to input.',
  },
  {
    id: 412702,
    topic: 'seppo-linnainmaa',
    difficulty: 'easy',
    question: 'The chain rule in reverse mode, as Linnainmaa formalized, computes $\\frac{\\partial L}{\\partial w}$ by:',
    options: [
      'Starting from the loss and propagating derivatives backward: $\\frac{\\partial L}{\\partial w} = \\frac{\\partial L}{\\partial a} \\cdot \\frac{\\partial a}{\\partial w}$',
      'Computing all derivatives simultaneously in parallel',
      'Starting from the inputs and propagating forward only',
      'Using finite differences to approximate each derivative',
    ],
    correctIndex: 0,
    explanation: 'Reverse-mode AD starts from the scalar loss L and chains derivatives backward through each operation. For a network with N parameters, this computes ALL N gradients in one backward pass — vastly more efficient than forward mode.',
    realWorld: 'This efficiency is why we can train models with billions of parameters. Forward-mode would require a separate pass per parameter — infeasible for modern networks.',
    hint: 'One backward pass gives you all gradients — that\'s the magic of reverse mode.',
  },
  {
    id: 412703,
    topic: 'seppo-linnainmaa',
    difficulty: 'hard',
    question: 'The historical controversy around backpropagation\'s invention involves:',
    options: [
      'Linnainmaa (1970) discovered reverse-mode AD, but Rumelhart, Hinton & Williams (1986) popularized its application to neural networks — the ideas are related but distinct',
      'Everyone agrees Hinton invented backpropagation from scratch',
      'Backpropagation was discovered by a single person with no precursors',
      'The algorithm was classified military research until 2000',
    ],
    correctIndex: 0,
    explanation: 'Linnainmaa (1970) and Werbos (1974) described the mathematical algorithm. Rumelhart, Hinton & Williams (1986) showed it could train multi-layer neural networks effectively. The algorithm vs. application distinction is crucial.',
    realWorld: 'This attribution debate highlights how scientific progress is often cumulative — the mathematical insight, the neural network application, and the computational resources all had to align.',
    hint: 'Multiple people contributed at different levels — math algorithm vs. neural network application.',
  },
  {
    id: 12704,
    topic: 'seppo-linnainmaa',
    difficulty: 'hard',
    question: 'Reverse-mode AD is more efficient than forward-mode AD for neural networks because:',
    options: [
      'It computes gradients for all parameters in $O(1)$ backward passes vs. $O(N)$ forward passes, since neural networks have many parameters but a scalar loss',
      'It uses less memory than forward mode',
      'It produces more accurate gradients',
      'It works without the chain rule',
    ],
    correctIndex: 0,
    explanation: 'With a scalar output (loss) and N parameters, reverse mode needs 1 backward pass to get all N gradients (cost: ~2-3× the forward pass). Forward mode would need N separate passes, one per parameter.',
    realWorld: 'A GPT-4-scale model with ~1.8 trillion parameters would need 1.8T forward passes with forward-mode AD. Reverse mode does it in one backward pass — the difference between feasible and impossible.',
    hint: 'Think about the shape: many inputs (parameters) → one output (loss). Reverse mode exploits this.',
  },
  {
    id: 12705,
    topic: 'seppo-linnainmaa',
    difficulty: 'sota',
    question: 'Modern automatic differentiation frameworks extend Linnainmaa\'s original algorithm with:',
    options: [
      'Dynamic computational graphs (tape-based AD) that record operations at runtime, enabling control flow (if/for) in differentiable programs',
      'Pre-computed static graphs that cannot handle variable-length inputs',
      'Symbolic differentiation that produces closed-form gradient expressions',
      'Numerical finite differences for all gradient computations',
    ],
    correctIndex: 0,
    explanation: 'PyTorch\'s autograd records a dynamic tape of operations during the forward pass, then replays it backward. This allows Python control flow (loops, conditionals) inside differentiable computations — a major advance over static graph frameworks.',
    realWorld: 'Dynamic AD enables differentiable programming: physics simulations, neural ODEs, and probabilistic programming all rely on differentiating through arbitrary code, not just fixed neural network architectures.',
    hint: 'The key advance is differentiating through arbitrary programs, not just fixed network architectures.',
  },
];
