import type { Question } from '../types';

export const shafiGoldwasserQuestions: Question[] = [
  {
    id: 12001,
    topic: 'shafi-goldwasser',
    difficulty: 'easy',
    question: 'Shafi Goldwasser co-invented zero-knowledge proofs. What is the key property?',
    options: [
      'The prover convinces the verifier a statement is true without revealing anything beyond its truth',
      'The proof is so short it takes zero storage space',
      'The verifier needs zero computational power to check the proof',
      'The proof requires no interaction between prover and verifier',
    ],
    correctIndex: 0,
    explanation: 'In a zero-knowledge proof, the verifier learns nothing except that the statement is true. Goldwasser, Micali, and Rackoff (1985) formalized this via simulation: anything the verifier "learns" could be simulated without the prover.',
    realWorld: 'Zero-knowledge proofs power privacy-preserving blockchain transactions (Zcash), identity verification without revealing personal data, and secure voting systems.',
    hint: 'Imagine proving you know a password without ever typing it — that\'s the spirit of zero-knowledge.',
  },
  {
    id: 12002,
    topic: 'shafi-goldwasser',
    difficulty: 'easy',
    question: 'Goldwasser and Micali defined the gold standard for encryption security called:',
    options: [
      'Semantic security — ciphertexts reveal no information about plaintexts to any efficient adversary',
      'Perfect secrecy — information-theoretic security like the one-time pad',
      'Post-quantum security — resistance to quantum computer attacks',
      'Differential privacy — bounding information leakage in databases',
    ],
    correctIndex: 0,
    explanation: 'Semantic security (1982) means no polynomial-time adversary can extract any partial information about the plaintext from the ciphertext. This became the standard security definition for all modern encryption schemes.',
    realWorld: 'Every modern encryption standard (AES, RSA-OAEP, elliptic curve encryption) is evaluated against semantic security. It\'s the foundation of provable security in cryptography.',
    hint: 'It\'s stronger than just "can\'t decrypt" — it means you can\'t learn ANYTHING about the message.',
  },
  {
    id: 12003,
    topic: 'shafi-goldwasser',
    difficulty: 'hard',
    question: 'Goldwasser\'s work on interactive proofs led to the IP = PSPACE theorem, which states:',
    options: [
      'Any problem solvable with polynomial space can be verified by an interactive protocol with a polynomial-time verifier',
      'All NP problems can be solved in polynomial time with interaction',
      'Interactive proofs are strictly more powerful than non-interactive proofs',
      'PSPACE problems require exponential communication in interactive proofs',
    ],
    correctIndex: 0,
    explanation: 'IP = PSPACE (Shamir 1992, building on Goldwasser et al.) shows that interactive proofs with a computationally unbounded prover and polynomial-time verifier capture exactly PSPACE — far more than NP.',
    realWorld: 'This theoretical result inspired practical protocols: verifiable computation lets cloud servers prove they computed correctly without re-doing the work, used in blockchain rollups and delegated computation.',
    hint: 'Interactive proofs can verify MUCH more than NP — they can verify anything solvable with polynomial space.',
  },
  {
    id: 12004,
    topic: 'shafi-goldwasser',
    difficulty: 'hard',
    question: 'The Goldwasser–Micali cryptosystem was the first to be provably semantically secure. Its security relies on:',
    options: [
      'The quadratic residuosity assumption — deciding if x is a square mod N is hard without knowing the factorization',
      'The discrete logarithm problem in prime-order groups',
      'The shortest vector problem in high-dimensional lattices',
      'The difficulty of factoring integers directly',
    ],
    correctIndex: 0,
    explanation: 'The GM cryptosystem encrypts one bit at a time. A random quadratic residue encodes 0; a random non-residue encodes 1. Without knowing the factorization of N = pq, distinguishing residues from non-residues is believed computationally hard.',
    realWorld: 'While not efficient enough for direct use today, GM\'s approach of reduction-based proofs became the template for designing and analyzing all modern cryptographic schemes.',
    hint: 'Is x a perfect square mod N? Easy if you know p, q. Hard otherwise.',
  },
  {
    id: 12005,
    topic: 'shafi-goldwasser',
    difficulty: 'sota',
    question: 'Modern succinct zero-knowledge proofs (zk-SNARKs), inspired by Goldwasser\'s foundational work, achieve:',
    options: [
      'Constant-size proofs verifiable in milliseconds for arbitrary computations, using elliptic curve pairings and polynomial commitments',
      'Linear-size proofs that require no trusted setup',
      'Proofs that are only secure against classical (non-quantum) adversaries',
      'Zero-knowledge only for specific algebraic statements, not general computation',
    ],
    correctIndex: 0,
    explanation: 'zk-SNARKs (Succinct Non-interactive Arguments of Knowledge) compress arbitrarily long computations into ~200 byte proofs verifiable in ~10ms. They use QAP reductions, elliptic curve pairings, and knowledge assumptions.',
    realWorld: 'Ethereum layer-2 rollups (zkSync, StarkNet) use zk-SNARKs to batch thousands of transactions into a single proof, dramatically reducing blockchain costs while preserving privacy.',
    hint: 'SNARK = Succinct Non-interactive ARgument of Knowledge — the proof is tiny no matter how big the computation.',
  },
];
