import type { Question } from '../types';

export const shiingShenChernQuestions: Question[] = [
  {
    id: 411801,
    topic: 'shiing-shen-chern',
    difficulty: 'easy',
    question: 'Shiing-Shen Chern is most famous for developing Chern classes. What do they classify?',
    options: [
      'Topological invariants of complex vector bundles that obstruct triviality',
      'The number of holes in a topological space',
      'The curvature of Riemannian manifolds at each point',
      'The symmetry groups of crystallographic structures',
    ],
    correctIndex: 0,
    explanation: 'Chern classes are cohomological invariants of complex vector bundles. The first Chern class c₁ determines line bundles; higher classes detect more subtle topology. They bridge differential geometry and algebraic topology.',
    realWorld: 'Chern classes appear in condensed matter physics: the quantum Hall effect has quantized conductance equal to a Chern number, explaining why certain physical quantities are precisely integer-valued.',
    hint: 'They answer: "How twisted is this vector bundle?" — 0 means trivial, nonzero means topologically nontrivial.',
  },
  {
    id: 411802,
    topic: 'shiing-shen-chern',
    difficulty: 'easy',
    question: 'The Chern–Gauss–Bonnet theorem generalizes the classical Gauss–Bonnet theorem by relating:',
    options: [
      'The integral of a curvature polynomial (Pfaffian) over a manifold to its Euler characteristic',
      'The volume of a manifold to its number of holes',
      'The surface area to the geodesic curvature',
      'The Ricci curvature to the fundamental group',
    ],
    correctIndex: 0,
    explanation: 'For a 2n-dimensional Riemannian manifold, ∫ Pf(Ω) = (2π)^n χ(M), where Pf is the Pfaffian of the curvature form and χ is the Euler characteristic. This unifies geometry (curvature) and topology (Euler number).',
    realWorld: 'This theorem is fundamental in topological materials science — it explains why certain material properties (like Hall conductance) are quantized and robust against perturbations.',
    hint: 'In 2D, it\'s ∫K dA = 2πχ. Chern proved the higher-dimensional version.',
  },
  {
    id: 411803,
    topic: 'shiing-shen-chern',
    difficulty: 'hard',
    question: 'Chern–Simons theory, co-developed with James Simons, defines a secondary characteristic class that:',
    options: [
      'Lives on odd-dimensional manifolds and whose variation gives the curvature invariant — used as a topological action in physics',
      'Classifies all even-dimensional manifolds up to cobordism',
      'Computes the signature of 4-manifolds',
      'Measures the volume of geodesic balls',
    ],
    correctIndex: 0,
    explanation: 'The Chern–Simons 3-form CS(A) = tr(A∧dA + ⅔A∧A∧A) is a secondary invariant whose exterior derivative gives a Chern class. As a Lagrangian in 3D, it defines a topological quantum field theory.',
    realWorld: 'Chern–Simons theory describes the fractional quantum Hall effect, topological quantum computing proposals, and knot invariants (Jones polynomial via Witten\'s path integral).',
    hint: 'Jim Simons (the billionaire hedge fund manager) was Chern\'s PhD student who co-authored this foundational work.',
  },
  {
    id: 411804,
    topic: 'shiing-shen-chern',
    difficulty: 'hard',
    question: 'In the classification of fiber bundles, Chern\'s work showed that complex vector bundles over a space $X$ are classified by:',
    options: [
      'Homotopy classes of maps from X to the classifying space BU(n), with Chern classes as the pullback of universal classes',
      'The fundamental group π₁(X) and its representations',
      'The de Rham cohomology of X with integer coefficients',
      'The K-theory group K(X) alone without reference to classifying spaces',
    ],
    correctIndex: 0,
    explanation: 'A rank-n complex vector bundle over X corresponds to a map X → BU(n). Chern classes are pullbacks of the universal classes in H*(BU(n)). This is the foundation of characteristic class theory.',
    realWorld: 'Classifying spaces and characteristic classes are used in gauge theory (Yang–Mills), string theory (anomaly cancellation via Chern classes), and topological data analysis.',
    hint: 'BU(n) is the Grassmannian in the limit — it classifies all possible n-plane sub-bundles.',
  },
  {
    id: 411805,
    topic: 'shiing-shen-chern',
    difficulty: 'sota',
    question: 'The Chern number in condensed matter physics quantizes the Hall conductance because:',
    options: [
      'The first Chern class of the Berry connection over the Brillouin zone is an integer topological invariant, making σ_xy = (e²/h)·C₁ exactly quantized',
      'The electric field is always perpendicular to the magnetic field in quantum systems',
      'Landau levels have equal spacing determined by the cyclotron frequency',
      'The Fermi surface encloses an integer number of electrons',
    ],
    correctIndex: 0,
    explanation: 'The Berry connection on the Bloch bundle over the Brillouin zone (a torus T²) has Chern number C₁ ∈ ℤ. TKNN showed σ_xy = (e²/h)C₁ — the quantum Hall conductance is a topological invariant, immune to disorder and impurities.',
    realWorld: 'Topological insulators, discovered using Chern number classification, are being developed for fault-tolerant quantum computing and spintronics devices.',
    hint: 'TKNN (1982) connected Berry phase geometry to the integer quantum Hall effect via Chern\'s mathematics.',
  },
];
