import type { Question } from '../types';

export const simonsQuestions: Question[] = [
  {
    id: 10081,
    topic: 'simons',
    difficulty: 'easy',
    question: 'A Hidden Markov Model (HMM) assumes:',
    options: [
      'An unobserved Markov chain generates observed emissions — the hidden state at time $t$ depends only on state at $t-1$',
      'All state variables are observed but transitions are random',
      'The observation sequence itself forms a Markov chain',
      'Hidden variables follow a Gaussian process over continuous time',
    ],
    correctIndex: 0,
    explanation: 'In an HMM, $P(z_t | z_{t-1}, ..., z_1) = P(z_t | z_{t-1})$ (Markov) and $P(x_t | z_1,...,z_t,x_1,...,x_{t-1}) = P(x_t | z_t)$ (emission). The Viterbi algorithm finds the most likely hidden state sequence.',
    realWorld: 'Renaissance Technologies used HMMs to model regime changes in financial markets — bull vs. bear market as hidden states with observable price returns.',
    hint: 'You see the symptoms (emissions) but not the disease (hidden states) — HMM infers the disease.',
  },
  {
    id: 10082,
    topic: 'simons',
    difficulty: 'easy',
    question: 'Stochastic calculus (Itô calculus) differs from ordinary calculus because:',
    options: [
      'Brownian motion has infinite variation, so the chain rule gains an extra term: $d(f(W)) = f\'(W)dW + \\frac{1}{2}f\'\'(W)dt$',
      'Derivatives are replaced by probability distributions at each time step',
      'Integration is performed over probability measures rather than Lebesgue measures',
      'Time steps must be discrete to maintain mathematical consistency',
    ],
    correctIndex: 0,
    explanation: 'Brownian motion $W_t$ has quadratic variation $[W]_t = t$ (unlike smooth functions where $[f]_t = 0$). This adds the $\\frac{1}{2}f\'\'(W)dt$ "Itô correction" — essential for pricing derivatives and modeling stochastic systems.',
    realWorld: 'Black-Scholes equation is derived using Itô\'s lemma on geometric Brownian motion — every option price on Wall Street uses this result.',
    hint: 'Randomness accumulates quadratically in time — the chain rule needs a correction term for that.',
  },
  {
    id: 10083,
    topic: 'simons',
    difficulty: 'easy',
    question: 'Arbitrage in finance means:',
    options: [
      'A risk-free profit opportunity from price discrepancies between markets — buying low and selling high simultaneously',
      'Leveraging borrowed capital to amplify investment returns',
      'Hedging a portfolio to reduce systematic market risk',
      'Taking opposite positions in correlated assets to reduce variance',
    ],
    correctIndex: 0,
    explanation: 'True arbitrage is simultaneously buying and selling the same or equivalent assets in different markets at different prices, locking in a guaranteed profit with no risk and no capital. Markets rapidly close arbitrage opportunities.',
    realWorld: 'Simons\' Medallion fund sought statistical arbitrage — not pure arbitrage, but exploiting small, persistent mispricings using pattern recognition and signal processing.',
    hint: 'Buy cheap here, sell expensive there, at the same time — guaranteed profit with zero risk.',
  },
  {
    id: 10084,
    topic: 'simons',
    difficulty: 'easy',
    question: 'A time series is said to be stationary if:',
    options: [
      'Its mean, variance, and autocovariance are invariant under time shifts',
      'It has no trend component in its additive decomposition',
      'Its autocorrelation function decays to zero monotonically',
      'It passes the Augmented Dickey-Fuller unit root test',
    ],
    correctIndex: 0,
    explanation: 'Weak (covariance) stationarity requires: $E[X_t] = \\mu$ (constant mean), $\\text{Var}(X_t) = \\sigma^2$ (constant variance), and $\\text{Cov}(X_t, X_{t+h})$ depends only on lag $h$, not $t$. Many financial models require stationarity for valid inference.',
    realWorld: 'Most raw financial price series are non-stationary (random walk). Returns (differences of log prices) are approximately stationary — a key preprocessing step.',
    hint: 'The statistical properties don\'t change over time — the series looks the same on Monday and on Friday.',
  },
  {
    id: 10085,
    topic: 'simons',
    difficulty: 'hard',
    question: 'The Viterbi algorithm for HMM decoding computes:',
    options: [
      'The most probable hidden state sequence $\\arg\\max_{z_{1:T}} P(z_{1:T} | x_{1:T})$ using dynamic programming in $O(TK^2)$ time',
      'The posterior marginals $P(z_t | x_{1:T})$ for each time step using forward-backward algorithm',
      'The maximum likelihood parameters $\\theta$ of the HMM via expectation-maximization',
      'The evidence $P(x_{1:T})$ by marginalizing over all hidden state sequences',
    ],
    correctIndex: 0,
    explanation: 'Viterbi tracks $\\delta_t(k) = \\max_{z_{1:t-1}} P(z_{1:t-1}, z_t=k, x_{1:t})$ via DP. Backtracking recovers the optimal path. Without DP, enumeration requires $O(K^T)$ — computationally infeasible for long sequences.',
    realWorld: 'Viterbi is used in speech recognition (phoneme sequence decoding), DNA sequencing (gene finding), and network packet decoding (convolutional codes).',
    hint: 'DP computes the best path to each state at each time, then traces back the optimal sequence.',
  },
  {
    id: 10086,
    topic: 'simons',
    difficulty: 'hard',
    question: 'The Sharpe ratio measures risk-adjusted return as $S = (R_p - R_f) / \\sigma_p$. A high Sharpe ratio indicates:',
    options: [
      'High excess return per unit of volatility — the strategy earns well relative to the risk taken',
      'Low drawdown relative to average return over the investment period',
      'The portfolio beats the market index on more than 50% of trading days',
      'Returns are normally distributed with minimal skewness',
    ],
    correctIndex: 0,
    explanation: 'Sharpe ratio = excess return / standard deviation. A Sharpe > 1 is good; > 2 is excellent; > 3 is exceptional. Renaissance\'s Medallion Fund reportedly achieved Sharpes > 5 — essentially impossible by random chance, implying genuine edge.',
    realWorld: 'The S&P 500 has a Sharpe of ~0.5. Medallion\'s reported Sharpe of 5+ (before fees) is among the highest sustained in financial history.',
    hint: 'How much return do you get for each unit of risk you take? Higher = better.',
  },
  {
    id: 10087,
    topic: 'simons',
    difficulty: 'hard',
    question: 'Pairs trading exploits mean reversion by:',
    options: [
      'Going long the underperforming asset and short the outperforming one when their spread deviates from the historical mean, expecting convergence',
      'Buying both assets in a correlated pair when market volatility is elevated',
      'Hedging one asset with options on its correlated pair to reduce directional exposure',
      'Arbitraging futures and spot prices of two correlated commodities simultaneously',
    ],
    correctIndex: 0,
    explanation: 'If assets $A$ and $B$ are cointegrated, the spread $S_t = A_t - \\beta B_t$ is stationary with mean $\\mu$. When $S_t > \\mu + k\\sigma$, sell $A$, buy $B$; when $S_t < \\mu - k\\sigma$, buy $A$, sell $B$. Profit from mean reversion.',
    realWorld: 'Simons\' team pioneered statistical arbitrage using cointegration. Modern quant funds trade thousands of such pairs simultaneously using ML to detect cointegrated relationships.',
    hint: 'When two correlated stocks temporarily diverge, bet on them converging — that\'s mean reversion.',
  },
  {
    id: 10088,
    topic: 'simons',
    difficulty: 'sota',
    question: 'Geometric Brownian Motion (GBM) $dS = \\mu S\\,dt + \\sigma S\\,dW$ has the solution:',
    options: [
      '$S_t = S_0 \\exp\\left((\\mu - \\frac{\\sigma^2}{2})t + \\sigma W_t\\right)$ — log-normal distribution at each time',
      '$S_t = S_0 + \\mu t + \\sigma W_t$ — normal distribution at each time',
      '$S_t = S_0 e^{\\mu t}$ — deterministic exponential growth',
      '$S_t = S_0 e^{\\sigma W_t}$ — pure multiplicative noise with zero drift',
    ],
    correctIndex: 0,
    explanation: 'Applying Itô\'s lemma to $f(S) = \\ln S$ gives $d(\\ln S) = (\\mu - \\sigma^2/2)dt + \\sigma dW$. The $-\\sigma^2/2$ term is the Itô correction. Integrating: $\\ln(S_t/S_0) \\sim \\mathcal{N}((\\mu-\\sigma^2/2)t, \\sigma^2 t)$ — log-normal prices.',
    realWorld: 'GBM is the foundation of the Black-Scholes model. The $\\sigma^2/2$ correction explains why expected log-return differs from expected return — critical for long-horizon investment analysis.',
    hint: 'Itô\'s lemma on $\\ln S$ generates the $-\\sigma^2/2$ correction that makes prices log-normal.',
  },
  {
    id: 10089,
    topic: 'simons',
    difficulty: 'sota',
    question: 'The Kalman filter for a linear-Gaussian state space model provides:',
    options: [
      'The exact posterior $P(z_t | x_{1:t})$ as a Gaussian, updated recursively via predict and update steps',
      'The maximum likelihood estimate of model parameters via the EM algorithm',
      'The optimal trading signal by filtering noise from financial time series',
      'The minimum variance linear predictor of future observations given past observations',
    ],
    correctIndex: 0,
    explanation: 'For linear dynamics and Gaussian noise, the Kalman filter computes the exact posterior mean $\\hat{z}_{t|t}$ and covariance $P_{t|t}$ via two steps: predict ($\\hat{z}_{t|t-1} = F\\hat{z}_{t-1|t-1}$) and update (incorporate new observation via Kalman gain $K_t$).',
    realWorld: 'Simons\' team used Kalman filtering to extract true market signals from noisy price data. GPS, autonomous vehicles, and robotics all rely on Kalman filters for state estimation.',
    hint: 'For linear + Gaussian systems, the posterior is always Gaussian — Kalman tracks its mean and variance exactly.',
  },
  {
    id: 10090,
    topic: 'simons',
    difficulty: 'sota',
    question: 'The Chern-Simons theory (named partly for Simons\' mathematical work on characteristic classes) computes topological invariants. The Chern-Simons 3-form $\\text{CS}(A) = \\text{tr}(A \\wedge dA + \\frac{2}{3} A \\wedge A \\wedge A)$ is significant because:',
    options: [
      'Its integral over a 3-manifold is a topological invariant of the gauge bundle, unchanged under smooth deformations of the gauge field',
      'It equals the Yang-Mills action density for self-dual gauge fields',
      'It generates the topological charge (winding number) of instanton solutions',
      'It provides the anomaly coefficient for chiral fermions in quantum field theory',
    ],
    correctIndex: 0,
    explanation: 'The Chern-Simons functional is gauge-invariant modulo integers, making $e^{2\\pi i \\int \\text{CS}(A)}$ a topological invariant. Witten (1988) used it to define 3-manifold and knot invariants, connecting topology to quantum field theory.',
    realWorld: 'Chern-Simons theory describes topological phases of matter (fractional quantum Hall effect, topological insulators) and is the basis for proposed topological quantum computers.',
    hint: 'The integral depends only on the topology of the bundle, not the specific gauge field — a pure topological quantity.',
  },
];

export const ramanujanQuestions: Question[] = [
  {
    id: 10091,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'Ramanujan\'s formula for $\\pi$ converges extremely rapidly. The Rogers-Ramanujan continued fraction satisfies:',
    options: [
      'Remarkable algebraic identities relating it to special values of modular functions and theta series',
      'A simple geometric series that converges to $\\pi$ in 10 terms',
      'A recurrence relation derived from the Euclidean algorithm',
      'A product formula for prime numbers via the zeta function',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan discovered continued fractions with extraordinary depth — connected to modular forms, elliptic functions, and theta series. His 1914 formula for $1/\\pi$ adds ~8 digits per term and shocked Western mathematicians.',
    realWorld: 'Ramanujan\'s formulas for $\\pi$ are used by computer scientists to compute $\\pi$ to trillions of digits — directly used in the Chudnovsky algorithm.',
    hint: 'His formulas came from deep connections between special functions, not elementary tricks.',
  },
  {
    id: 10092,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'The partition function $p(n)$ counts:',
    options: [
      'The number of ways to write $n$ as an unordered sum of positive integers',
      'The number of prime factorizations of $n$',
      'The number of permutations of $n$ elements with no fixed points',
      'The number of divisors of $n$ that are perfect squares',
    ],
    correctIndex: 0,
    explanation: '$p(4) = 5$: {4, 3+1, 2+2, 2+1+1, 1+1+1+1}. Ramanujan and Hardy proved the asymptotic formula $p(n) \\sim \\frac{1}{4n\\sqrt{3}} e^{\\pi\\sqrt{2n/3}}$ — a remarkable formula using the circle method.',
    realWorld: 'Partition functions appear in statistical mechanics (counting energy microstates), combinatorics, and string theory (counting string oscillation modes).',
    hint: 'How many ways can you make change for n cents using coins of any denomination?',
  },
  {
    id: 10093,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'The "taxicab number" 1729 is famous because Ramanujan noted:',
    options: [
      'It is the smallest number expressible as the sum of two cubes in two different ways: $1^3 + 12^3 = 9^3 + 10^3 = 1729$',
      'It is the product of the first four prime numbers',
      'It equals $\\pi^3 \\cdot e^2$ to four significant figures',
      'It is the smallest number whose digit sum equals its number of prime factors',
    ],
    correctIndex: 0,
    explanation: 'Hardy arrived in a taxi numbered 1729 to visit the ill Ramanujan, who immediately observed this property. Hardy-Ramanujan numbers (taxicab numbers) are now a rich area of number theory.',
    realWorld: 'This anecdote illustrates Ramanujan\'s extraordinary ability to recognize deep arithmetic structure in seemingly arbitrary numbers — a form of mathematical intuition unmatched in history.',
    hint: '$1^3 + 12^3 = 1 + 1728 = 1729$ and $9^3 + 10^3 = 729 + 1000 = 1729$.',
  },
  {
    id: 10094,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'Modular forms are complex functions satisfying $f\\left(\\frac{az+b}{cz+d}\\right) = (cz+d)^k f(z)$ for $\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix} \\in SL_2(\\mathbb{Z})$. Ramanujan\'s $\\tau$ function appears in:',
    options: [
      'The Fourier coefficients of $\\Delta(z) = q\\prod_{n=1}^\\infty(1-q^n)^{24}$, the unique weight-12 cusp form',
      'The error term of the prime number theorem',
      'The asymptotic expansion of the Riemann zeta function near $s=1$',
      'The generating function for the number of ways to represent $n$ as a sum of four squares',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan\'s tau function $\\tau(n)$ (coefficients of $\\Delta$) led to his conjecture $|\\tau(p)| \\leq 2p^{11/2}$ for primes $p$, proved by Deligne (1974) as a consequence of the Weil conjectures — one of the 20th century\'s deepest theorems.',
    realWorld: 'Modular forms are central to the proof of Fermat\'s Last Theorem (Wiles 1995) — every elliptic curve is modular, proved via Ramanujan-type analysis.',
    hint: '$\\Delta$ is the discriminant modular form — its coefficients are Ramanujan\'s mysterious $\\tau(n)$.',
  },
  {
    id: 10095,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'Ramanujan\'s master theorem states: $\\int_0^\\infty x^{s-1}\\sum_{k=0}^\\infty \\frac{(-1)^k \\phi(k)}{k!} x^k\\,dx = \\frac{\\pi}{\\sin(\\pi s)}\\phi(-s)$. This is remarkable because:',
    options: [
      'It analytically continues $\\phi$ from non-negative integer values to complex $s$, connecting Mellin transforms to interpolation',
      'It proves that all Mellin transforms of entire functions are meromorphic',
      'It gives a closed form for the Euler-Mascheroni constant in terms of $\\phi$',
      'It shows that the Gamma function can be expressed as an infinite product over zeros of $\\phi$',
    ],
    correctIndex: 0,
    explanation: 'The theorem extracts global information (the Mellin transform) from only the integer values $\\phi(0), \\phi(1), \\phi(2), ...$. This type of analytic continuation — reading a function from discrete samples — reflects Ramanujan\'s deep intuition about special functions.',
    realWorld: 'The master theorem has applications in computing Feynman integrals in particle physics and in the analysis of algorithms\' average-case complexity.',
    hint: 'Discrete integer values of $\\phi$ determine the Mellin transform for all complex $s$ — a miraculous bridge.',
  },
  {
    id: 10096,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'The Hardy-Ramanujan asymptotic formula for $p(n)$ uses the circle method, which works by:',
    options: [
      'Integrating the generating function $\\sum_{n=0}^\\infty p(n) q^n = \\prod_{k=1}^\\infty (1-q^k)^{-1}$ around a contour near $|q|=1$ using Farey sequences to handle singularities',
      'Applying the saddle-point method to the exponential generating function of partitions',
      'Using Euler\'s pentagonal theorem to derive a recurrence for $p(n)$',
      'Expressing $p(n)$ as a sum over prime partitions using the inclusion-exclusion principle',
    ],
    correctIndex: 0,
    explanation: 'The generating function has essential singularities at roots of unity. The circle method (Hardy-Ramanujan, refined by Rademacher to an exact formula) partitions the circle of integration using Farey arcs, approximating the contribution of each major arc to get the asymptotic expansion.',
    realWorld: 'The circle method became one of the most powerful tools in analytic number theory — later used to prove Vinogradov\'s theorem (every large odd number is a sum of three primes).',
    hint: 'The generating function has singularities everywhere on $|q|=1$ — the circle method systematically handles each one.',
  },
  {
    id: 10097,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'Mock theta functions (Ramanujan, 1920) were finally understood through:',
    options: [
      'Zweger\'s 2002 thesis showing they are holomorphic parts of harmonic Maass forms — non-holomorphic modular-like objects',
      'Proving they satisfy the same functional equations as classical theta functions',
      'Showing they generate the same partition statistics as Rogers-Ramanujan identities',
      'Connecting them to the L-functions of elliptic curves over finite fields',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan\'s 1920 deathbed letter described mock theta functions that "nearly" behave like modular forms. Zweger (2002) completed the theory: they are holomorphic parts of harmonic Maass forms, and the "error" from modularity is an Eichler integral — resolving an 80-year mystery.',
    realWorld: 'Mock theta functions appear in string theory (D-brane partition functions), black hole entropy calculations, and the study of Moonshine phenomena.',
    hint: 'Not quite modular, but with a precise correction term — Ramanujan knew they were special but couldn\'t complete the theory.',
  },
  {
    id: 10098,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'The Rogers-Ramanujan identities state: $\\sum_{n=0}^\\infty \\frac{q^{n^2}}{(q;q)_n} = \\prod_{n=1}^\\infty \\frac{1}{(1-q^{5n-1})(1-q^{5n-4})}$. Their significance for physics is:',
    options: [
      'They equal the partition function of the 2D Ising model at criticality — connecting pure number theory to statistical mechanics',
      'They enumerate Feynman diagrams with a fixed number of external legs',
      'They give the character of the free boson conformal field theory',
      'They compute the dimensions of representations of the symmetric group',
    ],
    correctIndex: 0,
    explanation: 'The Rogers-Ramanujan identities count partitions with specific gap conditions and appear as characters in conformal field theory (the $(2,5)$ minimal model). This deep connection between number theory and physics was discovered decades after Ramanujan.',
    realWorld: 'The appearance of Ramanujan\'s century-old identities in 2D critical phenomena is one of the most surprising connections between pure mathematics and physics.',
    hint: 'Partitions with gaps = products over primes ≡ ±1 (mod 5) — and this equals a physics partition function.',
  },
  {
    id: 10099,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'The Ramanujan conjecture for the modular discriminant $\\Delta$ states $|\\tau(p)| \\leq 2p^{11/2}$ for primes $p$. Deligne proved this via:',
    options: [
      'The Weil conjectures — proving the Riemann hypothesis for varieties over finite fields, which bounds eigenvalues of Frobenius on étale cohomology',
      'The Langlands correspondence connecting automorphic forms to Galois representations',
      'The modularity theorem showing all elliptic curves over $\\mathbb{Q}$ are modular',
      'The Petersson trace formula bounding Fourier coefficients of cusp forms',
    ],
    correctIndex: 0,
    explanation: 'Deligne (1974, Fields Medal) reduced Ramanujan\'s conjecture to the Weil conjectures via Grothendieck\'s étale cohomology. The pure Weil conjecture gives eigenvalue bounds $|\\alpha| = p^{(k-1)/2}$ for weight-$k$ forms, yielding Ramanujan\'s bound.',
    realWorld: 'This proof unified algebraic geometry (étale cohomology), number theory (modular forms), and representation theory — exemplifying Langlands program\'s grand unification.',
    hint: 'Bound eigenvalues of Frobenius on cohomology of a variety over $\\mathbb{F}_p$ → bound Fourier coefficients.',
  },
  {
    id: 10100,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'Monstrous Moonshine (Conway-Norton 1979) connects Ramanujan\'s modular forms to the Monster group by:',
    options: [
      'The McKay observation that the $j$-function coefficients (196884, 21493760, ...) equal sums of dimensions of Monster group representations',
      'Showing the Monster group acts on the space of modular forms of all weights simultaneously',
      'Proving the Monster group\'s order equals a special value of Ramanujan\'s tau function',
      'Constructing explicit modular forms from the Monster\'s character table entries',
    ],
    correctIndex: 0,
    explanation: '$j(\\tau) = q^{-1} + 744 + 196884q + ...$. McKay noticed $196884 = 196883 + 1$ where 196883 is the smallest non-trivial Monster representation dimension. Borcherds (1992, Fields Medal) proved Moonshine using vertex operator algebras — connecting the largest sporadic simple group to modular forms.',
    realWorld: 'Moonshine has connections to string theory (the Monster appears in 24+1 dimensional string compactifications) and inspired the discovery of Mathieu Moonshine and Umbral Moonshine.',
    hint: '$j$-function coefficient = sum of Monster representation dimensions. A stunning coincidence that turned out to be deep mathematics.',
  },
];
