import type { Question } from '../types';

export const kovalevskayaQuestions: Question[] = [
  {
    id: 12401,
    topic: 'kovalevskaya',
    difficulty: 'easy',
    question: 'Sofia Kovalevskaya was the first woman in modern Europe to:',
    options: [
      'Earn a doctorate in mathematics and later hold a university chair in mathematics',
      'Publish a paper in a peer-reviewed scientific journal',
      'Win a Nobel Prize in a scientific field',
      'Be elected to a national academy of sciences',
    ],
    correctIndex: 0,
    explanation: 'Kovalevskaya earned her doctorate from the University of Göttingen in 1874 (under Weierstrass) and became the first female professor of mathematics in Northern Europe at Stockholm University in 1889.',
    realWorld: 'Her persistence in overcoming institutional barriers paved the way for women in STEM. Universities that barred women had to reckon with her mathematical brilliance.',
    hint: 'She had to find a university that would even allow her to study — most wouldn\'t admit women.',
  },
  {
    id: 12402,
    topic: 'kovalevskaya',
    difficulty: 'easy',
    question: 'Kovalevskaya won the Prix Bordin (1888) for solving the rotation of a rigid body in which special case?',
    options: [
      'The Kovalevskaya top — a third integrable case of rigid body rotation with specific inertia ratios',
      'A perfectly symmetric sphere rotating in a gravitational field',
      'A gyroscope in zero gravity with no external torques',
      'A pendulum swinging in a viscous fluid',
    ],
    correctIndex: 0,
    explanation: 'After Euler (symmetric body, no gravity) and Lagrange (symmetric body with gravity), Kovalevskaya discovered the third integrable case with moments of inertia (2:2:1) and center of mass in the equatorial plane. Her solution used hyperelliptic functions.',
    realWorld: 'Rigid body dynamics is essential in satellite attitude control, robotics, and spacecraft stabilization. The Kovalevskaya case provides exact solutions for benchmark testing.',
    hint: 'Only three integrable cases of rigid body rotation are known — she found the last one.',
  },
  {
    id: 12403,
    topic: 'kovalevskaya',
    difficulty: 'hard',
    question: 'The Cauchy–Kovalevskaya theorem guarantees that for analytic PDEs with analytic initial data:',
    options: [
      'A unique local analytic solution exists — the fundamental existence theorem for analytic PDEs',
      'Global solutions exist for all time',
      'Solutions are always smooth (C^∞) but not necessarily analytic',
      'Solutions exist only for elliptic equations, not hyperbolic ones',
    ],
    correctIndex: 0,
    explanation: 'The Cauchy–Kovalevskaya theorem (1875) states that if the PDE and initial data are analytic and the PDE is non-characteristic with respect to the initial surface, then a unique local analytic solution exists. It\'s proved using majorant methods.',
    realWorld: 'This theorem is the starting point for PDE theory. While most physical PDEs need weaker existence theories (Sobolev spaces), Cauchy–Kovalevskaya provides the foundation and intuition.',
    hint: 'Analytic input → analytic output, at least locally. She proved this as part of her doctoral work.',
  },
  {
    id: 12404,
    topic: 'kovalevskaya',
    difficulty: 'hard',
    question: 'Kovalevskaya\'s method for finding the third integrable case of rigid body rotation used:',
    options: [
      'Painlevé analysis — requiring that solutions have no movable branch points in the complex plane',
      'Numerical integration of Hamilton\'s equations',
      'Group theory and Lie symmetries of the equations of motion',
      'Perturbation theory around the Euler top solution',
    ],
    correctIndex: 0,
    explanation: 'She systematically analyzed when the Euler equations for rotation have solutions without movable branch points (singularities that depend on initial conditions). This "Painlevé property" singled out exactly three integrable cases.',
    realWorld: 'The Painlevé property is now a standard test for integrability in mathematical physics, used to identify exactly solvable models in fluid dynamics, nonlinear optics, and soliton theory.',
    hint: 'She looked at the singularity structure of solutions in the complex plane — integrability requires "nice" singularities.',
  },
  {
    id: 12405,
    topic: 'kovalevskaya',
    difficulty: 'sota',
    question: 'The Kovalevskaya top has been shown to be algebraically completely integrable, meaning:',
    options: [
      'Its complexified phase space fibers over an abelian variety (a 2D complex torus), and the flow is linear on this torus',
      'It can be solved by elementary functions without any special functions',
      'The equations of motion reduce to a single ODE of order 2',
      'The Lyapunov exponents are all zero for every initial condition',
    ],
    correctIndex: 0,
    explanation: 'The Kovalevskaya top\'s complexified invariant manifolds are genus-2 abelian varieties. The flow linearizes on these tori, and solutions are expressed via genus-2 theta functions. This algebraic-geometric structure is the deepest form of integrability.',
    realWorld: 'Algebraic complete integrability connects classical mechanics to modern algebraic geometry and has applications in string theory (integrable systems on moduli spaces) and mathematical physics.',
    hint: 'The flow lives on a complex torus (abelian variety) and moves in straight lines — the most structured form of integrability.',
  },
];
