import type { Question } from '../types';

export const ramanujanQuestions: Question[] = [
  {
    id: 10091,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'Ramanujan\'s formula for $\\pi$ converges extremely rapidly. The Rogers-Ramanujan continued fraction satisfies:',
    options: [
      'Remarkable algebraic identities relating it to special values of modular functions and theta series',
      'A simple geometric series that converges to $\\pi$ in 10 terms',
      'A recurrence relation derived from the Euclidean algorithm',
      'A product formula for prime numbers via the zeta function',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan discovered continued fractions with extraordinary depth — connected to modular forms, elliptic functions, and theta series. His 1914 formula for $1/\\pi$ adds ~8 digits per term and shocked Western mathematicians.',
    realWorld: 'Ramanujan\'s formulas for $\\pi$ are used by computer scientists to compute $\\pi$ to trillions of digits — directly used in the Chudnovsky algorithm.',
    hint: 'His formulas came from deep connections between special functions, not elementary tricks.',
  },
  {
    id: 10092,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'The partition function $p(n)$ counts:',
    options: [
      'The number of ways to write $n$ as an unordered sum of positive integers',
      'The number of prime factorizations of $n$',
      'The number of permutations of $n$ elements with no fixed points',
      'The number of divisors of $n$ that are perfect squares',
    ],
    correctIndex: 0,
    explanation: '$p(4) = 5$: {4, 3+1, 2+2, 2+1+1, 1+1+1+1}. Ramanujan and Hardy proved the asymptotic formula $p(n) \\sim \\frac{1}{4n\\sqrt{3}} e^{\\pi\\sqrt{2n/3}}$ — a remarkable formula using the circle method.',
    realWorld: 'Partition functions appear in statistical mechanics (counting energy microstates), combinatorics, and string theory (counting string oscillation modes).',
    hint: 'How many ways can you make change for n cents using coins of any denomination?',
  },
  {
    id: 10093,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'The "taxicab number" 1729 is famous because Ramanujan noted:',
    options: [
      'It is the smallest number expressible as the sum of two cubes in two different ways: $1^3 + 12^3 = 9^3 + 10^3 = 1729$',
      'It is the product of the first four prime numbers',
      'It equals $\\pi^3 \\cdot e^2$ to four significant figures',
      'It is the smallest number whose digit sum equals its number of prime factors',
    ],
    correctIndex: 0,
    explanation: 'Hardy arrived in a taxi numbered 1729 to visit the ill Ramanujan, who immediately observed this property. Hardy-Ramanujan numbers (taxicab numbers) are now a rich area of number theory.',
    realWorld: 'This anecdote illustrates Ramanujan\'s extraordinary ability to recognize deep arithmetic structure in seemingly arbitrary numbers — a form of mathematical intuition unmatched in history.',
    hint: '$1^3 + 12^3 = 1 + 1728 = 1729$ and $9^3 + 10^3 = 729 + 1000 = 1729$.',
  },
  {
    id: 10094,
    topic: 'ramanujan',
    difficulty: 'easy',
    question: 'Modular forms are complex functions satisfying $f\\left(\\frac{az+b}{cz+d}\\right) = (cz+d)^k f(z)$ for $\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix} \\in SL_2(\\mathbb{Z})$. Ramanujan\'s $\\tau$ function appears in:',
    options: [
      'The Fourier coefficients of $\\Delta(z) = q\\prod_{n=1}^\\infty(1-q^n)^{24}$, the unique weight-12 cusp form',
      'The error term of the prime number theorem',
      'The asymptotic expansion of the Riemann zeta function near $s=1$',
      'The generating function for the number of ways to represent $n$ as a sum of four squares',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan\'s tau function $\\tau(n)$ (coefficients of $\\Delta$) led to his conjecture $|\\tau(p)| \\leq 2p^{11/2}$ for primes $p$, proved by Deligne (1974) as a consequence of the Weil conjectures — one of the 20th century\'s deepest theorems.',
    realWorld: 'Modular forms are central to the proof of Fermat\'s Last Theorem (Wiles 1995) — every elliptic curve is modular, proved via Ramanujan-type analysis.',
    hint: '$\\Delta$ is the discriminant modular form — its coefficients are Ramanujan\'s mysterious $\\tau(n)$.',
  },
  {
    id: 10095,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'Ramanujan\'s master theorem states: $\\int_0^\\infty x^{s-1}\\sum_{k=0}^\\infty \\frac{(-1)^k \\phi(k)}{k!} x^k\\,dx = \\frac{\\pi}{\\sin(\\pi s)}\\phi(-s)$. This is remarkable because:',
    options: [
      'It analytically continues $\\phi$ from non-negative integer values to complex $s$, connecting Mellin transforms to interpolation',
      'It proves that all Mellin transforms of entire functions are meromorphic',
      'It gives a closed form for the Euler-Mascheroni constant in terms of $\\phi$',
      'It shows that the Gamma function can be expressed as an infinite product over zeros of $\\phi$',
    ],
    correctIndex: 0,
    explanation: 'The theorem extracts global information (the Mellin transform) from only the integer values $\\phi(0), \\phi(1), \\phi(2), ...$. This type of analytic continuation — reading a function from discrete samples — reflects Ramanujan\'s deep intuition about special functions.',
    realWorld: 'The master theorem has applications in computing Feynman integrals in particle physics and in the analysis of algorithms\' average-case complexity.',
    hint: 'Discrete integer values of $\\phi$ determine the Mellin transform for all complex $s$ — a miraculous bridge.',
  },
  {
    id: 10096,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'The Hardy-Ramanujan asymptotic formula for $p(n)$ uses the circle method, which works by:',
    options: [
      'Integrating the generating function $\\sum_{n=0}^\\infty p(n) q^n = \\prod_{k=1}^\\infty (1-q^k)^{-1}$ around a contour near $|q|=1$ using Farey sequences to handle singularities',
      'Applying the saddle-point method to the exponential generating function of partitions',
      'Using Euler\'s pentagonal theorem to derive a recurrence for $p(n)$',
      'Expressing $p(n)$ as a sum over prime partitions using the inclusion-exclusion principle',
    ],
    correctIndex: 0,
    explanation: 'The generating function has essential singularities at roots of unity. The circle method (Hardy-Ramanujan, refined by Rademacher to an exact formula) partitions the circle of integration using Farey arcs, approximating the contribution of each major arc to get the asymptotic expansion.',
    realWorld: 'The circle method became one of the most powerful tools in analytic number theory — later used to prove Vinogradov\'s theorem (every large odd number is a sum of three primes).',
    hint: 'The generating function has singularities everywhere on $|q|=1$ — the circle method systematically handles each one.',
  },
  {
    id: 10097,
    topic: 'ramanujan',
    difficulty: 'hard',
    question: 'Mock theta functions (Ramanujan, 1920) were finally understood through:',
    options: [
      'Zweger\'s 2002 thesis showing they are holomorphic parts of harmonic Maass forms — non-holomorphic modular-like objects',
      'Proving they satisfy the same functional equations as classical theta functions',
      'Showing they generate the same partition statistics as Rogers-Ramanujan identities',
      'Connecting them to the L-functions of elliptic curves over finite fields',
    ],
    correctIndex: 0,
    explanation: 'Ramanujan\'s 1920 deathbed letter described mock theta functions that "nearly" behave like modular forms. Zweger (2002) completed the theory: they are holomorphic parts of harmonic Maass forms, and the "error" from modularity is an Eichler integral — resolving an 80-year mystery.',
    realWorld: 'Mock theta functions appear in string theory (D-brane partition functions), black hole entropy calculations, and the study of Moonshine phenomena.',
    hint: 'Not quite modular, but with a precise correction term — Ramanujan knew they were special but couldn\'t complete the theory.',
  },
  {
    id: 10098,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'The Rogers-Ramanujan identities state: $\\sum_{n=0}^\\infty \\frac{q^{n^2}}{(q;q)_n} = \\prod_{n=1}^\\infty \\frac{1}{(1-q^{5n-1})(1-q^{5n-4})}$. Their significance for physics is:',
    options: [
      'They equal the partition function of the 2D Ising model at criticality — connecting pure number theory to statistical mechanics',
      'They enumerate Feynman diagrams with a fixed number of external legs',
      'They give the character of the free boson conformal field theory',
      'They compute the dimensions of representations of the symmetric group',
    ],
    correctIndex: 0,
    explanation: 'The Rogers-Ramanujan identities count partitions with specific gap conditions and appear as characters in conformal field theory (the $(2,5)$ minimal model). This deep connection between number theory and physics was discovered decades after Ramanujan.',
    realWorld: 'The appearance of Ramanujan\'s century-old identities in 2D critical phenomena is one of the most surprising connections between pure mathematics and physics.',
    hint: 'Partitions with gaps = products over primes ≡ ±1 (mod 5) — and this equals a physics partition function.',
  },
  {
    id: 10099,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'The Ramanujan conjecture for the modular discriminant $\\Delta$ states $|\\tau(p)| \\leq 2p^{11/2}$ for primes $p$. Deligne proved this via:',
    options: [
      'The Weil conjectures — proving the Riemann hypothesis for varieties over finite fields, which bounds eigenvalues of Frobenius on étale cohomology',
      'The Langlands correspondence connecting automorphic forms to Galois representations',
      'The modularity theorem showing all elliptic curves over $\\mathbb{Q}$ are modular',
      'The Petersson trace formula bounding Fourier coefficients of cusp forms',
    ],
    correctIndex: 0,
    explanation: 'Deligne (1974, Fields Medal) reduced Ramanujan\'s conjecture to the Weil conjectures via Grothendieck\'s étale cohomology. The pure Weil conjecture gives eigenvalue bounds $|\\alpha| = p^{(k-1)/2}$ for weight-$k$ forms, yielding Ramanujan\'s bound.',
    realWorld: 'This proof unified algebraic geometry (étale cohomology), number theory (modular forms), and representation theory — exemplifying Langlands program\'s grand unification.',
    hint: 'Bound eigenvalues of Frobenius on cohomology of a variety over $\\mathbb{F}_p$ → bound Fourier coefficients.',
  },
  {
    id: 10100,
    topic: 'ramanujan',
    difficulty: 'sota',
    question: 'Monstrous Moonshine (Conway-Norton 1979) connects Ramanujan\'s modular forms to the Monster group by:',
    options: [
      'The McKay observation that the $j$-function coefficients (196884, 21493760, ...) equal sums of dimensions of Monster group representations',
      'Showing the Monster group acts on the space of modular forms of all weights simultaneously',
      'Proving the Monster group\'s order equals a special value of Ramanujan\'s tau function',
      'Constructing explicit modular forms from the Monster\'s character table entries',
    ],
    correctIndex: 0,
    explanation: '$j(\\tau) = q^{-1} + 744 + 196884q + ...$. McKay noticed $196884 = 196883 + 1$ where 196883 is the smallest non-trivial Monster representation dimension. Borcherds (1992, Fields Medal) proved Moonshine using vertex operator algebras — connecting the largest sporadic simple group to modular forms.',
    realWorld: 'Moonshine has connections to string theory (the Monster appears in 24+1 dimensional string compactifications) and inspired the discovery of Mathieu Moonshine and Umbral Moonshine.',
    hint: '$j$-function coefficient = sum of Monster representation dimensions. A stunning coincidence that turned out to be deep mathematics.',
  },
];
