import type { Question } from '../types';

export const stephenWolframQuestions: Question[] = [
  {
    id: 20480,
    topic: 'stephen-wolfram',
    difficulty: 'hard',
    question: 'Wolfram\'s "A New Kind of Science" argues that simple programs (cellular automata) can produce complex behavior. Which of his elementary cellular automata is Turing-complete?',
    options: ['Rule 110', 'Rule 30', 'Rule 90', 'Rule 184'],
    correctIndex: 0,
    explanation: 'Matthew Cook proved Rule 110 is Turing-complete in 2004 — a one-dimensional cellular automaton with just 2 states and 3 neighbors can compute anything.',
    realWorld: 'This shows that computational universality lurks in extremely simple systems — relevant to understanding emergence in biology and physics.',
    hint: 'This rule was proven capable of universal computation by one of Wolfram\'s researchers.',
  },
  {
    id: 20481,
    topic: 'stephen-wolfram',
    difficulty: 'hard',
    question: 'Wolfram classified elementary cellular automata into four behavioral classes. Class IV automata exhibit which behavior?',
    options: ['Complex patterns at the edge of chaos (neither periodic nor fully chaotic)', 'Fixed points only', 'Simple periodic oscillations', 'Complete randomness'],
    correctIndex: 0,
    explanation: 'Class IV automata sit at the "edge of chaos" — producing complex, structured but non-periodic patterns. Rule 110 is the canonical example.',
    realWorld: 'The "edge of chaos" concept influences theories of self-organized criticality in everything from neural networks to ecosystems.',
    hint: 'It\'s the class that\'s interesting precisely because it\'s between order and chaos.',
  },
  {
    id: 20482,
    topic: 'stephen-wolfram',
    difficulty: 'sota',
    question: 'Wolfram\'s "Wolfram Physics Project" (2020) proposes that spacetime emerges from hypergraph rewriting. What is the key structure in this model?',
    options: ['A multiway system of hypergraph transformations', 'A lattice of spin networks', 'A conformal field theory on the boundary', 'A tensor network in AdS space'],
    correctIndex: 0,
    explanation: 'The model applies simple rewriting rules to hypergraphs; different branches of the multiway system correspond to quantum superpositions, and spacetime curvature emerges from graph geometry.',
    realWorld: 'While still speculative, the project has generated new computational tools and attracted interest from digital physics researchers.',
    hint: 'Think of a graph where the vertices and edges themselves are transformed by simple rules.',
  },
  {
    id: 20483,
    topic: 'stephen-wolfram',
    difficulty: 'sota',
    question: 'Wolfram created Mathematica in 1988. Its core evaluation model is based on which computational paradigm?',
    options: ['Term rewriting (pattern matching on symbolic expressions)', 'Object-oriented programming', 'Lambda calculus with lazy evaluation', 'Stack-based concatenative programming'],
    correctIndex: 0,
    explanation: 'Mathematica uses term rewriting: expressions are trees of symbols, and transformation rules are applied until no more rules match — a powerful generalization of functional programming.',
    realWorld: 'Wolfram Language powers Wolfram Alpha, which processes millions of natural-language computational queries daily.',
    hint: 'The system works by matching patterns in symbolic expressions and replacing them.',
  },
  {
    id: 20484,
    topic: 'stephen-wolfram',
    difficulty: 'easy',
    question: 'What computational knowledge engine did Stephen Wolfram create that can answer factual questions?',
    options: ['Wolfram Alpha', 'Mathematica', 'ChatGPT', 'Google Scholar'],
    correctIndex: 0,
    explanation: 'Wolfram Alpha, launched in 2009, computes answers from structured data rather than searching web pages.',
    realWorld: 'Siri originally used Wolfram Alpha to answer mathematical and factual queries.',
    hint: 'It\'s a "computational knowledge engine" that computes answers rather than searching.',
  },
];
