import type { Question } from '../types';

export const talebQuestions: Question[] = [
  {
    id: 21060,
    topic: 'taleb',
    difficulty: 'sota',
    question: 'Taleb\'s "Black Swan" theory critiques which family of probability distributions as dangerously misapplied to financial markets?',
    options: ['Gaussian (thin-tailed) distributions', 'Power-law (fat-tailed) distributions', 'Poisson distributions', 'Exponential distributions'],
    correctIndex: 0,
    explanation: 'Taleb argues that financial markets follow fat-tailed distributions where extreme events are far more common than Gaussian models predict, making standard risk metrics like VaR dangerously misleading.',
    realWorld: 'The 2008 financial crisis was a textbook "Black Swan" — models based on Gaussian assumptions catastrophically underestimated tail risk.',
    hint: 'The bell curve dramatically underestimates the probability of extreme events.',
  },
  {
    id: 21061,
    topic: 'taleb',
    difficulty: 'sota',
    question: 'In Taleb\'s framework, what is "antifragility"?',
    options: ['A property of systems that gain from disorder and volatility', 'The ability to withstand shocks without breaking', 'The tendency to return to equilibrium after perturbation', 'Immunity to Black Swan events'],
    correctIndex: 0,
    explanation: 'Antifragility goes beyond resilience (surviving shocks) or robustness (being unchanged by shocks) — antifragile systems actually improve and strengthen when exposed to stressors, volatility, and randomness.',
    realWorld: 'Biological evolution, barbell investment strategies, and decentralized systems all exhibit antifragility.',
    hint: 'It is the opposite of fragile — not merely "robust" but something that benefits from chaos.',
  },
  {
    id: 21062,
    topic: 'taleb',
    difficulty: 'sota',
    question: 'Taleb\'s "barbell strategy" in portfolio construction involves combining which two extremes?',
    options: ['Ultra-safe assets and highly speculative bets, with nothing in between', 'Large-cap and small-cap equities equally weighted', 'Long and short positions on the same asset', 'Government bonds and corporate bonds in equal measure'],
    correctIndex: 0,
    explanation: 'The barbell strategy puts 85-90% of capital in extremely safe instruments (e.g., T-bills) and 10-15% in highly speculative, asymmetric bets with unlimited upside, avoiding the "medium risk" middle.',
    realWorld: 'Taleb personally profited from this strategy during the 1987 Black Monday crash and the 2008 crisis.',
    hint: 'Like a physical barbell — all the weight is at the two ends, nothing in the middle.',
  },
  {
    id: 21063,
    topic: 'taleb',
    difficulty: 'sota',
    question: 'Taleb\'s concept of "skin in the game" formalizes which principle about risk and decision-making?',
    options: ['Decision-makers must bear the consequences of their decisions', 'Markets are efficient because all information is priced in', 'Diversification eliminates all systematic risk', 'Experts always outperform random selection'],
    correctIndex: 0,
    explanation: 'Taleb argues that asymmetric risk transfer (where decision-makers benefit from upside but are insulated from downside) is the root cause of systemic fragility in finance, politics, and medicine.',
    realWorld: 'The 2008 crisis exemplified this: bankers earned bonuses on risky trades but taxpayers bore the losses.',
    hint: 'Those who make decisions should also face the downside consequences.',
  },
  {
    id: 21064,
    topic: 'taleb',
    difficulty: 'sota',
    question: 'Which mathematical concept does Taleb use to distinguish between "Mediocristan" and "Extremistan"?',
    options: ['The concentration of the probability distribution\'s tails (kurtosis)', 'The mean-variance trade-off', 'The central limit theorem convergence rate', 'The law of large numbers'],
    correctIndex: 0,
    explanation: '"Mediocristan" describes domains governed by thin-tailed distributions (e.g., height) where no single observation can dominate. "Extremistan" describes fat-tailed domains (e.g., wealth) where a single observation can dwarf all others.',
    realWorld: 'Book sales, city sizes, and financial returns all live in Extremistan, where averages are meaningless.',
    hint: 'In one world, the largest observation is bounded; in the other, it can be astronomical.',
  },
];
