import type { Question } from '../types';

export const taoQuestions: Question[] = [
  {
    id: 11401,
    topic: 'tao',
    difficulty: 'easy',
    question: 'Terence Tao, along with Ben Green, proved the Green–Tao theorem. What does it state?',
    options: [
      'The primes contain arbitrarily long arithmetic progressions',
      'Every even integer greater than 2 is the sum of two primes',
      'There are infinitely many twin primes',
      'The prime counting function π(x) ~ x/ln(x)',
    ],
    correctIndex: 0,
    explanation: 'The Green–Tao theorem (2004) proves that for any k, there exist arithmetic progressions of length k consisting entirely of prime numbers. This was a landmark in additive combinatorics.',
    realWorld: 'Additive combinatorics techniques from this work have applications in pseudorandomness, which is crucial for cryptography and derandomization in computer science.',
    hint: 'Think about primes like 3, 7, 11 (common difference 4) — can you always find longer chains?',
  },
  {
    id: 11402,
    topic: 'tao',
    difficulty: 'easy',
    question: 'Terence Tao won the Fields Medal in 2006 primarily for his contributions to:',
    options: [
      'Partial differential equations, combinatorics, and harmonic analysis',
      'Algebraic geometry and number theory',
      'Topology and differential geometry',
      'Mathematical logic and set theory',
    ],
    correctIndex: 0,
    explanation: 'Tao\'s Fields Medal cited his contributions to PDE, combinatorics, harmonic analysis, and additive number theory. He is known for extraordinary breadth across pure and applied mathematics.',
    realWorld: 'Tao\'s work on compressed sensing (with Candès) revolutionized MRI scanning, enabling faster scans with fewer measurements — directly saving patient time and improving healthcare.',
    hint: 'Tao is known as one of the most versatile mathematicians alive — his medal recognized work across multiple fields.',
  },
  {
    id: 11403,
    topic: 'tao',
    difficulty: 'easy',
    question: 'Tao\'s work with Emmanuel Candès on compressed sensing showed that:',
    options: [
      'Sparse signals can be recovered from far fewer measurements than traditionally required',
      'All signals require Nyquist-rate sampling for perfect reconstruction',
      'Neural networks can compress any signal losslessly',
      'Fourier transforms are the optimal basis for all signal types',
    ],
    correctIndex: 0,
    explanation: 'Compressed sensing proves that if a signal is sparse in some basis, it can be reconstructed from O(k log(n/k)) random measurements instead of n — exponentially fewer. This broke the Nyquist barrier for sparse signals.',
    realWorld: 'MRI machines use compressed sensing to reconstruct images from fewer measurements, reducing scan times by 2-8x. It\'s also used in radio astronomy and seismic imaging.',
    hint: 'If most coefficients are zero, you don\'t need to measure everything.',
  },
  {
    id: 11404,
    topic: 'tao',
    difficulty: 'hard',
    question: 'Tao\'s proof of the Green–Tao theorem crucially relies on which framework from additive combinatorics?',
    options: [
      'Szemerédi\'s theorem transferred to a pseudorandom setting via transference principle',
      'The Hardy–Littlewood circle method applied directly to primes',
      'Fourier analysis on finite fields with exponential sum estimates',
      'Ergodic theory and Furstenberg\'s correspondence principle alone',
    ],
    correctIndex: 0,
    explanation: 'Green and Tao showed that the primes sit inside a pseudorandom set, then used a transference principle to lift Szemerédi\'s theorem (which works for dense sets) to this sparse pseudorandom context.',
    realWorld: 'The transference principle technique has become a standard tool in analytic number theory and has been applied to many other problems about primes and combinatorial structures.',
    hint: 'Szemerédi\'s theorem works for dense sets — the challenge was making it work for the sparse primes.',
  },
  {
    id: 11405,
    topic: 'tao',
    difficulty: 'hard',
    question: 'Tao made a breakthrough on the Erdős discrepancy problem by proving that:',
    options: [
      'Every sequence of ±1 has unbounded partial sums along homogeneous arithmetic progressions',
      'Random ±1 sequences have bounded discrepancy with probability 1',
      'The discrepancy of any sequence grows at most logarithmically',
      'There exist ±1 sequences with discrepancy bounded by √n',
    ],
    correctIndex: 0,
    explanation: 'In 2015, Tao proved the Erdős discrepancy conjecture: for any infinite ±1 sequence and any C, there exist n and d such that |∑_{j=1}^{n} x_{jd}| > C. He used entropy decrement arguments and logarithmic Elliott-type results.',
    realWorld: 'Discrepancy theory underlies quasi-Monte Carlo methods used in quantitative finance for option pricing, where low-discrepancy sequences give faster convergence than random sampling.',
    hint: 'Erdős conjectured you can\'t keep partial sums bounded no matter how cleverly you choose ±1.',
  },
  {
    id: 11406,
    topic: 'tao',
    difficulty: 'hard',
    question: 'In the Kakeya conjecture, Tao and collaborators have made progress showing that Kakeya sets in $\\mathbb{R}^n$ must have:',
    options: [
      'Hausdorff dimension close to n — they cannot be too "thin"',
      'Lebesgue measure exactly zero in all dimensions',
      'Fractal dimension exactly (n+1)/2',
      'Positive measure in dimensions 3 and above',
    ],
    correctIndex: 0,
    explanation: 'A Kakeya set contains a unit line segment in every direction. The conjecture states these must have full Hausdorff dimension n. Tao and others have proved partial bounds pushing the known dimension upward.',
    realWorld: 'The Kakeya conjecture connects to restriction estimates in harmonic analysis, which are used in understanding wave propagation, medical imaging, and radar signal processing.',
    hint: 'A set containing needles in every direction can be measure zero but should still be dimensionally "full."',
  },
  {
    id: 11407,
    topic: 'tao',
    difficulty: 'sota',
    question: 'Tao\'s work on the Navier–Stokes regularity problem constructed:',
    options: [
      'An averaged version of Navier–Stokes that develops finite-time blowup, showing the supercriticality barrier',
      'A full proof that smooth solutions exist for all time in 3D',
      'A counterexample showing turbulent solutions with negative energy',
      'A reduction of Navier–Stokes to a system of ODEs solvable by neural networks',
    ],
    correctIndex: 0,
    explanation: 'Tao (2016) showed that a modified ("averaged") Navier–Stokes equation develops finite-time singularities, demonstrating that any proof of regularity for the actual equations must exploit specific structural cancellations — ruling out broad classes of proof strategies.',
    realWorld: 'Understanding Navier–Stokes regularity is a Millennium Prize Problem. Tao\'s work guides which proof techniques could possibly work for turbulence modeling in aerospace and climate science.',
    hint: 'He didn\'t solve the Millennium Problem — but showed why certain approaches can\'t work.',
  },
  {
    id: 11408,
    topic: 'tao',
    difficulty: 'sota',
    question: 'Tao\'s "polynomial method" breakthrough (with Dvir) for the finite field Kakeya problem showed:',
    options: [
      'Kakeya sets over finite fields $\\mathbb{F}_q^n$ must have size at least $c_n q^n$ — essentially full measure',
      'Kakeya sets can have zero measure over all finite fields',
      'The polynomial method fails for dimensions above 3',
      'Algebraic varieties cannot contain lines in all directions',
    ],
    correctIndex: 0,
    explanation: 'Dvir\'s proof (building on ideas connected to Tao\'s program) used the polynomial method: if a Kakeya set were small, a low-degree polynomial would vanish on it, but a polynomial vanishing on a line in every direction must have high degree — contradiction.',
    realWorld: 'The polynomial method has since been applied to problems in error-correcting codes, incidence geometry, and theoretical computer science, transforming multiple fields.',
    hint: 'A low-degree polynomial that vanishes at enough points must be identically zero — but directions force high degree.',
  },
];
