import type { Question } from '../types';

export const timnitGebruQuestions: Question[] = [
  {
    id: 13101,
    topic: 'timnit-gebru',
    difficulty: 'easy',
    question: 'Timnit Gebru\'s "Gender Shades" research revealed:',
    options: [
      'Commercial facial recognition systems had error rates up to 34% for dark-skinned women vs. <1% for light-skinned men — a massive bias disparity',
      'All facial recognition systems work equally well for all demographics',
      'Gender cannot be detected by AI systems',
      'Only open-source models have bias problems',
    ],
    correctIndex: 0,
    explanation: 'Gender Shades (2018, with Joy Buolamwini) benchmarked facial analysis systems from IBM, Microsoft, and Face++ using an intersectional framework. The worst accuracy gap: 34.7% error for darker-skinned females vs. 0.8% for lighter-skinned males.',
    realWorld: 'This research led IBM to exit the facial recognition market, Microsoft to improve its systems, and cities like San Francisco to ban government use of facial recognition. It changed the entire industry.',
    hint: 'She tested commercial AI systems and found they worked much worse for certain demographic groups.',
  },
  {
    id: 13102,
    topic: 'timnit-gebru',
    difficulty: 'easy',
    question: 'Gebru advocates for "Datasheets for Datasets," which are:',
    options: [
      'Standardized documentation describing a dataset\'s collection process, composition, intended use, and known biases — like a nutrition label for data',
      'Physical paper sheets included in dataset shipments',
      'Spreadsheets listing all data points in a dataset',
      'Legal contracts between data providers and users',
    ],
    correctIndex: 0,
    explanation: 'Just as electronics have datasheets specifying their properties, Gebru proposed that every ML dataset should come with documentation covering: who collected it, what populations are represented, what biases exist, and what it should/shouldn\'t be used for.',
    realWorld: 'Major ML platforms (Hugging Face, Google, Microsoft) now include dataset cards inspired by this work. It\'s becoming standard practice for responsible AI development.',
    hint: 'Think of it as a "nutrition label" for training data — what\'s in it, who made it, what\'s missing.',
  },
  {
    id: 13103,
    topic: 'timnit-gebru',
    difficulty: 'hard',
    question: 'The intersectional approach to AI fairness, championed by Gebru, reveals that:',
    options: [
      'Testing bias on single attributes (gender OR race) misses compounded effects — a system can be "fair" on gender and race separately but deeply biased against specific intersections (e.g., Black women)',
      'All bias can be eliminated by collecting more data',
      'Fairness can only be measured on one demographic axis at a time',
      'Intersectional analysis is unnecessary if overall accuracy is high',
    ],
    correctIndex: 0,
    explanation: 'Inspired by Kimberlé Crenshaw\'s intersectionality theory, Gebru showed that evaluating AI systems on aggregate metrics (overall accuracy, gender accuracy, racial accuracy) can hide severe biases at intersections of protected attributes.',
    realWorld: 'A hiring algorithm might pass gender and race fairness audits individually but systematically reject applications from women of color — intersectional analysis catches what single-axis analysis misses.',
    hint: 'The bias exists at the intersection of multiple identities, not on any single axis alone.',
  },
  {
    id: 13104,
    topic: 'timnit-gebru',
    difficulty: 'hard',
    question: 'Gebru\'s work on the "Stochastic Parrots" paper argued that large language models:',
    options: [
      'Generate fluent text by statistical pattern matching without understanding, creating risks of encoded bias, environmental cost, and false coherence that humans mistake for comprehension',
      'Truly understand language and should be treated as sentient',
      'Are too small to be useful for real applications',
      'Have completely solved the problem of natural language understanding',
    ],
    correctIndex: 0,
    explanation: 'The "Stochastic Parrots" paper (2021) warned that LLMs reproduce patterns from training data (including biases) without understanding meaning. The fluency of outputs can mislead users into trusting biased or false statements.',
    realWorld: 'This paper\'s themes proved prescient: LLM hallucinations, encoded biases, and users over-trusting AI outputs are now recognized as major challenges in AI deployment.',
    hint: 'A parrot can speak fluently without understanding — the question is whether LLMs are similar.',
  },
  {
    id: 13105,
    topic: 'timnit-gebru',
    difficulty: 'sota',
    question: 'Gebru\'s DAIR (Distributed AI Research Institute) advocates for:',
    options: [
      'Community-rooted AI research that centers the perspectives of marginalized communities BEFORE systems are built, not as an afterthought audit',
      'Building AI systems faster without any ethical review',
      'Replacing all AI research with manual processes',
      'Restricting AI research to government labs only',
    ],
    correctIndex: 0,
    explanation: 'DAIR\'s approach inverts the typical AI development cycle: instead of building first and auditing for bias later, involve affected communities in problem definition, data collection, and evaluation criteria from the start.',
    realWorld: 'This "participatory design" approach has influenced AI governance frameworks at the EU, informed the NIST AI Risk Management Framework, and shaped how organizations like the WHO deploy AI in healthcare for underserved populations.',
    hint: 'Don\'t build first and check for bias later — involve affected communities from the very beginning.',
  },
];
