import type { Question } from '../types';

export const ulamQuestions: Question[] = [
  {
    id: 21110,
    topic: 'ulam',
    difficulty: 'sota',
    question: 'Ulam invented the Monte Carlo method while recovering from surgery and playing which game?',
    options: ['Solitaire (Canfield)', 'Chess', 'Poker', 'Bridge'],
    correctIndex: 0,
    explanation: 'While playing solitaire during recovery from brain surgery, Ulam realized that instead of computing the exact probability of winning, he could simply play many random games and estimate the probability empirically — the core idea of Monte Carlo.',
    realWorld: 'Monte Carlo methods now underpin options pricing, AI training (MCTS in AlphaGo), drug discovery, and nuclear reactor design.',
    hint: 'A card game played alone gave him the insight that random sampling beats exact calculation.',
  },
  {
    id: 21111,
    topic: 'ulam',
    difficulty: 'sota',
    question: 'Ulam\'s key contribution to thermonuclear weapon design was proposing which configuration?',
    options: ['Radiation implosion (Teller–Ulam design)', 'Gun-type fission assembly', 'Boosted fission with tritium', 'Pure fusion ignition'],
    correctIndex: 0,
    explanation: 'The Teller–Ulam design uses radiation from a fission primary to compress and ignite a fusion secondary — the key breakthrough that made hydrogen bombs feasible.',
    realWorld: 'This design principle remains the basis of all modern thermonuclear weapons in every nuclear arsenal.',
    hint: 'X-rays from the first stage compress the second stage.',
  },
  {
    id: 21112,
    topic: 'ulam',
    difficulty: 'sota',
    question: 'The "Fermi–Pasta–Ulam–Tsingou problem" (1955) unexpectedly demonstrated which phenomenon in nonlinear systems?',
    options: ['Near-recurrence — the system returned close to its initial state instead of thermalizing', 'Immediate thermalization as expected', 'Chaotic divergence from any initial condition', 'Resonant energy transfer to the highest mode'],
    correctIndex: 0,
    explanation: 'Instead of energy spreading equally among all modes (thermalization), the simulation showed the system nearly returned to its initial state — a shocking result that helped launch the study of solitons and nonlinear dynamics.',
    realWorld: 'This early computer experiment was one of the first uses of numerical simulation to discover new physics, pioneering computational science.',
    hint: 'The energy didn\'t spread out — it came back, defying statistical mechanics expectations.',
  },
  {
    id: 21113,
    topic: 'ulam',
    difficulty: 'sota',
    question: 'Ulam\'s "lucky number" sieve is analogous to which classical algorithm in number theory?',
    options: ['The Sieve of Eratosthenes', 'Euclid\'s algorithm', 'Fermat\'s factorization method', 'Trial division'],
    correctIndex: 0,
    explanation: 'Just as the Sieve of Eratosthenes eliminates composite numbers, Ulam\'s sieve iteratively removes numbers at positions determined by the surviving numbers, generating "lucky numbers" that share many statistical properties with primes.',
    realWorld: 'Lucky numbers provide a testing ground for conjectures about primes — many prime number theorems have analogs for lucky numbers.',
    hint: 'Both sieves iteratively eliminate numbers from a list, but with different elimination rules.',
  },
  {
    id: 21114,
    topic: 'ulam',
    difficulty: 'sota',
    question: 'The Ulam spiral reveals unexpected visual patterns when plotting which mathematical objects on a grid?',
    options: ['Prime numbers arranged in a spiral of consecutive integers', 'Fibonacci numbers on a square lattice', 'Perfect squares in a circular arrangement', 'Twin primes on a number line'],
    correctIndex: 0,
    explanation: 'When integers are arranged in a spiral and primes are highlighted, they cluster along diagonal lines — revealing hidden structure in prime distribution that remains unexplained by number theory.',
    realWorld: 'The Ulam spiral is a famous example of how simple visualization can reveal deep mathematical patterns invisible to pure algebra.',
    hint: 'Doodling integers in a spiral during a boring meeting, he noticed diagonal lines of primes.',
  },
];
