import type { Question } from '../types';

export const vladimirVapnikQuestions: Question[] = [
  {
    id: 4412001,
    topic: 'vladimir-vapnik',
    difficulty: 'easy',
    question: 'Support Vector Machines (SVMs), developed by Vapnik, find the decision boundary that:',
    options: [
      'Maximizes the margin — the distance between the boundary and the nearest points from each class',
      'Minimizes the training error with zero tolerance for misclassification',
      'Passes through the centroids of each class in feature space',
      'Minimizes the number of support vectors to reduce model complexity',
    ],
    correctIndex: 0,
    explanation: 'The max-margin hyperplane is the unique decision boundary equidistant from the nearest points of each class (support vectors). Maximizing margin minimizes the VC dimension, giving a principled generalization guarantee.',
    realWorld: 'SVMs were state-of-art for text classification, bioinformatics, and image recognition before deep learning. They remain competitive on small datasets and are used in medical diagnosis for interpretability.',
    hint: 'Draw the widest possible "road" between two classes — the hyperplane is the centerline of the road.',
  },
  {
    id: 4412002,
    topic: 'vladimir-vapnik',
    difficulty: 'easy',
    question: 'The "kernel trick" used in SVMs computes inner products in high-dimensional feature spaces:',
    options: [
      'Without explicitly computing the mapping $\\phi(x)$ — using only $K(x,x\') = \\langle \\phi(x), \\phi(x\') \\rangle$',
      'By projecting inputs to a random low-dimensional subspace before computing distances',
      'By approximating $\\phi(x)$ with a Taylor series truncated at degree $d$',
      'By replacing the dot product with L1 distance for sparsity',
    ],
    correctIndex: 0,
    explanation: 'The kernel K(x,x\') computes ⟨φ(x),φ(x\')⟩ in an implicit (possibly infinite-dimensional) feature space without ever computing φ(x). The RBF kernel K(x,x\') = exp(-γ‖x-x\'‖²) corresponds to infinite-dimensional features.',
    realWorld: 'Gaussian processes (the Bayesian SVM analog) use the same kernel trick. Kernel methods inspired the "neural tangent kernel" theory explaining how wide neural networks behave at initialization.',
    hint: 'No need to compute the high-dimensional feature vector — just evaluate K(x,x\') = φ(x)·φ(x\') directly.',
  },
  {
    id: 4412003,
    topic: 'vladimir-vapnik',
    difficulty: 'easy',
    question: 'VC dimension (Vapnik-Chervonenkis dimension) measures model capacity by:',
    options: [
      'The largest number of points a model class can shatter (correctly classify in all 2^n configurations)',
      'The number of parameters in the model class',
      'The minimum sample size needed to achieve 95% accuracy',
      'The maximum training error achieved by the worst hypothesis in the class',
    ],
    correctIndex: 0,
    explanation: 'A classifier class has VC dimension d if there exist d points it can shatter (classify all 2^d labelings correctly) but no d+1 points. Linear classifiers in ℝⁿ have VC dimension n+1.',
    realWorld: 'VC theory predicted that SVMs would generalize well despite high feature dimensions — because the margin-maximizing constraint limits the effective VC dimension regardless of input dimensionality.',
    hint: 'A line in 2D can shatter 3 points (any labeling is achievable) but not 4 — so VC dim = 3.',
  },
  {
    id: 412004,
    topic: 'vladimir-vapnik',
    difficulty: 'easy',
    question: 'The soft-margin SVM introduces slack variables $\\xi_i$ to handle:',
    options: [
      'Non-separable data and outliers — allowing some misclassifications with a penalty $C \\sum \\xi_i$',
      'Non-Euclidean feature spaces where the margin is undefined',
      'Multi-class problems by extending binary SVMs to $K$ classes',
      'Imbalanced datasets where one class has far fewer training examples',
    ],
    correctIndex: 0,
    explanation: 'Soft-margin SVM: minimize ‖w‖²/2 + C∑ξᵢ subject to yᵢ(wᵀxᵢ+b) ≥ 1-ξᵢ. The hyperparameter C controls the tradeoff between margin width (generalization) and misclassification penalty (training accuracy).',
    realWorld: 'Setting C is the most critical hyperparameter in SVMs. Cross-validation on C (and kernel hyperparameters) is standard practice — analogous to regularization strength tuning in deep learning.',
    hint: 'ξᵢ = 0: point correctly classified. ξᵢ ∈ (0,1): inside margin. ξᵢ > 1: misclassified.',
  },
  {
    id: 412005,
    topic: 'vladimir-vapnik',
    difficulty: 'hard',
    question: 'The SVM dual optimization problem is: $\\max_\\alpha \\sum_i \\alpha_i - \\frac{1}{2}\\sum_{i,j} \\alpha_i \\alpha_j y_i y_j K(x_i, x_j)$ subject to $\\sum_i \\alpha_i y_i = 0$ and $0 \\leq \\alpha_i \\leq C$. The prediction function is:',
    options: [
      '$f(x) = \\text{sign}\\left(\\sum_i \\alpha_i y_i K(x_i, x)+ b\\right)$ — only support vectors ($\\alpha_i > 0$) contribute',
      '$f(x) = \\text{sign}(w^T x + b)$ with $w = \\sum_i \\alpha_i x_i$',
      '$f(x) = \\text{sign}(\\sum_i \\alpha_i K(x_i, x))$ without bias term',
      '$f(x) = \\sum_i \\alpha_i y_i \\exp(-\\|x_i - x\\|^2)$',
    ],
    correctIndex: 0,
    explanation: 'By KKT conditions, αᵢ > 0 only for support vectors (points on or inside the margin). The classifier depends only on these points — the SVM is sparse in this sense. This also means prediction scales with the number of support vectors, not the data size.',
    realWorld: 'In large-scale settings, many support vectors → slow prediction. This motivated kernel approximations (Random Fourier Features, Nyström) and the move to neural networks for scalable nonlinear classification.',
    hint: 'Most αᵢ = 0 by KKT complementary slackness — only support vectors have nonzero αᵢ.',
  },
  {
    id: 12006,
    topic: 'vladimir-vapnik',
    difficulty: 'hard',
    question: 'The PAC learning bound (Vapnik-Chervonenkis) guarantees that with probability $1-\\delta$, the generalization error satisfies:',
    options: [
      '$R(f) \\leq R_{emp}(f) + O\\left(\\sqrt{\\frac{d \\log(n/d) + \\log(1/\\delta)}{n}}\\right)$',
      '$R(f) \\leq R_{emp}(f) + O(1/\\sqrt{n})$ independent of model complexity',
      '$R(f) \\leq R_{emp}(f) \\cdot e^{d/n}$ growing exponentially with VC dimension',
      '$R(f) \\leq R_{emp}(f) + \\frac{d}{n} \\log\\frac{n}{d}$ for all $n > d$',
    ],
    correctIndex: 0,
    explanation: 'The VC generalization bound shows the gap between training and test error decreases as O(√(d/n)) in the VC dimension d and sample size n. This provides a mathematical foundation for the bias-variance tradeoff and justifies regularization.',
    realWorld: 'Modern deep learning violates this bound (d >> n yet generalizes) — the "deep learning theory puzzle" that motivated PAC-Bayes bounds, NTK theory, and double descent phenomenon research.',
    hint: 'More parameters (higher d) → looser bound unless you get more data n. The ratio d/n controls generalization.',
  },
  {
    id: 12007,
    topic: 'vladimir-vapnik',
    difficulty: 'hard',
    question: 'Structural Risk Minimization (SRM), Vapnik\'s framework, selects models by:',
    options: [
      'Minimizing empirical risk over a nested sequence of hypothesis classes, choosing the class that balances fit and complexity',
      'Minimizing the number of parameters subject to achieving zero training error',
      'Maximizing the margin while minimizing the number of support vectors simultaneously',
      'Adding a regularization term to prevent the training loss from reaching its global minimum',
    ],
    correctIndex: 0,
    explanation: 'SRM: H₁ ⊂ H₂ ⊂ ... with VC dimensions h₁ < h₂ < .... For each level, find the ERM solution; then pick the level that minimizes empirical risk + VC complexity penalty. This generalizes cross-validation with theoretical guarantees.',
    realWorld: 'Model selection via cross-validation is the practical SRM implementation. AIC/BIC criteria are asymptotic approximations to SRM. Regularization paths (LASSO, ridge) implicitly implement SRM by varying the constraint level.',
    hint: 'Simple models underfit (high training error); complex models overfit (low training, high test error). SRM finds the sweet spot with theory.',
  },
  {
    id: 12008,
    topic: 'vladimir-vapnik',
    difficulty: 'sota',
    question: 'The "double descent" phenomenon (contradicting classical VC theory) shows that:',
    options: [
      'Test error decreases, then increases (classical overfitting), then decreases again as model size passes the interpolation threshold',
      'Training error and test error both decrease monotonically with model size when using proper regularization',
      'VC dimension and test error are uncorrelated for neural networks with more than 1 million parameters',
      'Overparameterized models always overfit training data but can be pruned to good generalization',
    ],
    correctIndex: 0,
    explanation: 'Belkin et al. (2019) showed the classical U-shaped test error curve continues into a second descent when models can exactly interpolate training data. Benign overfitting occurs when the model smoothly interpolates — minimum-norm solutions in overparameterized systems generalize.',
    realWorld: 'GPT-3 has 175B parameters for millions of training examples — wildly overparameterized by VC standards yet it generalizes. Double descent explains why this works, challenging Vapnik\'s classical capacity bounds.',
    hint: 'Classical theory says overfitting starts after the interpolation threshold. But modern models keep improving after that — a second descent.',
  },
  {
    id: 12009,
    topic: 'vladimir-vapnik',
    difficulty: 'sota',
    question: 'Kernel methods and neural networks are connected by the Neural Tangent Kernel (NTK). For infinitely wide networks, training is equivalent to:',
    options: [
      'Kernel regression with the NTK $K_{NTK}(x,x\') = \\mathbb{E}_{\\theta}[\\nabla_\\theta f_\\theta(x)^T \\nabla_\\theta f_\\theta(x\')]$',
      'Maximum likelihood estimation in a Gaussian process with RBF kernel',
      'SVM classification with a polynomial kernel of degree equal to network depth',
      'Ridge regression on the raw input features with regularization $\\lambda \\to 0$',
    ],
    correctIndex: 0,
    explanation: 'Jacot et al. (2018) proved that as width → ∞, the network function evolves under gradient descent according to a linear kernel regression with kernel K_NTK — the inner product of parameter gradients. The kernel stays constant (lazy training regime).',
    realWorld: 'NTK theory explains why overparameterized networks trained with gradient descent find the minimum-norm interpolant — connecting Vapnik\'s kernel methods to modern deep learning in a rigorous theoretical framework.',
    hint: 'Infinite width → parameters barely move during training → linearize around initialization → kernel regression.',
  },
  {
    id: 12010,
    topic: 'vladimir-vapnik',
    difficulty: 'sota',
    question: 'Vapnik\'s "Statistical Learning Theory" framework with VC theory applies when samples are i.i.d. Modern ML violates this because:',
    options: [
      'Data is non-stationary (distribution shifts over time), correlated (sequences, graphs), and labels may be noisy or adversarial',
      'Modern datasets have more features than samples, making VC bounds vacuously large',
      'Neural networks have infinite VC dimension, making all VC bounds trivially uninformative',
      'The test distribution is always unknown, making worst-case bounds unachievable in practice',
    ],
    correctIndex: 0,
    explanation: 'Real-world ML: medical data has temporal shift (COVID mutations), text has correlations (n-grams), labels are noisy (crowdsourcing), and adversarial examples exist. VC theory assumes i.i.d. data — violating this invalidates the generalization guarantees.',
    realWorld: 'Distribution shift is the #1 cause of ML deployment failures: ImageNet-trained models fail on medical images, chatbots trained on 2021 data fail on 2024 events, and fraud detectors fail as attackers adapt.',
    hint: 'VC bounds assume the training and test distribution are identical — when does this assumption break in practice?',
  },
];
