import type { Question } from '../types';

export const yannLecunQuestions: Question[] = [
  {
    id: 11701,
    topic: 'yann-lecun',
    difficulty: 'easy',
    question: 'LeCun\'s Convolutional Neural Networks (CNNs) use convolution rather than full connections because:',
    options: [
      'Local connectivity and weight sharing exploit translation invariance and drastically reduce parameters',
      'Convolution is faster to compute on CPUs than matrix multiplication',
      'Convolutional layers can model longer-range dependencies than fully connected layers',
      'Convolution automatically learns optimal filter sizes for any input resolution',
    ],
    correctIndex: 0,
    explanation: 'A convolution filter slides across the input, sharing weights — detecting the same feature anywhere. This exploits translation invariance (a cat is a cat wherever it appears) and reduces parameters from O(n²) to O(k²) per layer.',
    realWorld: 'Modern vision models (ResNet, ViT, YOLO) all use convolutions or equivalent local attention — LeCun\'s weight-sharing insight is present in every image recognition system deployed today.',
    hint: 'If you\'re detecting an edge, the same detector works at every position in the image — that\'s the key insight.',
  },
  {
    id: 11702,
    topic: 'yann-lecun',
    difficulty: 'easy',
    question: 'LeNet-5, LeCun\'s seminal 1998 CNN, was trained to recognize handwritten digits using:',
    options: [
      'Gradient-based learning applied end-to-end from pixel inputs to class outputs',
      'Decision trees at each convolutional layer for feature selection',
      'SVM classifiers on top of hand-crafted Gabor filter banks',
      'Nearest-neighbor matching of digit templates using pixel correlation',
    ],
    correctIndex: 0,
    explanation: 'LeNet-5 was the first large-scale demonstration of end-to-end gradient learning in a deep convolutional network. It achieved 99%+ accuracy on MNIST and was deployed in US bank check readers, processing millions of checks per day.',
    realWorld: 'The MNIST benchmark LeCun created is still used for testing ML frameworks. LeNet-5\'s architecture — conv → pool → conv → pool → FC — is the template every modern CNN follows.',
    hint: 'Every layer, from pixel to class probability, is differentiable — backpropagation flows through the whole stack.',
  },
  {
    id: 11703,
    topic: 'yann-lecun',
    difficulty: 'easy',
    question: 'LeCun argues that "Energy-Based Models" (EBMs) are more general than probabilistic models because:',
    options: [
      'They associate a scalar energy to each input and don\'t require a normalized probability distribution',
      'They can be trained without any gradient computation using contrastive methods',
      'Energy functions are always convex, guaranteeing global optimization',
      'They directly output class probabilities without requiring a softmax normalization',
    ],
    correctIndex: 0,
    explanation: 'An EBM assigns low energy to observed/compatible configurations and high energy to incompatible ones. Unlike probability distributions, no partition function is needed — which is often intractable in high dimensions.',
    realWorld: 'Score-based diffusion models (Stable Diffusion, DALL-E) are EBMs in disguise — they learn ∇log p(x) (the score) rather than p(x) directly, avoiding the partition function problem.',
    hint: 'A probability model needs to normalize (sum/integrate to 1) — an energy model just needs to be low for good data.',
  },
  {
    id: 11704,
    topic: 'yann-lecun',
    difficulty: 'easy',
    question: 'LeCun proposed "JEPA" (Joint Embedding Predictive Architecture) as an alternative to generative models for self-supervised learning. JEPA learns by:',
    options: [
      'Predicting the representation of a masked region, not the pixels themselves',
      'Generating photorealistic masked regions using a GAN discriminator',
      'Contrastively learning representations by comparing augmented image pairs',
      'Predicting future video frames in pixel space using a variational autoencoder',
    ],
    correctIndex: 0,
    explanation: 'JEPA predicts abstract representations of missing patches rather than pixels — avoiding the need to model irrelevant fine-grained details. This resembles how humans form abstract mental models rather than precise sensory predictions.',
    realWorld: 'Meta\'s V-JEPA and I-JEPA models achieve strong video and image understanding with significantly less compute than generative models — demonstrating the power of representation-space prediction.',
    hint: 'Instead of predicting "what does the hidden patch look like in pixels?", predict "what abstract features would the hidden patch have?"',
  },
  {
    id: 11705,
    topic: 'yann-lecun',
    difficulty: 'hard',
    question: 'The receptive field of a neuron in layer $l$ of a CNN with stride $s$ and kernel size $k$ grows as:',
    options: [
      '$r_l = r_{l-1} + (k-1) \\cdot \\prod_{i=1}^{l-1} s_i$ — growing multiplicatively with stride',
      '$r_l = r_{l-1} + k$ — growing additively regardless of stride',
      '$r_l = k^l$ — growing exponentially with depth',
      '$r_l = l \\cdot k$ — growing linearly with depth and kernel size',
    ],
    correctIndex: 0,
    explanation: 'Each layer adds (k-1) input pixels to the receptive field, scaled by all previous strides (since earlier strides expanded the effective coverage). Strides enable efficient coverage of large input areas with few layers.',
    realWorld: 'Designing CNNs for high-resolution images requires computing effective receptive fields — too small means global context is missed, too large wastes capacity on irrelevant regions.',
    hint: 'A stride-2 layer makes one step in feature space correspond to 2 input pixels — so subsequent receptive field growth is doubled.',
  },
  {
    id: 11706,
    topic: 'yann-lecun',
    difficulty: 'hard',
    question: 'LeCun\'s document recognition system used Connectionist Temporal Classification (CTC). CTC loss allows sequence prediction without:',
    options: [
      'Pre-segmented training data — it marginalizes over all possible alignments between input frames and output labels',
      'Recurrent networks — CTC can be applied to any sequence-to-sequence model',
      'Beam search decoding — CTC directly outputs the most likely label sequence',
      'A language model — CTC jointly learns acoustics and language modeling',
    ],
    correctIndex: 0,
    explanation: 'CTC introduces a "blank" token and sums over all valid alignments (via dynamic programming) of output labels to input frames. This allows training on paired (audio, transcript) data without frame-level annotation.',
    realWorld: 'CTC is used in production speech recognition (DeepSpeech, wav2vec), OCR systems (recognizing text in images without character segmentation), and protein structure prediction (sequence labeling).',
    hint: 'The key problem: "cat" could align to frames as "c-a-t", "cc-a-t", "c-aa-t" etc. — CTC sums over all valid alignments.',
  },
  {
    id: 11707,
    topic: 'yann-lecun',
    difficulty: 'hard',
    question: 'LeCun\'s "flat minima" hypothesis about generalization states:',
    options: [
      'Wide, flat minima in the loss landscape generalize better than sharp minima because small input perturbations don\'t increase loss much',
      'Global minima of the training loss always correspond to global minima of the test loss',
      'Stochastic gradient descent always converges to the flattest minimum available',
      'Adding L2 regularization always finds flatter minima than unregularized training',
    ],
    correctIndex: 0,
    explanation: 'Hochreiter and Schmidhuber (1997), following LeCun\'s intuitions, argued flat minima have low description length and better generalization. Sharp minima are sensitive to distribution shift. SAM (Sharpness-Aware Minimization) explicitly seeks flat minima.',
    realWorld: 'SAM optimizer and its variants are state-of-the-art on ImageNet and NLP benchmarks — directly implementing the flat minima principle LeCun articulated for improving generalization.',
    hint: 'Imagine moving the test distribution slightly — a flat minimum still has low loss, a sharp minimum may suddenly have high loss.',
  },
  {
    id: 11708,
    topic: 'yann-lecun',
    difficulty: 'sota',
    question: 'LeCun\'s "World Models" framework argues that intelligent systems need an internal model that can predict consequences of actions. This connects to:',
    options: [
      'Model-based reinforcement learning: planning by simulating trajectories through a learned world model',
      'Model-free policy gradient methods that directly optimize expected reward',
      'Imitation learning that clones expert behavior without internal prediction',
      'Contrastive self-supervised learning that matches views of the same scene',
    ],
    correctIndex: 0,
    explanation: 'A world model predicts s_{t+1} = f(s_t, a_t). Planning via model rollouts (MCTS, MPC) enables sample-efficient learning and zero-shot generalization — the missing ingredient LeCun argues current LLMs lack for physical reasoning.',
    realWorld: 'AlphaZero uses a world model for MCTS planning. DreamerV3 learns world models in latent space for Atari and robot control. Physical simulation in robotics training uses learned world models for dexterous manipulation.',
    hint: 'Chess engines don\'t just react — they simulate future moves. LeCun wants AI to do the same in the physical world.',
  },
  {
    id: 11709,
    topic: 'yann-lecun',
    difficulty: 'sota',
    question: 'The "manifold hypothesis" underlying deep learning representations states that:',
    options: [
      'Natural data (images, text, audio) lies near a low-dimensional manifold embedded in high-dimensional space',
      'All deep network layers compute projections onto hyperplanes through the origin',
      'The loss surface of a deep network is a smooth Riemannian manifold with no local minima',
      'Neural network features lie on geodesics of the input space metric tensor',
    ],
    correctIndex: 0,
    explanation: 'ImageNet images live in 224×224×3 ≈ 150K dimensional space, but the manifold of "natural images" has far lower intrinsic dimension. Deep networks unfold and flatten this manifold, making classification linear in the learned representation space.',
    realWorld: 'Diffusion models sample from the natural image manifold. Out-of-distribution detection identifies points far from the learned manifold. Dimensionality reduction (UMAP, t-SNE) reveals this manifold structure in 2D.',
    hint: 'A million random 224×224 pixel grids are nearly never natural images — natural images form a thin manifold in that huge space.',
  },
  {
    id: 11710,
    topic: 'yann-lecun',
    difficulty: 'sota',
    question: 'LeCun\'s objection to autoregressive LLMs as a path to AGI centers on their inability to:',
    options: [
      'Perform persistent memory, planning, and reasoning over grounded physical world models',
      'Scale to longer context windows without quadratic attention complexity',
      'Generate coherent multi-paragraph text without repetition or contradiction',
      'Be fine-tuned with RLHF without catastrophic forgetting of pre-trained knowledge',
    ],
    correctIndex: 0,
    explanation: 'LeCun argues LLMs predict next tokens without grounding in physical reality, persistent working memory, or genuine planning ability. AGI requires System 2 deliberate reasoning, a hierarchical world model, and the ability to plan over latent representations.',
    realWorld: 'Current LLMs fail at: counting objects in novel arrangements, consistent 3D spatial reasoning, long-horizon planning, and physical commonsense — exactly the World Model capabilities LeCun identifies as missing.',
    hint: 'Predicting the next word is not the same as understanding the world — LeCun distinguishes language mastery from physical intelligence.',
  },
];
