import type { Question } from '../types';

export const bengioQuestions: Question[] = [
  {
    id: 11601,
    topic: 'yoshua-bengio',
    difficulty: 'easy',
    question: 'Bengio, LeCun, and Hinton won the 2018 Turing Award for their contributions to:',
    options: [
      'Deep learning — the conceptual and practical foundations of modern neural networks',
      'Reinforcement learning — policy gradient methods and temporal difference learning',
      'Probabilistic graphical models — Bayesian networks and belief propagation',
      'Evolutionary computation — genetic algorithms and neuroevolution',
    ],
    correctIndex: 0,
    explanation: 'The three "godfathers of deep learning" received the ACM Turing Award for breakthrough work that enabled practical deep neural networks, which now power voice recognition, image classification, and language models.',
    realWorld: 'GPT-4, Stable Diffusion, AlphaFold, and essentially every modern AI system is built on the deep learning foundations developed by Bengio, LeCun, and Hinton.',
    hint: 'It\'s often called the "Nobel Prize of Computing" — what field connects all three winners?',
  },
  {
    id: 11602,
    topic: 'yoshua-bengio',
    difficulty: 'easy',
    question: 'Bengio\'s work on word embeddings and neural language models (early 2000s) showed that words could be represented as:',
    options: [
      'Dense continuous vectors in a learned semantic space where similar words are nearby',
      'Sparse one-hot vectors indexed by vocabulary position',
      'Probability distributions over all possible next words',
      'Binary codes derived from word frequency statistics',
    ],
    correctIndex: 0,
    explanation: 'Bengio et al. (2003) "A Neural Probabilistic Language Model" introduced learned word embeddings — dense vectors where semantic similarity corresponds to geometric proximity. This directly preceded Word2Vec, GloVe, and BERT embeddings.',
    realWorld: 'Every modern NLP model — BERT, GPT, T5 — uses dense token embeddings descended directly from Bengio\'s 2003 neural language model architecture.',
    hint: 'The embedding layer maps discrete tokens to points in a continuous vector space — nearby points have similar meanings.',
  },
  {
    id: 11603,
    topic: 'yoshua-bengio',
    difficulty: 'easy',
    question: 'The "attention mechanism" in transformers computes weighted sums over values. Bengio\'s group at Mila contributed foundational work on attention via:',
    options: [
      'Neural machine translation models that first used soft attention to align source and target words',
      'Hard attention models for image generation using REINFORCE',
      'Cross-attention in Vision Transformers for image-text alignment',
      'Flash attention: an IO-efficient exact attention algorithm',
    ],
    correctIndex: 0,
    explanation: 'Bahdanau, Cho, and Bengio (2014) "Neural Machine Translation by Jointly Learning to Align and Translate" introduced soft attention — the encoder-decoder model that revolutionized NLP and directly led to the Transformer.',
    realWorld: 'The 2014 Bahdanau attention paper is one of the most cited in NLP history — its softmax-over-keys mechanism is now in every Transformer, LLM, and vision model worldwide.',
    hint: 'The 2014 translation model learned to focus on relevant source words while generating each target word — that\'s attention.',
  },
  {
    id: 11604,
    topic: 'yoshua-bengio',
    difficulty: 'easy',
    question: 'Bengio\'s research on "consciousness priors" and "system 2 deep learning" argues that AI needs:',
    options: [
      'Compositionality, causality, and deliberate reasoning beyond pattern recognition',
      'Larger models with more parameters to achieve human-level intelligence',
      'Purely unsupervised pretraining without any human feedback',
      'Reinforcement learning from human feedback as the primary training signal',
    ],
    correctIndex: 0,
    explanation: 'Bengio argues current deep learning excels at System 1 (fast, intuitive pattern matching) but lacks System 2 reasoning (deliberate, symbolic, causal). His research agenda targets inductive biases for causality, compositionality, and generalization.',
    realWorld: 'LLM failures on multi-step reasoning, counterfactuals, and novel compositions illustrate exactly the System 2 limitations Bengio identified — motivating neuro-symbolic and causal AI research.',
    hint: 'Kahneman\'s "Thinking Fast and Slow" — System 1 is automatic, System 2 is deliberate.',
  },
  {
    id: 11605,
    topic: 'yoshua-bengio',
    difficulty: 'hard',
    question: 'Bengio et al. (2013) proved that deep networks can represent certain functions exponentially more efficiently than shallow networks. This "depth advantage" relies on:',
    options: [
      'Compositionality: deep networks compute hierarchical features, avoiding exponential blowup in circuit size',
      'Universal approximation: any function can be approximated by a single hidden layer',
      'The vanishing gradient theorem: gradients grow exponentially with depth',
      'Lottery ticket hypothesis: sparse subnetworks in deep models generalize better',
    ],
    correctIndex: 0,
    explanation: 'Some functions (like parity of n bits) require exponential width in a shallow network but only O(n) depth in a deep one. This compositional hierarchy — each layer reuses representations from below — is the theoretical foundation for why depth matters.',
    realWorld: 'ResNets, ViTs, and language models all benefit from depth for this reason — each layer learns increasingly abstract, compositional features of the input.',
    hint: 'Computing XOR of n bits: shallow needs 2^n neurons, deep needs O(n) layers of 2-input XOR gates.',
  },
  {
    id: 11606,
    topic: 'yoshua-bengio',
    difficulty: 'hard',
    question: 'Variational Autoencoders (VAEs), connected to Bengio\'s generative modeling work, maximize the ELBO:',
    options: [
      '$\\mathcal{L} = \\mathbb{E}_{q(z|x)}[\\log p(x|z)] - D_{KL}(q(z|x) \\| p(z))$',
      '$\\mathcal{L} = \\log p(x) - D_{KL}(p(z|x) \\| q(z))$',
      '$\\mathcal{L} = -\\|x - \\hat{x}\\|^2 + \\|z\\|^2$',
      '$\\mathcal{L} = \\mathbb{E}_{p(z)}[\\log q(x|z)] + H(q(z|x))$',
    ],
    correctIndex: 0,
    explanation: 'The ELBO (Evidence Lower BOund) is a tractable lower bound on log p(x). The reconstruction term E[log p(x|z)] rewards accurate decoding; the KL term -D_KL(q‖p) regularizes the latent space to be smooth and well-structured.',
    realWorld: 'VAEs generate smooth latent spaces enabling interpolation between faces, drug molecule generation, and anomaly detection by measuring reconstruction error.',
    hint: 'ELBO = reconstruction quality − KL penalty for deviating from the prior p(z).',
  },
  {
    id: 11607,
    topic: 'yoshua-bengio',
    difficulty: 'hard',
    question: 'Curriculum learning (Bengio et al., 2009) improves training by:',
    options: [
      'Presenting examples in order of increasing difficulty, mimicking human pedagogical strategies',
      'Balancing class frequencies by oversampling rare categories',
      'Annealing the learning rate based on validation loss plateau detection',
      'Mixing data from multiple domains to improve transfer learning',
    ],
    correctIndex: 0,
    explanation: 'Curriculum learning starts with easy examples (clear patterns), gradually introducing harder ones. This improves convergence speed and generalization, especially for structured tasks like parsing, translation, and sequence modeling.',
    realWorld: 'AlphaGo Zero\'s self-play curriculum, InstructGPT\'s RLHF difficulty progression, and speech recognition training on clean-then-noisy audio all use curriculum learning principles.',
    hint: 'Teachers don\'t start with calculus — they start with arithmetic. The same principle applies to neural network training.',
  },
  {
    id: 11608,
    topic: 'yoshua-bengio',
    difficulty: 'sota',
    question: 'Bengio\'s "GFlowNets" (2021) are trained to sample objects proportional to a reward $R(x)$. Unlike MCMC which samples from $p(x) \\propto R(x)$, GFlowNets:',
    options: [
      'Learn a sequential construction policy that generates diverse high-reward objects, not just the mode',
      'Use importance sampling to reweight MCMC samples by R(x)',
      'Apply simulated annealing to escape local reward maxima',
      'Train a discriminator to distinguish high-reward from low-reward objects',
    ],
    correctIndex: 0,
    explanation: 'GFlowNets treat generation as a flow network and train to make flow proportional to R(x). Unlike RL which seeks the maximum reward object, GFlowNets sample the full distribution — crucial for drug discovery where diversity matters as much as quality.',
    realWorld: 'GFlowNets are applied to molecular generation in drug discovery, generating diverse antibody candidates and exploring combinatorial design spaces that MCMC and RL would collapse into mode-seeking behavior.',
    hint: 'MCMC finds typical samples; RL finds the maximum. GFlowNets find all good samples proportionally.',
  },
  {
    id: 11609,
    topic: 'yoshua-bengio',
    difficulty: 'sota',
    question: 'The Bengio-Courville-Vincent textbook "Deep Learning" defines representation learning as:',
    options: [
      'Learning transformations that expose underlying explanatory factors of variation in data',
      'Any method that learns a mapping from inputs to outputs without manual feature engineering',
      'Unsupervised pretraining followed by supervised fine-tuning on any task',
      'Training autoencoders to reconstruct inputs through information bottleneck layers',
    ],
    correctIndex: 0,
    explanation: 'Good representations disentangle the true factors of variation (object identity, pose, lighting) from each other. Learning these "explanatory factors" is the deep learning research program — from embeddings to disentangled VAEs to causal representations.',
    realWorld: 'CLIP learns representations where "a dog playing fetch" and the corresponding image are nearby — exposing the shared semantic factors across vision and language modalities.',
    hint: 'What makes a representation "good"? It should expose the true causes of what varies in the data.',
  },
  {
    id: 11610,
    topic: 'yoshua-bengio',
    difficulty: 'sota',
    question: 'Bengio\'s "Causal Representation Learning" agenda argues that ML models fail to generalize out-of-distribution because:',
    options: [
      'They exploit spurious statistical correlations rather than invariant causal mechanisms',
      'They are not trained on enough diverse data to cover the test distribution',
      'Gradient descent converges to sharp minima that generalize poorly',
      'Transformer architectures lack inductive biases for structured reasoning',
    ],
    correctIndex: 0,
    explanation: 'Causal models have stable mechanisms: P(Y|do(X)) is invariant across environments, while P(Y|X) is not. Models trained on correlations fail when the distribution shifts (hospital COVID models failing on new demographics). Causal structure enables robust generalization.',
    realWorld: 'Medical AI models trained during COVID-19 failed catastrophically when disease prevalence changed — they learned spurious correlations (e.g., ICU equipment → severe disease) rather than causal mechanisms.',
    hint: 'Correlation ≠ causation — a model exploiting spurious correlations will fail when those correlations break in new environments.',
  },
];
