import type { Question } from '../types';

export const zenoQuestions: Question[] = [
  {
    id: 20600,
    topic: 'zeno',
    difficulty: 'hard',
    question: 'Zeno\'s "Achilles and the Tortoise" paradox is resolved by recognizing that the infinite sum $\\sum_{n=0}^{\\infty} ar^n$ with $|r|<1$ converges to:',
    options: ['$\\frac{a}{1-r}$', '$\\infty$', '$0$', '$\\frac{a}{r}$'],
    correctIndex: 0,
    explanation: 'The geometric series converges to a finite value — Achilles catches the tortoise in finite time. Zeno\'s error was assuming an infinite number of steps requires infinite time.',
    realWorld: 'Geometric series underpin compound interest calculations, signal processing, and digital-to-analog conversion.',
    hint: 'An infinite number of terms can still sum to a finite number.',
  },
  {
    id: 20601,
    topic: 'zeno',
    difficulty: 'hard',
    question: 'Zeno\'s "Dichotomy Paradox" states you must traverse half the distance, then half the remainder, ad infinitum. This implicitly raises which foundational question?',
    options: ['Whether the real number line is actually complete (no gaps)', 'Whether space is discrete', 'Whether time is circular', 'Whether velocity is constant'],
    correctIndex: 0,
    explanation: 'The paradox probes whether the continuum is truly complete — resolved by the Cauchy/Weierstrass construction of the real numbers and limits.',
    realWorld: 'The completeness of ℝ is the foundation of all modern analysis, differential equations, and numerical computing.',
    hint: 'The resolution requires a rigorous definition of limits and the structure of the number line.',
  },
  {
    id: 20602,
    topic: 'zeno',
    difficulty: 'sota',
    question: 'In quantum mechanics, the "Quantum Zeno Effect" describes what happens when a system is measured continuously:',
    options: ['The system is frozen in its initial state (evolution is inhibited)', 'The system evolves faster', 'The system decays immediately', 'Superposition is enhanced'],
    correctIndex: 0,
    explanation: 'Frequent measurement collapses the wave function back to the initial state, effectively freezing evolution — "a watched pot never boils" made literal by quantum theory.',
    realWorld: 'The Quantum Zeno Effect is exploited in quantum error correction and protecting fragile quantum states in quantum computers.',
    hint: 'Named after Zeno because continuous observation prevents change.',
  },
  {
    id: 20603,
    topic: 'zeno',
    difficulty: 'sota',
    question: 'Abraham Robinson\'s non-standard analysis (1966) resolves Zeno\'s paradoxes using which mathematical objects?',
    options: ['Infinitesimals as rigorous elements of a hyperreal number field', 'Imaginary numbers', 'p-adic numbers', 'Surreal numbers'],
    correctIndex: 0,
    explanation: 'Non-standard analysis restores Leibniz\'s infinitesimals as legitimate mathematical objects in the hyperreal field *ℝ, providing an alternative resolution to Zeno.',
    realWorld: 'Non-standard analysis has applications in probability theory, mathematical economics, and stochastic calculus.',
    hint: 'Robinson made the "infinitely small" quantities that Leibniz used rigorous via model theory.',
  },
  {
    id: 20604,
    topic: 'zeno',
    difficulty: 'easy',
    question: 'In Zeno\'s "Arrow Paradox," why does he argue a flying arrow is actually motionless?',
    options: ['At any single instant, the arrow occupies a fixed position and has no motion', 'The arrow is too fast to see', 'Air resistance stops it', 'Gravity pulls it down instantly'],
    correctIndex: 0,
    explanation: 'Zeno argued that at each instant, the arrow is "at rest" in a fixed location — so when is it moving? This challenges the concept of instantaneous velocity.',
    realWorld: 'This paradox motivated the rigorous definition of velocity as a derivative: $v = \\lim_{\\Delta t \\to 0} \\frac{\\Delta x}{\\Delta t}$.',
    hint: 'If time is made of instants, and at each instant the arrow is still, how can it move?',
  },
];
