import type { Question } from '../types';

export const zhangYitangQuestions: Question[] = [
  {
    id: 11901,
    topic: 'zhang-yitang',
    difficulty: 'easy',
    question: 'Yitang Zhang stunned the mathematical world in 2013 by proving:',
    options: [
      'There are infinitely many pairs of primes differing by at most 70 million',
      'The Riemann Hypothesis is true for all zeros with real part 1/2',
      'Every even number is the sum of two primes (Goldbach\'s conjecture)',
      'The twin prime conjecture (primes differing by exactly 2)',
    ],
    correctIndex: 0,
    explanation: 'Zhang proved the first finite bound on prime gaps: there are infinitely many pairs of primes with gap ≤ 70,000,000. This was later reduced to 246 by the Polymath project (Maynard, Tao et al.).',
    realWorld: 'Understanding prime gaps is fundamental to cryptography — the distribution of primes determines the security of RSA and other cryptographic systems.',
    hint: 'He didn\'t prove twins (gap = 2), but proved a finite bound existed — the first breakthrough in the bounded gaps problem.',
  },
  {
    id: 11902,
    topic: 'zhang-yitang',
    difficulty: 'easy',
    question: 'What makes Zhang\'s story particularly remarkable in the history of mathematics?',
    options: [
      'He was a largely unknown 58-year-old lecturer at the University of New Hampshire when he made his breakthrough',
      'He was the youngest mathematician to solve a major conjecture at age 22',
      'He used artificial intelligence to discover the proof',
      'He solved the problem while working at a major research institute with unlimited funding',
    ],
    correctIndex: 0,
    explanation: 'Zhang had struggled to find an academic position for years, working at Subway sandwich shops and as a motel clerk before becoming a lecturer. His proof, submitted to the Annals of Mathematics, was verified in weeks.',
    realWorld: 'Zhang\'s story demonstrates that breakthrough mathematics can come from unexpected places — inspiring the mathematical community to value persistence and independent thinking.',
    hint: 'His path was unconventional — academic setbacks didn\'t stop him from working on hard problems for decades.',
  },
  {
    id: 11903,
    topic: 'zhang-yitang',
    difficulty: 'hard',
    question: 'Zhang\'s proof of bounded prime gaps crucially relied on a modified version of:',
    options: [
      'The Goldston–Pintz–Yıldırım (GPY) sieve method with a breakthrough handling of Type III sums',
      'The Green–Tao transference principle for primes in arithmetic progressions',
      'The Selberg sieve with optimal weights',
      'The Bombieri–Vinogradov theorem without any modifications',
    ],
    correctIndex: 0,
    explanation: 'GPY had shown that bounded gaps would follow if primes were well-distributed in arithmetic progressions beyond the Bombieri–Vinogradov range. Zhang proved a weaker but sufficient form of this distribution using novel estimates for incomplete exponential sums.',
    realWorld: 'Sieve methods from analytic number theory have applications in coding theory and error detection, where "sieving" through candidate codewords mirrors sieving for primes.',
    hint: 'GPY set up the framework — Zhang\'s innovation was proving primes are equidistributed "enough" in progressions.',
  },
  {
    id: 11904,
    topic: 'zhang-yitang',
    difficulty: 'hard',
    question: 'After Zhang\'s breakthrough, James Maynard independently improved the bound to 600 using:',
    options: [
      'A multidimensional Selberg sieve with optimized weight functions, different from Zhang\'s approach',
      'The same method as Zhang with better computational optimization',
      'Machine learning to search for optimal sieve parameters',
      'A completely new approach based on the circle method',
    ],
    correctIndex: 0,
    explanation: 'Maynard (and independently Tao) used a multidimensional sieve optimization that was simpler and more powerful than Zhang\'s method. The Polymath 8 project then pushed the bound down to 246.',
    realWorld: 'The Polymath project\'s collaborative approach to optimizing Zhang\'s result demonstrated the power of open, internet-based mathematical collaboration.',
    hint: 'Maynard\'s sieve uses multiple variables and variational calculus to optimize — a different path to the same goal.',
  },
  {
    id: 11905,
    topic: 'zhang-yitang',
    difficulty: 'sota',
    question: 'Zhang\'s handling of "Type III sums" in his proof introduced a novel technique by:',
    options: [
      'Using incomplete Kloosterman sums and the Weil bound to control bilinear forms in the sieve beyond Bombieri–Vinogradov',
      'Applying the Riemann Hypothesis for function fields directly',
      'Using the spectral theory of automorphic forms on GL(3)',
      'Reducing to counting lattice points in high-dimensional convex bodies',
    ],
    correctIndex: 0,
    explanation: 'The key innovation was bounding Type III exponential sums (bilinear forms involving Kloosterman-type sums) using the Weil bound for algebraic curves over finite fields. This gave the extra saving needed beyond Bombieri–Vinogradov.',
    realWorld: 'Techniques from algebraic geometry over finite fields (Weil\'s theorem) originally developed for pure mathematics now power error-correcting codes and cryptographic protocols.',
    hint: 'Kloosterman sums are exponential sums that arise when studying primes in arithmetic progressions — Weil\'s bound controls their size.',
  },
];
