// Shared question bank for edge functions (Deno runtime)
// This is a duplicate of the src/content data for server-side use.

export interface Question {
  id: number;
  topic: string;
  difficulty: 'easy' | 'hard' | 'sota';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  realWorld: string;
  hint: string;
}

export const allQuestions: Question[] = [
  // ── Linear Algebra: Easy ──
  { id: 1, topic: 'linear-algebra', difficulty: 'easy', question: 'What does Ax = b represent?', options: ['A system of linear equations', 'A differential equation', 'A probability distribution', 'An optimization problem'], correctIndex: 0, explanation: 'Matrix-vector multiplication encodes a system of linear equations.', realWorld: 'Used in circuits and linear regression.', hint: 'Think about how rows of a matrix combine with entries of a vector.' },
  { id: 2, topic: 'linear-algebra', difficulty: 'easy', question: 'What is the L2 norm of a vector?', options: ['Sum of absolute values', 'Euclidean length (square root of sum of squares)', 'Maximum component', 'Number of nonzero entries'], correctIndex: 1, explanation: 'L2 norm gives the Euclidean distance from the origin.', realWorld: 'Backbone of regularization in ML.', hint: 'Recall the Pythagorean theorem generalized to n dimensions.' },
  { id: 26, topic: 'linear-algebra', difficulty: 'easy', question: 'The transpose of A swaps:', options: ['Eigenvalues and eigenvectors', 'Rows and columns', 'Diagonal and off-diagonal', 'Real and imaginary parts'], correctIndex: 1, explanation: 'Transpose reflects the matrix across its diagonal.', realWorld: 'Used in least-squares and covariance matrices.', hint: 'What happens when you flip a matrix along its main diagonal?' },
  { id: 29, topic: 'linear-algebra', difficulty: 'easy', question: 'The dot product a·b = 0 means:', options: ['Parallel', 'Orthogonal (perpendicular)', 'Equal', 'Unit vectors'], correctIndex: 1, explanation: 'Zero dot product means 90° angle — orthogonal.', realWorld: 'Fundamental in PCA and attention mechanisms.', hint: 'Consider what angle between two vectors gives cosine = 0.' },
  { id: 48, topic: 'linear-algebra', difficulty: 'easy', question: 'An identity matrix I satisfies Ix = ?', options: ['0', 'x', 'x^T', '2x'], correctIndex: 1, explanation: 'Identity matrix leaves any vector unchanged.', realWorld: 'Used in weight initialization and default transformations.', hint: 'This special matrix does absolutely nothing to whatever it multiplies.' },
  { id: 49, topic: 'linear-algebra', difficulty: 'easy', question: 'A 3×2 matrix has:', options: ['3 columns and 2 rows', '3 rows and 2 columns', '6 rows', '5 elements'], correctIndex: 1, explanation: 'Matrix dimensions are rows × columns.', realWorld: 'Verifying dimensions is essential for neural network architectures.', hint: 'The first number is always the number of rows.' },
  { id: 50, topic: 'linear-algebra', difficulty: 'easy', question: 'Matrix multiplication AB requires:', options: ['Both square', 'Columns of A = rows of B', 'Same rows', 'Both symmetric'], correctIndex: 1, explanation: 'Inner dimensions must match for valid multiplication.', realWorld: 'Layer dimensions must be compatible in neural networks.', hint: 'The inner dimensions must agree.' },
  { id: 51, topic: 'linear-algebra', difficulty: 'easy', question: 'A symmetric matrix satisfies:', options: ['A = -A^T', 'A = A^T', 'A = A^{-1}', 'det(A) = 1'], correctIndex: 1, explanation: 'Symmetric matrix equals its own transpose.', realWorld: 'Covariance and kernel matrices are always symmetric.', hint: 'This matrix is a mirror image of itself across the diagonal.' },

  // ── Linear Algebra: Hard ──
  { id: 3, topic: 'linear-algebra', difficulty: 'hard', question: 'If Av = λv, what is λ?', options: ['A singular value', 'An eigenvalue', 'The determinant', 'The trace'], correctIndex: 1, explanation: 'Lambda is an eigenvalue — a direction that A only scales.', realWorld: 'PCA uses eigenvalues.', hint: 'This scalar tells you how much a special direction gets stretched.' },
  { id: 5, topic: 'linear-algebra', difficulty: 'hard', question: 'What does det(A) = 0 imply?', options: ['A is orthogonal', 'A is singular (non-invertible)', 'A is symmetric', 'All positive eigenvalues'], correctIndex: 1, explanation: 'Zero determinant means the matrix loses information.', realWorld: 'Singularity detection in numerical solvers.', hint: 'What happens to the volume of a parallelepiped when it collapses?' },
  { id: 27, topic: 'linear-algebra', difficulty: 'hard', question: 'The trace tr(A) equals:', options: ['Product of eigenvalues', 'Sum of diagonal elements', 'The determinant', 'The rank'], correctIndex: 1, explanation: 'Trace is sum of diagonal elements, also sum of eigenvalues.', realWorld: 'Used in Frobenius norm and graph clustering.', hint: 'Look at what sits on the main diagonal and sum it up.' },
  { id: 52, topic: 'linear-algebra', difficulty: 'hard', question: 'The null space of A is vectors x where:', options: ['Ax = x', 'Ax = 0', '||x|| = 0', 'x^T A = x^T'], correctIndex: 1, explanation: 'Null space contains all vectors mapped to zero by A.', realWorld: 'Diagnoses underdetermined systems in robotics.', hint: 'Which vectors get completely annihilated by the matrix?' },
  { id: 53, topic: 'linear-algebra', difficulty: 'hard', question: 'An orthogonal matrix Q satisfies Q^T Q = ?', options: ['0', 'Q', 'I', 'Q²'], correctIndex: 2, explanation: 'Orthogonal matrix has orthonormal columns: Q^T Q = I.', realWorld: 'QR decomposition for stable numerical computation.', hint: 'The transpose does the job of the inverse.' },
  { id: 54, topic: 'linear-algebra', difficulty: 'hard', question: 'The column space of A is:', options: ['Set of all possible Ax', 'The diagonal of A', 'The eigenvalues', 'The transpose'], correctIndex: 0, explanation: 'Column space is the span of all columns of A.', realWorld: 'Least-squares projects b onto the column space.', hint: 'What outputs can the matrix actually produce?' },
  { id: 55, topic: 'linear-algebra', difficulty: 'hard', question: 'If A has n distinct eigenvalues, A is:', options: ['Always singular', 'Diagonalizable', 'Always symmetric', 'Always orthogonal'], correctIndex: 1, explanation: 'Distinct eigenvalues guarantee diagonalizability.', realWorld: 'Speeds up matrix powers in Markov chains.', hint: 'Distinct eigenvalues ensure eigenvectors form a basis.' },
  { id: 56, topic: 'linear-algebra', difficulty: 'hard', question: 'The Frobenius norm ||A||_F is:', options: ['Max singular value', 'sqrt(sum of all A_ij²)', 'Sum of eigenvalues', 'Max row sum'], correctIndex: 1, explanation: 'Frobenius norm treats the matrix as a vector and takes L2 norm.', realWorld: 'Used as regularization for weight matrices.', hint: 'Square every entry, add them all up, take the square root.' },

  // ── Linear Algebra: SOTA ──
  { id: 4, topic: 'linear-algebra', difficulty: 'sota', question: 'In SVD, what are U and V?', options: ['Diagonal matrices', 'Orthogonal (unitary) matrices', 'Lower triangular matrices', 'Permutation matrices'], correctIndex: 1, explanation: 'U and V are orthogonal matrices of singular vectors.', realWorld: 'SVD powers recommendations and image compression.', hint: 'These matrices have the property that their transpose equals their inverse.' },
  { id: 28, topic: 'linear-algebra', difficulty: 'sota', question: 'Positive definite matrix guarantees:', options: ['A is diagonal', 'All eigenvalues positive', 'Rank 1', 'det(A) = 0'], correctIndex: 1, explanation: 'Positive definiteness = all eigenvalues strictly positive.', realWorld: 'Covariance matrices and Hessians of convex functions.', hint: 'What must be true about eigenvalues for the quadratic form to never go negative?' },
  { id: 30, topic: 'linear-algebra', difficulty: 'sota', question: 'The rank of A is:', options: ['Always min(m,n)', 'Number of linearly independent columns', 'Number of zero eigenvalues', 'Equal to m·n'], correctIndex: 1, explanation: 'Rank counts maximum linearly independent rows/columns.', realWorld: 'LoRA uses low-rank approximations for fine-tuning LLMs.', hint: 'Think about the dimension of the column space.' },
  { id: 57, topic: 'linear-algebra', difficulty: 'sota', question: 'Spectral theorem: real symmetric A decomposes as:', options: ['A = LU', 'A = QΛQ^T with orthogonal Q', 'A = A^T A', 'A = PD with permutation P'], correctIndex: 1, explanation: 'Symmetric matrices have real eigenvalues and orthogonal eigenvectors.', realWorld: 'Underpins PCA and spectral clustering.', hint: 'Symmetric matrices have a clean eigendecomposition with orthogonal eigenvectors.' },
  { id: 58, topic: 'linear-algebra', difficulty: 'sota', question: 'Condition number κ(A) measures:', options: ['Rank of A', 'Sensitivity of solutions to perturbations', 'Number of eigenvalues', 'Whether A is symmetric'], correctIndex: 1, explanation: 'Large condition number = ill-conditioned system.', realWorld: 'Ill-conditioned matrices cause numerical instability.', hint: 'Ratio of largest to smallest singular value.' },
  { id: 59, topic: 'linear-algebra', difficulty: 'sota', question: 'Moore-Penrose pseudoinverse A⁺:', options: ['A⁺ = A^T', 'Minimizes ||Ax-b|| with smallest ||x||', 'Does not exist', 'A⁺ = A^{-1}'], correctIndex: 1, explanation: 'Pseudoinverse gives minimum-norm least-squares solution.', realWorld: 'Used in robotics inverse kinematics and regression.', hint: 'Best approximate solution when exact inverse does not exist.' },
  { id: 60, topic: 'linear-algebra', difficulty: 'sota', question: 'Kronecker product A⊗B of m×n and p×q has size:', options: ['(m+p)×(n+q)', '(mp)×(nq)', 'm×q', 'max(m,p)×max(n,q)'], correctIndex: 1, explanation: 'Each entry of A gets replaced by a scaled copy of B.', realWorld: 'Used in quantum computing and multi-task learning.', hint: 'Each element of A becomes a scaled copy of the entire B matrix.' },
  { id: 61, topic: 'linear-algebra', difficulty: 'sota', question: 'Matrix exponential e^A solves:', options: ['Ax = b', 'dx/dt = Ax with x(t) = e^{At}x₀', 'det(A) = 0', 'A^T = A^{-1}'], correctIndex: 1, explanation: 'Matrix exponential solves linear ODEs.', realWorld: 'Used in neural ODEs and control theory.', hint: 'Generalizes scalar exponential to solve systems of differential equations.' },

  // ── Calculus: Easy ──
  { id: 6, topic: 'calculus', difficulty: 'easy', question: 'What does ∇f(x) represent?', options: ['The Hessian matrix', 'The gradient vector', 'The Jacobian matrix', 'The Laplacian'], correctIndex: 1, explanation: 'Gradient points in the direction of steepest ascent.', realWorld: 'Core of backpropagation in neural networks.', hint: 'It collects all partial derivatives into one vector pointing uphill.' },
  { id: 7, topic: 'calculus', difficulty: 'easy', question: 'What is d/dx[x^n]?', options: ['x^(n+1)/(n+1)', 'nx^(n-1)', 'n!', 'ln(x^n)'], correctIndex: 1, explanation: 'Power rule: differentiate x^n to get nx^(n-1).', realWorld: 'Used in polynomial regression and Taylor series.', hint: 'Bring the exponent down and reduce it by one.' },
  { id: 31, topic: 'calculus', difficulty: 'easy', question: 'What is d/dx[e^x]?', options: ['xe^(x-1)', 'e^x', 'ln(x)', 'e^(x+1)'], correctIndex: 1, explanation: 'e^x is its own derivative.', realWorld: 'Appears in softmax and logistic regression.', hint: 'This function is famously unchanged by differentiation.' },
  { id: 62, topic: 'calculus', difficulty: 'easy', question: 'What is d/dx[sin(x)]?', options: ['-cos(x)', 'cos(x)', 'sin(x)', 'tan(x)'], correctIndex: 1, explanation: 'Derivative of sin(x) is cos(x).', realWorld: 'Sinusoidal derivatives model oscillations in signal processing.', hint: 'Sine and cosine are derivatives of each other (with sign changes).' },
  { id: 63, topic: 'calculus', difficulty: 'easy', question: 'What is d/dx[ln(x)]?', options: ['e^x', '1/x', 'x ln(x)', 'ln(x)/x'], correctIndex: 1, explanation: 'Derivative of natural log is 1/x.', realWorld: 'Log-likelihood derivatives use this in statistical learning.', hint: 'The natural log has a beautifully simple derivative — just a reciprocal.' },
  { id: 64, topic: 'calculus', difficulty: 'easy', question: 'Antiderivative of 2x is:', options: ['2', 'x² + C', 'x²', '2x² + C'], correctIndex: 1, explanation: 'Reverse the power rule and add constant C.', realWorld: 'Integration computes areas and cumulative distributions.', hint: "Reverse the power rule and don't forget the constant." },
  { id: 65, topic: 'calculus', difficulty: 'easy', question: 'Continuity at x=a requires:', options: ['Derivative exists at a', 'lim f(x) = f(a)', 'Differentiable everywhere', 'f(a) = 0'], correctIndex: 1, explanation: 'Limit must exist and equal the function value.', realWorld: 'Continuity is needed for gradient-based optimization.', hint: 'The function value and the limit must agree at that point.' },
  { id: 66, topic: 'calculus', difficulty: 'easy', question: 'Product rule: d/dx[f(x)g(x)] = ?', options: ["f'g'", "f'g + fg'", "fg'", "[fg]'"], correctIndex: 1, explanation: "Product rule: (fg)' = f'g + fg'.", realWorld: 'Used in deriving loss functions involving products of probabilities.', hint: 'Each factor gets its turn to be differentiated while the other stays.' },

  // ── Calculus: Hard ──
  { id: 8, topic: 'calculus', difficulty: 'hard', question: 'Chain rule: if y = f(g(x)), dy/dx = ?', options: ["f'(x)·g'(x)", "f'(g(x))·g'(x)", "f(g'(x))", "f'(x)+g'(x)"], correctIndex: 1, explanation: 'Chain rule composes derivatives.', realWorld: 'Backpropagation IS the chain rule applied layer by layer.', hint: 'Differentiate the outer at the inner, then multiply by the inner derivative.' },
  { id: 10, topic: 'calculus', difficulty: 'hard', question: '∂/∂x[xy² + x²] = ?', options: ['2xy + 2x', 'y² + 2x', 'x² + 2xy', '2y + x'], correctIndex: 1, explanation: 'Treat y as constant when differentiating w.r.t. x.', realWorld: 'Partial derivatives compute gradients for multi-variable losses.', hint: 'Treat y as a constant and differentiate only with respect to x.' },
  { id: 32, topic: 'calculus', difficulty: 'hard', question: 'Definite integral ∫f(x)dx represents:', options: ['Slope of f', 'Signed area under f', 'Maximum of f', 'Derivative of f'], correctIndex: 1, explanation: 'Definite integral computes signed area.', realWorld: 'Used for probability and expected values.', hint: 'Think about the region between the curve and the horizontal axis.' },
  { id: 67, topic: 'calculus', difficulty: 'hard', question: "L'Hôpital's rule applies when limit has form:", options: ['∞ - ∞', '0/0 or ∞/∞', '0 · ∞', '1^∞'], correctIndex: 1, explanation: "When both go to same extreme, differentiate them both.", realWorld: 'Analyzes convergence rates of loss functions.', hint: 'When both numerator and denominator go to the same extreme, differentiate them both.' },
  { id: 68, topic: 'calculus', difficulty: 'hard', question: 'Fundamental Theorem of Calculus connects:', options: ['Limits and continuity', 'Differentiation and integration', 'Sequences and series', 'Vectors and scalars'], correctIndex: 1, explanation: 'Differentiation and integration are inverse operations.', realWorld: 'Enables computing exact areas and probabilities.', hint: 'These two fundamental operations of calculus undo each other.' },
  { id: 69, topic: 'calculus', difficulty: 'hard', question: 'Directional derivative D_u f gives:', options: ['Maximum rate of change', 'Rate of change of f in direction u', 'Second derivative', 'Integral along u'], correctIndex: 1, explanation: 'D_u f = ∇f · u, rate of change in direction u.', realWorld: 'Understanding how loss changes along specific parameter directions.', hint: 'Project the gradient onto a specific direction.' },
  { id: 70, topic: 'calculus', difficulty: 'hard', question: 'Integration by parts: ∫u dv = ?', options: ['u·v', 'uv - ∫v du', 'F(g(x))', '∫u dx + ∫v dx'], correctIndex: 1, explanation: 'Integration by parts reverses the product rule.', realWorld: 'Used in deriving ELBO in variational inference.', hint: 'It is the integral version of the product rule.' },
  { id: 71, topic: 'calculus', difficulty: 'hard', question: 'A critical point of f(x) occurs where:', options: ['f(x) = 0', "f'(x) = 0 or undefined", 'f(x) is maximum', "f''(x) = 0"], correctIndex: 1, explanation: 'Critical points are where derivative is zero or undefined.', realWorld: 'Optimization algorithms locate minima at critical points.', hint: 'The slope must be zero or not exist at these special points.' },

  // ── Calculus: SOTA ──
  { id: 9, topic: 'calculus', difficulty: 'sota', question: 'The Hessian H of f is:', options: ['Vector of first partial derivatives', 'Matrix of second partial derivatives', 'Determinant of Jacobian', 'Integral of gradient'], correctIndex: 1, explanation: 'Hessian captures curvature information.', realWorld: "Newton's method uses the Hessian.", hint: 'Go one derivative deeper than the gradient.' },
  { id: 23, topic: 'calculus', difficulty: 'sota', question: 'Jacobian matrix entries are:', options: ['J_ij = ∂f_i/∂x_j', 'J_ij = ∂²f/∂x_i∂x_j', 'J_ij = f_i·x_j', 'J_ij = δ_ij'], correctIndex: 0, explanation: 'Jacobian generalizes derivative to vector-valued functions.', realWorld: 'Used in robotics and normalizing flows.', hint: 'Each row is the gradient of one output component.' },
  { id: 33, topic: 'calculus', difficulty: 'sota', question: 'First-order Taylor approximation gives:', options: ['f(a)', "f(a) + f'(a)(x-a)", "f'(a)", 'f(a)·(x-a)'], correctIndex: 1, explanation: 'Linear approximation: tangent line at a.', realWorld: 'Linearizes complex functions in optimization.', hint: 'Keep only the constant and linear terms.' },
  { id: 72, topic: 'calculus', difficulty: 'sota', question: 'Laplacian ∇²f measures:', options: ['Gradient magnitude', 'Divergence of the gradient (net curvature)', 'Cross-partial derivatives', 'Integral of f'], correctIndex: 1, explanation: 'Laplacian is the trace of the Hessian.', realWorld: 'Used in heat equations and graph neural networks.', hint: 'Sum up the second derivatives along each axis.' },
  { id: 73, topic: 'calculus', difficulty: 'sota', question: 'Divergence theorem relates:', options: ['Line integrals to derivatives', 'Surface flux to volume integral of divergence', 'Gradient to Hessian', 'Eigenvalues to singular values'], correctIndex: 1, explanation: 'Connects local divergence to total flux through surface.', realWorld: 'Used in physics-informed neural networks.', hint: 'Total outflow through boundary equals integral of sources inside.' },
  { id: 74, topic: 'calculus', difficulty: 'sota', question: 'Automatic differentiation computes gradients by:', options: ['Symbolic simplification', 'Numerical finite differences', 'Applying chain rule to elementary operations', 'Random perturbations'], correctIndex: 2, explanation: 'AD applies chain rule exactly to elementary ops.', realWorld: 'PyTorch autograd and JAX use reverse-mode AD.', hint: 'Break computation into tiny steps and chain their derivatives.' },
  { id: 75, topic: 'calculus', difficulty: 'sota', question: 'Leibniz integral rule involves:', options: ['Only boundary terms', 'Boundary terms plus integral of ∂f/∂x', 'Just f(b(x))-f(a(x))', 'Hessian of f'], correctIndex: 1, explanation: 'Differentiates under integral sign with moving limits.', realWorld: 'Used in score functions for variational inference and RL.', hint: 'Handle both changing limits and integrand dependence on x.' },
  { id: 76, topic: 'calculus', difficulty: 'sota', question: 'A saddle point has:', options: ['All positive second derivatives', 'All negative second derivatives', 'Hessian with both positive and negative eigenvalues', 'Zero gradient and zero Hessian'], correctIndex: 2, explanation: 'Saddle point: function curves up in some directions, down in others.', realWorld: 'More common than local minima in deep learning loss landscapes.', hint: 'Looks like a minimum along one axis but a maximum along another.' },

  // ── Probability & Stats: Easy ──
  { id: 11, topic: 'probability-stats', difficulty: 'easy', question: "Bayes' theorem: P(A|B) = ?", options: ['P(B|A)·P(A)', 'P(B|A)P(A)/P(B)', 'P(A)+P(B)', 'P(A∩B)'], correctIndex: 1, explanation: "Inverts conditional probabilities.", realWorld: 'Powers spam filters and medical diagnosis.', hint: 'You need the prior, likelihood, and evidence in the denominator.' },
  { id: 12, topic: 'probability-stats', difficulty: 'easy', question: 'Expected value E[X] is:', options: ['Most likely outcome', 'Weighted average over all outcomes', 'Median', 'Maximum probability'], correctIndex: 1, explanation: 'Probability-weighted average.', realWorld: 'Used in A/B testing and RL.', hint: 'Weight each outcome by how likely it is, then sum.' },
  { id: 34, topic: 'probability-stats', difficulty: 'easy', question: 'If X,Y independent, P(X,Y) = ?', options: ['P(X)+P(Y)', 'P(X)·P(Y)', 'P(X|Y)', 'P(X)/P(Y)'], correctIndex: 1, explanation: 'Independence means joint probability factors.', realWorld: 'Naive Bayes assumes this.', hint: 'Knowing one tells you nothing about the other.' },
  { id: 77, topic: 'probability-stats', difficulty: 'easy', question: 'P(A) must satisfy:', options: ['-1 ≤ P(A) ≤ 1', '0 ≤ P(A) ≤ 1', 'P(A) > 0', 'P(A) = P(Aᶜ)'], correctIndex: 1, explanation: 'Probabilities are between 0 and 1.', realWorld: 'Softmax and sigmoid ensure valid probability outputs.', hint: 'Probability can never be negative or greater than certainty.' },
  { id: 78, topic: 'probability-stats', difficulty: 'easy', question: 'Complement rule: P(Aᶜ) = ?', options: ['P(A)', '1 - P(A)', 'P(A)²', '1/P(A)'], correctIndex: 1, explanation: 'Probability of not happening is 1 minus the probability it does.', realWorld: 'Computing probability of at least one success.', hint: 'Total probability must sum to 1.' },
  { id: 79, topic: 'probability-stats', difficulty: 'easy', question: 'The median is:', options: ['Most frequent value', 'Value splitting distribution in half', 'Average of all values', 'Range / 2'], correctIndex: 1, explanation: 'Median is the 50th percentile.', realWorld: 'Robust to outliers — median income vs mean income.', hint: 'The middle value that divides the distribution into equal halves.' },
  { id: 80, topic: 'probability-stats', difficulty: 'easy', question: 'Uniform distribution on [a,b] means:', options: ['All outcomes equally likely', 'Clusters near mean', 'Variance is zero', 'Only a and b possible'], correctIndex: 0, explanation: 'Every value in [a,b] has equal density.', realWorld: 'Random number generators start with uniform distributions.', hint: 'The density is flat — no region more likely than another.' },
  { id: 81, topic: 'probability-stats', difficulty: 'easy', question: 'Standard deviation σ is:', options: ['Square of variance', 'Square root of variance', 'Mean of absolute deviations', 'Range of data'], correctIndex: 1, explanation: 'σ = √Var(X), spread in same units as data.', realWorld: 'Used in z-scores and batch normalization.', hint: 'Take the variance and undo the squaring.' },

  // ── Probability & Stats: Hard ──
  { id: 13, topic: 'probability-stats', difficulty: 'hard', question: 'Variance σ² measures:', options: ['Central tendency', 'Spread of distribution', 'Skewness', 'Correlation'], correctIndex: 1, explanation: 'Quantifies spread from the mean.', realWorld: 'Critical for risk modeling in finance.', hint: 'How far do values typically wander from the center?' },
  { id: 14, topic: 'probability-stats', difficulty: 'hard', question: 'Gaussian N(μ,σ²) defined by:', options: ['Mean and mode', 'Mean μ and variance σ²', 'Median and range', 'Rate λ'], correctIndex: 1, explanation: 'Fully characterized by mean and variance.', realWorld: 'Used in GANs and VAEs.', hint: 'Bell curve needs two parameters: center and width.' },
  { id: 35, topic: 'probability-stats', difficulty: 'hard', question: 'CLT: sample means converge to:', options: ['Uniform', 'Poisson', 'Normal distribution', 'Population median'], correctIndex: 2, explanation: 'Sample means become approximately normal.', realWorld: 'Justifies confidence intervals.', hint: 'Average enough samples and a bell shape emerges.' },
  { id: 82, topic: 'probability-stats', difficulty: 'hard', question: 'Cov(X,Y) > 0 indicates:', options: ['Independent', 'Tend to increase together', 'X causes Y', 'Same distribution'], correctIndex: 1, explanation: 'Positive covariance: both go up together. Not causation.', realWorld: 'Covariance matrices central to PCA and finance.', hint: 'When one goes up, the other tends to follow.' },
  { id: 83, topic: 'probability-stats', difficulty: 'hard', question: 'Law of large numbers: as n→∞:', options: ['Variance → ∞', 'Sample mean → population mean', 'All outcomes equally likely', 'Distribution becomes uniform'], correctIndex: 1, explanation: 'Sample mean converges to E[X].', realWorld: 'Justifies Monte Carlo methods.', hint: 'More data means the average gets closer to the true value.' },
  { id: 84, topic: 'probability-stats', difficulty: 'hard', question: 'Bernoulli X ~ Bern(p) takes values:', options: ['Any real number', '0 or 1 with P(X=1)=p', 'Integers 0 to n', 'Only positive'], correctIndex: 1, explanation: 'Binary outcome: success (1) or failure (0).', realWorld: 'Models clicks, coin flips, binary classification.', hint: 'The simplest random variable — success or failure.' },
  { id: 85, topic: 'probability-stats', difficulty: 'hard', question: 'Correlation ρ ranges between:', options: ['0 and 1', '-1 and 1', '-∞ and ∞', '0 and ∞'], correctIndex: 1, explanation: 'ρ normalizes covariance to [-1,1]. ±1 = perfect linear.', realWorld: 'Feature correlation guides feature selection.', hint: 'Normalized covariance with fixed bounds.' },
  { id: 86, topic: 'probability-stats', difficulty: 'hard', question: 'Poisson distribution models:', options: ['Continuous measurements', 'Count of events in fixed interval', 'Sample mean', 'Time between events'], correctIndex: 1, explanation: 'Counts events occurring at rate λ.', realWorld: 'Models website visits, server requests.', hint: 'Counts how many times something happens in a fixed window.' },

  // ── Probability & Stats: SOTA ──
  { id: 15, topic: 'probability-stats', difficulty: 'sota', question: 'p-value of 0.03 means:', options: ['3% chance alt is true', '97% accurate', 'Under H₀, this extreme occurs 3%', 'Effect size 0.03'], correctIndex: 2, explanation: 'Probability of this extreme data assuming null.', realWorld: 'Guides clinical trials and A/B tests.', hint: 'Assume null is true — how surprising is this?' },
  { id: 25, topic: 'probability-stats', difficulty: 'sota', question: 'KL divergence measures:', options: ['Distance between points', 'How much P differs from Q', 'Correlation', 'Entropy of P'], correctIndex: 1, explanation: 'Information lost when approximating P with Q.', realWorld: 'Loss in VAEs and policy gradient RL.', hint: 'Information cost of using Q to approximate P.' },
  { id: 36, topic: 'probability-stats', difficulty: 'sota', question: 'MLE finds θ that:', options: ['Minimize prior', 'Maximize P(data|θ)', 'Minimize entropy', 'Maximize p-value'], correctIndex: 1, explanation: 'Selects θ making observed data most probable.', realWorld: 'Trains logistic regression and GMMs.', hint: 'Which parameters make the data most likely?' },
  { id: 87, topic: 'probability-stats', difficulty: 'sota', question: 'Entropy H(X) maximized when:', options: ['X deterministic', 'X uniform over all outcomes', 'P(x)=1 for one', 'Variance is zero'], correctIndex: 1, explanation: 'Maximum entropy = uniform = maximum uncertainty.', realWorld: 'Maximum entropy principle in NLP.', hint: 'Most uncertain distribution has no preference.' },
  { id: 88, topic: 'probability-stats', difficulty: 'sota', question: 'MAP differs from MLE by:', options: ['Different loss', 'Incorporating prior P(θ)', 'Not using likelihood', 'Requiring more data'], correctIndex: 1, explanation: 'MAP includes prior as regularization.', realWorld: 'MAP + Gaussian prior = L2 regularization.', hint: 'Adds prior beliefs about parameters to likelihood.' },
  { id: 89, topic: 'probability-stats', difficulty: 'sota', question: 'Mutual information I(X;Y) measures:', options: ['Linear correlation only', 'Shared information between X and Y', 'Causal effect', 'Joint entropy'], correctIndex: 1, explanation: 'Captures all dependencies, not just linear.', realWorld: 'Feature selection and information bottleneck.', hint: 'How much does knowing Y reduce uncertainty about X?' },
  { id: 90, topic: 'probability-stats', difficulty: 'sota', question: 'Conjugate prior means:', options: ['Prior = posterior', 'Posterior same family as prior', 'Prior always uniform', 'Likelihood is Gaussian'], correctIndex: 1, explanation: 'Same functional form for prior and posterior.', realWorld: 'Beta-Binomial and Normal-Normal in A/B testing.', hint: 'Prior and posterior are from the same family.' },
  { id: 91, topic: 'probability-stats', difficulty: 'sota', question: 'Cramér-Rao bound: estimator variance ≥:', options: ['Zero', '1/I(θ) (Fisher information)', 'Population variance', '1/n'], correctIndex: 1, explanation: 'Fundamental limit on estimation precision.', realWorld: 'Guides efficient estimator design.', hint: 'There is a fundamental limit on how precisely you can estimate.' },

  // ── Optimization: Easy ──
  { id: 16, topic: 'optimization', difficulty: 'easy', question: 'In gradient descent, what is η?', options: ['Loss function', 'Learning rate', 'Momentum', 'Weight decay'], correctIndex: 1, explanation: 'Learning rate controls step size.', realWorld: 'Most important hyperparameter.', hint: 'This Greek letter controls how big each step is.' },
  { id: 24, topic: 'optimization', difficulty: 'easy', question: 'Loss function L(θ) measures:', options: ['Model complexity', 'How wrong predictions are', 'Parameter count', 'Training speed'], correctIndex: 1, explanation: 'Loss quantifies prediction error.', realWorld: 'MSE for regression, cross-entropy for classification.', hint: 'How far off predictions are from truth.' },
  { id: 37, topic: 'optimization', difficulty: 'easy', question: 'Overfitting is:', options: ['Model too simple', 'Memorizes training, fails on new', 'Converges quickly', 'Too few parameters'], correctIndex: 1, explanation: 'Captures noise instead of pattern.', realWorld: 'Dropout and regularization combat this.', hint: 'Great at training data but terrible at anything new.' },
  { id: 92, topic: 'optimization', difficulty: 'easy', question: 'Underfitting is:', options: ['Model too complex', 'Too simple to capture pattern', 'Trains too long', 'Too many parameters'], correctIndex: 1, explanation: 'Model lacks capacity — high bias, low variance.', realWorld: 'Linear model on nonlinear data.', hint: 'Not expressive enough to learn even training data.' },
  { id: 93, topic: 'optimization', difficulty: 'easy', question: 'A hyperparameter is:', options: ['Learned during training', 'Chosen before training', 'Final output', 'Loss value'], correctIndex: 1, explanation: 'Set before training to control learning process.', realWorld: 'Tuned via grid search or Bayesian optimization.', hint: 'Decided by the practitioner, not learned from data.' },
  { id: 94, topic: 'optimization', difficulty: 'easy', question: 'Early stopping halts when:', options: ['Training loss = 0', 'Validation loss increases', 'All parameters converge', 'Learning rate = 0'], correctIndex: 1, explanation: 'Stops when validation degrades — regularization.', realWorld: 'Used in virtually all practical deep learning.', hint: 'Stop when model gets worse on held-out data.' },
  { id: 95, topic: 'optimization', difficulty: 'easy', question: 'Train/val/test split is for:', options: ['Speed up training', 'Evaluate generalization and tune hyperparameters', 'Reduce dataset', 'Balance classes'], correctIndex: 1, explanation: 'Train fits, val tunes, test gives final evaluation.', realWorld: 'Standard 80/10/10 splits everywhere.', hint: 'Each subset has a different role.' },
  { id: 96, topic: 'optimization', difficulty: 'easy', question: 'Batch size is:', options: ['Total epochs', 'Samples per gradient update', 'Number of layers', 'Test set size'], correctIndex: 1, explanation: 'How many samples per gradient estimate.', realWorld: 'Larger = more stable; smaller = can escape local minima.', hint: 'How many examples before one optimization step?' },

  // ── Optimization: Hard ──
  { id: 17, topic: 'optimization', difficulty: 'hard', question: 'Adam advantage over SGD:', options: ['Second-order derivatives', 'Adapts learning rates per-parameter', 'Guarantees global convergence', 'No loss function needed'], correctIndex: 1, explanation: 'Adam uses momentum estimates for adaptive rates.', realWorld: 'Default optimizer in most DL frameworks.', hint: 'Tracks average gradient and variance per parameter.' },
  { id: 38, topic: 'optimization', difficulty: 'hard', question: 'L1 regularization encourages:', options: ['Large weights', 'Sparse weights (many zeros)', 'Uniform weights', 'Complex models'], correctIndex: 1, explanation: 'L1 drives small weights to zero.', realWorld: 'Lasso for feature selection.', hint: 'Diamond-shaped constraint pushes weights to axes.' },
  { id: 39, topic: 'optimization', difficulty: 'hard', question: 'SGD differs from batch GD by:', options: ['Using full dataset', 'Using random mini-batch', 'No gradients', 'Only convex functions'], correctIndex: 1, explanation: 'SGD approximates gradient with mini-batch.', realWorld: 'All modern DL uses mini-batch SGD.', hint: 'Use a random sample instead of all data.' },
  { id: 97, topic: 'optimization', difficulty: 'hard', question: 'L2 regularization is equivalent to:', options: ['Adding noise', 'Gaussian prior on weights', 'Pruning', 'Reducing learning rate'], correctIndex: 1, explanation: 'L2 = weight decay = Gaussian prior on weights.', realWorld: 'Ridge regression and weight decay in Adam.', hint: 'Bayesian view: weights drawn from bell curve at zero.' },
  { id: 98, topic: 'optimization', difficulty: 'hard', question: 'Momentum helps by:', options: ['Reducing learning rate', 'Accumulating past gradients to accelerate', 'Eliminating loss', 'Making model deeper'], correctIndex: 1, explanation: 'Adds fraction of previous update for faster convergence.', realWorld: 'SGD with momentum β=0.9 is standard.', hint: 'Ball rolling downhill builds speed from previous movement.' },
  { id: 99, topic: 'optimization', difficulty: 'hard', question: 'Dropout during training:', options: ['Removes layers', 'Randomly zeroes outputs to prevent co-adaptation', 'Increases learning rate', 'Reduces dataset'], correctIndex: 1, explanation: 'Forces redundant representations.', realWorld: 'Breakthrough regularization technique.', hint: 'Randomly turning off neurons forces distributed learning.' },
  { id: 100, topic: 'optimization', difficulty: 'hard', question: 'Learning rate scheduling:', options: ['Keeps LR constant', 'Changes LR during training', 'Eliminates LR', 'Only for Adam'], correctIndex: 1, explanation: 'Cosine annealing, step decay adjust LR over time.', realWorld: 'Standard in transformer training.', hint: 'Start high and gradually reduce.' },
  { id: 101, topic: 'optimization', difficulty: 'hard', question: 'Batch normalization normalizes to:', options: ['Mean 0, variance 1 per mini-batch', 'All positive values', 'Remove gradients', 'Double batch size'], correctIndex: 0, explanation: 'Standardizes layer inputs, reducing covariate shift.', realWorld: 'Standard in CNNs like ResNet.', hint: 'Center and scale activations for nice statistical properties.' },

  // ── Optimization: SOTA ──
  { id: 18, topic: 'optimization', difficulty: 'sota', question: 'Convex loss guarantees:', options: ['Multiple local minima', 'No gradient', 'Local min = global min', 'Hessian always zero'], correctIndex: 2, explanation: 'Convexity: no valleys to get trapped in.', realWorld: 'Logistic regression and SVMs are convex.', hint: 'If the bowl only curves one way, only one bottom.' },
  { id: 40, topic: 'optimization', difficulty: 'sota', question: 'Vanishing gradient problem:', options: ['LR too high', 'Gradients → 0 through layers', 'Loss is convex', 'Too few parameters'], correctIndex: 1, explanation: 'Gradients shrink exponentially through layers.', realWorld: 'ReLU and ResNets solve this.', hint: 'Multiplying small numbers makes signal disappear.' },
  { id: 41, topic: 'optimization', difficulty: 'sota', question: 'Cross-entropy preferred because:', options: ['Always convex', 'Penalizes confident wrong predictions heavily', 'No hyperparameters', 'Only two classes'], correctIndex: 1, explanation: 'Small predicted probability = large loss and gradient.', realWorld: 'Standard classification loss.', hint: 'Being confidently wrong is punished much more.' },
  { id: 102, topic: 'optimization', difficulty: 'sota', question: 'Bias-variance tradeoff: total error =', options: ['Train + test error', 'Bias² + variance + noise', 'Gradient + Hessian', 'Precision + recall'], correctIndex: 1, explanation: 'High bias = underfit, high variance = overfit.', realWorld: 'Guides model complexity decisions.', hint: 'Simple models: high bias. Complex models: high variance.' },
  { id: 103, topic: 'optimization', difficulty: 'sota', question: 'Gradient clipping prevents:', options: ['Underfitting', 'Exploding gradients by capping norm', 'Vanishing gradients', 'Overfitting'], correctIndex: 1, explanation: 'Rescales gradient when norm exceeds threshold.', realWorld: 'Essential for RNNs and transformers.', hint: 'If gradient too large, scale it down.' },
  { id: 104, topic: 'optimization', difficulty: 'sota', question: 'Knowledge distillation:', options: ['Prunes weights', 'Student learns from teacher output distribution', 'Uses less data', 'Reduces LR'], correctIndex: 1, explanation: 'Student learns soft targets from teacher.', realWorld: 'DistilBERT and TinyML.', hint: 'Large teacher shares knowledge with small student.' },
  { id: 105, topic: 'optimization', difficulty: 'sota', question: 'Lottery ticket hypothesis:', options: ['Larger = better', 'Dense nets contain sparse subnetworks that train well', 'Init irrelevant', 'Pruning hurts'], correctIndex: 1, explanation: 'Winning tickets match full network performance.', realWorld: 'Inspires pruning strategies.', hint: 'Small network hidden inside the large one.' },
  { id: 106, topic: 'optimization', difficulty: 'sota', question: 'Mixed-precision training uses:', options: ['Only 64-bit', 'Both 16-bit and 32-bit floats', 'Integer only', 'No precision'], correctIndex: 1, explanation: 'FP16 for speed with FP32 master weights for stability.', realWorld: 'Standard on NVIDIA Tensor Cores.', hint: 'Lower precision where possible, higher where needed.' },

  // ── Discrete Math: Easy ──
  { id: 19, topic: 'discrete-math', difficulty: 'easy', question: 'O(n²) means:', options: ['Exactly n² steps', 'Runtime grows at most quadratically', 'Uses n² memory', 'Fastest possible'], correctIndex: 1, explanation: 'Big-O describes upper bound on growth.', realWorld: 'O(n log n) vs O(n²) matters hugely.', hint: 'Upper bound on growth rate, not exact count.' },
  { id: 42, topic: 'discrete-math', difficulty: 'easy', question: 'Hash function used for:', options: ['Sorting', 'Mapping to fixed-size values for fast lookup', 'Encrypting only', 'Compressing images'], correctIndex: 1, explanation: 'Enables O(1) lookups.', realWorld: 'Python dicts and database indexing.', hint: 'Fixed-size fingerprint for quick retrieval.' },
  { id: 44, topic: 'discrete-math', difficulty: 'easy', question: 'Binary search runs in:', options: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'], correctIndex: 2, explanation: 'Halves search space each step.', realWorld: 'Database queries and hyperparameter tuning.', hint: 'Each comparison eliminates half.' },
  { id: 107, topic: 'discrete-math', difficulty: 'easy', question: 'Stack follows:', options: ['FIFO', 'LIFO', 'Random access', 'Priority'], correctIndex: 1, explanation: 'Last-In, First-Out like a stack of plates.', realWorld: 'Call stacks, undo operations, expression parsing.', hint: 'Most recently added is first removed.' },
  { id: 108, topic: 'discrete-math', difficulty: 'easy', question: 'Queue follows:', options: ['LIFO', 'FIFO', 'Sorted', 'Random'], correctIndex: 1, explanation: 'First-In, First-Out like a line at a store.', realWorld: 'BFS, task queues, message brokers.', hint: 'First to arrive, first served.' },
  { id: 109, topic: 'discrete-math', difficulty: 'easy', question: 'A tree is:', options: ['Linked list', 'Graph', 'Acyclic connected graph', 'Hash table'], correctIndex: 2, explanation: 'Connected graph with no cycles and n-1 edges.', realWorld: 'Decision trees, file systems, DOM.', hint: 'No loops — one path from root to each node.' },
  { id: 110, topic: 'discrete-math', difficulty: 'easy', question: 'AND (∧) returns true when:', options: ['At least one true', 'Both true', 'Both false', 'Inputs differ'], correctIndex: 1, explanation: 'All inputs must be true.', realWorld: 'Logic gates in circuits and programming.', hint: 'Every input must be true.' },
  { id: 111, topic: 'discrete-math', difficulty: 'easy', question: 'Array provides O(1) access by:', options: ['Sorting first', 'Hash function', 'Direct indexing with offset', 'Binary search'], correctIndex: 2, explanation: 'Contiguous memory: base + i × size.', realWorld: 'NumPy and GPU tensors rely on this.', hint: 'Jump directly to memory location by position.' },

  // ── Discrete Math: Hard ──
  { id: 20, topic: 'discrete-math', difficulty: 'hard', question: 'Shannon entropy measures:', options: ['Energy', 'Information/uncertainty', 'Compression ratio', 'Temperature'], correctIndex: 1, explanation: 'Average surprise in a random variable.', realWorld: 'Decision trees and data compression.', hint: 'More uncertainty = higher information content.' },
  { id: 21, topic: 'discrete-math', difficulty: 'hard', question: 'Tensor X_{i,j,k} is:', options: ['Scalar', '2D matrix', 'Multi-dimensional array', 'Vector'], correctIndex: 2, explanation: 'Tensors generalize scalars, vectors, matrices.', realWorld: 'PyTorch and TensorFlow use tensors for everything.', hint: 'Matrix with more than two index dimensions.' },
  { id: 43, topic: 'discrete-math', difficulty: 'hard', question: 'Softmax converts logits to:', options: ['Binary values', 'Probability distribution summing to 1', 'Negative values', 'Integer labels'], correctIndex: 1, explanation: 'Produces valid probabilities that sum to 1.', realWorld: 'Classification output and attention mechanisms.', hint: 'Exponentiate and normalize to sum to one.' },
  { id: 46, topic: 'discrete-math', difficulty: 'hard', question: 'Dynamic programming solves by:', options: ['Random sampling', 'Overlapping subproblems + caching', 'Brute force', 'Gradient descent'], correctIndex: 1, explanation: 'Solve each subproblem once, cache results.', realWorld: 'Viterbi algorithm and sequence alignment.', hint: 'Solve once, store, reuse.' },
  { id: 112, topic: 'discrete-math', difficulty: 'hard', question: 'BFS explores graph:', options: ['Deepest first', 'Level by level from source', 'Random', 'By edge weight'], correctIndex: 1, explanation: 'Queue-based, explores all neighbors at distance d before d+1.', realWorld: 'Friend suggestions and shortest paths.', hint: 'Explore all immediate neighbors before going deeper.' },
  { id: 113, topic: 'discrete-math', difficulty: 'hard', question: 'Merge sort time complexity:', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], correctIndex: 1, explanation: 'Divide in half recursively, merge in O(n).', realWorld: 'External sorting and TimSort in Python.', hint: 'Log n levels of division, n work per level.' },
  { id: 114, topic: 'discrete-math', difficulty: 'hard', question: 'BST property:', options: ['All nodes have 2 children', 'Left < parent < right', 'All leaves same depth', 'Always balanced'], correctIndex: 1, explanation: 'Left subtree smaller, right subtree larger.', realWorld: 'Database indexes with balanced variants.', hint: 'Smaller left, larger right.' },
  { id: 115, topic: 'discrete-math', difficulty: 'hard', question: 'Pigeonhole principle: n items in m containers, n>m:', options: ['All empty', 'At least one has more than one', 'Evenly distributed', 'No overflow'], correctIndex: 1, explanation: 'More pigeons than holes = at least one shared.', realWorld: 'Hash collision inevitability and birthday paradox.', hint: 'More items than slots means sharing.' },

  // ── Discrete Math: SOTA ──
  { id: 22, topic: 'discrete-math', difficulty: 'sota', question: 'Adjacency matrix A_ij=1 if:', options: ['Node i has degree j', 'Edge between i and j', 'Shortest path is 1', 'Same color'], correctIndex: 1, explanation: 'Encodes graph connectivity.', realWorld: 'GNNs for social networks and molecules.', hint: 'Entry is 1 when direct connection exists.' },
  { id: 45, topic: 'discrete-math', difficulty: 'sota', question: 'Why divide by √d_k in attention?', options: ['Normalize output', 'Prevent softmax saturation', 'Reduce computation', 'Make Q,K orthogonal'], correctIndex: 1, explanation: 'Large d_k makes dot products large, saturating softmax.', realWorld: 'Foundation of all modern transformers.', hint: 'Scaling keeps gradients healthy.' },
  { id: 47, topic: 'discrete-math', difficulty: 'sota', question: 'Graph Laplacian L = D - A used for:', options: ['Image compression', 'Spectral clustering and partitioning', 'Sorting', 'Matrix inversion'], correctIndex: 1, explanation: "Eigenvalues reveal graph connectivity.", realWorld: 'Spectral clustering and GNNs.', hint: 'Eigenvalues of this matrix reveal graph structure.' },
  { id: 116, topic: 'discrete-math', difficulty: 'sota', question: 'NP-completeness means:', options: ['Cannot be solved', 'Verifiable in poly time, hardest in NP', 'Only exponential algorithms', 'Unsolvable'], correctIndex: 1, explanation: 'Hardest in NP — if one solved in poly time, all can.', realWorld: 'TSP and SAT use heuristics in practice.', hint: 'Easy to verify, hard to find.' },
  { id: 117, topic: 'discrete-math', difficulty: 'sota', question: 'Master theorem compares:', options: ['a and b only', 'f(n) with n^(log_b a)', 'Base case with f(n)', 'T(n) with T(n-1)'], correctIndex: 1, explanation: 'Compares work per level with number of subproblems.', realWorld: 'Analyzes divide-and-conquer algorithms.', hint: 'Compare dividing cost with shrinking speed.' },
  { id: 118, topic: 'discrete-math', difficulty: 'sota', question: 'GNN message passing:', options: ['Sort by degree', 'Aggregate neighbor features to update nodes', 'Remove edges randomly', 'Grid convolutions'], correctIndex: 1, explanation: 'Each node gathers from neighbors and updates.', realWorld: 'Drug discovery and recommendations.', hint: 'Each node collects info from neighbors.' },
  { id: 119, topic: 'discrete-math', difficulty: 'sota', question: 'Amortized analysis shows:', options: ['Every op O(1)', 'Average cost per op is low despite some expensive ones', 'Worst = best case', 'Space is constant'], correctIndex: 1, explanation: 'Expensive ops rare enough that average stays low.', realWorld: 'Hash table resizing and Python list appends.', hint: 'Expensive operations are rare enough.' },
  { id: 120, topic: 'discrete-math', difficulty: 'sota', question: 'FFT computes DFT in:', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(2^n)'], correctIndex: 1, explanation: 'Exploits symmetry to reduce O(n²) to O(n log n).', realWorld: 'Signal processing and polynomial multiplication.', hint: 'Divide into even/odd indices, solve recursively.' },
];

/** Strip answer data for client delivery */
export type PublicQuestion = Omit<Question, 'correctIndex' | 'explanation' | 'realWorld'>;

export function sanitize(q: Question): PublicQuestion {
  const { correctIndex, explanation, realWorld, ...pub } = q;
  return pub;
}
