import type { Question } from '../types';

export const creditRiskQuestions: Question[] = [
  {
    id: 185001, topic: 'credit-risk', difficulty: 'easy',
    question: 'Credit risk is the risk that:',
    options: ['A borrower fails to meet debt obligations (default)', 'Interest rates rise', 'The stock market crashes', 'Inflation erodes returns'],
    correctIndex: 0,
    explanation: 'Credit risk (default risk) is the possibility that a counterparty will not fulfill their contractual payment obligations.',
    realWorld: 'The 2008 financial crisis was fundamentally a credit risk event — subprime borrowers defaulting on mortgages.',
    hint: 'Will they pay you back? That\'s credit risk.',
  },
  {
    id: 185002, topic: 'credit-risk', difficulty: 'easy',
    question: 'A credit default swap (CDS) provides:',
    options: ['Insurance against default — the buyer pays a premium and receives payment if the reference entity defaults', 'Leverage for equity trading', 'Guaranteed returns', 'Currency hedging'],
    correctIndex: 0,
    explanation: 'A CDS is like insurance: the protection buyer pays periodic premiums; if the reference entity defaults, the protection seller pays the loss amount.',
    realWorld: 'CDS spreads on US Treasury debt are watched as a barometer of sovereign credit risk.',
    hint: 'Think of it as default insurance — premium in, payout if default occurs.',
  },
  {
    id: 185003, topic: 'credit-risk', difficulty: 'easy',
    question: 'The probability of default (PD) is typically estimated using:',
    options: ['Credit ratings, financial ratios, and statistical models', 'Stock price only', 'The company\'s marketing budget', 'Employee count'],
    correctIndex: 0,
    explanation: 'PD estimation combines fundamental analysis (leverage, coverage ratios), market signals (CDS spreads, equity volatility), and statistical models (logistic regression, ML).',
    realWorld: 'Banks use PD estimates for loan pricing, regulatory capital (Basel III), and loss provisioning.',
    hint: 'How likely is a borrower to default? PD quantifies that probability.',
  },
  {
    id: 185004, topic: 'credit-risk', difficulty: 'hard',
    question: 'The Merton structural model treats a firm\'s equity as:',
    options: ['A call option on the firm\'s assets with strike equal to the face value of debt', 'A put option on bonds', 'A futures contract', 'A risk-free asset'],
    correctIndex: 0,
    explanation: 'Merton (1974): equity = $\\max(V_T - D, 0)$ where $V_T$ is asset value and $D$ is debt face value. Shareholders exercise their "call option" by paying off debt; if $V_T < D$, they default.',
    realWorld: 'Moody\'s KMV model, used globally for credit risk, is based on Merton\'s framework.',
    hint: 'Equity holders have limited liability — their downside is zero (like a call option).',
  },
  {
    id: 185005, topic: 'credit-risk', difficulty: 'hard',
    question: 'Loss Given Default (LGD) depends primarily on:',
    options: ['Seniority of the claim, collateral, and recovery process', 'The borrower\'s revenue', 'Current interest rates', 'Market volatility'],
    correctIndex: 0,
    explanation: 'LGD = 1 - Recovery Rate. Senior secured debt typically has LGD ~35-40%; subordinated unsecured debt has LGD ~70-80%. Collateral quality is the biggest driver.',
    realWorld: 'Expected Loss = PD × LGD × EAD — all three components matter for Basel III capital requirements.',
    hint: 'How much do you lose if they default? It depends on what you can recover.',
  },
  {
    id: 185006, topic: 'credit-risk', difficulty: 'hard',
    question: 'The Gaussian copula model for CDO pricing is criticized because:',
    options: ['It assumes a constant default correlation and underestimates tail dependence', 'It overestimates risk', 'It is too computationally expensive', 'It only works for single-name CDS'],
    correctIndex: 0,
    explanation: 'Li\'s Gaussian copula (2000) assumes normal dependence between defaults, missing the fat-tailed joint behavior seen in crises. This led to catastrophic mispricing of CDO tranches pre-2008.',
    realWorld: 'The Gaussian copula was called "the formula that killed Wall Street" — it enabled toxic CDO underpricing.',
    hint: 'In a crisis, everything defaults together — Gaussian copulas can\'t capture that.',
  },
  {
    id: 185007, topic: 'credit-risk', difficulty: 'sota',
    question: 'XVA (Valuation Adjustments) in modern derivatives pricing includes CVA, DVA, FVA, and MVA. CVA specifically accounts for:',
    options: ['The expected loss from counterparty default — an adjustment to the risk-free price', 'The firm\'s own credit risk', 'Funding costs', 'Initial margin requirements'],
    correctIndex: 0,
    explanation: 'CVA = $\\int_0^T \\text{LGD} \\cdot \\text{PD}(t) \\cdot \\text{EE}(t)\\,dt$ where EE is expected exposure. It is now a mandatory capital charge under Basel III.',
    realWorld: 'Major banks have dedicated XVA desks managing billions in valuation adjustments.',
    hint: 'CVA = Credit Valuation Adjustment — the market price of counterparty credit risk.',
  },
  {
    id: 185008, topic: 'credit-risk', difficulty: 'sota',
    question: 'Machine learning approaches to credit scoring (e.g., XGBoost, neural networks) improve upon logistic regression by:',
    options: ['Capturing non-linear feature interactions and handling missing data more robustly', 'Always being more interpretable', 'Requiring less data', 'Being regulation-free'],
    correctIndex: 0,
    explanation: 'ML models capture complex non-linear relationships between features (income × debt × employment history interactions) that linear models miss. XGBoost typically improves AUC by 2-5% over logistic regression.',
    realWorld: 'LendingClub, Upstart, and major banks use ML credit models — but face regulatory scrutiny on explainability.',
    hint: 'ML excels at finding patterns humans and linear models miss — but at the cost of interpretability.',
  },
  {
    id: 185009, topic: 'credit-risk', difficulty: 'sota',
    question: 'The IFRS 9 expected credit loss (ECL) framework requires banks to:',
    options: ['Recognize expected losses upfront using a three-stage model based on credit deterioration', 'Only recognize losses after default occurs', 'Ignore future credit risk', 'Use historical averages only'],
    correctIndex: 0,
    explanation: 'IFRS 9 replaced IAS 39\'s "incurred loss" model: Stage 1 (performing) recognizes 12-month ECL; Stage 2 (significant deterioration) and Stage 3 (default) recognize lifetime ECL.',
    realWorld: 'IFRS 9 forced banks to front-load massive provisions during COVID-19, absorbing expected losses earlier.',
    hint: 'Don\'t wait for default — recognize expected losses from Day 1.',
  },
];
