import type { Question } from '../types';

export const hardQuestions: Question[] = [
  {
    id: 17,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'What advantage does Adam optimizer have over vanilla SGD?',
    options: ['It uses second-order derivatives', 'It adapts learning rates per-parameter using momentum estimates', 'It guarantees global convergence', 'It eliminates the need for a loss function'],
    correctIndex: 1,
    explanation: 'Adam combines first moment (mean) and second moment (variance) estimates of the gradient for adaptive per-parameter learning rates.',
    realWorld: 'Adam is the default optimizer in most deep learning frameworks (PyTorch, TensorFlow).',
    hint: 'It tracks both the average gradient and its variance per parameter.',
  },
  {
    id: 38,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'L1 regularization ($\\|\\theta\\|_1$) encourages:',
    options: ['Large weights', 'Sparse weights (many zeros)', 'Uniform weights', 'Complex models'],
    correctIndex: 1,
    explanation: 'L1 penalty drives small weights exactly to zero, performing automatic feature selection.',
    realWorld: 'Lasso regression uses L1 to select important features in high-dimensional genomics data.',
    hint: 'This penalty has a diamond-shaped constraint that pushes weights to axes.',
  },
  {
    id: 39,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'Stochastic Gradient Descent (SGD) differs from batch GD by:',
    options: ['Using the full dataset per update', 'Using a random subset (mini-batch) per update', 'Not using gradients at all', 'Only working with convex functions'],
    correctIndex: 1,
    explanation: 'SGD approximates the true gradient using a random mini-batch, trading accuracy for speed and enabling large-scale training.',
    realWorld: 'All modern deep learning uses mini-batch SGD variants to train on datasets too large to fit in memory.',
    hint: 'Instead of computing gradients over all data, use a random sample.',
  },
  {
    id: 97,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'L2 regularization ($\\|\\theta\\|_2^2$) is equivalent to:',
    options: ['Adding noise to the data', 'Placing a Gaussian prior on weights', 'Pruning small weights', 'Reducing the learning rate'],
    correctIndex: 1,
    explanation: 'L2 regularization = weight decay = Gaussian prior in Bayesian interpretation. It penalizes large weights smoothly.',
    realWorld: 'Ridge regression and weight decay in Adam are L2 regularization in practice.',
    hint: 'From a Bayesian perspective, this penalty assumes weights are drawn from a bell curve centered at zero.',
  },
  {
    id: 98,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'Momentum in gradient descent helps by:',
    options: ['Reducing the learning rate', 'Accumulating past gradients to accelerate convergence', 'Eliminating the need for a loss function', 'Making the model deeper'],
    correctIndex: 1,
    explanation: 'Momentum adds a fraction of the previous update to the current one, helping escape narrow valleys and speeding up optimization.',
    realWorld: 'SGD with momentum (β=0.9) is standard practice and significantly improves training dynamics.',
    hint: 'Think of a ball rolling downhill — it builds up speed from previous movement.',
  },
  {
    id: 99,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'Dropout during training:',
    options: ['Removes layers permanently', 'Randomly zeroes neuron outputs to prevent co-adaptation', 'Increases the learning rate', 'Reduces the dataset size'],
    correctIndex: 1,
    explanation: 'Dropout randomly deactivates neurons during training, forcing the network to learn redundant representations.',
    realWorld: 'Dropout (p=0.5) was a breakthrough regularization technique that improved generalization in deep networks.',
    hint: 'Randomly turning off neurons forces the network to not rely on any single feature.',
  },
  {
    id: 100,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'Learning rate scheduling:',
    options: ['Keeps the learning rate constant', 'Changes the learning rate during training according to a schedule', 'Eliminates the learning rate', 'Only applies to Adam'],
    correctIndex: 1,
    explanation: 'Schedules like cosine annealing, step decay, and warmup adjust the learning rate over training for better convergence.',
    realWorld: 'Cosine annealing with warm restarts is standard in modern transformer training.',
    hint: 'Starting with a high learning rate and gradually reducing it often works best.',
  },
  {
    id: 101,
    topic: 'optimization',
    difficulty: 'hard',
    question: 'Batch normalization normalizes activations to:',
    options: ['Have mean 0 and variance 1 within each mini-batch', 'Have all positive values', 'Remove all gradients', 'Double the batch size'],
    correctIndex: 0,
    explanation: 'BatchNorm standardizes layer inputs per mini-batch, reducing internal covariate shift and allowing higher learning rates.',
    realWorld: 'BatchNorm enabled training much deeper networks and is standard in CNNs like ResNet.',
    hint: 'Center and scale the activations so they have nice statistical properties.',
  },
];
