import type { Question } from '../types';

export const sotaQuestions: Question[] = [
  {
    id: 18,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["optimization-objectives"],
    question: 'A convex loss function $L(\\theta)$ guarantees:',
    options: ['Multiple local minima', 'No gradient exists', 'Any local minimum is a global minimum', 'The Hessian is always zero'],
    correctIndex: 2,
    explanation: 'Convexity means the function curves upward everywhere — no valleys to get trapped in. Gradient descent finds the global optimum.',
    realWorld: 'Logistic regression and SVMs have convex losses, guaranteeing optimal solutions.',
    hint: 'If the bowl only curves one way, there is only one bottom.',
  },
  {
    id: 40,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["training-stability"],
    question: 'The vanishing gradient problem occurs when:',
    options: ['Learning rate is too high', 'Gradients approach zero through many layers, stalling learning', 'The loss function is convex', 'The model has too few parameters'],
    correctIndex: 1,
    explanation: 'In deep networks with sigmoid/tanh activations, gradients multiply through layers and can shrink exponentially to near-zero.',
    realWorld: 'ReLU activations, residual connections (ResNets), and batch normalization were invented to solve this.',
    hint: 'Multiplying many small numbers through layers makes the signal disappear.',
  },
  {
    id: 41,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["optimization-objectives"],
    question: 'Cross-entropy loss $H(p, q) = -\\sum_i p_i \\log q_i$ is preferred for classification because:',
    options: ['It is always convex', 'It heavily penalizes confident wrong predictions', 'It has no hyperparameters', 'It works only with two classes'],
    correctIndex: 1,
    explanation: 'When $q_i$ (predicted probability for the true class) is small, $-\\log q_i$ becomes very large, creating strong gradients for correction.',
    realWorld: 'Cross-entropy is the standard loss for classification in deep learning, from image recognition to NLP.',
    hint: 'Being confidently wrong is punished much more than being uncertain.',
  },
  {
    id: 102,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["generalization-model-selection"],
    question: 'The bias-variance tradeoff states that total error decomposes into:',
    options: ['Training error + test error', 'Bias² + variance + irreducible noise', 'Gradient + Hessian', 'Precision + recall'],
    correctIndex: 1,
    explanation: 'Expected error = bias² + variance + noise. High bias = underfitting, high variance = overfitting.',
    realWorld: 'Understanding this tradeoff guides model complexity decisions in all of machine learning.',
    hint: 'Simple models have high bias; complex models have high variance.',
  },
  {
    id: 103,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["training-stability"],
    question: 'Gradient clipping prevents:',
    options: ['Underfitting', 'Exploding gradients by capping their norm', 'Vanishing gradients', 'Overfitting'],
    correctIndex: 1,
    explanation: 'Gradient clipping rescales the gradient when its norm exceeds a threshold, preventing destabilizing large updates.',
    realWorld: 'Essential for training RNNs, LSTMs, and transformers where gradients can explode.',
    hint: 'If the gradient is too large, scale it down to a maximum allowed size.',
  },
  {
    id: 104,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["model-compression-efficiency"],
    question: 'Knowledge distillation trains a smaller model by:',
    options: ['Pruning weights from a large model', 'Learning to match the output distribution of a larger teacher model', 'Using less training data', 'Reducing the learning rate'],
    correctIndex: 1,
    explanation: 'The student model learns from soft targets (probability distributions) of the teacher, capturing richer information than hard labels.',
    realWorld: 'Used to deploy efficient models on mobile devices (DistilBERT, TinyML).',
    hint: 'A large teacher model shares its knowledge with a smaller student.',
  },
  {
    id: 105,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["model-compression-efficiency","regularization"],
    question: 'The lottery ticket hypothesis states that:',
    options: ['Larger models always generalize better', 'Dense networks contain sparse subnetworks that train equally well', 'Random initialization doesn\'t matter', 'Pruning always hurts performance'],
    correctIndex: 1,
    explanation: 'Sparse subnetworks (winning tickets) within randomly initialized networks can match the full network\'s performance when trained in isolation.',
    realWorld: 'Inspires neural network pruning strategies for efficient deployment.',
    hint: 'Hidden inside a large network is a small one that could have done the job alone.',
  },
  {
    id: 106,
    topic: 'optimization',
    difficulty: 'sota',
    conceptIds: ["model-compression-efficiency","training-stability"],
    question: 'Mixed-precision training uses:',
    options: ['Only 64-bit floats', 'Both 16-bit and 32-bit floats to speed up training', 'Integer arithmetic only', 'No numerical precision'],
    correctIndex: 1,
    explanation: 'FP16 for forward/backward passes (faster, less memory) with FP32 master weights for numerical stability.',
    realWorld: 'Standard practice for training large models on GPUs (NVIDIA Tensor Cores optimize FP16).',
    hint: 'Use lower precision where you can, higher precision where you must.',
  },
];
