import type { Question } from '../types';

export const opticsQuestions: Question[] = [
  {
    id: 3201,
    topic: 'optics',
    difficulty: 'easy',
    question: 'Snell\'s law $n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2$ describes:',
    options: ['Diffraction', 'Refraction at an interface', 'Polarization', 'Absorption'],
    correctIndex: 1,
    explanation: 'Snell\'s law relates the angles of incidence and refraction to the refractive indices of the two media.',
    realWorld: 'Snell\'s law governs lens design in cameras, eyeglasses, microscopes, and fiber optics.',
    hint: 'Light bends when it crosses a boundary between materials.',
  },
  {
    id: 3202,
    topic: 'optics',
    difficulty: 'easy',
    question: 'Total internal reflection occurs when:',
    options: ['Light enters a denser medium', 'The angle of incidence exceeds the critical angle in a denser medium', 'Light hits a mirror', 'The wavelength is very short'],
    correctIndex: 1,
    explanation: 'When light travels from a denser to a less dense medium at an angle exceeding the critical angle, all light is reflected back.',
    realWorld: 'This is how optical fibers guide light over thousands of kilometers for internet communication.',
    hint: 'The refracted ray would have to bend beyond 90°.',
  },
  {
    id: 3203,
    topic: 'optics',
    difficulty: 'easy',
    question: 'A convex lens causes parallel light rays to:',
    options: ['Diverge', 'Converge to a focal point', 'Remain parallel', 'Reflect backwards'],
    correctIndex: 1,
    explanation: 'A convex (converging) lens bends parallel rays inward to meet at the focal point $f$.',
    realWorld: 'Camera lenses, magnifying glasses, and the human eye all use converging lenses.',
    hint: 'It\'s called a converging lens for a reason.',
  },
  {
    id: 3204,
    topic: 'optics',
    difficulty: 'hard',
    question: 'The resolving power of a telescope is limited by:',
    options: ['The magnification only', 'Diffraction — the Rayleigh criterion $\\theta \\approx 1.22\\lambda/D$', 'The eyepiece focal length', 'The color of light only'],
    correctIndex: 1,
    explanation: 'Even a perfect lens cannot resolve details smaller than the diffraction limit, set by wavelength $\\lambda$ and aperture diameter $D$.',
    realWorld: 'This is why the James Webb Space Telescope has a 6.5m mirror — larger aperture means finer resolution.',
    hint: 'Bigger aperture = better resolution, but there\'s a fundamental wave limit.',
  },
  {
    id: 3205,
    topic: 'optics',
    difficulty: 'hard',
    question: 'In a Michelson interferometer, constructive interference occurs when the path difference is:',
    options: ['$\\lambda/4$', 'An integer multiple of $\\lambda$', '$\\lambda/2$', 'Zero only'],
    correctIndex: 1,
    explanation: 'When the optical path difference equals $m\\lambda$ (integer $m$), the waves add constructively, producing bright fringes.',
    realWorld: 'LIGO uses Michelson interferometry to detect gravitational waves with sub-proton-diameter sensitivity.',
    hint: 'Waves in phase = bright fringe.',
  },
  {
    id: 3206,
    topic: 'optics',
    difficulty: 'hard',
    question: 'Brewster\'s angle $\\theta_B = \\arctan(n_2/n_1)$ is special because:',
    options: ['All light is absorbed', 'The reflected light is completely polarized', 'No refraction occurs', 'The light changes color'],
    correctIndex: 1,
    explanation: 'At Brewster\'s angle, the reflected and refracted rays are perpendicular, and the reflected light is fully polarized in the plane of the surface.',
    realWorld: 'Polarized sunglasses exploit this principle, and laser windows are set at Brewster\'s angle to minimize reflection.',
    hint: 'The reflected ray becomes perfectly polarized.',
  },
  {
    id: 3207,
    topic: 'optics',
    difficulty: 'sota',
    question: 'Metamaterials can achieve a negative refractive index, enabling:',
    options: ['Faster-than-light travel', 'Perfect lensing beyond the diffraction limit (superlens)', 'Perpetual motion', 'Infinite magnification'],
    correctIndex: 1,
    explanation: 'Pendry (2000) showed that a slab with $n = -1$ amplifies evanescent waves, theoretically enabling imaging below the diffraction limit.',
    realWorld: 'Metamaterial research has produced cloaking devices at microwave frequencies and super-resolution near-field imaging.',
    hint: 'Evanescent waves carry sub-wavelength detail.',
  },
  {
    id: 3208,
    topic: 'optics',
    difficulty: 'sota',
    question: 'Adaptive optics in modern telescopes correct for:',
    options: ['Lens manufacturing defects', 'Atmospheric turbulence in real time using deformable mirrors', 'Chromatic aberration only', 'Detector noise'],
    correctIndex: 1,
    explanation: 'A wavefront sensor measures atmospheric distortion, and a deformable mirror adjusts hundreds of times per second to compensate.',
    realWorld: 'Adaptive optics give ground-based telescopes resolution rivaling space telescopes like Hubble.',
    hint: 'The atmosphere blurs starlight — these systems un-blur it.',
  },
  {
    id: 3209,
    topic: 'optics',
    difficulty: 'sota',
    question: 'Photonic crystals control light propagation through:',
    options: ['Chemical reactions', 'Periodic dielectric structures creating photonic band gaps', 'Gravitational lensing', 'Random scattering'],
    correctIndex: 1,
    explanation: 'Like electronic band gaps in semiconductors, photonic crystals have frequency ranges where light cannot propagate, enabling precise control of light.',
    realWorld: 'Photonic crystals enable low-loss optical waveguides, efficient LEDs, and next-generation optical computing.',
    hint: 'Periodic structure for photons, analogous to crystal lattices for electrons.',
  },
];
