import type { Question } from '../types';

export const differentialGeometryQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8301,
    topic: 'differential-geometry',
    difficulty: 'easy',
    question: 'The Gaussian curvature $K$ of a sphere of radius $R$ is:',
    options: ['$1/R^2$', '$1/R$', '$R$', '$R^2$'],
    correctIndex: 0,
    explanation: 'For a sphere of radius $R$, the principal curvatures are both $1/R$, so the Gaussian curvature $K = \\kappa_1 \\cdot \\kappa_2 = 1/R^2$. Gauss\'s Theorema Egregium (1827) proved that $K$ is an intrinsic invariant — a 2D being living on the surface could measure it without knowing about the embedding 3D space.',
    realWorld: 'Gaussian curvature determines whether a surface can be flattened without distortion — key for cartography and manufacturing.',
    hint: 'Product of principal curvatures, each $1/R$ for a sphere.',
    symbolLinks: { 'K': 'kappa', 'R': 'rho', '\\kappa': 'kappa' },
    glossaryLinks: ['gaussian-curvature'],
    formulaLinks: ['Gaussian Curvature'],
  },
  {
    id: 8302,
    topic: 'differential-geometry',
    difficulty: 'easy',
    question: 'A geodesic on a surface is a curve that locally minimizes:',
    options: ['Arc length', 'Curvature', 'Area', 'Torsion'],
    correctIndex: 0,
    explanation: 'Geodesics are the "straightest possible" curves on a surface — they locally minimize arc length between nearby points. On a sphere, geodesics are great circles. In general relativity, freely falling particles follow spacetime geodesics. The geodesic equation $\\nabla_{\\dot{\\gamma}} \\dot{\\gamma} = 0$ says the tangent vector is parallel-transported along itself.',
    realWorld: 'Airlines fly great circle routes (geodesics on the sphere) to minimize fuel consumption.',
    hint: 'The generalization of "straight line" to curved surfaces.',
    symbolLinks: { '\\gamma': 'gamma', '\\nabla': 'nabla' },
    glossaryLinks: ['geodesic'],
  },
  {
    id: 8303,
    topic: 'differential-geometry',
    difficulty: 'easy',
    question: 'The Gauss-Bonnet theorem relates the total Gaussian curvature of a closed surface to its:',
    options: ['Euler characteristic $\\chi$', 'Volume', 'Surface area', 'Mean curvature'],
    correctIndex: 0,
    explanation: 'The Gauss-Bonnet theorem states $\\int_M K\\,dA = 2\\pi\\chi(M)$. It connects local geometry (curvature) to global topology (Euler characteristic) in the most elegant way possible. For a sphere: $\\int K\\,dA = 4\\pi = 2\\pi \\cdot 2$. For a torus: $\\int K\\,dA = 0 = 2\\pi \\cdot 0$. Pure beauty.',
    realWorld: 'Gauss-Bonnet is used in computational geometry to verify mesh topology and detect genus.',
    hint: 'Total curvature = $2\\pi$ × (topological invariant).',
    symbolLinks: { 'K': 'kappa', '\\chi': 'chi', 'M': 'mu' },
    glossaryLinks: ['gauss-bonnet-theorem', 'euler-characteristic'],
    formulaLinks: ['Gauss-Bonnet Theorem'],
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8304,
    topic: 'differential-geometry',
    difficulty: 'hard',
    question: 'The Levi-Civita connection on a Riemannian manifold is uniquely determined by being:',
    options: [
      'Metric-compatible and torsion-free',
      'Flat and symmetric',
      'Metric-compatible only',
      'Torsion-free only',
    ],
    correctIndex: 0,
    explanation: "The fundamental theorem of Riemannian geometry: there exists a unique connection $\\nabla$ that is both metric-compatible ($\\nabla g = 0$, preserving lengths/angles) and torsion-free ($\\nabla_X Y - \\nabla_Y X = [X,Y]$). This is the Levi-Civita connection, and it defines how vectors are parallel-transported on curved manifolds. Einstein used it to write general relativity.",
    realWorld: 'The Levi-Civita connection defines how GPS satellite clocks are corrected for spacetime curvature.',
    hint: 'Two conditions: preserves the metric + no torsion.',
    symbolLinks: { '\\nabla': 'nabla', 'g': 'gamma' },
    glossaryLinks: ['riemannian-manifold', 'connection'],
  },
  {
    id: 8305,
    topic: 'differential-geometry',
    difficulty: 'hard',
    question: 'The Riemann curvature tensor $R^i_{\\;jkl}$ measures the failure of:',
    options: [
      'Parallel transport to be path-independent',
      'Geodesics to exist',
      'The metric to be positive-definite',
      'Coordinate charts to overlap',
    ],
    correctIndex: 0,
    explanation: 'If you parallel-transport a vector around a closed loop on a curved manifold, it comes back rotated — the Riemann tensor quantifies this holonomy. $R = 0$ iff the manifold is locally flat (parallel transport is path-independent). In GR, the Riemann tensor encodes tidal forces and gravitational waves.',
    realWorld: "Gravitational wave detectors (LIGO) measure components of the Riemann tensor — spacetime's curvature oscillations.",
    hint: 'Parallel transport around a loop: flat space → no change. Curved space → rotation.',
    symbolLinks: { 'R': 'rho' },
    glossaryLinks: ['riemann-curvature-tensor'],
    formulaLinks: ['Riemann Curvature Tensor'],
  },
  {
    id: 8306,
    topic: 'differential-geometry',
    difficulty: 'hard',
    question: 'In a fiber bundle $(E, B, \\pi, F)$, the map $\\pi: E \\to B$ is called the:',
    options: ['Projection', 'Section', 'Connection', 'Trivialization'],
    correctIndex: 0,
    explanation: 'The projection $\\pi$ maps each point in the total space $E$ to its base point in $B$, with fibers $F = \\pi^{-1}(b)$ sitting over each $b \\in B$. Fiber bundles formalize "attaching a space to each point" — tangent bundles, gauge fields in physics, and vector bundles in ML all use this framework.',
    realWorld: 'Gauge theories in particle physics (electromagnetism, QCD) are connections on principal fiber bundles.',
    hint: 'The map that "projects down" from total space to base.',
    symbolLinks: { '\\pi': 'pi', 'E': 'epsilon', 'B': 'beta', 'F': 'phi' },
    glossaryLinks: ['fiber-bundle'],
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8307,
    topic: 'differential-geometry',
    difficulty: 'sota',
    question: "Perelman's proof of the Poincaré conjecture (2003) used Hamilton's:",
    options: ['Ricci flow with surgery', 'Mean curvature flow', 'Kähler-Ricci flow', 'Yamabe flow'],
    correctIndex: 0,
    explanation: "Perelman resolved the 100-year-old Poincaré conjecture by analyzing Hamilton's Ricci flow $\\partial_t g_{ij} = -2R_{ij}$, which deforms a metric by its Ricci curvature. Perelman introduced entropy functionals and surgery techniques to handle singularities. He declined both the Fields Medal and the $1M Clay Prize.",
    realWorld: 'Ricci flow is now used in medical imaging for brain surface registration and mesh smoothing in computer graphics.',
    hint: 'The PDE that evolves metrics toward uniformity — think "geometric heat equation."',
    symbolLinks: { 'R': 'rho', 'g': 'gamma' },
    glossaryLinks: ['ricci-flow', 'poincare-conjecture'],
    formulaLinks: ['Ricci Flow'],
  },
  {
    id: 8308,
    topic: 'differential-geometry',
    difficulty: 'sota',
    question: 'The Atiyah-Singer index theorem relates the analytical index of an elliptic operator to:',
    options: [
      'Topological invariants (characteristic classes)',
      'The dimension of the manifold only',
      'Spectral gaps',
      'Eigenvalue multiplicities',
    ],
    correctIndex: 0,
    explanation: 'The Atiyah-Singer index theorem (1963) equates $\\text{ind}(D) = \\dim\\ker D - \\dim\\operatorname{coker} D$ with a topological integral involving Chern characters and Todd classes. It unifies Gauss-Bonnet, Riemann-Roch, and Hirzebruch signature in one framework. It earned Atiyah and Singer the Abel Prize.',
    realWorld: 'Index theory constrains zero modes of the Dirac operator, crucial for anomaly cancellation in string theory.',
    hint: 'Analysis (kernel dimensions) = topology (characteristic classes).',
    glossaryLinks: ['index-theorem'],
    formulaLinks: ['Atiyah-Singer Index Theorem'],
  },
  {
    id: 8309,
    topic: 'differential-geometry',
    difficulty: 'sota',
    question: 'Optimal transport theory, revived by Villani, studies the Wasserstein distance. The $W_2$ distance uses which cost function?',
    options: ['$c(x,y) = \\|x - y\\|^2$', '$c(x,y) = \\|x - y\\|$', '$c(x,y) = |x - y|^p$ for any $p$', '$c(x,y) = \\log\\|x-y\\|$'],
    correctIndex: 0,
    explanation: 'The $W_2$ (Earth Mover\'s) distance uses quadratic cost and has deep connections to Riemannian geometry — Otto showed the space of probability measures with $W_2$ is an infinite-dimensional Riemannian manifold. Villani won the Fields Medal (2010) for his work connecting optimal transport to Ricci curvature bounds.',
    realWorld: 'Wasserstein distances power generative adversarial networks (WGANs) and point cloud registration in 3D vision.',
    hint: 'The "2" in $W_2$ corresponds to quadratic cost.',
    symbolLinks: { 'W': 'omega' },
    glossaryLinks: ['wasserstein-distance', 'optimal-transport'],
    formulaLinks: ['Wasserstein Distance'],
  },
];
