import type { Question } from '../types';

export const numericalMethodsQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8401,
    topic: 'numerical-methods',
    difficulty: 'easy',
    question: "Newton's method for finding roots of $f(x) = 0$ uses the iteration $x_{n+1} = $?",
    options: [
      "$x_n - \\frac{f(x_n)}{f'(x_n)}$",
      "$x_n - f(x_n)$",
      "$x_n - \\frac{f'(x_n)}{f(x_n)}$",
      "$\\frac{x_n + f(x_n)}{2}$",
    ],
    correctIndex: 0,
    explanation: "Newton-Raphson iteration achieves quadratic convergence near simple roots — each step roughly doubles the number of correct digits. The geometric intuition: follow the tangent line to the $x$-axis. Newton invented this in 1669, and it remains the workhorse of numerical root-finding, optimization, and training neural networks (as a second-order method).",
    realWorld: "Newton's method variants power GPU-accelerated training in deep learning and real-time physics simulations.",
    hint: "Tangent line intersection with the $x$-axis — slope is $f'(x_n)$.",
    symbolLinks: { 'f': 'phi', 'x': 'chi' },
    glossaryLinks: ['newtons-method'],
    formulaLinks: ["Newton-Raphson Method"],
  },
  {
    id: 8402,
    topic: 'numerical-methods',
    difficulty: 'easy',
    question: 'The condition number $\\kappa(A)$ of a matrix $A$ measures sensitivity to perturbations. For a singular matrix, $\\kappa(A) = $?',
    options: ['$\\infty$', '$0$', '$1$', 'Undefined'],
    correctIndex: 0,
    explanation: 'The condition number $\\kappa(A) = \\|A\\| \\cdot \\|A^{-1}\\|$ (or $\\sigma_{\\max}/\\sigma_{\\min}$ via SVD). When $A$ is singular, $\\sigma_{\\min} = 0$, so $\\kappa = \\infty$. A large condition number warns that small input errors produce large output errors — the system is ill-conditioned.',
    realWorld: 'Ill-conditioned matrices arise in polynomial interpolation (Vandermonde) and cause numerical instability in scientific computing.',
    hint: 'Singular → zero smallest singular value → ratio blows up.',
    symbolLinks: { '\\kappa': 'kappa', '\\sigma': 'sigma', 'A': 'alpha' },
    glossaryLinks: ['condition-number'],
    formulaLinks: ['Condition Number'],
  },
  {
    id: 8403,
    topic: 'numerical-methods',
    difficulty: 'easy',
    question: "Simpson's rule approximates $\\int_a^b f(x)\\,dx$ using which type of interpolation?",
    options: ['Quadratic (parabolic)', 'Linear (trapezoidal)', 'Cubic spline', 'Constant'],
    correctIndex: 0,
    explanation: "Simpson's rule fits a parabola through three points per panel, achieving $O(h^4)$ error — two orders better than the trapezoidal rule's $O(h^2)$ for the same number of evaluations. Thomas Simpson published it in 1743, though Newton had the idea earlier.",
    realWorld: "Simpson's rule is used in embedded systems for real-time numerical integration where function evaluations are expensive.",
    hint: "Trapezoidal = linear. Simpson's = one step up.",
    symbolLinks: { 'h': 'eta' },
    formulaLinks: ["Simpson's Rule"],
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8404,
    topic: 'numerical-methods',
    difficulty: 'hard',
    question: 'The conjugate gradient method solves $Ax = b$ for symmetric positive-definite $A$ in at most $n$ iterations. It minimizes the $A$-norm of the error, which is:',
    options: [
      '$\\|e\\|_A = \\sqrt{e^T A e}$',
      '$\\|e\\|_2 = \\sqrt{e^T e}$',
      '$\\|e\\|_\\infty = \\max|e_i|$',
      '$\\|e\\|_1 = \\sum|e_i|$',
    ],
    correctIndex: 0,
    explanation: 'CG minimizes the error in the energy norm $\\|e\\|_A$ — equivalently, it minimizes the quadratic form $\\frac{1}{2}x^TAx - b^Tx$. Hestenes and Stiefel (1952) showed it converges in $n$ steps for $n \\times n$ systems, but in practice converges much faster when $A$ is well-conditioned or effectively low-rank.',
    realWorld: 'CG is the method of choice for solving sparse SPD systems in finite element analysis and weather simulation.',
    hint: 'The "energy" norm uses $A$ as the inner product matrix.',
    symbolLinks: { 'A': 'alpha', 'e': 'epsilon' },
    glossaryLinks: ['conjugate-gradient'],
    formulaLinks: ['Conjugate Gradient Method'],
  },
  {
    id: 8405,
    topic: 'numerical-methods',
    difficulty: 'hard',
    question: 'Gaussian elimination with partial pivoting has time complexity:',
    options: ['$O(n^3)$', '$O(n^2)$', '$O(n^2 \\log n)$', '$O(n^4)$'],
    correctIndex: 0,
    explanation: 'Gaussian elimination performs $\\sim \\frac{2}{3}n^3$ flops — the $n^3$ comes from the triple-nested loop over rows, columns, and elimination steps. Partial pivoting (swapping rows for numerical stability) adds only $O(n^2)$ comparisons. Strassen (1969) showed matrix multiplication can be done in $O(n^{2.807})$, but Gaussian elimination in practice is hard to beat.',
    realWorld: 'LAPACK\'s dgesv routine uses LU with partial pivoting — it runs in every scientific computing stack worldwide.',
    hint: 'Three nested loops over $n$ — classic cubic algorithm.',
    symbolLinks: { 'n': 'nu', 'O': 'omicron' },
    formulaLinks: ['Gaussian Elimination'],
  },
  {
    id: 8406,
    topic: 'numerical-methods',
    difficulty: 'hard',
    question: 'The Runge phenomenon shows that polynomial interpolation on equally spaced points can:',
    options: [
      'Diverge wildly at the interval edges',
      'Always converge uniformly',
      'Produce complex-valued results',
      'Require exponentially many points',
    ],
    correctIndex: 0,
    explanation: "Runge (1901) showed that interpolating $f(x) = \\frac{1}{1+25x^2}$ on $[-1,1]$ with equally spaced points produces increasingly wild oscillations near $\\pm 1$. The fix: use Chebyshev nodes $x_k = \\cos(\\frac{(2k-1)\\pi}{2n})$, which cluster near edges and give near-optimal interpolation. This is why spectral methods use Chebyshev polynomials.",
    realWorld: 'Spectral methods with Chebyshev nodes achieve exponential convergence for smooth PDEs in weather modeling.',
    hint: 'Equal spacing + high degree = edge oscillations. Chebyshev nodes fix it.',
    glossaryLinks: ['chebyshev-nodes'],
    formulaLinks: ['Chebyshev Interpolation'],
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8407,
    topic: 'numerical-methods',
    difficulty: 'sota',
    question: 'Randomized numerical linear algebra (RandNLA) uses sketching to approximate SVD. The Johnson-Lindenstrauss lemma guarantees distances are preserved in dimension:',
    options: [
      '$O(\\log n / \\varepsilon^2)$',
      '$O(n)$',
      '$O(\\sqrt{n})$',
      '$O(n / \\varepsilon)$',
    ],
    correctIndex: 0,
    explanation: 'JL (1984) shows $n$ points in $\\mathbb{R}^d$ can be projected to $O(\\log n / \\varepsilon^2)$ dimensions while preserving all pairwise distances within $(1\\pm\\varepsilon)$. This is the foundation of randomized algorithms for SVD, least squares, and kernel approximation that scale to massive datasets.',
    realWorld: 'JL random projections power locality-sensitive hashing in billion-scale nearest-neighbor search at Google and Spotify.',
    hint: 'Logarithmic in $n$ — exponential dimension reduction.',
    symbolLinks: { 'n': 'nu', '\\varepsilon': 'epsilon' },
    glossaryLinks: ['johnson-lindenstrauss'],
    formulaLinks: ['Johnson-Lindenstrauss Lemma'],
  },
  {
    id: 8408,
    topic: 'numerical-methods',
    difficulty: 'sota',
    question: 'Physics-informed neural networks (PINNs) enforce PDE constraints by adding which term to the loss function?',
    options: [
      'PDE residual evaluated at collocation points',
      'Gradient penalty on network weights',
      'Reconstruction error only',
      'KL divergence from a prior',
    ],
    correctIndex: 0,
    explanation: 'PINNs (Raissi et al., 2019) embed physical laws directly into the neural network loss: $\\mathcal{L} = \\mathcal{L}_{\\text{data}} + \\lambda\\mathcal{L}_{\\text{PDE}}$, where $\\mathcal{L}_{\\text{PDE}} = \\|\\mathcal{N}[u](x)\\|^2$ is the PDE residual. Automatic differentiation computes spatial/temporal derivatives of the network output. This enables solving inverse problems with sparse data.',
    realWorld: 'PINNs are used for cardiac electrophysiology modeling, turbulence closure, and subsurface flow prediction.',
    hint: 'The physics is in the loss — the PDE residual must vanish.',
    symbolLinks: { '\\lambda': 'lambda', '\\mathcal{L}': 'lambda', '\\mathcal{N}': 'nu' },
    formulaLinks: ['Physics-Informed Neural Networks'],
    paper: { title: 'Physics-informed neural networks', url: 'https://doi.org/10.1016/j.jcp.2018.10.045', venue: 'JCP', year: 2019 },
  },
  {
    id: 8409,
    topic: 'numerical-methods',
    difficulty: 'sota',
    question: 'The fast multipole method (FMM), named one of the top 10 algorithms of the 20th century, reduces $N$-body interaction computation from $O(N^2)$ to:',
    options: ['$O(N)$', '$O(N \\log N)$', '$O(N^{3/2})$', '$O(N \\log^2 N)$'],
    correctIndex: 0,
    explanation: "Greengard and Rokhlin's FMM (1987) achieves $O(N)$ complexity for $N$-body problems by hierarchically clustering particles and using multipole expansions to approximate far-field interactions. It revolutionized molecular dynamics, astrophysics, and electromagnetics. The key insight: far-away groups of charges look like a single multipole.",
    realWorld: 'FMM accelerates molecular dynamics simulations (GROMACS, AMBER) enabling drug discovery at atomic resolution.',
    hint: 'Hierarchical decomposition: nearby = exact, far = multipole approximation.',
    symbolLinks: { 'N': 'nu', 'O': 'omicron' },
    glossaryLinks: ['fast-multipole-method'],
    formulaLinks: ['Fast Multipole Method'],
  },
];
