import type { Question } from '../types';

export const philosophyScienceQuestions: Question[] = [
  {
    id: 41101, topic: 'philosophy-of-science', difficulty: 'easy',
    question: 'Popper\'s falsifiability criterion emphasizes that a scientific claim should:',
    options: [
      'Risk being contradicted by possible evidence',
      'Be accepted whenever experts agree on it',
      'Avoid making predictions about observations',
      'Be impossible to revise after publication',
    ],
    correctIndex: 0,
    explanation: 'Popper argued that scientific theories should expose themselves to potential refutation by making claims that could conflict with possible observations.',
    realWorld: 'The criterion encourages researchers to formulate risky tests rather than protecting a claim from every possible outcome.',
    hint: 'A scientific claim should be able to lose a fair empirical test.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41104, topic: 'philosophy-of-science', difficulty: 'easy',
    question: 'The principle of parsimony recommends preferring, other things equal:',
    options: [
      'The explanation with the most assumptions',
      'The explanation with fewer unnecessary assumptions',
      'The explanation with the newest terminology',
      'The explanation with the longest derivation',
    ],
    correctIndex: 1,
    explanation: 'Parsimony favors explanations that account for the evidence without adding unnecessary entities, mechanisms, or assumptions.',
    realWorld: 'The idea appears in model selection, regularization, scientific explanation, and engineering tradeoffs between complexity and evidence.',
    hint: 'Do not add complexity unless the evidence requires it.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41107, topic: 'philosophy-of-science', difficulty: 'easy',
    question: 'Scientific realism typically treats successful scientific theories as aiming to:',
    options: [
      'Describe observations without discussing causes',
      'Replace experiments with logical deduction',
      'Describe both observable and unobservable features of reality',
      'Avoid claims about entities that cannot be directly seen',
    ],
    correctIndex: 2,
    explanation: 'Scientific realism generally holds that mature scientific theories aim to describe a mind-independent world, including entities and structures that may be unobservable directly.',
    realWorld: 'The debate matters when interpreting claims about electrons, genes, fields, spacetime, or other theoretical entities inferred through evidence.',
    hint: 'The view takes theoretical entities seriously rather than only as prediction tools.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41102, topic: 'philosophy-of-science', difficulty: 'hard',
    question: 'In Kuhn\'s account, a scientific revolution occurs when:',
    options: [
      'Every scientist independently derives the same equation',
      'A field permanently stops using experiments',
      'Normal science eliminates all remaining anomalies',
      'A prevailing framework is replaced by a substantially different one',
    ],
    correctIndex: 3,
    explanation: 'Kuhn described periods of normal science within a paradigm and revolutionary transitions in which a different framework reorganizes central problems, concepts, and standards.',
    realWorld: 'The account is used to analyze major historical transitions in physics, chemistry, astronomy, and other sciences.',
    hint: 'The change is not just a new fact; it is a change in the framework used to organize facts.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41105, topic: 'philosophy-of-science', difficulty: 'hard',
    question: 'Hume\'s problem of induction asks how we can justify:',
    options: [
      'Generalizing from observed cases to unobserved cases',
      'Deriving a conclusion that follows deductively from premises',
      'Defining mathematical symbols within a formal proof',
      'Checking whether two measurements use the same units',
    ],
    correctIndex: 0,
    explanation: 'The problem concerns the justification for projecting regularities observed in a finite set of cases onto unobserved cases or the future.',
    realWorld: 'Every empirical forecast, statistical model, and machine-learning system relies on assumptions about how observed data relate to new cases.',
    hint: 'Past observations alone do not deductively guarantee future observations.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41108, topic: 'philosophy-of-science', difficulty: 'hard',
    question: 'The underdetermination problem arises when:',
    options: [
      'A theory contains no mathematical notation',
      'Available evidence is compatible with multiple explanations',
      'An experiment uses more than one measuring instrument',
      'A hypothesis predicts a result with complete certainty',
    ],
    correctIndex: 1,
    explanation: 'Underdetermination occurs when the evidence available at a time does not uniquely determine which of several competing theoretical explanations should be accepted.',
    realWorld: 'Scientists often need additional experiments, background assumptions, or explanatory criteria to distinguish models that fit the same observations.',
    hint: 'The data do not always select exactly one theory by themselves.',
    sources: [{
      title: 'Underdetermination of Scientific Theory',
      url: 'https://plato.stanford.edu/entries/scientific-underdetermination/',
      publisher: 'Stanford Encyclopedia of Philosophy',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 41103, topic: 'philosophy-of-science', difficulty: 'sota',
    question: 'In Bayesian confirmation, evidence supports a hypothesis when the evidence:',
    options: [
      'Makes every competing hypothesis logically impossible',
      'Has already been observed before the hypothesis exists',
      'Raises the probability assigned to the hypothesis',
      'Guarantees a posterior probability of exactly one',
    ],
    correctIndex: 2,
    explanation: 'A central Bayesian notion of confirmation is incremental: evidence confirms a hypothesis when conditioning on that evidence raises the hypothesis\'s probability.',
    realWorld: 'Bayesian confirmation gives a formal language for discussing how new observations change confidence in competing scientific hypotheses.',
    hint: 'Compare belief in the hypothesis before and after incorporating the evidence.',
    sources: [{
      title: 'Confirmation',
      url: 'https://plato.stanford.edu/entries/confirmation/',
      publisher: 'Stanford Encyclopedia of Philosophy',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 41106, topic: 'philosophy-of-science', difficulty: 'sota',
    question: 'Why can a direct replication be epistemically useful even when it is not decisive?',
    options: [
      'It proves that every methodological choice was optimal',
      'It removes all uncertainty from the original hypothesis',
      'It guarantees the same effect size in every population',
      'It supplies additional evidence about the robustness of a result',
    ],
    correctIndex: 3,
    explanation: 'A replication provides another evidential test of whether a result reappears under specified conditions, even though one success or failure rarely settles every interpretation.',
    realWorld: 'Replication programs help identify which findings are robust, which are sensitive to conditions, and where methods or theories need refinement.',
    hint: 'A replication adds evidence rather than delivering absolute proof.',
    sources: [{
      title: 'Reproducibility of Scientific Results',
      url: 'https://plato.stanford.edu/entries/scientific-reproducibility/',
      publisher: 'Stanford Encyclopedia of Philosophy',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 41109, topic: 'philosophy-of-science', difficulty: 'sota',
    question: 'The theory-ladenness of observation is the idea that:',
    options: [
      'Background concepts and assumptions can shape how observations are interpreted',
      'Scientific observations are always fabricated to protect a favored theory',
      'Measurement devices cannot provide information about unobservable entities',
      'Only theories stated in mathematical language can be tested empirically',
    ],
    correctIndex: 0,
    explanation: 'Theory-ladenness claims that observation and its interpretation can depend partly on concepts, expectations, background knowledge, or theoretical commitments.',
    realWorld: 'The issue motivates careful operational definitions, calibration, blinded analysis, and attention to how measurements connect raw signals to scientific claims.',
    hint: 'Observation is not always conceptually independent of what the observer already knows.',
    sources: [{
      title: 'Theory and Observation in Science',
      url: 'https://plato.stanford.edu/entries/science-theory-observation/',
      publisher: 'Stanford Encyclopedia of Philosophy',
    }],
    reviewedAt: '2026-09-20',
  },
];
