import type { Question } from '../types';

export const philosophyScienceQuestions: Question[] = [
  {
    id: 41101, topic: 'philosophy-of-science', difficulty: 'easy',
    question: 'Karl Popper\'s criterion of falsifiability states that:',
    options: [
      'A theory is scientific only if it makes predictions that could potentially be proven wrong — unfalsifiable claims are not science',
      'All scientific theories are eventually proven false',
      'Science can only study observable phenomena',
      'A theory is true if it has not been falsified yet',
    ],
    correctIndex: 0,
    explanation: 'Popper distinguished science from pseudoscience by falsifiability: "All swans are white" is scientific (one black swan falsifies it). "The universe is guided by an invisible force" is not.',
    realWorld: 'String theory faces criticism for being unfalsifiable. ML models face similar issues: a model that "explains everything" (overfitting) actually explains nothing.',
    hint: 'If nothing could possibly prove your theory wrong, it\'s not science — it\'s faith.',
  },
  {
    id: 41104, topic: 'philosophy-of-science', difficulty: 'easy',
    question: 'Occam\'s Razor (principle of parsimony) states:',
    options: [
      'Among competing explanations, the simplest one that fits the evidence should be preferred — don\'t multiply entities beyond necessity',
      'The most complex theory is always correct',
      'All explanations are equally valid',
      'Only mathematical proofs count as evidence',
    ],
    correctIndex: 0,
    explanation: 'William of Ockham (c. 1287-1347) formalized this: "Entities should not be multiplied beyond necessity." In modern terms: prefer the model with fewer parameters that still explains the data.',
    realWorld: 'Occam\'s Razor is formalized in ML as regularization (L1/L2 penalties) and information-theoretic model selection (AIC, BIC, MDL). Simpler models generalize better — this is the bias-variance tradeoff.',
    hint: 'The simplest explanation that works is probably the best one.',
  },
  {
    id: 41102, topic: 'philosophy-of-science', difficulty: 'hard',
    question: 'Thomas Kuhn\'s "paradigm shifts" describe science as:',
    options: [
      'Alternating between "normal science" (puzzle-solving within a paradigm) and revolutionary shifts when anomalies accumulate beyond what the current paradigm can explain',
      'A steady, linear accumulation of knowledge',
      'Purely driven by individual genius without social influence',
      'Completely relative with no objective progress',
    ],
    correctIndex: 0,
    explanation: 'Kuhn argued science isn\'t cumulative — it undergoes revolutions. Newtonian → Einsteinian physics, classical → quantum mechanics were paradigm shifts where the fundamental framework changed.',
    realWorld: 'The shift from symbolic AI to deep learning (2012-present) is a Kuhnian paradigm shift in computer science.',
    hint: 'Science doesn\'t progress smoothly — it has revolutions where the entire framework changes.',
  },
  {
    id: 41105, topic: 'philosophy-of-science', difficulty: 'hard',
    question: 'The problem of induction (Hume) challenges science because:',
    options: [
      'No number of observations can logically prove a universal law — seeing 1 million white swans doesn\'t prove "all swans are white," yet science depends on generalizing from finite observations',
      'Inductive reasoning always produces correct conclusions',
      'Only deductive reasoning is used in science',
      'Observation plays no role in scientific discovery',
    ],
    correctIndex: 0,
    explanation: 'Hume showed that induction (generalizing from specific cases) has no logical justification — the future need not resemble the past. Science works despite this problem, which is why Popper proposed falsification as an alternative.',
    realWorld: 'ML faces exactly this problem: a model trained on past data may not generalize to future data (distribution shift). The no-free-lunch theorem formalizes this — no algorithm generalizes without assumptions.',
    hint: 'Just because the Sun has risen every day doesn\'t logically guarantee it will rise tomorrow.',
  },
  {
    id: 41103, topic: 'philosophy-of-science', difficulty: 'sota',
    question: 'The "Chinese Room" argument (Searle, 1980) challenges AI by arguing:',
    options: [
      'A system can manipulate symbols according to rules and produce correct outputs without any understanding — syntactic processing ≠ semantic comprehension',
      'Chinese is too complex for computers to process',
      'Only Chinese-speaking programmers can build AI',
      'AI systems must be built in China to work properly',
    ],
    correctIndex: 0,
    explanation: 'Searle imagines following English instructions to manipulate Chinese symbols, producing perfect responses — without understanding Chinese. He argues computers similarly process syntax without semantics.',
    realWorld: 'Directly relevant to LLMs: GPT-4 produces coherent text by predicting tokens — but does it "understand"? This has implications for AI safety, rights, and regulation.',
    hint: 'Following rules perfectly ≠ understanding. Can a machine truly understand, or just simulate it?',
  },
  {
    id: 41106, topic: 'philosophy-of-science', difficulty: 'sota',
    question: 'The "hard problem of consciousness" (Chalmers, 1995) asks:',
    options: [
      'Why and how physical brain processes give rise to subjective experience (qualia) — explaining WHY there is "something it is like" to see red, not just the neural correlates of seeing red',
      'How to build a brain from scratch',
      'Why some people are smarter than others',
      'How neurons transmit electrical signals',
    ],
    correctIndex: 0,
    explanation: 'The "easy problems" (how the brain processes information, controls behavior) are hard but tractable. The "hard problem" is why any physical process produces subjective experience at all. No scientific theory explains this.',
    realWorld: 'As AI systems become more sophisticated, the hard problem becomes urgent: could an AI be conscious? If so, does it have moral status? These questions affect AI policy, rights frameworks, and the ethics of shutting down advanced AI systems.',
    hint: 'We can explain HOW the brain processes color — but not WHY you EXPERIENCE redness.',
  },
];
