import type { Question } from '../types';

export const differentialEquationsQuestions: Question[] = [
  {
    id: 3001,
    topic: 'differential-equations',
    difficulty: 'easy',
    question: 'A first-order ODE $\\frac{dy}{dx} = ky$ has the general solution:',
    options: ['$y = kx + C$', '$y = Ce^{kx}$', '$y = \\sin(kx)$', '$y = x^k$'],
    correctIndex: 1,
    explanation: 'This is the standard exponential growth/decay equation. Separating variables and integrating gives $y = Ce^{kx}$.',
    realWorld: 'Models population growth, radioactive decay, and compound interest.',
    hint: 'Separate variables: $\\frac{dy}{y} = k\\,dx$.',
  },
  {
    id: 3002,
    topic: 'differential-equations',
    difficulty: 'easy',
    question: 'The order of the ODE $y\'\' + 3y\' + 2y = 0$ is:',
    options: ['0', '1', '2', '3'],
    correctIndex: 2,
    explanation: 'The order is determined by the highest derivative present. Here $y\'\'$ is a second derivative, so it is second-order.',
    realWorld: 'Second-order ODEs describe springs, circuits, and mechanical vibrations.',
    hint: 'Count the highest number of primes on y.',
  },
  {
    id: 3003,
    topic: 'differential-equations',
    difficulty: 'easy',
    question: 'An ODE is "linear" if:',
    options: ['It contains only first derivatives', 'The dependent variable and its derivatives appear to the first power only', 'It has constant coefficients', 'It can be graphed as a straight line'],
    correctIndex: 1,
    explanation: 'Linearity means no products of $y$ with its derivatives, no $y^2$ terms, etc. Coefficients can be functions of $x$.',
    realWorld: 'Linear ODEs have superposition, enabling powerful analytical solution techniques.',
    hint: 'Think about what "linear in y" means.',
  },
  {
    id: 3004,
    topic: 'differential-equations',
    difficulty: 'hard',
    question: 'The characteristic equation of $y\'\' - 5y\' + 6y = 0$ is:',
    options: ['$r^2 + 5r + 6 = 0$', '$r^2 - 5r + 6 = 0$', '$r^2 - 5r - 6 = 0$', '$r^2 + 5r - 6 = 0$'],
    correctIndex: 1,
    explanation: 'Substituting $y = e^{rx}$ gives $r^2 - 5r + 6 = 0$, which factors as $(r-2)(r-3) = 0$, giving $r = 2, 3$.',
    realWorld: 'Characteristic equations determine the natural modes of oscillation in mechanical and electrical systems.',
    hint: 'Replace $y\'\'$ with $r^2$, $y\'$ with $r$, and $y$ with $1$.',
  },
  {
    id: 3005,
    topic: 'differential-equations',
    difficulty: 'hard',
    question: 'The Laplace transform of $f\'(t)$ is:',
    options: ['$sF(s) - f(0)$', '$F(s)/s$', '$s^2F(s)$', '$F(s) + f(0)$'],
    correctIndex: 0,
    explanation: 'By integration by parts, $\\mathcal{L}\\{f\'(t)\\} = sF(s) - f(0)$. This converts differential equations into algebraic ones.',
    realWorld: 'Laplace transforms are essential in control theory and electrical engineering for analyzing system responses.',
    hint: 'Differentiation in time domain becomes multiplication in s-domain, minus initial conditions.',
  },
  {
    id: 3006,
    topic: 'differential-equations',
    difficulty: 'hard',
    question: 'The Wronskian $W(y_1, y_2)$ of two solutions is used to verify:',
    options: ['Convergence', 'Linear independence', 'Stability', 'Periodicity'],
    correctIndex: 1,
    explanation: 'If $W(y_1, y_2) \\neq 0$ on an interval, the solutions are linearly independent and form a fundamental set.',
    realWorld: 'Ensures that a general solution spans all possible behaviors of the system.',
    hint: 'It\'s a determinant involving the solutions and their derivatives.',
  },
  {
    id: 3007,
    topic: 'differential-equations',
    difficulty: 'sota',
    question: 'Neural ODEs (Chen et al., 2018) parameterize the derivative $\\frac{dh}{dt} = f_\\theta(h, t)$ and compute gradients via:',
    options: ['Backpropagation through all ODE solver steps', 'The adjoint sensitivity method', 'Finite differences only', 'Symbolic differentiation'],
    correctIndex: 1,
    explanation: 'The original Neural ODE formulation uses an adjoint sensitivity method: it integrates an augmented adjoint system backward in time instead of retaining the full forward solver trajectory. This gives constant-memory scaling with respect to the number of forward solver steps in the idealized method, though practical implementations may trade memory for numerical accuracy and stability.',
    realWorld: 'Neural ODEs enable continuous-depth networks, normalizing flows, and time-series modeling with adaptive computation.',
    hint: 'It avoids storing the full forward trajectory by solving an adjoint system backward in time.',
  },
  {
    id: 3008,
    topic: 'differential-equations',
    difficulty: 'sota',
    question: 'Stiff ODEs require specialized solvers because:',
    options: ['They have no solution', 'Explicit methods need impractically small step sizes for stability', 'They are always nonlinear', 'They cannot be solved numerically'],
    correctIndex: 1,
    explanation: 'Stiff systems contain rapidly decaying modes that can force explicit methods to take step sizes far smaller than accuracy alone would require in order to remain numerically stable. Implicit methods such as BDF schemes have larger stability regions and can often take much larger steps.',
    realWorld: 'Chemical kinetics, combustion modeling, and circuit simulation all produce stiff systems.',
    hint: 'The difficulty is numerical stability: a fast-decaying mode can constrain an explicit method even when the solution of interest changes slowly.',
  },
  {
    id: 3009,
    topic: 'differential-equations',
    difficulty: 'sota',
    question: 'Physics-Informed Neural Networks (PINNs) enforce a PDE $\\mathcal{N}[u] = 0$ by:',
    options: ['Discretizing the PDE on a mesh', 'Adding the PDE residual as a loss term at collocation points', 'Using only boundary data', 'Solving the PDE analytically first'],
    correctIndex: 1,
    explanation: 'PINNs minimize $\\|\\mathcal{N}[u_\\theta]\\|^2$ at sampled collocation points plus data/boundary losses, embedding physics directly into the learning objective.',
    realWorld: 'PINNs solve inverse problems in fluid dynamics, heat transfer, and medical imaging without full simulation meshes.',
    hint: 'The neural network\'s output must satisfy the governing equation.',
  },
];
