import type { Question } from '../types';

export const audioEngineeringQuestions: Question[] = [
  {
    id: 40401, topic: 'audio-engineering', difficulty: 'easy',
    question: 'The Nyquist-Shannon sampling theorem states that to perfectly reconstruct an analog audio signal:',
    options: ['Sampling rate doesn\'t matter if bit depth is high enough', 'One sample per cycle is sufficient', 'You must sample at least twice the highest frequency — CDs use 44.1 kHz because human hearing tops out at ~20 kHz', 'You need infinite samples per second'],
    correctIndex: 2,
    explanation: 'Nyquist proved that a bandlimited signal can be perfectly reconstructed from samples taken at ≥2× its maximum frequency. Below this rate, aliasing occurs.',
    realWorld: 'CD audio (44.1 kHz), professional audio (96 kHz), and telephone (8 kHz for 4 kHz bandwidth) all follow Nyquist. Anti-aliasing filters remove frequencies above Nyquist before sampling.',
    hint: 'Two samples per cycle of the highest frequency — that\'s the minimum.',
  },
  {
    id: 40404, topic: 'audio-engineering', difficulty: 'easy',
    question: 'Bit depth in digital audio determines:',
    options: ['The physical size of the audio file only', 'The maximum frequency that can be recorded', 'The number of audio channels (mono, stereo)', 'The dynamic range — each bit adds ~6 dB, so 16-bit audio has ~96 dB range (quiet whisper to rock concert)'],
    correctIndex: 3,
    explanation: 'Bit depth sets the number of amplitude levels: 16-bit = 65,536 levels (~96 dB). 24-bit = 16.7 million levels (~144 dB). More bits = more dynamic range = lower noise floor.',
    realWorld: 'Professional studios record at 24-bit for headroom during mixing. Final consumer formats (CD, streaming) often use 16-bit. 32-bit float is used in DAWs for internal processing to prevent clipping.',
    hint: 'More bits = finer amplitude resolution = quieter noise floor.',
  },
  {
    id: 40402, topic: 'audio-engineering', difficulty: 'hard',
    question: 'Why is the Fast Fourier Transform (FFT) so useful in digital audio processing?',
    options: ['It converts every lossy codec into a lossless codec', 'It computes discrete-frequency representations efficiently enough for many practical spectral algorithms', 'It raises bit depth without adding information', 'It removes the need for windowing or filter design'],
    correctIndex: 1,
    explanation: 'The FFT computes a discrete Fourier transform in roughly $O(n \\log n)$ operations rather than the direct $O(n^2)$ approach, making repeated spectral analysis and frequency-domain processing practical.',
    realWorld: 'Spectrum analyzers, convolution engines, filter design tools, and many denoising or feature-extraction pipelines rely on FFT-based computation.',
    hint: 'Its advantage is computational efficiency for moving between time and frequency representations.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40405, topic: 'audio-engineering', difficulty: 'hard',
    question: 'A compressor set to a 4:1 ratio above threshold ideally means that:',
    options: ['Every 1 dB above threshold becomes 4 dB at the output', 'The signal is muted whenever it crosses threshold', 'A 4 dB increase above threshold produces about a 1 dB output increase above the threshold-related level', 'The sample rate is divided by four'],
    correctIndex: 2,
    explanation: 'Compression ratio describes how input level above threshold is mapped to output level above threshold. At 4:1, four additional input decibels yield approximately one additional output decibel before considering knee and time constants.',
    realWorld: 'Engineers combine threshold, ratio, attack, release, knee, and makeup gain to control peaks and shape dynamics without treating compression as simple clipping.',
    hint: 'The first number is input change; the second is output change above threshold.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40403, topic: 'audio-engineering', difficulty: 'sota',
    question: 'In Meta\'s EnCodec research, high-fidelity neural audio compression represents audio using:',
    options: ['Only a hand-designed MP3 transform with no learned model', 'A MIDI event stream with no waveform decoder', 'Uncompressed floating-point samples transmitted directly', 'A learned encoder-decoder with a quantized latent representation'],
    correctIndex: 3,
    explanation: 'EnCodec uses an end-to-end neural encoder-decoder and quantized latent space so audio can be represented compactly and reconstructed by the decoder. The research also studies residual quantization and learned modeling of the representation.',
    realWorld: 'Discrete learned audio representations can serve both compression systems and generative-audio pipelines that model audio as token-like sequences.',
    hint: 'The waveform is mapped into a learned latent space before quantization.',
    paper: { title: 'High Fidelity Neural Audio Compression', url: 'https://arxiv.org/abs/2210.13438', venue: 'arXiv', year: 2022 },
    reviewedAt: '2026-09-19',
  },
  {
    id: 40406, topic: 'audio-engineering', difficulty: 'sota',
    question: 'MusicGen generates conditioned music by modeling:',
    options: ['Multiple streams of compressed discrete music tokens with a transformer language model', 'A fixed library of complete songs selected by nearest-neighbor search', 'Only symbolic MIDI notes with no audio representation', 'A deterministic oscillator bank with no learned sequence model'],
    correctIndex: 0,
    explanation: 'MusicGen is a single-stage transformer language model operating over several streams of compressed discrete audio tokens, with conditioning from text and optionally melodic information.',
    realWorld: 'The architecture illustrates how neural audio tokenizers can turn waveform generation into a sequence-modeling problem while preserving direct audio output.',
    hint: 'The model predicts learned audio tokens rather than raw waveform samples one at a time.',
    paper: { title: 'Simple and Controllable Music Generation', url: 'https://arxiv.org/abs/2306.05284', venue: 'NeurIPS', year: 2023 },
    reviewedAt: '2026-09-19',
  },

  {
    id: 80653, topic: 'audio-engineering', difficulty: 'sota',
    question: 'A core advantage of scene- or object-aware immersive audio formats is that they can:',
    options: ['Render audio content adaptively for different loudspeaker layouts while preserving spatial intent', 'Guarantee identical acoustics in every physical room', 'Remove the need for any metadata or renderer', 'Make localization independent of listener position and playback geometry'],
    correctIndex: 0,
    explanation: 'Immersive formats can carry spatial structure separately from a single fixed channel layout, allowing a renderer to adapt presentation to the available playback configuration.',
    realWorld: 'MPEG-H 3D Audio was designed to support immersive presentation across different numbers and arrangements of loudspeakers and other playback environments.',
    hint: 'The content description can be rendered for the playback system that is actually available.',
    sources: [{ title: 'MPEG-H 3D Audio', url: 'https://mpeg.chiariglione.org/standards/mpeg-h/3d-audio.html', publisher: 'MPEG' }],
    reviewedAt: '2026-09-19',
  },
];
