import type { Question } from '../types';

export const audioEngineeringQuestions: Question[] = [
  {
    id: 40401, topic: 'audio-engineering', difficulty: 'easy',
    question: 'The Nyquist-Shannon sampling theorem states that to perfectly reconstruct an analog audio signal:',
    options: [
      'You must sample at least twice the highest frequency — CDs use 44.1 kHz because human hearing tops out at ~20 kHz',
      'One sample per cycle is sufficient',
      'Sampling rate doesn\'t matter if bit depth is high enough',
      'You need infinite samples per second',
    ],
    correctIndex: 0,
    explanation: 'Nyquist proved that a bandlimited signal can be perfectly reconstructed from samples taken at ≥2× its maximum frequency. Below this rate, aliasing occurs.',
    realWorld: 'CD audio (44.1 kHz), professional audio (96 kHz), and telephone (8 kHz for 4 kHz bandwidth) all follow Nyquist. Anti-aliasing filters remove frequencies above Nyquist before sampling.',
    hint: 'Two samples per cycle of the highest frequency — that\'s the minimum.',
  },
  {
    id: 40404, topic: 'audio-engineering', difficulty: 'easy',
    question: 'Bit depth in digital audio determines:',
    options: [
      'The dynamic range — each bit adds ~6 dB, so 16-bit audio has ~96 dB range (quiet whisper to rock concert)',
      'The maximum frequency that can be recorded',
      'The number of audio channels (mono, stereo)',
      'The physical size of the audio file only',
    ],
    correctIndex: 0,
    explanation: 'Bit depth sets the number of amplitude levels: 16-bit = 65,536 levels (~96 dB). 24-bit = 16.7 million levels (~144 dB). More bits = more dynamic range = lower noise floor.',
    realWorld: 'Professional studios record at 24-bit for headroom during mixing. Final consumer formats (CD, streaming) often use 16-bit. 32-bit float is used in DAWs for internal processing to prevent clipping.',
    hint: 'More bits = finer amplitude resolution = quieter noise floor.',
  },
  {
    id: 40402, topic: 'audio-engineering', difficulty: 'hard',
    question: 'The Fast Fourier Transform (FFT) is essential in audio because:',
    options: [
      'It converts time-domain audio signals to frequency-domain in $O(n \\log n)$ time, enabling real-time spectral analysis, EQ, and compression',
      'It makes audio files smaller by removing silence',
      'It only works on digital signals, not analog',
      'It was invented specifically for music production',
    ],
    correctIndex: 0,
    explanation: 'The FFT reduces the DFT from $O(n^2)$ to $O(n \\log n)$. A 1024-point FFT takes ~10,000 operations instead of ~1,000,000, enabling real-time spectral processing.',
    realWorld: 'Every digital EQ, noise cancellation system (AirPods), Auto-Tune pitch correction, and Shazam music identification uses FFT.',
    hint: 'It turns sound waves into frequency bars — and does it fast enough for real-time use.',
  },
  {
    id: 40405, topic: 'audio-engineering', difficulty: 'hard',
    question: 'Dynamic range compression in mastering works by:',
    options: [
      'Reducing the volume of signals above a threshold by a set ratio — making loud parts quieter so the overall level can be raised without clipping',
      'Removing all frequencies below 100 Hz',
      'Adding distortion to make audio sound louder',
      'Doubling the sample rate for better quality',
    ],
    correctIndex: 0,
    explanation: 'A compressor with ratio 4:1 and threshold -20 dB means: for every 4 dB above -20 dB, only 1 dB passes. Parameters: threshold, ratio, attack (how fast it engages), release (how fast it lets go), and knee (transition sharpness).',
    realWorld: 'The "loudness war" in music pushed average levels higher using heavy compression. Streaming services now normalize loudness (Spotify at -14 LUFS), finally ending the war.',
    hint: 'Squash the peaks, then turn everything up — the loud parts stay controlled while quiet parts become audible.',
  },
  {
    id: 40403, topic: 'audio-engineering', difficulty: 'sota',
    question: 'Neural audio codecs (Meta\'s EnCodec, Google\'s SoundStream) compress audio by:',
    options: [
      'Using an encoder-decoder neural network with residual vector quantization (RVQ) to represent audio at 1.5-6 kbps — 10× better than MP3 at comparable quality',
      'Simply applying MP3 compression with larger files',
      'Recording at lower sample rates',
      'Using only lossless compression techniques',
    ],
    correctIndex: 0,
    explanation: 'Neural codecs learn to compress audio into discrete tokens via RVQ: the encoder maps audio to a latent space, then multiple codebooks progressively refine the quantization.',
    realWorld: 'EnCodec enables real-time voice calls at 1.5 kbps (vs. 32 kbps for Opus). It also enables text-to-speech (VALL-E, MusicGen) by treating audio as a sequence of discrete tokens.',
    hint: 'A neural network learns to compress audio into tokens — the same tokens that language models can generate.',
  },
  {
    id: 40406, topic: 'audio-engineering', difficulty: 'sota',
    question: 'Text-to-music AI models (Suno, Udio, MusicGen) generate audio by:',
    options: [
      'Generating sequences of discrete audio tokens from text descriptions using language-model-style autoregressive or masked prediction, then decoding tokens back to waveforms',
      'Searching a database of existing songs and remixing them',
      'Converting text to MIDI and using fixed synthesizer presets',
      'Recording human musicians performing in real-time',
    ],
    correctIndex: 0,
    explanation: 'MusicGen uses a single-codebook language model over EnCodec tokens, conditioned on text embeddings. It generates audio autoregressively — like GPT generates text, but the "words" are audio tokens representing sound at 50 tokens/second.',
    realWorld: 'AI music generation is disrupting the $26B music industry. Legal battles over training data copyright are ongoing. These models can generate radio-quality songs in seconds from a text prompt.',
    hint: 'Same trick as ChatGPT — predict the next token — but the tokens represent sound instead of words.',
  },
];
