import type { Question } from '../types';

export const operatingSystemsQuestions: Question[] = [
  {
    id: 3501,
    topic: 'operating-systems',
    difficulty: 'easy',
    question: 'The kernel of an operating system is responsible for:',
    options: ['Only the GUI', 'Managing hardware, memory, and process scheduling', 'Web browsing', 'Compiling code'],
    correctIndex: 1,
    explanation: 'The kernel is the core of the OS, mediating between hardware and user programs. It handles CPU scheduling, memory management, and I/O.',
    realWorld: 'Linux, Windows NT, and macOS XNU are all kernels powering billions of devices.',
    hint: 'It\'s the most privileged layer of software.',
  },
  {
    id: 3502,
    topic: 'operating-systems',
    difficulty: 'easy',
    question: 'Virtual memory allows a process to:',
    options: ['Access unlimited physical RAM', 'Use more memory than physically available by using disk as backup', 'Run without an OS', 'Access other processes\' memory freely'],
    correctIndex: 1,
    explanation: 'Virtual memory maps virtual addresses to physical RAM or swap space on disk, giving each process the illusion of a large, private address space.',
    realWorld: 'Without virtual memory, running Chrome with 50 tabs would require massive physical RAM.',
    hint: 'Not all pages need to be in RAM at the same time.',
  },
  {
    id: 3503,
    topic: 'operating-systems',
    difficulty: 'easy',
    question: 'A deadlock occurs when:',
    options: ['A process runs too fast', 'Two or more processes are each waiting for resources held by the others', 'Memory is full', 'The CPU overheats'],
    correctIndex: 1,
    explanation: 'Deadlock requires four conditions simultaneously: mutual exclusion, hold and wait, no preemption, and circular wait.',
    realWorld: 'Database transactions can deadlock when two transactions each hold a lock the other needs.',
    hint: 'A circular dependency on resources.',
  },
  {
    id: 3504,
    topic: 'operating-systems',
    difficulty: 'hard',
    question: 'The page replacement algorithm that achieves the fewest page faults is:',
    options: ['FIFO (First-In, First-Out)', 'LRU (Least Recently Used)', 'OPT (Optimal — replace the page used farthest in the future)', 'Random'],
    correctIndex: 2,
    explanation: 'Bélády\'s OPT algorithm replaces the page not needed for the longest time. It\'s optimal but impractical since it requires future knowledge.',
    realWorld: 'LRU approximations (clock algorithm) are used in practice; OPT serves as a theoretical benchmark.',
    hint: 'If you could predict the future, which page would you evict?',
  },
  {
    id: 3505,
    topic: 'operating-systems',
    difficulty: 'hard',
    question: 'A semaphore differs from a mutex in that:',
    options: ['Semaphores can only be binary', 'Semaphores can allow multiple concurrent accesses (counting semaphore)', 'Mutexes support counting', 'They are identical'],
    correctIndex: 1,
    explanation: 'A counting semaphore allows up to $n$ threads into a critical section, while a mutex (binary semaphore) allows exactly one.',
    realWorld: 'Connection pools use counting semaphores to limit concurrent database connections.',
    hint: 'Think of a semaphore as a counter of available permits.',
  },
  {
    id: 3506,
    topic: 'operating-systems',
    difficulty: 'hard',
    question: 'Copy-on-Write (CoW) in fork() means:',
    options: ['The child immediately gets a full copy of parent memory', 'Parent and child share pages until one writes, triggering a copy', 'No memory is allocated to the child', 'The parent process is terminated'],
    correctIndex: 1,
    explanation: 'CoW marks shared pages as read-only. A write triggers a page fault, and only the written page is copied — saving time and memory.',
    realWorld: 'Redis uses fork() + CoW for background persistence (RDB snapshots) without doubling memory usage.',
    hint: 'Don\'t copy until you absolutely have to.',
  },
  {
    id: 3507,
    topic: 'operating-systems',
    difficulty: 'sota',
    question: 'eBPF (extended Berkeley Packet Filter) allows:',
    options: ['Only network packet filtering', 'Running sandboxed programs in the Linux kernel without modifying kernel source or loading modules', 'Replacing the entire kernel', 'User-space only debugging'],
    correctIndex: 1,
    explanation: 'eBPF attaches verified, JIT-compiled programs to kernel hooks, enabling observability, networking, and security without kernel changes.',
    realWorld: 'Cilium, Falco, and bpftrace use eBPF for Kubernetes networking, security monitoring, and performance profiling.',
    hint: 'It\'s like JavaScript for the kernel — sandboxed and verified.',
  },
  {
    id: 3508,
    topic: 'operating-systems',
    difficulty: 'sota',
    question: 'The io_uring interface in modern Linux improves I/O performance by:',
    options: ['Using blocking system calls', 'Providing a shared ring buffer between user space and kernel, eliminating syscall overhead for I/O', 'Replacing the filesystem entirely', 'Using only synchronous I/O'],
    correctIndex: 1,
    explanation: 'io_uring uses submission and completion ring buffers in shared memory, allowing batched, asynchronous I/O without per-operation syscall overhead.',
    realWorld: 'io_uring powers high-performance databases (RocksDB), web servers, and storage engines with millions of IOPS.',
    hint: 'Ring buffers in shared memory avoid the cost of context switches.',
  },
  {
    id: 3509,
    topic: 'operating-systems',
    difficulty: 'sota',
    question: 'Unikernels differ from traditional OS kernels by:',
    options: ['Running multiple applications', 'Compiling a single application with only the needed OS components into a single-purpose image', 'Requiring a hypervisor always', 'Being larger than general-purpose OS'],
    correctIndex: 1,
    explanation: 'Unikernels use library OS principles to link only required kernel functions (networking, filesystem) directly with the application, producing minimal, single-purpose VM images.',
    realWorld: 'Unikernels offer sub-millisecond boot times and minimal attack surfaces for serverless and edge computing.',
    hint: 'One application = one specialized kernel.',
  },
];
