import type { Question } from '../types';

export const topologyQuestions: Question[] = [
  {
    id: 41201, topic: 'topology', difficulty: 'easy',
    question: 'In topology, a coffee mug and a donut (torus) are considered equivalent because:',
    options: [
      'They are homeomorphic — one can be continuously deformed into the other without cutting or gluing, as both have exactly one hole',
      'They are made of the same material',
      'They have the same volume',
      'They weigh the same amount',
    ],
    correctIndex: 0,
    explanation: 'Topology studies properties preserved under continuous deformation. The number of holes (genus) is a topological invariant: mug and torus both have genus 1.',
    realWorld: 'Topological data analysis (TDA) uses persistent homology to find "holes" in high-dimensional data — revealing structure in protein folding, brain connectivity, and sensor networks.',
    hint: 'Imagine the mug is made of clay — you can smoothly reshape it into a donut without tearing.',
  },
  {
    id: 41204, topic: 'topology', difficulty: 'easy',
    question: 'A Möbius strip is topologically remarkable because:',
    options: [
      'It has only one side and one edge — if you draw a line along its surface, you return to the start having covered "both sides" without ever lifting the pen',
      'It has exactly two sides like a normal strip',
      'It is impossible to construct physically',
      'It has no edges at all',
    ],
    correctIndex: 0,
    explanation: 'The Möbius strip (1858) is formed by giving a strip a half-twist before joining the ends. It\'s a non-orientable surface — there\'s no consistent notion of "clockwise" on it. Cutting it down the middle produces one longer loop, not two!',
    realWorld: 'Möbius strips are used in conveyor belts (both "sides" wear evenly), continuous-loop recording tapes, and as a symbol of recycling. Non-orientability is key in topology and physics (gauge theory).',
    hint: 'Take a strip of paper, give it a half-twist, and tape the ends together. How many sides does it have?',
  },
  {
    id: 41202, topic: 'topology', difficulty: 'hard',
    question: 'The Euler characteristic $\\chi = V - E + F$ for a convex polyhedron always equals:',
    options: [
      '2 — for any convex polyhedron with V vertices, E edges, and F faces (e.g., cube: 8-12+6=2, tetrahedron: 4-6+4=2)',
      '0',
      '1',
      'It varies depending on the specific polyhedron',
    ],
    correctIndex: 0,
    explanation: 'The boundary of every convex polyhedron is homeomorphic to a sphere, so its Euler characteristic is $\\chi=V-E+F=2$. More generally, for a connected closed orientable surface of genus $g$, $\\chi=2-2g$; for example, a torus has genus 1 and $\\chi=0$.',
    realWorld: 'The Euler characteristic is used in mesh processing (3D graphics, CAD), computational geometry, and topological data analysis.',
    hint: 'Vertices minus edges plus faces — try it on a cube: 8 - 12 + 6.',
  },
  {
    id: 41205, topic: 'topology', difficulty: 'hard',
    question: 'The fundamental group $\\pi_1(X)$ of a topological space X captures:',
    options: [
      'The different ways loops can be drawn on the space — two loops are "the same" if one can be continuously deformed into the other; the group operation is concatenation',
      'The number of connected components',
      'The volume of the space',
      'The curvature at every point',
    ],
    correctIndex: 0,
    explanation: 'π₁(X) classifies loops up to homotopy. For a circle: π₁(S¹) = ℤ (loops counted by winding number). For a sphere: π₁(S²) = 0 (all loops can shrink to a point). For a torus: π₁(T²) = ℤ×ℤ.',
    realWorld: 'The fundamental group detects holes: a robot path planner uses π₁ to determine if two paths are topologically equivalent (can one be deformed into the other without crossing an obstacle?).',
    hint: 'Draw loops on the surface — which ones can shrink to a point, and which ones can\'t?',
  },
  {
    id: 41203, topic: 'topology', difficulty: 'sota',
    question: 'Persistent homology in topological data analysis (TDA) works by:',
    options: [
      'Growing balls around data points at increasing radii, tracking when topological features (components, loops, voids) appear and disappear — features that persist across many scales represent true structure',
      'Sorting data points by distance from the origin',
      'Applying PCA to reduce dimensionality',
      'Clustering data using k-means',
    ],
    correctIndex: 0,
    explanation: 'Persistent homology builds a filtration of simplicial complexes at increasing scale. Birth-death pairs of topological features are recorded in a "persistence diagram." Long-lived features represent genuine data topology.',
    realWorld: 'TDA has found novel structures in protein binding sites, detected coverage holes in sensor networks, identified market regimes in financial data, and discovered new subtypes of breast cancer.',
    hint: 'Grow circles around each point — track which clusters merge, which loops form, and how long they last.',
  },
  {
    id: 41206, topic: 'topology', difficulty: 'sota',
    question: 'Topological quantum computing uses anyons because:',
    options: [
      'Information is stored in the braiding patterns of quasiparticles — topological protection makes quantum states inherently immune to local perturbations and decoherence',
      'Anyons are just regular electrons in a different material',
      'Topological computing uses classical bits, not qubits',
      'Anyons only exist in theory and have never been observed',
    ],
    correctIndex: 0,
    explanation: 'In 2D systems, anyons (neither bosons nor fermions) can encode quantum information in their braiding history. This encoding is topologically protected: small perturbations can\'t change the braid, providing natural error correction.',
    realWorld: 'Microsoft\'s Station Q pursues topological qubits using Majorana zero modes in topological superconductors. If successful, they\'d need far fewer physical qubits for error correction than conventional approaches.',
    hint: 'Tie knots in particle paths — the quantum information is in the knot type, which is robust to small disturbances.',
  },
];
