import type { Question } from '../types';

export const topologyQuestions: Question[] = [
  {
    id: 41201, topic: 'topology', difficulty: 'easy',
    question: 'Two topological spaces are homeomorphic when there is:',
    options: [
      'A continuous bijection with a continuous inverse',
      'A distance-preserving linear transformation',
      'A differentiable map with zero derivative',
      'A coordinate system shared by both spaces',
    ],
    correctIndex: 0,
    explanation: 'A homeomorphism is a continuous one-to-one correspondence whose inverse is also continuous, so it preserves topological structure.',
    realWorld: 'Homeomorphism is the basic equivalence relation behind deformation-based reasoning in topology, geometry, and topological data analysis.',
    hint: 'The map and its inverse must both respect continuity.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41204, topic: 'topology', difficulty: 'easy',
    question: 'A Möbius strip has:',
    options: [
      'Two sides and two boundary components',
      'One side and one boundary component',
      'No boundary and two distinct sides',
      'No side because it is non-orientable',
    ],
    correctIndex: 1,
    explanation: 'A Möbius strip is a non-orientable surface with one side and one boundary component.',
    realWorld: 'The Möbius strip is a standard example for studying orientability and has inspired belt and loop designs that distribute wear across a surface.',
    hint: 'Trace the surface and boundary without lifting your finger.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41207, topic: 'topology', difficulty: 'easy',
    question: 'Which quantity is preserved by every homeomorphism?',
    options: [
      'The exact Euclidean area',
      'The lengths of all curves',
      'The number of connected components',
      'The numerical coordinates of points',
    ],
    correctIndex: 2,
    explanation: 'A homeomorphism preserves connectedness, so it preserves the number of connected components even though metric quantities such as area and length can change.',
    realWorld: 'Connected-component counts are among the simplest topological summaries used in image analysis, meshes, networks, and data analysis.',
    hint: 'Topological invariants survive continuous deformation, unlike metric measurements.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41202, topic: 'topology', difficulty: 'hard',
    question: 'For the boundary surface of any convex polyhedron, the Euler characteristic $V-E+F$ equals:',
    options: ['0', '1', '-2', '2'],
    correctIndex: 3,
    explanation: 'The boundary of a convex polyhedron is homeomorphic to a sphere, whose Euler characteristic is 2.',
    realWorld: 'Euler characteristic checks appear in mesh validation, computational geometry, image topology, and topological data analysis.',
    hint: 'A cube gives $8-12+6$.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41205, topic: 'topology', difficulty: 'hard',
    question: 'The fundamental group of a circle $S^1$ is isomorphic to:',
    options: ['$\\mathbb{Z}$', '$\\mathbb{R}$', '$\\mathbb{Z}/2\\mathbb{Z}$', 'The trivial group'],
    correctIndex: 0,
    explanation: 'Loops around a circle are classified up to homotopy by their integer winding number, giving $\\pi_1(S^1)\\cong\\mathbb{Z}$.',
    realWorld: 'Fundamental groups distinguish path classes around obstacles and support reasoning in robotics, knot theory, geometry, and gauge theory.',
    hint: 'Count how many times a loop winds around the circle, including direction.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41208, topic: 'topology', difficulty: 'hard',
    question: 'A path-connected space is simply connected when:',
    options: [
      'Every two points have exactly one path between them',
      'Every loop can be continuously contracted to a point',
      'Every open set is also closed',
      'Every continuous function on it is constant',
    ],
    correctIndex: 1,
    explanation: 'A path-connected space is simply connected when its fundamental group is trivial, equivalently when every loop can be contracted continuously to a point.',
    realWorld: 'Simple connectivity helps determine whether potentials, path integrals, and deformation classes can be defined globally without obstruction.',
    hint: 'The key question is whether any loop is trapped around a hole.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41203, topic: 'topology', difficulty: 'sota',
    question: 'Persistent homology summarizes a filtered data set by tracking:',
    options: [
      'Only pairwise Euclidean distances at one fixed scale',
      'Only the principal components of the data matrix',
      'Birth and death scales of topological features',
      'The gradient of a single fitted regression model',
    ],
    correctIndex: 2,
    explanation: 'Persistent homology follows connected components, loops, voids, and higher-dimensional features as a filtration parameter changes, recording when features appear and disappear.',
    realWorld: 'Persistence diagrams and barcodes provide multiscale summaries used in shape analysis, materials, biology, sensor networks, and other data-rich settings.',
    hint: 'A feature is informative partly because of how long it persists across scales.',
    sources: [{
      title: 'Stability of persistence diagrams',
      url: 'https://doi.org/10.1007/s00454-006-1276-5',
      publisher: 'Discrete & Computational Geometry',
      year: 2007,
    }],
    reviewedAt: '2026-09-21',
  },
  {
    id: 41206, topic: 'topology', difficulty: 'sota',
    question: 'In topological quantum computing, non-Abelian anyons are attractive because logical operations can be encoded in:',
    options: [
      'Only the instantaneous spatial distance between particles',
      'Classical voltage levels attached to each quasiparticle',
      'The total number of particles regardless of their paths',
      'Braiding histories that depend on topological path classes',
    ],
    correctIndex: 3,
    explanation: 'For non-Abelian anyons, exchanging particles acts nontrivially on a degenerate quantum state space, allowing information to be manipulated through braids that depend on topological path classes.',
    realWorld: 'The approach seeks fault-tolerant operations whose logical action is intrinsically insensitive to sufficiently small local deformations of the particle paths.',
    hint: 'The logical operation depends on how worldlines wind around one another.',
    paper: {
      title: 'Non-Abelian anyons and topological quantum computation',
      url: 'https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.80.1083',
      venue: 'Reviews of Modern Physics',
      year: 2008,
    },
    reviewedAt: '2026-09-21',
  },
  {
    id: 41209, topic: 'topology', difficulty: 'sota',
    question: 'A stability theorem for persistence diagrams implies, under standard assumptions, that small perturbations of an input function cause:',
    options: [
      'Only small changes in the resulting persistence diagram',
      'Every persistent feature to disappear immediately',
      'The filtration to become independent of the input',
      'The bottleneck distance to become infinite',
    ],
    correctIndex: 0,
    explanation: 'Persistence-diagram stability bounds changes in the diagram by changes in the underlying function, formalizing robustness to sufficiently small perturbations.',
    realWorld: 'Stability is one reason persistent homology is useful for noisy measurements and sampled geometric data.',
    hint: 'Robust summaries should not change dramatically under tiny input perturbations.',
    paper: {
      title: 'Stability of persistence diagrams',
      url: 'https://doi.org/10.1007/s00454-006-1276-5',
      venue: 'Discrete & Computational Geometry',
      year: 2007,
    },
    reviewedAt: '2026-09-21',
  },
];
