import type { Question } from '../types';

export const topologyQuestions: Question[] = [
  {
    id: 41201, topic: 'topology', difficulty: 'easy',
    question: 'In topology, a coffee mug and a donut (torus) are considered equivalent because:',
    options: [
      'They have the same volume',
      'They are made of the same material',
      'They are homeomorphic — one can be continuously deformed into the other without cutting or gluing, as both have exactly one hole',
      'They weigh the same amount',
    ],
    correctIndex: 2,
    explanation: 'Topology studies properties preserved under continuous deformation. The number of holes (genus) is a topological invariant: mug and torus both have genus 1.',
    realWorld: 'Topological data analysis (TDA) uses persistent homology to find "holes" in high-dimensional data — revealing structure in protein folding, brain connectivity, and sensor networks.',
    hint: 'Imagine the mug is made of clay — you can smoothly reshape it into a donut without tearing.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41204, topic: 'topology', difficulty: 'easy',
    question: 'A Möbius strip is topologically remarkable because:',
    options: [
      'It has exactly two sides like a normal strip',
      'It is impossible to construct physically',
      'It has no edges at all',
      'It has only one side and one edge — if you draw a line along its surface, you return to the start having covered "both sides" without ever lifting the pen',
    ],
    correctIndex: 3,
    explanation: 'The Möbius strip (1858) is formed by giving a strip a half-twist before joining the ends. It\'s a non-orientable surface — there\'s no consistent notion of "clockwise" on it. Cutting it down the middle produces one longer loop, not two!',
    realWorld: 'Möbius strips are used in conveyor belts (both "sides" wear evenly), continuous-loop recording tapes, and as a symbol of recycling. Non-orientability is key in topology and physics (gauge theory).',
    hint: 'Take a strip of paper, give it a half-twist, and tape the ends together. How many sides does it have?',
  },
  {
    id: 41202, topic: 'topology', difficulty: 'hard',
    question: 'The Euler characteristic $\\chi = V - E + F$ for a convex polyhedron always equals:',
    options: [
      '0',
      '2 — for any convex polyhedron with V vertices, E edges, and F faces (e.g., cube: 8-12+6=2, tetrahedron: 4-6+4=2)',
      'It varies depending on the specific polyhedron',
      '1',
    ],
    correctIndex: 1,
    explanation: 'The boundary of every convex polyhedron is homeomorphic to a sphere, so its Euler characteristic is $\\chi=V-E+F=2$. More generally, for a connected closed orientable surface of genus $g$, $\\chi=2-2g$; for example, a torus has genus 1 and $\\chi=0$.',
    realWorld: 'The Euler characteristic is used in mesh processing (3D graphics, CAD), computational geometry, and topological data analysis.',
    hint: 'Vertices minus edges plus faces — try it on a cube: 8 - 12 + 6.',
  },
  {
    id: 41205, topic: 'topology', difficulty: 'hard',
    question: 'The fundamental group $\\pi_1(X)$ of a topological space X captures:',
    options: [
      'The number of connected components',
      'The curvature at every point',
      'The different ways loops can be drawn on the space — two loops are "the same" if one can be continuously deformed into the other; the group operation is concatenation',
      'The volume of the space',
    ],
    correctIndex: 2,
    explanation: 'More precisely, $\\pi_1(X,x_0)$ consists of loops based at $x_0$, modulo homotopies that keep the basepoint fixed, with loop concatenation as the group operation. For a circle, $\\pi_1(S^1) \\cong \\mathbb{Z}$ via winding number; for a sphere, $\\pi_1(S^2)$ is trivial; and for a torus, $\\pi_1(T^2) \\cong \\mathbb{Z} \\times \\mathbb{Z}$.',
    realWorld: 'The fundamental group detects holes: a robot path planner uses π₁ to determine if two paths are topologically equivalent (can one be deformed into the other without crossing an obstacle?).',
    hint: 'Draw loops on the surface — which ones can shrink to a point, and which ones can\'t?',
  },
  {
    id: 41203, topic: 'topology', difficulty: 'sota',
    question: 'Persistent homology in topological data analysis (TDA) works by:',
    options: [
      'Applying PCA to reduce dimensionality',
      'Growing balls around data points at increasing radii, tracking when topological features (components, loops, voids) appear and disappear — features that persist across many scales represent true structure',
      'Clustering data using k-means',
      'Sorting data points by distance from the origin',
    ],
    correctIndex: 1,
    explanation: 'Persistent homology builds a filtration of simplicial complexes at increasing scale. Birth-death pairs of topological features are recorded in a "persistence diagram." Long-lived features represent genuine data topology.',
    realWorld: 'TDA has found novel structures in protein binding sites, detected coverage holes in sensor networks, identified market regimes in financial data, and discovered new subtypes of breast cancer.',
    hint: 'Grow circles around each point — track which clusters merge, which loops form, and how long they last.',
    paper: { title: 'Topological Persistence and Simplification', url: 'https://doi.org/10.1007/s00454-002-2885-2', venue: 'Discrete & Computational Geometry', year: 2002 },
    reviewedAt: '2026-09-21',
  },
  {
    id: 41206, topic: 'topology', difficulty: 'sota',
    question: 'Topological quantum computing uses anyons because:',
    options: [
      'Anyons are just regular electrons in a different material',
      'Anyons only exist in theory and have never been observed',
      'Topological computing uses classical bits, not qubits',
      'Information is stored in the braiding patterns of quasiparticles — topological protection makes quantum states inherently immune to local perturbations and decoherence',
    ],
    correctIndex: 3,
    explanation: 'In 2D systems, anyons (neither bosons nor fermions) can encode quantum information in their braiding history. This encoding is topologically protected: small perturbations can\'t change the braid, providing natural error correction.',
    realWorld: 'Topological quantum-computing proposals aim to encode information nonlocally so that sufficiently local perturbations are less able to corrupt the logical state; experimentally realizing suitable non-Abelian systems remains an active challenge.',
    hint: 'Tie knots in particle paths — the quantum information is in the braid type, which is robust to small local disturbances.',
    paper: { title: 'Non-Abelian anyons and topological quantum computation', url: 'https://doi.org/10.1103/RevModPhys.80.1083', venue: 'Reviews of Modern Physics', year: 2008 },
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41207, topic: 'topology', difficulty: 'easy',
    question: 'Which condition defines a homeomorphism $f:X\\to Y$?',
    options: [
      '$f$ is bijective, continuous, and has a continuous inverse',
      '$f$ preserves every distance between pairs of points',
      '$f$ is differentiable with a positive derivative everywhere',
      '$f$ maps every open set in $X$ to a single point in $Y',
    ],
    correctIndex: 0,
    explanation: 'A homeomorphism is a bijective continuous map whose inverse is also continuous. Homeomorphic spaces have the same topological structure even when their geometric shapes differ.',
    realWorld: 'Homeomorphism is the equivalence relation behind topology: it distinguishes deformations that preserve connectivity and holes from operations such as cutting or gluing.',
    hint: 'Topology requires a reversible continuous correspondence, not preservation of lengths or angles.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41208, topic: 'topology', difficulty: 'hard',
    question: 'By the Heine-Borel theorem, a subset of $\\mathbb{R}^n$ is compact exactly when it is:',
    options: [
      'Open and bounded',
      'Closed and bounded',
      'Closed and connected',
      'Bounded and path-connected',
    ],
    correctIndex: 1,
    explanation: 'In finite-dimensional Euclidean space, Heine-Borel states that compactness is equivalent to being closed and bounded. This equivalence does not hold unchanged in arbitrary metric or infinite-dimensional spaces.',
    realWorld: 'Compact feasible sets are important in optimization because continuous objective functions attain maxima and minima on compact domains.',
    hint: 'In Euclidean space, compactness combines one condition about containing limit points with one condition about not extending infinitely far.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41209, topic: 'topology', difficulty: 'sota',
    question: 'The stability theorem for persistence diagrams implies, under its standard assumptions, that:',
    options: [
      'Small changes in the filter cause small changes in the persistence diagram',
      'All short bars are guaranteed to represent measurement noise',
      'Any perturbation leaves the persistence diagram exactly unchanged',
      'Stability applies only to connected-component homology',
    ],
    correctIndex: 0,
    explanation: 'A central stability result bounds the bottleneck distance between persistence diagrams by the size of the perturbation of the underlying functions. This is why persistent-homology summaries can be robust rather than changing arbitrarily under small input perturbations.',
    realWorld: 'Stability gives topological data analysis a mathematical robustness guarantee when measurements, images, or sampled functions contain small perturbations.',
    hint: 'The theorem is a continuity statement: nearby inputs should produce nearby topological summaries.',
    paper: { title: 'Stability of Persistence Diagrams', url: 'https://doi.org/10.1007/s00454-006-1276-5', venue: 'Discrete & Computational Geometry', year: 2007 },
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
];
