import type { Question } from '../types';

export const quantumGravityEasyQuestions: Question[] = [
  {
    id: 28601,
    topic: 'quantum-gravity',
    difficulty: 'easy',
    question: 'The Planck length $\\ell_P = \\sqrt{\\hbar G / c^3} \\approx 1.6 \\times 10^{-35}$ m represents:',
    options: [
      'The scale where quantum gravitational effects are expected to become dominant',
      'The size of an atom',
      'The wavelength of visible light',
      'The radius of a proton',
    ],
    correctIndex: 0,
    explanation: 'The Planck length combines $\\hbar$ (quantum), $G$ (gravity), and $c$ (relativity) — the three fundamental constants. Below this scale, the classical notion of spacetime is expected to break down.',
    realWorld: 'The Planck length is $10^{20}$ times smaller than a proton — direct experimental access is impossible with current technology.',
    hint: 'It is built from the three pillars: quantum mechanics, gravity, and relativity.',
  },
  {
    id: 28602,
    topic: 'quantum-gravity',
    difficulty: 'easy',
    question: 'The fundamental problem of quantum gravity is:',
    options: [
      'General relativity and quantum mechanics are mathematically incompatible — gravity resists quantization',
      'Gravity is too weak to measure',
      'Quantum mechanics does not apply to large objects',
      'The speed of light is not constant',
    ],
    correctIndex: 0,
    explanation: 'GR treats spacetime as a smooth, dynamical manifold. QFT requires a fixed background. Naively quantizing GR produces non-renormalizable UV divergences — the theory explodes at high energies.',
    realWorld: 'This incompatibility means we cannot describe the Big Bang singularity or black hole interiors with current physics.',
    hint: 'Einstein\'s smooth spacetime and Heisenberg\'s uncertainty principle don\'t play well together.',
  },
  {
    id: 28603,
    topic: 'quantum-gravity',
    difficulty: 'easy',
    question: 'The Bekenstein-Hawking entropy of a black hole is proportional to:',
    options: [
      'Its horizon area: $S = A / 4\\ell_P^2$',
      'Its mass: $S = M / m_P$',
      'Its volume: $S \\propto R^3$',
      'Its charge: $S \\propto Q$',
    ],
    correctIndex: 0,
    explanation: 'Black hole entropy scales with area, not volume — a profound hint that gravity has a holographic nature. The information content of a region of space is bounded by its boundary area.',
    realWorld: 'This formula unifies thermodynamics, quantum mechanics, and gravity in a single equation — often called the most important equation in theoretical physics.',
    hint: 'The entropy is measured in units of Planck area $\\ell_P^2$, not Planck volume.',
  },
];

export const quantumGravityHardQuestions: Question[] = [
  {
    id: 28611,
    topic: 'quantum-gravity',
    difficulty: 'hard',
    question: 'The holographic principle, inspired by black hole thermodynamics, states that:',
    options: [
      'The maximum entropy in a region is bounded by its boundary area in Planck units, not its volume',
      'The universe is a hologram projected from a 2D surface',
      'Information is destroyed in black holes',
      'All physical theories must be formulated on lattices',
    ],
    correctIndex: 0,
    explanation: 'The Bekenstein bound $S \\leq A/(4\\ell_P^2)$ suggests that a $(d+1)$-dimensional gravitational theory is equivalent to a $d$-dimensional theory without gravity. This is realized concretely in AdS/CFT.',
    realWorld: 'The holographic principle has become a guiding paradigm for theoretical physics, connecting black hole physics, string theory, and quantum information.',
    hint: 'A 3D region of space can hold at most as much information as can be written on its 2D boundary.',
  },
  {
    id: 28612,
    topic: 'quantum-gravity',
    difficulty: 'hard',
    question: 'In Loop Quantum Gravity (LQG), the fundamental degrees of freedom are:',
    options: [
      'Spin networks — graphs with edges labeled by $SU(2)$ representations, giving quantized areas and volumes',
      'Vibrating strings in 10 dimensions',
      'Point particles on a lattice',
      'Continuous metric fields',
    ],
    correctIndex: 0,
    explanation: 'LQG quantizes GR directly. The area operator has discrete eigenvalues $A = 8\\pi \\gamma \\ell_P^2 \\sum \\sqrt{j_i(j_i+1)}$, where $j_i$ are spin labels and $\\gamma$ is the Barbero-Immirzi parameter.',
    realWorld: 'LQG predicts a quantum bounce replacing the Big Bang singularity — Loop Quantum Cosmology gives a bouncing universe scenario.',
    hint: 'Space itself is quantized — area and volume come in discrete chunks.',
  },
  {
    id: 28613,
    topic: 'quantum-gravity',
    difficulty: 'hard',
    question: 'The black hole information paradox arises because:',
    options: [
      'Hawking radiation appears thermal (featureless), suggesting pure states evolve into mixed states — violating unitarity',
      'Black holes absorb all information forever',
      'Information travels faster than light inside black holes',
      'Black holes do not emit radiation',
    ],
    correctIndex: 0,
    explanation: 'If a black hole evaporates completely via thermal Hawking radiation, the initial pure state becomes a mixed thermal state — violating quantum mechanics\' unitarity. Resolving this requires new physics.',
    realWorld: 'The Page curve, island formula, and replica wormholes (2019-2020) suggest unitarity is preserved via subtle gravitational effects.',
    hint: 'The paradox: does a black hole destroy information, or is it secretly encoded in the radiation?',
  },
];

export const quantumGravitySotaQuestions: Question[] = [
  {
    id: 28621,
    topic: 'quantum-gravity',
    difficulty: 'sota',
    question: 'The AdS/CFT correspondence (Maldacena, 1997) conjectures that:',
    options: [
      'Type IIB string theory on $AdS_5 \\times S^5$ is exactly dual to $\\mathcal{N}=4$ SYM in 4D — a quantum gravity theory equals a non-gravitational field theory',
      'Anti-de Sitter space is unstable',
      'Conformal field theories always have gravitational duals',
      'String theory is equivalent to loop quantum gravity',
    ],
    correctIndex: 0,
    explanation: 'AdS/CFT is the most concrete realization of the holographic principle. Strong coupling in the CFT maps to weak gravity in AdS (and vice versa), making unsolvable problems tractable.',
    realWorld: 'AdS/CFT has been applied to quark-gluon plasma viscosity (η/s bound), strange metals, and quantum entanglement entropy calculations.',
    hint: 'A gravitational theory in a "box" (AdS) is equivalent to a quantum theory living on the box\'s boundary.',
  },
  {
    id: 28622,
    topic: 'quantum-gravity',
    difficulty: 'sota',
    question: 'The Ryu-Takayanagi formula computes entanglement entropy in AdS/CFT as:',
    options: [
      '$S_A = \\frac{\\text{Area}(\\gamma_A)}{4G_N}$ where $\\gamma_A$ is the minimal surface in the bulk anchored to boundary region $A$',
      '$S_A = -\\text{Tr}(\\rho_A \\ln \\rho_A)$ computed directly in the bulk',
      '$S_A = \\text{Volume}(\\gamma_A) / 4G_N$',
      '$S_A = 0$ for any connected region',
    ],
    correctIndex: 0,
    explanation: 'Ryu-Takayanagi generalizes the Bekenstein-Hawking formula: entanglement entropy equals the area of the minimal surface in the bulk. This connects quantum information to geometry — "entanglement builds spacetime."',
    realWorld: 'This formula is central to understanding how spacetime emerges from entanglement and resolving the black hole information paradox.',
    hint: 'It looks like the Bekenstein-Hawking formula, but for arbitrary regions — geometry encodes entanglement.',
  },
  {
    id: 28623,
    topic: 'quantum-gravity',
    difficulty: 'sota',
    question: 'The "island formula" for the entropy of Hawking radiation modifies the Page curve by:',
    options: [
      'Including "island" regions inside the black hole whose von Neumann entropy is added, causing the entropy to decrease after the Page time',
      'Assuming Hawking radiation stops at half-evaporation',
      'Adding a cosmological constant correction',
      'Replacing thermal radiation with coherent states',
    ],
    correctIndex: 0,
    explanation: 'The island formula $S = \\min \\text{ext}\\left[\\frac{\\text{Area}(\\partial I)}{4G_N} + S_{\\text{vN}}(\\text{rad} \\cup I)\\right]$ includes islands $I$ inside the black hole, restoring unitarity by producing the correct Page curve.',
    realWorld: 'The island formula (2019) was hailed as a major breakthrough in resolving the black hole information paradox within semiclassical gravity.',
    hint: 'After the Page time, a quantum extremal surface appears inside the black hole, reducing the radiation entropy.',
  },
];
