import type { Question } from '../types';

export const complexAnalysisQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8001,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'What is the modulus of the complex number $z = 3 + 4i$?',
    options: ['$5$', '$7$', '$\\sqrt{7}$', '$25$'],
    correctIndex: 0,
    explanation: 'The modulus $|z| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = 5$. This is the Euclidean distance from the origin in the Argand plane — the same Pythagorean theorem that Euclid proved 2300 years ago, now powering signal processing and quantum state normalization.',
    realWorld: 'Complex moduli are used in electrical engineering to compute impedance magnitudes in AC circuits.',
    hint: 'Think Pythagorean theorem on the real and imaginary parts.',
    symbolLinks: { 'z': 'zeta', 'i': 'iota' },
    glossaryLinks: ['complex-number'],
    formulaLinks: ['Pythagorean Theorem'],
  },
  {
    id: 8002,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'The Cauchy-Riemann equations for $f(z) = u(x,y) + iv(x,y)$ to be holomorphic are:',
    options: [
      '$\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}$ and $\\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}$',
      '$\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial x}$ and $\\frac{\\partial u}{\\partial y} = \\frac{\\partial v}{\\partial y}$',
      '$\\frac{\\partial u}{\\partial x} = -\\frac{\\partial v}{\\partial y}$ and $\\frac{\\partial u}{\\partial y} = \\frac{\\partial v}{\\partial x}$',
      '$u = v$ everywhere',
    ],
    correctIndex: 0,
    explanation: 'The Cauchy-Riemann equations are necessary for complex differentiability, and together with suitable regularity of the partial derivatives they give a standard criterion for holomorphicity. A holomorphic function is conformal at points where its derivative is nonzero; at critical points with $f\'(z)=0$, local angle preservation can fail.',
    realWorld: 'Conformal mappings satisfying C-R equations are used in aerodynamics to map airfoil shapes to circles for flow analysis.',
    hint: 'The partial derivatives cross-link real and imaginary parts with a sign flip.',
    symbolLinks: { 'u': 'upsilon', 'v': 'upsilon' },
    glossaryLinks: ['holomorphic-function'],
    formulaLinks: ['Cauchy-Riemann Equations'],
  },
  {
    id: 8003,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: "By Cauchy's integral theorem, what is $\\oint_C f(z)\\,dz$ for a holomorphic function $f$ on a simply connected domain?",
    options: ['$0$', '$2\\pi i$', '$f(0)$', 'Depends on $C$'],
    correctIndex: 0,
    explanation: "Cauchy's integral theorem states that the contour integral of any holomorphic function over a closed curve in a simply connected domain vanishes. This is the cornerstone of complex analysis — every major result (residues, Laurent series, maximum modulus) flows from it.",
    realWorld: 'Used in physics to evaluate path integrals and in engineering for transfer function analysis.',
    hint: 'Holomorphic + simply connected = no singularities enclosed.',
    symbolLinks: { 'C': 'chi', 'f': 'phi' },
    glossaryLinks: ['contour-integral'],
    formulaLinks: ["Cauchy's Integral Theorem"],
  },
  {
    id: 8010,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'If $z=1-i$, what is its complex conjugate $\\overline z$?',
    options: ['$-1+i$', '$1+i$', '$-1-i$', '$1-i$'],
    correctIndex: 1,
    explanation: 'Complex conjugation keeps the real part and reverses the sign of the imaginary part, so $\\overline{1-i}=1+i$. In particular, $z\\overline z=|z|^2$.',
    realWorld: 'Conjugates appear in phasor calculations, Fourier analysis, and inner products on complex vector spaces.',
    hint: 'Keep the real coordinate and reflect the imaginary coordinate across the real axis.',
  },
  {
    id: 8011,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'For $z=re^{i\\theta}$ with $r>0$, multiplication by $e^{i\\phi}$ does what geometrically?',
    options: ['Scales the modulus by $e^{\\phi}$ without rotating', 'Reflects the point across the real axis', 'Translates the point by angle $\\phi$', 'Rotates the point by $\\phi$ while preserving its modulus'],
    correctIndex: 3,
    explanation: '$ze^{i\\phi}=re^{i(\\theta+\\phi)}$, so the argument increases by $\\phi$ while the modulus remains $r$.',
    realWorld: 'Complex multiplication compactly represents rotations in signal processing, control, and two-dimensional geometry.',
    hint: 'Multiply the exponential forms and combine their exponents.',
  },
  {
    id: 8012,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'Which statement about a power series $\\sum_{n=0}^\\infty a_n(z-z_0)^n$ inside its radius of convergence is correct?',
    options: ['It converges only on the real axis through $z_0$', 'It may converge but cannot be differentiated term by term', 'It defines a holomorphic function and may be differentiated term by term', 'It must represent a polynomial with finitely many nonzero coefficients'],
    correctIndex: 2,
    explanation: 'Inside its radius of convergence, a complex power series converges locally uniformly and defines a holomorphic function; its derivative is obtained by differentiating term by term.',
    realWorld: 'Power-series representations support numerical evaluation of analytic functions and local approximations in physics and engineering.',
    hint: 'Complex power series have especially strong regularity inside their convergence disk.',
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8004,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'What is the residue of $f(z) = \\frac{e^z}{z^2(z-1)}$ at $z = 0$?',
    options: ['$-2$', '$2$', '$-1$', '$1$'],
    correctIndex: 0,
    explanation: 'At $z=0$ there is a pole of order 2. Using the Laurent expansion or the residue formula for higher-order poles: $\\text{Res}_{z=0} = \\lim_{z\\to 0} \\frac{d}{dz}\\left[z^2 \\cdot \\frac{e^z}{z^2(z-1)}\\right] = \\lim_{z\\to 0} \\frac{d}{dz}\\left[\\frac{e^z}{z-1}\\right] = \\frac{e^0(z-1) - e^0}{(z-1)^2}\\big|_{z=0} = \\frac{-1-1}{1} = -2$.',
    realWorld: 'Residue calculus is the backbone of inverse Laplace transforms used in control systems engineering.',
    hint: 'Order-2 pole: differentiate once after multiplying by $z^2$.',
    symbolLinks: { 'z': 'zeta', 'e': 'epsilon' },
    glossaryLinks: ['residue-theorem', 'laurent-series'],
    formulaLinks: ['Residue Theorem'],
  },
  {
    id: 8005,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: "Which theorem states that a bounded entire function must be constant?",
    options: ["Liouville's theorem", "Picard's little theorem", 'Maximum modulus principle', 'Rouché\'s theorem'],
    correctIndex: 0,
    explanation: "Liouville's theorem is a stunning result: if $f$ is holomorphic on all of $\\mathbb{C}$ and $|f(z)| \\le M$ for all $z$, then $f$ is constant. This elegantly proves the Fundamental Theorem of Algebra — every non-constant polynomial has a root in $\\mathbb{C}$.",
    realWorld: "Liouville's theorem is used in mathematical physics to constrain solutions of elliptic PDEs.",
    hint: 'Named after Joseph Liouville — think "bounded + entire = boring."',
    symbolLinks: { 'M': 'mu', 'f': 'phi' },
    glossaryLinks: ['entire-function'],
    formulaLinks: ["Liouville's Theorem"],
  },
  {
    id: 8006,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'The Riemann mapping theorem guarantees a conformal bijection from any simply connected proper open subset of $\\mathbb{C}$ to:',
    options: ['The open unit disk $\\mathbb{D}$', 'The upper half-plane', 'The entire complex plane $\\mathbb{C}$', 'The Riemann sphere'],
    correctIndex: 0,
    explanation: "Riemann's mapping theorem is one of the most powerful existence results in mathematics. It says any simply connected domain (other than $\\mathbb{C}$ itself) can be conformally mapped to the unit disk. The proof is non-constructive — Riemann asserted it, and it took decades for Koebe and Carathéodory to make it rigorous.",
    realWorld: 'Conformal mapping is used in computational fluid dynamics to solve 2D potential flow problems.',
    hint: 'The target is the simplest simply connected domain — a disk.',
    symbolLinks: { '\\mathbb{D}': 'delta', '\\mathbb{C}': 'chi' },
    formulaLinks: ['Riemann Mapping Theorem'],
  },
  {
    id: 8013,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'If $f$ has a simple zero at $z_0$, what is the residue of $f\'(z)/f(z)$ at $z_0$?',
    options: ['$1$', '$0$', '$f\'(z_0)$', '$-1$'],
    correctIndex: 0,
    explanation: 'A simple zero gives $f(z)=(z-z_0)g(z)$ with $g(z_0)\\neq0$. Hence $f\'/f=1/(z-z_0)+g\'/g$, so the residue at $z_0$ is 1.',
    realWorld: 'The logarithmic derivative is central to the argument principle, which counts zeros and poles inside contours.',
    hint: 'Factor out the single power of $z-z_0$ and take the logarithmic derivative.',
  },
  {
    id: 8014,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'Suppose $f$ is holomorphic on a connected domain and vanishes on a set with an accumulation point inside the domain. What follows?',
    options: ['$f$ has only finitely many additional zeros', '$f$ must be a nonzero constant', '$f$ is identically zero on the domain', '$f$ can be arbitrary away from the accumulation point'],
    correctIndex: 2,
    explanation: 'The identity theorem says zeros of a nonzero holomorphic function are isolated. Therefore an interior accumulation point of zeros forces $f$ to vanish identically on the connected domain.',
    realWorld: 'Analytic continuation relies on this rigidity: agreement on sufficiently rich local data can determine a complex-analytic function globally.',
    hint: 'Nonzero holomorphic functions cannot have zeros accumulating in the interior.',
  },
  {
    id: 8015,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'For a nonconstant holomorphic function on a bounded domain, where can the maximum of $|f|$ occur if $f$ extends continuously to the boundary?',
    options: ['Only at an interior critical point', 'On the boundary of the domain', 'At every point because $|f|$ is constant', 'Only where the real part of $f$ vanishes'],
    correctIndex: 1,
    explanation: 'By the maximum modulus principle, a nonconstant holomorphic function cannot attain a local maximum of its modulus in the interior. Under the stated continuity and bounded-domain assumptions, the global maximum is attained on the boundary.',
    realWorld: 'Maximum principles provide stability bounds for harmonic and analytic models in potential theory and boundary-value problems.',
    hint: 'An interior maximum of the modulus would force much stronger rigidity than ordinary differentiability does.',
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8007,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'The Riemann Hypothesis conjectures that all non-trivial zeros of $\\zeta(s)$ lie on the critical line $\\text{Re}(s) = $?',
    options: ['$1/2$', '$1$', '$0$', '$2$'],
    correctIndex: 0,
    explanation: 'The Riemann Hypothesis — arguably the most important unsolved problem in mathematics — states that all non-trivial zeros of the Riemann zeta function $\\zeta(s) = \\sum_{n=1}^{\\infty} n^{-s}$ have real part exactly $1/2$. Its truth would unlock deep structure in the distribution of prime numbers. The Clay Mathematics Institute offers $1M for a proof.',
    realWorld: 'RH has implications for cryptographic security — the distribution of primes underlies RSA.',
    hint: 'The $1M Millennium Prize problem — the critical line bisects the critical strip.',
    symbolLinks: { '\\zeta': 'zeta', 's': 'sigma' },
    glossaryLinks: ['riemann-zeta-function'],
    formulaLinks: ['Riemann Zeta Function'],
  },
  {
    id: 8008,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'In the Langlands program, the modularity theorem (formerly Taniyama-Shimura) connects elliptic curves over $\\mathbb{Q}$ to:',
    options: ['Modular forms', 'Abelian varieties', 'Galois representations only', 'Algebraic K-theory'],
    correctIndex: 0,
    explanation: "The modularity theorem, proved by Andrew Wiles (with Taylor) in 1995, states every elliptic curve over $\\mathbb{Q}$ is modular — associated to a weight-2 newform. This was the key to proving Fermat's Last Theorem. It is now understood as a special case of the Langlands correspondence, one of the deepest conjectural frameworks in mathematics.",
    realWorld: 'Elliptic curves and modular forms underpin elliptic curve cryptography (ECC) used in TLS.',
    hint: 'Wiles proved this to establish Fermat\'s Last Theorem.',
    symbolLinks: { '\\mathbb{Q}': 'theta' },
    glossaryLinks: ['elliptic-curve', 'modular-form'],
    formulaLinks: ['Modularity Theorem'],
  },
  {
    id: 8009,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'The Bieberbach conjecture (proved by de Branges in 1985) states that for univalent functions $f(z) = z + \\sum a_n z^n$ on the unit disk, $|a_n| \\le$?',
    options: ['$n$', '$n^2$', '$2^n$', '$n!$'],
    correctIndex: 0,
    explanation: "De Branges' proof of the Bieberbach conjecture (1985) confirmed that for schlicht (univalent) functions on the disk, the $n$-th coefficient satisfies $|a_n| \\le n$. The proof used Löwner's parametric method and operator theory — a tour de force combining classical function theory with modern analysis.",
    realWorld: 'Coefficient bounds for conformal maps are applied in geometric function theory and quasiconformal mapping.',
    hint: 'The bound is linear in $n$ — the simplest possible growth.',
    symbolLinks: { 'a_n': 'alpha', 'z': 'zeta' },
    formulaLinks: ['Bieberbach Conjecture'],
  },
  {
    id: 8016,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'Which statement is the core conclusion of Runge\'s approximation theorem for a compact set $K\\subset\\mathbb C$?',
    options: ['Every continuous function on $K$ is uniformly approximable by entire functions', 'Holomorphic functions near $K$ can be approximated only by their Taylor polynomials about one fixed point', 'Every meromorphic function on $K$ is exactly equal to a rational function of bounded degree', 'Functions holomorphic near $K$ can be uniformly approximated by rational functions with poles chosen outside $K$'],
    correctIndex: 3,
    explanation: 'Runge\'s theorem gives rational approximation of functions holomorphic on a neighborhood of $K$, with poles placed outside $K$ in the appropriate complementary components. Stronger polynomial approximation requires additional conditions on the complement.',
    realWorld: 'Runge-type approximation is foundational in complex approximation theory and in constructing holomorphic functions with prescribed local behavior.',
    hint: 'The general theorem uses rational functions; polynomial approximation needs a stronger geometric condition.',
  },
  {
    id: 8017,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'For a nonconstant entire function, what does Picard\'s little theorem say about the values it assumes?',
    options: ['It assumes every complex value with at most one possible exception', 'It omits at least two complex values', 'It assumes only values lying in a bounded disk', 'It assumes every complex value exactly once'],
    correctIndex: 0,
    explanation: 'Picard\'s little theorem states that a nonconstant entire function takes every complex value, with at most one exception. The exponential function illustrates the exceptional-value possibility because $e^z$ never equals 0.',
    realWorld: 'Picard-type value-distribution results reveal the extreme rigidity of holomorphic functions and motivate Nevanlinna theory.',
    hint: 'Compare a polynomial with $e^z$: one hits every value, while the other misses just one.',
  },
  {
    id: 8018,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'If $f$ is meromorphic inside and on a positively oriented simple closed contour $C$ with no zeros or poles on $C$, what does $\\frac{1}{2\\pi i}\\oint_C f\'(z)/f(z)\\,dz$ equal?',
    options: ['The total number of zeros and poles, each counted positively', 'The winding number of $C$ around the origin regardless of $f$', 'The number of zeros minus the number of poles, counted with multiplicity', 'The sum of the residues of $f$ rather than of $f\'/f$'],
    correctIndex: 2,
    explanation: 'The argument principle gives $\\frac{1}{2\\pi i}\\oint_C f\'/f\\,dz=N-P$, where $N$ and $P$ count zeros and poles inside $C$ with multiplicity. Zeros contribute positive residues to $f\'/f$ and poles contribute negative residues.',
    realWorld: 'The argument principle underlies contour-based root counting and the Nyquist stability criterion in control engineering.',
    hint: 'Apply the residue theorem to the logarithmic derivative and track the sign of a zero versus a pole.',
  },
];
