import type { Question } from '../types';

export const complexAnalysisQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8001,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'What is the modulus of the complex number $z = 3 + 4i$?',
    options: ['$5$', '$7$', '$\\sqrt{7}$', '$25$'],
    correctIndex: 0,
    explanation: 'The modulus $|z| = \\sqrt{3^2 + 4^2} = \\sqrt{9+16} = 5$. This is the Euclidean distance from the origin in the Argand plane — the same Pythagorean theorem that Euclid proved 2300 years ago, now powering signal processing and quantum state normalization.',
    realWorld: 'Complex moduli are used in electrical engineering to compute impedance magnitudes in AC circuits.',
    hint: 'Think Pythagorean theorem on the real and imaginary parts.',
    symbolLinks: { 'z': 'zeta', 'i': 'iota' },
    glossaryLinks: ['complex-number'],
    formulaLinks: ['Pythagorean Theorem'],
  },
  {
    id: 8002,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: 'The Cauchy-Riemann equations for $f(z) = u(x,y) + iv(x,y)$ to be holomorphic are:',
    options: [
      '$\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial y}$ and $\\frac{\\partial u}{\\partial y} = -\\frac{\\partial v}{\\partial x}$',
      '$\\frac{\\partial u}{\\partial x} = \\frac{\\partial v}{\\partial x}$ and $\\frac{\\partial u}{\\partial y} = \\frac{\\partial v}{\\partial y}$',
      '$\\frac{\\partial u}{\\partial x} = -\\frac{\\partial v}{\\partial y}$ and $\\frac{\\partial u}{\\partial y} = \\frac{\\partial v}{\\partial x}$',
      '$u = v$ everywhere',
    ],
    correctIndex: 0,
    explanation: 'The Cauchy-Riemann equations are the fundamental test for complex differentiability. They encode the beautiful constraint that holomorphic functions are conformal (angle-preserving) — a fact Riemann and Cauchy independently discovered.',
    realWorld: 'Conformal mappings satisfying C-R equations are used in aerodynamics to map airfoil shapes to circles for flow analysis.',
    hint: 'The partial derivatives cross-link real and imaginary parts with a sign flip.',
    symbolLinks: { 'u': 'upsilon', 'v': 'upsilon' },
    glossaryLinks: ['holomorphic-function'],
    formulaLinks: ['Cauchy-Riemann Equations'],
  },
  {
    id: 8003,
    topic: 'complex-analysis',
    difficulty: 'easy',
    question: "By Cauchy's integral theorem, what is $\\oint_C f(z)\\,dz$ for a holomorphic function $f$ on a simply connected domain?",
    options: ['$0$', '$2\\pi i$', '$f(0)$', 'Depends on $C$'],
    correctIndex: 0,
    explanation: "Cauchy's integral theorem states that the contour integral of any holomorphic function over a closed curve in a simply connected domain vanishes. This is the cornerstone of complex analysis — every major result (residues, Laurent series, maximum modulus) flows from it.",
    realWorld: 'Used in physics to evaluate path integrals and in engineering for transfer function analysis.',
    hint: 'Holomorphic + simply connected = no singularities enclosed.',
    symbolLinks: { 'C': 'chi', 'f': 'phi' },
    glossaryLinks: ['contour-integral'],
    formulaLinks: ["Cauchy's Integral Theorem"],
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8004,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'What is the residue of $f(z) = \\frac{e^z}{z^2(z-1)}$ at $z = 0$?',
    options: ['$-2$', '$2$', '$-1$', '$1$'],
    correctIndex: 0,
    explanation: 'At $z=0$ there is a pole of order 2. Using the Laurent expansion or the residue formula for higher-order poles: $\\text{Res}_{z=0} = \\lim_{z\\to 0} \\frac{d}{dz}\\left[z^2 \\cdot \\frac{e^z}{z^2(z-1)}\\right] = \\lim_{z\\to 0} \\frac{d}{dz}\\left[\\frac{e^z}{z-1}\\right] = \\frac{e^0(z-1) - e^0}{(z-1)^2}\\big|_{z=0} = \\frac{-1-1}{1} = -2$.',
    realWorld: 'Residue calculus is the backbone of inverse Laplace transforms used in control systems engineering.',
    hint: 'Order-2 pole: differentiate once after multiplying by $z^2$.',
    symbolLinks: { 'z': 'zeta', 'e': 'epsilon' },
    glossaryLinks: ['residue-theorem', 'laurent-series'],
    formulaLinks: ['Residue Theorem'],
  },
  {
    id: 8005,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: "Which theorem states that a bounded entire function must be constant?",
    options: ["Liouville's theorem", "Picard's little theorem", 'Maximum modulus principle', 'Rouché\'s theorem'],
    correctIndex: 0,
    explanation: "Liouville's theorem is a stunning result: if $f$ is holomorphic on all of $\\mathbb{C}$ and $|f(z)| \\le M$ for all $z$, then $f$ is constant. This elegantly proves the Fundamental Theorem of Algebra — every non-constant polynomial has a root in $\\mathbb{C}$.",
    realWorld: "Liouville's theorem is used in mathematical physics to constrain solutions of elliptic PDEs.",
    hint: 'Named after Joseph Liouville — think "bounded + entire = boring."',
    symbolLinks: { 'M': 'mu', 'f': 'phi' },
    glossaryLinks: ['entire-function'],
    formulaLinks: ["Liouville's Theorem"],
  },
  {
    id: 8006,
    topic: 'complex-analysis',
    difficulty: 'hard',
    question: 'The Riemann mapping theorem guarantees a conformal bijection from any simply connected proper open subset of $\\mathbb{C}$ to:',
    options: ['The open unit disk $\\mathbb{D}$', 'The upper half-plane', 'The entire complex plane $\\mathbb{C}$', 'The Riemann sphere'],
    correctIndex: 0,
    explanation: "Riemann's mapping theorem is one of the most powerful existence results in mathematics. It says any simply connected domain (other than $\\mathbb{C}$ itself) can be conformally mapped to the unit disk. The proof is non-constructive — Riemann asserted it, and it took decades for Koebe and Carathéodory to make it rigorous.",
    realWorld: 'Conformal mapping is used in computational fluid dynamics to solve 2D potential flow problems.',
    hint: 'The target is the simplest simply connected domain — a disk.',
    symbolLinks: { '\\mathbb{D}': 'delta', '\\mathbb{C}': 'chi' },
    formulaLinks: ['Riemann Mapping Theorem'],
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8007,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'The Riemann Hypothesis conjectures that all non-trivial zeros of $\\zeta(s)$ lie on the critical line $\\text{Re}(s) = $?',
    options: ['$1/2$', '$1$', '$0$', '$2$'],
    correctIndex: 0,
    explanation: 'The Riemann Hypothesis — arguably the most important unsolved problem in mathematics — states that all non-trivial zeros of the Riemann zeta function $\\zeta(s) = \\sum_{n=1}^{\\infty} n^{-s}$ have real part exactly $1/2$. Its truth would unlock deep structure in the distribution of prime numbers. The Clay Mathematics Institute offers $1M for a proof.',
    realWorld: 'RH has implications for cryptographic security — the distribution of primes underlies RSA.',
    hint: 'The $1M Millennium Prize problem — the critical line bisects the critical strip.',
    symbolLinks: { '\\zeta': 'zeta', 's': 'sigma' },
    glossaryLinks: ['riemann-zeta-function'],
    formulaLinks: ['Riemann Zeta Function'],
  },
  {
    id: 8008,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'In the Langlands program, the modularity theorem (formerly Taniyama-Shimura) connects elliptic curves over $\\mathbb{Q}$ to:',
    options: ['Modular forms', 'Abelian varieties', 'Galois representations only', 'Algebraic K-theory'],
    correctIndex: 0,
    explanation: "The modularity theorem, proved by Andrew Wiles (with Taylor) in 1995, states every elliptic curve over $\\mathbb{Q}$ is modular — associated to a weight-2 newform. This was the key to proving Fermat's Last Theorem. It is now understood as a special case of the Langlands correspondence, one of the deepest conjectural frameworks in mathematics.",
    realWorld: 'Elliptic curves and modular forms underpin elliptic curve cryptography (ECC) used in TLS.',
    hint: 'Wiles proved this to establish Fermat\'s Last Theorem.',
    symbolLinks: { '\\mathbb{Q}': 'theta' },
    glossaryLinks: ['elliptic-curve', 'modular-form'],
    formulaLinks: ['Modularity Theorem'],
  },
  {
    id: 8009,
    topic: 'complex-analysis',
    difficulty: 'sota',
    question: 'The Bieberbach conjecture (proved by de Branges in 1985) states that for univalent functions $f(z) = z + \\sum a_n z^n$ on the unit disk, $|a_n| \\le$?',
    options: ['$n$', '$n^2$', '$2^n$', '$n!$'],
    correctIndex: 0,
    explanation: "De Branges' proof of the Bieberbach conjecture (1985) confirmed that for schlicht (univalent) functions on the disk, the $n$-th coefficient satisfies $|a_n| \\le n$. The proof used Löwner's parametric method and operator theory — a tour de force combining classical function theory with modern analysis.",
    realWorld: 'Coefficient bounds for conformal maps are applied in geometric function theory and quasiconformal mapping.',
    hint: 'The bound is linear in $n$ — the simplest possible growth.',
    symbolLinks: { 'a_n': 'alpha', 'z': 'zeta' },
    formulaLinks: ['Bieberbach Conjecture'],
  },
];
