import type { Question } from '../types';

export const earthSpaceQuestions: Question[] = [
  // ── Astronomy ──────────────────────────────────────────────
  {
    id: 70001, topic: "astronomy", difficulty: "easy",
    question: "A light-year is a unit of:",
    options: ["Distance","Time","Luminosity","Orbital period"],
    correctIndex: 0,
    explanation: "A light-year is the distance light travels through vacuum in one Julian year, about 9.46 trillion kilometres.",
    realWorld: "Astronomers use light-years and parsecs to describe distances between stars and across the Galaxy.",
    hint: "The name contains a unit of time, but the quantity tells you how far light travels.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70010, topic: "astronomy", difficulty: "easy",
    question: "If two nearby stars have accurately measured annual parallaxes, which star is closer to Earth?",
    options: ["The star with the smaller parallax angle","The star with the larger parallax angle","The star with the redder colour only","The star with the longer rotation period"],
    correctIndex: 1,
    explanation: "For nearby stars, distance in parsecs is approximately the reciprocal of parallax in arcseconds, so a larger parallax means a smaller distance.",
    realWorld: "Parallax is the geometric foundation of the nearby cosmic distance ladder and is measured at enormous scale by Gaia.",
    hint: "A bigger apparent shift against distant background stars means the object is nearer.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70011, topic: "astronomy", difficulty: "easy",
    question: "In the exoplanet transit method, a planet is detected primarily because it:",
    options: ["Makes the host star move across the sky once","Changes the star's chemical composition permanently","Produces a periodic dip in the host star's observed brightness","Causes the star to emit radio pulses"],
    correctIndex: 2,
    explanation: "When a planet passes in front of its star from our line of sight, it blocks a small fraction of starlight and produces a repeatable transit signal.",
    realWorld: "Transit surveys such as Kepler and TESS have found thousands of exoplanet candidates and can constrain planet size.",
    hint: "Look for a repeatable change caused by the planet crossing the stellar disk.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70002, topic: "astronomy", difficulty: "hard",
    question: "The Chandrasekhar mass is most directly associated with the maximum mass supportable by:",
    options: ["Thermal gas pressure in a main-sequence star","Neutron degeneracy pressure in a pulsar","Radiation pressure in an accretion disk","Electron degeneracy pressure in a cold white dwarf"],
    correctIndex: 3,
    explanation: "The Chandrasekhar mass is the limiting mass scale for a non-rotating white dwarf supported by electron degeneracy pressure, approximately 1.4 solar masses for typical composition.",
    realWorld: "This mass scale is central to white-dwarf evolution and to understanding pathways that can lead to thermonuclear supernovae.",
    hint: "Think about the compact remnant supported by degenerate electrons rather than neutrons.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70012, topic: "astronomy", difficulty: "hard",
    question: "For planets orbiting the same star, Kepler's third law implies that a planet with a larger semi-major axis generally has:",
    options: ["A longer orbital period","A shorter orbital period","The same orbital period","No predictable change in period"],
    correctIndex: 0,
    explanation: "For a fixed central mass, Kepler's third law gives P² proportional to a³, so more distant orbits take longer to complete.",
    realWorld: "The relation is used to infer orbital sizes and masses throughout planetary and binary-star systems.",
    hint: "Compare how orbital period scales when the orbital size increases.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70013, topic: "astronomy", difficulty: "hard",
    question: "Why is absolute magnitude useful when comparing stars?",
    options: ["It measures only a star's surface temperature","Brightness at a standard distance","It gives the star's age directly","It is identical to apparent magnitude for every star"],
    correctIndex: 1,
    explanation: "Absolute magnitude is defined from the brightness an object would have at 10 parsecs, allowing intrinsic brightness to be compared without the confounding effect of distance.",
    realWorld: "The apparent-versus-absolute magnitude distinction underlies distance-modulus calculations across astronomy.",
    hint: "The useful quantity puts different stars on the same distance footing.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70003, topic: "astronomy", difficulty: "sota",
    question: "Planck measurements of the cosmic microwave background, interpreted in the standard ΛCDM model, place the age of the Universe near:",
    options: ["9.8 billion years","18.4 billion years","13.8 billion years","27.6 billion years"],
    correctIndex: 2,
    explanation: "Planck's final cosmological analysis within base ΛCDM gives an age close to 13.8 billion years.",
    realWorld: "CMB anisotropy measurements constrain the expansion history, matter content, geometry, and age of the Universe.",
    hint: "The accepted value is a little under fourteen billion years.",
    sources: [{"title":"Planck 2018 results. VI. Cosmological parameters","url":"https://www.aanda.org/articles/aa/full_html/2020/09/aa36386-19/aa36386-19.html","publisher":"Astronomy & Astrophysics","year":2020}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 70014, topic: "astronomy", difficulty: "sota",
    question: "What is a central scientific capability of ESA's Gaia mission and Gaia DR3?",
    options: ["Imaging exoplanet surfaces at kilometre resolution","Detecting gravitational waves from black-hole mergers","Measuring only gamma-ray bursts outside the Milky Way","Precision stellar astrometry"],
    correctIndex: 3,
    explanation: "Gaia repeatedly measures stellar positions and motions with high precision, enabling three-dimensional and kinematic mapping of a large fraction of the Milky Way.",
    realWorld: "Gaia astrometry is transforming studies of Galactic structure, stellar populations, clusters, binaries, and the distance scale.",
    hint: "Think of the mission as an extraordinarily precise survey of where stars are and how they move.",
    sources: [{"title":"Gaia Data Release 3 contents summary","url":"https://www.cosmos.esa.int/web/gaia/dr3","publisher":"European Space Agency","year":2022}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 70015, topic: "astronomy", difficulty: "sota",
    question: "JWST transmission spectroscopy of the hot Saturn WASP-39b demonstrated that exoplanet atmospheres can be probed by:",
    options: ["Transit transmission spectroscopy","Photographing weather systems on the planet's solid surface","Measuring only the planet's radio rotation period","Sampling atmospheric gas directly with a spacecraft"],
    correctIndex: 0,
    explanation: "During transit, a small fraction of starlight passes through the planet's atmosphere; wavelength-dependent absorption reveals atmospheric species and chemical processes.",
    realWorld: "JWST spectra of WASP-39b robustly detected molecules including water, carbon dioxide, and carbon monoxide and opened a new precision era for comparative exoplanet atmospheres.",
    hint: "The key information comes from how the transit depth changes with wavelength.",
    paper: {"title":"Early Release Science of the exoplanet WASP-39b with JWST NIRSpec PRISM","url":"https://www.nature.com/articles/s41586-022-05677-y","venue":"Nature","year":2023},
    reviewedAt: "2026-09-19",
  },

  // ── Geology ──────────────────────────────────────────────
  {
    id: 70004, topic: "geology", difficulty: "easy",
    question: "The three broad rock classes are:",
    options: ["Igneous, sedimentary, and metamorphic","Granite, basalt, and quartz","Crustal, mantle, and core","Primary, secondary, and tertiary"],
    correctIndex: 0,
    explanation: "Rocks are classified by formation process: crystallization from melt, deposition and lithification of sediment, or transformation under heat, pressure, and fluids.",
    realWorld: "Rock classification helps reconstruct geologic history and informs construction, resource exploration, and hazard assessment.",
    hint: "Classify by how the rock formed rather than by a few example minerals or rock names.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70016, topic: "geology", difficulty: "easy",
    question: "At a convergent plate boundary where dense oceanic lithosphere meets another plate, the oceanic plate can:",
    options: ["Turn immediately into continental crust","Subduct into the mantle","Stop moving permanently","Become a mid-ocean ridge"],
    correctIndex: 1,
    explanation: "Oceanic lithosphere can descend beneath another plate at a subduction zone, recycling crust and driving earthquakes, volcanism, and mountain building.",
    realWorld: "Subduction zones produce many of Earth's largest earthquakes and volcanic arcs.",
    hint: "One plate descends beneath the other rather than pulling them apart.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70017, topic: "geology", difficulty: "easy",
    question: "The principle of superposition states that in an undisturbed sequence of sedimentary layers:",
    options: ["The youngest layers are always at the bottom","All layers are the same age","The oldest layers are generally at the bottom","Age can be determined only from magnetic polarity"],
    correctIndex: 2,
    explanation: "Sediments are deposited on top of older sediments, so an undeformed sequence generally becomes younger upward.",
    realWorld: "Superposition is a core rule of relative dating used before or alongside radiometric ages.",
    hint: "New sediment normally lands on material that was already there.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70005, topic: "geology", difficulty: "hard",
    question: "The Mohorovičić discontinuity, or Moho, is primarily a boundary between:",
    options: ["The mantle and outer core","The outer and inner core","The lithosphere and atmosphere","The crust and mantle"],
    correctIndex: 3,
    explanation: "The Moho is identified by a sharp seismic-velocity change associated with the compositional transition from crustal rocks to mantle peridotite.",
    realWorld: "Seismic observations of discontinuities reveal Earth's internal layering without directly drilling to most boundaries.",
    hint: "It separates the outer rocky shell from the compositionally distinct mantle below.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70018, topic: "geology", difficulty: "hard",
    question: "The absence of transmitted S-waves through Earth's outer core is strong evidence that the outer core is:",
    options: ["Liquid","Solid granite","A vacuum","Mostly water"],
    correctIndex: 0,
    explanation: "Shear waves require a material with shear rigidity and do not propagate through liquids, while P-waves do pass through the outer core with refraction.",
    realWorld: "Global earthquake seismology provided some of the first strong physical constraints on Earth's deep interior.",
    hint: "Ask which state of matter cannot sustain shear stress over long times.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70019, topic: "geology", difficulty: "hard",
    question: "A mineral contains one-quarter of its original radioactive parent isotope. Assuming a closed system, approximately how many half-lives have elapsed?",
    options: ["One","Two","Three","Four"],
    correctIndex: 1,
    explanation: "After one half-life one-half remains; after two half-lives one-quarter remains.",
    realWorld: "Radiometric dating converts measured parent-daughter isotope ratios into quantitative ages for rocks and minerals.",
    hint: "Repeatedly halve the original amount until you reach one-quarter.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70006, topic: "geology", difficulty: "sota",
    question: "Why are Jack Hills zircons scientifically important?",
    options: ["They are the youngest volcanic rocks on Earth","They prove plate tectonics operated exactly as today from Earth's first year","~4.4-billion-year-old zircons preserving Hadean evidence","They are meteorites that formed on Mars"],
    correctIndex: 2,
    explanation: "Detrital zircons from Jack Hills include grains around 4.4 billion years old, making them among the oldest known terrestrial minerals and rare archives of Hadean conditions.",
    realWorld: "Their age and isotope chemistry constrain when crust, magmatism, and surface water could have existed on the early Earth.",
    hint: "Their value comes from surviving from an interval for which intact rocks are exceedingly rare.",
    paper: {"title":"Evidence from detrital zircons for the existence of continental crust and oceans on the Earth 4.4 Gyr ago","url":"https://www.nature.com/articles/35051550","venue":"Nature","year":2001},
    reviewedAt: "2026-09-19",
  },
  {
    id: 70020, topic: "geology", difficulty: "sota",
    question: "Modern studies of great subduction-zone earthquakes emphasize that seismic and tsunami hazard depends strongly on:",
    options: ["Plate age alone determining whether magnitude-9 earthquakes are possible","A single universal recurrence interval at all trenches","Volcanic ash thickness as the only predictor","Rupture geometry, seafloor displacement, and recurrence"],
    correctIndex: 3,
    explanation: "Observations show that simple rules based only on plate age or convergence rate are inadequate; rupture geometry, coupling, seafloor displacement, recurrence, and monitoring all matter.",
    realWorld: "Improved offshore geodesy, seismology, and paleoseismic records are essential for realistic hazard assessment along subduction margins.",
    hint: "The best answer combines several physical properties of rupture rather than relying on one old rule of thumb.",
    sources: [{"title":"The occurrence and hazards of great subduction zone earthquakes","url":"https://www.nature.com/articles/s43017-021-00245-w","publisher":"Nature Reviews Earth & Environment","year":2022}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 70021, topic: "geology", difficulty: "sota",
    question: "Oxygen-isotope measurements in ancient Jack Hills zircons reported in 2024 support the inference that meteoric water interacted with emerged crust by roughly:",
    options: ["4.0 billion years ago or earlier","2.0 billion years ago","600 million years ago","65 million years ago"],
    correctIndex: 0,
    explanation: "Very low oxygen-isotope values in dated zircons were interpreted as evidence that meteoric water interacted with shallow crustal magmatic systems by about 4.0 billion years ago or earlier.",
    realWorld: "The result places an early lower bound on operation of parts of Earth's hydrological cycle and informs models of early habitability.",
    hint: "The result concerns the Hadean-Archean transition, not relatively recent geologic time.",
    paper: {"title":"Onset of the Earth's hydrological cycle four billion years ago or earlier","url":"https://www.nature.com/articles/s41561-024-01450-0","venue":"Nature Geoscience","year":2024},
    reviewedAt: "2026-09-19",
  },

  // ── Climate Science ──────────────────────────────────────────────
  {
    id: 70007, topic: "climate-science", difficulty: "easy",
    question: "Greenhouse gases warm Earth's surface system primarily because they:",
    options: ["Absorb and re-emit outgoing infrared radiation","Block essentially all incoming visible sunlight","Increase Earth's rotation rate","Create the ozone hole directly"],
    correctIndex: 0,
    explanation: "Greenhouse gases interact strongly with infrared wavelengths emitted by Earth, changing the altitude and efficiency at which heat escapes to space.",
    realWorld: "The natural greenhouse effect makes Earth habitable, while changes in greenhouse-gas concentrations alter the planet's energy balance.",
    hint: "Focus on longwave heat radiation leaving the surface-atmosphere system.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70022, topic: "climate-science", difficulty: "easy",
    question: "Which statement best distinguishes weather from climate?",
    options: ["Weather concerns temperature only; climate concerns precipitation only","Weather is short-term; climate is long-term statistics","Climate changes hourly while weather requires decades","They are exact synonyms"],
    correctIndex: 1,
    explanation: "Weather is the state of the atmosphere over short timescales, whereas climate summarizes distributions, averages, variability, and extremes over much longer periods.",
    realWorld: "A single cold day does not diagnose global climate trends; climate analysis uses many observations over time and space.",
    hint: "One is an immediate state; the other is a long-term statistical description.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70023, topic: "climate-science", difficulty: "easy",
    question: "Loss of reflective snow or sea ice can amplify warming through which feedback?",
    options: ["Radioactive-decay feedback","Tidal-locking feedback","Ice-albedo feedback","Plate-tectonic feedback"],
    correctIndex: 2,
    explanation: "Bright ice and snow reflect substantial sunlight; when they retreat, darker surfaces absorb more solar energy, reinforcing warming.",
    realWorld: "This feedback is one reason high-latitude regions can warm faster than the global mean.",
    hint: "The key property that changes is surface reflectivity.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70008, topic: "climate-science", difficulty: "hard",
    question: "Equilibrium climate sensitivity (ECS) is conventionally defined as the long-term global warming after:",
    options: ["A one-day doubling of rainfall","Complete melting of all land ice","A doubling of Earth's orbital speed","A sustained doubling of atmospheric carbon dioxide"],
    correctIndex: 3,
    explanation: "ECS measures the eventual global-mean surface temperature response to doubled CO₂ after the fast climate feedbacks equilibrate.",
    realWorld: "IPCC AR6 assessed a likely ECS range of 2.5°C to 4.0°C, with a central estimate near 3°C.",
    hint: "The standard experiment changes a greenhouse-gas concentration, not the planet's orbit.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70024, topic: "climate-science", difficulty: "hard",
    question: "Why do sulfate aerosols usually exert a cooling influence on climate?",
    options: ["Scattering sunlight and brightening clouds","They strongly absorb all outgoing infrared radiation like CO₂","They increase solar luminosity","They eliminate water vapour from the atmosphere"],
    correctIndex: 0,
    explanation: "Many sulfate aerosols directly scatter sunlight and indirectly alter cloud droplet properties, producing a net negative radiative forcing.",
    realWorld: "Aerosol cooling partially offsets greenhouse-gas warming but is shorter-lived and spatially heterogeneous.",
    hint: "Think about increasing the fraction of incoming solar energy reflected back to space.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70025, topic: "climate-science", difficulty: "hard",
    question: "Why does the ocean strongly affect the pace of surface climate change?",
    options: ["Seawater cannot store heat","Large heat capacity and ocean circulation","Ocean currents stop whenever atmospheric CO₂ rises","Only the deep ocean receives solar energy"],
    correctIndex: 1,
    explanation: "The ocean's high heat capacity and overturning circulation let it take up most of the excess heat accumulated by the climate system, delaying and redistributing surface warming.",
    realWorld: "Ocean heat content is therefore a central indicator of planetary energy imbalance and affects sea level through thermal expansion.",
    hint: "The relevant property is the ability of a vast water reservoir to store and move heat.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 70026, topic: "climate-science", difficulty: "sota",
    question: "IPCC AR6 assessed the likely range of equilibrium climate sensitivity as approximately:",
    options: ["0.5–1.0°C","6.0–9.0°C","2.5–4.0°C","10–15°C"],
    correctIndex: 2,
    explanation: "Using multiple lines of evidence, IPCC AR6 assessed ECS as likely between 2.5°C and 4.0°C and very likely between 2.0°C and 5.0°C.",
    realWorld: "Narrowing the plausible sensitivity range improves long-term warming projections and carbon-budget analysis.",
    hint: "The assessed central value is around three degrees for doubled CO₂.",
    sources: [{"title":"IPCC AR6 Working Group I, Chapter 7","url":"https://www.ipcc.ch/report/ar6/wg1/chapter/chapter-7/","publisher":"IPCC","year":2021}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 70009, topic: "climate-science", difficulty: "sota",
    question: "What did IPCC AR6 conclude about the Atlantic Meridional Overturning Circulation (AMOC) during the 21st century?",
    options: ["It is very likely to strengthen in every scenario","It has already permanently collapsed","Its future cannot be assessed at all","Likely weakening; abrupt pre-2100 collapse not expected"],
    correctIndex: 3,
    explanation: "AR6 assesses that the AMOC is very likely to weaken during the 21st century across considered scenarios, while an abrupt collapse before 2100 is not expected, though low-probability high-impact outcomes remain important.",
    realWorld: "AMOC changes influence regional sea level, heat transport, rainfall patterns, and marine ecosystems.",
    hint: "Separate the high-confidence direction of change from the lower-probability collapse scenario.",
    sources: [{"title":"IPCC AR6 Synthesis Report longer report","url":"https://www.ipcc.ch/report/ar6/syr/longer-report/","publisher":"IPCC","year":2023}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 70027, topic: "climate-science", difficulty: "sota",
    question: "Modern detection-and-attribution studies distinguish human influence from natural variability primarily by:",
    options: ["Observed fingerprints compared with forcing models","Assuming every warm year has the same cause","Using only one thermometer record","Ignoring volcanic and solar forcing"],
    correctIndex: 0,
    explanation: "Attribution combines observations, physical understanding, and climate-model experiments driven by greenhouse gases, aerosols, solar variability, volcanic forcing, and internal variability.",
    realWorld: "This fingerprint approach underpins the IPCC conclusion that human influence has unequivocally warmed the atmosphere, ocean, and land.",
    hint: "The method compares characteristic patterns expected from competing physical causes.",
    sources: [{"title":"IPCC AR6 Working Group I Summary for Policymakers","url":"https://www.ipcc.ch/report/ar6/wg1/chapter/summary-for-policymakers/","publisher":"IPCC","year":2021}],
    reviewedAt: "2026-09-19",
  },
];
