import type { Question } from '../types';

export const astrophysicsQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────
  {
    id: 71001, topic: "astrophysics", difficulty: "easy",
    question: "The Hertzsprung-Russell diagram classically compares stellar:",
    options: ["Luminosity and surface temperature","Mass and orbital eccentricity","Distance and radial velocity","Age and rotation period"],
    correctIndex: 0,
    explanation: "The H-R diagram places luminosity or absolute magnitude against temperature or spectral type, revealing the main sequence, giants, supergiants, and white dwarfs.",
    realWorld: "A star's location on the H-R diagram is a powerful clue to its mass, evolutionary stage, and energy output.",
    hint: "Think brightness on one axis and colour or temperature on the other.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 71002, topic: "astrophysics", difficulty: "easy",
    question: "A neutron star can form when:",
    options: ["A low-mass red dwarf simply cools for a few years","Core collapse of a sufficiently massive star","A planet accretes an atmosphere","A comet crosses the Roche limit"],
    correctIndex: 1,
    explanation: "When a massive star develops an unstable iron core, collapse can compress the remnant to nuclear densities; if the remnant is not too massive, a neutron star can remain.",
    realWorld: "Pulsars and magnetars are observational manifestations of neutron stars with extreme rotation and magnetic fields.",
    hint: "The object is a compact remnant of stellar core collapse.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 71003, topic: "astrophysics", difficulty: "easy",
    question: "The dominant energy source of a main-sequence star is:",
    options: ["Chemical combustion","Radioactive decay of uranium","Hydrogen fusion into helium","Accretion from an external disk"],
    correctIndex: 2,
    explanation: "Main-sequence stars are powered primarily by nuclear fusion that converts hydrogen into helium and releases binding energy.",
    realWorld: "The proton-proton chain dominates in stars like the Sun, while the CNO cycle becomes more important at higher core temperatures.",
    hint: "Look for the nuclear process that defines the main-sequence phase.",
    reviewedAt: "2026-09-19",
  },

  // ── HARD ──────────────────────────────────────────────
  {
    id: 71004, topic: "astrophysics", difficulty: "hard",
    question: "The Eddington luminosity marks the scale where outward force from radiation on ionized gas balances:",
    options: ["Magnetic tension","Electron degeneracy pressure","Centrifugal force only","Gravity"],
    correctIndex: 3,
    explanation: "At the Eddington luminosity, outward radiative force on the gas can balance inward gravitational attraction under the assumptions of the standard derivation.",
    realWorld: "Eddington ratios are widely used to characterize luminous accreting black holes and massive stars.",
    hint: "The competition is between light pushing outward and the central mass pulling inward.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 71005, topic: "astrophysics", difficulty: "hard",
    question: "Type Ia supernovae are useful for measuring cosmological distances mainly because:",
    options: ["Standardizable light-curve and colour relations","Every event explodes at exactly the same mass and brightness","They occur only in galaxies of known distance","Their spectra contain no heavy elements"],
    correctIndex: 0,
    explanation: "Type Ia supernovae are not perfectly identical, but their luminosities can be standardized using relationships involving light-curve shape and colour.",
    realWorld: "Standardized Type Ia supernovae provided key evidence for the accelerated expansion of the Universe.",
    hint: "The key word is standardized, not intrinsically identical.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 71006, topic: "astrophysics", difficulty: "hard",
    question: "The Tolman-Oppenheimer-Volkoff limit refers to the maximum mass of a cold, non-rotating:",
    options: ["White dwarf","Neutron star","Brown dwarf","Main-sequence star"],
    correctIndex: 1,
    explanation: "The TOV limit is the relativistic maximum mass that a neutron star can support for a given equation of state; above it, collapse to a black hole is expected.",
    realWorld: "Observed massive neutron stars and merger measurements constrain the dense-matter equation of state and therefore the allowed TOV limit.",
    hint: "It is the relativistic compact-star analogue of a white-dwarf mass limit.",
    reviewedAt: "2026-09-19",
  },

  // ── SOTA ──────────────────────────────────────────────
  {
    id: 71007, topic: "astrophysics", difficulty: "sota",
    question: "GW170817 was a landmark because astronomers detected the same neutron-star merger through:",
    options: ["Neutrinos without a gravitational-wave counterpart","Cosmic rays without an identified transient source","Gravitational waves and light","Optical light without a gravitational-wave signal"],
    correctIndex: 2,
    explanation: "GW170817 was the first binary-neutron-star merger detected in gravitational waves and was followed across the electromagnetic spectrum, inaugurating gravitational-wave multi-messenger astronomy.",
    realWorld: "The event linked compact-object dynamics to a kilonova and provided evidence that neutron-star mergers contribute to heavy r-process nucleosynthesis.",
    hint: "Two fundamentally different astronomical messengers arrived from one event.",
    paper: {"title":"GW170817: Observation of Gravitational Waves from a Binary Neutron Star Inspiral","url":"https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.119.161101","venue":"Physical Review Letters","year":2017},
    reviewedAt: "2026-09-19",
  },
  {
    id: 71008, topic: "astrophysics", difficulty: "sota",
    question: "The Event Horizon Telescope's 2019 M87* image most directly resolved:",
    options: ["Hawking radiation from the event horizon","A traversable wormhole throat","The singularity itself","Emission surrounding a black-hole shadow"],
    correctIndex: 3,
    explanation: "The EHT resolved an asymmetric emission ring around a central brightness depression whose scale is consistent with the expected shadow of a Kerr black hole.",
    realWorld: "Earth-sized very-long-baseline interferometry opened direct horizon-scale tests of accretion physics and strong-field gravity.",
    hint: "The image is of lensed emission around the hole, not a photograph of the singularity.",
    paper: {"title":"First M87 Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole","url":"https://arxiv.org/abs/1906.11238","venue":"The Astrophysical Journal Letters","year":2019},
    reviewedAt: "2026-09-19",
  },
  {
    id: 71009, topic: "astrophysics", difficulty: "sota",
    question: "JWST spectroscopy confirming luminous galaxies around redshift 14 is important because it:",
    options: ["How rapidly galaxies formed at cosmic dawn","Proves the standard cosmological model is false","Shows galaxies existed before the Big Bang","Measures dark matter particles directly"],
    correctIndex: 0,
    explanation: "Spectroscopic redshifts near 14 confirm galaxies at extremely early cosmic times and provide strong constraints on star-formation efficiency, galaxy growth, and models of cosmic dawn.",
    realWorld: "The observations sharpen tests of early-galaxy models without by themselves invalidating ΛCDM.",
    hint: "The significance is early, spectroscopically confirmed galaxy growth, not a direct falsification of cosmology.",
    paper: {"title":"Spectroscopic confirmation of two luminous galaxies at a redshift of 14","url":"https://www.nature.com/articles/s41586-024-07860-9","venue":"Nature","year":2024},
    reviewedAt: "2026-09-19",
  },

  // ── DEPTH EXPANSION ──────────────────────────────────
  {
    id: 71010, topic: "astrophysics", difficulty: "easy",
    question: "When a nearby star shows annual parallax, the apparent shift is caused mainly by:",
    options: ["The star's intrinsic pulsation","Earth's changing orbital viewpoint","Interstellar dust drifting past","The Galaxy's differential rotation"],
    correctIndex: 1,
    explanation: "Annual parallax is the apparent angular displacement of a nearby star as Earth observes it from different positions in its orbit around the Sun.",
    realWorld: "Astrometric missions use parallax as a geometric distance measurement that anchors many other rungs of the cosmic distance ladder.",
    hint: "The baseline comes from the observer moving around the Sun.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71011, topic: "astrophysics", difficulty: "easy",
    question: "Dark absorption lines in a stellar spectrum are especially useful because they reveal:",
    options: ["Only the star's distance","Only its total luminosity","Chemical species in its atmosphere","The number of orbiting planets"],
    correctIndex: 2,
    explanation: "Atoms and ions absorb photons at characteristic wavelengths, so absorption-line patterns identify chemical species and also constrain temperature, pressure, and motion.",
    realWorld: "Spectroscopy lets astronomers infer stellar composition and radial velocity without physically sampling a star.",
    hint: "Each atomic species has characteristic transitions.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71012, topic: "astrophysics", difficulty: "easy",
    question: "A typical white dwarf is supported against further gravitational collapse primarily by:",
    options: ["Electron degeneracy pressure","Continuous hydrogen burning","Radiation pressure from a disk","Rapid orbital motion"],
    correctIndex: 0,
    explanation: "Electron degeneracy pressure, arising from the Pauli exclusion principle, supports ordinary white dwarfs after sustained core fusion has ended.",
    realWorld: "This quantum-mechanical support leads to the Chandrasekhar mass scale, above which a cold non-rotating white dwarf cannot remain stable.",
    hint: "The support is quantum mechanical rather than thermal fusion pressure.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71013, topic: "astrophysics", difficulty: "hard",
    question: "For a self-gravitating system in virial equilibrium, the scalar virial theorem implies approximately:",
    options: ["K + U = 0","K = U","2K + U = 0","2U + K = 0"],
    correctIndex: 2,
    explanation: "For a bound system in steady virial equilibrium with the usual inverse-distance gravitational potential, twice the total kinetic energy plus the potential energy is approximately zero.",
    realWorld: "Astronomers use virial reasoning to estimate masses of star clusters and galaxy clusters from measured velocity dispersions and sizes.",
    hint: "The kinetic term carries the factor of two.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71014, topic: "astrophysics", difficulty: "hard",
    question: "For a non-rotating black hole of mass M, the Schwarzschild radius is:",
    options: ["GM/c²","2GM/c²","GM²/c²","2GM/c"],
    correctIndex: 1,
    explanation: "The Schwarzschild event horizon in general relativity occurs at radial coordinate r = 2GM/c² for an isolated, non-rotating, uncharged black hole.",
    realWorld: "The scaling makes a ten-solar-mass black hole's horizon tens of kilometres across, while supermassive black-hole horizons can span astronomical scales.",
    hint: "Remember the factor of two in the Schwarzschild solution.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71015, topic: "astrophysics", difficulty: "hard",
    question: "The Jeans instability criterion describes when a gas cloud is most likely to:",
    options: ["Become transparent to neutrinos","Collapse under its own gravity","Reach the Eddington luminosity","Evaporate through Hawking radiation"],
    correctIndex: 1,
    explanation: "When self-gravity overwhelms pressure support on a sufficiently large scale or mass, perturbations in a gas cloud can grow rather than oscillate, producing gravitational collapse.",
    realWorld: "Jeans-type arguments provide a first estimate of which regions in molecular clouds can fragment and begin forming stars.",
    hint: "Compare gravitational binding with pressure support.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 71016, topic: "astrophysics", difficulty: "sota",
    question: "The GRAVITY collaboration's observations of the star S2 near Sagittarius A* detected which relativistic orbital effect?",
    options: ["A cosmological redshift drift","A Shapiro delay from Jupiter","Schwarzschild orbital precession","A binary-pulsar spin flip"],
    correctIndex: 2,
    explanation: "GRAVITY measured a prograde relativistic precession of S2's orbit consistent with the Schwarzschild prediction for motion around the Milky Way's central compact mass.",
    realWorld: "Tracking S-stars provides a strong-field laboratory for testing gravity around the roughly four-million-solar-mass object at the Galactic Centre.",
    hint: "The measured change concerns the orientation of S2's orbit after periapse.",
    paper: {"title":"Detection of the Schwarzschild precession in the orbit of the star S2 near the Galactic centre massive black hole","url":"https://www.aanda.org/articles/aa/full_html/2020/05/aa37813-20/aa37813-20.html","venue":"Astronomy & Astrophysics","year":2020},
    reviewedAt: "2026-09-21",
    factualAsOf: "2026-09-21",
  },
  {
    id: 71017, topic: "astrophysics", difficulty: "sota",
    question: "The first direct gravitational-wave detection, GW150914, came from the merger of:",
    options: ["Two white dwarfs","Two stellar-mass black holes","Two supermassive black holes","A neutron star and a planet"],
    correctIndex: 1,
    explanation: "LIGO detected a transient gravitational-wave signal consistent with the inspiral and merger of two stellar-mass black holes, followed by ringdown of the remnant.",
    realWorld: "GW150914 opened gravitational-wave astronomy and demonstrated that heavy stellar-mass binary black holes exist and merge within the age of the Universe.",
    hint: "The landmark 2015 signal was a binary black-hole merger.",
    paper: {"title":"Observation of Gravitational Waves from a Binary Black Hole Merger","url":"https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.061102","venue":"Physical Review Letters","year":2016},
    reviewedAt: "2026-09-21",
    factualAsOf: "2026-09-21",
  },
  {
    id: 71018, topic: "astrophysics", difficulty: "sota",
    question: "The NANOGrav 15-year data set reported evidence for a nanohertz gravitational-wave background through:",
    options: ["Correlated timing variations among pulsars","Gamma-ray flashes from magnetars","Optical microlensing of quasars","Neutrino bursts from supernovae"],
    correctIndex: 0,
    explanation: "Pulsar timing arrays search for spatially correlated deviations in pulse arrival times; NANOGrav reported evidence for Hellings-Downs-like correlations consistent with a gravitational-wave background.",
    realWorld: "Nanohertz gravitational waves probe sources and epochs inaccessible to ground-based interferometers, with supermassive black-hole binaries a leading expected contributor.",
    hint: "The detector is a galaxy-scale network of exceptionally stable clocks.",
    paper: {"title":"The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background","url":"https://iopscience.iop.org/article/10.3847/2041-8213/acdac6","venue":"The Astrophysical Journal Letters","year":2023},
    reviewedAt: "2026-09-21",
    factualAsOf: "2026-09-21",
  },
];
