import type { Question } from '../types';

export const chemistryQuestions: Question[] = [
  // ── Physical Chemistry ──────────────────────────────────────
  {
    id: 40001, topic: 'physical-chemistry', difficulty: 'easy',
    question: 'The ideal gas law is expressed as:',
    options: ['$P = nRT/V^2$', '$PV^2 = nRT$', '$PV = nRT$', '$PV = nR/T$'],
    correctIndex: 2,
    explanation: 'The ideal gas law $PV = nRT$ relates pressure, volume, amount, and temperature of an ideal gas.',
    realWorld: 'Used in engineering to design pressurized containers, HVAC systems, and chemical reactors.',
    hint: 'The equation combines pressure-volume work with amount and absolute temperature.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40002, topic: 'physical-chemistry', difficulty: 'hard',
    question: 'The Clausius-Clapeyron equation relates:',
    options: ['Reaction rate and concentration', 'Vapor pressure and temperature during phase transitions', 'Diffusion rate and molecular weight', 'Entropy production and reaction order'],
    correctIndex: 1,
    explanation: 'The Clausius-Clapeyron equation $\\frac{dP}{dT} = \\frac{\\Delta H_{vap}}{T \\Delta V}$ describes how coexistence pressure changes with temperature during a phase transition.',
    realWorld: 'It helps estimate boiling-point shifts with altitude and supports distillation and phase-equilibrium calculations.',
    hint: 'Think about how a liquid-vapor coexistence curve moves when temperature changes.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40003, topic: 'physical-chemistry', difficulty: 'sota',
    question: 'In transition state theory, the rate constant $k$ is given by $k = \\frac{k_B T}{h} e^{-\\Delta G^\\ddagger / RT}$. What does $\\Delta G^\\ddagger$ represent?',
    options: ['Enthalpy of the products', 'Entropy change of the surroundings', 'Mean kinetic energy of reactants', 'Gibbs free energy of activation'],
    correctIndex: 3,
    explanation: 'The Eyring equation uses the Gibbs free energy of activation $\\Delta G^\\ddagger$, the free-energy barrier separating reactants from the transition-state region.',
    realWorld: 'Rate-theory models are used to estimate temperature-dependent reaction rates in catalysis, atmospheric chemistry, and drug stability.',
    hint: 'The double dagger denotes the barrier region rather than either stable endpoint.',
    sources: [
      {
        title: 'Current Status of Transition-State Theory',
        url: 'https://pubs.acs.org/doi/10.1021/jp953748q',
        publisher: 'American Chemical Society',
        year: 1996,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40010, topic: 'physical-chemistry', difficulty: 'easy',
    question: 'Which statement is a direct consequence of Hess\'s law?',
    options: ['Activation energy is independent of catalysts', 'Entropy is zero for every crystal at 0 K', 'Reaction enthalpy depends only on the initial and final states', 'Equilibrium constants are independent of temperature'],
    correctIndex: 2,
    explanation: 'Because enthalpy is a state function, the total enthalpy change for a reaction is the same whether the reaction occurs in one step or through several intermediate steps.',
    realWorld: 'Hess\'s law lets chemists combine tabulated combustion or formation data to estimate heats for reactions that are difficult to measure directly.',
    hint: 'Focus on a thermodynamic quantity that depends on endpoints rather than the route between them.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40011, topic: 'physical-chemistry', difficulty: 'easy',
    question: 'For a dilute solution of a nonvolatile nonelectrolyte, adding more solute generally causes the solvent freezing point to:',
    options: ['Decrease according to a colligative effect', 'Increase in proportion to vapor pressure', 'Remain exactly unchanged', 'Jump to the solvent boiling point'],
    correctIndex: 0,
    explanation: 'Freezing-point depression is a colligative property: at low concentration its magnitude depends primarily on the number of dissolved particles rather than their chemical identity.',
    realWorld: 'This principle underlies road de-icing and the use of antifreeze formulations to lower the freezing temperature of liquids.',
    hint: 'Dissolved particles stabilize the liquid solution relative to the pure solid solvent.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40012, topic: 'physical-chemistry', difficulty: 'hard',
    question: 'At phase equilibrium between liquid water and its vapor at fixed temperature, which condition must hold for water?',
    options: ['The liquid has zero entropy', 'The vapor has zero enthalpy', 'The two phases have identical molar volumes', 'The chemical potential is equal in both phases'],
    correctIndex: 3,
    explanation: 'For a component at equilibrium across coexisting phases, its chemical potential must be equal in each phase; otherwise there is a thermodynamic driving force for net transfer.',
    realWorld: 'Equality of chemical potentials is the basis of phase-diagram calculations used in separations, materials processing, and atmospheric modeling.',
    hint: 'Equilibrium removes the driving force for matter to move from one phase to the other.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40013, topic: 'physical-chemistry', difficulty: 'hard',
    question: 'In the canonical ensemble, the probability of a microstate with energy $E_i$ is proportional to:',
    options: ['$E_i/k_BT$', '$e^{-E_i/(k_BT)}$', '$e^{+E_i/(k_BT)}$', '$1/E_i^2$'],
    correctIndex: 1,
    explanation: 'A canonical ensemble assigns each microstate a Boltzmann weight $e^{-E_i/(k_BT)}$; dividing by the partition function normalizes these weights into probabilities.',
    realWorld: 'Boltzmann weighting connects molecular energy landscapes to measurable averages such as heat capacities, populations, and equilibrium observables.',
    hint: 'Higher-energy states become less probable through an exponential factor.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40014, topic: 'physical-chemistry', difficulty: 'sota',
    question: 'Marcus theory predicts an "inverted region" for some electron-transfer reactions. What happens there as the reaction becomes even more thermodynamically favorable?',
    options: ['The electron-transfer rate must become diffusion-limited and stay constant', 'The reorganization energy vanishes', 'The electron-transfer rate can decrease after passing its maximum', 'The activation barrier becomes independent of molecular structure'],
    correctIndex: 2,
    explanation: 'In Marcus theory, the activation free energy depends on both the driving force and reorganization energy. Beyond the activationless condition, increasing the driving force can increase the barrier again, producing the inverted region.',
    realWorld: 'Marcus theory is central to interpreting charge transfer in electrochemistry, photosynthesis, molecular electronics, and energy-conversion materials.',
    hint: 'The surprising prediction is non-monotonic: "more downhill" does not always mean "faster."',
    sources: [
      {
        title: 'The Nobel Prize in Chemistry 1992',
        url: 'https://www.nobelprize.org/prizes/chemistry/1992/summary/',
        publisher: 'Nobel Prize Outreach',
        year: 1992,
      },
      {
        title: 'Recent Advances in the Theory and Molecular Simulation of Biological Electron Transfer Reactions',
        url: 'https://pubs.acs.org/doi/10.1021/acs.chemrev.5b00298',
        publisher: 'American Chemical Society',
        year: 2015,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40015, topic: 'physical-chemistry', difficulty: 'sota',
    question: 'In variational transition-state theory, why is the dividing surface adjusted away from a simple saddle-point choice?',
    options: ['To force every trajectory to recross the barrier', 'To make the equilibrium constant equal to one', 'To eliminate the need for a potential-energy surface', 'To minimize the calculated rate by reducing recrossing error'],
    correctIndex: 3,
    explanation: 'Variational transition-state theory searches over possible dividing surfaces and selects the one giving the smallest transition-state-theory rate, which reduces overcounting caused by trajectories that recross.',
    realWorld: 'Variational rate methods improve kinetic predictions for reactions where a single geometric saddle point is not an adequate dynamical bottleneck.',
    hint: 'Conventional transition-state theory overestimates a rate when trajectories cross the chosen surface more than once.',
    sources: [
      {
        title: 'Current Status of Transition-State Theory',
        url: 'https://pubs.acs.org/doi/10.1021/jp953748q',
        publisher: 'American Chemical Society',
        year: 1996,
      },
    ],
    reviewedAt: '2026-09-19',
  },

  // ── Organic Chemistry ──────────────────────────────────────
  {
    id: 40004, topic: 'organic-chemistry', difficulty: 'easy',
    question: 'What type of reaction is the addition of HBr to an alkene under ordinary ionic conditions?',
    options: ['Nucleophilic substitution', 'Elimination', 'Electrophilic addition', 'Nucleophilic acyl substitution'],
    correctIndex: 2,
    explanation: 'The electron-rich alkene reacts with an electrophilic proton and then bromide adds, so the net transformation is an electrophilic addition across the double bond.',
    realWorld: 'Electrophilic additions are core transformations in chemical synthesis and in routes to monomers, intermediates, and pharmaceuticals.',
    hint: 'Classify the reaction by what first attacks the electron-rich pi bond.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40005, topic: 'organic-chemistry', difficulty: 'hard',
    question: 'At a stereogenic carbon, an idealized SN2 substitution normally gives which stereochemical outcome?',
    options: ['Complete retention', 'Inversion of configuration', 'A planar carbocation followed by racemization', 'No defined stereochemical relationship'],
    correctIndex: 1,
    explanation: 'SN2 substitution occurs through backside attack on the carbon bearing the leaving group, producing Walden inversion when that carbon is stereogenic.',
    realWorld: 'Controlling substitution stereochemistry is essential in medicinal chemistry because different stereoisomers can have very different biological effects.',
    hint: 'Picture the nucleophile approaching from the side opposite the leaving group.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40006, topic: 'organic-chemistry', difficulty: 'sota',
    question: 'The Woodward-Hoffmann rules predict the stereochemical outcome of pericyclic reactions primarily from:',
    options: ['Product boiling points', 'Solvent dielectric constants', 'Steric size alone', 'Conservation of orbital symmetry'],
    correctIndex: 3,
    explanation: 'Woodward-Hoffmann analysis tracks orbital symmetry through a concerted reaction coordinate to determine which thermal or photochemical pathways are symmetry-allowed.',
    realWorld: 'Orbital-symmetry reasoning guides the design of electrocyclic, cycloaddition, and sigmatropic steps in complex-molecule synthesis.',
    hint: 'The key constraint concerns how occupied molecular orbitals can transform continuously during a concerted reaction.',
    sources: [
      {
        title: 'Woodward–Hoffmann’s Stereochemistry of Electrocyclic Reactions: From Day 1 to the JACS Receipt Date',
        url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11393748/',
        publisher: 'National Library of Medicine',
        year: 2015,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40016, topic: 'organic-chemistry', difficulty: 'easy',
    question: 'A planar, cyclic, fully conjugated molecule is aromatic under Hückel\'s rule when it contains:',
    options: ['$4n$ pi electrons', '$(4n+2)$ pi electrons', 'Exactly two sigma bonds', 'An odd number of carbon atoms'],
    correctIndex: 1,
    explanation: 'Hückel\'s rule states that a planar cyclic conjugated system with $(4n+2)$ pi electrons is aromatic, whereas a comparable $4n$ system is antiaromatic if it remains planar and conjugated.',
    realWorld: 'Aromaticity helps predict stability, spectroscopy, and substitution behavior in molecules used throughout pharmaceuticals, dyes, and materials.',
    hint: 'The familiar aromatic sequence begins 2, 6, 10, 14, ... pi electrons.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40017, topic: 'organic-chemistry', difficulty: 'easy',
    question: 'Under typical oxidation conditions, an aldehyde is most directly converted into a:',
    options: ['Ketone with the same carbon skeleton', 'Primary amine', 'Terminal alkene', 'Carboxylic acid'],
    correctIndex: 3,
    explanation: 'Aldehydes are readily oxidized at the carbonyl carbon to carboxylic acids because the aldehydic hydrogen can be replaced effectively by a hydroxyl group during oxidation.',
    realWorld: 'Selective oxidation state changes are routine in synthesis, process chemistry, and biochemical pathways involving alcohols, aldehydes, and acids.',
    hint: 'Move the carbonyl carbon one oxidation level higher without changing its carbon count.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40018, topic: 'organic-chemistry', difficulty: 'hard',
    question: 'Why is the endo product often kinetically favored in a classic Diels-Alder reaction even when the exo product may be less sterically crowded?',
    options: ['The diene becomes aromatic before bond formation', 'The reaction proceeds through a free carbocation', 'Secondary orbital interactions can stabilize the endo transition state', 'The exo pathway is forbidden by conservation of mass'],
    correctIndex: 2,
    explanation: 'The traditional explanation for endo selectivity invokes favorable secondary orbital interactions between the diene and electron-withdrawing substituent orbitals in the endo transition-state geometry.',
    realWorld: 'Diels-Alder stereocontrol is widely used to build rings and multiple stereocenters efficiently in natural-product and pharmaceutical synthesis.',
    hint: 'Compare the two transition states rather than only the steric crowding of the final products.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40019, topic: 'organic-chemistry', difficulty: 'hard',
    question: 'For an unsymmetrical ketone, which conditions most strongly favor formation of the kinetic enolate?',
    options: ['A bulky strong base at low temperature with short reaction time', 'A weak acid at high temperature until equilibrium', 'Excess water and prolonged heating', 'A nucleophilic catalyst under strongly protic conditions'],
    correctIndex: 0,
    explanation: 'A bulky strong base such as LDA at low temperature removes the most accessible alpha proton rapidly, favoring the enolate formed fastest rather than the most substituted equilibrium enolate.',
    realWorld: 'Kinetic versus thermodynamic enolate control is a standard strategy for choosing which carbon-carbon bond forms in regioselective synthesis.',
    hint: 'Kinetic control rewards the fastest deprotonation and suppresses equilibration.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40020, topic: 'organic-chemistry', difficulty: 'sota',
    question: 'What key change makes the copper-catalyzed azide-alkyne cycloaddition (CuAAC) especially useful as a click reaction compared with the uncatalyzed thermal process?',
    options: ['It converts the alkyne into an alkane before cyclization', 'It requires strongly acidic water-free conditions', 'It accelerates the reaction and strongly favors a specific triazole connectivity', 'It replaces the azide with a carbonyl compound'],
    correctIndex: 2,
    explanation: 'Copper(I) catalysis makes azide-alkyne cycloaddition fast and highly selective, producing predominantly the 1,4-disubstituted 1,2,3-triazole connectivity under practical conditions.',
    realWorld: 'CuAAC is used to assemble probes, materials, drug conjugates, and molecular libraries with high reliability.',
    hint: 'The catalyst improves both practical rate and regioselectivity.',
    sources: [
      {
        title: 'Press release: The Nobel Prize in Chemistry 2022',
        url: 'https://www.nobelprize.org/prizes/chemistry/2022/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2022,
      },
      {
        title: 'K. Barry Sharpless — Research Focus',
        url: 'https://www.scripps.edu/faculty/sharpless/',
        publisher: 'Scripps Research',
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40021, topic: 'organic-chemistry', difficulty: 'sota',
    question: 'What defines a bioorthogonal reaction in the sense developed for chemistry inside living systems?',
    options: ['It must use only naturally occurring enzymes', 'It reacts selectively in a biological environment without disrupting native biochemical processes', 'It must generate ATP as its driving force', 'It can occur only outside intact cells'],
    correctIndex: 1,
    explanation: 'Bioorthogonal chemistry uses mutually selective chemical handles that can react in complex biological environments while leaving native biomolecules and cellular chemistry largely undisturbed.',
    realWorld: 'Bioorthogonal reactions enable live-cell labeling, molecular imaging, biomolecule tracking, and targeted therapeutic strategies.',
    hint: 'The defining requirement is compatibility with native biology, not merely high reaction yield.',
    sources: [
      {
        title: 'Scientific background: Click chemistry and bioorthogonal chemistry',
        url: 'https://www.nobelprize.org/prizes/chemistry/2022/advanced-information/',
        publisher: 'Nobel Prize Outreach',
        year: 2022,
      },
    ],
    reviewedAt: '2026-09-19',
  },

  // ── Inorganic Chemistry ──────────────────────────────────────
  {
    id: 40007, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'Crystal field theory predicts that an octahedral d⁶ complex with sufficiently strong-field ligands is typically:',
    options: ['High-spin with four unpaired electrons', 'Necessarily tetrahedral', 'Low-spin with all electrons paired', 'Unable to form metal-ligand bonds'],
    correctIndex: 2,
    explanation: 'When octahedral crystal-field splitting is larger than the pairing-energy cost, six d electrons occupy the lower-energy $t_{2g}$ set as paired electrons before occupying $e_g$, giving a low-spin state.',
    realWorld: 'Spin state strongly affects color, magnetism, reactivity, and electronic behavior in coordination compounds and functional materials.',
    hint: 'Compare the energetic cost of pairing in the lower set with promotion to the upper set.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40008, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'In Wade\'s rules, a closo borane cluster $B_nH_n^{2-}$ has how many skeletal electron pairs?',
    options: ['$n
    explanation: 'Wade\'s rules assign a closo cluster $n+1$ skeletal electron pairs, corresponding to a closed deltahedral framework with $n$ vertices.',
    realWorld: 'Electron-counting rules help rationalize boranes, carboranes, and related clusters used in synthesis, catalysis, and boron-containing functional materials.',
    hint: 'Closo is the closed-cage member of the closo/nido/arachno sequence.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40009, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'The isolobal analogy relates organometallic fragments to main-group fragments primarily on the basis of:',
    options: ['Identical atomic radii', 'Equal formal oxidation states', 'Matching electronegativities', 'Similar frontier-orbital number, symmetry, energy, shape, and occupancy'],
    correctIndex: 3,
    explanation: 'Two fragments are isolobal when their relevant frontier orbitals are similar in number, symmetry properties, approximate energy and shape, and electron occupancy, allowing structural and reactivity analogies across organic and inorganic chemistry.',
    realWorld: 'The isolobal analogy provides a compact way to predict bonding patterns and plausible structures in organometallic and cluster chemistry.',
    hint: 'The analogy compares the orbitals available for making new bonds rather than bulk elemental properties.',
    sources: [
      {
        title: 'Building Bridges Between Inorganic and Organic Chemistry (Nobel Lecture)',
        url: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.198207113',
        publisher: 'Wiley',
        year: 1982,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40022, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the coordination number of cobalt in the complex ion $[Co(NH_3)_6]^{3+}$?',
    options: ['3', '4', '6', '9'],
    correctIndex: 2,
    explanation: 'Six ammonia ligands each donate one lone pair through one nitrogen donor atom, so cobalt has coordination number 6 in $[Co(NH_3)_6]^{3+}$.',
    realWorld: 'Coordination number is a first step toward predicting geometry, ligand-field splitting, and reactivity in metal complexes.',
    hint: 'Count the donor atoms directly bonded to the central metal.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40023, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the oxidation state of iron in $[Fe(CN)_6]^{4-}$?',
    options: ['+1', '+2', '+3', '+4'],
    correctIndex: 1,
    explanation: 'Each cyanide ligand contributes a -1 formal charge. With six cyanides the ligand charge is -6, so iron must be +2 to give the complex ion an overall charge of -4.',
    realWorld: 'Oxidation-state bookkeeping is essential for analyzing redox chemistry, coordination compounds, electrochemistry, and catalytic cycles.',
    hint: 'Set the metal oxidation state plus six ligand charges equal to the overall ion charge.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40024, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'Which octahedral d-electron configuration is especially prone to a strong Jahn-Teller distortion because of uneven occupation of the $e_g$ orbitals?',
    options: ['d³', 'low-spin d⁶', 'd¹⁰', 'd⁹'],
    correctIndex: 3,
    explanation: 'An octahedral d⁹ ion has three electrons distributed across the doubly degenerate antibonding $e_g$ set, creating strong electronic degeneracy that is commonly relieved by tetragonal Jahn-Teller distortion.',
    realWorld: 'Jahn-Teller distortions influence the structures, spectra, magnetism, and electron transport of many copper(II) complexes and solids.',
    hint: 'Look for a configuration with an unevenly occupied pair of strongly metal-ligand antibonding orbitals.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40025, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'For a square-planar Pt(II) complex, a ligand with a strong trans effect primarily influences:',
    options: ['The rate at which the ligand opposite it is substituted', 'The formal oxidation state of every spectator ligand', 'The total number of d electrons on free platinum atoms', 'Whether the complex must become tetrahedral at equilibrium'],
    correctIndex: 0,
    explanation: 'The trans effect is kinetic: certain ligands labilize the ligand trans to themselves, changing substitution rates and therefore controlling which products form during stepwise synthesis of square-planar complexes.',
    realWorld: 'Trans-effect control is used to plan syntheses of platinum coordination compounds, including routes to medically relevant Pt complexes.',
    hint: 'Distinguish a kinetic substitution effect from the structural trans influence on bond lengths.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40026, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'Which description best captures the construction principle of a metal-organic framework (MOF)?',
    options: ['A dense alloy formed only from metallic bonds', 'A molecular crystal held together exclusively by hydrogen bonding', 'Metal-containing nodes connected by organic linkers into an extended porous network', 'A polymer whose backbone contains no metal coordination sites'],
    correctIndex: 2,
    explanation: 'MOFs are extended crystalline networks assembled from metal ions or metal-containing clusters linked by multitopic organic molecules, creating designable pores and internal cavities.',
    realWorld: 'MOFs are investigated for gas storage and separation, carbon capture, catalysis, sensing, water harvesting, and other molecular-separation problems.',
    hint: 'Think of an extended scaffold built from inorganic connection points and organic struts.',
    sources: [
      {
        title: 'Press release: Nobel Prize in Chemistry 2025',
        url: 'https://www.nobelprize.org/prizes/chemistry/2025/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2025,
      },
    ],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 40027, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'In reticular chemistry, why is describing a framework by its underlying net useful?',
    options: ['It replaces all chemical composition information with atomic mass', 'It guarantees every framework has the same pore size', 'It proves the material cannot undergo structural flexibility', 'It separates connectivity/topology from specific building-block chemistry so architectures can be compared and designed'],
    correctIndex: 3,
    explanation: 'An underlying net captures how nodes and linkers are connected independently of many chemical details, letting chemists classify framework topologies and reason about which building-unit geometries can realize a target architecture.',
    realWorld: 'Topology-guided design helps researchers compare large MOF families and plan new porous frameworks with intended connectivity and function.',
    hint: 'A net is an abstraction of connection pattern, not a complete molecular formula.',
    sources: [
      {
        title: 'Deconstructing the Crystal Structures of Metal–Organic Frameworks and Related Materials into Their Underlying Nets',
        url: 'https://pubs.acs.org/doi/10.1021/cr200205j',
        publisher: 'American Chemical Society',
        year: 2012,
      },
      {
        title: 'Reticular Chemistry: Occurrence and Taxonomy of Nets and Grammar for the Design of Frameworks',
        url: 'https://pubs.acs.org/doi/10.1021/ar020022l',
        publisher: 'American Chemical Society',
        year: 2005,
      },
    ],
    reviewedAt: '2026-09-19',
  },
];
, '$n + 1
    explanation: 'Wade\'s rules assign a closo cluster $n+1$ skeletal electron pairs, corresponding to a closed deltahedral framework with $n$ vertices.',
    realWorld: 'Electron-counting rules help rationalize boranes, carboranes, and related clusters used in synthesis, catalysis, and boron-containing functional materials.',
    hint: 'Closo is the closed-cage member of the closo/nido/arachno sequence.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40009, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'The isolobal analogy relates organometallic fragments to main-group fragments primarily on the basis of:',
    options: ['Identical atomic radii', 'Equal formal oxidation states', 'Matching electronegativities', 'Similar frontier-orbital number, symmetry, energy, shape, and occupancy'],
    correctIndex: 3,
    explanation: 'Two fragments are isolobal when their relevant frontier orbitals are similar in number, symmetry properties, approximate energy and shape, and electron occupancy, allowing structural and reactivity analogies across organic and inorganic chemistry.',
    realWorld: 'The isolobal analogy provides a compact way to predict bonding patterns and plausible structures in organometallic and cluster chemistry.',
    hint: 'The analogy compares the orbitals available for making new bonds rather than bulk elemental properties.',
    sources: [
      {
        title: 'Building Bridges Between Inorganic and Organic Chemistry (Nobel Lecture)',
        url: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.198207113',
        publisher: 'Wiley',
        year: 1982,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40022, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the coordination number of cobalt in the complex ion $[Co(NH_3)_6]^{3+}$?',
    options: ['3', '4', '6', '9'],
    correctIndex: 2,
    explanation: 'Six ammonia ligands each donate one lone pair through one nitrogen donor atom, so cobalt has coordination number 6 in $[Co(NH_3)_6]^{3+}$.',
    realWorld: 'Coordination number is a first step toward predicting geometry, ligand-field splitting, and reactivity in metal complexes.',
    hint: 'Count the donor atoms directly bonded to the central metal.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40023, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the oxidation state of iron in $[Fe(CN)_6]^{4-}$?',
    options: ['+1', '+2', '+3', '+4'],
    correctIndex: 1,
    explanation: 'Each cyanide ligand contributes a -1 formal charge. With six cyanides the ligand charge is -6, so iron must be +2 to give the complex ion an overall charge of -4.',
    realWorld: 'Oxidation-state bookkeeping is essential for analyzing redox chemistry, coordination compounds, electrochemistry, and catalytic cycles.',
    hint: 'Set the metal oxidation state plus six ligand charges equal to the overall ion charge.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40024, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'Which octahedral d-electron configuration is especially prone to a strong Jahn-Teller distortion because of uneven occupation of the $e_g$ orbitals?',
    options: ['d³', 'low-spin d⁶', 'd¹⁰', 'd⁹'],
    correctIndex: 3,
    explanation: 'An octahedral d⁹ ion has three electrons distributed across the doubly degenerate antibonding $e_g$ set, creating strong electronic degeneracy that is commonly relieved by tetragonal Jahn-Teller distortion.',
    realWorld: 'Jahn-Teller distortions influence the structures, spectra, magnetism, and electron transport of many copper(II) complexes and solids.',
    hint: 'Look for a configuration with an unevenly occupied pair of strongly metal-ligand antibonding orbitals.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40025, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'For a square-planar Pt(II) complex, a ligand with a strong trans effect primarily influences:',
    options: ['The rate at which the ligand opposite it is substituted', 'The formal oxidation state of every spectator ligand', 'The total number of d electrons on free platinum atoms', 'Whether the complex must become tetrahedral at equilibrium'],
    correctIndex: 0,
    explanation: 'The trans effect is kinetic: certain ligands labilize the ligand trans to themselves, changing substitution rates and therefore controlling which products form during stepwise synthesis of square-planar complexes.',
    realWorld: 'Trans-effect control is used to plan syntheses of platinum coordination compounds, including routes to medically relevant Pt complexes.',
    hint: 'Distinguish a kinetic substitution effect from the structural trans influence on bond lengths.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40026, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'Which description best captures the construction principle of a metal-organic framework (MOF)?',
    options: ['A dense alloy formed only from metallic bonds', 'A molecular crystal held together exclusively by hydrogen bonding', 'Metal-containing nodes connected by organic linkers into an extended porous network', 'A polymer whose backbone contains no metal coordination sites'],
    correctIndex: 2,
    explanation: 'MOFs are extended crystalline networks assembled from metal ions or metal-containing clusters linked by multitopic organic molecules, creating designable pores and internal cavities.',
    realWorld: 'MOFs are investigated for gas storage and separation, carbon capture, catalysis, sensing, water harvesting, and other molecular-separation problems.',
    hint: 'Think of an extended scaffold built from inorganic connection points and organic struts.',
    sources: [
      {
        title: 'Press release: Nobel Prize in Chemistry 2025',
        url: 'https://www.nobelprize.org/prizes/chemistry/2025/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2025,
      },
    ],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 40027, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'In reticular chemistry, why is describing a framework by its underlying net useful?',
    options: ['It replaces all chemical composition information with atomic mass', 'It guarantees every framework has the same pore size', 'It proves the material cannot undergo structural flexibility', 'It separates connectivity/topology from specific building-block chemistry so architectures can be compared and designed'],
    correctIndex: 3,
    explanation: 'An underlying net captures how nodes and linkers are connected independently of many chemical details, letting chemists classify framework topologies and reason about which building-unit geometries can realize a target architecture.',
    realWorld: 'Topology-guided design helps researchers compare large MOF families and plan new porous frameworks with intended connectivity and function.',
    hint: 'A net is an abstraction of connection pattern, not a complete molecular formula.',
    sources: [
      {
        title: 'Deconstructing the Crystal Structures of Metal–Organic Frameworks and Related Materials into Their Underlying Nets',
        url: 'https://pubs.acs.org/doi/10.1021/cr200205j',
        publisher: 'American Chemical Society',
        year: 2012,
      },
      {
        title: 'Reticular Chemistry: Occurrence and Taxonomy of Nets and Grammar for the Design of Frameworks',
        url: 'https://pubs.acs.org/doi/10.1021/ar020022l',
        publisher: 'American Chemical Society',
        year: 2005,
      },
    ],
    reviewedAt: '2026-09-19',
  },
];
, '$n + 2
    explanation: 'Wade\'s rules assign a closo cluster $n+1$ skeletal electron pairs, corresponding to a closed deltahedral framework with $n$ vertices.',
    realWorld: 'Electron-counting rules help rationalize boranes, carboranes, and related clusters used in synthesis, catalysis, and boron-containing functional materials.',
    hint: 'Closo is the closed-cage member of the closo/nido/arachno sequence.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40009, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'The isolobal analogy relates organometallic fragments to main-group fragments primarily on the basis of:',
    options: ['Identical atomic radii', 'Equal formal oxidation states', 'Matching electronegativities', 'Similar frontier-orbital number, symmetry, energy, shape, and occupancy'],
    correctIndex: 3,
    explanation: 'Two fragments are isolobal when their relevant frontier orbitals are similar in number, symmetry properties, approximate energy and shape, and electron occupancy, allowing structural and reactivity analogies across organic and inorganic chemistry.',
    realWorld: 'The isolobal analogy provides a compact way to predict bonding patterns and plausible structures in organometallic and cluster chemistry.',
    hint: 'The analogy compares the orbitals available for making new bonds rather than bulk elemental properties.',
    sources: [
      {
        title: 'Building Bridges Between Inorganic and Organic Chemistry (Nobel Lecture)',
        url: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.198207113',
        publisher: 'Wiley',
        year: 1982,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40022, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the coordination number of cobalt in the complex ion $[Co(NH_3)_6]^{3+}$?',
    options: ['3', '4', '6', '9'],
    correctIndex: 2,
    explanation: 'Six ammonia ligands each donate one lone pair through one nitrogen donor atom, so cobalt has coordination number 6 in $[Co(NH_3)_6]^{3+}$.',
    realWorld: 'Coordination number is a first step toward predicting geometry, ligand-field splitting, and reactivity in metal complexes.',
    hint: 'Count the donor atoms directly bonded to the central metal.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40023, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the oxidation state of iron in $[Fe(CN)_6]^{4-}$?',
    options: ['+1', '+2', '+3', '+4'],
    correctIndex: 1,
    explanation: 'Each cyanide ligand contributes a -1 formal charge. With six cyanides the ligand charge is -6, so iron must be +2 to give the complex ion an overall charge of -4.',
    realWorld: 'Oxidation-state bookkeeping is essential for analyzing redox chemistry, coordination compounds, electrochemistry, and catalytic cycles.',
    hint: 'Set the metal oxidation state plus six ligand charges equal to the overall ion charge.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40024, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'Which octahedral d-electron configuration is especially prone to a strong Jahn-Teller distortion because of uneven occupation of the $e_g$ orbitals?',
    options: ['d³', 'low-spin d⁶', 'd¹⁰', 'd⁹'],
    correctIndex: 3,
    explanation: 'An octahedral d⁹ ion has three electrons distributed across the doubly degenerate antibonding $e_g$ set, creating strong electronic degeneracy that is commonly relieved by tetragonal Jahn-Teller distortion.',
    realWorld: 'Jahn-Teller distortions influence the structures, spectra, magnetism, and electron transport of many copper(II) complexes and solids.',
    hint: 'Look for a configuration with an unevenly occupied pair of strongly metal-ligand antibonding orbitals.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40025, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'For a square-planar Pt(II) complex, a ligand with a strong trans effect primarily influences:',
    options: ['The rate at which the ligand opposite it is substituted', 'The formal oxidation state of every spectator ligand', 'The total number of d electrons on free platinum atoms', 'Whether the complex must become tetrahedral at equilibrium'],
    correctIndex: 0,
    explanation: 'The trans effect is kinetic: certain ligands labilize the ligand trans to themselves, changing substitution rates and therefore controlling which products form during stepwise synthesis of square-planar complexes.',
    realWorld: 'Trans-effect control is used to plan syntheses of platinum coordination compounds, including routes to medically relevant Pt complexes.',
    hint: 'Distinguish a kinetic substitution effect from the structural trans influence on bond lengths.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40026, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'Which description best captures the construction principle of a metal-organic framework (MOF)?',
    options: ['A dense alloy formed only from metallic bonds', 'A molecular crystal held together exclusively by hydrogen bonding', 'Metal-containing nodes connected by organic linkers into an extended porous network', 'A polymer whose backbone contains no metal coordination sites'],
    correctIndex: 2,
    explanation: 'MOFs are extended crystalline networks assembled from metal ions or metal-containing clusters linked by multitopic organic molecules, creating designable pores and internal cavities.',
    realWorld: 'MOFs are investigated for gas storage and separation, carbon capture, catalysis, sensing, water harvesting, and other molecular-separation problems.',
    hint: 'Think of an extended scaffold built from inorganic connection points and organic struts.',
    sources: [
      {
        title: 'Press release: Nobel Prize in Chemistry 2025',
        url: 'https://www.nobelprize.org/prizes/chemistry/2025/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2025,
      },
    ],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 40027, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'In reticular chemistry, why is describing a framework by its underlying net useful?',
    options: ['It replaces all chemical composition information with atomic mass', 'It guarantees every framework has the same pore size', 'It proves the material cannot undergo structural flexibility', 'It separates connectivity/topology from specific building-block chemistry so architectures can be compared and designed'],
    correctIndex: 3,
    explanation: 'An underlying net captures how nodes and linkers are connected independently of many chemical details, letting chemists classify framework topologies and reason about which building-unit geometries can realize a target architecture.',
    realWorld: 'Topology-guided design helps researchers compare large MOF families and plan new porous frameworks with intended connectivity and function.',
    hint: 'A net is an abstraction of connection pattern, not a complete molecular formula.',
    sources: [
      {
        title: 'Deconstructing the Crystal Structures of Metal–Organic Frameworks and Related Materials into Their Underlying Nets',
        url: 'https://pubs.acs.org/doi/10.1021/cr200205j',
        publisher: 'American Chemical Society',
        year: 2012,
      },
      {
        title: 'Reticular Chemistry: Occurrence and Taxonomy of Nets and Grammar for the Design of Frameworks',
        url: 'https://pubs.acs.org/doi/10.1021/ar020022l',
        publisher: 'American Chemical Society',
        year: 2005,
      },
    ],
    reviewedAt: '2026-09-19',
  },
];
, '$2n
    explanation: 'Wade\'s rules assign a closo cluster $n+1$ skeletal electron pairs, corresponding to a closed deltahedral framework with $n$ vertices.',
    realWorld: 'Electron-counting rules help rationalize boranes, carboranes, and related clusters used in synthesis, catalysis, and boron-containing functional materials.',
    hint: 'Closo is the closed-cage member of the closo/nido/arachno sequence.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40009, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'The isolobal analogy relates organometallic fragments to main-group fragments primarily on the basis of:',
    options: ['Identical atomic radii', 'Equal formal oxidation states', 'Matching electronegativities', 'Similar frontier-orbital number, symmetry, energy, shape, and occupancy'],
    correctIndex: 3,
    explanation: 'Two fragments are isolobal when their relevant frontier orbitals are similar in number, symmetry properties, approximate energy and shape, and electron occupancy, allowing structural and reactivity analogies across organic and inorganic chemistry.',
    realWorld: 'The isolobal analogy provides a compact way to predict bonding patterns and plausible structures in organometallic and cluster chemistry.',
    hint: 'The analogy compares the orbitals available for making new bonds rather than bulk elemental properties.',
    sources: [
      {
        title: 'Building Bridges Between Inorganic and Organic Chemistry (Nobel Lecture)',
        url: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.198207113',
        publisher: 'Wiley',
        year: 1982,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40022, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the coordination number of cobalt in the complex ion $[Co(NH_3)_6]^{3+}$?',
    options: ['3', '4', '6', '9'],
    correctIndex: 2,
    explanation: 'Six ammonia ligands each donate one lone pair through one nitrogen donor atom, so cobalt has coordination number 6 in $[Co(NH_3)_6]^{3+}$.',
    realWorld: 'Coordination number is a first step toward predicting geometry, ligand-field splitting, and reactivity in metal complexes.',
    hint: 'Count the donor atoms directly bonded to the central metal.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40023, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the oxidation state of iron in $[Fe(CN)_6]^{4-}$?',
    options: ['+1', '+2', '+3', '+4'],
    correctIndex: 1,
    explanation: 'Each cyanide ligand contributes a -1 formal charge. With six cyanides the ligand charge is -6, so iron must be +2 to give the complex ion an overall charge of -4.',
    realWorld: 'Oxidation-state bookkeeping is essential for analyzing redox chemistry, coordination compounds, electrochemistry, and catalytic cycles.',
    hint: 'Set the metal oxidation state plus six ligand charges equal to the overall ion charge.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40024, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'Which octahedral d-electron configuration is especially prone to a strong Jahn-Teller distortion because of uneven occupation of the $e_g$ orbitals?',
    options: ['d³', 'low-spin d⁶', 'd¹⁰', 'd⁹'],
    correctIndex: 3,
    explanation: 'An octahedral d⁹ ion has three electrons distributed across the doubly degenerate antibonding $e_g$ set, creating strong electronic degeneracy that is commonly relieved by tetragonal Jahn-Teller distortion.',
    realWorld: 'Jahn-Teller distortions influence the structures, spectra, magnetism, and electron transport of many copper(II) complexes and solids.',
    hint: 'Look for a configuration with an unevenly occupied pair of strongly metal-ligand antibonding orbitals.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40025, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'For a square-planar Pt(II) complex, a ligand with a strong trans effect primarily influences:',
    options: ['The rate at which the ligand opposite it is substituted', 'The formal oxidation state of every spectator ligand', 'The total number of d electrons on free platinum atoms', 'Whether the complex must become tetrahedral at equilibrium'],
    correctIndex: 0,
    explanation: 'The trans effect is kinetic: certain ligands labilize the ligand trans to themselves, changing substitution rates and therefore controlling which products form during stepwise synthesis of square-planar complexes.',
    realWorld: 'Trans-effect control is used to plan syntheses of platinum coordination compounds, including routes to medically relevant Pt complexes.',
    hint: 'Distinguish a kinetic substitution effect from the structural trans influence on bond lengths.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40026, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'Which description best captures the construction principle of a metal-organic framework (MOF)?',
    options: ['A dense alloy formed only from metallic bonds', 'A molecular crystal held together exclusively by hydrogen bonding', 'Metal-containing nodes connected by organic linkers into an extended porous network', 'A polymer whose backbone contains no metal coordination sites'],
    correctIndex: 2,
    explanation: 'MOFs are extended crystalline networks assembled from metal ions or metal-containing clusters linked by multitopic organic molecules, creating designable pores and internal cavities.',
    realWorld: 'MOFs are investigated for gas storage and separation, carbon capture, catalysis, sensing, water harvesting, and other molecular-separation problems.',
    hint: 'Think of an extended scaffold built from inorganic connection points and organic struts.',
    sources: [
      {
        title: 'Press release: Nobel Prize in Chemistry 2025',
        url: 'https://www.nobelprize.org/prizes/chemistry/2025/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2025,
      },
    ],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 40027, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'In reticular chemistry, why is describing a framework by its underlying net useful?',
    options: ['It replaces all chemical composition information with atomic mass', 'It guarantees every framework has the same pore size', 'It proves the material cannot undergo structural flexibility', 'It separates connectivity/topology from specific building-block chemistry so architectures can be compared and designed'],
    correctIndex: 3,
    explanation: 'An underlying net captures how nodes and linkers are connected independently of many chemical details, letting chemists classify framework topologies and reason about which building-unit geometries can realize a target architecture.',
    realWorld: 'Topology-guided design helps researchers compare large MOF families and plan new porous frameworks with intended connectivity and function.',
    hint: 'A net is an abstraction of connection pattern, not a complete molecular formula.',
    sources: [
      {
        title: 'Deconstructing the Crystal Structures of Metal–Organic Frameworks and Related Materials into Their Underlying Nets',
        url: 'https://pubs.acs.org/doi/10.1021/cr200205j',
        publisher: 'American Chemical Society',
        year: 2012,
      },
      {
        title: 'Reticular Chemistry: Occurrence and Taxonomy of Nets and Grammar for the Design of Frameworks',
        url: 'https://pubs.acs.org/doi/10.1021/ar020022l',
        publisher: 'American Chemical Society',
        year: 2005,
      },
    ],
    reviewedAt: '2026-09-19',
  },
];
],
    correctIndex: 1,
    explanation: 'Wade\'s rules assign a closo cluster $n+1$ skeletal electron pairs, corresponding to a closed deltahedral framework with $n$ vertices.',
    realWorld: 'Electron-counting rules help rationalize boranes, carboranes, and related clusters used in synthesis, catalysis, and boron-containing functional materials.',
    hint: 'Closo is the closed-cage member of the closo/nido/arachno sequence.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40009, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'The isolobal analogy relates organometallic fragments to main-group fragments primarily on the basis of:',
    options: ['Identical atomic radii', 'Equal formal oxidation states', 'Matching electronegativities', 'Similar frontier-orbital number, symmetry, energy, shape, and occupancy'],
    correctIndex: 3,
    explanation: 'Two fragments are isolobal when their relevant frontier orbitals are similar in number, symmetry properties, approximate energy and shape, and electron occupancy, allowing structural and reactivity analogies across organic and inorganic chemistry.',
    realWorld: 'The isolobal analogy provides a compact way to predict bonding patterns and plausible structures in organometallic and cluster chemistry.',
    hint: 'The analogy compares the orbitals available for making new bonds rather than bulk elemental properties.',
    sources: [
      {
        title: 'Building Bridges Between Inorganic and Organic Chemistry (Nobel Lecture)',
        url: 'https://onlinelibrary.wiley.com/doi/10.1002/anie.198207113',
        publisher: 'Wiley',
        year: 1982,
      },
    ],
    reviewedAt: '2026-09-19',
  },
  {
    id: 40022, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the coordination number of cobalt in the complex ion $[Co(NH_3)_6]^{3+}$?',
    options: ['3', '4', '6', '9'],
    correctIndex: 2,
    explanation: 'Six ammonia ligands each donate one lone pair through one nitrogen donor atom, so cobalt has coordination number 6 in $[Co(NH_3)_6]^{3+}$.',
    realWorld: 'Coordination number is a first step toward predicting geometry, ligand-field splitting, and reactivity in metal complexes.',
    hint: 'Count the donor atoms directly bonded to the central metal.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40023, topic: 'inorganic-chemistry', difficulty: 'easy',
    question: 'What is the oxidation state of iron in $[Fe(CN)_6]^{4-}$?',
    options: ['+1', '+2', '+3', '+4'],
    correctIndex: 1,
    explanation: 'Each cyanide ligand contributes a -1 formal charge. With six cyanides the ligand charge is -6, so iron must be +2 to give the complex ion an overall charge of -4.',
    realWorld: 'Oxidation-state bookkeeping is essential for analyzing redox chemistry, coordination compounds, electrochemistry, and catalytic cycles.',
    hint: 'Set the metal oxidation state plus six ligand charges equal to the overall ion charge.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40024, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'Which octahedral d-electron configuration is especially prone to a strong Jahn-Teller distortion because of uneven occupation of the $e_g$ orbitals?',
    options: ['d³', 'low-spin d⁶', 'd¹⁰', 'd⁹'],
    correctIndex: 3,
    explanation: 'An octahedral d⁹ ion has three electrons distributed across the doubly degenerate antibonding $e_g$ set, creating strong electronic degeneracy that is commonly relieved by tetragonal Jahn-Teller distortion.',
    realWorld: 'Jahn-Teller distortions influence the structures, spectra, magnetism, and electron transport of many copper(II) complexes and solids.',
    hint: 'Look for a configuration with an unevenly occupied pair of strongly metal-ligand antibonding orbitals.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40025, topic: 'inorganic-chemistry', difficulty: 'hard',
    question: 'For a square-planar Pt(II) complex, a ligand with a strong trans effect primarily influences:',
    options: ['The rate at which the ligand opposite it is substituted', 'The formal oxidation state of every spectator ligand', 'The total number of d electrons on free platinum atoms', 'Whether the complex must become tetrahedral at equilibrium'],
    correctIndex: 0,
    explanation: 'The trans effect is kinetic: certain ligands labilize the ligand trans to themselves, changing substitution rates and therefore controlling which products form during stepwise synthesis of square-planar complexes.',
    realWorld: 'Trans-effect control is used to plan syntheses of platinum coordination compounds, including routes to medically relevant Pt complexes.',
    hint: 'Distinguish a kinetic substitution effect from the structural trans influence on bond lengths.',
    reviewedAt: '2026-09-19',
  },
  {
    id: 40026, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'Which description best captures the construction principle of a metal-organic framework (MOF)?',
    options: ['A dense alloy formed only from metallic bonds', 'A molecular crystal held together exclusively by hydrogen bonding', 'Metal-containing nodes connected by organic linkers into an extended porous network', 'A polymer whose backbone contains no metal coordination sites'],
    correctIndex: 2,
    explanation: 'MOFs are extended crystalline networks assembled from metal ions or metal-containing clusters linked by multitopic organic molecules, creating designable pores and internal cavities.',
    realWorld: 'MOFs are investigated for gas storage and separation, carbon capture, catalysis, sensing, water harvesting, and other molecular-separation problems.',
    hint: 'Think of an extended scaffold built from inorganic connection points and organic struts.',
    sources: [
      {
        title: 'Press release: Nobel Prize in Chemistry 2025',
        url: 'https://www.nobelprize.org/prizes/chemistry/2025/press-release/',
        publisher: 'Nobel Prize Outreach',
        year: 2025,
      },
    ],
    reviewedAt: '2026-09-19',
    factualAsOf: '2026-09-19',
  },
  {
    id: 40027, topic: 'inorganic-chemistry', difficulty: 'sota',
    question: 'In reticular chemistry, why is describing a framework by its underlying net useful?',
    options: ['It replaces all chemical composition information with atomic mass', 'It guarantees every framework has the same pore size', 'It proves the material cannot undergo structural flexibility', 'It separates connectivity/topology from specific building-block chemistry so architectures can be compared and designed'],
    correctIndex: 3,
    explanation: 'An underlying net captures how nodes and linkers are connected independently of many chemical details, letting chemists classify framework topologies and reason about which building-unit geometries can realize a target architecture.',
    realWorld: 'Topology-guided design helps researchers compare large MOF families and plan new porous frameworks with intended connectivity and function.',
    hint: 'A net is an abstraction of connection pattern, not a complete molecular formula.',
    sources: [
      {
        title: 'Deconstructing the Crystal Structures of Metal–Organic Frameworks and Related Materials into Their Underlying Nets',
        url: 'https://pubs.acs.org/doi/10.1021/cr200205j',
        publisher: 'American Chemical Society',
        year: 2012,
      },
      {
        title: 'Reticular Chemistry: Occurrence and Taxonomy of Nets and Grammar for the Design of Frameworks',
        url: 'https://pubs.acs.org/doi/10.1021/ar020022l',
        publisher: 'American Chemical Society',
        year: 2005,
      },
    ],
    reviewedAt: '2026-09-19',
  },
];
