import type { Question } from '../types';

export const quantumComputingQuestions: Question[] = [
  {
    id: 440001, topic: "quantum-computing", difficulty: "easy",
    question: "A qubit can differ from a classical bit because, before measurement, its state can be:",
    options: ["Only the value 0","A superposition α|0⟩+β|1⟩","Exactly two classical bits","A continuous classical voltage with no quantum phase"],
    correctIndex: 1,
    explanation: "A pure qubit state is a normalized complex superposition of basis states |0⟩ and |1⟩; measurement probabilities depend on the amplitudes.",
    realWorld: "Superposition and relative phase enable quantum interference, which quantum algorithms manipulate to change outcome probabilities.",
    hint: "The state is described by amplitudes for two basis states rather than one definite classical value.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 440004, topic: "quantum-computing", difficulty: "easy",
    question: "Measuring α|0⟩+β|1⟩ in the computational basis gives outcome 1 with probability:",
    options: ["Magnitude of alpha","Squared magnitude of alpha","Magnitude of beta","Squared magnitude of beta"],
    correctIndex: 3,
    explanation: "The Born rule gives computational-basis probabilities |α|² and |β|² for outcomes 0 and 1 respectively.",
    realWorld: "Repeated measurements of identically prepared qubits estimate these probabilities statistically.",
    hint: "Square the magnitude of the amplitude multiplying |1⟩.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 440007, topic: "quantum-computing", difficulty: "easy",
    question: "Applying a Hadamard gate H to |0⟩ produces:",
    options: ["|1⟩","|0⟩","(|0⟩+|1⟩)/√2","(|0⟩-|1⟩) with no normalization"],
    correctIndex: 2,
    explanation: "The Hadamard maps |0⟩ to an equal-amplitude superposition (|0⟩+|1⟩)/√2.",
    realWorld: "Hadamard gates are basic building blocks for creating interference and superposition in many quantum algorithms.",
    hint: "The two computational-basis outcomes should have equal probability.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 440002, topic: "quantum-computing", difficulty: "hard",
    question: "Entangled quantum states are important because they can exhibit:",
    options: ["Nonclassical Bell correlations","Deterministic faster-than-light communication","Perfect immunity to decoherence","Two independent single-qubit states by definition"],
    correctIndex: 0,
    explanation: "Entanglement creates joint states that cannot be factorized into independent subsystem states and can produce correlations incompatible with local hidden-variable models, without enabling faster-than-light signalling.",
    realWorld: "Entanglement is a resource for teleportation, quantum networking, sensing, and many quantum algorithms, while still respecting no-signalling constraints.",
    hint: "Bell correlations can be stronger than classical local models allow, but they do not transmit controllable information faster than light.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 440005, topic: "quantum-computing", difficulty: "hard",
    question: "The quantum subroutine at the heart of Shor's factoring algorithm is used to find:",
    options: ["A shortest path","The period of modular exponentiation","A minimum spanning tree","The median of an unsorted list"],
    correctIndex: 1,
    explanation: "Shor reduces factoring to order or period finding and uses quantum Fourier-transform techniques to recover that period efficiently.",
    realWorld: "The threat Shor's algorithm poses to deployed public-key cryptography motivates migration to post-quantum standards.",
    hint: "Factoring is reduced to discovering a repeating modular pattern.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 440003, topic: "quantum-computing", difficulty: "sota",
    question: "A below-threshold surface code is significant because increasing code distance can:",
    options: ["Increase logical error at a fixed rate","Remove the need for classical decoding","Lower logical error as code distance grows","Make every physical gate perfect"],
    correctIndex: 2,
    explanation: "Below threshold, larger surface-code distances can reduce logical error rates rather than amplifying them; Google's Willow experiments demonstrated this scaling regime for encoded quantum memories.",
    realWorld: "Below-threshold logical-error suppression is a key prerequisite for scaling toward fault-tolerant quantum computation, though substantial engineering challenges remain.",
    hint: "The milestone is that adding redundancy improves the logical memory instead of making it worse.",
    paper: {"title":"Quantum error correction below the surface code threshold","url":"https://www.nature.com/articles/s41586-024-08449-y","venue":"Nature","year":2025},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 440006, topic: "quantum-computing", difficulty: "sota",
    question: "QAOA constructs a variational state by alternating:",
    options: ["Classical sorting and hash-table lookups","Quantum error correction and measurement only","Fourier transforms and database queries","Cost and mixer unitaries with optimized parameters"],
    correctIndex: 3,
    explanation: "The Quantum Approximate Optimization Algorithm alternates parameterized cost and mixer evolutions, with a classical outer loop choosing parameters to improve an objective.",
    realWorld: "QAOA is an important testbed for quantum optimization, but broad practical quantum advantage over strong classical methods remains an open benchmarking question.",
    hint: "Alternate evolution under the objective with an operator that explores candidate solutions.",
    sources: [{"title":"Challenges and opportunities in quantum optimization","url":"https://www.nature.com/articles/s42254-024-00770-9","publisher":"Nature Reviews Physics","year":2024}],
    reviewedAt: "2026-09-19",
  },
  {
    id: 440008, topic: "quantum-computing", difficulty: "hard",
    question: "The no-cloning theorem rules out a device that can:",
    options: [
      "Measure a qubit in a chosen basis",
      "Prepare a known basis state repeatedly",
      "Perfectly copy an arbitrary unknown quantum state",
      "Entangle two qubits with a unitary gate",
    ],
    correctIndex: 2,
    explanation: "Quantum mechanics forbids a universal operation that perfectly copies an arbitrary unknown quantum state while leaving the original unchanged.",
    realWorld: "The no-cloning theorem shapes quantum communication and error correction: redundancy must be created through encoded entanglement rather than ordinary bit copying.",
    hint: "Known states can be prepared again; the restriction concerns arbitrary unknown states.",
    reviewedAt: "2026-09-21",
  },
  {
    id: 440009, topic: "quantum-computing", difficulty: "sota",
    question: "The Eastin-Knill theorem implies that a quantum error-correcting code with local error-detection capability cannot have:",
    options: [
      "A universal logical gate set implemented entirely by transversal gates",
      "Any fault-tolerant logical operation at all",
      "Any encoded qubit protected from single-qubit errors",
      "Any classical decoder associated with the code",
    ],
    correctIndex: 0,
    explanation: "Eastin and Knill proved that sufficiently error-detecting quantum codes cannot support a universal set of encoded gates using transversal operations alone.",
    realWorld: "Fault-tolerant architectures therefore combine transversal operations with additional techniques such as code switching, lattice surgery, or magic-state methods.",
    hint: "Transversal gates are useful, but they cannot supply universality by themselves.",
    paper: {
      title: "Restrictions on Transversal Encoded Quantum Gate Sets",
      url: "https://doi.org/10.1103/PhysRevLett.102.110502",
      venue: "Physical Review Letters",
      year: 2009,
    },
    reviewedAt: "2026-09-21",
  },
];
