import type { Question } from '../types';

export const linguisticsQuestions: Question[] = [
  {
    id: 40601, topic: 'linguistics', difficulty: 'easy',
    question: 'Chomsky\'s theory of Universal Grammar proposes that:',
    options: [
      'All human languages share an innate underlying structure — children are born with a "language acquisition device" that constrains possible grammars',
      'All languages are equally easy to learn at any age',
      'Grammar is entirely learned from environmental input',
      'Only Indo-European languages share common structures',
    ],
    correctIndex: 0,
    explanation: 'Chomsky argued that the poverty of stimulus (children learn language from limited, noisy input) implies an innate grammar faculty.',
    realWorld: 'This theory influenced early NLP (context-free grammars, parse trees) and the debate continues in the age of LLMs.',
    hint: 'Children learn language too quickly from too little input — something must be innate.',
  },
  {
    id: 40604, topic: 'linguistics', difficulty: 'easy',
    question: 'The International Phonetic Alphabet (IPA) classifies speech sounds by:',
    options: [
      'Place of articulation (where in the mouth), manner of articulation (how air flows), and voicing (vocal cords vibrating or not)',
      'The letters used to spell the sound in English',
      'How loud the sound is',
      'The emotional content of the utterance',
    ],
    correctIndex: 0,
    explanation: 'IPA provides a universal notation: [p] is a voiceless bilabial plosive, [z] is a voiced alveolar fricative. This three-dimensional classification (place × manner × voicing) covers all human speech sounds (~600 consonants, ~200 vowels).',
    realWorld: 'IPA is essential for speech therapy, language documentation (recording endangered languages), text-to-speech systems, and training speech recognition models across languages.',
    hint: 'WHERE in your mouth, HOW the air moves, and WHETHER your vocal cords buzz.',
  },
  {
    id: 40602, topic: 'linguistics', difficulty: 'hard',
    question: 'The distributional hypothesis in computational linguistics states:',
    options: [
      '"You shall know a word by the company it keeps" — words in similar contexts have similar meanings, the foundation of word embeddings',
      'All words are distributed equally across all texts',
      'Word meanings are fixed and context-independent',
      'Only grammatical structure determines meaning',
    ],
    correctIndex: 0,
    explanation: 'Firth (1957) and Harris (1954) proposed that semantic similarity correlates with contextual similarity. This is exactly what Word2Vec, GloVe, and transformer embeddings learn.',
    realWorld: 'Every search engine, chatbot, and translation system relies on this. Word2Vec\'s famous: vector("king") - vector("man") + vector("woman") ≈ vector("queen").',
    hint: '"Bank" near "river" means something different than "bank" near "money" — context determines meaning.',
  },
  {
    id: 40605, topic: 'linguistics', difficulty: 'hard',
    question: 'Sapir-Whorf hypothesis (linguistic relativity) in its strong form claims:',
    options: [
      'The language you speak determines how you think — different languages create fundamentally different cognitive realities and conceptual categories',
      'All languages express exactly the same concepts',
      'Language has no influence on thought whatsoever',
      'Only written languages affect cognition',
    ],
    correctIndex: 0,
    explanation: 'The strong form (linguistic determinism) is largely rejected, but the weak form (linguistic influence) has empirical support: Russian speakers distinguish light blue (голубой) from dark blue (синий) faster than English speakers. Language shapes attention, not thought itself.',
    realWorld: 'Linguistic relativity matters for AI: multilingual LLMs may reason differently depending on the language used. Translation always loses nuance — some concepts are untranslatable (German "Schadenfreude," Japanese "木漏れ日").',
    hint: 'Does language shape thought, or just express it? The truth is somewhere in between.',
  },
  {
    id: 40603, topic: 'linguistics', difficulty: 'sota',
    question: 'Large language models challenge traditional linguistics because:',
    options: [
      'They achieve human-level language performance without explicit grammar rules, recursive structure, or innate constraints — suggesting statistical patterns may suffice for linguistic competence',
      'They prove Chomsky was completely correct about Universal Grammar',
      'They cannot process any natural language',
      'They only work for English and no other language',
    ],
    correctIndex: 0,
    explanation: 'LLMs learn language purely from statistical co-occurrence (next-token prediction) with no built-in grammar. Their success challenges the necessity of Chomsky\'s innate grammar hypothesis.',
    realWorld: 'GPT-4 passes the bar exam, writes poetry, and translates 100+ languages — all from predicting the next word. This has reignited the empiricism vs. nativism debate.',
    hint: 'If a machine can master language from pure statistics, do we really need innate grammar?',
  },
  {
    id: 40606, topic: 'linguistics', difficulty: 'sota',
    question: 'Tokenization in LLMs reveals linguistic assumptions because:',
    options: [
      'Byte-pair encoding (BPE) creates subword tokens optimized for the training language distribution — underrepresenting low-resource languages with more tokens per word, increasing cost and latency',
      'All languages are tokenized with equal efficiency',
      'Tokenization has no effect on model performance',
      'Every word is always one token regardless of language',
    ],
    correctIndex: 0,
    explanation: 'BPE merges frequent byte pairs into tokens. English "hello" = 1 token, but the same word in Tamil or Khmer might be 5+ tokens. This means non-English users get less "thinking" per context window and pay more per API call.',
    realWorld: 'GPT-4 uses ~1.5× more tokens for Chinese than English for equivalent content. This creates economic and capability disparities in multilingual AI access — a linguistic equity issue with real-world consequences.',
    hint: 'The tokenizer was trained mainly on English — other languages get chopped into more pieces.',
  },
];
