import type { Question } from '../types';

export const linguisticsQuestions: Question[] = [
  {
    id: 40601, topic: 'linguistics', difficulty: 'easy',
    question: 'A phoneme is best described as:',
    options: [
      'A sound category that can distinguish words',
      'A complete sentence with one main clause',
      'A writing system used for every language',
      'A rule for arranging paragraphs in a text',
    ],
    correctIndex: 0,
    explanation: 'A phoneme is a contrastive sound category: replacing one phoneme with another can distinguish words in a particular language.',
    realWorld: 'Phoneme inventories matter in language teaching, speech recognition, pronunciation tools, and clinical speech assessment.',
    hint: 'Think of sound contrasts such as the initial sounds in pat and bat.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40604, topic: 'linguistics', difficulty: 'easy',
    question: 'For consonants, the International Phonetic Alphabet commonly distinguishes sounds using:',
    options: [
      'Spelling, word length, and punctuation',
      'Place, manner, and voicing features',
      'Frequency, loudness, and sentence position',
      'Meaning, politeness, and writing direction',
    ],
    correctIndex: 1,
    explanation: 'Consonants are commonly described by place of articulation, manner of articulation, and whether vocal-fold vibration is present.',
    realWorld: 'A shared phonetic notation supports pronunciation teaching, speech therapy, field linguistics, and speech-technology development.',
    hint: 'Ask where the constriction occurs, how airflow is shaped, and whether the vocal folds vibrate.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40607, topic: 'linguistics', difficulty: 'easy',
    question: 'A morpheme is:',
    options: [
      'A complete paragraph in spoken form',
      'A sound with no linguistic function',
      'A smallest unit carrying meaning or grammar',
      'A writing symbol that must equal one word',
    ],
    correctIndex: 2,
    explanation: 'A morpheme is a minimal unit that contributes lexical meaning or grammatical information, such as cat, un-, or the plural suffix -s.',
    realWorld: 'Morpheme analysis supports language learning, dictionaries, search, translation, and computational processing of richly inflected languages.',
    hint: 'A word can contain more than one of these meaningful building blocks.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40602, topic: 'linguistics', difficulty: 'hard',
    question: 'The distributional hypothesis predicts that words occurring in similar contexts tend to:',
    options: [
      'Have identical spellings in all languages',
      'Belong to the same grammatical sentence',
      'Appear equally often in every document',
      'Have related meanings or linguistic functions',
    ],
    correctIndex: 3,
    explanation: 'Distributional approaches infer linguistic similarity from patterns of contextual co-occurrence: similar contextual distributions often signal related meanings or functions.',
    realWorld: 'This idea underlies many vector-space representations used in search, recommendation, clustering, and natural-language processing.',
    hint: 'A word is partly characterized by the company it keeps.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40605, topic: 'linguistics', difficulty: 'hard',
    question: 'A moderate form of linguistic relativity proposes that language can:',
    options: [
      'Bias attention or categorization without determining thought',
      'Make translation between languages logically impossible',
      'Determine every belief a speaker is able to form',
      'Eliminate all nonverbal forms of human reasoning',
    ],
    correctIndex: 0,
    explanation: 'Moderate linguistic-relativity claims allow language to influence habitual attention, memory, or categorization without claiming that language completely determines possible thought.',
    realWorld: 'The distinction matters when interpreting cross-linguistic experiments in color, space, time, number, and grammatical categorization.',
    hint: 'Influence is a weaker claim than total determination.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40608, topic: 'linguistics', difficulty: 'hard',
    question: 'In information-theoretic language modeling, a less probable next word has:',
    options: [
      'Lower surprisal by definition',
      'Higher surprisal by definition',
      'Exactly the same surprisal',
      'No measurable probability',
    ],
    correctIndex: 1,
    explanation: 'Surprisal is minus the logarithm of probability, so an event assigned lower probability carries higher surprisal when it occurs.',
    realWorld: 'Surprisal is used to study language processing and to quantify how expected or unexpected linguistic material is in context.',
    hint: 'Unexpected events carry more information than highly predictable ones.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 40603, topic: 'linguistics', difficulty: 'sota',
    question: 'In multilingual tokenization research, token fertility refers to:',
    options: [
      'The number of languages in a training corpus',
      'The percentage of tokens that are punctuation',
      'The average number of tokens needed per word',
      'The number of model layers devoted to syntax',
    ],
    correctIndex: 2,
    explanation: 'Token fertility measures how many subword tokens a tokenizer uses, on average, to represent a word or comparable unit in a language.',
    realWorld: 'High fertility can increase sequence length and computational cost, and recent multilingual studies associate it with performance disadvantages in some languages.',
    hint: 'It measures how many pieces a tokenizer creates from ordinary words.',
    sources: [{
      title: 'The Token Tax: Systematic Bias in Multilingual Tokenization',
      url: 'https://aclanthology.org/2026.africanlp-main.10/',
      publisher: 'Association for Computational Linguistics',
      year: 2026,
    }],
    reviewedAt: '2026-09-20',
    factualAsOf: '2026-09-20',
  },
  {
    id: 40606, topic: 'linguistics', difficulty: 'sota',
    question: 'What is the key idea behind byte-pair-encoding-style subword tokenization for open-vocabulary NLP?',
    options: [
      'Assign one fixed token to every possible word',
      'Delete rare words before model training begins',
      'Represent every sentence as a single token',
      'Build reusable units by merging frequent symbol pairs',
    ],
    correctIndex: 3,
    explanation: 'BPE-style tokenization begins with smaller symbols and repeatedly merges frequent adjacent pairs, producing reusable subword units that can compose rare or unseen words.',
    realWorld: 'Subword vocabularies reduce out-of-vocabulary failures and remain foundational in many modern language-processing systems.',
    hint: 'Frequent neighboring pieces are combined into larger reusable pieces.',
    sources: [{
      title: 'Neural Machine Translation of Rare Words with Subword Units',
      url: 'https://aclanthology.org/P16-1162/',
      publisher: 'Association for Computational Linguistics',
      year: 2016,
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 40609, topic: 'linguistics', difficulty: 'sota',
    question: 'In multilingual NLP, zero-shot cross-lingual transfer means:',
    options: [
      'Applying learned task behavior to a target language without target-language task training',
      'Training a separate model from scratch for every language before evaluation',
      'Translating all evaluation data into the source language before scoring',
      'Removing all shared parameters between the source and target languages',
    ],
    correctIndex: 0,
    explanation: 'Zero-shot cross-lingual transfer evaluates whether knowledge learned with task supervision in one language can generalize to another language without target-language task labels.',
    realWorld: 'Cross-lingual transfer is important for extending NLP capabilities to languages that have limited labeled datasets.',
    hint: 'The target language receives no task-specific labeled examples during training.',
    sources: [{
      title: 'XTREME: A Massively Multilingual Multi-task Benchmark for Evaluating Cross-lingual Generalisation',
      url: 'https://proceedings.mlr.press/v119/hu20b.html',
      publisher: 'Proceedings of Machine Learning Research',
      year: 2020,
    }],
    reviewedAt: '2026-09-20',
  },
];
