import type { Question } from '../types';

export const cybersecurityExpansionQuestions: Question[] = [
  {
    id: 40807, topic: 'cybersecurity', difficulty: 'easy',
    question: 'What is the main security benefit of multi-factor authentication (MFA)?',
    options: ['It encrypts every file on the device automatically', 'It requires evidence from more than one authentication factor', 'It prevents all phishing messages from being delivered', 'It makes account passwords unnecessary in every system'],
    correctIndex: 1,
    explanation: 'MFA requires multiple kinds of authentication evidence, so theft of a password alone is less likely to be enough for account access.',
    realWorld: 'Organizations use MFA to reduce account takeover risk when passwords are guessed, reused, phished, or exposed in a breach.',
    hint: 'The protection comes from requiring an attacker to defeat more than one kind of proof.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40808, topic: 'cybersecurity', difficulty: 'easy',
    question: 'Why are parameterized database queries safer than building SQL by concatenating user input?',
    options: ['They hide the database server from the network', 'They make every database column read-only', 'They keep supplied values separate from SQL command structure', 'They automatically encrypt every returned row'],
    correctIndex: 2,
    explanation: 'Parameterized queries bind user-controlled values as data rather than parsing them as part of the SQL command, preventing a major class of injection attacks.',
    realWorld: 'Prepared statements are a standard defense in web applications that accept names, search terms, identifiers, or other input used in database queries.',
    hint: 'The key distinction is whether input is interpreted as data or executable query syntax.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40809, topic: 'cybersecurity', difficulty: 'easy',
    question: 'The principle of least privilege says an account or service should receive:',
    options: ['Administrator access in case it is needed later', 'The same permissions as every other account', 'No logging when privileged operations are performed', 'Only the permissions needed for its required tasks'],
    correctIndex: 3,
    explanation: 'Least privilege limits permissions to what a user, process, or service actually needs, reducing the damage possible after mistakes or compromise.',
    realWorld: 'Cloud roles, database accounts, service identities, and employee access are commonly scoped so a compromised credential exposes fewer systems and actions.',
    hint: 'Minimize what a compromised identity would be able to do.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40810, topic: 'cybersecurity', difficulty: 'hard',
    question: 'Why is storing a unique random salt with each password hash useful?',
    options: ['It makes a fast hash function memory-hard', 'It allows the original password to be decrypted', 'It eliminates the need to rate-limit login attempts', 'It makes identical passwords produce different stored hashes'],
    correctIndex: 3,
    explanation: 'A unique salt changes the input to the password-hashing function, so users with the same password do not share the same stored hash and precomputed hash tables are far less reusable.',
    realWorld: 'Password-storage systems combine per-password salts with deliberately expensive password-hashing functions to raise the cost of offline cracking after a credential database leak.',
    hint: 'Think about what happens when two users choose the same password.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40811, topic: 'cybersecurity', difficulty: 'hard',
    question: 'A web application has a cross-site scripting (XSS) flaw when attacker-controlled content can:',
    options: ['Change a DNS record without any credentials', 'Execute as active script in another user’s browser context', 'Read encrypted disk sectors without a key', 'Bypass network routing and address translation'],
    correctIndex: 1,
    explanation: 'XSS occurs when untrusted content reaches an HTML or script execution context without appropriate handling, allowing attacker-controlled code to run with the affected site’s browser privileges.',
    realWorld: 'Context-aware output encoding, safe templating, sanitization where appropriate, and restrictive browser policies help reduce XSS risk.',
    hint: 'The vulnerable boundary is between untrusted web content and the browser’s execution context.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40812, topic: 'cybersecurity', difficulty: 'hard',
    question: 'Why are offline, tested backups especially important for ransomware resilience?',
    options: ['They guarantee ransomware cannot enter the network', 'They reveal every attacker’s identity before an incident', 'They can preserve recoverable data even if production systems are encrypted or deleted', 'They remove the need to patch vulnerable systems'],
    correctIndex: 2,
    explanation: 'Backups that attackers cannot readily alter provide an independent recovery path when ransomware encrypts or destroys production data; restoration testing verifies that the path actually works.',
    realWorld: 'Incident-response planning often separates backup credentials and storage from production administration so one compromise does not automatically destroy both copies.',
    hint: 'A backup helps only if the incident cannot destroy it and the organization can restore from it.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 40813, topic: 'cybersecurity', difficulty: 'sota',
    question: 'Which function was added in NIST Cybersecurity Framework 2.0 alongside Identify, Protect, Detect, Respond, and Recover?',
    options: ['Encrypt', 'Authenticate', 'Isolate', 'Govern'],
    correctIndex: 3,
    explanation: 'NIST CSF 2.0 added Govern as a sixth high-level function, emphasizing cybersecurity risk strategy, expectations, policy, roles, and oversight.',
    realWorld: 'The Govern function connects cybersecurity decisions with enterprise risk management and leadership responsibilities rather than treating security only as a technical operations problem.',
    hint: 'The new function addresses how an organization directs and oversees cybersecurity risk.',
    sources: [{ title: 'The NIST Cybersecurity Framework (CSF) 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', publisher: 'NIST', year: 2024 }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 40814, topic: 'cybersecurity', difficulty: 'sota',
    question: 'Why do CISA and partner agencies encourage software manufacturers to develop memory-safety roadmaps?',
    options: ['To replace cryptographic key management with garbage collection', 'To reduce vulnerabilities caused by memory-unsafe software and dependencies', 'To make every program execute entirely in browser sandboxes', 'To eliminate the need for vulnerability disclosure programs'],
    correctIndex: 1,
    explanation: 'Memory-safety guidance focuses on reducing vulnerability classes associated with memory-unsafe code and understanding exposure inherited through software dependencies.',
    realWorld: 'Manufacturers can inventory memory-unsafe components, prioritize high-risk dependencies, and plan migration or other mitigations instead of addressing memory-corruption bugs only after disclosure.',
    hint: 'The roadmap targets a recurring class of implementation vulnerabilities, including risk inherited from dependencies.',
    sources: [{ title: 'CISA and Partners Release Guidance for Exploring Memory Safety in Critical Open Source Projects', url: 'https://www.cisa.gov/news-events/alerts/2024/06/26/cisa-and-partners-release-guidance-exploring-memory-safety-critical-open-source-projects', publisher: 'CISA', year: 2024 }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 40815, topic: 'cybersecurity', difficulty: 'sota',
    question: 'In NIST CSF 2.0, what is an Organizational Profile used to describe?',
    options: ['A ranked list of individual employee security scores', 'A mandatory catalog of specific security products', 'An organization’s current or target cybersecurity posture in terms of CSF Core outcomes', 'A cryptographic identity certificate for the organization'],
    correctIndex: 2,
    explanation: 'CSF Organizational Profiles describe current and/or target cybersecurity posture using outcomes from the CSF Core, supporting prioritization and communication of risk-management goals.',
    realWorld: 'An organization can compare a Current Profile with a Target Profile to identify and communicate gaps without the framework prescribing one implementation technology.',
    hint: 'Profiles connect the framework’s outcomes to where an organization is now or wants to be.',
    sources: [{ title: 'The NIST Cybersecurity Framework (CSF) 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', publisher: 'NIST', year: 2024 }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
];
