import type { Question } from '../types';

export const cybersecurityQuestions: Question[] = [
  {
    id: 40801, topic: 'cybersecurity', difficulty: 'easy',
    question: 'Public-key cryptography (RSA) relies on the computational difficulty of:',
    options: [
      'Factoring the product of two large primes — multiplying is easy, but reversing is computationally infeasible for large numbers',
      'Adding two numbers together',
      'Sorting a list of numbers',
      'Finding the square root of a perfect square',
    ],
    correctIndex: 0,
    explanation: 'RSA creates a public key from n = p·q (two large primes). Encrypting with n is easy; decrypting requires knowing p and q. The best classical factoring algorithms are sub-exponential but infeasible for 2048-bit keys.',
    realWorld: 'RSA secures HTTPS (every website with a padlock), email encryption, digital signatures, and cryptocurrency.',
    hint: 'Easy to multiply two big primes. Nearly impossible to figure out which primes were multiplied.',
  },
  {
    id: 40804, topic: 'cybersecurity', difficulty: 'easy',
    question: 'A hash function (SHA-256) is used in security because:',
    options: [
      'It maps any input to a fixed-size output (256 bits) where even a 1-bit input change produces a completely different hash — and the function is practically irreversible',
      'It encrypts data so only the sender can read it',
      'It compresses files to save storage space',
      'It generates random numbers for passwords',
    ],
    correctIndex: 0,
    explanation: 'Cryptographic hash functions have three key properties: pre-image resistance (can\'t find input from hash), collision resistance (can\'t find two inputs with same hash), and avalanche effect (tiny input change → massive output change).',
    realWorld: 'SHA-256 secures Bitcoin (mining = finding inputs with specific hash patterns), password storage (store hashes, not passwords), file integrity verification (checksums), and digital signatures.',
    hint: 'A digital fingerprint — unique, fixed-size, and impossible to reverse.',
  },
  {
    id: 40802, topic: 'cybersecurity', difficulty: 'hard',
    question: 'Zero-knowledge proofs allow a prover to:',
    options: [
      'Convince a verifier that a statement is true without revealing ANY information beyond the statement\'s truth',
      'Share their private key securely with the verifier',
      'Encrypt data so only the verifier can read it',
      'Prove they own a password by sending it in plaintext',
    ],
    correctIndex: 0,
    explanation: 'A ZKP has three properties: completeness (honest prover convinces), soundness (dishonest prover fails), and zero-knowledge (verifier learns nothing beyond validity).',
    realWorld: 'ZKPs power privacy-preserving blockchains (Zcash), anonymous credentials, and zk-SNARKs enable Ethereum L2 rollups processing 1000+ TPS.',
    hint: 'Prove you know the secret without showing the secret.',
  },
  {
    id: 40805, topic: 'cybersecurity', difficulty: 'hard',
    question: 'SQL injection attacks exploit:',
    options: [
      'Unsanitized user input being concatenated into SQL queries — allowing attackers to inject malicious SQL that modifies the query\'s logic (e.g., OR 1=1 bypasses authentication)',
      'Weaknesses in the SQL language specification itself',
      'Physical access to the database server',
      'Brute-force guessing of database passwords',
    ],
    correctIndex: 0,
    explanation: 'If code does `SELECT * FROM users WHERE name=\'${input}\'` and input is `\' OR 1=1 --`, the query becomes `SELECT * FROM users WHERE name=\'\' OR 1=1 --\'`, returning all users. Prevention: parameterized queries (prepared statements).',
    realWorld: 'SQL injection has caused massive breaches: Sony (2011, 77M accounts), Heartland (2008, 130M cards). It remains OWASP\'s #3 web vulnerability. Prepared statements are the definitive fix.',
    hint: 'When user input becomes part of the SQL command instead of just data.',
  },
  {
    id: 40803, topic: 'cybersecurity', difficulty: 'sota',
    question: 'Post-quantum cryptography is urgently needed because:',
    options: [
      'Shor\'s algorithm on a sufficiently large quantum computer can factor RSA keys and break elliptic curve cryptography in polynomial time — "harvest now, decrypt later" attacks are already occurring',
      'Quantum computers have already broken all encryption',
      'Classical computers are getting fast enough to break RSA',
      'Post-quantum cryptography is only theoretical',
    ],
    correctIndex: 0,
    explanation: 'NIST standardized CRYSTALS-Kyber (key exchange) and CRYSTALS-Dilithium (signatures) in 2024, based on lattice problems believed to resist quantum attacks.',
    realWorld: 'Google, Apple, and Signal have already deployed post-quantum key exchange. The US government mandated post-quantum migration by 2035.',
    hint: 'Quantum computers will break current encryption — we need to switch before that happens.',
  },
  {
    id: 40806, topic: 'cybersecurity', difficulty: 'sota',
    question: 'AI-powered offensive security tools create new threats because:',
    options: [
      'LLMs can generate polymorphic malware that rewrites its own code to evade signature-based detection, craft highly personalized phishing at scale, and automate vulnerability discovery',
      'AI makes all existing security tools obsolete overnight',
      'AI can only be used defensively, not offensively',
      'Firewalls are completely ineffective against AI attacks',
    ],
    correctIndex: 0,
    explanation: 'GPT-4 can generate functional exploits from CVE descriptions, craft phishing emails indistinguishable from human-written ones, and create malware variants that evade traditional antivirus. Defense now requires AI-vs-AI: ML-based detection vs. ML-generated attacks.',
    realWorld: 'WormGPT and FraudGPT (dark web LLMs) lower the barrier for cybercrime. Meanwhile, defenders use AI for anomaly detection, automated patching, and threat intelligence. The AI security arms race is intensifying.',
    hint: 'AI helps attackers create better malware and phishing — defenders must use AI too.',
  },
];
