// Canonical concept graph for the mastery layer.
//
// Topics remain the routing/loading taxonomy. Concepts are smaller pedagogical
// units that can span reference surfaces and eventually drive learner mastery.

export type ConceptStatus = 'active' | 'experimental' | 'deprecated';

export interface Concept {
  id: string;
  label: string;
  field: string;
  topics: readonly string[];
  prerequisites: readonly string[];
  related?: readonly string[];
  applications?: readonly string[];
  status: ConceptStatus;
}

export const CONCEPTS: readonly Concept[] = [
  // ── Linear Algebra pilot ───────────────────────────────────
  {
    id: 'matrix-dimensions',
    label: 'Matrix Dimensions',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: [],
    related: ['matrix-multiplication'],
    status: 'active',
  },
  {
    id: 'matrix-multiplication',
    label: 'Matrix Multiplication',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-dimensions'],
    applications: ['linear systems', 'neural-network layers'],
    status: 'active',
  },
  {
    id: 'linear-systems',
    label: 'Linear Systems',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-multiplication'],
    applications: ['circuits', 'least squares', 'numerical solvers'],
    status: 'active',
  },
  {
    id: 'vector-norms',
    label: 'Vector Norms',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: [],
    applications: ['distance', 'regularization'],
    status: 'active',
  },
  {
    id: 'matrix-transpose',
    label: 'Matrix Transpose',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-dimensions'],
    related: ['symmetric-matrices', 'orthogonal-matrices'],
    status: 'active',
  },
  {
    id: 'dot-product-orthogonality',
    label: 'Dot Product & Orthogonality',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['vector-norms'],
    applications: ['projections', 'PCA', 'Gram-Schmidt'],
    status: 'active',
  },
  {
    id: 'identity-matrix',
    label: 'Identity Matrix',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-multiplication'],
    status: 'active',
  },
  {
    id: 'symmetric-matrices',
    label: 'Symmetric Matrices',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-transpose'],
    applications: ['covariance matrices', 'kernel methods'],
    status: 'active',
  },
  {
    id: 'eigenvalues-eigenvectors',
    label: 'Eigenvalues & Eigenvectors',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-multiplication'],
    applications: ['PCA', 'dynamical systems', 'Markov chains'],
    status: 'active',
  },
  {
    id: 'null-space',
    label: 'Null Space',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['linear-systems'],
    related: ['matrix-singularity', 'column-space'],
    status: 'active',
  },
  {
    id: 'matrix-singularity',
    label: 'Matrix Singularity',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['null-space'],
    applications: ['solver diagnostics', 'rank analysis'],
    status: 'active',
  },
  {
    id: 'matrix-trace',
    label: 'Matrix Trace',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-dimensions'],
    status: 'active',
  },
  {
    id: 'orthogonal-matrices',
    label: 'Orthogonal Matrices',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['matrix-transpose', 'dot-product-orthogonality'],
    applications: ['QR decomposition', 'stable transformations'],
    status: 'active',
  },
  {
    id: 'column-space',
    label: 'Column Space',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['linear-systems'],
    applications: ['least squares', 'range of linear maps'],
    status: 'active',
  },
  {
    id: 'diagonalization',
    label: 'Diagonalization',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['eigenvalues-eigenvectors'],
    applications: ['matrix powers', 'dynamical systems'],
    status: 'active',
  },
  {
    id: 'frobenius-norm',
    label: 'Frobenius Norm',
    field: 'math',
    topics: ['linear-algebra'],
    prerequisites: ['vector-norms'],
    applications: ['matrix regularization', 'matrix approximation'],
    status: 'active',
  },

  // ── Calculus pilot ─────────────────────────────────────────
  {
    id: 'derivatives',
    label: 'Derivatives',
    field: 'math',
    topics: ['calculus'],
    prerequisites: ['continuity'],
    applications: ['rates of change', 'optimization'],
    status: 'active',
  },
  {
    id: 'continuity',
    label: 'Continuity',
    field: 'math',
    topics: ['calculus'],
    prerequisites: [],
    related: ['derivatives'],
    status: 'active',
  },
  {
    id: 'gradient',
    label: 'Gradient',
    field: 'math',
    topics: ['calculus'],
    prerequisites: ['derivatives'],
    applications: ['multivariable optimization', 'machine learning'],
    status: 'active',
  },
  {
    id: 'elementary-derivatives',
    label: 'Elementary Derivatives',
    field: 'math',
    topics: ['calculus'],
    prerequisites: ['derivatives'],
    applications: ['symbolic differentiation', 'modeling'],
    status: 'active',
  },
  {
    id: 'product-rule',
    label: 'Product Rule',
    field: 'math',
    topics: ['calculus'],
    prerequisites: ['derivatives'],
    status: 'active',
  },
  {
    id: 'antiderivatives',
    label: 'Antiderivatives',
    field: 'math',
    topics: ['calculus'],
    prerequisites: ['derivatives'],
    applications: ['integration', 'accumulation'],
    status: 'active',
  },

  // ── Probability & Statistics ───────────────────────────────
  {
    id: 'probability-rules',
    label: 'Probability Rules',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: [],
    related: ['bayesian-inference', 'dependence-correlation'],
    applications: ['risk calculation', 'reliability', 'classification'],
    status: 'active',
  },
  {
    id: 'bayesian-inference',
    label: 'Bayesian Inference',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['probability-rules'],
    applications: ['diagnosis', 'A/B testing', 'probabilistic modeling'],
    status: 'active',
  },
  {
    id: 'expectation-variance',
    label: 'Expectation & Variance',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['probability-rules'],
    related: ['sampling-convergence', 'dependence-correlation'],
    applications: ['risk', 'uncertainty', 'Monte Carlo'],
    status: 'active',
  },
  {
    id: 'probability-distributions',
    label: 'Probability Distributions',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['probability-rules', 'expectation-variance'],
    applications: ['noise models', 'event counts', 'simulation'],
    status: 'active',
  },
  {
    id: 'sampling-convergence',
    label: 'Sampling & Convergence',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['expectation-variance', 'probability-distributions'],
    applications: ['confidence intervals', 'Monte Carlo', 'empirical estimation'],
    status: 'active',
  },
  {
    id: 'dependence-correlation',
    label: 'Dependence & Correlation',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['expectation-variance'],
    applications: ['feature analysis', 'portfolio risk', 'multivariate modeling'],
    status: 'active',
  },
  {
    id: 'statistical-inference',
    label: 'Statistical Inference',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['sampling-convergence', 'probability-distributions'],
    related: ['bayesian-inference'],
    applications: ['hypothesis tests', 'parameter estimation', 'experiments'],
    status: 'active',
  },
  {
    id: 'information-measures',
    label: 'Information Measures',
    field: 'math',
    topics: ['probability-stats'],
    prerequisites: ['probability-distributions'],
    related: ['dependence-correlation'],
    applications: ['representation learning', 'compression', 'model comparison'],
    status: 'active',
  },

  // ── Optimization ────────────────────────────────────────────
  {
    id: 'optimization-objectives',
    label: 'Objectives & Convexity',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['derivatives'],
    related: ['gradient-descent'],
    applications: ['regression', 'classification', 'operations research'],
    status: 'active',
  },
  {
    id: 'gradient-descent',
    label: 'Gradient Descent',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['gradient', 'optimization-objectives'],
    applications: ['model training', 'numerical optimization'],
    status: 'active',
  },
  {
    id: 'stochastic-optimization',
    label: 'Stochastic Optimization',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['gradient-descent', 'expectation-variance'],
    applications: ['large-scale learning', 'online learning'],
    status: 'active',
  },
  {
    id: 'regularization',
    label: 'Regularization',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['optimization-objectives'],
    related: ['generalization-model-selection'],
    applications: ['feature selection', 'weight decay', 'robust learning'],
    status: 'active',
  },
  {
    id: 'generalization-model-selection',
    label: 'Generalization & Model Selection',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['optimization-objectives'],
    related: ['regularization'],
    applications: ['validation', 'hyperparameter tuning', 'bias-variance analysis'],
    status: 'active',
  },
  {
    id: 'training-stability',
    label: 'Training Stability',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['gradient-descent'],
    applications: ['deep networks', 'mixed precision', 'gradient control'],
    status: 'active',
  },
  {
    id: 'model-compression-efficiency',
    label: 'Model Compression & Efficiency',
    field: 'math',
    topics: ['optimization'],
    prerequisites: ['generalization-model-selection'],
    related: ['regularization'],
    applications: ['deployment', 'distillation', 'pruning'],
    status: 'active',
  },

] as const;

export const CONCEPT_MAP: Readonly<Record<string, Concept>> = Object.fromEntries(
  CONCEPTS.map((concept) => [concept.id, concept]),
);
