// Generated by scripts/generate-content-stats.ts. Do not edit by hand.
export const CONTENT_COUNTS = {
  "questions": 1078,
  "standardQuestions": 1078,
  "vaultQuestions": 64,
  "glossaryTerms": 488,
  "thinkers": 651,
  "vaultEntries": 74,
  "equations": 480
} as const;

export const QUESTION_COUNTS = {
  "abstract-algebra": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "aerodynamics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "ai-models": {
    "easy": 2,
    "hard": 4,
    "sota": 3,
    "total": 9
  },
  "ai-substrates": {
    "easy": 6,
    "hard": 8,
    "sota": 14,
    "total": 28
  },
  "algebraic-geometry": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "algo-trading": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "algorithms": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "astronomy": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "astrophysics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "audio-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "behavioral-economics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "biomedical-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "calculus": {
    "easy": 8,
    "hard": 8,
    "sota": 8,
    "total": 24
  },
  "category-theory": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "circuits-electronics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "classical-mechanics": {
    "easy": 5,
    "hard": 5,
    "sota": 2,
    "total": 12
  },
  "climate-science": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "combinatorics": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "communications-coding": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "compiler-theory": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "complex-analysis": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "condensed-matter": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "control-systems": {
    "easy": 4,
    "hard": 5,
    "sota": 5,
    "total": 14
  },
  "credit-risk": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "cryptography": {
    "easy": 1,
    "hard": 1,
    "sota": 1,
    "total": 3
  },
  "cybersecurity": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "derivatives-pricing": {
    "easy": 5,
    "hard": 5,
    "sota": 3,
    "total": 13
  },
  "development-economics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "differential-equations": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "differential-geometry": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "discrete-math": {
    "easy": 8,
    "hard": 8,
    "sota": 8,
    "total": 24
  },
  "distributed-systems": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "ecology": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "econometrics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "electromagnetism": {
    "easy": 1,
    "hard": 1,
    "sota": 1,
    "total": 3
  },
  "environmental-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "environmental-science": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "ergodic-theory": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "fixed-income": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "fluid-dynamics": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "formal-verification": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "functional-analysis": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "game-theory": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "genetics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "geology": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "graph-theory": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "information-theory": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "inorganic-chemistry": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "linear-algebra": {
    "easy": 8,
    "hard": 8,
    "sota": 8,
    "total": 24
  },
  "linguistics": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "machine-learning": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "macroeconomics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "many-body-physics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "market-microstructure": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "materials-science": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "measure-theory": {
    "easy": 5,
    "hard": 5,
    "sota": 5,
    "total": 15
  },
  "meteorology": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "microeconomics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "molecular-biology": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "neuroscience": {
    "easy": 3,
    "hard": 2,
    "sota": 3,
    "total": 8
  },
  "nonlinear-dynamics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "nuclear-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "nuclear-physics": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "number-theory": {
    "easy": 1,
    "hard": 1,
    "sota": 1,
    "total": 3
  },
  "numerical-methods": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "oceanography": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "operating-systems": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "optics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "optimization": {
    "easy": 8,
    "hard": 8,
    "sota": 8,
    "total": 24
  },
  "orbital-mechanics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "organic-chemistry": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "pharmacology": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "philosophy-of-science": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "physical-chemistry": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "plasma-physics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "portfolio-theory": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "power-systems": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "prediction-markets": {
    "easy": 7,
    "hard": 8,
    "sota": 9,
    "total": 24
  },
  "probability-stats": {
    "easy": 8,
    "hard": 8,
    "sota": 8,
    "total": 24
  },
  "process-design": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "psychology": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "quantum-computing": {
    "easy": 3,
    "hard": 2,
    "sota": 2,
    "total": 7
  },
  "quantum-field-theory": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "quantum-gravity": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "quantum-mechanics": {
    "easy": 5,
    "hard": 5,
    "sota": 3,
    "total": 13
  },
  "reaction-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "real-analysis": {
    "easy": 1,
    "hard": 1,
    "sota": 1,
    "total": 3
  },
  "relativity": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "risk-management": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "robotics-mechatronics": {
    "easy": 3,
    "hard": 4,
    "sota": 4,
    "total": 11
  },
  "semiconductor-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "signal-processing": {
    "easy": 5,
    "hard": 5,
    "sota": 4,
    "total": 14
  },
  "solid-mechanics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "sota-2024": {
    "easy": 5,
    "hard": 6,
    "sota": 4,
    "total": 15
  },
  "sota-2025": {
    "easy": 0,
    "hard": 0,
    "sota": 11,
    "total": 11
  },
  "sota-2026": {
    "easy": 0,
    "hard": 0,
    "sota": 20,
    "total": 20
  },
  "spaceflight-systems": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "statistical-physics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "stochastic-calculus": {
    "easy": 5,
    "hard": 5,
    "sota": 2,
    "total": 12
  },
  "structural-engineering": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "thermodynamics": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "thermofluids": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  },
  "topology": {
    "easy": 2,
    "hard": 2,
    "sota": 2,
    "total": 6
  },
  "transport-phenomena": {
    "easy": 3,
    "hard": 3,
    "sota": 3,
    "total": 9
  }
} as const;
