export interface Equation {
  rank: number;
  name: string;
  equation: string;        // LaTeX string
  discoverer: string;
  year: string;
  field: string;
  domain: string;
  domainEmoji: string;
  significance: string;
  constants: string;
  applications: string;
  beauty: number;           // 1–10
  difficulty: 'easy' | 'hard' | 'sota';
}

export const EQUATIONS: Equation[] = [
  {
    rank: 1,
    name: "Euler's Identity",
    equation: "e^{i\\pi} + 1 = 0",
    discoverer: "Leonhard Euler",
    year: "1748",
    field: "Complex Analysis / Pure Math",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Connects five fundamental constants (0, 1, π, e, i) in one perfectly balanced equation. Feynman called it 'the most remarkable formula in mathematics.'",
    constants: "e ≈ 2.718, i = √−1, π ≈ 3.14159",
    applications: "Signal processing, quantum mechanics, electrical engineering",
    beauty: 10,
    difficulty: 'hard',
  },
  {
    rank: 2,
    name: "Pythagorean Theorem",
    equation: "a^2 + b^2 = c^2",
    discoverer: "Pythagoras (attributed)",
    year: "~570 BC",
    field: "Geometry",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Defines the fundamental relationship between the sides of a right triangle. One of the oldest and most widely applied theorems in mathematics.",
    constants: "a, b = legs; c = hypotenuse",
    applications: "Architecture, navigation, GPS, computer graphics, physics",
    beauty: 9,
    difficulty: 'easy',
  },
  {
    rank: 3,
    name: "Newton's Law of Universal Gravitation",
    equation: "F = G \\frac{m_1 m_2}{r^2}",
    discoverer: "Isaac Newton",
    year: "1687",
    field: "Physics / Applied Math",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Describes the gravitational force between any two masses. Unified celestial and terrestrial mechanics and enabled prediction of planetary orbits.",
    constants: "G = 6.674×10⁻¹¹ N·m²/kg²",
    applications: "Orbital mechanics, satellite navigation, space exploration",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 4,
    name: "Mass-Energy Equivalence",
    equation: "E = mc^2",
    discoverer: "Albert Einstein",
    year: "1905",
    field: "Physics / Relativity",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Shows that mass and energy are interchangeable. Underpins nuclear physics, particle physics, and our understanding of the universe's energy content.",
    constants: "c ≈ 3×10⁸ m/s",
    applications: "Nuclear power, medical imaging (PET), particle accelerators",
    beauty: 10,
    difficulty: 'hard',
  },
  {
    rank: 5,
    name: "Fundamental Theorem of Calculus",
    equation: "\\int_a^b f(x)\\,dx = F(b) - F(a)",
    discoverer: "Newton & Leibniz",
    year: "1668–1686",
    field: "Calculus",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Links differentiation and integration as inverse operations. Forms the backbone of calculus and enables computation of areas, volumes, and many physical quantities.",
    constants: "f(x) = integrand, F(x) = antiderivative",
    applications: "Physics, engineering, economics, probability, statistics",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 6,
    name: "Maxwell's Equations",
    equation: "\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\varepsilon_0}",
    discoverer: "James Clerk Maxwell",
    year: "1865",
    field: "Electromagnetism",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Unified electricity, magnetism, and light into a single theory. Predicted electromagnetic waves and laid the foundation for modern technology.",
    constants: "ε₀, μ₀, c = 1/√(ε₀μ₀)",
    applications: "Radio, Wi-Fi, MRI, fiber optics, all electromagnetic tech",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 7,
    name: "Schrödinger Equation",
    equation: "i\\hbar \\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi",
    discoverer: "Erwin Schrödinger",
    year: "1926",
    field: "Quantum Mechanics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Governs the evolution of quantum systems. Describes how wavefunctions change over time and predicts the behavior of particles at atomic scale.",
    constants: "ℏ = h/2π, Ψ = wavefunction, Ĥ = Hamiltonian",
    applications: "Semiconductors, lasers, quantum computing, chemistry",
    beauty: 9,
    difficulty: 'sota',
  },
  {
    rank: 8,
    name: "Second Law of Thermodynamics",
    equation: "\\Delta S \\geq 0",
    discoverer: "Rudolf Clausius",
    year: "1850",
    field: "Thermodynamics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Entropy of an isolated system never decreases. Defines the arrow of time and constrains all energy transformations in the universe.",
    constants: "S = entropy, Q = heat, T = temperature",
    applications: "Heat engines, refrigeration, cosmology, information theory",
    beauty: 8,
    difficulty: 'hard',
  },
  {
    rank: 9,
    name: "Boltzmann Entropy",
    equation: "S = k_B \\ln \\Omega",
    discoverer: "Ludwig Boltzmann",
    year: "1877",
    field: "Statistical Mechanics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Bridges the microscopic world of atoms to macroscopic thermodynamics. Engraved on Boltzmann's tombstone.",
    constants: "k_B ≈ 1.38×10⁻²³ J/K, Ω = microstates",
    applications: "Information theory, black hole physics, material science",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 10,
    name: "Heisenberg Uncertainty Principle",
    equation: "\\Delta x \\, \\Delta p \\geq \\frac{\\hbar}{2}",
    discoverer: "Werner Heisenberg",
    year: "1927",
    field: "Quantum Mechanics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Sets a fundamental limit on the precision of simultaneous measurements of position and momentum. Reveals the inherent probabilistic nature of reality.",
    constants: "ℏ ≈ 1.055×10⁻³⁴ J·s",
    applications: "Quantum computing, electron microscopy, cryptography",
    beauty: 8,
    difficulty: 'hard',
  },
  {
    rank: 11,
    name: "Einstein Field Equations",
    equation: "G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}",
    discoverer: "Albert Einstein",
    year: "1915",
    field: "General Relativity",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Describes how matter and energy curve spacetime. Predicted gravitational waves, black holes, and the expansion of the universe.",
    constants: "Λ = cosmological constant, G = Newton's constant",
    applications: "GPS correction, gravitational wave detection, cosmology",
    beauty: 10,
    difficulty: 'sota',
  },
  {
    rank: 12,
    name: "Euler's Formula",
    equation: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta",
    discoverer: "Leonhard Euler",
    year: "1748",
    field: "Complex Analysis",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Reveals the deep connection between exponential and trigonometric functions through complex numbers. Parent formula of Euler's Identity.",
    constants: "e, i, θ = angle in radians",
    applications: "Signal processing, AC circuits, Fourier analysis, quantum mechanics",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 13,
    name: "Navier-Stokes Equations",
    equation: "\\rho\\left(\\frac{\\partial \\mathbf{v}}{\\partial t} + \\mathbf{v}\\cdot\\nabla\\mathbf{v}\\right) = -\\nabla p + \\mu\\nabla^2\\mathbf{v}",
    discoverer: "Navier & Stokes",
    year: "1822–1845",
    field: "Fluid Dynamics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Governs the motion of fluids. One of the Clay Millennium Prize Problems — proving smoothness remains unsolved and worth $1M.",
    constants: "ρ = density, μ = viscosity, p = pressure",
    applications: "Aerodynamics, weather prediction, blood flow, ocean currents",
    beauty: 8,
    difficulty: 'sota',
  },
  {
    rank: 14,
    name: "Bayes' Theorem",
    equation: "P(A|B) = \\frac{P(B|A)\\,P(A)}{P(B)}",
    discoverer: "Thomas Bayes",
    year: "1763",
    field: "Probability / Statistics",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Foundation of probabilistic reasoning and statistical inference. Enables updating beliefs with new evidence — the mathematical engine of machine learning.",
    constants: "P(A|B) = posterior, P(B|A) = likelihood",
    applications: "Machine learning, medical diagnosis, spam filtering, AI",
    beauty: 8,
    difficulty: 'hard',
  },
  {
    rank: 15,
    name: "Fourier Transform",
    equation: "\\hat{f}(\\xi) = \\int_{-\\infty}^{\\infty} f(x)\\,e^{-2\\pi i x \\xi}\\,dx",
    discoverer: "Joseph Fourier",
    year: "1822",
    field: "Harmonic Analysis",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Decomposes any signal into its constituent frequencies. Arguably the most useful mathematical tool in science and engineering.",
    constants: "ξ = frequency, i = √−1",
    applications: "MP3/JPEG compression, MRI, spectroscopy, telecommunications",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 16,
    name: "Dirac Equation",
    equation: "(i\\gamma^\\mu \\partial_\\mu - m)\\psi = 0",
    discoverer: "Paul Dirac",
    year: "1928",
    field: "Relativistic Quantum Mechanics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "First equation consistent with both quantum mechanics and special relativity. Predicted antimatter before it was discovered experimentally.",
    constants: "γᵘ = gamma matrices, m = electron mass",
    applications: "Particle physics, quantum field theory, antimatter research",
    beauty: 9,
    difficulty: 'sota',
  },
  {
    rank: 17,
    name: "Euler–Lagrange Equation",
    equation: "\\frac{\\partial L}{\\partial q} - \\frac{d}{dt}\\frac{\\partial L}{\\partial \\dot{q}} = 0",
    discoverer: "Euler & Lagrange",
    year: "1755",
    field: "Analytical Mechanics",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "The cornerstone of the calculus of variations and Lagrangian mechanics. Nature chooses paths that extremize the action.",
    constants: "L = Lagrangian, q = generalized coordinate",
    applications: "Classical mechanics, optics, control theory, general relativity",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 18,
    name: "Normal Distribution",
    equation: "f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}",
    discoverer: "Carl Friedrich Gauss",
    year: "1809",
    field: "Statistics / Probability",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "The bell curve appears everywhere in nature due to the Central Limit Theorem. Foundation of modern statistics and quality control.",
    constants: "μ = mean, σ = standard deviation",
    applications: "Finance, quality control, social science, hypothesis testing",
    beauty: 8,
    difficulty: 'hard',
  },
  {
    rank: 19,
    name: "Riemann Zeta Function",
    equation: "\\zeta(s) = \\sum_{n=1}^{\\infty} \\frac{1}{n^s}",
    discoverer: "Bernhard Riemann",
    year: "1859",
    field: "Analytic Number Theory",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Encodes the distribution of prime numbers. The Riemann Hypothesis — that all non-trivial zeros have real part ½ — remains the greatest unsolved problem in mathematics.",
    constants: "s = complex variable, n = natural numbers",
    applications: "Cryptography (RSA), prime distribution, quantum chaos",
    beauty: 9,
    difficulty: 'sota',
  },
  {
    rank: 20,
    name: "Stokes' Theorem",
    equation: "\\oint_{\\partial \\Omega} \\omega = \\int_{\\Omega} d\\omega",
    discoverer: "George Stokes",
    year: "1854",
    field: "Differential Geometry",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "The ultimate generalization of the Fundamental Theorem of Calculus to higher dimensions. Unifies Green's, Gauss's, and classical Stokes' theorems.",
    constants: "ω = differential form, Ω = manifold",
    applications: "Electromagnetism, fluid dynamics, topology, gauge theory",
    beauty: 9,
    difficulty: 'hard',
  },
  {
    rank: 21,
    name: "Black-Scholes Equation",
    equation: "\\frac{\\partial V}{\\partial t} + \\frac{1}{2}\\sigma^2 S^2 \\frac{\\partial^2 V}{\\partial S^2} + rS\\frac{\\partial V}{\\partial S} - rV = 0",
    discoverer: "Black, Scholes & Merton",
    year: "1973",
    field: "Financial Mathematics",
    domain: "Finance",
    domainEmoji: "💹",
    significance: "Revolutionized options pricing and spawned the derivatives market. Won the Nobel Prize in Economics. Changed Wall Street forever.",
    constants: "σ = volatility, r = risk-free rate, S = stock price",
    applications: "Options pricing, risk management, hedge funds, trading",
    beauty: 7,
    difficulty: 'hard',
  },
  {
    rank: 22,
    name: "Shannon Entropy",
    equation: "H = -\\sum_{i} p_i \\log_2 p_i",
    discoverer: "Claude Shannon",
    year: "1948",
    field: "Information Theory",
    domain: "Computer Science",
    domainEmoji: "💻",
    significance: "Quantifies information content and channel capacity. Founded the entire field of information theory and enabled the digital revolution.",
    constants: "pᵢ = probability of symbol i",
    applications: "Data compression, cryptography, machine learning, telecommunications",
    beauty: 8,
    difficulty: 'hard',
  },
  {
    rank: 23,
    name: "Noether's Theorem",
    equation: "\\text{Symmetry} \\Leftrightarrow \\text{Conservation Law}",
    discoverer: "Emmy Noether",
    year: "1918",
    field: "Theoretical Physics / Abstract Algebra",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Every continuous symmetry of a physical system corresponds to a conservation law. Einstein called it 'the most important theorem in physics.'",
    constants: "Symmetry groups, conserved currents",
    applications: "Particle physics, cosmology, quantum field theory",
    beauty: 10,
    difficulty: 'sota',
  },
  {
    rank: 24,
    name: "Quadratic Formula",
    equation: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    discoverer: "Ancient (Babylonian / al-Khwarizmi)",
    year: "~2000 BC / 820 AD",
    field: "Algebra",
    domain: "Mathematics",
    domainEmoji: "📐",
    significance: "Solves any quadratic equation. One of the first general-purpose algebraic formulas, spanning from ancient Babylon to modern classrooms.",
    constants: "a, b, c = polynomial coefficients",
    applications: "Physics, engineering, optimization, ballistics",
    beauty: 7,
    difficulty: 'easy',
  },
  {
    rank: 25,
    name: "Wave Equation",
    equation: "\\frac{\\partial^2 u}{\\partial t^2} = c^2 \\nabla^2 u",
    discoverer: "Jean le Rond d'Alembert",
    year: "1747",
    field: "Mathematical Physics",
    domain: "Physics",
    domainEmoji: "⚛️",
    significance: "Describes the propagation of waves — sound, light, water, seismic. One of the most important PDEs in all of science.",
    constants: "c = wave speed, u = displacement",
    applications: "Acoustics, seismology, optics, electromagnetic waves",
    beauty: 8,
    difficulty: 'hard',
  },
];

/** All unique domains */
export const EQUATION_DOMAINS = [...new Set(EQUATIONS.map((e) => e.domain))];

/** All unique difficulty levels */
export const EQUATION_DIFFICULTIES = [...new Set(EQUATIONS.map((e) => e.difficulty))];
