// ============================================================
// Thinker Mode Configuration — THINKER_REGISTRY
// ============================================================

export interface ThinkerMeta {
  slug: string;
  name: string;
  archetype: string;
  emoji: string;
  era: string;
  domain: string;
  /** Field slugs from the FIELDS registry for structured filtering */
  fields: string[];
  description: string;
  color: string;
  tagline: string;
  era_group: 'ancient' | 'modern' | 'contemporary' | 'prodigy';
  funFact?: string;
}

export const THINKERS: ThinkerMeta[] = [
  // ── Ancient thinkers (pre-1900 birth) ─────────────────────
  {
    slug: 'pythagoras',
    name: 'Pythagoras of Samos',
    archetype: 'The Harmonist',
    emoji: '🔺',
    era: '≈570–495 BC',
    domain: 'Geometry & Number Theory',
    fields: ['math'],
    description: 'a²+b²=c², Irrational Numbers, Musical Ratios',
    color: 'success',
    tagline: 'He found that the universe speaks in numbers.',
    era_group: 'ancient',
    funFact: 'His followers were forbidden from eating beans — possibly because they believed souls resided in them.',
  },
  {
    slug: 'euclid',
    name: 'Euclid of Alexandria',
    archetype: 'The Axiomatist',
    emoji: '📐',
    era: '≈300 BC',
    domain: 'Geometry & Logic',
    fields: ['math'],
    description: 'Axiomatic Geometry, Infinitely Many Primes, GCD Algorithm',
    color: 'accent',
    tagline: 'He built all of geometry from five humble axioms.',
    era_group: 'ancient',
    funFact: 'His "Elements" was the second most printed book in history after the Bible for over 2000 years.',
  },
  {
    slug: 'archimedes',
    name: 'Archimedes of Syracuse',
    archetype: 'The Mechanic',
    emoji: '⚖️',
    era: '≈287–212 BC',
    domain: 'Calculus & Mechanics',
    fields: ['math', 'physics', 'engineering'],
    description: 'Proto-Calculus, Buoyancy, Spiral, π Approximation',
    color: 'success',
    tagline: 'He invented integral calculus 1800 years early.',
    era_group: 'ancient',
    funFact: 'He reportedly set Roman ships on fire using mirrors to focus sunlight — the original "death ray."',
  },
  {
    slug: 'alkhwarizmi',
    name: 'Al-Khwarizmi',
    archetype: 'The Algebraist',
    emoji: '📜',
    era: '≈780–850',
    domain: 'Algebra & Algorithms',
    fields: ['math', 'cs'],
    description: 'Al-Jabr, Hindu-Arabic Numerals, Systematic Equation Solving',
    color: 'primary',
    tagline: 'He gave us algebra — and the word "algorithm."',
    era_group: 'ancient',
    funFact: 'The word "algorithm" is a Latinization of his name: Al-Khwarizmi → Algoritmi.',
  },
  {
    slug: 'newton',
    name: 'Isaac Newton',
    archetype: 'The Physicist',
    emoji: '🍎',
    era: '1643–1727',
    domain: 'Calculus & Mechanics',
    fields: ['math', 'physics'],
    description: 'Calculus, Laws of Motion, Gravitation, Newton\'s Method',
    color: 'primary',
    tagline: 'He unified Earth and sky with a single equation.',
    era_group: 'ancient',
    funFact: 'He was Warden of the Royal Mint and personally hunted down counterfeiters.',
  },
  {
    slug: 'leibniz',
    name: 'Gottfried Wilhelm Leibniz',
    archetype: 'The Polymath',
    emoji: '∂',
    era: '1646–1716',
    domain: 'Calculus & Logic',
    fields: ['math', 'cs'],
    description: 'dy/dx Notation, Binary System, Calculus Ratiocinator',
    color: 'accent',
    tagline: 'He dreamed of a machine that could reason.',
    era_group: 'ancient',
    funFact: 'He invented binary arithmetic in 1679 — the foundation of every digital computer — inspired by the Chinese I Ching.',
  },
  {
    slug: 'euler',
    name: 'Leonhard Euler',
    archetype: 'The Prolific',
    emoji: '🔢',
    era: '1707–1783',
    domain: 'Analysis & Graph Theory',
    fields: ['math'],
    description: 'e^{iπ}+1=0, Graph Theory, Euler Characteristic, π²/6',
    color: 'destructive',
    tagline: 'He wrote more mathematics than any human before or since.',
    era_group: 'ancient',
    funFact: 'He went blind in both eyes but continued producing 400+ pages of mathematics per year by dictating.',
  },
  {
    slug: 'gauss',
    name: 'Carl Friedrich Gauss',
    archetype: 'The Prince',
    emoji: '👑',
    era: '1777–1855',
    domain: 'Number Theory & Statistics',
    fields: ['math'],
    description: 'Normal Distribution, Gaussian Elimination, FFT, Modular Arithmetic',
    color: 'accent',
    tagline: 'He was doing modern mathematics at age 19.',
    era_group: 'ancient',
    funFact: 'At age 10, he instantly summed 1+2+...+100 = 5050 by pairing numbers, stunning his teacher.',
  },
  {
    slug: 'lovelace',
    name: 'Ada Lovelace',
    archetype: 'The Visionary',
    emoji: '💻',
    era: '1815–1852',
    domain: 'Computing & Algorithms',
    fields: ['cs'],
    description: 'First Algorithm, Analytical Engine Notes, General Computation',
    color: 'primary',
    tagline: 'She wrote the first computer program — for a machine that didn\'t exist yet.',
    era_group: 'ancient',
    funFact: 'She was Lord Byron\'s daughter but never met him — her mother steered her toward math to prevent "poetic madness."',
  },
  {
    slug: 'riemann',
    name: 'Bernhard Riemann',
    archetype: 'The Navigator',
    emoji: '🌐',
    era: '1826–1866',
    domain: 'Differential Geometry',
    fields: ['math'],
    description: 'Riemannian Metrics, Curved Spaces, Geodesics',
    color: 'accent',
    tagline: 'He curved space before Einstein needed it.',
    era_group: 'ancient',
    funFact: 'He died at 39, but his single 8-page paper on prime numbers spawned 150+ years of research.',
  },
  {
    slug: 'poincare',
    name: 'Henri Poincaré',
    archetype: 'The Geometer',
    emoji: '🌀',
    era: '1854–1912',
    domain: 'Topology & Chaos',
    fields: ['math', 'physics'],
    description: 'Topology, Chaos Theory, Manifolds, Poincaré Conjecture',
    color: 'destructive',
    tagline: 'He found that the universe cannot be predicted.',
    era_group: 'ancient',
    funFact: 'He discovered chaos theory while trying to win a prize for solving the three-body problem — and found it unsolvable.',
  },
  {
    slug: 'curie',
    name: 'Marie Curie',
    archetype: 'The Pioneer',
    emoji: '☢️',
    era: '1867–1934',
    domain: 'Radioactivity & Nuclear Physics',
    fields: ['physics', 'chemistry'],
    description: 'Radioactivity, Polonium, Radium, Two Nobel Prizes',
    color: 'success',
    tagline: 'She held radioactive elements in her bare hands — for science.',
    era_group: 'ancient',
    funFact: 'Her lab notebooks are still so radioactive they\'re kept in lead-lined boxes; visitors must sign a liability waiver.',
  },
  {
    slug: 'ramanujan',
    name: 'Srinivasa Ramanujan',
    archetype: 'The Oracle',
    emoji: '∞',
    era: '1887–1920',
    domain: 'Pure Mathematics',
    fields: ['math'],
    description: 'Infinite Series, Number Theory, Partition Functions',
    color: 'primary',
    tagline: 'He dreamed of formulas no one had proved.',
    era_group: 'ancient',
    funFact: 'Hardy rated mathematicians on a scale of 100. He gave himself 25, Hilbert 80, and Ramanujan 100.',
  },
  {
    slug: 'fermat',
    name: 'Pierre de Fermat',
    archetype: 'The Marginist',
    emoji: '📝',
    era: '1601–1665',
    domain: 'Number Theory & Probability',
    fields: ['math'],
    description: 'Last Theorem, Little Theorem, Probability Foundations',
    color: 'destructive',
    tagline: 'His margin note tormented mathematicians for 358 years.',
    era_group: 'ancient',
    funFact: 'He was a full-time lawyer and judge who did mathematics as a hobby — arguably the greatest amateur mathematician ever.',
  },
  {
    slug: 'noether',
    name: 'Emmy Noether',
    archetype: 'The Symmetrist',
    emoji: '🔄',
    era: '1882–1935',
    domain: 'Abstract Algebra & Physics',
    fields: ['math', 'physics'],
    description: 'Noether\'s Theorem, Ring Theory, Ideals, Conservation Laws',
    color: 'accent',
    tagline: 'She proved that symmetry is the deepest law of nature.',
    era_group: 'ancient',
    funFact: 'Einstein called her "the most significant creative mathematical genius thus far produced since higher education opened to women."',
  },
  // ── Modern thinkers (1900-1980 birth) ─────────────────────
  {
    slug: 'einstein',
    name: 'Albert Einstein',
    archetype: 'The Relativist',
    emoji: '⚡',
    era: '1879–1955',
    domain: 'Relativity & Quantum Theory',
    fields: ['physics'],
    description: 'E=mc², General Relativity, Photoelectric Effect, Brownian Motion',
    color: 'primary',
    tagline: 'He reimagined space, time, and the nature of light.',
    era_group: 'modern',
    funFact: 'He won the Nobel Prize for the photoelectric effect, not relativity — because the committee wasn\'t sure relativity was correct.',
  },
  {
    slug: 'godel',
    name: 'Kurt Gödel',
    archetype: 'The Limiter',
    emoji: '🚫',
    era: '1906–1978',
    domain: 'Mathematical Logic',
    fields: ['math', 'cs'],
    description: 'Incompleteness Theorems, Completeness Theorem, Constructible Universe',
    color: 'destructive',
    tagline: 'He proved that mathematics cannot fully know itself.',
    era_group: 'modern',
    funFact: 'He found a logical loophole in the US Constitution that could legally allow a dictatorship — Einstein had to stop him from telling the judge at his citizenship hearing.',
  },
  {
    slug: 'dirac',
    name: 'Paul Dirac',
    archetype: 'The Elegant',
    emoji: '🎭',
    era: '1902–1984',
    domain: 'Quantum Mechanics',
    fields: ['physics'],
    description: 'Dirac Equation, Antimatter Prediction, Bra-Ket Notation',
    color: 'accent',
    tagline: 'He predicted antimatter with pure mathematics.',
    era_group: 'modern',
    funFact: 'He was so famously laconic that Cambridge colleagues defined a "dirac" as one word per hour.',
  },
  {
    slug: 'turing',
    name: 'Alan Turing',
    archetype: 'The Logician',
    emoji: '⚙️',
    era: '1912–1954',
    domain: 'Computability',
    fields: ['cs', 'math'],
    description: 'Turing Machines, Halting Problem, Turing Test',
    color: 'accent',
    tagline: 'He defined what a computer could ever do.',
    era_group: 'modern',
    funFact: 'He chained his coffee mug to a radiator to prevent it from being stolen at Bletchley Park.',
  },
  {
    slug: 'shannon',
    name: 'Claude Shannon',
    archetype: 'The Messenger',
    emoji: '📡',
    era: '1916–2001',
    domain: 'Information Theory',
    fields: ['cs', 'math', 'engineering'],
    description: 'Entropy, Channel Capacity, Data Compression',
    color: 'success',
    tagline: 'He turned noise into signal — and bits into science.',
    era_group: 'modern',
    funFact: 'He built a flame-throwing trumpet and rode a unicycle through the halls of Bell Labs while juggling.',
  },
  {
    slug: 'feynman',
    name: 'Richard Feynman',
    archetype: 'The Explainer',
    emoji: '⚛️',
    era: '1918–1988',
    domain: 'Quantum Physics & Computing',
    fields: ['physics', 'cs'],
    description: 'Path Integrals, Quantum Computing, Physics-Informed NNs',
    color: 'primary',
    tagline: 'He made the impossible feel obvious.',
    era_group: 'modern',
    funFact: 'He cracked safes at Los Alamos during the Manhattan Project — for fun — and left notes inside saying "guess who?"',
  },
  {
    slug: 'kolmogorov',
    name: 'Andrey Kolmogorov',
    archetype: 'The Foundationalist',
    emoji: '🎲',
    era: '1903–1987',
    domain: 'Probability & Complexity',
    fields: ['math', 'cs'],
    description: 'Probability Axioms, Kolmogorov Complexity, Turbulence Theory',
    color: 'success',
    tagline: 'He gave probability its mathematical soul.',
    era_group: 'modern',
    funFact: 'He contributed to 25+ fields including topology, turbulence, linguistics, and music — possibly the most versatile mathematician of the 20th century.',
  },
  {
    slug: 'vonneumann',
    name: 'John von Neumann',
    archetype: 'The Architect',
    emoji: '🏛️',
    era: '1903–1957',
    domain: 'Game Theory & Architecture',
    fields: ['math', 'cs', 'economics'],
    description: 'Minimax, Game Theory, Von Neumann Architecture',
    color: 'success',
    tagline: 'He designed the mind of every modern computer.',
    era_group: 'modern',
    funFact: 'He could memorize entire books and recite them years later. He once entertained guests by reciting the first chapter of A Tale of Two Cities from memory.',
  },
  {
    slug: 'hawking',
    name: 'Stephen Hawking',
    archetype: 'The Cosmologist',
    emoji: '🕳️',
    era: '1942–2018',
    domain: 'Black Holes & Cosmology',
    fields: ['physics', 'earth-space'],
    description: 'Hawking Radiation, Black Hole Thermodynamics, Singularity Theorems',
    color: 'destructive',
    tagline: 'He made black holes glow — and the universe understandable.',
    era_group: 'modern',
    funFact: 'Given 2 years to live at 21, he lived to 76 and became the most famous scientist since Einstein.',
  },
  {
    slug: 'pearl',
    name: 'Judea Pearl',
    archetype: 'The Causalist',
    emoji: '🔀',
    era: '1936–present',
    domain: 'Causal Inference',
    fields: ['cs', 'math'],
    description: 'Do-Calculus, Causal Diagrams, Bayesian Networks',
    color: 'destructive',
    tagline: 'He taught machines to ask "why?"',
    era_group: 'modern',
    funFact: 'His son Daniel Pearl was the journalist murdered in 2002; Judea founded a foundation for cross-cultural dialogue in his memory.',
  },
  {
    slug: 'simons',
    name: 'Jim Simons',
    archetype: 'The Quant',
    emoji: '📈',
    era: '1938–2024',
    domain: 'Quantitative Finance',
    fields: ['quant', 'math'],
    description: 'Hidden Markov Models, Stochastic Calculus, Arbitrage',
    color: 'accent',
    tagline: 'He weaponized mathematics against the market.',
    era_group: 'modern',
    funFact: 'His Medallion Fund averaged 66% annual returns before fees for 30 years — the best track record in investing history.',
  },
  {
    slug: 'hinton',
    name: 'Geoffrey Hinton',
    archetype: 'The Godfather',
    emoji: '🧠',
    era: '1947–present',
    domain: 'Deep Learning',
    fields: ['cs'],
    description: 'Backpropagation, Boltzmann Machines, Capsule Networks',
    color: 'primary',
    tagline: 'He taught machines to learn from their mistakes.',
    era_group: 'modern',
    funFact: 'He can\'t sit down due to a back injury, so he\'s worked standing or lying down for decades.',
  },
  {
    slug: 'bengio',
    name: 'Yoshua Bengio',
    archetype: 'The Representor',
    emoji: '🎓',
    era: '1964–present',
    domain: 'Representation Learning',
    fields: ['cs'],
    description: 'Word Embeddings, Attention, GFlowNets, Causal AI',
    color: 'primary',
    tagline: 'He taught machines to represent meaning itself.',
    era_group: 'modern',
    funFact: 'He kept working on neural networks during the "AI winter" when most researchers abandoned them.',
  },
  {
    slug: 'lecun',
    name: 'Yann LeCun',
    archetype: 'The Vision Master',
    emoji: '👁️',
    era: '1960–present',
    domain: 'Computer Vision',
    fields: ['cs'],
    description: 'CNNs, LeNet, Energy-Based Models, JEPA, World Models',
    color: 'accent',
    tagline: 'He gave machines the gift of sight.',
    era_group: 'modern',
    funFact: 'His LeNet-5 was reading checks at banks in the 1990s — deep learning was useful decades before it was trendy.',
  },
  {
    slug: 'sutton',
    name: 'Richard Sutton',
    archetype: 'The Reinforcer',
    emoji: '🎮',
    era: '1956–present',
    domain: 'Reinforcement Learning',
    fields: ['cs'],
    description: 'TD Learning, Policy Gradients, Dyna, The Bitter Lesson',
    color: 'success',
    tagline: 'He showed that reward is all you need.',
    era_group: 'modern',
    funFact: 'His "Bitter Lesson" essay argues that leveraging computation always beats clever human-designed features — a controversial but prescient view.',
  },
  {
    slug: 'vapnik',
    name: 'Vladimir Vapnik',
    archetype: 'The Statistician',
    emoji: '📊',
    era: '1936–present',
    domain: 'Statistical Learning',
    fields: ['cs', 'math'],
    description: 'SVMs, Kernel Methods, VC Theory, PAC Learning',
    color: 'primary',
    tagline: 'He gave learning theory its mathematical foundation.',
    era_group: 'modern',
    funFact: 'He developed SVMs in 1963 but they only became famous in the 1990s when computers could finally run them.',
  },
  // ── Contemporary thinkers (active today, post-1980 birth or recent) ──
  {
    slug: 'goodfellow',
    name: 'Ian Goodfellow',
    archetype: 'The Adversary',
    emoji: '⚔️',
    era: '1985–present',
    domain: 'Generative AI',
    fields: ['cs'],
    description: 'GANs, Adversarial Examples, WGAN, Deep Learning Textbook',
    color: 'destructive',
    tagline: 'He pitted two AIs against each other — and magic happened.',
    era_group: 'contemporary',
    funFact: 'He invented GANs after an argument at a bar — went home, coded it up, and it worked on the first try.',
  },
  {
    slug: 'hassabis',
    name: 'Demis Hassabis',
    archetype: 'The Gamer',
    emoji: '🎯',
    era: '1976–present',
    domain: 'AGI & Protein Folding',
    fields: ['cs', 'biology'],
    description: 'AlphaGo, AlphaFold, AlphaZero, Neuroscience-AI Bridge',
    color: 'primary',
    tagline: 'He taught AI to master Go, fold proteins, and dream.',
    era_group: 'contemporary',
    funFact: 'He was a chess prodigy (2nd highest-rated under-14 in the world) and designed the hit game Theme Park at age 17.',
  },
  {
    slug: 'vaswani',
    name: 'Ashish Vaswani',
    archetype: 'The Attender',
    emoji: '🔮',
    era: '1986–present',
    domain: 'Sequence Modeling',
    fields: ['cs'],
    description: 'Transformer Architecture, Self-Attention, Positional Encodings',
    color: 'accent',
    tagline: '"Attention is all you need" — and it was.',
    era_group: 'contemporary',
    funFact: 'The original "Attention Is All You Need" paper had 8 authors — all left Google to start their own AI companies.',
  },
  {
    slug: 'karpathy',
    name: 'Andrej Karpathy',
    archetype: 'The Educator',
    emoji: '🎥',
    era: '1986–present',
    domain: 'Neural Networks & Autonomy',
    fields: ['cs', 'engineering'],
    description: 'char-rnn, Software 2.0, Tesla Autopilot Vision, nanoGPT',
    color: 'success',
    tagline: 'He made deep learning understandable — and driveable.',
    era_group: 'contemporary',
    funFact: 'His YouTube series "Neural Networks: Zero to Hero" has millions of views — he quit OpenAI and Tesla to become a full-time AI educator.',
  },
  {
    slug: 'altman',
    name: 'Sam Altman',
    archetype: 'The Scaler',
    emoji: '🚀',
    era: '1985–present',
    domain: 'AGI Strategy & Scaling',
    fields: ['cs'],
    description: 'OpenAI CEO, GPT-4, ChatGPT, Scaling Laws',
    color: 'primary',
    tagline: 'He bet everything on scaling — and won.',
    era_group: 'contemporary',
    funFact: 'He was fired and rehired as OpenAI CEO within 5 days in November 2023 — the fastest executive comeback in tech history.',
  },
  {
    slug: 'amodei',
    name: 'Dario Amodei',
    archetype: 'The Alignist',
    emoji: '🛡️',
    era: '1983–present',
    domain: 'AI Safety & Alignment',
    fields: ['cs'],
    description: 'Anthropic, Constitutional AI, Claude, Mechanistic Interpretability',
    color: 'accent',
    tagline: 'He left OpenAI to build AI that can be trusted.',
    era_group: 'contemporary',
    funFact: 'Before AI, he was a computational biophysicist — his safety-first approach comes from understanding complex systems that can fail catastrophically.',
  },
  {
    slug: 'ng',
    name: 'Andrew Ng',
    archetype: 'The Democratizer',
    emoji: '🎓',
    era: '1976–present',
    domain: 'ML Education & Data-Centric AI',
    fields: ['cs', 'data-science'],
    description: 'Coursera ML, Google Brain, Landing AI, Data-Centric AI',
    color: 'success',
    tagline: 'He taught the world machine learning — literally.',
    era_group: 'contemporary',
    funFact: 'His free Coursera ML course has over 5 million enrollments — more students than most universities teach in a century.',
  },
  {
    slug: 'li-fei-fei',
    name: 'Fei-Fei Li',
    archetype: 'The Curator',
    emoji: '🖼️',
    era: '1976–present',
    domain: 'Computer Vision & Spatial AI',
    fields: ['cs'],
    description: 'ImageNet, Visual Recognition, Stanford HAI, World Labs',
    color: 'destructive',
    tagline: 'She gave AI the data it needed to see.',
    era_group: 'contemporary',
    funFact: 'She cleaned houses and worked in a dry cleaner as a teenager after immigrating to the US — then became one of the most influential AI scientists in history.',
  },
  {
    slug: 'ilya',
    name: 'Ilya Sutskever',
    archetype: 'The Believer',
    emoji: '🔬',
    era: '1986–present',
    domain: 'Deep Learning & Superintelligence',
    fields: ['cs'],
    description: 'AlexNet, Seq2Seq, GPT series, SSI',
    color: 'primary',
    tagline: 'He saw the future in neural networks before anyone else.',
    era_group: 'contemporary',
    funFact: 'He co-authored both AlexNet (started the deep learning revolution) and the GPT series (started the LLM revolution) — arguably the most impactful CV in AI.',
  },
  // ── Additional Modern & Contemporary MasterMinds ──
  {
    slug: 'hilbert',
    name: 'David Hilbert',
    archetype: 'The Axiomatizer',
    emoji: '📋',
    era: '1862–1943',
    domain: 'Foundations & Geometry',
    fields: ['math'],
    description: '23 Problems, Hilbert Spaces, Formalism, Entscheidungsproblem',
    color: 'primary',
    tagline: 'He challenged mathematics to solve itself — and it couldn\'t.',
    era_group: 'ancient',
    funFact: 'When told a student had dropped math to become a poet, he replied: "Good — he didn\'t have enough imagination for mathematics."',
  },
  {
    slug: 'schmidhuber',
    name: 'Jürgen Schmidhuber',
    archetype: 'The Grandfather',
    emoji: '🔁',
    era: '1963–present',
    domain: 'Recurrent Networks & Creativity',
    fields: ['cs'],
    description: 'LSTM, Formal Creativity Theory, Self-Referential Networks',
    color: 'accent',
    tagline: 'He taught machines to remember — and to be curious.',
    era_group: 'modern',
    funFact: 'He claims to have invented nearly everything in deep learning before everyone else — and he has the papers to back up most of it.',
  },
  {
    slug: 'linnainmaa',
    name: 'Seppo Linnainmaa',
    archetype: 'The Differentiator',
    emoji: '⛓️',
    era: '1945–present',
    domain: 'Automatic Differentiation',
    fields: ['cs', 'math'],
    description: 'Reverse-Mode AD (1970), Backpropagation Foundation, Chain Rule',
    color: 'success',
    tagline: 'He discovered how to compute gradients — before neural networks needed them.',
    era_group: 'modern',
    funFact: 'His 1970 master\'s thesis described backpropagation 16 years before Hinton popularized it — but it was written in Finnish and went largely unnoticed.',
  },
  {
    slug: 'jeff-dean',
    name: 'Jeff Dean',
    archetype: 'The Infra-Builder',
    emoji: '🏗️',
    era: '1968–present',
    domain: 'Distributed Systems & ML Infra',
    fields: ['cs', 'engineering'],
    description: 'MapReduce, TensorFlow, TPUs, Pathways, Gemini',
    color: 'primary',
    tagline: 'He built the infrastructure that makes AI possible at scale.',
    era_group: 'contemporary',
    funFact: 'There are "Jeff Dean Facts" (like Chuck Norris Facts) at Google: "Jeff Dean compiles and runs his code before submitting — to check that the compiler is working."',
  },
  {
    slug: 'kai-fu-lee',
    name: 'Kai-Fu Lee',
    archetype: 'The Bridge-Builder',
    emoji: '🌉',
    era: '1961–present',
    domain: 'Speech Recognition & AI Strategy',
    fields: ['cs'],
    description: 'Sphinx Speech System, AI Superpowers, 4 Waves of AI, Sinovation',
    color: 'accent',
    tagline: 'He bridged AI between East and West.',
    era_group: 'contemporary',
    funFact: 'He led Google China, then became China\'s most influential AI voice. His book "AI Superpowers" sold millions and shaped global AI policy debates.',
  },
  {
    slug: 'kozyrkov',
    name: 'Cassie Kozyrkov',
    archetype: 'The Decision Scientist',
    emoji: '🎯',
    era: '1986–present',
    domain: 'Decision Intelligence & Applied ML',
    fields: ['cs', 'data-science'],
    description: 'Decision Intelligence, A/B Testing Rigor, ML Pitfalls, Data-Driven Decisions',
    color: 'destructive',
    tagline: 'She taught the world to decide before analyzing.',
    era_group: 'contemporary',
    funFact: 'She created Google\'s Decision Intelligence discipline and taught ML to 20,000+ Googlers — making data-driven decisions a company-wide skill.',
  },
  {
    slug: 'suleyman',
    name: 'Mustafa Suleyman',
    archetype: 'The Containment Thinker',
    emoji: '🌊',
    era: '1984–present',
    domain: 'AI Safety & Containment',
    fields: ['cs'],
    description: 'DeepMind Co-founder, Inflection Pi, The Coming Wave, Microsoft AI CEO',
    color: 'success',
    tagline: 'He warned that the wave is coming — and we can\'t stop it.',
    era_group: 'contemporary',
    funFact: 'Before AI, he was a human rights activist and negotiator at age 19. He co-founded DeepMind at 25 with no formal CS degree.',
  },
  {
    slug: 'gebru',
    name: 'Timnit Gebru',
    archetype: 'The Auditor',
    emoji: '⚖️',
    era: '1982–present',
    domain: 'AI Ethics & Fairness',
    fields: ['cs', 'law'],
    description: 'Gender Shades, Datasheets for Datasets, Stochastic Parrots, DAIR',
    color: 'destructive',
    tagline: 'She proved AI sees some people better than others.',
    era_group: 'contemporary',
    funFact: 'Born in Ethiopia, she fled as a refugee and became one of the most influential voices in AI ethics — her Gender Shades paper changed an entire industry.',
  },
  // ── Global MasterMinds — diverse contemporary & modern additions ──
  {
    slug: 'tao',
    name: 'Terence Tao',
    archetype: 'The Universalist',
    emoji: '🌏',
    era: '1975–present',
    domain: 'Harmonic Analysis & Number Theory',
    fields: ['math'],
    description: 'Green–Tao Theorem, Compressed Sensing, Erdős Discrepancy',
    color: 'primary',
    tagline: 'He solves problems across all of mathematics — for fun.',
    era_group: 'contemporary',
    funFact: 'He scored 760 on the SAT math section at age 8 and won the Fields Medal at 31 — often called the "Mozart of math."',
  },
  {
    slug: 'erdos',
    name: 'Paul Erdős',
    archetype: 'The Wanderer',
    emoji: '🧳',
    era: '1913–1996',
    domain: 'Combinatorics & Number Theory',
    fields: ['math'],
    description: 'Probabilistic Method, Ramsey Theory, Random Graphs, 1500+ Papers',
    color: 'accent',
    tagline: 'He lived for mathematics — literally out of a suitcase.',
    era_group: 'modern',
    funFact: 'He published over 1,500 papers with 500+ co-authors, lived out of a single suitcase, and said "A mathematician is a machine for turning coffee into theorems."',
  },
  {
    slug: 'raman',
    name: 'C.V. Raman',
    archetype: 'The Spectroscopist',
    emoji: '🔬',
    era: '1888–1970',
    domain: 'Optics & Molecular Physics',
    fields: ['physics', 'chemistry'],
    description: 'Raman Effect, Light Scattering, Molecular Spectroscopy',
    color: 'success',
    tagline: 'He discovered that light carries the fingerprint of molecules.',
    era_group: 'modern',
    funFact: 'He made his Nobel Prize-winning discovery with equipment costing less than $200 — proving that great science doesn\'t require expensive labs.',
  },
  {
    slug: 'mirzakhani',
    name: 'Maryam Mirzakhani',
    archetype: 'The Explorer',
    emoji: '🌸',
    era: '1977–2017',
    domain: 'Geometry & Dynamics',
    fields: ['math'],
    description: 'Riemann Surfaces, Moduli Spaces, Geodesic Counting, Ergodic Theory',
    color: 'destructive',
    tagline: 'She mapped the hidden geometry of curved universes.',
    era_group: 'contemporary',
    funFact: 'She worked by drawing on huge sheets of paper on the floor — her daughter called it "painting." She is the only woman to win the Fields Medal.',
  },
  {
    slug: 'chern',
    name: 'Shiing-Shen Chern',
    archetype: 'The Geometer',
    emoji: '🔷',
    era: '1911–2004',
    domain: 'Differential Geometry & Topology',
    fields: ['math'],
    description: 'Chern Classes, Chern–Simons Theory, Chern–Gauss–Bonnet, Fiber Bundles',
    color: 'accent',
    tagline: 'He bridged the gap between geometry and topology.',
    era_group: 'modern',
    funFact: 'He founded mathematics institutes in both the US (MSRI in Berkeley) and China (Nankai), shaping modern math on two continents.',
  },
  {
    slug: 'yitang-zhang',
    name: 'Yitang Zhang',
    archetype: 'The Perseverer',
    emoji: '🔢',
    era: '1955–present',
    domain: 'Analytic Number Theory',
    fields: ['math'],
    description: 'Bounded Prime Gaps, Landau–Siegel Zeros, Sieve Methods',
    color: 'primary',
    tagline: 'He proved the impossible — after decades in obscurity.',
    era_group: 'contemporary',
    funFact: 'He worked at Subway restaurants and as a motel accountant before his breakthrough paper at age 58 — one of the greatest "late bloomer" stories in science.',
  },
  {
    slug: 'goldwasser',
    name: 'Shafi Goldwasser',
    archetype: 'The Cryptographer',
    emoji: '🔐',
    era: '1958–present',
    domain: 'Cryptography & Complexity',
    fields: ['cs', 'math'],
    description: 'Zero-Knowledge Proofs, Semantic Security, Interactive Proofs',
    color: 'destructive',
    tagline: 'She taught machines to prove without revealing.',
    era_group: 'contemporary',
    funFact: 'Born in New York to Israeli parents, she won two Gödel Prizes and the Turing Award — the highest honor in computer science.',
  },
  {
    slug: 'kashiwara',
    name: 'Masaki Kashiwara',
    archetype: 'The Analyst',
    emoji: '📖',
    era: '1947–present',
    domain: 'Algebraic Analysis & Representation Theory',
    fields: ['math'],
    description: 'D-Modules, Crystal Bases, Microlocal Analysis, Riemann–Hilbert Correspondence',
    color: 'success',
    tagline: 'He turned differential equations into algebra — and algebra into crystals.',
    era_group: 'modern',
    funFact: 'He won the Abel Prize (2025) — Japan\'s first Abel laureate — for work spanning 50 years across analysis, algebra, and geometry.',
  },
  {
    slug: 'birkar',
    name: 'Caucher Birkar',
    archetype: 'The Classifier',
    emoji: '🏔️',
    era: '1978–present',
    domain: 'Birational Geometry',
    fields: ['math'],
    description: 'BAB Conjecture, Minimal Model Program, Fano Varieties',
    color: 'accent',
    tagline: 'From Kurdish refugee to Fields Medalist — he classifies the shapes of the universe.',
    era_group: 'contemporary',
    funFact: 'His Fields Medal was stolen from its case within minutes of the ceremony in Rio de Janeiro — he was given a replacement.',
  },
  {
    slug: 'grothendieck',
    name: 'Alexander Grothendieck',
    archetype: 'The Architect',
    emoji: '🏗️',
    era: '1928–2014',
    domain: 'Algebraic Geometry & Category Theory',
    fields: ['math'],
    description: 'Schemes, Étale Cohomology, Toposes, Derived Categories, Motives',
    color: 'destructive',
    tagline: 'He rebuilt mathematics from scratch — twice.',
    era_group: 'modern',
    funFact: 'Born stateless to anarchist parents fleeing Nazi Germany, he became perhaps the greatest mathematician of the 20th century, then abandoned mathematics at 42 to live as a recluse.',
  },
  {
    slug: 'kovalevskaya',
    name: 'Sofia Kovalevskaya',
    archetype: 'The Trailblazer',
    emoji: '🌊',
    era: '1850–1891',
    domain: 'Analysis & Mechanics',
    fields: ['math', 'physics'],
    description: 'Cauchy–Kovalevskaya Theorem, Kovalevskaya Top, Rigid Body Dynamics',
    color: 'primary',
    tagline: 'She solved what no one else could — and broke barriers while doing it.',
    era_group: 'ancient',
    funFact: 'She entered a sham marriage just to leave Russia and attend university — because Russian women were not allowed to study abroad without a husband\'s permission.',
  },
  // ── Earth & Space thinkers ──────────────────────────────────
  {
    slug: 'carl-sagan',
    name: 'Carl Sagan',
    archetype: 'The Communicator',
    emoji: '🌌',
    era: '1934–1996',
    domain: 'Planetary Science & Cosmology',
    fields: ['earth-space'],
    description: 'Cosmos, Pale Blue Dot, SETI, Planetary Atmospheres, Nuclear Winter',
    color: 'primary',
    tagline: 'He made the cosmos personal — billions and billions of times.',
    era_group: 'modern',
    funFact: 'He pushed NASA to turn Voyager 1 around to photograph Earth from 6 billion km away — the iconic "Pale Blue Dot" image.',
  },
  {
    slug: 'wegener',
    name: 'Alfred Wegener',
    archetype: 'The Drifter',
    emoji: '🗺️',
    era: '1880–1930',
    domain: 'Continental Drift & Meteorology',
    fields: ['earth-space'],
    description: 'Continental Drift, Pangaea, Paleoclimatology, Polar Expeditions',
    color: 'accent',
    tagline: 'He saw that continents moved — and nobody believed him for 50 years.',
    era_group: 'modern',
    funFact: 'He died on a supply expedition across the Greenland ice sheet. His theory of continental drift was ridiculed until plate tectonics proved him right in the 1960s.',
  },
  {
    slug: 'vera-rubin',
    name: 'Vera Rubin',
    archetype: 'The Dark Matter Pioneer',
    emoji: '🌑',
    era: '1928–2016',
    domain: 'Galactic Astronomy & Dark Matter',
    fields: ['earth-space', 'physics'],
    description: 'Galaxy Rotation Curves, Dark Matter Evidence, Observational Astronomy',
    color: 'destructive',
    tagline: 'She proved the universe is mostly invisible.',
    era_group: 'modern',
    funFact: 'She was told Princeton didn\'t accept women in astronomy. She proved dark matter exists — arguably the most important unrecognized Nobel-worthy discovery.',
  },
  // ── Economics thinkers ──────────────────────────────────────
  {
    slug: 'adam-smith',
    name: 'Adam Smith',
    archetype: 'The Invisible Hand',
    emoji: '🤝',
    era: '1723–1790',
    domain: 'Political Economy & Markets',
    fields: ['economics'],
    description: 'Wealth of Nations, Invisible Hand, Division of Labor, Free Markets',
    color: 'primary',
    tagline: 'He explained how self-interest creates public good.',
    era_group: 'ancient',
    funFact: 'He was so absent-minded he once fell into a tanning pit while deep in conversation about trade policy.',
  },
  {
    slug: 'john-nash',
    name: 'John Nash',
    archetype: 'The Equilibrist',
    emoji: '♟️',
    era: '1928–2015',
    domain: 'Game Theory & Equilibria',
    fields: ['economics', 'math'],
    description: 'Nash Equilibrium, Bargaining Problem, Embedding Theorem, Differential Equations',
    color: 'accent',
    tagline: 'He found the balance point where no player wants to move.',
    era_group: 'modern',
    funFact: 'He battled schizophrenia for decades, then made a remarkable recovery and won the Nobel Prize in 1994 — the story behind "A Beautiful Mind."',
  },
  {
    slug: 'keynes',
    name: 'John Maynard Keynes',
    archetype: 'The Macro Thinker',
    emoji: '📉',
    era: '1883–1946',
    domain: 'Macroeconomics & Fiscal Policy',
    fields: ['economics'],
    description: 'General Theory, Aggregate Demand, Multiplier Effect, Liquidity Trap',
    color: 'success',
    tagline: 'He argued governments should spend when no one else will.',
    era_group: 'modern',
    funFact: 'He personally managed King\'s College Cambridge endowment, growing it 10x. He also amassed a fortune speculating on currencies — while lying in bed each morning.',
  },
  // ── Engineering thinkers ──────────────────────────────────────
  {
    slug: 'nikola-tesla',
    name: 'Nikola Tesla',
    archetype: 'The Visionary Engineer',
    emoji: '⚡',
    era: '1856–1943',
    domain: 'Electrical Engineering & Electromagnetics',
    fields: ['engineering', 'physics'],
    description: 'AC Power, Tesla Coil, Induction Motor, Wireless Transmission, Polyphase Systems',
    color: 'accent',
    tagline: 'He lit the world with alternating current — and imagined wireless power.',
    era_group: 'ancient',
    funFact: 'He could visualize entire machines in his head, run them mentally, and check for wear — all before building a single prototype.',
  },
  {
    slug: 'wernher-von-braun',
    name: 'Wernher von Braun',
    archetype: 'The Rocketeer',
    emoji: '🚀',
    era: '1912–1977',
    domain: 'Rocket Engineering & Spaceflight',
    fields: ['engineering', 'earth-space'],
    description: 'Saturn V, V-2 Rocket, Moon Landing Architecture, Multi-Stage Rockets',
    color: 'primary',
    tagline: 'He built the rocket that put humans on the Moon.',
    era_group: 'modern',
    funFact: 'He surrendered to Americans with 500 scientists and 300 rail cars of V-2 parts. His Saturn V remains the most powerful rocket ever successfully flown.',
  },
  {
    slug: 'hedy-lamarr',
    name: 'Hedy Lamarr',
    archetype: 'The Secret Inventor',
    emoji: '📻',
    era: '1914–2000',
    domain: 'Communications Engineering & Signal Processing',
    fields: ['engineering', 'cs'],
    description: 'Frequency Hopping, Spread Spectrum, Torpedo Guidance, Wireless Security',
    color: 'destructive',
    tagline: 'Hollywood star by day — she invented the tech behind WiFi and Bluetooth.',
    era_group: 'modern',
    funFact: 'She co-invented frequency-hopping spread spectrum to help WWII torpedoes avoid jamming. It became the basis for WiFi, Bluetooth, and GPS.',
  },
  // ── Biology thinkers ──────────────────────────────────────
  {
    slug: 'darwin',
    name: 'Charles Darwin',
    archetype: 'The Naturalist',
    emoji: '🐢',
    era: '1809–1882',
    domain: 'Evolutionary Biology & Natural Selection',
    fields: ['biology'],
    description: 'Origin of Species, Natural Selection, Common Descent, Sexual Selection',
    color: 'success',
    tagline: 'He showed that all life shares a single family tree.',
    era_group: 'ancient',
    funFact: 'He ate almost every animal he studied, including owl, puma, and giant tortoise. He also waited 20 years to publish his theory.',
  },
  {
    slug: 'rosalind-franklin',
    name: 'Rosalind Franklin',
    archetype: 'The Crystallographer',
    emoji: '🔬',
    era: '1920–1958',
    domain: 'Molecular Biology & X-ray Crystallography',
    fields: ['biology', 'chemistry'],
    description: 'Photo 51, DNA Structure, Virus Crystallography, Coal Microstructure',
    color: 'accent',
    tagline: 'Her X-ray photograph revealed the double helix — without credit.',
    era_group: 'modern',
    funFact: 'Photo 51, her X-ray diffraction image of DNA, was shown to Watson without her knowledge. She died at 37, four years before the Nobel was awarded.',
  },
  {
    slug: 'jennifer-doudna',
    name: 'Jennifer Doudna',
    archetype: 'The Gene Editor',
    emoji: '✂️',
    era: '1964–present',
    domain: 'Genetic Engineering & CRISPR',
    fields: ['biology', 'chemistry', 'medical'],
    description: 'CRISPR-Cas9, Gene Editing, RNA Biology, Structural Biology',
    color: 'primary',
    tagline: 'She gave humanity the power to rewrite the code of life.',
    era_group: 'contemporary',
    funFact: 'She had a nightmare about Hitler asking to learn CRISPR — it haunted her ethics work. She won the Nobel Prize in Chemistry in 2020.',
  },
  // ── Prodigies — remarkable minds from a young age ──────────
  {
    slug: 'pascal',
    name: 'Blaise Pascal',
    archetype: 'The Inventor',
    emoji: '🔧',
    era: '1623–1662',
    domain: 'Probability & Mechanics',
    fields: ['math', 'physics'],
    description: 'Pascaline Calculator, Pascal\'s Triangle, Probability Theory, Pascal\'s Wager',
    color: 'primary',
    tagline: 'He built a mechanical calculator at 19 and invented probability.',
    era_group: 'prodigy',
    funFact: 'He proved 32 propositions of Euclid by age 12, having taught himself geometry with charcoal drawings on tiles.',
  },
  {
    slug: 'galois',
    name: 'Évariste Galois',
    archetype: 'The Revolutionary',
    emoji: '⚔️',
    era: '1811–1832',
    domain: 'Abstract Algebra',
    fields: ['math'],
    description: 'Galois Theory, Group Theory, Field Extensions, Unsolvability of Quintics',
    color: 'destructive',
    tagline: 'He invented group theory the night before he died in a duel — at age 20.',
    era_group: 'prodigy',
    funFact: 'He wrote his most important mathematical ideas in a letter the night before his fatal duel, scribbling "I have no time" in the margins.',
  },
  {
    slug: 'hamilton-wr',
    name: 'William Rowan Hamilton',
    archetype: 'The Linguist-Mathematician',
    emoji: '🌉',
    era: '1805–1865',
    domain: 'Algebra & Mechanics',
    fields: ['math', 'physics'],
    description: 'Quaternions, Hamiltonian Mechanics, Icosian Game, Optics',
    color: 'accent',
    tagline: 'He mastered 13 languages by 13 and carved quaternions into a bridge.',
    era_group: 'prodigy',
    funFact: 'By age 5 he could read Latin, Greek, and Hebrew. By 13 he spoke 13 languages including Persian, Arabic, and Sanskrit.',
  },
  {
    slug: 'abel',
    name: 'Niels Henrik Abel',
    archetype: 'The Impossibilist',
    emoji: '🏔️',
    era: '1802–1829',
    domain: 'Algebra & Analysis',
    fields: ['math'],
    description: 'Abel–Ruffini Theorem, Abelian Groups, Elliptic Functions, Abel\'s Theorem',
    color: 'success',
    tagline: 'He proved the quintic unsolvable at 19 — then died at 26.',
    era_group: 'prodigy',
    funFact: 'He lived in extreme poverty and died of tuberculosis at 26. Two days after his death, a letter arrived offering him a prestigious professorship.',
  },
  {
    slug: 'scholze',
    name: 'Peter Scholze',
    archetype: 'The Perfectoid',
    emoji: '💎',
    era: '1987–present',
    domain: 'Arithmetic Geometry',
    fields: ['math'],
    description: 'Perfectoid Spaces, Condensed Mathematics, p-adic Hodge Theory',
    color: 'primary',
    tagline: 'He became a full professor at 24 and won the Fields Medal at 30.',
    era_group: 'prodigy',
    funFact: 'He learned research-level mathematics as a teenager by reading Wiles\' proof of Fermat\'s Last Theorem — and understood it.',
  },
  {
    slug: 'venkatesh',
    name: 'Akshay Venkatesh',
    archetype: 'The Connector',
    emoji: '🔗',
    era: '1981–present',
    domain: 'Number Theory & Dynamics',
    fields: ['math'],
    description: 'Automorphic Forms, Ergodic Methods, Subconvexity Bounds, Langlands Program',
    color: 'accent',
    tagline: 'He started university at 13 and connects worlds that shouldn\'t be connected.',
    era_group: 'prodigy',
    funFact: 'He won a bronze medal at the International Physics Olympiad at age 12 — then switched to mathematics and won the Fields Medal.',
  },
  {
    slug: 'shakuntala-devi',
    name: 'Shakuntala Devi',
    archetype: 'The Human Computer',
    emoji: '🧮',
    era: '1929–2013',
    domain: 'Mental Arithmetic & Number Theory',
    fields: ['math'],
    description: 'Mental Multiplication, Cube Roots, Calendar Calculation, Guinness Records',
    color: 'success',
    tagline: 'She multiplied two 13-digit numbers in her head in 28 seconds.',
    era_group: 'prodigy',
    funFact: 'She could tell the day of the week for any date in history instantly. She also wrote one of India\'s first books advocating for LGBTQ rights (1977).',
  },
  {
    slug: 'demaine',
    name: 'Erik Demaine',
    archetype: 'The Folder',
    emoji: '📄',
    era: '1981–present',
    domain: 'Computational Geometry & Origami',
    fields: ['cs', 'math'],
    description: 'Fold-and-Cut Theorem, Computational Origami, PSPACE Puzzles, Data Structures',
    color: 'destructive',
    tagline: 'Youngest MIT professor at 20 — he proved origami is mathematics.',
    era_group: 'prodigy',
    funFact: 'He was homeschooled while traveling across North America and started his PhD at 14. His origami art is in the permanent collection of MoMA.',
  },
];

/** Typed registry map — O(1) lookup by slug */
export const THINKER_REGISTRY: Record<string, ThinkerMeta> = Object.fromEntries(
  THINKERS.map((t) => [t.slug, t])
);

/** Backward-compatible alias */
export const THINKER_MAP = THINKER_REGISTRY;

export function getThinker(slug: string): ThinkerMeta | undefined {
  return THINKER_REGISTRY[slug];
}

export const ANCIENT_THINKERS = THINKERS.filter((t) => t.era_group === 'ancient');
export const MODERN_THINKERS = THINKERS.filter((t) => t.era_group === 'modern');
export const CONTEMPORARY_THINKERS = THINKERS.filter((t) => t.era_group === 'contemporary');
export const PRODIGY_THINKERS = THINKERS.filter((t) => t.era_group === 'prodigy');
