// ── Vault Registry — Humanity's Greatest Classified Secrets ──────────

export interface VaultEntry {
  id: string;
  rank: number;
  name: string;
  codename?: string;
  classifiedYear: string;
  declassifiedYear: string;
  agency: string;
  field: string;
  domain: string;
  domainEmoji: string;
  summary: string;
  fullStory: string;
  keyFigures: string[];
  significance: string;
  legacy: string;
  /** Related quiz topic slug */
  relatedTopic: string;
  /** Secrecy rating 1–10 */
  secrecyLevel: number;
  /** Impact on modern world 1–10 */
  impact: number;
}

export const VAULT_ENTRIES: VaultEntry[] = [
  {
    id: 'gchq-rsa',
    rank: 1,
    name: 'The GCHQ RSA Equations',
    codename: 'Non-Secret Encryption',
    classifiedYear: '1973',
    declassifiedYear: '1997',
    agency: 'GCHQ',
    field: 'Public-Key Cryptography',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Clifford Cocks invented RSA encryption at GCHQ in 1973 — four years before Rivest, Shamir, and Adleman published it publicly.',
    fullStory: 'In the summer of 1973, GCHQ mathematician Clifford Cocks was briefed on a problem posed by his colleague James Ellis: could two parties establish a shared secret over an insecure channel without prior contact? Cocks solved it the same afternoon by recognizing that the mathematical hardness of factoring the product of two large primes could serve as a trapdoor function. He wrote a classified internal memo describing what is now known as RSA encryption. Malcolm Williamson independently invented the equivalent of Diffie-Hellman key exchange the following year. All three discoveries were immediately classified. GCHQ was reportedly approached after Diffie and Hellman published their 1976 paper and Rivest, Shamir, and Adleman published RSA in 1978, but declined to acknowledge priority. James Ellis, who had conceived the foundational idea of "non-secret encryption" in 1970, died on November 25, 1997 — exactly 23 days before the announcement that would have given him public credit.',
    keyFigures: ['Clifford Cocks', 'James Ellis', 'Malcolm Williamson'],
    significance: 'The inventors of the mathematical foundations of internet security died in public obscurity, having been forbidden for 24 years to claim their own discovery.',
    legacy: 'RSA secures every HTTPS connection, digital signature, and cryptocurrency transaction on Earth. The irony: the man who invented it couldn\'t tell anyone.',
    relatedTopic: 'cryptography',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'des-sbox',
    rank: 2,
    name: 'DES S-Box Differential Resistance',
    codename: 'IBM T-Attack',
    classifiedYear: '1974',
    declassifiedYear: '1994',
    agency: 'NSA / IBM',
    field: 'Block Cipher Design',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'IBM discovered differential cryptanalysis in 1974 and engineered DES S-boxes to resist it — then the NSA asked them to keep it secret for 16 years.',
    fullStory: 'In 1974, IBM\'s cryptography team — led by Horst Feistel and including Walter Tuchman and Don Coppersmith — discovered what they called "differential cryptanalysis": a method of attacking block ciphers by analyzing how specific differences in plaintext pairs produce differences in ciphertext pairs. They applied this to design the S-boxes (substitution tables) in DES such that differential characteristics had uniformly low probability, making the cipher resistant to an attack that the public cryptography community would not independently discover for sixteen years. The NSA asked IBM to keep the technique classified. IBM agreed. In 1990, Israeli cryptographers Eli Biham and Adi Shamir independently discovered differential cryptanalysis and published it. Don Coppersmith published IBM\'s original design criteria in 1994, confirming the S-boxes were intentionally engineered to resist the attack.',
    keyFigures: ['Don Coppersmith', 'Horst Feistel', 'Eli Biham', 'Adi Shamir'],
    significance: 'The most consequential deliberate suppression of a mathematical technique in civilian cryptography history.',
    legacy: 'Differential cryptanalysis became a foundational tool for evaluating all modern ciphers. AES candidates were specifically tested against it.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 8,
    impact: 9,
  },
  {
    id: 'skipjack',
    rank: 3,
    name: 'The Skipjack Block Cipher',
    codename: 'Clipper Chip',
    classifiedYear: '1987',
    declassifiedYear: '1998',
    agency: 'NSA',
    field: 'Block Cipher Design',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The only NSA-designed block cipher ever publicly released. An 80-bit key, 32-round Feistel network deployed in the controversial Clipper chip.',
    fullStory: 'Skipjack was developed by the NSA around 1987 and deployed in the Clipper chip — the government\'s controversial key-escrow encryption system for telephone communications. The NSA refused to publish the algorithm, allowing only a panel of five civilian cryptographers to review it under non-disclosure. They pronounced it sound. The public cryptography community was deeply skeptical: any algorithm whose security relied on secrecy rather than mathematical rigor violated Kerckhoffs\'s principle. The Clipper chip program collapsed largely because no one would trust a classified cipher from an intelligence agency. Under pressure, NSA declassified Skipjack on June 24, 1998. Within one day, Biham and Shamir had found an attack against 16 of 32 rounds. Within months, they extended it to 31 of 32 rounds. The declassification revealed that Skipjack\'s structure dated to building blocks developed as early as 1940 — confirming a classified 40+ year cryptographic research program.',
    keyFigures: ['NSA Cryptographic Division', 'Eli Biham', 'Adi Shamir'],
    significance: 'Demonstrated that classified algorithms violate Kerckhoffs\'s principle and that government backdoors erode public trust in cryptographic standards.',
    legacy: 'The Clipper chip\'s failure established the precedent that public cryptographic standards must be openly reviewed. This principle directly shaped AES selection.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 8,
  },
  {
    id: 'enigma',
    rank: 4,
    name: 'The Enigma Decryption',
    codename: 'Ultra',
    classifiedYear: '1940',
    declassifiedYear: '1974',
    agency: 'GC&CS (Bletchley Park)',
    field: 'Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Alan Turing and the Bletchley Park team broke the Enigma cipher, shortening WWII by an estimated 2 years. Kept secret for 29 years after the war ended.',
    fullStory: 'Building on Polish breakthroughs by Marian Rejewski, the British codebreakers at Bletchley Park — led by Alan Turing and Gordon Welchman — developed the Bombe, an electromechanical device that exploited the Enigma machine\'s mathematical weaknesses. The key insight was that Enigma never encrypted a letter as itself, providing a critical constraint. Turing\'s probabilistic approach (Banburismus) reduced the search space for naval Enigma, enabling the Allies to read U-boat communications and win the Battle of the Atlantic. Churchill called the Bletchley Park staff "the geese that laid the golden egg and never cackled." The entire operation — codenamed Ultra — remained classified until 1974, when F.W. Winterbotham published "The Ultra Secret." For 29 years after the war, the thousands who had worked at Bletchley Park kept total silence.',
    keyFigures: ['Alan Turing', 'Gordon Welchman', 'Marian Rejewski', 'Dilly Knox'],
    significance: 'Historians estimate Ultra shortened WWII by 2 years and saved 14 million lives. Turing\'s theoretical work on computability directly led to modern computer science.',
    legacy: 'The conceptual foundation of modern computing was born from wartime cryptanalysis. Turing\'s persecution and death remain a profound moral stain on British history.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'venona',
    rank: 5,
    name: 'The VENONA Decryptions',
    codename: 'VENONA / BRIDE',
    classifiedYear: '1943',
    declassifiedYear: '1995',
    agency: 'US Army SIS / NSA',
    field: 'One-Time Pad Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The US secretly broke Soviet one-time pad messages — supposedly unbreakable — by exploiting key reuse. Kept classified for 52 years.',
    fullStory: 'In 1943, the US Army\'s Signal Intelligence Service began a secret program to decrypt Soviet diplomatic communications. One-time pads are theoretically unbreakable (Shannon proved this in 1949), but wartime Soviet manufacturing errors caused some key pages to be duplicated and reused. Cryptanalyst Meredith Gardner exploited these "depth" collisions, eventually decrypting roughly 3,000 messages that revealed the scope of Soviet espionage in the Manhattan Project. VENONA identified Klaus Fuchs, the Rosenbergs, and dozens of other spies. The program was so secret that even President Truman was reportedly not briefed. VENONA was not declassified until 1995 — 52 years after it began — making it one of the longest-running classified intelligence programs in US history.',
    keyFigures: ['Meredith Gardner', 'Cecil Phillips', 'Gene Grabeel'],
    significance: 'Proved that even "perfect" cryptographic systems fail when implementation is flawed. The gap between theoretical security and operational security remains the central problem of cryptography.',
    legacy: 'VENONA reshaped Cold War historiography. The decryptions definitively settled decades of debate about the extent of Soviet espionage in the US.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 9,
  },
  {
    id: 'dual-ec',
    rank: 6,
    name: 'Dual_EC_DRBG Backdoor',
    codename: 'BULLRUN',
    classifiedYear: '2004',
    declassifiedYear: '2013',
    agency: 'NSA',
    field: 'Random Number Generation',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The NSA inserted a mathematical backdoor into a NIST-standardized random number generator, undermining global cryptographic infrastructure.',
    fullStory: 'In 2004, NIST published Special Publication 800-90A, standardizing four pseudorandom number generators. One of them — Dual_EC_DRBG — was championed by the NSA. In 2007, cryptographers Dan Shumow and Niels Ferguson demonstrated at a rump session of CRYPTO that the algorithm contained what appeared to be a backdoor: the relationship between two elliptic curve points (P and Q) could allow anyone who knew the discrete logarithm between them to predict all future outputs. Despite this, Dual_EC remained a NIST and ISO standard. RSA Security made it the default in their BSAFE library (reportedly after receiving $10 million from the NSA). In 2013, Edward Snowden\'s documents revealed the NSA\'s BULLRUN program, which sought to "insert vulnerabilities into commercial encryption systems." NIST withdrew the standard. RSA Security advised customers to stop using it.',
    keyFigures: ['Dan Shumow', 'Niels Ferguson', 'Edward Snowden'],
    significance: 'The most significant known case of a government deliberately compromising a public cryptographic standard. Shattered trust in NIST standardization processes.',
    legacy: 'Led to complete reform of NIST\'s cryptographic standardization process. The post-quantum cryptography competition was explicitly designed with transparency to prevent a repeat.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'manhattan-implosion',
    rank: 7,
    name: 'The Implosion Lens Equations',
    codename: 'Manhattan Project — Fat Man',
    classifiedYear: '1944',
    declassifiedYear: '1960s (partial)',
    agency: 'Los Alamos / US DoE',
    field: 'Shaped Charge Physics',
    domain: 'Physics',
    domainEmoji: '⚛️',
    summary: 'The mathematical equations for spherical implosion lenses that compress plutonium to supercriticality — the hardest engineering problem of the atomic age.',
    fullStory: 'The gun-type uranium bomb (Little Boy) was straightforward. The plutonium bomb (Fat Man) required solving a far harder problem: simultaneously detonating 32 explosive lenses to produce a perfectly spherical converging shockwave that would compress a plutonium core from subcritical to supercritical in microseconds. The mathematics — hydrodynamic equations governing converging detonation waves in heterogeneous explosive charges — was solved by John von Neumann, who also co-invented the Monte Carlo method at Los Alamos specifically to numerically simulate the implosion process. The lens equations remained classified for decades because they represent the core "secret" of nuclear weapons: the geometry of implosion.',
    keyFigures: ['John von Neumann', 'Seth Neddermeyer', 'George Kistiakowsky'],
    significance: 'Von Neumann\'s work at Los Alamos led to both nuclear weapons and the birth of computational science. The Monte Carlo method, invented to model implosion, now underpins all of computational statistics.',
    legacy: 'Every thermonuclear weapon, every Monte Carlo simulation in finance, every MCMC chain in Bayesian ML — all trace lineage to classified equations written in a New Mexico desert.',
    relatedTopic: 'quantum-mechanics',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'public-key-knapsack',
    rank: 8,
    name: 'NSA Suite A Algorithms',
    codename: 'Suite A',
    classifiedYear: '~1960s',
    declassifiedYear: 'Still classified',
    agency: 'NSA',
    field: 'Classified Cryptographic Algorithms',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The NSA\'s Suite A — a family of classified algorithms for TOP SECRET and above — has never been publicly described. We know they exist. We know nothing else.',
    fullStory: 'The NSA maintains two tiers of cryptographic algorithms: Suite B (public algorithms like AES-256, SHA-384, ECDSA P-384) for SECRET and below, and Suite A for TOP SECRET/SCI and above. Suite A algorithms have never been publicly described — not their names, not their structures, not their key sizes, not their mathematical foundations. The only public knowledge is that they exist, that they are implemented in Type 1 cryptographic equipment, and that they require clearance to access. In 2016, the NSA announced it was transitioning away from Suite B\'s elliptic curve algorithms (due to quantum computing concerns), raising the question of what Suite A has used all along — and whether the NSA\'s classified mathematicians solved the post-quantum problem decades before NIST began its public competition.',
    keyFigures: ['Unknown — NSA cryptographers with no public identity'],
    significance: 'Suite A represents the outer boundary of known unknown cryptography — algorithms that protect the most sensitive intelligence on Earth, designed by mathematicians who cannot publish.',
    legacy: 'The existence of Suite A is a permanent reminder that the publicly known frontier of cryptography may be decades behind the classified frontier.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 8,
  },
  // ── 4 Older Classified Secrets ──────────────────────────────
  {
    id: 'lorenz-colossus',
    rank: 9,
    name: 'The Lorenz Cipher & Colossus',
    codename: 'Tunny / Fish',
    classifiedYear: '1941',
    declassifiedYear: '2000',
    agency: 'GC&CS (Bletchley Park)',
    field: 'Automated Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The world\'s first programmable electronic computer — Colossus — was built in 1943 to break the Lorenz cipher used by Hitler\'s High Command. Its existence was classified for 57 years.',
    fullStory: 'While Enigma encrypted tactical battlefield messages, the Lorenz SZ40/42 cipher machine encrypted Hitler\'s strategic communications with his generals. The cipher used 12 rotors (vs Enigma\'s 3-4) producing a key stream XORed with the Baudot-coded plaintext. Mathematician Bill Tutte reverse-engineered the entire Lorenz machine\'s logical structure from intercepted ciphertext alone — without ever seeing the physical device. To break messages in operational time, Tommy Flowers built Colossus at the Post Office Research Station: a 1,500-valve electronic machine that could process 5,000 characters per second. Ten Colossus machines were built by 1945. After the war, Churchill ordered eight destroyed and the remaining two moved to GCHQ, where they operated until 1960. Their existence was classified until 2000. The entire history of computing was rewritten — ENIAC (1945) was not the first electronic computer.',
    keyFigures: ['Bill Tutte', 'Tommy Flowers', 'Max Newman', 'Ralph Tester'],
    significance: 'The first electronic programmable computer was built 2 years before ENIAC, but the world didn\'t know for 57 years. The entire origin story of computing was wrong.',
    legacy: 'Flowers received £1,000 for his invention and died in relative obscurity. Tutte\'s feat of reverse-engineering an unseen machine from pure mathematics is considered one of the greatest intellectual achievements of the 20th century.',
    relatedTopic: 'cryptography',
    secrecyLevel: 10,
    impact: 10,
  },
  {
    id: 'purple-cipher',
    rank: 10,
    name: 'Breaking Japan\'s Purple Cipher',
    codename: 'MAGIC',
    classifiedYear: '1939',
    declassifiedYear: '1946',
    agency: 'US Army SIS',
    field: 'Electromechanical Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'William Friedman\'s team reverse-engineered Japan\'s "unbreakable" Purple diplomatic cipher machine without ever seeing it — building a functional replica from cryptanalysis alone.',
    fullStory: 'In 1939, Japan deployed a new cipher machine for its highest-level diplomatic communications, which the US codenamed "Purple." William Friedman, head of the Army\'s Signal Intelligence Service, led a team that spent 18 months analyzing intercepted ciphertext. They deduced that Purple used telephone stepping switches (not rotors like Enigma) to create its substitution cipher. The team built a working replica — the "Purple analog" — that could decrypt Japanese diplomatic traffic in real time. The intelligence product, codenamed MAGIC, gave US leaders advance knowledge of Japanese diplomatic positions. The stress of the work caused Friedman to suffer a nervous breakdown. MAGIC intelligence was so sensitive that knowledge of Purple\'s break was restricted to fewer than a dozen people. The irony: the US knew Japan\'s negotiating positions at every stage leading to Pearl Harbor, yet the intelligence was not actionable because sharing it would have revealed the source.',
    keyFigures: ['William Friedman', 'Frank Rowlett', 'Genevieve Grotjan', 'Abraham Sinkov'],
    significance: 'Genevieve Grotjan\'s discovery of the mathematical pattern that cracked Purple is one of the greatest individual codebreaking insights in history — and she received almost no credit for decades.',
    legacy: 'Friedman is now recognized as the father of American cryptanalysis. The MAGIC/Pearl Harbor controversy remains one of the most debated intelligence failures in history.',
    relatedTopic: 'cryptography',
    secrecyLevel: 9,
    impact: 9,
  },
  {
    id: 'navajo-code',
    rank: 11,
    name: 'The Navajo Code Talkers',
    codename: 'Arizona / New Mexico',
    classifiedYear: '1942',
    declassifiedYear: '1968',
    agency: 'US Marine Corps',
    field: 'Linguistic Cryptography',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'The only military cipher in modern history never broken — a code built on the unwritten Navajo language, used across the Pacific Theater in WWII.',
    fullStory: 'In 1942, Philip Johnston, a civil engineer who had grown up on the Navajo reservation, proposed using Navajo as a military communication code. The Marine Corps recruited 29 Navajo men who developed a dual-layered system: common military terms were assigned Navajo words (e.g., "tank" = "turtle"), while spelling out uncommon words used a Navajo alphabet where each letter had multiple possible encodings. This created a code that was simultaneously fast enough for real-time battlefield communication and complex enough to resist cryptanalysis. Japanese intelligence, which had broken US Army codes, never made any progress against the Navajo transmissions. Over 400 Navajo Code Talkers served in every major Pacific engagement from Guadalcanal to Iwo Jima. Major Howard Connor declared: "Were it not for the Navajos, the Marines would never have taken Iwo Jima." The program was declassified in 1968, but the Code Talkers received no recognition until 2001.',
    keyFigures: ['Chester Nez', 'Carl Gorman', 'Philip Johnston', 'Major Howard Connor'],
    significance: 'The only unbroken code in modern military history — not because of mathematical complexity, but because it exploited the irreducible complexity of human language.',
    legacy: 'The Code Talkers waited 26 years for declassification and 59 years for the Congressional Gold Medal. Their story remains one of the most powerful examples of marginalized people defending the nation that marginalized them.',
    relatedTopic: 'cryptography',
    secrecyLevel: 7,
    impact: 9,
  },
  {
    id: 'room-40',
    rank: 12,
    name: 'Room 40 & The Zimmermann Telegram',
    codename: 'Room 40',
    classifiedYear: '1914',
    declassifiedYear: '1931',
    agency: 'British Admiralty',
    field: 'Diplomatic Cryptanalysis',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Britain\'s secret codebreaking unit decrypted a German telegram proposing a military alliance with Mexico against the US — and it changed the course of WWI.',
    fullStory: 'In January 1917, Room 40 — the British Admiralty\'s codebreaking office — intercepted and decrypted a telegram from German Foreign Secretary Arthur Zimmermann to the German ambassador in Mexico. It proposed that if the US entered WWI, Mexico should attack the United States, with German support, to recover Texas, New Mexico, and Arizona. The British faced a dilemma: revealing the telegram would prove they were reading German diplomatic traffic. They devised an elaborate cover story, claiming the telegram was obtained by a spy in Mexico City. When published on March 1, 1917, the telegram caused a firestorm of public outrage in the US. Zimmermann himself confirmed its authenticity, eliminating any doubt. The US declared war on Germany five weeks later. Room 40 had been operational since 1914, employing academics, linguists, and crossword enthusiasts — establishing the template that Bletchley Park would later follow on a massive scale.',
    keyFigures: ['Nigel de Grey', 'William Montgomery', 'Admiral Reginald Hall'],
    significance: 'A single decrypted telegram brought the United States into World War I, fundamentally altering the outcome of the war and the trajectory of the 20th century.',
    legacy: 'Room 40 established the precedent for signals intelligence as a strategic weapon. Its organizational model — academics working in secret for the state — became the blueprint for Bletchley Park, NSA, and GCHQ.',
    relatedTopic: 'cryptography',
    secrecyLevel: 8,
    impact: 10,
  },
  // ── 4 Modern Classified Secrets ──────────────────────────────
  {
    id: 'stuxnet',
    rank: 13,
    name: 'Stuxnet — The First Cyber Weapon',
    codename: 'Olympic Games',
    classifiedYear: '~2005',
    declassifiedYear: '2010 (discovered)',
    agency: 'NSA / Unit 8200',
    field: 'Cyber Warfare',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'The first known cyber weapon — a worm that physically destroyed Iran\'s nuclear centrifuges by silently altering their spin speeds while reporting normal telemetry.',
    fullStory: 'Stuxnet was a 500KB Windows worm discovered in 2010 that targeted Siemens SCADA systems controlling Iran\'s uranium enrichment centrifuges at Natanz. It exploited four zero-day vulnerabilities simultaneously — an unprecedented level of sophistication. Once inside the air-gapped facility (likely via infected USB drives), Stuxnet intercepted commands to the Siemens S7-315/417 PLCs controlling the centrifuge motors. It periodically altered rotor speeds between 1,410 Hz and 2 Hz (normal: 1,064 Hz), causing mechanical stress and failure, while replaying normal telemetry to operators — a man-in-the-middle attack on physical reality. An estimated 984 centrifuges were destroyed. The worm was designed to spread silently and self-delete after a set date. Its escape into the wild was reportedly accidental. Journalists David Sanger and Kim Zetter traced it to a joint US-Israeli operation codenamed "Olympic Games," initiated under Bush and expanded under Obama.',
    keyFigures: ['Ralph Langner', 'Sergey Ulasen', 'David Sanger', 'Kim Zetter'],
    significance: 'The first act of cyber warfare that caused physical destruction. It proved that software could be weaponized to destroy critical infrastructure without conventional military action.',
    legacy: 'Stuxnet opened Pandora\'s box. Every nation now develops offensive cyber capabilities. The line between espionage and act of war in cyberspace remains undefined in international law.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 9,
    impact: 10,
  },
  {
    id: 'heartbleed',
    rank: 14,
    name: 'Heartbleed — The Internet\'s Heart Attack',
    codename: 'CVE-2014-0160',
    classifiedYear: '2012 (introduced)',
    declassifiedYear: '2014 (disclosed)',
    agency: 'Open Source / NSA (suspected prior knowledge)',
    field: 'TLS Implementation Vulnerability',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'A single missing bounds check in OpenSSL exposed the private keys, passwords, and encrypted communications of 17% of the internet\'s secure servers for 27 months.',
    fullStory: 'On December 31, 2011, German developer Robin Seggelmann submitted a patch to OpenSSL implementing the TLS Heartbeat extension (RFC 6520). A missing bounds check in the heartbeat response allowed an attacker to read up to 64KB of server memory per request — including private keys, session cookies, passwords, and any data in process memory. The bug went live in OpenSSL 1.0.1 on March 14, 2012. For 27 months, any of the ~500,000 affected servers could be silently exfiltrated with no trace in server logs. Google security researcher Neel Mehta independently discovered the bug in April 2014, reporting it to OpenSSL. Codenomicon independently found it and gave it the name "Heartbleed" with a logo and website — pioneering the era of branded vulnerabilities. Bloomberg reported (and the NSA denied) that the NSA had known about and exploited Heartbleed for two years before public disclosure. The bug was caused by a single missing `if (payload + padding > length) return;` check.',
    keyFigures: ['Robin Seggelmann', 'Neel Mehta', 'Bodo Möller', 'Codenomicon team'],
    significance: 'Demonstrated that the security of the entire internet depended on a handful of underfunded open-source maintainers. One missing bounds check compromised half a million servers.',
    legacy: 'Heartbleed led directly to the creation of the Linux Foundation\'s Core Infrastructure Initiative (now OpenSSF), which funds critical open-source security projects. It proved that "given enough eyeballs, all bugs are shallow" was dangerously optimistic.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 7,
    impact: 9,
  },
  {
    id: 'shattered',
    rank: 15,
    name: 'SHAttered — Breaking SHA-1',
    codename: 'SHAttered',
    classifiedYear: '2013 (research begins)',
    declassifiedYear: '2017 (published)',
    agency: 'Google / CWI Amsterdam',
    field: 'Collision Attacks on Hash Functions',
    domain: 'Cryptography',
    domainEmoji: '🔐',
    summary: 'Google produced the first real-world SHA-1 collision — two different PDF files with the same hash — proving a foundational internet security primitive was broken.',
    fullStory: 'SHA-1, designed by the NSA in 1995, was the most widely used cryptographic hash function for digital signatures, certificates, and version control. In 2005, Xiaoyun Wang published theoretical attacks reducing SHA-1\'s collision resistance from the ideal 2^80 to 2^69 operations. The cryptography community warned of deprecation, but migration was slow — SHA-1 was embedded everywhere. In 2017, researchers Marc Stevens (CWI Amsterdam) and Elie Bursztein (Google) performed the first practical collision attack: they created two different PDF documents with identical SHA-1 hashes. The attack required 9,223,372,036,854,775,808 (2^63) SHA-1 computations — equivalent to 6,500 years of single-CPU computation or 110 years of single-GPU computation. Google donated the equivalent cloud computing time. The "SHAttered" attack was 100,000 times faster than brute force. Within hours of publication, Linus Torvalds (whose Git relied on SHA-1) acknowledged the need to transition.',
    keyFigures: ['Marc Stevens', 'Elie Bursztein', 'Xiaoyun Wang', 'Pierre Karpman'],
    significance: 'Proved that theoretical cryptographic attacks eventually become practical. The gap between "theoretically broken" and "practically broken" is just time and compute.',
    legacy: 'Forced the migration of billions of digital certificates, Git repositories, and signing systems to SHA-256. Established that cryptographic deprecation must happen proactively, not reactively.',
    relatedTopic: 'cryptography',
    secrecyLevel: 5,
    impact: 8,
  },
  {
    id: 'prism-xkeyscore',
    rank: 16,
    name: 'PRISM & XKeyscore — Mass Surveillance',
    codename: 'PRISM / XKeyscore',
    classifiedYear: '2007',
    declassifiedYear: '2013 (Snowden)',
    agency: 'NSA / Five Eyes',
    field: 'Signals Intelligence Infrastructure',
    domain: 'Cybersecurity',
    domainEmoji: '🛡️',
    summary: 'Edward Snowden revealed that the NSA had built systems to collect and search virtually all internet communications worldwide — including from US tech companies\' own servers.',
    fullStory: 'In June 2013, NSA contractor Edward Snowden leaked thousands of classified documents to journalists Glenn Greenwald, Laura Poitras, and Barton Gellman. The documents revealed two programs of unprecedented scope. PRISM: established in 2007 under Section 702 of FISA, allowed the NSA to collect data directly from the servers of nine major US tech companies — Microsoft, Google, Yahoo, Facebook, Apple, AOL, Skype, YouTube, and PalTalk. Companies disputed the "direct access" characterization but acknowledged providing data under legal compulsion. XKeyscore: a search system that allowed NSA analysts to search through vast databases of emails, browsing history, and chat logs with no prior authorization. Training materials boasted it could intercept "nearly everything a typical user does on the internet." The Five Eyes alliance (US, UK, Canada, Australia, New Zealand) shared access. The legal framework relied on a secret interpretation of Section 215 of the Patriot Act that the FISA Court had approved in classified rulings.',
    keyFigures: ['Edward Snowden', 'Glenn Greenwald', 'Laura Poitras', 'Barton Gellman'],
    significance: 'Revealed the largest mass surveillance apparatus in human history, operating with secret legal authority and minimal oversight, fundamentally challenging the relationship between security and privacy.',
    legacy: 'Led to the USA FREEDOM Act (2015), Apple\'s encryption-by-default on iPhones, Signal\'s mainstream adoption, and a permanent global debate about surveillance vs. security. Snowden remains in Russia.',
    relatedTopic: 'cybersecurity',
    secrecyLevel: 10,
    impact: 10,
  },
];

export const VAULT_AGENCIES = [...new Set(VAULT_ENTRIES.map((e) => e.agency))];
export const VAULT_DOMAINS = [...new Set(VAULT_ENTRIES.map((e) => e.domain))];
