import type { Question } from '../types';

export const manyBodyEasyQuestions: Question[] = [
  {
    id: 28501,
    topic: 'many-body-physics',
    difficulty: 'easy',
    question: 'The many-body problem in quantum mechanics is fundamentally hard because the Hilbert space dimension scales:',
    options: [
      'Exponentially with particle number ($d^N$ for $N$ particles in $d$-dimensional single-particle space)',
      'Linearly with particle number',
      'Quadratically with particle number',
      'Logarithmically with particle number',
    ],
    correctIndex: 0,
    explanation: 'For $N$ spin-1/2 particles, the Hilbert space has dimension $2^N$. With 300 spins, $2^{300} > 10^{90}$ — more states than atoms in the observable universe.',
    realWorld: 'This exponential scaling is precisely why quantum computers could revolutionize materials simulation.',
    hint: 'This is the "curse of dimensionality" — and the reason quantum computers exist.',
  },
  {
    id: 28502,
    topic: 'many-body-physics',
    difficulty: 'easy',
    question: 'Second quantization reformulates quantum mechanics using creation ($a^\\dagger$) and annihilation ($a$) operators. For bosons, the commutation relation is:',
    options: [
      '$[a_i, a_j^\\dagger] = \\delta_{ij}$',
      '$\\{a_i, a_j^\\dagger\\} = \\delta_{ij}$',
      '$[a_i, a_j^\\dagger] = i\\hbar$',
      '$a_i a_j^\\dagger = 0$',
    ],
    correctIndex: 0,
    explanation: 'Bosons use commutators $[\\cdot,\\cdot]$, fermions use anticommutators $\\{\\cdot,\\cdot\\}$. This automatically handles symmetrization/antisymmetrization of many-particle states.',
    realWorld: 'Second quantization is the language of condensed matter, nuclear physics, and quantum field theory — it makes particle creation/destruction natural.',
    hint: 'Commutators for bosons, anticommutators for fermions — the bracket type encodes quantum statistics.',
  },
  {
    id: 28503,
    topic: 'many-body-physics',
    difficulty: 'easy',
    question: 'A quasiparticle is:',
    options: [
      'An effective single-particle excitation emerging from collective many-body interactions',
      'An actual fundamental particle',
      'A virtual particle in a Feynman diagram',
      'A particle in a non-inertial frame',
    ],
    correctIndex: 0,
    explanation: 'In a strongly interacting system, individual particles are ill-defined. But low-energy excitations often behave like weakly-interacting "dressed" particles with renormalized mass and lifetime.',
    realWorld: 'Electrons in metals behave as quasiparticles with effective masses up to 1000× the bare electron mass (heavy fermions).',
    hint: 'The electron in a metal is not a bare electron — it drags along a cloud of lattice distortions.',
  },
];

export const manyBodyHardQuestions: Question[] = [
  {
    id: 28511,
    topic: 'many-body-physics',
    difficulty: 'hard',
    question: 'Density Functional Theory (DFT) is based on the Hohenberg-Kohn theorem, which states:',
    options: [
      'The ground-state energy is a unique functional of the electron density $n(\\mathbf{r})$ alone',
      'The wavefunction must be computed for all particles',
      'Only the kinetic energy can be expressed as a density functional',
      'The exchange-correlation energy is exactly known',
    ],
    correctIndex: 0,
    explanation: 'Hohenberg-Kohn proved $E_0 = E[n_0(\\mathbf{r})]$ — the 3D density $n(\\mathbf{r})$ contains all information about the $3N$-dimensional ground state. The Kohn-Sham scheme makes this practical.',
    realWorld: 'DFT is the most widely used method in computational chemistry and materials science — responsible for designing catalysts, drugs, and batteries.',
    hint: 'Instead of a $3N$-dimensional wavefunction, you only need the 3D electron density.',
  },
  {
    id: 28512,
    topic: 'many-body-physics',
    difficulty: 'hard',
    question: 'The Hubbard model Hamiltonian $H = -t\\sum_{\\langle i,j\\rangle,\\sigma} c^\\dagger_{i\\sigma}c_{j\\sigma} + U\\sum_i n_{i\\uparrow}n_{i\\downarrow}$ describes the competition between:',
    options: [
      'Electron hopping (kinetic energy $t$) and on-site Coulomb repulsion ($U$)',
      'Electron-phonon coupling and disorder',
      'Spin-orbit coupling and exchange interactions',
      'Magnetic field and electric field effects',
    ],
    correctIndex: 0,
    explanation: 'At $U/t \\gg 1$, electrons localize (Mott insulator). At $U/t \\ll 1$, they delocalize (metal). The Mott transition between these regimes is one of the great challenges in condensed matter.',
    realWorld: 'The Hubbard model is believed to capture the essential physics of high-$T_c$ cuprate superconductors — but solving it in 2D remains an open problem.',
    hint: 'Two terms compete: electrons want to hop (delocalize) but repel each other when on the same site.',
  },
  {
    id: 28513,
    topic: 'many-body-physics',
    difficulty: 'hard',
    question: 'Many-body localization (MBL) is the phenomenon where:',
    options: [
      'Interacting quantum systems in strong disorder fail to thermalize, violating the eigenstate thermalization hypothesis',
      'All particles become trapped in a periodic potential',
      'Electrons localize due to crystal field effects',
      'Many-body systems always reach thermal equilibrium',
    ],
    correctIndex: 0,
    explanation: 'MBL extends Anderson localization to interacting systems. MBL phases have area-law entanglement, emergent local integrals of motion, and logarithmic entanglement growth — they remember their initial conditions forever.',
    realWorld: 'MBL could protect quantum information from thermalization — a potential resource for quantum memory.',
    hint: 'Even with interactions, disorder can prevent a quantum system from ever reaching thermal equilibrium.',
  },
];

export const manyBodySotaQuestions: Question[] = [
  {
    id: 28521,
    topic: 'many-body-physics',
    difficulty: 'sota',
    question: 'Tensor network states (MPS, PEPS, MERA) efficiently represent many-body wavefunctions by exploiting:',
    options: [
      'The area law of entanglement entropy — ground states of gapped local Hamiltonians have limited entanglement',
      'The fact that most quantum states are product states',
      'Classical correlations only',
      'Translation invariance',
    ],
    correctIndex: 0,
    explanation: 'The area law states that entanglement entropy scales with the boundary area, not volume. MPS exploit this in 1D (bond dimension $\\chi$), enabling efficient DMRG calculations with $O(N\\chi^3)$ cost.',
    realWorld: 'DMRG (White, 1992) and tensor networks are the gold standard for 1D quantum many-body systems and are now being extended to 2D and quantum chemistry.',
    hint: 'Most of the exponentially large Hilbert space is unphysical — physical states live in a tiny "corner" with limited entanglement.',
  },
  {
    id: 28522,
    topic: 'many-body-physics',
    difficulty: 'sota',
    question: 'Dynamical Mean-Field Theory (DMFT) maps a lattice many-body problem to:',
    options: [
      'A self-consistent quantum impurity model embedded in a bath — exact in infinite dimensions',
      'A classical Monte Carlo simulation',
      'A single Hartree-Fock equation',
      'A 1D chain model',
    ],
    correctIndex: 0,
    explanation: 'DMFT replaces the lattice with a single site coupled to a self-consistent bath, capturing local correlations exactly. It becomes exact in $d = \\infty$ and is a powerful approximation for 3D correlated materials.',
    realWorld: 'DMFT+DFT predicts electronic properties of correlated materials like VO₂, plutonium, and iron-based superconductors.',
    hint: 'It is the many-body analog of mean-field theory, but for quantum dynamics — the bath adjusts self-consistently.',
  },
  {
    id: 28523,
    topic: 'many-body-physics',
    difficulty: 'sota',
    question: 'The sign problem in quantum Monte Carlo for fermionic systems arises because:',
    options: [
      'The antisymmetry of fermionic wavefunctions produces negative statistical weights, causing exponential variance growth',
      'Fermions have negative charge',
      'The Hamiltonian is non-Hermitian',
      'Monte Carlo methods cannot handle continuous variables',
    ],
    correctIndex: 0,
    explanation: 'Fermion exchange introduces minus signs in the path integral. Importance sampling fails when the integrand oscillates, causing the signal-to-noise ratio to degrade exponentially with system size and inverse temperature.',
    realWorld: 'The sign problem is NP-hard in general. It is the primary obstacle to simulating the Hubbard model, nuclear matter, and dense QCD from first principles.',
    hint: 'Bosonic QMC has no sign problem. The fermion sign problem is fundamentally a consequence of the Pauli principle.',
  },
];
