import type { Question } from '../types';

export const ucbEecs126Questions: Question[] = [
  {
    id: 90000,
    topic: 'ucb-eecs126',
    difficulty: 'easy',
    question: 'Basic probability: $P(A \\cup B) = P(A) + P(B) - $ ?',
    options: ['$P(A \\cap B)$', '$P(A|B)$', '$P(B|A)$', '$P(A)P(B)$'],
    correctIndex: 0,
    explanation: 'Inclusion-exclusion principle: overlapping events are double-counted in $P(A)+P(B)$, so subtract $P(A \\cap B)$.',
    realWorld: 'Risk management: probability of loan default OR recession requires subtracting the overlap.',
    hint: 'Think about double-counting in unions.',
    symbolLinks: { '∪': 'union', '∩': 'intersection' },
    formulaLinks: ['inclusion-exclusion'],
    glossaryLinks: ['probability', 'set-theory'],
  },
  {
    id: 90001,
    topic: 'ucb-eecs126',
    difficulty: 'easy',
    question: 'For independent events $A$ and $B$, $P(A \\cap B) = $ ?',
    options: ['$P(A) \\cdot P(B)$', '$P(A) + P(B)$', '$P(A|B)$', '$P(A) - P(B)$'],
    correctIndex: 0,
    explanation: 'Independence means knowing $B$ tells you nothing about $A$: joint probability factors.',
    realWorld: 'Insurance pricing assumes independent claim events across uncorrelated policies.',
    hint: 'Independence = multiplication.',
    symbolLinks: { '∩': 'intersection' },
    formulaLinks: ['independence'],
    glossaryLinks: ['probability'],
  },
  {
    id: 90002,
    topic: 'ucb-eecs126',
    difficulty: 'easy',
    question: 'Bayes\' Theorem: $P(A|B) = P(B|A) \\cdot P(A) \\;/\\;$ ?',
    options: ['$P(B)$', '$P(A)$', '$P(A \\cup B)$', '$1 - P(B)$'],
    correctIndex: 0,
    explanation: '$P(A|B) = \\frac{P(B|A)P(A)}{P(B)}$. Normalizing by total evidence $P(B)$.',
    realWorld: 'Medical diagnostics: updating disease probability given a positive test result.',
    hint: 'The denominator is the total probability of the evidence.',
    symbolLinks: { 'P': 'probability' },
    formulaLinks: ['bayes-theorem'],
    glossaryLinks: ['bayesian-inference'],
  },
  {
    id: 90003,
    topic: 'ucb-eecs126',
    difficulty: 'hard',
    question: 'Markov chain stationary distribution $\\pi$ satisfies $\\pi P = $ ?',
    options: ['$\\pi$ (left eigenvector with eigenvalue 1)', '$P\\pi$ (right eigenvector)', '$P^{-1}\\pi$', '$\\pi P^{-1}$'],
    correctIndex: 0,
    explanation: '$\\pi P = \\pi$: the stationary distribution is the left eigenvector of the row-stochastic transition matrix with eigenvalue 1.',
    realWorld: 'PageRank: Google models the web as a Markov chain and computes its stationary distribution.',
    hint: 'Stationary means invariant under one transition step.',
    symbolLinks: { 'π': 'pi' },
    formulaLinks: ['markov-stationary'],
    glossaryLinks: ['markov-chain', 'eigenvalue'],
  },
  {
    id: 90004,
    topic: 'ucb-eecs126',
    difficulty: 'hard',
    question: 'PageRank propagates authority scores via power iteration on which matrix?',
    options: ['Column-stochastic $H$ ($H_{ij} = 1/\\text{outdeg}(j)$ if $j \\to i$)', 'Row-stochastic adjacency', 'Graph Laplacian', 'Symmetric adjacency'],
    correctIndex: 0,
    explanation: '$H_{ij} = 1/\\text{deg}(j)$ if page $j$ links to $i$. PageRank: $\\mathbf{r} = (1-d)\\frac{\\mathbf{1}}{n} + d H\\mathbf{r}$.',
    realWorld: 'Larry Page\'s 1996 "BackRub" project became Google — the world\'s most valuable company.',
    hint: 'Authority flows backward along hyperlinks.',
    symbolLinks: { 'π': 'pi', 'H': 'eta' },
    formulaLinks: ['pagerank'],
    glossaryLinks: ['markov-chain', 'eigenvalue'],
  },
  {
    id: 90005,
    topic: 'ucb-eecs126',
    difficulty: 'hard',
    question: 'The DTMC first-passage time $T_j = \\min\\{n \\geq 1 : X_n = j\\}$ has finite expectation when state $j$ is?',
    options: ['Positive recurrent', 'Transient', 'Null recurrent', 'Absorbing'],
    correctIndex: 0,
    explanation: 'Positive recurrent states have $E[T_j | X_0 = j] < \\infty$. Null recurrent: returns w.p. 1 but $E[T] = \\infty$.',
    realWorld: 'Network routing: positive recurrence guarantees packets eventually reach their destination in bounded expected time.',
    hint: 'Recurrent = guaranteed return. Positive = finite expected time.',
    symbolLinks: { 'T': 'tau' },
    formulaLinks: ['hitting-time'],
    glossaryLinks: ['markov-chain'],
  },
  {
    id: 90006,
    topic: 'ucb-eecs126',
    difficulty: 'sota',
    question: 'Little\'s Law $L = \\lambda W$ relates which three quantities in queueing systems?',
    options: ['Average queue length, arrival rate, average wait time', 'Service rate, utilization, variance', 'Burstiness, blocking probability, throughput', 'Buffer size, packet loss, delay jitter'],
    correctIndex: 0,
    explanation: '$L = \\lambda W$ is fundamental and model-independent: holds for M/M/1, M/G/1, networks, any stable system.',
    realWorld: 'HFT systems: order book depth ($L$) vs fill rate ($\\lambda$) vs execution latency ($W$).',
    hint: 'A conservation law — no distributional assumptions needed.',
    symbolLinks: { 'λ': 'lambda', 'L': 'lambda' },
    formulaLinks: ['littles-law'],
    glossaryLinks: ['queueing-theory'],
  },
  {
    id: 90007,
    topic: 'ucb-eecs126',
    difficulty: 'sota',
    question: 'In an M/M/1 queue with arrival rate $\\lambda$ and service rate $\\mu$, the system is stable when?',
    options: ['$\\rho = \\lambda / \\mu < 1$', '$\\lambda > \\mu$', '$\\lambda = \\mu$', '$\\mu = 0$'],
    correctIndex: 0,
    explanation: 'Traffic intensity $\\rho = \\lambda/\\mu < 1$ ensures the queue doesn\'t grow without bound. At $\\rho \\geq 1$, queue length → $\\infty$.',
    realWorld: 'Cloud auto-scaling: if request rate exceeds service capacity ($\\rho \\geq 1$), add servers.',
    hint: 'Arrivals must not outpace service.',
    symbolLinks: { 'λ': 'lambda', 'μ': 'mu', 'ρ': 'rho' },
    formulaLinks: ['mm1-queue'],
    glossaryLinks: ['queueing-theory'],
  },
  {
    id: 90008,
    topic: 'ucb-eecs126',
    difficulty: 'hard',
    question: 'The Poisson process: $N(t) \\sim \\text{Pois}(\\lambda t)$. What is $P(N(t) = k)$?',
    options: ['$e^{-\\lambda t}(\\lambda t)^k / k!$', '$(\\lambda t)^k / k!$', '$e^{-\\lambda}\\lambda^k$', '$\\binom{n}{k}p^k(1-p)^{n-k}$'],
    correctIndex: 0,
    explanation: 'Poisson PMF with rate parameter $\\lambda t$. Models rare events with constant average rate.',
    realWorld: 'Modeling website hits per minute, radioactive decay counts, insurance claims per year.',
    hint: 'Exponential decay times a polynomial, normalized by factorial.',
    symbolLinks: { 'λ': 'lambda', 'N': 'nu' },
    formulaLinks: ['poisson-distribution'],
    glossaryLinks: ['poisson-process', 'probability'],
  },
  {
    id: 90009,
    topic: 'ucb-eecs126',
    difficulty: 'sota',
    question: 'The Chernoff bound for sum of independent RVs $S_n$: $P(S_n \\geq a) \\leq$ ?',
    options: ['$\\min_{t>0} e^{-ta} \\prod E[e^{tX_i}]$', '$E[S_n]/a$', '$\\text{Var}(S_n)/a^2$', '$e^{-a}$'],
    correctIndex: 0,
    explanation: 'Chernoff applies Markov\'s inequality to the MGF: exponential tilt then optimize over $t$. Gives exponentially tight tail bounds.',
    realWorld: 'Randomized algorithms: proving concentration for hash table load balancing, random sampling.',
    hint: 'Optimize the exponential moment bound over the tilt parameter.',
    symbolLinks: { 'Σ': 'sigma' },
    formulaLinks: ['chernoff-bound'],
    glossaryLinks: ['concentration-inequality', 'moment-generating-function'],
  },
];
