import type { Question } from '../types';

export const pharmacologyQuestions: Question[] = [
  {
    id: 41501, topic: 'pharmacology', difficulty: 'easy',
    question: 'Drug-receptor binding follows the law of mass action, where potency is measured by:',
    options: [
      'EC₅₀ — the drug concentration producing 50% of maximum effect; lower EC₅₀ means higher potency',
      'The color of the pill',
      'How quickly the drug dissolves in water',
      'The molecular weight of the drug',
    ],
    correctIndex: 0,
    explanation: 'The dose-response curve relates drug concentration to biological effect. EC₅₀ quantifies potency. Efficacy (maximum achievable effect) and potency are independent properties.',
    realWorld: 'Fentanyl has EC₅₀ ~100× lower than morphine — it\'s 100× more potent. AI drug discovery predicts EC₅₀ computationally, reducing the need for animal testing.',
    hint: 'The dose that gives you half the maximum effect — lower means the drug works at smaller amounts.',
  },
  {
    id: 41504, topic: 'pharmacology', difficulty: 'easy',
    question: 'Antibiotics target bacteria without harming human cells because:',
    options: [
      'They exploit structural differences — e.g., penicillin blocks peptidoglycan synthesis (bacterial cell walls) which human cells lack entirely',
      'Antibiotics kill all living cells equally',
      'Human cells have thicker membranes that block antibiotics',
      'Bacteria are too small for antibiotics to reach',
    ],
    correctIndex: 0,
    explanation: 'Selective toxicity exploits differences between prokaryotic and eukaryotic cells: bacterial cell walls (penicillins), bacterial ribosomes (tetracyclines, aminoglycosides), bacterial DNA gyrase (fluoroquinolones) — none of which humans have.',
    realWorld: 'Antibiotic resistance is a global crisis: MRSA, drug-resistant TB, and resistant gonorrhea threaten to make common infections lethal again. The WHO estimates 10 million annual deaths from resistant infections by 2050.',
    hint: 'Bacteria have structures that human cells don\'t — antibiotics target those unique structures.',
  },
  {
    id: 41502, topic: 'pharmacology', difficulty: 'hard',
    question: 'Pharmacokinetics follows the ADME model, which describes:',
    options: [
      'Absorption (how drug enters blood), Distribution (where it goes), Metabolism (how liver transforms it), Excretion (how kidneys remove it) — determining drug concentration over time',
      'The four stages of drug approval by the FDA',
      'Four types of drug side effects',
      'The four main drug manufacturing steps',
    ],
    correctIndex: 0,
    explanation: 'ADME determines the drug\'s concentration-time profile. First-pass metabolism explains why oral and IV doses differ. Half-life ($t_{1/2} = \\ln 2 / k_e$) determines dosing frequency.',
    realWorld: 'ML models now predict ADME properties from molecular structure alone, reducing drug development time. Poor ADME is the #1 reason drugs fail in clinical trials.',
    hint: 'Four steps: how does the drug get in, spread around, get processed, and get removed?',
  },
  {
    id: 41505, topic: 'pharmacology', difficulty: 'hard',
    question: 'The therapeutic index (TI) of a drug is:',
    options: [
      'The ratio of toxic dose to effective dose ($TI = TD_{50}/ED_{50}$) — a larger TI means a wider safety margin between therapeutic and dangerous doses',
      'How many diseases the drug can treat',
      'The speed at which the drug takes effect',
      'The number of side effects the drug causes',
    ],
    correctIndex: 0,
    explanation: 'A drug with TI=10 has a 10-fold margin between the dose that helps and the dose that harms. Lithium (TI~3) requires careful blood monitoring; acetaminophen (TI~10) has a modest margin; penicillin (TI>100) is very safe.',
    realWorld: 'Drugs with narrow TI (warfarin, digoxin, lithium, chemotherapy) require therapeutic drug monitoring — regular blood tests to ensure concentrations stay in the safe-effective window.',
    hint: 'How much room is there between "enough to help" and "enough to harm"?',
  },
  {
    id: 41503, topic: 'pharmacology', difficulty: 'sota',
    question: 'AI-driven drug discovery using diffusion models (RFDiffusion, DiffDock) works by:',
    options: [
      'Generating novel protein structures or predicting ligand binding poses by iteratively denoising random 3D coordinates — learning the distribution of valid molecular conformations',
      'Randomly trying every possible molecule until one works',
      'Using only 2D molecular fingerprints without 3D information',
      'Replacing all wet-lab experiments with simulations',
    ],
    correctIndex: 0,
    explanation: 'Diffusion models learn the distribution of valid 3D molecular structures by training to denoise corrupted atomic coordinates. RFDiffusion generates novel protein binders; DiffDock predicts drug docking poses.',
    realWorld: 'RFDiffusion designed novel protein binders for flu, COVID, and cancer targets that worked in the lab on the first try — previously taking years of experimental iteration.',
    hint: 'Start with random atomic positions and gradually refine them into physically realistic molecules.',
  },
  {
    id: 41506, topic: 'pharmacology', difficulty: 'sota',
    question: 'AlphaFold\'s impact on drug discovery is transformative because:',
    options: [
      'It predicts protein 3D structures from amino acid sequences with near-experimental accuracy — enabling structure-based drug design for proteins that were previously impossible to crystallize',
      'It directly designs drug molecules without any human input',
      'It replaces all clinical trials',
      'It only works for proteins smaller than 100 amino acids',
    ],
    correctIndex: 0,
    explanation: 'AlphaFold2 (2020) solved the protein folding problem: predicting 3D structure from sequence alone at ~1 Å accuracy. AlphaFold3 (2024) extends to protein-ligand, protein-DNA, and protein-protein complexes.',
    realWorld: 'The AlphaFold Protein Structure Database contains 200+ million predicted structures — essentially every known protein. Drug companies use AlphaFold to identify drug targets, design molecules, and understand disease mechanisms.',
    hint: 'Know the protein\'s shape → know where a drug molecule can bind → design the drug.',
  },
];
