import type { Question } from '../types';

export const pharmacologyQuestions: Question[] = [
  {
    id: 41501, topic: "pharmacology", difficulty: "easy",
    question: "On a graded concentration-response curve, EC50 is the concentration that produces:",
    options: ["The maximum toxic effect in every patient","Irreversible receptor binding","Half of the system's measured maximal effect under the assay conditions","Exactly half of all drug molecules absorbed"],
    correctIndex: 2,
    explanation: "EC50 is the concentration associated with 50% of the measured maximal response in a particular assay and is commonly used as a potency descriptor.",
    realWorld: "Comparing EC50 values can be useful within a defined experimental system, but potency is distinct from efficacy and does not alone determine a clinical dose.",
    hint: "Look for the halfway point on the response axis, not a statement about absorption or toxicity.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41504, topic: "pharmacology", difficulty: "easy",
    question: "Selective toxicity of many antibacterial drugs is possible because they target features such as:",
    options: ["Bacterial peptidoglycan synthesis or bacterial ribosomes that differ from human-cell machinery","Structures that are identical in bacteria and human cells","Only the color of bacterial colonies","Human mitochondrial DNA exclusively"],
    correctIndex: 0,
    explanation: "Antibacterial drugs can exploit biological differences such as peptidoglycan cell walls, bacterial ribosomes, or enzymes that are absent from or sufficiently different in human cells.",
    realWorld: "Selective targets make antimicrobial therapy possible, although adverse effects and microbiome disruption still occur and resistance can evolve.",
    hint: "Look for a cellular structure or process that differs substantially between bacteria and their human host.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41502, topic: "pharmacology", difficulty: "hard",
    question: "The ADME framework in pharmacokinetics refers to:",
    options: ["Absorption, distribution, metabolism, and excretion","Approval, dosing, monitoring, and efficacy","Affinity, degradation, mutation, and elimination","Administration, diagnosis, mechanism, and ethics"],
    correctIndex: 0,
    explanation: "ADME summarizes major processes controlling how a drug enters the body or circulation, distributes into tissues, is chemically transformed, and is removed.",
    realWorld: "Pharmacokinetic models use these processes to interpret concentration-time profiles and to design dosing regimens.",
    hint: "Think about the journey of a compound from entry through movement, transformation, and removal.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41505, topic: "pharmacology", difficulty: "hard",
    question: "The therapeutic index is traditionally expressed as a ratio such as TD50/ED50. A larger value generally indicates:",
    options: ["A narrower separation between desired and toxic effects","No possibility of adverse effects","That efficacy is zero","A wider separation between the doses producing the chosen toxic and effective endpoints"],
    correctIndex: 3,
    explanation: "The therapeutic index compares a toxic-dose metric with an effective-dose metric; a larger ratio indicates greater separation between those specified endpoints in the studied population.",
    realWorld: "The concept is useful for safety reasoning, while real prescribing also depends on exposure variability, patient factors, and which toxicity and efficacy endpoints matter.",
    hint: "Compare how far apart the chosen effective and toxic dose levels are.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41503, topic: "pharmacology", difficulty: "sota",
    question: "RFdiffusion is relevant to therapeutic discovery because it can:",
    options: ["Generate candidate protein backbones by learning to reverse structural noise under design constraints","Guarantee clinical efficacy from sequence alone","Replace all experimental validation","Predict only small-molecule solubility from 2D fingerprints"],
    correctIndex: 0,
    explanation: "RFdiffusion adapts a protein-structure network to a diffusion-style denoising process that can generate protein backbones satisfying structural or functional design constraints.",
    realWorld: "Generative protein design can propose binders and other functional scaffolds for experimental testing, shortening some design cycles without eliminating laboratory validation.",
    hint: "The method starts from noisy structural representations and iteratively denoises toward protein-like structures.",
    paper: {"title":"De novo design of protein structure and function with RFdiffusion","url":"https://www.nature.com/articles/s41586-023-06415-8","venue":"Nature","year":2023},
    reviewedAt: "2026-09-19",
  },
  {
    id: 41506, topic: "pharmacology", difficulty: "sota",
    question: "Compared with AlphaFold 2, AlphaFold 3 was designed to model a broader range of biomolecular complexes, including:",
    options: ["Only isolated proteins shorter than 100 residues","Proteins together with nucleic acids, small molecules, ions, and modified residues","Only lipid bilayers without proteins","Clinical outcomes directly from a patient's diagnosis"],
    correctIndex: 1,
    explanation: "AlphaFold 3 extends structure prediction beyond many protein-only settings to complexes containing proteins, nucleic acids, small molecules, ions, and modified residues.",
    realWorld: "Better structural models of biomolecular interactions can support hypothesis generation in structural biology and drug discovery, while predicted structures still require context and validation.",
    hint: "The extension is about interaction modeling across more molecular classes, not about replacing clinical trials.",
    paper: {"title":"Accurate structure prediction of biomolecular interactions with AlphaFold 3","url":"https://www.nature.com/articles/s41586-024-07487-w","venue":"Nature","year":2024},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 41507, topic: "pharmacology", difficulty: "easy",
    question: "An agonist at a receptor is a ligand that:",
    options: ["Prevents all receptor binding permanently","Must always be an irreversible covalent drug","Binds only to plasma proteins","Binds the receptor and promotes receptor activation or signaling"],
    correctIndex: 3,
    explanation: "An agonist has affinity for a receptor and produces receptor activation or a downstream response; antagonists instead reduce or block activation by other ligands without necessarily activating the receptor themselves.",
    realWorld: "Agonist-versus-antagonist behavior is a foundational way to classify drugs acting at receptors.",
    hint: "Ask whether the ligand merely occupies the receptor or also drives its active signaling state.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41508, topic: "pharmacology", difficulty: "hard",
    question: "For a drug eliminated by first-order kinetics, which statement is generally true?",
    options: ["A constant fraction of the drug amount is eliminated per unit time","A constant absolute mass is eliminated per unit time regardless of concentration","Elimination stops below the EC50","Half-life necessarily increases after every dose"],
    correctIndex: 0,
    explanation: "With first-order elimination, elimination rate is proportional to concentration, so the same fraction is removed over equal time intervals when clearance and distribution parameters remain stable.",
    realWorld: "This property underlies common exponential-decay pharmacokinetic models and helps connect clearance, volume of distribution, and half-life.",
    hint: "Contrast a constant fraction per interval with zero-order removal of a constant amount per interval.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41509, topic: "pharmacology", difficulty: "sota",
    question: "A PROTAC is designed to reduce the abundance of a target protein by:",
    options: ["Blocking transcription of every gene in the cell","Recruiting a target protein and an E3 ubiquitin ligase into a ternary complex that promotes ubiquitination and proteasomal degradation","Cleaving genomic DNA at the target gene","Converting the target protein directly into RNA"],
    correctIndex: 1,
    explanation: "PROTACs are heterobifunctional molecules with one ligand for the target and another for an E3 ubiquitin ligase; productive ternary-complex formation can drive target ubiquitination and degradation.",
    realWorld: "Targeted protein degradation offers a pharmacological strategy that can remove a disease-relevant protein rather than merely occupy one of its active sites.",
    hint: "The molecule acts as a bridge between the target and the cell's ubiquitin-proteasome machinery.",
    sources: [{"title":"PROTAC targeted protein degraders: the past is prologue","url":"https://www.nature.com/articles/s41573-021-00371-6","publisher":"Nature Reviews Drug Discovery","year":2022}],
    reviewedAt: "2026-09-19",
  },
];
