import type { Question } from '../types';

export const distributedSystemsQuestions: Question[] = [
  {
    id: 3401,
    topic: 'distributed-systems',
    difficulty: 'easy',
    question: 'The CAP theorem states that a distributed system can guarantee at most:',
    options: ['All three: Consistency, Availability, Partition tolerance', 'Two of three: Consistency, Availability, Partition tolerance', 'Only Consistency', 'Only Availability'],
    correctIndex: 1,
    explanation: 'Brewer\'s CAP theorem (proven by Gilbert & Lynch) shows that during a network partition, a system must choose between consistency and availability.',
    realWorld: 'DynamoDB chooses AP (availability), while traditional SQL databases choose CP (consistency).',
    hint: 'Pick two out of three.',
  },
  {
    id: 3402,
    topic: 'distributed-systems',
    difficulty: 'easy',
    question: 'Consensus in distributed systems means:',
    options: ['All nodes have the fastest network', 'All nodes agree on a single value or decision', 'Nodes can disagree safely', 'Only one node makes decisions'],
    correctIndex: 1,
    explanation: 'Consensus protocols ensure all non-faulty nodes agree on the same value, even if some nodes crash or messages are delayed.',
    realWorld: 'Raft and Paxos power leader election in etcd, ZooKeeper, and most distributed databases.',
    hint: 'Agreement despite failures.',
  },
  {
    id: 3403,
    topic: 'distributed-systems',
    difficulty: 'easy',
    question: 'Horizontal scaling means:',
    options: ['Upgrading to a more powerful server', 'Adding more machines to distribute the load', 'Increasing disk size', 'Using faster network cables'],
    correctIndex: 1,
    explanation: 'Horizontal scaling (scaling out) adds more nodes, while vertical scaling (scaling up) upgrades a single machine.',
    realWorld: 'Cloud platforms like AWS enable elastic horizontal scaling — adding/removing instances based on demand.',
    hint: 'More machines, not a bigger machine.',
  },
  {
    id: 3404,
    topic: 'distributed-systems',
    difficulty: 'hard',
    question: 'The Raft consensus algorithm ensures safety by:',
    options: ['Allowing split-brain scenarios', 'Requiring a majority quorum for leader election and log commitment', 'Using timestamps only', 'Having all nodes vote simultaneously without a leader'],
    correctIndex: 1,
    explanation: 'Raft uses a leader-based approach where log entries are committed only when replicated to a majority, preventing conflicting decisions.',
    realWorld: 'Raft powers etcd (Kubernetes\' brain), CockroachDB, and HashiCorp Consul.',
    hint: 'Majority rules — more than half must agree.',
  },
  {
    id: 3405,
    topic: 'distributed-systems',
    difficulty: 'hard',
    question: 'Consistent hashing is used in distributed systems to:',
    options: ['Encrypt data uniformly', 'Distribute keys across nodes with minimal redistribution when nodes join/leave', 'Sort data alphabetically', 'Compress data for storage'],
    correctIndex: 1,
    explanation: 'Consistent hashing maps keys and nodes to a ring, so adding/removing a node only redistributes $K/n$ keys on average (vs. all keys with modular hashing).',
    realWorld: 'Used in DynamoDB, Cassandra, and CDNs to distribute data and requests evenly.',
    hint: 'Think of a hash ring where nodes and keys are placed.',
  },
  {
    id: 3406,
    topic: 'distributed-systems',
    difficulty: 'hard',
    question: 'Vector clocks track causality in distributed systems by:',
    options: ['Using a single global timestamp', 'Assigning each node a logical counter that increments on events, forming a vector', 'Using GPS synchronization', 'Ordering events alphabetically'],
    correctIndex: 1,
    explanation: 'Each node maintains a vector of counters. Comparing vectors reveals causal ordering: $V_a < V_b$ iff all components of $V_a \\leq V_b$ and at least one is strictly less.',
    realWorld: 'Vector clocks detect conflicts in eventually consistent systems like Amazon DynamoDB and Riak.',
    hint: 'Each node counts its own events; vectors are compared component-wise.',
  },
  {
    id: 3407,
    topic: 'distributed-systems',
    difficulty: 'sota',
    question: 'CRDTs (Conflict-free Replicated Data Types) guarantee convergence because:',
    options: ['They use strong consensus', 'Their merge function forms a join-semilattice (commutative, associative, idempotent)', 'They prevent all concurrent writes', 'They require a central coordinator'],
    correctIndex: 1,
    explanation: 'CRDTs are mathematically designed so that merging replicas in any order always converges to the same state, without coordination.',
    realWorld: 'CRDTs power real-time collaboration in Figma, Apple Notes, and Redis Enterprise.',
    hint: 'The math guarantees convergence regardless of merge order.',
  },
  {
    id: 3408,
    topic: 'distributed-systems',
    difficulty: 'sota',
    question: 'Google Spanner achieves external consistency (linearizability) across data centers using:',
    options: ['Optimistic locking only', 'TrueTime — GPS + atomic clock-based globally synchronized timestamps', 'Eventual consistency with manual conflict resolution', 'Single-leader replication'],
    correctIndex: 1,
    explanation: 'TrueTime provides bounded clock uncertainty. Spanner waits out the uncertainty interval before committing, guaranteeing that transaction ordering matches real-time ordering.',
    realWorld: 'Spanner is the only globally distributed database with external consistency — it powers Google Ads, Google Play, and Cloud Spanner.',
    hint: 'Atomic clocks and GPS receivers in every data center.',
  },
  {
    id: 3409,
    topic: 'distributed-systems',
    difficulty: 'sota',
    question: 'The FLP impossibility result proves that:',
    options: ['Consensus is easy in asynchronous systems', 'No deterministic consensus protocol can guarantee termination in an asynchronous system with even one crash failure', 'Distributed systems always converge', 'Byzantine failures are impossible'],
    correctIndex: 1,
    explanation: 'Fischer, Lynch, and Paterson (1985) proved that in a purely asynchronous model, even one crash can prevent any deterministic protocol from always reaching consensus.',
    realWorld: 'This is why practical systems use timeouts, randomization, or partial synchrony assumptions to circumvent FLP.',
    hint: 'A fundamental impossibility in asynchronous distributed computing.',
  },
];
