import type { Question } from '../types';

export const combinatoricsQuestions: Question[] = [
  // ── Easy ──
  {
    id: 90001, topic: 'combinatorics', difficulty: 'easy',
    question: 'How many ways can you choose 3 items from a set of 10? (i.e. $\\binom{10}{3}$)',
    options: ['120', '720', '210', '100'],
    correctIndex: 0,
    explanation: '$\\binom{10}{3} = \\frac{10!}{3!\\cdot7!} = 120$.',
    realWorld: 'Combination calculations underpin lottery odds, committee selection, and feature subset selection in ML.',
    hint: 'Use the binomial coefficient formula $\\frac{n!}{k!(n-k)!}$.',
  },
  {
    id: 90002, topic: 'combinatorics', difficulty: 'easy',
    question: 'The Pigeonhole Principle states that if $n+1$ objects are placed into $n$ boxes, then at least one box contains:',
    options: ['At least 2 objects', 'Exactly 1 object', 'At most 1 object', 'n objects'],
    correctIndex: 0,
    explanation: 'By the Pigeonhole Principle, at least one box must contain more than one object.',
    realWorld: 'Used in hash collision proofs, birthday paradox arguments, and network routing guarantees.',
    hint: 'Think about what happens when items outnumber containers.',
  },
  {
    id: 90003, topic: 'combinatorics', difficulty: 'easy',
    question: 'The number of permutations of $n$ distinct objects is:',
    options: ['$n!$', '$2^n$', '$n^2$', '$\\binom{n}{2}$'],
    correctIndex: 0,
    explanation: 'There are $n!$ ways to arrange $n$ distinct objects in a row.',
    realWorld: 'Permutation counting is fundamental to cryptographic key space analysis.',
    hint: 'First position has $n$ choices, second has $n-1$, etc.',
  },
  {
    id: 90004, topic: 'combinatorics', difficulty: 'easy',
    question: 'The Catalan number $C_3$ equals:',
    options: ['5', '14', '4', '8'],
    correctIndex: 0,
    explanation: '$C_n = \\frac{1}{n+1}\\binom{2n}{n}$, so $C_3 = \\frac{1}{4}\\binom{6}{3} = 5$.',
    realWorld: 'Catalan numbers count valid parenthesizations, binary trees, and Dyck paths.',
    hint: 'Apply $C_n = \\frac{1}{n+1}\\binom{2n}{n}$ with $n=3$.',
  },
  {
    id: 90005, topic: 'combinatorics', difficulty: 'easy',
    question: 'How many subsets does a set of $n$ elements have?',
    options: ['$2^n$', '$n!$', '$n^2$', '$2n$'],
    correctIndex: 0,
    explanation: 'Each element is either included or excluded, giving $2^n$ subsets.',
    realWorld: 'Power set enumeration is central to feature selection in machine learning.',
    hint: 'Each element has 2 choices: in or out.',
  },
  // ── Hard ──
  {
    id: 90006, topic: 'combinatorics', difficulty: 'hard',
    question: 'The chromatic polynomial $P(K_4, k)$ for the complete graph $K_4$ is:',
    options: ['$k(k-1)(k-2)(k-3)$', '$k^4$', '$k(k-1)^3$', '$(k-1)^4$'],
    correctIndex: 0,
    explanation: 'For $K_n$, the chromatic polynomial is $k(k-1)(k-2)\\cdots(k-n+1) = k^{\\underline{n}}$.',
    realWorld: 'Chromatic polynomials model register allocation and frequency assignment in networks.',
    hint: 'In a complete graph, each vertex must differ from all previously colored vertices.',
  },
  {
    id: 90007, topic: 'combinatorics', difficulty: 'hard',
    question: 'The Stirling number of the second kind $S(4,2)$ (partitioning 4 elements into 2 non-empty subsets) equals:',
    options: ['7', '6', '8', '15'],
    correctIndex: 0,
    explanation: '$S(4,2) = 2^{3} - 1 = 7$, using the recurrence or direct enumeration.',
    realWorld: 'Stirling numbers count clustering configurations in unsupervised learning.',
    hint: 'Count the ways to split $\\{1,2,3,4\\}$ into two non-empty groups (unordered).',
  },
  {
    id: 90008, topic: 'combinatorics', difficulty: 'hard',
    question: 'Burnside\'s lemma counts distinct colorings under group action. For a necklace of 4 beads with 2 colors under rotation, the number of distinct necklaces is:',
    options: ['6', '4', '8', '16'],
    correctIndex: 0,
    explanation: 'Burnside gives $\\frac{1}{4}(2^4 + 2^2 + 2^1 + 2^2) = \\frac{16+4+2+4}{4} = 6$.',
    realWorld: 'Symmetry-aware counting is used in molecular chemistry and pattern recognition.',
    hint: 'Average the number of colorings fixed by each rotation.',
  },
  {
    id: 90009, topic: 'combinatorics', difficulty: 'hard',
    question: 'The Ramsey number $R(3,3)$ equals:',
    options: ['6', '5', '9', '8'],
    correctIndex: 0,
    explanation: 'Any 2-coloring of $K_6$ edges contains a monochromatic triangle. $K_5$ does not guarantee this.',
    realWorld: 'Ramsey theory provides worst-case guarantees in distributed consensus and network design.',
    hint: 'What is the smallest $n$ such that any red-blue coloring of $K_n$ edges yields a monochromatic triangle?',
  },
  {
    id: 90010, topic: 'combinatorics', difficulty: 'hard',
    question: 'The permanent of an $n \\times n$ matrix differs from its determinant in that:',
    options: ['It uses no sign changes in the Leibniz expansion', 'It is always zero', 'It equals the determinant for symmetric matrices', 'It is only defined for real matrices'],
    correctIndex: 0,
    explanation: 'The permanent sums over all permutations without the $(-1)^{\\text{sgn}(\\sigma)}$ sign factor.',
    realWorld: 'Computing permanents (#P-hard) is central to boson sampling and quantum advantage arguments.',
    hint: 'Compare the signs in the summation formulas for det vs perm.',
  },
  // ── SOTA ──
  {
    id: 90011, topic: 'combinatorics', difficulty: 'sota',
    question: 'The Hales-Jewett theorem generalizes van der Waerden\'s theorem to which setting?',
    options: ['Combinatorial lines in high-dimensional cubes', 'Coloring of hypergraphs', 'Ramsey numbers for bipartite graphs', 'Turán density of 3-uniform hypergraphs'],
    correctIndex: 0,
    explanation: 'Hales-Jewett guarantees a combinatorial line in $[k]^n$ for large enough $n$, generalizing arithmetic progressions.',
    realWorld: 'The polymath project\'s density Hales-Jewett proof pioneered massively collaborative mathematics.',
    hint: 'Think about tic-tac-toe generalized to high dimensions.',
  },
  {
    id: 90012, topic: 'combinatorics', difficulty: 'sota',
    question: 'Szemerédi\'s Regularity Lemma approximates any large graph by a bounded number of:',
    options: ['Pseudo-random bipartite pairs', 'Cliques', 'Independent sets', 'Perfect matchings'],
    correctIndex: 0,
    explanation: 'The lemma partitions vertices into a bounded number of parts where most pairs behave pseudo-randomly.',
    realWorld: 'Graph regularity underpins modern approaches to property testing and graph neural networks.',
    hint: 'The key concept is ε-regularity between vertex partition classes.',
  },
  {
    id: 90013, topic: 'combinatorics', difficulty: 'sota',
    question: 'The sunflower conjecture (Erdős-Ko-Rado variant) was recently advanced by Alweiss et al. (2020), improving the bound to roughly:',
    options: ['$(\\log k)^k$ for $k$-uniform sunflower-free families', '$k^k$', '$2^k$', '$k!$'],
    correctIndex: 0,
    explanation: 'The breakthrough showed sunflower-free families have size at most $(C \\log k)^k$, dramatically improving the previous $k^k$ bound.',
    realWorld: 'Sunflower bounds impact circuit complexity lower bounds and data structure design.',
    hint: 'This was a major breakthrough improving the Erdős-Rado sunflower lemma.',
  },
  {
    id: 90014, topic: 'combinatorics', difficulty: 'sota',
    question: 'In additive combinatorics, the Polynomial Freiman-Ruzsa conjecture (proven by Gowers, Green, Manners, Tao 2023) relates sets with small doubling to:',
    options: ['Subgroups of bounded index via polynomial bounds', 'Arithmetic progressions of length $k$', 'Sum-free subsets', 'Sidon sets'],
    correctIndex: 0,
    explanation: 'PFR shows sets $A$ with $|A+A| \\leq K|A|$ are covered by polynomially many cosets of a subgroup, settling a major conjecture.',
    realWorld: 'This breakthrough connects additive structure to coding theory and compressed sensing.',
    hint: 'Think about what small doubling $|A+A| \\leq K|A|$ structurally implies.',
  },
  {
    id: 90015, topic: 'combinatorics', difficulty: 'sota',
    question: 'The container method in combinatorics provides:',
    options: ['A small family of "containers" covering all independent sets in a hypergraph', 'Optimal graph colorings', 'Minimum spanning trees', 'Maximum flows'],
    correctIndex: 0,
    explanation: 'Hypergraph containers show that independent sets in uniform hypergraphs can be encoded by a small collection of almost-independent "containers".',
    realWorld: 'Container methods have resolved longstanding conjectures about random graphs and arithmetic structures.',
    hint: 'Think about efficiently describing all independent sets without listing them.',
  },
];
