import type { Question } from '../types';

export const psychologyQuestions: Question[] = [
  {
    id: 41301, topic: 'psychology', difficulty: 'easy',
    question: 'Kahneman\'s "System 1 vs System 2" framework describes:',
    options: [
      'Two modes of thinking: System 1 (fast, automatic, intuitive) and System 2 (slow, deliberate, analytical) — most cognitive biases arise from System 1 shortcuts',
      'Two different brain hemispheres',
      'Two stages of memory formation',
      'Two types of intelligence (verbal and spatial)',
    ],
    correctIndex: 0,
    explanation: 'System 1 handles ~98% of daily decisions using heuristics. It\'s fast but prone to biases (anchoring, availability, representativeness). System 2 is effortful and logical but lazy.',
    realWorld: 'This framework explains why smart people make irrational decisions. It\'s applied in behavioral economics (nudges), UX design, and AI alignment.',
    hint: 'Fast thinking (gut feeling) vs. slow thinking (careful analysis) — we mostly use the fast one.',
  },
  {
    id: 41304, topic: 'psychology', difficulty: 'easy',
    question: 'Confirmation bias causes people to:',
    options: [
      'Seek out, interpret, and remember information that confirms their existing beliefs while ignoring contradictory evidence',
      'Always change their mind when presented with new data',
      'Equally weigh all evidence regardless of source',
      'Prefer information from authority figures only',
    ],
    correctIndex: 0,
    explanation: 'Confirmation bias is one of the most robust findings in psychology. People actively search for confirming evidence (selection bias), interpret ambiguous evidence as supportive (interpretation bias), and better remember confirming information (memory bias).',
    realWorld: 'Social media algorithms amplify confirmation bias by showing content users agree with. In ML, confirmation bias appears when researchers only report metrics that support their hypothesis.',
    hint: 'We\'re all natural lawyers — building cases for what we already believe.',
  },
  {
    id: 41302, topic: 'psychology', difficulty: 'hard',
    question: 'The replication crisis in psychology revealed that:',
    options: [
      'Over 60% of classic psychology experiments failed to replicate when repeated with larger samples and pre-registered methods',
      'All psychology experiments are perfectly reproducible',
      'Only neuroscience experiments have replication issues',
      'Replication is unnecessary if the original study was published',
    ],
    correctIndex: 0,
    explanation: 'The Open Science Collaboration (2015) found only 36% of 100 psychology studies replicated. Causes include p-hacking, small samples, publication bias, and questionable research practices.',
    realWorld: 'This crisis transformed scientific practice: pre-registration, registered reports, open data/code, and larger sample sizes are now standard. It also affects ML research.',
    hint: 'When scientists tried to repeat famous experiments with better methods, most didn\'t work.',
  },
  {
    id: 41305, topic: 'psychology', difficulty: 'hard',
    question: 'The anchoring effect demonstrates that:',
    options: [
      'Initial exposure to a number (even random) systematically biases subsequent numerical judgments — people adjust insufficiently from the anchor',
      'People always make perfectly rational numerical estimates',
      'Numbers have no effect on decision-making',
      'Only experts are affected by numerical priming',
    ],
    correctIndex: 0,
    explanation: 'Tversky & Kahneman (1974) showed that spinning a wheel to get a random number (10 or 65) influenced people\'s estimate of African countries in the UN. Anchoring works even when the anchor is obviously irrelevant.',
    realWorld: 'Anchoring drives pricing strategy ($999 vs $1000), salary negotiations (first number stated dominates), and legal sentencing (prosecutors\' recommended sentences anchor judges\' decisions).',
    hint: 'The first number you hear sticks — even if it\'s completely irrelevant to the question.',
  },
  {
    id: 41303, topic: 'psychology', difficulty: 'sota',
    question: 'Computational cognitive science models human cognition as:',
    options: [
      'Approximate Bayesian inference under resource constraints — the brain computes posterior beliefs from prior knowledge and sensory evidence using efficient approximations',
      'A simple lookup table of stimulus-response pairs',
      'Pure logical deduction without any uncertainty',
      'Random behavior with no underlying computational principles',
    ],
    correctIndex: 0,
    explanation: 'The Bayesian brain hypothesis models perception, learning, and decision-making as probabilistic inference: $P(\\text{world}|\\text{data}) \\propto P(\\text{data}|\\text{world})P(\\text{world})$.',
    realWorld: 'This framework explains optical illusions (priors override data), placebo effects, and why AI alignment is hard (human preferences are probabilistic and context-dependent).',
    hint: 'The brain is a prediction machine — combining prior beliefs with new evidence, approximately.',
  },
  {
    id: 41306, topic: 'psychology', difficulty: 'sota',
    question: 'Large language models exhibit cognitive biases similar to humans because:',
    options: [
      'Training on human-generated text embeds human heuristics and biases into the model\'s statistical patterns — the model learns our cognitive shortcuts along with our knowledge',
      'LLMs have consciousness and make biased decisions intentionally',
      'Biases are hardcoded by programmers',
      'LLMs never exhibit any systematic biases',
    ],
    correctIndex: 0,
    explanation: 'Studies show GPT-4 exhibits anchoring, framing effects, and sunk-cost fallacies matching human patterns. Since LLMs learn from human text, they absorb the same systematic reasoning errors humans display.',
    realWorld: 'This has direct implications for AI deployment: if LLMs inherit human cognitive biases, they can\'t be trusted for "objective" decision-making in hiring, lending, or criminal justice without explicit debiasing.',
    hint: 'Trained on human text → learns human thinking patterns → inherits human biases.',
  },
];
