import type { Question } from '../types';

export const psychologyQuestions: Question[] = [
  {
    id: 41301, topic: 'psychology', difficulty: 'easy',
    question: 'In dual-process accounts of cognition, fast automatic processing is commonly contrasted with:',
    options: [
      'Slower deliberate reasoning',
      'Stored sensory information',
      'Language-specific grammar',
      'Long-term episodic recall',
    ],
    correctIndex: 0,
    explanation: 'Dual-process accounts distinguish relatively fast, automatic processing from slower, more effortful and deliberative reasoning.',
    realWorld: 'The distinction helps researchers study when quick judgments are useful and when deliberate checking can improve decisions.',
    hint: 'The contrast is between quick intuition and effortful reflection.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41304, topic: 'psychology', difficulty: 'easy',
    question: 'Which behavior best illustrates confirmation bias?',
    options: [
      'Changing a belief after strong contrary evidence',
      'Seeking evidence that supports an existing belief',
      'Sampling sources without knowing their conclusions',
      'Giving equal attention to competing explanations',
    ],
    correctIndex: 1,
    explanation: 'Confirmation bias describes a tendency to seek, interpret, or remember information in ways that favor an existing belief or hypothesis.',
    realWorld: 'Recognizing the bias matters in research, investing, diagnosis, hiring, and any setting where people evaluate evidence under uncertainty.',
    hint: 'Think about evidence that feels especially welcome because it agrees with you.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41307, topic: 'psychology', difficulty: 'easy',
    question: 'Working memory is most closely associated with:',
    options: [
      'Permanent storage of autobiographical events',
      'Automatic regulation of heart rate',
      'Brief maintenance and manipulation of information',
      'Detection of light by retinal receptors',
    ],
    correctIndex: 2,
    explanation: 'Working memory supports the short-term maintenance and active manipulation of information needed for tasks such as reasoning and mental arithmetic.',
    realWorld: 'Working-memory demands shape interface design, classroom instruction, multitasking, and the difficulty of following multi-step procedures.',
    hint: 'It is the mental workspace used while actively solving a problem.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41302, topic: 'psychology', difficulty: 'hard',
    question: 'What did the 2015 Open Science Collaboration replication project most clearly show?',
    options: [
      'Every original effect reproduced at the same size',
      'Replication is unnecessary with large samples',
      'Only clinical psychology showed weaker effects',
      'Replicated effects were often weaker than originals',
    ],
    correctIndex: 3,
    explanation: 'The large replication project found that replication effects were, on average, substantially smaller than the effects reported in the original studies.',
    realWorld: 'The project accelerated adoption of larger samples, preregistration, data sharing, and other practices intended to improve research reliability.',
    hint: 'The central lesson concerned how strongly many published effects reappeared.',
    sources: [{
      title: 'Estimating the reproducibility of psychological science',
      url: 'https://www.science.org/doi/10.1126/science.aac4716',
      publisher: 'Science',
      year: 2015,
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 41305, topic: 'psychology', difficulty: 'hard',
    question: 'In judgment research, an anchoring effect occurs when:',
    options: [
      'An initial value pulls later estimates toward it',
      'Recent memories become impossible to retrieve',
      'People ignore every numerical cue they encounter',
      'A reward becomes less valuable after repetition',
    ],
    correctIndex: 0,
    explanation: 'Anchoring occurs when an initial value or reference point influences a later estimate, often even when the starting value is weakly informative.',
    realWorld: 'Anchors can affect negotiations, pricing, forecasts, legal judgments, and estimates made under uncertainty.',
    hint: 'The first number can become a reference point for the next judgment.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41308, topic: 'psychology', difficulty: 'hard',
    question: 'In signal detection theory, d-prime primarily measures:',
    options: [
      'The observer\'s preference for saying yes',
      'Separation between signal and noise distributions',
      'The number of trials completed per minute',
      'Memory capacity for recently seen stimuli',
    ],
    correctIndex: 1,
    explanation: 'The sensitivity measure d-prime summarizes how well an observer can distinguish the signal distribution from the noise distribution independently of response bias.',
    realWorld: 'Signal detection theory is used in medical screening, radar, quality control, perception research, and human-factors engineering.',
    hint: 'It describes discriminability rather than a willingness to choose one response.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 41303, topic: 'psychology', difficulty: 'sota',
    question: 'What is the central purpose of preregistering an empirical study?',
    options: [
      'Guaranteeing that the hypothesis will be supported',
      'Preventing researchers from collecting new data',
      'Recording planned hypotheses and analyses in advance',
      'Replacing peer review with an automated decision',
    ],
    correctIndex: 2,
    explanation: 'Preregistration time-stamps key hypotheses, methods, and analysis plans before outcomes are known, helping distinguish confirmatory tests from later exploratory choices.',
    realWorld: 'The practice can make analytical flexibility more visible and helps readers interpret which findings were planned versus discovered after looking at the data.',
    hint: 'The key step happens before researchers know the study outcome.',
    sources: [{
      title: 'Preregistration',
      url: 'https://www.cos.io/initiatives/prereg',
      publisher: 'Center for Open Science',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 41306, topic: 'psychology', difficulty: 'sota',
    question: 'How does the NIMH Research Domain Criteria framework organize much of its research?',
    options: [
      'Only by traditional diagnostic categories',
      'Only by a single level of brain measurement',
      'Only by symptoms reported during one interview',
      'By functional dimensions studied across multiple levels',
    ],
    correctIndex: 3,
    explanation: 'RDoC studies dimensions of neurobehavioral functioning across a range from normal to abnormal and encourages integration of multiple units of analysis.',
    realWorld: 'This transdiagnostic framework lets researchers investigate mechanisms that can cut across several conventional diagnostic categories.',
    hint: 'The framework emphasizes dimensions and multiple kinds of evidence.',
    sources: [{
      title: 'About RDoC',
      url: 'https://www.nimh.nih.gov/research/research-funded-by-nimh/rdoc/about-rdoc',
      publisher: 'National Institute of Mental Health',
    }],
    reviewedAt: '2026-09-20',
    factualAsOf: '2026-09-20',
  },
  {
    id: 41309, topic: 'psychology', difficulty: 'sota',
    question: 'In a drift-diffusion model of a two-choice decision, the drift rate represents:',
    options: [
      'The average rate at which evidence accumulates',
      'The fixed delay before a stimulus is displayed',
      'The number of response buttons in the experiment',
      'The probability that all trials are discarded',
    ],
    correctIndex: 0,
    explanation: 'Drift rate captures the average speed and quality of evidence accumulation toward one of the model\'s decision boundaries.',
    realWorld: 'Diffusion models help separate changes in evidence quality from changes in response caution and nondecision time.',
    hint: 'It is about how quickly evidence moves toward a choice boundary.',
    sources: [{
      title: 'The diffusion decision model: theory and data for two-choice decision tasks',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2474742/',
      publisher: 'Neural Computation',
      year: 2008,
    }],
    reviewedAt: '2026-09-20',
  },
];
