// Generated by scripts/generate-question-loaders.ts. Do not edit by hand.
import type { Question } from './types';

export const QUESTION_GROUPS = [
  "linear-algebra",
  "calculus",
  "probability-stats",
  "optimization",
  "discrete-math",
  "physics",
  "quant",
  "chemistry",
  "biology",
  "computer-science",
  "earth-space",
  "astrophysics",
  "engineering",
  "economics",
  "new-topics",
  "thermodynamics",
  "quantum-computing",
  "game-theory",
  "robotics",
  "meteorology",
  "audio-engineering",
  "neuroscience",
  "linguistics",
  "oceanography",
  "cybersecurity",
  "aerospace",
  "nuclear-physics",
  "fluid-dynamics",
  "philosophy-of-science",
  "topology",
  "psychology",
  "environmental-science",
  "pharmacology",
  "differential-equations",
  "abstract-algebra",
  "optics",
  "relativity",
  "statistical-physics",
  "plasma-physics",
  "condensed-matter",
  "nonlinear-dynamics",
  "quantum-field-theory",
  "many-body-physics",
  "quantum-gravity",
  "distributed-systems",
  "operating-systems",
  "sota-2024",
  "sota-2025",
  "sota-2026",
  "combinatorics",
  "category-theory",
  "ergodic-theory",
  "algebraic-geometry",
  "measure-theory",
  "compiler-theory",
  "control-theory",
  "signal-processing",
  "behavioral-economics",
  "development-economics",
  "market-microstructure",
  "credit-risk",
  "prediction-markets",
  "formal-verification",
  "ai-substrates",
  "information-theory",
  "complex-analysis",
  "functional-analysis",
  "graph-theory",
  "differential-geometry",
  "numerical-methods"
] as const;

const GROUP_LOADERS: Record<string, () => Promise<Question[]>> = {
  "linear-algebra": () => import('./linear-algebra').then((module) => module.linearAlgebraQuestions),
  "calculus": () => import('./calculus').then((module) => module.calculusQuestions),
  "probability-stats": () => import('./probability-stats').then((module) => module.probabilityStatsQuestions),
  "optimization": () => import('./optimization').then((module) => module.optimizationQuestions),
  "discrete-math": () => import('./discrete-math').then((module) => module.discreteMathQuestions),
  "physics": () => import('./physics').then((module) => module.physicsQuestions),
  "quant": () => import('./quant').then((module) => module.quantQuestions),
  "chemistry": () => import('./chemistry').then((module) => module.chemistryQuestions),
  "biology": () => import('./biology').then((module) => module.biologyQuestions),
  "computer-science": () => import('./computer-science').then((module) => module.computerScienceQuestions),
  "earth-space": () => import('./earth-space').then((module) => module.earthSpaceQuestions),
  "astrophysics": () => import('./astrophysics').then((module) => module.astrophysicsQuestions),
  "engineering": () => import('./engineering').then((module) => module.engineeringQuestions),
  "economics": () => import('./economics').then((module) => module.economicsQuestions),
  "new-topics": () => import('./new-topics').then((module) => [...module.electromagnetismQuestions, ...module.numberTheoryQuestions, ...module.realAnalysisQuestions, ...module.riskManagementQuestions]),
  "thermodynamics": () => import('./thermodynamics').then((module) => module.thermodynamicsTopicQuestions),
  "quantum-computing": () => import('./quantum-computing').then((module) => module.quantumComputingQuestions),
  "game-theory": () => import('./game-theory').then((module) => module.gameTheoryQuestions),
  "robotics": () => import('./robotics').then((module) => module.roboticsQuestions),
  "meteorology": () => import('./meteorology').then((module) => module.meteorologyQuestions),
  "audio-engineering": () => import('./audio-engineering').then((module) => module.audioEngineeringQuestions),
  "neuroscience": () => import('./neuroscience').then((module) => module.neuroscienceQuestions),
  "linguistics": () => import('./linguistics').then((module) => module.linguisticsQuestions),
  "oceanography": () => import('./oceanography').then((module) => module.oceanographyQuestions),
  "cybersecurity": () => import('./cybersecurity').then((module) => module.cybersecurityQuestions),
  "aerospace": () => import('./aerospace').then((module) => module.aerospaceQuestions),
  "nuclear-physics": () => import('./nuclear-physics').then((module) => module.nuclearPhysicsQuestions),
  "fluid-dynamics": () => import('./fluid-dynamics').then((module) => module.fluidDynamicsQuestions),
  "philosophy-of-science": () => import('./philosophy-of-science').then((module) => module.philosophyScienceQuestions),
  "topology": () => import('./topology').then((module) => module.topologyQuestions),
  "psychology": () => import('./psychology').then((module) => module.psychologyQuestions),
  "environmental-science": () => import('./environmental-science').then((module) => module.environmentalScienceQuestions),
  "pharmacology": () => import('./pharmacology').then((module) => module.pharmacologyQuestions),
  "differential-equations": () => import('./differential-equations').then((module) => module.differentialEquationsQuestions),
  "abstract-algebra": () => import('./abstract-algebra').then((module) => module.abstractAlgebraQuestions),
  "optics": () => import('./optics').then((module) => module.opticsQuestions),
  "relativity": () => import('./relativity').then((module) => module.relativityQuestions),
  "statistical-physics": () => import('./statistical-physics').then((module) => module.statisticalPhysicsQuestions),
  "plasma-physics": () => import('./plasma-physics').then((module) => module.plasmaPhysicsQuestions),
  "condensed-matter": () => import('./condensed-matter').then((module) => module.condensedMatterQuestions),
  "nonlinear-dynamics": () => import('./nonlinear-dynamics').then((module) => module.nonlinearDynamicsQuestions),
  "quantum-field-theory": () => import('./quantum-field-theory').then((module) => module.quantumFieldTheoryQuestions),
  "many-body-physics": () => import('./many-body-physics').then((module) => module.manyBodyPhysicsQuestions),
  "quantum-gravity": () => import('./quantum-gravity').then((module) => module.quantumGravityQuestions),
  "distributed-systems": () => import('./distributed-systems').then((module) => module.distributedSystemsQuestions),
  "operating-systems": () => import('./operating-systems').then((module) => module.operatingSystemsQuestions),
  "sota-2024": () => import('./sota-2024').then((module) => module.sota2024Questions),
  "sota-2025": () => import('./sota-2025').then((module) => module.sota2025Questions),
  "sota-2026": () => import('./sota-2026').then((module) => module.sota2026Questions),
  "combinatorics": () => import('./combinatorics').then((module) => module.combinatoricsQuestions),
  "category-theory": () => import('./category-theory').then((module) => module.categoryTheoryQuestions),
  "ergodic-theory": () => import('./ergodic-theory').then((module) => module.ergodicTheoryQuestions),
  "algebraic-geometry": () => import('./algebraic-geometry').then((module) => module.algebraicGeometryQuestions),
  "measure-theory": () => import('./measure-theory').then((module) => module.measureTheoryQuestions),
  "compiler-theory": () => import('./compiler-theory').then((module) => module.compilerTheoryQuestions),
  "control-theory": () => import('./control-theory').then((module) => module.controlTheoryQuestions),
  "signal-processing": () => import('./signal-processing').then((module) => module.signalProcessingQuestions),
  "behavioral-economics": () => import('./behavioral-economics').then((module) => module.behavioralEconomicsQuestions),
  "development-economics": () => import('./development-economics').then((module) => module.developmentEconomicsQuestions),
  "market-microstructure": () => import('./market-microstructure').then((module) => module.marketMicrostructureQuestions),
  "credit-risk": () => import('./credit-risk').then((module) => module.creditRiskQuestions),
  "prediction-markets": () => import('./prediction-markets').then((module) => module.predictionMarketsQuestions),
  "formal-verification": () => import('./formal-verification').then((module) => module.formalVerificationQuestions),
  "ai-substrates": () => import('./ai-substrates').then((module) => module.aiSubstratesQuestions),
  "information-theory": () => import('./information-theory').then((module) => module.informationTheoryQuestions),
  "complex-analysis": () => import('./complex-analysis').then((module) => module.complexAnalysisQuestions),
  "functional-analysis": () => import('./functional-analysis').then((module) => module.functionalAnalysisQuestions),
  "graph-theory": () => import('./graph-theory').then((module) => module.graphTheoryQuestions),
  "differential-geometry": () => import('./differential-geometry').then((module) => module.differentialGeometryQuestions),
  "numerical-methods": () => import('./numerical-methods').then((module) => module.numericalMethodsQuestions),
};

export const TOPIC_TO_GROUPS: Readonly<Record<string, readonly string[]>> = {
  "linear-algebra": [
    "linear-algebra"
  ],
  "calculus": [
    "calculus"
  ],
  "probability-stats": [
    "probability-stats"
  ],
  "optimization": [
    "optimization"
  ],
  "discrete-math": [
    "discrete-math"
  ],
  "classical-mechanics": [
    "physics"
  ],
  "quantum-mechanics": [
    "physics"
  ],
  "algo-trading": [
    "quant"
  ],
  "derivatives-pricing": [
    "quant"
  ],
  "fixed-income": [
    "quant"
  ],
  "portfolio-theory": [
    "quant"
  ],
  "stochastic-calculus": [
    "quant"
  ],
  "inorganic-chemistry": [
    "chemistry"
  ],
  "organic-chemistry": [
    "chemistry"
  ],
  "physical-chemistry": [
    "chemistry"
  ],
  "ecology": [
    "biology"
  ],
  "genetics": [
    "biology"
  ],
  "molecular-biology": [
    "biology"
  ],
  "ai-models": [
    "computer-science"
  ],
  "algorithms": [
    "computer-science"
  ],
  "cryptography": [
    "computer-science"
  ],
  "machine-learning": [
    "computer-science"
  ],
  "astronomy": [
    "earth-space"
  ],
  "climate-science": [
    "earth-space"
  ],
  "geology": [
    "earth-space"
  ],
  "astrophysics": [
    "astrophysics"
  ],
  "aerodynamics": [
    "engineering",
    "aerospace"
  ],
  "audio-engineering": [
    "engineering",
    "audio-engineering"
  ],
  "biomedical-engineering": [
    "engineering"
  ],
  "circuits-electronics": [
    "engineering"
  ],
  "communications-coding": [
    "engineering"
  ],
  "control-systems": [
    "engineering",
    "control-theory"
  ],
  "environmental-engineering": [
    "engineering"
  ],
  "materials-science": [
    "engineering"
  ],
  "nuclear-engineering": [
    "engineering"
  ],
  "orbital-mechanics": [
    "engineering",
    "aerospace"
  ],
  "power-systems": [
    "engineering"
  ],
  "process-design": [
    "engineering"
  ],
  "reaction-engineering": [
    "engineering"
  ],
  "robotics-mechatronics": [
    "engineering",
    "robotics"
  ],
  "semiconductor-engineering": [
    "engineering"
  ],
  "signal-processing": [
    "engineering",
    "signal-processing"
  ],
  "solid-mechanics": [
    "engineering"
  ],
  "structural-engineering": [
    "engineering"
  ],
  "thermofluids": [
    "engineering"
  ],
  "transport-phenomena": [
    "engineering"
  ],
  "econometrics": [
    "economics"
  ],
  "macroeconomics": [
    "economics"
  ],
  "microeconomics": [
    "economics"
  ],
  "electromagnetism": [
    "new-topics"
  ],
  "number-theory": [
    "new-topics"
  ],
  "real-analysis": [
    "new-topics"
  ],
  "risk-management": [
    "new-topics"
  ],
  "thermodynamics": [
    "thermodynamics"
  ],
  "quantum-computing": [
    "quantum-computing"
  ],
  "game-theory": [
    "game-theory"
  ],
  "meteorology": [
    "meteorology"
  ],
  "neuroscience": [
    "neuroscience"
  ],
  "linguistics": [
    "linguistics"
  ],
  "oceanography": [
    "oceanography"
  ],
  "cybersecurity": [
    "cybersecurity"
  ],
  "spaceflight-systems": [
    "aerospace"
  ],
  "nuclear-physics": [
    "nuclear-physics"
  ],
  "fluid-dynamics": [
    "fluid-dynamics"
  ],
  "philosophy-of-science": [
    "philosophy-of-science"
  ],
  "topology": [
    "topology"
  ],
  "psychology": [
    "psychology"
  ],
  "environmental-science": [
    "environmental-science"
  ],
  "pharmacology": [
    "pharmacology"
  ],
  "differential-equations": [
    "differential-equations"
  ],
  "abstract-algebra": [
    "abstract-algebra"
  ],
  "optics": [
    "optics"
  ],
  "relativity": [
    "relativity"
  ],
  "statistical-physics": [
    "statistical-physics"
  ],
  "plasma-physics": [
    "plasma-physics"
  ],
  "condensed-matter": [
    "condensed-matter"
  ],
  "nonlinear-dynamics": [
    "nonlinear-dynamics"
  ],
  "quantum-field-theory": [
    "quantum-field-theory"
  ],
  "many-body-physics": [
    "many-body-physics"
  ],
  "quantum-gravity": [
    "quantum-gravity"
  ],
  "distributed-systems": [
    "distributed-systems"
  ],
  "operating-systems": [
    "operating-systems"
  ],
  "sota-2024": [
    "sota-2024"
  ],
  "sota-2025": [
    "sota-2025"
  ],
  "sota-2026": [
    "sota-2026"
  ],
  "combinatorics": [
    "combinatorics"
  ],
  "category-theory": [
    "category-theory"
  ],
  "ergodic-theory": [
    "ergodic-theory"
  ],
  "algebraic-geometry": [
    "algebraic-geometry"
  ],
  "measure-theory": [
    "measure-theory"
  ],
  "compiler-theory": [
    "compiler-theory"
  ],
  "behavioral-economics": [
    "behavioral-economics"
  ],
  "development-economics": [
    "development-economics"
  ],
  "market-microstructure": [
    "market-microstructure"
  ],
  "credit-risk": [
    "credit-risk"
  ],
  "prediction-markets": [
    "prediction-markets"
  ],
  "formal-verification": [
    "formal-verification"
  ],
  "ai-substrates": [
    "ai-substrates"
  ],
  "information-theory": [
    "information-theory"
  ],
  "complex-analysis": [
    "complex-analysis"
  ],
  "functional-analysis": [
    "functional-analysis"
  ],
  "graph-theory": [
    "graph-theory"
  ],
  "differential-geometry": [
    "differential-geometry"
  ],
  "numerical-methods": [
    "numerical-methods"
  ]
};

const groupCache = new Map<string, Promise<Question[]>>();

function loadGroup(group: string): Promise<Question[]> {
  const cached = groupCache.get(group);
  if (cached) return cached;
  const loader = GROUP_LOADERS[group];
  if (!loader) return Promise.resolve([]);
  const request = loader().catch((error) => { groupCache.delete(group); throw error; });
  groupCache.set(group, request);
  return request;
}

export interface QuestionLoadProgress { loaded: number; total: number }

export async function loadQuestionsForTopics(topics: string[], onProgress?: (progress: QuestionLoadProgress) => void): Promise<Question[]> {
  const groups = topics.length === 0 ? Object.keys(GROUP_LOADERS) : [...new Set(topics.flatMap((topic) => TOPIC_TO_GROUPS[topic] ?? []))];
  let loaded = 0;
  onProgress?.({ loaded, total: groups.length });
  const pools = await Promise.all(groups.map(async (group) => { const questions = await loadGroup(group); loaded += 1; onProgress?.({ loaded, total: groups.length }); return questions; }));
  const pool = pools.flat();
  return topics.length === 0 ? pool : pool.filter((question) => topics.includes(question.topic));
}
