import type { Question } from '../types';

export const environmentalScienceQuestions: Question[] = [
  {
    id: 41401, topic: 'environmental-science', difficulty: 'easy',
    question: 'The greenhouse effect works because:',
    options: [
      'Certain gases (CO₂, CH₄, H₂O) absorb outgoing infrared radiation and re-emit it in all directions, warming the surface by ~33°C above what it would be without an atmosphere',
      'The Sun is getting hotter every year',
      'The ozone hole lets in more solar radiation',
      'Heat from the Earth\'s core warms the surface',
    ],
    correctIndex: 0,
    explanation: 'Solar radiation passes through the atmosphere and warms the surface. The surface emits infrared radiation, which greenhouse gases absorb and re-radiate.',
    realWorld: 'CO₂ has risen from 280 ppm (pre-industrial) to 424 ppm (2024). The enhanced greenhouse effect has warmed the planet by ~1.2°C.',
    hint: 'The atmosphere acts like a blanket — it lets sunlight in but traps heat going out.',
  },
  {
    id: 41404, topic: 'environmental-science', difficulty: 'easy',
    question: 'The ozone layer protects life on Earth by:',
    options: [
      'Absorbing 97-99% of harmful UV-B and UV-C radiation from the Sun — without it, surface UV levels would sterilize most land life',
      'Reflecting all visible light back to space',
      'Trapping heat to warm the planet',
      'Producing oxygen for breathing',
    ],
    correctIndex: 0,
    explanation: 'Ozone (O₃) in the stratosphere (15-35 km altitude) absorbs UV radiation via photodissociation: UV + O₃ → O₂ + O. The Montreal Protocol (1987) phased out CFCs that were destroying ozone — the most successful environmental treaty in history.',
    realWorld: 'The ozone hole over Antarctica has been healing since CFC bans — expected to recover by ~2066. This success story shows that global environmental cooperation can work when the science is clear and alternatives exist.',
    hint: 'A thin layer of gas high in the atmosphere blocks the Sun\'s most dangerous radiation.',
  },
  {
    id: 41402, topic: 'environmental-science', difficulty: 'hard',
    question: 'Climate feedback loops amplify warming because:',
    options: [
      'Initial warming triggers secondary effects (ice melt reduces albedo → more absorption, permafrost thaw releases CH₄ → more warming) that accelerate the original change',
      'The Sun\'s output increases in response to CO₂',
      'Volcanoes erupt more frequently when temperature rises',
      'Feedback loops always reduce warming',
    ],
    correctIndex: 0,
    explanation: 'Positive feedbacks include: ice-albedo (less ice → darker surface → more absorption), water vapor (warmer air holds more H₂O), and permafrost methane release.',
    realWorld: 'The Arctic is warming 4× faster than the global average due to ice-albedo feedback. Permafrost contains ~1.5 trillion tons of carbon.',
    hint: 'Warming causes changes that cause more warming — a vicious cycle.',
  },
  {
    id: 41405, topic: 'environmental-science', difficulty: 'hard',
    question: 'The carbon cycle balances Earth\'s climate through:',
    options: [
      'Natural fluxes between atmosphere, ocean, biosphere, and lithosphere — photosynthesis and ocean absorption remove CO₂, while respiration, volcanism, and decomposition release it, with a ~100-year residence time',
      'A single process that only absorbs CO₂ from the atmosphere',
      'Complete isolation of carbon in underground reservoirs',
      'Instantaneous equilibrium that adjusts within days',
    ],
    correctIndex: 0,
    explanation: 'The natural carbon cycle moved ~750 Gt CO₂/year between reservoirs before humans. We now add ~36 Gt CO₂/year from fossil fuels — the ocean and biosphere absorb ~55%, the rest accumulates in the atmosphere.',
    realWorld: 'Understanding the carbon cycle is essential for evaluating carbon capture technologies. Direct air capture (DAC) currently costs $250-600/ton CO₂. Natural solutions (reforestation) cost $5-50/ton but have limited scalability.',
    hint: 'Carbon moves between air, water, life, and rock — humans have disrupted this ancient balance.',
  },
  {
    id: 41403, topic: 'environmental-science', difficulty: 'sota',
    question: 'AI-driven climate modeling advances include:',
    options: [
      'Neural operator emulators that learn PDE dynamics from data, providing 1000× faster climate projections while maintaining physical consistency through physics-informed loss functions',
      'Replacing all climate observations with AI predictions',
      'Using AI to control the weather directly',
      'Training models exclusively on historical temperature records',
    ],
    correctIndex: 0,
    explanation: 'Neural operators learn the solution operator of climate PDEs from simulation data. Physics-informed neural networks add PDE residuals as loss terms, ensuring predictions respect conservation laws.',
    realWorld: 'NVIDIA\'s FourCastNet produces global weather forecasts in seconds. ClimaX can be fine-tuned for regional projections. These tools enable millions of scenario analyses for policy decisions.',
    hint: 'Instead of solving equations from scratch, AI learns the patterns — 1000× faster with physics built into the training.',
  },
  {
    id: 41406, topic: 'environmental-science', difficulty: 'sota',
    question: 'Planetary boundaries (Rockström et al.) identify:',
    options: [
      'Nine Earth system processes with quantitative thresholds — exceeding them risks irreversible, abrupt environmental change; six of nine boundaries are already crossed as of 2023',
      'Exactly two environmental limits that matter',
      'Boundaries that only apply to developing countries',
      'Theoretical limits with no empirical evidence',
    ],
    correctIndex: 0,
    explanation: 'The nine boundaries: climate change, biodiversity loss, nitrogen/phosphorus cycles, ocean acidification, land use, freshwater, ozone, aerosols, novel entities (plastics, chemicals). Six are transgressed: biosphere integrity is the most critical.',
    realWorld: 'The framework guides corporate sustainability (Science-Based Targets), EU environmental policy, and the UN Sustainable Development Goals. It provides a scientific foundation for "how much is too much."',
    hint: 'Nine guardrails for the planet — we\'ve already broken through more than half.',
  },
];
