import type { Question } from '../types';

export const environmentalScienceQuestions: Question[] = [
  {
    id: 41401, topic: "environmental-science", difficulty: "easy",
    question: "Eutrophication in a lake is commonly driven by excessive inputs of:",
    options: ["Nitrogen and phosphorus nutrients","Helium and neon","Silica only from bedrock","Atmospheric argon"],
    correctIndex: 0,
    explanation: "Excess nitrogen and phosphorus can stimulate algal blooms; decomposition of the added biomass can then deplete dissolved oxygen.",
    realWorld: "Nutrient management in agriculture and wastewater treatment is central to controlling harmful algal blooms and hypoxic zones.",
    hint: "Think of the nutrients that fertilize both crops and algae.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41404, topic: "environmental-science", difficulty: "easy",
    question: "The stratospheric ozone layer protects life primarily by absorbing much of the Sun's:",
    options: ["Visible green light","Ultraviolet radiation","Radio emission","Infrared radiation from Earth's surface"],
    correctIndex: 1,
    explanation: "Stratospheric ozone strongly absorbs biologically damaging ultraviolet wavelengths, especially UV-B and UV-C.",
    realWorld: "The Montreal Protocol's control of ozone-depleting substances is a major example of science-informed global environmental policy.",
    hint: "The relevant radiation can damage DNA and cause sunburn.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41407, topic: "environmental-science", difficulty: "easy",
    question: "Biomagnification means that the concentration of a persistent contaminant can:",
    options: ["Always decrease in predators","Remain identical in every organism","Increase at higher trophic levels of a food web","Occur only in rocks"],
    correctIndex: 2,
    explanation: "Persistent contaminants that are not readily metabolized or excreted can become more concentrated as predators consume many contaminated prey.",
    realWorld: "Biomagnification helps explain why top predators can face high exposure to substances such as methylmercury and some persistent organic pollutants.",
    hint: "Think about repeated transfer up a food chain.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41402, topic: "environmental-science", difficulty: "hard",
    question: "A positive environmental feedback is one that:",
    options: ["Always restores the system to its starting state","Has no effect on system behaviour","Can occur only in computer models","Amplifies an initial change"],
    correctIndex: 3,
    explanation: "Positive feedback reinforces the direction of an initial disturbance; ice-albedo feedback is a classic climate-related example.",
    realWorld: "Recognizing feedbacks is essential in ecosystem management because responses can be nonlinear and can cross thresholds.",
    hint: "Positive refers to reinforcement, not whether the outcome is beneficial.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41405, topic: "environmental-science", difficulty: "hard",
    question: "A life-cycle assessment (LCA) is designed to compare environmental impacts across:",
    options: ["Stages from raw-material extraction through production, use, and end-of-life","Only the retail price of a product","Only emissions at the factory gate","Only consumer opinions"],
    correctIndex: 0,
    explanation: "LCA tracks material and energy flows and associated impacts across a defined product system, with boundaries and functional units stated explicitly.",
    realWorld: "Life-cycle thinking can reveal trade-offs where a technology reduces impacts in one stage but shifts them to another.",
    hint: "The method follows the product beyond a single factory or use phase.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41408, topic: "environmental-science", difficulty: "hard",
    question: "In environmental toxicology, risk is usually distinguished from hazard because risk also considers:",
    options: ["Only whether a substance can ever cause harm","The likelihood and magnitude of exposure","The colour of the chemical","Whether the chemical is natural or synthetic"],
    correctIndex: 1,
    explanation: "Hazard describes the potential to cause harm, whereas risk combines hazard with exposure conditions such as dose, route, duration, and probability.",
    realWorld: "Environmental standards and remediation decisions depend on both toxic potency and realistic exposure pathways.",
    hint: "A dangerous property matters differently when exposure is negligible versus frequent and high.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 41403, topic: "environmental-science", difficulty: "sota",
    question: "The 2023 update to the planetary-boundaries framework concluded that:",
    options: ["All nine boundaries were safely within their operating space","Only climate change had a quantified boundary","Six of nine assessed planetary boundaries were transgressed","The framework contains exactly three Earth-system processes"],
    correctIndex: 2,
    explanation: "The 2023 assessment concluded that six of nine planetary boundaries were transgressed, indicating growing departure from the proposed safe operating space for humanity.",
    realWorld: "The framework integrates multiple Earth-system pressures rather than treating climate, biodiversity, nutrient cycles, freshwater, and pollution as isolated problems.",
    hint: "The published update reported more than half of the nine boundaries beyond the proposed safe zone.",
    paper: {"title":"Earth beyond six of nine planetary boundaries","url":"https://pubmed.ncbi.nlm.nih.gov/37703365/","venue":"Science Advances","year":2023},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 41409, topic: "environmental-science", difficulty: "sota",
    question: "Why can modern multispectral satellites help find large methane point-source emissions?",
    options: ["Methane is brightly visible to the naked eye from orbit","Methane plumes permanently change Earth's magnetic field","Satellites detect methane only through sound waves","Methane leaves wavelength-dependent absorption signatures that algorithms can detect in repeated imagery"],
    correctIndex: 3,
    explanation: "Methane absorbs in specific shortwave-infrared bands; repeated multispectral observations combined with image processing or machine learning can isolate plume-like signals.",
    realWorld: "Rapid identification of large leaks can support repair and mitigation because methane is a strong but relatively short-lived greenhouse gas.",
    hint: "The signal is spectral: the gas changes reflected light differently at selected wavelengths.",
    paper: {"title":"Automatic detection of methane emissions in multispectral satellite imagery using a vision transformer","url":"https://www.nature.com/articles/s41467-024-47754-y","venue":"Nature Communications","year":2024},
    reviewedAt: "2026-09-19",
  },
  {
    id: 41406, topic: "environmental-science", difficulty: "sota",
    question: "A major reason environmental scientists require baseline surveys before industrial deep-sea mining is to:",
    options: ["Separate mining impacts from substantial natural spatial and temporal variability","Guarantee that no organisms are present","Prove impacts are always zero","Replace post-disturbance monitoring entirely"],
    correctIndex: 0,
    explanation: "Robust before-after-control-impact designs need pre-disturbance data so changes caused by mining can be distinguished from natural variability in abyssal communities.",
    realWorld: "Recent large-scale collector trials show why baseline taxonomy, abundance, and community data are essential for credible environmental impact assessment.",
    hint: "You need to know what variation existed before disturbance to attribute what changed afterward.",
    paper: {"title":"Impacts of an industrial deep-sea mining trial on macrofaunal biodiversity","url":"https://www.nature.com/articles/s41559-025-02911-4","venue":"Nature Ecology & Evolution","year":2025},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
];
