import type { Question } from '../types';

export const functionalAnalysisQuestions: Question[] = [
  // ── EASY ──────────────────────────────────────────────────
  {
    id: 8101,
    topic: 'functional-analysis',
    difficulty: 'easy',
    question: 'A Hilbert space is a complete inner product space. Which of the following is a Hilbert space?',
    options: ['$L^2([0,1])$', '$L^1([0,1])$', '$C([0,1])$ with sup norm', 'The space of polynomials'],
    correctIndex: 0,
    explanation: '$L^2$ is the quintessential Hilbert space — complete with respect to the inner product $\\langle f,g \\rangle = \\int f\\bar{g}$. It is the mathematical home of quantum mechanics, where states live as square-integrable wave functions. $L^1$ lacks an inner product, and polynomials are not complete.',
    realWorld: 'Quantum mechanics is formulated entirely in $L^2$ Hilbert spaces — every state, observable, and measurement.',
    hint: 'Which space has both an inner product and is complete?',
    symbolLinks: { 'L': 'lambda' },
    glossaryLinks: ['hilbert-space'],
    formulaLinks: ['Inner Product'],
  },
  {
    id: 8102,
    topic: 'functional-analysis',
    difficulty: 'easy',
    question: 'The Banach fixed-point theorem guarantees a unique fixed point for a contraction mapping on a complete metric space. What condition defines a contraction?',
    options: [
      '$d(T(x), T(y)) \\le k \\cdot d(x,y)$ for some $k < 1$',
      '$d(T(x), T(y)) < d(x,y)$ for all $x \\ne y$',
      '$T$ is continuous',
      '$T$ is bounded',
    ],
    correctIndex: 0,
    explanation: "A contraction mapping shrinks distances by a factor $k < 1$ uniformly. Banach's theorem (1922) guarantees not just existence but uniqueness, and the iterative sequence $x_{n+1} = T(x_n)$ converges geometrically. This powers Picard iteration for ODEs and value iteration in reinforcement learning.",
    realWorld: 'Bellman operators in RL are contractions — this theorem guarantees convergence of value iteration.',
    hint: 'The Lipschitz constant must be strictly less than 1.',
    symbolLinks: { 'T': 'tau', 'k': 'kappa', 'd': 'delta' },
    glossaryLinks: ['fixed-point-theorem'],
    formulaLinks: ['Banach Fixed-Point Theorem'],
  },
  {
    id: 8103,
    topic: 'functional-analysis',
    difficulty: 'easy',
    question: "What does the Riesz representation theorem say about continuous linear functionals on a Hilbert space $H$?",
    options: [
      'Every functional has the form $\\phi(x) = \\langle x, y \\rangle$ for unique $y \\in H$',
      'Every functional is bounded',
      'Every functional is a projection',
      'Functionals form a finite-dimensional space',
    ],
    correctIndex: 0,
    explanation: "Riesz's theorem establishes a canonical isomorphism $H \\cong H^*$ — every continuous linear functional is inner product with a fixed element. This is why physicists can freely use Dirac's bra-ket notation $\\langle \\psi | \\phi \\rangle$: bras and kets live in isomorphic spaces.",
    realWorld: 'Bra-ket notation in quantum mechanics relies directly on Riesz representation.',
    hint: 'In a Hilbert space, functionals and vectors are the same thing (up to isomorphism).',
    symbolLinks: { 'H': 'eta', '\\phi': 'phi' },
    glossaryLinks: ['dual-space'],
    formulaLinks: ['Riesz Representation Theorem'],
  },
  // ── HARD ──────────────────────────────────────────────────
  {
    id: 8104,
    topic: 'functional-analysis',
    difficulty: 'hard',
    question: 'The Hahn-Banach theorem allows extension of bounded linear functionals from a subspace to the whole space. What is preserved in the extension?',
    options: ['The operator norm', 'Linearity only', 'Continuity but not norm', 'The kernel'],
    correctIndex: 0,
    explanation: "Hahn-Banach is the Swiss army knife of functional analysis. It extends a bounded linear functional from a subspace $M \\subset X$ to all of $X$ while preserving the operator norm $\\|\\phi\\|$. This seemingly technical result has profound consequences: separation of convex sets, existence of supporting hyperplanes, and the entire theory of dual spaces.",
    realWorld: 'Hahn-Banach underpins duality in optimization — every LP has a dual via supporting hyperplane arguments.',
    hint: 'The extension is norm-preserving — no inflation allowed.',
    symbolLinks: { '\\phi': 'phi', 'X': 'chi', 'M': 'mu' },
    glossaryLinks: ['hahn-banach-theorem'],
  },
  {
    id: 8105,
    topic: 'functional-analysis',
    difficulty: 'hard',
    question: 'The spectral theorem for compact self-adjoint operators on a Hilbert space states that the eigenvalues:',
    options: [
      'Are real, countable, and accumulate only at 0',
      'Are complex and dense in $\\mathbb{C}$',
      'Form a continuous spectrum',
      'Are all equal to 1',
    ],
    correctIndex: 0,
    explanation: 'For compact self-adjoint operators, the spectrum is beautifully discrete: real eigenvalues $\\lambda_n \\to 0$, with orthogonal eigenvectors forming a basis. This is the infinite-dimensional generalization of diagonalizing symmetric matrices — and the mathematical foundation of PCA, SVD, and quantum observables.',
    realWorld: 'Principal Component Analysis (PCA) is literally the spectral theorem applied to covariance operators.',
    hint: 'Self-adjoint → real. Compact → eigenvalues shrink to zero.',
    symbolLinks: { '\\lambda': 'lambda' },
    glossaryLinks: ['spectral-theorem', 'compact-operator'],
    formulaLinks: ['Spectral Theorem'],
  },
  {
    id: 8106,
    topic: 'functional-analysis',
    difficulty: 'hard',
    question: 'The open mapping theorem (Banach-Schauder) states that a surjective bounded linear operator between Banach spaces:',
    options: [
      'Maps open sets to open sets',
      'Is always injective',
      'Has finite-dimensional range',
      'Is compact',
    ],
    correctIndex: 0,
    explanation: 'The open mapping theorem is one of the three pillars of Banach space theory (alongside Hahn-Banach and uniform boundedness). If $T: X \\to Y$ is a surjective bounded linear map between Banach spaces, then $T$ is an open map. Corollary: a bijective bounded linear operator has a bounded inverse (the inverse mapping theorem).',
    realWorld: 'Guarantees stability of linear systems — bounded perturbations produce bounded responses.',
    hint: 'Surjective + bounded + linear between complete spaces → open.',
    symbolLinks: { 'T': 'tau', 'X': 'chi', 'Y': 'upsilon' },
  },
  // ── SOTA ──────────────────────────────────────────────────
  {
    id: 8107,
    topic: 'functional-analysis',
    difficulty: 'sota',
    question: 'The invariant subspace problem asks whether every bounded operator on a separable Hilbert space has a non-trivial invariant subspace. For which class was this famously resolved by Per Enflo?',
    options: ['Banach spaces (negative — counterexample)', 'Finite-dimensional spaces', 'Compact operators', 'Self-adjoint operators'],
    correctIndex: 0,
    explanation: "Per Enflo constructed a bounded operator on a Banach space with no non-trivial invariant subspace (1987), but the Hilbert space version remains open. For compact operators, Lomonosov (1973) proved the affirmative. This is one of the great unsolved problems in operator theory.",
    realWorld: 'Invariant subspace structure underpins decomposition methods in quantum chemistry and dynamical systems.',
    hint: 'Enflo found a counterexample, but only on a Banach space — not Hilbert.',
    symbolLinks: { 'H': 'eta' },
  },
  {
    id: 8108,
    topic: 'functional-analysis',
    difficulty: 'sota',
    question: "In non-commutative geometry (Connes), spectral triples $(\\mathcal{A}, H, D)$ generalize Riemannian manifolds. What role does the Dirac operator $D$ play?",
    options: [
      'Encodes the metric geometry via $d(p,q) = \\sup\\{|a(p)-a(q)| : \\|[D,a]\\| \\le 1\\}$',
      'Generates the algebra $\\mathcal{A}$',
      'Defines the topology only',
      'Acts as a projection operator',
    ],
    correctIndex: 0,
    explanation: "Connes' spectral geometry recovers metric information from operator-theoretic data. The Dirac operator $D$ acting on the Hilbert space $H$ encodes distances via a supremum formula that generalizes the geodesic distance. This framework unifies differential geometry with operator algebras and is a leading candidate for quantum gravity.",
    realWorld: "Connes' approach connects the Standard Model of particle physics with gravitational geometry.",
    hint: 'The commutator $[D, a]$ measures how fast functions change — encoding the metric.',
    symbolLinks: { 'D': 'delta', 'H': 'eta' },
    glossaryLinks: ['spectral-triple'],
  },
  {
    id: 8109,
    topic: 'functional-analysis',
    difficulty: 'sota',
    question: 'The Kadison-Singer problem, resolved by Marcus-Spielman-Srivastava (2013), is equivalent to which statement about frame theory?',
    options: [
      'Every Bessel sequence in $\\ell^2$ can be partitioned into finitely many subsequences that are Riesz basic sequences',
      'Every frame is a Riesz basis',
      'All operators on $\\ell^2$ are diagonalizable',
      'The Weyl algebra has a unique representation',
    ],
    correctIndex: 0,
    explanation: "The Kadison-Singer conjecture (1959) was resolved using the method of interlacing families of polynomials. Marcus, Spielman, and Srivastava proved a stronger result (the Weaver conjecture) implying Kadison-Singer. Their technique — bounding roots of expected characteristic polynomials — has since revolutionized combinatorics and theoretical CS.",
    realWorld: 'The proof technique now yields optimal algorithms for graph sparsification and column subset selection.',
    hint: 'Resolved in 2013 with a breakthrough in polynomial method — think interlacing.',
    symbolLinks: { '\\ell': 'lambda' },
    formulaLinks: ['Kadison-Singer Problem'],
  },
];
