import type { Question } from '../types';

export const numberTheoryExpansionQuestions: Question[] = [
  {
    id: 10100, topic: 'number-theory', difficulty: 'easy',
    question: 'Which integer is relatively prime to 15?',
    options: ['6', '10', '14', '21'],
    correctIndex: 2,
    explanation: 'Two integers are relatively prime when their greatest common divisor is 1. Since 14 shares no prime factor with 15, their gcd is 1.',
    realWorld: 'Coprimality determines when modular inverses exist and is fundamental to residue systems and public-key cryptography.',
    hint: 'Factor 15 and check which option shares none of its prime factors.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 10101, topic: 'number-theory', difficulty: 'easy',
    question: 'What is the remainder when 38 is divided by 7?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2,
    explanation: 'Since 38 = 5 × 7 + 3, the quotient is 5 and the remainder is 3.',
    realWorld: 'Remainders are the basic representatives of congruence classes used in cyclic arithmetic, checksums, and cryptographic computations.',
    hint: 'Subtract the largest multiple of 7 that does not exceed 38.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 10102, topic: 'number-theory', difficulty: 'hard',
    question: 'A modular inverse of $a$ modulo $n$ exists exactly when:',
    options: ['$a<n$', '$a$ is prime', '$n$ is prime', '$\\gcd(a,n)=1$'],
    correctIndex: 3,
    explanation: 'Bézout’s identity gives integers x and y with ax + ny = 1 exactly when gcd(a,n)=1; reducing modulo n then makes x an inverse of a.',
    realWorld: 'Modular inverses appear in RSA key calculations, elliptic-curve arithmetic, coding theory, and algorithms over finite residue rings.',
    hint: 'The condition is the same one that makes Bézout’s identity produce 1.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 10103, topic: 'number-theory', difficulty: 'hard',
    question: 'For an odd prime $p$, Euler’s criterion says a nonzero $a$ is a quadratic residue modulo $p$ when:',
    options: ['$a^{(p-1)/2} \\equiv 1 \\pmod p$', '$a^{p} \\equiv 0 \\pmod p$', '$a^{p-1} \\equiv -1 \\pmod p$', '$a^{(p+1)/2} \\equiv 1 \\pmod p$'],
    correctIndex: 0,
    explanation: 'Euler’s criterion states that $a^{(p-1)/2}$ is congruent to 1 modulo p for quadratic residues and to -1 for quadratic nonresidues.',
    realWorld: 'Quadratic-residuosity tests are useful in computational number theory and underpin constructions such as the Blum Blum Shub pseudorandom generator.',
    hint: 'The exponent is half of p minus 1.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 10104, topic: 'number-theory', difficulty: 'sota',
    question: 'The Green–Tao theorem proves that the prime numbers contain:',
    options: ['Only finitely many arithmetic progressions', 'Arithmetic progressions of every finite length', 'An infinite arithmetic progression of primes', 'Every sufficiently large odd integer as a prime'],
    correctIndex: 1,
    explanation: 'Green and Tao proved that for every positive integer k, there is an arithmetic progression of k prime numbers. The theorem does not claim one infinite progression of primes.',
    realWorld: 'The result showed that a sparse set such as the primes can still contain arbitrarily long additive patterns, connecting analytic number theory with additive combinatorics.',
    hint: 'The progression length can be made arbitrarily large, but remains finite.',
    paper: {
      title: 'The primes contain arbitrarily long arithmetic progressions',
      url: 'https://annals.math.princeton.edu/2008/167-2/p03',
      venue: 'Annals of Mathematics',
      year: 2008,
    },
    reviewedAt: '2026-09-21',
  },
  {
    id: 10105, topic: 'number-theory', difficulty: 'sota',
    question: 'The Maynard–Tao refinement of bounded-gap methods is especially notable for proving that:',
    options: ['Prime gaps eventually equal two', 'Every admissible tuple consists entirely of primes infinitely often', 'Intervals of bounded length can contain arbitrarily many primes infinitely often', 'Every even integer is a difference of consecutive primes'],
    correctIndex: 2,
    explanation: 'Maynard’s multidimensional sieve method shows that, for any fixed m, infinitely many bounded intervals contain at least m primes, with the bound depending on m.',
    realWorld: 'The method strengthened the modern theory of small gaps between primes and made it possible to study clusters of several primes rather than only pairs.',
    hint: 'The advance controls clusters containing any fixed number of primes.',
    paper: {
      title: 'Small gaps between primes',
      url: 'https://annals.math.princeton.edu/2015/181-1/p07',
      venue: 'Annals of Mathematics',
      year: 2015,
    },
    reviewedAt: '2026-09-21',
  },
];
