import type { Question } from '../types';

// ── New topics for existing fields — 3 questions each ────────────────

// ── Electromagnetism (Physics) ──────────────────────────────────
export const electromagnetismQuestions: Question[] = [
  {
    id: 20050, topic: 'electromagnetism', difficulty: 'easy',
    question: 'Maxwell\'s equations collectively relate:',
    options: [
      'Electric and magnetic fields to charges and currents',
      'Fluid velocity fields to pressure and viscosity',
      'Spacetime curvature to mass and momentum',
      'Temperature gradients to heat conductivity',
    ],
    correctIndex: 0,
    explanation: 'Maxwell\'s equations connect electric and magnetic fields with electric charge, electric current, and changing electromagnetic fields.',
    realWorld: 'They underpin antennas, motors, generators, optics, transmission lines, wireless communication, and most electrical engineering.',
    hint: 'The equations unify two field theories that were once studied separately.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20053, topic: 'electromagnetism', difficulty: 'easy',
    question: 'For a positive charge moving through a magnetic field, the magnetic part of the Lorentz force points:',
    options: [
      'Parallel to the magnetic field',
      'Perpendicular to velocity and field',
      'Always opposite to particle velocity',
      'Independent of the particle charge',
    ],
    correctIndex: 1,
    explanation: 'The magnetic force is q times the cross product of velocity and magnetic field, so its direction is perpendicular to both vectors.',
    realWorld: 'This geometry governs charged-particle motion in mass spectrometers, accelerators, plasma devices, and magnetic confinement systems.',
    hint: 'Use the right-hand rule for a cross product.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20054, topic: 'electromagnetism', difficulty: 'easy',
    question: 'Gauss\'s law for electricity says the net electric flux through a closed surface is proportional to:',
    options: [
      'The magnetic field along its boundary',
      'The electric potential at its center',
      'The electric charge enclosed by it',
      'The surface area regardless of fields',
    ],
    correctIndex: 2,
    explanation: 'Gauss\'s law states that total electric flux through a closed surface equals the enclosed charge divided by the vacuum permittivity.',
    realWorld: 'The law makes highly symmetric electric-field problems much easier and is built directly into numerical electromagnetics.',
    hint: 'Only charge inside the closed surface contributes to the net flux.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20051, topic: 'electromagnetism', difficulty: 'hard',
    question: 'Faraday\'s law states that the induced electromotive force around a loop equals:',
    options: [
      'Current times the loop resistance',
      'Charge divided by the capacitance',
      'Magnetic field times path length',
      'Negative time derivative of magnetic flux',
    ],
    correctIndex: 3,
    explanation: 'Faraday\'s law gives the induced electromotive force as the negative time derivative of magnetic flux through the loop; the sign encodes Lenz\'s law.',
    realWorld: 'Generators, transformers, inductive sensors, wireless charging, and induction heating all exploit changing magnetic flux.',
    hint: 'A changing flux drives the induced voltage.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20055, topic: 'electromagnetism', difficulty: 'hard',
    question: 'Why did Maxwell add the displacement-current term to Ampère\'s law?',
    options: [
      'To handle changing electric flux consistently',
      'To remove magnetic fields around wires',
      'To make electric charge nonconserved',
      'To replace Faraday\'s induction law',
    ],
    correctIndex: 0,
    explanation: 'The displacement-current term makes the Ampère-Maxwell law consistent with charge conservation when electric fields change in time, such as between capacitor plates.',
    realWorld: 'This correction is also what lets Maxwell\'s equations support self-propagating electromagnetic waves in vacuum.',
    hint: 'Think about a charging capacitor where conduction current does not cross the dielectric gap.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20056, topic: 'electromagnetism', difficulty: 'hard',
    question: 'The Poynting vector primarily represents:',
    options: [
      'Charge density stored in a conductor',
      'Electromagnetic energy flux and direction',
      'Magnetic flux enclosed by a loop',
      'Electric potential per unit charge',
    ],
    correctIndex: 1,
    explanation: 'The Poynting vector is the cross product of electric and magnetic fields divided by the permeability, and it describes electromagnetic power flow per unit area.',
    realWorld: 'Engineers use it to analyze power carried by waves, transmission lines, antennas, waveguides, and optical systems.',
    hint: 'It points in the direction that electromagnetic energy flows.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 20052, topic: 'electromagnetism', difficulty: 'sota',
    question: 'The Aharonov-Bohm effect shows that a charged particle can acquire a measurable quantum phase from:',
    options: [
      'Only a local electric force on its path',
      'Only a local magnetic force on its path',
      'Electromagnetic potentials where local fields vanish',
      'Gravitational curvature around the apparatus',
    ],
    correctIndex: 2,
    explanation: 'The Aharonov-Bohm effect demonstrates that electromagnetic potentials can affect quantum phase even along paths where the classical electric and magnetic fields vanish.',
    realWorld: 'The effect is a foundational demonstration of gauge potentials in quantum mechanics and is used in mesoscopic interference experiments.',
    hint: 'The particle can respond to a potential even in a field-free region.',
    paper: {
      title: 'Significance of Electromagnetic Potentials in the Quantum Theory',
      url: 'https://journals.aps.org/pr/abstract/10.1103/PhysRev.115.485',
      venue: 'Physical Review',
      year: 1959,
    },
    reviewedAt: '2026-09-20',
  },
  {
    id: 20057, topic: 'electromagnetism', difficulty: 'sota',
    question: 'The superconducting magnetic-flux quantum has the value:',
    options: ['$h/e$', '$2h/e$', '$h/(4e)$', '$h/(2e)$'],
    correctIndex: 3,
    explanation: 'The superconducting flux quantum is $\\Phi_0 = h/(2e)$, reflecting the effective charge 2e associated with paired charge carriers in conventional superconductors.',
    realWorld: 'Flux quantization is central to SQUID magnetometers, Josephson devices, superconducting qubits, and precision electromagnetic metrology.',
    hint: 'The denominator contains the charge of a Cooper pair.',
    sources: [{
      title: 'CODATA recommended values of the fundamental physical constants',
      url: 'https://physics.nist.gov/cuu/Constants/',
      publisher: 'National Institute of Standards and Technology',
    }],
    reviewedAt: '2026-09-20',
    factualAsOf: '2026-09-20',
  },
  {
    id: 20058, topic: 'electromagnetism', difficulty: 'sota',
    question: 'The Casimir force between nearby neutral conductors is associated with:',
    options: [
      'Boundary-dependent quantum fluctuations of the electromagnetic field',
      'Classical electrostatic charge permanently trapped on ideal surfaces',
      'A chemical bond formed when two metallic lattices approach each other',
      'A gravitational interaction enhanced by nanoscale surface curvature',
    ],
    correctIndex: 0,
    explanation: 'The Casimir interaction arises because electromagnetic quantum fluctuations and their allowed modes depend on the boundary conditions imposed by nearby material surfaces.',
    realWorld: 'At micro- and nanoscales the force can affect mechanical sensors, actuators, relays, and experiments probing fluctuation-induced interactions.',
    hint: 'The effect persists for electrically neutral idealized conductors because the vacuum field is quantized.',
    sources: [{
      title: 'Calculating Quantum Vacuum Forces in Nanostructures',
      url: 'https://www.nist.gov/news-events/news/2013/02/calculating-quantum-vacuum-forces-nanostructures',
      publisher: 'National Institute of Standards and Technology',
      year: 2013,
    }],
    reviewedAt: '2026-09-20',
  },
];

// ── Thermodynamics (Physics) ──────────────────────────────────
export const thermodynamicsQuestions: Question[] = [
  {
    id: 20060, topic: 'thermodynamics', difficulty: 'easy',
    question: 'The second law of thermodynamics states that:',
    options: ['Entropy of an isolated system never decreases', 'Energy is always conserved', 'Temperature always increases', 'Pressure equals force per area'],
    correctIndex: 0,
    explanation: 'The second law states $\\Delta S_{\\text{universe}} \\geq 0$ — natural processes increase total entropy, defining the arrow of time.',
    realWorld: 'This is why you can\'t un-scramble an egg or build a perpetual motion machine.',
    hint: 'Think about the direction of spontaneous processes — disorder tends to increase.',
  },
  {
    id: 20061, topic: 'thermodynamics', difficulty: 'hard',
    question: 'The Boltzmann entropy formula is:',
    options: ['$S = k_B \\ln \\Omega$', '$S = k_B T$', '$S = \\Delta H / T$', '$S = nR \\ln V$'],
    correctIndex: 0,
    explanation: 'Boltzmann\'s formula $S = k_B \\ln \\Omega$ connects macroscopic entropy to the number of microstates $\\Omega$, bridging thermodynamics and statistical mechanics.',
    realWorld: 'This equation is engraved on Boltzmann\'s tombstone in Vienna.',
    hint: 'The number of microstates $\\Omega$ counts how many microscopic arrangements give the same macrostate.',
  },
  {
    id: 20062, topic: 'thermodynamics', difficulty: 'sota',
    question: 'The Jarzynski equality $\\langle e^{-\\beta W} \\rangle = e^{-\\beta \\Delta F}$ relates:',
    options: ['Non-equilibrium work measurements to equilibrium free energy differences', 'Temperature to pressure', 'Entropy to enthalpy', 'Volume to internal energy'],
    correctIndex: 0,
    explanation: 'Jarzynski\'s remarkable equality (1997) shows that free energy differences can be extracted from an ensemble of non-equilibrium work measurements, extending the second law.',
    realWorld: 'Used in single-molecule experiments (optical tweezers) to measure free energies of protein folding.',
    hint: 'It connects irreversible processes to equilibrium thermodynamics — a profound result.',
  },
];

// ── Number Theory (Math) ──────────────────────────────────────
export const numberTheoryQuestions: Question[] = [
  {
    id: 10050, topic: 'number-theory', difficulty: 'easy',
    question: 'The Fundamental Theorem of Arithmetic states that every integer greater than 1:',
    options: [
      'Has a prime factorization unique up to order',
      'Can be expressed as a sum of two primes',
      'Has exactly two positive integer divisors',
      'Can be written as a power of two',
    ],
    correctIndex: 0,
    explanation: 'Every integer greater than 1 factors into prime numbers, and that prime factorization is unique apart from the order of the factors.',
    realWorld: 'Unique factorization supports divisibility algorithms and underlies many constructions in computational number theory and cryptography.',
    hint: 'Think about breaking a positive integer into prime building blocks.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10053, topic: 'number-theory', difficulty: 'easy',
    question: 'The Euclidean algorithm is used primarily to compute:',
    options: [
      'The number of primes below a limit',
      'The greatest common divisor of two integers',
      'The decimal expansion of an irrational number',
      'The number of divisors of a prime power',
    ],
    correctIndex: 1,
    explanation: 'The Euclidean algorithm repeatedly replaces a pair of integers by a smaller remainder pair until the greatest common divisor is exposed.',
    realWorld: 'The algorithm is fundamental to fraction reduction, modular inverses, Diophantine equations, and public-key cryptography.',
    hint: 'Repeated division with remainder reveals the largest shared divisor.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10054, topic: 'number-theory', difficulty: 'easy',
    question: 'The congruence $a \\equiv b \\pmod n$ means that:',
    options: [
      '$a$ and $b$ must both be prime numbers',
      '$a+b$ is exactly equal to the modulus $n$',
      '$n$ divides the difference $a-b$',
      '$a/b$ must be an integer multiple of $n$',
    ],
    correctIndex: 2,
    explanation: 'Two integers are congruent modulo n when their difference is divisible by n, which is equivalent to having the same remainder after division by n.',
    realWorld: 'Modular arithmetic models clocks, cyclic counters, checksums, cryptographic groups, and periodic computational structures.',
    hint: 'Subtract the two numbers and ask whether the modulus divides the result.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10051, topic: 'number-theory', difficulty: 'hard',
    question: 'If $p$ is prime and $p$ does not divide $a$, Fermat\'s Little Theorem gives:',
    options: [
      '$a^p \\equiv 0 \\pmod p$',
      '$a^{p+1} \\equiv a \\pmod p$',
      '$a^2 \\equiv -1 \\pmod p$',
      '$a^{p-1} \\equiv 1 \\pmod p$',
    ],
    correctIndex: 3,
    explanation: 'Fermat\'s Little Theorem states that $a^{p-1}$ is congruent to 1 modulo p whenever p is prime and a is not divisible by p.',
    realWorld: 'The theorem is used in modular exponentiation, primality-testing ideas, and reasoning about finite multiplicative groups.',
    hint: 'The exponent is one less than the prime modulus.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10055, topic: 'number-theory', difficulty: 'hard',
    question: 'For pairwise coprime moduli, the Chinese Remainder Theorem guarantees:',
    options: [
      'A simultaneous solution unique modulo the product',
      'A prime solution for every residue system',
      'A solution only when all residues are equal',
      'Exactly one integer solution without periodicity',
    ],
    correctIndex: 0,
    explanation: 'For pairwise coprime moduli, a system of congruences has a solution, and all solutions are congruent modulo the product of those moduli.',
    realWorld: 'CRT methods accelerate large-integer arithmetic and appear in cryptographic implementations, coding, and residue-number systems.',
    hint: 'Separate congruence conditions can be combined into one repeating solution class.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10056, topic: 'number-theory', difficulty: 'hard',
    question: 'Euler\'s theorem says that when $\\gcd(a,n)=1$:',
    options: [
      '$a^n \\equiv 0 \\pmod n$',
      '$a^{\\varphi(n)} \\equiv 1 \\pmod n$',
      '$a^{n-1} \\equiv n \\pmod a$',
      '$a^2 \\equiv -1 \\pmod n$',
    ],
    correctIndex: 1,
    explanation: 'Euler\'s theorem generalizes Fermat\'s Little Theorem: raising a number coprime to n to the Euler-totient exponent gives 1 modulo n.',
    realWorld: 'The theorem explains important modular exponent cycles and is part of the elementary number-theoretic foundation behind RSA.',
    hint: 'The exponent counts residue classes relatively prime to the modulus.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10052, topic: 'number-theory', difficulty: 'sota',
    question: 'The Riemann Hypothesis asserts that:',
    options: [
      'Every zero of the zeta function is a real number',
      'Every trivial zero occurs at a positive even integer',
      'Every nontrivial zeta zero has real part one-half',
      'Every zeta zero lies inside the complex unit circle',
    ],
    correctIndex: 2,
    explanation: 'The Riemann Hypothesis states that every nontrivial zero of the Riemann zeta function lies on the critical line with real part one-half.',
    realWorld: 'A proof would sharpen understanding of fluctuations in the distribution of prime numbers and resolve one of the Clay Millennium Prize Problems.',
    hint: 'The conjectured zeros lie on a vertical line halfway across the critical strip.',
    sources: [{
      title: 'Riemann Hypothesis',
      url: 'https://www.claymath.org/millennium/Riemann-Hypothesis/',
      publisher: 'Clay Mathematics Institute',
    }],
    reviewedAt: '2026-09-20',
    factualAsOf: '2026-09-20',
  },
  {
    id: 10057, topic: 'number-theory', difficulty: 'sota',
    question: 'A central theorem in Wiles\'s proof of Fermat\'s Last Theorem established that:',
    options: [
      'Every integer factors uniquely in every number ring',
      'Every prime number is a sum of two integer squares',
      'Every elliptic curve has only finitely many rational points',
      'Every semistable elliptic curve over the rationals is modular',
    ],
    correctIndex: 3,
    explanation: 'Wiles proved the modularity of semistable elliptic curves over the rationals, which—through earlier work connecting a hypothetical Fermat counterexample to such a curve—implies Fermat\'s Last Theorem.',
    realWorld: 'The proof linked elliptic curves and modular forms, reshaping modern number theory far beyond the original Diophantine equation.',
    hint: 'The bridge joins elliptic curves to modular forms.',
    paper: {
      title: 'Modular elliptic curves and Fermat’s Last Theorem',
      url: 'https://annals.math.princeton.edu/1995/141-3/p01',
      venue: 'Annals of Mathematics',
      year: 1995,
    },
    reviewedAt: '2026-09-20',
  },
  {
    id: 10058, topic: 'number-theory', difficulty: 'sota',
    question: 'The bounded-gaps breakthrough on prime numbers proves that:',
    options: [
      'Infinitely many prime pairs have gaps below some fixed finite bound',
      'Every pair of consecutive primes differs by exactly two',
      'Prime gaps eventually become smaller than every fixed integer',
      'There are only finitely many primes separated by an even distance',
    ],
    correctIndex: 0,
    explanation: 'Bounded-gaps results prove unconditionally that there is some fixed finite bound such that infinitely many distinct pairs of primes occur within that distance.',
    realWorld: 'The theorem transformed research on prime gaps and created new methods for studying how closely prime numbers can recur.',
    hint: 'The result gives a finite recurring upper bound without proving the twin-prime conjecture.',
    paper: {
      title: 'Bounded gaps between primes',
      url: 'https://annals.math.princeton.edu/2014/179-3/p07',
      venue: 'Annals of Mathematics',
      year: 2014,
    },
    reviewedAt: '2026-09-20',
  },
];

// ── Real Analysis (Math) ──────────────────────────────────────
export const realAnalysisQuestions: Question[] = [
  {
    id: 10060, topic: 'real-analysis', difficulty: 'easy',
    question: 'A sequence $\\{a_n\\}$ converges to $L$ when, for every $\\epsilon>0$, eventually:',
    options: [
      '$|a_n-L|<\\epsilon$ and remains so',
      '$a_n=L$ exactly for every later term',
      '$|a_n|<\\epsilon$ regardless of the limit',
      '$a_n>L$ for every sufficiently large index',
    ],
    correctIndex: 0,
    explanation: 'The epsilon-N definition requires that for every positive tolerance there is an index after which every term remains within that tolerance of the limit.',
    realWorld: 'This definition turns the intuitive idea of approaching a value into a precise tool used throughout calculus and analysis.',
    hint: 'The sequence must eventually stay inside every requested tolerance around the limit.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10063, topic: 'real-analysis', difficulty: 'easy',
    question: 'A monotone increasing real sequence that is bounded above must:',
    options: [
      'Eventually become exactly constant',
      'Converge to a finite real limit',
      'Alternate between two limit points',
      'Diverge to positive infinity',
    ],
    correctIndex: 1,
    explanation: 'The monotone convergence theorem for sequences says that an increasing sequence bounded above converges, in fact to the supremum of its set of values.',
    realWorld: 'Monotone bounded approximations are a standard way to prove existence of limits in numerical methods and constructive arguments.',
    hint: 'Increasing terms cannot escape upward, so completeness supplies a limit.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10064, topic: 'real-analysis', difficulty: 'easy',
    question: 'The Extreme Value Theorem says a continuous real function on a compact interval:',
    options: [
      'Must be differentiable at every point',
      'Must have a unique zero in the interval',
      'Attains both a maximum and a minimum',
      'Has a derivative that is bounded everywhere',
    ],
    correctIndex: 2,
    explanation: 'A continuous function on a compact interval attains its supremum and infimum, so actual maximum and minimum points exist.',
    realWorld: 'This theorem supports existence arguments in optimization, engineering design, economics, and numerical search on bounded domains.',
    hint: 'Continuity plus compactness turns upper and lower bounds into achieved values.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10061, topic: 'real-analysis', difficulty: 'hard',
    question: 'The Bolzano-Weierstrass theorem states that every bounded sequence in $\\mathbb{R}^n$:',
    options: [
      'Converges to a unique point',
      'Is eventually monotone',
      'Attains a maximum term',
      'Contains a convergent subsequence',
    ],
    correctIndex: 3,
    explanation: 'Bolzano-Weierstrass guarantees that every bounded sequence in finite-dimensional Euclidean space contains at least one convergent subsequence.',
    realWorld: 'The result is a key compactness tool in existence proofs for optimization, differential equations, and variational problems.',
    hint: 'The whole sequence may oscillate, but a convergent part can be extracted.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10065, topic: 'real-analysis', difficulty: 'hard',
    question: 'The Heine-Borel theorem characterizes compact subsets of $\\mathbb{R}^n$ as exactly those that are:',
    options: [
      'Closed and bounded',
      'Open and connected',
      'Dense and countable',
      'Convex and differentiable',
    ],
    correctIndex: 0,
    explanation: 'In Euclidean space, Heine-Borel says that a subset is compact if and only if it is both closed and bounded.',
    realWorld: 'Compactness lets analysts pass from local information to global conclusions and extract convergent subsequences from bounded families.',
    hint: 'Two familiar geometric properties combine to characterize compactness in finite-dimensional Euclidean space.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10066, topic: 'real-analysis', difficulty: 'hard',
    question: 'If continuous functions $f_n$ converge uniformly to $f$ on a set, then $f$ is:',
    options: [
      'Necessarily differentiable everywhere',
      'Continuous on that set',
      'Necessarily a polynomial',
      'Constant on every component',
    ],
    correctIndex: 1,
    explanation: 'Uniform convergence controls the approximation simultaneously across the domain strongly enough that the uniform limit of continuous functions remains continuous.',
    realWorld: 'The theorem is essential when approximating functions numerically or representing them by series while preserving continuity.',
    hint: 'Uniform convergence preserves a basic topological property that pointwise convergence alone need not preserve.',
    reviewedAt: '2026-09-20',
  },
  {
    id: 10062, topic: 'real-analysis', difficulty: 'sota',
    question: 'A standard form of the Dominated Convergence Theorem requires $f_n\\to f$ almost everywhere and:',
    options: [
      'Every $f_n$ to be continuous on a compact set',
      'The sequence to converge uniformly everywhere',
      '$|f_n|$ to be bounded by one integrable function',
      'The integrals of all $f_n$ to equal one another',
    ],
    correctIndex: 2,
    explanation: 'If the measurable functions converge almost everywhere and are dominated in absolute value by a single integrable function, their integrals converge to the integral of the limit.',
    realWorld: 'Dominated convergence is fundamental in probability, PDEs, statistical mechanics, and any analysis that interchanges limits with integration.',
    hint: 'One integrable safety-net function controls every member of the sequence.',
    sources: [{
      title: 'Convergence, types of',
      url: 'https://encyclopediaofmath.org/wiki/Convergence%2C_types_of',
      publisher: 'Encyclopedia of Mathematics',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 10067, topic: 'real-analysis', difficulty: 'sota',
    question: 'Rademacher\'s theorem says that a Lipschitz map between Euclidean spaces is:',
    options: [
      'Analytic at every point of its domain',
      'Uniformly convex on every bounded subset',
      'Twice differentiable except at finitely many points',
      'Differentiable almost everywhere',
    ],
    correctIndex: 3,
    explanation: 'Rademacher\'s theorem states that Lipschitz maps on Euclidean domains are differentiable almost everywhere with respect to Lebesgue measure.',
    realWorld: 'The result is foundational in geometric measure theory, nonsmooth optimization, PDEs, and the analysis of Lipschitz mappings.',
    hint: 'Nondifferentiable points may exist, but they occupy a measure-zero set.',
    sources: [{
      title: 'Rademacher theorem',
      url: 'https://encyclopediaofmath.org/wiki/Rademacher_theorem',
      publisher: 'Encyclopedia of Mathematics',
    }],
    reviewedAt: '2026-09-20',
  },
  {
    id: 10068, topic: 'real-analysis', difficulty: 'sota',
    question: 'Carleson\'s theorem on Fourier series states that for every function in $L^2(0,2\\pi)$, its Fourier series:',
    options: [
      'Converges to the function almost everywhere',
      'Converges uniformly at every point',
      'Has only finitely many nonzero coefficients',
      'Is absolutely convergent for every argument',
    ],
    correctIndex: 0,
    explanation: 'Carleson proved that the trigonometric Fourier series of every square-integrable function converges to that function almost everywhere.',
    realWorld: 'The theorem resolved a major convergence problem and shaped modern harmonic analysis and the study of oscillatory operators.',
    hint: 'The conclusion is pointwise almost-everywhere convergence, not uniform or absolute convergence.',
    sources: [{
      title: 'Carleson theorem',
      url: 'https://encyclopediaofmath.org/wiki/Carleson_theorem',
      publisher: 'Encyclopedia of Mathematics',
    }],
    reviewedAt: '2026-09-20',
  },
];

// ── Risk Management (Quant) ──────────────────────────────────
export const riskManagementQuestions: Question[] = [
  {
    id: 30050, topic: 'risk-management', difficulty: 'easy',
    question: 'Value at Risk (VaR) at the 95% confidence level estimates:',
    options: ["A model loss quantile","The average daily return","The total portfolio value","The maximum possible loss"],
    correctIndex: 0,
    explanation: 'VaR is a quantile-based risk measure: "We are 95% confident the loss will not exceed $X over the next day."',
    realWorld: 'Banks are required by Basel III regulations to report VaR daily for capital adequacy.',
    hint: 'It answers: "What is the worst loss in the best 95% of scenarios?"',
  },
  {
    id: 30051, topic: 'risk-management', difficulty: 'hard',
    question: 'Expected Shortfall (CVaR) differs from VaR by:',
    options: ["Average loss beyond VaR","Only considering gains","Ignoring tail risk","Using standard deviation instead of quantiles"],
    correctIndex: 0,
    explanation: 'ES (or CVaR) = $E[L | L > \\text{VaR}_\\alpha]$. Unlike VaR, it captures the severity of tail losses and is a coherent risk measure (satisfies subadditivity).',
    realWorld: 'Basel III shifted from VaR to Expected Shortfall as the primary market risk measure in 2019.',
    hint: 'VaR tells you the threshold; ES tells you what happens when things get worse than that.',
  },
  {
    id: 30052, topic: 'risk-management', difficulty: 'sota',
    question: 'The Fundamental Review of the Trading Book (FRTB) replaced the standardized approach with:',
    options: ["Sensitivity-based approach","Simple historical VaR","Monte Carlo simulation only","Parametric VaR with normal distribution"],
    correctIndex: 0,
    explanation: 'FRTB\'s SBA computes capital charges using portfolio sensitivities to risk factors (delta, vega, curvature) with prescribed correlation scenarios, replacing the simplistic standardized method.',
    realWorld: 'FRTB modernizes market-risk capital with a risk-sensitive standardized approach and an internal-models approach centered on stressed Expected Shortfall.',
    hint: 'It decomposes risk into sensitivities (Greeks) rather than relying on a single VaR number.',
  
    sources: [{"title":"Minimum capital requirements for market risk","url":"https://www.bis.org/publications/201901-standards-minimum-capital-requirements-market-risk","publisher":"Basel Committee on Banking Supervision","year":2019}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },

  // ── Risk Management foundation expansion ──────────────────
  {
    id: 30053, topic: "risk-management", difficulty: "easy",
    question: "Diversification reduces risk when positions are:",
    options: ["Identical","Imperfectly correlated","Guaranteed positive","Fully leveraged"],
    correctIndex: 1,
    explanation: "Combining imperfectly correlated exposures can lower aggregate variance relative to concentrated stand-alone risks.",
    realWorld: "Diversification can weaken in stress when correlations rise, so it does not replace scenario analysis.",
    hint: "Imperfect co-movement is the key.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 30054, topic: "risk-management", difficulty: "easy",
    question: "Financial leverage tends to:",
    options: ["Lower all portfolio risk","Remove possible drawdowns","Amplify equity moves","Guarantee positive returns"],
    correctIndex: 2,
    explanation: "With debt fixed over a horizon, changes in a larger asset base are absorbed by a smaller residual equity base.",
    realWorld: "Leverage is a core amplifier of market, margin, liquidity, and solvency risk.",
    hint: "A smaller equity cushion absorbs asset moves.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 30055, topic: "risk-management", difficulty: "hard",
    question: "VaR backtesting focuses on:",
    options: ["Average portfolio returns","Factor-model loadings","Accounting book value","Threshold exceptions"],
    correctIndex: 3,
    explanation: "Backtesting compares realized losses with forecast quantile thresholds and examines how often exceptions occur.",
    realWorld: "Model governance uses backtests alongside stress tests and qualitative review.",
    hint: "Count losses that breach predicted thresholds.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 30056, topic: "risk-management", difficulty: "hard",
    question: "Reverse stress testing begins with:",
    options: ["Normal market conditions","A failure outcome","Recent realized volatility","A benchmark index"],
    correctIndex: 1,
    explanation: "Reverse stress testing specifies an unacceptable outcome and works backward to identify plausible shock combinations that could cause it.",
    realWorld: "It can reveal vulnerabilities not covered by conventional scenario libraries.",
    hint: "Start with failure, then search for causes.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 30057, topic: "risk-management", difficulty: "sota",
    question: "Under FRTB, a non-modellable risk factor lacks:",
    options: ["Sufficient regulatory capital","A liquid secondary market","Enough real-price data","A long enough duration"],
    correctIndex: 2,
    explanation: "FRTB distinguishes modellable and non-modellable risk factors using prescribed evidence from real price observations.",
    realWorld: "Non-modellable risk factors receive separate stress-scenario capital treatment.",
    hint: "The issue is sufficient observable real-price evidence.",
    sources: [{"title":"Minimum capital requirements for market risk","url":"https://www.bis.org/publications/201901-standards-minimum-capital-requirements-market-risk","publisher":"Basel Committee on Banking Supervision","year":2019}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 30058, topic: "risk-management", difficulty: "sota",
    question: "FRTB liquidity horizons recognize that positions:",
    options: ["Can exit immediately","Use one fixed horizon","Have no liquidity risk","Need different exit times"],
    correctIndex: 3,
    explanation: "The framework uses liquidity horizons so risk aggregation reflects differences in how quickly exposures can be closed or hedged under stress.",
    realWorld: "Less liquid risk factors can require longer horizons and more conservative tail-risk aggregation.",
    hint: "Not every position unwinds on the same timetable.",
    sources: [{"title":"Minimum capital requirements for market risk","url":"https://www.bis.org/publications/201901-standards-minimum-capital-requirements-market-risk","publisher":"Basel Committee on Banking Supervision","year":2019}],
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
];
