import type { Question } from '../types';

export const relativityQuestions: Question[] = [
  {
    id: 3301,
    topic: 'relativity',
    difficulty: 'easy',
    question: 'Einstein\'s famous equation $E = mc^2$ states that:',
    options: ['Energy equals mass times the speed of light', 'Energy and mass are equivalent, related by $c^2$', 'Energy is always conserved', 'Mass cannot be converted to energy'],
    correctIndex: 1,
    explanation: 'Mass-energy equivalence shows that a small amount of mass corresponds to an enormous amount of energy since $c^2 \\approx 9 \\times 10^{16}$ m²/s².',
    realWorld: 'This principle powers nuclear reactors, the Sun, and explains why atomic bombs release such devastating energy.',
    hint: '$c$ is the speed of light — a very large number.',
  },
  {
    id: 3302,
    topic: 'relativity',
    difficulty: 'easy',
    question: 'Time dilation in special relativity means:',
    options: ['Time stops for all observers', 'A moving clock ticks slower relative to a stationary observer', 'Time runs faster in motion', 'Time is the same for all observers'],
    correctIndex: 1,
    explanation: 'The Lorentz factor $\\gamma = 1/\\sqrt{1 - v^2/c^2}$ causes a moving clock to tick slower by a factor of $\\gamma$.',
    realWorld: 'GPS satellites must account for time dilation — without corrections, positions would drift by ~10 km/day.',
    hint: 'Moving clocks run slow.',
  },
  {
    id: 3303,
    topic: 'relativity',
    difficulty: 'easy',
    question: 'The speed of light in vacuum is:',
    options: ['Variable depending on the source', 'The same for all inertial observers ($c \\approx 3 \\times 10^8$ m/s)', 'Infinite', 'Depends on the observer\'s speed'],
    correctIndex: 1,
    explanation: 'The constancy of the speed of light for all inertial observers is the second postulate of special relativity.',
    realWorld: 'This counterintuitive fact has been confirmed to extraordinary precision by interferometry experiments.',
    hint: 'It\'s one of Einstein\'s two foundational postulates.',
  },
  {
    id: 3304,
    topic: 'relativity',
    difficulty: 'hard',
    question: 'The spacetime interval $ds^2 = -c^2dt^2 + dx^2 + dy^2 + dz^2$ is significant because:',
    options: ['It changes between reference frames', 'It is invariant under Lorentz transformations', 'It equals zero everywhere', 'It only applies in curved spacetime'],
    correctIndex: 1,
    explanation: 'The spacetime interval is a Lorentz scalar — all inertial observers compute the same value, making it the fundamental geometric quantity in relativity.',
    realWorld: 'This invariance is the mathematical foundation of all relativistic physics, from particle physics to GPS.',
    hint: 'Different observers disagree on space and time separately, but agree on this combination.',
  },
  {
    id: 3305,
    topic: 'relativity',
    difficulty: 'hard',
    question: 'In general relativity, gravity is described as:',
    options: ['A force between masses (Newtonian)', 'Curvature of spacetime caused by mass-energy', 'An electromagnetic phenomenon', 'A quantum field effect only'],
    correctIndex: 1,
    explanation: 'Einstein\'s field equations $G_{\\mu\\nu} = 8\\pi G T_{\\mu\\nu}/c^4$ relate spacetime curvature (left side) to mass-energy content (right side).',
    realWorld: 'General relativity predicts black holes, gravitational waves (detected by LIGO 2015), and the Big Bang expansion.',
    hint: 'Mass tells spacetime how to curve; spacetime tells matter how to move.',
  },
  {
    id: 3306,
    topic: 'relativity',
    difficulty: 'hard',
    question: 'Gravitational lensing occurs because:',
    options: ['Gravity refracts light like a glass lens', 'Massive objects curve spacetime, bending the path of light', 'Light has mass and is attracted gravitationally', 'The speed of light changes near massive objects'],
    correctIndex: 1,
    explanation: 'Light follows geodesics in curved spacetime. A massive foreground object bends spacetime, deflecting light from background sources.',
    realWorld: 'Gravitational lensing maps dark matter distribution and has revealed some of the most distant galaxies ever observed.',
    hint: 'Light follows the curved geometry of spacetime.',
  },
  {
    id: 3307,
    topic: 'relativity',
    difficulty: 'sota',
    question: 'The Penrose singularity theorem (1965) proves that:',
    options: ['Black holes cannot exist', 'Singularities inevitably form under gravitational collapse given a trapped surface', 'Spacetime is always flat', 'General relativity is wrong'],
    correctIndex: 1,
    explanation: 'Penrose showed that once a trapped surface forms, general relativity guarantees geodesic incompleteness — a singularity must exist. This earned the 2020 Nobel Prize.',
    realWorld: 'This theorem established that black holes are a robust prediction of GR, not just a mathematical curiosity.',
    hint: 'It uses topology rather than exact solutions to prove singularity formation.',
  },
  {
    id: 3308,
    topic: 'relativity',
    difficulty: 'sota',
    question: 'The Event Horizon Telescope imaged M87* by using:',
    options: ['A single giant telescope', 'Very Long Baseline Interferometry (VLBI) creating an Earth-sized virtual dish', 'Gravitational wave detection', 'Neutrino imaging'],
    correctIndex: 1,
    explanation: 'EHT synchronized radio telescopes worldwide to achieve angular resolution of ~20 microarcseconds — enough to read a newspaper in New York from Paris.',
    realWorld: 'The 2019 M87* image and 2022 Sgr A* image confirmed GR predictions about black hole shadows.',
    hint: 'Many telescopes around the world combined as one.',
  },
  {
    id: 3309,
    topic: 'relativity',
    difficulty: 'sota',
    question: 'Loop Quantum Gravity proposes that spacetime at the Planck scale is:',
    options: ['Continuous and smooth', 'Discrete — composed of quantized loops (spin networks)', 'Non-existent', 'Purely classical'],
    correctIndex: 1,
    explanation: 'LQG quantizes spacetime itself, predicting a minimum area ($\\sim l_P^2$) and volume, replacing the classical continuum with spin network states.',
    realWorld: 'If correct, LQG would resolve the Big Bang singularity (replacing it with a "Big Bounce") and black hole information paradox.',
    hint: 'Space itself comes in discrete chunks at the smallest scales.',
  },
];
