import type { Question } from '../types';

export const frmQuestions: Question[] = [
  {
    id: 84000,
    topic: 'frm',
    difficulty: 'easy',
    question: 'Value at Risk (VaR) at the 99% confidence level over one day represents:',
    options: [
      'The maximum loss not exceeded with 99% probability over a one-day horizon',
      'The expected average loss over one day',
      'The maximum possible loss under any scenario',
      'The standard deviation of daily returns',
    ],
    correctIndex: 0,
    explanation: 'VaR is a quantile measure: P(Loss > VaR) = 1%. It does NOT tell you how bad losses can be beyond VaR.',
    realWorld: 'Basel III requires banks to compute 10-day 99% VaR for market risk capital charges.',
    hint: 'It\'s a threshold — losses exceed this level only 1% of the time.',
  },
  {
    id: 84001,
    topic: 'frm',
    difficulty: 'easy',
    question: 'Credit risk is best described as the risk that:',
    options: [
      'A counterparty fails to meet its contractual obligations (default)',
      'Market prices move against your position',
      'The central bank changes interest rates',
      'A natural disaster destroys physical assets',
    ],
    correctIndex: 0,
    explanation: 'Credit risk encompasses default risk, downgrade risk, and spread risk — all related to the counterparty\'s creditworthiness.',
    realWorld: 'The 2008 financial crisis was fundamentally a credit risk event, with cascading defaults in mortgage-backed securities.',
    hint: 'It\'s about the other party not paying what they owe.',
  },
  {
    id: 84002,
    topic: 'frm',
    difficulty: 'hard',
    question: 'Expected Shortfall (ES) is preferred over VaR as a risk measure because ES:',
    options: [
      'Is coherent (subadditive) and captures the expected loss in the tail beyond VaR',
      'Is always smaller than VaR',
      'Ignores extreme losses',
      'Does not require any distributional assumptions',
    ],
    correctIndex: 0,
    explanation: 'ES = $E[L | L > \\text{VaR}]$. It satisfies subadditivity (ES of portfolio ≤ sum of ES of components), unlike VaR.',
    realWorld: 'Basel III\'s Fundamental Review of the Trading Book (FRTB) replaced VaR with ES for market risk capital.',
    hint: 'ES asks: "When we do exceed VaR, how bad is it on average?"',
  },
  {
    id: 84003,
    topic: 'frm',
    difficulty: 'hard',
    question: 'The Merton model values a firm\'s equity as:',
    options: [
      'A call option on the firm\'s assets with a strike price equal to the face value of debt',
      'The book value of assets minus liabilities',
      'The present value of future dividends',
      'A put option on the firm\'s stock price',
    ],
    correctIndex: 0,
    explanation: 'In Merton\'s structural model, equity = $C(V, D, T, \\sigma_V, r)$ where V = asset value, D = debt face value. Equity holders have the residual claim.',
    realWorld: 'Moody\'s KMV model, based on Merton, estimates "distance to default" for credit risk assessment of publicly traded firms.',
    hint: 'Equity holders get what\'s left after paying debt — like a call option payoff.',
  },
  {
    id: 84004,
    topic: 'frm',
    difficulty: 'sota',
    question: 'The Basel III leverage ratio requires banks to maintain:',
    options: [
      'Tier 1 capital of at least 3% of total exposure (on- and off-balance sheet) without risk-weighting',
      'Total capital of at least 8% of risk-weighted assets',
      'Zero leverage at all times',
      'A fixed ratio of deposits to loans',
    ],
    correctIndex: 0,
    explanation: 'The leverage ratio is a non-risk-based backstop: Tier 1 Capital / Total Exposure ≥ 3%. G-SIBs face a higher buffer. It prevents gaming of risk weights.',
    realWorld: 'The leverage ratio was introduced because banks had manipulated risk-weighted asset calculations pre-2008.',
    hint: 'It\'s a simple, non-risk-weighted measure to complement the risk-based capital ratio.',
  },
];
