import type { Question } from '../types';

export const abstractAlgebraQuestions: Question[] = [
  {
    id: 3101,
    topic: 'abstract-algebra',
    difficulty: 'easy',
    question: 'A group $(G, *)$ must satisfy all of the following EXCEPT:',
    options: ['Closure', 'Commutativity', 'Associativity', 'Existence of an identity element'],
    correctIndex: 1,
    explanation: 'A group requires closure, associativity, identity, and inverses. Commutativity is only required for abelian groups.',
    realWorld: 'Group theory underpins symmetry analysis in physics, chemistry (molecular orbitals), and cryptography.',
    hint: 'Not all groups have $a * b = b * a$.',
  },
  {
    id: 3102,
    topic: 'abstract-algebra',
    difficulty: 'easy',
    question: 'The order of a finite group is:',
    options: ['The largest element', 'The number of elements in the group', 'The number of subgroups', 'The rank of the group'],
    correctIndex: 1,
    explanation: 'The order $|G|$ is simply the cardinality (number of elements) of the group.',
    realWorld: 'Lagrange\'s theorem says subgroup orders must divide the group order — fundamental in number theory.',
    hint: 'How many elements does the set have?',
  },
  {
    id: 3103,
    topic: 'abstract-algebra',
    difficulty: 'easy',
    question: 'A ring differs from a group by having:',
    options: ['Only one operation', 'Two operations (addition and multiplication)', 'No identity element', 'Infinite order only'],
    correctIndex: 1,
    explanation: 'A ring $(R, +, \\cdot)$ has addition (forming an abelian group) and multiplication (associative with distribution over addition).',
    realWorld: 'Polynomial rings are the foundation of error-correcting codes (Reed-Solomon) used in QR codes and CDs.',
    hint: 'Think integers: you can add AND multiply.',
  },
  {
    id: 3104,
    topic: 'abstract-algebra',
    difficulty: 'hard',
    question: 'Lagrange\'s theorem states that for a finite group $G$ and subgroup $H$:',
    options: ['$|H|$ divides $|G|$', '$|G|$ divides $|H|$', '$|H| = |G|$', '$|H| + |G|$ is prime'],
    correctIndex: 0,
    explanation: 'The cosets of $H$ partition $G$ into $[G:H]$ equal-sized pieces, so $|G| = |H| \\cdot [G:H]$.',
    realWorld: 'This implies that in a group of order 12, subgroups can only have orders 1, 2, 3, 4, 6, or 12.',
    hint: 'The subgroup order divides evenly into the group order.',
  },
  {
    id: 3105,
    topic: 'abstract-algebra',
    difficulty: 'hard',
    question: 'An ideal $I$ of a ring $R$ is used to construct:',
    options: ['A vector space', 'A quotient ring $R/I$', 'A topological space', 'A Hilbert space'],
    correctIndex: 1,
    explanation: 'Ideals are the ring-theoretic analogue of normal subgroups. The quotient $R/I$ consists of cosets $r + I$ with well-defined ring operations.',
    realWorld: 'Quotient rings like $\\mathbb{Z}/n\\mathbb{Z}$ underpin modular arithmetic in cryptography (RSA).',
    hint: 'Like normal subgroups allow quotient groups, ideals allow quotient rings.',
  },
  {
    id: 3106,
    topic: 'abstract-algebra',
    difficulty: 'hard',
    question: 'Galois theory connects field extensions to:',
    options: ['Topological spaces', 'Group theory (automorphism groups)', 'Probability distributions', 'Differential equations only'],
    correctIndex: 1,
    explanation: 'Galois theory establishes a correspondence between intermediate field extensions and subgroups of the Galois group of automorphisms.',
    realWorld: 'Galois theory proves the impossibility of solving the general quintic by radicals.',
    hint: 'Named after Évariste Galois, who died in a duel at age 20.',
  },
  {
    id: 3107,
    topic: 'abstract-algebra',
    difficulty: 'sota',
    question: 'According to the classification of finite simple groups, every finite simple group belongs to which list?',
    options: ['Only abelian groups', 'Cyclic groups of prime order, alternating groups ($A_n$, $n \\geq 5$), groups of Lie type, or one of 26 sporadic groups', 'All subgroups of symmetric groups', 'Only groups isomorphic to $\\mathbb{Z}/p\\mathbb{Z}$'],
    correctIndex: 1,
    explanation: 'The classification theorem places every finite simple group into these families: cyclic groups of prime order, alternating groups $A_n$ for $n \\geq 5$, groups of Lie type, and the 26 sporadic groups. Cayley\'s theorem says every finite group embeds in some symmetric group, so that fact alone is not the classification.',
    realWorld: 'The largest sporadic group, the Monster, has surprising connections to string theory (Monstrous Moonshine).',
    hint: 'The classification has three infinite families plus 26 sporadic exceptions.',
  },
  {
    id: 3108,
    topic: 'abstract-algebra',
    difficulty: 'sota',
    question: 'Homomorphic encryption relies on ring homomorphisms to:',
    options: ['Decrypt data faster', 'Perform computations on encrypted data without decrypting', 'Generate random keys', 'Compress data'],
    correctIndex: 1,
    explanation: 'If $\\phi$ is a ring homomorphism, then $\\phi(a + b) = \\phi(a) + \\phi(b)$ and $\\phi(ab) = \\phi(a)\\phi(b)$, enabling computation on ciphertexts.',
    realWorld: 'Fully homomorphic encryption (FHE) enables private cloud computing and is being adopted by healthcare and finance.',
    hint: 'The algebraic structure is preserved through encryption.',
  },
  {
    id: 3109,
    topic: 'abstract-algebra',
    difficulty: 'sota',
    question: 'In the Langlands program, the "functoriality conjecture" relates:',
    options: ['Differential equations to topology', 'Automorphic representations of different groups via L-functions', 'Probability distributions to algebraic varieties', 'Finite groups to infinite groups'],
    correctIndex: 1,
    explanation: 'Functoriality predicts that automorphic representations transfer between reductive groups, unified by their L-functions. It is a central organizing principle of modern number theory.',
    realWorld: 'Progress on Langlands (e.g., proof of Fermat\'s Last Theorem) connects seemingly unrelated areas of mathematics.',
    hint: 'It\'s sometimes called a "grand unified theory" of mathematics.',
  },
];
