import { writeFile } from 'node:fs/promises';
import { QUESTION_PACKS } from '../src/config/content-registry';

type QuestionLike = { topic: string };

const groups: Array<{ path: string; exports: readonly string[]; topics: string[] }> = [];
for (const pack of QUESTION_PACKS.filter((entry) => entry.includeInStandardQuiz)) {
  const module = await import(`../src/content/${pack.group}/index.ts`) as Record<string, unknown>;
  const questions = pack.exports.flatMap((name) => {
    const value = module[name];
    if (!Array.isArray(value)) throw new Error(`${pack.group} does not export question array ${name}`);
    return value as QuestionLike[];
  });
  groups.push({ path: pack.group, exports: pack.exports, topics: [...new Set(questions.map(({ topic }) => topic))].sort() });
}

const topicGroups = new Map<string, string[]>();
for (const group of groups) for (const topic of group.topics) {
  topicGroups.set(topic, [...(topicGroups.get(topic) ?? []), group.path]);
}
const loaderLines = groups.map(({ path, exports }) => {
  const expression = exports.length === 1 ? `module.${exports[0]}` : `[${exports.map((name) => `...module.${name}`).join(', ')}]`;
  return `  ${JSON.stringify(path)}: () => import('./${path}').then((module) => ${expression}),`;
});
const output = `// Generated by scripts/generate-question-loaders.ts. Do not edit by hand.\n` +
`import type { Question } from './types';\n\n` +
`export const QUESTION_GROUPS = ${JSON.stringify(groups.map(({ path }) => path), null, 2)} as const;\n\n` +
`const GROUP_LOADERS: Record<string, () => Promise<Question[]>> = {\n${loaderLines.join('\n')}\n};\n\n` +
`export const TOPIC_TO_GROUPS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(Object.fromEntries(topicGroups), null, 2)};\n\n` +
`const groupCache = new Map<string, Promise<Question[]>>();\n\n` +
`function loadGroup(group: string): Promise<Question[]> {\n  const cached = groupCache.get(group);\n  if (cached) return cached;\n  const loader = GROUP_LOADERS[group];\n  if (!loader) return Promise.resolve([]);\n  const request = loader().catch((error) => { groupCache.delete(group); throw error; });\n  groupCache.set(group, request);\n  return request;\n}\n\n` +
`export interface QuestionLoadProgress { loaded: number; total: number }\n\n` +
`export async function loadQuestionsForTopics(topics: string[], onProgress?: (progress: QuestionLoadProgress) => void): Promise<Question[]> {\n  const groups = topics.length === 0 ? Object.keys(GROUP_LOADERS) : [...new Set(topics.flatMap((topic) => TOPIC_TO_GROUPS[topic] ?? []))];\n  let loaded = 0;\n  onProgress?.({ loaded, total: groups.length });\n  const pools = await Promise.all(groups.map(async (group) => { const questions = await loadGroup(group); loaded += 1; onProgress?.({ loaded, total: groups.length }); return questions; }));\n  const pool = pools.flat();\n  return topics.length === 0 ? pool : pool.filter((question) => topics.includes(question.topic));\n}\n`;
await writeFile(new URL('../src/content/question-loaders.ts', import.meta.url), output);
console.log(`Generated ${groups.length} question groups covering ${topicGroups.size} topics.`);
