import { writeFile } from 'node:fs/promises';
import { allQuestions } from '../src/content/index';
import { allGlossaryTerms } from '../src/content/glossary/index';
import { THINKERS } from '../src/config/thinkers';
import { EQUATIONS } from '../src/config/equations';
import { VAULT_ENTRIES } from '../src/config/vault';

const questionCounts = Object.fromEntries(
  [...new Set(allQuestions.map(({ topic }) => topic))]
    .sort()
    .map((topic) => {
      const questions = allQuestions.filter((question) => question.topic === topic);
      const easy = questions.filter(({ difficulty }) => difficulty === 'easy').length;
      const hard = questions.filter(({ difficulty }) => difficulty === 'hard').length;
      const sota = questions.filter(({ difficulty }) => difficulty === 'sota').length;
      return [topic, { easy, hard, sota, total: questions.length }];
    }),
);

const output = `// Generated by scripts/generate-content-stats.ts. Do not edit by hand.\n` +
  `export const CONTENT_COUNTS = ${JSON.stringify({
    questions: allQuestions.length,
    glossaryTerms: allGlossaryTerms.length,
    thinkers: THINKERS.length,
    vaultEntries: VAULT_ENTRIES.length,
    equations: EQUATIONS.length,
  }, null, 2)} as const;\n\n` +
  `export const QUESTION_COUNTS = ${JSON.stringify(questionCounts, null, 2)} as const;\n`;

await writeFile(new URL('../src/config/content-stats.ts', import.meta.url), output);
