import type { Question } from '../types';

// ── CFA Level I: Ethics & Professional Standards ──
export const cfaLevel1Questions: Question[] = [
  {
    id: 80100,
    topic: 'cfa-level-1',
    difficulty: 'easy',
    question: 'Under the CFA Institute Code of Ethics, members must place the interests of:',
    options: [
      'Clients above their own personal interests',
      'Their employer above all other parties',
      'Regulatory bodies above clients',
      'Shareholders above bondholders always',
    ],
    correctIndex: 0,
    explanation: 'The Code requires members to place client interests first, acting with loyalty, prudence, and care.',
    realWorld: 'CFA charterholders sign an annual attestation to uphold these ethical standards.',
    hint: 'Client duty is paramount in fiduciary relationships.',
  },
  {
    id: 80101,
    topic: 'cfa-level-1',
    difficulty: 'hard',
    question: 'Under Standard III(B) Fair Dealing, a portfolio manager who receives material nonpublic information should:',
    options: [
      'Not trade until the information becomes public',
      'Share with select institutional clients only',
      'Trade immediately to benefit clients',
      'Report to the SEC but continue trading',
    ],
    correctIndex: 0,
    explanation: 'Standard III(B) combined with insider trading laws prohibits acting on material nonpublic information until it is publicly disseminated.',
    realWorld: 'Mosaic theory allows combining non-material info, but material MNPI triggers a trading ban.',
    hint: 'Think about insider trading regulations.',
  },
  {
    id: 80102,
    topic: 'cfa-level-1',
    difficulty: 'sota',
    question: 'The CFA Institute\'s Global Investment Performance Standards (GIPS) require composite construction based on:',
    options: [
      'Similar investment mandate, objective, or strategy',
      'Alphabetical client name ordering',
      'Portfolio size from largest to smallest',
      'Random sampling of 10% of accounts',
    ],
    correctIndex: 0,
    explanation: 'GIPS composites must group portfolios with similar strategies to prevent cherry-picking of high-performing accounts.',
    realWorld: 'GIPS compliance is a global standard for asset managers claiming performance track records.',
    hint: 'Composites prevent selection bias in performance reporting.',
  },
  {
    id: 80103,
    topic: 'cfa-level-1',
    difficulty: 'easy',
    question: 'The time value of money concept states that $\\$1$ today is worth:',
    options: [
      'More than $\\$1$ in the future due to earning potential',
      'Exactly $\\$1$ in the future regardless of rates',
      'Less than $\\$1$ in the future due to deflation',
      'The same as $\\$1$ in the future if inflation is zero',
    ],
    correctIndex: 0,
    explanation: 'Money today can be invested to earn interest, making it worth more than the same nominal amount received later.',
    realWorld: 'TVM underpins all of corporate finance: NPV, IRR, bond pricing, and annuity valuation.',
    hint: 'A dollar today can be invested and grow.',
  },
  {
    id: 80104,
    topic: 'cfa-level-1',
    difficulty: 'hard',
    question: 'The coefficient of variation (CV) is preferred over standard deviation for comparing risk because:',
    options: [
      'CV normalizes risk per unit of expected return, enabling cross-asset comparison',
      'CV is always lower than standard deviation',
      'CV ignores negative returns',
      'CV only works for normally distributed returns',
    ],
    correctIndex: 0,
    explanation: 'CV = σ/μ measures relative risk. Two assets with different expected returns can be compared on a risk-per-return basis.',
    realWorld: 'Analysts compare CV across asset classes with different return profiles (equities vs. bonds).',
    hint: 'It\'s about risk relative to return, not absolute risk.',
  },
];

// ── CFA Level II: Equity Valuation & Financial Reporting ──
export const cfaLevel2Questions: Question[] = [
  {
    id: 80200,
    topic: 'cfa-level-2',
    difficulty: 'easy',
    question: 'The Gordon Growth Model values a stock as D₁/(r - g), where g represents:',
    options: [
      'The constant dividend growth rate',
      'The risk-free rate',
      'The stock\'s beta',
      'The earnings yield',
    ],
    correctIndex: 0,
    explanation: 'The Gordon Growth Model assumes dividends grow at a constant rate g forever, giving P₀ = D₁/(r-g).',
    realWorld: 'Utilities and mature companies with stable dividends are commonly valued with this model.',
    hint: 'It\'s the perpetual growth rate of dividends.',
  },
  {
    id: 80201,
    topic: 'cfa-level-2',
    difficulty: 'hard',
    question: 'Residual Income (RI) valuation differs from DDM because RI:',
    options: [
      'Values the excess return above the cost of equity applied to book value',
      'Ignores the cost of capital entirely',
      'Only works for non-dividend-paying stocks',
      'Uses free cash flow instead of earnings',
    ],
    correctIndex: 0,
    explanation: 'RI = NI - (r_e × BV), capturing economic profit. Stock value = BV₀ + PV(future RIs).',
    realWorld: 'RI models are preferred for valuing financial institutions where FCF is hard to define.',
    hint: 'It\'s about earning more than your cost of equity capital.',
  },
  {
    id: 80202,
    topic: 'cfa-level-2',
    difficulty: 'sota',
    question: 'In a multi-stage DDM with an H-model, the "H" factor represents:',
    options: [
      'The half-life of the transition from high growth to stable growth',
      'The Herfindahl index of market concentration',
      'The hedge ratio for the portfolio',
      'The historical average dividend yield',
    ],
    correctIndex: 0,
    explanation: 'The H-model assumes linear decline in growth rate over 2H years: V₀ = D₀(1+g_L)/(r-g_L) + D₀·H·(g_S-g_L)/(r-g_L).',
    realWorld: 'Analysts use the H-model for tech companies expected to see growth decelerate gradually.',
    hint: 'H is the half-life of the growth transition period.',
  },
  {
    id: 80203,
    topic: 'cfa-level-2',
    difficulty: 'easy',
    question: 'Enterprise Value (EV) is calculated as:',
    options: [
      'Market cap + total debt - cash and cash equivalents',
      'Market cap only',
      'Total assets minus total liabilities',
      'Net income times the P/E ratio',
    ],
    correctIndex: 0,
    explanation: 'EV represents the total value of the firm to all capital providers (equity + debt holders), net of cash.',
    realWorld: 'EV/EBITDA is the most widely used valuation multiple in M&A and leveraged buyouts.',
    hint: 'Think about what an acquirer would pay to own the entire firm.',
  },
  {
    id: 80204,
    topic: 'cfa-level-2',
    difficulty: 'hard',
    question: 'Under IFRS, goodwill impairment testing requires:',
    options: [
      'Annual testing at the cash-generating unit (CGU) level with no amortization',
      'Straight-line amortization over 20 years',
      'Testing only when a triggering event occurs',
      'Immediate write-off at acquisition',
    ],
    correctIndex: 0,
    explanation: 'IFRS requires annual impairment testing of goodwill allocated to CGUs. Unlike US GAAP (which added an optional qualitative step), IFRS has no amortization alternative.',
    realWorld: 'Large write-downs (e.g., HP\'s $8.8B Autonomy impairment) can materially impact reported earnings.',
    hint: 'IFRS does not amortize goodwill — it only impairs.',
  },
];

// ── CFA Level III: Portfolio Management & Wealth Planning ──
export const cfaLevel3Questions: Question[] = [
  {
    id: 80300,
    topic: 'cfa-level-3',
    difficulty: 'easy',
    question: 'An Investment Policy Statement (IPS) should specify all of the following EXCEPT:',
    options: [
      'Specific stock ticker symbols to buy',
      'Return objectives',
      'Risk tolerance',
      'Time horizon and liquidity needs',
    ],
    correctIndex: 0,
    explanation: 'An IPS sets broad guidelines (objectives, constraints) but does not prescribe specific securities.',
    realWorld: 'Wealth managers draft IPS documents before constructing any portfolio.',
    hint: 'The IPS is about policy, not individual security selection.',
  },
  {
    id: 80301,
    topic: 'cfa-level-3',
    difficulty: 'hard',
    question: 'In a core-satellite portfolio strategy, the "core" typically consists of:',
    options: [
      'Low-cost passive index funds capturing broad market beta',
      'High-frequency trading algorithms',
      'Concentrated positions in 3-5 stocks',
      'Leveraged derivatives only',
    ],
    correctIndex: 0,
    explanation: 'Core-satellite uses passive core for market exposure and active satellites seeking alpha, optimizing cost and tracking error.',
    realWorld: 'Many endowments and sovereign wealth funds employ core-satellite allocation.',
    hint: 'The core provides beta cheaply; satellites hunt for alpha.',
  },
  {
    id: 80302,
    topic: 'cfa-level-3',
    difficulty: 'sota',
    question: 'Liability-Driven Investing (LDI) for pension funds primarily uses:',
    options: [
      'Duration-matched fixed income to hedge present value of liabilities',
      'Maximum equity allocation to outgrow liabilities',
      'Short-selling stocks to reduce risk',
      'Cash-only holdings for liquidity',
    ],
    correctIndex: 0,
    explanation: 'LDI matches asset duration/convexity to liability duration, immunizing funded status against interest rate changes.',
    realWorld: 'UK and Dutch pension funds widely adopted LDI; the 2022 UK gilt crisis exposed leverage risks in LDI structures.',
    hint: 'The goal is hedging liability interest rate sensitivity, not maximizing returns.',
  },
  {
    id: 80303,
    topic: 'cfa-level-3',
    difficulty: 'hard',
    question: 'The Black-Litterman model improves on mean-variance optimization by:',
    options: [
      'Starting from market-implied equilibrium returns and blending in investor views',
      'Eliminating the need for a covariance matrix',
      'Using only historical returns without adjustment',
      'Ignoring market capitalization weights entirely',
    ],
    correctIndex: 0,
    explanation: 'Black-Litterman combines CAPM equilibrium (reverse-optimized from market cap weights) with subjective views, producing more stable and intuitive portfolio allocations.',
    realWorld: 'Goldman Sachs developed Black-Litterman; it\'s now standard in institutional asset allocation.',
    hint: 'It anchors to market equilibrium, then tilts toward your views.',
  },
  {
    id: 80304,
    topic: 'cfa-level-3',
    difficulty: 'sota',
    question: 'Risk parity portfolio construction allocates capital so that each asset class contributes:',
    options: [
      'Equal marginal risk (volatility contribution) to the portfolio',
      'Equal dollar amounts regardless of risk',
      'Maximum expected return per unit of capital',
      'Inverse beta-weighted positions',
    ],
    correctIndex: 0,
    explanation: 'Risk parity equalizes risk contributions: $w_i \\cdot \\frac{\\partial \\sigma_p}{\\partial w_i}$ is the same for all assets. Low-vol assets get higher weight.',
    realWorld: 'Bridgewater\'s All Weather fund popularized risk parity; it typically levers up bonds to match equity risk.',
    hint: 'It\'s about equal risk, not equal dollars.',
  },
];
