import type { Question } from '../types';

export const condensedMatterEasyQuestions: Question[] = [
  {
    id: 28201,
    topic: 'condensed-matter',
    difficulty: 'easy',
    question: 'Bloch\'s theorem states that electron wavefunctions in a periodic crystal potential take the form:',
    options: [
      '$\\psi_k(r) = e^{ik \\cdot r} u_k(r)$ where $u_k$ has the periodicity of the lattice',
      'Plane waves $e^{ik \\cdot r}$',
      'Localized Gaussians centered on each atom',
      'Spherical harmonics $Y_l^m(\\theta, \\phi)$',
    ],
    correctIndex: 0,
    explanation: 'Bloch\'s theorem decomposes crystal wavefunctions into a plane wave modulated by a periodic function. This leads to energy bands $E_n(k)$ and the concept of the Brillouin zone.',
    realWorld: 'Band theory explains why some materials are metals, some insulators, and some semiconductors — the basis of all electronics.',
    hint: 'The periodicity of the lattice imprints itself on the wavefunction through $u_k(r)$.',
  },
  {
    id: 28202,
    topic: 'condensed-matter',
    difficulty: 'easy',
    question: 'A phonon is:',
    options: [
      'A quantized lattice vibration — the sound equivalent of a photon',
      'A type of electron in a metal',
      'A magnetic excitation in a ferromagnet',
      'A defect in a crystal',
    ],
    correctIndex: 0,
    explanation: 'Phonons are quasiparticles representing quantized collective vibrations of atoms in a crystal lattice. They carry heat and mediate electron-phonon interactions.',
    realWorld: 'Phonons determine thermal conductivity, superconductivity (BCS theory), and thermoelectric device performance.',
    hint: 'Photo = light quantum. Phonon = sound quantum.',
  },
  {
    id: 28203,
    topic: 'condensed-matter',
    difficulty: 'easy',
    question: 'In BCS theory, conventional superconductivity arises from:',
    options: [
      'Cooper pairs — electrons bound via phonon-mediated attraction overcoming Coulomb repulsion',
      'Electrons moving without scattering off the lattice',
      'Magnetic ordering of electrons',
      'Bose-Einstein condensation of individual electrons',
    ],
    correctIndex: 0,
    explanation: 'Two electrons with opposite momenta and spins form a Cooper pair via virtual phonon exchange. These bosonic pairs condense into a macroscopic quantum state with zero resistance.',
    realWorld: 'BCS theory earned Bardeen, Cooper, and Schrieffer the 1972 Nobel Prize. MRI magnets use NbTi superconductors.',
    hint: 'The attraction is counterintuitive — two negative charges attract each other through lattice deformation.',
  },
];

export const condensedMatterHardQuestions: Question[] = [
  {
    id: 28211,
    topic: 'condensed-matter',
    difficulty: 'hard',
    question: 'The integer quantum Hall effect shows Hall conductance quantized as $\\sigma_{xy} = \\nu e^2/h$. The integer $\\nu$ is:',
    options: [
      'A topological invariant (Chern number) — robust against disorder and deformation',
      'The number of electrons per atom',
      'The Landau level index only',
      'The lattice coordination number',
    ],
    correctIndex: 0,
    explanation: 'Thouless, Kohmoto, Nightingale, and den Nijs (TKNN) showed $\\nu$ is the first Chern number of the Berry connection over the magnetic Brillouin zone — a topological invariant that cannot change continuously.',
    realWorld: 'The quantum Hall effect now defines the international resistance standard ($R_K = h/e^2 = 25812.807\\,\\Omega$) with precision better than 1 ppb.',
    hint: 'The quantization is exact because topology is discrete — you can\'t have half a Chern number.',
  },
  {
    id: 28212,
    topic: 'condensed-matter',
    difficulty: 'hard',
    question: 'Topological insulators are materials that:',
    options: [
      'Are insulating in the bulk but have conducting surface states protected by time-reversal symmetry',
      'Are perfect insulators at all temperatures',
      'Have topological defects in their crystal structure',
      'Conduct only along one crystallographic axis',
    ],
    correctIndex: 0,
    explanation: 'Topological insulators have a bulk band gap but gapless surface states with spin-momentum locking. These surface states are robust against non-magnetic disorder — they cannot be localized.',
    realWorld: 'Materials like Bi₂Se₃ are experimental topological insulators, promising for spintronics and topological quantum computing.',
    hint: 'The surface is metallic, the bulk is insulating — and the surface states survive even with dirt.',
  },
  {
    id: 28213,
    topic: 'condensed-matter',
    difficulty: 'hard',
    question: 'The Mermin-Wagner theorem states that continuous symmetries cannot be spontaneously broken in systems of dimension $d \\leq$:',
    options: ['$2$ (at finite temperature, for short-range interactions)', '$1$', '$3$', '$4$'],
    correctIndex: 0,
    explanation: 'In 1D and 2D, thermal fluctuations destroy long-range order for continuous symmetries (like ferromagnetism with Heisenberg spins). Discrete symmetries (Ising) CAN break in 2D.',
    realWorld: 'This explains why 2D Heisenberg magnets don\'t order, but the 2D Ising model does — and why the BKT transition in 2D is so special.',
    hint: 'The Ising model (discrete $\\mathbb{Z}_2$ symmetry) orders in 2D. Heisenberg (continuous $SO(3)$) does not.',
  },
];

export const condensedMatterSotaQuestions: Question[] = [
  {
    id: 28221,
    topic: 'condensed-matter',
    difficulty: 'sota',
    question: 'The tenfold classification of topological insulators and superconductors (Altland-Zirnbauer) is based on which symmetries?',
    options: [
      'Time-reversal ($\\mathcal{T}$), particle-hole ($\\mathcal{C}$), and chiral ($\\mathcal{S} = \\mathcal{T}\\mathcal{C}$)',
      'Translation, rotation, and inversion',
      'Gauge symmetry and Lorentz invariance',
      'Parity, charge conjugation, and CPT',
    ],
    correctIndex: 0,
    explanation: 'The "periodic table of topological phases" classifies all free-fermion topological phases by the presence/absence of $\\mathcal{T}$, $\\mathcal{C}$, $\\mathcal{S}$ symmetries and spatial dimension $d$.',
    realWorld: 'This classification predicted topological superconductors hosting Majorana fermions — candidates for fault-tolerant quantum computing.',
    hint: 'Three discrete symmetries, each present or absent with different squares ($\\pm 1$), yield 10 symmetry classes.',
  },
  {
    id: 28222,
    topic: 'condensed-matter',
    difficulty: 'sota',
    question: 'Sachdev-Ye-Kitaev (SYK) model features $N$ Majorana fermions with all-to-all random interactions. At low temperature it exhibits:',
    options: [
      'Maximal chaos (Lyapunov exponent saturating the Maldacena-Shenker-Stanford bound $\\lambda_L = 2\\pi k_BT/\\hbar$)',
      'Perfect Fermi liquid behavior',
      'Anderson localization',
      'Bose-Einstein condensation',
    ],
    correctIndex: 0,
    explanation: 'The SYK model is maximally chaotic — its Lyapunov exponent saturates the theoretical upper bound, just like black holes. It is solvable in the large-$N$ limit and holographically dual to 2D gravity.',
    realWorld: 'The SYK model bridges condensed matter, quantum chaos, and quantum gravity — it is a laboratory for studying the information paradox.',
    hint: 'It scrambles quantum information as fast as theoretically possible — just like a black hole.',
  },
  {
    id: 28223,
    topic: 'condensed-matter',
    difficulty: 'sota',
    question: 'Twisted bilayer graphene at the "magic angle" ($\\theta \\approx 1.1°$) exhibits:',
    options: [
      'Flat electronic bands leading to correlated insulating states and unconventional superconductivity',
      'Perfect metallic conductivity',
      'Topological surface states',
      'Antiferromagnetic Néel ordering',
    ],
    correctIndex: 0,
    explanation: 'At the magic angle, the moiré superlattice creates nearly flat bands with bandwidth $\\sim 10$ meV. Strong correlations produce a cascade of insulating, superconducting, and magnetic phases.',
    realWorld: 'Discovered by Cao et al. (2018), "twistronics" created a new platform for studying correlated electron physics without traditional heavy-element materials.',
    hint: 'A tiny twist angle between two graphene sheets creates a whole new universe of quantum phases.',
  },
];
