import type { Question } from '../types';

export const algebraicGeometryQuestions: Question[] = [
  // ── Easy ──
  {
    id: 93001, topic: 'algebraic-geometry', difficulty: 'easy',
    question: 'An algebraic variety is the set of solutions to:',
    options: ['A system of polynomial equations', 'A system of differential equations', 'A system of linear inequalities', 'A single transcendental equation'],
    correctIndex: 0,
    explanation: 'Algebraic varieties are defined as zero sets of polynomial equations in affine or projective space.',
    realWorld: 'Algebraic varieties model elliptic curves used in modern cryptography (ECC).',
    hint: 'Think about curves and surfaces defined by polynomials.',
  },
  {
    id: 93002, topic: 'algebraic-geometry', difficulty: 'easy',
    question: 'The degree of the curve $x^2 + y^2 = 1$ in $\\mathbb{R}^2$ is:',
    options: ['2', '1', '3', '4'],
    correctIndex: 0,
    explanation: 'The degree equals the highest total degree of monomials in the defining polynomial, which is 2.',
    realWorld: 'Degree determines how many times a generic line intersects a curve (Bézout\'s theorem).',
    hint: 'What is the highest power appearing in $x^2 + y^2 - 1 = 0$?',
  },
  {
    id: 93003, topic: 'algebraic-geometry', difficulty: 'easy',
    question: 'Projective space $\\mathbb{P}^n$ adds what to affine space $\\mathbb{A}^n$?',
    options: ['Points at infinity, so parallel lines meet', 'A metric structure', 'Negative dimensions', 'A time coordinate'],
    correctIndex: 0,
    explanation: 'Projective space compactifies affine space by adding a hyperplane at infinity.',
    realWorld: 'Projective geometry is the foundation of computer vision and camera calibration.',
    hint: 'In projective space, every two lines in a plane intersect.',
  },
  {
    id: 93004, topic: 'algebraic-geometry', difficulty: 'easy',
    question: 'An elliptic curve over $\\mathbb{Q}$ is a smooth curve of genus:',
    options: ['1', '0', '2', '3'],
    correctIndex: 0,
    explanation: 'Elliptic curves are genus-1 curves with a specified rational point, typically written $y^2 = x^3 + ax + b$.',
    realWorld: 'Elliptic curve cryptography (ECC) secures TLS, Bitcoin, and Signal protocols.',
    hint: 'Think about the topology of a torus.',
  },
  {
    id: 93005, topic: 'algebraic-geometry', difficulty: 'easy',
    question: 'Bézout\'s theorem states that two projective curves of degrees $m$ and $n$ intersect in:',
    options: ['$mn$ points (counting multiplicity)', '$m + n$ points', '$\\max(m,n)$ points', '$m^n$ points'],
    correctIndex: 0,
    explanation: 'Over an algebraically closed field, counting multiplicities and points at infinity gives exactly $mn$ intersections.',
    realWorld: 'Bézout\'s theorem is used in computational geometry for intersection counting.',
    hint: 'A line ($m=1$) meets a conic ($n=2$) in at most $1 \\times 2 = 2$ points.',
  },
  // ── Hard ──
  {
    id: 93006, topic: 'algebraic-geometry', difficulty: 'hard',
    question: 'A scheme, as introduced by Grothendieck, generalizes a variety by:',
    options: ['Using the spectrum of any commutative ring, not just polynomial rings over fields', 'Restricting to smooth varieties', 'Only considering finite fields', 'Removing singular points'],
    correctIndex: 0,
    explanation: 'Schemes = locally ringed spaces locally isomorphic to $\\text{Spec}(R)$, unifying geometry and number theory.',
    realWorld: 'Schemes allow treating $\\mathbb{Z}$ geometrically, unifying algebraic geometry and number theory.',
    hint: 'Grothendieck replaced coordinate rings with arbitrary commutative rings.',
  },
  {
    id: 93007, topic: 'algebraic-geometry', difficulty: 'hard',
    question: 'Sheaf cohomology $H^i(X, \\mathcal{F})$ measures:',
    options: ['The obstruction to extending local sections of $\\mathcal{F}$ to global sections', 'The number of singular points on $X$', 'The dimension of $X$', 'The number of connected components'],
    correctIndex: 0,
    explanation: '$H^0$ gives global sections; higher $H^i$ measure the failure of exactness (obstructions to gluing).',
    realWorld: 'Sheaf cohomology computes dimensions of spaces of differential forms and line bundle sections.',
    hint: 'Think about when local data can or cannot be glued into global data.',
  },
  {
    id: 93008, topic: 'algebraic-geometry', difficulty: 'hard',
    question: 'The Riemann-Roch theorem for a curve of genus $g$ with divisor $D$ of degree $d$ gives $\\ell(D) - \\ell(K-D) =$',
    options: ['$d - g + 1$', '$d + g$', '$g - d$', '$2g - 2$'],
    correctIndex: 0,
    explanation: 'Riemann-Roch: $\\ell(D) - \\ell(K-D) = \\deg(D) - g + 1$, where $K$ is the canonical divisor.',
    realWorld: 'Riemann-Roch determines the parameters of algebraic-geometry error-correcting codes (Goppa codes).',
    hint: 'This is the fundamental theorem relating line bundles to topology on curves.',
  },
  {
    id: 93009, topic: 'algebraic-geometry', difficulty: 'hard',
    question: 'The Weil conjectures (proven by Deligne) relate the number of points on a variety over $\\mathbb{F}_q$ to:',
    options: ['The topology of the corresponding complex variety via étale cohomology', 'The Euler characteristic only', 'The dimension of the variety', 'The Picard group'],
    correctIndex: 0,
    explanation: 'The zeta function of a variety over $\\mathbb{F}_q$ has properties (rationality, functional equation, Riemann hypothesis) reflecting the complex topology.',
    realWorld: 'Point counting on curves over finite fields is essential for elliptic curve cryptography parameter selection.',
    hint: 'Deligne proved the "Riemann hypothesis" part using $\\ell$-adic cohomology.',
  },
  {
    id: 93010, topic: 'algebraic-geometry', difficulty: 'hard',
    question: 'A blowup of a surface at a point replaces that point with:',
    options: ['A projective line (exceptional divisor)', 'A circle', 'A point at infinity', 'Nothing — it removes the point'],
    correctIndex: 0,
    explanation: 'Blowing up replaces a point with $\\mathbb{P}^1$ (or $\\mathbb{P}^{n-1}$ in $n$ dimensions), resolving singularities.',
    realWorld: 'Resolution of singularities (Hironaka) is fundamental to birational geometry and string theory compactifications.',
    hint: 'Think about replacing a point with all the directions through it.',
  },
  // ── SOTA ──
  {
    id: 93011, topic: 'algebraic-geometry', difficulty: 'sota',
    question: 'The Minimal Model Program (MMP) in birational geometry aims to:',
    options: ['Classify algebraic varieties by finding canonical "simplest" representatives in each birational class', 'Find minimal polynomial equations', 'Compute cohomology groups', 'Enumerate rational points'],
    correctIndex: 0,
    explanation: 'MMP (Mori, Birkar, Hacon, McKernan) reduces varieties to minimal models or Mori fiber spaces via flips and contractions.',
    realWorld: 'Birkar\'s proof of BAB conjecture (Fields Medal 2018) was a MMP milestone.',
    hint: 'Think about surgeries (flips, flops) that simplify the geometry.',
  },
  {
    id: 93012, topic: 'algebraic-geometry', difficulty: 'sota',
    question: 'Derived algebraic geometry replaces commutative rings with:',
    options: ['Simplicial commutative rings / $E_\\infty$-ring spectra to handle derived intersections', 'Noncommutative rings', 'Boolean algebras', 'Lie algebras'],
    correctIndex: 0,
    explanation: 'Derived AG (Toën, Vezzosi, Lurie) uses derived stacks to correctly handle non-transverse intersections.',
    realWorld: 'Derived algebraic geometry provides rigorous foundations for moduli spaces in string theory.',
    hint: 'When two subvarieties intersect non-transversally, classical intersection theory fails — derived geometry fixes this.',
  },
  {
    id: 93013, topic: 'algebraic-geometry', difficulty: 'sota',
    question: 'Mirror symmetry (Kontsevich\'s homological mirror symmetry conjecture) relates:',
    options: ['The derived category of coherent sheaves on $X$ to the Fukaya category of the mirror $\\check{X}$', 'Two identical varieties', 'Complex and real algebraic geometry', 'Finite and infinite fields'],
    correctIndex: 0,
    explanation: 'HMS: $D^b(\\text{Coh}(X)) \\cong D^b(\\text{Fuk}(\\check{X}))$, connecting algebraic and symplectic geometry.',
    realWorld: 'Mirror symmetry computes Gromov-Witten invariants (curve counting) via period integrals on the mirror.',
    hint: 'One side is algebraic (sheaves), the other is symplectic (Lagrangians).',
  },
  {
    id: 93014, topic: 'algebraic-geometry', difficulty: 'sota',
    question: 'Perfectoid spaces, introduced by Scholze (Fields Medal 2018), are valued for:',
    options: ['Tilting between characteristic 0 and characteristic $p$ geometry', 'Only working over the reals', 'Simplifying Euclidean geometry', 'Computing determinants of large matrices'],
    correctIndex: 0,
    explanation: 'Perfectoid spaces create an equivalence between mixed characteristic and equal characteristic $p$ settings.',
    realWorld: 'Scholze used perfectoid spaces to prove cases of the weight-monodromy conjecture and advance the Langlands program.',
    hint: 'The key technique is "tilting" from $\\mathbb{Q}_p$ to $\\mathbb{F}_p((t))$.',
  },
  {
    id: 93015, topic: 'algebraic-geometry', difficulty: 'sota',
    question: 'Motivic homotopy theory (Voevodsky, Fields Medal 2002) extends algebraic topology to algebraic geometry using:',
    options: ['$\\mathbb{A}^1$-homotopy theory where the affine line plays the role of the unit interval', 'Only simplicial methods', 'Classical point-set topology', 'Discrete mathematics'],
    correctIndex: 0,
    explanation: '$\\mathbb{A}^1$-invariance replaces the topological interval $[0,1]$ with the algebraic affine line.',
    realWorld: 'Voevodsky used motivic cohomology to prove the Milnor and Bloch-Kato conjectures.',
    hint: 'The affine line $\\mathbb{A}^1$ is the algebraic analog of the topological interval.',
  },
];
