import type { Question } from '../types';

export const roboticsQuestions: Question[] = [
  {
    id: 40201, topic: 'robotics-mechatronics', difficulty: 'easy',
    question: 'A PID controller in robotics adjusts motor output based on:',
    options: [
      'Proportional error, Integral of past errors, and Derivative of error change — $u(t) = K_p e + K_i \\int e\\,dt + K_d \\frac{de}{dt}$',
      'Only the current sensor reading',
      'A pre-recorded sequence of movements',
      'Random perturbations to find optimal actions',
    ],
    correctIndex: 0,
    explanation: 'PID combines three terms: P (corrects current error), I (eliminates steady-state offset), D (dampens oscillation). Tuning K_p, K_i, K_d is the core challenge.',
    realWorld: 'PID controllers run in virtually every industrial robot, drone stabilization system, cruise control, and 3D printer. Over 95% of industrial control loops use some form of PID.',
    hint: 'Three letters, three jobs: fix NOW, fix PAST accumulation, anticipate FUTURE change.',
  },
  {
    id: 40204, topic: 'robotics-mechatronics', difficulty: 'easy',
    question: 'Forward kinematics computes:',
    options: [
      'The end-effector position given joint angles — using the chain of transformation matrices along the kinematic chain',
      'The joint angles needed to reach a target position',
      'The force required to move each joint',
      'The mass of the robot arm',
    ],
    correctIndex: 0,
    explanation: 'Forward kinematics maps joint space → task space using Denavit-Hartenberg parameters. Each joint has a 4×4 homogeneous transformation matrix; multiplying them gives the end-effector pose. The inverse problem (IK) is much harder.',
    realWorld: 'Every robot arm, from factory welders to surgical da Vinci systems, uses forward kinematics to know where its tool tip is. Video game character animation uses the same math.',
    hint: 'Given the angles of all joints, where is the hand? Matrix multiplication along the chain.',
  },
  {
    id: 40202, topic: 'robotics-mechatronics', difficulty: 'hard',
    question: 'SLAM (Simultaneous Localization and Mapping) is challenging because:',
    options: [
      'The robot must build a map of an unknown environment while simultaneously tracking its own position within that map — a chicken-and-egg problem',
      'Robots already know perfect maps of all environments',
      'GPS works perfectly indoors and underground',
      'Cameras can directly measure distance without computation',
    ],
    correctIndex: 0,
    explanation: 'SLAM requires estimating both the robot\'s pose and the environment map simultaneously. Errors in one affect the other. Solutions include EKF-SLAM, particle filters (FastSLAM), and graph-based optimization.',
    realWorld: 'Every self-driving car, delivery robot, and AR headset uses SLAM. Apple\'s ARKit and Google\'s ARCore perform visual SLAM in real-time on your phone.',
    hint: 'You need a map to know where you are, but you need to know where you are to build a map.',
  },
  {
    id: 40205, topic: 'robotics-mechatronics', difficulty: 'hard',
    question: 'Sim-to-real transfer in robotics is difficult because:',
    options: [
      'Physics simulators don\'t perfectly match reality — the "reality gap" in friction, contact dynamics, and sensor noise causes policies trained in simulation to fail on real hardware',
      'Robots in simulation run faster than real robots',
      'Real robots are always more expensive than simulated ones',
      'Simulation uses different programming languages',
    ],
    correctIndex: 0,
    explanation: 'Domain randomization (randomizing simulation parameters) forces policies to be robust across many physical configurations. This hedges against the sim-to-real gap. Alternative: system identification to calibrate the simulator precisely.',
    realWorld: 'OpenAI trained a robotic hand to solve a Rubik\'s Cube entirely in simulation, then transferred to a real hand. Domain randomization was critical — the policy needed to handle friction/mass variations it had never seen.',
    hint: 'The simulator is never perfect — the robot needs to be robust enough to handle the differences.',
  },
  {
    id: 40203, topic: 'robotics-mechatronics', difficulty: 'sota',
    question: 'Foundation models for robotics (RT-2, π₀) aim to solve:',
    options: [
      'The generalization gap — training a single vision-language-action model that transfers manipulation skills to novel objects and environments without task-specific fine-tuning',
      'Making robots move faster than humans',
      'Replacing all sensors with a single camera',
      'Eliminating the need for any training data',
    ],
    correctIndex: 0,
    explanation: 'RT-2 and π₀ treat robotic control as a vision-language problem: the model sees an image, reads a text instruction, and outputs motor actions. Pre-training on internet-scale data provides world knowledge that transfers to manipulation.',
    realWorld: 'These models can follow instructions like "pick up the bag of chips" in unseen kitchens — a capability that would have required months of task-specific programming just two years ago.',
    hint: 'The same idea as LLMs — pre-train on massive data, then generalize to new tasks without retraining.',
  },
  {
    id: 40206, topic: 'robotics-mechatronics', difficulty: 'sota',
    question: 'Humanoid robots (Tesla Optimus, Figure 02) use whole-body control by:',
    options: [
      'Solving a hierarchical optimization problem that balances multiple objectives (balance, manipulation, locomotion) subject to joint torque limits and contact constraints in real-time',
      'Pre-programming every possible movement sequence',
      'Using simple PID control on every joint independently',
      'Copying human movements exactly without adaptation',
    ],
    correctIndex: 0,
    explanation: 'Whole-body control formulates robot motion as a quadratic program (QP) solved at 1kHz: minimize tracking error subject to dynamics constraints ($M\\ddot{q} + h = \\tau + J^T f$), torque limits, friction cones, and balance constraints.',
    realWorld: 'Boston Dynamics\' Atlas and Tesla\'s Optimus use model-predictive control (MPC) with learned dynamics. The challenge: a 30+ DOF humanoid must plan contacts, balance, and manipulation simultaneously at millisecond timescales.',
    hint: 'Balance + reach + grip + walk — all optimized together under physical constraints, hundreds of times per second.',
  },
];
