import type { Question } from '../types';

export const formalVerificationQuestions: Question[] = [
  {
    id: 186001, topic: 'formal-verification', difficulty: 'easy',
    question: 'Formal verification proves program correctness by:',
    options: ['Using mathematical proofs to show a program satisfies its specification', 'Running extensive tests', 'Code review by experts', 'Measuring performance benchmarks'],
    correctIndex: 0,
    explanation: 'Unlike testing (which finds bugs), formal verification mathematically proves that a program meets its specification for ALL possible inputs — complete correctness.',
    realWorld: 'The CompCert C compiler is formally verified — it is guaranteed to never miscompile code.',
    hint: 'Testing shows the presence of bugs; verification proves their absence.',
  },
  {
    id: 186002, topic: 'formal-verification', difficulty: 'easy',
    question: 'A Hoare triple $\\{P\\}\\,S\\,\\{Q\\}$ means:',
    options: ['If precondition $P$ holds before executing $S$, then postcondition $Q$ holds after', '$P$ and $Q$ are always true', '$S$ runs in polynomial time', '$P$ implies $Q$ without executing $S$'],
    correctIndex: 0,
    explanation: 'Hoare logic (1969) formalizes program reasoning: $\\{P\\}$ is the precondition, $S$ is the statement, $\\{Q\\}$ is the postcondition. The triple asserts partial correctness.',
    realWorld: 'Hoare logic is the foundation of tools like Dafny, Frama-C, and SPARK Ada for verified software.',
    hint: 'If the input satisfies $P$, then after running $S$, the output satisfies $Q$.',
  },
  {
    id: 186003, topic: 'formal-verification', difficulty: 'easy',
    question: 'Model checking verifies systems by:',
    options: ['Exhaustively exploring all possible states to check if a property holds', 'Sampling random states', 'Testing with representative inputs', 'Static analysis of source code'],
    correctIndex: 0,
    explanation: 'Model checking (Clarke, Emerson, Sifakis — 2007 Turing Award) systematically explores the state space of a finite-state system to verify temporal logic properties.',
    realWorld: 'Intel uses model checking to verify CPU designs — a single bug (Pentium FDIV) cost $475 million.',
    hint: 'Check every possible state — if the property holds everywhere, the system is correct.',
  },
  {
    id: 186004, topic: 'formal-verification', difficulty: 'hard',
    question: 'The Curry-Howard correspondence establishes a deep connection between:',
    options: ['Proofs and programs — a proof of proposition $A$ is a program of type $A$', 'Data structures and algorithms', 'Complexity classes and languages', 'Hardware and software'],
    correctIndex: 0,
    explanation: 'Propositions = types, proofs = terms, proof simplification = computation. This isomorphism means writing a proof in Coq/Lean IS writing a correct program.',
    realWorld: 'Lean 4 and Coq exploit Curry-Howard — proving a theorem produces a verified algorithm as a byproduct.',
    hint: 'Types are propositions; programs are proofs — computation is proof normalization.',
  },
  {
    id: 186005, topic: 'formal-verification', difficulty: 'hard',
    question: 'Lean 4\'s type system is based on:',
    options: ['The Calculus of Inductive Constructions (CIC) with quotient types', 'Simply typed lambda calculus', 'System F only', 'Untyped lambda calculus'],
    correctIndex: 0,
    explanation: 'Lean 4 uses CIC (like Coq) extended with quotient types, universe polymorphism, and a powerful tactic framework. It supports both theorem proving and general-purpose programming.',
    realWorld: 'Lean 4 is used by mathematicians (Mathlib has 150K+ theorems) and for verified ML (LeanDojo).',
    hint: 'CIC = dependent types + inductive types — the workhorse of proof assistants.',
  },
  {
    id: 186006, topic: 'formal-verification', difficulty: 'hard',
    question: 'SMT (Satisfiability Modulo Theories) solvers like Z3 extend SAT solving by:',
    options: ['Reasoning about arithmetic, arrays, bit-vectors, and other first-order theories beyond pure Boolean logic', 'Only handling Boolean formulas', 'Using probabilistic methods', 'Requiring exponential time always'],
    correctIndex: 0,
    explanation: 'SMT solvers combine SAT solving with theory-specific decision procedures: linear arithmetic, uninterpreted functions, arrays, etc. This enables rich verification queries.',
    realWorld: 'Z3 powers formal verification at AWS (s2n TLS), Microsoft (Hyper-V), and smart contract auditing.',
    hint: 'SAT handles $x \\lor y$; SMT handles $x + 2y \\leq 10 \\land z = f(x)$.',
  },
  {
    id: 186007, topic: 'formal-verification', difficulty: 'sota',
    question: 'AI-assisted theorem proving (e.g., AlphaProof, LeanDojo) approaches formal math by:',
    options: ['Training LLMs to generate proof steps and using the proof assistant as a verifier', 'Replacing the proof assistant entirely', 'Using brute-force search only', 'Generating informal proofs'],
    correctIndex: 0,
    explanation: 'Systems like AlphaProof (DeepMind, 2024) combine neural proof generation with formal verification: the LLM proposes proof steps, Lean/Isabelle checks them. This achieved IMO silver-medal performance.',
    realWorld: 'AlphaProof solved 4/6 IMO 2024 problems — the first AI to achieve medal-level math competition performance.',
    hint: 'The LLM generates candidates; the proof assistant guarantees correctness.',
  },
  {
    id: 186008, topic: 'formal-verification', difficulty: 'sota',
    question: 'Verified smart contracts (e.g., using Certora, Halmos) are critical because:',
    options: ['Smart contract bugs are irreversible and have caused billions in losses', 'Gas costs increase with verification', 'Formal methods slow down execution', 'Testing alone is sufficient for financial code'],
    correctIndex: 0,
    explanation: 'Smart contracts are immutable once deployed and hold billions in value. The DAO hack ($60M), Wormhole ($320M), and Ronin ($625M) all had exploitable bugs that formal verification could have caught.',
    realWorld: 'Aave and Compound now use formal verification for critical DeFi protocol upgrades.',
    hint: 'You can\'t patch a deployed smart contract — the bug is the law.',
  },
  {
    id: 186009, topic: 'formal-verification', difficulty: 'sota',
    question: 'The seL4 microkernel is notable in OS verification because:',
    options: ['It has a complete functional correctness proof — the implementation matches its formal specification', 'It is the fastest kernel', 'It supports the most hardware', 'It uses no formal methods'],
    correctIndex: 0,
    explanation: 'seL4 has a machine-checked proof (in Isabelle/HOL) that its C implementation correctly implements its abstract specification. This is ~200,000 lines of proof for ~10,000 lines of C.',
    realWorld: 'seL4 is used in military helicopters, autonomous vehicles, and DARPA\'s cyber-resilient systems.',
    hint: 'The proof guarantees the kernel can never crash, deadlock, or be exploited — mathematically.',
  },
];
