import type { Question } from '../types';

export const fluidDynamicsQuestions: Question[] = [
  {
    id: 21001,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'The Reynolds number $Re = \\frac{\\rho v L}{\\mu}$ determines whether flow is:',
    options: [
      'Laminar (smooth, orderly) or turbulent (chaotic, mixing)',
      'Compressible or incompressible',
      'Steady-state or transient',
      'Subsonic or supersonic',
    ],
    correctIndex: 0,
    explanation: 'The Reynolds number measures the ratio of inertial forces to viscous forces. Below a critical $Re$ (~2300 for pipe flow), viscosity dominates and flow is laminar. Above it, inertial forces dominate and turbulence develops.',
    realWorld: 'Aircraft wings, blood flow in arteries, and oil pipeline design all depend on Reynolds number analysis to predict flow behavior and optimize performance.',
    hint: 'High $Re$ = fast, big, or low-viscosity flows → turbulence. Low $Re$ = slow, small, or viscous flows → laminar.',
  },
  {
    id: 21002,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'Bernoulli\'s principle states that for an ideal fluid flowing along a streamline:',
    options: [
      'As flow speed increases, pressure decreases (and vice versa)',
      'Faster flow always produces higher pressure',
      'Pressure is constant regardless of velocity',
      'Temperature determines pressure independent of velocity',
    ],
    correctIndex: 0,
    explanation: 'Bernoulli\'s equation $P + \\frac{1}{2}\\rho v^2 + \\rho gh = \\text{const}$ expresses energy conservation along a streamline. Increased kinetic energy ($\\frac{1}{2}\\rho v^2$) comes at the expense of pressure energy ($P$).',
    realWorld: 'Bernoulli\'s principle explains airplane lift, Venturi flow meters, carburetors, and why shower curtains blow inward when you turn on the water.',
    hint: 'Think of energy conservation: if kinetic energy goes up, something else must go down.',
  },
  {
    id: 21003,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'The Navier-Stokes equations describe fluid motion. Why is proving the existence and smoothness of their solutions a Millennium Prize Problem?',
    options: [
      'It is unknown whether smooth solutions always exist in 3D or whether singularities (blow-ups) can form in finite time',
      'The equations cannot be solved numerically',
      'They violate conservation of energy in all cases',
      'They only apply to incompressible fluids',
    ],
    correctIndex: 0,
    explanation: 'In 3D, the Navier-Stokes existence and smoothness problem asks whether solutions remain smooth for all time given smooth initial data, or whether the velocity field can become infinite in finite time. This $1M Clay Institute problem remains unsolved.',
    realWorld: 'Despite the theoretical gap, computational fluid dynamics (CFD) uses numerical Navier-Stokes solutions daily for aircraft design, weather prediction, and cardiovascular simulation.',
    hint: 'The 2D case was solved in the 1960s. The 3D case has resisted all attempts for over 60 years.',
  },
  {
    id: 21004,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'Kolmogorov\'s theory of turbulence (K41) predicts that in the inertial range, the energy spectrum $E(k)$ scales as:',
    options: [
      '$E(k) \\propto k^{-5/3}$ — the famous five-thirds law',
      '$E(k) \\propto k^{-2}$ — inverse square law',
      '$E(k) \\propto k^{-1}$ — pink noise spectrum',
      '$E(k) \\propto e^{-k}$ — exponential decay',
    ],
    correctIndex: 0,
    explanation: 'Kolmogorov\'s 1941 theory assumes energy cascades from large to small scales at a constant rate $\\varepsilon$. Dimensional analysis yields $E(k) = C_K \\varepsilon^{2/3} k^{-5/3}$, one of the most experimentally verified scaling laws in physics.',
    realWorld: 'The $-5/3$ law is observed in atmospheric turbulence, ocean currents, solar wind, and even financial markets. It\'s foundational for weather forecasting and pollutant dispersion modeling.',
    hint: 'Kolmogorov used dimensional analysis with only two parameters: energy dissipation rate $\\varepsilon$ and wavenumber $k$.',
  },
  {
    id: 21005,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'Physics-informed neural networks (PINNs) for fluid dynamics embed the Navier-Stokes equations by:',
    options: [
      'Adding PDE residuals as penalty terms in the loss function, enforcing physics without labeled data',
      'Training on millions of CFD simulation snapshots only',
      'Replacing differential equations with lookup tables',
      'Using reinforcement learning to discover new fluid equations',
    ],
    correctIndex: 0,
    explanation: 'PINNs minimize $\\mathcal{L} = \\mathcal{L}_{\\text{data}} + \\lambda \\mathcal{L}_{\\text{PDE}}$ where $\\mathcal{L}_{\\text{PDE}}$ penalizes violations of the Navier-Stokes equations at collocation points. Automatic differentiation computes the PDE residuals through the network.',
    realWorld: 'PINNs enable real-time fluid simulation for surgical planning, turbine blade optimization, and urban wind modeling — solving problems where full CFD would take days.',
    hint: 'The neural network learns to satisfy the physics equations as soft constraints, not just fit data.',
  },
  {
    id: 21006,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'The Mach number $Ma = v/c_s$ determines compressibility effects. At transonic speeds ($Ma \\approx 1$), the critical phenomenon is:',
    options: [
      'Shock wave formation — abrupt, discontinuous changes in pressure, density, and temperature',
      'Complete laminar-to-turbulent transition',
      'Fluid cavitation and bubble collapse',
      'Reversal of Bernoulli\'s principle',
    ],
    correctIndex: 0,
    explanation: 'When flow locally exceeds $Ma = 1$, information cannot propagate upstream. Pressure disturbances pile up into shock waves — discontinuities where entropy increases irreversibly. This is fundamentally different from subsonic flow.',
    realWorld: 'Shock waves cause sonic booms, limit aircraft efficiency near $Ma = 1$ (the "sound barrier"), and are exploited in scramjet engines and medical lithotripsy (kidney stone treatment).',
    hint: 'Below $Ma = 1$, pressure waves can "warn" the fluid ahead. Above $Ma = 1$, they can\'t — creating a sudden discontinuity.',
  },
];
