import type { Question } from '../types';

export const fluidDynamicsQuestions: Question[] = [
  {
    id: 21001, topic: 'fluid-dynamics', difficulty: 'easy',
    question: 'The Reynolds number compares:',
    options: [
      'Inertial effects with viscous effects',
      'Pressure effects with thermal effects',
      'Acoustic speed with light speed',
      'Surface tension with gravity only',
    ],
    correctIndex: 0,
    explanation: 'Reynolds number is a dimensionless ratio of inertial to viscous effects and helps characterize flow regimes for a specified geometry.',
    realWorld: 'Engineers use Reynolds-number similarity in pipes, aircraft tests, blood-flow studies, vehicles, and industrial fluid systems.',
    hint: 'Large values mean inertia is strong relative to viscosity.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21002, topic: 'fluid-dynamics', difficulty: 'easy',
    question: 'For steady incompressible inviscid flow along a streamline at fixed height, Bernoulli\'s equation implies that higher speed is associated with:',
    options: [
      'Higher static pressure',
      'Lower static pressure',
      'Zero density',
      'Infinite viscosity',
    ],
    correctIndex: 1,
    explanation: 'Under Bernoulli\'s assumptions, the sum of static pressure and kinetic-energy density is constant along a streamline at fixed elevation.',
    realWorld: 'Bernoulli reasoning is useful in Venturi meters, nozzles, ducts, and many first-pass flow estimates when its assumptions are appropriate.',
    hint: 'At fixed height, kinetic and pressure terms trade off.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21007, topic: 'fluid-dynamics', difficulty: 'easy',
    question: 'For an incompressible velocity field, mass conservation requires:',
    options: [
      '$\\nabla \\times \\mathbf{u}=0$ everywhere',
      '$\\partial_t \\mathbf{u}=0$ everywhere',
      '$\\nabla \\cdot \\mathbf{u}=0$',
      '$\\mathbf{u}=0$ on every boundary',
    ],
    correctIndex: 2,
    explanation: 'For constant-density incompressible flow, the continuity equation reduces to a divergence-free velocity field.',
    realWorld: 'This constraint is central to incompressible CFD, water-flow models, aerodynamics at low Mach number, and many laboratory flows.',
    hint: 'No local accumulation of an incompressible fluid means zero velocity divergence.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21003, topic: 'fluid-dynamics', difficulty: 'hard',
    question: 'The three-dimensional Navier-Stokes Millennium Problem asks whether smooth incompressible solutions from smooth initial data:',
    options: [
      'Must always become periodic',
      'Must always conserve vorticity pointwise',
      'Can be represented by finite polynomials',
      'Remain globally smooth or can develop singularities',
    ],
    correctIndex: 3,
    explanation: 'For the specified three-dimensional incompressible Navier-Stokes problem, it is unknown whether sufficiently smooth initial data always yield global smooth solutions or whether finite-time singularities can occur.',
    realWorld: 'The equations remain the workhorse of fluid simulation even though this foundational mathematical regularity question is unresolved.',
    hint: 'The unresolved issue is global regularity versus blow-up.',
    sources: [{
      title: 'Navier-Stokes Equation',
      url: 'https://www.claymath.org/millennium/navier-stokes-equation/',
      publisher: 'Clay Mathematics Institute',
    }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 21004, topic: 'fluid-dynamics', difficulty: 'hard',
    question: 'Kolmogorov\'s 1941 inertial-range theory predicts an energy spectrum proportional to:',
    options: ['$k^{-5/3}$', '$k^{-1/2}$', '$k^{2}$', '$e^{-k^2}$'],
    correctIndex: 0,
    explanation: 'Under the idealized K41 assumptions, dimensional analysis gives an inertial-range energy spectrum proportional to $\\varepsilon^{2/3}k^{-5/3}$.',
    realWorld: 'The five-thirds scaling is a reference point for turbulence measurements in laboratory, atmospheric, oceanic, and astrophysical flows.',
    hint: 'The famous exponent is between minus one and minus two.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21008, topic: 'fluid-dynamics', difficulty: 'hard',
    question: 'The vorticity field of a velocity field $\\mathbf{u}$ is:',
    options: [
      '$\\nabla \\cdot \\mathbf{u}$',
      '$\\nabla \\times \\mathbf{u}$',
      '$\\nabla^2 p$',
      '$\\partial_t p$',
    ],
    correctIndex: 1,
    explanation: 'Vorticity is the curl of velocity and measures local rotational tendency in the flow.',
    realWorld: 'Vorticity is central to vortex dynamics, wakes, boundary layers, turbulence, atmospheric flow, and aerodynamic lift generation.',
    hint: 'Local rotation is measured by a curl.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21005, topic: 'fluid-dynamics', difficulty: 'sota',
    question: 'Physics-informed neural networks incorporate a governing PDE primarily by:',
    options: [
      'Replacing every derivative with a lookup table',
      'Using only experimental labels and no equations',
      'Penalizing PDE residuals in the training objective',
      'Restricting the network to linear activation functions',
    ],
    correctIndex: 2,
    explanation: 'PINNs use automatic differentiation to evaluate derivatives and add residuals of the governing equations and boundary conditions to the training objective.',
    realWorld: 'They are studied for forward and inverse PDE problems where observations are sparse or physical constraints are valuable.',
    hint: 'The network is trained not only to fit data but also to satisfy the equation.',
    paper: {
      title: 'Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations',
      url: 'https://doi.org/10.1016/j.jcp.2018.10.045',
      venue: 'Journal of Computational Physics',
      year: 2019,
    },
    reviewedAt: '2026-09-21',
  },
  {
    id: 21006, topic: 'fluid-dynamics', difficulty: 'sota',
    question: 'A normal shock in compressible flow is characterized by:',
    options: [
      'A smooth isentropic decrease in entropy',
      'No change in pressure or density',
      'A discontinuity that preserves stagnation pressure',
      'An abrupt irreversible rise in entropy',
    ],
    correctIndex: 3,
    explanation: 'Across a physical shock, pressure, density, temperature, and velocity change abruptly, while entropy increases and stagnation pressure decreases.',
    realWorld: 'Shock waves shape transonic and supersonic aircraft, nozzles, propulsion systems, explosions, and high-speed experimental facilities.',
    hint: 'A shock is not an isentropic compression.',
    sources: [{
      title: 'Normal Shock Wave Equations',
      url: 'https://www.grc.nasa.gov/www/k-12/airplane/normal.html',
      publisher: 'NASA Glenn Research Center',
    }],
    reviewedAt: '2026-09-21',
  },
  {
    id: 21009, topic: 'fluid-dynamics', difficulty: 'sota',
    question: 'A Fourier neural operator is designed to learn:',
    options: [
      'An operator mapping input functions to solution functions across a PDE family',
      'One scalar constant shared by all PDE instances',
      'Only a mesh-independent list of boundary coordinates',
      'A symbolic proof of existence for every PDE solution',
    ],
    correctIndex: 0,
    explanation: 'Neural operators learn mappings between function spaces; the Fourier neural operator parameterizes part of that mapping in Fourier space so one trained model can represent a family of parametric PDE solution maps.',
    realWorld: 'Operator-learning methods are researched as fast surrogates for repeated simulation, inverse problems, and scientific design loops.',
    hint: 'The target is a map from one function to another, not one fixed solution vector.',
    paper: {
      title: 'Fourier Neural Operator for Parametric Partial Differential Equations',
      url: 'https://openreview.net/forum?id=c8P9NQVtmnO',
      venue: 'ICLR',
      year: 2021,
    },
    reviewedAt: '2026-09-21',
  },
];
