import type { Question } from '../types';

export const fluidDynamicsQuestions: Question[] = [
  {
    id: 21001,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'The Reynolds number compares which two effects in a flow?',
    options: [
      'Inertial effects to viscous effects',
      'Pressure effects to thermal effects',
      'Acoustic effects to gravitational effects',
      'Surface tension effects to compressibility effects',
    ],
    correctIndex: 0,
    explanation: 'The Reynolds number $Re = \\rho v L / \\mu$ measures the relative importance of inertial and viscous effects. Low Reynolds number flows are viscosity-dominated, while high Reynolds number flows are more prone to complex inertial behavior and turbulence.',
    realWorld: 'Reynolds-number similarity is used when testing aircraft, vehicles, pipes, blood-flow devices, and scale models in wind or water tunnels.',
    hint: 'The numerator contains inertia; the denominator contains viscosity.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21002,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'For steady incompressible flow through a pipe that narrows, the average flow speed usually:',
    options: [
      'Decreases because fluid must accumulate upstream',
      'Increases because the same flow rate passes through less area',
      'Falls to zero because the walls are closer together',
      'Stays fixed because incompressible flow cannot accelerate',
    ],
    correctIndex: 1,
    explanation: 'For steady incompressible flow, continuity gives $A_1 v_1 = A_2 v_2$. If cross-sectional area decreases, average velocity must increase to preserve volumetric flow rate.',
    realWorld: 'Continuity underlies nozzle design, Venturi meters, blood-flow estimates, and many internal-flow calculations.',
    hint: 'The same amount of incompressible fluid must pass each cross section per unit time.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21007,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'In a stationary liquid of uniform density, pressure increases with depth approximately as:',
    options: [
      '$\\Delta p = \\rho g / h$',
      '$\\Delta p = g h / \\rho$',
      '$\\Delta p = \\rho g h$',
      '$\\Delta p = \\rho h / g$',
    ],
    correctIndex: 2,
    explanation: 'Hydrostatic balance gives $dp/dz=-\\rho g$. Over a depth change $h$ in a constant-density liquid, the pressure increase is $\\Delta p=\\rho g h$.',
    realWorld: 'Hydrostatic pressure matters in dams, diving, hydraulic systems, atmospheric approximations, and medical pressure measurements.',
    hint: 'Pressure must increase enough with depth to support the weight of the fluid above.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21008,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'Dynamic viscosity most directly measures a fluid\'s:',
    options: [
      'Resistance to heat conduction between fluid layers',
      'Resistance to density changes caused by pressure',
      'Ability to store gravitational potential energy',
      'Resistance to shear between neighboring fluid layers',
    ],
    correctIndex: 3,
    explanation: 'Dynamic viscosity relates shear stress to velocity gradient for a Newtonian fluid. A more viscous fluid requires greater shear stress to produce the same rate of deformation.',
    realWorld: 'Viscosity controls lubrication, pipeline pressure losses, coating flows, polymer processing, and microscale fluid motion.',
    hint: 'Think of the difference between honey and water when adjacent layers slide past each other.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21009,
    topic: 'fluid-dynamics',
    difficulty: 'easy',
    question: 'Bernoulli\'s equation for an ideal steady flow along a streamline expresses conservation of:',
    options: [
      'Mechanical energy per unit volume',
      'Mass density at every point',
      'Vorticity magnitude at every point',
      'Entropy across every possible shock',
    ],
    correctIndex: 0,
    explanation: 'For steady, inviscid, incompressible flow along a streamline, $p + \\tfrac12\\rho v^2 + \\rho g z$ remains constant. The terms represent pressure, kinetic, and gravitational potential energy per unit volume.',
    realWorld: 'Bernoulli-based reasoning appears in flow meters, nozzles, siphons, and introductory aerodynamic and hydraulic analyses.',
    hint: 'The equation trades pressure, kinetic, and gravitational terms against one another.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21003,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'What remains unresolved in the three-dimensional incompressible Navier-Stokes Millennium Prize problem?',
    options: [
      'Whether incompressible solutions conserve total mass',
      'Whether smooth 3D solutions can form finite-time singularities',
      'Whether viscosity has a consistent system of physical units',
      'Whether two-dimensional flows can be simulated numerically',
    ],
    correctIndex: 1,
    explanation: 'The open problem asks whether sufficiently regular three-dimensional incompressible Navier-Stokes initial data always produce globally smooth solutions, or whether singularities can develop in finite time.',
    realWorld: 'Computational fluid dynamics remains extremely useful even though this global mathematical regularity question for the idealized equations is unresolved.',
    hint: 'The issue is mathematical regularity in three dimensions, not whether engineers can run CFD.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21004,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'Kolmogorov\'s 1941 inertial-range theory predicts an energy spectrum proportional to:',
    options: [
      '$k^{-1}$',
      '$k^{-2}$',
      '$k^{-5/3}$',
      '$e^{-k}$',
    ],
    correctIndex: 2,
    explanation: 'Under the assumptions of homogeneous, isotropic turbulence with a scale-local energy cascade, dimensional analysis gives $E(k) \\propto \\varepsilon^{2/3}k^{-5/3}$ in the inertial range.',
    realWorld: 'The five-thirds spectrum is a central benchmark in turbulence measurements, simulations, atmospheric flows, and model development.',
    hint: 'The famous exponent lies between -1 and -2.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21010,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'A boundary layer is especially prone to separate from a surface when it encounters:',
    options: [
      'A strong favorable pressure gradient that accelerates near-wall flow',
      'Exactly zero pressure gradient over the entire surface',
      'A perfectly inviscid wall with no velocity gradients',
      'A sufficiently strong adverse pressure gradient that decelerates near-wall flow',
    ],
    correctIndex: 3,
    explanation: 'An adverse pressure gradient means pressure rises in the flow direction. The low-momentum fluid near the wall can decelerate to zero and reverse, causing the boundary layer to detach.',
    realWorld: 'Flow separation strongly affects aircraft stall, diffuser performance, vehicle drag, turbomachinery, and bluff-body wakes.',
    hint: 'Near-wall fluid has little momentum and struggles when pressure rises downstream.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21011,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'Fluid vorticity is defined as:',
    options: [
      'The curl of the velocity field, $\\boldsymbol{\\omega}=\\nabla\\times\\mathbf{u}$',
      'The divergence of pressure, $\\nabla\\cdot p$',
      'The time derivative of density, $\\partial\\rho/\\partial t$',
      'The gradient of temperature divided by viscosity',
    ],
    correctIndex: 0,
    explanation: 'Vorticity is the curl of velocity and measures local rotational motion of the flow. It is a vector field whose evolution is central to vortex dynamics and turbulence.',
    realWorld: 'Vorticity analysis is used to study aircraft wakes, tornadoes, mixing layers, rotating machinery, and turbulent coherent structures.',
    hint: 'It is the rotational counterpart to divergence.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21012,
    topic: 'fluid-dynamics',
    difficulty: 'hard',
    question: 'For many explicit CFD schemes, the Courant-Friedrichs-Lewy condition limits the time step so that:',
    options: [
      'Viscosity becomes numerically equal to fluid density',
      'A signal cannot cross too many grid cells in one step',
      'Every computational cell has exactly the same pressure',
      'The computed Reynolds number always remains below one',
    ],
    correctIndex: 1,
    explanation: 'The CFL condition links time step, grid spacing, and characteristic signal speed. Explicit methods generally require a time step small enough that numerical information propagation remains compatible with the discretization.',
    realWorld: 'CFL restrictions can dominate runtime in simulations of compressible flow, waves, shocks, and fine-grid transient CFD.',
    hint: 'Compare how far a physical signal travels during one numerical time step with the grid spacing.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 21005,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'Physics-informed neural networks incorporate governing PDEs primarily by:',
    options: [
      'Replacing all derivatives with a fixed lookup table',
      'Training only on CFD snapshots without physics terms',
      'Penalizing governing-equation residuals during training',
      'Restricting every network layer to a finite-volume stencil',
    ],
    correctIndex: 2,
    explanation: 'PINNs use automatic differentiation to evaluate PDE residuals and penalize violations of governing equations alongside available observations and boundary or initial conditions.',
    realWorld: 'PINNs are studied for forward and inverse problems where data are sparse and physical equations provide additional structure, though training difficulty remains an active research area.',
    hint: 'The physics enters as a constraint on the learned function, often through the loss.',
    paper: { title: 'Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations', url: 'https://doi.org/10.1016/j.jcp.2018.10.045', venue: 'Journal of Computational Physics', year: 2019 },
    reviewedAt: '2026-09-21',
  },
  {
    id: 21006,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'A Fourier Neural Operator differs from a conventional single-instance PDE solver because it is designed to:',
    options: [
      'Eliminate all discretization and evaluate an exact analytic fluid solution',
      'Model only one scalar value from a fixed input vector',
      'Guarantee conservation laws without any architectural or training choices',
      'Learn a mapping between input functions and solution functions across a family of PDE instances',
    ],
    correctIndex: 3,
    explanation: 'Neural operators aim to learn maps between function spaces. The Fourier Neural Operator parameterizes part of that mapping in Fourier space and can approximate solution operators across varying PDE inputs.',
    realWorld: 'Neural operators are researched as fast surrogate models for repeated PDE solves, including Navier-Stokes-type systems, while accuracy and physical consistency remain important validation concerns.',
    hint: 'The target is an operator that maps whole fields to whole solution fields, not one fixed numerical solve.',
    paper: { title: 'Fourier Neural Operator for Parametric Partial Differential Equations', url: 'https://arxiv.org/abs/2010.08895', venue: 'ICLR', year: 2021 },
    reviewedAt: '2026-09-21',
  },
  {
    id: 21013,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'In large-eddy simulation of turbulent flow, the standard modeling split is to:',
    options: [
      'Resolve the larger turbulent motions while modeling the effects of unresolved subgrid scales',
      'Model every turbulent scale and resolve only the mean velocity',
      'Resolve molecular collisions directly and discard the Navier-Stokes equations',
      'Assume all unresolved motion has zero influence on resolved scales',
    ],
    correctIndex: 0,
    explanation: 'LES applies spatial filtering so that large, energetic eddies are represented on the grid while the net influence of smaller unresolved motions is represented with a subgrid-scale treatment.',
    realWorld: 'LES is widely used when engineers and researchers need more unsteady turbulent detail than typical Reynolds-averaged models provide but cannot afford full DNS.',
    hint: 'The name tells you which eddies are explicitly resolved.',
    sources: [{ title: 'Large Eddy simulation of turbulence: A subgrid scale model including shear, vorticity, rotation, and buoyancy', url: 'https://ntrs.nasa.gov/citations/19950029134', publisher: 'NASA Technical Reports Server', year: 1994 }],
    reviewedAt: '2026-09-21',
  },
  {
    id: 21014,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'What distinguishes direct numerical simulation of turbulence from LES and RANS approaches?',
    options: [
      'DNS assumes turbulent fluctuations are Gaussian everywhere',
      'DNS resolves turbulent scales directly instead of modeling unresolved eddies',
      'DNS removes viscosity from the equations to reduce computational cost',
      'DNS computes only the mean flow and discards fluctuations',
    ],
    correctIndex: 1,
    explanation: 'DNS numerically resolves the full range of dynamically relevant turbulent scales down toward the dissipative scales. The required spatial and temporal resolution grows rapidly with Reynolds number, making DNS primarily a research tool for limited configurations.',
    realWorld: 'High-quality DNS databases provide detailed turbulence physics and benchmark data for experiments, reduced-order models, LES closures, and machine-learning methods.',
    hint: 'The word direct means the turbulent motions themselves are resolved instead of closed with a turbulence model.',
    paper: { title: 'Direct Numerical Simulation: A Tool in Turbulence Research', url: 'https://doi.org/10.1146/annurev.fluid.30.1.539', venue: 'Annual Review of Fluid Mechanics', year: 1998 },
    reviewedAt: '2026-09-21',
  },
  {
    id: 21015,
    topic: 'fluid-dynamics',
    difficulty: 'sota',
    question: 'One strategy used in machine-learning-accelerated CFD is to:',
    options: [
      'Discard the numerical solver and infer all future flows from a single scalar measurement',
      'Force every turbulent flow onto the same coarse-grid solution regardless of geometry',
      'Learn corrections or model components that let a coarser numerical solver reproduce more fine-scale behavior',
      'Replace conservation equations with image-classification labels at each grid cell',
    ],
    correctIndex: 2,
    explanation: 'Hybrid approaches can retain a conventional discretized fluid solver while using learned components to correct unresolved or discretization effects, improving accuracy or effective resolution at lower computational cost.',
    realWorld: 'Research has demonstrated learned interpolation and correction strategies that accelerate two-dimensional CFD while preserving the structure of established numerical solvers.',
    hint: 'The machine-learning component augments the solver instead of pretending the governing equations do not exist.',
    paper: { title: 'Machine learning-accelerated computational fluid dynamics', url: 'https://doi.org/10.1073/pnas.2101784118', venue: 'Proceedings of the National Academy of Sciences', year: 2021 },
    reviewedAt: '2026-09-21',
  },
];
