import type { GlossaryTerm } from './types';

export const aiMlTerms: GlossaryTerm[] = [
  {
    id: 'transformer',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Transformer',
    definition: 'A neural network architecture that processes sequences entirely through self-attention, replacing recurrence and convolution. Introduced in "Attention Is All You Need" (2017) by Vaswani et al. The encoder-decoder structure uses multi-head attention, positional encodings, and layer normalization to achieve massive parallelism and state-of-the-art performance on virtually every sequence task.',
    example: 'GPT-4, Claude, Gemini, BERT, LLaMA, AlphaFold, Stable Diffusion — virtually every frontier AI system is built on Transformers.',
    formula: '$\\text{MultiHead}(Q,K,V) = \\text{Concat}(\\text{head}_1,\\ldots,\\text{head}_h)W^O$',
    latex: '\\text{MultiHead}(Q,K,V) = \\text{Concat}(\\text{head}_1,\\ldots,\\text{head}_h)W^O',
    code: '-- Transformer pseudocode\ndef transformer_block(x):\n  attn = multi_head_attention(q=x, k=x, v=x)\n  x = layer_norm(x + attn)       -- residual + norm\n  ff = swiglu(linear(x))          -- feed-forward\n  return layer_norm(x + ff)       -- residual + norm',
    related: ['attention-mechanism', 'positional-encoding', 'mixture-of-experts'],
    formulaLinks: ['Multi-Head Attention (Attention Is All You Need)', 'Residual Connection (ResNet)'],
    thinkerLinks: ['geoffrey-hinton'],
    difficulty: 'intermediate',
  },
  {
    id: 'attention-mechanism',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Attention Mechanism',
    definition: 'A differentiable addressing scheme that computes a weighted sum of value vectors, where weights are determined by the compatibility (dot product) between query and key vectors: $\\text{Attn}(Q,K,V) = \\text{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$. The $\\sqrt{d_k}$ scaling prevents softmax saturation. Self-attention (Q=K=V from same input) lets each token attend to all others, capturing long-range dependencies in $O(1)$ sequential steps.',
    example: 'In "The cat sat on the mat because it was tired," attention lets "it" attend strongly to "cat" regardless of distance.',
    formula: '$\\text{Attn}(Q,K,V) = \\text{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$',
    latex: '\\text{Attn}(Q,K,V) = \\text{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V',
    code: 'def scaled_dot_product_attention(Q, K, V):\n  d_k = Q.shape[-1]\n  scores = Q @ K.transpose(-2, -1) / sqrt(d_k)\n  weights = softmax(scores, dim=-1)\n  return weights @ V',
    related: ['transformer', 'flash-attention', 'group-query-attention'],
    formulaLinks: ['Multi-Head Attention (Attention Is All You Need)', 'FlashAttention (IO-Aware Exact Attention)'],
    difficulty: 'intermediate',
  },
  {
    id: 'tokenization',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Tokenization',
    definition: 'The process of converting raw text into a sequence of discrete tokens from a fixed vocabulary. Modern LLMs use subword tokenization algorithms like Byte Pair Encoding (BPE), which iteratively merges the most frequent byte pairs until reaching a target vocabulary size (typically 32K–128K tokens). This balances character-level flexibility (handling any input) with word-level efficiency (common words are single tokens).',
    example: '"unhappiness" might tokenize as ["un", "happiness"] in BPE, while rare words like "defenestration" split into more pieces.',
    formula: '$\\text{Merge: } (a,b) \\to ab \\;\\text{where}\\; (a,b) = \\arg\\max \\text{freq}(a,b)$',
    latex: '\\text{Merge: } (a,b) \\to ab \\;\\text{where}\\; (a,b) = \\arg\\max \\text{freq}(a,b)',
    code: 'def bpe_merge(vocab, num_merges):\n  for i in range(num_merges):\n    pairs = get_pair_frequencies(vocab)\n    best = max(pairs, key=pairs.get)\n    vocab = merge_pair(vocab, best)\n  return vocab',
    related: ['transformer'],
    formulaLinks: ['Byte Pair Encoding (BPE) Tokenization'],
    difficulty: 'intro',
  },
  {
    id: 'mixture-of-experts',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Mixture of Experts (MoE)',
    definition: 'An architecture that routes each input to a sparse subset of $K$ out of $N$ expert sub-networks via a learned gating function: $y = \\sum_i G(x)_i \\cdot E_i(x)$. This achieves massive model capacity (trillions of parameters) with constant compute per token, since only $K$ experts are active. Load balancing losses prevent expert collapse. The Switch Transformer (2022) scaled to 1.6T parameters; Mixtral 8×7B demonstrated GPT-3.5-level performance with MoE.',
    example: 'Mixtral 8×7B uses 8 expert FFN blocks but activates only 2 per token, achieving 47B total params but ~13B active compute.',
    formula: '$y = \\sum_{i=1}^{N} G(x)_i \\cdot E_i(x)$',
    latex: 'y = \\sum_{i=1}^{N} G(x)_i \\cdot E_i(x)',
    code: 'def moe_layer(x, experts, gate):\n  weights = topk(softmax(gate(x)), k=2)\n  output = sum(w * expert(x) for w, expert\n               in zip(weights, selected_experts))\n  return output',
    related: ['transformer', 'attention-mechanism'],
    formulaLinks: ['Mixture of Experts (MoE) Gating'],
    difficulty: 'advanced',
  },
  {
    id: 'flow-matching',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Flow Matching',
    definition: 'A generative modeling framework that learns a velocity field $v_\\theta$ transporting samples from a noise distribution to the data distribution along straight-line paths: $\\psi_t(x_0,x_1) = (1-t)x_0 + tx_1$. Simpler than diffusion models (no noise schedules, no score matching), flow matching trains by regressing the velocity at interpolated points. Optimal transport variants (OT-CFM) further straighten paths for faster sampling.',
    example: 'Stable Diffusion 3 and Flux use flow matching instead of DDPM, generating high-quality images in fewer sampling steps.',
    formula: '$\\psi_t(x_0, x_1) = (1-t)x_0 + t x_1$',
    latex: '\\psi_t(x_0, x_1) = (1-t)x_0 + t x_1',
    code: 'def flow_matching_loss(model, x1):\n  t = uniform(0, 1)\n  x0 = randn_like(x1)           # noise\n  xt = (1 - t) * x0 + t * x1    # interpolate\n  target_v = x1 - x0            # straight-line velocity\n  pred_v = model(xt, t)\n  return mse(pred_v, target_v)',
    related: ['diffusion-model', 'classifier-free-guidance'],
    formulaLinks: ['Flow Matching (Conditional Flow)'],
    difficulty: 'advanced',
  },
  {
    id: 'flash-attention',
    field: 'cs',
    topic: 'ai-ml',
    term: 'FlashAttention',
    definition: 'An IO-aware exact attention algorithm that avoids materializing the $N \\times N$ attention matrix in GPU high-bandwidth memory (HBM). By tiling the Q, K, V matrices into SRAM-sized blocks and using online softmax (numerically stable running computation), FlashAttention reduces HBM accesses from $O(N^2)$ to $O(N^2 d/M)$ where $M$ is SRAM size. Result: 2–4× wall-clock speedup with $O(N)$ memory.',
    example: 'Every major LLM (GPT-4, LLaMA 3, Claude) uses FlashAttention for training and inference.',
    formula: '$O(N^2 d / M) \\text{ HBM accesses vs } O(N^2) \\text{ naive}$',
    latex: 'O(N^2 d / M) \\text{ HBM accesses}',
    related: ['attention-mechanism', 'group-query-attention'],
    formulaLinks: ['FlashAttention (IO-Aware Exact Attention)'],
    difficulty: 'advanced',
  },
  {
    id: 'group-query-attention',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Group Query Attention (GQA)',
    definition: 'A variant of multi-head attention where multiple query heads share a single key-value head, reducing KV cache memory by a factor of $h/g$ (where $h$ = query heads, $g$ = KV groups). Interpolates between multi-head attention ($g=h$) and multi-query attention ($g=1$). Standard in production LLMs since LLaMA 2.',
    example: 'LLaMA 2 70B uses 64 query heads but only 8 KV heads (GQA with g=8), cutting KV cache by 8×.',
    related: ['attention-mechanism', 'flash-attention', 'transformer'],
    formulaLinks: ['Group Query Attention (GQA)'],
    difficulty: 'advanced',
  },
  {
    id: 'diffusion-model',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Diffusion Model',
    definition: 'A generative model that learns to reverse a gradual noising process. The forward process adds Gaussian noise over $T$ steps: $q(x_t|x_0) = \\mathcal{N}(\\sqrt{\\bar\\alpha_t}\\,x_0, (1-\\bar\\alpha_t)I)$. A neural network learns to denoise (predict the added noise), enabling generation from pure noise via iterative denoising. Achieves state-of-the-art image, video, and audio generation.',
    example: 'DALL·E 2/3, Stable Diffusion, Midjourney, and Sora all use diffusion models for generation.',
    formula: '$q(x_t|x_0) = \\mathcal{N}(\\sqrt{\\bar\\alpha_t}\\,x_0,\\;(1-\\bar\\alpha_t)I)$',
    latex: 'q(x_t|x_0) = \\mathcal{N}(\\sqrt{\\bar\\alpha_t}\\,x_0,\\;(1-\\bar\\alpha_t)I)',
    related: ['flow-matching', 'classifier-free-guidance'],
    formulaLinks: ['Diffusion Forward Process (DDPM)'],
    difficulty: 'intermediate',
  },
  {
    id: 'classifier-free-guidance',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Classifier-Free Guidance (CFG)',
    definition: 'A technique for improving conditional generation quality in diffusion/flow models by extrapolating between conditional and unconditional predictions: $\\hat\\epsilon = (1+w)\\epsilon_\\theta(x_t,c) - w\\,\\epsilon_\\theta(x_t,\\varnothing)$. Higher guidance scale $w$ improves text-image alignment at the cost of diversity. The key innovation behind high-quality text-to-image generation.',
    example: 'Setting guidance scale w=7.5 in Stable Diffusion produces images that closely follow the text prompt.',
    formula: '$\\hat\\epsilon = (1+w)\\epsilon_\\theta(x_t,c) - w\\,\\epsilon_\\theta(x_t,\\varnothing)$',
    latex: '\\hat\\epsilon = (1+w)\\epsilon_\\theta(x_t,c) - w\\,\\epsilon_\\theta(x_t,\\varnothing)',
    related: ['diffusion-model', 'flow-matching'],
    formulaLinks: ['Classifier-Free Guidance (CFG)'],
    difficulty: 'advanced',
  },
  {
    id: 'positional-encoding',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Positional Encoding',
    definition: 'Since attention is permutation-invariant, positional information must be injected explicitly. The original Transformer used sinusoidal encodings; modern LLMs use Rotary Position Embedding (RoPE), which encodes position by rotating query/key vectors in 2D subspaces so that dot products naturally depend on relative position $(m-n)$.',
    example: 'RoPE enables LLaMA to generalize to longer contexts than seen during training via NTK-aware scaling.',
    formula: '$f(x_m,m) = R_m \\cdot x_m, \\quad R_m = \\text{block-diag rotation by } m\\theta_i$',
    latex: 'f(x_m,m) = R_m \\cdot x_m',
    related: ['transformer', 'attention-mechanism'],
    formulaLinks: ['Rotary Position Embedding (RoPE)'],
    difficulty: 'intermediate',
  },
  {
    id: 'lora',
    field: 'cs',
    topic: 'ai-ml',
    term: 'LoRA (Low-Rank Adaptation)',
    definition: 'A parameter-efficient fine-tuning method that injects trainable low-rank matrices $\\Delta W = BA$ alongside frozen pretrained weights $W_0$, where $B \\in \\mathbb{R}^{d \\times r}$, $A \\in \\mathbb{R}^{r \\times k}$, and rank $r \\ll \\min(d,k)$. Reduces trainable parameters by 10,000× while matching full fine-tuning performance. The standard method for adapting LLMs.',
    example: 'Fine-tuning LLaMA 70B with LoRA rank=16 requires only ~20M trainable parameters instead of 70B.',
    formula: '$W\' = W_0 + BA, \\quad r \\ll \\min(d,k)$',
    latex: 'W\' = W_0 + BA, \\quad r \\ll \\min(d,k)',
    related: ['transformer'],
    formulaLinks: ['LoRA (Low-Rank Adaptation)'],
    difficulty: 'intermediate',
  },
  {
    id: 'rlhf',
    field: 'cs',
    topic: 'ai-ml',
    term: 'RLHF (Reinforcement Learning from Human Feedback)',
    definition: 'An alignment technique that fine-tunes language models using human preference data. A reward model $r_\\phi$ is trained on pairwise preference judgments (Bradley-Terry model), then the policy is optimized via PPO to maximize reward while staying close to a reference policy via KL penalty: $\\max_\\pi \\mathbb{E}[r_\\phi(x,y) - \\beta D_{KL}(\\pi \\| \\pi_{\\text{ref}})]$. DPO simplifies this by eliminating the reward model entirely.',
    example: 'RLHF transformed GPT-3 into ChatGPT by aligning it with human preferences for helpfulness and safety.',
    formula: '$\\max_\\pi \\mathbb{E}[r_\\phi(x,y) - \\beta D_{KL}(\\pi \\| \\pi_{\\text{ref}})]$',
    latex: '\\max_\\pi \\mathbb{E}[r_\\phi(x,y) - \\beta D_{KL}(\\pi \\| \\pi_{\\text{ref}})]',
    related: ['transformer'],
    formulaLinks: ['RLHF Objective (PPO for Language Models)', 'DPO (Direct Preference Optimization)', 'Reward Modeling (Bradley-Terry for LLMs)'],
    difficulty: 'advanced',
  },
  {
    id: 'kolmogorov-arnold-network',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Kolmogorov–Arnold Network (KAN)',
    definition: 'A neural architecture based on the Kolmogorov–Arnold representation theorem: any multivariate continuous function can be decomposed as $f(x_1,\\ldots,x_n) = \\sum_{q=0}^{2n} \\Phi_q(\\sum_p \\phi_{q,p}(x_p))$. Unlike MLPs (fixed activations on nodes), KANs place learnable activation functions (B-splines) on edges. This yields better accuracy with fewer parameters on scientific tasks and produces interpretable, symbolic outputs.',
    example: 'KANs rediscovered known physics equations from data, outputting human-readable symbolic formulas.',
    formula: '$f(\\mathbf{x}) = \\sum_{q=0}^{2n} \\Phi_q\\!\\left(\\sum_{p=1}^{n} \\phi_{q,p}(x_p)\\right)$',
    latex: 'f(\\mathbf{x}) = \\sum_{q=0}^{2n} \\Phi_q\\!\\left(\\sum_{p=1}^{n} \\phi_{q,p}(x_p)\\right)',
    related: ['transformer'],
    formulaLinks: ['Kolmogorov–Arnold Network (KAN)'],
    difficulty: 'advanced',
  },
  {
    id: 'neural-scaling-laws',
    field: 'cs',
    topic: 'ai-ml',
    term: 'Neural Scaling Laws',
    definition: 'Empirical power-law relationships between model performance (loss $L$) and compute budget, model size $N$, and dataset size $D$: $L(N,D) = A/N^\\alpha + B/D^\\beta + L_\\infty$. The Chinchilla result (2022) showed that optimal compute allocation scales $N$ and $D$ equally, reshaping LLM training strategies industry-wide.',
    example: 'Chinchilla (70B params, 1.4T tokens) outperformed the 3× larger Gopher (280B) by training on more data.',
    formula: '$L(N,D) = \\frac{A}{N^\\alpha} + \\frac{B}{D^\\beta} + L_\\infty$',
    latex: 'L(N,D) = \\frac{A}{N^\\alpha} + \\frac{B}{D^\\beta} + L_\\infty',
    related: ['transformer'],
    formulaLinks: ['Chinchilla Scaling Law'],
    difficulty: 'advanced',
  },
];
