import type { GlossaryTerm } from './types';

export const opticsTerms: GlossaryTerm[] = [
  { id: 'refraction', field: 'physics', term: 'Refraction', definition: 'The bending of light as it passes between media with different refractive indices, governed by Snell\'s law: $n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2$.', example: 'A straw appears bent in a glass of water due to refraction at the air-water interface.' },
  { id: 'diffraction', field: 'physics', term: 'Diffraction', definition: 'The spreading of waves around obstacles or through apertures, significant when the obstacle size is comparable to the wavelength.', example: 'CD/DVD surfaces produce rainbow patterns because their tracks act as diffraction gratings.' },
  { id: 'total-internal-reflection', field: 'physics', term: 'Total Internal Reflection', definition: 'When light hits a boundary at an angle greater than the critical angle $\\theta_c = \\arcsin(n_2/n_1)$, it is completely reflected back into the denser medium.', example: 'Fibre optic cables transmit data as light bouncing inside glass fibres via total internal reflection.' },
  { id: 'polarization', field: 'physics', term: 'Polarisation', definition: 'The restriction of a transverse wave\'s oscillation to a single plane. Unpolarised light vibrates in all directions perpendicular to propagation.', example: 'Polarised sunglasses block glare by filtering horizontally polarised light reflected off surfaces.' },
  { id: 'coherence', field: 'physics', term: 'Coherence', definition: 'The property of waves maintaining a fixed phase relationship over time (temporal) or space (spatial), essential for interference and laser operation.', example: 'Lasers produce highly coherent light; incandescent bulbs produce incoherent light.' },
  { id: 'numerical-aperture', field: 'engineering', term: 'Numerical Aperture (NA)', definition: 'A measure of a lens\'s light-gathering ability: $NA = n \\sin\\theta$, where $\\theta$ is the half-angle of the maximum cone of light. Higher NA = better resolution.', example: 'EUV lithography machines use mirrors with NA ≈ 0.33 to pattern sub-5nm chip features.' },
];

export const commsTerms: GlossaryTerm[] = [
  { id: 'bandwidth', field: 'engineering', term: 'Bandwidth', definition: 'The range of frequencies a channel can carry, measured in Hz. Higher bandwidth allows higher data rates per the Shannon–Hartley theorem.', example: '5G uses wider bandwidths (up to 400 MHz) than 4G to achieve multi-gigabit speeds.' },
  { id: 'modulation', field: 'engineering', term: 'Modulation', definition: 'Encoding information onto a carrier wave by varying its amplitude (AM), frequency (FM), or phase (PM/QAM).', example: 'WiFi uses QAM-1024: each symbol encodes 10 bits by combining 32 amplitude levels × 32 phase states.' },
  { id: 'multiplexing', field: 'engineering', term: 'Multiplexing', definition: 'Combining multiple signals on a single channel: time-division (TDM), frequency-division (FDM), code-division (CDM), or wavelength-division (WDM).', example: 'Undersea fibre cables use WDM to carry 100+ wavelengths simultaneously, each at 100+ Gbps.' },
  { id: 'error-correction', field: 'cs', term: 'Error-Correcting Code', definition: 'Adds redundant bits to data so the receiver can detect and correct transmission errors without retransmission. Examples: Hamming, Reed-Solomon, LDPC, Polar codes.', example: 'QR codes use Reed-Solomon coding — you can still scan them even when partly damaged or obscured.' },
  { id: 'antenna-gain', field: 'engineering', term: 'Antenna Gain', definition: 'The ratio of power radiated in a preferred direction to that of an isotropic antenna, measured in dBi. Higher gain = more directional beam.', example: 'Satellite dishes have high gain (~30-40 dBi) to communicate with spacecraft millions of km away.' },
  { id: 'ofdm', field: 'engineering', term: 'OFDM', definition: 'Orthogonal Frequency-Division Multiplexing splits a wideband channel into many narrow orthogonal subcarriers, each modulated independently. Robust against multipath fading.', example: 'WiFi (802.11a/g/n/ac/ax), 4G LTE, 5G NR, and DVB-T all use OFDM.' },
];

export const semiconductorTerms: GlossaryTerm[] = [
  { id: 'doping', field: 'physics', term: 'Doping', definition: 'Intentionally adding impurity atoms to a semiconductor to control its conductivity: n-type (extra electrons, e.g. phosphorus in Si) or p-type (holes, e.g. boron in Si).', example: 'A silicon solar cell is a p-n junction created by doping — the boundary generates voltage from sunlight.' },
  { id: 'mosfet', field: 'engineering', term: 'MOSFET', definition: 'Metal-Oxide-Semiconductor Field-Effect Transistor: a voltage at the gate controls current between source and drain. The building block of all modern digital circuits.', example: 'A modern Apple M3 chip contains ~25 billion MOSFETs, each switching billions of times per second.' },
  { id: 'band-gap', field: 'physics', term: 'Band Gap', definition: 'The energy difference $E_g$ between valence and conduction bands. Determines whether a material is a conductor ($E_g = 0$), semiconductor ($E_g \\sim 0.5{-}3$ eV), or insulator ($E_g > 4$ eV).', example: 'Silicon ($E_g = 1.1$ eV) is ideal for electronics; diamond ($E_g = 5.5$ eV) is an insulator.' },
  { id: 'photolithography', field: 'engineering', term: 'Photolithography', definition: 'Transferring circuit patterns onto a wafer using light: coat with photoresist, expose through a mask, develop, then etch. The resolution limit is $\\sim \\lambda/(2\\text{NA})$.', example: 'TSMC\'s 3nm process uses EUV lithography at 13.5nm wavelength to print features smaller than a virus.' },
  { id: 'pn-junction', field: 'physics', term: 'p-n Junction', definition: 'The boundary between p-type and n-type semiconductor regions, creating a built-in electric field (depletion region) that allows current flow in one direction.', example: 'LEDs, solar cells, and diodes all rely on p-n junctions — the most important structure in electronics.' },
  { id: 'hall-effect', field: 'physics', term: 'Hall Effect', definition: 'A voltage develops perpendicular to both current flow and an applied magnetic field in a conductor: $V_H = IB/(nqt)$. Reveals carrier type and density.', example: 'Hall sensors are in every brushless motor, smartphone compass, and automotive speed sensor.' },
];

export const materialsTerms: GlossaryTerm[] = [
  { id: 'crystal-structure', field: 'engineering', term: 'Crystal Structure', definition: 'The repeating 3D arrangement of atoms in a solid, described by a unit cell and lattice. Common types: FCC (copper), BCC (iron), HCP (titanium), diamond cubic (silicon).', example: 'Steel\'s properties change dramatically depending on crystal structure: austenite (FCC) vs ferrite (BCC) vs martensite.' },
  { id: 'alloy', field: 'engineering', term: 'Alloy', definition: 'A mixture of metals (or metal + non-metal) designed to combine desirable properties: strength, corrosion resistance, conductivity, or weight.', example: 'Titanium alloy Ti-6Al-4V is used in jet engines and hip implants — strong, light, and biocompatible.' },
  { id: 'polymer', field: 'engineering', term: 'Polymer', definition: 'A large molecule made of repeating subunits (monomers). Properties depend on chain length, branching, cross-linking, and crystallinity.', example: 'Kevlar is a polymer 5× stronger than steel per unit weight — used in bulletproof vests and F1 cars.' },
  { id: 'composite-material', field: 'engineering', term: 'Composite Material', definition: 'A material combining two or more constituents with different properties to create superior performance: e.g. carbon fibre reinforced polymer (CFRP).', example: 'Modern aircraft (Boeing 787) are ~50% composite by weight — lighter, stronger, and more fatigue-resistant than aluminium.' },
  { id: 'superconductor', field: 'physics', term: 'Superconductor', definition: 'A material with exactly zero electrical resistance below a critical temperature $T_c$. Also expels magnetic fields (Meissner effect).', example: 'MRI machines use superconducting magnets cooled to 4K to generate the intense, stable magnetic fields needed for imaging.' },
  { id: 'piezoelectric', field: 'engineering', term: 'Piezoelectricity', definition: 'The generation of electric charge in response to mechanical stress (and vice versa) in certain crystals like quartz, PZT, and some ceramics.', example: 'Every quartz watch, ultrasound probe, and piezo igniter (BBQ lighter) uses the piezoelectric effect.' },
];
