import type { GlossaryTerm } from './types';

export const economicsTerms: GlossaryTerm[] = [
  { id: 'supply-demand', field: 'finance', term: 'Supply & Demand', definition: 'The fundamental model where price is determined by the intersection of how much producers will supply and how much consumers will buy.', example: 'Oil price spikes when OPEC cuts supply while demand stays constant.' },
  { id: 'gdp', field: 'finance', term: 'Gross Domestic Product (GDP)', definition: 'The total monetary value of all finished goods and services produced within a country\'s borders in a specific period.', example: 'US GDP is roughly $28 trillion annually.' },
  { id: 'nash-equilibrium', field: 'finance', term: 'Nash Equilibrium', definition: 'A state in a game where no player can improve their payoff by unilaterally changing their strategy, given other players\' strategies.', example: 'Two competing firms choosing identical prices in a Bertrand duopoly.' },
  { id: 'moral-hazard', field: 'finance', term: 'Moral Hazard', definition: 'When an entity takes on more risk because it does not bear the full consequences of that risk.', example: 'Banks taking excessive risks knowing they\'ll be bailed out by governments.' },
  { id: 'opportunity-cost', field: 'finance', term: 'Opportunity Cost', definition: 'The value of the best alternative forgone when making a choice. Every decision has an implicit cost.', example: 'Attending university has an opportunity cost of 4 years of potential salary.' },
  { id: 'elasticity', field: 'finance', term: 'Elasticity', definition: 'Measures how much quantity demanded or supplied responds to a change in price: $E = \\frac{\\%\\Delta Q}{\\%\\Delta P}$.', example: 'Luxury goods are highly elastic; insulin is highly inelastic.' },
  { id: 'inflation', field: 'finance', term: 'Inflation', definition: 'A sustained increase in the general price level of goods and services, eroding purchasing power over time.', example: 'Central banks target ~2% annual inflation as a stability benchmark.' },
  { id: 'loss-aversion', field: 'finance', term: 'Loss Aversion', definition: 'The tendency for people to feel losses ~2× more strongly than equivalent gains. Central to Kahneman & Tversky\'s Prospect Theory.', example: 'Investors hold losing stocks too long, hoping to avoid realizing the loss.' },
  { id: 'prospect-theory', field: 'finance', term: 'Prospect Theory', definition: 'A behavioral model with an S-shaped value function: concave for gains, convex for losses, and steeper for losses. Replaces expected utility for descriptive accuracy.', example: 'Explains why people buy insurance (risk-averse for gains) yet gamble (risk-seeking for losses).' },
  { id: 'nudge', field: 'finance', term: 'Nudge', definition: 'A choice architecture intervention that guides behavior without restricting options (libertarian paternalism). Coined by Thaler & Sunstein.', example: 'Auto-enrollment in retirement plans increased participation from 49% to 86%.' },
  { id: 'hdi', field: 'finance', term: 'Human Development Index (HDI)', definition: 'A composite index measuring average achievement in health (life expectancy), education (schooling years), and living standards (GNI per capita).', example: 'Norway consistently ranks #1; HDI was created by Amartya Sen and Mahbub ul Haq.' },
  { id: 'poverty-trap', field: 'finance', term: 'Poverty Trap', definition: 'A self-reinforcing cycle where low income → low savings → low investment → low growth → low income. Breaking it may require a "big push."', example: 'Sachs argues targeted foreign aid can break poverty traps in sub-Saharan Africa.' },
  { id: 'rct-economics', field: 'finance', term: 'Randomized Controlled Trial (RCT)', definition: 'An experiment randomly assigning subjects to treatment and control groups, establishing causal effects. Pioneered in development economics by Banerjee, Duflo, and Kremer (2019 Nobel).', example: 'RCTs showed deworming pills ($0.50/child) dramatically increased school attendance in Kenya.' },
];
