import type { GlossaryTerm } from './types';

export const engineeringTerms: GlossaryTerm[] = [
  // ── Signal Processing & DSP ────────────────────────────────────
  { id: 'fourier-transform', field: 'engineering', topic: 'signal-processing', term: 'Fourier Transform', definition: 'Decomposes a signal into its constituent frequencies: $F(\\omega) = \\int f(t)\\,e^{-i\\omega t}\\,dt$.', example: 'Audio equalizers, MRI imaging, and JPEG compression all use FFTs.' },
  { id: 'signal-noise-ratio', field: 'engineering', topic: 'signal-processing', term: 'Signal-to-Noise Ratio (SNR)', definition: 'The ratio of useful signal power to background noise power, often in decibels: $SNR = 10\\log_{10}(P_s/P_n)$.', example: 'WiFi routers need high SNR for fast, reliable data transmission.' },
  { id: 'compressed-sensing', field: 'engineering', topic: 'signal-processing', term: 'Compressed Sensing', definition: 'Reconstructing sparse signals from far fewer measurements than Nyquist requires, using $\\ell_1$ minimization or greedy algorithms.', example: 'MRI scan times reduced by 4-8× using compressed sensing — fewer measurements, same image quality.' },
  { id: 'wavelet-transform', field: 'engineering', topic: 'signal-processing', term: 'Wavelet Transform', definition: 'A multiresolution signal decomposition using dilated and translated wavelets, providing adaptive time-frequency localization.', example: 'JPEG 2000, seismic analysis, and ECG processing all use wavelet transforms.' },
  { id: 'z-transform', field: 'engineering', topic: 'signal-processing', term: 'z-Transform', definition: 'The discrete-time analog of the Laplace transform: $X(z) = \\sum_{n} x[n]\\,z^{-n}$. Poles and zeros of $X(z)$ determine filter stability and frequency response.', example: 'Digital filter design in audio plugins and 5G receivers is done entirely in the $z$-domain.' },
  { id: 'nyquist-rate', field: 'engineering', topic: 'signal-processing', term: 'Nyquist Rate', definition: 'The minimum sampling rate $f_s = 2f_{max}$ needed to perfectly reconstruct a band-limited signal, per the Shannon-Nyquist theorem.', example: 'CD audio samples at 44.1 kHz to capture the full 20 kHz audible range.' },

  // ── Control Systems ────────────────────────────────────────────
  { id: 'feedback-loop', field: 'engineering', topic: 'control-systems', term: 'Feedback Loop', definition: 'A system where the output is routed back as input, either amplifying (positive) or stabilising (negative) behaviour.', example: 'A thermostat uses negative feedback to maintain room temperature.' },
  { id: 'pid-controller', field: 'engineering', topic: 'control-systems', term: 'PID Controller', definition: 'A control loop mechanism using Proportional, Integral, and Derivative terms to minimise error between desired and actual output.', example: 'Cruise control in cars adjusts throttle using PID feedback.' },
  { id: 'transfer-function', field: 'engineering', topic: 'control-systems', term: 'Transfer Function', definition: 'The Laplace-domain ratio $H(s) = Y(s)/X(s)$ that fully characterizes a linear time-invariant system\'s input-output behavior.', example: 'Control engineers shape $H(s)$ to design autopilots, cruise control, and robot arms.' },
  { id: 'kalman-filter', field: 'engineering', topic: 'control-systems', term: 'Kalman Filter', definition: 'An optimal recursive estimator for linear Gaussian systems, fusing noisy measurements with a dynamic model: $\\hat{x}_{k|k} = \\hat{x}_{k|k-1} + K_k(z_k - H\\hat{x}_{k|k-1})$.', example: 'GPS navigation, Apollo spacecraft guidance, and self-driving cars all use Kalman filters.' },
  { id: 'mpc', field: 'engineering', topic: 'control-systems', term: 'Model Predictive Control (MPC)', definition: 'A control strategy that solves a finite-horizon optimization problem online at each timestep, handling constraints on states and inputs.', example: 'Tesla Autopilot and chemical process controllers use MPC for real-time constrained control.' },
  { id: 'bode-plot', field: 'engineering', topic: 'control-systems', term: 'Bode Plot', definition: 'A pair of logarithmic graphs (gain and phase vs frequency) used to visualise a system\'s frequency response and determine stability margins.', example: 'Every control engineer uses Bode plots to assess gain margin and phase margin before deployment.' },
  { id: 'root-locus', field: 'engineering', topic: 'control-systems', term: 'Root Locus', definition: 'A graphical method plotting the trajectories of closed-loop poles as a gain parameter varies, revealing stability transitions.', example: 'Automotive cruise control tuning uses root locus to ensure poles stay in the left-half plane.' },

  // ── Circuits & Electronics ─────────────────────────────────────
  { id: 'kirchhoff-laws', field: 'engineering', topic: 'circuits-electronics', term: 'Kirchhoff\'s Laws', definition: 'KCL (current law): $\\sum I = 0$ at each node. KVL (voltage law): $\\sum V = 0$ around each loop. The foundation of all circuit analysis.', example: 'SPICE simulators solve millions of KCL/KVL equations to verify chip designs before fabrication.' },
  { id: 'thevenin-theorem', field: 'engineering', topic: 'circuits-electronics', term: 'Thévenin\'s Theorem', definition: 'Any linear two-terminal network can be replaced by a voltage source $V_{Th}$ in series with a resistance $R_{Th}$.', example: 'Audio engineers use Thévenin equivalents to match impedances between microphones and preamps.' },
  { id: 'op-amp', field: 'engineering', topic: 'circuits-electronics', term: 'Operational Amplifier', definition: 'A high-gain differential amplifier used with feedback to create precise amplifiers, filters, integrators, and comparators.', example: 'The inverting amplifier $A_v = -R_f/R_{in}$ is the most common op-amp configuration in analog design.' },
  { id: 'cmos-inverter', field: 'engineering', topic: 'circuits-electronics', term: 'CMOS Inverter', definition: 'A complementary pair of NMOS and PMOS transistors that draws near-zero static power, switching only during transitions. The building block of all digital logic.', example: 'Apple\'s M3 chip contains 25 billion CMOS transistors, each switching billions of times per second.' },

  // ── Communications & Coding ────────────────────────────────────
  { id: 'shannon-capacity', field: 'engineering', topic: 'communications-coding', term: 'Shannon Capacity', definition: 'The maximum error-free data rate for a noisy channel: $C = B\\log_2(1 + SNR)$ bits/s, where $B$ is bandwidth.', example: '5G and WiFi 7 approach Shannon limits using LDPC codes and massive MIMO.' },
  { id: 'ofdm', field: 'engineering', topic: 'communications-coding', term: 'OFDM', definition: 'Orthogonal Frequency-Division Multiplexing splits a wideband channel into many narrow orthogonal subcarriers, each modulated independently. Robust against multipath fading.', example: 'WiFi (802.11a/g/n/ac/ax), 4G LTE, 5G NR, and DVB-T all use OFDM.' },
  { id: 'ldpc-code', field: 'engineering', topic: 'communications-coding', term: 'LDPC Code', definition: 'Low-Density Parity-Check codes use sparse bipartite graphs and iterative belief-propagation decoding to approach the Shannon limit within 0.1 dB.', example: '5G NR, WiFi 6/7, DVB-S2, and 10GbE Ethernet all use LDPC for near-capacity performance.' },
  { id: 'hamming-code', field: 'engineering', topic: 'communications-coding', term: 'Hamming Code', definition: 'A linear error-correcting code with minimum distance 3, capable of single-error correction. Hamming(7,4) encodes 4 data bits with 3 parity bits.', example: 'ECC memory in servers uses extended Hamming codes to silently correct cosmic-ray bit flips.' },

  // ── Solid Mechanics & Vibrations ───────────────────────────────
  { id: 'tensile-strength', field: 'engineering', topic: 'solid-mechanics', term: 'Tensile Strength', definition: 'The maximum stress a material can withstand while being stretched or pulled before breaking.', example: 'Spider silk has a higher tensile strength per weight than steel.' },
  { id: 'fatigue-failure', field: 'engineering', topic: 'solid-mechanics', term: 'Fatigue Failure', definition: 'Progressive structural damage from repeated cyclic loading, even at stresses well below ultimate tensile strength.', example: 'Aircraft fuselages are inspected for fatigue cracks after flight cycles.' },
  { id: 'euler-buckling', field: 'engineering', topic: 'solid-mechanics', term: 'Euler Buckling', definition: 'A slender column buckles at critical load $P_{cr} = \\pi^2 EI / L_e^2$, which can be far below the material yield stress.', example: 'Structural engineers must check buckling for every column in buildings and bridges.' },
  { id: 'natural-frequency', field: 'engineering', topic: 'solid-mechanics', term: 'Natural Frequency', definition: 'The frequency $\\omega_n = \\sqrt{k/m}$ at which an undamped system oscillates freely. Resonance occurs when forcing frequency matches $\\omega_n$.', example: 'The Tacoma Narrows Bridge collapsed in 1940 when wind matched its natural frequency.' },
  { id: 'paris-law', field: 'engineering', topic: 'solid-mechanics', term: 'Paris\' Law', definition: 'Empirical power law for fatigue crack growth: $da/dN = C(\\Delta K)^m$, where $\\Delta K$ is the stress intensity factor range.', example: 'Aircraft inspection intervals are calculated using Paris\' law to prevent catastrophic failure.' },

  // ── Thermofluids ───────────────────────────────────────────────
  { id: 'reynolds-number', field: 'engineering', topic: 'thermofluids', term: 'Reynolds Number', definition: 'Dimensionless ratio $Re = \\frac{\\rho v L}{\\mu}$ predicting whether fluid flow is laminar (smooth) or turbulent.', example: 'Aircraft wing design uses Reynolds number to predict drag.' },
  { id: 'navier-stokes', field: 'engineering', topic: 'thermofluids', term: 'Navier-Stokes Equations', definition: 'The fundamental PDEs governing viscous fluid motion: $\\rho(\\partial \\mathbf{v}/\\partial t + \\mathbf{v} \\cdot \\nabla \\mathbf{v}) = -\\nabla p + \\mu \\nabla^2 \\mathbf{v} + \\mathbf{f}$.', example: 'CFD simulations solving Navier-Stokes design F1 cars, artificial hearts, and jet engines.' },
  { id: 'bernoulli-equation', field: 'engineering', topic: 'thermofluids', term: 'Bernoulli\'s Equation', definition: 'For steady, inviscid, incompressible flow: $P + \\frac{1}{2}\\rho v^2 + \\rho gh = \\text{const}$ along a streamline.', example: 'Venturi meters, carburetors, and pitot tubes for airspeed all rely on Bernoulli\'s principle.' },
  { id: 'nusselt-number', field: 'engineering', topic: 'thermofluids', term: 'Nusselt Number', definition: 'Dimensionless ratio $Nu = hL/k$ of convective to conductive heat transfer at a surface. $Nu = 1$ means pure conduction.', example: 'Every heat exchanger, radiator, and cooling system is designed using Nusselt number correlations.' },
  { id: 'boundary-layer', field: 'engineering', topic: 'thermofluids', term: 'Boundary Layer', definition: 'The thin region near a surface where viscous effects are significant, with thickness $\\delta \\sim L/\\sqrt{Re}$. Prandtl\'s key insight (1904).', example: 'Aircraft skin friction drag depends on boundary layer thickness — thinner = less drag.' },

  // ── Robotics & Mechatronics ────────────────────────────────────
  { id: 'degrees-of-freedom', field: 'engineering', topic: 'robotics-mechatronics', term: 'Degrees of Freedom (DOF)', definition: 'The number of independent motions a mechanism can perform. A rigid body in 3D has at most 6 DOF (3 translational + 3 rotational).', example: 'Industrial robot arms typically have 6 DOF for full spatial manipulation.' },
  { id: 'jacobian-robotics', field: 'engineering', topic: 'robotics-mechatronics', term: 'Jacobian Matrix (Robotics)', definition: 'Maps joint velocities to end-effector velocities: $\\dot{\\mathbf{x}} = J(\\mathbf{q})\\dot{\\mathbf{q}}$. Singularities occur where $J$ loses rank.', example: 'Surgical robots use Jacobian-based control to translate surgeon hand movements into precise instrument motion.' },
  { id: 'slam', field: 'engineering', topic: 'robotics-mechatronics', term: 'SLAM', definition: 'Simultaneous Localisation and Mapping — building a map of an unknown environment while tracking the robot\'s position within it.', example: 'Self-driving cars, Roomba vacuums, and Apple Vision Pro all run SLAM algorithms.' },
  { id: 'dh-parameters', field: 'engineering', topic: 'robotics-mechatronics', term: 'DH Parameters', definition: 'Denavit-Hartenberg convention: four parameters $(\\theta, d, a, \\alpha)$ per joint that define coordinate frame transformations for forward kinematics.', example: 'Every robot manufacturer uses DH convention to specify arm geometry in datasheets.' },

  // ── Reaction Engineering ───────────────────────────────────────
  { id: 'arrhenius-equation', field: 'engineering', topic: 'reaction-engineering', term: 'Arrhenius Equation', definition: 'Rate constant temperature dependence: $k = Ae^{-E_a/(RT)}$. The exponential makes temperature the most powerful rate controller.', example: 'Reaction rates roughly double for every 10°C increase — fundamental to food preservation and chemical plants.' },
  { id: 'cstr', field: 'engineering', topic: 'reaction-engineering', term: 'CSTR', definition: 'Continuous Stirred-Tank Reactor: a perfectly mixed vessel at steady state where exit conditions equal internal conditions. Design equation: $V = F_{A0}X_A/(-r_A)$.', example: 'Polymerisation, fermentation, and wastewater treatment plants commonly use CSTRs.' },
  { id: 'damkohler-number', field: 'engineering', topic: 'reaction-engineering', term: 'Damköhler Number', definition: 'Dimensionless ratio of reaction rate to transport rate: $Da = k\\tau$. High $Da$ means fast reaction (high conversion); low $Da$ means most reactant passes through.', example: 'Catalytic converter designers use $Da$ to size catalyst beds for >99% pollutant conversion.' },

  // ── Transport Phenomena ────────────────────────────────────────
  { id: 'fourier-heat-law', field: 'engineering', topic: 'transport-phenomena', term: 'Fourier\'s Law', definition: 'Heat flux is proportional to the negative temperature gradient: $q = -k\\nabla T$. The thermal analog of Fick\'s and Ohm\'s laws.', example: 'Insulation design, CPU heatsinks, and building energy codes all use Fourier\'s law.' },
  { id: 'fick-diffusion', field: 'engineering', topic: 'transport-phenomena', term: 'Fick\'s Law', definition: 'Mass flux is proportional to the negative concentration gradient: $J = -D\\nabla C$. Diffusion coefficient $D$ depends on species, medium, and temperature.', example: 'Drug delivery patches, semiconductor doping, and oxygen transport in lungs follow Fick\'s law.' },
  { id: 'peclet-number', field: 'engineering', topic: 'transport-phenomena', term: 'Péclet Number', definition: 'Ratio of advective to diffusive transport: $Pe = UL/\\alpha$ (thermal) or $UL/D$ (mass). High $Pe$ = advection-dominated.', example: 'Designing chromatography columns and blood oxygenators requires knowing $Pe$ to balance advection and diffusion.' },

  // ── Process Design ─────────────────────────────────────────────
  { id: 'mccabe-thiele', field: 'engineering', topic: 'process-design', term: 'McCabe-Thiele Method', definition: 'A graphical technique for distillation column design that determines theoretical stages by stepping between equilibrium and operating lines on a $y$-$x$ diagram.', example: 'Petroleum refineries use McCabe-Thiele to design every distillation column.' },
  { id: 'pinch-analysis', field: 'engineering', topic: 'process-design', term: 'Pinch Analysis', definition: 'Identifies the thermodynamic bottleneck temperature in heat integration where minimum utility usage is determined. No heat should cross the pinch.', example: 'Chemical plants save 20-40% energy costs by designing heat exchanger networks using pinch analysis.' },

  // ── Aerodynamics ───────────────────────────────────────────────
  { id: 'mach-number', field: 'engineering', topic: 'aerodynamics', term: 'Mach Number', definition: 'The ratio $M = v/a$ of flow velocity to local speed of sound. Subsonic ($M<1$), supersonic ($M>1$), hypersonic ($M>5$).', example: 'Concorde cruised at $M = 2.04$; modern scramjets target $M > 5$.' },
  { id: 'drag-coefficient', field: 'engineering', topic: 'aerodynamics', term: 'Drag Coefficient', definition: 'Nondimensional drag: $C_D = D / (\\frac{1}{2}\\rho v^2 S)$. Depends on shape, Reynolds number, and Mach number.', example: 'Tesla reduced Model S $C_D$ to 0.208 — among the lowest of any production car.' },
  { id: 'lift-coefficient', field: 'engineering', topic: 'aerodynamics', term: 'Lift Coefficient', definition: 'Nondimensional lift: $C_L = L / (\\frac{1}{2}\\rho v^2 S)$. Varies with angle of attack, airfoil shape, and Reynolds number.', example: 'A Boeing 747 needs $C_L \\approx 0.5$ at cruise and $C_L \\approx 2.5$ at landing (with flaps).' },

  // ── Orbital Mechanics ──────────────────────────────────────────
  { id: 'hohmann-transfer', field: 'engineering', topic: 'orbital-mechanics', term: 'Hohmann Transfer', definition: 'The most fuel-efficient two-impulse maneuver between coplanar circular orbits, using an elliptical path tangent to both.', example: 'Interplanetary missions use Hohmann-like transfers timed for planetary alignment.' },
  { id: 'tsiolkovsky-equation', field: 'engineering', topic: 'orbital-mechanics', term: 'Tsiolkovsky Rocket Equation', definition: '$\\Delta v = v_e \\ln(m_0/m_f)$: achievable velocity change depends logarithmically on mass ratio — the "tyranny of the rocket equation."', example: 'Saturn V was 85% fuel by mass, yet barely reached lunar orbit velocity.' },
  { id: 'lagrange-points', field: 'engineering', topic: 'orbital-mechanics', term: 'Lagrange Points', definition: 'Five equilibrium positions ($L_1$–$L_5$) in the restricted three-body problem where gravitational and centrifugal forces balance.', example: 'The James Webb Space Telescope orbits the Sun-Earth $L_2$ point, 1.5 million km from Earth.' },

  // ── Nuclear Engineering ────────────────────────────────────────
  { id: 'criticality', field: 'engineering', topic: 'nuclear-engineering', term: 'Criticality', definition: 'The state where the neutron multiplication factor $k = 1$ — each fission produces exactly one new fission on average, sustaining a steady chain reaction.', example: 'Reactor operators maintain $k$ within 0.001 of unity — the most precisely controlled chain reaction on Earth.' },
  { id: 'four-factor-formula', field: 'engineering', topic: 'nuclear-engineering', term: 'Four-Factor Formula', definition: '$k_\\infty = \\eta f p \\varepsilon$: reproduction factor $\\times$ utilisation $\\times$ resonance escape $\\times$ fast fission factor for infinite-medium multiplication.', example: 'Reactor designers optimize fuel enrichment and moderator geometry to achieve $k_\\infty > 1$.' },
  { id: 'lawson-criterion', field: 'engineering', topic: 'nuclear-engineering', term: 'Lawson Criterion', definition: 'For fusion net energy gain, the triple product $n\\tau_E T > 3 \\times 10^{21}$ keV·s/m³ must be exceeded — density, confinement time, and temperature.', example: 'ITER aims for $Q = 10$ (10× energy gain) to demonstrate fusion power feasibility.' },

  // ── Power Systems ──────────────────────────────────────────────
  { id: 'three-phase-power', field: 'engineering', topic: 'power-systems', term: 'Three-Phase Power', definition: 'Three AC voltages 120° apart delivering constant instantaneous power $P = 3V_pI_p\\cos\\phi$, using less conductor than single-phase for the same power.', example: 'Every power grid on Earth uses three-phase AC from generators to substations.' },
  { id: 'per-unit-system', field: 'engineering', topic: 'power-systems', term: 'Per-Unit System', definition: 'Normalises electrical quantities by base values ($x_{pu} = x_{actual}/x_{base}$) to eliminate transformer turns ratios from calculations.', example: 'Power system operators report "Bus 7 is at 0.97 pu" meaning 3% below rated voltage.' },

  // ── Biomedical Engineering ─────────────────────────────────────
  { id: 'hodgkin-huxley', field: 'engineering', topic: 'biomedical-engineering', term: 'Hodgkin-Huxley Model', definition: 'Coupled nonlinear ODEs modeling neuron membrane potential via voltage-gated ion conductances: $C_m dV/dt = -\\sum g_i(V - E_i) + I_{ext}$.', example: 'Brain simulators like NEURON solve millions of H-H equations to model neural circuits.' },
  { id: 'elastography', field: 'engineering', topic: 'biomedical-engineering', term: 'Elastography', definition: 'Imaging technique that measures tissue stiffness by tracking shear wave speed: $E = 3\\rho v_s^2$. Stiffer tissue = faster waves.', example: 'Liver fibrosis staging by elastography replaces painful biopsies.' },

  // ── Semiconductor & VLSI ───────────────────────────────────────
  { id: 'moores-law', field: 'engineering', topic: 'semiconductor-engineering', term: 'Moore\'s Law', definition: 'Empirical observation that transistor density doubles approximately every two years. Held for 50+ years but is approaching physical limits.', example: 'From 2,300 transistors (Intel 4004, 1971) to 114 billion (Apple M2 Ultra, 2023).' },
  { id: 'finfet', field: 'engineering', topic: 'semiconductor-engineering', term: 'FinFET', definition: 'A 3D transistor where the gate wraps around a thin silicon fin on three sides, providing superior electrostatic control at sub-22nm nodes.', example: 'Every modern smartphone and laptop chip uses FinFET technology.' },
  { id: 'gaa-nanosheet', field: 'engineering', topic: 'semiconductor-engineering', term: 'GAA Nanosheet', definition: 'Gate-All-Around transistors with stacked horizontal nanosheets surrounded by gate material on all four sides — the successor to FinFETs below 3nm.', example: 'Samsung (3nm, 2022) and Intel (20A, 2024) use GAA for continued transistor scaling.' },

  // ── Environmental Engineering ──────────────────────────────────
  { id: 'bod', field: 'engineering', topic: 'environmental-engineering', term: 'BOD (Biological Oxygen Demand)', definition: 'Oxygen consumed by microorganisms to decompose organic matter in water — an indirect measure of organic pollution.', example: 'Wastewater plants must reduce BOD from ~200 mg/L (raw sewage) to <20 mg/L before discharge.' },
  { id: 'lca', field: 'engineering', topic: 'environmental-engineering', term: 'Life Cycle Assessment (LCA)', definition: 'ISO 14040/14044 methodology quantifying energy, material, and emission flows from raw material extraction through disposal ("cradle to grave").', example: 'EV vs ICE vehicle comparison requires full LCA: battery manufacturing emissions vs lifetime tailpipe savings.' },

  // ── Structural Engineering ─────────────────────────────────────
  { id: 'lrfd', field: 'engineering', topic: 'structural-engineering', term: 'LRFD', definition: 'Load and Resistance Factor Design: $\\phi R_n \\geq \\sum \\gamma_i Q_i$, applying factors $>1$ to loads and $<1$ to resistance to ensure structural safety.', example: 'Modern building codes (AISC, Eurocode) are based on LRFD for steel and concrete design.' },
  { id: 'bending-moment', field: 'engineering', topic: 'structural-engineering', term: 'Bending Moment', definition: 'Internal moment at a section of a beam: for a simply supported beam with midspan load $P$, $M_{max} = PL/4$.', example: 'Every structural engineer learns this as the first beam calculation for bridge and floor design.' },

  // ── Audio & Acoustics ──────────────────────────────────────────
  { id: 'decibel-scale', field: 'engineering', topic: 'audio-engineering', term: 'Decibel Scale', definition: 'Logarithmic measure of sound intensity: $L = 10\\log_{10}(I/I_0)$ dB, spanning from 0 dB (hearing threshold) to 140 dB (jet engine).', example: 'Every sound level meter, audio mixer, and noise regulation uses the dB scale.' },
  { id: 'impulse-response', field: 'engineering', topic: 'audio-engineering', term: 'Impulse Response', definition: 'A room\'s complete acoustic signature: any sound output $y(t) = x(t) * h(t)$ is the input convolved with the impulse response $h(t)$.', example: 'Convolution reverb plugins use measured impulse responses to simulate famous concert halls.' },
];
