import type { GlossaryTerm } from './types';

export const magnetismTerms: GlossaryTerm[] = [
  {
    id: 'landau-lifshitz-equation',
    field: 'physics',
    topic: 'condensed-matter',
    term: 'Landau-Lifshitz Equation',
    definition: 'A continuum equation for magnetization dynamics in which the magnetization precesses around an effective field and relaxes via damping.',
    example: 'Used to model how magnetic domains evolve in ferromagnets and nanomagnetic devices.',
    thinkerLinks: ['evgeny-lifshitz'],
    formulaLinks: ['landau-lifshitz-equation', 'landau-lifshitz-gilbert-equation'],
    symbolLinks: { 'M': 'mu', 'H': 'eta', 'γ': 'gamma', 'λ': 'lambda' },
    difficulty: 'intermediate',
  },
  {
    id: 'gilbert-damping',
    field: 'physics',
    topic: 'condensed-matter',
    term: 'Gilbert Damping',
    definition: 'The dissipative term in magnetization dynamics that causes a magnetic moment to relax toward alignment with the effective field, usually parameterized by α.',
    example: 'High Gilbert damping can help a magnetic bit settle quickly after switching.',
    thinkerLinks: ['thomas-gilbert'],
    formulaLinks: ['gilbert-damping-term', 'landau-lifshitz-gilbert-equation'],
    symbolLinks: { 'α': 'alpha', 'M': 'mu' },
    difficulty: 'intermediate',
  },
  {
    id: 'magnetization',
    field: 'physics',
    topic: 'condensed-matter',
    term: 'Magnetization',
    definition: 'A vector field describing the local magnetic moment density of a material, often denoted by M.',
    example: 'Micromagnetic simulations track how magnetization rotates inside a magnetic nanostructure.',
    thinkerLinks: ['evgeny-lifshitz', 'thomas-gilbert'],
    formulaLinks: ['landau-lifshitz-equation', 'landau-lifshitz-gilbert-equation'],
    symbolLinks: { 'M': 'mu' },
    difficulty: 'intro',
  },
  {
    id: 'precession',
    field: 'physics',
    topic: 'classical-mechanics',
    term: 'Precession',
    definition: 'A rotation of a vector quantity around an axis or field direction, such as the precession of magnetization around an effective magnetic field.',
    example: 'In ferromagnetic resonance, the magnetization vector precesses around the applied field.',
    thinkerLinks: ['evgeny-lifshitz'],
    formulaLinks: ['landau-lifshitz-equation'],
    symbolLinks: { 'γ': 'gamma' },
    difficulty: 'intro',
  },
  {
    id: 'micromagnetics',
    field: 'physics',
    topic: 'condensed-matter',
    term: 'Micromagnetics',
    definition: 'The continuum theory of magnetic structures at sub-micrometer scales, combining exchange, anisotropy, Zeeman, and magnetostatic effects.',
    example: 'Micromagnetics is used to design MRAM cells and simulate domain wall motion.',
    thinkerLinks: ['evgeny-lifshitz', 'thomas-gilbert'],
    formulaLinks: ['landau-lifshitz-gilbert-equation', 'gilbert-damping-term'],
    symbolLinks: { 'M': 'mu', 'α': 'alpha' },
    difficulty: 'advanced',
  },
  {
    id: 'spintronics',
    field: 'physics',
    topic: 'condensed-matter',
    term: 'Spintronics',
    definition: 'A branch of electronics that exploits electron spin, magnetization dynamics, and spin currents in addition to electric charge.',
    example: 'Spintronic devices include MRAM, spin valves, and spin-torque oscillators.',
    thinkerLinks: ['thomas-gilbert'],
    formulaLinks: ['gilbert-damping-term', 'landau-lifshitz-gilbert-equation'],
    symbolLinks: { 'α': 'alpha', 'M': 'mu' },
    difficulty: 'intermediate',
  },
];
