import type { GlossaryTerm } from './types';

export const mathTerms: GlossaryTerm[] = [
  { id: 'eigenvalue', field: 'math', topic: 'linear-algebra', term: 'Eigenvalue', definition: 'A scalar $\\lambda$ such that $A\\mathbf{v} = \\lambda\\mathbf{v}$ for some non-zero vector $\\mathbf{v}$. Eigenvalues reveal how a matrix stretches space.', example: 'Google PageRank uses the dominant eigenvalue of the web link matrix.' },
  { id: 'determinant', field: 'math', topic: 'linear-algebra', term: 'Determinant', definition: 'A scalar value $\\det(A)$ that encodes how a linear transformation scales area/volume. Zero determinant means the matrix is singular.', example: 'Checking if a system of equations has a unique solution.' },
  { id: 'gradient', field: 'math', topic: 'calculus', term: 'Gradient', definition: 'The vector of all partial derivatives $\\nabla f$. Points in the direction of steepest ascent of a scalar field.', example: 'Gradient descent in ML follows $-\\nabla f$ to minimise loss.' },
  { id: 'integral', field: 'math', topic: 'calculus', term: 'Integral', definition: 'The accumulation of a quantity over a region: $\\int_a^b f(x)\\,dx$. Inverse operation of differentiation.', example: 'Computing the area under a revenue curve gives total earnings.' },
  { id: 'bayes-theorem', field: 'math', topic: 'probability-stats', term: 'Bayes\' Theorem', definition: '$P(A|B) = \\frac{P(B|A)\\,P(A)}{P(B)}$. Updates prior beliefs given new evidence.', example: 'Spam filters update the probability an email is spam given its words.' },
  { id: 'std-deviation', field: 'math', topic: 'probability-stats', term: 'Standard Deviation', definition: 'The square root of variance $\\sigma = \\sqrt{E[(X-\\mu)^2]}$. Measures dispersion around the mean.', example: 'Quality control uses ±3σ to define acceptable manufacturing tolerance.' },
  { id: 'convexity-math', field: 'math', topic: 'optimization', term: 'Convexity', definition: 'A set or function where any line segment between two points stays within the set/above the graph. Guarantees a single global minimum.', example: 'Convex optimisation problems can be solved efficiently in polynomial time.' },
  { id: 'graph-theory', field: 'math', topic: 'discrete-math', term: 'Graph', definition: 'A structure $G = (V, E)$ of vertices and edges modelling pairwise relationships.', example: 'Social networks, routing algorithms, and dependency trees all use graphs.' },
  { id: 'topology-def', field: 'math', topic: 'topology', term: 'Topology', definition: 'The study of properties preserved under continuous deformations (stretching, bending, but not tearing).', example: 'A coffee cup and a donut are topologically equivalent (both genus 1).' },
  { id: 'proof-by-contradiction', field: 'math', term: 'Proof by Contradiction', definition: 'Assume the negation of the statement, then derive a logical impossibility. This proves the original statement must be true.', example: 'Euclid proved the infinitude of primes this way.' },
];
