import type { GlossaryTerm } from './types';

export const physicsTerms: GlossaryTerm[] = [
  { id: 'entropy-phys', field: 'physics', term: 'Entropy', definition: 'A measure of disorder or the number of microscopic configurations consistent with a macroscopic state: $S = k_B \\ln \\Omega$.', example: 'Ice melting increases entropy as molecules gain freedom of movement.' },
  { id: 'wave-particle', field: 'physics', term: 'Wave–Particle Duality', definition: 'Quantum objects exhibit both wave-like interference and particle-like detection depending on the experiment.', example: 'Electrons create interference patterns in the double-slit experiment.' },
  { id: 'spacetime', field: 'physics', term: 'Spacetime', definition: 'The four-dimensional continuum merging three spatial dimensions with time, curved by mass-energy per General Relativity.', example: 'GPS satellites correct for spacetime curvature to stay accurate.' },
  { id: 'conservation-energy', field: 'physics', term: 'Conservation of Energy', definition: 'Energy cannot be created or destroyed, only transformed from one form to another. Total energy in a closed system is constant.', example: 'A pendulum converts potential energy to kinetic and back.' },
  { id: 'superposition', field: 'physics', term: 'Superposition', definition: 'A quantum system exists in a combination of all possible states simultaneously until measured.', example: 'Schrödinger\'s cat is both alive and dead until the box is opened.' },
  { id: 'planck-constant', field: 'physics', term: 'Planck\'s Constant', definition: 'Fundamental constant $h \\approx 6.626 \\times 10^{-34}$ J·s relating photon energy to frequency: $E = hf$.', example: 'Determines the minimum energy a photon of a given colour can carry.' },
  { id: 'schwarzschild-radius', field: 'physics', term: 'Schwarzschild Radius', definition: 'The radius $r_s = 2GM/c^2$ at which an object\'s escape velocity equals the speed of light, defining a black hole\'s event horizon.', example: 'Earth\'s Schwarzschild radius is about 9 mm.' },
  { id: 'doppler-effect', field: 'physics', term: 'Doppler Effect', definition: 'The change in frequency of a wave relative to an observer moving relative to the wave source.', example: 'An ambulance siren sounds higher-pitched as it approaches you.' },
  { id: 'nuclear-shell-model', field: 'physics', term: 'Nuclear Shell Model', definition: 'Goeppert Mayer\'s model explaining magic numbers (2, 8, 20, 28, 50, 82, 126) where nuclei are exceptionally stable, analogous to electron shells in atoms.', example: 'Lead-208 is doubly magic (82 protons, 126 neutrons) and the heaviest stable nucleus.' },
  { id: 'parity-violation', field: 'physics', term: 'Parity Violation', definition: 'The weak nuclear force does not conserve parity (mirror symmetry). Proven by Chien-Shiung Wu\'s 1956 cobalt-60 experiment.', example: 'Parity violation helps explain why the universe is made of matter rather than antimatter.' },
  { id: 'two-photon-absorption', field: 'physics', term: 'Two-Photon Absorption', definition: 'A nonlinear optical process where an atom absorbs two photons simultaneously to reach an excited state. Predicted by Goeppert Mayer in 1931, confirmed with lasers.', example: 'Two-photon microscopy enables deep tissue biological imaging with reduced photodamage.' },
  { id: 'nuclear-fission', field: 'physics', term: 'Nuclear Fission', definition: 'The splitting of a heavy nucleus into lighter fragments, releasing ~200 MeV per event. First explained theoretically by Lise Meitner using $E=mc^2$.', example: 'Nuclear power plants generate ~10% of global electricity through controlled fission.' },
  { id: 'saha-equation', field: 'physics', term: 'Saha Ionization Equation', definition: 'Relates the ionization state of atoms to temperature and pressure: $\\frac{n_{i+1}n_e}{n_i} = f(T)$. Used by Cecilia Payne to determine stellar composition.', example: 'Revealed that stars are primarily hydrogen and helium, not iron as previously assumed.' },,
  { id: 'einstein-smoluchowski-relation', field: 'physics', topic: 'statistical-mechanics', term: 'Einstein–Smoluchowski Relation', definition: 'A relation connecting diffusive spreading to mobility and thermal agitation, central to fluctuation-driven transport.', example: 'It helps connect microscopic random motion with measurable transport coefficients.' },

];
