import type { GlossaryTerm } from './types';

export const quantumGravityTerms: GlossaryTerm[] = [
  {
    id: 'ads-cft', field: 'physics', topic: 'quantum-gravity',
    term: 'AdS/CFT Correspondence',
    definition: 'Maldacena\'s conjecture that a gravitational theory in anti-de Sitter space is dual to a conformal field theory on its boundary — a realization of the holographic principle.',
    example: 'Used to compute quark-gluon plasma viscosity, matching RHIC experiments.',
    thinkerLinks: ['maldacena'],
    related: ['holographic-principle', 'black-hole-entropy'],
    difficulty: 'advanced',
  },
  {
    id: 'holographic-principle', field: 'physics', topic: 'quantum-gravity',
    term: 'Holographic Principle',
    definition: 'The maximum entropy of a region scales with its boundary area, not volume: $S \\leq A/(4G\\hbar)$. Information in 3D space is encoded on a 2D surface.',
    formula: '$S \\leq \\frac{A}{4G\\hbar}$',
    latex: 'S \\leq \\frac{A}{4G\\hbar}',
    thinkerLinks: ['thooft', 'susskind'],
    related: ['ads-cft', 'black-hole-entropy'],
    difficulty: 'advanced',
  },
  {
    id: 'black-hole-entropy', field: 'physics', topic: 'quantum-gravity',
    term: 'Bekenstein–Hawking Entropy',
    definition: 'A black hole\'s entropy is proportional to its event horizon area: $S_{BH} = \\frac{k_B c^3 A}{4G\\hbar}$. Bekenstein (1973) proposed entropy $\\propto A$; Hawking (1974) fixed the $1/4$ coefficient via his temperature calculation.',
    formula: '$S_{BH} = \\frac{k_B c^3 A}{4G\\hbar} = \\frac{A}{4\\ell_P^2}$',
    latex: 'S_{BH} = \\frac{k_B c^3 A}{4G\\hbar}',
    thinkerLinks: ['jacob-bekenstein', 'stephen-hawking'],
    formulaLinks: ['bekenstein-hawking'],
    related: ['holographic-principle', 'strominger-vafa', 'bekenstein-bound', 'black-hole-complementarity'],
    difficulty: 'advanced',
  },
  {
    id: 'bekenstein-bound', field: 'physics', topic: 'quantum-gravity',
    term: 'Bekenstein Bound',
    definition: 'The maximum entropy (information) of a system with energy $E$ in a sphere of radius $R$: $S \\leq 2\\pi k_B ER / (\\hbar c)$. The tightest universal bound on information content.',
    formula: '$S \\leq \\frac{2\\pi k_B E R}{\\hbar c}$',
    latex: 'S \\leq \\frac{2\\pi k_B E R}{\\hbar c}',
    thinkerLinks: ['jacob-bekenstein'],
    related: ['holographic-principle', 'black-hole-entropy'],
    difficulty: 'advanced',
  },
  {
    id: 'black-hole-complementarity', field: 'physics', topic: 'quantum-gravity',
    term: 'Black Hole Complementarity',
    definition: 'Susskind\'s principle that an infalling observer and a distant observer give complementary descriptions of a black hole: information is on the horizon (exterior) and passes through it (interior), with no single observer able to verify both — preserving unitarity without contradiction.',
    thinkerLinks: ['leonard-susskind', 'gerard-thooft'],
    related: ['holographic-principle', 'black-hole-entropy', 'ads-cft'],
    difficulty: 'advanced',
  },
  {
    id: 'er-epr', field: 'physics', topic: 'quantum-gravity',
    term: 'ER = EPR',
    definition: 'Maldacena and Susskind\'s conjecture that Einstein-Rosen bridges (wormholes) and Einstein-Podolsky-Rosen quantum entanglement are the same phenomenon — spacetime connectivity emerges from quantum correlations.',
    thinkerLinks: ['juan-maldacena', 'leonard-susskind'],
    related: ['ads-cft', 'holographic-principle'],
    difficulty: 'advanced',
  },
  {
    id: 'strominger-vafa', field: 'physics', topic: 'quantum-gravity',
    term: 'Strominger–Vafa Microstate Counting',
    definition: 'The first microscopic derivation of Bekenstein-Hawking entropy (1996): counting D-brane bound states of an extremal 5D black hole yields $S = 2\\pi\\sqrt{n_1 n_5 n_p}$, exactly matching $A/(4G)$.',
    formula: '$S = 2\\pi\\sqrt{n_1 n_5 n_p}$',
    latex: 'S = 2\\pi\\sqrt{n_1 n_5 n_p}',
    thinkerLinks: ['juan-maldacena'],
    formulaLinks: ['bekenstein-hawking'],
    related: ['black-hole-entropy', 'ads-cft'],
    difficulty: 'advanced',
  },
  {
    id: 'thooft-large-n', field: 'physics', topic: 'quantum-gravity',
    term: '\'t Hooft Large-N Expansion',
    definition: 'In the limit $N \\to \\infty$ with $g^2 N$ fixed, $SU(N)$ gauge theory Feynman diagrams organize by topology (genus). Planar diagrams dominate, revealing a string-theory-like structure that foreshadowed AdS/CFT.',
    thinkerLinks: ['gerard-thooft'],
    related: ['ads-cft'],
    difficulty: 'advanced',
  },
  {
    id: 'generalized-second-law', field: 'physics', topic: 'quantum-gravity',
    term: 'Generalized Second Law',
    definition: 'Bekenstein\'s extension of the second law of thermodynamics: the total entropy $S_{\\text{matter}} + S_{BH}$ (ordinary entropy plus black hole entropy) never decreases, even when matter crosses the horizon.',
    thinkerLinks: ['jacob-bekenstein'],
    related: ['black-hole-entropy'],
    difficulty: 'intermediate',
  },
];
