import type { GlossaryTerm } from './types';

export const quantTerms: GlossaryTerm[] = [
  { id: 'black-scholes', field: 'quant', term: 'Black–Scholes Model', definition: 'A model for pricing European options using stock price, strike, volatility, time to expiry, and risk-free rate: $C = S\\,N(d_1) - Ke^{-rT}N(d_2)$.', example: 'Every options trading desk uses Black-Scholes or its extensions.' },
  { id: 'sharpe-ratio', field: 'quant', term: 'Sharpe Ratio', definition: 'Risk-adjusted return: $S = \\frac{R_p - R_f}{\\sigma_p}$. Higher is better—more return per unit of risk.', example: 'Hedge funds target Sharpe ratios above 1.0 for investor appeal.' },
  { id: 'var', field: 'quant', term: 'Value at Risk (VaR)', definition: 'The maximum expected loss over a given time horizon at a specified confidence level (e.g., 95% VaR).', example: 'Banks use VaR to determine capital reserves for regulatory compliance.' },
  { id: 'stochastic-process', field: 'quant', term: 'Stochastic Process', definition: 'A collection of random variables indexed by time, modelling systems that evolve probabilistically.', example: 'Stock prices are modelled as geometric Brownian motion.' },
  { id: 'monte-carlo', field: 'quant', term: 'Monte Carlo Simulation', definition: 'Using repeated random sampling to estimate numerical results, especially for problems with many degrees of freedom.', example: 'Pricing exotic derivatives with path-dependent payoffs.' },
  { id: 'alpha-finance', field: 'quant', term: 'Alpha (α)', definition: 'Excess return of an investment relative to a benchmark index. Positive alpha means the strategy beat the market.', example: 'A fund returning 12% when the S&P returned 10% has α = 2%.' },
  { id: 'bid-ask-spread', field: 'quant', term: 'Bid-Ask Spread', definition: 'The difference between the highest price a buyer will pay (bid) and the lowest price a seller will accept (ask). It is the cost of immediacy.', example: 'Apple stock has a ~$0.01 spread; illiquid penny stocks may have $0.10+ spreads.' },
  { id: 'kyles-lambda', field: 'quant', term: 'Kyle\'s Lambda (λ)', definition: 'The price impact coefficient from Kyle (1985): $\\Delta P = \\lambda Q$. It measures market depth and adverse selection — higher λ means less liquid.', example: 'Optimal execution algorithms use λ to estimate how much a large order will move the market.' },
  { id: 'hawkes-process', field: 'quant', term: 'Hawkes Process', definition: 'A self-exciting point process where each event increases the probability of subsequent events: $\\lambda(t) = \\mu + \\sum \\alpha e^{-\\beta(t-t_i)}$.', example: 'Used to model clustered trade arrivals, flash crashes, and HFT dynamics.' },
  { id: 'merton-model', field: 'quant', term: 'Merton Structural Model', definition: 'Treats equity as a call option on firm assets: default occurs when $V_T < D$. The distance-to-default measures credit risk.', example: 'Moody\'s KMV model, used globally for credit risk assessment, is based on Merton\'s framework.' },
  { id: 'cva', field: 'quant', term: 'Credit Valuation Adjustment (CVA)', definition: 'The market price of counterparty credit risk: $\\text{CVA} = \\int \\text{LGD} \\cdot \\text{PD}(t) \\cdot \\text{EE}(t)\\,dt$. Required under Basel III.', example: 'Major banks have dedicated XVA desks managing billions in valuation adjustments.' },
];
