import type { GlossaryTerm } from './types';

export const quantumConsciousnessTerms: GlossaryTerm[] = [
  {
    id: 'orch-or', field: 'physics', topic: 'neuroscience',
    term: 'Orchestrated Objective Reduction (Orch OR)',
    definition: 'Penrose-Hameroff theory that consciousness arises from quantum superpositions in microtubule tubulin proteins, which collapse via gravitational objective reduction (OR) at timescale $\\tau \\approx \\hbar / E_G$, producing ~40 Hz "moments" of awareness.',
    formula: '$\\tau \\approx \\frac{\\hbar}{E_G}$',
    latex: '\\tau \\approx \\frac{\\hbar}{E_G}',
    thinkerLinks: ['roger-penrose', 'stuart-hameroff'],
    formulaLinks: ['penrose-or-timescale'],
    related: ['objective-reduction', 'microtubule-quantum-coherence', 'frohlich-condensate'],
    difficulty: 'advanced',
  },
  {
    id: 'objective-reduction', field: 'physics', topic: 'quantum-gravity',
    term: 'Penrose Objective Reduction (OR)',
    definition: 'Penrose\'s proposal that quantum superpositions of sufficiently different spacetime geometries are inherently unstable and collapse non-computably in time $\\tau \\approx \\hbar / E_G$, where $E_G$ is the gravitational self-energy difference between the superposed mass configurations.',
    formula: '$\\tau \\approx \\frac{\\hbar}{E_G}$',
    latex: '\\tau \\approx \\frac{\\hbar}{E_G}',
    thinkerLinks: ['roger-penrose'],
    related: ['orch-or', 'black-hole-entropy'],
    difficulty: 'advanced',
  },
  {
    id: 'microtubule-quantum-coherence', field: 'physics', topic: 'neuroscience',
    term: 'Microtubule Quantum Coherence',
    definition: 'The hypothesis that tubulin proteins in neuronal microtubules can maintain quantum superposition states within hydrophobic pockets, shielded from thermal decoherence. Bandyopadhyay\'s THz resonance experiments (2023–2024) provide preliminary evidence.',
    thinkerLinks: ['stuart-hameroff', 'anirban-bandyopadhyay'],
    related: ['orch-or', 'frohlich-condensate'],
    difficulty: 'advanced',
  },
  {
    id: 'frohlich-condensate', field: 'physics', topic: 'neuroscience',
    term: 'Fröhlich Condensate',
    definition: 'Herbert Fröhlich\'s (1968) prediction that metabolic energy pumped into biological oscillators can drive them into a single coherent quantum mode — a phonon condensate at THz frequencies, analogous to a biological Bose-Einstein condensate at body temperature.',
    formula: '$\\dot{n}_s = P_s - \\gamma_s n_s + \\sum_{s\'} \\Phi_{ss\'}(n_s n_{s\'} - n_s\' n_s)$',
    latex: '\\dot{n}_s = P_s - \\gamma_s n_s + \\sum_{s\'} \\Phi_{ss\'}(n_s n_{s\'} - n_s\' n_s)',
    thinkerLinks: ['stuart-hameroff'],
    related: ['orch-or', 'microtubule-quantum-coherence'],
    difficulty: 'advanced',
  },
  {
    id: 'tubulin-dipole-qubit', field: 'physics', topic: 'neuroscience',
    term: 'Tubulin Dipole Qubit',
    definition: 'In Orch OR, each tubulin dimer has two conformational states (α and β) with different electric dipole moments, forming a natural two-state quantum system (qubit). The microtubule lattice of ~$10^4$–$10^5$ coupled tubulin qubits supports entangled superpositions.',
    thinkerLinks: ['stuart-hameroff', 'roger-penrose'],
    related: ['orch-or', 'microtubule-quantum-coherence'],
    difficulty: 'advanced',
  },
  {
    id: 'penrose-non-computability', field: 'physics', topic: 'quantum-gravity',
    term: 'Penrose Non-Computability Thesis',
    definition: 'Penrose\'s argument (The Emperor\'s New Mind, 1989; Shadows of the Mind, 1994) that human mathematical understanding involves non-computable processes — consciousness cannot be simulated by any Turing machine, requiring new physics (objective reduction) beyond algorithmic quantum mechanics.',
    thinkerLinks: ['roger-penrose'],
    related: ['objective-reduction', 'orch-or'],
    difficulty: 'advanced',
  },
  {
    id: 'gravitational-self-energy', field: 'physics', topic: 'quantum-gravity',
    term: 'Gravitational Self-Energy of Superposition',
    definition: 'The energy $E_G$ measuring the gravitational "cost" of maintaining a quantum superposition of two distinct mass distributions. In Penrose OR, $E_G = \\int |\\nabla(\\Phi_1 - \\Phi_2)|^2 / (8\\pi G)\\, d^3x$ where $\\Phi_1, \\Phi_2$ are the Newtonian potentials of the two configurations.',
    formula: '$E_G = \\frac{1}{8\\pi G}\\int |\\nabla(\\Phi_1 - \\Phi_2)|^2 \\, d^3x$',
    latex: 'E_G = \\frac{1}{8\\pi G}\\int |\\nabla(\\Phi_1 - \\Phi_2)|^2 \\, d^3x',
    thinkerLinks: ['roger-penrose'],
    formulaLinks: ['penrose-or-timescale'],
    related: ['objective-reduction', 'orch-or'],
    difficulty: 'advanced',
  },
  {
    id: 'quantum-biology', field: 'physics', topic: 'neuroscience',
    term: 'Quantum Biology',
    definition: 'The study of quantum phenomena in biological systems: photosynthetic energy transfer (FMO complex), enzyme tunneling, avian magnetoreception (radical pair mechanism), olfaction (phonon-assisted tunneling), and potentially consciousness (Orch OR). Distinct from molecular biology, which treats molecules classically.',
    related: ['orch-or', 'microtubule-quantum-coherence', 'frohlich-condensate'],
    difficulty: 'intermediate',
  },
];
