import type { GlossaryTerm } from './types';

export const quantTerms: GlossaryTerm[] = [
  { id: 'black-scholes', field: 'quant', term: 'Black–Scholes Model', definition: 'A model for pricing European options using stock price, strike, volatility, time to expiry, and risk-free rate: $C = S\\,N(d_1) - Ke^{-rT}N(d_2)$.', example: 'Every options trading desk uses Black-Scholes or its extensions.' },
  { id: 'sharpe-ratio', field: 'quant', term: 'Sharpe Ratio', definition: 'Risk-adjusted return: $S = \\frac{R_p - R_f}{\\sigma_p}$. Higher is better—more return per unit of risk.', example: 'Hedge funds target Sharpe ratios above 1.0 for investor appeal.' },
  { id: 'var', field: 'quant', term: 'Value at Risk (VaR)', definition: 'The maximum expected loss over a given time horizon at a specified confidence level (e.g., 95% VaR).', example: 'Banks use VaR to determine capital reserves for regulatory compliance.' },
  { id: 'stochastic-process', field: 'quant', term: 'Stochastic Process', definition: 'A collection of random variables indexed by time, modelling systems that evolve probabilistically.', example: 'Stock prices are modelled as geometric Brownian motion.' },
  { id: 'monte-carlo', field: 'quant', term: 'Monte Carlo Simulation', definition: 'Using repeated random sampling to estimate numerical results, especially for problems with many degrees of freedom.', example: 'Pricing exotic derivatives with path-dependent payoffs.' },
  { id: 'alpha-finance', field: 'quant', term: 'Alpha (α)', definition: 'Excess return of an investment relative to a benchmark index. Positive alpha means the strategy beat the market.', example: 'A fund returning 12% when the S&P returned 10% has α = 2%.' },
  { id: 'bid-ask-spread', field: 'quant', term: 'Bid-Ask Spread', definition: 'The difference between the highest price a buyer will pay (bid) and the lowest price a seller will accept (ask). It is the cost of immediacy.', example: 'Apple stock has a ~$0.01 spread; illiquid penny stocks may have $0.10+ spreads.' },
  { id: 'kyles-lambda', field: 'quant', term: 'Kyle\'s Lambda (λ)', definition: 'The price impact coefficient from Kyle (1985): $\\Delta P = \\lambda Q$. It measures market depth and adverse selection — higher λ means less liquid.', example: 'Optimal execution algorithms use λ to estimate how much a large order will move the market.' },
  { id: 'hawkes-process', field: 'quant', term: 'Hawkes Process', definition: 'A self-exciting point process where each event increases the probability of subsequent events: $\\lambda(t) = \\mu + \\sum \\alpha e^{-\\beta(t-t_i)}$.', example: 'Used to model clustered trade arrivals, flash crashes, and HFT dynamics.' },
  { id: 'merton-model', field: 'quant', term: 'Merton Structural Model', definition: 'Treats equity as a call option on firm assets: default occurs when $V_T < D$. The distance-to-default measures credit risk.', example: 'Moody\'s KMV model, used globally for credit risk assessment, is based on Merton\'s framework.' },
  { id: 'cva', field: 'quant', term: 'Credit Valuation Adjustment (CVA)', definition: 'The market price of counterparty credit risk: $\\text{CVA} = \\int \\text{LGD} \\cdot \\text{PD}(t) \\cdot \\text{EE}(t)\\,dt$. Required under Basel III.', example: 'Major banks have dedicated XVA desks managing billions in valuation adjustments.' },
  { id: 'reservation-price', field: 'quant', term: 'Reservation Price (Avellaneda-Stoikov)', definition: 'The market maker\'s internal fair value adjusted for inventory: $r = s - q \\cdot \\gamma \\sigma^2 (T - t)$. Long inventory shades $r$ below mid; short inventory shades above.', example: 'A Kalshi weather market maker long on heat bins shades YES fair value down to sell more aggressively.', formula: 'r = s - q \\cdot \\gamma \\sigma^2 (T - t)', latex: 'r = s - q \\cdot \\gamma \\sigma^2 (T - t)', code: '-- Discrete adaptation\\nr = s - λ · q\\n-- where λ = γ·σ²·(T−t)' },
  { id: 'optimal-spread', field: 'quant', term: 'Optimal Half-Spread (A-S)', definition: 'The optimal quote width: $\\delta = \\gamma\\sigma^2(T-t) + \\frac{2}{\\gamma}\\ln(1 + \\gamma/\\kappa)$. First term = inventory risk; second = pure liquidity profit ($\\kappa$ = order arrival rate).', example: 'Widen spread when models diverge or expiry nears; tighten when forecast confidence is high and order flow is balanced.', formula: '\\delta = \\gamma\\sigma^2(T-t) + \\frac{2}{\\gamma}\\ln\\left(1 + \\frac{\\gamma}{\\kappa}\\right)', latex: '\\delta = \\gamma\\sigma^2(T-t) + \\frac{2}{\\gamma}\\ln\\left(1 + \\frac{\\gamma}{\\kappa}\\right)' },
  { id: 'binary-contract', field: 'quant', term: 'Binary Prediction Contract', definition: 'A contract that pays $1 if an event occurs, $0 otherwise. The price equals the market-implied probability. YES + NO = $1.00 by no-arbitrage.', example: 'Kalshi offers binary contracts on Fed decisions, weather, GDP, and elections.' },
  { id: 'lmsr', field: 'quant', term: 'Logarithmic Market Scoring Rule (LMSR)', definition: 'Hanson\'s automated market maker: $C(\\mathbf{q}) = b \\cdot \\ln(\\sum_i e^{q_i/b})$. Provides continuous liquidity with bounded maximum loss of $b \\cdot \\ln(n)$.', example: 'Used in academic prediction tournaments and early DeFi prediction platforms like Augur.', formula: 'C(\\mathbf{q}) = b \\cdot \\ln\\left(\\sum_i e^{q_i/b}\\right)', latex: 'C(\\mathbf{q}) = b \\cdot \\ln\\left(\\sum_i e^{q_i/b}\\right)' },
  { id: 'vpin', field: 'quant', term: 'VPIN (Volume-Synchronized PIN)', definition: 'A real-time toxicity metric measuring informed trading: $\\text{VPIN} = \\frac{\\sum |V_B^\\tau - V_S^\\tau|}{n \\cdot V}$. High VPIN signals one-sided flow and potential adverse selection.', example: 'VPIN spiked before the 2010 Flash Crash. Market makers use it to widen spreads or withdraw quotes.', formula: '\\text{VPIN} = \\frac{\\sum |V_B^\\tau - V_S^\\tau|}{n \\cdot V}', latex: '\\text{VPIN} = \\frac{\\sum |V_B^\\tau - V_S^\\tau|}{n \\cdot V}' },
];
