import type { GlossaryTerm } from './types';

export const statisticalLearningTerms: GlossaryTerm[] = [
  {
    id: 'lasso',
    field: 'math',
    topic: 'statistics',
    term: 'LASSO',
    definition: 'Least Absolute Shrinkage and Selection Operator: $\\min_\\beta \\|y - X\\beta\\|_2^2 + \\lambda\\|\\beta\\|_1$. The $L_1$ penalty drives coefficients to exactly zero, performing automatic variable selection.',
    example: 'Selecting 20 disease-associated genes from 20,000 candidates in a genome-wide association study.',
    formula: '$\\hat{\\beta} = \\arg\\min_\\beta \\|y - X\\beta\\|_2^2 + \\lambda\\|\\beta\\|_1$',
    latex: '\\hat{\\beta} = \\arg\\min_\\beta \\|y - X\\beta\\|_2^2 + \\lambda\\|\\beta\\|_1',
    symbolLinks: { 'λ': 'lambda', 'β': 'beta' },
    formulaLinks: ['lasso-l1-regularisation'],
    thinkerLinks: ['robert-tibshirani'],
    related: ['elastic-net', 'regularization', 'sparsity'],
    difficulty: 'intermediate',
  },
  {
    id: 'elastic-net',
    field: 'math',
    topic: 'statistics',
    term: 'Elastic Net',
    definition: 'Combines $L_1$ (LASSO) and $L_2$ (Ridge) penalties: $\\lambda_1\\|\\beta\\|_1 + \\lambda_2\\|\\beta\\|_2^2$. Handles correlated predictors better than pure LASSO by grouping them together.',
    example: 'Gene pathway analysis where co-regulated genes should be selected as a group, not individually.',
    formula: '$\\hat{\\beta} = \\arg\\min_\\beta \\|y - X\\beta\\|_2^2 + \\lambda_1\\|\\beta\\|_1 + \\lambda_2\\|\\beta\\|_2^2$',
    latex: '\\hat{\\beta} = \\arg\\min_\\beta \\|y - X\\beta\\|_2^2 + \\lambda_1\\|\\beta\\|_1 + \\lambda_2\\|\\beta\\|_2^2',
    symbolLinks: { 'λ': 'lambda', 'β': 'beta' },
    formulaLinks: ['elastic-net', 'lasso-l1-regularisation'],
    thinkerLinks: ['robert-tibshirani'],
    related: ['lasso', 'regularization'],
    difficulty: 'intermediate',
  },
  {
    id: 'regularization',
    field: 'math',
    topic: 'statistics',
    term: 'Regularization',
    definition: 'Adding a penalty term $\\Omega(\\theta)$ to the loss function to prevent overfitting: $\\mathcal{L}(\\theta) + \\lambda\\Omega(\\theta)$. Controls model complexity by trading bias for reduced variance.',
    example: 'Weight decay in neural networks is $L_2$ regularization applied to every layer.',
    formula: '$\\min_\\theta \\mathcal{L}(\\theta) + \\lambda\\Omega(\\theta)$',
    latex: '\\min_\\theta \\mathcal{L}(\\theta) + \\lambda\\Omega(\\theta)',
    symbolLinks: { 'λ': 'lambda', 'θ': 'theta', 'Ω': 'omega' },
    formulaLinks: ['lasso-l1-regularisation'],
    thinkerLinks: ['robert-tibshirani', 'vladimir-vapnik'],
    related: ['lasso', 'elastic-net', 'bias-variance-tradeoff'],
    difficulty: 'intro',
  },
  {
    id: 'sparsity',
    field: 'math',
    topic: 'statistics',
    term: 'Sparsity',
    definition: 'A vector is $k$-sparse if at most $k$ of its entries are nonzero: $\\|x\\|_0 \\leq k$. Sparsity is the structural assumption underlying compressed sensing, LASSO, and high-dimensional statistics.',
    example: 'Natural images are sparse in wavelet bases — most coefficients are near zero, enabling JPEG compression.',
    formula: '$\\|x\\|_0 = |\\{i : x_i \\neq 0\\}| \\leq k$',
    latex: '\\|x\\|_0 = |\\{i : x_i \\neq 0\\}| \\leq k',
    symbolLinks: { 'k': 'kappa' },
    formulaLinks: ['lasso-l1-regularisation'],
    thinkerLinks: ['robert-tibshirani', 'emmanuel-candes'],
    related: ['lasso', 'compressed-sensing'],
    difficulty: 'intro',
  },
  {
    id: 'bias-variance-tradeoff',
    field: 'math',
    topic: 'statistics',
    term: 'Bias–Variance Tradeoff',
    definition: 'Mean squared error decomposes as $\\text{MSE} = \\text{Bias}^2 + \\text{Variance} + \\sigma^2$. Simple models have high bias (underfit); complex models have high variance (overfit). Regularization navigates this tradeoff.',
    example: 'A degree-1 polynomial underfits noisy data (high bias); a degree-20 polynomial overfits (high variance).',
    formula: '$E[(y - \\hat{f})^2] = (E[\\hat{f}] - f)^2 + \\text{Var}(\\hat{f}) + \\sigma^2$',
    latex: 'E[(y - \\hat{f})^2] = (E[\\hat{f}] - f)^2 + \\text{Var}(\\hat{f}) + \\sigma^2',
    symbolLinks: { 'σ': 'sigma' },
    thinkerLinks: ['robert-tibshirani'],
    related: ['regularization', 'cross-validation'],
    difficulty: 'intro',
  },
  {
    id: 'cross-validation',
    field: 'math',
    topic: 'statistics',
    term: 'Cross-Validation',
    definition: '$k$-fold CV splits data into $k$ folds, trains on $k-1$ and tests on the held-out fold, rotating through all folds. The average test error estimates generalization performance.',
    example: 'Choosing $\\lambda$ in LASSO: 10-fold CV finds the $\\lambda$ that minimizes out-of-sample prediction error.',
    formula: '$\\text{CV}(k) = \\frac{1}{k}\\sum_{i=1}^k L(y_i^{\\text{test}}, \\hat{f}_{-i}(x_i^{\\text{test}}))$',
    latex: '\\text{CV}(k) = \\frac{1}{k}\\sum_{i=1}^k L(y_i^{\\text{test}}, \\hat{f}_{-i}(x_i^{\\text{test}}))',
    symbolLinks: { 'k': 'kappa', 'λ': 'lambda' },
    thinkerLinks: ['robert-tibshirani'],
    related: ['bias-variance-tradeoff', 'regularization'],
    difficulty: 'intro',
  },
  {
    id: 'false-discovery-rate',
    field: 'math',
    topic: 'statistics',
    term: 'False Discovery Rate (FDR)',
    definition: 'The expected proportion of false positives among all rejected hypotheses: $\\text{FDR} = E[V/R]$ where $V$ = false rejections, $R$ = total rejections. Benjamini-Hochberg controls FDR at level $q$.',
    example: 'In a genomics study testing 20,000 genes, FDR control at 5% means ~5% of "significant" genes are false leads.',
    formula: '$\\text{FDR} = E\\left[\\frac{V}{\\max(R, 1)}\\right] \\leq q$',
    latex: '\\text{FDR} = E\\left[\\frac{V}{\\max(R, 1)}\\right] \\leq q',
    thinkerLinks: ['robert-tibshirani'],
    related: ['multiple-testing', 'sam'],
    difficulty: 'intermediate',
  },
  {
    id: 'conformal-prediction',
    field: 'math',
    topic: 'statistics',
    term: 'Conformal Prediction',
    definition: 'A distribution-free framework that wraps any prediction model to produce prediction sets $C(X)$ with exact finite-sample coverage: $P(Y \\in C(X)) \\geq 1-\\alpha$. Requires only exchangeability.',
    example: 'Medical AI: "This patient\'s estimated survival is 18-30 months with 90% coverage."',
    formula: '$P(Y_{n+1} \\in C(X_{n+1})) \\geq 1 - \\alpha$',
    latex: 'P(Y_{n+1} \\in C(X_{n+1})) \\geq 1 - \\alpha',
    symbolLinks: { 'α': 'alpha' },
    formulaLinks: ['conformal-prediction'],
    thinkerLinks: ['robert-tibshirani'],
    related: ['prediction-interval', 'cross-validation'],
    difficulty: 'advanced',
  },
  {
    id: 'lars',
    field: 'math',
    topic: 'statistics',
    term: 'LARS (Least Angle Regression)',
    definition: 'An efficient algorithm that computes the entire LASSO regularization path. At each step, it identifies the predictor most correlated with the residual and moves $\\hat{\\beta}$ in that direction until another predictor is equally correlated, then adjusts the angle.',
    example: 'Computing LASSO solutions for 100 values of $\\lambda$ at the cost of a single OLS fit.',
    formula: '$\\hat{\\mu}_{\\text{LARS}} = \\hat{\\mu}_{\\mathcal{A}} + \\hat{\\gamma} u_{\\mathcal{A}}$',
    latex: '\\hat{\\mu}_{\\text{LARS}} = \\hat{\\mu}_{\\mathcal{A}} + \\hat{\\gamma} u_{\\mathcal{A}}',
    symbolLinks: { 'γ': 'gamma', 'μ': 'mu' },
    formulaLinks: ['lasso-l1-regularisation'],
    thinkerLinks: ['robert-tibshirani'],
    related: ['lasso', 'regularization'],
    difficulty: 'advanced',
  },
  {
    id: 'multiple-testing',
    field: 'math',
    topic: 'statistics',
    term: 'Multiple Testing Correction',
    definition: 'When performing $m$ simultaneous hypothesis tests, the probability of at least one false positive is $1-(1-\\alpha)^m \\approx m\\alpha$ for small $\\alpha$. Bonferroni, Holm, and FDR methods control error rates.',
    example: 'Testing 10,000 SNPs for disease association: without correction, ~500 false positives at $\\alpha=0.05$.',
    formula: '$\\alpha_{\\text{Bonferroni}} = \\alpha / m$',
    latex: '\\alpha_{\\text{Bonferroni}} = \\alpha / m',
    symbolLinks: { 'α': 'alpha' },
    thinkerLinks: ['robert-tibshirani'],
    related: ['false-discovery-rate'],
    difficulty: 'intermediate',
  },
  {
    id: 'bootstrap',
    field: 'math',
    topic: 'statistics',
    term: 'Bootstrap',
    definition: 'A resampling method that draws $B$ samples of size $n$ with replacement from the observed data to estimate the sampling distribution of a statistic $\\hat{\\theta}$.',
    example: 'Constructing a 95% confidence interval for the median income without assuming normality.',
    formula: '$\\widehat{\\text{Var}}(\\hat{\\theta}) = \\frac{1}{B-1}\\sum_{b=1}^{B}(\\hat{\\theta}^{*b} - \\bar{\\theta}^{*})^2$',
    latex: '\\widehat{\\text{Var}}(\\hat{\\theta}) = \\frac{1}{B-1}\\sum_{b=1}^{B}(\\hat{\\theta}^{*b} - \\bar{\\theta}^{*})^2',
    symbolLinks: { 'θ': 'theta' },
    formulaLinks: ['bootstrap-variance-estimator'],
    thinkerLinks: ['bradley-efron'],
    related: ['cross-validation', 'bias-variance-tradeoff'],
    difficulty: 'intro',
  },
  {
    id: 'empirical-bayes',
    field: 'math',
    topic: 'statistics',
    term: 'Empirical Bayes',
    definition: 'A framework where the prior distribution $f(\\theta)$ is estimated from the data\'s marginal distribution rather than specified subjectively: $\\hat{\\theta}_i^{EB} = (1 - B_i)\\hat{\\theta}_i + B_i \\hat{\\mu}$.',
    example: 'Estimating batting averages for baseball players by shrinking individual averages toward the league mean.',
    formula: '$\\hat{\\theta}_i^{EB} = (1 - B_i)\\hat{\\theta}_i^{MLE} + B_i \\hat{\\mu}$',
    latex: '\\hat{\\theta}_i^{EB} = (1 - B_i)\\hat{\\theta}_i^{MLE} + B_i \\hat{\\mu}',
    symbolLinks: { 'θ': 'theta', 'μ': 'mu' },
    formulaLinks: ['empirical-bayes-estimation'],
    thinkerLinks: ['bradley-efron'],
    related: ['false-discovery-rate', 'regularization'],
    difficulty: 'intermediate',
  },
  {
    id: 'gam',
    field: 'math',
    topic: 'statistics',
    term: 'Generalized Additive Model (GAM)',
    definition: 'Extends GLMs by replacing linear predictors with smooth nonparametric functions: $g(E[Y]) = \\alpha + \\sum f_j(X_j)$. Fitted via backfitting with smoothing splines.',
    example: 'Modeling the nonlinear effect of temperature on mortality rates while controlling for humidity linearly.',
    formula: '$g(E[Y]) = \\alpha + \\sum_{j=1}^{p} f_j(X_j)$',
    latex: 'g(E[Y]) = \\alpha + \\sum_{j=1}^{p} f_j(X_j)',
    formulaLinks: ['gam-additive-model'],
    thinkerLinks: ['trevor-hastie', 'robert-tibshirani'],
    related: ['regularization', 'sparsity'],
    difficulty: 'intermediate',
  },
  {
    id: 'random-forest',
    field: 'cs',
    topic: 'machine-learning',
    term: 'Random Forest',
    definition: 'An ensemble method that trains $B$ decision trees on bootstrap samples with random feature subsets at each split, then averages predictions to reduce variance.',
    example: 'Predicting customer churn using hundreds of decorrelated decision trees trained on different data subsets.',
    formula: '$\\hat{f}_{\\text{RF}}(x) = \\frac{1}{B}\\sum_{b=1}^{B} T_b(x)$',
    latex: '\\hat{f}_{\\text{RF}}(x) = \\frac{1}{B}\\sum_{b=1}^{B} T_b(x)',
    formulaLinks: ['bootstrap-variance-estimator'],
    thinkerLinks: ['trevor-hastie'],
    related: ['bootstrap', 'gradient-boosting', 'bias-variance-tradeoff'],
    difficulty: 'intro',
  },
  {
    id: 'gradient-boosting',
    field: 'cs',
    topic: 'machine-learning',
    term: 'Gradient Boosting',
    definition: 'Builds an ensemble sequentially: each new weak learner $h_m$ fits the negative gradient of the loss $-\\nabla_F L(y, F(x))$ with respect to the current prediction.',
    example: 'XGBoost winning Kaggle competitions by sequentially correcting prediction errors with small decision trees.',
    formula: '$F_m(x) = F_{m-1}(x) + \\nu \\cdot h_m(x)$',
    latex: 'F_m(x) = F_{m-1}(x) + \\nu \\cdot h_m(x)',
    symbolLinks: { 'ν': 'nu' },
    formulaLinks: ['gradient-boosting-update'],
    thinkerLinks: ['trevor-hastie'],
    related: ['random-forest', 'bias-variance-tradeoff'],
    difficulty: 'intermediate',
  },
];
