import type { GlossaryTerm } from './types';

export const statisticalPhysicsTerms: GlossaryTerm[] = [
  {
    id: 'partition-function', field: 'physics', topic: 'statistical-physics',
    term: 'Partition Function',
    definition: 'The sum over all microstates $Z = \\sum_i e^{-\\beta E_i}$ that encodes the statistical properties of a system in thermodynamic equilibrium.',
    formula: '$Z = \\sum_i e^{-E_i / k_B T}$',
    latex: 'Z = \\sum_i e^{-E_i / k_B T}',
    example: 'All thermodynamic quantities (free energy, entropy, pressure) can be derived from $Z$.',
    symbolLinks: { 'Z': 'zeta', 'β': 'beta', 'E': 'epsilon' },
    thinkerLinks: ['boltzmann', 'gibbs'],
    formulaLinks: ['boltzmann-distribution'],
    related: ['entropy-phys', 'boltzmann-distribution-gloss'],
    difficulty: 'intermediate',
  },
  {
    id: 'boltzmann-distribution-gloss', field: 'physics', topic: 'statistical-physics',
    term: 'Boltzmann Distribution',
    definition: 'The probability of a microstate with energy $E$ is $p \\propto e^{-E/k_BT}$. Foundation of classical statistical mechanics.',
    formula: '$p_i = \\frac{e^{-E_i/k_BT}}{Z}$',
    latex: 'p_i = \\frac{e^{-E_i/k_BT}}{Z}',
    example: 'Explains why gas molecules follow the Maxwell speed distribution.',
    symbolLinks: { 'p': 'pi', 'E': 'epsilon', 'T': 'tau' },
    thinkerLinks: ['boltzmann'],
    related: ['partition-function', 'entropy-phys'],
    difficulty: 'intro',
  },
  {
    id: 'ising-model', field: 'physics', topic: 'statistical-physics',
    term: 'Ising Model',
    definition: 'A lattice model of interacting spins $H = -J\\sum_{\\langle ij \\rangle} s_i s_j$ exhibiting a phase transition between ordered and disordered states.',
    formula: '$H = -J\\sum_{\\langle ij \\rangle} s_i s_j - h\\sum_i s_i$',
    latex: 'H = -J\\sum_{\\langle ij \\rangle} s_i s_j - h\\sum_i s_i',
    example: 'Onsager\'s exact solution of the 2D Ising model was a landmark in theoretical physics.',
    thinkerLinks: ['onsager'],
    related: ['partition-function', 'renormalization-gloss'],
    difficulty: 'intermediate',
  },
  {
    id: 'renormalization-gloss', field: 'physics', topic: 'statistical-physics',
    term: 'Renormalization Group',
    definition: 'A mathematical framework for studying how physical systems change under scale transformations, explaining universality near critical points.',
    example: 'Explains why water boiling and magnets demagnetizing share the same critical exponents.',
    thinkerLinks: ['wilson'],
    related: ['ising-model'],
    difficulty: 'advanced',
  },
  {
    id: 'fermi-dirac', field: 'physics', topic: 'statistical-physics',
    term: 'Fermi–Dirac Distribution',
    definition: 'The occupancy of fermion states: $f(E) = \\frac{1}{e^{(E-\\mu)/k_BT}+1}$. Governs electrons in metals and white dwarfs.',
    formula: '$f(E) = \\frac{1}{e^{(E-\\mu)/k_BT}+1}$',
    latex: 'f(E) = \\frac{1}{e^{(E-\\mu)/k_BT}+1}',
    symbolLinks: { 'μ': 'mu', 'E': 'epsilon' },
    thinkerLinks: ['dirac'],
    related: ['bose-einstein-gloss'],
    difficulty: 'intermediate',
  },
  {
    id: 'bose-einstein-gloss', field: 'physics', topic: 'statistical-physics',
    term: 'Bose–Einstein Distribution',
    definition: 'The occupancy of boson states: $n(E) = \\frac{1}{e^{(E-\\mu)/k_BT}-1}$. Predicts Bose–Einstein condensation at ultra-cold temperatures.',
    formula: '$n(E) = \\frac{1}{e^{(E-\\mu)/k_BT}-1}$',
    latex: 'n(E) = \\frac{1}{e^{(E-\\mu)/k_BT}-1}',
    thinkerLinks: ['einstein'],
    related: ['fermi-dirac'],
    difficulty: 'intermediate',
  },
];
