import type { Question } from '../types';

export const statisticalPhysicsEasyQuestions: Question[] = [
  {
    id: 28001,
    topic: 'statistical-physics',
    difficulty: 'easy',
    question: 'The Boltzmann distribution gives the probability of a microstate with energy $E$ as $P \\propto$:',
    options: ['$e^{-E/k_BT}$', '$e^{E/k_BT}$', '$E/k_BT$', '$1/E$'],
    correctIndex: 0,
    explanation: 'The canonical Boltzmann factor $e^{-E/k_BT}$ exponentially suppresses high-energy states. The partition function $Z = \\sum e^{-E_i/k_BT}$ normalizes it.',
    realWorld: 'Every chemical reaction rate, semiconductor band gap calculation, and stellar atmosphere model uses the Boltzmann distribution.',
    hint: 'Higher energy → lower probability. Temperature controls the suppression.',
  },
  {
    id: 28002,
    topic: 'statistical-physics',
    difficulty: 'easy',
    question: 'The equipartition theorem states that each quadratic degree of freedom contributes what average energy?',
    options: ['$\\frac{1}{2}k_BT$', '$k_BT$', '$\\frac{3}{2}k_BT$', '$2k_BT$'],
    correctIndex: 0,
    explanation: 'Each quadratic term in the Hamiltonian (e.g., $\\frac{1}{2}mv_x^2$) contributes $\\frac{1}{2}k_BT$ to the average energy at thermal equilibrium.',
    realWorld: 'This explains why monatomic ideal gases have $C_V = \\frac{3}{2}Nk_B$ — three translational degrees of freedom.',
    hint: 'A 3D ideal gas has 3 quadratic terms → total energy $\\frac{3}{2}k_BT$ per particle.',
  },
  {
    id: 28003,
    topic: 'statistical-physics',
    difficulty: 'easy',
    question: 'The partition function $Z$ encodes all thermodynamic information. The free energy $F$ is related to $Z$ by:',
    options: ['$F = -k_BT \\ln Z$', '$F = k_BT Z$', '$F = -k_BT / Z$', '$F = k_BT \\ln(1/Z)$'],
    correctIndex: 0,
    explanation: 'The Helmholtz free energy $F = -k_BT \\ln Z$ is the bridge between statistical mechanics and thermodynamics. All quantities (entropy, pressure, energy) follow from derivatives of $F$.',
    realWorld: 'Computational chemists calculate $Z$ via molecular dynamics to predict drug binding affinities.',
    hint: 'The logarithm converts the multiplicative partition function into an additive free energy.',
  },
];

export const statisticalPhysicsHardQuestions: Question[] = [
  {
    id: 28011,
    topic: 'statistical-physics',
    difficulty: 'hard',
    question: 'Fermions obey Fermi-Dirac statistics. The mean occupation number of a single-particle state with energy $\\epsilon$ is:',
    options: [
      '$\\frac{1}{e^{(\\epsilon-\\mu)/k_BT} + 1}$',
      '$\\frac{1}{e^{(\\epsilon-\\mu)/k_BT} - 1}$',
      '$e^{-(\\epsilon-\\mu)/k_BT}$',
      '$\\frac{1}{2}$ always',
    ],
    correctIndex: 0,
    explanation: 'The $+1$ in the denominator enforces the Pauli exclusion principle: $\\langle n \\rangle \\leq 1$. At $T=0$, the distribution becomes a sharp step at the Fermi energy $\\mu$.',
    realWorld: 'Fermi-Dirac statistics govern electron behavior in metals, semiconductors, and white dwarf stars.',
    hint: 'Bosons get a $-1$ (Bose-Einstein). Fermions get a $+1$. The sign enforces their quantum identity.',
  },
  {
    id: 28012,
    topic: 'statistical-physics',
    difficulty: 'hard',
    question: 'The Ising model on a 2D square lattice exhibits a phase transition at the Onsager critical temperature $T_c$. What is $k_BT_c/J$?',
    options: [
      '$\\frac{2}{\\ln(1+\\sqrt{2})} \\approx 2.269$',
      '$1$',
      '$\\pi$',
      '$\\frac{1}{2}$',
    ],
    correctIndex: 0,
    explanation: 'Onsager\'s exact solution (1944) gave $k_BT_c/J = 2/\\ln(1+\\sqrt{2})$. This was the first exact solution of a model with a phase transition — a landmark in theoretical physics.',
    realWorld: 'The 2D Ising model is the benchmark for every Monte Carlo simulation in statistical physics and materials science.',
    hint: 'Onsager solved it exactly in 1944 — one of the greatest feats of mathematical physics.',
  },
  {
    id: 28013,
    topic: 'statistical-physics',
    difficulty: 'hard',
    question: 'In the grand canonical ensemble, the thermodynamic potential is the grand potential $\\Omega$. It relates to the grand partition function $\\mathcal{Z}$ by:',
    options: [
      '$\\Omega = -k_BT \\ln \\mathcal{Z}$',
      '$\\Omega = k_BT \\mathcal{Z}$',
      '$\\Omega = -k_BT / \\mathcal{Z}$',
      '$\\Omega = \\ln \\mathcal{Z} / k_BT$',
    ],
    correctIndex: 0,
    explanation: 'The grand potential $\\Omega = -k_BT \\ln \\mathcal{Z} = F - \\mu N = -PV$ for a homogeneous system. It naturally handles particle exchange with a reservoir.',
    realWorld: 'Essential for modeling open systems: adsorption on surfaces, chemical reactions, and Bose-Einstein condensation.',
    hint: 'Same structure as $F = -k_BT \\ln Z$, but now the partition function sums over particle numbers too.',
  },
];

export const statisticalPhysicsSotaQuestions: Question[] = [
  {
    id: 28021,
    topic: 'statistical-physics',
    difficulty: 'sota',
    question: 'The renormalization group (RG) explains universality in phase transitions. Near a critical point, the correlation length diverges as $\\xi \\sim |T-T_c|^{-\\nu}$. What determines $\\nu$?',
    options: [
      'The dimensionality $d$ and symmetry of the order parameter — not microscopic details',
      'The lattice constant and atomic mass',
      'The specific chemical composition',
      'The external magnetic field strength',
    ],
    correctIndex: 0,
    explanation: 'Critical exponents like $\\nu$ depend only on universality class (dimension + symmetry). Water and ferromagnets share the same $\\nu$ because both belong to the 3D Ising universality class.',
    realWorld: 'Wilson\'s RG earned the 1982 Nobel Prize and is now the foundation of effective field theory in particle physics.',
    hint: 'Universality means microscopically different systems behave identically near criticality.',
  },
  {
    id: 28022,
    topic: 'statistical-physics',
    difficulty: 'sota',
    question: 'The fluctuation-dissipation theorem (FDT) connects equilibrium fluctuations to linear response. For a system at temperature $T$, the spectral density of fluctuations $S(\\omega)$ relates to the dissipative response $\\chi\'\'(\\omega)$ by:',
    options: [
      '$S(\\omega) = \\frac{2k_BT}{\\omega} \\chi\'\'(\\omega)$ (classical limit)',
      '$S(\\omega) = \\chi\'\'(\\omega) / T$',
      '$S(\\omega) = \\omega \\chi\'\'(\\omega)$',
      '$S(\\omega) = k_BT \\cdot \\chi\'(\\omega)$',
    ],
    correctIndex: 0,
    explanation: 'The FDT states that spontaneous thermal fluctuations and the system\'s dissipative response to external perturbations are related by temperature. This is the Einstein relation generalized to all frequencies.',
    realWorld: 'Johnson-Nyquist noise in resistors, Brownian motion, and LIGO thermal noise budgets all rely on the FDT.',
    hint: 'Einstein\'s relation $D = k_BT/\\gamma$ is the zero-frequency case of the FDT.',
  },
  {
    id: 28023,
    topic: 'statistical-physics',
    difficulty: 'sota',
    question: 'The Jarzynski equality relates non-equilibrium work $W$ to equilibrium free energy differences $\\Delta F$:',
    options: [
      '$\\langle e^{-W/k_BT} \\rangle = e^{-\\Delta F/k_BT}$',
      '$\\langle W \\rangle = \\Delta F$',
      '$W_{\\min} = \\Delta F$',
      '$\\langle e^{W/k_BT} \\rangle = e^{\\Delta F/k_BT}$',
    ],
    correctIndex: 0,
    explanation: 'Jarzynski\'s equality (1997) is exact for arbitrarily far-from-equilibrium processes. It recovers the second law ($\\langle W \\rangle \\geq \\Delta F$) via Jensen\'s inequality.',
    realWorld: 'Used in single-molecule experiments (optical tweezers, AFM) to extract free energies from non-equilibrium pulling experiments on proteins and DNA.',
    hint: 'The exponential average of work equals the exponential of free energy — even far from equilibrium.',
  },
];
