import type { Question } from '../types';

export const nuclearPhysicsQuestions: Question[] = [
  {
    id: 41001, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'Einstein\'s $E = mc^2$ reveals that:',
    options: [
      'Only light has energy',
      'Energy equals mass times the speed of light (not squared)',
      'Mass and energy are interconvertible — a tiny amount of mass converts to enormous energy because $c^2$ is ~9×10¹⁶ m²/s²',
      'Mass cannot be converted to energy',
    ],
    correctIndex: 2,
    explanation: 'The speed of light squared is huge (~9×10¹⁶), so even tiny mass changes release enormous energy. In fission, ~0.1% of uranium\'s mass converts to energy; in fusion, ~0.7% of hydrogen\'s mass converts.',
    realWorld: 'Nuclear power plants convert ~1 kg of mass to energy per day, producing ~1 GW. The Sun converts 4.3 million tons of mass to energy every second.',
    hint: 'c² is a HUGE number — even a paperclip\'s mass contains the energy of an atomic bomb.',
  },
  {
    id: 41004, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'Radioactive half-life means:',
    options: [
      'Half the energy is released',
      'The time for all atoms to decay',
      'The sample loses half its mass to evaporation',
      'The time for exactly half of a radioactive sample to decay — after n half-lives, only $(1/2)^n$ of the original material remains',
    ],
    correctIndex: 3,
    explanation: 'Radioactive decay is exponential: $N(t) = N_0 \\cdot 2^{-t/t_{1/2}}$. Carbon-14 has t₁/₂ = 5,730 years; Uranium-238 has t₁/₂ = 4.5 billion years. Each individual atom\'s decay is random, but the aggregate behavior is precisely predictable.',
    realWorld: 'Carbon-14 dating uses this to age archaeological artifacts up to ~50,000 years old. Nuclear waste management requires understanding half-lives spanning milliseconds (nitrogen-16) to billions of years (uranium-238).',
    hint: 'Start with 1000 atoms. After one half-life: 500. After two: 250. After three: 125. The pattern is exponential.',
  },
  {
    id: 41002, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'Nuclear fusion is harder to achieve than fission because:',
    options: [
      'Fusion produces less energy than fission',
      'Positively charged nuclei repel via Coulomb force — overcoming this requires temperatures >100 million °C to give nuclei enough kinetic energy to fuse',
      'The required fuel (hydrogen) is extremely rare',
      'Fusion reactions cannot be sustained',
    ],
    correctIndex: 1,
    explanation: 'The Coulomb barrier requires nuclei to approach within ~1 fm. At >100 million K, the Maxwell-Boltzmann tail has enough fast particles to tunnel through. Confinement must maintain this plasma.',
    realWorld: 'NIF achieved ignition in 2022. ITER aims for Q=10 by the 2030s. Private companies target commercial fusion by 2030s using high-temperature superconducting magnets.',
    hint: 'Like charges repel — you need extreme heat to force positive nuclei close enough to fuse.',
  },
  {
    id: 41005, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'The strong nuclear force binds protons and neutrons in the nucleus despite:',
    options: [
      'Gravity holding the nucleus together',
      'Electrons screening the repulsion between protons',
      'Electromagnetic repulsion between protons — the strong force is ~100× stronger than EM but only acts over ~1 femtometer (10⁻¹⁵ m), creating the delicate balance that determines nuclear stability',
      'Protons being electrically neutral inside the nucleus',
    ],
    correctIndex: 2,
    explanation: 'The strong force (mediated by pions between nucleons, or gluons between quarks) creates an attractive potential that dominates at ~1 fm but drops to zero beyond ~2 fm. This short range is why heavy nuclei (>uranium) are unstable — distant protons repel but don\'t feel the strong force.',
    realWorld: 'The binding energy curve (peaking at iron-56) explains both fission (heavy elements) and fusion (light elements). Stars fuse elements up to iron; elements heavier than iron require supernovae.',
    hint: 'The strongest force in nature — but it only reaches across the width of a single proton.',
  },
  {
    id: 41003, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'The NIF achieved fusion ignition in December 2022 by:',
    options: [
      'Using magnetic confinement like a tokamak',
      'Focusing 192 laser beams delivering 2.05 MJ onto a deuterium-tritium pellet, producing 3.15 MJ of fusion energy — the first target-energy gain from laboratory fusion',
      'Achieving room-temperature fusion',
      'Fusing heavy elements like uranium',
    ],
    correctIndex: 1,
    explanation: 'Inertial confinement fusion compresses a DT capsule to ~1000× liquid density in nanoseconds. The resulting conditions trigger a thermonuclear burn wave. Net energy gain was ~54%.',
    realWorld: 'The 2022 result established target gain, not power-plant gain: the facility required far more electrical energy than the laser energy delivered to the target. NIF has since repeated ignition and increased target yield.',
    hint: 'Crush a tiny fuel pellet with lasers so fast and hard that it becomes a miniature star.',
    sources: [{ title: 'NIF’s Fusion Ignition Shot Hailed as Historic Scientific Feat', url: 'https://lasers.llnl.gov/news/nifs-fusion-ignition-shot-hailed-as-historic-scientific-feat', publisher: 'Lawrence Livermore National Laboratory', year: 2022 }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41006, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'High-temperature superconducting (HTS) magnets transform fusion reactor design because:',
    options: [
      'They eliminate the need for any magnetic confinement',
      'They only work at absolute zero temperature',
      'They are made from common household materials',
      'HTS tapes such as REBCO can sustain very high magnetic fields, enabling stronger confinement in more compact tokamak designs',
    ],
    correctIndex: 3,
    explanation: 'Tokamak performance depends strongly on magnetic field strength. REBCO high-temperature superconductors can sustain very high fields at fusion-relevant scale, allowing designers to pursue stronger confinement without making the device as large as lower-field alternatives.',
    realWorld: 'Commonwealth Fusion Systems and MIT demonstrated a 20-tesla large-bore HTS magnet in 2021 and use REBCO-based high-field magnets in the SPARC program; net-energy performance remains an experimental objective rather than an established reactor result.',
    hint: 'Stronger fields can improve confinement and enable a more compact high-performance tokamak design.',
    sources: [{ title: 'HTS magnets', url: 'https://www.cfs.energy/technology/hts-magnets/', publisher: 'Commonwealth Fusion Systems' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41007, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'Two atoms are isotopes of the same element when they have the same number of protons but different numbers of:',
    options: [
      'Neutrons in their nuclei',
      'Protons in their nuclei',
      'Chemical elements',
      'Units of nuclear charge',
    ],
    correctIndex: 0,
    explanation: 'An element is defined by its proton number. Isotopes share that proton number but differ in neutron number, so they have different mass numbers while remaining the same chemical element.',
    realWorld: 'Isotope ratios are used in radiometric dating, medical tracers, environmental forensics, and studies of nuclear reaction pathways.',
    hint: 'Changing this neutral nuclear particle changes mass number without changing atomic number.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41008, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'Why can both fusion of light nuclei and fission of very heavy nuclei release energy?',
    options: [
      'Both processes remove all electric charge from the products',
      'Both can move products toward greater binding energy per nucleon',
      'Both convert every neutron directly into a photon',
      'Both always produce nuclei heavier than iron',
    ],
    correctIndex: 1,
    explanation: 'The binding-energy-per-nucleon curve rises from very light nuclei toward the iron-nickel region and falls gradually for very heavy nuclei. Fusion and fission can therefore release energy when their products are more tightly bound than their initial nuclei.',
    realWorld: 'The binding-energy curve explains why stars extract energy by fusing light nuclei while reactors extract energy by splitting selected heavy nuclei.',
    hint: 'Compare the initial and final nuclei on the binding-energy-per-nucleon curve.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41009, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'What is a defining feature of chiral effective field theory in modern nuclear physics?',
    options: [
      'It organizes low-energy nuclear forces as a symmetry-constrained expansion',
      'It assumes all nuclear forces are exactly pairwise at every order',
      'It replaces nucleons with free quarks inside ordinary nuclei',
      'It treats the strong interaction as an electromagnetic correction',
    ],
    correctIndex: 0,
    explanation: 'Chiral effective field theory exploits the low-energy symmetries of QCD and a controlled expansion in ratios of low momenta or pion masses to a breakdown scale. Two- and many-nucleon interactions then enter systematically rather than being added without an organizing principle.',
    realWorld: 'Chiral EFT interactions are inputs to ab initio calculations of nuclei, reactions, and nuclear matter, with order-by-order structure that helps quantify theoretical uncertainty.',
    hint: 'The method is effective because it uses low-energy degrees of freedom, QCD symmetries, and an expansion with a finite validity range.',
    paper: { title: 'Nuclear effective field theory: Status and perspectives', url: 'https://doi.org/10.1103/RevModPhys.92.025004', venue: 'Reviews of Modern Physics', year: 2020 },
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
];
