import type { Question } from '../types';

export const nuclearPhysicsQuestions: Question[] = [
  {
    id: 41001, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'The mass-energy relation $E=mc^2$ implies that:',
    options: [
      'A change in rest mass corresponds to a change in energy',
      'Only photons can carry energy',
      'Mass is conserved separately from energy in every reaction',
      'The speed of light changes when nuclear binding changes',
    ],
    correctIndex: 0,
    explanation: 'Relativity relates rest mass and energy, so differences in nuclear binding energy appear as differences in the mass of the bound system.',
    realWorld: 'Mass defects and binding energies are central to fission, fusion, radioactive decay, nuclear masses, and reaction energetics.',
    hint: 'Nuclear reactions can convert a small mass difference into other forms of energy.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41004, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'A radioactive half-life is the time required for:',
    options: [
      'Every unstable nucleus in a sample to decay',
      'The expected number of undecayed nuclei to fall by half',
      'The sample temperature to fall by half',
      'Each nucleus to lose half of its mass',
    ],
    correctIndex: 1,
    explanation: 'For exponential radioactive decay, the expected number of undecayed nuclei and the activity both fall by a factor of two over each half-life.',
    realWorld: 'Half-lives guide radiometric dating, nuclear medicine, detector design, isotope production, and radioactive-waste planning.',
    hint: 'It describes a population-level exponential decay law.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41007, topic: 'nuclear-physics', difficulty: 'easy',
    question: 'Two isotopes of the same element have the same number of:',
    options: ['Neutrons', 'Nucleons', 'Protons', 'Nuclear excited states'],
    correctIndex: 2,
    explanation: 'An element is defined by proton number. Isotopes share that proton number but contain different numbers of neutrons.',
    realWorld: 'Isotopes enable medical imaging, radiotherapy, dating, tracing, nuclear-energy applications, and tests of nuclear structure.',
    hint: 'The atomic number does not change between isotopes of one element.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41002, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'Why does controlled fusion require demanding plasma conditions?',
    options: [
      'Fusion fuel is electrically neutral before ionization',
      'Fusion violates conservation of electric charge',
      'The strong interaction repels nuclei at all distances',
      'Positive nuclei must approach despite Coulomb repulsion',
    ],
    correctIndex: 3,
    explanation: 'Fusion reactions require positively charged nuclei to approach closely enough for the attractive nuclear interaction and quantum tunneling to overcome the Coulomb barrier.',
    realWorld: 'Fusion research therefore focuses on achieving sufficient temperature, density, confinement, and reaction time.',
    hint: 'Like electric charges repel before the nuclei become close enough to interact strongly.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41005, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'The residual strong interaction between nucleons is important because it:',
    options: [
      'Provides short-range attraction that helps bind nuclei',
      'Makes protons electrically neutral inside nuclei',
      'Acts with infinite range like gravity',
      'Prevents all radioactive decay processes',
    ],
    correctIndex: 0,
    explanation: 'Nuclear binding emerges from the strong interaction between quarks and gluons and its residual effects between nucleons, producing short-range nuclear forces that compete with proton-proton electromagnetic repulsion.',
    realWorld: 'This competition helps determine nuclear binding, shell structure, reaction thresholds, and which isotopes are stable.',
    hint: 'The relevant binding interaction is strong but short ranged.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41008, topic: 'nuclear-physics', difficulty: 'hard',
    question: 'The binding-energy-per-nucleon curve helps explain why energy can be released by:',
    options: [
      'Only splitting light nuclei',
      'Fusing light nuclei and splitting very heavy nuclei',
      'Fusing every nucleus regardless of mass',
      'Converting electrons directly into neutrons in any atom',
    ],
    correctIndex: 1,
    explanation: 'Nuclei near the iron-group region are among the most tightly bound per nucleon, so fusion of light nuclei and fission of very heavy nuclei can move products toward greater binding per nucleon.',
    realWorld: 'The curve gives a compact explanation for stellar fusion energetics and the energy available from heavy-nucleus fission.',
    hint: 'Both processes can move nuclei toward the strongly bound middle of the curve.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41003, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'In the December 2022 NIF ignition experiment, 3.15 MJ of fusion energy exceeded:',
    options: [
      'The total electrical energy used by the entire facility',
      'The chemical energy stored in the target chamber',
      'The 2.05 MJ of laser energy delivered to the target',
      'The annual energy consumption of the laser system',
    ],
    correctIndex: 2,
    explanation: 'DOE reported that 2.05 MJ of laser energy reached the target and produced 3.15 MJ of fusion energy, demonstrating target-level scientific breakeven rather than net electrical energy from the full facility.',
    realWorld: 'The result established fusion ignition in the laboratory while leaving major efficiency, repetition-rate, materials, and engineering challenges for practical energy systems.',
    hint: 'The comparison is target output versus laser energy delivered to the target, not wall-plug energy.',
    sources: [{
      title: 'DOE National Laboratory Makes History by Achieving Fusion Ignition',
      url: 'https://www.energy.gov/articles/doe-national-laboratory-makes-history-achieving-fusion-ignition',
      publisher: 'U.S. Department of Energy',
      year: 2022,
    }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41006, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'At the Facility for Rare Isotope Beams, short-lived rare isotopes can be produced primarily by:',
    options: [
      'Cooling ordinary atoms until they become radioactive',
      'Chemically separating isotopes from seawater only',
      'Using visible-light photons to add arbitrary neutrons',
      'Fragmentation or fission of fast primary ion beams',
    ],
    correctIndex: 3,
    explanation: 'DOE describes FRIB as producing rare isotopes through fragmentation or fission of energetic stable primary beams, followed by separation and delivery to experiments.',
    realWorld: 'These beams let researchers study nuclei far from stability, exotic decay, reactions relevant to astrophysics, and fundamental symmetries.',
    hint: 'A high-energy ion beam strikes a target and the resulting fragments are separated.',
    sources: [{
      title: 'The Facility for Rare Isotope Beams after One Year of Operation',
      url: 'https://www.energy.gov/science/np/articles/facility-rare-isotope-beams-after-one-year-operation',
      publisher: 'U.S. Department of Energy Office of Science',
      year: 2024,
    }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41009, topic: 'nuclear-physics', difficulty: 'sota',
    question: 'A major scientific reason to study very neutron-rich rare isotopes is to improve understanding of:',
    options: [
      'Nuclear structure and reactions involved in cosmic element synthesis',
      'Only the chemistry of stable noble gases',
      'Why all atomic nuclei contain equal proton and neutron counts',
      'How electron shells determine molecular bond angles',
    ],
    correctIndex: 0,
    explanation: 'Rare-isotope measurements probe how nuclear structure changes far from stability and constrain reactions and decay properties that enter models of how elements are synthesized in astrophysical environments.',
    realWorld: 'FRIB experiments connect laboratory nuclear measurements with models of stellar explosions, neutron-rich matter, and the origin of heavy elements.',
    hint: 'Exotic nuclei help connect nuclear structure to astrophysical nucleosynthesis.',
    sources: [{
      title: 'The Facility for Rare Isotope Beams after One Year of Operation',
      url: 'https://www.energy.gov/science/np/articles/facility-rare-isotope-beams-after-one-year-operation',
      publisher: 'U.S. Department of Energy Office of Science',
      year: 2024,
    }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
];
