import type { Question } from '../types';

export const nuclearPhysicsQuestions: Question[] = [
  {
    id: 41001,
    topic: 'nuclear-physics',
    difficulty: 'easy',
    question: 'If a nuclear reaction has mass defect $\\Delta m$, the corresponding released energy is:',
    options: [
      '$E = \\Delta m c^2$',
      '$E = \\Delta m / c^2$',
      '$E = c^2 / \\Delta m$',
      '$E = \\Delta m c$',
    ],
    correctIndex: 0,
    explanation: 'Mass-energy equivalence gives $E=\\Delta m c^2$. In nuclear reactions, a small decrease in rest mass can therefore correspond to a large released energy because $c^2$ is large.',
    realWorld: 'Mass defects determine reaction Q-values, nuclear binding energies, and the energy released by fission and fusion.',
    hint: 'Use Einstein\'s mass-energy relation with the change in rest mass.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41004,
    topic: 'nuclear-physics',
    difficulty: 'easy',
    question: 'A radioactive isotope has a half-life of 10 days. What fraction remains after 30 days?',
    options: [
      '$1/4$ of the original sample',
      '$1/8$ of the original sample',
      '$1/16$ of the original sample',
      '$3/10$ of the original sample',
    ],
    correctIndex: 1,
    explanation: 'Thirty days is three half-lives, so the remaining fraction is $(1/2)^3 = 1/8$. Radioactive decay follows an exponential law for a large ensemble of nuclei.',
    realWorld: 'Half-life calculations are used in radiometric dating, medical isotope planning, reactor operations, and radioactive-waste management.',
    hint: 'Count how many 10-day half-lives fit into 30 days.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41007,
    topic: 'nuclear-physics',
    difficulty: 'easy',
    question: 'For an isotope written as $^{A}_{Z}X$, the number of neutrons is:',
    options: [
      '$A + Z$',
      '$Z - A$',
      '$A - Z$',
      '$A \\times Z$',
    ],
    correctIndex: 2,
    explanation: 'The mass number $A$ counts protons plus neutrons, while the atomic number $Z$ counts protons. Therefore the neutron number is $N=A-Z$.',
    realWorld: 'Tracking proton and neutron counts is fundamental when identifying isotopes, decay chains, and nuclei far from stability.',
    hint: 'Mass number equals protons plus neutrons.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41008,
    topic: 'nuclear-physics',
    difficulty: 'easy',
    question: 'In beta-minus decay, what happens inside the nucleus?',
    options: [
      'A proton becomes a neutron and emits a positron',
      'Two protons fuse into a deuteron and photon',
      'A neutron leaves the nucleus without changing charge',
      'A neutron becomes a proton while an electron and antineutrino are emitted',
    ],
    correctIndex: 3,
    explanation: 'In beta-minus decay, a neutron transforms into a proton through the weak interaction, emitting an electron and an electron antineutrino.',
    realWorld: 'Beta decay changes one element into another and is central to radioactive decay chains, reactor products, and nuclear astrophysics.',
    hint: 'Beta-minus decay increases the atomic number by one while keeping the mass number unchanged.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41009,
    topic: 'nuclear-physics',
    difficulty: 'easy',
    question: 'What changes when an excited nucleus emits a gamma ray?',
    options: [
      'Its energy decreases while its proton and neutron counts remain unchanged',
      'Its atomic number decreases by one while mass number stays fixed',
      'Its neutron number decreases by one while charge remains fixed',
      'Its mass number decreases by four and atomic number by two',
    ],
    correctIndex: 0,
    explanation: 'Gamma emission is an electromagnetic transition between nuclear energy levels. It lowers the excitation energy but does not change the nucleus\'s proton number or neutron number.',
    realWorld: 'Gamma spectroscopy identifies nuclear energy levels and isotopes in research, medicine, security, and materials analysis.',
    hint: 'A gamma ray carries away energy, not a proton or neutron.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41002,
    topic: 'nuclear-physics',
    difficulty: 'hard',
    question: 'Why must light nuclei in a fusion plasma have very high kinetic energies?',
    options: [
      'They must overcome the strong force before entering its attractive range',
      'They must approach closely enough for tunneling through the Coulomb barrier to become likely',
      'They must ionize neutrons before a fusion reaction can conserve charge',
      'They must suppress gamma emission so the fused nucleus remains stable',
    ],
    correctIndex: 1,
    explanation: 'Positively charged nuclei repel through the Coulomb interaction. High temperatures increase collision energies, while quantum tunneling allows some nuclei to penetrate the barrier and reach distances where the strong interaction can bind them.',
    realWorld: 'Fusion experiments optimize temperature, density, and confinement time to create enough successful fusion reactions for useful energy gain.',
    hint: 'Like charges repel, but quantum mechanics lets some close encounters penetrate the barrier.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41005,
    topic: 'nuclear-physics',
    difficulty: 'hard',
    question: 'Why can both fission of very heavy nuclei and fusion of very light nuclei release energy?',
    options: [
      'Both processes always convert protons directly into photons',
      'Both processes move nuclei toward larger electric charge',
      'Both can move products toward greater binding energy per nucleon',
      'Both require the final nuclei to contain fewer total nucleons',
    ],
    correctIndex: 2,
    explanation: 'Binding energy per nucleon rises from very light nuclei toward the iron-nickel region and falls for very heavy nuclei. Fusion of light nuclei and fission of heavy nuclei can therefore produce more tightly bound products and release the difference as energy.',
    realWorld: 'The binding-energy curve explains why stars gain energy from fusion and why reactors can gain energy from fission.',
    hint: 'Compare how tightly bound the initial and final nuclei are per nucleon.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41010,
    topic: 'nuclear-physics',
    difficulty: 'hard',
    question: 'For a nuclear reaction, the Q-value is positive when:',
    options: [
      'The final rest mass exceeds the initial rest mass',
      'The reaction changes the total electric charge',
      'The products contain fewer particles than the reactants',
      'The initial rest mass exceeds the final rest mass',
    ],
    correctIndex: 3,
    explanation: 'The reaction Q-value is $Q=(m_{\\text{initial}}-m_{\\text{final}})c^2$. A positive Q means rest-mass energy has been converted into kinetic energy, radiation, or excitation energy.',
    realWorld: 'Q-values determine whether nuclear reactions are exothermic and help predict reaction thresholds and product energies.',
    hint: 'A positive energy release corresponds to a decrease in total rest mass.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41011,
    topic: 'nuclear-physics',
    difficulty: 'hard',
    question: 'What is the main significance of nuclear magic numbers such as 2, 8, 20, 28, 50, 82, and 126?',
    options: [
      'They correspond to filled proton or neutron shells that often give extra nuclear stability',
      'They mark nuclei whose protons and neutrons must always be equal in number',
      'They are the only nucleon counts for which beta decay is forbidden',
      'They identify nuclei whose binding energy per nucleon is exactly constant',
    ],
    correctIndex: 0,
    explanation: 'The nuclear shell model predicts enhanced stability when proton or neutron energy shells are filled. These closed-shell configurations produce the observed magic numbers.',
    realWorld: 'Shell closures guide the study of nuclear structure, rare isotopes, superheavy nuclei, and the changing limits of stability.',
    hint: 'Think of shell filling in atoms, but applied separately to protons and neutrons.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41012,
    topic: 'nuclear-physics',
    difficulty: 'hard',
    question: 'A nuclear reaction cross section most directly represents:',
    options: [
      'The geometric diameter of the target nucleus measured in meters',
      'An effective interaction probability expressed as an area, commonly in barns',
      'The energy released per reaction expressed in electron-volts',
      'The number of neutrons that remain after a reaction finishes',
    ],
    correctIndex: 1,
    explanation: 'A reaction cross section is an effective area that quantifies how likely a specified interaction is for an incident particle and target under given conditions. One barn is $10^{-28}$ m².',
    realWorld: 'Cross sections are essential for reactor calculations, radiation transport, isotope production, detector design, and nuclear astrophysics.',
    hint: 'It behaves like an effective target area for a particular interaction.',
    reviewedAt: '2026-09-21',
  },
  {
    id: 41003,
    topic: 'nuclear-physics',
    difficulty: 'sota',
    question: 'At the National Ignition Facility, fusion ignition is defined by which energy comparison?',
    options: [
      'Fusion yield exceeds the total electrical energy drawn from the power grid',
      'Fusion yield exceeds the kinetic energy of the entire target chamber',
      'Fusion yield exceeds the laser energy delivered to the fusion target',
      'Fusion yield exceeds the rest-mass energy of the deuterium-tritium fuel',
    ],
    correctIndex: 2,
    explanation: 'NIF defines ignition by producing more fusion energy than the laser energy delivered to the target. This is a target-level energy gain criterion, not a claim of net electrical power from the full facility.',
    realWorld: 'NIF first achieved this ignition criterion on December 5, 2022 and has since repeated ignition shots, enabling experiments in high-energy-density and fusion science.',
    hint: 'The comparison is made at the target, not at the facility wall plug.',
    sources: [{ title: 'Achieving Fusion Ignition', url: 'https://lasers.llnl.gov/science/achieving-fusion-ignition', publisher: 'Lawrence Livermore National Laboratory' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41006,
    topic: 'nuclear-physics',
    difficulty: 'sota',
    question: 'What capability makes the Facility for Rare Isotope Beams especially valuable for nuclear-structure research?',
    options: [
      'It stores macroscopic samples of every radioactive isotope for decades',
      'It collides only electrons and positrons at the highest available energies',
      'It measures nuclei without producing or accelerating any ion beams',
      'It produces intense rare-isotope beams for studying short-lived nuclei far from stability',
    ],
    correctIndex: 3,
    explanation: 'FRIB uses a high-power superconducting linear accelerator and advanced separation systems to produce rare isotopes that can be studied as fast, stopped, or reaccelerated beams.',
    realWorld: 'These beams let researchers probe how nuclear structure changes for nuclei with unusual proton-to-neutron ratios and help constrain models of nuclear reactions and astrophysical processes.',
    hint: 'Its name points directly to the unusual nuclei it is designed to produce.',
    sources: [{ title: 'About FRIB', url: 'https://frib.msu.edu/about', publisher: 'Facility for Rare Isotope Beams' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41013,
    topic: 'nuclear-physics',
    difficulty: 'sota',
    question: 'A central goal of the future Electron-Ion Collider is to:',
    options: [
      'Map how quarks and gluons are distributed inside protons, neutrons, and nuclei',
      'Measure chemical bond lengths in neutral molecules with visible light',
      'Produce bulk samples of stable isotopes for medical imaging',
      'Replace rare-isotope facilities with low-energy neutron sources',
    ],
    correctIndex: 0,
    explanation: 'The Electron-Ion Collider will scatter electrons from protons and nuclei to create high-resolution information about their quark and gluon structure and the strong interaction described by quantum chromodynamics.',
    realWorld: 'EIC measurements are intended to clarify how quarks and gluons generate properties such as nucleon structure, spin, and the internal dynamics of nuclear matter.',
    hint: 'The collider acts like a high-resolution probe of the strong-force constituents inside visible matter.',
    sources: [{ title: 'DOE Explains...Quantum Chromodynamics', url: 'https://www.energy.gov/science/doe-explainsquantum-chromodynamics', publisher: 'U.S. Department of Energy' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41014,
    topic: 'nuclear-physics',
    difficulty: 'sota',
    question: 'What is the central accelerator goal of the proposed FRIB400 upgrade?',
    options: [
      'Reduce all rare-isotope beam energies below 40 MeV per nucleon',
      'Raise the facility toward 400 MeV per nucleon for uranium and increase access to key rare isotopes',
      'Replace heavy-ion acceleration with an electron-positron storage ring',
      'Convert the facility into a thermal-neutron reactor for isotope production',
    ],
    correctIndex: 1,
    explanation: 'FRIB400 is designed to extend the FRIB linear accelerator to 400 MeV per nucleon for uranium, with higher energies for lighter ions, expanding rare-isotope reach and substantially increasing yields for many important isotopes.',
    realWorld: 'Higher beam energy and isotope yield would open additional experiments on nuclear structure, reactions, and nuclear astrophysics.',
    hint: 'The upgrade name refers to a target beam energy scale.',
    sources: [{ title: 'Research Areas & Capabilities — FRIB400', url: 'https://frib.msu.edu/research-areas-and-capabilities', publisher: 'Facility for Rare Isotope Beams' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
  {
    id: 41015,
    topic: 'nuclear-physics',
    difficulty: 'sota',
    question: 'Why are measurements of very neutron-rich rare isotopes important for nuclear astrophysics?',
    options: [
      'They determine the orbital periods of planets around neutron stars',
      'They directly measure the dark-matter density inside ordinary stars',
      'Their masses, decays, and reactions help model how heavy elements form in extreme cosmic events',
      'They remove the need for astronomical observations of element abundances',
    ],
    correctIndex: 2,
    explanation: 'Many heavy-element nucleosynthesis pathways involve short-lived neutron-rich nuclei. Measurements of their masses, decay properties, and reactions improve models of element production in environments such as neutron-star mergers and stellar explosions.',
    realWorld: 'Rare-isotope data connect laboratory nuclear physics with observed cosmic element abundances and the physics of neutron-rich astrophysical environments.',
    hint: 'Think about the short-lived nuclei that lie along pathways for building heavy elements.',
    sources: [{ title: 'Nuclear Astrophysics', url: 'https://frib.msu.edu/research-areas-and-capabilities/research-areas/nuclear-astrophysics', publisher: 'Facility for Rare Isotope Beams' }],
    reviewedAt: '2026-09-21',
    factualAsOf: '2026-09-21',
  },
];
