import type { Question } from '../types';

export const qftEasyQuestions: Question[] = [
  {
    id: 28401,
    topic: 'quantum-field-theory',
    difficulty: 'easy',
    question: 'In quantum field theory, particles are understood as:',
    options: [
      'Quantized excitations of underlying fields pervading all of spacetime',
      'Tiny billiard balls with definite positions',
      'Waves in a classical medium',
      'Mathematical abstractions with no physical content',
    ],
    correctIndex: 0,
    explanation: 'QFT replaces the particle concept with fields. An electron is a quantum of the Dirac field, a photon is a quantum of the electromagnetic field. Creation and annihilation operators add/remove quanta.',
    realWorld: 'QFT is the framework of the Standard Model — every particle physics experiment at CERN validates it.',
    hint: 'The field is fundamental; the particle is an excitation of that field.',
  },
  {
    id: 28402,
    topic: 'quantum-field-theory',
    difficulty: 'easy',
    question: 'Feynman diagrams represent:',
    options: [
      'Terms in a perturbative expansion of scattering amplitudes',
      'Actual particle trajectories in spacetime',
      'Classical force fields',
      'Wavefunction shapes',
    ],
    correctIndex: 0,
    explanation: 'Each Feynman diagram corresponds to a term in the Dyson series. Internal lines represent virtual particles (propagators), vertices represent interactions, and external lines represent real particles.',
    realWorld: 'The anomalous magnetic moment of the electron has been computed to $\\sim 12,000$ Feynman diagrams, matching experiment to 12 decimal places.',
    hint: 'They are visual bookkeeping for integrals — each line and vertex has precise mathematical rules.',
  },
  {
    id: 28403,
    topic: 'quantum-field-theory',
    difficulty: 'easy',
    question: 'The Dirac equation predicts the existence of:',
    options: [
      'Antimatter — every fermion has an antiparticle with opposite charge',
      'Photons',
      'Gravitons',
      'Dark matter',
    ],
    correctIndex: 0,
    explanation: 'Dirac\'s equation for the electron ($i\\gamma^\\mu \\partial_\\mu \\psi - m\\psi = 0$) has negative-energy solutions, which Dirac reinterpreted as positrons — antimatter, confirmed by Anderson in 1932.',
    realWorld: 'PET scanners detect positron-electron annihilation photons — antimatter used in hospitals every day.',
    hint: 'Dirac combined quantum mechanics with special relativity and got more particles than he expected.',
  },
];

export const qftHardQuestions: Question[] = [
  {
    id: 28411,
    topic: 'quantum-field-theory',
    difficulty: 'hard',
    question: 'Renormalization in QFT is necessary because:',
    options: [
      'Naive loop integrals diverge, requiring systematic absorption of infinities into redefined physical parameters',
      'Perturbation theory converges too slowly',
      'Classical fields have infinite energy',
      'Particles have infinite mass',
    ],
    correctIndex: 0,
    explanation: 'Loop corrections in Feynman diagrams produce UV-divergent integrals. Renormalization systematically redefines mass, charge, and field strength to absorb these divergences, yielding finite, testable predictions.',
    realWorld: 'QED predictions of $g-2$ for the electron agree with experiment to $10^{-12}$ — the most precise prediction in physics.',
    hint: 'The "bare" parameters are infinite, but physical (measured) parameters are finite after renormalization.',
  },
  {
    id: 28412,
    topic: 'quantum-field-theory',
    difficulty: 'hard',
    question: 'The Higgs mechanism gives mass to gauge bosons through:',
    options: [
      'Spontaneous breaking of a gauge symmetry by a scalar field acquiring a nonzero vacuum expectation value',
      'Explicit mass terms added to the Lagrangian',
      'Gravitational effects on massless particles',
      'Quantum loop corrections only',
    ],
    correctIndex: 0,
    explanation: 'The Higgs field $\\phi$ has a Mexican hat potential. At its minimum, $\\langle \\phi \\rangle \\neq 0$ breaks the gauge symmetry. The would-be Goldstone bosons are "eaten" by gauge bosons, which acquire mass.',
    realWorld: 'The Higgs boson was discovered at the LHC in 2012, earning Englert and Higgs the 2013 Nobel Prize.',
    hint: 'The symmetry is broken by the ground state, not the Lagrangian — "spontaneous" symmetry breaking.',
  },
  {
    id: 28413,
    topic: 'quantum-field-theory',
    difficulty: 'hard',
    question: 'Asymptotic freedom in QCD means that the strong coupling constant $\\alpha_s$:',
    options: [
      'Decreases at higher energies (shorter distances), making quarks quasi-free',
      'Increases at higher energies',
      'Remains constant at all scales',
      'Oscillates between strong and weak coupling',
    ],
    correctIndex: 0,
    explanation: 'The beta function of QCD is negative: $\\beta(g) < 0$ for $N_f < 33/2$. At high energies, quarks interact weakly (perturbative QCD). At low energies, the coupling grows → confinement.',
    realWorld: 'Gross, Politzer, and Wilczek received the 2004 Nobel Prize. Asymptotic freedom explains deep inelastic scattering and jet physics at CERN.',
    hint: 'The opposite of QED — the strong force gets weaker when you zoom in.',
  },
];

export const qftSotaQuestions: Question[] = [
  {
    id: 28421,
    topic: 'quantum-field-theory',
    difficulty: 'sota',
    question: 'The conformal bootstrap program in CFT constrains operator dimensions and OPE coefficients by demanding:',
    options: [
      'Crossing symmetry of four-point functions combined with unitarity bounds',
      'Lorentz invariance only',
      'Perturbative convergence',
      'Supersymmetry',
    ],
    correctIndex: 0,
    explanation: 'The bootstrap uses crossing symmetry ($s$-channel = $t$-channel) plus unitarity to carve out the space of consistent CFTs. It determined the 3D Ising critical exponents to record precision without Feynman diagrams.',
    realWorld: 'The conformal bootstrap solved the 3D Ising critical exponents more precisely than any Monte Carlo simulation — a triumph of pure mathematical consistency.',
    hint: 'No Lagrangian needed — consistency alone determines the theory.',
  },
  {
    id: 28422,
    topic: 'quantum-field-theory',
    difficulty: 'sota',
    question: 'The amplituhedron, proposed by Arkani-Hamed and Trnka, reformulates scattering amplitudes as:',
    options: [
      'Volumes of a geometric object in a generalized "kinematic space," bypassing Feynman diagrams entirely',
      'Eigenvalues of a random matrix',
      'Fourier transforms of wavefunctions',
      'Products of Wilson loops',
    ],
    correctIndex: 0,
    explanation: 'The amplituhedron encodes tree-level and loop-level scattering amplitudes in $\\mathcal{N}=4$ SYM as the "volume" of a positive Grassmannian geometry. Locality and unitarity emerge rather than being assumed.',
    realWorld: 'This hints that spacetime itself may not be fundamental — it could emerge from more primitive geometric structures.',
    hint: 'Feynman diagrams enforce locality and unitarity. The amplituhedron derives them from geometry.',
  },
  {
    id: 28423,
    topic: 'quantum-field-theory',
    difficulty: 'sota',
    question: 'Lattice QCD computes hadronic quantities from first principles by:',
    options: [
      'Discretizing spacetime on a Euclidean lattice and evaluating the path integral via Monte Carlo importance sampling',
      'Solving the Dirac equation analytically',
      'Using perturbation theory in $\\alpha_s$',
      'Employing dimensional regularization on a continuum',
    ],
    correctIndex: 0,
    explanation: 'Lattice QCD replaces continuous spacetime with a grid, making the path integral finite-dimensional. Monte Carlo methods sample gauge field configurations weighted by $e^{-S_E}$, enabling non-perturbative predictions.',
    realWorld: 'Lattice QCD predicted the proton mass to 2% accuracy and computes CKM matrix elements critical for CP violation studies at the LHC.',
    hint: 'It is the only known method to solve QCD at low energies where $\\alpha_s \\sim 1$.',
  },
];
