import type { Question } from '../types';

export const neuroscienceQuestions: Question[] = [
  {
    id: 40501, topic: "neuroscience", difficulty: "easy",
    question: "At a typical chemical synapse, an arriving presynaptic action potential communicates with the next cell primarily by:",
    options: ["Sending electromagnetic radio waves","Transferring DNA across the synaptic cleft","Triggering neurotransmitter release that binds postsynaptic receptors","Making the two neurons permanently fuse"],
    correctIndex: 2,
    explanation: "Presynaptic depolarization opens voltage-gated calcium channels, promoting vesicle fusion and neurotransmitter release into the synaptic cleft.",
    realWorld: "Synaptic transmission is the target of many neurological and psychiatric drugs, toxins, and experimental tools.",
    hint: "The electrical event is converted briefly into a chemical signal between the two cells.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40504, topic: "neuroscience", difficulty: "easy",
    question: "Why can an action potential propagate along an axon without progressively shrinking?",
    options: ["Local depolarization opens voltage-gated ion channels in the next membrane segment, regenerating the signal","Electrons move through the axon exactly like current in a metal wire","Every point on the axon is forced to depolarize simultaneously","Neurotransmitter vesicles physically travel down the axon to regenerate voltage"],
    correctIndex: 0,
    explanation: "An action potential is regenerated as local current brings adjacent membrane to threshold and opens voltage-gated channels; myelin speeds propagation by concentrating regeneration at nodes.",
    realWorld: "The same channel dynamics explain why local anesthetics and many neurological disorders can alter impulse conduction.",
    hint: "The key is active regeneration by membrane channels rather than passive decay alone.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40502, topic: "neuroscience", difficulty: "hard",
    question: "A simple Hebbian learning rule strengthens a synapse most directly when:",
    options: ["Pre- and postsynaptic activity are correlated in time","Only the presynaptic neuron is permanently silent","The synapse is inhibitory by definition","Learning occurs during sleep and never while awake"],
    correctIndex: 0,
    explanation: "Hebbian plasticity captures the idea that correlated activity can strengthen effective connectivity, although real synaptic plasticity depends on timing, receptors, neuromodulators, and circuit state.",
    realWorld: "Hebbian principles influenced experimental studies of long-term potentiation and computational learning rules.",
    hint: "Focus on correlation between activity on the two sides of a synapse.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40505, topic: "neuroscience", difficulty: "hard",
    question: "The default mode network is best characterized as a distributed set of brain regions that often:",
    options: ["Controls all voluntary movement","Activates only during deep sleep","Functions as a single anatomical nucleus","Shows relatively high activity during internally oriented thought and often decreases activity during externally demanding tasks"],
    correctIndex: 3,
    explanation: "The default mode network includes interacting cortical regions whose activity is commonly associated with internally directed cognition, autobiographical processing, and rest-relative task contrasts.",
    realWorld: "Resting-state network measurements are widely used in systems-neuroscience research, but they are not by themselves a stand-alone diagnostic test for psychiatric disease.",
    hint: "The word default refers to a reproducible network pattern seen when attention is not dominated by an external task.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40503, topic: "neuroscience", difficulty: "sota",
    question: "What made the 2024 adult Drosophila FlyWire resource a major connectomics milestone?",
    options: ["It mapped every synapse in the human cortex","It reconstructed a whole adult fly brain with roughly 139,000 neurons and more than 50 million chemical synapses","It showed that synaptic connectivity is identical across all flies","It replaced electron microscopy with ordinary MRI"],
    correctIndex: 1,
    explanation: "The FlyWire consortium produced a synapse-resolution wiring diagram of an entire adult female fruit-fly brain containing 139,255 neurons and about 54.5 million synapses.",
    realWorld: "The resource enables brain-wide circuit analysis and computational models that link complete wiring structure to hypotheses about information flow and behavior.",
    hint: "The milestone is the scale and completeness of a whole adult animal brain reconstructed at synaptic resolution.",
    paper: {"title":"Neuronal wiring diagram of an adult brain","url":"https://www.nature.com/articles/s41586-024-07558-y","venue":"Nature","year":2024},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 40506, topic: "neuroscience", difficulty: "sota",
    question: "In high-performance speech brain-computer interfaces, neural population activity is decoded primarily to:",
    options: ["Estimate blood glucose without sensors","Replace every peripheral nerve with an electrode","Translate attempted speech-related neural activity into text or synthesized communication","Read arbitrary private thoughts with perfect accuracy"],
    correctIndex: 2,
    explanation: "Modern speech BCIs combine implanted neural recordings with statistical or neural-network decoders trained on attempted speech, producing text or other communication outputs with imperfect but increasingly useful accuracy.",
    realWorld: "Research systems have demonstrated substantially faster communication than earlier cursor-based BCIs for some participants with severe paralysis.",
    hint: "The decoder learns a mapping from recorded cortical activity to attempted speech units or language outputs.",
    paper: {"title":"A high-performance speech neuroprosthesis","url":"https://www.nature.com/articles/s41586-023-06377-x","venue":"Nature","year":2023},
    reviewedAt: "2026-09-19",
    factualAsOf: "2026-09-19",
  },
  {
    id: 40507, topic: "neuroscience", difficulty: "easy",
    question: "In the central nervous system, myelin around many axons is produced by:",
    options: ["Astrocytes only","Microglia only","Schwann cells","Oligodendrocytes"],
    correctIndex: 3,
    explanation: "Oligodendrocytes form myelin around axons in the central nervous system, whereas Schwann cells perform the analogous role in the peripheral nervous system.",
    realWorld: "Myelin enables rapid saltatory conduction and is disrupted in demyelinating disorders of the central nervous system.",
    hint: "Distinguish the CNS glial cell from the PNS myelinating cell.",
    reviewedAt: "2026-09-19",
  },
  {
    id: 40508, topic: "neuroscience", difficulty: "sota",
    question: "What is a key advantage of high-density Neuropixels probes in systems neuroscience?",
    options: ["They measure only average scalp voltage","They can record action-potential activity from many individual neurons across multiple nearby brain regions with one slender probe","They infer neural activity solely from gene expression","They eliminate the need for any signal processing"],
    correctIndex: 1,
    explanation: "Neuropixels probes integrate many closely spaced recording sites on a thin shank, enabling large-scale extracellular recordings with single-neuron resolution across extended brain trajectories.",
    realWorld: "Dense neural recordings help researchers study population dynamics and interactions across circuits rather than sampling only a few neurons at a time.",
    hint: "The defining gain is many simultaneous electrophysiological channels along a compact probe.",
    paper: {"title":"Large-scale neural recordings with single neuron resolution using Neuropixels probes in human cortex","url":"https://www.nature.com/articles/s41593-021-00997-0","venue":"Nature Neuroscience","year":2022},
    reviewedAt: "2026-09-19",
  },
];
