import type { Question } from '../types';

export const neuroscienceQuestions: Question[] = [
  {
    id: 40501, topic: 'neuroscience', difficulty: 'easy',
    question: 'Neurons communicate across synapses by:',
    options: [
      'Releasing neurotransmitters that bind to receptors on the postsynaptic neuron, triggering ion channel opening and electrical signal propagation',
      'Direct electrical contact between all neurons',
      'Sending radio waves through the brain',
      'Sharing DNA between connected neurons',
    ],
    correctIndex: 0,
    explanation: 'Chemical synapses dominate: an action potential triggers vesicle fusion, releasing neurotransmitters (glutamate, GABA, dopamine) into the synaptic cleft.',
    realWorld: 'Understanding synaptic transmission led to SSRIs (antidepressants), L-DOPA (Parkinson\'s), and inspired artificial neural networks.',
    hint: 'Chemical messengers cross the tiny gap between neurons.',
  },
  {
    id: 40504, topic: 'neuroscience', difficulty: 'easy',
    question: 'An action potential propagates along an axon because:',
    options: [
      'Voltage-gated sodium channels open in sequence — depolarization at one point triggers the next segment, creating a self-propagating electrical wave at ~100 m/s',
      'Electrons flow through the neuron like a wire',
      'The entire neuron depolarizes simultaneously',
      'Neurotransmitters travel along the axon interior',
    ],
    correctIndex: 0,
    explanation: 'Action potentials are all-or-nothing: once threshold (~-55mV) is reached, Na⁺ channels open → rapid depolarization → K⁺ channels open → repolarization. Myelin sheaths speed conduction via saltatory propagation (jumping between nodes of Ranvier).',
    realWorld: 'Multiple sclerosis destroys myelin, slowing nerve signals. Understanding action potentials led to local anesthetics (lidocaine blocks Na⁺ channels) and treatments for epilepsy and cardiac arrhythmias.',
    hint: 'Sodium in, potassium out — a wave of charge that cascades down the nerve fiber.',
  },
  {
    id: 40502, topic: 'neuroscience', difficulty: 'hard',
    question: 'Hebbian learning ("neurons that fire together wire together") formalizes as:',
    options: [
      '$\\Delta w_{ij} = \\eta \\cdot x_i \\cdot x_j$ — the synaptic weight increases when pre- and post-synaptic neurons are simultaneously active',
      'Neurons randomly strengthen and weaken connections',
      'Only inhibitory connections are strengthened',
      'Learning only occurs during sleep',
    ],
    correctIndex: 0,
    explanation: 'Hebb (1949) proposed that correlated neural activity strengthens connections. This was later confirmed biologically as Long-Term Potentiation (LTP).',
    realWorld: 'LTP is the biological basis of memory formation. Disruption of LTP is implicated in Alzheimer\'s disease. Hebbian rules also underpin unsupervised ML algorithms.',
    hint: 'If two neurons activate at the same time, the connection between them gets stronger.',
  },
  {
    id: 40505, topic: 'neuroscience', difficulty: 'hard',
    question: 'The default mode network (DMN) is significant because:',
    options: [
      'It activates during rest and mind-wandering but deactivates during focused tasks — suggesting the brain has a structured "idle" state for self-reflection and planning',
      'It is the network responsible for all motor control',
      'It only activates during deep sleep',
      'It is a single brain region, not a network',
    ],
    correctIndex: 0,
    explanation: 'The DMN (medial prefrontal cortex, posterior cingulate, angular gyrus) was discovered by Raichle (2001) when brain areas showed MORE activity during rest than tasks. It\'s linked to self-referential thought, memory consolidation, and future planning.',
    realWorld: 'Altered DMN connectivity is found in depression, ADHD, Alzheimer\'s, and autism. Understanding the DMN has transformed psychiatric diagnosis and inspired "resting-state" fMRI as a clinical tool.',
    hint: 'Your brain is never truly idle — there\'s a specific network for daydreaming and self-reflection.',
  },
  {
    id: 40503, topic: 'neuroscience', difficulty: 'sota',
    question: 'Connectomics — mapping complete neural wiring diagrams — recently achieved:',
    options: [
      'A complete synapse-resolution connectome of the adult Drosophila brain with ~140,000 neurons and 50 million synapses, using electron microscopy and AI segmentation',
      'Mapping every neuron in the human brain at single-synapse resolution',
      'Proving that brains don\'t use electrical signals',
      'Showing all brains have identical wiring',
    ],
    correctIndex: 0,
    explanation: 'The FlyWire project (2024) completed the first whole-brain connectome of an adult animal with complex behavior. AI (flood-filling networks) automated 99% of the neuron tracing from petabytes of EM imagery.',
    realWorld: 'Connectomics reveals circuit motifs that may inspire new neural network architectures. The fly brain\'s navigation circuits are already informing robotics research and neuromorphic chip design.',
    hint: 'A complete wiring diagram of an insect brain — every neuron, every connection.',
  },
  {
    id: 40506, topic: 'neuroscience', difficulty: 'sota',
    question: 'Brain-computer interfaces (BCIs) like Neuralink achieve neural decoding by:',
    options: [
      'Recording from thousands of neurons simultaneously with implanted electrode arrays, then using neural network decoders to translate firing patterns into movement intentions or text',
      'Reading thoughts using external EEG caps with perfect accuracy',
      'Connecting brains directly to the internet',
      'Stimulating muscles directly without any neural recording',
    ],
    correctIndex: 0,
    explanation: 'Intracortical BCIs (Utah arrays, Neuralink\'s N1) record single-unit activity from motor cortex. Recurrent neural network decoders map neural population dynamics to cursor movement or text at ~90 characters/minute (BrainGate, 2024).',
    realWorld: 'A paralyzed man typed at 90 chars/min using a BCI in 2024 — faster than most smartphone users. BCIs are restoring communication to people with ALS and spinal cord injuries.',
    hint: 'Record brain signals → decode what the person intends → translate to computer commands.',
  },
];
