import type { Question } from '../types';

export const plasmaPhysicsEasyQuestions: Question[] = [
  {
    id: 28101,
    topic: 'plasma-physics',
    difficulty: 'easy',
    question: 'A plasma is often called the "fourth state of matter." What distinguishes it from a gas?',
    options: [
      'It consists of ionized particles that exhibit collective electromagnetic behavior',
      'It is always hotter than any gas',
      'It only exists in stars',
      'It has no pressure',
    ],
    correctIndex: 0,
    explanation: 'A plasma contains free ions and electrons whose long-range Coulomb interactions produce collective phenomena (waves, instabilities) absent in neutral gases.',
    realWorld: 'Over 99% of visible matter in the universe is plasma — stars, nebulae, the solar wind, and lightning.',
    hint: 'The key word is "collective" — particles interact via electromagnetic fields, not just collisions.',
  },
  {
    id: 28102,
    topic: 'plasma-physics',
    difficulty: 'easy',
    question: 'The Debye length $\\lambda_D$ in a plasma characterizes:',
    options: [
      'The distance over which electric fields are screened by mobile charges',
      'The mean free path of ions',
      'The wavelength of plasma oscillations',
      'The radius of a fusion reactor',
    ],
    correctIndex: 0,
    explanation: '$\\lambda_D = \\sqrt{\\varepsilon_0 k_BT_e / n_e e^2}$. Beyond $\\lambda_D$, the plasma appears electrically neutral — this is Debye shielding.',
    realWorld: 'Debye shielding determines how far probe voltages penetrate into fusion plasmas and ionospheric layers.',
    hint: 'It is the scale at which individual charge effects fade into collective neutrality.',
  },
  {
    id: 28103,
    topic: 'plasma-physics',
    difficulty: 'easy',
    question: 'The plasma frequency $\\omega_p = \\sqrt{n_e e^2 / m_e \\varepsilon_0}$ determines:',
    options: [
      'The natural oscillation frequency of electrons displaced from equilibrium',
      'The rotation frequency of ions in a magnetic field',
      'The frequency of electromagnetic radiation emitted',
      'The collision rate between electrons and ions',
    ],
    correctIndex: 0,
    explanation: 'Electrons displaced from ions oscillate at $\\omega_p$. Electromagnetic waves with $\\omega < \\omega_p$ cannot propagate through the plasma — they are reflected.',
    realWorld: 'This is why radio waves bounce off the ionosphere (enabling shortwave radio) but microwaves pass through.',
    hint: 'Below this frequency, the plasma is opaque. Above it, transparent.',
  },
];

export const plasmaPhysicsHardQuestions: Question[] = [
  {
    id: 28111,
    topic: 'plasma-physics',
    difficulty: 'hard',
    question: 'Alfvén waves are low-frequency oscillations in a magnetized plasma. Their phase velocity is:',
    options: [
      '$v_A = B / \\sqrt{\\mu_0 \\rho}$ where $\\rho$ is the mass density',
      '$v_A = c$ (speed of light)',
      '$v_A = \\omega_p / k$',
      '$v_A = \\sqrt{k_BT/m_i}$',
    ],
    correctIndex: 0,
    explanation: 'Alfvén waves propagate along magnetic field lines like waves on a string, with the field providing tension ($B^2/\\mu_0$) and plasma providing inertia ($\\rho$).',
    realWorld: 'Alfvén waves transport energy through the solar corona and are candidates for coronal heating to millions of degrees.',
    hint: 'The magnetic field acts as a "string" and the plasma mass provides the inertia.',
  },
  {
    id: 28112,
    topic: 'plasma-physics',
    difficulty: 'hard',
    question: 'The Lawson criterion for nuclear fusion ignition requires the triple product $nT\\tau_E$ to exceed approximately:',
    options: [
      '$3 \\times 10^{21}$ keV·s/m³ for D-T fusion',
      '$10^{10}$ keV·s/m³',
      '$10^{30}$ keV·s/m³',
      '$1$ keV·s/m³',
    ],
    correctIndex: 0,
    explanation: 'The Lawson criterion balances fusion power output against energy losses. For D-T fusion at ~15 keV, $n\\tau_E > 2 \\times 10^{20}$ s/m³, giving the triple product threshold.',
    realWorld: 'JET achieved $Q = 0.67$ in 1997. ITER aims for $Q = 10$. NIF achieved $Q > 1$ via inertial confinement in 2022.',
    hint: 'Density × Temperature × Confinement time must be high enough for fusion to be self-sustaining.',
  },
  {
    id: 28113,
    topic: 'plasma-physics',
    difficulty: 'hard',
    question: 'In a tokamak, particles follow helical paths along magnetic field lines. Trapped particles in the mirror-like outboard side execute "banana orbits." What determines if a particle is trapped?',
    options: [
      'The ratio of perpendicular to parallel velocity: $v_\\perp / v_\\parallel > \\sqrt{2\\varepsilon}$ where $\\varepsilon = r/R$',
      'Whether the particle is an ion or electron',
      'The particle\'s total energy exceeds $k_BT$',
      'The toroidal field strength at the midplane',
    ],
    correctIndex: 0,
    explanation: 'The toroidal geometry creates a magnetic mirror. Particles with large $v_\\perp/v_\\parallel$ are reflected by the stronger inboard field, tracing banana-shaped orbits in the poloidal plane.',
    realWorld: 'Banana orbits enhance neoclassical transport in tokamaks and affect bootstrap current — crucial for ITER performance predictions.',
    hint: 'Think of a magnetic mirror: particles with too much perpendicular velocity get reflected.',
  },
];

export const plasmaPhysicsSotaQuestions: Question[] = [
  {
    id: 28121,
    topic: 'plasma-physics',
    difficulty: 'sota',
    question: 'Magnetic reconnection converts magnetic energy into kinetic energy and heat. The Sweet-Parker model predicts a reconnection rate that scales as:',
    options: [
      '$v_{\\text{in}} / v_A \\sim S^{-1/2}$ where $S$ is the Lundquist number — too slow to explain solar flares',
      '$v_{\\text{in}} / v_A \\sim 1$ — instantaneous reconnection',
      '$v_{\\text{in}} / v_A \\sim S^{-1}$',
      '$v_{\\text{in}} / v_A \\sim \\ln S$',
    ],
    correctIndex: 0,
    explanation: 'Sweet-Parker gives $v_{\\text{in}}/v_A \\sim S^{-1/2}$. For solar corona ($S \\sim 10^{14}$), this is far too slow. Fast reconnection requires plasmoid instabilities or Hall MHD effects.',
    realWorld: 'NASA\'s MMS mission directly observed electron-scale reconnection in Earth\'s magnetosphere, confirming Hall physics.',
    hint: 'The Lundquist number $S$ is huge in astrophysical plasmas — making Sweet-Parker hopelessly slow.',
  },
  {
    id: 28122,
    topic: 'plasma-physics',
    difficulty: 'sota',
    question: 'Gyrokinetic theory reduces the 6D Vlasov equation to 5D by averaging over which fast motion?',
    options: [
      'The cyclotron gyration around magnetic field lines',
      'The parallel bounce motion',
      'The $\\mathbf{E} \\times \\mathbf{B}$ drift',
      'The plasma oscillation at $\\omega_p$',
    ],
    correctIndex: 0,
    explanation: 'Charged particles gyrate rapidly around field lines at the cyclotron frequency $\\omega_c$. Gyrokinetics averages over this fast motion, keeping the slower drift dynamics — reducing computation by orders of magnitude.',
    realWorld: 'Gyrokinetic codes (GS2, GENE, GYRO) are the primary tools for predicting turbulent transport in fusion reactors like ITER.',
    hint: 'The fastest periodic motion in a magnetized plasma is the Larmor gyration.',
  },
  {
    id: 28123,
    topic: 'plasma-physics',
    difficulty: 'sota',
    question: 'The Grad-Shafranov equation describes:',
    options: [
      'Axisymmetric magnetohydrostatic equilibria in toroidal geometry ($\\Delta^* \\psi = -\\mu_0 R^2 p\'(\\psi) - FF\'(\\psi)$)',
      'The dispersion relation for Alfvén waves',
      'The evolution of magnetic islands',
      'The kinetic equation for trapped particles',
    ],
    correctIndex: 0,
    explanation: 'The Grad-Shafranov equation is a nonlinear elliptic PDE for the poloidal flux $\\psi$. Its solutions define the magnetic equilibrium shapes of tokamaks and stellarators.',
    realWorld: 'Every tokamak in the world solves Grad-Shafranov to design the magnetic configuration before a single plasma discharge.',
    hint: 'It is THE equation for computing the shape of confined plasma in a toroidal device.',
  },
];
