import type { Question } from '../types';

export const cqfQuestions: Question[] = [
  {
    id: 84100,
    topic: 'cqf',
    difficulty: 'easy',
    question: 'The Black-Scholes equation for a European call option assumes:',
    options: [
      'Geometric Brownian motion for the stock price with constant volatility and risk-free rate',
      'Arithmetic Brownian motion with stochastic volatility',
      'Jump-diffusion dynamics with Poisson jumps',
      'Mean-reverting price dynamics',
    ],
    correctIndex: 0,
    explanation: '$dS = \\mu S \\, dt + \\sigma S \\, dW$. The PDE: $\\frac{\\partial V}{\\partial t} + \\frac{1}{2}\\sigma^2 S^2 \\frac{\\partial^2 V}{\\partial S^2} + rS\\frac{\\partial V}{\\partial S} - rV = 0$.',
    realWorld: 'Despite its limitations, Black-Scholes remains the benchmark pricing framework and quoting convention for options.',
    hint: 'It\'s the foundational continuous-time model with constant parameters.',
  },
  {
    id: 84101,
    topic: 'cqf',
    difficulty: 'easy',
    question: 'Itô\'s lemma is the chain rule for stochastic calculus and differs from the ordinary chain rule because:',
    options: [
      'It includes a second-order term $\\frac{1}{2}\\sigma^2 S^2 f_{SS} \\, dt$ due to $(dW)^2 = dt$',
      'It only applies to deterministic functions',
      'It eliminates all randomness from the model',
      'It requires no assumptions about the process',
    ],
    correctIndex: 0,
    explanation: 'For $f(S,t)$ where $dS = \\mu S\\,dt + \\sigma S\\,dW$: $df = (f_t + \\mu S f_S + \\frac{1}{2}\\sigma^2 S^2 f_{SS})dt + \\sigma S f_S \\, dW$.',
    realWorld: 'Itô\'s lemma is used to derive the Black-Scholes PDE and to transform between different representations of financial models.',
    hint: 'The key insight is that $(dW)^2 = dt$, not zero as in ordinary calculus.',
  },
  {
    id: 84102,
    topic: 'cqf',
    difficulty: 'hard',
    question: 'The Heston stochastic volatility model differs from Black-Scholes by allowing:',
    options: [
      'Volatility itself to follow a mean-reverting stochastic process correlated with the stock price',
      'Only deterministic time-varying volatility',
      'Constant volatility with jumps in stock price',
      'Volatility to be a function of strike price only',
    ],
    correctIndex: 0,
    explanation: 'Heston: $dv = \\kappa(\\theta - v)dt + \\xi\\sqrt{v}\\,dW_v$ with $\\text{Corr}(dW_S, dW_v) = \\rho$. The negative correlation generates the volatility skew.',
    realWorld: 'Equity derivatives desks use Heston (and its extensions) to price exotic options that depend on the volatility surface.',
    hint: 'Volatility is stochastic and correlated with the stock — producing skew.',
  },
  {
    id: 84103,
    topic: 'cqf',
    difficulty: 'hard',
    question: 'In finite difference methods for option pricing, the Crank-Nicolson scheme is preferred because it:',
    options: [
      'Is unconditionally stable and second-order accurate in both time and space',
      'Is the simplest to implement with only explicit steps',
      'Requires no boundary conditions',
      'Always converges in a single iteration',
    ],
    correctIndex: 0,
    explanation: 'Crank-Nicolson averages the explicit and implicit schemes, achieving $O(\\Delta t^2, \\Delta x^2)$ accuracy while maintaining unconditional stability.',
    realWorld: 'Quantitative analysts implement Crank-Nicolson PDE solvers for American options and path-dependent exotics.',
    hint: 'It blends explicit and implicit methods for the best of both worlds.',
  },
  {
    id: 84104,
    topic: 'cqf',
    difficulty: 'sota',
    question: 'The Longstaff-Schwartz algorithm for American option pricing via Monte Carlo uses:',
    options: [
      'Least-squares regression at each exercise date to estimate the continuation value from simulated paths',
      'A binomial tree with risk-neutral probabilities',
      'Closed-form solutions derived from Black-Scholes',
      'Only European option payoffs evaluated at maturity',
    ],
    correctIndex: 0,
    explanation: 'LSM regresses discounted future cash flows on basis functions of current state variables, estimating $E[\\text{continuation}|S_t]$ to decide early exercise.',
    realWorld: 'Energy and commodity traders use LSM to price American-style swing options and real options in project valuation.',
    hint: 'Regression on simulated paths approximates when it\'s optimal to exercise early.',
  },
];
