import type { Question } from '../types';

export const caiaQuestions: Question[] = [
  {
    id: 84200,
    topic: 'caia',
    difficulty: 'easy',
    question: 'Alternative investments typically include all of the following EXCEPT:',
    options: [
      'Publicly traded large-cap stocks',
      'Hedge funds',
      'Private equity',
      'Real assets (real estate, infrastructure, commodities)',
    ],
    correctIndex: 0,
    explanation: 'Traditional investments (public equity, fixed income) are excluded. Alternatives = hedge funds, PE, real estate, commodities, infrastructure, and structured products.',
    realWorld: 'Institutional investors (endowments, pensions) allocate 20-60% to alternatives for diversification and alpha.',
    hint: 'If it trades on a major stock exchange, it\'s generally "traditional."',
  },
  {
    id: 84201,
    topic: 'caia',
    difficulty: 'easy',
    question: 'The "J-curve" effect in private equity refers to:',
    options: [
      'Initial negative returns due to fees and capital deployment, followed by positive returns as investments mature',
      'A consistently upward-sloping return curve',
      'The shape of the yield curve',
      'The relationship between fund size and returns',
    ],
    correctIndex: 0,
    explanation: 'PE funds draw capital gradually, incur fees immediately, and realize gains later. Early IRRs are negative, creating a J-shaped return profile.',
    realWorld: 'LPs (limited partners) must understand the J-curve when planning liquidity needs and commitment pacing.',
    hint: 'Returns go down first (fees, unrealized investments) then up as exits occur.',
  },
  {
    id: 84202,
    topic: 'caia',
    difficulty: 'hard',
    question: 'A hedge fund\'s "2 and 20" fee structure means:',
    options: [
      '2% annual management fee on AUM plus 20% performance fee on profits above a hurdle rate',
      '2% of profits plus 20% of AUM',
      'A flat 22% annual fee',
      '2% entry fee and 20% exit fee',
    ],
    correctIndex: 0,
    explanation: 'The management fee covers operations; the incentive fee aligns manager interests with investors. High-water marks prevent charging on recovered losses.',
    realWorld: 'Fee compression has pushed many hedge funds to "1.5 and 15" or even lower, especially for institutional allocators.',
    hint: 'One fee is on assets, the other is on performance.',
  },
  {
    id: 84203,
    topic: 'caia',
    difficulty: 'hard',
    question: 'In a leveraged buyout (LBO), the primary source of returns comes from:',
    options: [
      'Debt paydown using the target company\'s cash flows, amplifying equity returns through financial leverage',
      'Issuing new equity to the public markets',
      'Reducing the company\'s revenue',
      'Government subsidies',
    ],
    correctIndex: 0,
    explanation: 'LBO returns are driven by: (1) debt paydown from cash flows, (2) EBITDA growth, (3) multiple expansion. Leverage amplifies equity returns (and risks).',
    realWorld: 'KKR\'s $31B buyout of RJR Nabisco in 1989 was the iconic LBO that defined the industry.',
    hint: 'The company\'s own cash flows pay down the acquisition debt, boosting equity value.',
  },
  {
    id: 84204,
    topic: 'caia',
    difficulty: 'sota',
    question: 'The "illiquidity premium" in alternative investments is best described as:',
    options: [
      'The excess return demanded by investors for holding assets that cannot be easily sold or traded',
      'A discount applied to all alternative investments',
      'The fee charged by fund managers for providing liquidity',
      'The spread between bid and ask prices',
    ],
    correctIndex: 0,
    explanation: 'Investors require higher expected returns to compensate for lockup periods, limited secondary markets, and valuation uncertainty in illiquid alternatives.',
    realWorld: 'The Yale Endowment model (David Swensen) explicitly harvests the illiquidity premium by investing in PE, VC, and real assets.',
    hint: 'Less liquid = you need to be paid more to accept that constraint.',
  },
];
